### ISSUE TITLE
Partial payments

### ISSUE THREAD

**Issue by 3dmerchant** [MicrosoftDocs/dynamics-365-unified-operations-public#1001]
If the initial authorization and final settlement are not the same, the merchant must submit a reversal within 24 hours. Verify the selected payment gateway can do this or pay steep penalties. For example, MasterCard has a .25% misuse of authorization penalty.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90ff0495-53f4-2439-5588-5bb51aea5374
* Version Independent ID: bf8dcca0-8992-ed4f-f42f-c4c1521890e4
* Content: [Credit card setup, authorization, and capture - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/accounts-receivable/credit-card-authorizations#feedback)
* Content Source: [articles/financials/accounts-receivable/credit-card-authorizations.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/accounts-receivable/credit-card-authorizations.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @ShivamPandey-msft
* Microsoft Alias: **shpandey**

**Comment by tonyafehr** [comment]
Bug 301736 has been logged to track this issue.

**Comment by panolte** [comment]
Thank you for reporting this issue.  While we understand the functionality doesn’t meet this specific business requirement the feature is working as it was designed to function. 

This fee is part of the credit card merchant processing and not part of the system functional process.
