### ISSUE TITLE
Documentation not complete

### ISSUE THREAD

**Issue by rat-af** [MicrosoftDocs/dynamics-365-unified-operations-public#1002]
Hi,
    This document is not complete.  This describes the process for exporting a DB from a Tier 2 environment.  However, if I wanted to export a database from a Tier 1 environment (say going from my DEV box to a 'Cloud hosted environment' for example), this document is not complete.  To export the data for Tier 1 environments, the 'Move Database' option under the 'Maintain' menu is not available.  You have to manually take a backup on the VM and restore it to get a copy of the DB, then manually create the bacpac if you intend on moving it to a Tier 2 environment.
This document needs to be more complete and include content that helps people understand how to export a DB for both UAT and DEV environments.  For those just coming on board to D365, they need a complete picture.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d6f499a-5dd9-2928-3f2e-ef35e206e474
* Version Independent ID: c1075ce8-398c-f7b9-9420-cbb0c92f0151
* Content: [Export a database - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-au/dynamics365/unified-operations/dev-itpro/database/export-database)
* Content Source: [articles/dev-itpro/database/export-database.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/database/export-database.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @laneswenka
* Microsoft Alias: **laneswenka**

**Comment by laneswenka** [comment]
Please review the tutorials section:
https://docs.microsoft.com/en-au/dynamics365/unified-operations/dev-itpro/database/dbmovement-operations


Lane

**Comment by rat-af** [comment]
Lane,
      Thanks for the update. However, your link still does not address the concern I raised about the document. In the link you gave me, there is no way to explain how to export a database for a Tier 1 environment. 

If I want to promote a database to a Tier 2 environment, or if I want to export a Tier 1 database for use in a cloud hosted environment, this document fails to inform on how this is done. 

Earlier version had all the information (a little clunky, but it was there). Now, there is no information on exporting or importing databases in reference to a Tier 1 environment. 

The document is great for Tier 2 (UAT) environments, but useless for Tier 1 environments. 

There are no LCS tools for moving databases for Tier 1 environments. So the process described in the document can’t be used for Tier 1 environments. This means there is a documentation gap that needs to be resolved. 

Regards,
Andrew Friebel

**Comment by laneswenka** [comment]
Please see the Tutorials section. It has the export from Tier1 and Import to Tier2. This is commonly referred to Golden Configuration Promotion.

The Debug tutorial has Export from Tier2 and Import to Tier1.

In general the Tutorials show you how to use components of DataALM in a real world flow.

Thanks,
Lane

**Comment by rat-af** [comment]
Lane,
      Thanks for the clarification.  I overlooked that part. For me, i didn’t think they were obvious links, but you are right, the information is there. Thanks again for clarification. 

Regards,
Andrew Friebel
