### ISSUE TITLE
How to avoid naming conflicts between table and form extensions class where the table/form share the same name

### ISSUE THREAD

**Issue by noakesey** [MicrosoftDocs/dynamics-365-unified-operations-public#1004]
It would be good to clarify the naming convention for extension classes where the underlying table and form share the same name.  For example if I create extension classes for the CustTable table and also the CustTable form I will need to add an additional infix somewhere to prevent a clash.  I am using CustTable_myinfix_Extension (for the table) and CustTableForm_myinfix_Extension for the form.  Is the standard approach taken by others for consistency?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4937eba-2f4a-16c0-1d97-68056be97bfa
* Version Independent ID: e6827e77-86e4-5de2-9237-c9a64ac335a2
* Content: [Naming guidelines for model extensions - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/extensibility/naming-guidelines-extensions#feedback)
* Content Source: [articles/dev-itpro/extensibility/naming-guidelines-extensions.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/extensibility/naming-guidelines-extensions.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @LarsBlaaberg
* Microsoft Alias: **pvillads**

**Comment by ShylaThompson** [comment]
@LarsBlaaberg please review and update the topic as necessary.

**Comment by pvillads** [comment]
This is a question for Lars more than me. From my perspective, as long as the name of the extension class contains a prefix that is unique per model or per ISV then I think we are good. How we disambiguate the case for forms or class extensions is not so important. I will let Lars comment.

**Comment by fraga** [comment]
@noakesey As a partner we have been using our unique name for all extensions. Suffix: XYZExtension. 
Ie.: CustTable.XYZExtension. I've seen ISVs not taking this into consideration.

**Comment by TrudAX** [comment]
Hi. I understand that from MS perspective disambiguate the case for forms or class extensions is not so important, but for the customer projects it creates a real mess when someone create a class for the form, and then a class with the same name for the table. Can we at least try to minimize this mess by updating the documentation. I created a pull request #1507 for this

**Comment by TrudAX** [comment]
Hi @noakesey. It seems MS approved my request(for forms) which is great. 
What naming convention do you use for  Form data sources, Form data fields, Form controls? I think it also will be good to add it to this document. 
I propose the following names:
[ExtensionOf(formdatasourcestr(CustTable, DataSource1))]
final class CustTableFormTST_DataSource1_Extension

[ExtensionOf(formdatafieldstr(CustTable, DataSource1, Field1))]
final class CustTableFormTST_DataSource1Field1_Extension

Button1	[ExtensionOf(formcontrolstr(CustTable, Button1))]
final class CustTableFormTST_Button1_Extension

Any comments on this?

**Comment by noakesey** [comment]
Hi @TrudAX, 

Great work!  Sorry for the delay in following up - I am putting some notes together and will share my thoughts and experiences shortly!!

**Comment by PetrusAlberts** [comment]
Hi
@TrudAX I would like to propose a slightly different convention. This is the convention I am currently using.

[ExtensionOf(tableStr(CustTable))]
final class CustTableTST_Extension
[ExtensionOf(formStr(CustTable))]
final class CustTableFormTST_Extension
[ExtensionOf(formdatasourcestr(CustTable, DataSource1))]
final class CustTableDataSource1TST_Extension
[ExtensionOf(formdatafieldstr(CustTable, DataSource1, Field1))]
final class CustTableFormDataSource1Field1TST_Extension
Button1 [ExtensionOf(formcontrolstr(CustTable, Button1))]
final class CustTableButton1TST_Extension

Although your suggestion would be better from a conformance point of view, I think this would be better from a readability and AOT searching efficiency point of view. A lot of underscores are straining in my opinion and developers are used to working with elements with a long train of words (for example ApplicationSuite class BudgetControlDimensionStructureSynchronizationProvider). And then about always pushing the model identifier to the end of the extension: I think it will be better for AOT querying and would be simpler in my opinion.
