### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Ievgenm** [MicrosoftDocs/dynamics-365-unified-operations-public#1006]
Should be "Azure Data Lake" instead of "Axure Data Lake".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a19d5e09-3e76-35e3-636a-e9c2ebb86b5a
* Version Independent ID: de7b6e2e-e778-d393-5035-bfbe4eddb49c
* Content: [Preview features in Dynamics 365 for Finance and Operations platform update 25 (April 2019) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/whats-new-platform-25#feedback)
* Content Source: [articles/fin-and-ops/get-started/whats-new-platform-25.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/whats-new-platform-25.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @tonyafehr
* Microsoft Alias: **tfehr**

**Comment by ShylaThompson** [comment]
@levgenm thanks for pointing this out. I've fixed this and the change should be live by end of day today.
