### ISSUE TITLE
When will PU24 be available in LCS Shared Assets Library?

### ISSUE THREAD

**Issue by steevegilbert** [MicrosoftDocs/dynamics-365-unified-operations-public#1008]
Or should I go somewhere else to get it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a8f30d9-db2d-d580-6c0d-37f9ac709701
* Version Independent ID: e042d248-5402-e627-bb2d-20579ab2b3e8
* Content: [What's new or changed in Finance and Operations platform update 24 (March 2019) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/whats-new-platform-update-24)
* Content Source: [articles/fin-and-ops/get-started/whats-new-platform-update-24.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/whats-new-platform-update-24.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @tonyafehr
* Microsoft Alias: **tfehr**

**Comment by ShylaThompson** [comment]
@sericks007 can you review this one?

**Comment by windfly2006** [comment]
same question here.

**Comment by ostola** [comment]
I join to the question...
Thanks ¡

**Comment by sericks007** [comment]
@meeramahabala, can you please answer this question.

**Comment by steevegilbert** [comment]
I see it's now available in the asset library
