### ISSUE TITLE
Links to Sign-up and Setup do not exist

### ISSUE THREAD

**Issue by Angelos102** [MicrosoftDocs/dynamics-365-unified-operations-public#1009]
In the Overview section there are three links, but two of these point to this page and sections which do not exist. Also the supported features only has a version placeholder and no other content. can you please update the links and provide an indication where these sections will be provided. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af578496-df16-bb9c-a626-f9298c94ece1
* Version Independent ID: 36a3e95f-1152-0722-f142-0a4041ff6a48
* Content: [Dynamics 365 Payment Connector for Adyen - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/dev-itpro/adyen-connector?tabs=8-1-3#Supported-features-functionality-and-payment-terminals)
* Content Source: [articles/retail/dev-itpro/adyen-connector.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/dev-itpro/adyen-connector.md)
* Service: **dynamics-365-retail**
* GitHub Login: @rassadi
* Microsoft Alias: **rassadi**

**Comment by Angelos102** [comment]
Located the instructions until 10.0.1, maybe the headings should be moved out of the sections as a minimum

**Comment by ShylaThompson** [comment]
@kfend can you review this?
