### ISSUE TITLE
Clarify about New API's

### ISSUE THREAD

**Issue by manishmoothedath** [MicrosoftDocs/dynamics-365-unified-operations-public#1014]
Could you please clarify what has changed ? "New APIs have been added to help data integration retrieve errors that occurred during the import execution runs in a data project. For more information, see Data management package REST API."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a8f30d9-db2d-d580-6c0d-37f9ac709701
* Version Independent ID: e042d248-5402-e627-bb2d-20579ab2b3e8
* Content: [What's new or changed in Finance and Operations platform update 24 (March 2019) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/whats-new-platform-update-24)
* Content Source: [articles/fin-and-ops/get-started/whats-new-platform-update-24.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/whats-new-platform-update-24.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @tonyafehr
* Microsoft Alias: **tfehr**

**Comment by tonyafehr** [comment]
@manishmoothedath, thanks for the feedback.

@Sunil-Garg , please review this feedback and provide updates, if needed.

**Comment by tonyafehr** [comment]
Bug 301735  has been logged to track this issue.

**Comment by kfend** [comment]
@manishmoothedath,   
The new APIs are: 
- GetImportTargetErrorKeysFileUrl 
- GenerateImportTargetErrorKeysFile 
- GetImportStagingErrorFileUrl
I have updated the topic to list these out. The updated version will be available shortly.
