### ISSUE TITLE
synchronize-work-orders

### ISSUE THREAD

**Issue by moko33** [MicrosoftDocs/dynamics-365-unified-operations-public#1016]
These scentences must be wrong and should be corrected:

> The used Field Service Products (Finance and Operations to Field Service) template is based on the Products (Finance and Operations to Sales) – Direct template from Prospect to Cash. For more information, see Products (Finance and Operations to Sales) – Direct.
> 
> This topic only describes the differences between the Field Service Products (Finance and Operations to Field Service) and Field Service Products (Finance and Operations to Field Service) templates.

Also the title of the hyperlink on the left side leading to this article is wrong and doesn't correspond to the headline of the article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60b89419-36ad-d7ec-2525-a82fc4da598e
* Version Independent ID: 01fa1590-3010-6154-34e7-9ea3859ed555
* Content: [Synchronize work orders with project from Field Service to Finance and Operations - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/sales-marketing/synchronize-work-orders)
* Content Source: [articles/supply-chain/sales-marketing/synchronize-work-orders.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/sales-marketing/synchronize-work-orders.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @ChristianRytt
* Microsoft Alias: **crytt**

**Comment by ChristianRytt** [comment]
Created PR #1017 for this topic to fix the issue listed below.

Didn’t find any issues with mentioned hyperlink:
[A screenshot of a cell phone  Description automatically generated]

Thanks,
/Christian

**Comment by moko33** [comment]
The hyperlink is named:
"Synchronize work orders from Finance and Operations to Field Service"
however it should be named 
"Synchronize work orders with project from Field Service to Finance and Operations"

**Comment by ChristianRytt** [comment]
Got it - it's another page you are talking about for the link issue. 
It's not "Synchronize products with inventory unit from Finance and Operations to Field Service" but "Synchronize work orders with project from Field Service to Finance and Operations".
I see the issue, will ask for this to be updated.

**Comment by tonyafehr** [comment]
@moko33, thanks for the feedback. An updated version of this topic will be published later today.
