### ISSUE TITLE
Add the steps to resolve error "Record for ID - {GUID} not found"

### ISSUE THREAD

**Issue by manjarikm** [MicrosoftDocs/dynamics-365-unified-operations-public#1018]
Would be great to add the steps to resolve the common error described on this link - Record for ID - {GUID} not found (where the solution is to delete the template and reload the system templates) - https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/dm-error-descriptions#data-package-download---error-downloading-data-package-for-job--record-for-id---guid-not-found

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85ebf5ac-935b-265f-83a9-20463d015b46
* Version Independent ID: 3306c853-840a-1e49-8627-7ac4ae943961
* Content: [Upgrade data in development, demo, or sandbox environments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/upgrade-data-to-latest-update#feedback)
* Content Source: [articles/dev-itpro/migration-upgrade/upgrade-data-to-latest-update.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/migration-upgrade/upgrade-data-to-latest-update.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @tariqbell
* Microsoft Alias: **tabell**

**Comment by tonyafehr** [comment]
@manjarikm, thanks for the feedback. 

@laneswenka, please review this feedback and provide updates, if needed.

**Comment by tonyafehr** [comment]
Bug 301737 has been logged to track this issue.

**Comment by laneswenka** [comment]
@tonyafehr this will be resolved on another article as this is not specific to data upgrade.  Instead it is related to database refresh where the system templates may need refreshing.

**Comment by sloppypointless** [comment]
How is this marked completed?  I do not see a resolution on the page, and it still happens to today almost 4 years later.
