### ISSUE TITLE
Update to Visual Studio 2019

### ISSUE THREAD

**Issue by SysC0mp** [MicrosoftDocs/dynamics-365-unified-operations-public#1020]
Hi, 

is an update to Visual Studio 2019 planned for the AX developer tools?

Best regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 549e9730-4488-4aa0-1bd9-483e12568b85
* Version Independent ID: 2d017075-0988-0101-b3ff-8c21255905eb
* Content: [Development tools in Visual Studio - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-tools/development-tools-overview)
* Content Source: [articles/dev-itpro/dev-tools/development-tools-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-tools/development-tools-overview.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @robadawy
* Microsoft Alias: **robadawy**

**Comment by tonyafehr** [comment]
@SysC0mp, thanks for contacting us. Unfortunately, we're unable to handle your request here. You can go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your question from the Dynamics community.
