### ISSUE TITLE
Import to development environments

### ISSUE THREAD

**Issue by darrancroft** [MicrosoftDocs/dynamics-365-unified-operations-public#1021]
The content on how to copy a database from an Azure SQL environment (e.g. UAT) to SQL Server environment (e.g. development box) seems to have been removed. Could we please have this documentation reinstated (or updated if the process has changed)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 142d4b7f-e485-b424-39a0-c059b81481a8
* Version Independent ID: 5a4c7cd0-f446-0c79-cc1a-2b69ba46b579
* Content: [Import a database - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/import-database#feedback)
* Content Source: [articles/dev-itpro/database/import-database.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/database/import-database.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @laneswenka
* Microsoft Alias: **laneswenka**

**Comment by laneswenka** [comment]
@darrancroft  this is available on the home page -> tutorials section.  Please see the related options for export and debugging:
https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/dbmovement-scenario-debugdiag
https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/dbmovement-scenario-exportuat

**Comment by darrancroft** [comment]
Thanks Lane,

I see the link on the overview page (https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/dbmovement-operations) under tutorials (now that I look 😊) but it doesn’t include the link on the left hand menu so it just takes a bit of looking to find it.

Thanks for pointing me in the right direction.

Regards

Darran Croft

A Suite 2, Level 14, 141 Queen Street, Brisbane, QLD 4000
T +61 7 3018 2425<tel:+61%207%203018%202425>
W www.pa.com.au<http://www.pa.com.au> |

[cid:image001.png@01D4D981.7F49F970]<https://www.linkedin.com/company/15711?trk=tyah> [cid:image002.jpg@01D4D981.7F49F970] <https://twitter.com/ProfessionalAdv>  [cid:image004.jpg@01D4D981.7F49F970] <http://blog.pa.com.au/>

  |

[cid:image006.png@01D4D981.7F49F970]

1300 658 608

[cid:image007.gif@01D4D981.7F49F970]<http://www.pa.com.au/>
