### ISSUE TITLE
Why PU22 is expired?

### ISSUE THREAD

**Issue by DKobayashi-ykgw** [MicrosoftDocs/dynamics-365-unified-operations-public#1022]
Why PU22 is expired on Mar 13th 2019? PU24 is still not GA so currently alive PU is only 23.
Application update can skip 2 times so permitted version is three, latest, latest - 1, latest - 2. Therefore PU23, PU22, PU21 should alive.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcdefbcf-c3ad-9b1f-0988-452cea3e2108
* Version Independent ID: 7e002437-1ad9-ca29-7844-87e6709fe0fe
* Content: [Software lifecycle policy and cloud releases - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/versions-update-policy)
* Content Source: [articles/dev-itpro/migration-upgrade/versions-update-policy.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/migration-upgrade/versions-update-policy.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RyanCCarlson2
* Microsoft Alias: **rcarlson**

**Comment by sericks007** [comment]
@DKobayashi-ykgw, thanks for posting this!

@josaw1 or @meeramahabala, can you please review this, and update the topic if needed.

**Comment by sericks007** [comment]
Bug 302057 has been logged for this issue.

**Comment by DKobayashi-ykgw** [comment]
PU25 was released in last week, so PU22 was exactly expired. I can close this issue but I want to confirm supported PU versions are three or not.
Regards,
Daisuke

**Comment by josaw1** [comment]
@meeramahabalam can you please confirm? Thank you.
