### ISSUE TITLE
The C# Sample in "Comparison: Automated Retry After an Exception"

### ISSUE THREAD

**Issue by pndyjack** [MicrosoftDocs/dynamics-365-unified-operations-public#1029]
The C# Sample in "Comparison: Automated Retry After an Exception" doesn't appear to be properly formatted. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d90f60ed-891b-151d-c963-522a1b0b1c17
* Version Independent ID: f9ab9cef-beda-06fb-c5c0-dce07969fbd5
* Content: [X++ and C# comparison - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-ref/xpp-cs-comparison#comparison-automated-retry-after-an-exception)
* Content Source: [articles/dev-itpro/dev-ref/xpp-cs-comparison.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-ref/xpp-cs-comparison.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RobinARH
* Microsoft Alias: **robinr**

**Comment by kfend** [comment]
Thanks for this feedback! I have updated the formatting and the changes will be published soon.
