### ISSUE TITLE
Microsoft.Dynamics.DataEntities.ExportToPackage definitionGroupId

### ISSUE THREAD

**Issue by cameron-interactive** [MicrosoftDocs/dynamics-365-unified-operations-public#1030]
It should be noted here the "definitionGroupId" is NOT the DefinitionGroupId field from the data project, the NAME of the data project needs to be used here. This API does not return an error when submitting a job with the incorrect name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85d06c76-517e-c0f9-f089-be75a47c1605
* Version Independent ID: 18059b14-4123-298f-51b0-c870f13a9bdc
* Content: [Data management package REST API - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/data-management-api?toc=%2Ffin-and-ops%2Ftoc.json#feedback)
* Content Source: [articles/dev-itpro/data-entities/data-management-api.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/data-management-api.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by ShylaThompson** [comment]
@Sunil-Garg bug @ 303300 is logged for investigation.

**Comment by Sunil-Garg** [comment]
Thanks, the doc had been updated. Pls give a day for the changes to reflect.
