### ISSUE TITLE
Encountering an error when applying merged package in UAT

### ISSUE THREAD

**Issue by aledoy** [MicrosoftDocs/dynamics-365-unified-operations-public#1031]
Need to add note to do the merge within the project that is to be updated to 8.1 to avoid the error. I merged the package and binary using the 8.1 project, saved to shared asset then imported to the target project. This gave me the following error when trying to apply the merged package:

An error occurred while trying to process the child package information for merged package.

I did a new merge on the target project and the update went through.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b3b5ec6-1a21-e71a-df38-ba497f7f1116
* Version Independent ID: d1e49823-7934-6a3a-50e1-547cdd632077
* Content: [Update environments from version 8.0 to 8.1.X - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/appupdate-80-81#feedback)
* Content Source: [articles/dev-itpro/migration-upgrade/appupdate-80-81.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/migration-upgrade/appupdate-80-81.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by laneswenka** [comment]
This is good feedback, and a scenario we hadn't thought of before.  I will add a note of caution regarding this.
