### ISSUE TITLE
Failed update

### ISSUE THREAD

**Issue by aledoy** [MicrosoftDocs/dynamics-365-unified-operations-public#1032]
You might get a failed update error at a step that runs 

'GlobalUpdate script for service model: AOSService on machine'. 

Just resume, don't mind the error log that points to 'The specified module 'C:\Program Files\Microsoft Security Client\MpProvider' was not loaded because no valid module file was found in any module directory.'. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b3b5ec6-1a21-e71a-df38-ba497f7f1116
* Version Independent ID: d1e49823-7934-6a3a-50e1-547cdd632077
* Content: [Update environments from version 8.0 to 8.1.X - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/appupdate-80-81)
* Content Source: [articles/dev-itpro/migration-upgrade/appupdate-80-81.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/migration-upgrade/appupdate-80-81.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by aledoy** [comment]
Actually, in general regardless if the update was successful or not, the logs will always show an error for the antivirus folder and the message will be "C:\Program Files\Microsoft Security Client\MpProvider' was not loaded because no valid module file was found in any module directory.". This can be ignored.

**Comment by ShylaThompson** [comment]
@laneswenka bug # 303303 is logged for investigation.

**Comment by Rupeshsri** [comment]
Same error for me also.
