### ISSUE TITLE
Who will perform a delayed upgrade?

### ISSUE THREAD

**Issue by codingeugene** [MicrosoftDocs/dynamics-365-unified-operations-public#1033]
If the customer delays an UAT upgrade (Tier-2), which would be done by Microsoft, will it be Microsoft who will perform this delayed upgrade based on the maintenance window? Or should the customer take over?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14372486-6284-da4b-6bbb-30acd36dd7de
* Version Independent ID: f8301c48-61db-e9e5-aba5-413528cd91d2
* Content: [One Version service updates FAQ - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/one-version#feedback)
* Content Source: [articles/fin-and-ops/get-started/one-version.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/one-version.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @meeramahabala
* Microsoft Alias: **meeram**

**Comment by meeramahabala** [comment]
The new configuration experience (https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/configure-service-updates) can help you configure a new maintenance window or pause a service update. The article has added details.
