### ISSUE TITLE
No Documentation on Adobe Acrobat Reader Settings?

### ISSUE THREAD

**Issue by Krytical13** [MicrosoftDocs/dynamics-365-unified-operations-public#1038]
Adobe Acrobat Reader is required to be installed, however there is no documentation on the settings required in the Adobe Acrobat reader application.

While printing checks we have noticed that the Adobe Acrobat reader settings directly affect the printed checks.
Scaling has been an issue, and we found that the Adobe settings are per-user, so you have to login as the DRA user, change the settings, and then print a document to save those settings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2128b07d-7349-6642-f05f-c94fe800d104
* Version Independent ID: 0568d0d1-8035-3423-f791-7bd82a5d070f
* Content: [Install the Document Routing Agent to enable network printing - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/install-document-routing-agent#feedback)
* Content Source: [articles/dev-itpro/analytics/install-document-routing-agent.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/install-document-routing-agent.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by ShylaThompson** [comment]
@TJVass please review this issue and update the topic as necessary.

**Comment by ShylaThompson** [comment]
@TJVass Bug #303304 is logged for investigation

**Comment by imbisc** [comment]
Adobe Acrobat reader settings automatically sets to Shrink oversized pages, and moves the MICR line up and changes the entire format of the report.  Will test and validate if logging in as the user resolves the issue, but I had a case open with MS support for 3 months, and this is the first response that I found stating a workaround.  If you can add to documentation, that would be great.

**Comment by sericks007** [comment]
This topic was updated in [PR 6258](https://github.com/MicrosoftDocs/Dynamics-365-Operations/pull/6258) and will be published later today.

**Comment by Pattern-Brandon** [comment]
Somehow our check printing recently broke, and I wanted to come back here to check if there was any updated documentation.
The URL above that says "PR 6258" is a dead link.

Can anyone provide any more info on this?
