### ISSUE TITLE
AADSTS50011: The reply url specified in the request does not match the reply urls 

### ISSUE THREAD

**Issue by iwiaCorp** [MicrosoftDocs/dynamics-365-unified-operations-public#1039]
In step To validate the PowerBI.com configuration, if someone have the issues AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application: ...

Verify the Base URL and Reply URL starts with Https://.... and not with Http://

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 717d397d-4186-c7de-431d-3260d3f0484a
* Version Independent ID: bdd7545b-5970-93e0-5cbb-a59da4ace01b
* Content: [Configure Power BI integration for workspaces - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/configure-power-bi-integration)
* Content Source: [articles/dev-itpro/analytics/configure-power-bi-integration.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/configure-power-bi-integration.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by ShylaThompson** [comment]
@MilindaV2 Can you review the suggested change to the help documentation above and update the topic if necessary.

**Comment by ShylaThompson** [comment]
@MilindaV2 bug # 303307 is logged for investigating this issue.

**Comment by dominicdelaire** [comment]
I have the same problem and my Base and reply URL start with https. Do you have a solution ?

**Comment by manojbatchu** [comment]
Do we have any update on this ?

**Comment by patrickEssa** [comment]
I had this error, and actually the fix was to add 'oauth' at the end of the Dynamics 365 url. 
Initially registered it with the url like: https://xxxxx.operations.dynamics.com/
Fixed by changing the Redirect URL to: https://xxxxx.operations.dynamics.com/oauth

**Comment by MilindaV2** [comment]
You do need to add the URL with the oauth suffix as below
https://xxxxx.operations.dynamics.com/oauth
