### ISSUE TITLE
Passing parameter from D365FO to PowerApps - clarification

### ISSUE THREAD

**Issue by manishmoothedath** [MicrosoftDocs/dynamics-365-unified-operations-public#1040]
could you please explain little more about this - "If(!IsBlank(Param("EntityId")), Set(FinOpsInput, Param("EntityId")), Set(FinOpsInput, ""));"
What is "EntityId" here, Is it the name of the parameter in D365FO ? or the name of the data entity ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2ba2071-d17c-cb98-a965-52258c0ddc9c
* Version Independent ID: d4a1e83c-549b-08f9-1f92-370c58bb30f3
* Content: [Embed PowerApps apps - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/embed-power-apps)
* Content Source: [articles/fin-and-ops/get-started/embed-power-apps.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/embed-power-apps.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by ShylaThompson** [comment]
@jasongre can you review this issue and update the topic if necessary?

**Comment by ShylaThompson** [comment]
@jasongre bug #303310 is logged for investigation

**Comment by jasongre** [comment]
"EntityID" is the URL parameter that is used to pass the data context from D365FO to the PowerApp.  It specifically corresponds to the "Input data for the PowerApp" selected when configuring the PowerApp inside D365FO (and does not refer to any data entity).

**Comment by manishmoothedath** [comment]
> "EntityID" is the URL parameter that is used to pass the data context from D365FO to the PowerApp. It specifically corresponds to the "Input data for the PowerApp" selected when configuring the PowerApp inside D365FO (and does not refer to any data entity).

Thanks, Jason, I understand that. To clarify my question -
It is mentioned in the Docs site to use this formula in the OnStart function of the PowerApp.
 If(!IsBlank(Param("EntityId")), Set(FinOpsInput, Param("EntityId")), Set(FinOpsInput, ""));
But just isn't making any difference or filtering the parameter when embedded into D365FO. I wonder the "EntityId" should be replaces with the name of the Parameter from D365FO?
It will be good, If this document can be updated with what needs to be done in the PowerApp to get this working.

**Comment by PrebenAmilcare** [comment]
Have you gotten any reply to your latest question? I can't get this to work either. I can't find any good solution to automatically set legal entity when opening the app.

**Comment by jasongre** [comment]
@manishmoothedath Today we only support sending one piece of context from Finance and Operations app to Power Apps. That data, regardless of what field you selected for context, comes into Power Apps via the "EntityID" URL parameter. Once we move to supporting more fields of context, we will consider allowing the parameters that are passed to be named to better reflect the data that's being passed.  

@PrebenAmilcare The current legal entity does not currently get passed as context from Finance and Operations apps. That is a future consideration. Also, if you are using the Finance and Operators data connector in Power Apps, it does not currently support specifying the legal entity; instead, it retrieves data based on the default legal entity for the current user.
