### ISSUE TITLE
Retail self-service installer issue

### ISSUE THREAD

**Issue by Junaidahm3d** [MicrosoftDocs/dynamics-365-unified-operations-public#1041]
@jashanno, I have copied all self-service installers into the folder C:/selfservicepackages defined and created in step 2 in each of the AOS machines, but when I click on Retail Store Scale Unit package drop down it shows nothing.  please help.

![image](https://user-images.githubusercontent.com/47216961/54514424-edbe7d80-497b-11e9-8ffe-da621001ab11.png)

Regards,
Junaid Ahmed

--

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecc51933-08be-36c7-8f82-d9df6f220bfa
* Version Independent ID: 29846b09-d0e5-9076-d451-0f86429a778a
* Content: [Installation steps for Retail channel components in an on-premises environment - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/deployment/deploy-retail-onprem)
* Content Source: [articles/dev-itpro/deployment/deploy-retail-onprem.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/deployment/deploy-retail-onprem.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @jashanno
* Microsoft Alias: **jashanno**

**Comment by ShylaThompson** [comment]
@jashanno can you review the issue with this topic and update the procedure with helpful information if possible?

**Comment by Junaidahm3d** [comment]
@jashanno please update, I am stuck at step 2.

**Comment by Junaidahm3d** [comment]
@ShylaThompson,

I have resolved the issue by myself. the document is not up to date with latest information.
