### ISSUE TITLE
Document attachments

### ISSUE THREAD

**Issue by miursu** [MicrosoftDocs/dynamics-365-unified-operations-public#1043]
While working with a customer for importing invoices with attachments, we faced several issues and the document needs to be updated:
1) When creating the package to import invoices line, header and attachment we used 7.zip to create the zip file. If using WinRAR we received error message when importing the package. The error message said: The file extension is not mapped to a data source. Specify if there is a recommended program to create the package for import
2) The  excel file Vendor invoice document attachment contains field called DocumentID. Nowhere in the document it says that this DocumentID should be a value mandatory and coming from where.
During tests I found out that the attachment must exist in the Resources\Vendor invoice document attachment folder along with a file which represents the content file, content stored as a file, rather than as a structured content object. This is usually meant to refer to images, PDFs, and other files which are uploaded. I created this content file by right click on the attachment, open in a text editor, save file to the folder Vendor invoice document attachment as it is, type All files, no extension. Then use the file name here to populate in the Vendor invoice document attachment excel file, FileContentsFileName.
Also DocumentID to be populated to the excel file Vendor invoice document attachment can be found in the content file:
![image](https://user-images.githubusercontent.com/48678760/54527493-ce771e80-4982-11e9-8153-4e280e3b3a91.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1c7d1d8-45ae-5caa-cbcd-9622cb789f1b
* Version Independent ID: 6b1f4b43-be42-6817-b5e4-3707f5938a02
* Content: [Vendor invoice automation - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/accounts-payable/vendor-invoice-automation#feedback)
* Content Source: [articles/financials/accounts-payable/vendor-invoice-automation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/accounts-payable/vendor-invoice-automation.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @ShivamPandey-msft
* Microsoft Alias: **shpandey**

**Comment by ShylaThompson** [comment]
@ShivamPandeyMSFT please review this issue and update the topic as necessary.

**Comment by ShylaThompson** [comment]
@abruer please review and update the topic as necessary.

**Comment by dynsm** [comment]
Does this functionality allow for PO line matching?  If so how is this done or is there a detailed specification that describes the functionality and process?

**Comment by abruer** [comment]
The document attachment itself is not a part of the invoice matching validation process. To learn more about the invoice matching validation that is available in the product, please refer to the topics contained in the "Accounts payable invoice matching" documentation.

**Comment by vishalaw** [comment]
What's the equivalent REST API to do post invoices with attachment or attachment links?

**Comment by CamillaBro** [comment]
I am working on a project where we have set up Vendor Invoice Automation and where many of the users are team member users.

We have had issues with the team users not being able to approve invoices lines, but also we are facing the issue that team members is not able to view the side by side invoice image.  That kind of makes the use obsolete from the approver's point of view.

**Comment by josaw1** [comment]
BUG 437617 created and reprioritized.

**Comment by josaw1** [comment]
@abruer is updating the topic and it will be republished soon. Thanks.
