### ISSUE TITLE
Data Import/Export Framework doesn't exist in Dynamics 365 F&O

### ISSUE THREAD

**Issue by amadse** [MicrosoftDocs/dynamics-365-unified-operations-public#1046]
Health monitoring – In addition to availability checks, some basic health checks must be performed. These health checks span various components, such as Application Object Server, Batch Framework, Data Import/Export Framework 
In 365 the name is Data management Framework which is specified in another article. Please correct this

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c73b0eff-ab53-afb9-b3e2-40f94cb71a3e
* Version Independent ID: 069fa33b-6a69-2d29-908d-fca5ca0dc516
* Content: [Monitoring and diagnostics tools in Lifecycle Services (LCS) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/monitoring-diagnostics)
* Content Source: [articles/dev-itpro/lifecycle-services/monitoring-diagnostics.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/lifecycle-services/monitoring-diagnostics.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @manalidongre
* Microsoft Alias: **manado**

**Comment by tonyafehr** [comment]
@amadse, thanks for the feedback. 

@manalidongre, can you review the suggested change and update this topic if necessary.

**Comment by ShylaThompson** [comment]
@manalidongre bug #303315 is logged for investigation

**Comment by sericks007** [comment]
This topic has been updated.
