### ISSUE TITLE
Data not populating after setting entity store

### ISSUE THREAD

**Issue by clundy-columbia** [MicrosoftDocs/dynamics-365-unified-operations-public#1051]
Hello,
We setup the entity store full push from D365 through enablement of flighting. We tested the data lake store connection and the key vault connection but have not seen data yet. Is there a process that I can kick off to make this work? Also we assume that since there is no container selection process that the process creates the folders it needs. Any documentation on this process?

https://docs.microsoft.com/en-us/business-applications-release-notes/april19/dynamics365-finance-operations/erp-data-entity-store-byod-business-data-lake

https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/automated-entity-store-refresh

**Comment by tonyafehr** [comment]
@clundy-columbia, thanks for the feedback. To get product help you can contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community. 

@MilindaV2, can you review the suggested change and update these topics if necessary.

**Comment by ShylaThompson** [comment]
@MilindaV2 bug #303316 is logged for investigation

**Comment by jharbering** [comment]
Hi everyone, same issue here. Connected the D365 correctly with the datalake gen2. Received successful connection messages in D365. Still, no data is getting populated. Environment is Microsoft Dynamics 365 for Finance and Operations (10), Installed platform version : Update26 (7.0.5257.16584), Serial number: 3fd52bb5-748d-4840-a166-f16832faf12a. Any ideas?

**Comment by tonyafehr** [comment]
This is not a Support site. You can contact Support by going to [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
