### ISSUE TITLE
<ConfigurationOnly> mentioned twice under Data project defenition

### ISSUE THREAD

**Issue by manishmoothedath** [MicrosoftDocs/dynamics-365-unified-operations-public#1052]
Hi,
&lt;ConfigurationOnly&gt; tag is mentioned twice under the Data project definition. Please fix

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a1cb5a1-742b-580e-0866-8ad52eaec61e
* Version Independent ID: cf55462f-c2d2-81d8-c50d-66490331fb65
* Content: [Data task automation - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/data-task-automation)
* Content Source: [articles/dev-itpro/data-entities/data-task-automation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/data-task-automation.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by tonyafehr** [comment]
@manishmoothedath, thanks for posting this feedback. 

@Sunil-Garg,can you review the suggested change and update this topic if necessary.

**Comment by tonyafehr** [comment]
Bug 301735 has been logged to track this issue.
