### ISSUE TITLE
Maximum number of updates you can pause is unclear.

### ISSUE THREAD

**Issue by glenturnbullazure** [MicrosoftDocs/dynamics-365-unified-operations-public#1054]
The document states: "You can pause a maximum of two continuous updates at a time. " However I think it would be reasonable for a customer to expect that they can pause both the sandbox and production environments for 3 months, which would be a maximum of four updates paused in total (two environments on two occasions). In LCS it only allows a maximum of two boxes to be ticked across sandbox and production when making the selection under 'edit settings', i.e. either production on 2 occasions (but not sandbox), or sandbox and production on one occasion each (so not 3 months). Is that the intended design, or is it an LCS bug? I think it needs to be clarified here, if it is intended design. Please advise either way, thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c296e1c-432e-8fb3-e9d8-a87c26d9b59d
* Version Independent ID: b4b2af10-17e2-1878-c8c2-2319471bbc79
* Content: [Pause service updates through Lifecycle Services (LCS) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/pause-service-updates)
* Content Source: [articles/dev-itpro/lifecycle-services/pause-service-updates.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/lifecycle-services/pause-service-updates.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @manalidongre
* Microsoft Alias: **manado**

**Comment by tonyafehr** [comment]
@glenturnbullazure, thanks for the feedback.  

@manalidongre, can you review the suggested change and update this topic if necessary.

**Comment by tonyafehr** [comment]
Bug 303664 has been logged to track this issue.

**Comment by satyakejriwal** [comment]
I am not able to see the pause tab in LCS project setting. Our sandbox is already on 10.0 and PROD is on 8.0 and we are in the process of update. 
I want to pause update on Sandbox to 10.0.1

**Comment by manalidongre** [comment]
It depends on what version you are on that controls how many updates you are allowed to pause. If you are unable to pause 4 instances in the update calendar (for 2 updates total) then you might not be on the latest version. If you are on the latest version and still seeing this, please log a bug. In addition, the new policy now allows for 3 updates in total (6 instances in the calendar).
