### ISSUE TITLE
Tenant 

### ISSUE THREAD

**Issue by SGick** [MicrosoftDocs/dynamics-365-unified-operations-public#1055]
You should mention that the user who executes the Task Automation has to be in the same tenant as the D365 Environment and LCS Project. We are a partner and tried to do this task automation in the customer tenant with our partner logins. 
The Task Automation failed every time, even if we had Admin Role in D365 F&O and Admin Role in LCS project. And even when the OAuth LCS Authorization was successful. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a1cb5a1-742b-580e-0866-8ad52eaec61e
* Version Independent ID: cf55462f-c2d2-81d8-c50d-66490331fb65
* Content: [Data task automation - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/data-task-automation#feedback)
* Content Source: [articles/dev-itpro/data-entities/data-task-automation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/data-task-automation.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by tonyafehr** [comment]
@SGick, thanks for posting this feedback. 

@Sunil-Garg,can you review the suggested change and update this topic if necessary.

**Comment by tonyafehr** [comment]
Bug 303661 has been logged to track this issue.

**Comment by tonyafehr** [comment]
The documentation will be updated to reflect this, thanks again for posting this feedback.
