### ISSUE TITLE
Data export does not work in the repro environment

### ISSUE THREAD

**Issue by illese** [MicrosoftDocs/dynamics-365-unified-operations-public#1057]
Unfortunately the above described process only partially works at least for 8.1 PU 23. If you try to execute a data package in the repro environment you will get an error. So the instructions for the import export manually should not have been removed from the documentation 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbfc55db-29cd-7e02-772a-4e590ff1fa78
* Version Independent ID: e4594af2-7087-6795-43f8-86cb3349534f
* Content: [Debug a copy of the production database - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/dbmovement-scenario-debugdiag#feedback)
* Content Source: [articles/dev-itpro/database/dbmovement-scenario-debugdiag.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/database/dbmovement-scenario-debugdiag.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @laneswenka
* Microsoft Alias: **laneswenka**

**Comment by tonyafehr** [comment]
@illesthanks, for the feedback.

@laneswenka, can you review the suggested change and update this topic if necessary.

**Comment by illese** [comment]
Cannot repro the issue any more, maybe a code inconsystency.
