### ISSUE TITLE
It is a duplicate and info is missing

### ISSUE THREAD

**Issue by TomekMelissa** [MicrosoftDocs/dynamics-365-unified-operations-public#1058]
It is almost a duplicate of another page.
https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/dbmovement-scenario-debugdiag
This page is missing information how to add firewall rules, which makes it impossible to follow. At the time of writing the only option was support ticket I suppose.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 146fecc8-6786-266e-2a47-d8c96883e837
* Version Independent ID: a7592d6b-7bd8-1d41-95b5-5b4ebae1b59d
* Content: [Debug X++ against copies of production databases - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-tools/debug-x-issue-against-copy-of-production#feedback)
* Content Source: [articles/dev-itpro/dev-tools/debug-x-issue-against-copy-of-production.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-tools/debug-x-issue-against-copy-of-production.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @tariqbell
* Microsoft Alias: **tabell**

**Comment by tonyafehr** [comment]
@TomekMelissa, thanks for the feedback. If I understand correctly, https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/dbmovement-scenario-debugdiag is missing information that you found in https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/dbmovement-scenario-debugdiag.

@laneswenka, please review the suggested change and update this topic as needed.

**Comment by tonyafehr** [comment]
Bug 303676 has been logged to track this issue.

**Comment by laneswenka** [comment]
@tonyafehr I don't own the article this feedback was given about:
https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-tools/debug-x-issue-against-copy-of-production#feedback

It should however be deprecated as this area is owned by me and the best article to use is:
https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/dbmovement-scenario-debugdiag

**Comment by laneswenka** [comment]
@sericks007 the above article should be deprecated

**Comment by sericks007** [comment]
The [Debug X++ against copies of production databases](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-tools/debug-x-issue-against-copy-of-production) topic will be deprecated.  Links to that topic will be redirected to the [Debug a copy of the production database](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/dbmovement-scenario-debugdiag) topic.
