### ISSUE TITLE
Article Needs Update Reflecting New OneVersion Policy

### ISSUE THREAD

**Issue by tomhig** [MicrosoftDocs/dynamics-365-unified-operations-public#1060]
There are no longer 2 update types once OneVersion Policy in place. Update Policy language also needs to be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4cf63cc-75ac-0caf-56ca-40dee3c77cca
* Version Independent ID: c99f8d16-c635-8879-860a-0d0ad4a24a0d
* Content: [Cloud operations and servicing - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/cloud-operations-servicing#feedback)
* Content Source: [articles/dev-itpro/lifecycle-services/cloud-operations-servicing.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/lifecycle-services/cloud-operations-servicing.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @manalidongre
* Microsoft Alias: **manado**

**Comment by sericks007** [comment]
@tomhig, thank you for posting this.

@manalidongre, please review this and update the content, as needed.

**Comment by tonyafehr** [comment]
Bug 303668 has been logged to track this issue.

**Comment by manalidongre** [comment]
There are still 2 update types. For customers that are on version 8.0 and below, they still get platform updates separately and app updates are released as X++ updates. For customers that are on version 8.1 and above they get app updates as a cumulative update.
