### ISSUE TITLE
"The devInstall option is not applicable to the current deployable package"

### ISSUE THREAD

**Issue by steevegilbert** [MicrosoftDocs/dynamics-365-unified-operations-public#1062]
I tried following the "Install an application (AOT) deployable package on a development environment" but the step 4 fails with "The devInstall option is not applicable to the current deployable package".  I think there's missing info as mentionned here : https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/issues/204

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b080cde1-a8b7-2677-9de1-df7fd1c13467
* Version Independent ID: 932204fa-5988-997a-530b-1985646517ba
* Content: [Install deployable packages from the command line - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/deployment/install-deployable-package)
* Content Source: [articles/dev-itpro/deployment/install-deployable-package.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/deployment/install-deployable-package.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @manalidongre
* Microsoft Alias: **manado**

**Comment by sericks007** [comment]
@steevegilbert, thank you for posting this.

@manalidongre, please review this and update the content accordingly.

**Comment by tonyafehr** [comment]
Bug 303670 has been logged to track this issue.

**Comment by manalidongre** [comment]
If you are having issues using the devInstall command for an Application deployable package (AOT package) then please log a support ticket. devInstall is only support for this one package type.

**Comment by mores** [comment]
Where do you create the support ticket ?
I am having the same issue.

**Comment by tonyafehr** [comment]
To contact Support, visit [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). You also might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
