### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by amadse** [MicrosoftDocs/dynamics-365-unified-operations-public#1065]
should only be used with extremem caution.
extremen should be extreme

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28023f28-4aa0-18fd-b5fd-c2cc5f117f0b
* Version Independent ID: fe115611-d105-3b1d-f630-2df5398af447
* Content: [What's new or changed in Dynamics 365 for Finance and Operations platform update 23 (January 2019) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/whats-new-platform-update-23)
* Content Source: [articles/fin-and-ops/get-started/whats-new-platform-update-23.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/whats-new-platform-update-23.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @tonyafehr
* Microsoft Alias: **tfehr**

**Comment by sericks007** [comment]
@amadse, thanks for pointing this out! We'll get this fixed!

**Comment by sericks007** [comment]
This is fixed - the updated topic will be published later today. Thanks again!
