### ISSUE TITLE
Default automatic settlement table

### ISSUE THREAD

**Issue by B-rade** [MicrosoftDocs/dynamics-365-unified-operations-public#1068]
I think the example table for Default automatic settlement has incorrect values for the interest note. The interest note should still have a balance of 7.00 if the amount to settle was 0.00.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 723ee582-b7dc-c08c-f49d-e0a92da4e47d
* Version Independent ID: 31057a02-b3bb-4986-4a23-d4e106b7e7aa
* Content: [Automatic settlement and prioritization - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/accounts-receivable/automatic-settlement-prioritization#feedback)
* Content Source: [articles/financials/accounts-receivable/automatic-settlement-prioritization.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/accounts-receivable/automatic-settlement-prioritization.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @ShivamPandey-msft
* Microsoft Alias: **shpandey**

**Comment by josaw1** [comment]
Thank you for your feedback. I've let the author, @ShivamPandey-msft know.

**Comment by sericks007** [comment]
Bug 304170 has been logged to track this issue.
