### ISSUE TITLE
What happened to importing data for onebox DEV environments

### ISSUE THREAD

**Issue by rat-af** [MicrosoftDocs/dynamics-365-unified-operations-public#1069]
I think this document has changed again.  This document now seems to describe how to connect a onebox dev environment to an Azure DB, but the D365FO database is a local DB.  It no longer has the instructions on how to import the data to the local SQL server.  While the information here is quite useful to the purpose, those that are trying to refresh the local DB are once again left in the dark.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbfc55db-29cd-7e02-772a-4e590ff1fa78
* Version Independent ID: e4594af2-7087-6795-43f8-86cb3349534f
* Content: [Debug a copy of the production database - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/dbmovement-scenario-debugdiag)
* Content Source: [articles/dev-itpro/database/dbmovement-scenario-debugdiag.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/database/dbmovement-scenario-debugdiag.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @laneswenka
* Microsoft Alias: **laneswenka**

**Comment by firyanis** [comment]
Exactly... And I would say as usual...

**Comment by firyanis** [comment]
Forget my last comment, i found a link the page on the "Overview" page. It does not appear on the left side menu but it's still there : https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/dbmovement-scenario-exportuat

**Comment by rat-af** [comment]
Good pickup.  I do see it as a link in the overview page.
MS:  I think all the 'Step by Step' tutorials in the overview page should be in the 'Tutorial' listing in the left hand pane.  It would give a consistent and easier look and feel imo.  Would also help make that content easier to find, rather than sifting through lots of pages.

**Comment by josaw1** [comment]
Thanks for the feedback. 
@laneswenka, can you please help with this? Thanks.

**Comment by tonyafehr** [comment]
Bug 308965 has been logged to track this issue.

**Comment by laneswenka** [comment]
This was resolved in the latest PR

**Comment by tonyafehr** [comment]
@rat-af, thanks again for your feedback. This updated topic will be published tomorrow.
