### ISSUE TITLE
Retail Store Scale Unit Installer Issue

### ISSUE THREAD

**Issue by Phineas019** [MicrosoftDocs/dynamics-365-unified-operations-public#1070]
When I try to Download the Retails Scale store unit installer Got the error as Path Does not contain Package. Kindly suggest me a solution

![image](https://user-images.githubusercontent.com/41485361/54735977-e642e280-4bce-11e9-8634-3902160104be.png)

**Comment by josaw1** [comment]
Thanks for your feedback. I've let the program manager know about it.

**Comment by Phineas019** [comment]
Is that any update on this ?

**Comment by Dynamics365Fan** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

**Comment by sericks007** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
