### ISSUE TITLE
wrong menu for sharepoint config

### ISSUE THREAD

**Issue by haecktom** [MicrosoftDocs/dynamics-365-unified-operations-public#1071]
In 'Document Management and SharePoint experiences', there is mentioned 'Organization administration &gt; Document management &gt; Document management' while it should be 'System Administration &gt; Document management &gt; Document management'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9341b52a-c8a6-0e54-c3ee-7eaf4652f44c
* Version Independent ID: 2ef9cd6f-b4d3-b9f6-15dd-fb534a936b84
* Content: [Office integration tutorial - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/office-integration/office-integration-tutorial?toc=%2Fdynamics365%2Funified-operations%2Ftalent%2Ftoc.json#feedback)
* Content Source: [articles/dev-itpro/office-integration/office-integration-tutorial.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/office-integration/office-integration-tutorial.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @ChrisGarty
* Microsoft Alias: **cgarty**

**Comment by ShylaThompson** [comment]
@haecktom , the path in [the topic](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/office-integration/office-integration-tutorial?toc=%2Fdynamics365%2Funified-operations%2Ftalent%2Ftoc.json#document-management-and-sharepoint-experiences) is accurate in the most recent versions of the product. Closing as a non-issue.
