### ISSUE TITLE
PDF Folder and HA/Load Balancing for DRA

### ISSUE THREAD

**Issue by teomsn** [MicrosoftDocs/dynamics-365-unified-operations-public#1072]
I have two questions:
1) I found some documentation that the PDF-Folder is used if the DRA is running as a service and custom margins are used in reports. In this case the document cannot be printed directly and gets stored in that folder for manual printing. Is this the only usage for the PDF Folder? In which format other documents (with default margins) are transferred to the DRA and is there a second file with the printersettings?

2) If we install the DRA on two different print servers (exactly the same PrinterName) - is it possible to establish kind of a load balancing / HA solution? I could see that each printer in D365 can have several DRAs configured. When a document got sent to a printer is there a load balancing between the DRAs or is the document sent to always the first DRA in the list and if that DRA is not reachable will the next be used?

Thanks for supporting me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2128b07d-7349-6642-f05f-c94fe800d104
* Version Independent ID: 0568d0d1-8035-3423-f791-7bd82a5d070f
* Content: [Install the Document Routing Agent to enable network printing - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/install-document-routing-agent#feedback)
* Content Source: [articles/dev-itpro/analytics/install-document-routing-agent.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/install-document-routing-agent.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by tonyafehr** [comment]
Bug 308966 has been logged to track this issue.

**Comment by SteveBurkettNZ** [comment]
Regarding #2, it's load balancing. The print jobs are being stored in a queue on the D365FO end in the cloud. DRA's will check in every 5 seconds for new jobs waiting to be printed on that queue that are for any printers that that DRA has been configured to handle. If they find one in the queue it'll download and print it. Therefore two DRA's can print two documents in parallel, even if it's to the same printer. We're seeing each DRA able to handle around 12 print jobs per minute, which correlates to that 5-seconds poll period mentioned above.

**Comment by TJVass** [comment]
Regarding #1: **YES)** the PDF folder is only used for documents that are stored instead of printed.  In cases where documents contain standard margins, the document exchange between client and server is optimized using compressed EMF.  PDF is the only output format supported by the DRA.

Thanks @SteveBurkettNZ for providing details on question #2.
