### ISSUE TITLE
Unable  to download PDF of Microsoft Dynamics 365 for Finance and Operations documentation

### ISSUE THREAD

**Issue by avinashdandy** [MicrosoftDocs/dynamics-365-unified-operations-public#1081]
Please help me downloading PDF of Microsoft Dynamics 365 for Finance and Operations documentation.  As im getting error 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 784a9997-47ed-b2d1-980a-b453138e16ad
* Version Independent ID: d57cdbe6-a216-41ec-80bf-01a0292587a8
* Content: [Microsoft Dynamics 365 for Finance and Operations documentation - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/)
* Content Source: [articles/fin-and-ops/index.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/index.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @MargoC
* Microsoft Alias: **margoc**

**Comment by kfend** [comment]
Thanks for bringing this to our attention. We will work to get this resolved as soon as possible.

**Comment by kfend** [comment]
This issue has been fixed and you can now download the pdf.

**Comment by avinashdandy** [comment]
Hi Kristin,Thank you so much for your support.Yes, i can download it.Thanks,Avinash DandySent from my Samsung Galaxy smartphone.
-------- Original message --------From: Kristin Fender <notifications@github.com> Date: 23/03/2019  01:04  (GMT+05:30) To: MicrosoftDocs/dynamics-365-unified-operations-public <dynamics-365-unified-operations-public@noreply.github.com> Cc: avinashdandy <avinash.dandy09@gmail.com>, Author <author@noreply.github.com> Subject: Re: [MicrosoftDocs/dynamics-365-unified-operations-public] Unable  to download PDF of Microsoft Dynamics 365 for Finance and Operations documentation (#1081) This issue has been fixed and you can now download the pdf.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/MicrosoftDocs/dynamics-365-unified-operations-public","title":"MicrosoftDocs/dynamics-365-unified-operations-public","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public"}},"updates":{"snippets":[{"icon":"PERSON","message":"@kfend in #1081: This issue has been fixed and you can now download the pdf."}],"action":{"name":"View Issue","url":"https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/issues/1081#issuecomment-475753019"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/issues/1081#issuecomment-475753019",
"url": "https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/issues/1081#issuecomment-475753019",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
