### ISSUE TITLE
PO does not have to be confirmed.

### ISSUE THREAD

**Issue by fgork** [MicrosoftDocs/dynamics-365-unified-operations-public#1083]
It is not right where it says "If you are not using USMF, you need to have a confirmed purchase order with an open purchase order line before you start this guide."
You can do the steps if your PO isn't confirmed as well. There is actually an idea on Microsoft ideas site to make confirmation mandatory. (https://experience.dynamics.com/ideas/idea/?ideaid=76744bb3-7c2a-e911-9461-0003ff688f57)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5499159-d4f8-8622-911a-e6b5067ee8b6
* Version Independent ID: 9a0183e3-f0f0-b311-8e4f-07391b194fe2
* Content: [Register items for a basic warehousing enabled item using an item an item arrival journal - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/warehousing/tasks/register-items-basic-warehousing)
* Content Source: [articles/supply-chain/warehousing/tasks/register-items-basic-warehousing.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/warehousing/tasks/register-items-basic-warehousing.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @ShylaThompson
* Microsoft Alias: **shylaw**

**Comment by kfend** [comment]
@fgork   - can you create a pull request for the changes you made?

**Comment by ShylaThompson** [comment]
@fgork I created PR #1091 to merge your change with the public Live branch. I'm setting this issue as resolved now. 

Please note, it may take a day or two for the change to be completely published.
