### ISSUE TITLE
Override postLoad

### ISSUE THREAD

**Issue by dch9** [MicrosoftDocs/dynamics-365-unified-operations-public#1086]
This article should consider describing utilizing the OnPostedLoad event handler instead of overriding postLoad which is not a supported option with the extension model.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 897be989-9546-94dd-a260-6dcfcef08c53
* Version Independent ID: b4b73984-d8a8-edb4-2333-2ccde9b48488
* Content: [Computed columns and virtual fields in data entities - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/data-entity-computed-columns-virtual-fields#feedback)
* Content Source: [articles/dev-itpro/data-entities/data-entity-computed-columns-virtual-fields.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/data-entity-computed-columns-virtual-fields.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by ShylaThompson** [comment]
@Sunil-Garg please review and update the topic if necessary.

**Comment by tonyafehr** [comment]
Bug 308967 has been logged to track this issue.

**Comment by tonyafehr** [comment]
@dch9, thanks again for the feedback. An update to this topic will be published this week.
