### ISSUE TITLE
Document best practices and caveats around usage of exists/notexists joins

### ISSUE THREAD

**Issue by FH-Inway** [MicrosoftDocs/dynamics-365-unified-operations-public#1089]
Usage of exists/notexists joins can introduce issues in data selection or manipulation. For example, some combinations of exists and notexists joins in the same select can impact performance. Another example is that usage of order by in an exists join does not work.
These and other behaviors should be documented so that developers can avoid these kinds of issues.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f2875aa-c614-a807-90eb-247f8259cb1b
* Version Independent ID: 95a6e7b3-2f3d-cdb2-64e6-7c610704ae78
* Content: [X++ data selection and manipulation - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-ref/xpp-data-query)
* Content Source: [articles/dev-itpro/dev-ref/xpp-data-query.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-ref/xpp-data-query.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RobinARH
* Microsoft Alias: **robinr**

**Comment by ShylaThompson** [comment]
@RobinARH Can you review this documentation request?

**Comment by tonyafehr** [comment]
Bug 308970 has been logged to track this issue.

**Comment by RobinARH** [comment]
I added a link to this topic to the [X++ data selection and manipulation overview](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-ref/xpp-data/xpp-data-home-page) topic:

[Common misconception about Exists and Notexists joins](https://community.dynamics.com/365/financeandoperations/b/peter-s-x-developer-blog/posts/common-misconception-about-exists-and-notexists-joins)

It will go live later today.
