### ISSUE TITLE
Should add Navigation to the business event catalog page

### ISSUE THREAD

**Issue by Izmiyash** [MicrosoftDocs/dynamics-365-unified-operations-public#1090]
There is no information about how to open business event catalog page.
The navigation path (System administration > Setup > System parameters > Tab Business events - Preview.) should be added before you refer the navigation in Business events - Preview tab (Manage > Rebuild business events catalog). 
Thanks,
Izuru

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 655c157f-5478-4c71-7cd4-1b04383264ee
* Version Independent ID: 6555a353-87cd-c919-0c3e-dcfc4ede9909
* Content: [Business events - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/business-events/home-page#feedback)
* Content Source: [articles/dev-itpro/business-events/home-page.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/business-events/home-page.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by ShylaThompson** [comment]
@Sunil-Garg please review the issue and update the topic if necessary.
@sericks007 for awareness

**Comment by tonyafehr** [comment]
Bug 308968 has been logged to track this issue.

**Comment by Sunil-Garg** [comment]
This has been updated to show the navigation to the business event catalog. Pls note that after GA, the navigation is no longer via the system parameters.
