### ISSUE TITLE
How to configure this on 1-box environments?

### ISSUE THREAD

**Issue by turbozapekanka** [MicrosoftDocs/dynamics-365-unified-operations-public#1093]
There used to be a link but it has been disabled: https://blogs.msdn.microsoft.com/dynamicsaxbi/2017/07/29/accessing-analytical-workspaces-on-1box-environment/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd3a076-d364-f4e8-fe37-f10c77a75466
* Version Independent ID: 0f767e21-3f33-2139-0931-7cd044c81b9f
* Content: [Power BI integration with Entity store - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/power-bi-integration-entity-store?toc=%2Ffin-and-ops%2Ftoc.json#feedback)
* Content Source: [articles/dev-itpro/analytics/power-bi-integration-entity-store.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/power-bi-integration-entity-store.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by tonyafehr** [comment]
@turbozapekanka, thanks for the feedback. 

@laneswenka, can you address the issue with the link that is not working.

**Comment by tonyafehr** [comment]
@MilindaV2, can you address this issue. Thanks!

**Comment by tonyafehr** [comment]
Bug 308972 has been logged to track this issue.

**Comment by turbozapekanka** [comment]
I found another link
https://community.dynamics.com/365/financeandoperations/b/dynamicsaxbi/archive/2019/02/03/how-to-configure-power-bi-embedded-for-dynamics-365-for-finance-and-operations-one-box-environment
Looks like the content of all dynamics blogs is moved from msdn blogs to
another site but old links do not redirect to the new site

**Comment by tonyafehr** [comment]
@turbozapekanka, thanks for the info. I don't see a history of this blog - https://blogs.msdn.microsoft.com/dynamicsaxbi/2017/07/29/accessing-analytical-workspaces-on-1box-environment/ in this topic. 
Is this the topic where you accessed this blog?
https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/power-bi-integration-entity-store?toc=%2Ffin-and-ops%2Ftoc.json#feedback
