### ISSUE TITLE
Skip this section if you are updating to platform update 7 or newer. This was a pre-requesite step for build environments.

### ISSUE THREAD

**Issue by noakesey** [MicrosoftDocs/dynamics-365-unified-operations-public#1095]
I think regardless of the platform update, it will always be necessary to at least remove the metadata backup folder to prevent the next build replacing the updated binaries with those from the backup of the earlier version?  I would think its a good idea to also restore the backup before applying the update using PrepareForBuild.ps1?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 058d220b-d85d-eabd-abfb-8fadb3b8bf47
* Version Independent ID: c25f2d4d-dfef-7736-311f-8c1f25ddc696
* Content: [Apply the latest platform update to environments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/upgrade-latest-platform-update#feedback)
* Content Source: [articles/dev-itpro/migration-upgrade/upgrade-latest-platform-update.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/migration-upgrade/upgrade-latest-platform-update.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @tariqbell
* Microsoft Alias: **tabell**

**Comment by tonyafehr** [comment]
@noakesey, thanks for the feedback.

@laneswenka, can you review the suggested change and update this topic if necessary.

**Comment by tonyafehr** [comment]
Bug 308973 has been logged to track this issue.

**Comment by laneswenka** [comment]
I've reassigned the internal bug to the DevALM team

**Comment by laneswenka** [comment]
@tonyafehr  please reassign to Robert per the bug

**Comment by sericks007** [comment]
@robadawy, please review and update the topic if needed.

**Comment by jorisdg** [comment]
The reason this is no longer needed after PU7 is because the servicing does it for you (remove the backup).
