### ISSUE TITLE
Customer search criteria

### ISSUE THREAD

**Issue by hiteshgoldeneye** [MicrosoftDocs/dynamics-365-unified-operations-public#1097]
Can we default the customer search criteria to search by a particular field (say Email) when searching for customers.

**Comment by tonyafehr** [comment]
Your comment is not tied to a particular help topic. Which topic is this in reference to?

In the meantime, to get product help you can contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

**Comment by hiteshgoldeneye** [comment]
https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/pos-search-improvements


Regards
Hitesh

On 26 Mar 2019, at 9:17 PM, Tonya Fehr <notifications@github.com<mailto:notifications@github.com>> wrote:


Your comment is not tied to a particular help topic. Which topic is this in reference to?

In the meantime, to get product help you can contact Support using one of the options described here: Support contact options<https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support>. In particular, you might want to go to the Dynamics 365 for Finance and Operations community page<https://community.dynamics.com/> to get help with your questions from the Dynamics community.

**Comment by tonyafehr** [comment]
@hiteshgoldeneye, thanks for the additional info. 

@ShalabhjainMSFT, can you review the suggested change and update this topic if necessary.

**Comment by ShalabhjainMSFT** [comment]
The default search behavior can be updated by code customization. You would have to override the default customer search logic and write your own. However, the easier way would be to use the "Customer search shortcuts" and add Email as a shortcut. I am assuming you have already read the article, but adding it again just in case you missed reading this part:

https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/pos-search-improvements
