### ISSUE TITLE
Print Management settings aren't exported

### ISSUE THREAD

**Issue by FINOPSAOSCEWA** [MicrosoftDocs/dynamics-365-unified-operations-public#1098]
Hi, is there an option to export a database with Print management settings?
The print management settings are configured per legal entity. And the client has more than 100 legal entities in the system.
When the database is refreshed from Prod (or any tier 2 environment) to another environment (such as UAT) for testing, it will not feasible for the client to re-configure print management settings of 100+ legal entities in the target environment after each database refresh.
And there is not data entity available for print management setup.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d6f499a-5dd9-2928-3f2e-ef35e206e474
* Version Independent ID: c1075ce8-398c-f7b9-9420-cbb0c92f0151
* Content: [Export a database - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/export-database#feedback)
* Content Source: [articles/dev-itpro/database/export-database.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/database/export-database.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @laneswenka
* Microsoft Alias: **laneswenka**

**Comment by tonyafehr** [comment]
@FINOPSAOSCEWA, thanks for the feedback. To get product help you can contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

@laneswenka, can you review the suggested change and update this topic if necessary.

**Comment by tonyafehr** [comment]
Bug 308974 has been logged to track this issue.

**Comment by laneswenka** [comment]
We are required to sanitize the print management settings when copying databases between environments to prevent outbound email and integrations from being triggered.  I would suggest creating a custom data entity if this is a requirement for your customer.

**Comment by FINOPSAOSCEWA** [comment]
Thanks for your comment. I can understand why Microsoft want to prevent outbound emails and integrations from being triggered. To achieve it, deleting the print management setting records is one of many simple ways. However, is it a best practice to clear the configuration data during the database refresh every time?  There should be a better way. For instance, the Admin user email address can be used to replace (not delete) print management email address.
