### ISSUE TITLE
"Power BI content in LCS from Microsoft and your partners Link" is broken

### ISSUE THREAD

**Issue by tomhig** [MicrosoftDocs/dynamics-365-unified-operations-public#1101]
The Power BI content in LCS from Microsoft and your partners link in the Accessing Power BI Content section is referencing a Blog that is no longer in service.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb0614e8-5677-60b5-10b4-5faa4a434bcf
* Version Independent ID: ca01592c-5983-e089-2901-ab9edfb46550
* Content: [Cost accounting analysis Power BI content - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/cost-accounting-analysis-content-pack#feedback)
* Content Source: [articles/dev-itpro/analytics/cost-accounting-analysis-content-pack.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/cost-accounting-analysis-content-pack.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @AndersGirke
* Microsoft Alias: **aevengir**

**Comment by tonyafehr** [comment]
@tomhig, thank you for the feedback. 

@AndersGirke, please review this issue and update the link in this topic.

**Comment by tonyafehr** [comment]
Bug 308975 has been logged to track this issue.
