### ISSUE TITLE
Link to supported countries

### ISSUE THREAD

**Issue by karleesm** [MicrosoftDocs/dynamics-365-unified-operations-public#1102]
Can we please include a link to supported countries in the document - "Modular applications will be provisioned only in supported countries or regions."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43e145b6-a02f-49e3-3fc0-7d80a0e85303
* Version Independent ID: e4652c2f-8125-d6a2-f288-f172c7e629f6
* Content: [Provisioning for the Dynamics 365 for Talent modular apps - Talent | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/talent/modular-app-tech-faq#feedback)
* Content Source: [articles/talent/modular-app-tech-faq.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/talent/modular-app-tech-faq.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @andreabichsel
* Microsoft Alias: **anbichse**

**Comment by sericks007** [comment]
@karleesm, thanks for providing this feedback!

@andreabichsel, can you please review and update the topic as needed.

**Comment by andreabichsel** [comment]
Thank you @karleesm, I added the link!
