### ISSUE TITLE
Broken link for the F&O BI blog

### ISSUE THREAD

**Issue by maveloso** [MicrosoftDocs/dynamics-365-unified-operations-public#1105]
the link under getting started, "Finance and Operations: Business intelligence (blog)" Leads to a "page not found" page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adf5c448-2cd0-1538-d380-4af101563e90
* Version Independent ID: e6497148-5f30-b30a-98ca-853181932447
* Content: [Business intelligence (BI) and reporting home page - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/bi-reporting-home-page?toc=%2Ffin-and-ops%2Ftoc.json#feedback)
* Content Source: [articles/dev-itpro/analytics/bi-reporting-home-page.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/bi-reporting-home-page.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @sericks007
* Microsoft Alias: **sericks**

**Comment by sericks007** [comment]
@maveloso, thanks for making us aware of this issue!  I've fixed the link, and the updated topic will be published later today.

In the meantime, you can find the blog here: https://community.dynamics.com/365/financeandoperations/b/powerbianalyticsandreporting
