### ISSUE TITLE
Retail Cloud Scale Unit

### ISSUE THREAD

**Issue by AndersDahlin** [MicrosoftDocs/dynamics-365-unified-operations-public#1106]
Can this also be used for the RCSU database? Any information on how to access the information for the channel database?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2cf3f22-3c3d-7a29-cd1e-df61b9edd3c0
* Version Independent ID: 4db504aa-4f47-d9b4-89e6-4e6292984238
* Content: [Performance troubleshooting using tools in Lifecycle Services (LCS) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/performancetroubleshooting#feedback)
* Content Source: [articles/dev-itpro/lifecycle-services/performancetroubleshooting.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/lifecycle-services/performancetroubleshooting.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @manalidongre
* Microsoft Alias: **manado**

**Comment by josaw1** [comment]
Hi, thanks for your question. I've let @manalidongre know about it.

**Comment by sericks007** [comment]
Bug 309250 has been logged to track this issue.

**Comment by AamirAllaq** [comment]
At this point, this content does not apply to RCSU database. RCSU database does not currently support direct access. We're evaluating various options to enhance troubleshooting experience for RCSU and will share it broadly once we solidify on a plan of action.

Thanks.
