### ISSUE TITLE
Upgrade from 8.1 to 10

### ISSUE THREAD

**Issue by teomsn** [MicrosoftDocs/dynamics-365-unified-operations-public#1107]
Hello, we would like to upgrade a customer from 8.1 to 10. I'm not sure at the moment - do we only have to apply "Generally available - Dynamics 365 for Finance and Operations version 10.0" Package like doing a platform update to all the different sandboxes (and PROD) or do we have to do all the steps desciped in this article (like Deploying new DEV and BUILD sandboxes, create a new branch, remove all hotfixes, recompile, produce a new deployable package, merge it with 10.0 package,...). The customer is not in standard - he has several modifications in place and is productive since almost a year. Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b3b5ec6-1a21-e71a-df38-ba497f7f1116
* Version Independent ID: d1e49823-7934-6a3a-50e1-547cdd632077
* Content: [Update environments from version 8.0 to 8.1.X or 10.X - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/appupdate-80-81)
* Content Source: [articles/dev-itpro/migration-upgrade/appupdate-80-81.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/migration-upgrade/appupdate-80-81.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by josaw1** [comment]
Thanks for your question. I've let @laneswenka know about it.

**Comment by tonyafehr** [comment]
Bug 313337 has been logged to track this issue.

**Comment by naveenkumarjagtab** [comment]
Hi Guys, any update on the steps to be followed for upgrading 8.1 to 10.0  D365 sandbox

**Comment by teomsn** [comment]
Hi, simply upgrade with the GA package, no redeployments, no additional trunks,...Regards

**Comment by aledoy** [comment]
plus 1 on the GA package, straight forward

**Comment by laneswenka** [comment]
Yes, this is because we don't refer to this as Upgrade.  This is called Update going forward.  Please see https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/upgrade-latest-update#automatic-update
