### ISSUE TITLE
All tables that contain financial dimensions can be used as sources for statistical measures.

### ISSUE THREAD

**Issue by aariste** [MicrosoftDocs/dynamics-365-unified-operations-public#1108]
We've seen in the form lookup that displays the table list that it's not an automatically generated list of tables anymore (the code is commented). Instead it's a fixed list (actually a X++ List) of tables. 

Is this list mantained through different 365FO versions? Are all dimension enabled tables in that list?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eaeebfc9-853a-d1c1-18ac-023e0c499775
* Version Independent ID: d2802ca2-add0-4167-7a42-7cd01634044f
* Content: [Statistical dimension members and statistical measure provider templates - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/cost-accounting/statistical-measure-provider-template#feedback)
* Content Source: [articles/financials/cost-accounting/statistical-measure-provider-template.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/cost-accounting/statistical-measure-provider-template.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @AndersGirke
* Microsoft Alias: **shylaw**

**Comment by josaw1** [comment]
Thanks for your question. I've let @AndersGirke know about it.

**Comment by tonyafehr** [comment]
Bug 313338 has been logged to track this issue.
