### ISSUE TITLE
Strd Structured Remittance message format not available for Netherlands, France, Germany?

### ISSUE THREAD

**Issue by JohanMaria1974** [MicrosoftDocs/dynamics-365-unified-operations-public#1111]
Hi, thanks for this very insightful information on SEPA credit transfers in D3FO.  Our organization also has branches in Germany, France and the Netherlands and we would need to (continue) use structured remittance messages for payments by our customers.  I read under the section on Strd that this option is not avialble for the specific formats used in Netherlands, France & Germany.  Could you give me some more info on that ?  Is there a fix in the making?  or alternative approaches in D3FO (not requiring (heavy) customizing?) thanks in advance, Johan Peeters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de09203c-d84c-c239-179e-18cd71e6984d
* Version Independent ID: 0ec46dbf-b754-5980-ddb2-90c1e4268853
* Content: [SEPA credit transfer overview - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/accounts-payable/sepa-credit-transfer#feedback)
* Content Source: [articles/financials/accounts-payable/sepa-credit-transfer.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/accounts-payable/sepa-credit-transfer.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @ShylaThompson
* Microsoft Alias: **mrolecki**

**Comment by ShylaThompson** [comment]
@mrolecki can you review this issue?

**Comment by tonyafehr** [comment]
Bug 313339 has been logged to track this issue.

**Comment by v-oloski** [comment]
Thank you for your question. 
Really ISO20022 Credit transfer format for Germany, France and the Netherlands does not contain structured remittance messages block in current design.  These formats were implemented according the country level guidelines. But a company may use ISO20022 Credit transfer generic format (all country formats were implemented on base of this format), if this format is aligned with bank requirements, or update country specific formats. These updates are not complex and require only GER configuration modifications. In general, it is necessary to derive GER format configuration and add several updates in the format (as example a user may use ISO20022 Credit transfer format (generic)):
1.	Add ExportFormat(Format): Data model enumeration user input parameter Format ExportFormat(Format): Data model enumeration user input parameter Format/ User input parameter)
2.	Add Format enumeration (mapping/ Add root/ Add source – Data model/ Enumeration) 
3.	Add Strd node under RmtInf node and input conditions and mapping. Example of this node may be found in ISO20022 Credit transfer format (generic)
4.	Modify enabled condition for RmtInf node
5.	Add any other conditions, if needed.  
More info for GER customization process see under link Electronic reporting (ER).
If you think that this is not bank specific requirements but legislation or country level requirements for Germany, France and the Netherlands, please, let us know.

**Comment by JohanMaria1974** [comment]
Thank you all so much for following up on this matter. I highly appreciate
it - our company is in the middle of implementing D3FO as the single global
ERP and in Europe we serve all 3 markets and want to go for structured
payments /remittance.

Thanks again

Kind regards

Johan Peeters
Customer Service Manager
CRC Industries Europe

Op wo 10 apr. 2019 17:18 schreef Olga Oskina <notifications@github.com>:
