### ISSUE TITLE
Bug Fixes Typo

### ISSUE THREAD

**Issue by JoelLeichty** [MicrosoftDocs/dynamics-365-unified-operations-public#1112]
Should say "10.0.1" not "10.0" in the Bug fixes section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 926b95da-8eaa-e23b-eeca-b334ea932e19
* Version Independent ID: 8f4901db-8cd1-74b3-0306-09b6295abd05
* Content: [Preview features in Finance and Operations version 10.0.1 (April 2019) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/whats-new-changed-10-0-1)
* Content Source: [articles/fin-and-ops/get-started/whats-new-changed-10-0-1.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/whats-new-changed-10-0-1.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @tonyafehr
* Microsoft Alias: **tfehr**

**Comment by tonyafehr** [comment]
@JoelLeichty, thanks for noting this. I'll update the topic and it should be re-published later today.
