### ISSUE TITLE
Certain WITs not showing up in LCS

### ISSUE THREAD

**Issue by mitchellgarner** [MicrosoftDocs/dynamics-365-unified-operations-public#1113]
We recently restored the default mappings in LCS for Azure DevOps WITs.  This took away the mapping of Issues in LCS to Issues in Azure DevOps.  How do I restore this?

Is it possible to map to a custom WIT?  We added "Issue Log" so that our issues could show up in the backlog pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1804282-0c48-6305-c6b2-b31dec2727df
* Version Independent ID: 2650812b-ab37-47ef-c103-a8a094cc8fce
* Content: [Synchronize BPM libraries with Azure DevOps - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/synchronize-bpm-vsts#feedback)
* Content Source: [articles/dev-itpro/lifecycle-services/synchronize-bpm-vsts.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/lifecycle-services/synchronize-bpm-vsts.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @kfend
* Microsoft Alias: **ntecklu**

**Comment by kfend** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
