### ISSUE TITLE
Extension articles under this article

### ISSUE THREAD

**Issue by emurakami** [MicrosoftDocs/dynamics-365-unified-operations-public#1115]
The three articles hierarchical under this one (Extend the list of electronic reporting functions, Electronic reporting framework API Changes for Application update 7.3, and Specify a customer storage for generated documents) don't seem to be related to this article. I would suggested a different summary article discussing extending the ER framework to organize those articles.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16129700-c41f-2d90-1805-843bef3cb418
* Version Independent ID: 1c495cba-42ce-b8e7-527f-5f3e4e1a3599
* Content: [Split generated XML files based on file size and content quantity - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/er-split-files?toc=/fin-and-ops/toc.json)
* Content Source: [articles/dev-itpro/analytics/er-split-files.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/er-split-files.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @NickSelin
* Microsoft Alias: **nselin**

**Comment by ShylaThompson** [comment]
@emurakami thanks for your comment. We are currently in the process of rearranging the Electronic reporting table of contents and I appreciate your comment. Please expect to see a different and better organization of this content in the near future.
