### ISSUE TITLE
Missing information about "Run Best Practices Fixers" option

### ISSUE THREAD

**Issue by SysC0mp** [MicrosoftDocs/dynamics-365-unified-operations-public#1117]
It is possible to execute the "Run Best Practices Fixers" command for each project in a visual studio solution, but I cannot find any information about that option. I also could not find any information about that in the Dynamics AX Community Forum.

- How can I use this feature?
- Is it possible to write own "Best practice fixers"?

Thanks & Best regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15d3cf22-c316-5df9-4203-88a0add25e2d
* Version Independent ID: c4844080-547b-90f7-0780-eb843294d6b4
* Content: [Write best practice rules - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-tools/author-best-practice-rules)
* Content Source: [articles/dev-itpro/dev-tools/author-best-practice-rules.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-tools/author-best-practice-rules.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @pvillads
* Microsoft Alias: **pvillads**

**Comment by tonyafehr** [comment]
Bug 313341 has been logged to track this issue.

**Comment by SysC0mp** [comment]
Any information regarding that topic?

**Comment by SysC0mp** [comment]
Any news to that?
