### ISSUE TITLE
This is what I had to do to get this to work

### ISSUE THREAD

**Issue by brgarity** [MicrosoftDocs/dynamics-365-unified-operations-public#1118]
The documentation is missing some steps.  I have a doc that I made that includes the missing information but I don't know how to submit that to you???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3eb22af1-4e63-ed08-7586-341a5593b8fd
* Version Independent ID: b5b82695-ef06-7e5a-37b9-043aef0011e0
* Content: [Show order notifications in the point of sale (POS) - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/notifications-pos#feedback)
* Content Source: [articles/retail/Notifications-POS.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/Notifications-POS.md)
* Service: **dynamics-365-retail**
* GitHub Login: @ShalabhjainMSFT
* Microsoft Alias: **ShalabhjainMSFT**

**Comment by ShylaThompson** [comment]
@brgarity thanks for reaching out.  

To get edit a topic, click the Edit (pencil) button on a topic in the upper right corner of the page, or go to our repo at [https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public) and navigate to the file that you want to edit.

For more information, please refer to [our contributor's guide](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/blob/live/CONTRIBUTING.md).

**Comment by brgarity** [comment]
I could not see how to best update the documentation.  I’ve included a .pdf of the additional steps required to accomplish this task.

Brian Garity | Dynamics 365 Operations Technical Specialist
Email: brgarity@microsoft.com
Cell: 262-490-4267

**Comment by ShylaThompson** [comment]
@ShalabhjainMSFT please review and update the content as necessary.

@brgarity your PDF upload did not work. Please try to upload directly to the GitHub issue. Do no reply via email.

**Comment by brgarity** [comment]
To make the required changes to the buttons you need to start on the POS side.  From the POS , click on Settings which is circled.  Then take note of the Screen Layout ID "F3MGR"  & the layout resolution of 1440x960.

Note:  The button development changes need to be done using the Edge browser.
[Session information  Application session ID  cc982467-57e7-d89b-666d-d071c9e99363  User session ID  a-1165-cefb-d41b-bfb128eeaOaf  Screen layout ID  Layout resolution  1440x960  App window resolution  1500x890  Device activation  Retail server  httpsfld365env15e88c2d1e6ba5617ret.cloudax_dyna  mics.com/Commerce  Store  Houston  Register  HOUSTON-U  Device  HOUSTON-U  Deactivate device  Deactivate  After the device is deactivated, it can no longer be  used to access the point of sale system until  activated again.  Task Recorder  use task recorder to cre  that can be turned into  played back as tutorials  g] Open task recon]





Next, go to F&O Screen Layouts as shown below.  Search on F3MGR.  Select the correct resolution and then select Welcome Screen 1 "START" line as that is where the buttons we want to change are.  Then select "Designer".
[Untitled picture.png Dynamics 365 v Finance and Operations  Edit 4— New Delete Copy OPTIONS p  Reta  Channel setup  POS setup  >  pos  Screen layouts  Width  1024  1280  1366  1440  480  USRT  p  F3mgr  F3MGR  Fabrikam Manager  SCREEN LAYOUTS  Screen layout ID  F3MGR  LAYOUT SIZES  Name  Fabrikam Manager  + Add 13 Remove Layout designer  Name  024x768 - Full  280x720 - Full  366x768 - Full  1440x960 - Full  480x853 - Compact  Add Remove  Caput zone  Welcome screen 1  Welcome screen 2  Layout type  Modern POS  Modern POS  Modern POS  Modern POS  Default start screen  Welcome screen  - Full  - Full  - Full  - Full  Height  768  720  768  960  853  Designer  Modern POS - Compact  Button grid ID  F2WIM  F2W2  Name  Start  Products   Ink Drawings]






When you click on "Designer" the button grid designer will pop up.  Then you right click on the buttons you want to modify and that will open up
[Untitled picture.png * autton grid design - Button grid ID: F2WIM  New button Delete button New design Select grid  Select  Button properties  Delete button  Add row  Add column  Delete row  Delete column   Ink Drawings  Ink Drawings]



When the Configure Button editor pops up, it will look like what you see below.  Click the "Enable live content" box and select "Top Right" for content alignment.  Then simply select OK.
[Configure  Action  Delivery mode  Order fulfillment  Ship from store  Enable live content Z]  Content alignment Top right  Button text  Hide button text  Tooltip  Image alignment  Size in columns  Size in rows  Orders to ship  Center  2  Enable custom font for POS  Font size  Font style  12  Regular  Q'tton  Select image...  Clear image  use custom theme  Back color  Back color 2  Border color  Font color  Gradient mode  OK  —s, 161, 96  —s, 161, 96  Horizontal  Cancel]
[Then close the Button grid design box.    Untitled picture.png *autton grid design Button grid ID: F2WIM  New button Delete button New design Select grid  Close           Ink Drawings]
Then Run this batch job.  Once you run the job, it should take less than 30 minutes before you see the changes in your buttons on the POS.
[Dynamics 365 v Finance and Operations  Retail > Retail IT >  Distribution schedule  New Delete Create batch job Run now History OPTIONS p  Edit  p Filter  I uuu  1070  Channel configuration  1080  1090  Registers  1095  Offline database configuration  1100  Product and price parameters  1110  DISTR13UT10N SCHEDULES  Name  1090  General  Direction of data flow  Download  Channel database groups  Add Remove  Channel database g  Default  Description  Registers  Current batch job  Current batch  N/A  Active]


Brian Garity | Dynamics 365 Operations Technical Specialist
Email: brgarity@microsoft.com
Cell: 262-490-4267

**Comment by tonyafehr** [comment]
Bug 313342 has been logged to track this issue.

**Comment by tonyafehr** [comment]
The topic has been updated to reflect this feedback and new content will be published this week.
