### ISSUE TITLE
Cannot drop the procedure 'XU_DisableEnableNonClusteredIndexes', because it does not exist or you do not have permission.

### ISSUE THREAD

**Issue by valerymoskalenko** [MicrosoftDocs/dynamics-365-unified-operations-public#1119]
I can't find XU_DisableEnableNonClusteredIndexes in the stored procedures. My version is 8.1.3

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 277452eb-70c4-3d29-5219-1355a40bb714
* Version Independent ID: a9d425c4-c627-d20f-4098-307eceb2dd07
* Content: [Golden configuration promotion - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/dbmovement-scenario-goldenconfig)
* Content Source: [articles/dev-itpro/database/dbmovement-scenario-goldenconfig.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/database/dbmovement-scenario-goldenconfig.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @laneswenka
* Microsoft Alias: **laneswenka**

**Comment by ShylaThompson** [comment]
@laneswenka can you review this issue and update the topic or respond to the poster?

**Comment by tonyafehr** [comment]
Bug 313343 has been logged to track this issue.

**Comment by laneswenka** [comment]
Updated in the latest Pull Request

**Comment by tonyafehr** [comment]
@valerymoskalenko, this updated content will be published tomorrow.
