### ISSUE TITLE
Retail store scale unit components

### ISSUE THREAD

**Issue by OksanaKovaliova** [MicrosoftDocs/dynamics-365-unified-operations-public#1120]
Hi, does RSSU not include Cloud POS component anymore? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 117efc64-27a2-cc6d-277b-34835be7b08d
* Version Independent ID: d7066d76-58e5-3cfb-90f0-1b76f187fcf4
* Content: [Select an in-store topology - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations//retail/dev-itpro/retail-in-store-topology#feedback)
* Content Source: [articles/retail/dev-itpro/retail-in-store-topology.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/dev-itpro/retail-in-store-topology.md)
* Service: **dynamics-365-retail**
* GitHub Login: @rassadi
* Microsoft Alias: **jashanno**

**Comment by ShylaThompson** [comment]
@jashanno can you review this issue and update the topic or respond to the poster?

**Comment by tonyafehr** [comment]
Bug 313344 has been logged to track this issue.

**Comment by nazimi-msft** [comment]
Cloud POS is included as part of Retail store scale unit. The documentation will be updated accordingly. Thank you!
