### ISSUE TITLE
Run the installer on any other device

### ISSUE THREAD

**Issue by OksanaKovaliova** [MicrosoftDocs/dynamics-365-unified-operations-public#1121]
Run the installer on any other device - does this section describe 'Hybrid App' installation (CPOS inside mobile App) - or some another App? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 927871b0-20f5-3541-bd32-f6dc785374df
* Version Independent ID: 15ec7fef-92df-4ec5-5507-0d97527b64c5
* Content: [Configure, install, and activate Retail Modern POS (MPOS) - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/retail-modern-pos-device-activation)
* Content Source: [articles/retail/retail-modern-pos-device-activation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/retail-modern-pos-device-activation.md)
* Service: **dynamics-365-retail**
* GitHub Login: @jashanno
* Microsoft Alias: **jashanno**

**Comment by ShylaThompson** [comment]
@jashanno can you review this issue and update the topic or respond to the question?

**Comment by tonyafehr** [comment]
Bug 313345 has been logged to track this issue.

**Comment by jashanno** [comment]
Hi OksanaKovaliova,

That section refers to the Android or iOS application (Which functions as Cloud POS within a mobile app).  There are no other applications offered by Dynamics Retail that function on iOS or Android at this time.
