### ISSUE TITLE
Hardware station

### ISSUE THREAD

**Issue by OksanaKovaliova** [MicrosoftDocs/dynamics-365-unified-operations-public#1122]
Hi, is Hardware station still not available component? The following article says it is available: https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/deployment/deploy-retail-onprem

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cf9a796-9280-5e52-4530-77e4154ff532
* Version Independent ID: 1789b865-6c46-9597-7ad3-268af43ca7b4
* Content: [Retail capabilities that are available in on-premises deployments - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/retail-onprem)
* Content Source: [articles/retail/retail-onprem.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/retail-onprem.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @aamirallaqaband
* Microsoft Alias: **aamiral**

**Comment by ShylaThompson** [comment]
@AamirAllaq can you review this issue and update the topic if necessary?

**Comment by tonyafehr** [comment]
Bug 313346 has been logged to track this issue.

**Comment by Reza-Assadi** [comment]
Hi Oksana,

That is correct but we are currently working on providing support by the fall release.

Thanks,
Reza
