### ISSUE TITLE
Document change tracking

### ISSUE THREAD

**Issue by alanflanders** [MicrosoftDocs/dynamics-365-unified-operations-public#1125]
I would like to subscribe to changes on this content page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f271eeaf-54e1-5476-bfbf-37f8b899c425
* Version Independent ID: b5156471-8259-9cbd-f68b-ad4a9a4c864a
* Content: [Videos for Finance and Operations - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/videos#feedback)
* Content Source: [articles/fin-and-ops/get-started/videos.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/videos.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by tonyafehr** [comment]
You can only subscribe to an RSS feed of all updates to the Unified Operations content. To do that, use the following link from a browser that supports RSS feeds: [RSS feed](https://docs.microsoft.com/api/search/rss?locale=en-us&$filter=scopes%2Fany(t%3A%20t%20eq%20%27Unified%20Operations%27))
