### ISSUE TITLE
Link for (bank reconciliation import file technical layout definitions and..) fails with "ERR_CONNECTION_CLOSED"

### ISSUE THREAD

**Issue by gaggaz12** [MicrosoftDocs/dynamics-365-unified-operations-public#1134]
Hi, the link for "Below are examples of the advanced bank reconciliation import file technical layout definitions and three related bank statement example files: https://mbs.microsoft.com/customersource/northamerica/AX/learning/documentation/how-to-articles/exofbankstfotechlayouts"
fails with ERR_CONNECTION_CLOSED in chrome, firefox and IE

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e05abef3-f815-21a0-eedb-e67901e5bf99
* Version Independent ID: c4556269-06f3-177a-7da7-1de63eea835b
* Content: [Set up the advanced bank reconciliation import process - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/cash-bank-management/set-up-advanced-bank-reconciliation-import-process#feedback)
* Content Source: [articles/financials/cash-bank-management/set-up-advanced-bank-reconciliation-import-process.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/cash-bank-management/set-up-advanced-bank-reconciliation-import-process.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @ShylaThompson
* Microsoft Alias: **saraschi**

**Comment by sericks007** [comment]
@gaggaz12, thanks for making us aware of this issue.

@ShylaThompson, can you please fix the link?

**Comment by ShylaThompson** [comment]
@gaggaz12 the link works now. CustomerSource went through maintenance last week, which was likely why the link was broken for you. Please try again.
