### ISSUE TITLE
Track user sign-ins is not working as mentioned. no capturing in telemetry. browser and IP information showing blank in all cases

### ISSUE THREAD

**Issue by uzairsaleem75** [MicrosoftDocs/dynamics-365-unified-operations-public#1135]
Track user sign-ins is not working as mentioned. no capturing in telemetry. browser and IP information showing blank in all cases. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3d645ca-b551-53d7-6156-86c6822975da
* Version Independent ID: 814c625e-202e-ba34-3120-99265859e78c
* Content: [Track user sign-ins - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/user-logins#feedback)
* Content Source: [articles/dev-itpro/lifecycle-services/user-logins.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/lifecycle-services/user-logins.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @manalidongre
* Microsoft Alias: **sarvanis**

**Comment by sericks007** [comment]
@uzairsaleem75, thanks for making us aware of this issue.

@manalidongre, can you please review and update the topic, as needed.

**Comment by tonyafehr** [comment]
Bug 313432 has been logged to track this issue.

**Comment by manalidongre** [comment]
Please log a support ticket for this issue. The process is correct.
