### ISSUE TITLE
reg. Deriving from internal classes is deprecated

### ISSUE THREAD

**Issue by markusotte08** [MicrosoftDocs/dynamics-365-unified-operations-public#1136]
Can we add below links for clarification?
https://community.dynamics.com/365/financeandoperations/b/mfp/archive/2019/03/20/x-access-specifiers-revisited
https://community.dynamics.com/365/financeandoperations/b/mfp/archive/2019/01/24/x-access-modifiers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07111f31-687b-8c0c-202e-8763be825357
* Version Independent ID: edbb6ff7-509d-f2c0-4a88-fc3976f11b8b
* Content: [Removed or deprecated features - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/deprecated-features#feedback)
* Content Source: [articles/dev-itpro/migration-upgrade/deprecated-features.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/migration-upgrade/deprecated-features.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @sericks007
* Microsoft Alias: **sericks**

**Comment by sericks007** [comment]
@markusotte08, thank you for bringing this to our attention!  I'll check with the PM.

**Comment by sericks007** [comment]
Bug 313994 has been logged for this issue.
