### ISSUE TITLE
Improve documentation for local development environments

### ISSUE THREAD

**Issue by FH-Inway** [MicrosoftDocs/dynamics-365-unified-operations-public#1137]
The current documentation is written for environments that are not local development environments. It should be updated with information for those environments, especially when it comes to the creation of the topology file. A comment in that file indicates that for local development environments, only an update of the AOSService component is supported. But at least for the 10.0 update, this will lead to issues because other service components (such as DevToolsService and DIXFService) need to be updated, too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b080cde1-a8b7-2677-9de1-df7fd1c13467
* Version Independent ID: 932204fa-5988-997a-530b-1985646517ba
* Content: [Install deployable packages from the command line - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/deployment/install-deployable-package#feedback)
* Content Source: [articles/dev-itpro/deployment/install-deployable-package.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/deployment/install-deployable-package.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @manalidongre
* Microsoft Alias: **manado**

**Comment by FH-Inway** [comment]
See also https://community.dynamics.com/365/financeandoperations/b/365foroperationstechnical/archive/2019/04/06/issues-after-installing-binary-updates-to-local-dev-machine

**Comment by sericks007** [comment]
Bug 313995 has been logged to track this issue.

**Comment by FH-Inway** [comment]
Any updates on this? It has been 4 months and people are still getting confused by this (see e.g. https://stackoverflow.com/questions/57203150/d365-devvm-bestpractise-broken-after-updating-to-pu28)

**Comment by AlexHimself** [comment]
I second this. Microsoft is focused on everything cloud, but they don't realize the bulk of development occurs in the Dev VM's, which feel like an after thought.

**Comment by sericks007** [comment]
@manalidongre or @robadawy, could you please review and respond.

**Comment by robadawy** [comment]
The instructions in the linked article work on all environments, including local development environment.  Regarding this comment above "A comment in that file indicates that for local development environments, only an update of the AOSService component is supported. But at least for the 10.0 update, this will lead to issues because other service components (such as DevToolsService and DIXFService) need to be updated, too" - The instructions in the article guide you through updating the topology file so you don't run into this issue.

On the other hand, I agree we can simplify / re-organize the document more highlight areas that need attention. It is currently too technical.

**Comment by FH-Inway** [comment]
Hello Robert, thank you for your answer. I think other than the misleading comment in the topology file itself, the confusion also stems from the section "Collect topology configuration data" that starts with "1. In LCS, on the Environment page, select the name of a VM." This seems to indicate that this part of the document is only meant for environments in LCS, but not for local vhd development environments. I recommend to rephrase this so that it becomes clear that this is also a necessary step for local vhd development environments.
I also recommend adding a link to the [Invoke-D365SDPInstall](https://github.com/d365collaborative/d365fo.tools/blob/development/docs/Invoke-D365SDPInstall.md) function that hides away much of the technical details of this process.

**Comment by jorisdg** [comment]
There are simplified command line options for dev VMs that can be used which we should add to the documentation.

**Comment by jorisdg** [comment]
Looks like the article already describes the simplified command line: https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/install-deployable-package#install-an-application-aot-deployable-package-on-a-development-environment

**Comment by FH-Inway** [comment]
Hello @jorisdg , could you confirm that the `AXUpdateInstaller.exe devinstall` command will work for Microsoft updates (e.g. version 10.0.8 with PU 32)? Last time we checked, this command only worked for application packages, but not for platform updates. To install those, you have to go through the whole topology file and runbook stuff, which causes the confusion. Maybe just add link to [Invoke-D365SDPInstall](https://github.com/d365collaborative/d365fo.tools/blob/master/docs/Invoke-D365SDPInstall.md)?

**Comment by jorisdg** [comment]
devinstall only updates the X++ binaries for the AOS - nothing else. So no, it does not update dev tools, SSRS, etc. etc.
You can see this in the deployable package. If you open the ZIP file, you'll find the "DevInstallServiceModelData.xml" which only shows the AOS (and DIXF but I believe this is just to stop/start that service to allow the update).

The point here is that devinstall can work without admin rights, to install ISV packages.
