### ISSUE TITLE
Unable to add the MS LCS repository, step 5

### ISSUE THREAD

**Issue by ponek** [MicrosoftDocs/dynamics-365-unified-operations-public#1143]
Get the following error when trying to add the MS LCS repo

Failed to generate the user token for Dynamics Lifecycle services on behalf on user {C872AA9A-EF7F-4745-968A-C584F02D0C4D}. Please contact your system administrator.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54fd860e-7cd1-af1d-c9f2-9f892060b663
* Version Independent ID: fc98ae9d-8e9a-3f0c-945a-8949422d5e9b
* Content: [Download Electronic reporting configurations from Lifecycle Services - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/download-electronic-reporting-configuration-lcs#feedback)
* Content Source: [articles/dev-itpro/analytics/download-electronic-reporting-configuration-lcs.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/download-electronic-reporting-configuration-lcs.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @NickSelin
* Microsoft Alias: **nselin**

**Comment by ShylaThompson** [comment]
@ponek  Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

**Comment by GeorgeSasDK** [comment]
@ponekbladh solved your issue ? Have same issue on my test environment.
