### ISSUE TITLE
Content pack link

### ISSUE THREAD

**Issue by davecope1982** [MicrosoftDocs/dynamics-365-unified-operations-public#1144]
The link above to the content pack in LCS is not working, please could you advise where we can get these resources from?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 044f1dfc-75e0-e4de-4a75-03266e0be158
* Version Independent ID: 5beb82c0-d1d2-9d79-259c-45d86f5a848b
* Content: [Expense management Power BI content - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-nz/dynamics365/unified-operations/dev-itpro/analytics/expense-management-content-pack?toc=/fin-and-ops/toc.json)
* Content Source: [articles/dev-itpro/analytics/expense-management-content-pack.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/expense-management-content-pack.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @ryansand
* Microsoft Alias: **shylaw**

**Comment by ShylaThompson** [comment]
@davecope1982 Thanks for letting us know about the broken link. 

@ryansandness can you respond with a link to where @davecope1982 can get the content packs from?

**Comment by tonyafehr** [comment]
Bug 314834 has been logged to track this issue.

**Comment by tonyafehr** [comment]
This is a known LCS bug, so I am closing this issue as resolved.

**Comment by davecope1982** [comment]
is there a link to the LCS bug and an ETA please?

**Comment by tonyafehr** [comment]
LCS bug # 3754049

**Comment by davecope1982** [comment]
is there any other way for us to import the pbix into our LCS asset library as it is quite urgent?

**Comment by tonyafehr** [comment]
This site hosts documentation, we're unable to handle Support requests for the product here. I suggest that you go here for [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support), or go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

**Comment by tonyafehr** [comment]
LCS has been updated and the changes you are looking for are now available.
