### ISSUE TITLE
Personalization Toolbar Image is not current

### ISSUE THREAD

**Issue by tomhig** [MicrosoftDocs/dynamics-365-unified-operations-public#1146]
Personalization Toolbar image is not current.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e113c5e-0085-f1ca-efab-21d65155d9fd
* Version Independent ID: f50b77f0-46f0-5924-68e4-ebd2b67566b4
* Content: [Personalize the user experience - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/personalize-user-experience#feedback)
* Content Source: [articles/fin-and-ops/get-started/personalize-user-experience.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/personalize-user-experience.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @TLeforMicrosoft
* Microsoft Alias: **tlefor**

**Comment by ShylaThompson** [comment]
@TLeforMicrosoft can we get an updated image in this topic?

**Comment by tonyafehr** [comment]
Bug 314835 has been logged to track this issue.

**Comment by jasongre** [comment]
Images have been updated and are waiting to be published.
