### ISSUE TITLE
url for flow

### ISSUE THREAD

**Issue by JbKarlsson** [MicrosoftDocs/dynamics-365-unified-operations-public#1147]
[Hi, You need to explain how to get the url to the flow that is mandatory when you configure the endpoint. Because as it is now it seems that the flow url that you take from the details page for the flow does not work.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f11c236-140a-b6dd-c5c6-533eb177b539
* Version Independent ID: f70529c9-5c5f-63ea-9979-4cb5423edc0a
* Content: [Business events in Microsoft Flow - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/business-events/business-events-flow)
* Content Source: [articles/dev-itpro/business-events/business-events-flow.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/business-events/business-events-flow.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by tonyafehr** [comment]
@JbKarlsson, thanks for the feedback.  
@Sunil-Garg, please consider updating this topic based on what's noted in this feedback.

**Comment by tonyafehr** [comment]
Bug 314837 has been logged to track this issue.

**Comment by Sunil-Garg** [comment]
Hi @JbKarlsson -- the Flow end point does not have to be configured from F&O. As a Flow maker, you can directly subscribe and unsubscribe to a business event from Flow itself using the trigger in F&O connector. When you do this, the end point will automatically get created. We have also added this clarification to the business events documentation. Hope this helps. Thanks.

**Comment by Henrik-Grender** [comment]
Unfortunately, this doesn't work for me, No port is created in F&O. Are there any other prerequisites? I am running Update 27 (10.0.0.3).
