### ISSUE TITLE
Leave without pay

### ISSUE THREAD

**Issue by mannesneuer** [MicrosoftDocs/dynamics-365-unified-operations-public#1149]
The instructions on this page are incorrect for Leave without pay where we want to still track  zero dollar earnings. Example: FMLA Leave. Steps:
1 - Set up FMLA Earning code, zero hourly pay, reduces FMLA.
2- Set up HR Leave type: FMLA, using Earning code: FMLA.
3- Set Worker Leave to start and end at given dates.
4 - Following instructions on this page, change worker Position to generate earnings from schedule, Default earning code: FMLA. Also toggle Generate salary to "No". Be sure to use "Manage changes" to assign this to the correct leave period.
4- Generate an Earning statement for a period the Worker is on leave. Observe that two FMLA earning lines have been created for each day.

Instead: For correct processing, do not Generate earnings from schedule. The FMLA leave setup from HR will create a single FMLA line per day.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8be68ed-96cd-6196-bca9-ce72f465bfc4
* Version Independent ID: f513acff-981b-e943-2b19-42b04d22ce08
* Content: [Set up work schedules and leave - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/hr/localizations/noam-usa-work-schedule-leave-tasks)
* Content Source: [articles/fin-and-ops/hr/localizations/noam-usa-work-schedule-leave-tasks.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/hr/localizations/noam-usa-work-schedule-leave-tasks.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @rschloma
* Microsoft Alias: **brpotter**

**Comment by sericks007** [comment]
@mannesneuer, thanks for making us aware of this!

@brpotter, please update the topic accordingly.

**Comment by sericks007** [comment]
@andreabichsel, please work with your team to address this issue. Thanks!

**Comment by sericks007** [comment]
Bug 315492 has been logged to track this issue.

**Comment by andreabichsel** [comment]
@mannesneuer I think this comment applies to a different page than the one mentioned here. Are you referring to this page: https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/hr/localizations/noam-usa-generate-earnings, or a different one? I want to make sure I'm making changes in the appropriate place. Thanks!

**Comment by mannesneuer** [comment]
My comments were originally made on this page since it mentions FMLA and Schedules. However, I believe the best place to document FMLA setup and integration with Payroll is on the https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/hr/localizations/noam-usa-track-time-for-fmla page. There, a note exists: "The Source column is always set to Manual. If you're using Finance and Operations and Payroll, the Source column can be updated automatically, based on the earning code that is used on the employee's pay statement." This note should also mention that there is a option required in the FMLA Case to allow Payroll to update. It is a toggle (Yes/No), named "To manually enter and maintain the hours worked, uncheck this box". When the option is set to "No", updates are done automatically from Payroll. Also note that the option label is misleading - one would think that the default is to have the updates from Payroll and that is not the case.

**Comment by andreabichsel** [comment]
Topics have been updated. Thank you!
