### ISSUE TITLE
Error while importing Tier 2 sandbox database bacpac file to cloud hosted environment

### ISSUE THREAD

**Issue by manishmoothedath** [MicrosoftDocs/dynamics-365-unified-operations-public#1150]
*** Error importing database:Could not import package.
Error SQL72014: .Net SqlClient Data Provider: Msg 208, Level 16, State 1, Procedure SYSSQLRESOURCESTATSVIEW, Line 1 Invalid object name 'sys.dm_db_resource_stats'.
Error SQL72045: Script execution error.  The executed script:
CREATE VIEW SYSSQLRESOURCESTATSVIEW
AS
SELECT 1010 AS RECID,
       end_time AS ENDTIME,
       avg_cpu_percent AS AVGCPUPERCENT,
       avg_data_io_percent AS AVGDATAIOPERCENT,
       avg_log_write_percent AS AVGLOGWRITEPERCENT,
       avg_memory_usage_percent AS AVGMEMUSAGEPERCENT,
       xtp_storage_percent AS XTPSTORAGEPERCENT,
       max_worker_percent AS MAXWORKERPERCENT,
       max_session_percent AS MAXSESSIONPERCENT,
       dtu_limit AS DTULIMIT
FROM   sys.dm_db_resource_stats;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28d0933f-ad59-1626-3e46-d766d9f4ef66
* Version Independent ID: 0b5603bc-86cb-84d7-90c8-ede61d98898f
* Content: [Export a copy of the standard user acceptance testing (UAT) database - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/dbmovement-scenario-exportuat)
* Content Source: [articles/dev-itpro/database/dbmovement-scenario-exportuat.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/database/dbmovement-scenario-exportuat.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @laneswenka
* Microsoft Alias: **laneswenka**

**Comment by sericks007** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
