### ISSUE TITLE
Make subpages

### ISSUE THREAD

**Issue by MichaelFruergaardPontoppidan** [MicrosoftDocs/dynamics-365-unified-operations-public#1151]
The TOC is quite hard to understand. It would improve if the ATL pages (Navigation concepts, … , Frequently asked questions) were made children of this page.
As it is right now, it appears as the FAQ is for "Testing support in VS" - which it is not.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e22191c2-edc9-fe49-3624-93bf958e4223
* Version Independent ID: d3082c96-b23e-358f-fb0d-8b160f3f7a31
* Content: [Acceptance test library - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-gb/dynamics365/unified-operations/dev-itpro/perf-test/acceptance-test-library)
* Content Source: [articles/dev-itpro/perf-test/acceptance-test-library.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/perf-test/acceptance-test-library.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @MichaelFruergaardPontoppidan
* Microsoft Alias: **MichaelFruergaardPontoppidan**

**Comment by sericks007** [comment]
@MichaelFruergaardPontoppidan, thanks for the feedback! We'll work to make this better.

**Comment by sericks007** [comment]
Bug 315229 has been logged to track this issue.

**Comment by kfend** [comment]
Thanks for bringing this to our attention.
The TOC has been updated.
