### ISSUE TITLE
.DimensionIntegration suffix required?

### ISSUE THREAD

**Issue by Costin-hcl** [MicrosoftDocs/dynamics-365-unified-operations-public#1152]
Hello,

It looks like when we extend the entity using the add-in, we need to keep the name = Data Entity Name + “.DimensionIntegration”. In our case: DimensionCombinationEntity.DimensionIntegration.
If we change the ending to something that follows normal naming convention (e.g. 3-letter project prefix or customer name), the values are not populated anymore.

Is this a bug or the intended behaviour?

Thanks,
Costin Boldisor

**Comment by sericks007** [comment]
@Costin-hcl, thank you for posting this! Could you please clarify which article this feedback applies to?

**Comment by Costin-hcl** [comment]
> @Costin-hcl, thank you for posting this! Could you please clarify which article this feedback applies to?

It's this one:  https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/financial/dimensions-overview

**Comment by sericks007** [comment]
@Costin-hcl, thank you!

**Comment by RobinARH** [comment]
Yes, you need to use DimensionCombinationEntity.DimensionIntegration. ‘DimensionIntegration’ is a reserved namespace to separate changes from the DimensionCombinationEntity and DimensionSetEntity from other customizations.

-Robin
