### ISSUE TITLE
inconsistent description about multiple prod instances under a same tenent

### ISSUE THREAD

**Issue by Izmiyash** [MicrosoftDocs/dynamics-365-unified-operations-public#1154]
[Enter feedback here]

Though I know the description in this page is quite correct, Licencing Guide linked from this page has inconsistent description. 

Licensing guide is saying "Dynamics 365 for Finance and Operations and Dynamics 365 for Retail both only support a single production instance per tenant."  
It's totally incorrect in reality and really misleading. must be corrected. 

Can you guys ask someone in charge to correct Licensing Guide?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b2eb6c9-f8e7-bb65-1fe1-566324528c4d
* Version Independent ID: d838536b-97b6-ff50-7086-44dff174146d
* Content: [Multiple LCS projects and production environments on one Azure AD tenant - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/implement-multiple-projects-aad-tenant)
* Content Source: [articles/fin-and-ops/get-started/implement-multiple-projects-aad-tenant.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/implement-multiple-projects-aad-tenant.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @ClaudiaBetz-Haubold
* Microsoft Alias: **chaubold**

**Comment by sericks007** [comment]
@Izmiyash, thank you for providing feedback!

@ClaudiaBetz-Haubold, please review and update the topic appropriately.

**Comment by sericks007** [comment]
@Izmiyash, I've reached out to a member of the Pricing & Licensing team, and she will review this and get clarify for the guide.

**Comment by sericks007** [comment]
I'm going to close this issue now, as another team will handle the update to the Licensing Guide.  But if you don't see changes relatively soon, feel free to re-open this issue. Thanks!
