### ISSUE TITLE
Workflow Export Fails

### ISSUE THREAD

**Issue by ELandAX** [MicrosoftDocs/dynamics-365-unified-operations-public#1155]
Hello,

I did not find a related page to this functionality so I post the workflow export issue here. I guess, you will delegate it to the right place and people.

The problem occurs when the workflow name exceeds 48 chars, workflow export fails. 
The max allowed workflow name size is 60.

The file name is constructed from workflow name, version number and .xml file extension. 
SysWorkflowConfigurationListPage::getExportFileName

The problem is in the following method:
Method SysWorkflowConfigurationListPage::exportConfiguration

The first parameter accept the file name and it's type is Name which is 60 chars long (!)
So the constructed file name gets truncated and results in a failure in workflow export.

The class and it's methods are internal and the only workaround is to use shorter workflow names.

I am working on 8.1 PU23.

More info I posted in the blogpost:
https://community.dynamics.com/ax/b/elandaxdynamicsaxupgradesanddevelopment/archive/2019/04/10/workflow-export-troubleshooting

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f81e3f61-e82e-66d0-9cbd-55b056ed982c
* Version Independent ID: 42b64249-9478-7715-491a-ce8d4d137132
* Content: [Workflow FAQ - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/organization-administration/workflow-faq)
* Content Source: [articles/fin-and-ops/organization-administration/workflow-FAQ.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/organization-administration/workflow-FAQ.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @ChrisGarty
* Microsoft Alias: **cgarty**

**Comment by sericks007** [comment]
@ELandAX, thank you for providing this feedback!

@ChrisGarty, please review and update the documentation appropriately.

**Comment by tonyafehr** [comment]
Bug 316473 has been logged to track this issue.

**Comment by ChrisGarty** [comment]
I've logged product bug 319991 to fix this. Thanks for letting us know @ELandAX!

**Comment by ELandAX** [comment]
Welcome, happy to help!
