### ISSUE TITLE
I don't see any ExportToExcelIGeneratedCustomExport interface

### ISSUE THREAD

**Issue by PalleAgermark** [MicrosoftDocs/dynamics-365-unified-operations-public#1156]
I don't think the ExportToExcelIGeneratedCustomExport interface is available in the application anymore. It seems to be replaced by OfficeIGeneratedWorkbookCustomExporter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8848c893-613d-1271-9f00-306fda77eae3
* Version Independent ID: 0c390ed8-b9a7-c636-4069-cc84551293d5
* Content: [Create Open in Excel experiences - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/office-integration/office-integration-edit-excel#how-can-an-entity-be-added-as-an-open-in-excel-option-on-a-form-that-doesnt-share-the-same-root-datasource)
* Content Source: [articles/dev-itpro/office-integration/office-integration-edit-excel.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/office-integration/office-integration-edit-excel.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @ChrisGarty
* Microsoft Alias: **cgarty**

**Comment by sericks007** [comment]
@PalleAgermark, thanks for posting this feedback!

@ChrisGarty, please review and update the topic appropriately.

**Comment by tonyafehr** [comment]
Duplicate
