### ISSUE TITLE
I don't see any ExportToExcelIGeneratedCustomExport interface

### ISSUE THREAD

**Issue by PalleAgermark** [MicrosoftDocs/dynamics-365-unified-operations-public#1157]
I don't think the ExportToExcelIGeneratedCustomExport interface is available in the application anymore. It seems to be replaced by OfficeIGeneratedWorkbookCustomExporter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f5fd999-8250-2c6f-1871-3d3d2b9a19f4
* Version Independent ID: dbec8e0d-6ad3-df5c-518b-005622b0e2f8
* Content: [Office integration concepts and features - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/office-integration/office-integration)
* Content Source: [articles/dev-itpro/office-integration/office-integration.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/office-integration/office-integration.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @ChrisGarty
* Microsoft Alias: **cgarty**

**Comment by sericks007** [comment]
@PalleAgermark, thanks for posting this feedback!

@ChrisGarty, please review and update the topic appropriately.

**Comment by tonyafehr** [comment]
Bug 316470 has been logged to track this issue.

**Comment by ChrisGarty** [comment]
You are quite right. I'll remove that content. People can refer to the [Customize the Open in Microsoft Office menu documentation](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/office-integration/customize-open-office-menu ) for information about OfficeIGeneratedWorkbookCustomExporter.
