### ISSUE TITLE
Process does not work for merged packages

### ISSUE THREAD

**Issue by FH-Inway** [MicrosoftDocs/dynamics-365-unified-operations-public#1159]
While trying to deploy a package that was merged from a 10.0 update package and a package with customizations, I got errors about modules not in the package that are on the environment where I'm trying to deploy the package. After adding the ModuleToRemove.txt file with the names from the error message to the customizations package and merging it again with the 10.0 update package, I tried to apply it to the environment again. This time, there was first the confirmation dialog about changing the environment to OneVersion, but after that, the same error occured. Seems there are several checks for missing modules and not all take the ModuleToRemove.txt file into account.
Also see https://www.yammer.com/dynamicsaxfeedbackprograms/threads/1196096707 for the same issue.
I suggest to add the information to this article that ModuleToRemove.txt cannot be used with merged packages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3565b319-747b-2aa4-36f0-6296adf930fb
* Version Independent ID: 847c2a77-9613-33ad-4455-bda3924b4286
* Content: [Uninstall a package - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/deployment/uninstall-deployable-package)
* Content Source: [articles/dev-itpro/deployment/uninstall-deployable-package.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/deployment/uninstall-deployable-package.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @Manado
* Microsoft Alias: **robadawy**

**Comment by sericks007** [comment]
@FH-Inway, thanks for making us aware of this.

@manalidongre or @robadawy, please review and update the topic as needed.

**Comment by tonyafehr** [comment]
Bug 316471 has been logged to track this issue.

**Comment by robadawy** [comment]
The process works with merged package. Any failure related to this should go through standard support.
