### ISSUE TITLE
Link to SSRS Technical Reference Report is Broken

### ISSUE THREAD

**Issue by tomhig** [MicrosoftDocs/dynamics-365-unified-operations-public#1164]
The link in To View The Report section of this article is broken. It is referencing a page on CustomerSource.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2ec1069-b2cd-2aff-6d1a-745b582f71d0
* Version Independent ID: 28414467-caf2-963b-a830-561240c70e89
* Content: [SQL Server Reporting Services (SSRS) reports that are available - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/ssrs-report#to-view-the-report)
* Content Source: [articles/dev-itpro/analytics/SSRS-report.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/SSRS-report.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @sericks007
* Microsoft Alias: **sericks**

**Comment by sericks007** [comment]
The SSRS technical reference report is available on CustomerSource, but it appears that CustomerSource is temporarily unavailable due to system maintenance.  Please check the link again soon, when CustomerSource is available again.
