### ISSUE TITLE
Upgrade 8.0 UAT environment to 10.0

### ISSUE THREAD

**Issue by burakuygur** [MicrosoftDocs/dynamics-365-unified-operations-public#1166]
Hello,

I am trying to upgrade my 8.0 Update 15 environment to 10.0 Update 24.
I already upgraded dev-build and a development environment to 10.0 and created single software deployable package which contains all developments and ISV solutions.
I merged this deployable package and Dynamics 365 for Finance and Operations version 10.0 package on asset library.
Now I am a bit confused because, when I try to upgrade my UAT environment from LC using Upgrade button, LCS says throws an error an says "An error occurred while retrieving upgrade topologies. If your environment is on version 8.1, you can update your environment by applying a package from your Update Tiles. If the issue persists, please contact support." 
After this error I try to apply merged package to UAT environment but it gives this error:"The environment 'yatamos-uat' is of Platform version: Update 15 - 7.0.4841.41248, Application version: 8.0 - 8.0.30.8022. The package and its solution is: 
(1) UATMerge_10.0 (Platform version: Update24 - 7.0.5179.35389, Application version: Unknown - Unknown). Error message: The Platform Release of the Package is not applicable to the Target Environment. Solution: Please ensure that the Package is from an older or same Platform release than the Target Environment"
Can you help me?

regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b3b5ec6-1a21-e71a-df38-ba497f7f1116
* Version Independent ID: d1e49823-7934-6a3a-50e1-547cdd632077
* Content: [Update environments from version 8.0 to 8.1.X or 10.X - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/appupdate-80-81#deploy-to-target-environments-for-validation)
* Content Source: [articles/dev-itpro/migration-upgrade/appupdate-80-81.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/migration-upgrade/appupdate-80-81.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by tonyafehr** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
