### ISSUE TITLE
Typos in Instructions

### ISSUE THREAD

**Issue by mitchgrnr** [MicrosoftDocs/dynamics-365-unified-operations-public#1167]
Hello, step three in both processes have a typo.  They should read as follows:
            Create an entity backed financial dimension:
3. In the use values from field, select a system-defined entity to base the financial dimension on. (currently says "User values from")
           Create a custom financial dimension
3. In the Use values from field, select &lt; Custom Dimension &gt;. (currently says "select .")

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50a99a9e-4b71-764e-a884-39ed452fe29d
* Version Independent ID: aa081487-d78c-ed93-4e6b-a75b259645ad
* Content: [Define financial dimensions - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/general-ledger/tasks/define-financial-dimensions#feedback)
* Content Source: [articles/financials/general-ledger/tasks/define-financial-dimensions.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/general-ledger/tasks/define-financial-dimensions.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @aprilolson
* Microsoft Alias: **aolson**

**Comment by tonyafehr** [comment]
@mitchgrnr , thanks for the feedback. I will update the topic and get it published this week.
