### ISSUE TITLE
Standard BP errors in Upgrade 8.1.3 and PU23 Development VM

### ISSUE THREAD

**Issue by VijayD365FO** [MicrosoftDocs/dynamics-365-unified-operations-public#1168]
I have deployed new Development VM 8.1.3 with PU23 for upgrade.After Full build i am getting 8 standard BP errors which are related to Retail Module.

Below is  one of the  BP error.

BP   Rule: [DataEntityFieldLabelPropertyCheck]:Path:   [dynamics://DataEntityView/RetailTerminalCustomFieldEntity/DataEntityViewMappedField/Type]:DataEntityFieldLabelPropertyCheck:   The field 'Type' has the same label '@RET5722' as the backing data source 'RetailTerminalCustomField'   field 'Type'.
--

All 8 Standard BP errors are same as above.

List of standard Entities Giving BP errors:
------------------------------------------------
1.RetailTerminalCustomFieldEntity
2.MCRUpSellCrossSellVariableEntity
3.RetailRoundingMethodEntity
4.RetailSalesPricePointGroupEntity

Please help me on this.

**Comment by tonyafehr** [comment]
@VijayD365FO, thanks for posting this. Could you please clarify which topic this feedback applies to?

**Comment by VijayD365FO** [comment]
Hi Tony,
Thanks for reply.
This topic applies to x++ code and Best practices rules check.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tonyafehr** [comment]
@pvillads, please review and update the documentation appropriately.
