### ISSUE TITLE
Trace menu item moved

### ISSUE THREAD

**Issue by kjgro** [MicrosoftDocs/dynamics-365-unified-operations-public#1169]
Trace menu item has moved to the "?" button in later releases 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe3185f9-a301-ca41-90c2-6a4715df55ca
* Version Independent ID: 0ec0e0ba-5839-806a-5471-dda4bc56996a
* Content: [Take traces by using Trace parser - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/perf-test/trace-trace-tutorial#feedback)
* Content Source: [articles/dev-itpro/perf-test/trace-trace-tutorial.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/perf-test/trace-trace-tutorial.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RobinARH
* Microsoft Alias: **chwolf**

**Comment by tonyafehr** [comment]
@kjgro, thanks for the feedback.  

@RobinARH, please review and update the documentation appropriately.

**Comment by RobinARH** [comment]
It is still under Settings. It takes a while for the Settings menu to load and appear, and it persists even if you hover over Help.

**Comment by prdpmv** [comment]
The screenshot of menu is still not corrected. https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/perf-test/trace-trace-tutorial

**Comment by RobinARH** [comment]
It matches what I have, except for the yellow highlighting we added to the screenshot. How is yours different? I don't plan to update the image. I would remove it instead, since the text is clear about what to do.

**Comment by prdpmv** [comment]
We are in 10.0.2
![image](https://user-images.githubusercontent.com/12284677/63474005-4fec4480-c42c-11e9-9cdf-7be5b5188e12.png)

Setting is like below but the docs says otherwise.

![image](https://user-images.githubusercontent.com/12284677/63474039-76aa7b00-c42c-11e9-985e-320ab69712af.png)

But I can see the trace here.
![image](https://user-images.githubusercontent.com/12284677/63474082-a8bbdd00-c42c-11e9-9ca1-fe8380a0ab40.png)

**Comment by RobinARH** [comment]
Thanks! I'm going to remove the image. The text is sufficient, and we can't maintain multiple views.

**Comment by prdpmv** [comment]
Text also says wrong. Its not there in settings. Its there under help,

**Comment by RobinARH** [comment]
I'll ask around and see what I find out.
