### ISSUE TITLE
Real-time refresh

### ISSUE THREAD

**Issue by davecope1982** [MicrosoftDocs/dynamics-365-unified-operations-public#1170]
Is there a roadmap timeframe for when the real-time refresh will be made available? With the previous version of entity store we had the ability to refresh as often as we liked, without this we now have reports that are not refreshing as often as required. Please advise

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e110aad1-fa4e-5fa0-ab1f-daae28097266
* Version Independent ID: c7aecc90-8e7c-ab0d-2cfe-94e9d09da1b0
* Content: [Automated Entity store refresh - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/automated-entity-store-refresh#feedback)
* Content Source: [articles/dev-itpro/analytics/automated-entity-store-refresh.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/automated-entity-store-refresh.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by tonyafehr** [comment]
@davecope1982, we appreciate your question, however we typically do not provide this kind of information in our help content. Please refer to the [Spring '19 Release Notes](https://docs.microsoft.com/en-us/business-applications-release-notes/April19/index) for latest release and roadmap information.
