### ISSUE TITLE
Commit for purchase and transfer orders

### ISSUE THREAD

**Issue by OksanaKovaliova** [MicrosoftDocs/dynamics-365-unified-operations-public#1175]
Hi, I was testing Purchase order receive and Transfer order operations yesterday (DEMO data, clear environment) - when I specified quantities and clicked Commit, D365 posted 'Product receipt' for purchase order; for transfer order - receiving document was posted.
Could you, please, check, if current article is still valid  - as it says about Ship now and Receive now quantities update only, that never happened in my testing. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14823d18-cf5f-6afb-4814-fa9e7fcea153
* Version Independent ID: 131f4c26-346d-7052-7f9c-7a733f2047db
* Content: [Store inventory management - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/work-with-store-inventory)
* Content Source: [articles/retail/work-with-store-inventory.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/work-with-store-inventory.md)
* Service: **dynamics-365-retail**
* GitHub Login: @rubencdelgado
* Microsoft Alias: **rubendel**

**Comment by tonyafehr** [comment]
@OksanaKovaliova, thanks for the feedback. 

@rubencdelgado, please review and update the documentation appropriately.

**Comment by rubencdelgado** [comment]
Previously, 'Ship now' and 'Receive now' quantities were updated and the related documents had to be posted as part of a separate process. This may have changed since I last owned this area. @hhainesms now owns the area and should confirm if current capabilities and if a change is needed to documentation.

**Comment by hhainesms** [comment]
The documentation is not accurate.  We will correct this.  When Transfer or Purchase Orders are "Committed" from POS, the receipt is posted immediately.  Receive now quantities entered in POS are used as receiving quantities in HQ as the receipt is posted.  The only area where we do not systematically post inventory processing in POS is the count journals.  Count journals are saved to HQ but require a secondary posting in HQ to finish the process.  Receipts do not require this.

**Comment by tonyafehr** [comment]
@OksanaKovaliova, extensive updates have been made to this topic, which will be published on Wednesday.
