### ISSUE TITLE
KB Article Issues

### ISSUE THREAD

**Issue by JoelLeichty** [MicrosoftDocs/dynamics-365-unified-operations-public#1176]
Inside the LCS KB article:
1. It says this is for preview customers.
2. It's unclear whether the article has been updated to include all issues included in the GA release.
3. It says "The What's New for Version 10.0 is Coming Soon"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 926b95da-8eaa-e23b-eeca-b334ea932e19
* Version Independent ID: 8f4901db-8cd1-74b3-0306-09b6295abd05
* Content: [What's new or changed in Finance and Operations version 10.0.1 (April 2019) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/whats-new-changed-10-0-1)
* Content Source: [articles/fin-and-ops/get-started/whats-new-changed-10-0-1.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/whats-new-changed-10-0-1.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @tonyafehr
* Microsoft Alias: **tfehr**

**Comment by tonyafehr** [comment]
@JoelLeichty, thanks for the feedback. You noted issues that are within LCS, not the article that's noted here, so I will forward your request for review. 

@manalidongre, can you review these questions and ensure that the LCS content is up to date. Thanks!

**Comment by JoelLeichty** [comment]
There’s no other place to provide feedback on KB articles, so I think feedback has to come through this medium?

Thanks,

Joel



Joel Leichty | SAGlobal

m +1 574.238.1393 | www.SAGlobal.com<http://www.saglobal.com/> | t @joelleichty<https://twitter.com/joelleichty>

**Comment by tiwarirajeev27** [comment]
1) Unsupported Database used for positiontorecord in v10 and v8.0 when having more than 45 lines in intercompany purchase order
2) Manual discount getting disappear and not calculating in Sales order lines of call center in v10
3) SalesPrice,ManualDiscount,itemid gets disappear and not calculating in v10

These are very basic things which should be tested..Now we are in middle -We upgraded sandbox and I think I have to rollback by deleting environment as now we cannot deploy our development also to production.

**Comment by JoelLeichty** [comment]
1. This comment is in reply to a thread.
2. This comment does not belong here. Product feedback needs to go through a Microsoft Support case.
