### ISSUE TITLE
This page is out of date

### ISSUE THREAD

**Issue by UnaFresa** [MicrosoftDocs/dynamics-365-unified-operations-public#1177]
The screens and steps for for "Set the contributor workflow" and "Enable the Azure connector and add an LCS user" have changed, if you updated this page it would probably result in fewer people having to contact Microsoft Support for help with these steps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b74fa4a-cee2-e0ef-a33c-af98a4ed5ed0
* Version Independent ID: 2416fc39-2965-94e6-b6b3-ac12132e8ec4
* Content: [Complete the Azure Resource Manager (ARM) onboarding process - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/deployment/arm-onboarding#feedback)
* Content Source: [articles/dev-itpro/deployment/arm-onboarding.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/deployment/arm-onboarding.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @sarvanisathish
* Microsoft Alias: **sarvanis**

**Comment by tonyafehr** [comment]
@UnaFresa, thanks for the feedback. 

@sarvanisathish or @manalidongre, please review and update the documentation appropriately.

**Comment by tonyafehr** [comment]
Bug 316477 has been logged to track this issue.
