### ISSUE TITLE
API to export raw logs

### ISSUE THREAD

**Issue by OksanaKovaliova** [MicrosoftDocs/dynamics-365-unified-operations-public#1178]
Hi, do you have any plans to provide API for LCS to trigger automatic raw log export on a scheduled basis? (or maybe you already have it and I just failed to find) 
The business case is: support team on Customer side is receiving Alerts in Service-App, when any error appears in a special channel (like AX-DataAccess) - and can quickly react (for example, if this looks like a bug in Extensions - send a ticket to developers). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c73b0eff-ab53-afb9-b3e2-40f94cb71a3e
* Version Independent ID: 069fa33b-6a69-2d29-908d-fca5ca0dc516
* Content: [Monitoring and diagnostics tools in Lifecycle Services (LCS) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/monitoring-diagnostics)
* Content Source: [articles/dev-itpro/lifecycle-services/monitoring-diagnostics.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/lifecycle-services/monitoring-diagnostics.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @manalidongre
* Microsoft Alias: **manado**

**Comment by tonyafehr** [comment]
@OksanaKovaliova, thank you for the feedback. You might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

@manalidongre,can you review and ensure that the content is up to date. Thanks!

**Comment by tonyafehr** [comment]
Bug 316478 has been logged to track this issue.

**Comment by manalidongre** [comment]
This is a feature request. Please submit you idea through the ideas portal - https://experience.dynamics.com/ideas/categories/list/?category=9abeac15-80ed-e611-8101-5065f38b21f1&forum=16691718-61e2-e611-8101-5065f38b21f1
