### ISSUE TITLE
Secured media server issue

### ISSUE THREAD

**Issue by biggibby** [MicrosoftDocs/dynamics-365-unified-operations-public#1179]
Hello,

If external content management system, content delivery network (CDN), or media server is password protected, how do I get past authentication?

Thank you,

Biggibby

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdd996af-4087-832d-1834-c069d8404d0a
* Version Independent ID: 7414efaf-e527-64c3-1be2-d2a28975f3dd
* Content: [Set up and manage images for Retail Modern POS (MPOS) - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/set-up-manage-images-retail-mpos#feedback)
* Content Source: [articles/retail/set-up-manage-images-retail-mpos.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/set-up-manage-images-retail-mpos.md)
* Service: **dynamics-365-retail**
* GitHub Login: @athinesh99
* Microsoft Alias: **athinesh**

**Comment by sericks007** [comment]
@biggibby, thanks for posting this! In the meantime, to get product help you can contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community. 

@athinesh99, please review and update the topic as necessary.

**Comment by sericks007** [comment]
@josaw1, just wanted to make you aware of this issue.

**Comment by sericks007** [comment]
Bug 316722 has been logged to track this issue.

**Comment by andreesteve** [comment]
@biggibby - can you share the specifics of your issue? CDNs usually provide content without need for authentication. The Retail Media Server is not password protected.

**Comment by nazimi-msft** [comment]
If the media endpoint is protected, then you need to manipulate the URLs being returned by Retail Server to include the necessary authentication token as part of the endpoint URL. This would be an extension to the existing GetMediaLocations() API.
