### ISSUE TITLE
Remove reference to Web-App purchase for Attract

### ISSUE THREAD

**Issue by karleesm** [MicrosoftDocs/dynamics-365-unified-operations-public#1181]
Hi team - we need to update the following statement given the recent changes to web app purchases.

"This functionality can also be purchased as standalone modular applications through web-direct. Examples include Microsoft Dynamics 365 for Talent: Attract and Microsoft Dynamics 365 for Talent: Onboard SKUs. Depending on whether you purchase full Talent or the modular applications, the experience differs somewhat."

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43e145b6-a02f-49e3-3fc0-7d80a0e85303
* Version Independent ID: e4652c2f-8125-d6a2-f288-f172c7e629f6
* Content: [Provisioning for the Dynamics 365 for Talent modular apps - Talent | Dynamics 365](https://docs.microsoft.com/en-au/dynamics365/unified-operations/talent/modular-app-tech-faq)
* Content Source: [articles/talent/modular-app-tech-faq.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/talent/modular-app-tech-faq.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @andreabichsel
* Microsoft Alias: **anbichse**

**Comment by andreabichsel** [comment]
Thank you for pointing this out! I'm working on the changes now and will publish after I get sign off from the product team.

**Comment by andreabichsel** [comment]
Changes are live. Thanks!
