### ISSUE TITLE
Sandbox step not mentioned

### ISSUE THREAD

**Issue by amerms** [MicrosoftDocs/dynamics-365-unified-operations-public#1182]
I cannot see sandbox step in this procedure. Does it means we have to upgrade VHD and then directly production environment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97072d18-e50b-c4c4-bfda-51150c66f45f
* Version Independent ID: 9cd5e72f-b2cd-81aa-4be0-7e4e02c17d78
* Content: [In-place upgrade process for on-premises environments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/on-prem-upgrade#feedback)
* Content Source: [articles/dev-itpro/migration-upgrade/on-prem-upgrade.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/migration-upgrade/on-prem-upgrade.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by sericks007** [comment]
@amerms, thanks for posting this! In the meantime, to get product help you can contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community. 

@laneswenka, please review and update the topic as needed.

**Comment by sericks007** [comment]
Bug 316726 has been logged to track this issue.

**Comment by ansartroops** [comment]
I don't see the procedure for On-premises upgrade from version 7.x (with Platform update 11 or earlier) to 8.1

**Comment by sericks007** [comment]
This topic was updated, so closing this issue.
