### ISSUE TITLE
Any Updates for Create Custom Help doc to reflect Azure changes in last 6 months?

### ISSUE THREAD

**Issue by pbonny1** [MicrosoftDocs/dynamics-365-unified-operations-public#1184]
The document "Create Custom Help for Microsoft Dynamics 365 for Finance and Operations" has been most helpful, but many of the Azure options/screens/selections have changed since the doc was written. 
Is and update likely in the not too distant future?
Cheers

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55d63462-2df6-7954-d80c-e9211718f3a8
* Version Independent ID: f345be27-924a-d0c1-b0f4-3c2d78849ede
* Content: [Connect a custom help site to Dynamics 365 for Finance and Operations - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-gb/dynamics365/unified-operations/fin-and-ops/get-started/help-custom)
* Content Source: [articles/fin-and-ops/get-started/help-custom.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/help-custom.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @MargoC
* Microsoft Alias: **margoc**

**Comment by josaw1** [comment]
@pbonny1, thank you for posting this!

@jasongre, can you please review and update the topic as needed?

**Comment by sericks007** [comment]
Bug 316729 has been logged to track this issue.
