### ISSUE TITLE
Public Preview for existing customers appears to be down

### ISSUE THREAD

**Issue by AlexHimself** [MicrosoftDocs/dynamics-365-unified-operations-public#1185]
The link for "Public Preview for existing customers" appears to be down.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42cc8126-b6d5-92ad-f53d-5985daf726b0
* Version Independent ID: 103b81f2-3fa7-5509-aab7-c6ca23a55ff9
* Content: [Get evaluation copies - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-tools/get-evaluation-copy#feedback)
* Content Source: [articles/dev-itpro/dev-tools/get-evaluation-copy.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-tools/get-evaluation-copy.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RobinARH
* Microsoft Alias: **robadawy**

**Comment by josaw1** [comment]
@AlexHimself, thank you for your post. 

@RobinARH can you please update the link in the topic?

**Comment by tonyafehr** [comment]
Bug 318220 has been logged to track this issue.
