### ISSUE TITLE
Automated way to Create new products

### ISSUE THREAD

**Issue by rdovgalyuk** [MicrosoftDocs/dynamics-365-unified-operations-public#1186]
How to create new products (massive) in an automated way?
-Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 266cd03a-2ad8-62b0-d73c-169984c7e7d6
* Version Independent ID: fbbc344f-f814-a97a-27ef-49063f0fa8ef
* Content: [Create a new product - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/pim/tasks/create-new-product#feedback)
* Content Source: [articles/supply-chain/pim/tasks/create-new-product.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/pim/tasks/create-new-product.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @ShylaThompson
* Microsoft Alias: **shylaw**

**Comment by josaw1** [comment]
@rdovgalyuk thanks for posting this! In the meantime, to get product help you can contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

@sorenva can you please review and update the topic as needed?

**Comment by rdovgalyuk** [comment]
@josaw1 thanks for your quick response!

**Comment by tonyafehr** [comment]
Bug 318219 has been logged to track this issue.

**Comment by sorenva** [comment]
You can use the **Released product creation V2** data entity to import/create new product in an automated manner through Data Management. This data entity mimics the behavior of the **New released product** dialog on the **Released products** page.
