### ISSUE TITLE
Ledger Integration

### ISSUE THREAD

**Issue by Chrisslima** [MicrosoftDocs/dynamics-365-unified-operations-public#1187]
Please, where I could find the content about "Ledger Integration"? It looks like it's missing. 

Is there some documentation about inventory posting configuration for D365FO like as the "Appendix A: Postings based on recommended settings" in the document "Cost Management in Microsoft Dynamics AX 2009"? (https://www.microsoft.com/en-us/download/confirmation.aspx?id=1041)

Tks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f223e1d2-3d7a-592a-a404-6cfe30fecbbf
* Version Independent ID: 63478ba4-0e82-63ce-3d80-a7ec5d39e84b
* Content: [Cost management home page - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/cost-management/cost-management-home-page#feedback)
* Content Source: [articles/supply-chain/cost-management/cost-management-home-page.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/cost-management/cost-management-home-page.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @AndersGirke
* Microsoft Alias: **aevengir**

**Comment by josaw1** [comment]
@Chrisslima thank you for posting this. 

@AndersGirke can you please review the comment and provide assistance as needed?

**Comment by tonyafehr** [comment]
Bug 318221 has been logged to track this issue.
