### ISSUE TITLE
Did not work with version 8.0 Tier 2 sandbox

### ISSUE THREAD

**Issue by JoniLoponen** [MicrosoftDocs/dynamics-365-unified-operations-public#1189]
Packages were uninstalled only on one of the AOS servers. The packages stayed on the other server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3565b319-747b-2aa4-36f0-6296adf930fb
* Version Independent ID: 847c2a77-9613-33ad-4455-bda3924b4286
* Content: [Uninstall a package - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/deployment/uninstall-deployable-package#feedback)
* Content Source: [articles/dev-itpro/deployment/uninstall-deployable-package.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/deployment/uninstall-deployable-package.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @Manado
* Microsoft Alias: **robadawy**

**Comment by josaw1** [comment]
@JoniLoponen thanks for posting this! To get product help you can contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
