### ISSUE TITLE
How do we merge the packages?

### ISSUE THREAD

**Issue by computerwizjared** [MicrosoftDocs/dynamics-365-unified-operations-public#1190]
When I do the steps in this article and then try to compile both the Retail SDK and the Finance and Operations packages, it will output 3 files: AXDeployableRuntime, AXModelSource, and RetailDeployablePackage. How do we merge the AXDeployableRuntime and RetailDeployablePackage package zips so that we can deploy a single package to our production environment?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2aa11b3-17d0-a8b6-2503-8796121d04bf
* Version Independent ID: 5ae5fddb-2c0a-a5e7-8b57-a39f5670a254
* Content: [Merge the build systems for Retail and Finance and Operations - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/dev-itpro/retail-sdk/integrate-retail-sdk-continuous-build#add-a-copy-step-for-all-retail-packages)
* Content Source: [articles/retail/dev-itpro/retail-sdk/integrate-retail-sdk-continuous-build.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/dev-itpro/retail-sdk/integrate-retail-sdk-continuous-build.md)
* Service: **dynamics-365-retail**
* GitHub Login: @andreash1
* Microsoft Alias: **andreash**

**Comment by josaw1** [comment]
@computerwizjared thanks for posting this! To get product help you can contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

@mugunthanm can you please take a look at the comment?

**Comment by computerwizjared** [comment]
Hi @josaw1 thanks for your reply. I tried opening a support ticket from LCS however they directed me to the partner portal to raise an "advisory ticket". I am a customer and don't have access to the partner portal to do so, so I thought I'd comment here since it should be part of the documentation here. Thanks!

**Comment by tonyafehr** [comment]
Bug 318223 has been logged to track this issue.

**Comment by mugunthanm** [comment]
We have option in LCS to merge packages, check the below link:

https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/deployment/apply-deployable-package-system

https://community.dynamics.com/365/financeandoperations/b/howtodynamics365/archive/2018/07/09/how-to-merge-multiple-packages-in-lcs-for-dynamics-365

**Comment by computerwizjared** [comment]
@mugunthanm Our FastTrack specialist told us we should merge the packages in the Azure DevOps pipeline rather than using the LCS merge function, as that was used for older versions of Dynamics, however never followed up with us about implementing the package merge. We are past implementation at this point but it would still be helpful to have a single package built through DevOps for future builds. Is this possible?

**Comment by gammelgaard52** [comment]
Any update on @computerwizjared comment? Setting with it right now and that would be nice with some feedback. @josaw1

**Comment by gammelgaard52** [comment]
Returning question, is it still not possible?

**Comment by tonyafehr** [comment]
@mugunthanm, please review.

**Comment by mugunthanm** [comment]
Unfortunately it will not be one package because the packages goes to different systems. D365 package goes to D365 F & O env and Retail deployable package goes to RCSU and the deployment flow is different for D365 F & O and Retail.
