### ISSUE TITLE
Error trying to schedule PowerApps Data Integration project - prospect to cash

### ISSUE THREAD

**Issue by gprodware** [MicrosoftDocs/dynamics-365-unified-operations-public#1191]
Hi,
I am getting an error message when trying to schedule a data integration project on PowerApp Admin center :
Exception occured for PUT request https://management.azure.com/subscriptions/6989f3ba-b425-45dc-affb-047d53242a54/resourceGroups/d365-prod-integ-weu/providers/Microsoft.Scheduler/jobCollections/bbfde416-ad70-4316-81eb-73b70da0b6cd/jobs/28457997-47aa-4729-9db1-e98042e4a70b-Project_Accounts_Customers?api-version=2016-03-01 - {"error":{"code":"BadRequest","message":"Job definition state 'Completed' cannot be set for job."}} Session id: 5d49dfa8-4a22-4569-a5fd-d95d61fe4d0a

Thanks,

Gill

**Comment by RobinARH** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
