### ISSUE TITLE
PDF not downloading

### ISSUE THREAD

**Issue by omerahm** [MicrosoftDocs/dynamics-365-unified-operations-public#1192]
I am unable to download the PDF getting error failed to load the pdf and the link on the browser is https://opdhsblobprod03.blob.core.windows.net/contents/3217822f545149bc956510410f5a4ad3/d98c1dd4008f04b2e9800998ecf8427e?sv=2015-04-05&sr=b&sig=Tt1a1sR55GYQMIg1DSkyTyzsB3JiZbnNwOQknGsBX68%3D&st=2019-04-22T11%3A31%3A00Z&se=2019-04-23T11%3A41%3A00Z&sp=r

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 784a9997-47ed-b2d1-980a-b453138e16ad
* Version Independent ID: d57cdbe6-a216-41ec-80bf-01a0292587a8
* Content: [Microsoft Dynamics 365 for Finance and Operations documentation - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/#feedback)
* Content Source: [articles/fin-and-ops/index.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/index.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @MargoC
* Microsoft Alias: **margoc**

**Comment by RobinARH** [comment]
Thanks for letting us know. We are investigating this issue.

**Comment by RobinARH** [comment]
We fixed the link. - Robin
