### ISSUE TITLE
Deprecated

### ISSUE THREAD

**Issue by shirdesai** [MicrosoftDocs/dynamics-365-unified-operations-public#1193]
This functionality can no longer be used after platform update 24 due to version control feature being enabled to track documents stored on Sharepoint. Is there any alternative for this ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91d63cbc-bcb7-c1e5-05b3-6485ec194d43
* Version Independent ID: e7ac3f29-a58d-6c1c-6c5c-fa9cc8c69e6e
* Content: [Configure Electronic reporting (ER) to pull data into Power BI - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/general-electronic-reporting-report-configuration-get-data-powerbi#feedback)
* Content Source: [articles/dev-itpro/analytics/general-electronic-reporting-report-configuration-get-data-powerbi.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/general-electronic-reporting-report-configuration-get-data-powerbi.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @NickSelin
* Microsoft Alias: **nselin**

**Comment by RobinARH** [comment]
@NickSelin

Hi Nickolay - Can you take a look at this? thanks - Robin

**Comment by NickSelin** [comment]
This functionality can be used after platform update 24 - it works for me on the platform update 26 (preview).
