### ISSUE TITLE
Dynamics 365 on premises Management Reporter 

### ISSUE THREAD

**Issue by ahmerkhalid636** [MicrosoftDocs/dynamics-365-unified-operations-public#1194]
Dear Experts,

I had used Dynamics 365 7.3 **(on premises)**, the services was working fine. Now the after upgradation of Dynamics 365 10.0 Updated 24, the MR cant login and showing the below error.

An error occured while processing the request. {E5768EA0-3FBC-4EEC-8124-FB39CED600BD}

Any suggestion in this regards

Thanks 
Ahmer Khalid

**Comment by RobinARH** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
