### ISSUE TITLE
example has incorrect amount

### ISSUE THREAD

**Issue by B-rade** [MicrosoftDocs/dynamics-365-unified-operations-public#1195]
In example 2, in the table "Payment is received and posted in Fabrikam for Fabrikam customer 4000", the payment amount is incorrect. 
The payment to Fabrikam should be 580.00, not 600.00. Otherwise Fabrikam would have 20 extra dollars in their cash and accounts receivable accounts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 013607d1-0d01-d6f4-a014-ce8a1a433968
* Version Independent ID: ea111036-d41f-a99a-adc3-0c2b3013b74a
* Content: [Centralized payments for Accounts receivable - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/accounts-receivable/centralized-payments-accounts-receivable#feedback)
* Content Source: [articles/financials/accounts-receivable/centralized-payments-accounts-receivable.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/accounts-receivable/centralized-payments-accounts-receivable.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @ShivamPandey-msft
* Microsoft Alias: **shpandey**

**Comment by RobinARH** [comment]
@ShivamPandeyMSFT
Hi Shivam - Can you take a look? thanks - Robin

**Comment by tonyafehr** [comment]
Bug 318225 has been logged to track this issue.

**Comment by panolte** [comment]
Thank you for reporting.  The document will be updated.
