### ISSUE TITLE
Back to Basics

### ISSUE THREAD

**Issue by tbarron2** [MicrosoftDocs/dynamics-365-unified-operations-public#1198]
Suggestion: In the opening summary, define clearly the difference between Test Plan, Test Suite, and Test Case.  Each of the following subsections jump right in to functionality with many assumptions that the reader knows the difference before starting.    By the end of the document, the reader can likely put the pieces together -- but if those terms were defined up front, it might make the remaining content more digestible.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18d6a0b7-38dc-ddcd-c495-67e3b7498a7c
* Version Independent ID: 36a6bc94-6939-9daf-ad3d-4e0064258172
* Content: [Create and automate user acceptance tests - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/using-task-guides-and-bpm-to-create-user-acceptance-tests)
* Content Source: [articles/dev-itpro/lifecycle-services/using-task-guides-and-bpm-to-create-user-acceptance-tests.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/lifecycle-services/using-task-guides-and-bpm-to-create-user-acceptance-tests.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @kfend
* Microsoft Alias: **ntecklu**

**Comment by tonyafehr** [comment]
@tbarron2, thank you for the great feedback. 

@robadawy, please review and update the topic (or topic owner) as needed.

**Comment by tonyafehr** [comment]
Bug 318226 has been logged to track this issue.

**Comment by RobinARH** [comment]
I added a link to the topic that explains the differences between test plans, suites, and tests in Azure DevOps. It should go live this evening. -Robin
