### ISSUE TITLE
Restrict payment methods for returns without a receipt

### ISSUE THREAD

**Issue by Dictator365** [MicrosoftDocs/dynamics-365-unified-operations-public#1199]
Hi All
Restrict payment methods for returns without a receipt - This feature is not found in all versions. I'm using Update21 (7.0.5073.41326). I don't see this Non-receipt returns, set Restrict for refunds without a receipt to Yes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fc75e31-3c3d-434c-1dea-169682d35738
* Version Independent ID: 6c27ec45-9753-7e29-af76-450b5932520c
* Content: [Restrict payment methods for returns without a receipt - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/payment-methods-restrictions#feedback)
* Content Source: [articles/retail/payment-methods-restrictions.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/payment-methods-restrictions.md)
* Service: **dynamics-365-retail**
* GitHub Login: @rapraj
* Microsoft Alias: **yabinl**

**Comment by sericks007** [comment]
@Dictator365, thanks for posting this!

@rapraj, please review and update the topic, as necessary.

**Comment by tonyafehr** [comment]
Bug 318227 has been logged to track this issue.

**Comment by rapraj** [comment]
This feature was released in Apr 2019 in 10.0.1 release of Dynamics 365 for Finance and Operations & Dynamics 365 for Retail. See release notes of Apr 2019.

**Comment by rapraj** [comment]
https://docs.microsoft.com/en-us/business-applications-release-notes/October18/dynamics365-retail/returns-without-receipt 

Stand corrected - it was published in Oct '18 release notes for features to be released between Oct 18 - Mar 19. 

This feature is only available for 10.0.1 release and later.
