### ISSUE TITLE
Bug: Article "copy-database-from-azure-sql-to-sql-server.md" has a bug in the SQL

### ISSUE THREAD

**Issue by JohnLBevan** [MicrosoftDocs/dynamics-365-unified-operations-public#120]
This article includes SQL which can be run when copying a staging environment.  This SQL includes the following:

```
declare userCursor CURSOR for
select 'DROP USER ' + name
from sys.sysusers
where issqlrole = 0 and hasdbaccess = 1 and name <> 'dbo'
```

However, we had a number of user with names formatted `WDDB-########-####-####-####-####-############` (i.e. WDDB followed by a GUID).  The hyphens in these usernames caused the command to fail.  This can be resolved by escaping the usernames in the dynamic SQL; i.e.

```
declare userCursor CURSOR for
select 'DROP USER ' + quotename(name)
from sys.sysusers
where issqlrole = 0 and hasdbaccess = 1 and name <> 'dbo'
```

Link to file: https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/blob/live/articles/dev-itpro/database/copy-database-from-azure-sql-to-sql-server.md
Link to article: https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/copy-database-from-azure-sql-to-sql-server

**Comment by JohnLBevan** [comment]
ps. to also incorporate the FullText Catalog issue:

```
declare @userSQL varchar(max)
, @user varchar(1000)

set quoted_identifier off

declare userCursor CURSOR for
select name
from sys.sysusers
where issqlrole = 0 and hasdbaccess = 1 and name <> 'dbo'

OPEN userCursor
FETCH userCursor into @user 
WHILE @@Fetch_Status = 0
BEGIN
	set @userSql = ''
	--remove any full text indexes
	select @userSql += 'ALTER AUTHORIZATION ON Fulltext Catalog::' + quotename(name) +' TO [dbo];' + char(10) 
	From sys.fulltext_catalogs 
	where principal_id = user_id(@user)

	--then remove the user
	select @userSql += 'drop user ' + quotename(@user)

	--execute dynamic sql then progress to the next user
	print @userSql
	exec(@userSQL)
	FETCH userCursor into @user 
END
CLOSE userCursor
DEALLOCATE userCursor
```

**Comment by MargoC** [comment]
Thanks John, we're just starting to use GitHub issues for article feedback. I've assigned this to the owner of the article to review.

**Comment by MargoC** [comment]
John, we've updated the article. Please take a look.
