### ISSUE TITLE
Typing error

### ISSUE THREAD

**Issue by mannesneuer** [MicrosoftDocs/dynamics-365-unified-operations-public#1200]
Section B. Create earnings statement for an employee to have a beginning balance
2. In the Earnings statement line tab, enter the following:
Line 1: Earning statement line tab
"Rage" should be replaced with "Rate"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c989259c-4c2a-98c3-8903-cbbcde51ecec
* Version Independent ID: d13f126d-b279-c9eb-7492-fa8c42f48c31
* Content: [Enter payroll beginning balances - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/hr/localizations/noam-usa-enter-beginning-balances)
* Content Source: [articles/fin-and-ops/hr/localizations/noam-usa-enter-beginning-balances.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/hr/localizations/noam-usa-enter-beginning-balances.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @kherr75
* Microsoft Alias: **kherr**

**Comment by sericks007** [comment]
@mannesneuer, thank you for bringing this to our attention! I've fixed the typo. The updated topic will be published later today or tomorrow. Thanks again!
