### ISSUE TITLE
Missing Link to Microsoft Dynamics 365 for Finance and Operations - operated by 21Vianet in China

### ISSUE THREAD

**Issue by Izmiyash** [MicrosoftDocs/dynamics-365-unified-operations-public#1204]
[Enter feedback here]
The link to "Microsoft Dynamics 365 for Finance and Operations - operated by 21Vianet in China" is not correct. Please avoid making us to see 404 error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05359761-bd4b-2841-db9a-5bcc11359430
* Version Independent ID: 86a4d7d2-9ce9-b0dc-0300-67c3e1e5b74a
* Content: [Globalization - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lcs-solutions/country-region?toc=/fin-and-ops/toc.json)
* Content Source: [articles/dev-itpro/lcs-solutions/country-region.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/lcs-solutions/country-region.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @ShylaThompson
* Microsoft Alias: **shylaw**

**Comment by tonyafehr** [comment]
@Izmiyash, thanks for the feedback. I've fixed the link and it'll be updated later today. 

In the meantime, here's a direct link: https://docs.microsoft.com/dynamics365/unified-operations/dev-itpro/deployment/china-local-deployment
