### ISSUE TITLE
D365 Finance and operation on premises Integration middle wares

### ISSUE THREAD

**Issue by MadhanRamachandran** [MicrosoftDocs/dynamics-365-unified-operations-public#1205]
[Enter feedback here]
Hi,

We need to know supported middle wares application for the D365 Finance and operation on premises Integration wit third party and MS products.

Also provide the more details on the middle wares uses and architecture diagram.

Thanks, 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2535f3a8-a225-3925-fea4-b22769ef90d0
* Version Independent ID: 99dbbaab-c4e6-925b-0fb9-e444af567aa6
* Content: [Recurring integrations - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/recurring-integrations)
* Content Source: [articles/dev-itpro/data-entities/recurring-integrations.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/recurring-integrations.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by Sunil-Garg** [comment]
Hi Madhan-- Finance and Operations provides integration capabilities which are generic enough to work with middleware platforms. Whether it is cloud or on-premise, these capabilities are expected to work. We do not promote one middleware over another. However, if you are seeing issues with a certain middleware platform to integrate with Finance and Operations, then pls do let us know and we will be happy to assist.

Thank You.
