### ISSUE TITLE
Somewhat outdated topic

### ISSUE THREAD

**Issue by MichaelFruergaardPontoppidan** [MicrosoftDocs/dynamics-365-unified-operations-public#1209]
"The application stack has been divided into three separate models: Application Platform, Application Foundation, and Application Suite. "  Application Suite has since been separated into 20+ models.
Also there are references to "Rainier"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44045a16-e5bc-365a-45a3-5ddbc61f018b
* Version Independent ID: 85872ae7-e67e-6932-aaca-b9bcf9df3a86
* Content: [Application stack and server architecture - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-tools/application-stack-server-architecture#feedback)
* Content Source: [articles/dev-itpro/dev-tools/application-stack-server-architecture.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-tools/application-stack-server-architecture.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @kfend
* Microsoft Alias: **meeram**

**Comment by RobinARH** [comment]
Thanks for letting us know. We are working on updating the topic. - Robin

**Comment by RobinARH** [comment]
We published an update to the topic.
