### ISSUE TITLE
F365 FO Localization - International Availability Guide

### ISSUE THREAD

**Issue by craigfraser9** [MicrosoftDocs/dynamics-365-unified-operations-public#1212]
Can anyone advise the implications for Countries which do not feature in the Availability section. I have a requirement to set up a Legal Entity for Cambodia however it does not feature in the "Availability" section of the International Availability guide. Can D365 FO still be deployed in Cambodia and if so what does the lack of mention in the "Availability" section imply?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05359761-bd4b-2841-db9a-5bcc11359430
* Version Independent ID: 86a4d7d2-9ce9-b0dc-0300-67c3e1e5b74a
* Content: [Globalization - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lcs-solutions/country-region#feedback)
* Content Source: [articles/dev-itpro/lcs-solutions/country-region.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/lcs-solutions/country-region.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @ShylaThompson
* Microsoft Alias: **shylaw**

**Comment by RobinARH** [comment]
@sshvedov 
Hi Sergey - Can you take a look at this one? thanks - Robin

**Comment by RobinARH** [comment]
Bug 319616 has been logged to track this issue.

**Comment by craigfraser9** [comment]
Hi - Have you had a chance to give any thought to the localization query? Thanks, Craig
