### ISSUE TITLE
Elaborate on setup / architecture / process flows / best practices

### ISSUE THREAD

**Issue by ransoentjens** [MicrosoftDocs/dynamics-365-unified-operations-public#1215]
There is a general lack of documentation related to this specific task. Listing the current topic as a task here is correct, but there is no context.

What is required is a section below the statement posting section that explains the architecture and process flow of e-commerce orders. Using a flowchart it should be indicated what the best practice of importing e-commerce orders and then processing them in D365 is. 

- This should include integration nuances such as (dis)advantages of doing it the prescribed way
- This should include entities that should be taken into consideration
- This should include timing advice given the sensitivity of the business process
- This should include configuration options and their impact

In summary, I'm really looking for something on par with the statement posting process that is described.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98539819-c05d-c918-d0f6-23d4984d4383
* Version Independent ID: 2b5c0054-7aef-6104-4c7f-eb1513933216
* Content: [Posting of online sales and payments - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/tasks/posting-online-sales-payments)
* Content Source: [articles/retail/tasks/posting-online-sales-payments.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/tasks/posting-online-sales-payments.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @jashanno
* Microsoft Alias: **jashanno**

**Comment by tonyafehr** [comment]
@ransoentjens, thanks for the great feedback. 
@jashanno, please review this feedback and consider making updates to this topic.

**Comment by tonyafehr** [comment]
Bug 319951 has been logged to track this issue.

**Comment by tonyafehr** [comment]
Updates to this topic will be posted today.
