### ISSUE TITLE
Section "VM that is running on-premises" steps are outdated

### ISSUE THREAD

**Issue by bhesingh** [MicrosoftDocs/dynamics-365-unified-operations-public#1217]
The section "VM that is running on-premises" talks about downloading the VHD's from LCS. This process has changed long back. So, the documentation needs to be updated accordingly.

Thanks & Regards
Bheem Singh

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae28fb1e-25a4-72cd-6694-322bec60769e
* Version Independent ID: 461c7a2b-ce3f-4083-af9d-07093dbed387
* Content: [Deploy and access development environments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-tools/access-instances#vm-that-is-running-on-premises)
* Content Source: [articles/dev-itpro/dev-tools/access-instances.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-tools/access-instances.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @robadawy
* Microsoft Alias: **robadawy**

**Comment by tonyafehr** [comment]
@bhesingh, thanks for the feedback. 
@robadawy, please review this feedback and consider making updates to this topic.

**Comment by tonyafehr** [comment]
Bug 319956 has been logged to track this issue.

**Comment by jorisdg** [comment]
I'm not sure if the document was updated since this issue was filed, but the doc looks correct to me. Can you please elaborate what is missing or wrong?
