### ISSUE TITLE
On-premises upgrade from version 7.x (with Platform update 11 or earlier) to 8.1

### ISSUE THREAD

**Issue by ansartroops** [MicrosoftDocs/dynamics-365-unified-operations-public#1218]
I don't see the procedure for On-premises upgrade from version 7.x (with Platform update 11 or earlier) to 8.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97072d18-e50b-c4c4-bfda-51150c66f45f
* Version Independent ID: 9cd5e72f-b2cd-81aa-4be0-7e4e02c17d78
* Content: [In-place upgrade process for on-premises environments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/on-prem-upgrade)
* Content Source: [articles/dev-itpro/migration-upgrade/on-prem-upgrade.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/migration-upgrade/on-prem-upgrade.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by tonyafehr** [comment]
@ansartroops, thanks for the feedback. 
@laneswenka , please review this feedback and consider making updates to this topic.

**Comment by tonyafehr** [comment]
Bug 319957 has been logged to track this issue.

**Comment by sericks007** [comment]
This topic has been updated.
