### ISSUE TITLE
Entity Store Export to Data Lake Gen2 and Consumption via Power BI

### ISSUE THREAD

**Issue by jharbering** [MicrosoftDocs/dynamics-365-unified-operations-public#1219]
Hi everyone, we are having issues getting the entity store -> data lake gen2 -> power bi option to work. The core issue, in my opinion, is that when exporting data from D365FO to the data lake gen2 the data lake must not have the hierarchical namespace enabled. But when connecting the power bi with the data lake gen2 (with dataflows) it needs to have the hierarchical namespace enabled. Any ideas on how to resolve this?

Best, Jonas

**Comment by tonyafehr** [comment]
@jharbering, thanks for posting this! Your comment is not directed toward a specific topic, which is the intent of this feedback site. This is not a support site. To get product help you can contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
