### ISSUE TITLE
Vendor type person vs. organization

### ISSUE THREAD

**Issue by maveloso** [MicrosoftDocs/dynamics-365-unified-operations-public#1227]
it is not clear from this documentation weather the 1099 functionality works the same for vendors of type person and organization. can you clarify if 1099 processing is available for vendors of type organization?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 222d0832-bb4c-31f2-a203-0b2a0826f90c
* Version Independent ID: e32f8cb0-a4e5-9666-b6f7-f528360cf406
* Content: [Year-end 1099 reporting - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/localizations/noam-usa-year-end-1099-reporting#feedback)
* Content Source: [articles/financials/localizations/noam-usa-year-end-1099-reporting.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/localizations/noam-usa-year-end-1099-reporting.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @abruer
* Microsoft Alias: **abruer**

**Comment by josaw1** [comment]
Thank you for the comment. @abruer, can you please help with this question?

**Comment by tonyafehr** [comment]
Bug 320705 has been logged to track this issue.

**Comment by abruer** [comment]
The 1099 functionality is available for vendors of type Organization and Person.
