### ISSUE TITLE
How do I report outage when LCS is down too?

### ISSUE THREAD

**Issue by turbozapekanka** [MicrosoftDocs/dynamics-365-unified-operations-public#1228]
a question

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a326d11-a0a3-1e59-06d3-e576f72e6f5e
* Version Independent ID: 7601cd35-9b1f-2dec-99ea-5e417f5f643b
* Content: [Report a production outage - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/report-production-outage)
* Content Source: [articles/dev-itpro/lifecycle-services/report-production-outage.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/lifecycle-services/report-production-outage.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @manalidongre
* Microsoft Alias: **manado**

**Comment by josaw1** [comment]
Thanks for the comment. @manalidongre, can you please help with this question?

**Comment by turbozapekanka** [comment]
Should probably link to this information
https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/cloud-powered-support-lcs#phone-support

**Comment by sericks007** [comment]
I've updated the [Report a production outage](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/report-production-outage) topic to link to the [Phone support](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/cloud-powered-support-lcs#phone-support) section. The change will be published in a day or two.
