### ISSUE TITLE
Old video

### ISSUE THREAD

**Issue by depakgupta** [MicrosoftDocs/dynamics-365-unified-operations-public#1230]
The video 'Ep 59 Long Running ...' shows AX 2012. It needs to be verified if it still holds good for D365FO.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df19fbb0-d719-6131-3200-c8f6a3102da2
* Version Independent ID: cbb243ec-98d0-263e-6cef-a5ff28798b24
* Content: [Help prevent long-running reports from timing out - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/prevent-long-running-reports-timing-out?toc=/fin-and-ops/toc.json)
* Content Source: [articles/dev-itpro/analytics/prevent-long-running-reports-timing-out.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/prevent-long-running-reports-timing-out.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by tonyafehr** [comment]
Bug 320706 has been logged to track this issue.

**Comment by TJVass** [comment]
You are correct.  This video is intended for AX2012 customers.  Thanks for letting us know.
