### ISSUE TITLE
Actions mentioned in step 13 and 14 are not availeble

### ISSUE THREAD

**Issue by amolbs2106** [MicrosoftDocs/dynamics-365-unified-operations-public#1231]
[Enter feedback here]
Hello,
i tried to add custom control to POS.
when i went to screen layout designer and dragged the custom control on transaction page the i didn't found relative url option instead i found below option therefore i coudn't proceed as steps mentioned do not match with custom control customization options. Please provide me the update steps i am using retail 7.3.0
![image](https://user-images.githubusercontent.com/9738934/57134995-9195a880-6dc5-11e9-9764-d818cd0b4cd8.png)

Thanks
Amol

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 165b59ae-390f-fe98-dfc9-6dcad0b088b1
* Version Independent ID: a885bb03-2395-60d4-ff21-85281753254b
* Content: [Add custom controls to Retail Modern POS (MPOS) screen layouts - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/dev-itpro/add-new-custom-control-mpos-screen-layout)
* Content Source: [articles/retail/dev-itpro/add-new-custom-control-mpos-screen-layout.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/dev-itpro/add-new-custom-control-mpos-screen-layout.md)
* Service: **dynamics-365-retail**
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by mugunthanm** [comment]
Please use this document for version 7.3 and later:
https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/dev-itpro/pos-custom-transaction

The document you are referring is for older versions.
