### ISSUE TITLE
Timestamp retail package for code signing purposes?

### ISSUE THREAD

**Issue by dch9** [MicrosoftDocs/dynamics-365-unified-operations-public#1232]
Is there any ability to utilize code timestamp functionality (via a timestamp URL) when building the Retail Deployable package?  Without time stamping, packages would become invalid for install once the code signing certificate reaches it's expiration date.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c268f5fb-7fbc-b82c-5f6f-b3640344f4a4
* Version Independent ID: 559b9e5f-7514-f3d1-8b73-bf9248cbac80
* Content: [Create retail deployable packages - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/dev-itpro/retail-sdk/retail-sdk-packaging)
* Content Source: [articles/retail/dev-itpro/retail-sdk/retail-sdk-packaging.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/dev-itpro/retail-sdk/retail-sdk-packaging.md)
* Service: **dynamics-365-retail**
* GitHub Login: @mugunthanm
* Microsoft Alias: **sijoshi**

**Comment by mugunthanm** [comment]
Unfortunately this is not supported.  Certificate management has to be managed separately form this.
