### ISSUE TITLE
Code Generation Wizard available in 10.0.2?

### ISSUE THREAD

**Issue by regrebud** [MicrosoftDocs/dynamics-365-unified-operations-public#1233]
I have installed Update 26 (10.0.2), but I don't see the 'Generate ATL Entity' option in VS menu.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d635373-8279-5322-1dd1-73ab400e871c
* Version Independent ID: dd72cfa6-e04c-3965-0cfc-79e446bf6112
* Content: [Acceptance test library Code generation wizard - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-gb/dynamics365/unified-operations/dev-itpro/perf-test/code-generation-wizard#feedback)
* Content Source: [articles/dev-itpro/perf-test/code-generation-wizard.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/perf-test/code-generation-wizard.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @MichaelFruergaardPontoppidan
* Microsoft Alias: **MichaelFruergaardPontoppidan**

**Comment by RobinARH** [comment]
Logged bug 321301 to track this issue.

**Comment by MichaelFruergaardPontoppidan** [comment]
Thank you.  The wizard will be available with platform update 28.

**Comment by regrebud** [comment]
Are we still aligned on update 28? I don’t see any information about ATL on the release notes.

**Comment by regrebud** [comment]
Apparently not available in update 28 either... Just installed this version and I don't see the menu item "Generate ATL Specification".

**Comment by MichaelFruergaardPontoppidan** [comment]
The wizard should be available with PU28.   You should have these 2 DLLs in your Visual Studio 14 folder:
![image](https://user-images.githubusercontent.com/28089437/59657531-4c74dc80-91a1-11e9-8626-a555fcb448ee.png)

And then you should get the wizard in the context menu in the DESIGNER on tables.
![image](https://user-images.githubusercontent.com/28089437/59657599-7e863e80-91a1-11e9-9593-6205a7b54d5f.png)

Also we are demoing this in 2 Tech Talks - please sign-up here.  There will be an Q&A opportunity too.
https://aka.ms/d365techtalks/
