### ISSUE TITLE
Not clear that a new AAD Native Application must be created

### ISSUE THREAD

**Issue by tomhig** [MicrosoftDocs/dynamics-365-unified-operations-public#1235]
In step 3 under Parameter Setup there is a note. While this note references an AAD application, it is not clear that you MUST create a new Azure AD Application and reference that Application ID in the Parameters form. This article should include the step by step instructions to create a Native AAD application in the Azure Portal and the permissions to grant to that application. Actual Screen Shots would also be helpful with field-by-field guidance, not just selected fields. Refer to the instruction steps under "Register a web application with AAD" and "Register your external application in Finance and Operations" in the following article as an example (note example is to create a Web application, not a Native application): https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/services-home-page#authentication 

 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ca4616b-e29f-a9c3-0d42-fe75c4659d57
* Version Independent ID: 9a438e2c-12e3-bb72-bcb2-1c45b05039e7
* Content: [AX 2009 migration - Install the Data migration tool - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/install-dmt)
* Content Source: [articles/dev-itpro/migration-upgrade/install-dmt.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/migration-upgrade/install-dmt.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @kfend
* Microsoft Alias: **kfend**

**Comment by RobinARH** [comment]
@kfend and @Sunil-Garg 
Hi - Can you take a look at this issue? thanks - Robin

**Comment by Gokul06** [comment]
we are in process of changing it from native app to web app. So lets up this on-hold, i will circle back in few weeks to update the documentation
