### ISSUE TITLE
Please explain the difference between Subscription and ProDirect support contracts

### ISSUE THREAD

**Issue by turbozapekanka** [MicrosoftDocs/dynamics-365-unified-operations-public#1239]
When should I choose one or another when submitting a new incident?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d3bf99a-6a62-915c-9a2a-f4c2ec4fdf63
* Version Independent ID: 1cef419f-bfe5-3154-5b4a-8c3934bcb934
* Content: [Manage Finance and Operations support experiences - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/cloud-powered-support-lcs#manage-support-plans)
* Content Source: [articles/dev-itpro/lifecycle-services/cloud-powered-support-lcs.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/lifecycle-services/cloud-powered-support-lcs.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @kfend
* Microsoft Alias: **anupams**

**Comment by sericks007** [comment]
@turbozapekanka, thanks for posting this.

@EricMoos, can you please answer this question.

**Comment by sericks007** [comment]
At a high level, the Subscription plan is bundled with your online purchase. ProDirect is an additional offering that we have.  For details and benefits of different support plans, please reach out to your account representative.
