### ISSUE TITLE
Trickle feed for entity store in Azure data lake 

### ISSUE THREAD

**Issue by D365BI** [MicrosoftDocs/dynamics-365-unified-operations-public#1241]
I tried trickle feed for entity store in Azure data lake and it seems to be working. However it is impossible to identify in data lake changed and new rows which prevents incremental data loads from data lake.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a19d5e09-3e76-35e3-636a-e9c2ebb86b5a
* Version Independent ID: de7b6e2e-e778-d393-5035-bfbe4eddb49c
* Content: [Preview features in Dynamics 365 for Finance and Operations platform update 25 (April 2019) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/whats-new-platform-25#feedback)
* Content Source: [articles/fin-and-ops/get-started/whats-new-platform-25.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/whats-new-platform-25.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @tonyafehr
* Microsoft Alias: **tfehr**

**Comment by tonyafehr** [comment]
@D365BI, thanks for the feedback. If you need further assistance you can contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

@MilindaV2, please review this product feedback.
