### ISSUE TITLE
How do I know the version scheduled for update

### ISSUE THREAD

**Issue by turbozapekanka** [MicrosoftDocs/dynamics-365-unified-operations-public#1251]
I also see a notification in the action center about available update with a button to "Save update" which saves a package to the asset library. Do I have to save the update in order to auto-update to happen? Or it will take whatever is the latest GA version at the scheduled update time and applies this version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79fdb5d3-d717-813c-4c11-0fd82522a71b
* Version Independent ID: 3ab7bac4-cf1c-c5c2-e0c5-c6a7c6fe17ca
* Content: [Configure service updates through Lifecycle Services (LCS) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/configure-service-updates)
* Content Source: [articles/dev-itpro/lifecycle-services/configure-service-updates.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/lifecycle-services/configure-service-updates.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @manalidongre
* Microsoft Alias: **manado**

**Comment by turbozapekanka** [comment]
Example: A customer is on 10.0 PU24
There is 10.0.1 PU 25 available
The next update is scheduled second week next month.
Do I have to save the 10.0.1 PU 25 from the action center in order to update to happen?
What if 10.0.2 PU 26 is out before scheduled update date (and I don't have it saved in the asset library)?
How do I know which version is going to be applied?

**Comment by tonyafehr** [comment]
@turbozapekanka, thanks for posting this! This is not a support site. To get product help you can contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

 @manalidongre, please review and update the topic, if needed.

**Comment by turbozapekanka** [comment]
This is not a support question either, may be wrong page, should be answered on the FAQ page https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/one-version

**Comment by tonyafehr** [comment]
I've passed this feedback on to the author of these topics so the appropriate updates can be made. Thanks!

**Comment by sericks007** [comment]
Bug 321793 has been logged to track this issue.

**Comment by sericks007** [comment]
The [Get notified about service updates through Lifecycle Services (LCS)](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/notifications-service-updates) topic as been updated based on this issue.
