### ISSUE TITLE
Elaborate on table group properties

### ISSUE THREAD

**Issue by ibruynin** [MicrosoftDocs/dynamics-365-unified-operations-public#1253]
cfr. https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/issues/258

We'd like to see more explanation on the different (and especially the newly introduced in FinOps as opposed to AX2012) enumeration values in the TableGroup property. Also, there seems to be a link with the properties on the related data entities, which allows - or not - using those entities for copy company functionalities.
I posted our interpretation of the different values in one of my previous docs related issues about a year ago.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7d5f5d5-c95d-4c70-0af6-69bb881052e6
* Version Independent ID: 2dbf3828-ed0d-06c9-0e07-1335951a9637
* Content: [Application Explorer properties - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-ref/application-explorer-aot-properties)
* Content Source: [articles/dev-itpro/dev-ref/application-explorer-aot-properties.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-ref/application-explorer-aot-properties.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RobinARH
* Microsoft Alias: **robinr**

**Comment by tonyafehr** [comment]
@ibruynin, thanks for the great feedback.
@RobinARH, please review and consider making updates to this topic.

**Comment by ibruynin** [comment]
related issues 
#253 
#258 
#265

**Comment by sericks007** [comment]
Bug 321794 has been logged to track this issue.

**Comment by ibruynin** [comment]
Hi @sericks007 
Can you provide an update on Bug 321794?

Thanks!

**Comment by sericks007** [comment]
Hi @ibruynin, bug 321794 is assigned to @RobinARH.  

@RobinARH, can you please provide an update.

**Comment by RobinARH** [comment]
We are not planning to make these updates. - Robin
