### ISSUE TITLE
"iX guidelines"

### ISSUE THREAD

**Issue by f1eetie** [MicrosoftDocs/dynamics-365-unified-operations-public#1254]
"Wording, punctuation, and abbreviations must follow the iX guidelines."

What are "iX guidelines"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75951059-1b55-637e-9ee9-19279698c262
* Version Independent ID: b0a08073-0e50-1ab0-74a7-6b9d1efdc27f
* Content: [General form guidelines - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/user-interface/general-form-guidelines#feedback)
* Content Source: [articles/dev-itpro/user-interface/general-form-guidelines.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/user-interface/general-form-guidelines.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by tonyafehr** [comment]
@f1eetie, thanks for the feedback. 

@jasongre, please review and update this topic.

**Comment by tonyafehr** [comment]
Bug 323139 has been logged to track this issue.

**Comment by jasongre** [comment]
"iX" refers to "Information experience". I'm updating the article to remove that section since it's internal guidance.
