### ISSUE TITLE
This page needs to be updated with new version of App Registration flow in Azure AD

### ISSUE THREAD

**Issue by TomekMelissa** [MicrosoftDocs/dynamics-365-unified-operations-public#1259]
current instructions are for now legacy version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48cf34e5-5de2-319c-c709-f06ea8fe4164
* Version Independent ID: 1b04f148-d442-f72b-a3b9-3eb4ede9f719
* Content: [Make Entity store available as a Data Lake - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/entity-store-data-lake)
* Content Source: [articles/dev-itpro/data-entities/entity-store-data-lake.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/entity-store-data-lake.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by tonyafehr** [comment]
@TomekMelissa, thanks for the feedback. 

@MilindaV2, please review and update this topic.

**Comment by tonyafehr** [comment]
Bug 323140 has been logged to track this issue.
