### ISSUE TITLE
there are not: Send email and Email recipients fields

### ISSUE THREAD

**Issue by ostola** [MicrosoftDocs/dynamics-365-unified-operations-public#1262]
Hello every one.
Anyone knows why mentioned fields do not appear in create alert form? I have  version 10 P24 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b9b2766-4ec8-bc37-67a6-624308c4cacb
* Version Independent ID: b0f59676-4dc7-afc5-0b82-75f6614e1402
* Content: [Client alert notifications by email - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/alert-email-notifications#feedback)
* Content Source: [articles/fin-and-ops/get-started/alert-email-notifications.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/alert-email-notifications.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by tonyafehr** [comment]
Bug 323143 has been logged to track this issue. 

In the meantime, to get product help you can contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

**Comment by TJVass** [comment]
The email notification options were added with PU24.  The option becomes available once the SMTP service has been enabled.
