### ISSUE TITLE
business process?

### ISSUE THREAD

**Issue by prodev42** [MicrosoftDocs/dynamics-365-unified-operations-public#1265]
Can we add an overall business diagram chart here just like other processes?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff2f03a9-638c-0f08-123a-3a790ba3c0d4
* Version Independent ID: 48c5f196-d266-92a9-bcd5-388d4ae78ee0
* Content: [Budgeting home page - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/budgeting/budgeting-overview)
* Content Source: [articles/financials/budgeting/budgeting-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/budgeting/budgeting-overview.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @ShylaThompson
* Microsoft Alias: **shylaw**

**Comment by kfend** [comment]
Thanks for the feedback. I have passed this suggestion on to the topic owner.
