### ISSUE TITLE
 Regression Suite Automation Tool support for sandbox environments

### ISSUE THREAD

**Issue by maheshambati410** [MicrosoftDocs/dynamics-365-unified-operations-public#1268]
Can we install and configure Regression Suite Automation Tool in sandbox environments? guide us the process and documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18d6a0b7-38dc-ddcd-c495-67e3b7498a7c
* Version Independent ID: 36a6bc94-6939-9daf-ad3d-4e0064258172
* Content: [Create and automate user acceptance tests - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/using-task-guides-and-bpm-to-create-user-acceptance-tests)
* Content Source: [articles/dev-itpro/lifecycle-services/using-task-guides-and-bpm-to-create-user-acceptance-tests.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/lifecycle-services/using-task-guides-and-bpm-to-create-user-acceptance-tests.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @kfend
* Microsoft Alias: **ntecklu**

**Comment by RobinARH** [comment]
@kfend - Can you take a look at this one? thanks.

**Comment by robadawy** [comment]
The regression suite automation tool (RSAT) is designed to be installed on client computers connected to Fin and Ops environment via the browser. You do not install on the environment itself. You can set it up to connect to sandbox environment. The process of setting up is described in the user manual available with RSAT here https://www.microsoft.com/en-us/download/details.aspx?id=57357

**Comment by maheshambati410** [comment]
Thanks Robert. 
As per documentation Thumbprint to be updated in AOS servers, in self service deployment option we will not get RDP access to sandbox servers, how we can add thumbprint in this scenario? 
https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/deployment/infrastructure-stack
