### ISSUE TITLE
Profit tax functionality

### ISSUE THREAD

**Issue by vavd** [MicrosoftDocs/dynamics-365-unified-operations-public#1269]
Hello,

Where can I find a documentation regarding RU profit tax functionality?

The questions is about the "Tax &gt; Setup &gt; Profit tax &gt; ..." menu items.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c38d189-e0aa-0479-d35b-f26e81fe135f
* Version Independent ID: 48764b7d-19b7-1bce-3c2b-ec8a10596062
* Content: [Russia - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/localizations/russia)
* Content Source: [articles/financials/localizations/russia.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/localizations/russia.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @ShylaThompson
* Microsoft Alias: **shylaw**

**Comment by tonyafehr** [comment]
@vavd, thanks for the feedback.

Bug 323144 has been logged to track this issue.

**Comment by v-oloski** [comment]
Hello Vadim,

Unfortunately the Tax profit documentation for Microsoft Dynamics 365 for Finance and Operations is not ready yet. But the Tax profit functionality for Microsoft Dynamics 365 for Finance and Operations has not significant difference in comparing to Ax 2012 R3/ AX 2009. 
Therefore you may download Guides for AX 2009 Client Help Files for Russia and Eastern Europe where you can read the guides for tax registers in Russian. Please download the Guide from https://www.microsoft.com/en-us/download/details.aspx?id=19269.
Guides for AX 2012 could be found here: 
https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/rus-general-ledger
