### ISSUE TITLE
Compability text correct?

### ISSUE THREAD

**Issue by fw1978** [MicrosoftDocs/dynamics-365-unified-operations-public#1270]
Is this correct?

"The compatibility is only backwards. A customization can be compiled on a newer platform and then deployed in a customer environment that hasn't yet been updated to that version or a later version."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20ba628a-45d6-eafd-763f-5cdacd9f5018
* Version Independent ID: b77c2475-5777-27b4-d9ba-7cfd23ef11eb
* Content: [Delivering ISV solutions - One Version guidelines - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/oneversion-isv#feedback)
* Content Source: [articles/dev-itpro/lifecycle-services/oneversion-isv.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/lifecycle-services/oneversion-isv.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @FrankDahl
* Microsoft Alias: **rhaertle**

**Comment by FrankDahl** [comment]
Binary compatibility is backwards only. This means a customization may be compiled on an older application and platform, and deployed to a customer environment that has been updated to a later version. You cannot deploy code compiled on a later version than the one running on the environment you deploy to.

**Comment by fw1978** [comment]
Totally agree. That's way I reacted on the text in the document. The text that I cited was from the "Runtime compatibility" section.

**Comment by RobinARH** [comment]
I updated the content in the topic and the new content should to live in the next couple of days.

-Robin
