### ISSUE TITLE
Import a bank statement

### ISSUE THREAD

**Issue by vavd** [MicrosoftDocs/dynamics-365-unified-operations-public#1271]
Where we can find a documentation about setting up a bank statement format and importing a bank statement?

For example, documentation about formats in AX 2012:
https://docs.microsoft.com/en-us/dynamicsax-2012//rus-exchange-formats-of-client-bank-form

Please provide a link where we can find a documentation how to set up functionality for importing a bank statement in Dynamics 365 FO.

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8d08902-6f7b-40cf-364e-8d7100843495
* Version Independent ID: 869a50fd-7220-0e65-07df-b5ebd5a2d82b
* Content: [Cash flow management (Russia) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/localizations/rus-cash-flow)
* Content Source: [articles/financials/localizations/rus-cash-flow.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/localizations/rus-cash-flow.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @ShylaThompson
* Microsoft Alias: **shylaw**

**Comment by tonyafehr** [comment]
@vavd, thanks for the feedback.

Bug 323145 has been logged to track this issue.

**Comment by vsklyarovaGMCS** [comment]
Hello! Tell me please when will the documentation be released?
