### ISSUE TITLE
Current list of supported languages

### ISSUE THREAD

**Issue by maveloso** [MicrosoftDocs/dynamics-365-unified-operations-public#1272]
it would be good to have a link on this page to the actual current list of supported languges OOB. this information is not easily accessible or findable on the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41c33fc3-69e4-575e-02f1-9c611a15f0a3
* Version Independent ID: 8855f576-f1e6-6aeb-7f80-aa8ce01e51c5
* Content: [Microsoft Dynamics 365 Translation Service - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/translation-service-overview#glossary)
* Content Source: [articles/dev-itpro/lifecycle-services/translation-service-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/lifecycle-services/translation-service-overview.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @ejcho
* Microsoft Alias: **ejchoGIT**

**Comment by RobinARH** [comment]
@ejcho - Can you take a look at this? thanks.

**Comment by tonyafehr** [comment]
Bug 323145 has been logged to track this issue.

**Comment by ejchoGIT** [comment]
The supported languages vary depending on the product and the version. Dynamics Translation Service supports multiple products and the associated versions, so there is no one-page information to list them all. User can contact dtssup@microsoft.com to check if a specific language is supported for a specific product and version or request to add one if not found from within Dynamics Translation Service.
