### ISSUE TITLE
A precision document

### ISSUE THREAD

**Issue by amadse** [MicrosoftDocs/dynamics-365-unified-operations-public#1273]
What is the definition on "A precision document"?
Is that a document that is saved with the contend and layout on the printing time and never changed later?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 516e4dbe-6af2-93f4-9b3e-938b97b155a5
* Version Independent ID: c11073d9-97bf-763c-5d6e-966b8a3c62ce
* Content: [Document printing - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/print-documents)
* Content Source: [articles/dev-itpro/analytics/print-documents.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/print-documents.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by RobinARH** [comment]
@TJVass @sericks007  - Can you take a look at this? Thanks.

**Comment by tonyafehr** [comment]
@amadse, thanks for the feedback.

Bug 323151 has been logged to track this issue.

**Comment by TJVass** [comment]
Thanks for the question, @amadse
The term "precision document" in this context refers to any paginated report where character spacing and text can be scaled to the target paper size.  PDF is the preferred format for supplying non-editable precision documents like Sales Invoice & Packing Slips.
