### ISSUE TITLE
Data entity filter issue

### ISSUE THREAD

**Issue by ripannandy** [MicrosoftDocs/dynamics-365-unified-operations-public#1274]
Configured export data jobs using "Transfer order lines" entity. My requirement is to filter the data entity but application is throwing an error on putting filter on data entity. Error is "No tree node for Data Dictionary\Views\InventTransferOrderLineEntity\Fields\TransferOrderNumber".
![Error](https://user-images.githubusercontent.com/41295860/57634286-a5f65400-75c2-11e9-84ab-bc6d83f1c2c9.JPG)

**Comment by RobinARH** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
