### ISSUE TITLE
Create a web service application in Azure Active Directory - New Version

### ISSUE THREAD

**Issue by stuartahonour** [MicrosoftDocs/dynamics-365-unified-operations-public#1275]
Instructions for "Create a web service application in Azure Active Directory" This section needs to be updated as App Registrations in Azure has been updated and the screen shoots in this page are no longer accurate .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24ad63f4-807c-fc88-58b6-33514bd034d0
* Version Independent ID: d727eb59-1162-f195-031a-5400301c8e5b
* Content: [Install and configure Microsoft Dynamics 365 for Finance and Operations – Warehousing - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/warehousing/install-configure-warehousing-app#feedback)
* Content Source: [articles/supply-chain/warehousing/install-configure-warehousing-app.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/warehousing/install-configure-warehousing-app.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @MarkusFogelberg
* Microsoft Alias: **mafoge**

**Comment by RobinARH** [comment]
@MarkusFogelberg Can you take a look at this one? Thanks.

**Comment by RobinARH** [comment]
@josaw1 Add Jo, too.

**Comment by stuartahonour** [comment]
@MarkusFogelberg Do you know when the information will be updated?

**Comment by tonyafehr** [comment]
Bug 323152 has been logged to track this issue.

**Comment by carolinapadolina** [comment]
Any update? Can't seem to set this up to any of the new environments starting around March and still. The working one we had before is already decommissioned. Can't get past the "Unauthorized" error on the app.

**Comment by gammelgaard52** [comment]
Any update, this is critical now? We cannot create new App Registrations, until this is fixed.

**Comment by AndersDahlin** [comment]
Yes, please update instructions for web app registration.

**Comment by jonasdeco** [comment]
It's no longer possible to create a working app registration using this method because of changes in  the Azure portal. Please update the documentation

**Comment by CelesteDG** [comment]
Hi @RobinARH and @tonyafehr - Do you have an ETA when the updated app reg content will go live? 

For reference, please see the instructions here: https://docs.microsoft.com/azure/active-directory/develop/quickstart-register-app. It might be helpful to just point to this topic (my team owns the app reg experience in the Azure portal) but provide only the specific settings needed for your feature. Thank you.

**Comment by RobinARH** [comment]
The updated content is live now.
