### ISSUE TITLE
Performance Testing in Dynamics 365 FO 8.1 with Platform Update 23

### ISSUE THREAD

**Issue by kvigneshvaran** [MicrosoftDocs/dynamics-365-unified-operations-public#1277]
Hi,

I need to do the Performance testing using task recorder in Dynamics 365 FO 8.1 with platform update 23.
I followed the steps which is given in the below mentioned link.
https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/perf-test/perfsdk-tutorial-lbd

But in this link they provide the CloudEnvironment file details which is only applicable upto D365 FO 7.3 with platform update 15.

D365 FO 8.1 with Platform update 23 ask the client app id details in CloudEnvironment file.
what should i do?

and another onething if give the details of client appid and secret keys then during run the test the below mentioned error occurs.

MS.Dynamics.Performance.Application.SCM.CreatePurchReqBase.CreatPurchReq threw exception:
System.IO.FileLoadException: Could not load file or assembly 'WebDriver, Version=3.13.1.0, Culture=neutral,
PublicKeyToken=1c2bd16353048f' or one of its dependencies. The located assembly's manifest definition
does not match the assembly reference. (exception from HRESULT:0x80131040)

**Comment by tonyafehr** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
