### ISSUE TITLE
Hide Prices

### ISSUE THREAD

**Issue by SimonHoey** [MicrosoftDocs/dynamics-365-unified-operations-public#1282]
Is there a way to create a quotation and have it publish only the total of the lines rather than publish the individual line prices?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a588a9f-2dda-d33d-5ce9-1c25f25a5a06
* Version Independent ID: c9547cc6-74a5-5822-db46-08fddf332ff1
* Content: [Create and edit sales quotations - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/sales-marketing/tasks/create-edit-sales-quotations#feedback)
* Content Source: [articles/supply-chain/sales-marketing/tasks/create-edit-sales-quotations.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/sales-marketing/tasks/create-edit-sales-quotations.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @omulvad
* Microsoft Alias: **omulvad**

**Comment by sericks007** [comment]
@SimonHoey, thanks for posting this! In the meantime, to get product help you can contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community. 

@omulvad, can you please review and answer the question.

**Comment by tonyafehr** [comment]
Bug 323662 has been logged to track this issue.

**Comment by lachlancashMS** [comment]
@SimonHoey when you say publish are you referring to the price simulation or printing out a quote confirmation ? Either way we still have line level prices.
