### ISSUE TITLE
Well documented.

### ISSUE THREAD

**Issue by ransoentjens** [MicrosoftDocs/dynamics-365-unified-operations-public#1283]
Kudos for this article page. This clearly describes the framework as a whole, impact and relation with other funcitonalities, implementation considerations, etc.

This really is the level of documentation that we are looking for. Will done for this building block of the module. I encourage the Microsoft team to gradually get to this level of quality for other components as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a52e942-e19f-4130-bcce-81b1332f7c0b
* Version Independent ID: b3d8bfcd-76f7-1d8f-adf8-19bd14b12fe7
* Content: [Assortment management - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/assortments)
* Content Source: [articles/retail/assortments.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/assortments.md)
* Service: **dynamics-365-retail**
* GitHub Login: @jblucher
* Microsoft Alias: **jeffbl**

**Comment by sericks007** [comment]
@ransoentjens, thank you so much for providing this feedback! It's great to know that this article was helpful to you!
