### ISSUE TITLE
Correction required in the setup steps

### ISSUE THREAD

**Issue by SabyasachiChakraborti** [MicrosoftDocs/dynamics-365-unified-operations-public#1291]
"System setup for coupons" section step 5:  In the 'Retail Parameter' page 'Bar code' tab is not available. The correct step is to go to 'Discount' tab and then to the 'Coupon' fast tab to setup the bar code mask for coupons

"System setup for coupons" section step 6: This step is not required to create a bar code for coupons

**Comment by josaw1** [comment]
Thanks for the comment. @jblucher can you please help get this topic updated?
