### ISSUE TITLE
what are the specific permissions for the azure dev ops PAT?

### ISSUE THREAD

**Issue by maveloso** [MicrosoftDocs/dynamics-365-unified-operations-public#1294]
this documentation should specify the minimm specific permissions to be granted to the PAT. Granting all scopes to a PAT is just bad security practice

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1804282-0c48-6305-c6b2-b31dec2727df
* Version Independent ID: 2650812b-ab37-47ef-c103-a8a094cc8fce
* Content: [Synchronize BPM libraries with Azure DevOps - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/synchronize-bpm-vsts)
* Content Source: [articles/dev-itpro/lifecycle-services/synchronize-bpm-vsts.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/lifecycle-services/synchronize-bpm-vsts.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @amarshall
* Microsoft Alias: **tsmarsha**

**Comment by tonyafehr** [comment]
@maveloso, thank you for the feedback. 

@AngelMarshall, please review and update the topic accordingly.

**Comment by AngelMarshall** [comment]
Hi, 
For BPM to Azure DevOps sync, the minimum scopes needed would be for Work Items with read, write, & manage permission.
