### ISSUE TITLE
Odata data limit

### ISSUE THREAD

**Issue by ripannandy** [MicrosoftDocs/dynamics-365-unified-operations-public#1296]
Is there any data limit for each OData request ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64b023ab-59fb-87d9-d935-d60d0e9e4139
* Version Independent ID: 10120c96-a72d-60fd-63ff-db9f77e05817
* Content: [Open Data Protocol (OData) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/odata)
* Content Source: [articles/dev-itpro/data-entities/odata.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/odata.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by tonyafehr** [comment]
@ripannandy, thank you for the feedback. To get product help you can contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

@Sunil-Garg, please review and update the topic accordingly.
