### ISSUE TITLE
When will be the Entity Store available for D365FO On-Premise?

### ISSUE THREAD

**Issue by normatg** [MicrosoftDocs/dynamics-365-unified-operations-public#1298]
There was a post on Microsoft Docs that the Entity Store will be available. Does anyone have further details?
[https://docs.microsoft.com/en-us/business-applications-release-notes/April19/dynamics365-finance-operations/entity-store-on-prem-availability](url)

**Comment by tonyafehr** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle requests for release dates here. I suggest going to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
