### ISSUE TITLE
Mobile workspace: Max 50 items on lookup

### ISSUE THREAD

**Issue by HZRudi** [MicrosoftDocs/dynamics-365-unified-operations-public#1299]
Hi
".. By default, 50 items are loaded, but a developer can change this number."

Can not find anything about how to change this number?
Found nothing on "Mobile platform." about that issue...
Tnx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 552fe27a-7bdc-e542-e95e-3fd80a13cf95
* Version Independent ID: 9757e9d0-a499-46dd-d6b8-430a98f3b9bd
* Content: [Project time entry mobile workspace - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/project-management/project-time-entry-mobile-workspace#feedback)
* Content Source: [articles/financials/project-management/project-time-entry-mobile-workspace.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/project-management/project-time-entry-mobile-workspace.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @KimANelson
* Microsoft Alias: **knelson**

**Comment by tonyafehr** [comment]
@HZRudi, thanks for posting this. 

@KimANelson, please review this feedback and update the topic accordingly.

**Comment by hoanganhinfo** [comment]
Hello,

Do we have any update on this topic, I also need change this default number on Mobile workspace

Thank you

**Comment by tonyafehr** [comment]
@Yowelle, please review and provide feedback. Thanks!

**Comment by Yowelle** [comment]
This should be assigned to Steven Sporen as he manages the mobile app.
