### ISSUE TITLE
Business events are not showing up in Azure Service Bus queue

### ISSUE THREAD

**Issue by bhuvanabellala1** [MicrosoftDocs/dynamics-365-unified-operations-public#1300]
My endpoint is setup correctly because I do see the test message in the queue. I activated two business events on this queue. However, when I perform these actions, the messages are not showing up in the queue. I tried to make sure that the business events batch processor is running. However when I go to System Parameters, I do not see the Business events - Preview tab. How can I ensure that the batch processor is running? I am on update 26

**Comment by tonyafehr** [comment]
@bhuvanabellala1, thanks for posting this! Your comment is not directed toward a specific topic, which is the intent of this feedback site. This is not a support site. To get product help you can contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
