### ISSUE TITLE
Missing link

### ISSUE THREAD

**Issue by ptuerk** [MicrosoftDocs/dynamics-365-unified-operations-public#1301]
In the chapter immediate window a document is mentioned that the snippets should be written in C# syntax.
Please add the link here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d23000d7-984d-c071-f45a-af4679ae9d00
* Version Independent ID: 3b1286b4-c55c-7db9-4afa-eb2b21db0287
* Content: [X++ and debugger features - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-tools/new-x-debugger-features#feedback)
* Content Source: [articles/dev-itpro/dev-tools/new-x-debugger-features.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-tools/new-x-debugger-features.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @pvillads
* Microsoft Alias: **pvillads**

**Comment by tonyafehr** [comment]
@ptuerk, thanks for sending this feedback. 
@pvillads, please review and update the topic accordingly.
