### ISSUE TITLE
No configuration

### ISSUE THREAD

**Issue by soerenpc** [MicrosoftDocs/dynamics-365-unified-operations-public#1303]
After I have set up my own user I get this:
The menu item with name jmgregistrationtouch could not be opened.
There is no configuration for the current user.
What can be the problem ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c9cb448-e8e6-e8e8-401f-7dc1f456df49
* Version Independent ID: 388e1156-e266-cb51-faaa-19030f10c85b
* Content: [Configure a worker using the mobile job device - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/production-control/tasks/worker-mobile-job-device)
* Content Source: [articles/supply-chain/production-control/tasks/worker-mobile-job-device.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/production-control/tasks/worker-mobile-job-device.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @ShylaThompson
* Microsoft Alias: **shylaw**

**Comment by sericks007** [comment]
@soerenpc, Thanks for posting this! In the meantime, to get product help you can contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

**Comment by sericks007** [comment]
Bug 325485 has been logged for this issue.

**Comment by johanhoffmann** [comment]
You get this error message when you have not added the AX user to the configuration of the job card device. (Path: Configure Job Card Device). In the standard demo data, some users are already added, so if you log in with one of these users, then it is possible to log into the Job Card Device.
