### ISSUE TITLE
Assign only duties to roles

### ISSUE THREAD

**Issue by FINOPSAOSCEWA** [MicrosoftDocs/dynamics-365-unified-operations-public#1304]
Hi there,

In this article, there is a recommendation to "assign only duties to roles". Is this recommendation basing on the assumption that each privilege will be always assigned to one (and only one) duty? Or  it will be a case-by-case scenario?

For instance,  the privilege "VendProspectiveVendorDataAreaSelectDeny" does not belong to any duty. So, this privilege has to be assigned to a role directly.
And the privilege "ProjCostPriceExpenseView" is assigned to two standard duties. If these two duties are assigned to one role, and if the privilege "ProjCostPriceExpenseView" needs to be removed from the role, then two new customized duties (with the privilege removed) need to be created to replace these two standard duties in the role. In this case, actually, it easier to assign the privileges to the role directly, so the customization of the new duties can be avoided. 
 
As a result, to assign only duties to roles, is it a recommendation, a best practice or maybe just a case-by-case scenario? 

Thanks and regards,
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09327be4-4437-628d-65b0-45e5824a06d5
* Version Independent ID: 1bbaa6dd-6e50-77e1-36c2-10c2dbd55459
* Content: [Role-based security - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/sysadmin/role-based-security)
* Content Source: [articles/dev-itpro/sysadmin/role-based-security.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/sysadmin/role-based-security.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @sericks007
* Microsoft Alias: **sericks**

**Comment by sericks007** [comment]
@FINOPSAOSCEWA, thanks for posting this!

@robadawy, can you please review and answer the questions.

**Comment by sericks007** [comment]
@ChrisGarty, please review and answer the questions, and update the topic if needed.

**Comment by sericks007** [comment]
Bug 325481 has been logged to track this issue.

**Comment by ChrisGarty** [comment]
This is just a best practice. It needs to be evaluated on a case-by-case basis. I updated the documentation slightly to provide the reason for the recommendation: grouping.
"However, we recommend that you assign only duties to roles, so that the privileges are grouped together into a duty first for easier maintenance. "
