### ISSUE TITLE
DMFEnableAllCompanyExport

### ISSUE THREAD

**Issue by Ake-Olsson** [MicrosoftDocs/dynamics-365-unified-operations-public#1306]
For BYODB this one doesnt work since it do not work when you run it as a batchjob. If run manually it exports data for all companies but when it is run as a batchjob it only xports data from the company that you set up the batch job for

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c6788e8-dfb0-6108-71ae-e265bad542a2
* Version Independent ID: 68a26703-3d8c-4d46-6f3f-37c30aa79373
* Content: [Data management - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/data-entities-data-packages#feedback)
* Content Source: [articles/dev-itpro/data-entities/data-entities-data-packages.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/data-entities-data-packages.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by sericks007** [comment]
@Ake-Olsson, thanks for posting this.

@Sunil-Garg, please review and update the topic, as needed.

**Comment by sericks007** [comment]
Bug 325476 has been logged to track this issue.

**Comment by Sunil-Garg** [comment]
@Ake-Olson, can you try in the latest platform pls? We don't see this issue happening. If this is still an issue in your environment then, please open a support case. Thanks.
