### ISSUE TITLE
Custom shortcut not invoked

### ISSUE THREAD

**Issue by Rardd1997** [MicrosoftDocs/dynamics-365-unified-operations-public#1307]
Hello, how I can run my custom shortcut from Form. When I create a custom control and add a shortcut to him, I cannot to see it on "Currently available shortcuts". I can see it on the category "SHORTCUTS FOR SELECTED ELEMENT" only if I click right-button on the mouse when my cursor on my custom control. Also when I select my control using the Tab button, it not working too.
Maybe somebody says to me, where I made a mistake or how I can run my shortcut?)

$dyn.controls.MyControl.prototype = $dyn.extendPrototype($dyn.ui.Control.prototype, {
        click: function (event) {
            //Do something
        },
        Shortcuts: $dyn.extendPrototype($dyn.controls.Form.prototype.Shortcuts, {
            MyCustomShortcut: {
                Keys: { ctrl: true, shift: true, keyCode: $dyn.ui.KeyCodes.letterV },
                Handler: function (event) {
                    //Do the same logic when click control
                },
                Description: $dyn.label('MyControlLabel'),
                Category: $dyn.ui.ShortcutCategory.ElementAction
            },
        })
    });

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37fa074b-1f45-3dbc-7af4-557f92360f6e
* Version Independent ID: 3c68b75f-11fa-b0eb-9645-b646f5b6a0bc
* Content: [Keyboard shortcuts for extensible controls - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/user-interface/keyboard-shortcuts-controls)
* Content Source: [articles/dev-itpro/user-interface/keyboard-shortcuts-controls.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/user-interface/keyboard-shortcuts-controls.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RobinARH
* Microsoft Alias: **robinarh**

**Comment by sericks007** [comment]
Bug 325475 has been logged to track this issue.

**Comment by jasongre** [comment]
The shortcut is showing up under "Shortcuts for the selected element" because you selected the "ElementAction" category for the shortcut. 

Regarding adding a shortcut to the form, this is not currently supported. My recommendation is to visit the [Ideas portal](https://experience.dynamics.com/ideas/categories/?forum=0c1b9821-94e0-e911-a812-000d3a4f13c0&forumName=Dynamics%20365%20Finance%20and%20Operations%20Cross-Apps) and vote on an existing suggestion for this (if one exists), or create a new suggestion (if one doesn't exist).
