### ISSUE TITLE
DRA supported on Windows Server 2019?

### ISSUE THREAD

**Issue by SteveBurkettNZ** [MicrosoftDocs/dynamics-365-unified-operations-public#1310]
Got a few clients rolling out Windows Server 2019 these days, is it supported to run the DRA on this OS? If so, can the line under the What's Important To Know section on the OS requirements be updated to reflect this please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2128b07d-7349-6642-f05f-c94fe800d104
* Version Independent ID: 0568d0d1-8035-3423-f791-7bd82a5d070f
* Content: [Install the Document Routing Agent to enable network printing - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/install-document-routing-agent#feedback)
* Content Source: [articles/dev-itpro/analytics/install-document-routing-agent.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/install-document-routing-agent.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by sericks007** [comment]
@SteveBurkettNZ, thanks for posting this!

@TJVass, please answer the question, and update the topic as needed.

**Comment by sericks007** [comment]
Bug 325473 has been logged to track this issue.
