### ISSUE TITLE
Which is correct for PRO, 5 seconds or 5 minutes?

### ISSUE THREAD

**Issue by tsyanag** [MicrosoftDocs/dynamics-365-unified-operations-public#1311]
There is a statement regarding D365 SQL RPO as 5 seconds and also another statement little below saying 5 minutes, which confused clients. Can we fix these, even take them out?
------------------
(former one): Azure SQL active-geo replication for primary databases, with a Recovery Point Estimate (RPO) of &lt; 5 seconds.

(latter one): a Recovery Point Objective of 5 minutes
------------------

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 230ae369-93c3-90a0-cf0a-078afb39e621
* Version Independent ID: 22f367a5-3954-11c8-2e72-94a9990d89f3
* Content: [Cloud deployment option - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/deployment/cloud-deployment-overview)
* Content Source: [articles/dev-itpro/deployment/cloud-deployment-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/deployment/cloud-deployment-overview.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @kfend
* Microsoft Alias: **kfend**

**Comment by RobinARH** [comment]
Bug 328749 created to track this issue.

**Comment by kfend** [comment]
Thanks for bringing this to our attention. The recovery point objective was incorrectly stated at 5 minutes and it is in fact, 5 seconds. We have updated the topic and the changes will be reflected in the topic later today.
