### ISSUE TITLE
Unable to get the channel information

### ISSUE THREAD

**Issue by Nirvana115** [MicrosoftDocs/dynamics-365-unified-operations-public#1313]
Hi,

In my Orchestrator in Service fabric:/LocalAgent/BridgeService  i have this error message :

Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: AADSTS700024: Client assertion is not within its valid time range. Trace ID: cdf1bfce-d8d1-459e-b865-883af9511500 Correlation ID: 93c476d1-1d81-4705-bb18-15adae95820d Timestamp: 2019-05-23 18:31:33Z ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized). ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalException: {"error":"invalid_client","error_description":"AADSTS700024: Client assertion is not within its valid time range.\r\nTrace ID: cdf1bfce-d8d1-459e-b865-883af9511500\r\nCorrelation ID: 93c476d1-1d81-4705-bb18-15adae95820d\r\nTimestamp: 2019-05-23 18:31:33Z","error_codes":[700024],"timestamp":"2019-05-23 18:31:33Z","trace_id":"cdf1bfce-d8d1-459e-b865-883af9511500","correlation_id":"93c476d1-1d81-4705-bb18-15adae95820d"}: Unknown error --- End of inner exception stack trace --- --- End of inner exception stack trace ---

Best,

**Comment by kfend** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
