### ISSUE TITLE
The steps written as "Register a web application with AAD" should be updated.

### ISSUE THREAD

**Issue by yoison** [MicrosoftDocs/dynamics-365-unified-operations-public#1315]
The steps written as "Register a web application with AAD" seems to be changed on Azure like the docs below. So the chage of Azure feature should also be reflected on D365FO docs. 
https://docs.microsoft.com/en-us/azure/active-directory/develop/app-registrations-training-guide

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ba7bfc1-7c23-5662-8f2c-b41b19fb9070
* Version Independent ID: 19eb0a4a-1594-8f8b-054c-2c851df17e8b
* Content: [Service endpoints - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/services-home-page#register-a-web-application-with-aad)
* Content Source: [articles/dev-itpro/data-entities/services-home-page.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/services-home-page.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by yoison** [comment]
If you have ETA, please let me know it. Rough schedule is OK.

**Comment by RobinARH** [comment]
Bug 328750 created to track this issue.
