### ISSUE TITLE
What does mean by "turn off the Data Lake storage Gen2 (preview) option"?

### ISSUE THREAD

**Issue by Izmiyash** [MicrosoftDocs/dynamics-365-unified-operations-public#1316]
There is unclear description in the "Create storage accounts" section. in Azure Portal, there are two options for DATA LAKE STORAGE GEN2. enable and disable. we can choose either but not able to turn off. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48cf34e5-5de2-319c-c709-f06ea8fe4164
* Version Independent ID: 1b04f148-d442-f72b-a3b9-3eb4ede9f719
* Content: [Make Entity store available as a Data Lake - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/entity-store-data-lake#feedback)
* Content Source: [articles/dev-itpro/data-entities/entity-store-data-lake.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/entity-store-data-lake.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by RobinARH** [comment]
Bug 328753 created to track this issue.
