### ISSUE TITLE
No information on Authentication

### ISSUE THREAD

**Issue by Sumitranandank** [MicrosoftDocs/dynamics-365-unified-operations-public#1317]
There is no information on how the Authentication should be set in the Power BI report. When the pbix file is created, authentication information is stored in it and then how does it work in conjunction with user credentials from D365 login?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc7d8a19-6471-c70f-0452-74df0eded2f7
* Version Independent ID: a357999b-0336-cf39-a6b2-7cce6164be9e
* Content: [Add analytics to workspaces by using Power BI Embedded - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/add-analytics-tab-workspaces?toc=%2Ffin-and-ops%2Ftoc.json#feedback)
* Content Source: [articles/dev-itpro/analytics/add-analytics-tab-workspaces.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/add-analytics-tab-workspaces.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by RobinARH** [comment]
Bug 328754 created to track this issue.

**Comment by TJVass** [comment]
Details on creating reports for Analytical Workspaces using Power BI Desktop are available in [this article](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/author-distribute-power-bi-reports?toc=/dynamics365/commerce/toc.json). 

F&O automatically updates database connection information for customer environments when deploying reports to the PBI-Embedded service.
