### ISSUE TITLE
Update example

### ISSUE THREAD

**Issue by FH-Inway** [MicrosoftDocs/dynamics-365-unified-operations-public#1320]
The class AtlCreatorProductItem used in the example does not exist. 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9234ad43-0e7f-ed59-ae42-09946e66609e
* Version Independent ID: 68ca360a-d837-5b1f-2954-760cdfd4a72c
* Content: [Creators in the Acceptance test library - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-gb/dynamics365/unified-operations/dev-itpro/perf-test/concepts-creators)
* Content Source: [articles/dev-itpro/perf-test/concepts-creators.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/perf-test/concepts-creators.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @MichaelFruergaardPontoppidan
* Microsoft Alias: **MichaelFruergaardPontoppidan**

**Comment by MichaelFruergaardPontoppidan** [comment]
Thank you.  The example has been updated.
