### ISSUE TITLE
Changed based tracking for deleted record

### ISSUE THREAD

**Issue by ripannandy** [MicrosoftDocs/dynamics-365-unified-operations-public#1323]
On data insertion of any new record for any data entity with changed based tracking, incremental data gets uploaded and upload data can be retrieved accordingly. But when any record gets deleted for any data entity with changed based tracking, no data gets uploaded. How to handle this scenario?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 678ace49-2430-6d7a-b0d9-90388633d31e
* Version Independent ID: 9ba9b3ac-75cf-3bd1-7de0-df20713c85ad
* Content: [Enable change tracking for entities - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/entity-change-track)
* Content Source: [articles/dev-itpro/data-entities/entity-change-track.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/entity-change-track.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by RobinARH** [comment]
@Sunil-Garg and @MilindaV2 - Can you take a look at this one? Thanks.

**Comment by RobinARH** [comment]
Create bug 328755 to track this issue.

**Comment by MilindaV2** [comment]
Deletes are handled in BYOD. I will defer replying on this issue to @sunil

**Comment by puneetdarji** [comment]
@Sunil-Garg - any KB article number to track the progress of enabling CUD event on entities?

**Comment by jaredha** [comment]
@puneetdarji , can you clarify the request? Enabling CUD events on entities is functionality available today. Documentation here:

https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/business-events/data-events

Is this what you're looking for?

**Comment by puneetdarji** [comment]
@jaredha - Our client has reporting solution which reads out data from BYOD. There are masters like customer,vendor, payment terms, etc. which are huge and everytime to read all the records is process intensive. So they want to track if particular record from master is deleted so that they update only that record and take further actions. Is there no way to know in BYOD that this particular record is deleted kind of status?

**Comment by jaredha** [comment]
@puneetdarji - Delete operations are only tracked in change tracking where BYOD is configured to export to your SQL database, and in OData queries against virtual entities using odata.track-changes. Any other data export jobs won't include deletions in the result set. If you are using either of those options and still not seeing deletions in the result set, it may be easier for you to open a support ticket so we can look at the specifics of your export configuration.

**Comment by puneetdarji** [comment]
@jaredha - we do have change tracking enabled for BYOD. Here is the scenario: let say there are 10000 customers in D365 and same are exported to sql DB via BYOD. From these 10000, 1 record is deleted and same record will get deleted from SQL DB(BYOD) as well. Now external system does not know which record got deleted unless they read all records all the time and compare with previous version.

**Comment by jaredha** [comment]
@puneetdarji - thanks for clarifying. Am I understanding correctly that the record is being stored in three databases (D365, BYOD, and the external system)? It sounds like BYOD change tracking is working as designed by deleting the record from BYOD when it's deleted from D365. So this is a question about how to keep the external system in sync with D365 and BYOD, correct?

If that's the case, then the simplest option is likely to use change tracking through the OData endpoints.

https://docs.microsoft.com/en-us/powerapps/developer/data-platform/use-change-tracking-synchronize-data-external-systems
