### ISSUE TITLE
Extra FTP details

### ISSUE THREAD

**Issue by bradsprigg** [MicrosoftDocs/dynamics-365-unified-operations-public#1326]
Please add more info with regards to the type of FTP endpoint required. In what format should the endpoint be? How should the FTP site be secured? Is a self-signed certificate ok? Why is there linked info to an Azure storage account? How can we troubleshoot connection issues?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42b87d2b-70ca-e69c-80df-8128b5190918
* Version Independent ID: 3604d7a8-97aa-c647-63d5-08795dbad316
* Content: [Configure the payroll integration between Talent and Dayforce - Talent | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/talent/configure-payroll-integration#feedback)
* Content Source: [articles/talent/configure-payroll-integration.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/talent/configure-payroll-integration.md)
* Service: **dynamics-365-talent**
* GitHub Login: @andreabichsel
* Microsoft Alias: **anbichse**

**Comment by RobinARH** [comment]
@gregboyko and @andreabichsel - Can you take a look at this one? Thanks.

**Comment by RobinARH** [comment]
Bug 328760 created to track this issue.
