### ISSUE TITLE
New data source's field on a form extension cannot be wrapped in extension class

### ISSUE THREAD

**Issue by ELandAX** [MicrosoftDocs/dynamics-365-unified-operations-public#1329]
Hello,

I found that I cannot create an extension class for a field of the form's data source if the data source was added in a form extension. If the data source is not on a form extension, then I can create extension class.
I am working in PU24.

I get the following error at compile time.
Abnormal termination with unhandled exception. Exception key: ... System.NullReferenceException: Object reference not set to an instance of an object.

Is this solved in any later PUs?
I think it would be good idea to update the documentation.

I also wrote a short blog post about it:
https://elandax.blogspot.com/2019/05/how-to-extend-forms-data-source-field.html

Respectfully,
Evaldas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2b3708d-a8c1-612b-f4f3-9802ad0c5448
* Version Independent ID: d2f14c0f-b695-a234-53ef-864d8e243d14
* Content: [Class extension - Method wrapping and Chain of Command - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/extensibility/method-wrapping-coc)
* Content Source: [articles/dev-itpro/extensibility/method-wrapping-coc.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/extensibility/method-wrapping-coc.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @ChrisGarty
* Microsoft Alias: **cgarty**

**Comment by RobinARH** [comment]
@ChrisGarty @RobinARH  Can you take a look at this one? Thanks.

**Comment by RobinARH** [comment]
Bug 328761 created to track this issue.
