### ISSUE TITLE
The workflow editor does not start after upgrading to platform 25

### ISSUE THREAD

**Issue by Ruveles** [MicrosoftDocs/dynamics-365-unified-operations-public#1330]
Hey guys,
I just want to talk about one thing that can happen after upgrading to platform 25 from previous platforms.
The workflow editor does not start because the AD FS settings for the workflow application do not contain a redirect url https://dynamicsaxworkfloweditor/.
Yes, this url is in the new installation scripts, but if you are upgrading your old environment, you may not be aware of it.

To fix this, you need to add the url https://dynamicsaxworkfloweditor/ to the property "Microsoft Dynamics 365 for Operations On-premises - Workflow - Native application" in the AD FS settings.

Maybe it should be added to the Troubleshooting?

**Comment by RobinARH** [comment]
@ChrisGarty - Can you take a look at this? Thanks.

**Comment by RobinARH** [comment]
Bug 328763 created to track this issue.

**Comment by ChrisGarty** [comment]
Updated https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/organization-administration/workflow-faq via https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/pull/1876
