### ISSUE TITLE
typo: 'customer attributes' should be 'order attributes'

### ISSUE THREAD

**Issue by blackjoker17** [MicrosoftDocs/dynamics-365-unified-operations-public#1331]
"Why and when you should order attributes
If you want to add new fields to cash-and-carry transactions, customer orders, or call center orders, and if you want to capture the information in the POS or Retail headquarters, use customer attributes. "

I think this meant to say 'order attributes' instead of 'customer attributes', as it is talking about order attributes. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e96123e-0790-2800-e1cc-a290851adeb3
* Version Independent ID: 997c19d4-263b-ce07-b228-e0470f17f362
* Content: [Define and set order attributes - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/dev-itpro/order-attributes#feedback)
* Content Source: [articles/retail/dev-itpro/order-attributes.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/dev-itpro/order-attributes.md)
* Service: **dynamics-365-retail**
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by mugunthanm** [comment]
Thanks Peter for the feedback. Updated the document.
