### ISSUE TITLE
GetExecutionErrors ? is this method still available and if so then would this be a part of the documentation ?

### ISSUE THREAD

**Issue by shashisadasivan** [MicrosoftDocs/dynamics-365-unified-operations-public#1333]
GetExecutionErrors - is this method still available and would this be included in the documentation at some point in time ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85d06c76-517e-c0f9-f089-be75a47c1605
* Version Independent ID: 18059b14-4123-298f-51b0-c870f13a9bdc
* Content: [Data management package REST API - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/data-management-api#status-check-api)
* Content Source: [articles/dev-itpro/data-entities/data-management-api.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/data-management-api.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by sericks007** [comment]
@shashisadasivan , thanks for posting this! In the meantime, to get product help you can contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community. 

@Sunil-Garg, please answer the question, and update the documentation, if needed.
