### ISSUE TITLE
Dynamics 365 Finance & Operation Enterprise Licensing for On-Premise

### ISSUE THREAD

**Issue by MadhanRamachandran** [MicrosoftDocs/dynamics-365-unified-operations-public#1334]
Hi,

I have some customer who would like to implement Dynamics 365 Finance & Operation On-Premise system. But it's very difficult to get a clear answer for purchasing Licensing for this model. Based on the 14 Server Role requirements for On-Premise scenario, how many Dynamics 365 Server licensing do I need for each role installation? Client license is straight forward but not Server license, if I got a list of Production server like:

AOS x 3, I believe this role will required 3 Dynamics 365 Server licenses.
Orchestration x 3, Do I need any licensing for this three Orchestration? It's just a Service Fabric Server which use to download and update Component.
MR x 2, Again, any licensing need for Management Report Role?
SSRS x 1, This is definitely required SQL Server License. 
AD x 3 & SQL x 2 licensing is quite simple using the same old standard licensing.

Please provide the suggestion for the purchasing the license.

**Comment by sericks007** [comment]
@MadhanRamachandran, thanks for posting this.  I've been advised that you should contact Support, as described here: Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support)
