### ISSUE TITLE
Import composite entity (XML) through API

### ISSUE THREAD

**Issue by Dacesilian** [MicrosoftDocs/dynamics-365-unified-operations-public#1335]
I'm trying to import composite (XML) entity to D365 through API. I'm using the same way for which other entites work flawlessly - upload to blob storage and call ImportFromPackage. But for composite entity, error is thrown:

`Exception occurred while executing action ImportFromPackage on Entity DataManagementDefinitionGroup: A data project must exist before importing a package consisting of a composite data entity.`

It's the only one entity in the ZIP package.
I'm using Installed platform version : Update26 (7.0.5257.35417).

What can I do now? Thanks.

**Comment by sericks007** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
