### ISSUE TITLE
scenarios is mispelled 'scenarious'

### ISSUE THREAD

**Issue by blackjoker17** [MicrosoftDocs/dynamics-365-unified-operations-public#1337]
scenarios is mispelled 'scenarious' in this sentence in the 4th paragraph.
"In most cases, you should be able to test using Cloud POS, expect if you want to test for offline scenarious. "

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3f32de8-6477-a7ae-f2f1-2b4b912f1d01
* Version Independent ID: 93e6ef2e-18ca-f32c-4d67-ef0a560d504b
* Content: [Development in cloud-hosted development environments without admin access - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/dev-itpro/cloud-dev-box#feedback)
* Content Source: [articles/retail/dev-itpro/cloud-dev-box.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/dev-itpro/cloud-dev-box.md)
* Service: **dynamics-365-retail**
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by sericks007** [comment]
@blackjoker17, thanks for letting us know!  I've fixed the typo, and the updated topic will be published later today.
