### ISSUE TITLE
Run time length

### ISSUE THREAD

**Issue by nataku6262** [MicrosoftDocs/dynamics-365-unified-operations-public#1342]
When running this job we allowed a 4 hour window (240 minutes) however this task ran for 7 hours, until it had rebuilt the number of indexes defined in Count of Indexes. Does this prioritise number of indexes to target over the allowed time to run?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28e18001-d6d3-5a57-d0b6-34959612bce5
* Version Independent ID: 724d9573-fa2e-7588-6e4f-9f47a2546a05
* Content: [Batch job to handle SQL index defragmentation - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/sysadmin/batch-job-sql-defragmentation#feedback)
* Content Source: [articles/dev-itpro/sysadmin/batch-job-SQL-defragmentation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/sysadmin/batch-job-SQL-defragmentation.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @sericks
* Microsoft Alias: **ganas**

**Comment by RobinARH** [comment]
Created bug 330272 to track this issue.
