### ISSUE TITLE
File System Repository onPrem

### ISSUE THREAD

**Issue by matC90** [MicrosoftDocs/dynamics-365-unified-operations-public#1345]
hi,
I created a File System repository for import GER in D365 onPrem v10.
Donwloaded the lcs zip file and extracted to C:\Temp\SolutionRepository\ locally in ORC VM.
But when i try to Open the repository I get a "We didn't find anything to show here." some know issue? or missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef06186c-5341-5476-f29a-c777b8e13b91
* Version Independent ID: 3f4ed82f-e195-0bf6-716d-4d1f37894021
* Content: [Import Electronic reporting (ER) configurations - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/electronic-reporting-import-ger-configurations)
* Content Source: [articles/dev-itpro/analytics/electronic-reporting-import-ger-configurations.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/electronic-reporting-import-ger-configurations.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @NickSelin
* Microsoft Alias: **nselin**

**Comment by NickSelin** [comment]
As described in the https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/general-electronic-reporting page, the file system repository provides access to the list of configurations that are located as xml files in the specific folder of the local file system of the machine where the AOS service is hosted. Therefore, use the C:\Temp\SolutionRepository\ in the FS1AOS01 VM, not in the ORC VM.

**Comment by matC90** [comment]
thanks, i missed that part
tried into AOS and it's works
