### ISSUE TITLE
PurchPurchaseOrderModern report may not working as expected

### ISSUE THREAD

**Issue by FangyuanHou** [MicrosoftDocs/dynamics-365-unified-operations-public#1347]
We need to add one line under the class PrintMgmtReportFormatPopulator_Extension::populate method. there are some similar code added for other reports but not for this one. PurchPurchaseOrder has PurchaseOrderRequisition and PurchaseOrderConfirmationRequest.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dba24ab6-e8c4-c6b3-ecb5-1f6d7d06bd5d
* Version Independent ID: 2530db65-c1b4-1b2e-04d4-1c6bffb43011
* Content: [Install modern report design templates - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/install-modern-report-design-templates#feedback)
* Content Source: [articles/dev-itpro/analytics/install-modern-report-design-templates.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/install-modern-report-design-templates.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by RobinARH** [comment]
@TJVass Can you take a look at this one? Thanks.

**Comment by RobinARH** [comment]
Created bug 330274 to track this issue.

**Comment by RobinARH** [comment]
Thanks for the feedback. This is a product issue, not a doc issue, and we've contacted the product team.
