### ISSUE TITLE
Option to copy Financial reporting database

### ISSUE THREAD

**Issue by manishmoothedath** [MicrosoftDocs/dynamics-365-unified-operations-public#1349]
Hi,
the statement in this page - "A database refresh lets you copy the transactional and financial reporting databases of your production environment into the target, sandbox UAT environment. If you have another sandbox environment, you can also copy the databases from that environment to your target, sandbox UAT environment."
there is no option in the "Move database" to export a copy of financial reporting database, the export option is available only for Product database (AxDB). Could you please clarify how to export financial reporting database from a Sandbox to LCS?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15a09763-c088-80d0-b7c4-3eb7ff337017
* Version Independent ID: 42d1dcda-ca5d-3bb2-7e56-b080ee4a2dd4
* Content: [Refresh database - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/database-refresh)
* Content Source: [articles/dev-itpro/database/database-refresh.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/database/database-refresh.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @laneswenka
* Microsoft Alias: **laneswenka**

**Comment by RobinARH** [comment]
@laneswenka @sericks007 @kfend Lane - Can you take a look at this? Thanks.

**Comment by RobinARH** [comment]
Created bug 330275 to track this issue.

**Comment by HristoFilipov82** [comment]
Hello, Is it possible to do a database refresh from Tier-1 environment to Tier-2 environment using self-service database refresh?

**Comment by laneswenka** [comment]
It is not supported to export a financial reporting database.
