### ISSUE TITLE
Outdated data

### ISSUE THREAD

**Issue by LuisFilipeFernandes** [MicrosoftDocs/dynamics-365-unified-operations-public#1350]
The current solution of D365 F&O is not compatible with the instructions described on this article. Steps 2, 3 and 5 are not applicable according to the current solution code. If following the remaining tasks you end up with a VS solution that does not build due to several errors. Looking forward for updated instructions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 037bc124-9c48-4f09-3b15-ab7ea2c2241d
* Version Independent ID: 4311fb0b-3f50-7d44-578b-a53debcf162c
* Content: [Create and apply branding to the Retail Experience app - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/dev-itpro/create-retail-experience-app#feedback)
* Content Source: [articles/retail/dev-itpro/create-retail-experience-app.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/dev-itpro/create-retail-experience-app.md)
* Service: **dynamics-365-retail**
* GitHub Login: @josaw1
* Microsoft Alias: **shajain**

**Comment by RobinARH** [comment]
@ShalabhjainMSFT @RobinARH Shalabh - Can you take a look at this? Thanks.

**Comment by RobinARH** [comment]
Created bug 330276 to track this issue.

**Comment by RobinARH** [comment]
The doc is updated. - Robin
