### ISSUE TITLE
Incosistent information regarding pausing

### ISSUE THREAD

**Issue by sfmhe** [MicrosoftDocs/dynamics-365-unified-operations-public#1352]
According to https://cloudblogs.microsoft.com/dynamics365/bdm/2019/06/03/new-flexible-service-updates-for-dynamics-365-for-finance-and-operations/ pausing 3 (!) consecutive updates is possible now. Here we read about just 2. What is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c296e1c-432e-8fb3-e9d8-a87c26d9b59d
* Version Independent ID: b4b2af10-17e2-1878-c8c2-2319471bbc79
* Content: [Pause service updates through Lifecycle Services (LCS) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/pause-service-updates#feedback)
* Content Source: [articles/dev-itpro/lifecycle-services/pause-service-updates.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/lifecycle-services/pause-service-updates.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @manalidongre
* Microsoft Alias: **manado**

**Comment by sericks007** [comment]
@sfmhe, thanks for letting us know!

@manalidongre, please update the topic as appropriate.

**Comment by tonyafehr** [comment]
Bug 330575 has been logged to track this issue.

**Comment by eSBe-365** [comment]
Also, there isn't a "Pause Update" option that switches to "On" and "Off"
There is a random toggle that is "Yes" and "No"
