### ISSUE TITLE
Customer reported incpmplete documentation steps and aks, if we can please add the missing ones to this article.

### ISSUE THREAD

**Issue by mueckeflo** [MicrosoftDocs/dynamics-365-unified-operations-public#1353]
Feedback provided by customer:

There were also needed the resource-files containing localized strings. It took quite some reverse engineering to figure this out, as there was no mentioning of them in the deployment guideline. Furthermore, the code required a change of namespace to fit the <AssemblyNamePrefix> setting from Customization.settings. This propagated quite a lot of work, as more projects also needed their namespace changed to re-establish the references.

In addition, it is still not entirely clear to me how to register the resource-files in Customization.settings for deployment through Retail Deployment Package.

---------------

Pleasee add this content, if possible.
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8849226b-0bc6-0ec0-de5d-7b8f762594b5
* Version Independent ID: c4838143-6bb0-3abe-f377-e1e59904ddc8
* Content: [Deployment guidelines for cash registers for Norway - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/localizations/emea-nor-loc-deployment-guidelines?tabs=retail-8-1-1#feedback)
* Content Source: [articles/retail/localizations/emea-nor-loc-deployment-guidelines.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/localizations/emea-nor-loc-deployment-guidelines.md)
* Service: **dynamics-365-retail**
* GitHub Login: @AlexChern0v
* Microsoft Alias: **v-alexec**

**Comment by sericks007** [comment]
@mueckeflo, thanks for posting this!

@AlexChern0v, please review and update the topic appropriately.

**Comment by sericks007** [comment]
@EvgenyPopovMBS, please review and update the topic appropriately.

**Comment by sericks007** [comment]
Bug 330744 has been logged to track this issue.
