### ISSUE TITLE
D365FO documentation

### ISSUE THREAD

**Issue by maveloso** [MicrosoftDocs/dynamics-365-unified-operations-public#1354]
This page only refers to AX2012 upgrades. where is the D365FO upgrade analysis tool documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 521be614-6472-95d5-72bf-6e49c84ad3ba
* Version Independent ID: 4a556b59-c985-d0ec-c8d8-8f1d901801a1
* Content: [Upgrade analysis in Lifecycle Services (LCS) - AX 2012](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/ax-2012/upgrade-analysis-lcs)
* Content Source: [articles/dev-itpro/lifecycle-services/ax-2012/upgrade-analysis-lcs.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/lifecycle-services/ax-2012/upgrade-analysis-lcs.md)
* Product: **dynamics-ax-2012**
* GitHub Login: @RobinARH
* Microsoft Alias: **robadawy**

**Comment by sericks007** [comment]
@maveloso, thanks for posting this!

@robadawy or @laneswenka, could you please review and suggest a topic.

**Comment by sericks007** [comment]
Bug 330746 has been logged to track this issue.

**Comment by laneswenka** [comment]
Upgrade analysis is not applicable with OneVersion.  When upgrading from 7.x to 8.0+ you will require re-writting your overlayers as extensions and removing all X++ hotfixes (Microsoft packages) from your version control as X++ KBs are no longer supported.
