### ISSUE TITLE
Link incorrect

### ISSUE THREAD

**Issue by RobvanB** [MicrosoftDocs/dynamics-365-unified-operations-public#1355]
The link to the powerapps admin page under 'Templates and Tasks' is incorrect

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a0b764a-dd6b-581b-5d94-50e2af76c360
* Version Independent ID: 9eadf0e8-a4d2-6eb6-93f6-f4ba3a4ba2d0
* Content: [Synchronize products directly from Finance and Operations to products in Sales - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/sales-marketing/products-template-mapping-direct)
* Content Source: [articles/supply-chain/sales-marketing/products-template-mapping-direct.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/sales-marketing/products-template-mapping-direct.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @ChristianRytt
* Microsoft Alias: **crytt**

**Comment by ChristianRytt** [comment]
Thank you for reporting this, I have updated the link and the change should be available in a few days – now without preview in the link.
