### ISSUE TITLE
Mandatory Fields

### ISSUE THREAD

**Issue by kchaiser** [MicrosoftDocs/dynamics-365-unified-operations-public#1359]
I  often get request to make certain fields mandatory on forms. It would be great if personalization and saved views supported making field mandatory. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8523f95-cfbd-dc55-e36a-0dc6f3cb784d
* Version Independent ID: fdc89723-2d01-0d82-1931-79778ffb9646
* Content: [Build forms that fully optimize saved views - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/user-interface/understanding-saved-views#feedback)
* Content Source: [articles/dev-itpro/user-interface/understanding-saved-views.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/user-interface/understanding-saved-views.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by jasongre** [comment]
Thanks for the suggestion! This one of the personalization enhancements we're considering. Please vote for it on the Ideas portal: Ability to make a field mandatory by personalizing form (https://experience.dynamics.com/ideas/idea/?ideaid=1149e17c-d2c8-e711-80c0-00155d7cd0b4#(
