### ISSUE TITLE
"End of Service" Title

### ISSUE THREAD

**Issue by JoelLeichty** [MicrosoftDocs/dynamics-365-unified-operations-public#1360]
End of service title is confusing with the new policy. I believe this column means "End of hotfix support", even though the date is extended on how long you can use that particular version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1892de7-0902-054b-e430-8e23f714477b
* Version Independent ID: 20e0ff84-5f29-f5e3-ddde-288e52059ad0
* Content: [Service update availability - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/public-preview-releases)
* Content Source: [articles/fin-and-ops/get-started/public-preview-releases.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/public-preview-releases.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @meeramahabala
* Microsoft Alias: **meeram**

**Comment by meeramahabala** [comment]
Thanks for the feedback. We will look into changing the title to better reflect the state.
