### ISSUE TITLE
SSRS scale out

### ISSUE THREAD

**Issue by ahmerkhalid636** [MicrosoftDocs/dynamics-365-unified-operations-public#1363]
I am deploying the Dynamics 365 on premises environment with DR-Site. Please help me regarding the configuration of SSRS server on both site.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e67ea12d-2a68-cda6-ecfb-9e7ca852d149
* Version Independent ID: 88c57c99-c6d9-0c05-5b3a-1cb28be236e6
* Content: [Configure SQL Server Reporting Services for on-premises deployments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/configure-ssrs-on-premises)
* Content Source: [articles/dev-itpro/analytics/configure-ssrs-on-premises.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/configure-ssrs-on-premises.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @sarvanisathish
* Microsoft Alias: **sarvanis**

**Comment by RobinARH** [comment]
@sarvanisathish - Can you take a look? Thanks.

Your request might be beyond the scope of the docs, and you might considering contacting Support. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

**Comment by RobinARH** [comment]
Bug 332158 created to track this issue.

**Comment by sericks007** [comment]
@PeterRFriis, can you help here?

**Comment by PeterRFriis** [comment]
I think this should go through CSS and not through docs.
I would recommend closing this, and then ask the customer to create a customer support case.
Right now we do not have an official DR-documentation, setting up the SSRS will require both screenshares and talks regarding their specific setup.

**Comment by sericks007** [comment]
Thanks for the response, @PeterRFriis!

Closing this issue.  @ahmerkhalid636, please consider contacting Support. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support).
