### ISSUE TITLE
Link to the provisioning guide does not work

### ISSUE THREAD

**Issue by tino80** [MicrosoftDocs/dynamics-365-unified-operations-public#1366]
The link to the provisioning guide does not work and I can't find it elsewhere on customersource or partnersource. Can someone provide me with the guide?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e859ad9-22e1-e14e-2c7a-6df3ba1482ca
* Version Independent ID: 6eff91da-e5c3-3fcd-00f2-2fd690e7cc15
* Content: [Buy Finance and Operations (on-premises) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/purchase-on-premises#feedback)
* Content Source: [articles/fin-and-ops/get-started/purchase-on-premises.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/purchase-on-premises.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @maertenm
* Microsoft Alias: **maertenm**

**Comment by tonyafehr** [comment]
@tino80, thanks for bringing this to our attention. We're working to resolve this issue and will let you know when a working link is available.  

@ShellyBakke, please help to resolve this issue.

**Comment by tonyafehr** [comment]
Bug 332477 has been logged to track this issue.

**Comment by yusufghazi** [comment]
This is resolved now. Links are working.

**Comment by petersonfs** [comment]
The link provided in the documentation isn't working. There is a new link?

**Comment by tonyafehr** [comment]
Which link is not working? I've tested all of them and cannot find any that do not work.
