### ISSUE TITLE
Needs more details

### ISSUE THREAD

**Issue by MSFTRANDY** [MicrosoftDocs/dynamics-365-unified-operations-public#1367]
This is a very generic article that doesn't explain what Yes/No actually affects, nor does it cover all Posting parameters such as "Tax calculation behavior" that we're trying to figure out how it works.  This article simply states, Select "Yes" but there is much more to each feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4dd9fa33-50a2-6225-beca-9f607bc89970
* Version Independent ID: b054f53f-6226-8da1-f1c0-d32be3b1f451
* Content: [Parameter configurations for Retail statements - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/tasks/parameter-configurations-retail-statements)
* Content Source: [articles/retail/tasks/parameter-configurations-retail-statements.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/tasks/parameter-configurations-retail-statements.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by tonyafehr** [comment]
@MSFTRANDY, this topic was generated using Task recorder, so it's very basic and only meant to explain the simple steps needed to perform this task. We will review your feedback and considering adding content to provide more detail that is not standard in topics that have been created using Task recorder. 

@josaw1, please review this feedback, thanks!
