### ISSUE TITLE
path and menu item for Field descriptions page

### ISSUE THREAD

**Issue by SiccoAntuma** [MicrosoftDocs/dynamics-365-unified-operations-public#1368]
path and menu item for Field descriptions page:

path=Common>Inquiries>Field descriptions
mi=FieldDescriptions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8ec8bc2-61dd-085d-ba77-4cf9dd87cd4c
* Version Independent ID: 0492844e-fa69-4556-146e-de22da7e61a7
* Content: [View and export field descriptions - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/view-export-field-descriptions)
* Content Source: [articles/fin-and-ops/get-started/view-export-field-descriptions.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/view-export-field-descriptions.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @rschloma
* Microsoft Alias: **rschloma**

**Comment by sericks007** [comment]
Thank you for the feedback.  Our team has reviewed this feedback and decided not to make any updates to this content at this time.

**Comment by ugprashanth0912** [comment]
Thanks for the path. Was not familiar with this feature(relatively new feature?) and found the path was very useful. Will be good to include that in the page.
