### ISSUE TITLE
Description out dated

### ISSUE THREAD

**Issue by Izmiyash** [MicrosoftDocs/dynamics-365-unified-operations-public#1369]
still referring the Preview menu in the case Flow does not triggered ( System parameters &gt; Business events - Preview tab). Need to update accordingly as it's no longer Preview.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eeceffe9-8dec-90db-7c94-56b7a5632523
* Version Independent ID: fd7ce083-1363-ffc9-9ffe-4833f8204791
* Content: [Troubleshoot business events - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/business-events/troubleshooting#feedback)
* Content Source: [articles/dev-itpro/business-events/troubleshooting.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/business-events/troubleshooting.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by sericks007** [comment]
@Izmiyash, thanks for posting this!

@Sunil-Garg, please review and update the content as necessary.

**Comment by sericks007** [comment]
Bug 332881 has been logged to track this issue.

**Comment by valerymoskalenko** [comment]
Any updates on this?

**Comment by sericks007** [comment]
@Sunil-Garg, please review and update the content as necessary.

**Comment by Sunil-Garg** [comment]
Thanks all for highlighting this issue. The Flow scenario is now updated.
