### ISSUE TITLE
Improve code snippets

### ISSUE THREAD

**Issue by FH-Inway** [MicrosoftDocs/dynamics-365-unified-operations-public#1370]
I suggest to improve the code snippets in this guide. Currently they are a mix of screenshots of code (which cannot be copied) and unformatted code that is hard to read. Ideally, all code snippets should look like the first snippet after [Creating the controller](https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/warehousing/process-guide-framework#creating-the-controller).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad2b22dd-7062-041c-b5ad-2a60dde9a2e5
* Version Independent ID: 6ec4dd1a-86f0-5d27-417f-508ba00d0ab6
* Content: [Process guide framework - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/warehousing/process-guide-framework#feedback)
* Content Source: [articles/supply-chain/warehousing/process-guide-framework.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/warehousing/process-guide-framework.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @MarkusFogelberg
* Microsoft Alias: **mafoge**

**Comment by sericks007** [comment]
@FH-Inway, thanks for making us aware of this!

@MarkusFogelberg, please review and update the content, as needed.

**Comment by sericks007** [comment]
Bug 332883 has been logged to track this issue.

**Comment by MarkusFogelberg** [comment]
The code shown in this guide is in the product today. You can view it on your own with a dev environment, this is a better approach if you need to copy the code to new classes.

**Comment by FH-Inway** [comment]
Thanks for the feedback. I used the guide to implement a new process and would have found it easier if I had been able to copy the code directly from the guide. But as I mentioned in the issue description, the main issue is that the different styles of the code snippets makes reading and understanding the guide harder than it needs to be.

**Comment by RobinARH** [comment]
Hi - I converted the images to text so that you can cut-and-paste. The new content will be available in the next couple of days. -Robin

**Comment by FH-Inway** [comment]
Thank you, looks good now.
