### ISSUE TITLE
Information about WHSWorkActivity enum is missing

### ISSUE THREAD

**Issue by FH-Inway** [MicrosoftDocs/dynamics-365-unified-operations-public#1371]
The section on [Creating the controller](https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/warehousing/process-guide-framework#creating-the-controller) mentions the enum WHSWorkExecutionMode, but not the enum WHSWorkActivity. However, both need to be extended to create a new process. This information should be added to the guide.
See https://cloudblogs.microsoft.com/dynamics365/it/2017/07/06/customizing-the-warehousing-mobile-app/ for further information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad2b22dd-7062-041c-b5ad-2a60dde9a2e5
* Version Independent ID: 6ec4dd1a-86f0-5d27-417f-508ba00d0ab6
* Content: [Process guide framework - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/warehousing/process-guide-framework#building-a-new-process-using-the-processguide-framework)
* Content Source: [articles/supply-chain/warehousing/process-guide-framework.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/warehousing/process-guide-framework.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @MarkusFogelberg
* Microsoft Alias: **mafoge**

**Comment by sericks007** [comment]
@FH-Inway, thanks for making us aware of this!

@MarkusFogelberg, please review and update the content as needed.

**Comment by sericks007** [comment]
Bug 332885 has been logged to track this issue.

**Comment by MarkusFogelberg** [comment]
Adding to WHSWorkActivity is needed if the new menu item you create should be shown under indirect activities when configuring the menu item from the mobile device menu item page. As the “Start production order” was an existing process that was refactored to be a process guide, it was already existing in this enum. This guide mainly is about the change in business logic and user interface building of each step that comes with the process guide framework.

**Comment by FH-Inway** [comment]
I appreciate the background information on how the article came to be. For me as someone who implemented a new process using this guide, it came as a suprise that it did not contain all the information necessary to do so (this seems to be implied by the section titled "Building a new process using the ProcessGuide framework"). I think the guide would benefit if it would state clearly what you say in your last sentence ("This guide mainly is about the change in business logic and user interface building of each step that comes with the process guide framework.") and that it does not cover all the things necessary for building a new process. I think it would also benefit by a link to a guide that provides that information.
