### ISSUE TITLE
Might have a typo in the KB

### ISSUE THREAD

**Issue by bacconnaise** [MicrosoftDocs/dynamics-365-unified-operations-public#1374]
Hi, can we double-check if the ".com1" is indeed a typos?

Here is the quote: "The permissions SMTP user account is serviceacct@d365forops.onmicrosoft.com1."

thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fcd3b1a-d14e-7738-b4c3-c4aac5a9c791
* Version Independent ID: 85742fde-3ab0-ac8d-77c5-929a53f4a08f
* Content: [Troubleshoot the Office integration - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/office-integration/office-integration-troubleshooting?toc=%2Ffin-and-ops%2Ftoc.json#feedback)
* Content Source: [articles/dev-itpro/office-integration/office-integration-troubleshooting.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/office-integration/office-integration-troubleshooting.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @ChrisGarty
* Microsoft Alias: **cgarty**

**Comment by josaw1** [comment]
Thank you for your feedback.
@ChrisGarty, can you please verify and update the topic if needed?

**Comment by RobinARH** [comment]
Bug 335733 created to track this issue.

**Comment by ChrisGarty** [comment]
Removed the account info: https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/pull/1415
