### ISSUE TITLE
'Collection Letter' Drop-Down

### ISSUE THREAD

**Issue by tbarron2** [MicrosoftDocs/dynamics-365-unified-operations-public#1375]
On the 'Creation of Collection Letter' window, it would be nice to understand why the "Collection letter" field has an option of "None".  I'm not sure what purpose that is for. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bffb5971-919f-c1f5-c5de-2d5eba676362
* Version Independent ID: 8f1d627f-09ff-4049-9d8e-e91b7831890d
* Content: [Process collection letters - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/accounts-receivable/tasks/process-collection-letters)
* Content Source: [articles/financials/accounts-receivable/tasks/process-collection-letters.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/accounts-receivable/tasks/process-collection-letters.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @ShivamPandey-msft
* Microsoft Alias: **shpandey**

**Comment by ShivamPandeyMSFT** [comment]
> On the 'Creation of Collection Letter' window, it would be nice to understand why the "Collection letter" field has an option of "None". I'm not sure what purpose that is for.
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: bffb5971-919f-c1f5-c5de-2d5eba676362
> * Version Independent ID: 8f1d627f-09ff-4049-9d8e-e91b7831890d
> * Content: [Process collection letters - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/accounts-receivable/tasks/process-collection-letters)
> * Content Source: [articles/financials/accounts-receivable/tasks/process-collection-letters.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/accounts-receivable/tasks/process-collection-letters.md)
> * Service: **dynamics-ax-applications**
> * GitHub Login: @ShivamPandey-msft
There is no purpose on the "None" option. Is it legacy enum value that has lingered around.

**Comment by josaw1** [comment]
Thank you for your feedback.
@ShivamPandey-msft, can you please take a look?

**Comment by RobinARH** [comment]
Bug 335734 created to track this issue.

**Comment by RobinARH** [comment]
There is no purpose of the "None" option. Is it legacy enum value that has lingered around.
