### ISSUE TITLE
Error in SQL command?

### ISSUE THREAD

**Issue by PeterJarret** [MicrosoftDocs/dynamics-365-unified-operations-public#1376]
I think the fields in the SQL statement to enable a flight are shown in the wrong order.  The FlightingServiceCatalogID (FLIGHTSERVICEID in SQL) is the last field in the table

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c6788e8-dfb0-6108-71ae-e265bad542a2
* Version Independent ID: 68a26703-3d8c-4d46-6f3f-37c30aa79373
* Content: [Data management - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/data-entities-data-packages#feedback)
* Content Source: [articles/dev-itpro/data-entities/data-entities-data-packages.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/data-entities-data-packages.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by josaw1** [comment]
Thank you for your feedback.
@Sunil-Garg, can you please review?

**Comment by RobinARH** [comment]
Bug 335735 created to track this issue.

**Comment by Sunil-Garg** [comment]
Thanks for the feedback. The content has been updated.
