### ISSUE TITLE
Stop and exit the flow when a test case is failed

### ISSUE THREAD

**Issue by pdkhanh** [MicrosoftDocs/dynamics-365-unified-operations-public#1377]
I'm develop a suite of test case and I would suggest that we can have an option that if a test case in suite is failed, the rest of test case should be mark as blocked. It will save the time of execution. 
(Like "AddOperatorFieldsToExcelValidation")
I'm looking forward to looking your feedback.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18d6a0b7-38dc-ddcd-c495-67e3b7498a7c
* Version Independent ID: 36a6bc94-6939-9daf-ad3d-4e0064258172
* Content: [Create and automate user acceptance tests - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/using-task-guides-and-bpm-to-create-user-acceptance-tests#feedback)
* Content Source: [articles/dev-itpro/lifecycle-services/using-task-guides-and-bpm-to-create-user-acceptance-tests.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/lifecycle-services/using-task-guides-and-bpm-to-create-user-acceptance-tests.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @kfend
* Microsoft Alias: **ntecklu**

**Comment by kfend** [comment]
@pdkhanh - Thanks for taking the time to provide feedback on Finance and Operations! Can you use the [Ideas site](https://experience.dynamics.com/ideas/categories/list/) to submit your feedback directly? The ideas site will enable you to receive notifications, vote, and monitor the progress of your idea more closely.
As this is product feedback, and not documentation feedback, I'm closing this issue.
