### ISSUE TITLE
On which Version

### ISSUE THREAD

**Issue by shemais22** [MicrosoftDocs/dynamics-365-unified-operations-public#1379]
Abort button does not appear on my system, starting from which version of D365FO this button is available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a888b13-d579-ee76-4c5a-3d5020c4030c
* Version Independent ID: eb9ccd0a-033c-fa06-f0a9-60e702e2f800
* Content: [Abort an executing batch job - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/sysadmin/batch-abort#feedback)
* Content Source: [articles/dev-itpro/sysadmin/batch-abort.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/sysadmin/batch-abort.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @hasaid
* Microsoft Alias: **hasaid**

**Comment by RobinARH** [comment]
@hasaid - Can you take a look at this? thanks - Robin

**Comment by hasaid** [comment]
This is Available on Platform Update 27
