### ISSUE TITLE
No details on how long snapshots are retained

### ISSUE THREAD

**Issue by s3raph** [MicrosoftDocs/dynamics-365-unified-operations-public#1380]
I'm struggling to find any information on how far back it's possible to use PITR to restore back to.

I remember reading documentation in the past that stated that it was possible to select any 15 minute snapshot from the past 30 days, but this does not appear to be explicitly stated anywhere in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb178b0c-678f-b4df-9f18-eb783eff31d0
* Version Independent ID: 611992f2-4b1e-76b2-e405-f025a4d9b286
* Content: [Database point-in-time restore (PITR) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/database-point-in-time-restore)
* Content Source: [articles/dev-itpro/database/database-point-in-time-restore.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/database/database-point-in-time-restore.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @laneswenka
* Microsoft Alias: **laneswenka**

**Comment by RobinARH** [comment]
@laneswenka - Can you take a look at this one? thanks.

**Comment by RobinARH** [comment]
Bug 335736 created to track this issue.

**Comment by PeterJarret** [comment]
In addition, it isn't clear on this page that you are now able to do a point-in-time restore of Production to a sandbox (which seems to be new in LCS?)

**Comment by laneswenka** [comment]
The original ask in this issue is resolved in the next update
