### ISSUE TITLE
Cannot apply licenses via command prompt anymore

### ISSUE THREAD

**Issue by RobvanB** [MicrosoftDocs/dynamics-365-unified-operations-public#1381]
The command to apply the license via command prompt requires admin privileges - this is no longer available on the newer versions. So what is the new process?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce6f5dff-10da-6b04-bd4d-af056f772acc
* Version Independent ID: 075f0d3a-de0e-a434-c645-bc7c4689e930
* Content: [Independent software vendor (ISV) licensing - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-tools/isv-licensing)
* Content Source: [articles/dev-itpro/dev-tools/isv-licensing.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-tools/isv-licensing.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @robadawy
* Microsoft Alias: **robadawy**

**Comment by RobinARH** [comment]
@robadawy  - Can you take a look at this one? thanks.

**Comment by RobinARH** [comment]
Bug 335737 created to track this issue.

**Comment by robadawy** [comment]
Apply a license via LCS (the same way you do for production environments) when you don't have admin access on the box. The article needs some cleanup.
