### ISSUE TITLE
View name

### ISSUE THREAD

**Issue by anushamnair** [MicrosoftDocs/dynamics-365-unified-operations-public#1383]
[Is it the ReturnTransactioView or RetailTransactionView which is extensible]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fee7d52-3d12-d5c0-0434-2b51cee1502b
* Version Independent ID: 4c0d448e-1e64-a5a8-4df7-a8a77a8014cd
* Content: [What's new or changed in Finance and Operations version 10.0.2 (May 2019) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/whats-new-changed-10-0-2#feedback)
* Content Source: [articles/fin-and-ops/get-started/whats-new-changed-10-0-2.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/whats-new-changed-10-0-2.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @tonyafehr
* Microsoft Alias: **tfehr**

**Comment by tonyafehr** [comment]
@anushamnair, you are referencing something that's not in the [What's new or changed in Finance and Operations version 10.0.2 (May 2019)](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/whats-new-changed-10-0-2) topic. Have you looked at [Extensibility changes in Dynamics 365 for Finance and Operations version 10.0.2](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/extensibility/extensibility-changes-10-2) for this information?
