### ISSUE TITLE
SYSFLIGHTING is not copied during self-service database refresh

### ISSUE THREAD

**Issue by sminozhenko** [MicrosoftDocs/dynamics-365-unified-operations-public#1384]
Hi, When we move DB copy from PROD to sandbox, SYSFLIGHTING table is wiped and we need to set up all flights again in the sandbox. Are there any plans to copy flights too or add information about this behavior to section "Data elements that aren't copied during refresh"?

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15a09763-c088-80d0-b7c4-3eb7ff337017
* Version Independent ID: 42d1dcda-ca5d-3bb2-7e56-b080ee4a2dd4
* Content: [Refresh database - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/database-refresh#feedback)
* Content Source: [articles/dev-itpro/database/database-refresh.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/database/database-refresh.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @laneswenka
* Microsoft Alias: **laneswenka**

**Comment by tonyafehr** [comment]
Thanks for contacting us. Unfortunately we're unable to handle product questions here. You might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community. Also consider adding your request to the [Ideas site](https://experience.dynamics.com/ideas/). 

@laneswenka, adding you for awareness.
