### ISSUE TITLE
Wrong code snipets for body of request 

### ISSUE THREAD

**Issue by mutsun1** [MicrosoftDocs/dynamics-365-unified-operations-public#1385]
This document instructs to add a code to Body of the request, but these are wrong actually because I always get an error as invalid syntax if I copy and pasted them as is on code editor of Logic apps.
These should be fixed with correct codes.

Actual: 
body('Invoke_an_HTTP_request').value
(body('Invoke_an_HTTP_request_2').value)
Body of the request: {"executionId": body('GetExportedPackageURL').value}

Expected :
body('Invoke_an_HTTP_request')?['value']
(body('Invoke_an_HTTP_request_2')?['value'])
Body of the request: {"executionId": body('GetExportedPackageURL')?['value']}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a2009b3-5bd5-0181-0b04-75e4333b3bcc
* Version Independent ID: 162723ef-b111-0b62-cc50-30303449e78c
* Content: [Recurring data export using Azure Logic apps - Talent | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/talent/tutorial-integration-recurring-export#feedback)
* Content Source: [articles/talent/tutorial-integration-recurring-export.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/talent/tutorial-integration-recurring-export.md)
* Service: **dynamics-365-talent**
* GitHub Login: @andreabichsel
* Microsoft Alias: **anbichse**

**Comment by tonyafehr** [comment]
@mutsun1, thank you taking the time to note this issue. We'll update this topic based on your feedback.

@andreabichsel, please update this topic based on this feedback.

**Comment by andreabichsel** [comment]
Thank you for your feedback! I made the changes noted here, and they should be live by eod. I need to do more research for the namespace issues you submitted, so those won't appear in today's publish.
