### ISSUE TITLE
Duplicated sentences  

### ISSUE THREAD

**Issue by mutsun1** [MicrosoftDocs/dynamics-365-unified-operations-public#1386]
The following two sentences are duplicated and should be fixed. 

![image](https://user-images.githubusercontent.com/22488411/59665376-bc10b900-91ed-11e9-818f-feb27bbe4e86.png)

Also, the layout of  ![NOTE] section in above are broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a2009b3-5bd5-0181-0b04-75e4333b3bcc
* Version Independent ID: 162723ef-b111-0b62-cc50-30303449e78c
* Content: [Recurring data export using Azure Logic apps - Talent | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/talent/tutorial-integration-recurring-export)
* Content Source: [articles/talent/tutorial-integration-recurring-export.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/talent/tutorial-integration-recurring-export.md)
* Service: **dynamics-365-talent**
* GitHub Login: @andreabichsel
* Microsoft Alias: **anbichse**

**Comment by tonyafehr** [comment]
@mutsun1, thank you taking the time to note these issues. We'll update this topic based on your feedback.

@andreabichsel, please make the updates noted in this feedback.

**Comment by andreabichsel** [comment]
Thank you for your feedback! I made the changes noted here, and they should be live by eod. I need to do more research for the namespace issues you submitted, so those won't appear in today's publish.

**Comment by mutsun1** [comment]
@andreabichsel thank you for taking care of this issue ! however, I found another duplicated sentences on same page... I will open new issue later

**Comment by andreabichsel** [comment]
Thanks @mutsun1, I took care of this one, too. I appreciate it!
