### ISSUE TITLE
Namespace for URL of the request

### ISSUE THREAD

**Issue by mutsun1** [MicrosoftDocs/dynamics-365-unified-operations-public#1387]
It should add the steps to create and add a namespace to URL for URL of the request or add the link to jump to the document of a namespace on this document.
However, as far as we checked this , we can run DMF API without adding namespace and namespace_guid for D365FO online.
So, we need to add some notes for adding namespace / namespace-guid if there is any condition, or should remove “namespace” and “namespace_guid” if these are not needed to add to DMF API.

~~~
Url of the request: https://<hostname>/namespaces/<namespace_guid>/data/DataManagementDefinitionGroups/Microsoft.Dynamics.DataEntities.ExportToPackage
~~~

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a2009b3-5bd5-0181-0b04-75e4333b3bcc
* Version Independent ID: 162723ef-b111-0b62-cc50-30303449e78c
* Content: [Recurring data export using Azure Logic apps - Talent | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/talent/tutorial-integration-recurring-export)
* Content Source: [articles/talent/tutorial-integration-recurring-export.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/talent/tutorial-integration-recurring-export.md)
* Service: **dynamics-365-talent**
* GitHub Login: @andreabichsel
* Microsoft Alias: **anbichse**

**Comment by tonyafehr** [comment]
@mutsun1, thank you for noting these issues. We'll review this topic based on your feedback.

@andreabichsel, please review this feedback and consider making updates as noted.

**Comment by andreabichsel** [comment]
I'm closing this temporarily while doing some testing, will reopen again asap!

**Comment by sericks007** [comment]
Bug 336501 has been logged to track this issue.
