### ISSUE TITLE
Duplicated sentences 2 

### ISSUE THREAD

**Issue by mutsun1** [MicrosoftDocs/dynamics-365-unified-operations-public#1390]
I found another duplicated sentences on this document like the following. 

![image](https://user-images.githubusercontent.com/22488411/59745531-fb9fd980-92af-11e9-94ff-0764de5b58da.png)

The section – [NOTE] and the sentence is starting with “This sample doesn’t do error checking” are duplicated for each.
According to the contexts of this document, I think we should remove the sentences that are enclosed in Red from this document.. 
Can you please take a look at this ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a2009b3-5bd5-0181-0b04-75e4333b3bcc
* Version Independent ID: 162723ef-b111-0b62-cc50-30303449e78c
* Content: [Recurring data export using Azure Logic apps - Talent | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/talent/tutorial-integration-recurring-export#feedback)
* Content Source: [articles/talent/tutorial-integration-recurring-export.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/talent/tutorial-integration-recurring-export.md)
* Service: **dynamics-365-talent**
* GitHub Login: @andreabichsel
* Microsoft Alias: **anbichse**

**Comment by tonyafehr** [comment]
@andreabichsel, please address this feedback. Thanks!

**Comment by andreabichsel** [comment]
Thanks again @mutsun1! I agree with your suggestions and the changes should be live within an hour or so.
