### ISSUE TITLE
How does this integrate with the Source control and build process

### ISSUE THREAD

**Issue by turbozapekanka** [MicrosoftDocs/dynamics-365-unified-operations-public#1391]
We can have X++ code checked in to DevOps and picked up by a build VM.
Will it work for C# code? If not, please describe the process.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 292aba1a-611d-3c57-b6b3-4ad4c1f609c6
* Version Independent ID: a85180de-f264-3a6a-cd6c-51bb019cecac
* Content: [Write business logic by using C# and X++ source code - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-tools/write-business-logic#scenario)
* Content Source: [articles/dev-itpro/dev-tools/write-business-logic.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-tools/write-business-logic.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @pvillads
* Microsoft Alias: **pvillads**

**Comment by sericks007** [comment]
@turbozapekanka, Thanks for posting this! In the meantime, to get product help you can contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community. 

@pvillads, please review and update the content as needed.

**Comment by sericks007** [comment]
Bug 336503 has been logged to track this issue.

**Comment by jorisdg** [comment]
This is currently not integrated into the standard build pipeline. You would have to manually edit the pipeline to compile and copy the output. We have blogged about one somewhat standard option to accomplish this using dependency XML file: https://community.dynamics.com/365/financeandoperations/b/newdynamicsax/posts/selecting-what-models-are-part-of-the-build-automation-process

However, this is not a great experience and most people familiar with C# and builds can typically edit the build definition to their liking in a simpler way. Additionally, we are working on a newer build pipeline, without VM, which is more standard and will support this correctly out of the box.
As such, we are not planning to update the documentation as the new build is currently in private preview already and should go to a public preview soon.
