### ISSUE TITLE
LCS Asset Library Data Residency?

### ISSUE THREAD

**Issue by PeterJarret** [MicrosoftDocs/dynamics-365-unified-operations-public#1400]
Is there information anywhere about the geographic location of the LCS asset library anywhere?  In particular, where do database exports (bacpacs) reside?  I haven't been able to find a clear answer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53431d28-b101-57eb-84bf-738bdef09ba9
* Version Independent ID: 68aabf63-900f-beb3-21cf-a936c08f6e7a
* Content: [Guide to the GDPR for Finance and Operations - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/gdpr/gdpr-guide#controller-considerations)
* Content Source: [articles/dev-itpro/gdpr/gdpr-guide.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/gdpr/gdpr-guide.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @toddlefor
* Microsoft Alias: **ToddLefor**

**Comment by kfend** [comment]
I think this has been addressed. Please reopen if not.
