### ISSUE TITLE
No Run button

### ISSUE THREAD

**Issue by Helen2018** [MicrosoftDocs/dynamics-365-unified-operations-public#1401]
I don't see the Run button in the background tab. It is confusing. It would be great if you can add a screenshot for reference. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a871fd9c-d6ce-b3e4-8341-ad25095dc28f
* Version Independent ID: 70a42534-b035-8e42-c330-c96f619634b0
* Content: [Configure and run job to post statements - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/tasks/run-job-post-statements#feedback)
* Content Source: [articles/retail/tasks/run-job-post-statements.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/tasks/run-job-post-statements.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by josaw1** [comment]
The topic has been updated and will be republished today. Thanks!
