### ISSUE TITLE
Obsoleted screen shot in the document.

### ISSUE THREAD

**Issue by mutsun1** [MicrosoftDocs/dynamics-365-unified-operations-public#1402]
The screen shot at “5. Change the Is Read Only property to No. This is a known issue. Eventually, the value will be set to Yes or No” in this document is obsoleted and need to update it.

![image](https://user-images.githubusercontent.com/22488411/59910313-9cc39700-944c-11e9-85f3-d8bf4e9be361.png)

Actually, “Order By” is not available for Data Entities that is describes the screen shot in this document.

Actual:
![image](https://user-images.githubusercontent.com/22488411/59910351-a9e08600-944c-11e9-9e8c-fbcc0c18984c.png)

We got the feedback form Customer that this screen shot should be updated with latest UI.
Can you please ask EG to check this UI and update the screen shot? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a037761e-9ca8-e3b4-af2e-716b01042010
* Version Independent ID: 376f9fa3-bf0f-9f18-bddb-71bf0581061a
* Content: [Build and consume data entities - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/build-consuming-data-entities#visually-validate-and-customize-an-entity)
* Content Source: [articles/dev-itpro/data-entities/build-consuming-data-entities.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/build-consuming-data-entities.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by Sunil-Garg** [comment]
Thanks, the screenshot has been updated. Pls provide a day or two for the changes to get published.

**Comment by kfend** [comment]
The changes have now been published.
