### ISSUE TITLE
ExportToPackage-Do we have to input the Execution ID everytime if the Data project is configured for recurring export in Dynamics 365 F&O?

### ISSUE THREAD

**Issue by Anshulsr77** [MicrosoftDocs/dynamics-365-unified-operations-public#1403]
While using the ExportToPackage action in D365 F&O connector in Logic App, it is failing if the execution Id is left blank. The error says - An error has occurred.  InvokeAction - Model state is invalid.

**Comment by kfend** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the[ Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
