### ISSUE TITLE
Because the rules about valid of modes of delivery are maintained only in the Retail headquarters (HQ), the POS client makes a real-time call to fetch the valid modes of delivery for a ship line.

### ISSUE THREAD

**Issue by OksanaKovaliova** [MicrosoftDocs/dynamics-365-unified-operations-public#1405]
Is this statement true? 
All information about valid delivery modes is transferred via 1020 job - so it should be available for POS without real-time call to HQ.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d02bfc4-f592-11e3-a972-d7f8f4cd021b
* Version Independent ID: 3c0135b8-128b-01a5-d9e8-b34815fd0ba0
* Content: [Ship orders from another store by using the Charge send feature - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/charge-send)
* Content Source: [articles/retail/charge-send.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/charge-send.md)
* Service: **dynamics-365-retail**
* GitHub Login: @ashishmsft
* Microsoft Alias: **asharchw**

**Comment by RobinARH** [comment]
@ashishmsft - Can you take a look at this? Thanks.

**Comment by tonyafehr** [comment]
Bug 337704 has been logged to track this issue.

**Comment by ashishmsft** [comment]
@RobinARH @tonyafehr - I don't know how to respond to the actual comment - but there's the feedback from the product group - please help get it communicated on docs.microsoft.com

At time of the order creation, if the origin for the "Ship from" is same as the current channel - then certainly we look for delivery modes information available locally in the channel database. 

If channel id is not the current channel then we make a RTS call and go to back-office HQ to get the delivery options.
