### ISSUE TITLE
Post needs updating for Talent

### ISSUE THREAD

**Issue by tomstalentblog** [MicrosoftDocs/dynamics-365-unified-operations-public#1406]
This post was written for Dynamics 365 for Finance and Operations and needs to be updated for Talent. In F&O there is an option when adding course participants to filter for applicants or contacts. In the same form in Talent, the same filter does not exist and therefore only workers can be added to courses at present. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2750fa1-2d33-335a-91ec-7f5b49040e3f
* Version Independent ID: 2ba3a551-da61-9888-1c3a-45d2dae2d802
* Content: [Set up training courses - Talent | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/talent/courses#feedback)
* Content Source: [articles/talent/courses.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/talent/courses.md)
* Service: **dynamics-365-talent**
* GitHub Login: @andreabichsel
* Microsoft Alias: **anbichse**

**Comment by andreabichsel** [comment]
Thank you for pointing this out @tomstalentblog! I updated the doc and the change should be live within the hour. Taking this opportunity to put in a plug for your blog at http://www.tomstalentblog.co.uk/ - lots of great info!
