### ISSUE TITLE
How does the power bi desktop connect to AxDW database in the step 2 onwards?

### ISSUE THREAD

**Issue by dhruvinushah** [MicrosoftDocs/dynamics-365-unified-operations-public#1410]
The steps make it look very easy. But can you also include the concept as to how the D365 data suddenly becomes available on '.' or local server? I have tried to think logically about this but i don't understand it clearly. Please shed some light on this topic.
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 691a853f-967c-3059-2d37-8d68c111770b
* Version Independent ID: b14914f6-348c-748d-6a44-8fbff0e2a46d
* Content: [Create analytical reports by using Power BI Desktop - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/author-distribute-power-bi-reports#validating-reports-in-a-demo-environment)
* Content Source: [articles/dev-itpro/analytics/author-distribute-power-bi-reports.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/author-distribute-power-bi-reports.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by tonyafehr** [comment]
@dhruvinushah, thanks for the feedback. 

@MilindaV2, please review and consider updating this topic.

**Comment by tonyafehr** [comment]
Bug 337705 has been logged to track this issue.

**Comment by axaeffect** [comment]
Has this issue resolved?
I'm getting error "Failed to publish Power BI reports..." everywhere.
Thanks!

**Comment by SajeerAssiz** [comment]
This will work only with developer environment, after development publish to power BI it will work

**Comment by dhruvinushah** [comment]
> Bug 337705 has been logged to track this issue.

What's the update on this?
