### ISSUE TITLE
Not working on application release 8 platform 24 customer dev environment cloud hosted

### ISSUE THREAD

**Issue by uzairsaleem75** [MicrosoftDocs/dynamics-365-unified-operations-public#1412]
I tried the sql query on application release 10 PU 26 , its working fine but same process is not working on application release 8 PU 24, anyone have idea about this behaviour?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f2a8d7e-56e8-2ef5-b7a1-4ccf54a6ce1e
* Version Independent ID: 985efdc1-7b47-ad77-4eb9-7bd940547843
* Content: [Maintenance mode - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/sysadmin/maintenance-mode#feedback)
* Content Source: [articles/dev-itpro/sysadmin/maintenance-mode.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/sysadmin/maintenance-mode.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @manalidongre
* Microsoft Alias: **manado**

**Comment by tonyafehr** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the[ Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
