### ISSUE TITLE
D365 Finance and Operation on-premises environment deployment 

### ISSUE THREAD

**Issue by MadhanRamachandran** [MicrosoftDocs/dynamics-365-unified-operations-public#1413]
Hi ,

I have configured the D365 FO on-premises environment and successfully deployed the D365 FO from the LCS after that i am not able to login the application it is not redirecting to the  ADFC login page.

I checked LCS, Service Fabric, AOS Event, ORCH events and I don't see any problem.

Please advice on the same.

**Comment by tonyafehr** [comment]
We're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the[ Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
