### ISSUE TITLE
Module(s)ToRemove.txt

### ISSUE THREAD

**Issue by l-bri** [MicrosoftDocs/dynamics-365-unified-operations-public#1418]
The documentation specifies the file name as "ModuleToRemove.txt"
LCS validation for the deployable package will fail unless you name the file "ModulesToRemove.txt"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3565b319-747b-2aa4-36f0-6296adf930fb
* Version Independent ID: 847c2a77-9613-33ad-4455-bda3924b4286
* Content: [Uninstall a package - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/deployment/uninstall-deployable-package#feedback)
* Content Source: [articles/dev-itpro/deployment/uninstall-deployable-package.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/deployment/uninstall-deployable-package.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @Manado
* Microsoft Alias: **robadawy**

**Comment by tonyafehr** [comment]
Thank you for the feedback. I will update the topic accordingly. 

@robadawy, please note that the topic will be updated to reflect this.

**Comment by slickmoon** [comment]
This topic still mentions the original "ModuleToRemove.txt" line and this bug needs to be reopened.
![image](https://user-images.githubusercontent.com/7530241/62255517-d8d11b00-b440-11e9-9e42-2f83cf15e6eb.png)

**Comment by sericks007** [comment]
@slickmoon, thank you for letting us know.  I've made the fix and the update will be published soon.

**Comment by tclayton72** [comment]
This is incorrect.  Module singular is what both LCS and the PowerShell script that consumes this file expect.  ModuleToRemove.txt is the correct name, just successfully used it.

**Comment by primeitbr** [comment]
> This is incorrect. Module singular is what both LCS and the PowerShell script that consumes this file expect. ModuleToRemove.txt is the correct name, just successfully used it.

Yes @tclayton72 , you're right. I've got an error by using the "plural" file name. I have used it as you said and it worked!

**Comment by l-bri** [comment]
This must be a localisation or LCS area or platform problem then. I went back and edited the file name to the singular in my original uninstall SDP. After uploading to LCS validation will fail in the 

> Validation status
> Invalid - ModuleToRemove.txt is not valid

Renaming to ModulesToRemove.txt works fine (and uninstalled the package at that time)
The package I tested with is on Update 24, and if someone from MS checks the Asset ID that will fail if I name the file ModuleToRemove.txt is 0998e616-b30f-4a9f-924f-9914c96c59c8

**Comment by rsteber** [comment]
The LCS project of my customer still refuses to validate a deployable package with the singular filename.
Are there different versions of LCS online?
Error message:
_Validation status
Invalid - ModuleToRemove.txt is not valid_

The file is located correctly in the AOSService\Scripts\ path.

**Comment by sericks007** [comment]
This issue is apparently not solved.  @laneswenka, can you please review and update the text, if needed?

**Comment by sericks007** [comment]
Bug 7968474 has been logged in the LCS database.

**Comment by rsteber** [comment]
Hi Sally,
Can you please tell me, why this bug was closed?

Can you confirm, that the LCS validation was fixed? Because on our latest upload of a deployable package last night, LCS still demands the wrong filename inside the package.

Thanks,
Roland

**Comment by sericks007** [comment]
Hi @Rsteber, 
I just merged the changes @laneswenka made in [MicrosoftDocs/Dynamics-365-Operations#9229](https://github.com/MicrosoftDocs/Dynamics-365-Operations/pull/9229).  Those changes updated this content - and will be published later today.

If you find that the changes don't resolve this issue, please re-activate this issue.

Thanks!
Sally

**Comment by LeitchP** [comment]
Well, I literally had to rename the file to the Plural for this to work and it's 2023. Has a root cause been logged before the job was closed?
