### ISSUE TITLE
D365 On-Premises Installation 

### ISSUE THREAD

**Issue by MadhanRamachandran** [MicrosoftDocs/dynamics-365-unified-operations-public#1422]
Hi,

I comleted production and sandbox environment installation.
I can sign in  and using sandbox environment, But I can't sign in production.

ADFS login page not open for production.

In ADFS Server:
I have 2 application, and check application link. Its correct.
I checked production topology.xml and I dont have a problem for ADFS Production App.

I checked LCS, Service Fabric, AOS Event, ORCH events and I don't see any problem.

what can i do for this problem?
Thanks.

**Comment by sericks007** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
