### ISSUE TITLE
Out of date instructions

### ISSUE THREAD

**Issue by ptansey** [MicrosoftDocs/dynamics-365-unified-operations-public#1424]
In the section Register the App, #4 refers to Required Permissions when I believe it should be API Permissions
#8 Keys isn't there, it should be Certificates and Secrets

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48cf34e5-5de2-319c-c709-f06ea8fe4164
* Version Independent ID: 1b04f148-d442-f72b-a3b9-3eb4ede9f719
* Content: [Make Entity store available as a Data Lake - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/entity-store-data-lake#feedback)
* Content Source: [articles/dev-itpro/data-entities/entity-store-data-lake.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/entity-store-data-lake.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by sericks007** [comment]
@ptansey, thanks for making us aware of this!

@MilindaV2, please review and update the content accordingly.

**Comment by sericks007** [comment]
Bug 338389 has been logged to track this issue.
