### ISSUE TITLE
Please note what version or platform this is available on

### ISSUE THREAD

**Issue by johnnystruck** [MicrosoftDocs/dynamics-365-unified-operations-public#1425]
Documentation does not include.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6549a2b0-9d82-c1a7-9d2c-e64c87d4cd90
* Version Independent ID: 086760ed-feec-e9c9-94e6-24d4ea666719
* Content: [Feature management overview - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/feature-management/feature-management-overview)
* Content Source: [articles/fin-and-ops/get-started/feature-management/feature-management-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/feature-management/feature-management-overview.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @mikefalkner
* Microsoft Alias: **mfalkner**

**Comment by mikefalkner** [comment]
It was first available in PU27/10.0.3. More changes are coming to add to the capability.  This document is updated when the feature is available in a shipping platform version.

**Comment by POfP** [comment]
Is the "Feature management" data entity available in PU27/10.0.3?

**Comment by mikefalkner** [comment]
It is available in PU28.
