### ISSUE TITLE
Request to add values of encrypted fields to the list in Document the values of encrypted fields

### ISSUE THREAD

**Issue by yoison** [MicrosoftDocs/dynamics-365-unified-operations-public#1426]
A partner in Japan reports us the two values of encrypted fields below and requests to add  them to the list in Document the values of encrypted fields.

**Field name**	**Where to set the value**
PersonnelIntegrationConfiguration.STORAGEACCOUNTCONNECTIONSTRING	Select **System administration** > **Setup** > **Integration configuration** > **Azure storage account connection string**.

BIMEASUREMENTPARAMETERS.AZUREAPPSECRET	Select **System administration** > **Setup** > **System parameters**. On the **Document connections** Tab, in the **AZURE KEY VALUE** group, select **Application Secret**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 277452eb-70c4-3d29-5219-1355a40bb714
* Version Independent ID: a9d425c4-c627-d20f-4098-307eceb2dd07
* Content: [Golden configuration promotion - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/dbmovement-scenario-goldenconfig#document-the-values-of-encrypted-fields)
* Content Source: [articles/dev-itpro/database/dbmovement-scenario-goldenconfig.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/database/dbmovement-scenario-goldenconfig.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @laneswenka
* Microsoft Alias: **laneswenka**

**Comment by laneswenka** [comment]
Updated in latest update
