### ISSUE TITLE
OnDisplayOptionInitialize event is retrieving always the first record

### ISSUE THREAD

**Issue by lucasssfigueredo** [MicrosoftDocs/dynamics-365-unified-operations-public#143]
I am trying to use this event on PU17 and it is always returning the first record when I call sender.cursor(). This way all rows are getting the same colour.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 884d93a9-8fda-5aca-6916-a898fa0a0ad5
* Version Independent ID: 6c30979c-6642-a1a8-0e34-9358d9a0703e
* Content: [What's new or changed in Dynamics 365 for Finance and Operations platform update 15 (March 2018) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/whats-new-platform-update-15)
* Content Source: [articles/fin-and-ops/get-started/whats-new-platform-update-15.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/whats-new-platform-update-15.md)
* Service: **dynamics-ax-platform**
* Product: **unspecified**
* GitHub Login: @tonyafehr
* Microsoft Alias: **tfehr**

**Comment by ShylaThompson** [comment]
Thanks for contacting us. Unfortunately, we can't handle support requests for the product here. To contact support, consider one of the options described here:  https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support
