### ISSUE TITLE
Run configuration validation and template details are not described on this page

### ISSUE THREAD

**Issue by vavd** [MicrosoftDocs/dynamics-365-unified-operations-public#1431]
Hello,

The template functionality has the "Run configuration validation" buttons on top of the page and in the "Template details" section. Could you give info how it was intended to use this feature.

It is not obvious for what the "Template details" section is for. How is to use this section? Please give more info.

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 860f7a29-db39-89cc-cb30-9cb47c74a870
* Version Independent ID: ca1afca3-df7d-b5af-0d52-fe463d03c5e2
* Content: [Configuration data templates - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/configuration-data-templates?toc=/fin-and-ops/toc.json#feedback)
* Content Source: [articles/dev-itpro/data-entities/configuration-data-templates.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/configuration-data-templates.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @mikefalkner
* Microsoft Alias: **mfalkner**

**Comment by tonyafehr** [comment]
@vavd, thanks for the feedback.

@mikefalkner, please review and update the content accordingly.

**Comment by tonyafehr** [comment]
Bug 340048 has been logged to track this issue.

**Comment by mikefalkner** [comment]
The menu item takes either a template (if you come from the top menu) or a single entity (if you come from Template Details > Run Configuration Validation) and checks for any dependencies on that entity. It looks for dependencies that should exist and don’t; dependencies that don’t exist and should; and dependencies which exist across two different entities and can be shared.

The dependencies themselves can be found by using Template Details > Discover Dependencies and seen under Template Details > Dependencies. Most entities in the system have no dependencies. 

A good example of an entity with dependencies is the Vendor Invoice Line entity (VendorInvoiceLineEntity). The dependencies are defined in the metadata relationships on the entity definition. In this case, the lines entity has a relation to the header entity, and the header has a relation to the sublines entity. Both get pulled in as dependencies.

The functionality is not designed for composite entities. 

The functionality was intended to automatically discover dependencies on other entities but it relies on the metadata to make that determination. If the appropriate metadata is not set up to make that determination, it won't find the dependencies. The templates were delivered to provide the correct order for import of data.
