### ISSUE TITLE
Special application usage pattern

### ISSUE THREAD

**Issue by MariaChikitkina** [MicrosoftDocs/dynamics-365-unified-operations-public#1435]
It is mentioned that using a special application usage pattern for the number sequences is not recommended. What is the reason and is there any alternative for the General ledger journal's voucher series?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83b8224a-e177-034e-734b-f8fa1720cb68
* Version Independent ID: 3f4079f5-ea14-b2fc-8cf9-a065e61d5719
* Content: [Set up number sequences on an individual basis - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/organization-administration/tasks/set-up-number-sequences-individual-basis#feedback)
* Content Source: [articles/fin-and-ops/organization-administration/tasks/set-up-number-sequences-individual-basis.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/organization-administration/tasks/set-up-number-sequences-individual-basis.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @sericks007
* Microsoft Alias: **sericks**

**Comment by tonyafehr** [comment]
@MariaChikitkina, thank you for noting this.

@sericks00, please review and update the content accordingly.

**Comment by sericks007** [comment]
@chrisgarty, please review and update the content accordingly.

**Comment by tonyafehr** [comment]
Bug 340050 has been logged to track this issue.
