### ISSUE TITLE
Add documentation for existing best practice rules

### ISSUE THREAD

**Issue by FH-Inway** [MicrosoftDocs/dynamics-365-unified-operations-public#1436]
This seems to be the only place in the documentation on best practice rules. I suggest to add another page/section that details the existing best practice rules with information on when or how they can/should be suppressed. Basically an update for D365 of the existing documentation for AX 2012: https://docs.microsoft.com/en-us/dynamicsax-2012/developer/best-practices-for-microsoft-dynamics-ax-development

See for example the following discussion that shows that some guidance for BPUpgradeCodeLateBoundCall is needed: 
https://www.yammer.com/dynamicsaxfeedbackprograms/threads/99300423933952
https://www.yammer.com/dynamicsaxfeedbackprograms/threads/876654722

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15d3cf22-c316-5df9-4203-88a0add25e2d
* Version Independent ID: c4844080-547b-90f7-0780-eb843294d6b4
* Content: [Write best practice rules - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-tools/author-best-practice-rules)
* Content Source: [articles/dev-itpro/dev-tools/author-best-practice-rules.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-tools/author-best-practice-rules.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @pvillads
* Microsoft Alias: **pvillads**

**Comment by tonyafehr** [comment]
@FH-Inway, thanks for feedback and for providing examples. 

@pvillads, please review and update the content accordingly.

**Comment by tonyafehr** [comment]
Bug 340055 has been logged to track this issue.

**Comment by jorisdg** [comment]
There are several efforts ongoing to review BP rules, improve them and potentially remove irrelevant ones. I don't expect we will provide any documentation until that exercise has completed. There are also other efforts like AppChecker which will get more information publicized as they become available.
