### ISSUE TITLE
Update X++ system element documentation

### ISSUE THREAD

**Issue by SysC0mp** [MicrosoftDocs/dynamics-365-unified-operations-public#1437]
Is there a schedule on when all the missing pieces in the documentation will be added/updated? (e.g. missing method descriptions, missing parameter information)
There is often only the method name and parameters available which has not much-added value to the information provided in Visual Studio.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79990cab-0ea2-4d76-a9a4-51174295ffa3
* Version Independent ID: 591dd0d8-853d-5ac0-bbcd-2f5ce416f407
* Content: [Q classes - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-ref/q-classes)
* Content Source: [articles/dev-itpro/dev-ref/q-classes.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-ref/q-classes.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RobinARH
* Microsoft Alias: **robinr**

**Comment by tonyafehr** [comment]
@SysC0mp, thanks for your inquiry.

@RobinARH, please review and provide an update if possible.

**Comment by tonyafehr** [comment]
Bug 340058 has been logged to track this issue.

**Comment by RobinARH** [comment]
Hi - At this time, we do not plan to backfill the reference documentation. If you have questions about a particular API, let us know your scenario and we can track down some additional documentation. -Robin
