### ISSUE TITLE
Configure worker account: Time registration tab not in instructions

### ISSUE THREAD

**Issue by pvruyske** [MicrosoftDocs/dynamics-365-unified-operations-public#1438]
"Activate on registration terminals" and all other fields under the Time registration FastTab have been moved to the new Time registration tab. It's no longer situated under the Employment tab as stated in the text.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c9cb448-e8e6-e8e8-401f-7dc1f456df49
* Version Independent ID: 388e1156-e266-cb51-faaa-19030f10c85b
* Content: [Configure a worker using the mobile job device - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/production-control/tasks/worker-mobile-job-device)
* Content Source: [articles/supply-chain/production-control/tasks/worker-mobile-job-device.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/production-control/tasks/worker-mobile-job-device.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @ShylaThompson
* Microsoft Alias: **shylaw**

**Comment by tonyafehr** [comment]
@pvruyske, thanks for the feedback. 

@josaw1, please review and decide if action needs to be taken to update this topic.

**Comment by tonyafehr** [comment]
Bug 340060 has been logged to track this issue.

**Comment by josaw1** [comment]
This is fixed.
