### ISSUE TITLE
Wrong job id

### ISSUE THREAD

**Issue by meneksesaygili** [MicrosoftDocs/dynamics-365-unified-operations-public#1439]
Hi,
I think that it shouldn't be 1040 job. It should be 1070.
"Select the 1040 distribution schedule to sync the new hardware station to the store. Click Run now to sync changes to the POS."
Regards,
Menekse

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a23ac4f5-a8fd-ce83-2f3e-0912d95579d9
* Version Independent ID: 5a3bae91-72db-0e45-cd9b-2f68819fd148
* Content: [Retail peripherals - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/retail-peripherals-overview)
* Content Source: [articles/retail/retail-peripherals-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/retail-peripherals-overview.md)
* Service: **dynamics-365-retail**
* GitHub Login: @rubencdelgado
* Microsoft Alias: **rubendel**

**Comment by tonyafehr** [comment]
@meneksesaygili, thank you for the feedback. 
@rubencdelgado, please review and update the topic if needed.

**Comment by tonyafehr** [comment]
Bug 340062 has been logged to track this issue.

**Comment by tonyafehr** [comment]
This is correct. The document will be updated in the next few days.
