### ISSUE TITLE
[Acceptance Test Library] Errors after generating Entity/Query/Spec

### ISSUE THREAD

**Issue by carbage** [MicrosoftDocs/dynamics-365-unified-operations-public#1441]
When I select a table and generate code, I get a number of errors e.g. he class or interface 'AtlQueryBase' does not exist.

I have made sure to add all the ATL modules as references to the one I am working with - to no avail. I may be missing something but have not seen such errors documented anywhere. Please advise

**Comment by tonyafehr** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
