### ISSUE TITLE
Exported file when choosing XML-Element

### ISSUE THREAD

**Issue by boltlol** [MicrosoftDocs/dynamics-365-unified-operations-public#1442]
Is the BlobStorage file supposed to be in an xlsx format even when choosing xml-element as the export format in data management? At least the xml-element and xml-attribute format generates an xml file which is not readable but when changing the file ending to xlsx it is readable with excel.  ((When will fin&ops support exporting files to Json?))

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a2009b3-5bd5-0181-0b04-75e4333b3bcc
* Version Independent ID: 162723ef-b111-0b62-cc50-30303449e78c
* Content: [Recurring data export using Azure Logic apps - Talent | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/talent/tutorial-integration-recurring-export)
* Content Source: [articles/talent/tutorial-integration-recurring-export.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/talent/tutorial-integration-recurring-export.md)
* Service: **dynamics-365-talent**
* GitHub Login: @andreabichsel
* Microsoft Alias: **anbichse**

**Comment by tonyafehr** [comment]
@andreabichsel, please review and consider updating this topic based on this feedback. 

Meanwhile, to contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

**Comment by boltlol** [comment]
Solved my issue. ExecutionId pointed to an old temp file which was exported earlier as xlsx. recreated job as xml export with new executionid. worked like a charm. Sorry!
