### ISSUE TITLE
Broken link "Resolve conflicts using Visual Studio"

### ISSUE THREAD

**Issue by oathgg** [MicrosoftDocs/dynamics-365-unified-operations-public#1443]
Refers to https://mix.office.com/watch/1rl75ei2cs6d7, which I presume is the wrong link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a99b65e1-360c-5bf6-4f7d-e03cce1eed65
* Version Independent ID: 9aa6e121-7694-1f8e-c51b-301162bac7db
* Content: [Develop and customize - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-tools/developer-home-page)
* Content Source: [articles/dev-itpro/dev-tools/developer-home-page.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-tools/developer-home-page.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RobinARH
* Microsoft Alias: **robinr**

**Comment by tonyafehr** [comment]
@oathgg, thanks for the letting us know about the link. It used to point to an Office Mix, which is no longer supported media, so this is why the link points to information about end of service for Office Mix. We'll look into finding an alternative resource. In the meantime, I will remove the link from this topic. 

@RobinARH, please review and consider possible solutions.

**Comment by tonyafehr** [comment]
Bug 340065 has been logged to track this issue.

**Comment by RobinARH** [comment]
We updated and posted the video, and added a link to the developer home page:

https://www.youtube.com/watch?v=4rxO0zUN2zU
