### ISSUE TITLE
Prerequisites no longer accurate

### ISSUE THREAD

**Issue by andyNewnham** [MicrosoftDocs/dynamics-365-unified-operations-public#1444]
As of last month, there is no longer a need to raise a support request, with the 5 day lead time. (Point 2). I believe the Retail Manage button is now available for all Prod and Tier 2 environments.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31badb53-af9c-66c6-7408-58d481fa228c
* Version Independent ID: b098b405-95a6-de66-6451-bf42e7587da9
* Content: [Initialize Retail Cloud Scale Unit - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/deployment/initialize-retail-channels#feedback)
* Content Source: [articles/dev-itpro/deployment/Initialize-Retail-Channels.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/deployment/Initialize-Retail-Channels.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @AamirAllaq
* Microsoft Alias: **aamiral**

**Comment by tonyafehr** [comment]
@andyNewnham, thanks for commenting on the information in this topic. 

@AamirAllaq, please consider revising this topic based on this feedback.

**Comment by tonyafehr** [comment]
Bug 340067 has been logged to track this issue.
