### ISSUE TITLE
Nested contracts

### ISSUE THREAD

**Issue by Henrik-Grender** [MicrosoftDocs/dynamics-365-unified-operations-public#1453]
Is there any way to make nested contracts, in the sense of having one member returning a list or array of invoice lines. If not, it isn't particuarly useful, and do you have any plans to add this type of support?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be8eb23c-c09a-00c0-1dae-dc7e57484339
* Version Independent ID: 55b1e31c-b00b-c1f0-51b6-6528cc9ff602
* Content: [Business events developer documentation - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/business-events/business-events-dev-doc#feedback)
* Content Source: [articles/dev-itpro/business-events/business-events-dev-doc.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/business-events/business-events-dev-doc.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by tonyafehr** [comment]
@Henrik-Grender, thanks for the feedback. 
@Sunil-Garg, can you address this feedback. Bug 342557 has been logged to track this issue.

**Comment by Sunil-Garg** [comment]
Hello Henrik-Grender, we currently don't have plans to support an array or a list for the payload. An alternate approach could be to concatenate the values and split them back on the consuming end. Please note that, the recommendation is always to keep the payload light weight. Thanks and apologies for this delayed reply.
