### ISSUE TITLE
Getting error 500 after changes in config file

### ISSUE THREAD

**Issue by RakeshDataAnalytics** [MicrosoftDocs/dynamics-365-unified-operations-public#1454]
DYNAMICS 365 Finance and OPERATIONS DEBUG UAT DB ON DEV

Hi I followed the steps mentioned by you, and i am able to connect to SB DB from DEV environment.

I am getting below error:

There is a problem with the server
Sorry, the server has encountered an error. It is either not available or it can't respond at this time. Please contact your system administrator.

Error 500.

Can you please suggest a solution!

Regards,
RAKESH DAMASANI
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4ec2cf9-20fb-cf47-eb1e-a1f987e6ba44
* Version Independent ID: bd7c5fc6-39d2-857e-b8b1-1ee634bd63ec
* Content: [Database movement operations home page - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/dbmovement-operations)
* Content Source: [articles/dev-itpro/database/dbmovement-operations.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/database/dbmovement-operations.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by kfend** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
