### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by glenturnbullazure** [MicrosoftDocs/dynamics-365-unified-operations-public#146]
Under the section 'Subscribe', it says 'Existing customers can find details about how to access trials on CustomerSource....', it looks like the CustomerSource link is broken - should it be the following instead? https://mbs.microsoft.com/customersource/Global/365Enterprise/news-events/news/md365financeoperationsenterprisecusttrial 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c34e22c8-d2cd-8682-8fbd-9cd3a60c4ac6
* Version Independent ID: bd57e53d-7156-6ab9-06de-2b53e561a117
* Content: [Sign up for a preview subscription - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-tools/sign-up-preview-subscription)
* Content Source: [articles/dev-itpro/dev-tools/sign-up-preview-subscription.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-tools/sign-up-preview-subscription.md)
* Service: **dynamics-ax-platform**
* Product: **unspecified**
* GitHub Login: @RobinARH
* Microsoft Alias: **robadawy**

**Comment by MargoC** [comment]
Fixed!
