### ISSUE TITLE
UK scenario where Reverse charge should be setup for correct VAT report

### ISSUE THREAD

**Issue by anboudin** [MicrosoftDocs/dynamics-365-unified-operations-public#1461]
Reverse charge should be setup on specific scenario
* Domestic reverse charge. 
Purchase of UK services, Gold, Computers chips, Mobile phone.
* European service purchase

For European goods (item) purchase, Use tax should be activated on sales tax group. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63712d8a-5d39-7e12-6160-d0e77fbddc14
* Version Independent ID: 3807c237-8aa3-febc-0d01-0109e6d73508
* Content: [GB-00002 Set up reverse charge VAT item groups, rules, and parameters - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/localizations/tasks/gb-00002-reverse-charge-vat-item-groups#feedback)
* Content Source: [articles/financials/localizations/tasks/gb-00002-reverse-charge-vat-item-groups.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/localizations/tasks/gb-00002-reverse-charge-vat-item-groups.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @epodkolz
* Microsoft Alias: **epodkolz**

**Comment by tonyafehr** [comment]
@anboudin, thanks for the feedback. 
@epodkolz, please consider making updates to this topic. 
Bug 342565 has been logged to track this issue.

**Comment by kfend** [comment]
This topic has been updated and the changes will be live in the next 24 hours.
