### ISSUE TITLE
Value is blank when working with POSTMAN

### ISSUE THREAD

**Issue by Sunil-Behera** [MicrosoftDocs/dynamics-365-unified-operations-public#1463]
Tried all the steps exactly identical to the post. It worked. But I am not getting the value.

{
  "@odata.context": "D365URL/data/$metadata#Customers(CustomerAccount,Name,AddressDescription,FullPrimaryAddress)",
  "value": []
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 221bcbdf-2c16-ee9d-f289-75980e35b17a
* Version Independent ID: 6377db2c-d7b7-82bb-baeb-8f2311a9fb87
* Content: [Test services by using third-party utilities - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/third-party-service-test#feedback)
* Content Source: [articles/dev-itpro/data-entities/third-party-service-test.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/third-party-service-test.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**
![Blank value postman](https://user-images.githubusercontent.com/50621465/60728380-715aa500-9f40-11e9-98d0-63d43bc7f270.png)

**Comment by RobinARH** [comment]
@Sunil-Garg Can you take a look? Thanks.

**Comment by RobinARH** [comment]
Created bug 341559 to track this issue.

**Comment by Sunil-Garg** [comment]
Hi Sunil-Behera-- can you check if the user is mapped to a company that has data? Alternatively, have you tried adding 'cross-company=true' to the OData request? One of these should address the issue you are seeing. Thanks.
