### ISSUE TITLE
Unable to get extract setup folder issue

### ISSUE THREAD

**Issue by macchinettid** [MicrosoftDocs/dynamics-365-unified-operations-public#1464]
Another way to solve the "Unable to get extract setup folder" issue is to close ALL Open Files against the File Server related the Asset\WP shared Folders

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d86d2857-6199-f3cb-208b-db4e1cd9f8e2
* Version Independent ID: d425ad9e-6c01-6145-dad5-2af32ffaaff0
* Content: [Troubleshoot on-premises deployments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/deployment/troubleshoot-on-prem)
* Content Source: [articles/dev-itpro/deployment/troubleshoot-on-prem.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/deployment/troubleshoot-on-prem.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @sarvanisathish
* Microsoft Alias: **sarvanis**

**Comment by RobinARH** [comment]
Thanks for the tip!
