### ISSUE TITLE
Primary form pattern instead of secondary

### ISSUE THREAD

**Issue by SysC0mp** [MicrosoftDocs/dynamics-365-unified-operations-public#1466]
The pattern described here is a primary form pattern for dialogs (Dialog - Advanced Selection), no secondary one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d157ade9-9964-cb69-e4f7-68ed3172a137
* Version Independent ID: 3f769aca-565e-8c75-f275-02fbf6fe4cc3
* Content: [Advanced selection form pattern - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/user-interface/advanced-selection-form-pattern)
* Content Source: [articles/dev-itpro/user-interface/advanced-selection-form-pattern.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/user-interface/advanced-selection-form-pattern.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by RobinARH** [comment]
@jasongre Can you take a look? Thanks.

**Comment by RobinARH** [comment]
Bug 341560 created to track this issue.

**Comment by jasongre** [comment]
All dialogs are secondary (supporting) forms, so the Advanced selection pattern is categorized the same as any other dialog pattern.

**Comment by SysC0mp** [comment]
Thanks for the answer! You're right, I had confused the secondary patterns with the subpatterns.
