### ISSUE TITLE
Example uses form pattern "Custom"

### ISSUE THREAD

**Issue by SysC0mp** [MicrosoftDocs/dynamics-365-unified-operations-public#1467]
The example given here (ProcCategoryAddVendor) has form pattern "Custom" assigned and could therefore be misleading.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d157ade9-9964-cb69-e4f7-68ed3172a137
* Version Independent ID: 3f769aca-565e-8c75-f275-02fbf6fe4cc3
* Content: [Advanced selection form pattern - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/user-interface/advanced-selection-form-pattern)
* Content Source: [articles/dev-itpro/user-interface/advanced-selection-form-pattern.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/user-interface/advanced-selection-form-pattern.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by RobinARH** [comment]
@jasongre Can you take a look? Thanks.

**Comment by RobinARH** [comment]
Bug 341561 created to track this issue.

**Comment by jasongre** [comment]
Thanks for pointing it out. That form used to have the Advanced selection form pattern applied (and it still follows the pattern); however, it was removed to add some labels to some buttons.

**Comment by RobinARH** [comment]
Do we need to do anything with the doc?
