### ISSUE TITLE
Filter Power BI Embedded data

### ISSUE THREAD

**Issue by ZakMak9** [MicrosoftDocs/dynamics-365-unified-operations-public#1468]
How is possibile to filter PBIE data in D365 by code?
I want to filter data something like: 
_**PBIReportHelper::initializeReportControl('PBIX Name', powerBIReportGroup, '', true, true, ADD_MY_FILTERS_HERE);**_

I tried to create a filter in thi way:
 _List filter = new List(types::String);
filter.addEnd("DimUser/NAME eq 'User Name'");_

adding it to code above but it seems not working.

thank you for help.

**Comment by RobinARH** [comment]
@TJVass Can you take a look? Thanks.

The PBIReportHelper is mentioned on this page: https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/add-analytics-tab-workspaces

**Comment by RobinARH** [comment]
Bug 341562 created to track this issue.

**Comment by ZakMak9** [comment]
Any news?

**Comment by TJVass** [comment]
Hi ZakMak9,
Unfortunately, we do NOT have any extension points in place that allow app developers to control the default filters for embedded reports.  This is a fantastic feature that I fully support.  I highly recommend that you add this to the [Dynamics Ideas](https://experience.dynamics.com/ideas/categories/?forum=0c1b9821-94e0-e911-a812-000d3a4f13c0&forumName=Dynamics%20365%20Finance%20and%20Operations%20Cross-Apps) site for consideration by R&D team.

One could also imagine that user defined filters would be maintained between report seasons.  These two functions are quite similar and should be delivered in concert.  We appreciate your feedback...!
