### ISSUE TITLE
Example 1: Transactions – dynamic period seesm wrong

### ISSUE THREAD

**Issue by vavd** [MicrosoftDocs/dynamics-365-unified-operations-public#1474]
Hello,

Could you review the example "Example 1: Transactions – dynamic period."

https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/master-planning/reduction-keys#example-1-transactions--dynamic-period

The planned orders look like wrong there.

They should be:
January 1		500	Forecast requirements (= 1,000-500)
January 15	500	Sales orders requirements
February 1	400	Forecast requirements (= 500 – 100)
February 15	100	Sales orders requirements

Please provide more explanations if I'm wrong.

Thanks,
Vadim

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f36dc1d-4d8e-0bb7-317e-6b3cad97b4f6
* Version Independent ID: 8afbf079-6620-a200-af81-4ed147d28dbf
* Content: [Forecast reduction keys - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/master-planning/reduction-keys#example-1-transactions--dynamic-period)
* Content Source: [articles/supply-chain/master-planning/reduction-keys.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/master-planning/reduction-keys.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @roxanadiaconu
* Microsoft Alias: **roxanad**

**Comment by tonyafehr** [comment]
@vavd, thank you for noting this. We will investigate to determine if the topic needs to be updated. 
@ChristianRytt, please review this feedback and consider making updates, if needed.

**Comment by ChristianRytt** [comment]
@vavd  You are absolutely right, there is an error in the numbers. I have updated the forecast and sales order qty to match the result in the example. So now Jan and Feb forecast are both 1,000; Jan sales 200 and Feb sales 400. Giving the original result in the example.
