### ISSUE TITLE
Pause policy is old

### ISSUE THREAD

**Issue by DKobayashi-ykgw** [MicrosoftDocs/dynamics-365-unified-operations-public#1478]
Please update the pause policy according to other docs page [Pause service updates through Lifecycle Services (LCS)](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/pause-service-updates).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14372486-6284-da4b-6bbb-30acd36dd7de
* Version Independent ID: f8301c48-61db-e9e5-aba5-413528cd91d2
* Content: [One Version service updates FAQ - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/one-version)
* Content Source: [articles/fin-and-ops/get-started/one-version.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/one-version.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @meeramahabala
* Microsoft Alias: **meeram**

**Comment by sericks007** [comment]
@DKobayashi-ykgw, thanks for pointing this out!

@Manalidongre, please update the information about pausing service updates found in the [One Version service updates FAQ](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/one-version) topic.

**Comment by sericks007** [comment]
Bug 4948751 (in the ONE database) has been logged to track this issue.
