### ISSUE TITLE
Old references

### ISSUE THREAD

**Issue by ChrisHaleyAvanade** [MicrosoftDocs/dynamics-365-unified-operations-public#1483]
This article still refers to TFS in the 'generate a gap analysis' header (should be DevOps) and 'AX 2012' in the Unconnected flowcharts section (should be Fin & Ops)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e08b918-421f-e740-01c9-a1a274ee360b
* Version Independent ID: 9223490a-d88d-4509-2a09-9ffdfcf8d18b
* Content: [Flowcharts in Business process modeler (BPM) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/flowcharts-business-process-modeler)
* Content Source: [articles/dev-itpro/lifecycle-services/flowcharts-business-process-modeler.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/lifecycle-services/flowcharts-business-process-modeler.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @robadawy
* Microsoft Alias: **robadawy**

**Comment by tonyafehr** [comment]
@ChrisHaleyAvanade, thank you for the feedback.

@robadawy, please consider making updates to this topic based on this feedback. Bug 342553 has been logged to track this issue.

**Comment by kfend** [comment]
We have updated the topic content and changes will be published today or tomorrow.
