### ISSUE TITLE
Duplicate words

### ISSUE THREAD

**Issue by Lexie1919** [MicrosoftDocs/dynamics-365-unified-operations-public#1485]
Right under "Benefit elements", the sentence "Before you begin to create to create benefits ", there is duplicate "to create" here

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ded76cad-76b2-c8ce-1ed7-388446790253
* Version Independent ID: fc8622be-0f81-e6fb-0e69-18680c1592c1
* Content: [Define and manage a benefits program - Talent | Dynamics 365](https://docs.microsoft.com/en-au/dynamics365/unified-operations/talent/manage-benefit-program#feedback)
* Content Source: [articles/talent/manage-benefit-program.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/talent/manage-benefit-program.md)
* Service: **dynamics-365-talent**
* GitHub Login: @andreabichsel
* Microsoft Alias: **anbichse**

**Comment by tonyafehr** [comment]
@Lexie1919, thanks for pointing out this typo, we'll be sure to get it fixed.

**Comment by andreabichsel** [comment]
Updated topic, which should be live in a few minutes. Thanks for catching that!
