### ISSUE TITLE
List of supported OData operations is not present

### ISSUE THREAD

**Issue by MZade** [MicrosoftDocs/dynamics-365-unified-operations-public#1486]
It would be great if the list of supported OData operators is present in the documentation. 
i.e. the "startswith" is not present (verified on PU27).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64b023ab-59fb-87d9-d935-d60d0e9e4139
* Version Independent ID: 10120c96-a72d-60fd-63ff-db9f77e05817
* Content: [Open Data Protocol (OData) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/odata#feedback)
* Content Source: [articles/dev-itpro/data-entities/odata.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/odata.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by RobinARH** [comment]
@Sunil-Garg Can you take a look? Thanks.

**Comment by tonyafehr** [comment]
Bug 342900 has been logged to track this issue.

**Comment by Sunil-Garg** [comment]
Thanks for asking. We will look into providing this information.

**Comment by bhaarathms** [comment]
@MZade could you please share the request that you made with startswith function that worked for you?

**Comment by Sunil-Garg** [comment]
Hi Mehrdad-- the documentation around the list of supported operators have been updated. We will take some more time to update the documentation on other functions of the OData spec including the built-in query functions that you called out. This needs to be fully validated before we publish.

Thanks
