### ISSUE TITLE
Example user mapping file is incorrect

### ISSUE THREAD

**Issue by AndrewJonesA1X** [MicrosoftDocs/dynamics-365-unified-operations-public#1487]
In the User Mapping section, an example of the import file is shown. If you import that file as-is, the first entry (AaronE) will be dropped, as the import expects a header row.

The file should look like this:
_UserId, Email
AaronE, aarone@contoso.com
AaronP, aaronp@contoso.com_
and so on...

**Comment by RobinARH** [comment]
@AndrewJonesA1X Can you tell me which topic you are talking about? Thanks.

**Comment by AndrewJonesA1X** [comment]
Sorry I don't understand how this all works on GitHub. I was trying to add that comment to this page: [https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/prepare-data-upgrade](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/prepare-data-upgrade) - regarding the section titled **Set up user mapping**

**Comment by RobinARH** [comment]
@AndrewJonesA1X Thanks so much for adding that! I'm including the author of that topic.

@ robadawy Hi Robert - Can you take a look at this one? Thanks.

**Comment by AndrewJonesA1X** [comment]
Thanks for fixing it all up!

**Comment by tonyafehr** [comment]
Bug 342901 has been logged to track this issue.
