### ISSUE TITLE
use type from d365fo instead of general type var

### ISSUE THREAD

**Issue by vglu** [MicrosoftDocs/dynamics-365-unified-operations-public#1488]
[Enter feedback here]
>>Example of a break statement

var mainMenu = SysDictMenu::newMainMenu();
var enum = mainMenu.getEnumerator();
var found = false;
while (enum.moveNext())
{
    var menuItem = enum.current();
    if (menuItem.label() == "StringOfInterest")
    {
        found = true;
        break;
    }
}
if (found) 
{
    // do something
}

May we use more D365FO style for description code, please? Use native ax types instead var type. Additional - in D365FO if you are declare boolean variable - you have got default value FALSE - no need to initialize "found" variable.

Yours code in D365FO style should looks like

SysDictMenu                mainMenu = SysDictMenu::newMainMenu();
SysMenuEnumerator    enum         = mainMenu.getEnumerator();
boolean                        found;
while (enum.moveNext())
{
    var menuItem = enum.current();
    if (menuItem.label() == "StringOfInterest")
    {
        found = true;
        break;
    }
}
if (found) 
{
    // do something
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73324288-a542-a567-5ebb-6ec29ee36ab8
* Version Independent ID: 2c04e1ca-567f-3aba-ed37-5f933684c718
* Content: [X++ loop statements - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-ref/xpp-loops)
* Content Source: [articles/dev-itpro/dev-ref/xpp-loops.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-ref/xpp-loops.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RobinARH
* Microsoft Alias: **robinr**

**Comment by RobinARH** [comment]
Thanks for the feedback. The use of "var" is within our guidelines for the use of "var": https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-ref/xpp-variables-data-types#var. Initializing variables, even if the default works in a particular situation, is considered good coding. I plan to leave the example as is for now. - Robin

**Comment by vglu** [comment]
why VAR better?

**Comment by vglu** [comment]
One more notice - why you are initialize "found" variable?
