### ISSUE TITLE
'Organize project by element type' option reset every time

### ISSUE THREAD

**Issue by d47447** [MicrosoftDocs/dynamics-365-unified-operations-public#1489]
Hello,

I am using below version

Installed product version : Microsoft Dynamics 365 for Finance and Operations (10)
Installed platform version : Update24 (7.0.5179.35390)

with this update visual studio option for setting  Organize project by element type is resetting every time I restart the VM. 
Now I have to check this box everytime when I restart my VM which is not expected. 
(this option available under Dynamics365 > Option menu in visual studio. 

![image](https://user-images.githubusercontent.com/10023144/61220969-63aad980-a70f-11e9-8362-2d081ae493ed.png)

**Comment by RobinARH** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
