### ISSUE TITLE
Certificate expiry

### ISSUE THREAD

**Issue by nazmolla** [MicrosoftDocs/dynamics-365-unified-operations-public#1490]
What happens when the ISV License certificate expires? I understand that for new customers we will need to issue the license using the new certificate, but what about existing customers,do we need to reissue new licenses or the old one would keep working?, especially that with new updates they will get the new certificate in the model??

**Comment by RobinARH** [comment]
@robadawy Can you take a look at this one? Thanks.

Also, you might find some relevant information in this topic: https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-tools/isv-licensing

**Comment by nazmolla** [comment]
This is actually where I started from
The problem is it doesn’t describe what happens when the certificate expires. And with D365FO being updated so often, we will need to rebuild our solution so often as well and it doesn’t make sense to keep multiple  parallel tracks or branches to hold each of the expired certificates so our customers won’t need new licenses
And it also is not convenient to reissue licenses annually

**Comment by tonyafehr** [comment]
Bug 342902 has been logged to track this issue.
