### ISSUE TITLE
External web service is accepting static IP, how to achieve in D365 FFO in production

### ISSUE THREAD

**Issue by sannidhianjaneyulu** [MicrosoftDocs/dynamics-365-unified-operations-public#1494]

**Comment by tonyafehr** [comment]
Which topic are you referring to? 

To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

**Comment by sannidhianjaneyulu** [comment]
Hi 
we need to  consuming external  SOAP service from Dynamics 365 for finance and operations. SOAP provider is accepting request from static IP, but Dynamics 365 environment is hosted in azure  and IP will change frequently. SOAP provider will not have the option for DNS white-list. Need to provide static IP to them. Please advice how to achieve this.

**Comment by tonyafehr** [comment]
We're unable to handle Support requests on this site. Please contact Support for your questions. If you have a question or feedback about content in a particular topic, we need to know which topic you are referring to.
