### ISSUE TITLE
Details about Failed Updates

### ISSUE THREAD

**Issue by dferris87** [MicrosoftDocs/dynamics-365-unified-operations-public#1495]
If the Microsoft update fails for a Tier-2 environment, will Microsoft still try and apply the same update to the Production environment?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14372486-6284-da4b-6bbb-30acd36dd7de
* Version Independent ID: f8301c48-61db-e9e5-aba5-413528cd91d2
* Content: [One Version service updates FAQ - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/one-version)
* Content Source: [articles/fin-and-ops/get-started/one-version.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/one-version.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @meeramahabala
* Microsoft Alias: **meeram**

**Comment by tonyafehr** [comment]
We're unable to handle Support requests on this site. Please contact Support or the Communities site for questions like this. To contact Support, go to [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). Or go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

**Comment by dferris87** [comment]
Thank you for the feedback. However, I'm not looking for the cause of an update failure. The article above mentions this:
~~~~~~~~~~~~~~~
If there is a failure, can I reschedule the update to be auto applied?
You will not be able to reschedule the update per se, but you may to apply the package when it is convenient for you, just as you might schedule to apply any other update.
~~~~~~~~~~~~~~~
I would like to know if a failure happens on a Tier-2 environment when Microsoft tries to apply the update, will Microsoft still try and apply the update to a Production environment? I think that this a valid question for this article and am asking for more details related to failures, not specific to any of our environments.

Thank you.

**Comment by tonyafehr** [comment]
@dferris87, thanks for the additional info. 
@meeramahabala, please review this feedback and consider updating this topic.

**Comment by tonyafehr** [comment]
One Version bug # 4968873 has been logged to track this issue.
