### ISSUE TITLE
How do I reference an ISV dimension in the group by clause?

### ISSUE THREAD

**Issue by turbozapekanka** [MicrosoftDocs/dynamics-365-unified-operations-public#150]
or in the field list in the select clause.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c804a717-0730-abb8-7945-255b5549c72e
* Version Independent ID: d477daa0-e599-075a-9ccc-03509aa11e2f
* Content: [Add new inventory dimensions through extensions - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/extensibility/inventory-dimensions)
* Content Source: [articles/dev-itpro/extensibility/inventory-dimensions.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/extensibility/inventory-dimensions.md)
* Service: **dynamics-ax-platform**
* Product: **unspecified**
* GitHub Login: @MichaelFruergaardPontoppidan
* Microsoft Alias: **mfp**

**Comment by MichaelFruergaardPontoppidan** [comment]
As you cannot edit any Microsoft code, I'm assuming you mean in your own code.  Here you can reference your dimension by name in group clauses, field lists, where clauses - just like normal.

**Comment by turbozapekanka** [comment]
I mean ISV code. But as an ISV, we dont know what field from the InventDim is going to be used for mapping in the VAR Implementation, so we can not simply reference e.g. InventDimention1 or 2
The article shows example of the select statement:

//Select statements
select inventDim
    where inventDim.(InventDim::fieldIdISVDim()) == "Some value";

but what if I need to reference fieldIdISVDim in the list of selection fields or in the group by clause?

**Comment by MichaelFruergaardPontoppidan** [comment]
Thanks for clarification.  For field lists you can consider selecting all fields - the performance difference on InventDim is usually not measurable.   If you need a group by or order by, you'll have to use a Query object.

**Comment by MargoC** [comment]
Closing as question has been answered.
