### ISSUE TITLE
Limitation for CoC methods for "Form data fields"

### ISSUE THREAD

**Issue by lemcheyWhite** [MicrosoftDocs/dynamics-365-unified-operations-public#1501]
Hi, Is there any limitation which methods of form data fields could be wrapped by CoC? 
"Validate" method from example works fine, but I tried to wrap "lookup" method and looks like CoC doesn't work for this method. 

The code below compiles without any issues\errors, but the system doesn't hit it.

[ExtensionOf(formdatafieldstr(FormToExtend, DataSource1, Field1))]
final class FormDataField1_Extension 
{ 
    public void lookup(FormControl _formControl, str _filterStr)
    {               
        next lookup(_formControl, _filterStr);

       // do something
    }
}

BR, Sergei

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2b3708d-a8c1-612b-f4f3-9802ad0c5448
* Version Independent ID: d2f14c0f-b695-a234-53ef-864d8e243d14
* Content: [Class extension - Method wrapping and Chain of Command - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/extensibility/method-wrapping-coc)
* Content Source: [articles/dev-itpro/extensibility/method-wrapping-coc.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/extensibility/method-wrapping-coc.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @ChrisGarty
* Microsoft Alias: **cgarty**

**Comment by sericks007** [comment]
@lemcheyWhite, thanks for posting this!

@chrisgarty, please review and update the topic as needed.

**Comment by sericks007** [comment]
Bug 343782 has been logged to track this issue.

**Comment by SysC0mp** [comment]
Currently have the same problem. Lookup extension method is not triggered.

**Comment by josaw1** [comment]
@ChrisGarty please review.

**Comment by josaw1** [comment]
Closing as won't fix.
