### ISSUE TITLE
Difference between Gift card & Loyalty card in offline scenario

### ISSUE THREAD

**Issue by ransoentjens** [MicrosoftDocs/dynamics-365-unified-operations-public#1502]
How come it is possible to pay with a gift card in offline mode, but not with a loyalty card? Both cards have the same nature. What is the reasoning behand this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84a66cd0-7e3f-0509-6450-723cac39513c
* Version Independent ID: c24d3787-026f-9441-30a9-5067c89442e7
* Content: [Retail Modern POS (MPOS) in offline mode - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/dev-itpro/retail-modern-pos-offline)
* Content Source: [articles/retail/dev-itpro/retail-modern-pos-offline.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/dev-itpro/retail-modern-pos-offline.md)
* Service: **dynamics-365-retail**
* GitHub Login: @RobinARH
* Microsoft Alias: **meeram**

**Comment by sericks007** [comment]
@ransoentjens, thanks for posting this!

@hhainesms, please review and update the content as needed.

**Comment by sericks007** [comment]
@ShalabhjainMSFT, please review and update the content as needed.

**Comment by sericks007** [comment]
Bug 343783 has been logged to track this issue.

**Comment by ransoentjens** [comment]
Hi Sally. Is the bug logged to investigate the case. Or what is the insight/conclusion at the moment? What is the exact bug?

**Comment by sericks007** [comment]
The bug is for @ShalabhjainMSFT to investigate and update the content if needed.

**Comment by ShalabhjainMSFT** [comment]
The Gift allows the cashiers to conclude the transaction in offline mode only if the Gift card was added to the transaction when the POS was Online i.e. you cannot initiate the payment by Gift card if the user is in Offline mode. There is no plan yet to support pay by Gift card in offline mode. Similarly, loyalty also does not support offline payment, but unlike Gift card, we do not have a way to conclude the transaction if the loyalty payment was added when the POS was online

**Comment by ransoentjens** [comment]
Clear. Thanks for the feedback, @ShalabhjainMSFT .
