### ISSUE TITLE
"FiscalCalendars" form isn't using tree control as navigation

### ISSUE THREAD

**Issue by SysC0mp** [MicrosoftDocs/dynamics-365-unified-operations-public#1503]
The "FiscalCalendars" form is no longer using a tree control as navigation, so the example should be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7797247c-98f1-f2b5-bf68-beabfac7d8f1
* Version Independent ID: 645a6a59-7f30-6ae3-a28d-ee6a7f5e4742
* Content: [Simple List and Details form pattern - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/user-interface/simple-list-details-form-pattern)
* Content Source: [articles/dev-itpro/user-interface/simple-list-details-form-pattern.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/user-interface/simple-list-details-form-pattern.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by sericks007** [comment]
Bug 343815 has been logged to track this issue.
