### ISSUE TITLE
Application registration with AD mentions Key to never expire

### ISSUE THREAD

**Issue by deeppr** [MicrosoftDocs/dynamics-365-unified-operations-public#1505]
[In the Register a web application with AAD section. Point 10 mentions that the Keys should never expire. Not expiring the secret is not a good practice and should not be suggested, instead a finite expiry time should be given.]
![image](https://user-images.githubusercontent.com/32161615/61369559-ff724c00-a8ad-11e9-89f1-83d322b313f9.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ba7bfc1-7c23-5662-8f2c-b41b19fb9070
* Version Independent ID: 19eb0a4a-1594-8f8b-054c-2c851df17e8b
* Content: [Service endpoints - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/services-home-page)
* Content Source: [articles/dev-itpro/data-entities/services-home-page.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/services-home-page.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by sericks007** [comment]
@deeppr, thanks for posting this!

@Sunil-Garg, please review and update the content as needed.

**Comment by sericks007** [comment]
Bug 343816 has been logged to track this issue.

**Comment by Sunil-Garg** [comment]
Thanks. The steps have been collapsed and AAD links are provided to make sure AAD process changes does not have to be replicated in this doc. Hope this helps. If you see any other issues or challenges, pls let us know.
