### ISSUE TITLE
Can't find the functionality

### ISSUE THREAD

**Issue by EmilyD01** [MicrosoftDocs/dynamics-365-unified-operations-public#151]
The functionality described in this article is exactly what we require at a client but we can't seem to find any of the forms or functionality described. For example Warehouse management > Loads > Transport loads or the mobile device menu item for transport loading. Is this due to the version we are using or are we missing something here? The environments we have checked are mostly Update12 (7.0.4709.41190)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91ab4dcf-7c32-a35a-c5d4-768aa13b3fac
* Version Independent ID: 7b993e54-f072-ff8a-dbf3-a713a3a1fd30
* Content: [Partial shipment of a transport load - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/warehousing/partial-shipping-of-transport-loads)
* Content Source: [articles/supply-chain/warehousing/partial-shipping-of-transport-loads.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/warehousing/partial-shipping-of-transport-loads.md)
* Service: **dynamics-ax-applications**
* Product: **unspecified**
* GitHub Login: @Mirzaab
* Microsoft Alias: **mirzaab**

**Comment by Mirzaab** [comment]
Dear ,
We are very happy that you are interested in our partial shipping functionality. 
We do have this functionality in our latest version 8.0. 
So it is due to the version you are using.

Best Regards
Mirza Abdic'
Senior Program Manager

**Comment by EmilyD01** [comment]
Hi Mirza

Thank you for the feedback. We provisioned a new demo environment of version 8 and found the fields and functionality you documented.

I just wondered how this functionality works with a packing station process. Is a manual packing process supported with the transport loading functionality?

Thanks in advance
Emily

**Comment by MargoC** [comment]
Hi Emily, to discuss product functionality, rather than the documentation, please use the Finance and Operations forum: 

https://community.dynamics.com/365/financeandoperations/f/765
