### ISSUE TITLE
"Set up" Page doesn't actually tell you how to set up

### ISSUE THREAD

**Issue by howalker3514** [MicrosoftDocs/dynamics-365-unified-operations-public#1512]
Like so many Microsoft documents labeled "set up" under which this particular page falls, there are no instructions on how to actually set up this functionality.  It describes what the functionality does rather than how to begin using it.  Argh! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64bed266-2c03-5028-9c25-3611548c1ff3
* Version Independent ID: b313a96e-3e35-2ea0-13a8-a4183467a4aa
* Content: [Leave and absence management - Talent | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/talent/leave-absence-overview#feedback)
* Content Source: [articles/talent/leave-absence-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/talent/leave-absence-overview.md)
* Service: **dynamics-365-talent**
* GitHub Login: @andreabichsel
* Microsoft Alias: **anbichse**

**Comment by tonyafehr** [comment]
@howalker3514, thanks for the feedback. This topic is currently being rewritten, so updates will be coming soon.

**Comment by josaw1** [comment]
Created Bug 344275 to track.

**Comment by bcraigie** [comment]
Any update on this?

**Comment by shereen-yong** [comment]
Still waiting on an update

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by andreabichsel** [comment]
Please see the new documentation at: https://docs.microsoft.com/en-us/dynamics365/human-resources/hr-leave-and-absence-overview. If there are any documentation gaps in those articles, please leave feedback and I will address them. Thank you!
