### ISSUE TITLE
End of service is wrong

### ISSUE THREAD

**Issue by prdpmv** [MicrosoftDocs/dynamics-365-unified-operations-public#1514]
End of service is wrong is wrong for 10.0.6 Platform update 30 release.
https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/public-preview-releases

**Comment by tonyafehr** [comment]
@prdpmv, thank you for noting this.

@meeramahabala or @ShellyBakke, please make updates to this topic, as needed.
