### ISSUE TITLE
Payment Reversal Reason

### ISSUE THREAD

**Issue by MichaelSlipp** [MicrosoftDocs/dynamics-365-unified-operations-public#1517]
Note that the reason code must be allowed for BOTH Bank and Vendor transactions for it to show up when reversing payment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ebcc128-758c-26b6-8692-eb00404ca1c9
* Version Independent ID: 49f51c81-1faa-f1e7-a35e-13572d4cac8a
* Content: [Reverse a vendor payment - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/accounts-payable/reverse-vendor-payment)
* Content Source: [articles/financials/accounts-payable/reverse-vendor-payment.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/accounts-payable/reverse-vendor-payment.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @abruer
* Microsoft Alias: **shpandey**

**Comment by tonyafehr** [comment]
@MichaelSlipp, thanks for the feedback. 
@abruer, consider updating this topic based on this feedback. Thanks!

**Comment by RobinARH** [comment]
Bug 346443 created to track this issue.
