### ISSUE TITLE
this page does not appear on the navigation bar when coming in from the main site

### ISSUE THREAD

**Issue by maveloso** [MicrosoftDocs/dynamics-365-unified-operations-public#152]
if you land on https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/ there is no way to navigate to this page on the left side navigation, the only way to reach this page that i can find is through a Bing Search

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 221bcbdf-2c16-ee9d-f289-75980e35b17a
* Version Independent ID: 6377db2c-d7b7-82bb-baeb-8f2311a9fb87
* Content: [Use third-party service testing utilities with Finance and Operations - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/third-party-service-test)
* Content Source: [articles/dev-itpro/data-entities/third-party-service-test.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/third-party-service-test.md)
* Service: **dynamics-ax-platform**
* Product: **unspecified**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by vavd** [comment]
Hi @maveloso, I can find this page by following:
Development & administration for Finance and Operations / Data integration / Data integration APIs /
 / Use third-party service testing utilities with services

**Comment by maveloso** [comment]
yes, I was confused because of the two parallel tracks which have mostly the same links but not quite

**Comment by MargoC** [comment]
@maveloso Where else in the TOC did you expect to see it? We can have it both places.

**Comment by maveloso** [comment]
There are 4 main TOC's items on the page. the two I am referring to are Dynamics 365 for finance and operations and Development and administration for Dynamics 365 for finance and operations. Both are pretty similar, but this page only shows under the development one.
