### ISSUE TITLE
Business Event with HTTP

### ISSUE THREAD

**Issue by prathiradhakrishnan** [MicrosoftDocs/dynamics-365-unified-operations-public#1521]
Hi,

There is no step given for Business events using HTTP.

Can you please provide the steps or example for it.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 655c157f-5478-4c71-7cd4-1b04383264ee
* Version Independent ID: 6555a353-87cd-c919-0c3e-dcfc4ede9909
* Content: [Business events - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/business-events/home-page#feedback)
* Content Source: [articles/dev-itpro/business-events/home-page.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/business-events/home-page.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by tonyafehr** [comment]
@prathiradhakrishnan, thanks for the feedback. 
@Sunil-Garg, please review and consider making updates to this topic.

**Comment by RobinARH** [comment]
Bug 346440 created to track this issue.

**Comment by Sunil-Garg** [comment]
We will track this in our list of items. Thanks for asking.

**Comment by Sunil-Garg** [comment]
Thanks for asking. We will consider adding this tutorial in the future.
