### ISSUE TITLE
Azure SQL Premiun DB is going to be retired on July 2019

### ISSUE THREAD

**Issue by Rafael-Gil** [MicrosoftDocs/dynamics-365-unified-operations-public#1524]
Hi according to Azure documentation, Azure SQL Premiun DB (which is the option recommended in this page) is going to be retired soon. Can you update the page with the new Microsoft recommendation please?

What is the new recommended Azure Architecture option to support BYOD?

Thanks 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cd981b1-0ed1-34c8-d22a-e1c6d194ff9c
* Version Independent ID: 1e26cccc-eab2-e170-7004-98585128e3e1
* Content: [Bring your own database (BYOD) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-gb/dynamics365/unified-operations/dev-itpro/analytics/export-entities-to-your-own-database?toc=%2Ffin-and-ops%2Ftoc.json#feedback)
* Content Source: [articles/dev-itpro/analytics/export-entities-to-your-own-database.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/export-entities-to-your-own-database.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by tonyafehr** [comment]
@Rafael-Gil, thanks for the feedback. 
@Sunil-Garg, please review and consider updating this topic.

**Comment by sericks007** [comment]
Bug 346932 has been logged to track this issue.

**Comment by SteveBurkettNZ** [comment]
The Azure SQL Database Premium RS tier has been retired (it never got out of Preview), but the Premium tier lives on, no retirement date set as yet. Think this issue could be closed out?

**Comment by axaeffect** [comment]
We still have issue on Create Clustered Column Store Index, which to resolve it by disabling it. 
This doc mentioned in order to use that it requires Premium, does it relate ?

**Comment by sericks007** [comment]
This issue was resolved in [pull request 1650](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/pull/1650/files).
