### ISSUE TITLE
Ownership Journal

### ISSUE THREAD

**Issue by AartiKumar** [MicrosoftDocs/dynamics-365-unified-operations-public#1525]
Is there a way to automate the journal, that if someone consumes the inventory on Sales order or Item adjustment journal, system should auto create the ownership journal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 058b5d48-c42d-2e8b-cdac-cd5cbecb4761
* Version Independent ID: 7a9f54d6-8dde-ae3e-07f9-bdacda58990e
* Content: [Change the ownership of consignment inventory based on production demand - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/inventory/tasks/change-ownership-consignment#feedback)
* Content Source: [articles/supply-chain/inventory/tasks/change-ownership-consignment.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/inventory/tasks/change-ownership-consignment.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @perlynne
* Microsoft Alias: **perlynne**

**Comment by sericks007** [comment]
@AartiKumar, thanks for posting this!

@perlynne, please review and update the content as needed.

**Comment by sericks007** [comment]
Bug 346933 has been logged to track this issue.

**Comment by stevmo** [comment]
This issue is solved in [Content Source](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/inventory/tasks/change-ownership-consignment.md)
