### ISSUE TITLE
Emailing an electronic gift card

### ISSUE THREAD

**Issue by ransoentjens** [MicrosoftDocs/dynamics-365-unified-operations-public#1527]
Dear, 

In D365 for Retail, it is possible to configure and implement an electronic gift card process. I've configured and executed this process on a standard Contoso environment, with e-mail parametrization included. However, the system does not generate an e-mail, nor can you configure any e-mail settings specifically for this process.

Can you please test this scenario and validate if the system works correctly? I'm still not clear whether it is the intention to generate an email, or to rather interface this information to a marketing/CRM application..

Process steps (high level)

1. Create order 
2. add order line for gift card (type = electronic)
3. process order (complete, pick, pack, invoice)
4. validate if e-mail is received by the recipient

I would appreciate the feedback. 

Kind regards, 
Ran

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf694273-518a-83df-613a-de255e701c59
* Version Independent ID: 6b0b0567-1da4-3e7a-ed86-c429fcdd7d72
* Content: [Support for external gift cards - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/dev-itpro/gift-card)
* Content Source: [articles/retail/dev-itpro/gift-card.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/dev-itpro/gift-card.md)
* Service: **dynamics-365-retail**
* GitHub Login: @sericks007
* Microsoft Alias: **ivanv**

**Comment by sericks007** [comment]
@ransoentjens, thanks for posting this!

@rubencdelgado, please review and update the content as needed.

**Comment by sericks007** [comment]
Bug 346934 has been logged to track this issue.

**Comment by ransoentjens** [comment]
Dear, 

Please be informed that in the meantime, we have succeeded to create and send the e-mail. Reason causing the issue was corrupt data in the e-mail queue which resulted in errors. This was on a Contoso environment - however.

In any case, the scenario works and the thread can be closed.

Best regards,
Ran
