### ISSUE TITLE
New Modern POS tools for 10.0.x

### ISSUE THREAD

**Issue by vzjackally** [MicrosoftDocs/dynamics-365-unified-operations-public#1529]
This document doesn't cover some of the changes in v10.0.x environments.
In instance, I guess there is a new way to set-up Offline modern POS by tools placed at (C:\Program Files (x86)\Microsoft Dynamics 365\70\Retail Modern POS\Tools\...)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b9cd3cc-5f85-3f61-4670-83e050cb30e4
* Version Independent ID: 313ff91b-902d-7f27-f9b1-6aa4d2370945
* Content: [Set up new environments, Azure DevOps, and branches for Retail projects - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/dev-itpro/new-environments-visual-studio-teams-branch-retail-projects)
* Content Source: [articles/retail/dev-itpro/new-environments-visual-studio-teams-branch-retail-projects.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/dev-itpro/new-environments-visual-studio-teams-branch-retail-projects.md)
* Service: **dynamics-365-retail**
* GitHub Login: @andreash1
* Microsoft Alias: **andreash**

**Comment by josaw1** [comment]
Thank you for your feedback. @andreash1, can you please assist?

**Comment by josaw1** [comment]
Bug 347815 created to track.

**Comment by josaw1** [comment]
Hi @vzjackally, the feedback from the Program Manager was this: This folder is not new and not intended to be used by ISV/Customers. Installer uses this script to setup DB/POS.

Thank you!
