### ISSUE TITLE
Dynamics 365 for Outlook shows blank page

### ISSUE THREAD

**Issue by CRM-GSD** [MicrosoftDocs/dynamics-365-unified-operations-public#1530]
I use Dynamics 365 for CRM in Outlook.
Even my account is connected to CRM:
![image](https://user-images.githubusercontent.com/46699078/61848863-ab80ec00-aed9-11e9-995a-956effba32a7.png)
when clicking on Dynamics 365 add-in, the pane shows blank:
![image](https://user-images.githubusercontent.com/46699078/61848882-b63b8100-aed9-11e9-8497-a164d674f2c5.png)

The workarounds applied for CRM version 8.x is out of date. I tried but none of them work.
Is it a new issue introduced in version 9.x? Would appreciate for any solution from you guys.

**Comment by josaw1** [comment]
@CRM-GSD, thank you for your feedback. If your comment pertains to a topic, please make the comment on that topic so it gets routed to the correct person. Thanks.
