### ISSUE TITLE
Build on-premises

### ISSUE THREAD

**Issue by GeoffreyDelmee** [MicrosoftDocs/dynamics-365-unified-operations-public#1531]
On page https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/cloud-prem-comparison#development-and-administration it is said "Build and test" is available on both cloud and on-premises.
Can you update this topic for the on-premises support?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a74ae963-aca1-5622-b27a-05e40e40554c
* Version Independent ID: 64745ceb-8444-d806-6a3c-a695c288d07a
* Content: [Deploy and use an environment that supports continuous build and test automation - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/perf-test/continuous-build-test-automation#feedback)
* Content Source: [articles/dev-itpro/perf-test/continuous-build-test-automation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/perf-test/continuous-build-test-automation.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RobinARH
* Microsoft Alias: **shailesn**

**Comment by josaw1** [comment]
Thank you for your comment. @sericks007, can you please take a look? Thanks.

**Comment by sericks007** [comment]
@PeterRFriis, please review and update the content as needed.

**Comment by mozaki13** [comment]
@GeoffreyDelmee thanks for reaching out, can you elaborate more on what need to be updated? It is mentioned that Build and test is available for OnPrem and in the article you have shared it contains the steps to Deploy and use an environment that supports continuous build and test automation
Thank you :)

**Comment by GeoffreyDelmee** [comment]
@mozaki13 On cloud deployment, the build environment is the Tier1 one included in the license (setting up Azure DevOps is a prereq of this deployment).
On on-premises deployment, there are no Tier1 available to deploy the build. Also, going to on-premises deployment, the goal is not to deploy VM in an Azure subscription.

Seeing build and test is available for on-premises, what is the way?
If it's an on-premises environment, how to have the SDK and set Azure DevOps?
If it's a cloud environment, how to activate the Tier1? It is not seen in the LCS project.
If it's another way, can you elaborate?

**Comment by josaw1** [comment]
Bug 346938 created to track.

**Comment by josaw1** [comment]
Bug 350909 created to track this issue.

**Comment by sarvanisathish** [comment]
This means the ability to build and test is available for on-premises through downloadable VHD. It is not referring to the build/test cloud deployment topology.

**Comment by GeoffreyDelmee** [comment]
@sarvanisathish Thanks for the feedback.
Going with the downladable VHD from LCS, where can I find the information on how to set this VHD as a build environment as it is done during LCS deployment for managed and Azure VM? The refered pages on build environment deployment are only stating how to deploy from LCS.
Also, the build environment deployment from LCS generates the build process in Azure DevOps. Again, where can I find the information on how to set it up with the on-premises VHD?

**Comment by sarvanisathish** [comment]
@robadawy, @laneswenka  to help here.

**Comment by laneswenka** [comment]
@GeoffreyDelmee this article will get updated to reference Azure DevOps hosted agents which can either be an on-prem Windows VM or it can be one of their own Windows VMs.  We no longer require a full actual "Dynamics" environment to build and create packages.

**Comment by laneswenka** [comment]
@jorisdg could you review this please?  Anything special for the on-prem flow with the new hosted agents approach?

**Comment by jorisdg** [comment]
Consider using the new pipeline if it fits your requirements. This is available as of PU35.
https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/hosted-build-automation

If you use AZDO online, you can just deploy a build VM via LCS. There's no difference between on-prem or cloud. If you're using AZDO Server, you can use the new pipeline. Alternatively, all the "traditional" scripts from the build VM are also on the VHD, but they have not been run. We don't officially document or support this mode, but many people do it successfully. There is an old archived blog post you can use to guide on how to run the setup manually: https://docs.microsoft.com/en-us/archive/blogs/axdevalm/how-to-setup-build-agent-and-create-a-build-definition-manually
