### ISSUE TITLE
Sign off is no longer required

### ISSUE THREAD

**Issue by turbozapekanka** [MicrosoftDocs/dynamics-365-unified-operations-public#1532]
"After the import operation is completed, you must Sign off on the operation before you can perform another servicing operation, such as package deployment, database movement, or upgrade"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 277452eb-70c4-3d29-5219-1355a40bb714
* Version Independent ID: a9d425c4-c627-d20f-4098-307eceb2dd07
* Content: [Golden configuration promotion - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/dbmovement-scenario-goldenconfig)
* Content Source: [articles/dev-itpro/database/dbmovement-scenario-goldenconfig.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/database/dbmovement-scenario-goldenconfig.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @laneswenka
* Microsoft Alias: **laneswenka**

**Comment by josaw1** [comment]
Thank you for your comment. @laneswenka, can you please update the topic if needed?

**Comment by josaw1** [comment]
Bug 347816 created to track.

**Comment by laneswenka** [comment]
Resolved in latest update
