### ISSUE TITLE
Forecast models

### ISSUE THREAD

**Issue by ggriffith25** [MicrosoftDocs/dynamics-365-unified-operations-public#1533]
Fields for: 1) Original budget and 2) Remaining budget are required fields and should include valid values for Project Forecast Models.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aba05e0c-0cb4-b9c1-ddca-f0b2c1ae44c5
* Version Independent ID: 0a0487ab-70d9-2705-7468-56d6d29804a5
* Content: [Submit and approve project budget - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/procurement/tasks/submit-approve-project-budget#feedback)
* Content Source: [articles/supply-chain/procurement/tasks/submit-approve-project-budget.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/procurement/tasks/submit-approve-project-budget.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @mkirknel
* Microsoft Alias: **mkirknel**

**Comment by josaw1** [comment]
Thank you for your comment. @MaiKirknel, can you please review this feedback and update the topic if needed?

**Comment by josaw1** [comment]
Bug 347812 created to track.

**Comment by josaw1** [comment]
Bug 437964 created.

**Comment by kfend** [comment]
Closing as I have worked through this procedure and the fields mentioned are automatically filled with the information. If this is not what is being referred to, please reopen and provide more information. For example, which FastTab has the fields you are referring to as the Original budget field is shown on multiple FastTabs on the same page.
