### ISSUE TITLE
Microsoft Dynamics 365 - Translation Service - Cannot submit or delete requests

### ISSUE THREAD

**Issue by aacnsilva** [MicrosoftDocs/dynamics-365-unified-operations-public#1536]
When submitting or deleting a request in the translation service i get the following error:

![image](https://user-images.githubusercontent.com/50581065/62054469-8e1d8c00-b211-11e9-9b19-39a8091bc360.png)

**Comment by ejchoGIT** [comment]
Hi, if you continue to see the problem after retrial, please email to dtssup@microsoft.com with your request ID. Thanks!

**Comment by aacnsilva** [comment]
I still got the error. Email sent according to your instructions. Thank you
