### ISSUE TITLE
extension model without overlayering

### ISSUE THREAD

**Issue by ansartroops** [MicrosoftDocs/dynamics-365-unified-operations-public#1537]
Could you pls. add the topic "Extension model without overlayering", provide some samples for extending Hardware Station.
Regards,
Ansar Basha.S

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d3906b0-4ef0-3ee7-fb68-136442cff5c5
* Version Independent ID: 96819cbc-0e7b-7341-c534-d079387ef5b9
* Content: [Hardware Station extensibility - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/dev-itpro/hardware-station-extensibility)
* Content Source: [articles/retail/dev-itpro/hardware-station-extensibility.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/dev-itpro/hardware-station-extensibility.md)
* Service: **dynamics-365-retail**
* GitHub Login: @RobinARH
* Microsoft Alias: **sijoshi**

**Comment by RobinARH** [comment]
@mugunthanm Can you take a look at this one? Thanks.

**Comment by RobinARH** [comment]
Created bug 348284 to track this issue.
