### ISSUE TITLE
Where is this Page?

### ISSUE THREAD

**Issue by curtix** [MicrosoftDocs/dynamics-365-unified-operations-public#1546]
Article doesn't indicate where to find the "Project Services Automation Integration parameters page"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 898dd376-cd26-192b-1ea5-5b1353386d77
* Version Independent ID: e142a334-0c0f-2ee5-b236-dc2f99c6477a
* Content: [Project Service Automation integration parameters - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/project-management/psa-parameters?toc=%2Ffin-and-ops%2Ftoc.json#feedback)
* Content Source: [articles/financials/project-management/PSA-parameters.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/project-management/PSA-parameters.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @KimANelson
* Microsoft Alias: **knelson**

**Comment by sericks007** [comment]
@curtix, thanks for posting this!

@KimANelson, can you please answer the question and update the content as needed.

**Comment by curtix** [comment]
I finally found it - in Fin Ops.

So it looks like it's:
Dynamics 365 for Finance and Operations > Project management and accounting (module) > Setup > "Dynamics 365 for Project Service Automation integration parameters"

Thanks

**Comment by expiscornovus** [comment]
@sericks007, can you by any chance add the explanation from @curtix to the article? 

I had the exact same issue that I had to search for the location of this page. Ended up in this thread after Googling a bit. Still useful to add it to the article imo.

**Comment by sericks007** [comment]
@roschlom, please consider adding the location to this topic.

**Comment by sericks007** [comment]
Oops, I made an error.  @kfend, please consider adding the location to this topic.

**Comment by kfend** [comment]
I have updated the topic with the navigation path. This change will be published today.
