### ISSUE TITLE
Select all measurements that need to be refreshed.

### ISSUE THREAD

**Issue by turbozapekanka** [MicrosoftDocs/dynamics-365-unified-operations-public#1550]
Not possible to do as the list does not allow multiple measurements to be selected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3eab27bf-ee40-ebc6-b68e-481ddb368d27
* Version Independent ID: e75f13e0-a5b2-98e3-e1ba-22d26a4225cb
* Content: [Resolve issues after entity store maintenance - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/entity-store-maintenance)
* Content Source: [articles/dev-itpro/analytics/entity-store-maintenance.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/entity-store-maintenance.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @sarvanisathish
* Microsoft Alias: **sarvanis**

**Comment by josaw1** [comment]
Thank you for your comment. @sarvanisathish, can you please take a look and update the topic as needed?

**Comment by josaw1** [comment]
Bug 349650 created to track this issue.
