### ISSUE TITLE
Outdated information

### ISSUE THREAD

**Issue by turbozapekanka** [MicrosoftDocs/dynamics-365-unified-operations-public#1552]
It looks like new Auto-refresh feature has been added in the latest update that changes the way the entity store is refreshed.
Please update the documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd3a076-d364-f4e8-fe37-f10c77a75466
* Version Independent ID: 0f767e21-3f33-2139-0931-7cd044c81b9f
* Content: [Power BI integration with Entity store - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/power-bi-integration-entity-store?toc=/fin-and-ops/toc.json)
* Content Source: [articles/dev-itpro/analytics/power-bi-integration-entity-store.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/power-bi-integration-entity-store.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by josaw1** [comment]
Thank you for your feedback. @MilindaV2, can you please take a look at the comment and update the doc?

**Comment by josaw1** [comment]
Bug 349651 created to track this issue.
