### ISSUE TITLE
Step Duplicate

### ISSUE THREAD

**Issue by dinuasdinu** [MicrosoftDocs/dynamics-365-unified-operations-public#1555]
Step 14 to 25 appears duplicate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29ccd846-d529-ba33-11ce-3c2b7282ad34
* Version Independent ID: aa832360-7ce7-005d-de14-c80deb6c0d55
* Content: [Set up postdated checks - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/cash-bank-management/tasks/set-up-postdated-checks#feedback)
* Content Source: [articles/financials/cash-bank-management/tasks/set-up-postdated-checks.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/cash-bank-management/tasks/set-up-postdated-checks.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @kweekley
* Microsoft Alias: **kweekley**

**Comment by josaw1** [comment]
Thanks for the feedback. @rschloma, can you please update the topic if needed?

**Comment by josaw1** [comment]
Bug 349651 created to track this issue.

**Comment by josaw1** [comment]
Bob removed the extra steps.
