### ISSUE TITLE
Lack of information

### ISSUE THREAD

**Issue by oscarlozada** [MicrosoftDocs/dynamics-365-unified-operations-public#1556]
There is no information what about with sales of on-hand inventory, it isn't possible to sale before post an owner journal, so that, it isn't useful for sales orders and retail process.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6860e0b5-7f40-7969-6c2d-f2ddc0d9af65
* Version Independent ID: b187423b-b26a-93b3-1379-5784c9203f72
* Content: [Set up consignment - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/inventory/consignment#feedback)
* Content Source: [articles/supply-chain/inventory/consignment.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/inventory/consignment.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @perlynne
* Microsoft Alias: **perlynne**

**Comment by josaw1** [comment]
Bug 349652 created to track this issue.
