### ISSUE TITLE
Something wrong with example of if EDT is modified in more than one model

### ISSUE THREAD

**Issue by bhattsgsits** [MicrosoftDocs/dynamics-365-unified-operations-public#156]
"the properties of the EDT from the model with the highest Model ID will be used."
Highest model id is 15 "Super Item number" then why interface will show "Awesome item number"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ab86cf5-9cb0-f51b-3ac8-7f16ccef799a
* Version Independent ID: 1bbfad2d-92a3-d3aa-058f-b6c179906c55
* Content: [Modify an extended data type - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/extensibility/modify-edt)
* Content Source: [articles/dev-itpro/extensibility/modify-edt.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/extensibility/modify-edt.md)
* Service: **dynamics-ax-platform**
* Product: **unspecified**
* GitHub Login: @ivanv-microsoft
* Microsoft Alias: **ivanv**

**Comment by MargoC** [comment]
Updated the topic, based on your feedback. Thanks so much!
