### ISSUE TITLE
"Send extenal" setting

### ISSUE THREAD

**Issue by sminozhenko** [MicrosoftDocs/dynamics-365-unified-operations-public#1560]
Hi, In the article mentioned that "To configure an alert, the Send external setting must be enabled" - is it setting "Send externally" on "Create alert rule" dialog? If yes, could the name of setting be fixed in the article and maybe some screenshots added? (also for the part "The business event for the change-based alert and/or the due date alert must also be active for the alert to be sent out as a business event.")

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 079087bd-c5f1-1640-3f2a-220d76e2a0fa
* Version Independent ID: 27569782-821f-0b16-5162-d3ab94232c79
* Content: [Alerts as business events - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/business-events/alerts-business-events)
* Content Source: [articles/dev-itpro/business-events/alerts-business-events.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/business-events/alerts-business-events.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by RobinARH** [comment]
@Sunil-Garg: Can you take a look? Thanks.

**Comment by RobinARH** [comment]
Bug 349983 created to track this issue.

**Comment by Sunil-Garg** [comment]
Thanks. The wiki has been updated.
