### ISSUE TITLE
Incorrect path in description

### ISSUE THREAD

**Issue by ilitutilitam** [MicrosoftDocs/dynamics-365-unified-operations-public#1561]
General Ledger &gt; Inquiries and report &gt; Ledger reports &gt; FEC Accounting data export

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56989a16-a9a3-c8d1-d7d0-6e542871107f
* Version Independent ID: 1da2ec78-cf33-1741-c5cc-97b73d72b539
* Content: [Generate the Standard Audit File for France (FEC) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/localizations/emea-fra-fec-audit-file#feedback)
* Content Source: [articles/financials/localizations/emea-fra-fec-audit-file.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/localizations/emea-fra-fec-audit-file.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @ShylaThompson
* Microsoft Alias: **shylaw**

**Comment by RobinARH** [comment]
@kfend Can you take a look? Thanks.

**Comment by Anasyash** [comment]
Hello. Could you please clarify the path which is incorrect in the topic?

Also please consider the following information: https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/deprecated-features?toc=/fin-and-ops/toc.json#france-fec-accounting-data-export-in-xml
You can create a support ticket for getting more details on that.

**Comment by ilitutilitam** [comment]
Hello, 
The problem is that we cannot select the needed file format for Standard Audit File for France (FEC) using path "Go to General Ledger > Periodic tasks > Data export to open the Data export page".
Instead of this, there is a path "General ledger > Inquiries and reports > Ledger reports > FEC Accounting data export". So, we believe the description is not correct.

**Comment by ilitutilitam** [comment]
Installed platform version : Update27 (7.0.5286.35426)

**Comment by ilitutilitam** [comment]
I believe the is confusion from my side. 
For XML file path: General ledger > Inquiries and reports > Ledger reports > FEC Accounting data export
For TXT file path: General ledger > Inquiries and reports > Ledger reports > FEC Accounting data export
As XML file is depriciated, then only TXT file will be used in future. So, description in docs is correct.
