### ISSUE TITLE
Follow me Printer: What are the settings?

### ISSUE THREAD

**Issue by UmeshPandit** [MicrosoftDocs/dynamics-365-unified-operations-public#1563]
Follow me Printer: What are the settings?

**Comment by RobinARH** [comment]
@UmeshPandit Hi - What in particular did you want to print. That will help me route this to the correct team. Thanks.

**Comment by UmeshPandit** [comment]
How does this DRP work with Followme printers that are the point? as we can't batch them if we wish to print use Followme printers. right?

**Comment by tonyafehr** [comment]
Which topic are you referring to? Your comment is not associated with any particular topic so we're unable to determine what we need to address. I suggest that you contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
