### ISSUE TITLE
Link on the provisioning guide isn't working

### ISSUE THREAD

**Issue by petersonfs** [MicrosoftDocs/dynamics-365-unified-operations-public#1564]
The link provided in the documentation isn't working. I couldn't find the link anywhere in the PartnerSource nor CustomerSource.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e859ad9-22e1-e14e-2c7a-6df3ba1482ca
* Version Independent ID: 6eff91da-e5c3-3fcd-00f2-2fd690e7cc15
* Content: [Buy Finance and Operations (on-premises) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/purchase-on-premises)
* Content Source: [articles/fin-and-ops/get-started/purchase-on-premises.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/purchase-on-premises.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @maertenm
* Microsoft Alias: **maertenm**

**Comment by RobinARH** [comment]
@meeramahabala: Can you take a look? Thanks.

**Comment by sericks007** [comment]
I'm sorry, our team can't reproduce this issue.  Here are the direct links to the Provisioning Guide:

PartnerSource link: https://mbs.microsoft.com/partnersource/global/deployment/documentation/user-guides/D365Ops_OnPremEEProvisionGuide

CustomerSource link: https://mbs.microsoft.com/customersource/northamerica/365Enterprise/learning/documentation/user-guides/D365Ops_OnPremEEProvisionGuide

**Comment by petersonfs** [comment]
Hi @sericks007,

The problem is that the link ([https://portal.office.com/Signup/MainSignUp.aspx?OfferId=3f9e84aa-d15d4293-ac4c-5c467f1d4224&pc=814e410e-2e4a-49f1-940d-486c8bce0319](https://portal.office.com/Signup/MainSignUp.aspx?OfferId=3f9e84aa-d15d4293-ac4c-5c467f1d4224&pc=814e410e-2e4a-49f1-940d-486c8bce0319)) inside the documentation provided in the Customer ou Partner source aren't a valid anymore.

Could you help me?

**Comment by sericks007** [comment]
@petersonfs, the links don't work for me today, so I'll reopen this.

**Comment by sericks007** [comment]
@ShellyBakke, please provide new links to the Provisioning Guide.

**Comment by sericks007** [comment]
Bug 350591 has been logged to track this issue.

**Comment by SajeerAssiz** [comment]
The link is not working at all, then how microsoft onlu cant reproduce it
