### ISSUE TITLE
Wrong KB Article for Bug Fixes

### ISSUE THREAD

**Issue by caleblanchard** [MicrosoftDocs/dynamics-365-unified-operations-public#1565]
The KB article link points to the bug fixes for 10.0.3 instead of 10.0.5

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62d0e651-317f-3311-a82c-1a5e330c80d8
* Version Independent ID: abadbc06-6753-c524-ec12-4c540d1527e0
* Content: [Preview features in Finance and Operations version 10.0.5 (October 2019) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/whats-new-changed-10-0-5)
* Content Source: [articles/fin-and-ops/get-started/whats-new-changed-10-0-5.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/whats-new-changed-10-0-5.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @tonyafehr
* Microsoft Alias: **tfehr**

**Comment by josaw1** [comment]
Thank you for the feedback. I've updated the link!
