### ISSUE TITLE
Wrong SQL query for enabling the Flight

### ISSUE THREAD

**Issue by aariste** [MicrosoftDocs/dynamics-365-unified-operations-public#1566]
I think there's an error with the Flight name in the SQL query. With the query from the doc the flighting is not appearing on the list. I've tried changing the name from  'Dynamics.AX.Application.CLISavedViewsEnableFeature'  to  'CLISavedViewsEnableFeature' and after doing an iisreset and clicking the "Check for updates" button the saved views feature is now appearing on the list.

This is how the SQL query should be: INSERT INTO SYSFLIGHTING (FLIGHTNAME, enabled, FLIGHTSERVICEID, PARTITION) VALUES('CLISavedViewsEnableFeature', 1, 0, 5637144576);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56269725-2b74-50aa-9084-1ca2e8cd1403
* Version Independent ID: 992ef7ce-6a9e-cfe6-1e08-8d28bccdcd06
* Content: [Saved views - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/saved-views#frequently-asked-questions)
* Content Source: [articles/fin-and-ops/get-started/saved-views.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/saved-views.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by tonyafehr** [comment]
@aariste, thanks for the feedback. 
@jasongre, can you review this and update the topic, if needed.

**Comment by jasongre** [comment]
Thanks! The topic has been updated.

**Comment by tonyafehr** [comment]
Bug 350368 logged to track this issue.
