### ISSUE TITLE
Syntax for SQL Statement

### ISSUE THREAD

**Issue by illese** [MicrosoftDocs/dynamics-365-unified-operations-public#1567]
In the document it is stating 'Type a query as an SQL statement between parentheses.' but no details is given how to get the data source and the field name. I tested with 'Address and contact information purpose' neither the SQL table and field names (like LogisticsLocationRoleTranslation.LANGUAGEID)  nor the entity name (like LogisticsLocationRoleEntity.Language) worked.

**Comment by tonyafehr** [comment]
@illese, which topic are you referring to? Your comment is not in reference to a specific topic, thanks!

**Comment by illese** [comment]
Hi Tonya
Sorry, seems the UI is sometimes broken, as I started the comment form docs… Anyhow.
This is the doc I am referring to: https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/advanced-filtering-query-options

Illes

**Comment by tonyafehr** [comment]
@illese, thanks for the additional info. 

@jasongre, can you take a look at this and see if the topic should be updated. Thank you!

**Comment by jasongre** [comment]
@illese, I'm updating the topic with a more realistic example showing both a field from the root datasource as well as field on a different datasource.
