### ISSUE TITLE
Operating units - unique numbering

### ISSUE THREAD

**Issue by oyber** [MicrosoftDocs/dynamics-365-unified-operations-public#1568]
[A good information to give the users it that the system requires unique numbering of operating units. You can't have a Department and a Cost Center with the same ID number.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 418eaff4-9d4f-e9e6-db48-7b1e84661ff3
* Version Independent ID: 40000edf-6d67-8364-8f6b-3368e3ae4a3f
* Content: [Create an operating unit - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/organization-administration/tasks/create-operating-unit#feedback)
* Content Source: [articles/fin-and-ops/organization-administration/tasks/create-operating-unit.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/organization-administration/tasks/create-operating-unit.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @sericks007
* Microsoft Alias: **sericks**

**Comment by tonyafehr** [comment]
Bug 350370 has been logged to track this issue.

**Comment by ChrisGarty** [comment]
Added that as an extra point in the doc. Thanks!
