### ISSUE TITLE
Elaborate on Forecast Models for Project Forecasts v. Forecast Models for Project Budgets

### ISSUE THREAD

**Issue by ggriffith25** [MicrosoftDocs/dynamics-365-unified-operations-public#1571]
Use separate Forecast Models for Project Forecasts than for Project Budgets.  On Forecast Models for Project Forecasts, set value for Budget Type = None.  For Forecast Models for Project Budgets, set value for Budget Type = Original budget or Remaining budget or Carry-forward according to needs.  Note: When Budget Type is set to a value other than None, then the value of the Stopped field will be set to Yes to indicate that the parameters for the Forecast Model cannot be changed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3794964c-2c67-905b-98e8-6a2ecf978c23
* Version Independent ID: 66dd3a35-d3f1-3e82-5de2-20febaca9f64
* Content: [Project forecasts and budgets - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/project-management/project-forecasts-budgets)
* Content Source: [articles/financials/project-management/project-forecasts-budgets.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/project-management/project-forecasts-budgets.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @KimANelson
* Microsoft Alias: **knelson**

**Comment by sericks007** [comment]
@ggriffith25, thanks for posting this!

@KimANelson, please review and update the content, if appropriate.

**Comment by sericks007** [comment]
Bug 350547 has been logged to track this issue.

**Comment by ggriffith25** [comment]
Also, when the Forecast Models are setup with Budget Type filled in (and not blank), the form will show a value for Stopped = Yes.  This value for Stopped=Yes, appears to mean only that the settings for that particular Forecast Model ID are "stopped" and cannot be changed.  It does not mean that the Forecast Model ID itself should not be used because it is "stopped".  Each of the three values for Budget Type when it is filled in can be used only once.  When the value for Budget Type is blank, multiple Forecast Model ID's can be set up.

**Comment by ggriffith25** [comment]
Note: There is a pending/new product change related to this top.
Release: Dynamics 365 for Finance and Operations | 10.0.7
LCS quantity report number: 370574
KB 4520681

**Comment by PottSrikanth** [comment]
I am using the version of Update57 and Platform10.0.33. Does anyone have a solution how can I create different type of forecast models by selecting budget type. 

I am still facing the same issue like when I create a new model group and select the budget type everything gets greyed out and the Stopped button toggles to Yes.
