### ISSUE TITLE
Developer control over where a PowerApp can be embedded

### ISSUE THREAD

**Issue by sumadhuram456** [MicrosoftDocs/dynamics-365-unified-operations-public#1573]
[ExtensionOf(classStr(FormRunConfigurationPowerAppsConfiguration))]

public final class ClassTest_Extension
{
    public static boolean isPowerAppPersonalizationEnabled(str pageName)
    {
        var result = next isPowerAppPersonalizationEnabled(pageName);
        return true;
    }
    public static boolean isPowerAppTabPersonalizationEnabled(str pageName)
    {
        var result = next isPowerAppTabPersonalizationEnabled(pageName);
        return true;
    }
}

Both the return statements need to be return result? instead of return true

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2ba2071-d17c-cb98-a965-52258c0ddc9c
* Version Independent ID: d4a1e83c-549b-08f9-1f92-370c58bb30f3
* Content: [Embed PowerApps apps - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/embed-power-apps#feedback)
* Content Source: [articles/fin-and-ops/get-started/embed-power-apps.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/embed-power-apps.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by josaw1** [comment]
Thank you for your feedback. @jasongre, can you please address this comment?

**Comment by josaw1** [comment]
Bug 350909 created to track issue.

**Comment by josaw1** [comment]
Bug 350915 created to track this issue.

**Comment by jasongre** [comment]
The typo has been corrected.  Thanks!
