### ISSUE TITLE
Query options on expanded entities don't work

### ISSUE THREAD

**Issue by tclayton72** [MicrosoftDocs/dynamics-365-unified-operations-public#1577]
The only one that works is $select.  Should the others, $filter being the most useful one, work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64b023ab-59fb-87d9-d935-d60d0e9e4139
* Version Independent ID: 10120c96-a72d-60fd-63ff-db9f77e05817
* Content: [Open Data Protocol (OData) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/odata?toc=/fin-and-ops/toc.json)
* Content Source: [articles/dev-itpro/data-entities/odata.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/odata.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by RobinARH** [comment]
@Sunil-Garg : Can you take a look? Thanks.

**Comment by RobinARH** [comment]
Bug 351460 created to track issue.

**Comment by Sunil-Garg** [comment]
The support for expand are currently limited. Hence, you are correct in noticing the issue. We currently don't have plans to add the support. Thanks for sharing.
