### ISSUE TITLE
I would like to have document about all duty for all Roles

### ISSUE THREAD

**Issue by wandeewanikpun** [MicrosoftDocs/dynamics-365-unified-operations-public#1582]
In AX 2012, Microsoft release an Excel file lists all the Roles and Duty of every Roles. For example Purchasing Manager can Approve product prices and discounts, Approve purchase agreement, and Maintain all kinds of master, etc.
 I would like to have the same kind of file for MSD 365. Do you have it?
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09327be4-4437-628d-65b0-45e5824a06d5
* Version Independent ID: 1bbaa6dd-6e50-77e1-36c2-10c2dbd55459
* Content: [Role-based security - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/sysadmin/role-based-security#feedback)
* Content Source: [articles/dev-itpro/sysadmin/role-based-security.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/sysadmin/role-based-security.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @sericks007
* Microsoft Alias: **sericks**

**Comment by sericks007** [comment]
@wandeewanikpun, thanks for posting!

We haven't published an Excel file listing all of the roles and duties associated with each role in Dynamics 365 for Finance and Operations. Instead, this information is available in the product on the Security configuration page (System administration > Security > Security configuration).

**Comment by wandeewanikpun** [comment]
Thank you very much.
What you suggest is enough for us as implementor. However the customer would like to have clear explanation of who can do what. 

BTW, when it said "maintain", does it really mean create or edit or delete? or all of them? How do I know?

**Comment by sericks007** [comment]
@ChrisGarty, can you answer the question above regarding the word "maintain".
