### ISSUE TITLE
Cannot find correct versions for the sample ER customer invoicing solution

### ISSUE THREAD

**Issue by PalleAgermark** [MicrosoftDocs/dynamics-365-unified-operations-public#1587]
I can't find these versions in neither Shared Asset Library nor the PEAP Assets project:
Customer invoicing model.version.2.xml
Customer FTI report (GER).version.2.3.xml

Where do I get these?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01220120-d91e-59ae-70e2-0879779adb9d
* Version Independent ID: 3fe09ff9-be42-0f72-1231-6d9e5eba1d47
* Content: [Business document management overview - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/er-business-document-management)
* Content Source: [articles/dev-itpro/analytics/er-business-document-management.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/er-business-document-management.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @NickSelin
* Microsoft Alias: **nselin**

**Comment by NickSelin** [comment]
To download mentioned configurations, please, use the links that are provided in the “Import ER solutions” section of this page to complete the provided procedure for each downloaded configuration. To learn more about this feature, you can also use other configurations that can be taken from the asset library of the PEAP project.

**Comment by PalleAgermark** [comment]
Doh. Too easy - thanks :-)
