### ISSUE TITLE
Repeated sentence

### ISSUE THREAD

**Issue by mannesneuer** [MicrosoftDocs/dynamics-365-unified-operations-public#1588]
In the first and second paragraphs, the following sentence is duplicated: "Earning codes uniquely identify every type of earning that workers receive. They include parameters that are related to earnings, such as accounting rules, tax laws, reporting requirements, and gross-up capability."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ae502d5-7ba1-9488-e6ea-6aba18f7d8cb
* Version Independent ID: 9068fd4f-755e-4984-302d-bdc5eb44ba71
* Content: [Set up earning codes and earning code groups - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/hr/localizations/noam-usa-earning-code-group-tasks#feedback)
* Content Source: [articles/fin-and-ops/hr/localizations/noam-usa-earning-code-group-tasks.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/hr/localizations/noam-usa-earning-code-group-tasks.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @andreabichsel
* Microsoft Alias: **ryansand**

**Comment by sericks007** [comment]
@mannesneuer, thanks for letting us know!

@andreabichsel, please update the topic accordingly.

**Comment by andreabichsel** [comment]
Thank you for bringing this to my attention! I fixed the issue, and it should be live in just a few minutes.
