### ISSUE TITLE
New icons in PU29

### ISSUE THREAD

**Issue by PalleAgermark** [MicrosoftDocs/dynamics-365-unified-operations-public#1591]
Please note that, according to Jason Green, new icons wont render properly in PU29 unless you are on build 7.0.5372.16650 or later.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c174ba35-3d9c-61fb-b2a1-82cca1b88e4b
* Version Independent ID: 21f85208-93ab-420d-8de6-4c4ca064647f
* Content: [Create icons for workspace tiles - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/user-interface/create-icons-workspace-tiles)
* Content Source: [articles/dev-itpro/user-interface/create-icons-workspace-tiles.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/user-interface/create-icons-workspace-tiles.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by josaw1** [comment]
Thanks for the feedback. @sericks007 can you please take a look?

**Comment by josaw1** [comment]
@jasongre

**Comment by sericks007** [comment]
@jasongre, please review and update the topic if necessary.

**Comment by RobinARH** [comment]
Bug 353174 created to track this issue.

**Comment by jasongre** [comment]
The earliest preview build for Platform update 29 was missing a CSS tweak to render the workspace icons correctly, but this was fixed before the build became generally available.
