### ISSUE TITLE
Old versions?

### ISSUE THREAD

**Issue by AndersDahlin** [MicrosoftDocs/dynamics-365-unified-operations-public#1595]
Hi,
Has this been updated lately? Older versions in progress and current. What about current D365 operations version 10?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b352eb61-b9ae-5d2d-3d64-1b156c453124
* Version Independent ID: 1903d3d9-6771-85bd-85be-367dbe465742
* Content: [Payment Application Data Security Standards (PA-DSS) certification - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/dev-itpro/pa-dss-certification#feedback)
* Content Source: [articles/retail/dev-itpro/PA-DSS-Certification.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/dev-itpro/PA-DSS-Certification.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @jashanno
* Microsoft Alias: **jashanno**

**Comment by sericks007** [comment]
@AndersDahlin, thanks for posting!  This topic will be updated soon as we're currently reviewing the PA-DSS Implementation Guide for version 10.0.
