### ISSUE TITLE
Offline transactions earning/posting points

### ISSUE THREAD

**Issue by MSFTRANDY** [MicrosoftDocs/dynamics-365-unified-operations-public#1596]
There seems to have been an update to Loyalty where the offline section above for the Retail shared parameters "Earn offline" option no longer exists.  We've also added a "Post earned points in batches" option which is not mentioned in this article.  It is unclear how offline handles loyalty points.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d69dbedf-6ac0-c762-a732-f7c7e60bde07
* Version Independent ID: 1292ab05-4902-c8d1-b8e0-7cb9778d4415
* Content: [Loyalty overview - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/set-up-customer-loyalty-program)
* Content Source: [articles/retail/set-up-customer-loyalty-program.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/set-up-customer-loyalty-program.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @scott-tucker
* Microsoft Alias: **scotttuc**

**Comment by kfend** [comment]
@MSFTRANDY - Thanks for bringing this to our attention. The topic has been updated and the changes should be reflected in the next 24 hours.
