### ISSUE TITLE
Recurring Integration Http vs Https

### ISSUE THREAD

**Issue by ripannandy** [MicrosoftDocs/dynamics-365-unified-operations-public#1598]
I am unable to get the data from UAT/TEST environment using dequeue job but there is no issue with getting data from dev environment. Download location that is returned from dev environment contains "Https://***" but from test environment contains "Http://***". I have seen in this article that, URI scheme has to be set properly in middleware while accessing the test environment. How to set the URI scheme in POSTMAN tool?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2535f3a8-a225-3925-fea4-b22769ef90d0
* Version Independent ID: 99dbbaab-c4e6-925b-0fb9-e444af567aa6
* Content: [Recurring integrations - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/recurring-integrations)
* Content Source: [articles/dev-itpro/data-entities/recurring-integrations.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/recurring-integrations.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by RobinARH** [comment]
@Sunil-Garg : Can you take a look? Thanks.

**Comment by RobinARH** [comment]
Created bug 353172 to track this issue.
