### ISSUE TITLE
The tile "Import or Export" does not exists

### ISSUE THREAD

**Issue by lazejanev** [MicrosoftDocs/dynamics-365-unified-operations-public#1602]
In data management when we create a project there are separate tiles for Import and Export projects, and not one tile like mentioned above "Select the Import or Export tile to create a new data project.": 
https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/recurring-integrations#create-a-data-project

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2535f3a8-a225-3925-fea4-b22769ef90d0
* Version Independent ID: 99dbbaab-c4e6-925b-0fb9-e444af567aa6
* Content: [Recurring integrations - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/recurring-integrations#feedback)
* Content Source: [articles/dev-itpro/data-entities/recurring-integrations.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/recurring-integrations.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by tonyafehr** [comment]
@lazejanev, thanks for the feedback. 
@Sunil-Garg, please review and if needed update this topic.

**Comment by Sunil-Garg** [comment]
Thanks Laze. The doc has been updated.
