### ISSUE TITLE
Reschedule and Opt-Out rule were changed from 2019/05.

### ISSUE THREAD

**Issue by YujiImaoka** [MicrosoftDocs/dynamics-365-unified-operations-public#1603]
Reschedule and Opt-Out rule were changed from 2019/05.
Please revise these 2 sections as like below.
 Can I reschedule the planned maintenance?
 How do I opt out of the current maintenance cycle?
https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/planned-maintenance-window-faq

Can I reschedule the planned maintenance?
If there is an absolute business need and you are unable to move forward with the maintenance during the timeframe, submit a request to reschedule by contacting Microsoft support. The downtime for this re-schedule request should be no later than 1 week from the date notified (Note: Please allow for at least an 8-hour lead time for the reschedule window.). 

How do I opt out of the current maintenance cycle?
Microsoft doesn't offer an option to opt out a planned maintenance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c045df4-a0dc-8ab8-0ed0-deb60ba2b827
* Version Independent ID: 8d40df93-3243-f645-6608-40cd0d49e5d8
* Content: [Planned maintenance window FAQ - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/planned-maintenance-window-faq#feedback)
* Content Source: [articles/dev-itpro/lifecycle-services/planned-maintenance-window-faq.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/lifecycle-services/planned-maintenance-window-faq.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @manalidongre
* Microsoft Alias: **manado**

**Comment by sericks007** [comment]
@YujiImaoka, thanks for posting here!

@manalidongre, please answer the questions that were asked, and update the topic if needed.

**Comment by sericks007** [comment]
[Bug 5239365](https://msazure.visualstudio.com/One/_workitems/edit/5239365) has been logged to track this issue.
