### ISSUE TITLE
Consider entire renewal of contents in this page.

### ISSUE THREAD

**Issue by Izmiyash** [MicrosoftDocs/dynamics-365-unified-operations-public#1604]
[Enter feedback here]
It seems this page is based on the announcement published in very early stage of One Version transformation. Many part of them are now obsolete. 

For instance, Though I can see the line saying "There will be 2 major updates in April and October where new experiences can be enabled." in this page, there is no distinguish between  "Major" and "Minor" release as for D365FO according to the later announcement.  

Please get most current information, review entire contents based on it and make corrections.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14372486-6284-da4b-6bbb-30acd36dd7de
* Version Independent ID: f8301c48-61db-e9e5-aba5-413528cd91d2
* Content: [One Version service updates FAQ - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/one-version)
* Content Source: [articles/fin-and-ops/get-started/one-version.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/one-version.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @meeramahabala
* Microsoft Alias: **meeram**

**Comment by sericks007** [comment]
@Izmiyash, thanks for posting this!

@meeramahabala or @ShellyBakke, please review and update the topic as needed.

**Comment by sericks007** [comment]
Bug 368312 has been logged to track this issue.
