### ISSUE TITLE
Do we lose data even if we export database from Tier-1 environment for importing into Tier-2 Sandbox

### ISSUE THREAD

**Issue by satyakejriwal** [MicrosoftDocs/dynamics-365-unified-operations-public#1605]
Do we lose data even if we export database from Tier-1 environment for importing into Tier-2 Sandbox

**Comment by sericks007** [comment]
@satyakejriwal, thanks for posting your question.  Is your question in response to a specific article?  If so, can you please tell me which article so I can assign this question to the appropriate program manager.

**Comment by sericks007** [comment]
Closing as more information about the specific article this issue applies to wasn't provided.  

In the meantime, to get product help you can contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
