### ISSUE TITLE
On Premise

### ISSUE THREAD

**Issue by GeorgeSasDK** [MicrosoftDocs/dynamics-365-unified-operations-public#1606]
Please update this article to reflect the On Premise environments. Maintenance mode not available on LCS for On Premise deployments and must be made via the SQL database.
Also the World Wide Web Publishing Service not available anymore on the new version, instead the AXService must be killed or restarted.

**Comment by sericks007** [comment]
@GeorgeSasDK, thanks for posting your question. Is your question in response to a specific article? If so, can you please tell me which article so I can assign this question to the appropriate program manager.

**Comment by sericks007** [comment]
Closing this issue as more information about the specific article this issue applies to wasn't provided.

In the meantime, to get product help you can contact Support using one of the options described here: Support contact options. In particular, you might want to go to the Dynamics 365 for Finance and Operations community page to get help with your questions from the Dynamics community.
