### ISSUE TITLE
Better REST API documentation

### ISSUE THREAD

**Issue by bvpb** [MicrosoftDocs/dynamics-365-unified-operations-public#1607]
Is it possible to provide detailed technical information for all of the REST API endpoints?

An OpenAPI definition would be ideal, but at the very least a structured description of the parameters, return values and HTTP status codes.

Also, is it correct to be using the "/data/DataManagementDefinitionGroups/Microsoft.Dynamics.DataEntities.GetMessageStatus" OData endpoint instead of "/api/connector/jobstatus" which seems more appropriate?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2535f3a8-a225-3925-fea4-b22769ef90d0
* Version Independent ID: 99dbbaab-c4e6-925b-0fb9-e444af567aa6
* Content: [Recurring integrations - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/recurring-integrations?toc=%2Ffin-and-ops%2Ftoc.json#feedback)
* Content Source: [articles/dev-itpro/data-entities/recurring-integrations.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/recurring-integrations.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by RobinARH** [comment]
@Sunil-Garg : Can you take a look? Thanks.

**Comment by josaw1** [comment]
Created bug 370225 to track.

**Comment by Sunil-Garg** [comment]
Hi @bvpb can you pls set some time with me at sunilg@microsoft.com at your convenience? I would like to understand the specific asks you have in this area. Thanks.
