### ISSUE TITLE
E-commerce

### ISSUE THREAD

**Issue by AndersDahlin** [MicrosoftDocs/dynamics-365-unified-operations-public#1608]
Hi,

Is what mentioned here about unsupported flows valid for all channels?

"Linked refunds for transactions that use gift cards
Linked refunds for transactions that use loyalty cards"

We cannot automatically refund a return order for an e-commerce order to the same payment methods if multiple payment methods have been used on an online order? Customizations needed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 872de404-8d06-a587-859f-d4589678078e
* Version Independent ID: 93634461-730d-1242-d139-195562968fc1
* Content: [Linked refunds - Refunds of previously approved and confirmed transactions - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/dev-itpro/linked-refunds)
* Content Source: [articles/retail/dev-itpro/linked-refunds.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/dev-itpro/linked-refunds.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @josaw1
* Microsoft Alias: **rapraj**

**Comment by RobinARH** [comment]
@rapraj : Can you take a look? Thanks.

**Comment by josaw1** [comment]
Created bug 370224 to track.

**Comment by rapraj** [comment]
@AndersDahlin - Can you help e clarify your query? I do not understand your question(s)

Is what mentioned here about unsupported flows valid for all channels?
"Linked refunds for transactions that use gift cards
Linked refunds for transactions that use loyalty cards"
[**rapraj**] - The linked refunds for credit cards is only supported in MPOS & CPOS - not in Call-center, HQ or eCommerce

We cannot automatically refund a return order for an e-commerce order to the same payment methods if multiple payment methods have been used on an online order? Customizations needed.
[**rapraj**] -Linked refunds feature is only for CPOS & MPOS arnd supports authorization for Credit/Debit card payment methods only.

**Comment by AndersDahlin** [comment]
OK thank you for the information, we can close this.
