### ISSUE TITLE
Inventory postings setup

### ISSUE THREAD

**Issue by vavd** [MicrosoftDocs/dynamics-365-unified-operations-public#161]
Where can I find information about the "Inventory management &gt; Setut &gt; Posting &gt; Posting" page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c85626b5-b808-da48-143b-f2b3a38b151c
* Version Independent ID: a8a383ba-90af-d2d3-21dd-fabb8ef09ace
* Content: [Inventory management home page - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/inventory/inventory-home-page)
* Content Source: [articles/supply-chain/inventory/inventory-home-page.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/inventory/inventory-home-page.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @YuyuScheller
* Microsoft Alias: **perlynne**

**Comment by ShylaThompson** [comment]
Bug logged: 217493

**Comment by ShylaThompson** [comment]
@vavd, thanks for identifying this gap in documentation. We have a work item planned for the future on this.
