### ISSUE TITLE
First step of Vendor Creation

### ISSUE THREAD

**Issue by olufemioyedepo** [MicrosoftDocs/dynamics-365-unified-operations-public#1613]
[Enter feedback here]
Go to Procurement and sourcing > **Vendors** > All vendors.
should be Go to Procurement and sourcing > **All suppliers** > All vendors. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70a98db8-a47c-3ed1-2eed-ce60fae763e2
* Version Independent ID: 2e6824ce-c8b2-d0be-b479-7514df8b84f5
* Content: [Create a vendor account - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/procurement/tasks/create-vendor-account)
* Content Source: [articles/supply-chain/procurement/tasks/create-vendor-account.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/procurement/tasks/create-vendor-account.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @mkirknel
* Microsoft Alias: **mkirknel**

**Comment by josaw1** [comment]
Created bug 370228 to track.

**Comment by josaw1** [comment]
Hi, @MaiKirknel said this:
This is a matter of translation - If the user is on an English (UK) version of the product they traslate this to "suppliers"
So this is a "by design"  please close.
