### ISSUE TITLE
More Description Needed

### ISSUE THREAD

**Issue by evanfitzgerald** [MicrosoftDocs/dynamics-365-unified-operations-public#1617]
Would it be possible to give some more detail on how the commands function?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c23c1df5-a8e5-15a8-27cf-3206e61c09fc
* Version Independent ID: ecfd274b-3b74-d8aa-2830-9a7e64bce958
* Content: [Use Regression suite automation tool tutorial - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/hol-use-regression-suite-automation-tool#feedback)
* Content Source: [articles/fin-and-ops/get-started/hol-use-regression-suite-automation-tool.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/hol-use-regression-suite-automation-tool.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **kfend**

**Comment by josaw1** [comment]
Bug 370227 created to track.

**Comment by robadawy** [comment]
We will be publishing the full reference for the command line. In the meantime, you can reach out to support and they can share a doc after contacting the product team.
