### ISSUE TITLE
Playback for derived test cases?

### ISSUE THREAD

**Issue by evanfitzgerald** [MicrosoftDocs/dynamics-365-unified-operations-public#1618]
Since a derived test case has no .dll file it cannot be used by the 'playback' command. Is it possible to introduce a way for a 'playback' for derived cases so they can run like in the RSAT?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c23c1df5-a8e5-15a8-27cf-3206e61c09fc
* Version Independent ID: ecfd274b-3b74-d8aa-2830-9a7e64bce958
* Content: [Use Regression suite automation tool tutorial - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/hol-use-regression-suite-automation-tool#feedback)
* Content Source: [articles/fin-and-ops/get-started/hol-use-regression-suite-automation-tool.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/hol-use-regression-suite-automation-tool.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **kfend**

**Comment by josaw1** [comment]
Bug 370227 created to track.
