### ISSUE TITLE
URL references in Authorization code grant flow diagram

### ISSUE THREAD

**Issue by tomhig** [MicrosoftDocs/dynamics-365-unified-operations-public#1622]
In the Authorization code grant flow diagram above, step 2 states "http://login.windows.net/&lt;tenant&gt;" for the AAD authentication URL and step 3 states "http://&lt;baseUri&gt; for the Resource URL. The prefix for each of these should be https, so that there is no question about whether it is an encrypted connection. It is indeed an encrypted connection. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ba7bfc1-7c23-5662-8f2c-b41b19fb9070
* Version Independent ID: 19eb0a4a-1594-8f8b-054c-2c851df17e8b
* Content: [Service endpoints overview - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/services-home-page)
* Content Source: [articles/dev-itpro/data-entities/services-home-page.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/services-home-page.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by sericks007** [comment]
@tomhig, thanks for making us aware of this!

@Sunil-Garg, please update the illustration.

**Comment by sericks007** [comment]
Bug 369845 has been logged to track this issue.

**Comment by Sunil-Garg** [comment]
Thanks, the diagram is updated.

**Comment by sericks007** [comment]
The diagram was updated in [PR 6261](https://github.com/MicrosoftDocs/Dynamics-365-Operations/pull/6261) and will be published soon.
