### ISSUE TITLE
Use of cache

### ISSUE THREAD

**Issue by johnmkonrad** [MicrosoftDocs/dynamics-365-unified-operations-public#1623]
We've done testing with various "Use of Cache" settings and get nearly the exact same runtime.  I've read elsewhere that this setting was made obsolete to be managed by the MRP engine dating back to 2014?  Is this not the case?  Would be nice to note this in the documentation or just deprecate the setting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4d94c07-68fa-b36b-9a2b-e79dbd0b474f
* Version Independent ID: 74c49920-d228-2d81-8530-0f5a557e1aad
* Content: [Improve master planning performance - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/master-planning/master-planning-performance#feedback)
* Content Source: [articles/supply-chain/master-planning/master-planning-performance.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/master-planning/master-planning-performance.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @t-benebo
* Microsoft Alias: **benebotg**

**Comment by t-benebo** [comment]
The "Use of cache" setting is applicable (it has not been deprecated). Its influence on your master planning runtime will depend on your data composition. In some cases it may not affect while in others it can make a huge difference.

**Comment by johnmkonrad** [comment]
Thanks Beatriz, this is very helpful.
