### ISSUE TITLE
Clarification sought on vCore model,Managed Instances, as well as DTU (Premium / Standard) model of Azure SQL

### ISSUE THREAD

**Issue by sayanghosh123** [MicrosoftDocs/dynamics-365-unified-operations-public#1627]
The current guidance around Azure SQL states 
"If you're using the BYOD feature for integration with a business intelligence (BI) tool, you should consider creating a SQL premium database. Premium databases support clustered columnstore indexes (CCIs)." and some similar content in step 4.

As per https://azure.microsoft.com/en-au/blog/columnstore-support-in-standard-tier-azure-sql-databases/, CCIs are supported in Standard S3 onwards. As a result, does this page need to be updated, or is there any other restriction that still makes Premium the preferred DTU tier?

In addition, some guidance around the vCore model of SQL Azure will be appreciated. What is the preferred tier (General Purpose / Business Critical / Hyperscale) and why? As the referred blog post states, CCIs are supported in all vCore based models.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cd981b1-0ed1-34c8-d22a-e1c6d194ff9c
* Version Independent ID: 1e26cccc-eab2-e170-7004-98585128e3e1
* Content: [Bring your own database (BYOD) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/export-entities-to-your-own-database#)
* Content Source: [articles/dev-itpro/analytics/export-entities-to-your-own-database.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/export-entities-to-your-own-database.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by tonyafehr** [comment]
Bug 371166 has been logged to track this issue.

**Comment by tonyafehr** [comment]
This is has been clarified. The updated topic will be published soon.
