### ISSUE TITLE
Online Invoicing system

### ISSUE THREAD

**Issue by SilGitHub** [MicrosoftDocs/dynamics-365-unified-operations-public#1628]
Is there a reason why the online invoicing system is not included in the Hungarian overview?
https://support.microsoft.com/en-gb/help/4499832/hungary-online-invoicing-system-v-1-1-support-on-dynamics-365-for-fina

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a7b6aab-f5f6-8f67-ea96-f6ae9c6a5866
* Version Independent ID: 51f7f324-93ee-64b8-458f-b07f537b60bd
* Content: [Hungary overview - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/localizations/hungary)
* Content Source: [articles/financials/localizations/hungary.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/localizations/hungary.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @ShylaThompson
* Microsoft Alias: **shylaw**

**Comment by LizaGolub** [comment]
Hello,
Thank you for your question.
There is no specific reason why the Online Invoicing System is not included in documentation for Hungary.
For now, there are several KB articles dedicated to this topic:
https://support.microsoft.com/en-us/help/4341649
https://support.microsoft.com/en-us/help/4499832
There is a plan to publish also a common article on docs.microsoft.com dedicated to this feature.
