### ISSUE TITLE
Upgrade to the on-premises version

### ISSUE THREAD

**Issue by MSaad086** [MicrosoftDocs/dynamics-365-unified-operations-public#163]
Hi Can you suggest is Upgrade to the on-premises version of D365 Operations is available now? if not by when is it expected to release? and till that time if a customer wants to upgrade from AX 2012 to D365 On-premise what is the solution?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afebec12-9838-906e-1c0a-a435b9be3777
* Version Independent ID: dec9bdde-ac60-4c13-72b5-b3709f6b7089
* Content: [Upgrade Dynamics AX 2012 to Dynamics 365 for Finance and Operations - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/upgrade-overview-2012)
* Content Source: [articles/dev-itpro/migration-upgrade/upgrade-overview-2012.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/migration-upgrade/upgrade-overview-2012.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @tariqbell
* Microsoft Alias: **tabell**

**Comment by rsantana123** [comment]
I am also interested. Can we get any info on this ?

**Comment by MSaad086** [comment]
Hi, @MargoC 
Thank you for your Answer, it was really helpful.

However my Question was a bit specific about Upgrade from AX 2012 On-Premises to D365 Operations On-premises, the above article mentions step by step guide for upgrade from AX 2012 On-Premises to D365 Operations On-Cloud, is it technically possible to Upgrade AX 2012 On-Premises to D365 Operations On-premises?

**Comment by LogicoCR** [comment]
Hi @MargoC. Any news on tools to upgrade from AX 2012 to Dyn365 OnPremise?

**Comment by dynsm** [comment]
Is the Ax2012 on-premise to D365FO on-premise ready yet?

**Comment by sericks007** [comment]
Bug 346938 has been logged to track this issue.

**Comment by ansartroops** [comment]
Is Ax 2012 to D365FO on-premises Upgrade available yet?

**Comment by PeterRFriis** [comment]
Hi 
Ax2012 to D365FO on-premises Upgrade is not available at this time.
Currently I cannot provide a timeline for when it will be available.
Looping in @sarvanisathish.
Thansk,
Peter

**Comment by sarvanisathish** [comment]
Hello, at this time this ask is in the backlog. We are hoping to prioritize this for H2CY2020.
