### ISSUE TITLE
Default DB storage and file storage

### ISSUE THREAD

**Issue by ripannandy** [MicrosoftDocs/dynamics-365-unified-operations-public#1631]
As per new licensing guide, I heard that, 

File storage: Every customer receives 40 GB of file/Azure blob cloud storage for files and binary data instead of 100 GB that is written in this page.

Database storage: Every Finance and Operations subscription includes 20 GB of Azure SQL Database storage per customer at no additional charge instead of 10 GB that is written in this page.

Are these information correct?

**Comment by sericks007** [comment]
Closing as a duplicate. See [issue 1632](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/issues/1632).
