### ISSUE TITLE
Default DB storage and file storage

### ISSUE THREAD

**Issue by ripannandy** [MicrosoftDocs/dynamics-365-unified-operations-public#1632]
As per new licensing guide, I heard that,

File storage: Every customer receives 40 GB of file/Azure blob cloud storage for files and binary data instead of 100 GB that is written on this page.

Database storage: Every Finance and Operations subscription includes 20 GB of Azure SQL Database storage per customer at no additional charge instead of 10 GB that is written on this page.

Are these information correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00f88ef5-f857-b53e-8835-b944e8217560
* Version Independent ID: 1993cec6-ee86-f44d-97dc-107216269ccc
* Content: [Environment planning - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/imp-lifecycle/environment-planning)
* Content Source: [articles/fin-and-ops/imp-lifecycle/environment-planning.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/imp-lifecycle/environment-planning.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @ClaudiaBetz-Haubold
* Microsoft Alias: **chaubold**

**Comment by sericks007** [comment]
Thanks for contacting us! Unfortunately, our Documentation team is unable to answer questions related to the licensing guide.  Please consider posting your questions via one of the channels listed [here](https://dynamics.microsoft.com/en-us/contact-us/).

**Comment by chr-lim** [comment]
The licensing guide is the source of truth to know the amount of storage (whether file or database) included or added incrementally, refer to its latest version for the exact numbers.
