### ISSUE TITLE
RetailUpdateDatabase

### ISSUE THREAD

**Issue by OksanaKovaliova** [MicrosoftDocs/dynamics-365-unified-operations-public#1633]
Hi, is above article still valid? For version 10 of on-prem retail. 
I tried to find RetailUpdateDatabase.ps1 script - but it does not exist neither in binary package, nor anywhere on AOS machine. 
Also D365 is able to find retail packages without selfservicepackages folder creation and any steps described in 1-6 steps. Looks like it uses standard folder C:\RetailSelfService\Packages
Thank you!

---
#### Dokumentinformasjon

⚠ *Ikke rediger denne delen. Den kreves for koblingen docs.microsoft.com ➟ GitHub-problem.*

* ID: ecc51933-08be-36c7-8f82-d9df6f220bfa
* Version Independent ID: 29846b09-d0e5-9076-d451-0f86429a778a
* Content: [Installation steps for Retail channel components in an on-premises environment - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/nb-no/dynamics365/unified-operations//dev-itpro/deployment/deploy-retail-onprem#feedback)
* Content Source: [articles/dev-itpro/deployment/deploy-retail-onprem.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/deployment/deploy-retail-onprem.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @jashanno
* Microsoft Alias: **jashanno**

**Comment by sericks007** [comment]
@OksanaKovaliova, thanks for posting this!

@jashanno, please review and update the content as needed.

**Comment by tonyafehr** [comment]
Bug 371167 has been logged to track this issue.
