### ISSUE TITLE
Add pause between two test steps?   

### ISSUE THREAD

**Issue by AshyM** [MicrosoftDocs/dynamics-365-unified-operations-public#1635]
Is there a way to add pause between two test step (within a test case) ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c23c1df5-a8e5-15a8-27cf-3206e61c09fc
* Version Independent ID: ecfd274b-3b74-d8aa-2830-9a7e64bce958
* Content: [Use Regression suite automation tool tutorial - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/hol-use-regression-suite-automation-tool#feedback)
* Content Source: [articles/fin-and-ops/get-started/hol-use-regression-suite-automation-tool.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/hol-use-regression-suite-automation-tool.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **kfend**

**Comment by sericks007** [comment]
@AshyM, thanks for posting this! In the meantime, to get product help you can contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

@kfend, please review and update the content, if needed.

**Comment by tonyafehr** [comment]
Bug 371169 has been logged to track this issue.

**Comment by kfend** [comment]
Thanks for your question, @Ashym, At this time, you can't pause between two test steps, but that functionality will become available druing the month of October.
