### ISSUE TITLE
Missing information about name of entities extensions

### ISSUE THREAD

**Issue by sminozhenko** [MicrosoftDocs/dynamics-365-unified-operations-public#1637]
Hi, I noticed that the article is missing the part that entity extensions created through "Add financial dimensions for OData" add-on from Visual studio have to keep original extension name "DimensionIntegration", otherwise views created on SQL side will return empty values instead of real dimension values. Could you, please, add this information?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ebffb14-e6b3-dc4d-058a-e7fe1d9cf183
* Version Independent ID: 35d7818f-96ef-0724-f124-fd693d0510af
* Content: [Add dimensions to Excel templates - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/financial/dimensions-overview)
* Content Source: [articles/dev-itpro/financial/dimensions-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/financial/dimensions-overview.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **rbrow**

**Comment by sericks007** [comment]
@sminozhenko, thanks for letting us know!

@RobinARH, please review and update the content as needed.

**Comment by tonyafehr** [comment]
Bug 371172 has been logged to track this issue.
