### ISSUE TITLE
Many of the links here no longer works

### ISSUE THREAD

**Issue by kurthatlevik** [MicrosoftDocs/dynamics-365-unified-operations-public#1638]
When clicking on the links I get "Event Unavailable" - Sorry, it looks like Dynamics 365 for Retail POS Extensibility: Deep Dive (DYN342PAL) is no longer available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f271eeaf-54e1-5476-bfbf-37f8b899c425
* Version Independent ID: b5156471-8259-9cbd-f68b-ad4a9a4c864a
* Content: [Videos for Finance and Operations - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/videos#feedback)
* Content Source: [articles/fin-and-ops/get-started/videos.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/videos.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by sericks007** [comment]
@kurthatevik, thanks for letting us know!  We'll investigate.

**Comment by sericks007** [comment]
We've updated the content to remove the broken links.  FastTrack Tech Talks are now available on the [community.dynamics.com](https://community.dynamics.com/365/b/techtalks?c=Finance%20and%20Operations) site.
