### ISSUE TITLE
Data entity for GTIN

### ISSUE THREAD

**Issue by Fyrste** [MicrosoftDocs/dynamics-365-unified-operations-public#1639]
Hi,

When is it planned to release an entity for GTIN? Barcodes and GTIN are not interchangeable as such, and an entity for GTIN is highly required.

Thank you in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0647d0d4-fe0b-fdba-07d4-ed2379a5129b
* Version Independent ID: 6a1a026f-39c9-dc27-b25c-a727f1a252c4
* Content: [Product identifiers - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/pim/product-identifiers#feedback)
* Content Source: [articles/supply-chain/pim/product-identifiers.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/pim/product-identifiers.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @cvocph
* Microsoft Alias: **conradv**

**Comment by sericks007** [comment]
Thanks for contacting us!  For more information about features that are planned, please see the [Release Plans}(https://docs.microsoft.com/en-us/dynamics365/release-plans/).

To request a feature, please see the [Ideas site](https://experience.dynamics.com/ideas/).
