### ISSUE TITLE
You can't export composite entities into your own database

### ISSUE THREAD

**Issue by axaeffect** [MicrosoftDocs/dynamics-365-unified-operations-public#1640]
Just curios, was it error if we select entities which is composite ? what is the error message looks like ? or do we can't even choose (no selection) for that target entities made by composite ?
Please help to describe more.
Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cd981b1-0ed1-34c8-d22a-e1c6d194ff9c
* Version Independent ID: 1e26cccc-eab2-e170-7004-98585128e3e1
* Content: [Bring your own database (BYOD) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/export-entities-to-your-own-database)
* Content Source: [articles/dev-itpro/analytics/export-entities-to-your-own-database.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/export-entities-to-your-own-database.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by sericks007** [comment]
@axaeffect, thanks for posting here!

@Sunil-Garg, please review and update the content, as needed.

**Comment by sericks007** [comment]
Bug 371477 has been logged to track this issue.

**Comment by Sunil-Garg** [comment]
@axaeffect, you are right. As noted in this wiki, composite entities are not supported to export to BYOD. You will be able to select but, when publish will fail right away with an error that composite entity cannot be published. Hope this helps.
