### ISSUE TITLE
"Default extension" field undocumented

### ISSUE THREAD

**Issue by ccampora** [MicrosoftDocs/dynamics-365-unified-operations-public#1642]
Please add documentation regarding the "Default extension" field. This is missing in the document. Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cd981b1-0ed1-34c8-d22a-e1c6d194ff9c
* Version Independent ID: 1e26cccc-eab2-e170-7004-98585128e3e1
* Content: [Bring your own database (BYOD) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/export-entities-to-your-own-database#feedback)
* Content Source: [articles/dev-itpro/analytics/export-entities-to-your-own-database.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/export-entities-to-your-own-database.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by sericks007** [comment]
@ccampora, thanks for making us aware of this!

@Sunil-Garg, please review and update the content as requested.

**Comment by sericks007** [comment]
Bug 371478 has been logged to track this issue.

**Comment by Sunil-Garg** [comment]
@ccampora, can you clarify which section of the documentation are you referring to when talking about 'default extension' field? I don't find any references to that in this BYOD related wiki :)

**Comment by ccampora** [comment]
When you configure the source data format (first image on this document) you can see the field "default extension" at the let end of the image. Like you said there isn't any reference on this document to what the field does.

**Comment by Sunil-Garg** [comment]
@ccampora thanks for pointing that out. We have added a note just below the image clarifying that this field does not apply to BYOD. Thanks.
