### ISSUE TITLE
Need more details 

### ISSUE THREAD

**Issue by mmoalla** [MicrosoftDocs/dynamics-365-unified-operations-public#1648]
Hello,

Not working. Could you please details the process by exemple ? 

Thnaks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3565b319-747b-2aa4-36f0-6296adf930fb
* Version Independent ID: 847c2a77-9613-33ad-4455-bda3924b4286
* Content: [Uninstall a package - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/deployment/uninstall-deployable-package#feedback)
* Content Source: [articles/dev-itpro/deployment/uninstall-deployable-package.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/deployment/uninstall-deployable-package.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Manado
* Microsoft Alias: **robadawy**

**Comment by RobinARH** [comment]
Thanks for contacting us. At this time, we don't plan to add additional content to this topic.  -Robin
