### ISSUE TITLE
Application permissions section doesn't match the current Azure options

### ISSUE THREAD

**Issue by Gadgetgeek2000** [MicrosoftDocs/dynamics-365-unified-operations-public#1651]
Request API permissions is very different than the screenshot you have provided for requesting permissions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 717d397d-4186-c7de-431d-3260d3f0484a
* Version Independent ID: bdd7545b-5970-93e0-5cbb-a59da4ace01b
* Content: [Configure Power BI integration for workspaces - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/configure-power-bi-integration#feedback)
* Content Source: [articles/dev-itpro/analytics/configure-power-bi-integration.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/configure-power-bi-integration.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by RobinARH** [comment]
@MilindaV2 - Can you take a look? Thanks.

**Comment by RobinARH** [comment]
Created bug 381316 to track this issue.
