### ISSUE TITLE
Overlayering is no longer supported

### ISSUE THREAD

**Issue by jawn** [MicrosoftDocs/dynamics-365-unified-operations-public#1653]
The page still talks about overlayering as an option.

However, as the following (https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/extensibility/extensibility-home-page) page explains, overlayering is no longer supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd0c5515-aa2a-64c2-e5b6-093eecdfff53
* Version Independent ID: 53446ef1-fc30-9ad1-d097-409fcd5c7949
* Content: [Development and continuous delivery FAQ - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-tools/continuous-delivery-faq)
* Content Source: [articles/dev-itpro/dev-tools/continuous-delivery-faq.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-tools/continuous-delivery-faq.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **robadawy**

**Comment by RobinARH** [comment]
@robadawy Can you take a look? thanks.

**Comment by RobinARH** [comment]
Bug 381308 created to track this issue.

**Comment by RobinARH** [comment]
I corrected the text and the new text will be published live later today. - Robin
