### ISSUE TITLE
Sandboxes without server access

### ISSUE THREAD

**Issue by mawa77** [MicrosoftDocs/dynamics-365-unified-operations-public#1654]
How we should import the AX 2012 database without access to AOS server through RDP? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: babaa821-a53a-020c-4411-d2c39e371d05
* Version Independent ID: afb66707-3384-278c-2827-cff7499c56ea
* Content: [Upgrade from AX 2012 - Data upgrade in sandbox environments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/upgrade-data-sandbox#feedback)
* Content Source: [articles/dev-itpro/migration-upgrade/upgrade-data-sandbox.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/migration-upgrade/upgrade-data-sandbox.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @tariqbell
* Microsoft Alias: **tabell**

**Comment by RobinARH** [comment]
@laneswenka - Can you take a look? Thanks.

**Comment by RobinARH** [comment]
Created bug 381304 to track this issue.

**Comment by mawa77** [comment]
Current documentation does not apply to self service aka service fabric environments. The question is how we should do the data upgrade in sandbox (or production) when we have self service sandboxes? Could you please update the documentation or should we create a support ticket? We have customer project ongoing where the plan is to do the data upgrade

**Comment by laneswenka** [comment]
You will want a support ticket to redeploy your environments off self-service. We have work in progress to identify 2012 customers and enforce this in future.

Lane

Sent from my iPhone

On Oct 15, 2019, at 5:22 AM, mawa77 <notifications@github.com<mailto:notifications@github.com>> wrote:


Current documentation does not apply to self service aka service fabric environments. The question is how we should do the data upgrade in sandbox (or production) when we have self service sandboxes? Could you please update the documentation or should we create a support ticket? We have customer project ongoing where the plan is to do the data upgrade
