### ISSUE TITLE
Credit Invoicing on Free Text Invoice

### ISSUE THREAD

**Issue by vishwaspkale** [MicrosoftDocs/dynamics-365-unified-operations-public#1656]
How the Credit Invoicing on Free Text Invoice work? There's an option but it's disabled and there's no help text on that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d47e817-0a96-1769-5a43-0cf61d1978a2
* Version Independent ID: d8e5818e-f399-0540-2129-2c2214c3cc5f
* Content: [Create a corrective invoice (Spain) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/localizations/tasks/emea-esp-credit-invoicing#feedback)
* Content Source: [articles/financials/localizations/tasks/emea-esp-credit-invoicing.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/localizations/tasks/emea-esp-credit-invoicing.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @ShylaThompson
* Microsoft Alias: **shylaw**

**Comment by tonyafehr** [comment]
@kfend, can you review this feedback. Thanks!

**Comment by v-oloski** [comment]
Hello,
Thank you for your asking!
The **Credit invoicing** button is available when you create Free text invoice with negative amount. Th process is following:
1. A user create a free text invoice with positive amount.
2. Create a free text invoice (FTI) with negative amount, save the FTI. 
After saving the button is available.
3. Click this button and fill in the fields.
4. On the **Line detail** FastTab  fill in the reason code.

**Comment by vishwaspkale** [comment]
Thank you!
