### ISSUE TITLE
Missing information about "in" keyword in "where" clause

### ISSUE THREAD

**Issue by sminozhenko** [MicrosoftDocs/dynamics-365-unified-operations-public#1657]
Hi, Looks like the document is missing information about "in" keyword in "where" clause. Could you check it, please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f2875aa-c614-a807-90eb-247f8259cb1b
* Version Independent ID: 95a6e7b3-2f3d-cdb2-64e6-7c610704ae78
* Content: [X++ data selection and manipulation - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-ref/xpp-data-query#syntax-of-select-statements)
* Content Source: [articles/dev-itpro/dev-ref/xpp-data-query.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-ref/xpp-data-query.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **rhaertle**

**Comment by tonyafehr** [comment]
@RobinARH, can you review this feedback. Thanks!

**Comment by RobinARH** [comment]
It's on my ToDo list to add information about the In keyword. I'll post back here when I publish the new content.

**Comment by RobinARH** [comment]
It's documented now: https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-ref/xpp-data/xpp-select-statement#in-keyword
