### ISSUE TITLE
Integration for Pricing between FinOps & CE

### ISSUE THREAD

**Issue by AartiKumar** [MicrosoftDocs/dynamics-365-unified-operations-public#1658]
Is there a roadmap or guidelines about integration between D365 FinOps & D365 CE for Pricing. 
Sales quotes are created from D365 CE but there are scenerios where sales orders are created in D365 FinOps. How we can integrate the Trade agreements in FinOps with the price lists in D365 CE

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a0b764a-dd6b-581b-5d94-50e2af76c360
* Version Independent ID: 9eadf0e8-a4d2-6eb6-93f6-f4ba3a4ba2d0
* Content: [Synchronize products directly from Finance and Operations to products in Sales - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/sales-marketing/products-template-mapping-direct#feedback)
* Content Source: [articles/supply-chain/sales-marketing/products-template-mapping-direct.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/sales-marketing/products-template-mapping-direct.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @ChristianRytt
* Microsoft Alias: **crytt**

**Comment by sericks007** [comment]
@AartiKumar, thanks for posting here!

@ChristianRytt, can you please review and answer the questions.  Please update the topic if needed.

**Comment by sericks007** [comment]
Bug 373234 has been logged to track this issue.

**Comment by ChristianRytt** [comment]
We plan to include a possibility to trigger the price calculation in Finance and Operations and return the result on related sales order or quote in D365CE. This is planned as part of Dual Write.
https://docs.microsoft.com/en-us/business-applications-release-notes/april19/cdm-data-integration/dual-write-link-common-data-service-apps
