### ISSUE TITLE
Add reference to 'Environment planning' page

### ISSUE THREAD

**Issue by JeroenLeeflang** [MicrosoftDocs/dynamics-365-unified-operations-public#1659]
The section about how many sandboxes are needed is very short. Maybe add a reference to the 'Environment planning' page (https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/imp-lifecycle/environment-planning). 

Using the Tier-2 for both configuration and UAT doesn't seem realistic to me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd0c5515-aa2a-64c2-e5b6-093eecdfff53
* Version Independent ID: 53446ef1-fc30-9ad1-d097-409fcd5c7949
* Content: [Development and continuous delivery FAQ - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-tools/continuous-delivery-faq#customer-implementation-lcs-projects)
* Content Source: [articles/dev-itpro/dev-tools/continuous-delivery-faq.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-tools/continuous-delivery-faq.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **robadawy**

**Comment by sericks007** [comment]
@JeroenLeeflang, thanks for posting here!  I've added the link, as you suggested -- that update will be published later today.

@robadawy, can you please review the comment related to Tier-2.  Please update the topic if needed.

**Comment by sericks007** [comment]
Bug 377134 has been logged to track this issue.

**Comment by sericks007** [comment]
Closing, as the link has been added as suggested.

I discussed the Tier-2 comment with a PM, and he feels that the article sufficiently identifies you can get more Tier-2 environments to support your needs.
