### ISSUE TITLE
Finland does not use BankGiro - This should read Sweden?

### ISSUE THREAD

**Issue by Kotiann** [MicrosoftDocs/dynamics-365-unified-operations-public#1660]
Finland ---&gt; Sweden

In addition to the generated invoice form, Giro money transfer slips can be generated as follows:
For the legal entity that uses the country/region context for Finland, and that has at least one bank account that is marked as Giro account and Bank bar code.
For an invoice that is marked as required for the Finnish associated payment attachment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d35a48a9-b24d-8572-ca98-6a7ccbb01f57
* Version Independent ID: 7cee0a99-7281-6030-90b3-8ace2667709a
* Content: [Generate printable FTI forms - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/er-generate-printable-fti-forms#feedback)
* Content Source: [articles/dev-itpro/analytics/er-generate-printable-fti-forms.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/er-generate-printable-fti-forms.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @NickSelin
* Microsoft Alias: **nselin**

**Comment by NickSelin** [comment]
The possibility to print out Giro payment slips along with customer invoices for Finland was and is still supported in the application as the controlled by parameters option.

Please, refer to the "Payment slip report for Europe" document https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/localizations/emea-eur-payment-slip-report-giro for more details.
