### ISSUE TITLE
the instructions are incomplete

### ISSUE THREAD

**Issue by ceddings2112** [MicrosoftDocs/dynamics-365-unified-operations-public#1665]
I can't make the queries work can you add more information on how these queries work?
Automatically assign users to roles
Go to Navigation pane &gt; Modules &gt; System administration &gt; Security &gt; Assign users to roles.
In the tree, select 'Accounting supervisor'. Select the role that you want to configure the rule for. In this example, select Accounting supervisor.
Click Add rule to open the drop dialog.
In the Select a querylist, find and select the desired record. Select the query to use for this rule.
In the Membership rule name list, click the link in the selected row.
Click Edit query. Edit the query, as needed.
Click OK.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30166378-a551-155a-29ec-199d20810512
* Version Independent ID: 617e04b0-d40c-5c0b-96dc-16adefb499ed
* Content: [Assign users to security roles - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/sysadmin/tasks/assign-users-security-roles#feedback)
* Content Source: [articles/dev-itpro/sysadmin/tasks/assign-users-security-roles.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/sysadmin/tasks/assign-users-security-roles.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @maertenm
* Microsoft Alias: **maertenm**

**Comment by RobinARH** [comment]
@chrisgarty - Can you take a look? You make the latest updates to this topic.
@sericks007 - Can you update the topic authors?

Thanks - Robin

**Comment by sericks007** [comment]
I've updated the author metadata in the private repo.

**Comment by tonyafehr** [comment]
Bug 376891 has been logged to track this issue.

**Comment by ChrisGarty** [comment]
Added mention of "Run automatic role assignment" and reviewing in the Users form

**Comment by ChrisGarty** [comment]
https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/pull/1839
