### ISSUE TITLE
Using Raw Logs

### ISSUE THREAD

**Issue by tomhig** [MicrosoftDocs/dynamics-365-unified-operations-public#167]
An excellent detailed article on how to use Raw Logs in Environment Monitoring. Well worth a cross-reference link: https://blogs.msdn.microsoft.com/axsa/2018/06/05/how-to-use-environment-monitoring-view-raw-logs/ 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c73b0eff-ab53-afb9-b3e2-40f94cb71a3e
* Version Independent ID: 069fa33b-6a69-2d29-908d-fca5ca0dc516
* Content: [Monitoring and diagnostics (Lifecycle Services, LCS) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/monitoring-diagnostics)
* Content Source: [articles/dev-itpro/lifecycle-services/monitoring-diagnostics.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/lifecycle-services/monitoring-diagnostics.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @manalidongre
* Microsoft Alias: **manado**

**Comment by MargoC** [comment]
Thanks Tom, added.
