### ISSUE TITLE
Wrong "Additional resources" link

### ISSUE THREAD

**Issue by primeitbr** [MicrosoftDocs/dynamics-365-unified-operations-public#1671]
The first "Additional resources" link on this page points to the PU28 additional resources page.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 54cb6abe-0f3d-ba5f-7725-48ad458974a5
* Version Independent ID: e0eeda33-408f-3f1f-8d37-536e98b0cdbb
* Content: [What's new or changed in Dynamics 365 for Finance and Operations platform update 29 (October 2019) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/pt-br/dynamics365/unified-operations/fin-and-ops/get-started/whats-new-platform-update-29)
* Content Source: [articles/fin-and-ops/get-started/whats-new-platform-update-29.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/whats-new-platform-update-29.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @tonyafehr
* Microsoft Alias: **tfehr**

**Comment by josaw1** [comment]
I [updated the link ](https://fix.lcs.dynamics.com/Issue/Details?kb=4515866&bugId=348252&dbType=3&qc=75eda4912fe476283a638fbb74fe1619ee8d1ac63a506b1197697c1c4693d1fc)and it will be published later today.
