### ISSUE TITLE
Get lock details - different in LCS

### ISSUE THREAD

**Issue by mpburtt** [MicrosoftDocs/dynamics-365-unified-operations-public#1672]
The "Get lock details" query described here would be useful but the feature actually implemented in LCS with this query name has a parameter labelled "Table name" and returns lock properties of the indexes of that table. For example, here's what the query returns if I enter "ProjTable" as the table name... 

IndexName	IndexType	RowLocks	PageLocks	IsUnique	IsPrimaryKey	IsUniqueConstraint	IgnoreDupKey	ColumnName	ColumnOrder	ColumnIncluded
										
I_1074ASSETIDX	NONCLUSTERED	TRUE						PARTITION	1	
I_1074ASSETIDX	NONCLUSTERED	TRUE						DATAAREAID	2	
I_1074ASSETIDX	NONCLUSTERED	TRUE						ASSETID	3	
I_1074CUSTIDX	NONCLUSTERED	TRUE						PARTITION	1	
I_1074CUSTIDX	NONCLUSTERED	TRUE						DATAAREAID	2	
I_1074CUSTIDX	NONCLUSTERED	TRUE						CUSTACCOUNT	3	
I_1074CUSTIDX	NONCLUSTERED	TRUE						PROJID	4	
I_1074DELIVERYLOCATIONIDX	NONCLUSTERED	TRUE						PARTITION	1	
I_1074DELIVERYLOCATIONIDX	NONCLUSTERED	TRUE						DATAAREAID	2	
I_1074DELIVERYLOCATIONIDX	NONCLUSTERED	TRUE						DELIVERYLOCATION	3	

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0eb9329-2038-a4c0-07ea-7b1b649d08f2
* Version Independent ID: 650c15f7-d44c-2cae-e55f-1a609e54d0cf
* Content: [Query cookbook - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/querycookbook#feedback)
* Content Source: [articles/dev-itpro/lifecycle-services/querycookbook.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/lifecycle-services/querycookbook.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @manalidongre
* Microsoft Alias: **manado**

**Comment by tonyafehr** [comment]
Thanks for the feedback.
@manalidongre, please review and consider updates, if appropriate.

**Comment by tonyafehr** [comment]
Bug 5439253 has been logged to track this issue.
