### ISSUE TITLE
Removal of printers in red from DRA

### ISSUE THREAD

**Issue by studmuffinjj** [MicrosoftDocs/dynamics-365-unified-operations-public#1673]
After renaming printers and moving around from UAT to production environments, I have several printers which are no longer in use showing up at the top of my DRA in red. They are ticked, but with a status of not installed. These printers are no longer needed in the environment.

If they are unticked and I register them in the DRA, when I re-enter the printer window, they are still there, ticked. Deleting the printer from D365 succeeds, but when the printer screen for the DRA is reopened, they show back in D365 again.

Is there a way to remove these printers from both the DRA and D365 short of completely removing the DRA application, removing the associated folders and reinstalling?

**Comment by tonyafehr** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
