### ISSUE TITLE
Master Planning Wizard - Functionality

### ISSUE THREAD

**Issue by adrianmizzimlt** [MicrosoftDocs/dynamics-365-unified-operations-public#1674]
I found that this functionality will be released in 10.0.5.   Can't see it in release notes, did it make it through?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d233ac7e-29a6-1974-b86e-e7754c1a4659
* Version Independent ID: b6401971-4cd0-8479-82bf-39644c3f6c63
* Content: [Master planning setup wizard - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/master-planning/master-planning-setup-wizard#feedback)
* Content Source: [articles/supply-chain/master-planning/master-planning-setup-wizard.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/master-planning/master-planning-setup-wizard.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @t-benebo
* Microsoft Alias: **benebotg**

**Comment by tonyafehr** [comment]
@josaw1, please review this. Thank you!

**Comment by adrianmizzimlt** [comment]
I refer to https://docs.microsoft.com/en-us/business-applications-release-notes/april19/dynamics365-finance-operations/planned-features


Feature | Release type | Cloud or on-premises | Date
-- | -- | -- | --
Master planning stability and recovery improvements | General Availability | Both | March 8, 2019
Improved removal of obsolete planning data | General Availability | Both | March 8, 2019
_**Master planning configuration wizard | General Availability | Both | September 13, 2019**_
Planning optimization | Public Preview | Cloud | October 2019
Asset management | Public Preview | Both | July 23, 2019

Can you please let me know whether September 13, 2019 is 10.0.5?

**Comment by t-benebo** [comment]
The Master planning setup wizard is released in 10.0.5. Go to the master plans page and select the desired plan you want to configure and click "Setup wizard".
