### ISSUE TITLE
This document requires updating

### ISSUE THREAD

**Issue by dhand01** [MicrosoftDocs/dynamics-365-unified-operations-public#1675]
In Step 7, it describes creating a new Controller sub-class, with a new Main method. However the following line of code now creates a Best Practice deviation:

formLetterController.renderingCompleted += eventhandler(SalesConfirmJournalPrint::renderingCompleted);

This document should be updated to explain how to create the Controller sub-class, while still being able to ensure that these post-rendering delegates can still have event handlers added to them, without BP deviations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62563695-5ac8-7557-4221-19a7187d98c3
* Version Independent ID: 33eb8596-f9a9-c97b-fffc-d91c12b18ebd
* Content: [Create custom designs for business documents - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/custom-designs-business-docs?toc=%2Ffin-and-ops%2Ftoc.json#feedback)
* Content Source: [articles/dev-itpro/analytics/custom-designs-business-docs.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/custom-designs-business-docs.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by sericks007** [comment]
@dhand01, thanks for posting this!

@TJVass, please review and update the content as needed.

**Comment by sericks007** [comment]
Bug 377135 has been logged to track this issue.
