### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by ibruynin** [MicrosoftDocs/dynamics-365-unified-operations-public#1676]
UserSessionServiceetUserSessionInfo must be UserSessionServiceGetUserSessionInfo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be64e79b-f0cc-6450-36e8-24c25f7b982d
* Version Independent ID: 388b396d-95c1-4fef-4199-c6483258c3c5
* Content: [Choose a data integration (import/export) strategy - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/integration-overview?toc=/fin-and-ops/toc.json)
* Content Source: [articles/dev-itpro/data-entities/integration-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/integration-overview.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by sericks007** [comment]
@ibruynin, thanks for letting us know!  I've fixed the error, and the updated content will be published soon.  Thanks again!
