### ISSUE TITLE
KB Article link

### ISSUE THREAD

**Issue by ritagritag** [MicrosoftDocs/dynamics-365-unified-operations-public#1677]
The KB article for 10.0.6 indicates TBD however, the hyperlink takes the user to the KB articles for 10.0.5.  When will the 10.0.6 KB articles be released?  Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2dcd86cc-cbfe-8092-72b0-e6f6b7552cdd
* Version Independent ID: cc3e7b16-1e65-f740-18bf-e46db4491805
* Content: [Preview features in Finance and Operations version 10.0.6 (November 2019) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/whats-new-changed-10-0-6#feedback)
* Content Source: [articles/fin-and-ops/get-started/whats-new-changed-10-0-6.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/whats-new-changed-10-0-6.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @tonyafehr
* Microsoft Alias: **tfehr**

**Comment by josaw1** [comment]
Hi, the new link is here: https://fix.lcs.dynamics.com/Issue/Details?bugId=369581&dbType=3&qc=ba058110be40fe16a39469298041b1a7baf82eb65bb9df4d864602d2c6bf93d7
I've updated the link in the topic and it will go live later today. Thank you!
