### ISSUE TITLE
Link doesn't give inforation about on-premise

### ISSUE THREAD

**Issue by amadse** [MicrosoftDocs/dynamics-365-unified-operations-public#1679]
see Software lifecycle policy and cloud releases. For more information about One Version service updates, see One Version service updates FAQ. Thes2 2 links don't give any information about the on-premise releases.  If you follow the information for on-premise in these links you will end up in this page again, but you will never know the latest release for on-premise deployments.
From the first link: support policies for the Microsoft Dynamics 365 for Finance and Operations online service.
From the second link: Do these updates apply to on-premises?

Refer to the Software lifecycle policy and on-premises releases topic for the specific expiration dates of the version that you are on. They will have a 3 month expiry in general. However, the process of the updates outlined in this topic only apply to the cloud service.
Which is the link back to this page.

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: 72cf04b4-6ca4-218f-7a24-2945a11181ab
* Version Independent ID: f98f2ccc-caa8-de10-b64d-7398786e481b
* Content: [Software lifecycle policy and on-premises releases - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/da-dk/dynamics365/unified-operations/dev-itpro/migration-upgrade/on-prem-version-update-policy?toc=%2Ffin-and-ops%2Ftoc.json#feedback)
* Content Source: [articles/dev-itpro/migration-upgrade/on-prem-version-update-policy.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/migration-upgrade/on-prem-version-update-policy.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @meeramahabala
* Microsoft Alias: **meeram**

**Comment by ianmorgan99** [comment]
I agree . It is very difficult to tell from this if 10.0.5 and PU29 are currently supported On-Premise

**Comment by josaw1** [comment]
Thank you for your feedback. @meeramahabala, can you please look at this request?

**Comment by josaw1** [comment]
Bug 377510 created to track this issue.

**Comment by josaw1** [comment]
Hi @amadse, doc updates are in process. Please check back. Thanks!

@perlynne
