### ISSUE TITLE
Correct resource parameters description

### ISSUE THREAD

**Issue by ccampora** [MicrosoftDocs/dynamics-365-unified-operations-public#168]
Please correct the description in the resource parameter to include the following statement "The URL of the Finance and Operations instance without the last trailing slash." If a trailing slash is added at the end (normal to happens) authentication problems occur. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 221bcbdf-2c16-ee9d-f289-75980e35b17a
* Version Independent ID: 6377db2c-d7b7-82bb-baeb-8f2311a9fb87
* Content: [Use third-party service testing utilities with Finance and Operations - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/third-party-service-test)
* Content Source: [articles/dev-itpro/data-entities/third-party-service-test.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/third-party-service-test.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by ShylaThompson** [comment]
@Sunil-Garg, this should be a quick fix if it is correct.

**Comment by Sunil-Garg** [comment]
ccampora, thanks. The doc has been updated.
