### ISSUE TITLE
When removed

### ISSUE THREAD

**Issue by robertkara** [MicrosoftDocs/dynamics-365-unified-operations-public#1680]
Is it possible to add information to this page about when this method is planned to be removed from the solution? I know it has been announced a 12-month warning before breaking changes like this, but would be really nice to see in what version this will be removed.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfde6a82-bcb2-6732-6e60-8cedec1f4ea4
* Version Independent ID: c8835a65-391c-d32c-5500-4827421ae35f
* Content: [Settle transactions by using CustTrans::settleTransaction - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/financial/settletransact-obsolete#feedback)
* Content Source: [articles/dev-itpro/financial/settletransact-obsolete.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/financial/settletransact-obsolete.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **markskun**

**Comment by josaw1** [comment]
Thank you for your feedback. @RobinARH can you please take a look at this?

**Comment by josaw1** [comment]
Bug 377511 created to track issue.

**Comment by RobinARH** [comment]
We don't provide specific dates or versions for deprecation beyond our 12-month warning that a deprecation will occur. - Robin
