### ISSUE TITLE
Had to remove Entity-path part from primary connection string

### ISSUE THREAD

**Issue by stianask** [MicrosoftDocs/dynamics-365-unified-operations-public#1681]
Using service bus topic I had to remove the EntityPath part and the semi-colon just on front of it from the Primary Connection String before storing it as a Key Vault secret, otherwise the business events endpoint configuration would receive an error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95d370ed-df1e-44b6-a879-4212c701adf2
* Version Independent ID: 01fe2166-afdb-cfc8-e55a-abbdf53479c1
* Content: [Business events and Azure Service Bus - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/business-events/how-to/how-to-servicebus#feedback)
* Content Source: [articles/dev-itpro/business-events/how-to/how-to-servicebus.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/business-events/how-to/how-to-servicebus.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @ibenbouzid
* Microsoft Alias: **imbenbou**

**Comment by josaw1** [comment]
Thank you for your feedback. @ibenbouzid can you please look at this comment? Thanks.

**Comment by josaw1** [comment]
Bug 377509 created to track this issue.

**Comment by sericks007** [comment]
@Sunil-Garg, please review and update the content, as needed.

**Comment by Sunil-Garg** [comment]
stianask, thanks for the feedback. Did you mean, you have to remove this? Endpoint=sb:

If not, can you paste the string that you say should not be included when configuring the end point for business events?

**Comment by stianask** [comment]
The final string entered as a secret i key vault was like this:
Endpoint=sb://******.servicebus.windows.net/;SharedAccessKeyName=<KeyName>;SharedAccessKey=<Key>

No trailing semi-colon and no EntityPath=<queueName>

**Comment by josaw1** [comment]
@Sunil-Garg please see response.

**Comment by ibenbouzid** [comment]
Hi Stian,

Actually if you create your shared acces policy from the SB Topic configuration you will get an "...entitypath=YourTopicName" key at the end to restrict this policy only to the topic but not to the overall servicebus.
If you create your sharedPolicy from the servicebus configuration you won't get a trailing entitypath key at the end of the endpoint string. 
In the doc article i'm saying: "**Go back to the blade for your Service Bus**, and create a new shared access policy to send events. Only the Send policy is required to send events to the Service Bus topic"
so you won't have the entity path.
However if you get an error with the entitypath key at the end then i think this is something you should look at @Sunil-Garg as some organisation won't accept creating policies at the servicebus level but at the Topic level.
Thanks

**Comment by stianask** [comment]
Hi Imad

That's a good point and a detail I didn't catch when setting this up. I believe it's a good practice, at least security-wise, to have these policies on the lowest level suitable for each scenario. 

Perhaps it should be supported to have the EntityPath as well, or mentioned in the documentation that it has to be removed if you create the policy on the queue/topic level?

Thanks for an otherwise excellent, detailed step-by-step guide on how to set this up. I think it will turn out to be a very useful feature for integrations out of F&O.

Regards,
Stian

**Comment by Sunil-Garg** [comment]
Thanks guys for the detailed explanation. I have added a clarification note to the tutorial based on this learning. Imad, you are right that, we should be supporting topic level policy as well. I have added this tot he backlog. Thanks again.

**Comment by AndreasHassing** [comment]
Just FYI: This issue manifests as an error like:

```log
EventHub name should not be specified as EntityPath while using this Overload. Instead, please use 'path' parameter. Parameter name: entityPath
```
