### ISSUE TITLE
404 - link issue for Core area > "Work with analytics and reporting in Finance and Operation"

### ISSUE THREAD

**Issue by gaggaz12** [MicrosoftDocs/dynamics-365-unified-operations-public#1685]
Hi, please see that Core area &gt; "Work with analytics and reporting in Finance and Operation" link goes to a 404 page, please update to correct link to the online course. broken link is "https://docs.microsoft.com/en-us/learn/modules/work-with-analytics-reporting-in-dynamics-365-finance-ops/"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 254129c7-f92a-aa24-3c7e-f055de543ae4
* Version Independent ID: cbb3dabf-25ea-68af-3c86-e92b647e9db1
* Content: [Functional Consultant Learning Catalog - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/learning-catalog-functional-consultant#feedback)
* Content Source: [articles/fin-and-ops/get-started/learning-catalog-functional-consultant.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/learning-catalog-functional-consultant.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @MargoC
* Microsoft Alias: **margoc**

**Comment by MargoC** [comment]
Fixed.
