### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by adrianmizzimlt** [MicrosoftDocs/dynamics-365-unified-operations-public#1688]
I want to configure a couple of users to run this.   What are the roles/duties/privileges required to create and post the new statement?

I cannot create the statement with the following roles assigned:

1. Accountant
2. Inventory Accountant
3. Logistics manager
4. Purchasing manager
5. Retail Catalog manager
6. Retail Service
7. Retail Store IT 
8. Retail Store manager
9. Retail warehouse clerk
10. Sales manager
11. Shipping clerk
12. Shop supervisor

Am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fac94d7-62cb-1f7b-de54-0694351d9a84
* Version Independent ID: 31d65da1-60aa-3160-12a0-b080e4a439a7
* Content: [Create, calculate, and post statements for a retail store - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/tasks/create-calculate-post-statement-retail-store)
* Content Source: [articles/retail/tasks/create-calculate-post-statement-retail-store.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/tasks/create-calculate-post-statement-retail-store.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @jashanno
* Microsoft Alias: **jashanno**

**Comment by anpurush** [comment]
Please use the "Retail operations manager" role to create & post Statements
