### ISSUE TITLE
There is no text following the title "Generate payments"

### ISSUE THREAD

**Issue by Dimitri-Tetsch** [MicrosoftDocs/dynamics-365-unified-operations-public#1692]
There is no text following the title "Generate payments"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70c008c8-4977-37db-e43d-f96110a86616
* Version Independent ID: eaf9cccb-cab4-061a-ad4f-dcb80ecb4d23
* Content: [Create payments for a customer who have direct debit mandates - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/localizations/tasks/create-payments-customers-who-have-direct-debit-mandates#feedback)
* Content Source: [articles/financials/localizations/tasks/create-payments-customers-who-have-direct-debit-mandates.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/localizations/tasks/create-payments-customers-who-have-direct-debit-mandates.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @mrolecki
* Microsoft Alias: **mrolecki**

**Comment by tonyafehr** [comment]
@Dimitri-Tetsch, thanks for the feedback. This topic was generated from a task guide, but I will see if it can be updated, otherwise we will remove the empty section. 

@mrolecki, please review.
