### ISSUE TITLE
Incorrect information

### ISSUE THREAD

**Issue by RutvikMehta** [MicrosoftDocs/dynamics-365-unified-operations-public#1694]
This information is listed on many Microsoft pages.
"Modern POS for Android is an Android-based version of the Modern POS program that can be deployed on Android devices." 

Modern POS may be deployed on Android tablet but not on Android phones. You need to mention that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a23ac4f5-a8fd-ce83-2f3e-0912d95579d9
* Version Independent ID: 5a3bae91-72db-0e45-cd9b-2f68819fd148
* Content: [Retail peripherals - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/retail-peripherals-overview#feedback)
* Content Source: [articles/retail/retail-peripherals-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/retail-peripherals-overview.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @rubencdelgado
* Microsoft Alias: **rubendel**

**Comment by rubencdelgado** [comment]
@RutvikMehta can you please explain the issue you are facing? We are not aware of such an issue with the Android App. Many on the product team have Android phones and we routinely deploy the app on our phones for testing.

**Comment by RutvikMehta** [comment]
Hi thanks for replying. MPOS can not be downloaded on Android phone. You have to first make Hybrid POS App, install the apk on phone,  which will in turn run POS from Android. Is that correct?
