### ISSUE TITLE
Incorrect sample code for serviceCreateLedgerDimForDefaultDim

### ISSUE THREAD

**Issue by ravimeda** [MicrosoftDocs/dynamics-365-unified-operations-public#1696]
The sample code for `serviceCreateLedgerDimForDefaultDim` at 
( https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/financial/dimension-defaulting#servicecreateledgerdimfordefaultdim ) has an element that does not render correctly.

`![\\\\blackwoodstone\\share\\Research\\GFMBlog2\\media\\MSDNBlogsFS\\prod.evol.blogs.msdn.com\\CommunityServer.Blogs.Components.WeblogFiles\\00\\00\\01\\50\\86\\5710.c65.png](media/146d284328279f4737c6e2bd23a30530.png)`

**Comment by tonyafehr** [comment]
@jasonsto, please review the feedback for this topic.

**Comment by jasonsto** [comment]
Looks good
