### ISSUE TITLE
Redirected to wrong place

### ISSUE THREAD

**Issue by gkhushhal** [MicrosoftDocs/dynamics-365-unified-operations-public#1697]
See Additional resources (For more information about Platform update 29, see Additional resources) link is redirecting to Platform update 28 (July 2019) Additional resources

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54cb6abe-0f3d-ba5f-7725-48ad458974a5
* Version Independent ID: e0eeda33-408f-3f1f-8d37-536e98b0cdbb
* Content: [What's new or changed in Dynamics 365 for Finance and Operations platform update 29 (October 2019) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/whats-new-platform-update-29#feedback)
* Content Source: [articles/fin-and-ops/get-started/whats-new-platform-update-29.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/whats-new-platform-update-29.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @tonyafehr
* Microsoft Alias: **tfehr**

**Comment by tonyafehr** [comment]
Thank you for bringing this to our attention. We are not making updates to our topics this week, so I'm unable to make direct updates at this time. The link should in question should actually take you to the "Additional resources" section at the bottom of the topic (What's new or changed in Dynamics 365 for Finance and Operations platform update 29 (October 2019)).
