### ISSUE TITLE
Supported flows for credit card/payment connector

### ISSUE THREAD

**Issue by AndersDahlin** [MicrosoftDocs/dynamics-365-unified-operations-public#1701]
A process description is needed to explain when the payment connector is triggered, when capture, cancel and refund calls occurs in the system. Also a description of the logic. If multiple payment mehtods are used, when will it be triggered/used. Like shipping a partial order with the rest of the items are cancelled, creating a return order for some of the items etc. Continue to expand on more standard processes than just "partial payments.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90ff0495-53f4-2439-5588-5bb51aea5374
* Version Independent ID: bf8dcca0-8992-ed4f-f42f-c4c1521890e4
* Content: [Credit card setup, authorization, and capture - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/accounts-receivable/credit-card-authorizations#feedback)
* Content Source: [articles/financials/accounts-receivable/credit-card-authorizations.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/accounts-receivable/credit-card-authorizations.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @ShivamPandey-msft
* Microsoft Alias: **shpandey**

**Comment by josaw1** [comment]
Thank you for your feedback. @ShivamPandey-msft can you please take a look?

**Comment by josaw1** [comment]
Bug 382690 created to track issue,

**Comment by panolte** [comment]
Thank you for the feedback.  This documentation is intended for functional training and support.  This appears to be a functional request.
