### ISSUE TITLE
Unclear how to close the keyboard shortcut dialog using the keyboard

### ISSUE THREAD

**Issue by jawn** [MicrosoftDocs/dynamics-365-unified-operations-public#1702]
After right-click on a control and select View shortcuts, the dialog box with help is displayed.

I would expect that you can close this dialog using the keyboard. 

Most logical key: Esc.
Currently, this doesn't do anything and I see no other way to do this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1107997a-daa3-d7c7-9fd2-dc663e571b5a
* Version Independent ID: 747f14ea-be33-394c-5599-84d2b2bc537c
* Content: [Keyboard shortcuts - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/shortcut-keys)
* Content Source: [articles/fin-and-ops/get-started/shortcut-keys.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/shortcut-keys.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by josaw1** [comment]
Thank you for your feedback. @jasongre can you please take a look?

**Comment by josaw1** [comment]
Bug 382689 created to track this issue.

**Comment by jasongre** [comment]
Thanks for the feedback. Closing the keyboard shortcut dialog can be done today with the keyboard by tabbing to the Close button and pressing Enter. We'll look into why Esc isn't working.
