### ISSUE TITLE
Poorly worded Note

### ISSUE THREAD

**Issue by ptansey** [MicrosoftDocs/dynamics-365-unified-operations-public#1703]
The note at the beginning of this article is poorly worded: "There are many more features in the Trace parser are similar to Microsoft Dynamics AX 2012. See the Dynamics Ax Performance Team Blog for more information."
No biggie, just thought you should know

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ca95239-c2a9-10f0-babd-43225bf20669
* Version Independent ID: 8843088d-3f83-4314-1a18-ea63e0fbda56
* Content: [Diagnose issues and analyze performance by using Trace parser - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/perf-test/trace-parser#feedback)
* Content Source: [articles/dev-itpro/perf-test/trace-parser.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/perf-test/trace-parser.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **chwolf**

**Comment by josaw1** [comment]
Thank you for your feedback. @RobinARH please take a look.

**Comment by RobinARH** [comment]
Fixed. Will go live today.
