### ISSUE TITLE
Trace is not on Settings

### ISSUE THREAD

**Issue by ptansey** [MicrosoftDocs/dynamics-365-unified-operations-public#1704]
The trace feature mentioned in Step 2 is actually on the Help (?) menu, not Settings

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe3185f9-a301-ca41-90c2-6a4715df55ca
* Version Independent ID: 0ec0e0ba-5839-806a-5471-dda4bc56996a
* Content: [Take traces by using Trace parser - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/perf-test/trace-trace-tutorial)
* Content Source: [articles/dev-itpro/perf-test/trace-trace-tutorial.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/perf-test/trace-trace-tutorial.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **chwolf**

**Comment by josaw1** [comment]
Thank you for your feedback. @RobinARH can you please make the correction?

**Comment by josaw1** [comment]
Bug 382687 created to track this issue.

**Comment by RobinARH** [comment]
Fixed. It will be published to live today. - Robin
