### ISSUE TITLE
MKO Test

### ISSUE THREAD

**Issue by MKochanski** [MicrosoftDocs/dynamics-365-unified-operations-public#171]
Feedback test.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a58e8553-ea84-749e-edd6-fb62c0f0f458
* Version Independent ID: c323529d-896b-25e3-2c7a-e175cc218f27
* Content: [Set up and deploy on-premises environments (Platform update 12) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/deployment/setup-deploy-on-premises-pu12)
* Content Source: [articles/dev-itpro/deployment/setup-deploy-on-premises-pu12.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/deployment/setup-deploy-on-premises-pu12.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @sarvanisathish
* Microsoft Alias: **sarvanis**

**Comment by MargoC** [comment]
Closing.

**Comment by naveenkumarjagtab** [comment]
@MargoC  i have followed the above Microsoft blog mentioned for deploying on premises D365 and in  step 14  at Configure the OrchestratorData database please let me know what configuration file we need to change in configTemplate.xml  regarding the database server. please help me in this following as am struck at this step.

Thanks in advance
