### ISSUE TITLE
TechTalk Link is dead

### ISSUE THREAD

**Issue by marihul** [MicrosoftDocs/dynamics-365-unified-operations-public#1710]
Correct Link should be: https://community.dynamics.com/365/b/techtalks/posts/environment-planning-may-23-2018

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00f88ef5-f857-b53e-8835-b944e8217560
* Version Independent ID: 1993cec6-ee86-f44d-97dc-107216269ccc
* Content: [Environment planning - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/imp-lifecycle/environment-planning#feedback)
* Content Source: [articles/fin-and-ops/imp-lifecycle/environment-planning.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/imp-lifecycle/environment-planning.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @ClaudiaBetz-Haubold
* Microsoft Alias: **chaubold**

**Comment by tonyafehr** [comment]
@marihul, thanks for the feedback. I will get the link updated and published tomorrow.
