### ISSUE TITLE
Bad Screenshot in Procedure 2 step 4

### ISSUE THREAD

**Issue by ijensen808** [MicrosoftDocs/dynamics-365-unified-operations-public#1712]
Procedure 2, Step 4: the screenshot references a Service Bus key vault, but this is an event grid tutorial.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e2c1641-60b6-f7aa-1dcc-4de3a5ee0c21
* Version Independent ID: c38b474f-9e71-2477-3bf0-fe78f308d659
* Content: [Business events and Azure Event Grid - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/business-events/how-to/how-to-eventgrid)
* Content Source: [articles/dev-itpro/business-events/how-to/how-to-eventgrid.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/business-events/how-to/how-to-eventgrid.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @ibenbouzid
* Microsoft Alias: **imbenbou**

**Comment by tonyafehr** [comment]
@ijensen808, thanks for the feedback.  
@ibenbouzid, please consider updating this topic.

**Comment by tonyafehr** [comment]
Bug 381552 has been logged to track this issue.

**Comment by tonyafehr** [comment]
We've updated this topic and changes will be live later today.
