### ISSUE TITLE
Catching exceptions inside transactions: DuplicateKeyException and UpdateConflict 

### ISSUE THREAD

**Issue by weikanglim** [MicrosoftDocs/dynamics-365-unified-operations-public#1713]
The section for "Exceptions inside transactions" does not explain how DuplicateKeyException and UpdateConflict exceptions can be caught.

The current article states:

> When an exception is thrown inside a ttsBegin-ttsCommit transaction block, no catch statement inside that transaction block can process the exception.

Which is not completely accurate, given that `catch(Exception::DuplicateKeyException)`  and `catch(Exception::UpdateConflict)` does allow for catching inside transaction blocks, as explained in the article: https://community.dynamics.com/365/financeandoperations/b/mfp/posts/x-the-catch

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d181c21-1755-37c7-75b5-910b0fd03418
* Version Independent ID: 20b85e37-d16b-631a-32a9-2b9bc65da77e
* Content: [X++ exception handling - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-ref/xpp-exceptions#exceptions-inside-transactions)
* Content Source: [articles/dev-itpro/dev-ref/xpp-exceptions.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-ref/xpp-exceptions.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **rhaertle**

**Comment by tonyafehr** [comment]
@weikanglim, thanks for the feedback. 
@RobinARH, please review and consider updating this topic.

**Comment by tonyafehr** [comment]
Bug 381554 has been logged to track this issue.

**Comment by RobinARH** [comment]
@MichaelFruergaardPontoppidan - Can you take a look? Thanks.

**Comment by tonyafehr** [comment]
We've updated this topic and changes will be live later today.
