### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by JoelLeichty** [MicrosoftDocs/dynamics-365-unified-operations-public#1714]
Updates were made to the BYOD process that are not documented in this article, but reference Platform 27 in another article.
https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/export-entities-to-your-own-database

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f11411b8-faee-5db5-fca0-a9cc0b44f012
* Version Independent ID: 11d02bb2-082e-5a97-d645-2d82061f7ad2
* Content: [What's new or changed in Dynamics 365 for Finance and Operations platform update 27 (June 2019) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/whats-new-platform-update-27)
* Content Source: [articles/fin-and-ops/get-started/whats-new-platform-update-27.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/whats-new-platform-update-27.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @tonyafehr
* Microsoft Alias: **tfehr**

**Comment by tonyafehr** [comment]
@JoelLeichty. thanks for the feedback. We will consider making updates.
@sunil, please consider updating the What's New topic with this information.

**Comment by tonyafehr** [comment]
Bug 381555 has been logged to track this issue.

**Comment by tonyafehr** [comment]
We've updated the text and will be live later today.
