### ISSUE TITLE
Reporting currency exchange rate is defaulted to 0, when importing GL data with data entity LedgerJournalEntity

### ISSUE THREAD

**Issue by xhellot** [MicrosoftDocs/dynamics-365-unified-operations-public#1716]
The new added field ReportingCurrencyExchRate cannot be 0, otherwise the journal won't be posted. This makes our existing data import project fail to create valid GL data.
And I noticed that field is not defaulted to 100.00 if Accounting currency is the same as Reporting currency when importing with data entity LedgerJournalEntity. This logic is added in the method initValue of table LedgerJournalTrans, please consider adding it to the ledger journal trans related data entities.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9158a147-ea5a-9b4f-7987-c2801ca0e8a9
* Version Independent ID: 9f6dafeb-4d5d-9d80-a5d6-722ec6841a51
* Content: [What's new or changed in Finance and Operations apps version 10.0.5 (October 2019) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-ops-core/fin-ops/get-started/whats-new-changed-10-0-5#feedback)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/whats-new-changed-10-0-5.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/get-started/whats-new-changed-10-0-5.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @tonyafehr
* Microsoft Alias: **tfehr**

**Comment by RobinARH** [comment]
@aprilolson Can you take a look? This seems to be about general ledger. Thanks.

**Comment by aprilolson** [comment]
This would be @Kristi Slininger<mailto:kweekley@microsoft.com>

April Olson
Dynamics 365 Finance & Operations
Principal Group Program Manager, Financials & Service Industries
Check out our Financials blog: https://community.dynamics.com/365/financeandoperations/b/financials

Our workplace allows for a flexibile work schedule, which is an amazing benefit. I am sending this now because it is convenient for me. I do not expect you to read or respond until its convenient for you.

**Comment by RobinARH** [comment]
@kweekley Can you take a look? thanks.

**Comment by kweekley** [comment]
I’m not sure where to put my comments….but this is basically a bug and they need to work with support to report the issue.  If I put that in GitHub, is that visible externally?

**Comment by RobinARH** [comment]
Created bug 381302 to track this issue.

**Comment by RobinARH** [comment]
Closing. There's no doc issue here.
