### ISSUE TITLE
Vendor payments link dead

### ISSUE THREAD

**Issue by johnnystruck** [MicrosoftDocs/dynamics-365-unified-operations-public#1717]
PowerBI Vendor payments link is not working - unable to view details regarding this solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa86d056-40d0-c47f-478a-c767772b9b8b
* Version Independent ID: cf23b6ac-b1e3-c8c1-5e7d-82d338f1beca
* Content: [Power BI content home page - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/power-bi-home-page?toc=/dynamics365/unified-operations/finance/toc.json)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/power-bi-home-page.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/power-bi-home-page.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @sericks007
* Microsoft Alias: **sericks**

**Comment by RobinARH** [comment]
@sericks007 Can you take a look? Thanks.

**Comment by johnnystruck** [comment]
Cash overview and Credit and Collections are also not working, perhaps its the PowerBI section in general?

**Comment by sericks007** [comment]
@johnnystruck, thanks for letting us know! Our team is working on fixing links.

**Comment by sericks007** [comment]
These links have been fixed. The updated article will be published soon.
