### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by Fyrste** [MicrosoftDocs/dynamics-365-unified-operations-public#1719]
Dear Microsoft,

Which "notes" are meant in the introduction mentioned here "These tasks would typically be carried out by a warehouse manager. You can run this procedure in the USMF demo data company using the example values in the notes, or can run it on your own data."

Many thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82ec4b05-8c85-2d44-c716-b93798e460f8
* Version Independent ID: a0e18005-ab75-46ed-feb9-1b38f88f8fd7
* Content: [Set up a min-max replenishment process - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/supply-chain/warehousing/tasks/set-up-min-max-replenishment-process)
* Content Source: [articles/supply-chain/warehousing/tasks/set-up-min-max-replenishment-process.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/warehousing/tasks/set-up-min-max-replenishment-process.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @perlynne
* Microsoft Alias: **perlynne**

**Comment by sericks007** [comment]
@Fyrste, thanks for posting here!

@perlynne, please review and update the introduction to clarify.

**Comment by perlynne** [comment]
Notes was taken from task recordings, it "values below".

Thanks
