### ISSUE TITLE
Data entity extensions

### ISSUE THREAD

**Issue by maveloso** [MicrosoftDocs/dynamics-365-unified-operations-public#172]
The documentation on data entity extensions is missing. there are several limitations on data entity extensions that should be documented. for example, cant add new methods, several specific events for data entities exist and are not documented, for example: onUpdatedEntityDataSource ... The documentation simply mentions that data entities are kind of like tables and they are not... 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac5bd5e3-de75-79f0-1a00-4d9267032eba
* Version Independent ID: 28f1623d-c6db-5b5b-f2fe-9728a3c370e7
* Content: [Customize with extensions and overlayering - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/extensibility/customization-overlayering-extensions#table-extensions)
* Content Source: [articles/dev-itpro/extensibility/customization-overlayering-extensions.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/extensibility/customization-overlayering-extensions.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @robadawy
* Microsoft Alias: **robadawy**

**Comment by MargoC** [comment]
Thanks @maveloso. The PM for this area has agreed that this is important, and that we should add at least one new topic.

**Comment by KAleshire** [comment]
Any update on this issue, it'd be great to get some more clarity on what's possible with Data entity extensions.  In particular, onPostingLoad vs. onPostedLoad vs. creating a new entity and using the PostLoad override method.
