### ISSUE TITLE
Office 2019 compatibility?

### ISSUE THREAD

**Issue by GeoffreyDelmee** [MicrosoftDocs/dynamics-365-unified-operations-public#1721]
On the page, we cas read: "To run the Microsoft Excel and Microsoft Word add-ins, you must have Microsoft Office 2016 for Windows installed."
Following the link just after, we see Office add-in requires ExcelAPI 1.2 which is available in Excel 2019.
So, is Office 2019 validated and if so, can you update this page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc242273-ee42-3973-cc47-aece5771ca1f
* Version Independent ID: 0cf0f65b-6187-104a-8228-3c1431225267
* Content: [System requirements for on-premises deployments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/system-requirements-on-prem?toc=/dynamics365/commerce/toc.json#supported-microsoft-office-applications)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/system-requirements-on-prem.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/get-started/system-requirements-on-prem.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **kfend**

**Comment by sericks007** [comment]
@GeoffreyDelmee, thanks for bringing this to our attention!

@sarvanisathish or @PeterRFriis, could you please review and update the content, if needed.

**Comment by sericks007** [comment]
Bug 381823 has been logged to track this issue.

**Comment by ChrisGarty** [comment]
Adjusted to indicate that newer Office builds work fine.

**Comment by AndrewMaisey** [comment]
Hi MS Team, hoping to get some information about official Dynamics 9.x support on Windows Server 2019. Community forums suggest it is technically possible, but is it to be officially Microsoft supported? Thank you.

**Comment by faix** [comment]
@sericks007 the changes went live some time ago. The issue can be closed.
