### ISSUE TITLE
Unable to download PDF

### ISSUE THREAD

**Issue by sy-huss** [MicrosoftDocs/dynamics-365-unified-operations-public#1723]
When clicking on the download PDF - I get an error page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0cd4aef-33f1-d647-85eb-1a055ef216bd
* Version Independent ID: 73febada-4141-88bf-7a55-e8cc375dde92
* Content: [Business events overview - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/business-events/home-page)
* Content Source: [articles/fin-ops-core/dev-itpro/business-events/home-page.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/business-events/home-page.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by josaw1** [comment]
Bug 382686 created to track this issue.

**Comment by kfend** [comment]
@sy-huss  - please try downloading again. It seems that this issue has been resolved.
