### ISSUE TITLE
Examples on how to handle enum criteria

### ISSUE THREAD

**Issue by gertvdh** [MicrosoftDocs/dynamics-365-unified-operations-public#1724]
Can you add some examples on how to handle enums in odata queries?

it's possible when you do [Your organization's root URL]/data/CustomersV3?$filter= PersonGender eq Microsoft.Dynamics.DataEntities.Gender'Unknown'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d7c8b45-1531-ebbf-d417-4e1fe5bf4f1b
* Version Independent ID: c543a5fc-90c9-9edb-11d7-6d6d0f2c10a9
* Content: [Open Data Protocol (OData) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/odata#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/odata.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/odata.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by josaw1** [comment]
Bug 382685 created to track issue.

**Comment by Sunil-Garg** [comment]
Thanks gertvdh. The updates have been made as suggested.
