### ISSUE TITLE
The .pfx container file downloaded by the Download Secure File build task is not encrypted

### ISSUE THREAD

**Issue by skolbin-ssi** [MicrosoftDocs/dynamics-365-unified-operations-public#1731]
[Enter feedback here]

> Download the Download File task and add it as first step in the build process. **The advantage of using the Secure File task is the file is encrypted** and placed in the disk during build and no matter whether the build pipelines succeeds, fails, or canceled, the file is deleted from its download location after the build process is completed.

This part of the statement from the quote that is highlighted in bold is not correct. The .pxf container file is not encrypted while in transit on the disk in the VSO Build Agent's __temp_ folder for the duration of the build run. This makes the .pfx container file (and we keep in mind that the .pfx container file is not protected by a password) exposed and vulnerable to a compromise since even a non-administrator user with RDP access to a Build VM hosted on Microsoft subscription will be able to copy that .pfx file off the Build machine.

One way to remediate this situation is to add a PowerShell Script build task with an inline PS script to the build pipeline after the Download Secure File build task. The PS inline script can grab the path value of the Output Variable of the Download Secure File build task and then import the code signing certificate from the .pfx container that was downloaded to the file system into the CurrentUser\My certificate storage (make sure to not mark the private keys as exported during the import). The inline PS script runs in the security context of the VSO Build Agent's user account and the import of the certificate will be successful. After the certificate is in the Personal certificate storage of the VSO Build Agent's user account, it can then be referenced by its Thumbprint value in the _Customization.settings_ configuration file. After verifying the code singing works, both build tasks, Download Secure File and PowerShell Script can be removed from the Build pipeline, as they are no longer needed. In the end, the code certificate will be stored in the secure certificate storage and available to the VSO Build Agent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 367b8b85-3771-3eaa-51c1-eed74fa6eac4
* Version Independent ID: 2382a5dd-63f6-fe56-337b-b56cb6a6bc73
* Content: [Sign MPOS with a code signing certificate - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/retail/dev-itpro/pos-app-signing-certificate)
* Content Source: [articles/retail/dev-itpro/pos-app-signing-certificate.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/dev-itpro/pos-app-signing-certificate.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by RobinARH** [comment]
@mugunthanm Can you take a look? thanks.

**Comment by RobinARH** [comment]
Bug 385340 to track this issue.

**Comment by mugunthanm** [comment]
Thanks for the feedback. We will follow up with the DevOps team on this. 

https://docs.microsoft.com/en-us/azure/devops/pipelines/library/secure-files?view=azure-devops

Use the Secure Files library to store files such as signing certificates, Apple Provisioning Profiles, Android Keystore files, and SSH keys on the server without having to commit them to your source repository. Secure files are defined and managed in the Library tab in Azure Pipelines.

The contents of the secure files are encrypted and can only be used during the build or release pipeline by referencing them from a task. The secure files are available across multiple build and release pipelines in the project based on the security settings.
