### ISSUE TITLE
Import the bacpac file into SQL Database and db scale out

### ISSUE THREAD

**Issue by emstn** [MicrosoftDocs/dynamics-365-unified-operations-public#1738]
The import bacpac file into SQL database step doesn't seem to work anymore with the database scale out changes described in https://cloudblogs.microsoft.com/dynamics365/it/2019/08/06/lifecycle-services-august-2019-release-1-release-notes/
Getting an error that says client with IP address is not allowed to access the server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6717d4f3-0b93-713a-6a61-405cce70dfe0
* Version Independent ID: 050db2bb-9dd4-82ff-3f27-ec7a8d0ea64c
* Content: [Upgrade from AX 2012 - Data upgrade in sandbox environments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/upgrade-data-sandbox)
* Content Source: [articles/fin-ops-core/dev-itpro/migration-upgrade/upgrade-data-sandbox.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/migration-upgrade/upgrade-data-sandbox.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @tariqbell
* Microsoft Alias: **tabell**

**Comment by tonyafehr** [comment]
Thanks for the feedback. We will review and consider making updates. In the meantime, if you need to contact Support consider using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community. 
@tariqbell, consider updating this topic based on this feedback.

**Comment by tonyafehr** [comment]
Bug 383038 has been logged to track this issue.

**Comment by laneswenka** [comment]
You will be required to import all databases via LCS Self-service Database Import.  Please see this article for step by step on preparing the bacpac from SQL Server and promoting it for go live:
https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/dbmovement-scenario-goldenconfig

**Comment by wajahatmirza-afz** [comment]
HI,
My bacpac size is more than 35GB and while uploading on Asset Library it is giving error that "File cannot be greater than 14.6GB in size". If I try to restore database from Azure storage than I need "sqladmin" account which is not available in PU30. What should be the solution for it?

**Comment by tariqbell** [comment]
Hi, please contact Microsoft Support for help with this one.
________________________________

**Comment by emstn** [comment]
@laneswenka
We took the LCS import approach and found that some data like email addresses and attachments were wiped out (basically the stuff described here: https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/database-refresh#data-elements-that-arent-copied-during-refresh). Can probably deal with most of it but not sure what to do about the attachments.

**Comment by emstn** [comment]
Actually the attachments are there its just the paperclip icon is showing a count of zero.
