### ISSUE TITLE
initializeReportControl deprecated

### ISSUE THREAD

**Issue by phualcarrs** [MicrosoftDocs/dynamics-365-unified-operations-public#1742]
The best practice checks tell you to use initializeReportControlV2 as initializeReportControl is deprecated. Can you update the guidance on this page to use the correct method please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58543120-6ce0-15a0-dd0a-ca4888b11d85
* Version Independent ID: 4e804992-b8bd-e312-eb85-da4b25f9d3cd
* Content: [Add analytics to workspaces by using Power BI Embedded - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/add-analytics-tab-workspaces?toc=%2Fdynamics365%2Fsupply-chain%2Ftoc.json#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/add-analytics-tab-workspaces.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/add-analytics-tab-workspaces.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by tonyafehr** [comment]
@phualcarrs, thanks for the feedback. 
@TJVass, please review and consider updating this topic.

**Comment by tonyafehr** [comment]
Bug 383039 has been logged to track this issue.
