### ISSUE TITLE
Need to Auto Declare the form group control

### ISSUE THREAD

**Issue by dougbell-ms** [MicrosoftDocs/dynamics-365-unified-operations-public#1745]
I think it's worth point out that when you create the form group control in steps 12 and 13, you must set the Auto Declaration property to Yes.  For VS novices like me it took me quite some time to figure that out...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58543120-6ce0-15a0-dd0a-ca4888b11d85
* Version Independent ID: 4e804992-b8bd-e312-eb85-da4b25f9d3cd
* Content: [Add analytics to workspaces by using Power BI Embedded - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/add-analytics-tab-workspaces?toc=%2Fdynamics365%2Ffinance%2Ftoc.json#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/add-analytics-tab-workspaces.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/add-analytics-tab-workspaces.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by josaw1** [comment]
Thank you for your feedback. @TJVass, please consider adding more info here.

**Comment by josaw1** [comment]
Created bug 384070 to track.

**Comment by kfend** [comment]
Updated the topic with this feedback. Changes will publish later today.
