### ISSUE TITLE
Prerequisite

### ISSUE THREAD

**Issue by johnnystruck** [MicrosoftDocs/dynamics-365-unified-operations-public#1750]
Missing prerequisite steps to configure specific General Ledger "Journal name." Later referenced in step 3 in "setup the write off parameters section."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a60ea314-a744-196b-54d1-34972343a96c
* Version Independent ID: d4445025-22b0-4398-fc10-08c0120a9ec7
* Content: [Create a write-off journal for a customer - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/finance/accounts-receivable/tasks/create-write-off-journal-customer#feedback)
* Content Source: [articles/finance/accounts-receivable/tasks/create-write-off-journal-customer.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/accounts-receivable/tasks/create-write-off-journal-customer.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @ShivamPandey-msft
* Microsoft Alias: **shpandey**

**Comment by josaw1** [comment]
Thanks for your feedback. @ShivamPandey-msft can you please look at this?

**Comment by josaw1** [comment]
Created Bug 384074 to track.

**Comment by josaw1** [comment]
BUG 437987 created.
