### ISSUE TITLE
The call to print custom receipt type on client is referred to a video that is for old version

### ISSUE THREAD

**Issue by anytranya** [MicrosoftDocs/dynamics-365-unified-operations-public#1751]
Please update the reference to correct version, Managers in latest version is no longer available. So call of getReceiptsForPrintAsync is out of date already. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d88f5da-3dff-fa7e-ef65-a1f8e71e7930
* Version Independent ID: 43c19e9e-5113-c423-eda7-30f09a255d91
* Content: [Retail software development kit (SDK) samples - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/retail/dev-itpro/retail-sdk/retail-sdk-samples#feedback)
* Content Source: [articles/retail/dev-itpro/retail-sdk/retail-sdk-samples.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/dev-itpro/retail-sdk/retail-sdk-samples.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by mugunthanm** [comment]
Can you please send us the doc link/screenshot where you find this API used (getReceiptsForPrintAsync ), somehow not able to find this in our search.

**Comment by anytranya** [comment]
1. From the video which is a reference on page.
![image](https://user-images.githubusercontent.com/56044305/66784847-977dd280-eea9-11e9-8eb7-d6f245bddf62.png)
![image](https://user-images.githubusercontent.com/56044305/66784880-ab293900-eea9-11e9-82eb-7b88d0c866cd.png)
2. readme.txt from RetailSDK document
![image](https://user-images.githubusercontent.com/56044305/66784965-e4fa3f80-eea9-11e9-9343-5b7ac6f80231.png)
![image](https://user-images.githubusercontent.com/56044305/66784916-c8f69e00-eea9-11e9-905f-70bf2420db27.png)

**Comment by tonyafehr** [comment]
Bug 385435 has been logged to track this issue.

**Comment by mugunthanm** [comment]
Updated the doc with the right link - Print custom receipt from POS.
