### ISSUE TITLE
Offer Data Rules

### ISSUE THREAD

**Issue by awalkerholder** [MicrosoftDocs/dynamics-365-unified-operations-public#1753]
In this article it is unclear how to create an offer data rule that simply provides a user a list of choices. Even though it is possible you have to read between the lines or search else ware to discover this functionality.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2912d463-a227-dff6-0412-6e6bec0062ee
* Version Independent ID: 0b984c50-40a0-bc82-935d-cd733b338749
* Content: [Set up offer management - Talent | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/talent/offer-setup#feedback)
* Content Source: [articles/talent/offer-setup.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/talent/offer-setup.md)
* Service: **dynamics-365-talent**
* Product: ****
* Technology: ****
* GitHub Login: @andreabichsel
* Microsoft Alias: **anbichse**

**Comment by tonyafehr** [comment]
@awalkerholder, thank you for the feedback. 
@andreabichsel, please review and consider revising this topic.

**Comment by tonyafehr** [comment]
Bug 385437 has been logged to track this issue.

**Comment by andreabichsel** [comment]
Added the information to the first note under the **Offer data** heading. Thank you!
