### ISSUE TITLE
Missing word

### ISSUE THREAD

**Issue by awalkerholder** [MicrosoftDocs/dynamics-365-unified-operations-public#1756]
This sentence is missing the word “add”

You can activities to a stage either by dragging them to the appropriate stage or by double-clicking them in the activity list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44d4b786-af2d-5001-8d8f-b8140b53d632
* Version Independent ID: 4fc9cb7a-e8be-19dd-2d58-b13a070f2a21
* Content: [Create a process template in Attract - Talent | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/talent/process-templates-attract#feedback)
* Content Source: [articles/talent/process-templates-attract.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/talent/process-templates-attract.md)
* Service: **dynamics-365-talent**
* Product: ****
* Technology: ****
* GitHub Login: @andreabichsel
* Microsoft Alias: **anbichse**

**Comment by sericks007** [comment]
@awalkerholder, thanks for letting us know!

@andreabichsel, please update the topic as suggested.

**Comment by andreabichsel** [comment]
Thank you! I updated the topic and it should be live in a few minutes.
