### ISSUE TITLE
(How) does this work for ISV or customer specific data models/entities?

### ISSUE THREAD

**Issue by ibruynin** [MicrosoftDocs/dynamics-365-unified-operations-public#1758]
Does this tool only work for standard AX or can it be used to migrate ISV/customer specific data as wel?

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 7883c831-f332-73b6-6669-75e0f8f7956c
* Version Independent ID: c9a8a6a0-88dd-c432-1fda-a59259fd8533
* Content: [AX 2009 upgrade - Use the Data migration tool to migrate from Dynamics AX 2009 to Dynamics 365 for Finance and Operations - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/nl-nl/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/data-migration-tool)
* Content Source: [articles/fin-ops-core/dev-itpro/migration-upgrade/data-migration-tool.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/migration-upgrade/data-migration-tool.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **kfend**

**Comment by sericks007** [comment]
@ibruynin, thanks for posting here!

@laneswenka, would you be able to answer this question?

**Comment by laneswenka** [comment]
This would work with any table as long as it is mapped to a data entity in the target system.  This includes custom entities or ISV entities!  The 2009 migration tool is owned by our FastTrack Solution Architecture team, and they can help you if you have targeted questions during implementation.

**Comment by sbaber82** [comment]
Hi Lane,

Based on your comment above, if there are custom tables in customer's AX 2009 environment, then we have to create the corresponding data entities in target D365 environment in order to perform the mapping using this tool?

**Comment by sbaber82** [comment]
@laneswenka
