### ISSUE TITLE
axextdeployuser created twice

### ISSUE THREAD

**Issue by JoPe72** [MicrosoftDocs/dynamics-365-unified-operations-public#176]
Hi...
Why is the axextdeployuser created twice? 

CREATE USER axdeployextuser WITH PASSWORD = '&lt;password from LCS&gt;'
IF EXISTS (select * from sys.database_principals where type = 'R' and name = 'DeployExtensibilityRole')
BEGIN
    EXEC sp_addrolemember 'DeployExtensibilityRole', 'axdeployextuser'
END

CREATE USER axdeployextuser WITH PASSWORD = '&lt;password from LCS&gt;'
EXEC sp_addrolemember 'DeployExtensibilityRole', 'axdeployextuser'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cef28a03-9759-ae74-20ba-2ec089c43d5b
* Version Independent ID: 1b085a75-6c84-c2a8-1ce8-60c272e8bfaf
* Content: [Copy a Finance and Operations database – SQL Server to production Azure SQL - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/copy-database-from-sql-server-to-azure-sql)
* Content Source: [articles/dev-itpro/database/copy-database-from-sql-server-to-azure-sql.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/database/copy-database-from-sql-server-to-azure-sql.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @maertenm
* Microsoft Alias: **maertenm**

**Comment by MargoC** [comment]
Thanks for pointing out the issue. We've updated the topic.

**Comment by Splaxi** [comment]
Hi.

The issue still exists.

I can see that the change has been made to the article on github, but it hasn't been posted to docs yet. The date on the docs state that latest update was made 03/30/2018.

![image](https://user-images.githubusercontent.com/8750181/42265221-3440ef28-7f73-11e8-9d2b-13eb8a076f59.png)

How long does it normally take for an update to an article to be posted to docs?
