### ISSUE TITLE
Please update to reflect current version of D365 and Postman

### ISSUE THREAD

**Issue by rabol** [MicrosoftDocs/dynamics-365-unified-operations-public#1765]
[Enter feedback here]
The steps shoen under the Postman setup does not work with the current version of Postman.

Not sure if it is the version of D365 or Postman that is the problem

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39946d94-b987-869b-dcf9-fc8a53089976
* Version Independent ID: c4996190-a4d7-0531-072c-454cea691b63
* Content: [Test services by using third-party utilities - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/third-party-service-test#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/third-party-service-test.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/third-party-service-test.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by sericks007** [comment]
@rabol, thank you for submitting this feedback!

@Sunil-Garg, please review and update the content as necessary.

**Comment by sericks007** [comment]
Bug 386028 has been logged to track this issue.

**Comment by sericks007** [comment]
This content was updated last December, so I believe this issue has been resolved.  If you discover that the issue has not been resolved, please re-activate this. Thank you.
