### ISSUE TITLE
Can I delay an update?

### ISSUE THREAD

**Issue by elenchule** [MicrosoftDocs/dynamics-365-unified-operations-public#1766]
In the "Can I delay an update?" section, it's mentioned that it's 3 months for 2 consecutive updates, whereas is 3 consecutive updates, not 2. It has been misleading for some customers referring to this page.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23fde63f-0f6f-b1a0-50c8-e1bf5f6a48c4
* Version Independent ID: 59a1f734-87cb-f34c-afd5-9f14de877584
* Content: [One Version service updates FAQ - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/one-version?toc=%2Fdynamics365%2Fcommerce%2Ftoc.json#feedback)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/one-version.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/get-started/one-version.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @meeramahabala
* Microsoft Alias: **meeram**

**Comment by sericks007** [comment]
@elenchule, thanks for posting this!

@meeramahabala, please review and update the content as necessary.

**Comment by sericks007** [comment]
@ShellyBakke, can you please review and update the content, as needed.

**Comment by sericks007** [comment]
Bug 386052 has been logged to track this issue.

**Comment by VibekeHveberg** [comment]
Hi can the customer pause 3 or 2 consecutive service updates ? And when will the text be changed?

**Comment by sericks007** [comment]
This content has been updated and will be published later today.
