### ISSUE TITLE
Compiler warning when augementing BusinessEventsServiceBusAdapter with custom payloadContext

### ISSUE THREAD

**Issue by MartinVyuga** [MicrosoftDocs/dynamics-365-unified-operations-public#1769]
The section about adding a custom Payload Context https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/business-events/business-events-dev-doc#payload-context
is outdated IMHO.
The class BusinessEventsServiceBusAdapter is marked as internal and as of PU30 the compiler gives a warning when I try to augement its method in my own model. 

Please advise on what to do in the case I want to add custom payload context field e.g in the service bus adapter case!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11811157-3f2d-56d5-07d4-0f44ab2c9370
* Version Independent ID: 5bc47a47-4d27-aaf5-750f-72b47bb39fe1
* Content: [Business events developer documentation - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/business-events/business-events-dev-doc#payload-context)
* Content Source: [articles/fin-ops-core/dev-itpro/business-events/business-events-dev-doc.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/business-events/business-events-dev-doc.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by Sunil-Garg** [comment]
You are right. There is a compatibility issue that was un-covered in PU30 which is being tracked as a bug. We are looking into fixing this issue. In the meantime, the troubleshoot wiki has been updated about this issue to create awareness. Thanks again.
