### ISSUE TITLE
Example 2 is a copy of example 1 and does not set recurring schedule

### ISSUE THREAD

**Issue by swidz** [MicrosoftDocs/dynamics-365-unified-operations-public#1770]
There is no difference in &lt;Operation&gt; node in these to examples. Moreover, the second example lack the ConfigurationOnly node which cardinality is denoted as 1..1 so should be mandatory

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf51a7e8-9ae4-5b55-c61c-2dc31abe6621
* Version Independent ID: 934ab5eb-0b75-c8de-a76d-efd2ded27609
* Content: [Data task automation - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/data-task-automation)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/data-task-automation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/data-task-automation.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by RobinARH** [comment]
@Sunil-Garg Can you take a look? Thanks.

**Comment by RobinARH** [comment]
Bug 393508 created to track this issue.

**Comment by Sunil-Garg** [comment]
Thanks, swidz. The literature has been updated.
