### ISSUE TITLE
GetExecutionErrors Documentation Missing

### ISSUE THREAD

**Issue by elusivecube** [MicrosoftDocs/dynamics-365-unified-operations-public#1772]
This API is missing from this documentation.

It is available at: /data/DataManagementDefinitionGroups/Microsoft.Dynamics.DataEntities.GetExecutionErrors

Please update accordingly and provide request/response examples as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d963d4c-de1f-7730-bee2-016dcde40907
* Version Independent ID: 21b95d43-5ad9-0ffc-21b9-6a4ba9086a56
* Content: [Data management package REST API - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/data-management-api)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/data-management-api.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/data-management-api.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by RobinARH** [comment]
@Sunil-Garg Can you take a look? Thanks.

**Comment by RobinARH** [comment]
Bug 393502 created to track this issue.

**Comment by Sunil-Garg** [comment]
Thanks for asking. The wiki for both recurring integrations and data package API has been updated with the API information.

**Comment by elusivecube** [comment]
@Sunil-Garg, which wiki are you referring to? It is not on this page: https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/data-management-api

**Comment by Sunil-Garg** [comment]
Give it a day or two to get published.

________________________________

**Comment by shankarmaha** [comment]
Hi,

I am trying to test this feature. But the api returns an empty object, even though the job has failed and I can see the error in DMF. This is what the job returns

{
  "@odata.context": "https://xyz.operations.dynamics.com/data/$metadata#Edm.String",
  "value": "[]"
}

I am passing this as the input 
{
	"executionId":"F7A4B553-91A0-43CC-B108-31299A41D844"
}

Any idea?
