### ISSUE TITLE
Obsollete information

### ISSUE THREAD

**Issue by TrudAX** [MicrosoftDocs/dynamics-365-unified-operations-public#1773]
Hi. Can you please check the following sentence: 
"The data packages that Microsoft publishes on LCS use a numbering sequence that is based on the module, data type, and sequence. Here is an example:" 
It seems this is no longer true. For version 10 the following packages provided:
Demo data 10.0.0 300 Supply chain PICH
Demo data 10.0.0 200 Financials PIFB
Demo data 10.0.0 200 Financials HQEU
Demo data 10.0.0 100 System and Shared
...
So naming convention has changed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da1ee1f9-6624-ffbb-70a5-d275c0cf4c62
* Version Independent ID: 48f53ecb-a716-e17b-8939-63b669176e73
* Content: [Process and consume data packages in Dynamics 365 Finance and Operations apps solution - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lcs-solutions/process-data-packages-lcs-solutions#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/lcs-solutions/process-data-packages-lcs-solutions.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/lcs-solutions/process-data-packages-lcs-solutions.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **omarc**

**Comment by tonyafehr** [comment]
@TrudAX, thanks for the feedback. 
@manalidongre, please review and address this feedback. Thank you!

**Comment by tonyafehr** [comment]
Bug 5643360 has been logged to track this issue.
