### ISSUE TITLE
The header is for on-premise and all drawings show cloud solution

### ISSUE THREAD

**Issue by amadse** [MicrosoftDocs/dynamics-365-unified-operations-public#1775]
This article is poor, as the header is for on-premise and all drawings show cloud solution. It doesn't show any graphics over the on-premise printing. Reading it make you doubt that this is for on-premise printing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b720ef96-1322-53fd-6048-a329cf3d6405
* Version Independent ID: c7f04b37-a94d-400a-da0c-b694d124b99e
* Content: [Document generation, publishing, and printing in on-premises deployments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/printing-capabilities-on-premises?toc=/dynamics365/commerce/toc.json)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/printing-capabilities-on-premises.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/printing-capabilities-on-premises.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by tonyafehr** [comment]
@TJVass, please review this feedback from @amadse and consider updating this topic.

**Comment by tonyafehr** [comment]
Bug 387403 has been logged to track this issue.
