### ISSUE TITLE
Should we register the printers again while upgrading ?

### ISSUE THREAD

**Issue by manishmoothedath** [MicrosoftDocs/dynamics-365-unified-operations-public#1779]
Hi,
While we uninstall and install the DRA agent as part of the upgrade, Should one delete the existing network printers registered in D365FO and register them again in DRA after installation ? This is not clear from the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 985d5890-1f5e-396d-6e74-96f8e86795fb
* Version Independent ID: 462818b6-e7dd-acea-33ed-f3f140245377
* Content: [Upgrade the Document Routing Agent - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/upgrade-document-routing-agent)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/upgrade-document-routing-agent.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/upgrade-document-routing-agent.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by sericks007** [comment]
@manishmoothedath, thanks for posting here!

@TJVass, please answer the question and update the content as needed.

**Comment by sericks007** [comment]
Bug 387893 has been logged to track this issue.

**Comment by TJVass** [comment]
YES - upon completion of the DRA upgrade, it is recommended that Admins register the printers connected through the host server.  However, network printers are identified by their network paths so as long as those don't change, you won't need to update network printer settings in F&O.

**Comment by manishmoothedath** [comment]
@TJVass thanks for clarifying. Could you please add this to the documentation as well. It will bring in more clarity!!

**Comment by kfend** [comment]
I have updated the topic with this information. Change will be published today.
