### ISSUE TITLE
Efficient use of reflection

### ISSUE THREAD

**Issue by ThomasZak** [MicrosoftDocs/dynamics-365-unified-operations-public#178]
In the above example, the system reads the attribute for a specified class. But what if we were looking for classes that are decorated with a specific attribute? Are we forced to iterate through every class in the system and query its attributes? Or is there simpler way to find all classes with that attribute?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cfc2d36-f4f6-7082-dbd9-b0477cc5119a
* Version Independent ID: 782a059d-47f3-9d5a-1e30-add8baf13251
* Content: [X++ attribute classes - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-ref/xpp-attribute-classes)
* Content Source: [articles/dev-itpro/dev-ref/xpp-attribute-classes.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-ref/xpp-attribute-classes.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RobinARH
* Microsoft Alias: **robinr**

**Comment by tonyafehr** [comment]
The topic has been updated to include a note, which basically says "There is no mechanism for listing all methods or classes that are adorned with a particular attribute from X++ code."
