### ISSUE TITLE
The KB Article Link is leading to the wrong page

### ISSUE THREAD

**Issue by torbennehmer** [MicrosoftDocs/dynamics-365-unified-operations-public#1780]
The KB-Link for the detailed PU30 changelog leads to the 10.0.6 application entry, not to the PU30 entry. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fdcd25d-46a4-d7ee-2d7d-444cbe100df6
* Version Independent ID: 58bc9ab7-de8b-6d5e-eb7a-8c9c574698b3
* Content: [What's new or changed in Platform update 30 for Finance and Operations apps (November 2019) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/whats-new-platform-update-30)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/whats-new-platform-update-30.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/get-started/whats-new-platform-update-30.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @tonyafehr
* Microsoft Alias: **tfehr**

**Comment by sericks007** [comment]
@torbennehmer, thanks for making us aware of this issue!  I've fixed the link, and the updated content will be published later today.
