### ISSUE TITLE
ModuleToRemove.txt

### ISSUE THREAD

**Issue by beefcake123** [MicrosoftDocs/dynamics-365-unified-operations-public#1781]
https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/uninstall-deployable-package
This link talks about a "ModuleToRemove.txt" package the can be added to the structure 'package\AOSService\Scripts'. How is this file processed by the runbook? Which step is responsible for executing the ModelToRemove logic? 

We want to create a minimalistic package, preferably only with the ModelToRemove to remove some older models. We don't want to deploy additional or existing custom code. but are unsure what minimally is necessary to get this working. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bcf4a74-1317-2f29-a9a6-3eb4c20c431f
* Version Independent ID: 9ce93e91-c55a-708b-bc9c-95a34bbf5b7b
* Content: [Apply updates to cloud environments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/apply-deployable-package-system)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/apply-deployable-package-system.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/deployment/apply-deployable-package-system.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @manalidongre
* Microsoft Alias: **manado**

**Comment by sericks007** [comment]
@beefcake123, thanks for posting here!  You might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community. 

@manalidongre, please answer the question and update the content, as needed.

**Comment by sericks007** [comment]
Bug 387906 has been logged to track this issue.
