### ISSUE TITLE
Roles and Reports

### ISSUE THREAD

**Issue by JJ431** [MicrosoftDocs/dynamics-365-unified-operations-public#1782]
Hi,

I have assigned the System report editor role to myself, but if I change the Personnel Mgmt workspace, other users keep seeing the default lay-out for that report.

Is there a step that I am missing?

Many thanks in advance.

Kind regards,

Jasper

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7cdec30-10b0-81c8-cb36-8f52b6a15fb0
* Version Independent ID: 237bbb65-f9d0-e58c-8962-52f4446a1631
* Content: [Workforce metrics Power BI content - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/workforce-analysis-power-bi-content-pack#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/workforce-analysis-power-bi-content-pack.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/workforce-analysis-power-bi-content-pack.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @jcart1106
* Microsoft Alias: **jcart**

**Comment by sericks007** [comment]
@JJ431, thanks for posting here! You might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community. 

@jcart1106, can you please answer the question and update the content, as needed.

**Comment by sericks007** [comment]
Bug 387910 has been logged to track this issue.

**Comment by sericks007** [comment]
@TJVass, please answer the question, and update the content as necessary.
