### ISSUE TITLE
Why not import ER configurations from LCS

### ISSUE THREAD

**Issue by SST1982** [MicrosoftDocs/dynamics-365-unified-operations-public#1789]
As far as I know, the primary source for all ER configurations is Lifecycle Services (LCS). In this document it is advised to download xml files from some web repository and import them manually. As of today, there are ER invoice templates under "Customer invoice model". I suppose these are such configurations meant to produce Business Documents. If that is the case, please update this page to reflect the newest features. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c9d868b-2b3b-26c9-f8ff-863e6f8cd9d4
* Version Independent ID: 9ea7a0a4-99ab-aca8-ca48-62ee8c02a92b
* Content: [Business document management overview - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/er-business-document-management#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/er-business-document-management.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/er-business-document-management.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @NickSelin
* Microsoft Alias: **nselin**

**Comment by sericks007** [comment]
@SST1982, thanks for posting here!

@NickSelin, please review and update the content, as necessary.

**Comment by kfend** [comment]
@SST1982  - Thanks for the feedback. We have updated the topic and the changes will be reflected today.
