### ISSUE TITLE
Editing a task recording

### ISSUE THREAD

**Issue by kristyler** [MicrosoftDocs/dynamics-365-unified-operations-public#1790]
Editing a task recording currently is flaky. If you insert a step in an existing recording, Task Recorder moves it to the last position when the test runs. Looking in the CS file shows that the ID for the new step makes it the last thing the recording does.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da49381d-db38-c6fc-ab3e-0e88a73f9d41
* Version Independent ID: ace8a33d-498d-9f39-9520-e0d5b93e0a06
* Content: [Set up and install Regression suite automation tool tutorial - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/hol-set-up-regression-suite-automation-tool#feedback)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/hol-set-up-regression-suite-automation-tool.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/get-started/hol-set-up-regression-suite-automation-tool.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **kfend**

**Comment by sericks007** [comment]
@kristyler, thanks for posting here!

@kfend, please assign to the appropriate PM to resolve.

**Comment by sericks007** [comment]
Bug 390234 has been logged to track this issue.

**Comment by josaw1** [comment]
Created BUG 437655.

**Comment by jasongre** [comment]
Improvements for the editing experience are planned. We'll consider this with those improvements.

**Comment by kristyler** [comment]
@jasongre Consider? Do you realize how many hours of extra work it is to rerecord tasks, because I can't reliably insert steps after a code release? Editing a task is currently useless, because I can't trust it to work every time. I hope you're taking this product seriously. As it is, I'm looking at moving to a different test platform to save time.

**Comment by jasongre** [comment]
@kristyler My apologies that you are having difficulties with task recorder. Have you engaged with customer support yet? That would always be the recommended route for reporting product bugs, especially for anything that is causing major pain.

**Comment by kristyler** [comment]
This site is where reporting a bug sent me.

[cid:image001.png@01D61261.1E863D50]
Kris​ Tyler
Data Analyst
2321 N Loop Dr, Ste 220
,
Ames
,
IA
,
50010
O: (515) 817-2143<tel:(515)%20817-2143>
LandusCooperative.com<http://www.landuscooperative.com/>
  |
Kris.Tyler@landuscooperative.com<mailto:Kris.Tyler@landuscooperative.com>
This email is intended for the use of the person to whom it is addressed and may contain information that is privileged and confidential, the disclosure of which is governed by applicable law. Dissemination, distribution or copying of this information in an unauthorized manner is strictly prohibited. Sender accepts no liability for any damage caused by any virus transmitted by this email. If you receive this email in error, please notify the sender.

**Comment by jasongre** [comment]
@kristyler You can report support issues for LCS or Finance and Operations apps as noted here: https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/lcs-support
