### ISSUE TITLE
Garbled character

### ISSUE THREAD

**Issue by VigneshMSCRM** [MicrosoftDocs/dynamics-365-unified-operations-public#1794]
Using this manual, the data is getting corrupted. CSV file downloaded from Post office site will be in Shift-JIS format and I believe Dynamics 365 only support UTF-8. Eventhough save the file as UTF-8 resulting in garbled character. Kindly update the manual to resolve this issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebfb02b0-9082-da6c-b6d4-8ca2f22be6a9
* Version Independent ID: 64fef9b0-6205-1f03-0569-6e37e95c1f98
* Content: [Import postal codes for Japan - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/apac-jpn-import-postal-codes)
* Content Source: [articles/finance/localizations/apac-jpn-import-postal-codes.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/localizations/apac-jpn-import-postal-codes.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @yijialuan
* Microsoft Alias: **riluan**

**Comment by josaw1** [comment]
Than you for your feedback. @yijialuan, can you please address these comments?

**Comment by josaw1** [comment]
Bug 392612 opened to track.

**Comment by josaw1** [comment]
We will be updating the topic later today. Thanks.
