### ISSUE TITLE
https’s server IP address could not be found. (fix.lcs.dynamics)

### ISSUE THREAD

**Issue by beefcake123** [MicrosoftDocs/dynamics-365-unified-operations-public#1797]
the "bug fixes"/"KB article" section contains a deadline to LCS.
https://docs.microsoft.com/en-us/dynamics365/finance/get-started/whats-new-changed-10-0-7#bug-fixes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85a380bf-8777-9eb4-0791-74c92b321746
* Version Independent ID: f8d3164a-44de-ba52-74ce-a8a6818053cd
* Content: [Preview features in Dynamics 365 Finance version 10.0.7 (January 2020) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/finance/get-started/whats-new-changed-10-0-7#bug-fixes)
* Content Source: [articles/finance/get-started/whats-new-changed-10-0-7.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/get-started/whats-new-changed-10-0-7.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @roschlom
* Microsoft Alias: **roschlom**

**Comment by josaw1** [comment]
Thank you for your feedback. I've updated the [link ](https://fix.lcs.dynamics.com/Issue/Details?bugId=386529&dbType=3&qc=e03ced97fa18dc4439f36de17b00da7257dc15869a72e5b2435fec0acec0c493)and will republish the topic later today.
