### ISSUE TITLE
When to apply upgraded code to upgrade application

### ISSUE THREAD

**Issue by dermicrosolutions** [MicrosoftDocs/dynamics-365-unified-operations-public#180]
Hi, It is a little unclear for me when to apply the deployable packages with the upgraded code & ISV packages to the application running the data upgrade. Should this be done before or after executing the data upgrade package directly from the LCS ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85ebf5ac-935b-265f-83a9-20463d015b46
* Version Independent ID: 3306c853-840a-1e49-8627-7ac4ae943961
* Content: [Upgrade data in development, demo, or sandbox environments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/upgrade-data-to-latest-update#feedback)
* Content Source: [articles/dev-itpro/migration-upgrade/upgrade-data-to-latest-update.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/migration-upgrade/upgrade-data-to-latest-update.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @tariqbell
* Microsoft Alias: **tabell**

**Comment by ShylaThompson** [comment]
Bug: 228898
