### ISSUE TITLE
Simulate posting in batch

### ISSUE THREAD

**Issue by jmash76** [MicrosoftDocs/dynamics-365-unified-operations-public#1803]
Hello,

Can anyone point to where the available code is mentioned/quoted below?

"Simulate posting is not available for batch processing. However, there is code available to simulate posting in batch and developers can extend the code to add that functionality."

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66997aea-1202-3f78-1476-4080952c6400
* Version Independent ID: c8daee2b-38bf-8ca9-e984-312104fea9a4
* Content: [General journal processing - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/finance/general-ledger/general-journal-processing)
* Content Source: [articles/finance/general-ledger/general-journal-processing.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/general-ledger/general-journal-processing.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @ShylaThompson
* Microsoft Alias: **peakerbl**

**Comment by RyanCCarlson2** [comment]
@jmash76 the code related to this can be found at LedgerJournalCheckPost.canGoBatch() 
The base class code is set to return false. If you do make any extension to change the return value to true, it would need to be fully tested.

**Comment by roschlom** [comment]
Closing this based on Ryan's comment just above.
