### ISSUE TITLE
X++ Job code cannot be copied

### ISSUE THREAD

**Issue by tomhig** [MicrosoftDocs/dynamics-365-unified-operations-public#1805]
The job code at the end of this article is in an image/picture, instead of in a format that can copied like other source code examples. 

See the lower section of the following for Source Code example presentation and how the Copy icon is used in top-right corner of code block: https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/write-business-logic#write-a-c-method-named-checkdriverslicense

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3883e64b-d788-42c2-ffdb-b637325fdff1
* Version Independent ID: 5fc97868-8b9c-2574-f198-857c5696a7ba
* Content: [Date effectivity - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/date-effectivity)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/date-effectivity.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-tools/date-effectivity.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by tonyafehr** [comment]
@tomhig, thanks for the suggestion.
@Sunil-Garg, please review and consider updating this topic.

**Comment by tonyafehr** [comment]
Bug 392046 has been logged to track this issue.

**Comment by Sunil-Garg** [comment]
The code snippet is now out of the image file :)
