### ISSUE TITLE
Big Fixes KB article link incorrect

### ISSUE THREAD

**Issue by andyNewnham** [MicrosoftDocs/dynamics-365-unified-operations-public#1806]
The link to the KB article includes and extra "HTTPS//" at the beginning which causes the link to not work. After removing the extra value, the link works correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5422ea93-f976-dd55-8451-a3ce821c71df
* Version Independent ID: bfc8f75d-62c2-7b44-36b5-5dbd06a97ec5
* Content: [Preview features in Dynamics 365 Retail version 10.0.7 - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/retail/get-started/whats-new-10-0-7?toc=/dynamics365/commerce/toc.json)
* Content Source: [articles/retail/get-started/whats-new-10-0-7.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/get-started/whats-new-10-0-7.md)
* Service: **dynamics-ax-retail**
* Product: ****
* Technology: ****
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by tonyafehr** [comment]
@andyNewnham, thanks for bringing this to our attention. An updated version of this topic will be published later today.
