### ISSUE TITLE
Belgium TAx on Credit note code

### ISSUE THREAD

**Issue by anboudin** [MicrosoftDocs/dynamics-365-unified-operations-public#1807]
There is missing information how reporting code for credit note should be setup.
8284 for exemple should be setup on Taxable purchase credit note (it will depend on Business case as service, goods.) But setup is not known from all. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db83953c-facb-1dc0-a74e-172d525e3692
* Version Independent ID: 297603ca-f320-fba0-7b97-d05a24cbec39
* Content: [INTERVAT tax declaration - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/emea-bel-intervat-tax-declaration)
* Content Source: [articles/finance/localizations/emea-bel-intervat-tax-declaration.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/localizations/emea-bel-intervat-tax-declaration.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @v-oloski
* Microsoft Alias: **v-oloski**

**Comment by tonyafehr** [comment]
@anboudin, thank you for the feedback. 
@kfend, please review and considering updating this topic.

**Comment by tonyafehr** [comment]
Bug 392049 has been logged to track this issue.
