### ISSUE TITLE
Global Variables in Message Validation

### ISSUE THREAD

**Issue by kristyler** [MicrosoftDocs/dynamics-365-unified-operations-public#1808]
How do I use a variable in message validation. Some messages have IDs or other data in them, such as the SO number when a pack slip is posted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92365ac0-138a-8f93-5745-33447e1b6e39
* Version Independent ID: fdff4379-d9c2-6291-21f9-e239593f7d82
* Content: [Use the Regression suite automation tool tutorial - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/hol-use-regression-suite-automation-tool)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/hol-use-regression-suite-automation-tool.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/get-started/hol-use-regression-suite-automation-tool.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **kfend**

**Comment by tonyafehr** [comment]
We will consider updating this topic to include this information, however, in the meantime, if you need to contact Support consider using one of the options described here: [Support contact options](https://docs.microsoft.com/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community. 

@robadawy, consider updating this topic based on this feedback.

**Comment by kristyler** [comment]
Yeah, I've tried that, but I'm not getting a response.

**Comment by tonyafehr** [comment]
Bug 392051 has been logged to track this issue.

**Comment by tonyafehr** [comment]
This topic has been updated.
