### ISSUE TITLE
Environment deployment state at Unknown

### ISSUE THREAD

**Issue by vjevtani** [MicrosoftDocs/dynamics-365-unified-operations-public#181]
I am deploying D365 ON Premise from LCS. All the configurations are done as per documentation. I triggered the deployment when it was on Deploying state, I started seeing logs on Orchestrators and it kept saying Unable to dispatch command id (guid) retries 0.

after some time, it went to state Unknown, and now I am not able to delete or re-configure it.

Please help asap

![image](https://user-images.githubusercontent.com/10010661/41354638-29cae662-6f28-11e8-9bc0-d4706c3deaac.png)

**Comment by ShylaThompson** [comment]
Thanks for contacting us. Unfortunately, we can't handle support requests for the product here. To contact support, consider one of the options described here:  https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support
