### ISSUE TITLE
A partner request to add following statement in this document.

### ISSUE THREAD

**Issue by YujiImaoka** [MicrosoftDocs/dynamics-365-unified-operations-public#1811]
A partner request to add following statement in this document to prevent breaks the chain of available restore points by mistake.
<>
Importing database breaks the chain of available restore points on Sandbox and Production.
After performing following database import process, the chain of available restore points are broken.
Customer cannot perform Point-in-time restore the backup which was backed up before importing database.
 On Sandbox: Import Database/Refresh Database/Point-in-time restore Prod to Sandbox
 On Production: Sandbox to Production

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 805f3739-0cad-d6ab-7db0-175c972f189f
* Version Independent ID: 68be2d28-d5e9-471d-8648-a8cbae2e1e7d
* Content: [Database point-in-time restore (PITR) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/database-point-in-time-restore#point-in-time-restore-breaks-the-chain-of-available-restore-points)
* Content Source: [articles/fin-ops-core/dev-itpro/database/database-point-in-time-restore.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/database/database-point-in-time-restore.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laneswenka**

**Comment by tonyafehr** [comment]
@YujiImaoka, thanks for the suggestion. 
@laneswenka, please review and consider updating this topic.

**Comment by tonyafehr** [comment]
Bug 392052 has been logged to track this issue.
