### ISSUE TITLE
Security diagnostics for task recordings is missing in the security documentation

### ISSUE THREAD

**Issue by amadse** [MicrosoftDocs/dynamics-365-unified-operations-public#1815]
"Security diagnostics for task recordings" which is a menu in Dynamics 365 Finance & Operations is not mentioned anywhere in Docs. I suggest it is added under security somewhere

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9907d444-3d05-f72e-7a7d-9e667c344987
* Version Independent ID: 4d757287-4674-dddf-1761-c57d0abe3530
* Content: [Role-based security - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/role-based-security)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/role-based-security.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/sysadmin/role-based-security.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @sericks007
* Microsoft Alias: **sericks**

**Comment by sericks007** [comment]
@amadse, thanks for posting here!

@ChrisGarty, please update the documentation accordingly.

**Comment by ChrisGarty** [comment]
That is a task recorder behavior that I'll have to check with @jasongre about. I don't know if it will warrant mentioning here, but there should be some documentation for it somewhere...

**Comment by amadse** [comment]
It is the task recorder. I just got the 2 tools mixed up.
Thanks

Regards
Anders Madsen
Microsoft

________________________________

**Comment by sericks007** [comment]
Assigning to @jasongre so that this can be added to the task guide documentation.  Bug 392056 has been logged to track this issue.

**Comment by josaw1** [comment]
BUG 437649 created.
