### ISSUE TITLE
Missing reference

### ISSUE THREAD

**Issue by RobvanB** [MicrosoftDocs/dynamics-365-unified-operations-public#1819]
Following this example, right off the bat I get this error that I am not able to resolve:
The type 'IEnumerable&lt;&gt;' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9756d775-3976-9fc0-df41-dc6bcf04d069
* Version Independent ID: 6de5c1a7-ae8a-4f30-c1ac-ed2a2b73b3cb
* Content: [Block transactions by using triggers - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/retail/dev-itpro/trigger-example-blocking-transaction)
* Content Source: [articles/retail/dev-itpro/trigger-example-blocking-transaction.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/dev-itpro/trigger-example-blocking-transaction.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by sericks007** [comment]
@RobvanB, thanks for posting here!

@mugunthanm, please review and update the documentation accordingly.

**Comment by mugunthanm** [comment]
Install .NET Framework 4.8 runtime. You can download the .NET Runtime from the below link:
https://dotnet.microsoft.com/download/visual-studio-sdks

**Comment by RobvanB** [comment]
I installed it, but I am still getting the error. What exactly should the project be targeting? Mine is showing .Net framework 4.6, Windows Universal 10.0 and ASP.Net Core 1.0

**Comment by RobvanB** [comment]
FYI - the solution is to add the netstandard.dll that is in the retailSDK\References folder to the project.

**Comment by sericks007** [comment]
@mugunthanm, please update the content accordingly.

**Comment by sericks007** [comment]
Bug 392060 has been logged to track this issue.

**Comment by mugunthanm** [comment]
![image](https://user-images.githubusercontent.com/11687998/68797172-f0579c80-0608-11ea-99f6-0d617e1da639.png)

**Comment by mugunthanm** [comment]
![image](https://user-images.githubusercontent.com/11687998/68797479-8a1f4980-0609-11ea-87ed-a548f3cdd2d7.png)

Use any of our sample project as template (\RetailSDK\SampleExtensions\CommerceRuntime\Extensions.EmailPreferenceSample)
