### ISSUE TITLE
Azure Blob storage

### ISSUE THREAD

**Issue by maveloso** [MicrosoftDocs/dynamics-365-unified-operations-public#182]
It is not explicit here, but for on premises solutions, my understanding is that the Application will use the Azure Storage Emulator, which means that it needs to be configured and running on your environment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85d06c76-517e-c0f9-f089-be75a47c1605
* Version Independent ID: 18059b14-4123-298f-51b0-c870f13a9bdc
* Content: [Data management package integration API - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/data-management-api?toc=/fin-and-ops/toc.json)
* Content Source: [articles/dev-itpro/data-entities/data-management-api.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/data-management-api.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by Sunil-Garg** [comment]
Hello-- the Azure storage emulator is not required for on premise deployments. It is only needed for cloud deployments.

Thanks.

**Comment by maveloso** [comment]
Hi, thanks for your comment, but even for on-premises, if you are doing development, you are most likely using a onebox environment that needs to have the storage emulator configured and running if you want to do any kind of integration testing with the data package API. I understand that for service fabric on-prem deployments you don't need it, but that is not explicit anywhere in the documentation, neither is the means that replaces the storage emulator when you deploy your integrations to the service fabric environment

**Comment by Sunil-Garg** [comment]
The storage that is used for integrations is configured by the system admin in service fabric set up. SMB or other file share can be specified which will be used for integrations by the system.

**Comment by maveloso** [comment]
perfect, thanks for the response
