### ISSUE TITLE
Missing info

### ISSUE THREAD

**Issue by simonefinotti** [MicrosoftDocs/dynamics-365-unified-operations-public#1822]
The article doesn't describe how **Fleet Management Unit Tests** is created.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2673e0e6-36ff-72f9-11dd-bfcfa1916882
* Version Independent ID: 01b6cf39-57a3-c6ca-af2c-4b7c530e5fdf
* Content: [Testing and validations - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/perf-test/testing-validation#prerequisites)
* Content Source: [articles/fin-ops-core/dev-itpro/perf-test/testing-validation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/perf-test/testing-validation.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **shailesn**

**Comment by josaw1** [comment]
Thank you for your feedback. @RobinARH can you please take a look?

**Comment by josaw1** [comment]
Bug 392609 created to track this issue.

**Comment by jain-shailesh** [comment]
I am not part of F&O, you should look for a different shailesh

**Comment by jorisdg** [comment]
Hi @simonefinotti , can you elaborate on your question?
The document describes adding a new project, and modifying it to point to the fleet management unit tests model. Does that not work for you?

**Comment by wojzeh** [comment]
The project with the generated code must be built fisrt before you can proceed with paragraph 6.

**Comment by simonefinotti** [comment]
> 
> 
> Hi @simonefinotti , can you elaborate on your question?
> The document describes adding a new project, and modifying it to point to the fleet management unit tests model. Does that not work for you?

Uhm, it's passed quite some time since I open the issue, maybe at the time I just missed the link in the step 2.

I guess I can close this issue, thanks.
