### ISSUE TITLE
Registration process instructions are outdated

### ISSUE THREAD

**Issue by turbozapekanka** [MicrosoftDocs/dynamics-365-unified-operations-public#1824]
The old way of registering an APP in Azure is no longer available.
One can probably use this way to create an app, not sure if the result is the same though:
https://docs.microsoft.com/en-us/power-bi/developer/register-app

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2213414-926d-10e1-538b-efef09dc0181
* Version Independent ID: 03be53f7-c305-cb02-7627-2ea4f1c01bd4
* Content: [Configure Power BI integration for workspaces - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/configure-power-bi-integration)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/configure-power-bi-integration.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/configure-power-bi-integration.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by josaw1** [comment]
Thank you for your feedback. @MilindaV2 can you please take a look?

**Comment by josaw1** [comment]
Bug 392605 created to track the issue.

**Comment by HariSeldon23** [comment]
I'm running into the same issue. The old app registration is no longer available as of October 2019. This means these documents are now legacy and are potentially harming customers.

Some issues:
* New App registration doesn't allow Application Keys, but rather Secrets
* Permissions have changed

**Comment by BasvGMRN** [comment]
Same issue here, do not understand how to perform the required actions to enable PowerBI in workspaces. Please update this doc page!

**Comment by DrGee-gethub** [comment]
These App Registration procedures are outdated.  
In Azure the screens and choices are different that the procedure.   
In Azure the App Registration > API Permissions has a great many more options.
