### ISSUE TITLE
Adding mandatory fields on released product

### ISSUE THREAD

**Issue by AartiKumar** [MicrosoftDocs/dynamics-365-unified-operations-public#1825]
Hi There
I have followed the process and successfully imported the vendior catalog & released to approved products to the legal entity. 
However the mandatory fields like item group, item model group and storage & tracking dimensions are missing. Given the high volume of products in the catalog, shouldn't these fields be added on the 'detail' screen, so the user can add these velues on each line, before the products are approved and released

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80aa4fdc-6fd6-ed14-7cb7-016360bfa9d8
* Version Independent ID: b46cbc5c-99a6-a096-8d4e-8c7b3f0e87d5
* Content: [Import vendor catalogs - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/supply-chain/procurement/vendor-catalogs-import)
* Content Source: [articles/supply-chain/procurement/vendor-catalogs-import.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/procurement/vendor-catalogs-import.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @mkirknel
* Microsoft Alias: **mkirknel**

**Comment by MaiKirknel** [comment]
Once the products are imported to a company they need to be configured as you correctly mention. The best option currently to mass update is through the Data entities.
