### ISSUE TITLE
Document handling attachments

### ISSUE THREAD

**Issue by ThomasZak** [MicrosoftDocs/dynamics-365-unified-operations-public#1826]
I understand that a decision was made to not copy document handling attachments. However I am wondering about the details of the process. For example when overwriting an old database that had some document attachments, are those document attachment files deleted during the copy process or do they remain in place?

In some cases that would be good, for things like the excel templates that may be linked by the tame tableId/recId in the new database. But in other cases, if test attachments were in the old database, they might be orphaned files that remain in place with no way to delete them. 

Can the process be explained in more detail?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d28e8cc-5110-f01b-db76-94479ec2fa91
* Version Independent ID: f0710707-9ff2-84a1-30c7-1f0d44e3a0d7
* Content: [Refresh database - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/database-refresh)
* Content Source: [articles/fin-ops-core/dev-itpro/database/database-refresh.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/database/database-refresh.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laneswenka**

**Comment by laneswenka** [comment]
Hi Thomas, we cannot go in to fine grained detail for security reasons however it is possible for files to be orphaned in your UAT environments.  Our recommendation is to do some file attachment testing in UAT but for Go Live the attachments should be loaded there instead.  This will reduce wasted space utilization.  That said, Azure Storage accounts can grow up to 2000TB so there is no realistic limit.
