### ISSUE TITLE
DictSecurityKey has been deprecated

### ISSUE THREAD

**Issue by DAXRunBase** [MicrosoftDocs/dynamics-365-unified-operations-public#1828]
DictSecurityKey has been deprecated, and is invalid in the example for DictTable.securityKey

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 100622a3-c345-efbc-0eae-fb19eff4a0f9
* Version Independent ID: 62e270b7-a183-bc07-195b-e5c78f985c9b
* Content: [D classes - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-ref/d-classes#class-dicttable)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-ref/d-classes.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-ref/d-classes.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **rhaertle**

**Comment by tonyafehr** [comment]
@DAXRunBase, thank you for the feedback.
@RobinARH, please review and consider updating this topic.

**Comment by tonyafehr** [comment]
Bug 397248 has been logged to track this issue.

**Comment by RobinARH** [comment]
I removed the code example, and the change should be published this evening. - Robin
