### ISSUE TITLE
Incomplete documentation

### ISSUE THREAD

**Issue by mueckeflo** [MicrosoftDocs/dynamics-365-unified-operations-public#1832]
Hi,
Customer has come back to us saying, that the provided info on this page is incomplete/incorrect, as it requires some customization in order to work properly. Solely performing a setup is not sufficient - as described in this blog article:
https://cloudblogs.microsoft.com/dynamics365/no-audience/2018/12/14/extending-the-extended-logon-functionality-for-mpos-and-cloud-pos/

Please include the info from the blog to reflect the required customizations - esp. with regards to the barcode setup.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44d8654f-de0f-8263-7de3-07f27de99c2a
* Version Independent ID: c5928e21-a412-b45d-5cc4-7f9c9de02109
* Content: [Set up extended logon functionality for MPOS and Cloud POS - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/retail/extended-logon)
* Content Source: [articles/retail/extended-logon.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/extended-logon.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @rubencdelgado
* Microsoft Alias: **rubendel**

**Comment by sericks007** [comment]
@mueckeflo, thanks for making us aware of this!

@rubencdelgado, please review and update the topic as needed.

**Comment by sericks007** [comment]
Bug 394133 has been logged to track this issue.

**Comment by sericks007** [comment]
This issue has been reviewed and bug 409753 has been logged to fix the sample, instead of the documentation. Closing this issue because the "fix" won't be made in this topic.
