### ISSUE TITLE
Deployable packages from third parties

### ISSUE THREAD

**Issue by torbennehmer** [MicrosoftDocs/dynamics-365-unified-operations-public#1833]
When deploying third party packages, is the folder bin\GeneratedXppSource neccessary? It contains x++ files, already in the package provided from the build server from the ISV build process. Do we need this directory in the customer install or not? It would be great if you could clarify the documentation in this respect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8bbe687-430e-38d6-b408-29985afac48a
* Version Independent ID: f444ee9c-2c8a-b095-2eb0-50b40b963403
* Content: [Manage third-party models and runtime packages by using source control - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/manage-runtime-packages)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/manage-runtime-packages.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-tools/manage-runtime-packages.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @jorisdg
* Microsoft Alias: **jorisde**

**Comment by sericks007** [comment]
@torbennehmer, thanks for posting here!

@jorisdg, please review and update the topic as necessary.

**Comment by sericks007** [comment]
Bug 394134 has been logged to track this issue.

**Comment by jorisdg** [comment]
No the GeneratedXppSource doesn't need to be in there but it doesn't hurt. We're looking into avoiding packaging these up entirely so you wouldn't even have to think about this.
