### ISSUE TITLE
Architecture

### ISSUE THREAD

**Issue by RobertRudd** [MicrosoftDocs/dynamics-365-unified-operations-public#1835]
Security documentation does not talk about new architecture i.e. security roles now stored in database and how the movement of security roles are now performed i.e. export and import.  This is very different from AX 2012 and should be covered.

**Comment by josaw1** [comment]
Thank you for your feedback. @ChrisGarty can you please take a look?

**Comment by RobertRudd** [comment]
One of our developers just sent me this if that helps.
[cid:image001.png@01D59BA2.BF83C9B0]

Robert Rudd
Principal consultant
Microsoft Services
Business Applications Domain
Asia Pacific
Mobile: +61 407 784 054
Robert.Rudd@microsoft.com<mailto:Robert.Rudd@microsoft.com>
[Microsoft]

**Comment by josaw1** [comment]
Bug 400316 created to track this issue. @ChrisGarty
