### ISSUE TITLE
How to access SQL in Cloud/Prod scenarios?

### ISSUE THREAD

**Issue by SST1982** [MicrosoftDocs/dynamics-365-unified-operations-public#1836]
As far as I know, in a production system in cloud, it is not possible to access the underlying SQL server as instructed in this document. Does this document only apply to on-premise installations or only non-productive systems? Is there currently a way to use Entity store in PROD/Cloud scenario? 

Please also discuss the relation to the currently experimental Data Lake scenario as discussed in https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/entity-store-data-lake

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da145b17-ccd8-7bf7-7495-0ddb1bf5829f
* Version Independent ID: 2a24d715-ecac-1c65-d2d4-8d14b55b8765
* Content: [Power BI integration with Entity store - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/power-bi-integration-entity-store)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/power-bi-integration-entity-store.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/power-bi-integration-entity-store.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by josaw1** [comment]
Thank you for your feedback. @MilindaV2 can you please take a look?

**Comment by josaw1** [comment]
Bug 400314 created to track this issue.
