### ISSUE TITLE
Path in documentation is incorrect

### ISSUE THREAD

**Issue by beefcake123** [MicrosoftDocs/dynamics-365-unified-operations-public#1837]
The path seems to be outdated. We found it in AOS-service-drive:\PerfSDK\PerfSDKlocalDirectory\Perftools\traceparser.msi for all our T1 environments.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10726552-f92e-cfb9-7662-7f1db24f8bd3
* Version Independent ID: ea6e6432-effb-2626-858b-28bea131b673
* Content: [Diagnose issues and analyze performance by using Trace parser - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/perf-test/trace-parser)
* Content Source: [articles/fin-ops-core/dev-itpro/perf-test/trace-parser.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/perf-test/trace-parser.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **chwolf**

**Comment by josaw1** [comment]
Thank you for your feedback. @RobinARH can you please take a look?

**Comment by josaw1** [comment]
Bug 400312 created to track this issue.

**Comment by RobinARH** [comment]
Fixed. Should go live tonight.
