### ISSUE TITLE
Upgrade source environment to latest version

### ISSUE THREAD

**Issue by aariste** [MicrosoftDocs/dynamics-365-unified-operations-public#184]
I've been recommended by support to upgrade the source environment on AX2012 to the latest CU. I miss this here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69b1066c-6f4d-9496-597e-675df6232358
* Version Independent ID: 828b28e1-78af-6d09-1707-df1021ef5bf8
* Content: [Upgrade from AX 2012 - Pre-upgrade checklist for data upgrade - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/prepare-data-upgrade)
* Content Source: [articles/dev-itpro/migration-upgrade/prepare-data-upgrade.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/migration-upgrade/prepare-data-upgrade.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @robadawy
* Microsoft Alias: **robadawy**

**Comment by robadawy** [comment]
I am not sure how to document this request. I would not worry about it.

**Comment by noorsyyad** [comment]
do we need to have run this pregrade checklist for data upgrade when upgrading to D365 Finance & Operations 8.1

**Comment by laneswenka** [comment]
This should be closed, version 8.1 is out of support.  The AX2012 Preupgrade check list should be run on all upgrades per the documentation.
