### ISSUE TITLE
Wrong date in Ja-JP version of this page

### ISSUE THREAD

**Issue by VigneshMSCRM** [MicrosoftDocs/dynamics-365-unified-operations-public#1843]
Dear team,

10.0.8 Platform update 32 version's Generally available date is showing 2016 in Ja-JP page. Kindly help to fix the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7dcb285-f32c-c92e-fe49-1617f213066b
* Version Independent ID: 8f28c1a0-9da5-f853-90ee-d82a4c32df7e
* Content: [Service update availability - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/public-preview-releases#feedback)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/public-preview-releases.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/get-started/public-preview-releases.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @meeramahabala
* Microsoft Alias: **meeram**

**Comment by RobinARH** [comment]
Bug 23097 created to track this issue.

**Comment by vinceno** [comment]
this issue is now addressed
