### ISSUE TITLE
outdated

### ISSUE THREAD

**Issue by zmottie** [MicrosoftDocs/dynamics-365-unified-operations-public#1848]
This page hasn't been updated since late 2017 and there are versions as recently as September 2019.

https://cloudblogs.microsoft.com/dynamics365/it/2019/09/18/lifecycle-services-september-2019-release-2-release-notes/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d8d91ac-1947-9637-3b39-53d832483355
* Version Independent ID: 69495807-2269-65d3-0825-2f4174d6096c
* Content: [What's new in Lifecycle Services (LCS) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/whats-new-lcs)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/whats-new-lcs.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/lifecycle-services/whats-new-lcs.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **kfend**

**Comment by RobinARH** [comment]
@kfend - Can you take a look? Thanks - Robin

**Comment by RobinARH** [comment]
Created bug 398725 to track this issue.

**Comment by kfend** [comment]
@zmottie - thank you for bringing this to our attention. I have updated the topic with a link to the [release plans](https://go.microsoft.com/fwlink/?linkid=2010158) which is where we are now posting this type of information.
