### ISSUE TITLE
Some pre-upgrade steps missing

### ISSUE THREAD

**Issue by aariste** [MicrosoftDocs/dynamics-365-unified-operations-public#185]
There's some useful steps I'm missing in this doc, or maybe it's in another one under AX2012 upgrade but I've missed it.

- Mark all batches as withhold on the DB or perhaps stopping them in the source AX2012 before exporting the DB. Or just delete all of the batches before running the upgrade scripts...
- When upgrading large DBs split TempDB's MDF files between the free space of all disks. Otherwise the TempDB disk will run out of space and the process will fail.
- Reindex the source DB. Not even 50% sure this helps but I'd give it a try.

And this is just a little rant: why running the same upgrade scripts on the same DB on different VMs (with the same setup) has ALWAYS different outcomes? It's pretty hard and frustrating to estimate the time we need to do an upgrade because it's like the lottery.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f408443a-7381-120f-9a42-4a394db4c284
* Version Independent ID: 5ec84f24-c0dd-7ddb-7374-99227632dcb2
* Content: [Upgrade from AX 2012 - Data upgrade in a development environment - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/data-upgrade-2012#end-to-end-data-upgrade-process)
* Content Source: [articles/dev-itpro/migration-upgrade/data-upgrade-2012.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/migration-upgrade/data-upgrade-2012.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @tariqbell
* Microsoft Alias: **tabell**

**Comment by robadawy** [comment]
Please assign this to Dave Johnson or Meera Mahabala. I don't know if any changes are needed to the doc here.

**Comment by sbaber82** [comment]
There is no mention in the documentation that the Tier1 DEV environment you will get as part of D365 subscription have limited drive space and you won't be able to restore large databases there in order to run the database upgrade process. I think it should be there in the docs, so that as a partner we know that we need to have the cloud hosted environment to restore the database and then run the database upgrade because you can increase the disk space if you want to unlike in MS managed environment.

**Comment by laneswenka** [comment]
This is valid, I will make an update.  Please assign to me.

**Comment by sbaber82** [comment]
Has the document been updated about the limited space available on Azure DEV machine? I can't see the update on the original doc page. Am I missing anything ?
