### ISSUE TITLE
Wrong text

### ISSUE THREAD

**Issue by amadse** [MicrosoftDocs/dynamics-365-unified-operations-public#1851]
This is wrong
How does the default storage location for Document Management change in Finnce + Operations environments?

For Finance + Operations, the Azure Blob storage provider for attachments is replaced by a file folder storage provider so that attachments are kept on-premise instead of being stored in the cloud. Therefore, the default storage location for attachments is a file folder.

In both case "Finance + Operations" should be replaced with "Dynamics 365 Finance & Operation On-premise"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e919a898-2ff3-73a4-0960-33264a0ab5f3
* Version Independent ID: 9a49ca3d-b872-cb63-7e53-a8a0db55d749
* Content: [Configure document management - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/organization-administration/configure-document-management)
* Content Source: [articles/fin-ops-core/fin-ops/organization-administration/configure-document-management.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/organization-administration/configure-document-management.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @ChrisGarty
* Microsoft Alias: **cgarty**

**Comment by sericks007** [comment]
@ChrisGarty, please review the comments about blob storage, and update the content if necessary.

**Comment by sericks007** [comment]
Bug 397716 has been logged to track this issue.
