### ISSUE TITLE
What is the difference between two sections?

### ISSUE THREAD

**Issue by valerymoskalenko** [MicrosoftDocs/dynamics-365-unified-operations-public#1857]
I couldn't find any significant difference between the following sections on this document
## On-premises upgrade from version 7.x (with Platform update 21 or later) to 8.1

Well, the only difference is at Prerequisites' topic in the second section, block number 6. It is regarding PU version update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8de583e-d692-9b26-8dc9-257adf4386de
* Version Independent ID: 8b2b32ad-6e64-017e-8abd-77809fa8f6a5
* Content: [In-place upgrade process for on-premises environments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/on-prem-upgrade#on-premises-upgrade-from-version-7x-with-platform-update-21-or-later-to-81)
* Content Source: [articles/fin-ops-core/dev-itpro/migration-upgrade/on-prem-upgrade.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/migration-upgrade/on-prem-upgrade.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by laneswenka** [comment]
This article was written by the on-prem team, and it looks like there are 9 pre-reqs for the second section and only 6 for the first section.  I would examine those to determine the minor differences.
