### ISSUE TITLE
Developer tools as installable component

### ISSUE THREAD

**Issue by SysC0mp** [MicrosoftDocs/dynamics-365-unified-operations-public#1859]
What happened to the developer tools as installable component? I cannot find any information about it at the moment.  Is that feature still planned?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0723686d-7b30-9831-8978-10077d700724
* Version Independent ID: cbfeb85f-9ae0-8d93-bd8a-5a6bdd2fa41b
* Content: [Preview features in Platform update 31 for Finance and Operations apps (January 2020) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/get-started/whats-new-platform-update-31)
* Content Source: [articles/fin-ops-core/dev-itpro/get-started/whats-new-platform-update-31.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/get-started/whats-new-platform-update-31.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @tonyafehr
* Microsoft Alias: **tfehr**

**Comment by RobinARH** [comment]
You can find the latest date in the release plans:
https://docs.microsoft.com/en-us/dynamics365-release-plan/2019wave2/change-history
