### ISSUE TITLE
Power BI models with Data Entities instead of local DB

### ISSUE THREAD

**Issue by UnicornBeards** [MicrosoftDocs/dynamics-365-unified-operations-public#186]
This and other Model Power BI files available with LCS, are built for local AXDB connecting to a SQL server, which for companies using a Tennant in the cloud need to use Data Entities.  Are there versions of this and other Power BI models that can use Data Entities through the oData or Dynamics Online connector?   Unless there is another way, for most companies these power bi model files would be useless, unless they are recreated by end users, and have a scheduled sync.  Don't know what I'm missing here, maybe need to research more....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1669979-17c7-90b7-9ef9-1b577776de45
* Version Independent ID: 770f62b2-349b-7b77-13ed-ec9f19f133a8
* Content: [Warehouse performance Power BI content - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/warehouse-power-bi-content)
* Content Source: [articles/dev-itpro/analytics/warehouse-power-bi-content.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/warehouse-power-bi-content.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @Mirzaab
* Microsoft Alias: **mirzaab**

**Comment by UnicornBeards** [comment]
Used as Contact Feedback, maybe this goes to Product Feedback???

**Comment by ShylaThompson** [comment]
Thanks for contacting us. For discussions about how to use features, we recommend that you post on the [Finance and Operations community forum](https://community.dynamics.com/365/financeandoperations/f/765).

**Comment by UnicornBeards** [comment]
I have, but do not feel there is an answer.  looks like this is created only for customers who use on premise, and not hosted.  Thanks.
