### ISSUE TITLE
Transport documentation

### ISSUE THREAD

**Issue by RobertRudd** [MicrosoftDocs/dynamics-365-unified-operations-public#1862]
The transport documents needs a lot more work.  It focuses almost completely on configuration however, there is very little on the process.   For example, how are inbound loads/shipments processed?  A clear aim of the documentation should be to allow someone to process a transaction with in the demonstration environment so that they can learn the process.  The other aspect which is important for a lot of customer is whether transport can handle the costing back to products for landed costs.  This is not addressed at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46a6b0b9-0677-fb98-3a9a-f59cf8aa2af4
* Version Independent ID: 6d6d1f57-af3c-1f8a-87c3-8ddf035763f6
* Content: [Transportation management overview - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/supply-chain/transportation/transportation-management-overview?source=docs#feedback)
* Content Source: [articles/supply-chain/transportation/transportation-management-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/transportation/transportation-management-overview.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @MarkusFogelberg
* Microsoft Alias: **mafoge**

**Comment by MarkusFogelberg** [comment]
Thank you for the valuable feedback. We will take your suggestion to have more process oriented documentation into consideration for future development of our documentation. In the mean time you might want to have a look at this learning course at Microsoft Learn: 
[Configure and work with transportation management in Dynamics 365 for Finance and Operations](https://docs.microsoft.com/en-us/learn/modules/configure-transportation-management-dyn365-supply-chain-mgmt/)
If you are interested in a video demonstration, please have a look here: 
https://youtu.be/jgmTgJIgEFQ
