### ISSUE TITLE
control-collection-letters-at-the-customer-level vs control-collection-letters-at-transaction-level

### ISSUE THREAD

**Issue by Dimitri-Tetsch** [MicrosoftDocs/dynamics-365-unified-operations-public#1865]
Hi, It might be useful to expand as well on "Control collection letters at transaction level" so that the difference between "Control collection letters at customer level" vs "Control collection letters at transaction level" is explained. Or I am missing something? Best regards, Dimitri

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a4d4d55-5b82-1362-6b5f-70c20ab9b654
* Version Independent ID: 1c51a483-03df-e598-34fb-192b22aadce8
* Content: [Process collection letters - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/finance/accounts-receivable/tasks/process-collection-letters)
* Content Source: [articles/finance/accounts-receivable/tasks/process-collection-letters.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/accounts-receivable/tasks/process-collection-letters.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @ShivamPandey-msft
* Microsoft Alias: **shpandey**

**Comment by tonyafehr** [comment]
@Dimitri-Tetsch, thanks for suggestion.  
@ShivamPandey-msft, please review and consider making updates.

**Comment by tonyafehr** [comment]
Bug 398935 logged to track this issue.

**Comment by ShivamPandey-msft** [comment]
+Pat

**Comment by tonyafehr** [comment]
This topic has been updated.
