### ISSUE TITLE
The remote server returned an error: (400) Bad Request.

### ISSUE THREAD

**Issue by MRasheed84** [MicrosoftDocs/dynamics-365-unified-operations-public#1866]
Business Event is showing below error 
The remote server returned an error: (400) Bad Request. 
what could be the reason ?

**Comment by tonyafehr** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
