### ISSUE TITLE
Database Movement not working with AX 2012 bacpac

### ISSUE THREAD

**Issue by jkehlet** [MicrosoftDocs/dynamics-365-unified-operations-public#1868]
The instructions at https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/upgrade-data-sandbox#upload-the-bacpac-file-to-azure-storage-or-the-lcs-asset-library are no longer valid for AX 2012 R3 bacpac files. They now have to be uploaded to LCS and imported using the Data Movement process.

However, the Data Movement package has a SanitizeAOSDB.sql script that is expecting tables and columns that only exist in a D365F&O database that has already been upgraded - so it fails.

**UPDATE:** It also tries to do a synchronization of the database, which is a no-go, because we have to run the AX2012DataUpgrade-10-0-6 package afterwards. So the whole package/script needs to be revised to support AX 2012 R3 bacpac files.

**UPDATE:** It also tries to start the Batch service, which now fails because it's not a D365F&O database.

**UPDATE:** Maybe read SQLSYSTEMVARIABLES.SYSTABVERSION to detect? The latest version of AX 2012 R3 is somewhere around 119, whereas D365F&O is up to 146. I'm sure the cutover point (AX 7?) is somewhere in the 120es or 130es, right? The 2 scripts that need modifying is `AOSService\Scripts\DataMovement\DataMovementUpdateAOSDB.ps1` (should not execute the SQL scripts and synchronize at all) and `AOSService\Scripts\AutoStartAOS.ps1` (will not start the Batch service when an AX 2012 bacpac has been loaded).

**UPDATE:** For those brave enough to go through with this until an updated package has been made available, just edit these 2 PowerShell scripts to return immediately before executing anything.

Is there an ETA for an updated process/solution? We have customers in the middle of upgrading from AX 2012 R3, and this is holding us up.

**Comment by tonyafehr** [comment]
@jkehlet, thanks for the feedback. If you need immediate assistance, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community. 
@tariqbell, please review and consider making updates.

**Comment by tariqbell** [comment]
This one is owned by @Lane Swenka<mailto:Lane.Swenka@microsoft.com> now

Tariq Bell
Senior Solution Architect
United Kingdom
Dynamics 365 for Operations R&D
Office: +44 (118) 9092391
tabell@microsoft.com<mailto:tabell@microsoft.com>
[MSFT_logo]

This and subsequent emails on the same topic are for discussion and information purposes only. Only those matter set out in a fully executed agreement are legally binding. This email may contain confidential information and should not be shared with any third party without the prior written agreement of Microsoft. If you are not the intended recipient, take no action and contact the sender immediately.

Microsoft Limited (company number 01624297) is a company registered in England and Wales whose registered office is at Microsoft Campus, Thames Valley Park, Reading RG6 1WG

**Comment by tonyafehr** [comment]
Bug 398937 has been logged to track this issue.

**Comment by laneswenka** [comment]
2012 should use the .bacpac process and Azure storage if the file is large, or it can use the LCS Asset Library for storage.  Database Movement operations expect an already-upgraded bacpac as you point out, but you can still use Remote Desktop to download these bacpacs and import them manually.
In the customer implementation project, there is an option called Project Onboarding in the navigation menu.  Therein, on the project scope tab is the Legacy System field which customers can identify themselves as AX2012 Upgrade.  From there, they will get a traditional infrastructure deployment which allows for Remote Desktop and non-elastic databases which allows for manual bacpac import.
