### ISSUE TITLE
Link to App Faric planning is wrong

### ISSUE THREAD

**Issue by amadse** [MicrosoftDocs/dynamics-365-unified-operations-public#1870]
As this is true"An on-premises deployment uses Azure Service Fabric standalone clusters", the link in "see Service Fabric cluster capacity planning considerations" must be this one "https://docs.microsoft.com/da-dk/azure/service-fabric/service-fabric-cluster-standalone-deployment-preparation" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6c7e467-87c9-70c8-c819-b1f5c0057352
* Version Independent ID: 0feef83a-6d18-8685-2c6c-6225c0db03e5
* Content: [Plan and prepare for on-premises deployments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/plan-onprem-deployment?source=docs)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/plan-onprem-deployment.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/deployment/plan-onprem-deployment.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **robinr**

**Comment by sericks007** [comment]
@amadse, thanks for making us aware of this!  I've updated the link.  The updated article will be published later today.
