### ISSUE TITLE
Link to App Faric planning is wrong

### ISSUE THREAD

**Issue by amadse** [MicrosoftDocs/dynamics-365-unified-operations-public#1873]
As this is true"An on-premises deployment uses Azure Service Fabric standalone clusters", the link in "see Service Fabric cluster capacity planning considerations" must be this one "https://docs.microsoft.com/da-dk/azure/service-fabric/service-fabric-cluster-standalone-deployment-preparation"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8dadf2b-038b-f098-8670-ca580a3cc442
* Version Independent ID: 04c44292-1ebf-a7e1-dddb-3b57a1474c80
* Content: [Hardware sizing requirements for on-premises environments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/hardware-sizing-on-premises-environments?toc=/dev-itpro/toc.json)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/hardware-sizing-on-premises-environments.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/get-started/hardware-sizing-on-premises-environments.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **chwolf**

**Comment by sericks007** [comment]
@amadse, thanks for making us aware of this!  I've fixed the link.  The updated article will be published later today.
