### ISSUE TITLE
Add raise case to support for Production svc restarts.

### ISSUE THREAD

**Issue by robabb123** [MicrosoftDocs/dynamics-365-unified-operations-public#1877]
Would be a nice addition if it were mentioned to raise a support case if Production services need to be restarted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9452234-62df-d7ed-1243-4f2a14553df3
* Version Independent ID: 14f785e5-da29-5cc9-bd8a-d548c93d15e9
* Content: [Restart environment services - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/restart-environment-services#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/restart-environment-services.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/lifecycle-services/restart-environment-services.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **manado**

**Comment by sericks007** [comment]
@robabb123, thanks for posting here!

@manalidongre, please review and update the content as needed.

**Comment by sericks007** [comment]
Bug 401268 has been logged to track this issue.
