### ISSUE TITLE
Not Working with Hour Journal

### ISSUE THREAD

**Issue by NicholasFook79** [MicrosoftDocs/dynamics-365-unified-operations-public#1878]
Hi,

  I've tested and it seems that the timesheet optimized for mobile has an issue. It  does not create Hour journal that associated to a project. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a1ffaf4-9994-bb4d-1352-bc6f1b2970d5
* Version Independent ID: 92528eb8-8f45-9d35-0a94-c8618cdc0e8c
* Content: [Project timesheets on a mobile device - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/finance/project-management/mobile-timesheets)
* Content Source: [articles/finance/project-management/Mobile-timesheets.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/project-management/Mobile-timesheets.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @abruer
* Microsoft Alias: **abruer**

**Comment by sericks007** [comment]
@NicholasFook79, thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 Community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community. 

Adding @abruer here for awareness.
