### ISSUE TITLE
Setting navigation properties - No related content

### ISSUE THREAD

**Issue by erikpaperik** [MicrosoftDocs/dynamics-365-unified-operations-public#1880]
There is no content showing how to set up navigation properties under the "Setting navigation properties between OData entities".
Instead you find paragraphs about "Adding actions on OData entities" within the navigation properties section.
Is there any content missing or should "Adding actions on OData entities" simply not be nested below "Setting navigation properties between OData entities"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d7c8b45-1531-ebbf-d417-4e1fe5bf4f1b
* Version Independent ID: c543a5fc-90c9-9edb-11d7-6d6d0f2c10a9
* Content: [Open Data Protocol (OData) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/odata#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/odata.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/odata.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by RobinARH** [comment]
@Sunil-Garg - Can you take a look? Thanks.

**Comment by RobinARH** [comment]
Bug 413521 filed to track this issue.
