### ISSUE TITLE
Broken link in the Dynamics 365 Retail section of this page

### ISSUE THREAD

**Issue by skolbin-ssi** [MicrosoftDocs/dynamics-365-unified-operations-public#1881]
The correct link should be pointing to https://docs.microsoft.com/en-us/dynamics365/retail/retail-onprem

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e31272cf-a87f-0c73-631f-2829cf9ef1ff
* Version Independent ID: e81b0610-320c-eddc-fab2-557685148fc1
* Content: [Comparison of cloud and on-premises features - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/cloud-prem-comparison#dynamics-365-retail)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/cloud-prem-comparison.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/get-started/cloud-prem-comparison.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @sericks007
* Microsoft Alias: **sericks**

**Comment by sericks007** [comment]
@skolbin-ssi, thanks for bringing this to our attention!  I've fixed the link.  The updated content will be published later today.  Thanks again!
