### ISSUE TITLE
Incorrect Path in Header

### ISSUE THREAD

**Issue by LukeSchmidtPwC** [MicrosoftDocs/dynamics-365-unified-operations-public#1885]
Hi,

It appears that the path of this document is incorrect  in the Content header. It says "Dynamics -&gt; Dynamics 365 Finance -&gt; Accounts Payable" 

I am assuming this should be Accounts Receivable

Thanks &
Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 597ca5b7-29e5-a1c2-9cc5-2bf507afb7bf
* Version Independent ID: 67526d48-a13b-1a3c-3dc6-27d1779654a4
* Content: [Record vendor invoice and match against received quantity - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/finance/accounts-receivable/tasks/record-vendor-invoice-match-against-received-quantity#feedback)
* Content Source: [articles/finance/accounts-receivable/tasks/record-vendor-invoice-match-against-received-quantity.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/accounts-receivable/tasks/record-vendor-invoice-match-against-received-quantity.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @ShivamPandey-msft
* Microsoft Alias: **shpandey**

**Comment by tonyafehr** [comment]
@LukeSchmidtPwC, thanks for noting this. 
@roschlom, please review and fix. Thanks!

**Comment by roschlom** [comment]
@LukeSchmidtPwC, @tfehr, This is fixed now. Thanks again for noting the issue.

**Comment by roschlom** [comment]
This has been fixed (12/04/2019).
