### ISSUE TITLE
"Regulatory updates" summary

### ISSUE THREAD

**Issue by weaveriski** [MicrosoftDocs/dynamics-365-unified-operations-public#1886]
The summary for the "Regulatory updates" section in the LCS user guide mentions customers, partners and ISV's keeping up to date but the page you go to focuses solely on ISVs creating and submitting regulatory updates. There seems to be a disconnect here? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6f50615-72db-d0a6-6884-f8d8bcc54d1b
* Version Independent ID: de31cdbd-ce35-5971-37be-185491598b5a
* Content: [Lifecycle Services (LCS) user guide - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/lcs-user-guide)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/lcs-user-guide.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/lifecycle-services/lcs-user-guide.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @manalidongre
* Microsoft Alias: **manado**

**Comment by tonyafehr** [comment]
@weaveriski, thanks for the feedback. 
@kfend and @manalidongre, please consider making updates to this area.

**Comment by tonyafehr** [comment]
Bug 5888589 has been logged to track this issue.
