### ISSUE TITLE
Remvoing test cases from a topic in a BPM library

### ISSUE THREAD

**Issue by kristyler** [MicrosoftDocs/dynamics-365-unified-operations-public#1891]
Someone created duplicate test cases on one topic in the library. How do I clean that up?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89c1a6d1-3461-82e7-964d-54aa95a1ad93
* Version Independent ID: 7d9a39de-37e5-5d58-d6e6-bf705835b10f
* Content: [Create and automate user acceptance tests - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/using-task-guides-and-bpm-to-create-user-acceptance-tests)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/using-task-guides-and-bpm-to-create-user-acceptance-tests.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/lifecycle-services/using-task-guides-and-bpm-to-create-user-acceptance-tests.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **ntecklu**

**Comment by sericks007** [comment]
@kristyler, thanks posting here! We'll look into adding this information to the content.  In the meantime,  if you want to contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

**Comment by sericks007** [comment]
@robadawy, please review and consider updating the content based on this feedback.

**Comment by robadawy** [comment]
Delete the node in BPM, or if you are not using BPM, delete the test case in DevOps.

**Comment by kristyler** [comment]
Deleting the test case in DevOps results in a sync error in BPM when BPM can’t find it. That’s the issue. The other test case is valid, so I really don’t want to trash the whole thing.

[cid:image001.jpg@01D5AB8B.A258CC70]
Kris​ Tyler
Data Analyst
2321 N Loop Dr, Ste 220
,
Ames
,
IA
,
50010
O: (515) 817-2143<tel:(515)%20817-2143>
LandusCooperative.com<http://www.landuscooperative.com/>
  |
Kris.Tyler@landuscooperative.com<mailto:Kris.Tyler@landuscooperative.com>
This email is intended for the use of the person to whom it is addressed and may contain information that is privileged and confidential, the disclosure of which is governed by applicable law. Dissemination, distribution or copying of this information in an unauthorized manner is strictly prohibited. Sender accepts no liability for any damage caused by any virus transmitted by this email. If you receive this email in error, please notify the sender.

**Comment by sericks007** [comment]
Bug 401965 has been logged to track this issue.

**Comment by jorisdg** [comment]
Please go through support for help on this.

**Comment by kristyler** [comment]
I thought this WAS support.
