### ISSUE TITLE
incorrect instructions.

### ISSUE THREAD

**Issue by ThomasZak** [MicrosoftDocs/dynamics-365-unified-operations-public#1892]
this page says that a document is always uploaded as "just me" scope.  Then it claims " When an asset must be shared with multiple users within a tenant, the tenant admin can promote the asset to the Organization scope."

I have confirmed with my tenant admin that this does not work and they cannot see any objects I loaded with "just me" scope, and therefore cannot promote them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 786fc060-d324-2e48-d4db-787895b8df3e
* Version Independent ID: d37abcc6-f7f7-5752-7d24-28f17b5d78aa
* Content: [Asset library in Lifecycle Services (LCS) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/asset-library#asset-library-support)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/asset-library.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/lifecycle-services/asset-library.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @manalidongre
* Microsoft Alias: **manado**

**Comment by sericks007** [comment]
@ThomasZak, thanks for making us aware of this.

@manalidongre, please review and update the content, as needed.

**Comment by sericks007** [comment]
Bug 401968 has been logged to track this issue.
