### ISSUE TITLE
Consistency & clarity across related pages could be increased

### ISSUE THREAD

**Issue by leeds55** [MicrosoftDocs/dynamics-365-unified-operations-public#1896]
In this page, the "Prepare the PerfSDKSample solution for multi-user testing" step 4 doesn't provide the same level of detailed instruction to modify the "Test settings" as https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/perf-test/perfsdk-tutorial-lbd does.  In that tutorial, it's clearer that vsonline.testsettings is a solution file: "In your solution files, double-click the vsonline.testsettings file to modify the test settings."  If that guide was one of the pre-requisites for this one, I think the briefer description here would be reasonable, but as it is, consistency is probably desirable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa57e22a-a4d4-a433-8cf8-2e1257083a10
* Version Independent ID: 1251373f-3092-0825-cd85-ab49bbad9f71
* Content: [Multi-user testing with the Performance SDK and a local test controller - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/perf-test/multi-user-testing-local-test-controller#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/perf-test/multi-user-testing-local-test-controller.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/perf-test/multi-user-testing-local-test-controller.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @hasaid
* Microsoft Alias: **jujoh**

**Comment by josaw1** [comment]
Thank you for your suggestion. @hasaid, can you please take a look at this feedback?

**Comment by josaw1** [comment]
@hasaid updated the topic. Thanks.
