### ISSUE TITLE
The installation of SDP takes long time

### ISSUE THREAD

**Issue by diegoreza89** [MicrosoftDocs/dynamics-365-unified-operations-public#1899]
Hi, why in this new kind of architecture the installation of the SDP is too unstable? I mean, in some cases the installation takes 1 hour and minutes but in other cases takes unitl 7 or 8 hours!!

**Comment by josaw1** [comment]
Hi, this feedback is not associated with a particular topic. Please let us know which topic this refers to so we can further assist you. If you your comment refers to the product and not the documentation, please enter your feedback [here](https://experience.dynamics.com/ideas/). Thank you.
