### ISSUE TITLE
Upgrade-Banner inconsistency may be?

### ISSUE THREAD

**Issue by jaestevan** [MicrosoftDocs/dynamics-365-unified-operations-public#190]
Upgrade-Banner says "This feature is currently available by invitation only." but it's not clear the feature it is refering to. Also, it points to a survey that is not active anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afebec12-9838-906e-1c0a-a435b9be3777
* Version Independent ID: dec9bdde-ac60-4c13-72b5-b3709f6b7089
* Content: [Upgrade Dynamics AX 2012 to Dynamics 365 for Finance and Operations - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/upgrade-overview-2012#feedback)
* Content Source: [articles/dev-itpro/migration-upgrade/upgrade-overview-2012.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/migration-upgrade/upgrade-overview-2012.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @tariqbell
* Microsoft Alias: **tabell**

**Comment by MargoC** [comment]
Fixed, thanks!
