### ISSUE TITLE
Self-service Refresh database needs downtime ?

### ISSUE THREAD

**Issue by manishmoothedath** [MicrosoftDocs/dynamics-365-unified-operations-public#1901]
On a self service scenario, refresh from Production to a sandbox. Is it necessary to do this activity during downtime (non-business hours / No users are logged in to the system). Please clarify!!

-Manish

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d28e8cc-5110-f01b-db76-94479ec2fa91
* Version Independent ID: f0710707-9ff2-84a1-30c7-1f0d44e3a0d7
* Content: [Refresh database - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/database-refresh#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/database/database-refresh.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/database/database-refresh.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laneswenka**

**Comment by tonyafehr** [comment]
@manishmoothedath, thanks for contacting us. If you need immediate assistance consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 Community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.  

@laneswenka, please review this comment. Thanks!

**Comment by laneswenka** [comment]
Any action like database refresh will incur downtime as you are deleting the in-place database and bringing in a new copy.  Doing it off-hours is ideal if you have heavy load in your Sandbox environments during business hours.  You also can use the refresh API and something like LogicApps or Flow to schedule this to be hands-free.

**Comment by manishmoothedath** [comment]
> Any action like database refresh will incur downtime as you are deleting the in-place database and bringing in a new copy. Doing it off-hours is ideal if you have heavy load in your Sandbox environments during business hours. You also can use the refresh API and something like LogicApps or Flow to schedule this to be hands-free.

Hi,
I meant downtime in production environment (source) during a refresh to sandbox
