### ISSUE TITLE
Drawings Reference "AX" - Needs Update

### ISSUE THREAD

**Issue by aaronstackpole** [MicrosoftDocs/dynamics-365-unified-operations-public#1902]
New customers have no idea what "AX" is, and this is causing confusion as I'm delivering technical architecture overview workshops.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02e6cc89-39cd-5bbd-4574-b380d7787eef
* Version Independent ID: 9f7bb3e7-ba20-1856-2629-776e6d88487d
* Content: [Application stack and server architecture - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/application-stack-server-architecture#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/application-stack-server-architecture.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-tools/application-stack-server-architecture.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **meeram**

**Comment by RobinARH** [comment]
I updated the image and it will be published later today.
