### ISSUE TITLE
How to use the pre-and-post scripts feature

### ISSUE THREAD

**Issue by rabol** [MicrosoftDocs/dynamics-365-unified-operations-public#1903]
[Enter feedback here]

Some real examples on how to use would be nice
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74325503-4a6c-c662-7dc8-dbb8fe56d42d
* Version Independent ID: 4fb832ae-d59a-c615-90d6-a048424b04f1
* Content: [Local agent pre-deployment and post-deployment scripts - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/pre-post-scripts#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/pre-post-scripts.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/lifecycle-services/pre-post-scripts.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @faix
* Microsoft Alias: **osfaixat**

**Comment by tonyafehr** [comment]
@rabol, thanks for the feedback. 
@RobinARH, please review and assign to the appropriate content author.

**Comment by tonyafehr** [comment]
Reassigning to @faix

**Comment by faix** [comment]
Hi @rabol 
i'm not sure what your ask here is exactly...

We already have some scripts that are meant to be run as a predeployment script to solve some deployment issues: https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/onprem-tsg-implementations

If this is what you are looking for let me know and we will link the current page to the one i pasted above.

**Comment by rabol** [comment]
In the doc-post it is stated that one can use the PreDepoyment.ps1 scripts, but it is not clear how one makes a 'package' to include this scripts

**Comment by faix** [comment]
@rabol you don't need to create any package. As the documentation states you create a file called PreDeployment.ps1 and put whatever code you want there. You can also have the contents of the PreDeployment.ps1 script reference other scripts. You should then place the PreDeployment.ps1 script in the following location like the documentation already states: \\fileserver\agent\scripts\PreDeployment.ps1
