### ISSUE TITLE
Private preview survey

### ISSUE THREAD

**Issue by beefcake123** [MicrosoftDocs/dynamics-365-unified-operations-public#1904]
The private preview ended on Dec 31st 2018 according to the "complete the private preview survey" hyperlink. Is this feature and the documentation still accurate?
I had reached out to the contact person on 2019-10-01, but haven't heard back.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48aa991b-6ebf-f11c-f803-1baa0857cc90
* Version Independent ID: e20934b0-c4ff-0881-f45a-fd2cb957e469
* Content: [Database movement API - Reference - v1 - Overview - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/api/v1/dbmovement-api-v1-overview)
* Content Source: [articles/fin-ops-core/dev-itpro/database/api/v1/dbmovement-api-v1-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/database/api/v1/dbmovement-api-v1-overview.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by tonyafehr** [comment]
Thanks for contacting us. If you need immediate assistance, consider contacting Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community. 

@laneswenka, please address this feedback. Thank you!

**Comment by tonyafehr** [comment]
Bug 403507 has been logged to track this issue.

**Comment by laneswenka** [comment]
This is resolved, the private preview has completed and that verbiage has been removed since as well.
