### ISSUE TITLE
Import ISV License failed on-premises 

### ISSUE THREAD

**Issue by saadullahz** [MicrosoftDocs/dynamics-365-unified-operations-public#1905]
Importing our ISV license file failed on the on-premise UAT server.

Attached the error log details below.

C:\LS\UAT\Import-LicensePackage.ps1 : System.Management.Automation.RemoteException: 12/09/2019 01:38:28:

Microsoft.Dynamics.ApplicationPlatform.Environment.Settings.ConfigurationKeyNotFoundException: Failed to obtain app setting from for:

Common.IsOneboxEnvironment

At line:1 char:1

+ .\Import-LicensePackage.ps1

+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException

    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Import-LicensePackage.ps1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 367369e4-2f85-8a54-a07d-051377559c27
* Version Independent ID: dd172744-8482-e740-8376-bbf9be12167e
* Content: [Independent software vendor (ISV) licensing (on-premises) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/isv-licensing-on-prem)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/isv-licensing-on-prem.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-tools/isv-licensing-on-prem.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @manalidongre
* Microsoft Alias: **manado**

**Comment by tonyafehr** [comment]
Thanks for contacting us. Unfortunately, we do not handle Support requests here. Please contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

**Comment by arcria** [comment]
We were seeing the same error with Common.IsOneboxEnvironment when running the script from powershell directly. Ran the script from powershell ISE and it worked. It would be helpful if Microsoft could update their documentation as to what specific requirements are necessary for this script to run. Also the article mentions downtime, it would be helpful to have some information on what is happening in this import script so we don't have to dig through the .ps1 to figure it out. Lastly I'm sure people would appreciate showing an example section showing the syntax with parameters.
