### ISSUE TITLE
Which permission does the DevOps PAT need 

### ISSUE THREAD

**Issue by torbennehmer** [MicrosoftDocs/dynamics-365-unified-operations-public#1906]
Could you please describe in the documentation, which access permissions the DevOps PAT token needs?

https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/perf-test/rsat/rsat-install-configure#azure-devops-1

Best regards, Torben Nehmer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2458b41-99e9-53ff-b898-cdd957c1c924
* Version Independent ID: 9aad0fcb-b367-136a-9fb0-d8d04a2cfc33
* Content: [Regression suite automation tool installation and configuration - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/perf-test/rsat/rsat-install-configure)
* Content Source: [articles/fin-ops-core/dev-itpro/perf-test/rsat/rsat-install-configure.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/perf-test/rsat/rsat-install-configure.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @robadawy
* Microsoft Alias: **robadawy**

**Comment by tonyafehr** [comment]
@torbennehmer, thanks for the feedback. 
@robadawy, please review and consider updating this topic.

**Comment by tonyafehr** [comment]
Bug 403511 has been logged to track this issue.
