### ISSUE TITLE
Important info missing

### ISSUE THREAD

**Issue by mueckeflo** [MicrosoftDocs/dynamics-365-unified-operations-public#1907]
Hi!
It should be mentioned (and highlighted) that the dimensions SITE and WAREHOUSE are not supported pricing attributes by the retail pricing engine. Using those dimensions will cause incorrect pricing calculation as the prices using these dimensions are disregarded. Please correct me in case I'm wrong here.
Best regards,
Florian

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a36f4b4f-2673-c8ca-b245-8a17570f26eb
* Version Independent ID: e138c741-fec9-0d15-38db-e45c764f7b13
* Content: [Base price and trade agreements - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/retail/tasks/base-price-trade-agreements)
* Content Source: [articles/retail/tasks/base-price-trade-agreements.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/tasks/base-price-trade-agreements.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by tonyafehr** [comment]
@mueckeflo, thank you for the feedback. 
@josaw1, please review and assign to the appropriate content author.

**Comment by tonyafehr** [comment]
Bug 403513 has been logged to track this issue.

**Comment by tonyafehr** [comment]
This topic has been updated, thanks!
