### ISSUE TITLE
Incorrect information: CPOS only supports Shared HWS

### ISSUE THREAD

**Issue by woutermijle** [MicrosoftDocs/dynamics-365-unified-operations-public#1908]
The documenation states the following: 

> Modern POS uses hardware stations of the Dedicated type to detect that peripherals are directly connected to the computer where the app is being used. **However, the Dedicated type can also be used for IIS hardware stations. In a traditional, fixed POS scenario that uses Cloud POS as the POS application, the Dedicated hardware station type is used for IIS hardware stations that are deployed on the same computer that is running Cloud POS.** From a retail peripherals perspective, the dedicated IIS hardware station has better retail peripheral support for traditional, fixed POS scenarios. Dedicated hardware stations support all peripherals that are supported in the hardware profile.

However, it has been confirmed to me that **CPOS** only supports **shared HWS**. This is contradictory to what the documentation says...

**Comment by tonyafehr** [comment]
@woutermijle, this is great feedback, however it is not associated with a particular topic. Please let us know which topic this refers to so we can further assist you. Thank you.

**Comment by woutermijle** [comment]
Hi, it's related to "Hardware station deployment options": https://docs.microsoft.com/en-us/dynamics365/retail/retail-peripherals-overview#dedicated

**Comment by tonyafehr** [comment]
@rubencdelgado, please review and consider updating this topic.

**Comment by tonyafehr** [comment]
Bug 403514 has been logged to track this issue.
