### ISSUE TITLE
Please clarify how to get the SOAP hostname

### ISSUE THREAD

**Issue by torbennehmer** [MicrosoftDocs/dynamics-365-unified-operations-public#1909]
Please clarify, how to get the SOAP hostname. The given naming scheme didn't work for an UAT, where the actual prefix is like 
https://xxx-testaossoap.sandbox.operations.dynamics.com/
We got around to this value using the IIS console. I do not know, if there is a more precise naming scheme or if there is some place in lcs where you can look this up. If not, I'd recommend at least to refer to the IIS manager.

https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/perf-test/rsat/rsat-install-configure#test-environment-1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2458b41-99e9-53ff-b898-cdd957c1c924
* Version Independent ID: 9aad0fcb-b367-136a-9fb0-d8d04a2cfc33
* Content: [Regression suite automation tool installation and configuration - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/perf-test/rsat/rsat-install-configure#configuration)
* Content Source: [articles/fin-ops-core/dev-itpro/perf-test/rsat/rsat-install-configure.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/perf-test/rsat/rsat-install-configure.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @robadawy
* Microsoft Alias: **robadawy**

**Comment by tonyafehr** [comment]
@torbennehmer, thanks for the feedback. If you need immediate assistance, consider contacting Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community. 
@robadawy, please review and consider updating this topic.

**Comment by tonyafehr** [comment]
Bug 403515 has been logged to track this issue.

**Comment by kristyler** [comment]
Take the https:// out, both in the host name field and the soap host name field. They should look the same except for aossoap appended to the first section of the url in the soap field.
