### ISSUE TITLE
Microsoft Dynamics AX

### ISSUE THREAD

**Issue by kurthatlevik** [MicrosoftDocs/dynamics-365-unified-operations-public#1912]
Microsoft Dynamics AX is no longer the product name :-)  Please update texts to reflect this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42fe9dec-4097-a3f0-52f6-1236876b9f97
* Version Independent ID: 3bf7d15a-afa7-1049-4b88-1b1936638006
* Content: [License sizing estimator in Lifecycle Services (LCS) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/ax-2012/license-sizing-estimator-lcs#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/ax-2012/license-sizing-estimator-lcs.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/lifecycle-services/ax-2012/license-sizing-estimator-lcs.md)
* Service: ****
* Product: **dynamics-ax-2012**
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **kfend**

**Comment by sericks007** [comment]
@kurthatlevik, thanks for making us aware of this issue!

**Comment by sericks007** [comment]
The PM said that the License sizing estimator is a feature only available in LCS for AX 2012 projects. Our Content Publishing team is working to move this article from the Finance and Operations repo to the AX 2012 repo.

**Comment by sericks007** [comment]
This article has now been moved to the AX 2012 documentation.
