### ISSUE TITLE
Not all the paremeters are described in this page

### ISSUE THREAD

**Issue by pturegano** [MicrosoftDocs/dynamics-365-unified-operations-public#1913]
In PU28 we have found other parameter which is "Run in an offline mode" : When defragmentation is run offline for a particular index, underlying table and index are not available for queries and data modification.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee1ecd08-b417-33b6-46d9-9be22c92ed23
* Version Independent ID: 6082162f-3c1a-bce2-8f7a-c5b16223accd
* Content: [Batch job to handle SQL index defragmentation - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/batch-job-sql-defragmentation#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/batch-job-SQL-defragmentation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/sysadmin/batch-job-SQL-defragmentation.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @sericks
* Microsoft Alias: **ganas**

**Comment by sericks007** [comment]
@pturegano, thanks for making us aware of this.  I'll let the engineering manager know, so this content gets updated.

**Comment by sericks007** [comment]
Bug 406929 has been logged to track this issue.
