### ISSUE TITLE
Extension scenario implementation

### ISSUE THREAD

**Issue by simonefinotti** [MicrosoftDocs/dynamics-365-unified-operations-public#1914]
It would really help if the "Extension scenario" included some actual code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e6cfc5e-5f56-db68-24ff-7790edf508d2
* Version Independent ID: 7c04619f-f427-8769-1fe4-7a6101383477
* Content: [Extend table maps that are used as interfaces - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/extensibility/maps-as-interfaces#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/extensibility/maps-as-interfaces.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/extensibility/maps-as-interfaces.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @LarsBlaaberg
* Microsoft Alias: **lolsen**

**Comment by sericks007** [comment]
@simonefinotti, thank you for your feedback!

@LarsBlaaberg, please review and consider updating the content.

**Comment by sericks007** [comment]
Bug 406932 has been logged to track this issue.

**Comment by RobinARH** [comment]
We added a code example and it should go live tonight. -Robin
