### ISSUE TITLE
The storage account creation description has an error

### ISSUE THREAD

**Issue by andreash1** [MicrosoftDocs/dynamics-365-unified-operations-public#1923]
Hi, this section under "Create Storage accounts"

3. In the Advanced options dialog box, "turn off" the Data Lake storage Gen2 (preview) option.

should be changed to:

3. In the Advanced options dialog box, "enable" the Data Lake storage Gen2 (preview) option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a344a5de-68fa-e9cf-28eb-51269c33b9b3
* Version Independent ID: 1b3ede62-3954-574b-5778-8cdee0ededfe
* Content: [Make Entity store available as a Data Lake - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/entity-store-data-lake#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/entity-store-data-lake.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/entity-store-data-lake.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by cabeln** [comment]
Please explain better what the "root URL" refers to in App registration "Sign-on URL: Copy the root URL and paste it here." is tis AX root URL or of the storage account?

**Comment by cabeln** [comment]
It is the "DNS Name" of the key vault :-)
