### ISSUE TITLE
Error when logging in to the dev environment

### ISSUE THREAD

**Issue by danilo-AW** [MicrosoftDocs/dynamics-365-unified-operations-public#1925]
After doing the switch from dev to UAT database, I'm getting the following error:
You are not authorized to login with your current credentials. You will be redirected to the login page in a few seconds.
Any idea what it could be?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb08fb04-94d5-ef25-8162-a0d79f5ee70a
* Version Independent ID: 6d43b4b7-cc2e-49bc-564a-5eb5eacefa84
* Content: [Debug a copy of the production database - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/dbmovement-scenario-debugdiag)
* Content Source: [articles/fin-ops-core/dev-itpro/database/dbmovement-scenario-debugdiag.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/database/dbmovement-scenario-debugdiag.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laneswenka**

**Comment by maartendm** [comment]
My workaround is to disable/enable your user with another user account from the UAT environment.

**Comment by laneswenka** [comment]
This should not be required.  If it happens again, please file a support ticket and reference this docs article and request guidance from the 'Database Movement' team.  Thanks!

**Comment by feltrinf** [comment]
Please, take also care that the tenantId is the same in both dev and uat web.config file. In particular these two settings should coincide:
- Provisioning.AdminPrincipalName = the same value as in UAT sandbox
- Aad.AADTenantId = same value as in UAT sandbox
