### ISSUE TITLE
Endpoint for non-dev environment seems not correct

### ISSUE THREAD

**Issue by Julia341** [MicrosoftDocs/dynamics-365-unified-operations-public#1927]
Hi Team, please check whether the document needs to be updated as below:
Example endpoint for a non-dev environment
https://&lt;env-name&gt;aossoap.cloudax.dynamics.com/services/UserSessionService?wsdl

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b48cdcd6-bda2-2676-71b8-e0d51e5e746b
* Version Independent ID: 90adcd3c-b494-5e93-588c-8816dc0dbf79
* Content: [Custom service development - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/custom-services#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/custom-services.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/custom-services.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by tonyafehr** [comment]
@Julia341, thanks for the feedback. 
@Sunil-Garg, please review and consider making updates.

**Comment by tonyafehr** [comment]
Bug 407785 has been logged to track this issue.

**Comment by Julia341** [comment]
Thanks Tonya!

Thanks,
Julia

**Comment by Mzap89** [comment]
Hello everyone,

Do you know how to consume this services in a non-dev environment?

Thanks in advance.

**Comment by Sunil-Garg** [comment]
@julia341, the URL has been updated. Apologies for the confusion.
