### ISSUE TITLE
Incorrect procedure: Accessing Analytical Workspaces and Reports on 1-Box Environments

### ISSUE THREAD

**Issue by BasvGMRN** [MicrosoftDocs/dynamics-365-unified-operations-public#1929]
"Note
The analytical workspaces require a hosted Power BI service that is available only for dedicated environments. For more information, see the blog post, Accessing Analytical Workspaces and Reports on 1-Box Environments." 

The link points to a procedure that describes how to access the analytical workspaces on 1box environments - however this does no longer seem to work. Please update the note with a link to an alternative procedure. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49d529c3-f749-dcc9-deee-7143897f6503
* Version Independent ID: beb39e19-22e6-cc8f-638f-8db05f9ad508
* Content: [Select analytical workspaces from PowerBI.com - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/select-analytical-workspace)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/select-analytical-workspace.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/select-analytical-workspace.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by tonyafehr** [comment]
Thanks for the feedback. 
@TJVass, please review and update this topic.

**Comment by BasvGMRN** [comment]
Please ignore my earlier feedback - it is incorrect - the procedure does work for 1Box deployments.

**Comment by BasvGMRN** [comment]
Please ignore my earlier feedback.
The procedure that was linked to does work correctly – I made a mistake during the configuration.

Please accept my apologies for my incorrect feedback and any inconvenience this may have caused.

Kind regards,
Bas
