### ISSUE TITLE
Split Retail Channel Database & Retail Server

### ISSUE THREAD

**Issue by NicholasFook79** [MicrosoftDocs/dynamics-365-unified-operations-public#1930]
Hi,

  I would like to confirm if Retail Channel DB & Retail Server can be split and hosted separately. Please advise. 

Thank you.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 915a525f-f660-5cb2-fa18-be1a059acdbb
* Version Independent ID: 61eca697-a18c-f7a5-cc53-8331dcf3ff64
* Content: [Configure and install Retail Store Scale Unit - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/retail/dev-itpro/retail-store-scale-unit-configuration-installation)
* Content Source: [articles/retail/dev-itpro/retail-store-scale-unit-configuration-installation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/dev-itpro/retail-store-scale-unit-configuration-installation.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @jashanno
* Microsoft Alias: **jashanno**

**Comment by josaw1** [comment]
Thank you for your question. @jashanno can you please help?

**Comment by josaw1** [comment]
Bug 408805 created to track the issue.

**Comment by jashanno** [comment]
Hi @NicholasFook79 

Yes, the Retail channel DB (With Async client) can be installed separately from the Retail Server (With Retail Cloud POS, as needed).  The details on how to perform this are in this document under the Multiple-computer installation sub-heading.
