### ISSUE TITLE
Local Agent version 2.4.0 update deployment issues

### ISSUE THREAD

**Issue by MadhanRamachandran** [MicrosoftDocs/dynamics-365-unified-operations-public#1937]
[Enter feedback heAfter I have upgraded the agent 2.4.0 version and installed the .net 4.8 in ORCH then  started the deployment I am getting the error in clean up step.
 
Not able contuine the deployment . Please provide the suggestions .
 
Module aos failed with  error code 255.      
Detail at  System.Environment.GetStackTrace(Exception e, Boolean needFileInfo) at  System.Environment.get_StackTrace() at  Microsoft.Dynamics.Operations.Local.LocalAgentEvents.LocalAgentEventHelpers.ErrorPrettify(LocalAgentEventSource  source, Exception ex, Int32 errorCode, String format, Object[] values) at  SetupCore.SetupManager.<>c__DisplayClass12_1.<InvokeModules>b__6()  at System.Threading.Tasks.Task.Execute() at  System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext,  ContextCallback callback, Object state, Boolean preserveSyncCtx) at  System.Threading.ExecutionContext.Run(ExecutionContext executionContext,  ContextCallback callback, Object state, Boolean preserveSyncCtx) at  System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot) at  System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution) at  System.Threading.ThreadPoolWorkQueue.Dispatch()
 
Message Task  OrchestrationService.CleanupModulesRunnerTask,OrchestrationService failed for  command id 55936841-2b09-45e0-a614-735129c17b44     
 
Detail LocalAgentCommon.LocalAgentInvalidOperationException:  Unable to cleanup modules at  OrchestrationService.CleanupModulesRunnerTask.Run(OrchestratorRunbookResource  runbookResource, String commandId, String jobId, String runbookTaskId) at  OrchestrationService.OrchestrationJobManager.<>c__DisplayClass23_0.<CreateNewTaskThread>b__4()re]

**Comment by sericks007** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
