### ISSUE TITLE
Error in code sample

### ISSUE THREAD

**Issue by PalleAgermark** [MicrosoftDocs/dynamics-365-unified-operations-public#194]
You cannot call MessageSeverity::Info. You need to call MessageSeverity::Informational

This is the existing sample:
messageId = Message::Add(MessageSeverity::Info, "The customer is marked as inactive");

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e325214-7a60-da73-83e8-afc99e3818cc
* Version Independent ID: 08142e34-ff0f-e5b2-8989-d056f8fc1538
* Content: [Message center, message bar, and message details FAQ - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/user-interface/messaging-user)
* Content Source: [articles/dev-itpro/user-interface/messaging-user.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/user-interface/messaging-user.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RobinARH
* Microsoft Alias: **tlefor**

**Comment by jasongre** [comment]
Thanks for catching this! We'll get this updated.
