### ISSUE TITLE
Nice One!

### ISSUE THREAD

**Issue by goyalsachingithub** [MicrosoftDocs/dynamics-365-unified-operations-public#1943]
Good one to understand the new changes  in x++.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1bbc2c7-22f5-3b21-978c-4ed5867e400c
* Version Independent ID: 7d53e2be-80a2-e576-31c0-447fb947a568
* Content: [Changes in X++ and the X++ compiler](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/programming-language-support?source=docs#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/programming-language-support.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-tools/programming-language-support.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @pvillads
* Microsoft Alias: **pvillads**

**Comment by sericks007** [comment]
Thank you for your feedback! We appreciate it!
