### ISSUE TITLE
Validation of alpha values

### ISSUE THREAD

**Issue by kristyler** [MicrosoftDocs/dynamics-365-unified-operations-public#1945]
Does this work for alpha values? It's failing for me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84480f6c-693c-f9dc-f518-40327bee20f0
* Version Independent ID: 3544a89a-79ef-2467-d787-9ed717faeeb1
* Content: [Validate expected values](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/perf-test/rsat/rsat-validate-expected#validate-expected-values-using-operators)
* Content Source: [articles/fin-ops-core/dev-itpro/perf-test/rsat/rsat-validate-expected.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/perf-test/rsat/rsat-validate-expected.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @robadawy
* Microsoft Alias: **robadawy**

**Comment by kristyler** [comment]
<Message>The operator '&gt;' is not recoginized for comparison operations</Message>

( That's how it's spelled in the error details.)

**Comment by sericks007** [comment]
@kristyler, thanks for posting here.

@robadawy, please review and update the content, as necessary.

**Comment by sericks007** [comment]
Bug 408194 has been logged to track this issue.
