### ISSUE TITLE
 [Hookable(false)] vs [Wrappable(false)]

### ISSUE THREAD

**Issue by nagarazt** [MicrosoftDocs/dynamics-365-unified-operations-public#1946]
Is there any difference between  [Hookable(false)] and [Wrappable(false)]?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4317fdb2-b37f-550d-f229-bfd8498ab073
* Version Independent ID: ecd0974c-0abc-c494-cc8c-e81e7cf096f9
* Content: [Class extension - Method wrapping and Chain of Command](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/extensibility/method-wrapping-coc#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/extensibility/method-wrapping-coc.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/extensibility/method-wrapping-coc.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @ChrisGarty
* Microsoft Alias: **cgarty**

**Comment by sericks007** [comment]
@nagarazt, thanks for posting here! You might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community. 

@ChrisGarty, please review and update the content, as necessary.

**Comment by sericks007** [comment]
Bug 408197 has been logged to track this issue.

**Comment by irfan007-coder** [comment]
[HookableAttribute(false)] is default attribute attached with methods. it's mean that you cannot extend that method either method is public or protected. 
if a method has final modifier it's means that you cannot extend it but it's a option to override that functionality by using [Wrappable(true)] attribute .
You can override final method by using  [Wrappable(true)] and [Wrappable(false)]

**Comment by nagarazt** [comment]
Thanks Irfan. I understood the concept of both Hookable vs Wrappable. But [HookableAttribute(false)] and [Wrappable(false)] both we use for the normal public or protected methods not on final methods to avoid the extensible option. My question is if both are working in similar way why do we have two properties.  I feel Hookable is deprecated concept. Correct me if I am wrong.

**Comment by jorisdg** [comment]
I will review the doc with the team as I agree it's not clear.

Hookable(false) disallows pre/post handlers and CoC. Wrappable(false) only disallows CoC (still allows handlers).

Hookable(true) can be used to allow pre/post handlers on final or protected methods (default is only on non-final public).
Wrappable(true) can be used to allow CoC on final methods (protected or public, private methods can never be wrapped).

**Comment by RobinARH** [comment]
Joris updated the doc and the new info should go live tonight.
