### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by Huremix** [MicrosoftDocs/dynamics-365-unified-operations-public#1947]
dp.exe import \\location_of_demo_data \\Name_of_AX_business_database \\ServernameInstanceName.

dp.exe import "C:\MicrosoftDynamicsAXR3DemoData" CONTOSO DBSRV\MSSQLSRV_2016

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec31ca57-d96e-3fb8-9b2a-4c454f989f27
* Version Independent ID: 9d676dd2-4f78-da3a-603c-f5f96cd394ce
* Content: [Import demo data for AX 2012 R3 by using the Test Data Transfer Tool](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/ax-2012/import-demo-data-ax-2012-r3-test-data-transfer-tool#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/ax-2012/import-demo-data-ax-2012-r3-test-data-transfer-tool.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/lifecycle-services/ax-2012/import-demo-data-ax-2012-r3-test-data-transfer-tool.md)
* Service: ****
* Product: **dynamics-ax-2012**
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **kfend**

**Comment by sericks007** [comment]
@Huremix, thanks for posting here. We appreciate your feedback!
