### ISSUE TITLE
spelling mistake

### ISSUE THREAD

**Issue by huzaima** [MicrosoftDocs/dynamics-365-unified-operations-public#195]
Current: When you **compete** the wizard, it produces the following two items

It should be: When you **complete** the wizard, it produces the following two items:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5e2729b-116a-728c-1166-3c1a0cba9921
* Version Independent ID: 7c745e05-b5f4-40b6-65e1-395deeb17f1b
* Content: [Data entities - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/data-entities?toc=/fin-and-ops/toc.json#output)
* Content Source: [articles/dev-itpro/data-entities/data-entities.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/data-entities.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by huzaima** [comment]
Done via pull request 196.

**Comment by kfend** [comment]
Fixed.
