### ISSUE TITLE
update release schedule

### ISSUE THREAD

**Issue by subglo** [MicrosoftDocs/dynamics-365-unified-operations-public#1955]
Hi,
It's already January 2nd 2020 - today. 
Could You please update upcoming Platform update release schedule a bit further then March 13, 2020? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7dcb285-f32c-c92e-fe49-1617f213066b
* Version Independent ID: 8f28c1a0-9da5-f853-90ee-d82a4c32df7e
* Content: [Service update availability](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/public-preview-releases?source=docs#feedback)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/public-preview-releases.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/get-started/public-preview-releases.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @meeramahabala
* Microsoft Alias: **meeram**

**Comment by sericks007** [comment]
@subglo, thanks for posting here.

@ShellyBakke, please consider updating the content, as requested.

**Comment by sericks007** [comment]
Bug 408200 has been logged to track this issue.

**Comment by varunv16** [comment]
Any updates on these? There's no relase guideline past 10.0.9 which is supposed to come out in 9 days.

**Comment by curtiswatson** [comment]
Where's the release notes for v10.0.8 - which is already GA?

**Comment by sericks007** [comment]
Closing, as this content has been updated.
