### ISSUE TITLE
Two undocumented JobDefinition modes: ImportInBatch and ExportInBatch

### ISSUE THREAD

**Issue by swidz** [MicrosoftDocs/dynamics-365-unified-operations-public#1959]
There are two additional job definition modes: "ImportInBatch" "ExportInBatch" this will trigger Import or Export in Batch mode without setting any recurring integration schedules. Also other batch reccuring options do not apply. This work the same way as "Import async" and "Export async" but is not run in user session but in batch job instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf51a7e8-9ae4-5b55-c61c-2dc31abe6621
* Version Independent ID: 934ab5eb-0b75-c8de-a76d-efd2ded27609
* Content: [Data task automation](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/data-task-automation#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/data-task-automation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/data-task-automation.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by sericks007** [comment]
@swidz, thanks for posting here!

@Sunil-Garg, please review and update the content, as needed.

**Comment by sericks007** [comment]
Bug 408205 has been logged to track this issue.
