### ISSUE TITLE
8+ versions

### ISSUE THREAD

**Issue by OksanaKovaliova** [MicrosoftDocs/dynamics-365-unified-operations-public#1961]
Is this article valid for environment versions later than 8+? Tried to search in LCS - but returns no results

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d6f1ae2-5ee6-e87d-e09a-3d2652794086
* Version Independent ID: c4fb4871-22b6-b312-745d-f93ade86a436
* Content: [Known issues](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/known-issues#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/known-issues.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/lifecycle-services/known-issues.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @sericks007
* Microsoft Alias: **sericks**

**Comment by sericks007** [comment]
@OksanaKovaliova, thanks for posting here!

@josaw1, can you please answer this question.

**Comment by sericks007** [comment]
Bug 408207 has been logged to track this issue.

**Comment by ShylaThompson** [comment]
@OksanaKovaliova , no this article does not apply to versions greater than 8+. All issues for versions later than 8+ are documented in LCS issue search. I suggest searching for the Application or Platform version to find issues reported for that release (E.g. 10.0.7 or Platform Update 31). Some issues will be fixed, others in progress, and some might have been reviewed by Microsoft and we decided not to fix them.
