### ISSUE TITLE
Getting error "At least one security token in the message could not be validated"

### ISSUE THREAD

**Issue by prdpmv** [MicrosoftDocs/dynamics-365-unified-operations-public#1964]
Getting error "At least one security token in the message could not be validated". 
https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/perf-test/troubleshoot-perf-sdk-user-testing#at-least-one-security-token-in-the-message-could-not-be-validated

In this page there is no where certificate creation step is mentioned. I saw it mentioned in on-prem environment testing. https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/perf-test/perfsdk-tutorial-lbd

Is that applicable for cloud environment too? Can you please update the missing steps?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34add537-f522-ea26-18c9-c0df5f6e166c
* Version Independent ID: a0c4d5a9-d424-806a-51c0-099f08bbde71
* Content: [Single-user testing with Task recorder and the Performance SDK](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/perf-test/single-user-test-perf-sdk#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/perf-test/single-user-test-perf-sdk.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/perf-test/single-user-test-perf-sdk.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @hasaid
* Microsoft Alias: **jujoh**

**Comment by tonyafehr** [comment]
@prdpmv, thanks for the comment. If you need immediate assistance, please contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community. 


@hasaid, please review this feedback and make updates as needed.

**Comment by hasaid** [comment]
Please check that you have a 127.0.0.1 cert on your client/Dev box and make sure the thumbprint is configured on the AOS’s wif.config  then restarted and in the key SelfSigningCertificateThumbprint located in your CloudEnvironment.config in your Perfsdklocaldirectory folder

**Comment by prdpmv** [comment]
Do I need to follow step 4 to 7 from https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/perf-test/perfsdk-tutorial-lbd#run-a-single-user-test-by-using-the-performance-sdk
to do what you have mentioned below? 

I have already done changes to CloudEnvironment.config which is mentioned in current page.

> Please check that you have a 127.0.0.1 cert on your client/Dev box and make sure the thumbprint is configured on the AOS’s wif.config then restarted and in the key SelfSigningCertificateThumbprint located in your CloudEnvironment.config in your Perfsdklocaldirectory folder

**Comment by hasaid** [comment]
You can but it is not required.

You should have on your client 2 x 127.0.0.1 if you installed a new cert. make sure you take the thumbprint of the one you installed
