### ISSUE TITLE
STAR OPOS logo printing and Microsoft-tested devices

### ISSUE THREAD

**Issue by sukkal63** [MicrosoftDocs/dynamics-365-unified-operations-public#1968]
Please adjust the information related to the Star Printers and the OPOS drivers (maybe include a comment or something else), as they support PrintBitmap, whereas MPOS has only ever supported PrintMemoryBitmap. The difference is that their OPOS drivers require that the logo be set when we initialize the printer using ‘oposPrinter.setBitmap’. MPOS uses the newer ‘oposPrinter.printMemoryBitmap’ which passes along the file at the time of making the printing request, rather than loading into memory.

Additionally, please do note if the Tested peripherals are Recommended, as many people base their decisions on this article and specially on the "Microsoft-tested peripheral devices" list, as it seems they are proven to work Out-Of-The-Box. It is worth to mention somewhere if these tested scenarios fall under the "supported by Microsoft" scenarios.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a23ac4f5-a8fd-ce83-2f3e-0912d95579d9
* Version Independent ID: 5a3bae91-72db-0e45-cd9b-2f68819fd148
* Content: [Retail peripherals](https://docs.microsoft.com/en-us/dynamics365/retail/retail-peripherals-overview#feedback)
* Content Source: [articles/retail/retail-peripherals-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/retail-peripherals-overview.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @rubencdelgado
* Microsoft Alias: **rubendel**

**Comment by sericks007** [comment]
@sukkal63, thanks for posting here.

@rubencdelgado, please review and update the content, as needed.

**Comment by sericks007** [comment]
Bug 410629 has been logged to track this issue.

**Comment by rubencdelgado** [comment]
addressed in PR and assigned bug to Sally to close.

**Comment by josaw1** [comment]
The updates to the topic will be published today. Thanks.
