### ISSUE TITLE
This page needs an update on batch throttling

### ISSUE THREAD

**Issue by gertvdh** [MicrosoftDocs/dynamics-365-unified-operations-public#1969]
now a batch server has batch throttling enabled by default so that you cannot 'overcommit' threads

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6465b985-b976-a032-6f05-e540ef844f30
* Version Independent ID: d13d8e4c-36cd-21ea-1113-99774093458f
* Content: [Batch processing and batch servers](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/batch-server-overview)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/batch-server-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/sysadmin/batch-server-overview.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @maertenm
* Microsoft Alias: **maertenm**

**Comment by ParAkerblom** [comment]
Need input from my team. I have reached out.

**Comment by josaw1** [comment]
BUG 411397 created to track this issue.

**Comment by karimelazzouni** [comment]
@josaw1 @gertvdh issue has been addressed in #2010
