### ISSUE TITLE
Broken link (?)

### ISSUE THREAD

**Issue by Amakyusa** [MicrosoftDocs/dynamics-365-unified-operations-public#197]
The link in the section "Analyze" on "how to get the LCS trial Project for Customers" is not working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afebec12-9838-906e-1c0a-a435b9be3777
* Version Independent ID: dec9bdde-ac60-4c13-72b5-b3709f6b7089
* Content: [Upgrade Dynamics AX 2012 to Dynamics 365 for Finance and Operations - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/upgrade-overview-2012)
* Content Source: [articles/dev-itpro/migration-upgrade/upgrade-overview-2012.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/migration-upgrade/upgrade-overview-2012.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @tariqbell
* Microsoft Alias: **tabell**

**Comment by weaveriski** [comment]
This link is still broken, any update?

**Comment by robadawy** [comment]
Please change
https://diag.lcs.dynamics.com/ UpgradeAnalysisReport/Report/
to 
https://diag.lcs.dynamics.com/ UpgradeAnalysisReport/Report/<ProjectID>

<ProjectID> is missing.

**Comment by ShylaThompson** [comment]
@robadawy , the two links that you mention above are exactly the same. Can you confirm the change that you are suggesting for the topic?

**Comment by ShylaThompson** [comment]
@Amakyusa Here is the right link: https://go.microsoft.com/fwlink/?LinkId=2017742&clcid=0x409 . The topic will be fixed within the week.
