### ISSUE TITLE
Batch priority-based scheduling

### ISSUE THREAD

**Issue by gertvdh** [MicrosoftDocs/dynamics-365-unified-operations-public#1970]
since PU31 this is a feature, so it should be somewhere here too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6465b985-b976-a032-6f05-e540ef844f30
* Version Independent ID: d13d8e4c-36cd-21ea-1113-99774093458f
* Content: [Batch processing and batch servers](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/batch-server-overview)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/batch-server-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/sysadmin/batch-server-overview.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @maertenm
* Microsoft Alias: **maertenm**

**Comment by josaw1** [comment]
Thank you for your feedback. @Peakerbl can you please take a look at this?

**Comment by ParAkerblom** [comment]
Priority-based batch scheduling is still in private preview only, the content is available once the feature appears in Feature management. [](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/priority-based-batch-scheduling). We will update the section once this feature is GA and/or enabled by default.

**Comment by ParAkerblom** [comment]
https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/priority-based-batch-scheduling
