### ISSUE TITLE
MPN gold and silver incidents do not support LCS

### ISSUE THREAD

**Issue by AndrewCussons** [MicrosoftDocs/dynamics-365-unified-operations-public#1972]
MPN gold and silver incidents are for on-premises products only. Therefore, they should not be used for Cloud products such as Dynamics 365, Azure etc

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8710098e-7f1d-d216-83c2-b513753c969d
* Version Independent ID: 64e1a812-a65f-6d3e-a902-5e1cce22bc3e
* Content: [Manage the support experiences for Finance and Operations apps](https://docs.microsoft.com/en-gb/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/cloud-powered-support-lcs#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/cloud-powered-support-lcs.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/lifecycle-services/cloud-powered-support-lcs.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **anupams**

**Comment by josaw1** [comment]
Thank you for your feedback. @kfend can you please take a look?

**Comment by josaw1** [comment]
@AnupamMicrosoft

**Comment by josaw1** [comment]
@sericks007 BUG 411415 assigned to you. Can you help resolve this?

**Comment by sericks007** [comment]
I reviewed this content with a support engineer.  He said MPN can used, if applicable. LCS handles not only online, but on-premises, as well.
