### ISSUE TITLE
Unable to find 'POS search criteria' tab on Retail parameters form

### ISSUE THREAD

**Issue by asifbhimla** [MicrosoftDocs/dynamics-365-unified-operations-public#198]
I cannot find this tab page on Retail Parameter form. I checked this on the latest release (PU15 and 8.0). Is there a configuration that enables this tab  page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f39d23d-e79e-1f6d-b46b-20bc9e63df10
* Version Independent ID: d34fbe29-5c79-f3ea-1d0a-7900fd07e4db
* Content: [Product search and customer search in POS - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/pos-search-improvements)
* Content Source: [articles/retail/POS-search-improvements.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/POS-search-improvements.md)
* Service: **dynamics-365-retail**
* GitHub Login: @ShalabhjainMSFT
* Microsoft Alias: **shajain**

**Comment by ShalabhjainMSFT** [comment]
This feature will be a part of Dynamics 365 for Retail 7.3.3 and Dynamics 465 for Retail 8.0.1.

**Comment by PrudhviTummala** [comment]
The logic for Search all stores is incorrect-- It shouldn't return all parties i.e. Employees, Customers, Vendors & competitors.

It should only display parties associated with Customers  - Should this be logged as a bug?

**Comment by ShalabhjainMSFT** [comment]
The current implementation assumes that your employees, vendors, competitors etc. all can also be your customers and thus the remote search returns all parties which have a address book associated to them. If the ask is to restrict the remote search to only return the parties which are associated to the customer address book, then this will be treated as a design change request. In the mean time, a retailer can easily create a custom Customer search shortcut using the "POS search criteria" tab e.g. create a shortcut as 'Full name' and implement the search logic to return customers which are associated to the desired address book.
