### ISSUE TITLE
Dynamics 365 Finance

### ISSUE THREAD

**Issue by Den82spb** [MicrosoftDocs/dynamics-365-unified-operations-public#1981]
Dynamics 365 Finance and operations?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1fb1df0-9c03-99c0-fd65-e1014fb36176
* Version Independent ID: 0ab0746a-8c93-e3c4-1b50-a162ae09fb5f
* Content: [Database Movement API](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/api/dbmovement-api-overview)
* Content Source: [articles/fin-ops-core/dev-itpro/database/api/dbmovement-api-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/database/api/dbmovement-api-overview.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by tonyafehr** [comment]
@Den82spb, if you are inquiring about what apps are supported, keep in mind that Dynamics 365 for Finance and Operations is now being licensed as Dynamics 365 Finance and Dynamics 365 Supply Chain Management, which is noted in this topic.
