### ISSUE TITLE
include a sample on "Create a plan guide to add table hints" for hints parameter

### ISSUE THREAD

**Issue by gertvdh** [MicrosoftDocs/dynamics-365-unified-operations-public#1982]
we had some problems to find out what to use here as parameter, so including a bit of samples would help:
for example "OPTION(TABLE HINT(&lt;tablealias&gt;,INDEX(&lt;indexname&gt;)))"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b75b1a49-8365-0fc4-5c27-677ff4b26325
* Version Independent ID: 98fcce36-1717-a210-0bb6-5c7f48bdf36f
* Content: [Query cookbook](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/querycookbook#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/querycookbook.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/lifecycle-services/querycookbook.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @manalidongre
* Microsoft Alias: **manado**

**Comment by tonyafehr** [comment]
@gertvdh, thanks for the feedback. 
@manalidongre, please review and consider including samples as suggested.
