### ISSUE TITLE
baseURI value

### ISSUE THREAD

**Issue by mores** [MicrosoftDocs/dynamics-365-unified-operations-public#1983]
Where do you get the baseURI from ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 133cc363-a550-5cbf-622a-f0bd3da87eb6
* Version Independent ID: a7b1ce5d-ba20-b723-e3b0-23a9b79cde9d
* Content: [Service endpoints overview](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/services-home-page)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/services-home-page.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/services-home-page.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by tonyafehr** [comment]
@Sunil-Garg, please review. Thanks!

**Comment by bhesingh** [comment]
BaseURI is the URL of your Dynamics 365 F&O instance. Copy it from the browser address pane until cloudax.dynamics.com

**Comment by tonyafehr** [comment]
Bug 411973  has been logged to track this issue.
