### ISSUE TITLE
Wrong description of parameters for ExportToPackage action

### ISSUE THREAD

**Issue by TorbenPhilippsen** [MicrosoftDocs/dynamics-365-unified-operations-public#1984]
In the parameters C# sample section of ExportToPackage action it says:
"definitionGroupId":"&lt;Data project Id&gt;",
This is not correct. It should be:
"definitionGroupId":"&lt;Data project NAME&gt;",

In the parameters section it says:
string legalEntityId	- The legal entity for the data import.
this is not correct. It should be:
string legalEntityId	The legal entity for the data EXPORT.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d963d4c-de1f-7730-bee2-016dcde40907
* Version Independent ID: 21b95d43-5ad9-0ffc-21b9-6a4ba9086a56
* Content: [Data management package REST API](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/data-management-api#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/data-management-api.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/data-management-api.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by tonyafehr** [comment]
@Sunil-Garg, please review. Thanks!

**Comment by tonyafehr** [comment]
Bug 411975 has been logged to track this issue.

**Comment by Sunil-Garg** [comment]
Thanks, the update has been submitted.
