### ISSUE TITLE
Update settings not available

### ISSUE THREAD

**Issue by FH-Inway** [MicrosoftDocs/dynamics-365-unified-operations-public#1986]
I suggest an info is added to the "What's new or changed" part that the update settings in the LCS project settings is not available. According to Microsoft support, automatic updates are not available with self service environments.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c7f272b-4ea7-a285-4a9f-e67583a664e0
* Version Independent ID: 54ac0c3d-a2b5-6001-1581-167dd87a80c0
* Content: [Self-service deployment overview](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/infrastructure-stack#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/infrastructure-stack.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/deployment/infrastructure-stack.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @sarvanisathish
* Microsoft Alias: **sarvanis**

**Comment by tonyafehr** [comment]
@FH-Inway, thanks for the suggestion. 
@sarvanisathish, please consider making updates as noted.

**Comment by tonyafehr** [comment]
Bug 6089723 has been logged to track this issue.

**Comment by Angelos102** [comment]
Please reviews this, as I can see this is now available and no longer an issue

**Comment by FH-Inway** [comment]
@Angelos102 If update settings are now available for all LCS projects with self service environments, then this issue can be closed.
