### ISSUE TITLE
In the application, go to System administration > Setup > Azure Active Directory applications.

### ISSUE THREAD

**Issue by mores** [MicrosoftDocs/dynamics-365-unified-operations-public#1987]
Is the "application" referring to Finance and Operations website ?
After I go to "System administration" I do not see Setup - I do see:
Manage users
Security configuration
Lifecycle Services
Failed batch jobs
System settings
Data Management IT

Currently unable to 'Register your external application'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 133cc363-a550-5cbf-622a-f0bd3da87eb6
* Version Independent ID: a7b1ce5d-ba20-b723-e3b0-23a9b79cde9d
* Content: [Service endpoints overview](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/services-home-page)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/services-home-page.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/services-home-page.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by tonyafehr** [comment]
@mores, thanks for contacting us. If you need immediate assistance consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 Community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.  

@Sunil-Garg, please review this comment. Thanks!

**Comment by mores** [comment]
The root of the problem is that there are multiple "System administration" options -
On the home page there is a tile called "System administration" <- this is the wrong one !
![image](https://user-images.githubusercontent.com/1318377/72380328-31406000-36e3-11ea-91fe-8ff2d0b5b9cc.png)
Hamburger menu -> Modules -> "System Administration" <- this is the correct one !
![image](https://user-images.githubusercontent.com/1318377/72380473-7a90af80-36e3-11ea-9e74-39c19da3e28c.png)

**Comment by tonyafehr** [comment]
Bug 411977 has been logged to track this issue.

**Comment by Sunil-Garg** [comment]
@mores  you are right that, it is the module and not the workspace. The first step is now updated to clarify that its the module. Thanks.
