### ISSUE TITLE
Is the drill into detail to F&O works for Power BI report pin from PowerBI.com

### ISSUE THREAD

**Issue by axaeffect** [MicrosoftDocs/dynamics-365-unified-operations-public#1988]
As subject, if we pin report from PowerBI.com, are the drill report still works ? Also is there any document provided specific to FO on how to develop the menu item and everything like mentioned in part :
1. Help secure access to Power BI reports by using menu items. 
2. Filter reports based on application context

I mean really specific for F&O, not the generic that can use by any platform.
Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 630034c6-dbcc-d365-d58b-36bef4277582
* Version Independent ID: ce5941a7-67bb-9c0a-c1ab-230fe8aff69f
* Content: [Power BI Embedded integration](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/power-bi-embedded-integration?toc=%2Ffin-and-ops%2Ftoc.json)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/power-bi-embedded-integration.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/power-bi-embedded-integration.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by sericks007** [comment]
@axaeffect, thanks for posting here.  If you need to contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community. 

@TJVass, please review and answer the questions that were asked.

**Comment by sericks007** [comment]
Bug 412352 has been logged to track this issue.
