### ISSUE TITLE
What needs to be checked in?

### ISSUE THREAD

**Issue by torbennehmer** [MicrosoftDocs/dynamics-365-unified-operations-public#1989]
Hi there,

what I am missing in the documentation is what parts of a package actually needs to be checked in. This is defined for 3rd party packages in the docs, but it is missing for source package (or I'm too blind to find it). For myself, it is quite clear what I need. Alongside with the .gitignore/.tfignore I have written, there is no problem for me personally. However, I find it would be good to have a description on what to check in within the docs explicitly, including exceptions like binary dependencies (3rd party .net DLLs in use by your package, for example).

Best regards,
Torben Nehmer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71438101-e8d0-6636-a397-64b039c85a39
* Version Independent ID: 9db6265c-437c-75d2-be92-131273a8ca56
* Content: [Create models and data model elements overview](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/create-data-model-elements)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/create-data-model-elements.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-tools/create-data-model-elements.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **robadawy**

**Comment by sericks007** [comment]
@torbennehmer, thanks for posting here!

@robadawy, please review and update the content, if needed.

**Comment by sericks007** [comment]
Bug 412353 has been logged to track this issue.

**Comment by jorisdg** [comment]
We will consider adding this in the future. Currently we don't support Git officially, and other than the odd descriptor XML file missing customers have not had issues using the built-in TFVC source control support.
Once we get to Git we will have a standard gitignore file, we can consider then documenting also what should go in.
As far as checking in third-party DLLs, if you need those deployed you actually do need those in source control anyway or they won't be packaged up.
