### ISSUE TITLE
Is this document updated

### ISSUE THREAD

**Issue by axaeffect** [MicrosoftDocs/dynamics-365-unified-operations-public#1990]
I would like to know is this document updated. Provided there is the new Power BI Embedded service which has Dedicated Capacity stuff.

Is the code still applicable for Power BI Embedded service ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58543120-6ce0-15a0-dd0a-ca4888b11d85
* Version Independent ID: 4e804992-b8bd-e312-eb85-da4b25f9d3cd
* Content: [Add analytics to workspaces by using Power BI Embedded](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/add-analytics-tab-workspaces?toc=%2Ffin-and-ops%2Ftoc.json)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/add-analytics-tab-workspaces.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/add-analytics-tab-workspaces.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by sericks007** [comment]
@axaeffect, thanks for posting here.

@TJVass, please review and update the content, as necessary.

**Comment by sericks007** [comment]
Bug 412356 has been logged to track this issue.
