### ISSUE TITLE
 How can you submit a support request with out a premier support plan ?

### ISSUE THREAD

**Issue by AndrewCussons** [MicrosoftDocs/dynamics-365-unified-operations-public#1992]
I look at "Use the Cloud-powered support tool." above and it says "On the Active issue tab, select your issue, and then click Submit to Microsoft.".
But "! Submit to Microsoft" is greyed out
The other option On the Submitted to Microsoft tab requires a premier support contract

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32debc65-d382-465c-f0fd-a1aa5a7f9d48
* Version Independent ID: 31eb7664-5472-4fee-db0f-ac63ee2ca3ac
* Content: [Get support for Finance and Operations apps or Lifecycle Services (LCS)](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/lcs-support)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/lcs-support.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/lifecycle-services/lcs-support.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **anupams**

**Comment by AndrewCussons** [comment]
workitems Support issues and the Active issues tab do not display any buttons / icons to strat the process to Add issue or submit to Microsoft

**Comment by josaw1** [comment]
Thank you for your feedback. @AnupamMicrosoft can you please take a look?

**Comment by josaw1** [comment]
BUG 412924 created to track the issue.

**Comment by AndrewCussons** [comment]
I had a “Technical preview / trial”  subscription and there is no default free support plan, by design. If I use a paid subscription there is a free support plan that can be used.

Please clarify in the Docs help
"Note: Technical preview subscriptions cannot Submit to Microsoft unless they have a paid support plan. "

**Comment by shereen-yong** [comment]
any updates on this issue please?
