### ISSUE TITLE
Update document for option of Adyen Terminal API or Cloud API for POS devices

### ISSUE THREAD

**Issue by andyNewnham** [MicrosoftDocs/dynamics-365-unified-operations-public#1994]
Could this document please be updated to reference that you have the option of using Terminal API or Cloud API. More information on this set-up was demo'd by Ruben at the Biz Apps summit last year - see video here from 22:30: https://www.youtube.com/watch?v=bO1ycmc2P14&t=1429s 

Within the details of how to configure the connector properties it currently states:
Terminal architecture	This must be set to Local for POS terminals.
The above statement is not true, it can be Local or Cloud depending on which API architecture you choose.
The Cloud API key section states:
Cloud API Key	This field is used only for the card-not-present payment integration and should be left blank.
The above statement is also not true, Cloud API needs to be populated if using Cloud API architecture.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af578496-df16-bb9c-a626-f9298c94ece1
* Version Independent ID: 36a3e95f-1152-0722-f142-0a4041ff6a48
* Content: [Dynamics 365 Payment Connector for Adyen](https://docs.microsoft.com/en-us/dynamics365/retail/dev-itpro/adyen-connector?tabs=10-0-7)
* Content Source: [articles/retail/dev-itpro/adyen-connector.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/dev-itpro/adyen-connector.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @rassadi
* Microsoft Alias: **rassadi**

**Comment by josaw1** [comment]
Thank you for your feedback. @Reza-Assadi can you please take a look?

**Comment by josaw1** [comment]
@rubencdelgado

**Comment by josaw1** [comment]
An update is in the works. Please check back. Thank you.

**Comment by rubencdelgado** [comment]
Publishing PR to address this issue.
