### ISSUE TITLE
10.0.8 Platform update 32?

### ISSUE THREAD

**Issue by subglo** [MicrosoftDocs/dynamics-365-unified-operations-public#1996]
Hello, 
Where is 10.0.8 Platform update 32? It says it will be GA January 17, 2020.
Can't find it and shared asset library.

**Comment by josaw1** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
