### ISSUE TITLE
SDK download

### ISSUE THREAD

**Issue by GuidovTricht** [MicrosoftDocs/dynamics-365-unified-operations-public#200]
I would like to know where I can download this SDK solution. I can't seem to find it anywhere on the internet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f6646b0-8b93-0ca4-edf9-86698587f387
* Version Independent ID: 5dffea95-1a80-bb97-c813-4a9fddc33156
* Content: [e-Commerce Platform SDK - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/dev-itpro/ecommerce-platform-sdk#feedback)
* Content Source: [articles/retail/dev-itpro/ecommerce-platform-sdk.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/dev-itpro/ecommerce-platform-sdk.md)
* Service: **dynamics-365-retail**
* GitHub Login: @kfend
* Microsoft Alias: **meeram**

**Comment by MargoC** [comment]
Hi @GuidovTricht, how to get the SDK is described here: https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/dev-itpro/retail-sdk/retail-sdk-overview. We'll also add a link to this topic.
