### ISSUE TITLE
Copy the sandbox database to production (not exits the option "Sandbox to production in service request") 

### ISSUE THREAD

**Issue by diegoreza89** [MicrosoftDocs/dynamics-365-unified-operations-public#2001]
Our LCS is in "Self-service deployment architecture" and we cannot se the option to copy sandbox to production in the section Service Request..how can we copy sandbox (UAT) to production?

**Comment by tonyafehr** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
