### ISSUE TITLE
DateTime fields in UTC 

### ISSUE THREAD

**Issue by kurthatlevik** [MicrosoftDocs/dynamics-365-unified-operations-public#2004]
According to support request 119111421001006, it is clear that all fields of the type DateTime is presented in UTC timezone.  So if you are importing DateTime, it needs to be converted to UTC before importing into D365 using the Open in Excel add-in.  This should be documented on this docs page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c40f89cb-2263-7841-97fe-e6b24437b746
* Version Independent ID: 3672b2fd-08e8-5c6f-6c47-411dc6977d71
* Content: [Open entity data in Excel and update it by using the Excel add-in](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/office-integration/use-excel-add-in?toc=/dynamics365/supply-chain/toc.json)
* Content Source: [articles/fin-ops-core/dev-itpro/office-integration/use-excel-add-in.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/office-integration/use-excel-add-in.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @ChrisGarty
* Microsoft Alias: **cgarty**

**Comment by tonyafehr** [comment]
@kurthatlevik, thanks for the feedback. 
@ChrisGarty, please review and make updates as needed.

**Comment by tonyafehr** [comment]
Bug 413864 logged to track this issue.

**Comment by ChrisGarty** [comment]
Documented here: https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/office-integration/office-integration-troubleshooting?toc=/dynamics365/commerce/toc.json#why-are-date-and-time-values-in-utc-in-the-excel-add-in

**Comment by ChrisGarty** [comment]
Resolved Bug 413864: Docs issue #2004: DateTime fields in UTC
