### ISSUE TITLE
FIFO without the Include physical value option

### ISSUE THREAD

**Issue by GERGMAN** [MicrosoftDocs/dynamics-365-unified-operations-public#2007]
In FIFO without the Include physical value option, bullet 5a states…. a cost price of 20.00 each (running average of financially updated transactions). I believe that should be $15 each.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86ece8c8-fcea-0e14-9bb2-0544b62b17c1
* Version Independent ID: b2e81fea-7a8a-0f06-c760-b6abbbd07cea
* Content: [FIFO with physical value and marking](https://docs.microsoft.com/en-us/dynamics365/supply-chain/cost-management/fifo-physical-value-marking#feedback)
* Content Source: [articles/supply-chain/cost-management/fifo-physical-value-marking.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/cost-management/fifo-physical-value-marking.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @AndersGirke
* Microsoft Alias: **shylaw**

**Comment by tonyafehr** [comment]
@GERGMAN, thanks for the feedback. 
@AndersGirke, please review and consider making updates as needed.

**Comment by tonyafehr** [comment]
Bug 413865 has been logged to track this issue.
