### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by oathgg** [MicrosoftDocs/dynamics-365-unified-operations-public#2009]
Platform update xx
Microsoft Dynamics 365 Supply Chain Management 10.0.8 includes Platform update 32. To learn more about Platform update xx, see Preview features in Platform update 32.

Probably something went wrong with the above topic.
The link is also referencing 'https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/get-started/whats-new-platform-update-xx.md' which is dead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17478012-e3df-bb05-c161-136211020420
* Version Independent ID: c46df71a-44cd-bf55-2442-b7fa0c08b691
* Content: [Preview features in Dynamics 365 Finance version 10.0.8 (January 2020)](https://docs.microsoft.com/en-us/dynamics365/finance/get-started/whats-new-changed-10-0-8)
* Content Source: [articles/finance/get-started/whats-new-changed-10-0-8.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/get-started/whats-new-changed-10-0-8.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @roschlom
* Microsoft Alias: **roschlom**

**Comment by sericks007** [comment]
@oathgg, thanks for making us aware of this!

@roschlom, please review and update the content.

**Comment by sericks007** [comment]
Thanks again for reporting these issues!  This content has been updated.
