### ISSUE TITLE
Incorrect Content

### ISSUE THREAD

**Issue by ChrisTrainer88** [MicrosoftDocs/dynamics-365-unified-operations-public#201]
The content here, is for an Acquisition Journal - which is non PO/Purchase invoice based. The Title of the content is ''dispose of a fixed asset using a free text invoice' 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9937c4af-de95-7c05-eeb9-b1dce21f2978
* Version Independent ID: 5d997ec6-a5ac-2b72-a9f1-5765242572c7
* Content: [Dispose of a fixed asset using a free text invoice - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/fixed-assets/tasks/dispose-fixed-asset-free-text-invoice#feedback)
* Content Source: [articles/financials/fixed-assets/tasks/dispose-fixed-asset-free-text-invoice.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/fixed-assets/tasks/dispose-fixed-asset-free-text-invoice.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @saraschi2
* Microsoft Alias: **saraschi**

**Comment by saraschi2** [comment]
+ Current owners, Kim and Annette


Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by ShylaThompson** [comment]
@ChrisTrainer88 the topic has been updated.
