### ISSUE TITLE
v10.0.8 release notes

### ISSUE THREAD

**Issue by curtiswatson** [MicrosoftDocs/dynamics-365-unified-operations-public#2011]
Where are the v10.0.8 release notes which is already GA?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5422ea93-f976-dd55-8451-a3ce821c71df
* Version Independent ID: bfc8f75d-62c2-7b44-36b5-5dbd06a97ec5
* Content: [Preview features in Dynamics 365 Retail version 10.0.7](https://docs.microsoft.com/en-us/dynamics365/retail/get-started/whats-new-10-0-7?toc=/dynamics365/commerce/toc.json)
* Content Source: [articles/retail/get-started/whats-new-10-0-7.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/get-started/whats-new-10-0-7.md)
* Service: **dynamics-ax-retail**
* Product: ****
* Technology: ****
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by sericks007** [comment]
@curtiswatson, thanks for posting here!

@josaw1, please review.

**Comment by curtiswatson** [comment]
Also an issue with D365 Finance.

**Comment by josaw1** [comment]
Thanks for your feedback. We didn't publish a What's New topic for Retail version 10.0.8. You can always reference the Release Plans for new and upcoming functionality. We will publish a What's New topic for Finance version 10.0.8 in the coming days, so please check back.
