### ISSUE TITLE
[!NOTE] is probably missing formatting

### ISSUE THREAD

**Issue by oathgg** [MicrosoftDocs/dynamics-365-unified-operations-public#2013]
You probably intended the [!NOTE] tag to be formatted like your [!IMPORTANT] tags which I've seen on multiple pages.
An example would be: https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/edit/live/articles/fin-ops-core/fin-ops/get-started/before-you-buy.md.

However, when you look at this page on the actual Microsoft docs you will notice that the formatting does not match the formatting you're using for the [!IMPORTANT] tags.

Is the [!NOTE] tag like this intentional?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17478012-e3df-bb05-c161-136211020420
* Version Independent ID: c46df71a-44cd-bf55-2442-b7fa0c08b691
* Content: [Preview features in Dynamics 365 Finance version 10.0.8 (January 2020)](https://docs.microsoft.com/en-us/dynamics365/finance/get-started/whats-new-changed-10-0-8)
* Content Source: [articles/finance/get-started/whats-new-changed-10-0-8.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/get-started/whats-new-changed-10-0-8.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @roschlom
* Microsoft Alias: **roschlom**

**Comment by sericks007** [comment]
@oathgg, thanks for posting here!  Our Content Publishing team is working to update this topic.

@roschlom, please update the content.

**Comment by sericks007** [comment]
Thanks again for reporting the issue! This content has been updated.
