### ISSUE TITLE
Retail 365 SDK

### ISSUE THREAD

**Issue by stephenfournier** [MicrosoftDocs/dynamics-365-unified-operations-public#2018]
I am trying to figure out how to obtain the Retail 365 SDK. I have checked [this documentation](https://docs.microsoft.com/en-us/dynamics365/retail/dev-itpro/retail-sdk/retail-sdk-overview#download-the-retail-sdk) but am still confused. It says "The Retail SDK is available in development environments, and in hotfix packages in a Retail SDK folder." It does not mention how to obtain/setup a development environment. How can I obtain the Retail 365 SDK/setup a development environment?

**Comment by josaw1** [comment]
Thank you for your feedback. @mugunthanm can you please take a look?

**Comment by mugunthanm** [comment]
Please check the below document for how to deploy a development environment and get the SDK. Once the environment is deployed, RDP to the VM and in the service volume drive you can find the SDK.
https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/access-instances
