### ISSUE TITLE
Release Note 10.0.8 

### ISSUE THREAD

**Issue by HenrikLevinson** [MicrosoftDocs/dynamics-365-unified-operations-public#2021]
Looking for whats new in 10.0.8 and platform 3. When will the docs will be released?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85a380bf-8777-9eb4-0791-74c92b321746
* Version Independent ID: f8d3164a-44de-ba52-74ce-a8a6818053cd
* Content: [What's new and changed in Dynamics 365 Finance version 10.0.7 (January 2020)](https://docs.microsoft.com/en-us/dynamics365/finance/get-started/whats-new-changed-10-0-7)
* Content Source: [articles/finance/get-started/whats-new-changed-10-0-7.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/get-started/whats-new-changed-10-0-7.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @roschlom
* Microsoft Alias: **roschlom**

**Comment by josaw1** [comment]
Hi, thanks for your feedback. The What's New topic for Finance version 10.0.8 is live [here](https://docs.microsoft.com/en-us/dynamics365/finance/get-started/whats-new-changed-10-0-8).
