### ISSUE TITLE
PDF documents

### ISSUE THREAD

**Issue by soerenpc** [MicrosoftDocs/dynamics-365-unified-operations-public#2022]
HI
We can't send out invoices as Excel files. They need to be converted to PDF. 
Can we do that? 

SPC

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c9d868b-2b3b-26c9-f8ff-863e6f8cd9d4
* Version Independent ID: 9ea7a0a4-99ab-aca8-ca48-62ee8c02a92b
* Content: [Business document management overview](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/er-business-document-management?toc=%2Ffin-and-ops%2Ftoc.json#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/er-business-document-management.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/er-business-document-management.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @NickSelin
* Microsoft Alias: **nselin**

**Comment by NickSelin** [comment]
Hello [SPC](https://github.com/soerenpc),
Thanks for contacting us. Currently, you can do such conversion in only your customized code - the corresponding ER [extensibility point](https://docs.microsoft.com/dynamics365/fin-ops-core/dev-itpro/analytics/er-custom-storage-generated-documents) allows to catch Excel files and convert them to PDF by using any tool you have. To make great progress on the idea of the PDF conversion as the built-in ER functionality, vote for the respective [topic](https://experience.dynamics.com/ideas/idea/?ideaid=ffed8bd3-1bd6-e911-b3b9-0003ff68f1ff)  on the Microsoft Dynamics 365 Ideas Portal.
Nick Selin
