### ISSUE TITLE
connect to PowerBI.com 

### ISSUE THREAD

**Issue by gprodware** [MicrosoftDocs/dynamics-365-unified-operations-public#2024]
Hi,
it is not mentioned if there is a way to connect PowerBI.com to this data lake ?
Br,

Gill

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a344a5de-68fa-e9cf-28eb-51269c33b9b3
* Version Independent ID: 1b3ede62-3954-574b-5778-8cdee0ededfe
* Content: [Make Entity store available as a Data Lake](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/entity-store-data-lake?toc=%2Ffin-and-ops%2Ftoc.json#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/entity-store-data-lake.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/entity-store-data-lake.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by RobinARH** [comment]
@MilindaV2 - Can you take a look? Thanks.

**Comment by RobinARH** [comment]
Created bug 415932 to track this issue.

**Comment by RobinARH** [comment]
We have added more documentation.
