### ISSUE TITLE
Importing

### ISSUE THREAD

**Issue by Taketral** [MicrosoftDocs/dynamics-365-unified-operations-public#2025]
I cannot import even though I follow these step. There is always same error as below.
"File contains duplicate rows, cannot insert data into staging due to unique key violation.-
'0' 'ZIP Postal Code Japan' record(s) inserted in staging"
And I checked the file but there are no duplicate rows. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebfb02b0-9082-da6c-b6d4-8ca2f22be6a9
* Version Independent ID: 64fef9b0-6205-1f03-0569-6e37e95c1f98
* Content: [Import postal codes for Japan](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/apac-jpn-import-postal-codes#feedback)
* Content Source: [articles/finance/localizations/apac-jpn-import-postal-codes.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/localizations/apac-jpn-import-postal-codes.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @yijialuan
* Microsoft Alias: **riluan**

**Comment by RobinARH** [comment]
@yijialuan - Can you take a look? Thanks.

@Taketral - You might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

**Comment by RobinARH** [comment]
Created bug 415931 to track this issue.

**Comment by EricWangChen** [comment]
@Taketral could you provide the data which you want to upload for us to check?

**Comment by Taketral** [comment]
@EricWangChen  This is the file downloaded from Japanese postal office web site and added the header. Please confirm.
[KEN_ALL.zip](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/files/4157723/KEN_ALL.zip)

**Comment by EricWangChen** [comment]
Hi Taketral,

The raw CVS file downloaded from Japan postal office should automatic split all the fields into different excel columns
![image](https://user-images.githubusercontent.com/50563680/73822692-a3631b00-4831-11ea-91c2-34b0ccd89923.png)
But in your CSV file, all the fields are in column A.

Please try download the CSV file from Japan postal office again and upload

Feel free to let me know if there is still issue there.

**Comment by Taketral** [comment]
Hello Eric,
Yes, I've tried splitting but same error happens.
Thank you

**Comment by EricWangChen** [comment]
Hi Taketral,

There are some duplicate zip codes in this file. You could use excel function CountIf to check

![image](https://user-images.githubusercontent.com/50563680/73900570-24222580-48cb-11ea-9bae-8ea0b87ed68e.png)

**Comment by Taketral** [comment]
Hello Eric
Thanks for your help! I still have issues but now I can import after deleting the duplicates.
