### ISSUE TITLE
Outdated information

### ISSUE THREAD

**Issue by ransoentjens** [MicrosoftDocs/dynamics-365-unified-operations-public#2029]
The following information is incorrect / missing and should be updated:
- This topic does not only apply on MPOS, but als on CPOS. MPOS reference can thus be removed
- The generic %message% placeholder must be replaced with: 
&lt;pre&gt;
%message%
&lt;/pre&gt;
Otherwise the outline is incorrect. Furthermore, it is advised to put the html content in a notepad file and save as .txt (as discussed with the product team).

If the above actions are not correctly, then you get a wrong aligned receipt, and a big header/footer section.

Finally: Including the logo of the printed receipt is NOT possible. However, this can be achieved by creating a generic html e-mail template and embedding the placeholder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6c14a11-5423-2694-a4ae-39af475bb09e
* Version Independent ID: 89e7d16e-dfc5-60ea-f916-33f67f1c989a
* Content: [Send email receipts from Retail Modern POS (MPOS)](https://docs.microsoft.com/en-us/dynamics365/retail/email-receipts)
* Content Source: [articles/retail/email-receipts.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/email-receipts.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @jashanno
* Microsoft Alias: **jashanno**

**Comment by tonyafehr** [comment]
@ransoentjens, thanks for the feedback. 
@jashanno, please review and update this topic as necessary.

**Comment by tonyafehr** [comment]
Bug 416106 logged to track this issue.

**Comment by rubencdelgado** [comment]
MPOS describes the POS client regardless of platform.  Addressing other comments in docs article via PR.

**Comment by rubencdelgado** [comment]
Fixed in https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/pull/2062

**Comment by tonyafehr** [comment]
We will publish this topic with updated content later today. Thanks!
