### ISSUE TITLE
Payroll support for other countries

### ISSUE THREAD

**Issue by dcs-kartik** [MicrosoftDocs/dynamics-365-unified-operations-public#203]
Why it is only supported for US. Is there any planning to update for other countries?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42c7705f-f875-b2aa-4c1f-5be06cfecfed
* Version Independent ID: a64fe3a1-1a96-123d-e322-41431dba46bf
* Content: [Payroll overview - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/hr/localizations/noam-usa-payroll)
* Content Source: [articles/fin-and-ops/hr/localizations/noam-usa-payroll.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/hr/localizations/noam-usa-payroll.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @rschloma
* Microsoft Alias: **rschloma**

**Comment by kfend** [comment]
Thanks for taking the time to provide feedback on Finance and Operations! We recommend that you ask your question [here](https://community.dynamics.com/ax/b/axhcmnewslearningshighlights/archive/2018/05/18/2018-r6-payroll-tax-update-for-dynamics-365-for-finance-and-operations-enterprise-edition-in-progress) where there will be more information available regarding Payroll functionality.
