### ISSUE TITLE
Job History Cleanup

### ISSUE THREAD

**Issue by timwhalenin** [MicrosoftDocs/dynamics-365-unified-operations-public#2035]
The article states the Job History Cleanup job is available in PU29 and later.  I have one client on PU29 and they do not have this tile in the DM workspace or on the Tiles section in Visual Studio.  I have another client on PU30 and they have it in both areas.  Is there something I'm missing here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d35f4fb2-1296-20ef-56c2-a2c5aa00befe
* Version Independent ID: 0d515af9-9419-4f21-223e-25344cf1bfe8
* Content: [Data import and export jobs overview](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/data-import-export-job#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/data-import-export-job.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/data-import-export-job.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by Sunil-Garg** [comment]
You will have to enable the feature in feature management. Can you check on that pls?

________________________________

**Comment by timwhalenin** [comment]
Thanks Sunil!  I totally missed that sentence in the documentation.  I’ve got it enabled now.

Thanks!

Tim
