### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by dahirongm** [MicrosoftDocs/dynamics-365-unified-operations-public#2037]
[Enter feedback here]
I think there is a typo: "this update should very rarely". Maybe is "vary" instead of "very".

Thanks

Dahiron

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c00f86f-ec28-b1dc-d452-6d5514f9336c
* Version Independent ID: 7c1e6e4d-bc93-b5d8-22e1-ac56ddc488e1
* Content: [Retail software development kit (SDK) architecture](https://docs.microsoft.com/en-us/dynamics365/retail/dev-itpro/retail-sdk/retail-sdk-overview#retail-sdk-deep-dive)
* Content Source: [articles/retail/dev-itpro/retail-sdk/retail-sdk-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/dev-itpro/retail-sdk/retail-sdk-overview.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **sijoshi**

**Comment by tonyafehr** [comment]
@dahirongm, thanks for the feedback. Updates to the paragraph will be published later today.

**Comment by dahirongm** [comment]
@tonyafehr  my pleasure.
