### ISSUE TITLE
confusing documentation

### ISSUE THREAD

**Issue by turbozapekanka** [MicrosoftDocs/dynamics-365-unified-operations-public#204]
Step 4 points to a page that says run "AXUpdateInstaller.exe devinstall" but it does not work and generates this error: The devInstall option is not applicable to the current deployable package.

Example is missing this command:
AXUpdateInstaller.exe generate -runbookid="OneBoxDev" -topologyfile="DefaultTopologyData.xml" -servicemodelfile="DefaultServiceModelData.xml" -runbookfile="OneBoxDev-runbook.xml"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 058d220b-d85d-eabd-abfb-8fadb3b8bf47
* Version Independent ID: c25f2d4d-dfef-7736-311f-8c1f25ddc696
* Content: [Apply the latest platform update to your Dynamics 365 Finance and Operations environment - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/upgrade-latest-platform-update#apply-the-platform-update-package-to-your-development-environment)
* Content Source: [articles/dev-itpro/migration-upgrade/upgrade-latest-platform-update.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/migration-upgrade/upgrade-latest-platform-update.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @tariqbell
* Microsoft Alias: **tabell**

**Comment by tariqbell** [comment]
They are right, the example is missing a step. I don't own this article anymore - I think you'll need to look where that broken change came from (it's a more recent addition) to track down where/who it came from. @robadawy might be the owner now.

This is the bit that needs changing (attached)
![installlatestplatform_article_missingexample](https://user-images.githubusercontent.com/24258528/41856468-17b03ed2-788d-11e8-863f-e405c28affb5.JPG)

**Comment by MargoC** [comment]
Thanks for passing this along. The topic just had some bad formatting, and lost the first line of text.
