### ISSUE TITLE
D12v2 not available for selection when deploying a new instance with Demo topology?

### ISSUE THREAD

**Issue by BasvGMRN** [MicrosoftDocs/dynamics-365-unified-operations-public#2041]
Adding a new environment in my LCS project with topology "Demo" does not allow D12v2 to be selected as the VM size, although it is recommended in this article. Guess the documentation needs to be updated with a (new) VM size?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90265dfd-3035-a591-fbb4-4265024186b7
* Version Independent ID: 374ae0ff-ce77-54d5-f16c-2faf3fc6e7bb
* Content: [Deploy a demo environment](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/deploy-demo-environment#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/deploy-demo-environment.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/deployment/deploy-demo-environment.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @sarvanisathish
* Microsoft Alias: **sarvanis**

**Comment by kfend** [comment]
@BasvGMRN  - Thanks for the feedback. I have assigned this issue to the PM.
