### ISSUE TITLE
 Description "Asset management plans" is incorrect

### ISSUE THREAD

**Issue by 1harmsma** [MicrosoftDocs/dynamics-365-unified-operations-public#2042]
Hello,

On this page (create an asset) &gt; The Description of the FastTab "Asset management plans" is incorrect, it should be "Asset Maintenance Plans".
 (see link &gt; https://docs.microsoft.com/en-us/dynamics365/supply-chain/asset-management/objects/create-an-object#asset-management-plans) 

Greetings, Ton Harmsma

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6661c4c1-b997-aaf9-4265-a4b6edcea940
* Version Independent ID: ad27e562-b0bc-8dbf-71c4-924e84867be9
* Content: [Create an asset](https://docs.microsoft.com/en-us/dynamics365/supply-chain/asset-management/objects/create-an-object#asset-management-plans)
* Content Source: [articles/supply-chain/asset-management/objects/create-an-object.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/asset-management/objects/create-an-object.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @josaw1
* Microsoft Alias: **mkirknel**

**Comment by MaiKirknel** [comment]
Please assign to Arijit

/mai

**Comment by tonyafehr** [comment]
@kamaybac, please review.
