### ISSUE TITLE
Vendor on-hold = Requisition

### ISSUE THREAD

**Issue by texaspete** [MicrosoftDocs/dynamics-365-unified-operations-public#2047]
The text for

Putting a vendor on hold
Requisition – Only purchase requisitions can be created. No other transactions can be created.

has it completely the wrong way round. If the Vendor hold is set to Requisition, all transactions are allowed EXCEPT for Requisitions (and RFQs).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b99bd95-66ac-1ed4-9dee-211c09a00338
* Version Independent ID: 6fe3a034-2272-3030-da5c-7b64ccf896a3
* Content: [Set up vendor accounts](https://docs.microsoft.com/en-us/dynamics365/supply-chain/procurement/set-up-vendor-accounts)
* Content Source: [articles/supply-chain/procurement/set-up-vendor-accounts.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/procurement/set-up-vendor-accounts.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @mkirknel
* Microsoft Alias: **mkirknel**

**Comment by MaiKirknel** [comment]
I have updated the topic - please review and approve

**Comment by kamaybac** [comment]
I reviewed and merged the update. It should go live soon.

**Comment by MaiKirknel** [comment]
Thx 😊
