### ISSUE TITLE
Posting does not generate Voucher number

### ISSUE THREAD

**Issue by mcarvalho21** [MicrosoftDocs/dynamics-365-unified-operations-public#205]
"A voucher number must still be defined in the imported file. However, this number is temporary and is overwritten by the voucher number when the journal is posted." -- Does not work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2123bcb-5d8e-0756-4a25-0b8c064361c3
* Version Independent ID: bde40e2b-b045-6d50-e39d-dbcda5df038c
* Content: [Best practices for importing vouchers using the General journal entity - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/tips-tricks-import-general-journal-entity)
* Content Source: [articles/dev-itpro/data-entities/tips-tricks-import-general-journal-entity.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/tips-tricks-import-general-journal-entity.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @twheeloc
* Microsoft Alias: **kweekley**

**Comment by ShylaThompson** [comment]
bug logged: 228906

**Comment by kweekley** [comment]
If this isn't working, then please log a bug with the appropriate repro steps.

**Comment by ShylaThompson** [comment]
@mcarvalho21 
Thanks for contacting us. Unfortunately, we can't handle support requests for the product here. To contact support, consider one of the options described in the following topic: [LCS support](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support)
