### ISSUE TITLE
Retrieve execution_id

### ISSUE THREAD

**Issue by pricarvalho86** [MicrosoftDocs/dynamics-365-unified-operations-public#2054]
I'm trying to get the message errors, but the execution_id is mandatory to request. The problem that I got in here is that I don't know how to retrieve this information through Api Rest. What I'm trying to do is:

1- /api/connector/enqueue/:id?entity=:entity -&gt; return messageId
2- /data/DataManagementDefinitionGroups/Microsoft.Dynamics.DataEntities.GetMessageStatus -&gt; return JSON with status
3- /data/DataManagementDefinitionGroups/Microsoft.Dynamics.DataEntities.GetExecutionErrors &lt;---- To execute this request, I need a resource to retrieve the execution_id. Maybe the first one.

Can you help me?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d963d4c-de1f-7730-bee2-016dcde40907
* Version Independent ID: 21b95d43-5ad9-0ffc-21b9-6a4ba9086a56
* Content: [Data management package REST API](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/data-management-api#getting-the-list-of-errors)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/data-management-api.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/data-management-api.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by tonyafehr** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
