### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by bkdjayh** [MicrosoftDocs/dynamics-365-unified-operations-public#2055]
Where is the list of fonts available for documents rendered by the Cloud-hosted service?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c7f272b-4ea7-a285-4a9f-e67583a664e0
* Version Independent ID: 54ac0c3d-a2b5-6001-1581-167dd87a80c0
* Content: [Self-service deployment overview](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/infrastructure-stack#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/infrastructure-stack.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/deployment/infrastructure-stack.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @sarvanisathish
* Microsoft Alias: **sarvanis**

**Comment by tonyafehr** [comment]
@TJVass, can you assist with this. Thanks!

**Comment by tonyafehr** [comment]
Bug 418208 has been logged to track this issue.
