### ISSUE TITLE
Win7 no longer supports Hardware Station Installation D365 10.0.8 version 

### ISSUE THREAD

**Issue by JayStock57** [MicrosoftDocs/dynamics-365-unified-operations-public#2056]
Document needs to be updated as Powershell Scripts in 10.0.8 version of D365 Hardware Station Installer fail due to Win7 IIS app pool not having certain fields.  Only works on Windows 10 IIS App Pool.  These have to be edited in Powershell to work.  Also Win 7 is not longer supported since last month for Windows updates. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 043a7336-3d71-14f2-9856-05e03e24cd80
* Version Independent ID: 60414540-f243-27e6-0494-28c4af78e0a4
* Content: [System requirements for cloud deployments](https://docs.microsoft.com/en-us/dynamics365/commerce/get-started/system-requirements#feedback)
* Content Source: [articles/commerce/get-started/system-requirements.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/get-started/system-requirements.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @jashanno
* Microsoft Alias: **jashanno**

**Comment by JayStock57** [comment]
Problem Reason: There are some commands in the Common-Web.ps1 related to configuring Application Pool in IIS are only valid for IIS 8.5 which is not applicable in case of Windows 8. Please find the following screenshot of the commands in link below:

 [Problem Reason.docx](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/files/4160009/Problem.Reason.docx)


Solution: By dropping those 2 commands from the script file and executing the creation of Hardware Station manually through powershell (Thanks for the old link sent) the problem is solved.
https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/install-retail-hardware-station#option-2-install-hardware-station-by-using-windows-powershell

**Comment by sericks007** [comment]
@JayStock57, thanks for making us aware of this issue.

@jashanno, please review and update the content as needed.

**Comment by sericks007** [comment]
Bug 418629 has been logged to track this issue.

**Comment by sericks007** [comment]
This article has been updated! The updated version will be published soon.
