### ISSUE TITLE
Sample is out of date and does not match output today

### ISSUE THREAD

**Issue by mores** [MicrosoftDocs/dynamics-365-unified-operations-public#2059]
Images and data should be updated to match todays version: 10.0.5

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f295a3d-6be4-2144-bbfc-982d00e6e8cf
* Version Independent ID: 8ca42df5-fada-9e67-49b7-17f921fef344
* Content: [End-to-end scenario for the Fleet Management sample application](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/fleet-management-sample)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/fleet-management-sample.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-tools/fleet-management-sample.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **jorisde**

**Comment by mores** [comment]
![image](https://user-images.githubusercontent.com/1318377/73875698-ae16b380-4823-11ea-89f6-2bd502835e62.png)

**Comment by sericks007** [comment]
@mores, thanks for posting here!

@jorisdg, please review and consider updating the content.

**Comment by sericks007** [comment]
Bug 418628 has been logged to track this issue.

**Comment by RobinARH** [comment]
I updated the topic last week.
