### ISSUE TITLE
Need to run Create Users command as Administrator to avoid errors 

### ISSUE THREAD

**Issue by NatIFD** [MicrosoftDocs/dynamics-365-unified-operations-public#206]
Section "**Set up Visial Studio Online for multiuser testing**"  on the document [https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/mbam-v2/performing-bitlocker-management-with-mbam-mbam-2](url)

Step 3 should specify that the command `MS.Dynamics.Performance.CreateUsers.exe` should be run as **Administrator**. 

This has been validated by discussion with our Microsoft functional consultant, and our own experience. When running as a non-elevated command, a set of errors is generated. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71bd6e91-0511-905a-0e70-b0510d961f16
* Version Independent ID: 4942a200-93f3-6f2b-8a59-b88fdf6e825c
* Content: [Performance SDK and multiuser testing via Visual Studio Online - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/perf-test/perfsdk-tutorial)
* Content Source: [articles/dev-itpro/perf-test/perfsdk-tutorial.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/perf-test/perfsdk-tutorial.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @jujoh
* Microsoft Alias: **jujoh**

**Comment by MargoC** [comment]
Thanks for the feedback. We've updated the topic.
