### ISSUE TITLE
Where is the FMEntityLab project located

### ISSUE THREAD

**Issue by mores** [MicrosoftDocs/dynamics-365-unified-operations-public#2060]
Where can the project "FMEntityLab" be found. This is needed to continue with "Consuming entities by using OData"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67eb6eeb-d9fc-4e83-6282-fff9783b1466
* Version Independent ID: f16158fb-2a9b-6429-dd3e-05d4d1e1650b
* Content: [Build and consume data entities](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/build-consuming-data-entities)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/build-consuming-data-entities.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/build-consuming-data-entities.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by Sunil-Garg** [comment]
It should be in the Fleet Management model.

--------
Our workplace allows for a flexible work schedule, which is an amazing benefit. I am sending this now because it is convenient for me. I do not expect you to read or respond until it’s convenient for you.

**Comment by mores** [comment]
There is no FMEntityLab in the AOT:
![image](https://user-images.githubusercontent.com/1318377/73941004-7444bc00-48ba-11ea-959e-fe4cab06425c.png)

When it asks for "In Solution Explorer, verify that you're in the FMEntityLab project." I assume it is talking about a Visual Studio project. Do you need to start a new Visual Studio project called "FMEntityLab" or is there an existing one you need to download from some where ?

**Comment by Sunil-Garg** [comment]
@Ole Hellevik<mailto:oleh@microsoft.com> can you help here pls?

________________________________

**Comment by mores** [comment]
The page also says:
"In the Open Project dialog box, browse to C:\FMLab\Odata4ConsoleApplication, and then select Odata4ConsoleApplication.csproj."

But there is no FMLab in C:\
![image](https://user-images.githubusercontent.com/1318377/73955729-ce9d4700-48d1-11ea-9eb9-46face60513b.png)

**Comment by mores** [comment]
Found the location.
Create pull request: https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/pull/2068

**Comment by Sunil-Garg** [comment]
Second hit when searching for FMEntityLab on Bing points to a github repo and a yammer thread.

https://community.dynamics.com/365/financeandoperations/f/dynamics-365-for-finance-and-operations-forum/217646/where-are-the-solution-files-for-the-wiki-article-on-building-and-consuming-data-entities

You can also find the odata client code samples here.
