### ISSUE TITLE
Addressing section should mention special format for single Entity

### ISSUE THREAD

**Issue by justinkaufman** [MicrosoftDocs/dynamics-365-unified-operations-public#2063]
The OData calls to reference a single entity need to pass 2 named keys to work properly, the documentation should reflect this.
E.g. {uri}/data/VendorsV2('12345') will fail with "No route data was found for this request", where {uri}/data/VendorsV2(dataAreaId='10',VendorAccountNumber='12345') will work. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d7c8b45-1531-ebbf-d417-4e1fe5bf4f1b
* Version Independent ID: c543a5fc-90c9-9edb-11d7-6d6d0f2c10a9
* Content: [Open Data Protocol (OData)](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/odata#addressing)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/odata.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/odata.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by josaw1** [comment]
Thanks for your feedback. @Sunil-Garg, can you please take a look?

**Comment by josaw1** [comment]
BUG 419059 created to track this issue.

**Comment by Sunil-Garg** [comment]
Thanks @justinkaufman. A note has been added at the beginning to call out that all key fields must be provided to make a successful call. Hope this addresses what you highlighted. Thanks.
