### ISSUE TITLE
GetExecutionErrors for recurring integrations does not work

### ISSUE THREAD

**Issue by TomekMelissa** [MicrosoftDocs/dynamics-365-unified-operations-public#2064]
I think that information about GetExecutionErrors request was added to this page by mistake. GetExecutionErrors requires executionId parameter which does not exist in context of recurring integrations (dequeue/enqueue API). It only works with package API requests. This section should be removed from this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01b2cd6b-f885-7461-fbdf-cf81f9e50d86
* Version Independent ID: 8df7a6ae-67db-5d29-fb6a-0820704ff3ef
* Content: [Recurring integrations](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/recurring-integrations#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/recurring-integrations.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/recurring-integrations.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by josaw1** [comment]
Thank you for your feedback. @Sunil-Garg, can you please take a look?

**Comment by josaw1** [comment]
BUG 419060 created to track this issue.

**Comment by gvdsleen** [comment]
Any news on this problem of not being able to retrieve the errors when using recurring instead of the package api?

**Comment by Sunil-Garg** [comment]
Hi Tomek-- as long as the execution id is passed to this api, it will return the list of errors. The execution id can be from a job scheduled from a recurring integration. You are correct that the enqueue/dequeue set of API's don't work with execution id but, it shouldn't matter as long as an execution id is passed to the error API to get the list of execution errors. Hope this helped clarify. Let me know if you have further questions and we can discuss offline.

Thanks.

**Comment by ekersey** [comment]
> ...it shouldn't matter as long as an execution id is passed to the error API to get the list of execution errors

But the execution id is not returned by the enqueue/dequeue set of API's.  Therefore this endpoint cannot be used to get a list of errors, because the execution id is unknown.  If there is a way to retrieve the execution id, please document that.

**Comment by daccorti** [comment]
@ekersey - We are finding the same problem on our end. Were you ever able to find a resolution to this?
