### ISSUE TITLE
How customer can be aware with upcoming changes in LCS?

### ISSUE THREAD

**Issue by xbizzit** [MicrosoftDocs/dynamics-365-unified-operations-public#2065]
Hello team,
Do you update this source regularly? I can see the last update is from 2nd of December 2019. Where customers can see Dynamics 365 LCS upcoming updates? We have a case where customer complained about not being informed that PG decided to remove File size information from Asset library and he is complaining about lack of transparency in LCS changes done by PG, also not announcing this change in any monthly releases. Can someone clarify? Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d8d91ac-1947-9637-3b39-53d832483355
* Version Independent ID: 69495807-2269-65d3-0825-2f4174d6096c
* Content: [What's new in Lifecycle Services (LCS)](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/whats-new-lcs#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/whats-new-lcs.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/lifecycle-services/whats-new-lcs.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **kfend**

**Comment by sericks007** [comment]
@xbizzit, thanks for posting here!

The topic you commented on is no longer being updated, as mentioned in the "Important" note on that page.  For information about the latest features in Lifecycle Services, please see the [Release plans](https://docs.microsoft.com/en-us/dynamics365/release-plans/).
