### ISSUE TITLE
Code windows are mislabled as X++

### ISSUE THREAD

**Issue by tradotto** [MicrosoftDocs/dynamics-365-unified-operations-public#2066]
These code examples are C# note X++. Would be nice to show how to call the global::info from c#

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 773a3b8d-f10e-da6a-e21c-b2792b53544d
* Version Independent ID: 15f94271-592f-0851-8cd6-5932e786cbc9
* Content: [Write business logic by using C# and X++ source code](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/write-business-logic#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/write-business-logic.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-tools/write-business-logic.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @pvillads
* Microsoft Alias: **pvillads**

**Comment by josaw1** [comment]
Thank you for your feedback. @pvillads can you please take a look?

**Comment by josaw1** [comment]
BUG 419062 created to track this issue.

**Comment by RobinARH** [comment]
We updated the code labels, but it looks like there's still one that needs updating.

The call to Global::info from C# looks like this:

Global.info("This is an interesting text");

In the X++/C# [comparison topic](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-ref/xpp-cs-comparison), the suggestion is to use Console.WriteLine() in C#.
