### ISSUE TITLE
Microsoft.Dynamics.DataEntities.GetExecutionErrors method doesn't return the execution errors

### ISSUE THREAD

**Issue by shankarmaha** [MicrosoftDocs/dynamics-365-unified-operations-public#2074]
Hi,

I am trying to test this feature. But the api returns an empty object, even though the job has failed and I can see the error in DMF. This is what the job returns

{
"@odata.context": "https://xyz.operations.dynamics.com/data/$metadata#Edm.String",
"value": "[]"
}

I am passing this as the input
{
"executionId":"F7A4B553-91A0-43CC-B108-31299A41D844"
}

Any idea?

**Comment by tonyafehr** [comment]
This feedback is not associated with a particular topic. If you need immediate assistance, contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
