### ISSUE TITLE
Active Issues tab requires a support plan for trial subscriptions

### ISSUE THREAD

**Issue by AndrewCussons** [MicrosoftDocs/dynamics-365-unified-operations-public#2075]
If a customer uses a paid subscription they can submit to Microsoft by using the default support plan associated to their paid subscription. 
If a customer or partner uses a “Technical preview / trial”  they must purchase a support plan to submit to Microsoft (the default support plan is not available, unless they pay for the subscription) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32debc65-d382-465c-f0fd-a1aa5a7f9d48
* Version Independent ID: 31eb7664-5472-4fee-db0f-ac63ee2ca3ac
* Content: [Get support for Finance and Operations apps or Lifecycle Services (LCS)](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/lcs-support)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/lcs-support.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/lifecycle-services/lcs-support.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **anupams**

**Comment by sericks007** [comment]
I logged bug 7329132 in the LCS database.
