### ISSUE TITLE
Gift card provider is case sensitive GIVEX should be givex

### ISSUE THREAD

**Issue by dlanglie** [MicrosoftDocs/dynamics-365-unified-operations-public#2078]
POS payment terminal section:
Gift card provider	Enter the gift card provider that the connector should use to process gift cards. The possible values are SVS and GIVEX.

These values are case sensitive.  GIVEX should be givex

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1a7bb73-c6c0-fc10-9369-04714ac8e6f0
* Version Independent ID: df6ebf95-7def-f3d5-04fc-8f412e314ee1
* Content: [Dynamics 365 Payment Connector for Adyen](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/adyen-connector?tabs=8-1-3#feedback)
* Content Source: [articles/commerce/dev-itpro/adyen-connector.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/dev-itpro/adyen-connector.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @rassadi
* Microsoft Alias: **rassadi**

**Comment by kfend** [comment]
@dlanglie - thanks for your feedback. The topic has been updated.
