### ISSUE TITLE
Link to supported math symbols is broken.

### ISSUE THREAD

**Issue by elcanelo** [MicrosoftDocs/dynamics-365-unified-operations-public#2080]
The Supported math symbols link (http://redhivesoftware.github.io/math-expression-evaluator/#supported-maths-symbols) returns 404.

There seems to be an alternate repository (https://github.com/bugwheels94/math-expression-evaluator/blob/master/README.md) that contains the same documentation. 

I noticed however that the grids on PU32 do not support Sigma (summation) nor Pi (Product) operators, could it be that these were implemented on the newer library and this hasn't been used on the newer version of the grid yet?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75388071-94ef-d7e9-cbc1-a910621ef20e
* Version Independent ID: 6be15ff3-b119-2be7-535d-b0caa7072b5b
* Content: [Grid capabilities](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/grid-capabilities#feedback)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/grid-capabilities.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/get-started/grid-capabilities.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by sericks007** [comment]
@elcanelo, thanks for making us aware of this issue!

We've fixed the link and the updated content will be published later today.

**Comment by elcanelo** [comment]
Thanks!
