### ISSUE TITLE
"Log on as" account issue to configure DRA as windows service 

### ISSUE THREAD

**Issue by ripannandy** [MicrosoftDocs/dynamics-365-unified-operations-public#2083]
Unified operations application is hosted on "****.onmicrosoft.com" and company local domain is "companyname.com". In that scenario, how DRA is to be configured as windows service for network printers? What should be the "Log on as" account for windows service?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1745c96-57e0-956f-a5cc-dda604e34d7f
* Version Independent ID: 0209d62f-88de-ea09-ac08-a0d5ba8397ae
* Content: [Run the Document Routing Agent as a Windows service](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/run-document-routing-agent-as-windows-service?source=docs)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/run-document-routing-agent-as-windows-service.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/run-document-routing-agent-as-windows-service.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by tonyafehr** [comment]
Thanks for contacting us. If you need immediate assistance, contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

@TJVass, please review. Thanks!
