### ISSUE TITLE
Document limit of composite entity label and entity names

### ISSUE THREAD

**Issue by FH-Inway** [MicrosoftDocs/dynamics-365-unified-operations-public#2086]
See https://stackoverflow.com/questions/60147676/how-to-debug-composite-entity-with-incorrect-syntax-near-the-keyword-from-ex/60153163#60153163

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0198d960-ca6c-4d08-36e0-b5061e13a784
* Version Independent ID: 6e445b8a-8906-f8a8-5dda-d177ae12e3db
* Content: [Develop composite data entities](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/develop-composite-data-entities)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/develop-composite-data-entities.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/develop-composite-data-entities.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by tonyafehr** [comment]
@Sunil-Garg, please review. Thanks!

**Comment by tonyafehr** [comment]
Bug 419900 logged to track this issue.

**Comment by Sunil-Garg** [comment]
Thanks for highlighting this use case @FH-Inway.

Instead of publishing the troubleshooting steps, we are looking at adding validations at compile time to prevent this kids of errors from happening at development time itself. We have created a product bug for this which can be tracked as KB 4549600.

Thanks.
