### ISSUE TITLE
Practise Manager Power BI

### ISSUE THREAD

**Issue by AnjaHCph** [MicrosoftDocs/dynamics-365-unified-operations-public#2087]
[When I try to access the Analytics tab under the PM Workspace, I received the following error, ie. It is not possible to use or review the Practice Manager Power BI]

![image](https://user-images.githubusercontent.com/50369427/74162870-c6227480-4c21-11ea-96c3-822f4c0207fa.png)

How can we gain access to the PM analytics?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 656dfc38-396a-3c16-abcd-656c89a186c6
* Version Independent ID: 45a7d683-6630-a125-84b7-0fc75bfd6b09
* Content: [Practice manager Power BI content](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/practice-manager-power-bi?toc=%2Fdynamics365%2Fcommerce%2Ftoc.json#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/practice-manager-power-bi.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/practice-manager-power-bi.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @KimANelson
* Microsoft Alias: **knelson**

**Comment by tonyafehr** [comment]
Thanks for contacting us. If you need immediate assistance, contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

@KimANelson, please review. Thanks!

**Comment by AnjaHCph** [comment]
Maybe I should note that I'm assuming that the Analysis tab under Project Management Workspace is identical to the Practice Manager BI, i.e. as described here https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/practice-manager-power-bi

**Comment by AnjaHCph** [comment]
At least if it depends on having a certain subscription to see the Analysis tab under the PM workspace, which was what my manager told me we didn't have. I'm still interested in knowing whether the practice manager dashboard is accessible to all users (with access to the project management module) of D365FO
