### ISSUE TITLE
Contradiction for the "Enable export of incremental updates" feature

### ISSUE THREAD

**Issue by phil896** [MicrosoftDocs/dynamics-365-unified-operations-public#2088]
I think there's a contradiction between the Finance and SCM sections for one product feature. In Finance, "Data management and integration &gt; Enable the export of incremental updates to a data entity" is listed as supported on-premise, but in SCM the same feature is listed as unsupported. Aren't they supposed to be the same product, and the feature should either be supported or unsupported in both? Which is it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e31272cf-a87f-0c73-631f-2829cf9ef1ff
* Version Independent ID: e81b0610-320c-eddc-fab2-557685148fc1
* Content: [Comparison of cloud and on-premises features](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/cloud-prem-comparison#feedback)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/cloud-prem-comparison.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/get-started/cloud-prem-comparison.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @sericks007
* Microsoft Alias: **sericks**

**Comment by sericks007** [comment]
@phil896, thanks for letting us know about this!  We'll look into it!

**Comment by sericks007** [comment]
@Sunil-Garg, please review and update the content as needed.

**Comment by sericks007** [comment]
Bug 422684 has been logged to track this issue.

**Comment by faix** [comment]
Hi @phil896, thanks for pointing it out we have updated the documentation.
