### ISSUE TITLE
Dev box VM VHD download not available anymore

### ISSUE THREAD

**Issue by shafee005** [MicrosoftDocs/dynamics-365-unified-operations-public#2092]
The option to download VM VHD is not available anymore.  The only deployment option available is Azure only.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 146a6e6a-4f26-195e-80fc-15b38d77b948
* Version Independent ID: 489070bf-affb-4d92-eeac-91cad7a2a889
* Content: [Sign up for preview subscriptions](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/sign-up-preview-subscription)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/sign-up-preview-subscription.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-tools/sign-up-preview-subscription.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **jorisde**

**Comment by tonyafehr** [comment]
@jorisdg, please review this feedback. Thanks!

**Comment by amithprasanna** [comment]
you can still download VM from Shared Asset Library in LCS

**Comment by shafee005** [comment]
That is what I thought untill i raised a ticket with MS support. I would recommend the article be updated to say it can be downloaded from asset library.

**Comment by tonyafehr** [comment]
Bug 419902 logged to track this issue.
