### ISSUE TITLE
Download VM VHD option not available anymore

### ISSUE THREAD

**Issue by shafee005** [MicrosoftDocs/dynamics-365-unified-operations-public#2093]
The downloadable VHD file is not available anymore. When we  go to LCS and create a new environment the only option available is to deploy the environment to Azure VM.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe3913a6-4daa-9973-6f0b-d7ae4c1007c2
* Version Independent ID: f2cd311b-fcb8-cff4-57a3-47c3c52b19d6
* Content: [Deploy and access development environments](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/access-instances#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/access-instances.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-tools/access-instances.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @jorisdg
* Microsoft Alias: **jorisde**

**Comment by tonyafehr** [comment]
@jorisdg, please review this feedback. Thanks!

**Comment by tonyafehr** [comment]
Bug 419902 logged to track this issue.

**Comment by jorisdg** [comment]
This doc was updated.
