### ISSUE TITLE
Need to update the Configure parameters that affect retail statements page

### ISSUE THREAD

**Issue by SiouxGrad** [MicrosoftDocs/dynamics-365-unified-operations-public#2094]
There are a lot of Parameters on the Posting tab in Commerce Parameters that are not listed on this page.

For example, all of the Statement options are missing, 3 of the Batch processing options are missing, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58187e29-636c-e83f-6dfd-8b36b4ccb8df
* Version Independent ID: c3d72dfc-16bc-5933-7933-4d1f6ea7f984
* Content: [Configure parameters that affect retail statements](https://docs.microsoft.com/en-us/dynamics365/commerce/tasks/parameter-configurations-retail-statements#feedback)
* Content Source: [articles/commerce/tasks/parameter-configurations-retail-statements.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/tasks/parameter-configurations-retail-statements.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by sericks007** [comment]
@SiouxGrad, thanks for posting here!

@josaw1, please review.

**Comment by josaw1** [comment]
@anpurush, can you please review?

**Comment by sericks007** [comment]
Bug 420272 has been logged to track this issue.

**Comment by sericks007** [comment]
We plan to remove this topic. The parameters are discussed in other topics.
