### ISSUE TITLE
How to Delete Model/Package in Finance and Operations

### ISSUE THREAD

**Issue by Bijan-Ghofranian** [MicrosoftDocs/dynamics-365-unified-operations-public#2095]
Here is a nice example by Akshay Thombare:

https://www.cloudfronts.com/how-to-delete-model-package-in-finance-and-operations/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f21baa4-903d-1a42-eaaf-4efe1ed1b951
* Version Independent ID: e8d91d54-a0f1-5958-0623-6c0c54ec0b8d
* Content: [Uninstall a package](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/uninstall-deployable-package?source=docs#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/uninstall-deployable-package.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/deployment/uninstall-deployable-package.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Manado
* Microsoft Alias: **jorisde**

**Comment by sericks007** [comment]
@Bijan-Ghofranian, thanks for posting here!

@jorisdg, please review.

**Comment by sericks007** [comment]
Bug 420270 has been logged to track this issue.
