### ISSUE TITLE
Formatting/code issues

### ISSUE THREAD

**Issue by danshewchuk** [MicrosoftDocs/dynamics-365-unified-operations-public#2097]
The first X++ example has spaces between the sentences, which it shouldn't have, and also isn't code-style formatted.
The first C# example says that it shows the differences by commenting out the X++ code, but there's no commented code in the example at all.
Also that C# code has some of the worst formatting styles I've ever seen.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d11321af-2262-6bd7-9a87-4f2fb66c4e41
* Version Independent ID: 013e0e52-b0d1-97d4-6911-b178828a7bfc
* Content: [X++ and C# comparison](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-ref/xpp-cs-comparison#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-ref/xpp-cs-comparison.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-ref/xpp-cs-comparison.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **rhaertle**

**Comment by sericks007** [comment]
@danshewchuk, thanks for posting here!

@RobinARH, please review.

**Comment by sericks007** [comment]
Bug 420268 has been logged to track this issue.

**Comment by RobinARH** [comment]
I made some small updates to the coding style. It should go live in the next couple of days. - Robin
