### ISSUE TITLE
Business events are not mentioned in relation to on-premis

### ISSUE THREAD

**Issue by amadse** [MicrosoftDocs/dynamics-365-unified-operations-public#2099]
In the comparison between cloud and on-premise deployment https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/cloud-prem-comparison Business events https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/business-events/home-page are not mentioned. If you run a 100% disconneted on-premise environment you are not able to use Business events, but what is possible in an on-premise connected environment?
This needs to be answered and added to the https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/cloud-prem-comparison page

**Comment by sericks007** [comment]
@Sunil-Garg, please add business events to the [Comparison of cloud and on-premises features](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/cloud-prem-comparison) topic.

**Comment by sericks007** [comment]
Bug 420267 has been logged to track this issue.

**Comment by Sunil-Garg** [comment]
Thanks for the feedback amadse. We have updated the on-prem feature list comparision accordingly. Thanks again.

**Comment by sericks007** [comment]
The updated content (that Sunil referred to above) will be published in the next day or so.
