### ISSUE TITLE
Viewing Custom Fields

### ISSUE THREAD

**Issue by axaeffect** [MicrosoftDocs/dynamics-365-unified-operations-public#2101]
I just add a custom fields in Sales Order form (so it goes to SalesTable). It already appeared in my form, but when I go to System administration &gt; Setup &gt; Custom fields, the list is empty.
Please help how to use it.
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f63be40-3dbb-c580-7f16-8e31c30a3a22
* Version Independent ID: 1f5647db-79ca-5bff-dc68-8b9d8bb533ef
* Content: [Create and work with custom fields](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/user-defined-fields#viewing-all-custom-fields)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/user-defined-fields.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/get-started/user-defined-fields.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by josaw1** [comment]
Thank you for your feedback. @jasongre please comment.

**Comment by josaw1** [comment]
BUG 421155 created to track issue.

**Comment by lalitjivnani** [comment]
On the custom fields form in system administration, i can see the list of custom fields added to multiple tables which is fine. But when i select any field and delete that field, the system is actually not deleting it. It reappears if i select the same table again.
Is there any bug associated with it ?
Current version - PU32 10.0.8
