### ISSUE TITLE
Network printer account

### ISSUE THREAD

**Issue by d-j-schmidt** [MicrosoftDocs/dynamics-365-unified-operations-public#2103]
Some additional detail about how to set the network printers' service account to the same as axservice.exe would be helpful.

https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/troubleshoot-on-prem#printing-randomly-stops

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41f27bdd-7361-5030-a00d-db0674f6f9bf
* Version Independent ID: 228e03d2-5dc7-e428-d475-aecde408edfa
* Content: [Troubleshoot on-premises deployments](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/troubleshoot-on-prem#printing-randomly-stops)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/troubleshoot-on-prem.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/deployment/troubleshoot-on-prem.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @sarvanisathish
* Microsoft Alias: **sarvanis**

**Comment by josaw1** [comment]
Thanks for your feedback. @sarvanisathish please comment.

**Comment by josaw1** [comment]
BUG 421154 created to track this issue.

**Comment by faix** [comment]
Hi @d-j-schmidt,

You can refer to the following document to learn more about how to correctly setup printers in onpremise environments. 

https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/install-network-printer-onprem

**Comment by josaw1** [comment]
Update will be published today. Thank you.
