### ISSUE TITLE
BPM New Experience - Could not Publish copy under Corporate libraries either use Configurations Options

### ISSUE THREAD

**Issue by Chrisslima** [MicrosoftDocs/dynamics-365-unified-operations-public#2104]
Dear all, 

It seems that all these steps refer to the Old Experience of BPM. It does not appear to me the option to "Publish" a library under "Global Libraries" (only Copy). How could I move a Global library to a Corporate library? I have a role of Project Owner.

Besides that, in this new experience, it's not possible either to add "Data Package", the "Configure Process" tab does not appear anymore. This presentation of 2017 suggests that it would be a tab "Configure" in this new experience, but I could not find it (https://mbspartner.microsoft.com/D365/Videos/101429).

I appreciate your support. 

Best regards, 

Christiane Lima

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7afb1aff-eb51-dc9b-003f-b7e73b4d5971
* Version Independent ID: 7ba9a433-f255-bf30-f7de-9124359eb05a
* Content: [Business process modeler library (updated BPM experience)](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lcs-solutions/business-process-modeler-libraries-updated-experience)
* Content Source: [articles/fin-ops-core/dev-itpro/lcs-solutions/business-process-modeler-libraries-updated-experience.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/lcs-solutions/business-process-modeler-libraries-updated-experience.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **omarc**

**Comment by sericks007** [comment]
@Chrisslima. thank you for this feedback!

@AngelMarshall, please review and update the content as needed.

**Comment by sericks007** [comment]
Bug 6312813 was logged in the LCS database to track this issue .

**Comment by AngelMarshall** [comment]
@Chrisslima - Thanks for reaching out. 
BPM no longer use the legacy user interface, we will update the content to reflect the new UI.  
The Global libraries are managed by Microsoft to publish cross-industry standard processes. As a LCS user, you can copy any libraries from the Global libraries to your Project libraries, make changes to align with your organization's process, and publish to the Corporate libraries to share with other LCS users within your organization. 
The Configure tab feature in the video was part of the disclaimer, not all features illustrated in this part will be implemented and there’s no commitment to the delivery of this functionality.   
However, you can still add data package and process data package via the LCS Asset library.  
Hope that helps answering your question.
