### ISSUE TITLE
Retail to Commerce?

### ISSUE THREAD

**Issue by bebeale** [MicrosoftDocs/dynamics-365-unified-operations-public#2105]
Should this page be updated to "Commerce Hierarchies"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7eecb3b-5c30-e017-981f-8e0d00c5ada8
* Version Independent ID: a20d28cc-f636-0306-7303-d44b79651268
* Content: [Retail hierarchies](https://docs.microsoft.com/en-us/dynamics365/commerce/retail-hierarchies#feedback)
* Content Source: [articles/commerce/retail-hierarchies.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/retail-hierarchies.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @jblucher
* Microsoft Alias: **jeffbl**

**Comment by josaw1** [comment]
Hi, thanks for the comment. I'll make the change and publish today. Thanks.
