### ISSUE TITLE
Sales Tax Groups: Call Center Defaults

### ISSUE THREAD

**Issue by ransoentjens** [MicrosoftDocs/dynamics-365-unified-operations-public#2107]
On the sales tax groups setup form: What is the purpose of the Call Center Defaults configuration and HOW does it impact the call center sales order process?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 777ec7a1-9fed-a203-b352-23a01b80fae9
* Version Independent ID: 11351051-1028-89a4-0e37-40ce74c8a494
* Content: [Sales tax overview](https://docs.microsoft.com/en-us/dynamics365/finance/general-ledger/indirect-taxes-overview?toc=/dynamics365/commerce/toc.json)
* Content Source: [articles/finance/general-ledger/indirect-taxes-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/general-ledger/indirect-taxes-overview.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @ShylaThompson
* Microsoft Alias: **vstehman**

**Comment by josaw1** [comment]
Thank you for your feedback. @hhainesms, can you please take a look at this?
