### ISSUE TITLE
Table Permission Framework

### ISSUE THREAD

**Issue by tomhig** [MicrosoftDocs/dynamics-365-unified-operations-public#211]
There needs to be a little more explanation of what exactly the Table Permission Framework (TPF) is and how/why it would be used. The only reference for this is in the AX2012 documentation at the following: https://technet.microsoft.com/en-us/library/dd309699.aspx. So, unless one knows that TPF originated in AX2012, one wouldn't know to look there. Perhaps a link to this document? Or, better yet, a more comprehensive description of what TPF is, its benefit, and why one would use it in the D365 docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13fb1d17-679e-8b93-ffbe-eaa340050068
* Version Independent ID: 3fb88067-ab44-4bfb-729b-6191ee86f4cc
* Content: [Security architecture - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/sysadmin/security-architecture)
* Content Source: [articles/dev-itpro/sysadmin/security-architecture.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/sysadmin/security-architecture.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @sarvanisathish
* Microsoft Alias: **sarvanis**

**Comment by ShylaThompson** [comment]
bug logged: 228907

**Comment by batetech** [comment]
It is important to note that the "AOS Authorization" property cannot be changed via table extensions in D365FO (at least as of PU12), so can't be changed for any "out of box" standard tables.

**Comment by amadse** [comment]
If it is not in the extensions, why is not mentioned here:
https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/ax-2012-features-not-implemented-but-not-deprecated  or
https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/deprecated-features

**Comment by sericks007** [comment]
@ChrisGarty, please review this issue and update the content, as needed.

**Comment by amadse** [comment]
Why is this closed?

Anders Madsen
Prin Consultant Erp
Microsoft Global Domain
Denmark
Office: +45 (45) 678213
Mobile: +45 29499831
amadse@microsoft.com<mailto:amadse@microsoft.com>

[Microsoft Logo]
If you have any feedback about my work, please let either me or my manager Christian Appel Christian.Appel@microsoft.com<mailto:Christian.Appel@microsoft.com> know.
