### ISSUE TITLE
Page need updates

### ISSUE THREAD

**Issue by kristyler** [MicrosoftDocs/dynamics-365-unified-operations-public#2111]
This page should be updated when the l updates. There is new functionality that needs covered. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 621ba770-ffc3-8f2f-7f68-b3ec64424932
* Version Independent ID: 47db56b9-54db-c452-837f-b2ec5e7b0207
* Content: [Regression suite automation tool](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/perf-test/rsat/rsat-overview)
* Content Source: [articles/fin-ops-core/dev-itpro/perf-test/rsat/rsat-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/perf-test/rsat/rsat-overview.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @robadawy
* Microsoft Alias: **robadawy**

**Comment by robadawy** [comment]
The documentation has been updated last week. Any specific functionality you cannot find?

**Comment by gpatelqa** [comment]
Performance feature is missing in the documentation.
