### ISSUE TITLE
page updates

### ISSUE THREAD

**Issue by kristyler** [MicrosoftDocs/dynamics-365-unified-operations-public#2112]
Are we still on v3.13? RSAT keeps rolling back the chromedriver to v78, though Chrome is now at v80.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2458b41-99e9-53ff-b898-cdd957c1c924
* Version Independent ID: 9aad0fcb-b367-136a-9fb0-d8d04a2cfc33
* Content: [Regression suite automation tool installation and configuration](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/perf-test/rsat/rsat-install-configure#install-selenium-drivers)
* Content Source: [articles/fin-ops-core/dev-itpro/perf-test/rsat/rsat-install-configure.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/perf-test/rsat/rsat-install-configure.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @robadawy
* Microsoft Alias: **robadawy**

**Comment by robadawy** [comment]
The current RSAT release is not compatible with Chrome 80. It uses Chrome Driver 78 for Chrome version 78 and 79.  A new version of RSAT that is compatible (and downloads driver > 78) will be available this week.

The fix is part of RSAT version 1.200.45072.6. This will be released on or before February  21, 2020.  The latest official version of RSAT is always available at https://www.microsoft.com/en-us/download/details.aspx?id=57357

**Comment by kristyler** [comment]
I did not see that warning in the documentation. Since Google Chrome autoupdates, and requires a substantial effort to stop those updates, instructions and warnings to that affect should have been in your documentation with the download.

[cid:image001.jpg@01D5E6FE.BC93C460]
Kris​ Tyler
Data Analyst
2321 N Loop Dr, Ste 220
,
Ames
,
IA
,
50010
O: (515) 817-2143<tel:(515)%20817-2143>
LandusCooperative.com<http://www.landuscooperative.com/>
  |
Kris.Tyler@landuscooperative.com<mailto:Kris.Tyler@landuscooperative.com>
This email is intended for the use of the person to whom it is addressed and may contain information that is privileged and confidential, the disclosure of which is governed by applicable law. Dissemination, distribution or copying of this information in an unauthorized manner is strictly prohibited. Sender accepts no liability for any damage caused by any virus transmitted by this email. If you receive this email in error, please notify the sender.
