### ISSUE TITLE
Missing information on edit method modifier

### ISSUE THREAD

**Issue by SysC0mp** [MicrosoftDocs/dynamics-365-unified-operations-public#2116]
I was not able to find any additional information for edit / display methods that applies to D365? (for example on the caching behaviour) Where can i find that in the documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51bd2787-887e-c0b8-176e-1fb26c7de95b
* Version Independent ID: 1cd60a0e-3def-e4b0-7abe-4b36bec753a2
* Content: [X++ language reference](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-ref/xpp-language-reference)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-ref/xpp-language-reference.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-ref/xpp-language-reference.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **rhaertle**

**Comment by tonyafehr** [comment]
@RobinARH, please review this feedback. Thanks!

**Comment by tonyafehr** [comment]
Bug 422221 logged to track this issue.

**Comment by pvillads** [comment]
There is nothing new about edit and display methods in F&O. The semantics (as described here: https://docs.microsoft.com/en-us/dynamicsax-2012/developer/using-the-display-method-modifier) are identical from 2012 to now,

**Comment by SysC0mp** [comment]
Thanks for the info! I know about the AX 2012 documentation, but as a developer you cannot safely know at the moment what applies to D365 and what not. Maybe the "Applies to" information at the top should be updated to include that information.

The link also does not include any information about the caching behavior of edit methods, only the display modifier is described here: 
https://docs.microsoft.com/en-us/dynamicsax-2012/developer/caching-display-methods
But there is no information about the new SysClientCacheDataMethod attribute which should be used instead of cacheAddMethod on the form.

**Comment by pvillads** [comment]
Forwarding to @Haytham Said<mailto:Haytham.Said@microsoft.com> who may now those details.

**Comment by SysC0mp** [comment]
Any news on that? The D365 documentation is still lacking any information about the SysClientCacheDataMethod attribute or its usage.
