### ISSUE TITLE
Purchasing Card Processing

### ISSUE THREAD

**Issue by MMT0905** [MicrosoftDocs/dynamics-365-unified-operations-public#2117]
I cannot find any additional information on what type of public sector configuration needs to be made in order to have the "active purchasing cards" option available on the AP parameters. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e915b2ff-55b1-8e5a-0302-1e1c6efd25af
* Version Independent ID: bb4828c1-3b1d-daa5-c9b8-755e1d790332
* Content: [Purchasing cards](https://docs.microsoft.com/en-us/dynamics365/finance/public-sector/purchasing-cards)
* Content Source: [articles/finance/public-sector/purchasing-cards.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/public-sector/purchasing-cards.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @velofog
* Microsoft Alias: **v-alpavk**

**Comment by velofog** [comment]
You need to have the public sector configuration key active and enable the feature in feature management before you can enable the feature in Accounts Payable parameters

**Comment by MMT0905** [comment]
I would recommend adding that there is a prerequisite of having version 10.0.8 or higher, and enabling the Purchasing Card Processing in Feature Management.
