### ISSUE TITLE
Location of task guide

### ISSUE THREAD

**Issue by sbaber82** [MicrosoftDocs/dynamics-365-unified-operations-public#2119]
[Hi, I want to know where to find the task guide which is mentioned in the doc site. I tried to search it under Business process modeler in LCS, but couldn't find it. The task guide that I am referring to is mentioned below:
]
ER Create a format configuration to import data from an external CSV file (part of the 7.5.4.3 Acquire/Develop IT service/solution components (10677) business process)

Thanks,
Baber.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8821b49e-a196-7bd6-18e1-a01c69759b90
* Version Independent ID: 8c6f9824-4779-d837-7512-4629e8beb57a
* Content: [Parse incoming documents](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/er-parse-incoming-documents?toc=/dynamics365/commerce/toc.json)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/er-parse-incoming-documents.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/er-parse-incoming-documents.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @NickSelin
* Microsoft Alias: **nselin**

**Comment by NickSelin** [comment]
Hello Baber!

Please, cofigure the [Help system](https://docs.microsoft.com/dynamics365/fin-ops-core/fin-ops/get-started/help-overview) of your Finance instance to access the [March 2018 - All languages APQC Unified Library for Microsoft Dynamics 365 for Finance and Operations](https://bpm.lcs.dynamics.com/Home/App/1092654#/framework/200943) BPM library of the **APQC Unified Library Project 2** LCS project. The mentioned guide is named in ths library as **ER Design a configuration to import data from an external file in CSV format (7.3 Update)** and can be found  by using the **Process \> 
Manage IT \> Develop and maintain IT solutions \> Create IT services and solutions \> Acquire/Develop IT service/solution components** path.

Best regards,
Nick Selin

**Comment by sbaber82** [comment]
Hello Nick,

I can see the help system is configured under System parameters -> Help tab. I can see the library that you mentioned above. When I click on the Help icon -> Task guides tab, it doesn't load any thing and I got the following message:

We couldn't find any task guides for this page.
There are results on the help tab to review.
To help us improve our documentation, tell us what page you're on and what task you're trying to complete.

**Comment by NickSelin** [comment]
Hello Baber!

You need to perform the following steps:
1. Click the **Settings** icon on the top-most ribbon of the page (on the left from the **Help** icon).
2. Select the **Task recorder** option.
3. From the offered actions, select the **Play recording as guide** one.
4. Select the **Open from Lifecycle Services** source.
5. Click **Select the Lifecycle Services library** button.
6. Select the APQC library.
7 Browse to find the item APQC > Manage Information Technology > Develop and maintain information technology solutions > Create IT services and solutions > Acquire/Develop IT service/solution components >  ER Design a configuration to import data from an external file in CSV format (7.3 Update).
8. Select this guide and play it.

Best regards,
Nick Selin

**Comment by sbaber82** [comment]
Hi Nick,

It shows me only one library which has the customer name in it and not showing any other library starts with APQC.

**Comment by sbaber82** [comment]
It only shows me the BPM library which is under the customer LCS Project. Hope you understand my point.

**Comment by NickSelin** [comment]
Hello Baber!

Looks like you have access to the only project BPM libraries while the access to global BPM libraries is required. Please, contact your system administrator to have permission to access from Finance global BPM libraries of your project.
Alternatively, if you can sign in to LCS and access global BPM libraries by using a web browser - you can find the list of steps of the mentioned above task guide.

Best regards,
Nick Selin

**Comment by sbaber82** [comment]
Hi Nick,

I have found the BPM library on the path you mentioned above. Was not opening yesterday, so I couldn't see this. When I selected the library, I cannot see any option to play from here. Does it need to be played from D365 environment using Play recording as Task guide option ? Can I not play this one from LCS - > BPM ?

**Comment by sbaber82** [comment]
Please note that I am the Project owner in LCS Project, but I cannot see any other library to select when I am selecting BPM library under System parameters page. Please let me know how can I select other libraries in System parameters -> Help page ?

**Comment by NickSelin** [comment]
Hello Baber!

You can't play a task guide from LCS\BPM as any guide consist of the set of steps that are designed to perform certain actions in Finance user interface. Such steps are not playable in LCS\BPM. Until this guide is not loadable from LCS to you, you can read this guide’s steps in LCS and try to execute them in Finance. 

To resolve your issue with  other BPM libraries access, please report a service request - it is not related to the topic describing in this page.

Best regards,
Nick Selin

**Comment by JTWWI** [comment]
> Hello Baber!
> 
> You need to perform the following steps:
> 
>     1. Click the **Settings** icon on the top-most ribbon of the page (on the left from the **Help** icon).
> 
>     2. Select the **Task recorder** option.
> 
>     3. From the offered actions, select the **Play recording as guide** one.
> 
>     4. Select the **Open from Lifecycle Services** source.
> 
>     5. Click **Select the Lifecycle Services library** button.
> 
>     6. Select the APQC library.
>        7 Browse to find the item APQC > Manage Information Technology > Develop and maintain information technology solutions > Create IT services and solutions > Acquire/Develop IT service/solution components >  ER Design a configuration to import data from an external file in CSV format (7.3 Update).
> 
>     7. Select this guide and play it.
> 
> 
> Best regards, Nick Selin

This worked for me! Thanks again.  Now... if this guidance can just be linked somewhere in the MS Learn Documentation. :-)
