### ISSUE TITLE
Incorrect 'issuer' value

### ISSUE THREAD

**Issue by Pikhulya** [MicrosoftDocs/dynamics-365-unified-operations-public#212]
Please update the section "Finish the Retail Store Scale Unit configuration in headquarters" - its bullet #6 says that the Url should resemble `https://MyComputerName/RetailServer/auth` which is not precise because MyComputerName should be followed by the port number if one exists.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 915a525f-f660-5cb2-fa18-be1a059acdbb
* Version Independent ID: 61eca697-a18c-f7a5-cc53-8331dcf3ff64
* Content: [Retail Store Scale Unit configuration and installation - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/dev-itpro/retail-store-scale-unit-configuration-installation#finish-the-retail-store-scale-unit-configuration-in-headquarters)
* Content Source: [articles/retail/dev-itpro/retail-store-scale-unit-configuration-installation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/dev-itpro/retail-store-scale-unit-configuration-installation.md)
* Service: **dynamics-365-retail**
* GitHub Login: @jashanno
* Microsoft Alias: **jashanno**

**Comment by ShylaThompson** [comment]
Bug logged: 228908

**Comment by ShylaThompson** [comment]
@Pikhulya, thanks again for suggesting this fix. The topic is updated now.
