### ISSUE TITLE
Unrelated topic

### ISSUE THREAD

**Issue by ELandAX** [MicrosoftDocs/dynamics-365-unified-operations-public#2121]
How is this topic (Create a record template to facilitate data entry) and the other one (Create records using record templates) related to Data integration using data entities? :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ede22ec-5fee-7374-a723-1f1bdf464854
* Version Independent ID: 09239542-e16a-1723-ab5b-2a56cc6c8c01
* Content: [Create a record template to facilitate data entry](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/tasks/create-record-template-facilitate-data-entry)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/tasks/create-record-template-facilitate-data-entry.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/tasks/create-record-template-facilitate-data-entry.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @MargoC
* Microsoft Alias: **margoc**

**Comment by tonyafehr** [comment]
@RobinARH, please review. Thanks!

**Comment by tonyafehr** [comment]
Bug 422232 logged to track this issue.

**Comment by RobinARH** [comment]
[Create a record template to facilitate data entry](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/tasks/create-record-template-facilitate-data-entry) is the more detailed example, but the other one isn't incorrect. We probably don't need both, but removing the other doesn't meet our bug bar.
