### ISSUE TITLE
Development Limitations

### ISSUE THREAD

**Issue by gcantin** [MicrosoftDocs/dynamics-365-unified-operations-public#2122]
Any reason that there is no mention of the development limitations with these types of fields? These aren't accessible in the back end. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f63be40-3dbb-c580-7f16-8e31c30a3a22
* Version Independent ID: 1f5647db-79ca-5bff-dc68-8b9d8bb533ef
* Content: [Create and work with custom fields](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/user-defined-fields)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/user-defined-fields.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/get-started/user-defined-fields.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by tonyafehr** [comment]
@jasongre, please review this feedback. Thanks!

**Comment by tonyafehr** [comment]
Bug 422234 logged to track this issue.
