### ISSUE TITLE
Distributions/ledger account clarity

### ISSUE THREAD

**Issue by PeterJarret** [MicrosoftDocs/dynamics-365-unified-operations-public#2129]
There are no details provided about the ledger account and we faced issues when trying to use this functionality.  Looking back at the documentation for AX 2012, this is called dimensions and there is a bit more information about how "If the file you import has financial dimensions, you need to include all of the financial dimensions with the proper naming, otherwise an error message will appear stating that the ledger dimension is invalid. You’ll then need to either correct the financial dimensions or remove the columns from the file.".  This pointed us to a solution whereby we have columns for each dimension in the file, with the correct naming.  I feel that having a little more information on this page for Ledger Account would help people to avoid this confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53131fa0-be2f-1d0a-1e2f-653fc703f5fc
* Version Independent ID: ae64bc34-046a-820e-54bd-62e2a70cc4f4
* Content: [Plan for one-time vendors in the public sector](https://docs.microsoft.com/en-us/dynamics365/finance/public-sector/plan-one-time-vendors-public-sector#feedback)
* Content Source: [articles/finance/public-sector/plan-one-time-vendors-public-sector.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/public-sector/plan-one-time-vendors-public-sector.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @ShylaThompson
* Microsoft Alias: **brpotter**

**Comment by sericks007** [comment]
@PeterJarret, thanks for providing this feedback!

@roschlom, please review.

**Comment by sericks007** [comment]
Bug 422667 has been logged to track this issue.

**Comment by roschlom** [comment]
The topic has been updated in response to the feedback. Thanks again for the input.
