### ISSUE TITLE
Allow root navigation

### ISSUE THREAD

**Issue by jatomas** [MicrosoftDocs/dynamics-365-unified-operations-public#213]
Hi, the deep link doesn't work unless you set the property "Allow Root Navigation" of the Menu Item set to YES.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cb4331e-2b34-5622-d826-f01354178807
* Version Independent ID: 1df56697-ba62-5d04-d86c-bd87f9255f7e
* Content: [Create and use deep links - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/user-interface/create-deep-links)
* Content Source: [articles/dev-itpro/user-interface/create-deep-links.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/user-interface/create-deep-links.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RobinARH
* Microsoft Alias: **shshabazz**

**Comment by jasongre** [comment]
Thanks for the feedback. You are correct as only root navigable forms can be accessed by URL. We'll get the article updated to reflect that.

**Comment by ShylaThompson** [comment]
The topic has been updated and changes will go live at the end of today.
