### ISSUE TITLE
Custom menu buttons

### ISSUE THREAD

**Issue by iamJoshKnox** [MicrosoftDocs/dynamics-365-unified-operations-public#2135]
What controls how a button displays in the action search results?  I have a custom button not displaying in the action search, though most others do.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41d6d137-69fb-f35b-4d4b-48eece7aff65
* Version Independent ID: a3029eb3-455b-3ff3-9b56-730f2756fbb4
* Content: [Action search](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/action-search?toc=/dynamics365/commerce/toc.json)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/action-search.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/get-started/action-search.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by sericks007** [comment]
@iamJoshKnox, thanks for your feedback!  You might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community. 

@jasongre, please review and consider updating the content.

**Comment by sericks007** [comment]
Bug 422683 has been logged to track this issue.

**Comment by jasongre** [comment]
@iamJoshKnox, a few classes of buttons are not yet supported in Action search. These include drop dialog buttons and buttons from subforms (i.e. those inside FormPart controls). I'll adjust the article to explicitly mention this.

**Comment by iamJoshKnox** [comment]
Thanks!!!
