### ISSUE TITLE
Update settings tab disappeared

### ISSUE THREAD

**Issue by Mund75** [MicrosoftDocs/dynamics-365-unified-operations-public#2137]
After today's One Version update tab Update Settings disappeared, why?
Where is now the place to change maintenance window time?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcff93b4-d765-642b-f4ba-911b05344216
* Version Independent ID: be01a4e8-ba6f-8ac4-fbe3-7db75de310e8
* Content: [Configure service updates through Lifecycle Services (LCS)](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/configure-service-updates#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/configure-service-updates.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/lifecycle-services/configure-service-updates.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @manalidongre
* Microsoft Alias: **manado**

**Comment by sericks007** [comment]
@Mund75, thank you for your feedback!

@AngelMarshall, please review and consider updating the content.

**Comment by AngelMarshall** [comment]
@Mund75, there's no change on the Update settings tab.  If you're not able to see the Update setting tab in your LCS implementation project, please submit a support case.
