### ISSUE TITLE
Composite entities do not support multi-threaded import

### ISSUE THREAD

**Issue by MartinWalkerDynSA** [MicrosoftDocs/dynamics-365-unified-operations-public#2138]
Recommend we add a note that currently (as of PU32), entity import execution parameters will be ignored for a composite entity. If you are importing a composite entity, it will always be executed via the Async framework, and will be single threaded only.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0198d960-ca6c-4d08-36e0-b5061e13a784
* Version Independent ID: 6e445b8a-8906-f8a8-5dda-d177ae12e3db
* Content: [Develop composite data entities](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/develop-composite-data-entities#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/develop-composite-data-entities.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/develop-composite-data-entities.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by josaw1** [comment]
Thank you for the comment. @Sunil-Garg can you please consider this?

**Comment by josaw1** [comment]
BUG 425895 created to track this issue.

**Comment by Sunil-Garg** [comment]
The doc has been updated to call out that parallel processing is not supported for composite entities. However, pls note that, composite entities can be processed in async, sync or batch.

Thanks.
