### ISSUE TITLE
Add information about entity import execution parameters

### ISSUE THREAD

**Issue by MartinWalkerDynSA** [MicrosoftDocs/dynamics-365-unified-operations-public#2139]
It seems the only place on docs where we discuss using entity import execution parameters to speed up imports is under "Tips for speeding up the import process" at https://docs.microsoft.com/en-us/dynamics365/finance/localizations/rus-russian-address-format-and-import-from-fias#fias-import. Recommend we add the instructions here too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d35f4fb2-1296-20ef-56c2-a2c5aa00befe
* Version Independent ID: 0d515af9-9419-4f21-223e-25344cf1bfe8
* Content: [Data import and export jobs overview](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/data-import-export-job)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/data-import-export-job.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/data-import-export-job.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by josaw1** [comment]
Thank you for your feedback. @Sunil-Garg can you please take a look?

**Comment by josaw1** [comment]
BUG 425891 created to track the issue.

**Comment by josaw1** [comment]
Sunil updated the topic and it will go live shortly. Thanks.
