### ISSUE TITLE
End of Service for Application release 8.0

### ISSUE THREAD

**Issue by nbrowne1** [MicrosoftDocs/dynamics-365-unified-operations-public#214]
Is April 2019 actually end of service for Application release 8.0 or a typo? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcdefbcf-c3ad-9b1f-0988-452cea3e2108
* Version Independent ID: 7e002437-1ad9-ca29-7844-87e6709fe0fe
* Content: [Software lifecycle policy and cloud releases - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/versions-update-policy)
* Content Source: [articles/dev-itpro/migration-upgrade/versions-update-policy.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/migration-upgrade/versions-update-policy.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RyanCCarlson2
* Microsoft Alias: **rcarlson**

**Comment by MargoC** [comment]
That's the actual end of service date.
