### ISSUE TITLE
Master Records are Updated?

### ISSUE THREAD

**Issue by JoelLeichty** [MicrosoftDocs/dynamics-365-unified-operations-public#2140]
"If records already exist for the dimension, the master records are updated when you turn the feature on. However, existing documents and transactions aren't updated."

I'm not sure this is a factual statement? This suggests if I turn on this checkbox for Customer entity backed dimension, all existing customer records will be updated with this value? Is it only if I'm activating a new Dimension, not updating the flag for an already active dimension?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f8e6e20-9256-438b-597d-0e1cda7a8f6b
* Version Independent ID: b3539dbe-9ba8-db50-778f-ef6bfdd490ba
* Content: [Financial dimensions](https://docs.microsoft.com/en-us/dynamics365/finance/general-ledger/financial-dimensions#feedback)
* Content Source: [articles/finance/general-ledger/financial-dimensions.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/general-ledger/financial-dimensions.md)
* Service: **dynamics-ax-applications**
* Technology: ****
* GitHub Login: @aprilolson
* Microsoft Alias: **aolson**

**Comment by roschlom** [comment]
Thank you for your comment. We'll look into it further.

**Comment by roschlom** [comment]
Bug 565956 was created to track this issue.

**Comment by RyanCCarlson2** [comment]
For @JoelLeichty the statement is true. If the dimension setting is off, and you turn it on (for customers for example) it will copy the account value to that default financial dimension on dimension activation(required after a setting change).

**Comment by RyanCCarlson2** [comment]
@roschlom  can you close this issue accordingly?
