### ISSUE TITLE
Why is this under the Commerce pages?

### ISSUE THREAD

**Issue by assofohdz** [MicrosoftDocs/dynamics-365-unified-operations-public#2143]
Why is this under the Commerce pages?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5735746a-048b-ca95-dccb-feae57035123
* Version Independent ID: 84c9e5f8-dab5-8d8a-ed6f-011916758039
* Content: [Learning catalog for Finance and Operations](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/learning-catalog?toc=/dynamics365/commerce/toc.json)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/learning-catalog.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/get-started/learning-catalog.md)
* GitHub Login: @loreleishannonmsft
* Microsoft Alias: **v-lshann**

**Comment by RobinARH** [comment]
@josaw1 Hi Jo - Can you take a look? Thanks.

**Comment by assofohdz** [comment]
My point was merely, is there also such a page under the non Commerce pages of FinOps ? :)

**Comment by josaw1** [comment]
Hi, yes it is under the other applications. For example, here it is under Dynamics 365 Finance: https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/learning-catalog?toc=/dynamics365/finance/toc.json.

Thanks.

**Comment by assofohdz** [comment]
Thanks for the swift answer to something I could have found if I had made the effort. Apologies for that :)
