### ISSUE TITLE
 is not recognized as the name of a cmdlet, function, s

### ISSUE THREAD

**Issue by Bijan-Ghofranian** [MicrosoftDocs/dynamics-365-unified-operations-public#2146]

**Comment by jorisdg** [comment]
@Bijan-Ghofranian can you provide a description of your issue? Unfortunately with only half a title which looks like an error message of sorts, I'm not sure we can respond or take action.
Thanks!

**Comment by Bijan-Ghofranian** [comment]
Hi Joris,

My apologies, I was trying to delete this and create a new one, but then
got busy and forgot.
So, please delete this as I submitted a new one.  The issue has to do with
missing Commandlet Connect-Msolservice. It looks like this module is
missing. I found a solution but did not want to uninstall and re-install
the PowerShell. I wonder if that missing module can be copied and /or
loadad. If yes where can I download from.

Thanks - Bijan

**Comment by RobinARH** [comment]
Bug 424207 created to track this issue.
