### ISSUE TITLE
page not uptodate

### ISSUE THREAD

**Issue by jansenrf** [MicrosoftDocs/dynamics-365-unified-operations-public#2149]
The page is old. The performance monitor screenshots are old. Can you give me another page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a59d9fd-8c46-120c-efb1-ef73b158ac33
* Version Independent ID: 6ec54ef7-cbbb-32f3-42c7-ac695d3b94bd
* Content: [Performance troubleshooting using tools in Lifecycle Services (LCS)](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/performancetroubleshooting#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/performancetroubleshooting.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/lifecycle-services/performancetroubleshooting.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @manalidongre
* Microsoft Alias: **manado**

**Comment by tonyafehr** [comment]
@laneswenka, please review.

**Comment by tonyafehr** [comment]
Bug 426859 logged to track this issue.
