### ISSUE TITLE
What happens next?

### ISSUE THREAD

**Issue by TheMartha** [MicrosoftDocs/dynamics-365-unified-operations-public#2150]
Hi, great article. 
I would like to know how will the data be populated in the storage location. 
Will it be a copy of the Entity Store. 
Will it allow external data also (like other databases?) 
Or will it be exactly the same just bigger and faster?
Thanks in advance :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a344a5de-68fa-e9cf-28eb-51269c33b9b3
* Version Independent ID: 1b3ede62-3954-574b-5778-8cdee0ededfe
* Content: [Make Entity store available as a Data Lake](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/entity-store-data-lake?toc=%2Ffin-and-ops%2Ftoc.json#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/entity-store-data-lake.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/entity-store-data-lake.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by tonyafehr** [comment]
@TheMartha, thanks for the feedback. If you need immediate assistance, here are your [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). You might also want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

@MilindaV2, please review. Thanks!

**Comment by tonyafehr** [comment]
Bug 424471 has been logged to track this issue.

**Comment by TheMartha** [comment]
Hi team, 

I have been in the Dynamics 365 pages - that is why I am asking all this questions :)
Very interested in the topic

**Comment by HugoDJesus** [comment]
> Hi, great article.
> I would like to know how will the data be populated in the storage location.
> Will it be a copy of the Entity Store.
> Will it allow external data also (like other databases?)
> Or will it be exactly the same just bigger and faster?
> Thanks in advance :)
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: a344a5de-68fa-e9cf-28eb-51269c33b9b3
> * Version Independent ID: 1b3ede62-3954-574b-5778-8cdee0ededfe
> * Content: [Make Entity store available as a Data Lake](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/entity-store-data-lake?toc=%2Ffin-and-ops%2Ftoc.json#feedback)
> * Content Source: [articles/fin-ops-core/dev-itpro/data-entities/entity-store-data-lake.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/entity-store-data-lake.md)
> * Service: **dynamics-ax-platform**
> * Product: ****
> * Technology: ****
> * GitHub Login: @MilindaV2
> * Microsoft Alias: **milindav**

Once the use of Data Lake in Tier 1 environments is configured, is it possible to activate the Power BI embedded in one box environments?

**Comment by josaw1** [comment]
@MilindaV2 can you please take a look?

**Comment by MilindaV2** [comment]
We have provided additional information in recent articles under "export to Data lake" section below
[https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/azure-data-lake-overview](url)

You can also see demos and an overview of the roadmap in our MBAS session below
[https://mymbas.microsoft.com/sessions/46c51e7e-f1bb-4424-8772-13f89a5e3c3b?source=sessions](url)
