### ISSUE TITLE
Upload Capability

### ISSUE THREAD

**Issue by ajb-hso** [MicrosoftDocs/dynamics-365-unified-operations-public#2151]
This document makes no reference to upload capability of the PCard feature.  Is there any upload capability other than current D365 upload functionality?  If not, can we expect upload capabilities in the future?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e915b2ff-55b1-8e5a-0302-1e1c6efd25af
* Version Independent ID: bb4828c1-3b1d-daa5-c9b8-755e1d790332
* Content: [Purchasing cards](https://docs.microsoft.com/en-us/dynamics365/finance/public-sector/purchasing-cards#feedback)
* Content Source: [articles/finance/public-sector/purchasing-cards.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/public-sector/purchasing-cards.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @velofog
* Microsoft Alias: **v-alpavk**

**Comment by tonyafehr** [comment]
@velofog, please review this feedback and consider updating this topic.

**Comment by tonyafehr** [comment]
Bug 424469 logged to track this issue.

**Comment by velofog** [comment]
Hi, we have updated the standard data entities to include the P-card fields.

**Comment by ajb-hso** [comment]
Hi:

Thanks for the update.  Do you have any indication as to when this be available in D365??

Thanks.

Andrew Bernstein MCP, MCSD
Senior Consultant

[cid:image001.png@01D5F152.D58B5BF0]
M (813) 382.6913
E abernstein@hso.com <mailto:abernstein@hso.com>  W www.hso.com <http://www.hso.com/>  L Linkedin<http://www.linkedin.com/> T Twitter<https://twitter.com/HSODynamicsAX>

Looking for the right tools to digitally transform your business? Learn how<https://www.hso.com/en-us/news-blogs-events/> Microsoft and HSO can help

**Comment by velofog** [comment]
The data entity updates were included in the 10.0.9 release.

**Comment by ajb-hso** [comment]
Thanks for the update!

Thanks.

Andrew Bernstein MCP, MCSD
Senior Consultant

[cid:image001.png@01D5F156.ADCD92F0]
M (813) 382.6913
E abernstein@hso.com <mailto:abernstein@hso.com>  W www.hso.com <http://www.hso.com/>  L Linkedin<http://www.linkedin.com/> T Twitter<https://twitter.com/HSODynamicsAX>

Looking for the right tools to digitally transform your business? Learn how<https://www.hso.com/en-us/news-blogs-events/> Microsoft and HSO can help

**Comment by ajb-hso** [comment]
HI:

I am searching the data entities to locate the updates for PCard fields and have not been able to locate the entity or entities.  Please let me know which entities have been updated to include PCard data.

Thanks.

**Comment by kfend** [comment]
Re-opening this issue as there is another question. Closing the duplicate issue that was opened today. 
@velofog - Can you help out with this? Thanks!

**Comment by velofog** [comment]
Here are the data entities related to Pcard:

Bank purchasing card setup...this entity creates the Pcard records  | PSNBankPurchasingCardEntity
Posted Vendor transactions purchasing card information...this entity is to export posted pcard transactions (ReadOnly) | PSNVendTransPurchasingCardEntity
Vendor invoice   header...pcard fields were added | VendorInvoiceHeaderEntity
Vendor parameters...pcard fields were added | VendVendorParametersEntity

**Comment by ajb-hso** [comment]
Many thanks

Thanks.

Andrew Bernstein MCP, MCSD
Senior Consultant

[cid:image001.png@01D6069C.1BEDEA50]
M (813) 382.6913
E abernstein@hso.com <mailto:abernstein@hso.com>  W www.hso.com <http://www.hso.com/>  L Linkedin<http://www.linkedin.com/> T Twitter<https://twitter.com/HSODynamicsAX>

Looking for the right tools to digitally transform your business? Learn how<https://www.hso.com/en-us/news-blogs-events/> Microsoft and HSO can help

**Comment by ajb-hso** [comment]
Hi:
We have enabled the PCard feature in update 33 (10.0.9) and we are able to use the feature.  However, I have reviewed the entities listed below and it looks as if the PCard fields have not been added:
- Vendor invoice header
- Vendor Parameters

Additionally, both PSN entities (BankPurchasingCardEntity and VendTransPurchasingCardEntity) are not listed.

Am I missing something??
