### ISSUE TITLE
Windows Server 2019 Compatability

### ISSUE THREAD

**Issue by AndrewMaisey** [MicrosoftDocs/dynamics-365-unified-operations-public#2155]
Hi MS Team, I'm hoping to get some information about official Dynamics 9.x (and 8.x) support on Windows Server 2019. Community forums suggest this is technically possible, but is it to be officially Microsoft supported? Thank you.

(I have posted same question on the Customer Engagement page also as it would be good to know for both product variants).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc242273-ee42-3973-cc47-aece5771ca1f
* Version Independent ID: 0cf0f65b-6187-104a-8228-3c1431225267
* Content: [System requirements for on-premises deployments](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/system-requirements-on-prem?source=docs#feedback)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/system-requirements-on-prem.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/get-started/system-requirements-on-prem.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **kfend**

**Comment by sericks007** [comment]
@AndrewMaisey, thank you for posting here.

@PeterRFriis or @faix, please review and update the content if needed.

**Comment by faix** [comment]
Hello @AndrewMaisey,

I will reply only for Dynamics 365 Finance and Operations onPremises.
Officially we currently don't support Windows Server 2019 as validation has not been completed for this version. There are many different components that we need to check work without issues before we can officially state that it is supported. I unfortunately can't give you a time estimate as to when we will officially support it.

**Comment by AndrewMaisey** [comment]
Thank you, I have had similar feedback Re; 2019 SQL and Server from another Microsoft channel. Noted as not supported at present.  (I expect D365 Customer Engagement is similar as it is a similar product).

Hoping the validation gets done soon as I'm sure a number of customers will be looking for a supporting-platforms upgrade path.
