### ISSUE TITLE
Minimum time span between end of UAT and Go-Live

### ISSUE THREAD

**Issue by gcantin** [MicrosoftDocs/dynamics-365-unified-operations-public#2156]
Several of the tasks are executed by Microsoft, with minimal information or time ranges. What's the minimal time range a Customer would require between UAT sign-off and Production Go-live? There's a 3 day rough estimate for Project Assessment, 48h estimate for the Production Environment Deployment, but no Lead Times listed if there are any. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b23a0dbf-7870-affb-b07b-53b8ea704371
* Version Independent ID: 02442fdc-5733-1ab3-da37-a1e6dfc89c41
* Content: [Prepare for go-live](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/imp-lifecycle/prepare-go-live)
* Content Source: [articles/fin-ops-core/fin-ops/imp-lifecycle/prepare-go-live.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/imp-lifecycle/prepare-go-live.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @ClaudiaBetz-Haubold
* Microsoft Alias: **chaubold**

**Comment by ClaudiaBetz-Haubold** [comment]
It is difficult to come up with a hard number for this, as it depends on the core findings in the go-live assessment report and the time the customer and partner need to close them, as well as the project topology (traditional IAAS or Self-service deployment<https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/infrastructure-stack> type of implementation project). It is also important to know that you can already send the checklist when you are reasonably close to having UAT completed. We suggest that this should be the case at least about 4 weeks prior to the envisioned go-live date. The exact lead times for the service requests that are handled by Microsoft are published in the Submit service requests<https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/submit-request-dynamics-service-engineering-team?toc=/dynamics365/finance/toc.json#service-request-types-and-slas> article. It is Microsoft’s goal to reduce the number of services that depend on Dynamics Service Engineering team and instead to enable more and more activities as a self-service.

Kind regards, Claudia Betz-Haubold, Microsoft


Von: Kristin Fender <notifications@github.com>
Gesendet: Friday, February 28, 2020 7:34 PM
An: MicrosoftDocs/dynamics-365-unified-operations-public <dynamics-365-unified-operations-public@noreply.github.com>
Cc: Claudia Betz-Haubold <Claudia.Betz-Haubold@microsoft.com>; Assign <assign@noreply.github.com>
Betreff: Re: [MicrosoftDocs/dynamics-365-unified-operations-public] Minimum time span between end of UAT and Go-Live (#2156)


Assigned #2156<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fdynamics-365-unified-operations-public%2Fissues%2F2156&data=02%7C01%7CClaudia.Betz-Haubold%40microsoft.com%7Cf2e232ddae8945c5be1508d7bc7cc717%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637185116411804228&sdata=dwE6zb1J7AfQDdW26iU4rVPAKsNMxJw1jvfZMPc47qg%3D&reserved=0> to @ClaudiaBetz-Haubold<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FClaudiaBetz-Haubold&data=02%7C01%7CClaudia.Betz-Haubold%40microsoft.com%7Cf2e232ddae8945c5be1508d7bc7cc717%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637185116411804228&sdata=fZZUx3zfExJgUvHie1m8pQFv3XCedYx4vKHKgQsB8Xw%3D&reserved=0>.
