### ISSUE TITLE
The New Chip and Card payment 

### ISSUE THREAD

**Issue by stsbhava** [MicrosoftDocs/dynamics-365-unified-operations-public#2157]
Now a days, the Payment device like Verifone Mx915 or similar it take care of merchant detail and accepting card details from chip card and it directly process with payment processor and return the results with auth code or failed status. I dont see any documents to connect such devices.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8082a393-27b6-131d-b708-ddf23411fde9
* Version Independent ID: ffb5a30e-508b-5b65-2b0d-7e888063d85c
* Content: [Create an end-to-end payment integration for a payment terminal](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/end-to-end-payment-extension#feedback)
* Content Source: [articles/commerce/dev-itpro/end-to-end-payment-extension.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/dev-itpro/end-to-end-payment-extension.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @Reza-Assadi
* Microsoft Alias: **rassadi**

**Comment by tonyafehr** [comment]
@stsbhava, thanks for the feedback. 
@Reza-Assadi, please review and consider making updates to this topic.

**Comment by tonyafehr** [comment]
Bug 426862 logged to track this issue

**Comment by rubencdelgado** [comment]
This scenario isn't explicitly supported by the payments SDK. This issue can be worked around satisfying SDK requirements to provide merchant properties and then ignore them in the connector, but Microsoft does not provide official guidance around how to do this.
