### ISSUE TITLE
HTTP Request got Redirect response

### ISSUE THREAD

**Issue by DavidPaf** [MicrosoftDocs/dynamics-365-unified-operations-public#2158]
Hi team,

Can you help to clarify the reason for the API request always get redirected to location: login.microsoftonline.com though bearer token already retrieved successfully.

I am testing with Postman and Microsoft Flow HTTP action
![image](https://user-images.githubusercontent.com/61499598/75644502-6cb6cf80-5c3a-11ea-9523-58e33381e8a6.png)

![image](https://user-images.githubusercontent.com/61499598/75644532-848e5380-5c3a-11ea-97b2-493c54220726.png)

Also, reference: 
https://docs.microsoft.com/en-us/dynamics365/human-resources/hr-developer-api-authentication

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61d33ca4-f20d-0fb2-b370-aaae37aaebd3
* Version Independent ID: 6eb55981-9832-b121-21ec-e0b31d9d63a7
* Content: [Submit a leave request to workflow](https://docs.microsoft.com/en-us/dynamics365/human-resources/hr-developer-api-myleaverequests-submit#feedback)
* Content Source: [articles/human-resources/hr-developer-api-myleaverequests-submit.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/human-resources/hr-developer-api-myleaverequests-submit.md)
* Service: **dynamics-human-resources**
* Product: ****
* Technology: ****
* GitHub Login: @andreabichsel
* Microsoft Alias: **anbichse**

**Comment by RobinARH** [comment]
@andreabichsel Hi Andrea - Can you take a look at this? Thanks.

**Comment by DavidPaf** [comment]
Flow user can use the "Invoke HTTP request with AD" action to login to Talent and make queries.

**Comment by RobinARH** [comment]
Bug 438336 created to track this issue.
