### ISSUE TITLE
Banking

### ISSUE THREAD

**Issue by Rathoddn** [MicrosoftDocs/dynamics-365-unified-operations-public#216]
> 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5779b1d9-76f7-c025-2998-e9faae5a3786
* Version Independent ID: 7105f116-29c1-f813-56fb-4cf6592d61d8
* Content: [Set up bank facilities and posting profiles for letter of credit - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/cash-bank-management/tasks/set-up-bank-facilities-posting-profiles-letter-credit#create-bank-facility)
* Content Source: [articles/financials/cash-bank-management/tasks/set-up-bank-facilities-posting-profiles-letter-credit.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/cash-bank-management/tasks/set-up-bank-facilities-posting-profiles-letter-credit.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @kweekley
* Microsoft Alias: **kweekley**

**Comment by ShylaThompson** [comment]
No feedback submitted, issue is missing comment. Closing issue.
