### ISSUE TITLE
Syntax-breaking Curly quotes in powershell samples

### ISSUE THREAD

**Issue by ZStoner** [MicrosoftDocs/dynamics-365-unified-operations-public#2160]
The two powershell snippets in step 3 have a curly ending quote in them [ ’ ].
In addition the first of these snippets has a large blank section near the end of the command.
Both of these snippets are currently syntactically broken if used in powershell as given.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4e9b59c-8b2b-e2bc-a342-2289bb99a066
* Version Independent ID: 3237f2a5-90cb-e041-2a08-369ef38a8c4b
* Content: [Installation steps for Retail channel components in an on-premises environment](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/deploy-retail-onprem)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/deploy-retail-onprem.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/deployment/deploy-retail-onprem.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @jashanno
* Microsoft Alias: **jashanno**

**Comment by tonyafehr** [comment]
@jashanno, please review this feedback and consider making updates. Thanks!

**Comment by tonyafehr** [comment]
Bug 426865 logged to track this issue.

**Comment by tonyafehr** [comment]
This content has been updated, thanks!
