### ISSUE TITLE
Is there any way to apply groupByClause to multiple tables?

### ISSUE THREAD

**Issue by endlessutopia** [MicrosoftDocs/dynamics-365-unified-operations-public#2164]
When you have original query like this: group by Table1.Field1, Table1.Field2, Table2.Field, Table3.Field, how to convert to groupByClause? I tried SysDaExpression+toString but it didn't seem to work effectively.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2888e11c-17de-f90c-a48e-409baee04833
* Version Independent ID: b6f71c61-469e-46d8-9a7f-7cc5da547850
* Content: [Access data by using the SysDa classes](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-ref/sysda#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-ref/sysda.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-ref/sysda.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **rhaertle**

**Comment by tonyafehr** [comment]
If you need immediate assistance, contact Support at [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

@RobinARH, please review. Thanks!

**Comment by tonyafehr** [comment]
Bug 426869 has been logged to track this issue.

**Comment by RobinARH** [comment]
This feature is not implemented, and we do not plan to implement it at this time.
