### ISSUE TITLE
IMPORTANT tag has incorrect format

### ISSUE THREAD

**Issue by oathgg** [MicrosoftDocs/dynamics-365-unified-operations-public#2165]
[IMPORTANT] Remote desktop access will be restricted only to environments deployed using the self-service deployment. There is no change to existing environments or existing customers.

The format of the tag is not the usual 'Information' or 'Important' format box you see on many of the Microsoft Docs pages. Is this intentional?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c7f272b-4ea7-a285-4a9f-e67583a664e0
* Version Independent ID: 54ac0c3d-a2b5-6001-1581-167dd87a80c0
* Content: [Self-service deployment overview](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/infrastructure-stack#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/infrastructure-stack.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/deployment/infrastructure-stack.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @sarvanisathish
* Microsoft Alias: **sarvanis**

**Comment by tonyafehr** [comment]
@oathgg, we're reviewing your feedback. Thanks!

**Comment by sericks007** [comment]
@oathgg, thanks for making us aware of this! I've fixed the formatting and the updated topic will be published later today.
