### ISSUE TITLE
Admin Lockdown on RDP impact to SQL Server usage

### ISSUE THREAD

**Issue by gcantin** [MicrosoftDocs/dynamics-365-unified-operations-public#2166]
Will the upcoming admin lockdown on Tier2+ environments mean it is impossible to access SQL Server in any way shape or form? If so, how does Microsoft recommend running data masking scripts or old data cleanup for test environments? There are certain tasks required for test environments with no impacts to production that could be impacted by the lockdown. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2402dfea-008a-c7bb-8a3b-1d0457a39665
* Version Independent ID: 4936afad-9a39-e65d-a00c-81246de632cb
* Content: [Environment planning](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/imp-lifecycle/environment-planning)
* Content Source: [articles/fin-ops-core/fin-ops/imp-lifecycle/environment-planning.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/imp-lifecycle/environment-planning.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @ClaudiaBetz-Haubold
* Microsoft Alias: **chaubold**

**Comment by tonyafehr** [comment]
@ClaudiaBetz-Haubold, please review this feedback. Thanks!

**Comment by skaue-ms** [comment]
@gcantin 
You will not lose access to the sandbox databases, but the method to connect to the database will differ slightly. If you need to automatically run data masking (SQL) scripts after a database refresh, you will have to connect to the database directly from your SQL Server Management Studio and run these scripts yourself. If you need help to understand how to correctly connect to the database, you will find this on docs, or you can contact support and they will provide instructions.
