### ISSUE TITLE
Several Fields are missing from Parameters, General Tab

### ISSUE THREAD

**Issue by RobertRudd** [MicrosoftDocs/dynamics-365-unified-operations-public#2167]
The following fields are missing help from the Expense Management Parameters > General Tab:
 
Validate expense purpose
Validate travel requisition purpose

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e493702c-f9fa-57cc-723e-0f35f651b70d
* Version Independent ID: e2f983e0-0c9b-6b55-b76d-de22d441de53
* Content: [Expense management parameters](https://docs.microsoft.com/en-us/dynamics365/finance/expense-management/expense-management-parameters)
* Content Source: [articles/finance/expense-management/Expense-Management-Parameters.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/expense-management/Expense-Management-Parameters.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @KimANelson
* Microsoft Alias: **knelson**

**Comment by tonyafehr** [comment]
@RobertRudd, thanks for noting this. 
@KimANelson, please review and consider making updates.

**Comment by tonyafehr** [comment]
Bug 426875 has been logged to track this issue.

**Comment by josaw1** [comment]
BUG 437992 created to replace the above item.

**Comment by josaw1** [comment]
The program manager said she will address this issue in an upcoming release. Thanks.

**Comment by suvaidya** [comment]
Updated documentation with requested changes.
