### ISSUE TITLE
embedded power BI using Data Lake in Tier 1 env.

### ISSUE THREAD

**Issue by HugoDJesus** [MicrosoftDocs/dynamics-365-unified-operations-public#2168]
Once the use of Data Lake in Tier 1 environments is configured, is it possible to activate the Power BI embedded in one box environments?

**Comment by sericks007** [comment]
@HugoDJesus, thanks for posting this! In the meantime, to get product help you can contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community. 

@MilindaV2, please review.

**Comment by sericks007** [comment]
Bug 427175 was logged to track this issue.
