### ISSUE TITLE
Upload a new version for a specific asset not available un asset library

### ISSUE THREAD

**Issue by GeoffreyDelmee** [MicrosoftDocs/dynamics-365-unified-operations-public#2169]
The steps described in 'Upload a new version for a specific asset' are not available in the project asset library. The documentation is not clear if this functionality should be available there, or if should be only in the shared asset library.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 786fc060-d324-2e48-d4db-787895b8df3e
* Version Independent ID: d37abcc6-f7f7-5752-7d24-28f17b5d78aa
* Content: [Asset library in Lifecycle Services (LCS)](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/asset-library)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/asset-library.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/lifecycle-services/asset-library.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by sericks007** [comment]
@GeoffreyDelmee, thanks for posting here.

@laneswenka, please review and update the content as necessary.

**Comment by sericks007** [comment]
LCS bug 6451335 was logged to track this issue.
