### ISSUE TITLE
AX 2012 R3 Scope of Extended Support

### ISSUE THREAD

**Issue by chris-ayers-uk** [MicrosoftDocs/dynamics-365-unified-operations-public#2171]
AX 2012 R3 Scope of Extended Support is not clear on this page.
Are we supposed to assume that scope of AX 2012 R3 Extended support is same as AX 2012 R2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07b21efb-8608-4d17-2bcb-32052046cba5
* Version Independent ID: afcf5ce6-5277-119c-6414-db8e26d655cf
* Content: [End of mainstream support for Microsoft Dynamics AX 2009, Dynamics AX 2012, and Dynamics AX 2012 R2](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/mainstream-support-ax-2009-2012#feedback)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/mainstream-support-ax-2009-2012.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/get-started/mainstream-support-ax-2009-2012.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @meeramahabala
* Microsoft Alias: **meeram**

**Comment by sericks007** [comment]
@chris-ayers-uk, thanks for posting here.

@ShellyBakke or @meeramahabala, please review and update the content, as necessary.

**Comment by sericks007** [comment]
Bug 427168 has been logged to track this issue.

**Comment by ShellyBakke** [comment]
The scope for extended support for AX 2012 R2 will also apply to Dynamics AX 2012 R3 once R3 reaches the extended support phase.  I have updated the question in the FAQ to hopefully be more clear.

**Comment by sericks007** [comment]
The updated topic will be published later today.
