### ISSUE TITLE
Credit Management

### ISSUE THREAD

**Issue by sanjum7** [MicrosoftDocs/dynamics-365-unified-operations-public#2174]
Has any one got any idea how to get hold of new functionality of Credit Management before Apr 2020?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a07f87a-ebe3-e319-b622-0fab3c5d67a4
* Version Independent ID: 0f0ec9c2-b785-e6ad-b5ca-88f7da7ec8e9
* Content: [Credit management setup](https://docs.microsoft.com/en-us/dynamics365/finance/accounts-receivable/cm-setup-information#feedback)
* Content Source: [articles/finance/accounts-receivable/cm-setup-information.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/accounts-receivable/cm-setup-information.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @mikefalkner
* Microsoft Alias: **mfalkner**

**Comment by sericks007** [comment]
@sanjum7, please read about the Preview Early Access Program (PEAP) in the [Service update availability](https://docs.microsoft.com/dynamics365/fin-ops-core/fin-ops/get-started/public-preview-releases) topic.
