### ISSUE TITLE
VHD 10.0.9 version

### ISSUE THREAD

**Issue by vimarica** [MicrosoftDocs/dynamics-365-unified-operations-public#2176]
Currently in the asset library it's available for download only the 10.0.5 version, when will be available a newer version ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe3913a6-4daa-9973-6f0b-d7ae4c1007c2
* Version Independent ID: f2cd311b-fcb8-cff4-57a3-47c3c52b19d6
* Content: [Deploy and access development environments](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/access-instances)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/access-instances.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-tools/access-instances.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @jorisdg
* Microsoft Alias: **jorisde**

**Comment by jorisdg** [comment]
This isn't quite the place to ask, but I can answer anyway. The VHDs are released with the April and October waves. The updates in between have to be installed manually.
As far as the April release VHD, I expect it will be out some time this month as the first-release updates start rolling out.
