### ISSUE TITLE
Version of D365 for the referenced hotfix?

### ISSUE THREAD

**Issue by weaveriski** [MicrosoftDocs/dynamics-365-unified-operations-public#2177]
There is a hotfix referenced on this page from February 2016. Can it be made clear what the approach is for D365FO and the OneVersion solution, a 4 year old hotfix cannot be relevant to the current solution?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2992148-6192-d471-eec9-deb2a027e13e
* Version Independent ID: 5d36809c-4cf8-adb8-45f4-540753c2f0ca
* Content: [Best practices for importing vouchers by using the General journal entity](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/tips-tricks-import-general-journal-entity)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/tips-tricks-import-general-journal-entity.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/tips-tricks-import-general-journal-entity.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @ShylaThompson
* Microsoft Alias: **kweekley**

**Comment by josaw1** [comment]
Hi. Thank you for your feedback. @sericks007 can you please take a look?

**Comment by sericks007** [comment]
@roschlom, please review and update as necessary.

**Comment by josaw1** [comment]
BUG 427175 created to track the issue.

**Comment by roschlom** [comment]
As Jo said, thank you for the feedback! You're right that the hotfix isn't necessary now. We've updated the topic to reflect that. Thanks again!
