### ISSUE TITLE
LCS Trial Link Broken

### ISSUE THREAD

**Issue by CoreyVantilborg** [MicrosoftDocs/dynamics-365-unified-operations-public#2178]
The LCS link does not create a proper LCS trial,  instead, it takes you to the 30-day trial with is not helpful at all. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4c106-c0e3-81ba-db99-1fcdaa5158dd
* Version Independent ID: 0f4a76f7-d071-e9ee-4271-866a4ae417f9
* Content: [Upgrade from AX 2012 to Finance and Operations](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/upgrade-overview-2012#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/migration-upgrade/upgrade-overview-2012.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/migration-upgrade/upgrade-overview-2012.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @tariqbell
* Microsoft Alias: **tabell**

**Comment by josaw1** [comment]
Thank you for your feedback. @sericks007 can you please take a look?

**Comment by sericks007** [comment]
@tariqbell or @laneswenka, please update this content as necessary.

**Comment by josaw1** [comment]
BUG 427710 created to track.

**Comment by laneswenka** [comment]
I unfortunately don't own trials so not sure how this works today, will follow up with the team.

**Comment by CaptainCowell** [comment]
Hi,
Please can we get this LCS Trial link corrected/updated. Community members trying to initiate upgrade projects are getting stumped at step 1 - I know, I've been on a call with one this week.
**Please, if anyone knows the current and correct procedure or link for a customer to get their LCS trial project going please can you share it.** This is to enable a customer to perform the Analyze activities for an upgrade before actually purchasing Finance and Operations, which lets them deploy their own Finance and Operations environments and gives access to the tools in LCS that are used to evaluate their AX 2012 environment and existing custom code.
Thanks.

**Comment by sericks007** [comment]
@laneswenka, any update on this?  I believe you were going to check with your team.

**Comment by sericks007** [comment]
This content has been updated.  It now directs you to the [Sign up for preview subscriptions](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/sign-up-preview-subscription) article for more information -- which was also updated yesterday, as well.
