### ISSUE TITLE
From which release it is available

### ISSUE THREAD

**Issue by OksanaKovaliova** [MicrosoftDocs/dynamics-365-unified-operations-public#2181]
Hi dear Team, from which release can we already move to the new way of connector publishing? 
10.0.7 works or later? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27f678d1-840c-d7d3-1e97-ca80666328c2
* Version Independent ID: 2a0f90df-f8eb-d9e2-d5be-881734e72e21
* Content: [Create payment packaging for Application Explorer in Service Fabric deployments - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/payment-connector-package)
* Content Source: [articles/commerce/dev-itpro/payment-connector-package.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/dev-itpro/payment-connector-package.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by josaw1** [comment]
Thank you for your feedback. @mugunthanm can you please take a look?

**Comment by mugunthanm** [comment]
This is supported starting from 10.0.10.
