### ISSUE TITLE
Link is not working

### ISSUE THREAD

**Issue by stefanlundquist** [MicrosoftDocs/dynamics-365-unified-operations-public#2184]
The first link to "Removed or deprecated features" above is not working

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b49b0390-b474-21f6-7ab2-fee834c0f7ab
* Version Independent ID: 1cf62f36-e605-bc7d-17bd-1af1f50a447f
* Content: [What's new or changed in Dynamics 365 Finance version 10.0.10 (April 2020) - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/get-started/whats-new-changed-10-0-10)
* Content Source: [articles/finance/get-started/whats-new-changed-10-0-10.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/get-started/whats-new-changed-10-0-10.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @roschlom
* Microsoft Alias: **roschlom**

**Comment by RobinARH** [comment]
@roschlom - Can you take a look? thanks - Robin

**Comment by roschlom** [comment]
This has been fixed and re-published now. Thanks for letting me know about it.
