### ISSUE TITLE
Filter wildcard?

### ISSUE THREAD

**Issue by tclayton72** [MicrosoftDocs/dynamics-365-unified-operations-public#2185]
Is there a wildcard character for filtering?  To search for an unknown middle?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8320da9e-599b-0584-ea08-59bf8afffc98
* Version Independent ID: 76120ced-276f-bc16-9c03-c1ac3b189be6
* Content: [Application Explorer - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/application-explorer)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/application-explorer.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-tools/application-explorer.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **jorisde**

**Comment by RobinARH** [comment]
@jorisdg - Can you take a look? Thanks - Robin

**Comment by SysC0mp** [comment]
@tclayton72 You can use Regular Expressions in the Application Explorer to filter what you need. Take a look here -> http://dev.goshoom.net/en/2016/10/application-explorer-filtering/
