### ISSUE TITLE
Error on step #7

### ISSUE THREAD

**Issue by VV-B0Y** [MicrosoftDocs/dynamics-365-unified-operations-public#2188]
I get the following error when using the value of the 'Body of the request' provided in step 7 {"executionId": body('GetExportedPackageURL')?['value']}

`Failed to save logic app TalentDynamicsExportNew'. The template validation failed: 'The template action GetExportedPackageURL at line 1 and column 1639 is not valid: "Unable to parse template language expression 'base64('{'executionid":body('GetExportedPackageURL')?['Value']}')': expected token 'RightPerenthesis' and actual 'Identifier'.".'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04f7ad6f-3497-96ae-4a67-4d5e3f52e6f8
* Version Independent ID: 5508926a-a50b-c19e-eec2-d88c7a327726
* Content: [Create a recurring data export app - Human Resources | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/human-resources/hr-admin-integration-recurring-data-export)
* Content Source: [articles/human-resources/hr-admin-integration-recurring-data-export.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/human-resources/hr-admin-integration-recurring-data-export.md)
* Service: **dynamics-human-resources**
* Product: ****
* Technology: ****
* GitHub Login: @andreabichsel
* Microsoft Alias: **anbichse**

**Comment by tonyafehr** [comment]
Thanks for contacting us. We'll review and consider updating this topic. In the meantime,  if you need Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
@andreabichsel, please review.
