### ISSUE TITLE
Completed steps on both Azure, D365 and Postman, but still getting a 401 Unauthorized response from D365 FinOps

### ISSUE THREAD

**Issue by TheElectricCo** [MicrosoftDocs/dynamics-365-unified-operations-public#2194]
Hi, 

I'm currently trying to connect an app to the D365 Odata endpoint, but even when I have completed all the above steps, Postman still gives a 401 unauthorized response. Can someone help me figuring out what is wrong in my setup?

Thanks!
Lens

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39946d94-b987-869b-dcf9-fc8a53089976
* Version Independent ID: c4996190-a4d7-0531-072c-454cea691b63
* Content: [Test services by using third-party utilities - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/third-party-service-test)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/third-party-service-test.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/third-party-service-test.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by josaw1** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community. 
@Sunil-Garg FYI.

**Comment by TheElectricCo** [comment]
Ok, understood.

I'll close this issue here and try my luck on the community page.

Regards,
Lens

**Comment by haroonattari** [comment]
@TheElectricCo I wonder if you have found any solution to this issue on any other forum. I am also getting same error while initiating 'GET' request from Postman. 'POST' request to generate bearerToken works fine. Thanks in advance. Haroon.

**Comment by TheElectricCo** [comment]
@haroonattari Yes, I got it working eventually. My error is that I used a trailing slash at the resource part. Something that I overlooked.

**Comment by artemt1** [comment]
Got the same issue with 401 unauthorized response. Configured everything according to the article, got token, does not have trailing slash in my URL. 
Still "401 unauthorized"
