### ISSUE TITLE
This page needs an update on the frequency of picking up batch jobs and tasks

### ISSUE THREAD

**Issue by nickolash** [MicrosoftDocs/dynamics-365-unified-operations-public#2195]
The page mentions that a batch server checks for available threads one time per minute. Therefore, you might have to wait for a minute before you see that a waiting task is picked up for processing by an available thread. This does not seem to be the case anymore (it used to be) - batch tasks are started almost instantly after putting them in a waiting status.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6465b985-b976-a032-6f05-e540ef844f30
* Version Independent ID: d13d8e4c-36cd-21ea-1113-99774093458f
* Content: [Batch processing and batch servers - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/batch-server-overview#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/batch-server-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/sysadmin/batch-server-overview.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Peakerbl
* Microsoft Alias: **peakerbl**

**Comment by kfend** [comment]
Thanks for the feedback! While it's great that this is taking less than a minute, we would prefer to keep the documented committed time at one minute.
