### ISSUE TITLE
Trace Parser D365 Setup

### ISSUE THREAD

**Issue by aaronstackpole** [MicrosoftDocs/dynamics-365-unified-operations-public#2198]
I am not able to find any details related to the initial set up of Trace Parser for D365. I'm assuming it's similar to how you did it in AX 2012, but there should be some guidance on how to perform the initial configuration in addition to how to use it, because you can't use it until it's set up correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f7b3eb1-cffd-0554-499b-2b4613ec186a
* Version Independent ID: 57ba9f1a-9634-c077-4458-59da57186d8a
* Content: [Take traces by using Trace parser - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/perf-test/trace-trace-tutorial#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/perf-test/trace-trace-tutorial.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/perf-test/trace-trace-tutorial.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **chwolf**

**Comment by tonyafehr** [comment]
@aaronstackpole, thanks for the feedback. 
@RobinARH, please review.

**Comment by tonyafehr** [comment]
Bug 431246 logged to track this issue.

**Comment by RobinARH** [comment]
This articles says that it should be pre-installed and how to install it yourself. Are you saying it needs configuration beyond that? thanks.

https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/perf-test/trace-parser

**Comment by sbredallMCA** [comment]
> Bug 431246 logged to track this issue.

When I create a trace in a OneBox environment, the etl doesn't have any X++ detail.  The Code section only reads "SOURCE CODE NOT FOUND".  Any ideas?
