### ISSUE TITLE
QuickFilter control is missing on my pattern list

### ISSUE THREAD

**Issue by Augmentx-zw** [MicrosoftDocs/dynamics-365-unified-operations-public#2200]
QuickFilter control is missing on my pattern list

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d636f921-c6d6-25c3-c1e8-15332844eb6d
* Version Independent ID: 657c8193-2829-2c9d-65d0-f0dab5547756
* Content: [Filtering options - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/user-interface/filtering#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/user-interface/filtering.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/user-interface/filtering.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by RobinARH** [comment]
@jasongre - Can you take a look? Thanks.

**Comment by RobinARH** [comment]
Bug 438334 created to track this issue.

**Comment by jasongre** [comment]
@AugmentXY can you provide some more information about what you're looking for?
