### ISSUE TITLE
Email address Dynamics365Commerce@microsoft.com leads to nowhere

### ISSUE THREAD

**Issue by anderson-joyle** [MicrosoftDocs/dynamics-365-unified-operations-public#2201]
When sending requests to Dynamics365Commerce@microsoft.com, the following is given as reply:

=================================================================
Delivery has failed to these recipients or groups:
Dynamics365Commerce@microsoft.com (Dynamics365Commerce@microsoft.com)
Your message couldn't be delivered to the recipient because you don't have permission to send to it.
Ask the recipient's email admin to add you to the accept list for the recipient.
For more information, see DSN 5.7.129 Errors in Exchange Online and Office 365.
=================================================================

Not sure what do to. I need to have mentioned LCS e-Commerce Evaluation and Commerce Preview Program Environments activated for my account.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0737e52e-d1fc-a719-3fa3-5feef38ab9c3
* Version Independent ID: c8b1264a-2b1d-708c-29e5-48718736c117
* Content: [Provision a Dynamics 365 Commerce preview environment - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/provisioning-guide#feedback)
* Content Source: [articles/commerce/provisioning-guide.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/provisioning-guide.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @psimolin
* Microsoft Alias: **psimolin**

**Comment by tonyafehr** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community. 
@psimolin, please note this feedback.
