### ISSUE TITLE
The development image is using Visual Studio 2015

### ISSUE THREAD

**Issue by mores** [MicrosoftDocs/dynamics-365-unified-operations-public#2203]
Instructions are out of date. It says:
"Start Visual Studio 2013 as Administrator.

Click Project &gt; Options &gt; Source Control &gt; Plug-in Selection."

VS 2015 is installed - and the there is no Options under Project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1486907-b279-d1c2-9cac-acf009a20d26
* Version Independent ID: debe77cc-b887-0033-9c68-92c1d5ba1b39
* Content: [Version control, metadata search, and navigation - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/version-control-metadata-navigation)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/version-control-metadata-navigation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-tools/version-control-metadata-navigation.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **jorisde**

**Comment by tonyafehr** [comment]
@mores, thanks for the feedback. 
@jorisdg, please review. Thank you!

**Comment by RobinARH** [comment]
We updated the topic and the changes should go live tonight. - Robin
