### ISSUE TITLE
Please consider to add detail contents how to use performance timer.

### ISSUE THREAD

**Issue by yoison** [MicrosoftDocs/dynamics-365-unified-operations-public#2204]
Please consider to add detail contents how to use performance timer due to customers request.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 135281b4-08f4-fe51-60b1-257c3ee01037
* Version Independent ID: 5d07baaf-3c78-488d-a37c-177b1b5c2956
* Content: [Performance timer - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/perf-test/performance-timer)
* Content Source: [articles/fin-ops-core/dev-itpro/perf-test/performance-timer.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/perf-test/performance-timer.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **chwolf**

**Comment by sericks007** [comment]
@yoison, thank you for your feedback!

@RobinARH, please review.

**Comment by sericks007** [comment]
Bug 431639 has been logged to track this issue.

**Comment by RobinARH** [comment]
Hi Yoison - Thanks for the feedback, but it's unlikely we'll make significant changes to this doc in the near future. -Robin
