### ISSUE TITLE
Errors in bug fixes section

### ISSUE THREAD

**Issue by kasperrytter** [MicrosoftDocs/dynamics-365-unified-operations-public#2205]
Error in the section "bug fixes". It says "10.0.7" and not "10.0.9". Secondly, the link to the KB article is the link from 10.0.8.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f33802ea-99bc-2987-441c-466a9c7c0262
* Version Independent ID: a57f482c-856e-2ed3-757f-801104d06c65
* Content: [What's new or changed in Dynamics 365 Finance version 10.0.9 (March 2020) - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/get-started/whats-new-changed-10-0-9#feedback)
* Content Source: [articles/finance/get-started/whats-new-changed-10-0-9.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/get-started/whats-new-changed-10-0-9.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @roschlom
* Microsoft Alias: **roschlom**

**Comment by sericks007** [comment]
@kasperrytter, thanks for letting us know about this!

@roschlom, please review and update the content, as needed.

**Comment by roschlom** [comment]
Thanks for pointing out the issues. The topic has been updated now. It was just published so the updates should show up soon. Thanks again!
