### ISSUE TITLE
WBS Teamplates 

### ISSUE THREAD

**Issue by vissundd** [MicrosoftDocs/dynamics-365-unified-operations-public#221]
Also please explain to create WBS teamplates. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4fbad3d-0998-be8f-006e-6f9588375a5c
* Version Independent ID: 5269e8ea-2d31-f705-5d23-ed2aa0a2dd47
* Content: [Work breakdown structures - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/project-management/work-breakdown-structures#wbs-templates)
* Content Source: [articles/financials/project-management/work-breakdown-structures.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/project-management/work-breakdown-structures.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @KimANelson
* Microsoft Alias: **knelson**

**Comment by ShylaThompson** [comment]
bug logged for investigation:  229524

**Comment by ShylaThompson** [comment]
@vissundd Content for WBS templates is now planned and will be ready to publish within the next few weeks. Thanks for the suggestion!
