### ISSUE TITLE
Need to update Japan localization document 

### ISSUE THREAD

**Issue by mutsun1** [MicrosoftDocs/dynamics-365-unified-operations-public#2211]
There are some parts that are in only Japan localized document but is not in English document for this page.
These parts make Customer confuse and we got some question from Customer for this part in past.
We need to update Japan localization document and remove this parts as same as English document.

Japanese document. 
https://docs.microsoft.com/ja-jp/dynamics365/fin-ops-core/dev-itpro/database/database-point-in-time-restore#point-in-time-restore-breaks-the-chain-of-available-restore-points 

English document.
https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/database-point-in-time-restore

Different parts that we are asking to remove from Japan localized document is the changed by the following commit by Lane senka. 

https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/commit/ef856bec7daa6529cdaf7221a1897604fb6ea7f1#diff-128b92be29125492f599d8a03784cd30 

In English (these has been removed from this document by Commit - ef856bec7daa6529cdaf7221a1897604fb6ea7f1)
Going forward, the Lifecycle Services team will work to improve point-in-time restore by leveraging the restore history of deleted databases.  This will allow continual restore back to the same point-in-time for scenarios such as destructive testing.  This will be fixed in an upcoming release of LCS.

In Japanese:
今後、Lifecycle Services チームは、削除されたデータベースの復元履歴を活用することで時点でポイントインタイム復元を向上させるよう努めます。 これによって、破壊試験などのシナリオで同じ時点に継続的に復元できるようになります。 これは、LCS の今後のリリースで修正されます。

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 805f3739-0cad-d6ab-7db0-175c972f189f
* Version Independent ID: 68be2d28-d5e9-471d-8648-a8cbae2e1e7d
* Content: [Database point-in-time restore (PITR) - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/database-point-in-time-restore#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/database/database-point-in-time-restore.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/database/database-point-in-time-restore.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laneswenka**

**Comment by tonyafehr** [comment]
@vinceno, please review. Thanks!

**Comment by vinceno** [comment]
@mutsun1 -  thank you so much for this feedback, it is always very much appreciated.   While we look to minimise the impact, there will be some delay in changes to the English content being reflected in non-English languages. I believe the item you highlighted is now addressed, however, there has been further changes to this topic in English and those changes are currently in translation now., and will be reflected in Japanese version shortly.

**Comment by vinceno** [comment]
@tonyafehr - closing
