### ISSUE TITLE
Task Recording use against the Business Process Library

### ISSUE THREAD

**Issue by D365Princess** [MicrosoftDocs/dynamics-365-unified-operations-public#2215]
There is a conflict in information on this page, in the top "Important" note you are stating that at this time task recordings cannot be saved to the BPM but in the text under the heading "learn-about-task-recorder" you are saying this is possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea38a642-b6f9-7fbb-23a0-0f43e574aa75
* Version Independent ID: 046fee7f-d39d-5612-2c04-2b34558afebe
* Content: [Create documentation or training with Task Recorder - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/user-interface/task-recorder-training-docs?toc=/dynamics365/human-resources/toc.json#learn-about-task-recorder)
* Content Source: [articles/fin-ops-core/dev-itpro/user-interface/task-recorder-training-docs.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/user-interface/task-recorder-training-docs.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by tonyafehr** [comment]
@D365Princess, thanks for the feedback. 
@josaw1, please review.

**Comment by josaw1** [comment]
@D365Princess, thank you. I've removed the section about being able to save to BPM and display in the Help pane and will publish the changes later today.
