### ISSUE TITLE
Commerce CMS link and note on retail server hosting in production environments

### ISSUE THREAD

**Issue by andyNewnham** [MicrosoftDocs/dynamics-365-unified-operations-public#2220]
Hi, It would be great if a comment could be included on how to link POS images to the CMS (Asset library) now used by e-commerce. This is by using your public CMS address, with the suffix: /imageFileData/search?fileName=/imageFileData/search?fileName=

Also, a very frequent question that comes up (often on yammer), is regarding the use of retail server (MediaServer folder) to host images in a production environment, which is not possible. This document does state at the top that they must be hosted outside of Commerce (not 100% true with my initial comment), but further down there is a note stating:
"For this demo data example, the media server is deployed on the Commerce Scale Unit. However, you can have it anywhere outside Commerce." - This note should point out it only applies to either the demo data or a onebox environment, and cannot be applied to sandbox or production environments.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf296c0e-3bc3-c5a2-abb2-68ad5e22bcf2
* Version Independent ID: 8118927b-913a-1c90-4790-ef2c9a28ca0a
* Content: [Set up and manage images for Modern POS (MPOS) - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/set-up-manage-images-retail-mpos)
* Content Source: [articles/commerce/set-up-manage-images-retail-mpos.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/set-up-manage-images-retail-mpos.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @athinesh99
* Microsoft Alias: **athinesh**

**Comment by tonyafehr** [comment]
@andyNewnham, thanks for the feedback. 
@josaw1, please review.

**Comment by tonyafehr** [comment]
Bug 434422 logged to track this issue.

**Comment by josaw1** [comment]
@athinesh99 can you please take a look at this? Thanks.

**Comment by ashishmsft** [comment]
https://github.com/MicrosoftDocs/Dynamics-365-Operations/pull/8118

**Comment by ashishmsft** [comment]
@tonyafehr please review and publish the update
