### ISSUE TITLE
Mistake in writing

### ISSUE THREAD

**Issue by sebastianstrefel** [MicrosoftDocs/dynamics-365-unified-operations-public#2224]
The title BPCheckAltenateKeyAbsent is incorrect. It should be BPCheckAlternateKeyAbsent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cbcd513-d8ab-ddc6-ce0d-43e03d4692c2
* Version Independent ID: d1119159-09e4-1aa1-d90e-c8f23552adbc
* Content: [Customization Analysis Report (CAR) - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/customization-analysis-report#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/customization-analysis-report.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-tools/customization-analysis-report.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **jorisde**

**Comment by sericks007** [comment]
@sebastianstrefel, thanks for letting us know!

@RobinARH, please review and update the text.

**Comment by sericks007** [comment]
Bug 434682 has been logged to track this issue.

**Comment by RobinARH** [comment]
Fixed.
