### ISSUE TITLE
Include tips to search for the QueryID

### ISSUE THREAD

**Issue by sebaz86** [MicrosoftDocs/dynamics-365-unified-operations-public#2225]
Add tips in the "Get list of query ID's" section to help users retrieving the needed data like:
1. Replace any special character from the SQL statement like " ' " (single quote) or "?" (question mark) with the wildcard"%" which tells SQL to bring "anything in between".
Example: %where DataAreaID = N'DAT' and Partition =... -&gt; %where DataAreaID = % and Partition =... 
2. Add note that: this section will search the SQL query store for the !exact! statement including the formatting (spaces, tabs and so on), so if it isn't found, most likely there are missing or too many characters that don't match the exact SQL statement.

Also, please add notes to the "Get query plan and execution stats" section that some of the query plan stats displayed may belong to Prepare Statements and not the actual Execution of the SQL statement. The pattern is usually subsequent QueryPlanIDs and the lowest one is very fast (few microseconds). Maybe add reference documentation on how Prepare statement works for users to better understand the context: https://docs.microsoft.com/en-us/sql/relational-databases/native-client-odbc-queries/executing-statements/prepared-execution?view=sql-server-ver15

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b75b1a49-8365-0fc4-5c27-677ff4b26325
* Version Independent ID: 98fcce36-1717-a210-0bb6-5c7f48bdf36f
* Content: [Query cookbook - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/querycookbook?source=docs#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/querycookbook.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/lifecycle-services/querycookbook.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @meeramahabala
* Microsoft Alias: **meeram**

**Comment by sericks007** [comment]
@sebaz86, thank you for the feedback!

@meeramahabala, please review and update the content.

**Comment by sericks007** [comment]
LCS bug 6934393 was logged to track this issue.
