### ISSUE TITLE
Transaction data is commonly part of Data Migration

### ISSUE THREAD

**Issue by ronsonntag54** [MicrosoftDocs/dynamics-365-unified-operations-public#2226]
It is not correct to not include transaction data as part of data migration. Clients commonly want historical transaction data to be migrated into D365 so that their financials maintain continuity and forecasting can be maintained. You can also throw into the mix machine learning that requires significant historical data.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa534ca5-bcca-b26d-0ebe-22ec2e9287ad
* Version Independent ID: ba1356c4-d1f8-69ff-6228-dff3c218f9ec
* Content: [Data entities overview - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/data-entities)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/data-entities.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/data-entities.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by sericks007** [comment]
@ronsonntag54, thank you for your feedback!

@Sunil-Garg, please review and consider updating the content.

**Comment by sericks007** [comment]
Bug 434687 has been logged to track this issue.

**Comment by Sunil-Garg** [comment]
@ronsonntag54, we have updated that line of text to clarify as to why certain transactions are not recommended to migrate. Hope this helps to clarify. If not, pls do let us know. Thanks.
