### ISSUE TITLE
Two errors

### ISSUE THREAD

**Issue by PhilippeDoucette** [MicrosoftDocs/dynamics-365-unified-operations-public#2228]
1...and does not prevent the user from use either entry point.
2...when the task guide detects that the user is on the wrong from,...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5762f9e-d7f4-e7fc-49c7-6db64c01bc6a
* Version Independent ID: 2aab18ad-f2f1-c0ad-c109-38806c8491a3
* Content: [Task recorder resources - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/user-interface/task-recorder#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/user-interface/task-recorder.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/user-interface/task-recorder.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by josaw1** [comment]
Thank you for your feedback. @jasongre can you please look at this?

**Comment by josaw1** [comment]
BUG 440094 created to track.

**Comment by jasongre** [comment]
Thanks for catching those! They should be fixed soon!
