### ISSUE TITLE
Licensing Required for this process

### ISSUE THREAD

**Issue by mhammons** [MicrosoftDocs/dynamics-365-unified-operations-public#2229]
Can you please add details related to the type of Power BI licensing that is required for modifying these out of box, entity store based reports. Do authors require a Power BI Pro license?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40ae6a15-fb41-e9e6-bb76-bb570fd2d5d2
* Version Independent ID: 74ebfbfe-6123-ceeb-afeb-7d73a322892e
* Content: [Create analytical reports by using Power BI Desktop - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/author-distribute-power-bi-reports#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/author-distribute-power-bi-reports.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/author-distribute-power-bi-reports.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by josaw1** [comment]
Thank you  for your feedback. @MilindaV2 can you please take a look?

**Comment by josaw1** [comment]
BUG 440092 created to track the issue.
