### ISSUE TITLE
Licensing Required for Editing Entity Store Reports

### ISSUE THREAD

**Issue by mhammons** [MicrosoftDocs/dynamics-365-unified-operations-public#2230]
It is not clear here, nor in the Licensing Guide, what Power BI license is required for editing entity store based reports (those that stay in Dynamics, not the ones from powerbi.com). Do users need a Power BI Pro license to logon to the VM and edit the existing reports (more specifically the datasets)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 630034c6-dbcc-d365-d58b-36bef4277582
* Version Independent ID: ce5941a7-67bb-9c0a-c1ab-230fe8aff69f
* Content: [Power BI Embedded integration - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/power-bi-embedded-integration)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/power-bi-embedded-integration.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/power-bi-embedded-integration.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by mhammons** [comment]
That would also go for creating any NEW entity store based reports that are subsequently uploaded to LCS.

**Comment by josaw1** [comment]
Thanks for the feedback. @TJVass can you please take a look?

**Comment by josaw1** [comment]
BUG 440097 created to track

**Comment by hammr5900** [comment]
Hello. Is there an update to the docs that provide this information?

**Comment by tonyafehr** [comment]
@sericks007, please review.

**Comment by sericks007** [comment]
@RichdiMSFT or @MilindaV2, can one of you answer this question?
