### ISSUE TITLE
PCard Data/Vendor Invoice Upload

### ISSUE THREAD

**Issue by ajb-hso** [MicrosoftDocs/dynamics-365-unified-operations-public#2234]
Hi:

I submitted this issue previously and it has been closed, so please forgive me if adding to a closed issue is proper protocol.  

We are looking at uploading PCard data to use the new PCard feature.  This would entail using the vendor invoice templates in data management.

I have been told that data entity updates have been included in 10.0.9, but am not able to locate them.

If someone can shed some light on this I would appreciate it.

**Comment by kfend** [comment]
@ajb-hso - I am closing this issue and I have reopened issue [2151](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/issues/2151) and pinged the topic author.
