### ISSUE TITLE
Reporting  - Print to Screen

### ISSUE THREAD

**Issue by petrjanikac** [MicrosoftDocs/dynamics-365-unified-operations-public#2235]
Is printing with destination to screen supported on self-service deployment?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5510d9f-2080-9ce5-a04a-bddb63c90127
* Version Independent ID: 255a4b53-046e-55b2-3fd8-79b3f66fc28f
* Content: [Known issues with self-service deployment - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/known-issues-new-deployment-experience#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/known-issues-new-deployment-experience.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/deployment/known-issues-new-deployment-experience.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @rashmansur
* Microsoft Alias: **rashmim**

**Comment by kfend** [comment]
@rashmansur - can you address @petrjanikac's question?

**Comment by kfend** [comment]
Hi @petrjanikac - Thanks for your question. Yes, print to screen is supported.
