### ISSUE TITLE
how do emails get sent???

### ISSUE THREAD

**Issue by MSFTRANDY** [MicrosoftDocs/dynamics-365-unified-operations-public#2236]
Missing step to process the job for "Send email notification" so that the emails actually go out.  Customers otherwise expect this to be automatically sent via email when the action occurs since its not listed in this setup.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90ad114e-bfab-ee83-2c83-a1a665bcd975
* Version Independent ID: 00dd5f4b-6dc9-b2fc-359b-3ae2bec6f315
* Content: [Set up an email notification profile - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/email-notification-profiles#feedback)
* Content Source: [articles/commerce/email-notification-profiles.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/email-notification-profiles.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @samjarawan
* Microsoft Alias: **samjar**

**Comment by kfend** [comment]
This topic has been updated with the requested information. Changes will be published in the next few hours.
