### ISSUE TITLE
How do I upload asset into asset library using an API ?

### ISSUE THREAD

**Issue by ShabuddinKhan** [MicrosoftDocs/dynamics-365-unified-operations-public#2238]

**Comment by tonyafehr** [comment]
@ShabuddinKhan, what topic is this in reference to? Your comment does not have any topic information, which we need to understand where you are looking for information. Keep in mind that we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
