### ISSUE TITLE
Document routing agent support OS

### ISSUE THREAD

**Issue by DKobayashi-ykgw** [MicrosoftDocs/dynamics-365-unified-operations-public#224]
Will Document routing agent work on Windows Server 2016 or higher?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2128b07d-7349-6642-f05f-c94fe800d104
* Version Independent ID: 0568d0d1-8035-3423-f791-7bd82a5d070f
* Content: [Install the Document Routing Agent to enable network printer devices - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/install-document-routing-agent?toc=/fin-and-ops/toc.json)
* Content Source: [articles/dev-itpro/analytics/install-document-routing-agent.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/install-document-routing-agent.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by ShylaThompson** [comment]
Bug logged for investigation: 229526

**Comment by SteveBurkettNZ** [comment]
@TJVass Any update on this one?  Should be fairly easy to comment on if Windows Server 2016 is supported or not?  Windows 2012 R2 goes out of Mainstream Support next month so don't really want to be deploying DRA's on it if possible.

**Comment by TJVass** [comment]
Hi Steve.  Sorry, for the delayed response....

YES - the DRA is fully supported on Windows Server 2016.

**Comment by DKobayashi-ykgw** [comment]
@TJVass Thank you for answering for this question!

**Comment by maheshrajput2907** [comment]
@TJVass Is that for windows server 2019 as well?
