### ISSUE TITLE
Replaceable : are there additional requirements when working with replaceable methods?

### ISSUE THREAD

**Issue by tclayton72** [MicrosoftDocs/dynamics-365-unified-operations-public#2240]
Is there something else needed or has to be done differently when the method is decorated with [Replaceable]?  I get an exception at runtime for an extension on a method with this attribute: "Common Language Runtime detected an invalid program"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4317fdb2-b37f-550d-f229-bfd8498ab073
* Version Independent ID: ecd0974c-0abc-c494-cc8c-e81e7cf096f9
* Content: [Class extension - Method wrapping and Chain of Command - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/extensibility/method-wrapping-coc)
* Content Source: [articles/fin-ops-core/dev-itpro/extensibility/method-wrapping-coc.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/extensibility/method-wrapping-coc.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @ChrisGarty
* Microsoft Alias: **cgarty**

**Comment by tonyafehr** [comment]
We'll review your feedback. If you need immediate assistance, you might want to contact Support using the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

@ChrisGarty, please review. Thanks!
