### ISSUE TITLE
Workflow approval for cancelling the delivery remainder quantity

### ISSUE THREAD

**Issue by AartiKumar** [MicrosoftDocs/dynamics-365-unified-operations-public#2246]
Can you please clarify on this page that if the PO is approved through workflow, confirmed and partially received, changing the delivery remainder will require the user to submit the PO again to workflow. Also please specify the navigation path to 'finalize' option to prevent further changes to PO lines

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d09ece69-12d2-04e0-016c-f92d207f0d0c
* Version Independent ID: 077bc53d-fa09-d4c8-083f-2ecc53a1a667
* Content: [Approve and confirm purchase orders - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/procurement/purchase-order-approval-confirmation#feedback)
* Content Source: [articles/supply-chain/procurement/purchase-order-approval-confirmation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/procurement/purchase-order-approval-confirmation.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @FrankDahl
* Microsoft Alias: **fdahl**

**Comment by sericks007** [comment]
@AartiKumar, thank you for providing this feedback!

@FrankDahl, please review and update the content, as needed.

**Comment by sericks007** [comment]
@MaiKirknel, please review and update the content, as needed.

**Comment by sericks007** [comment]
Bug 437003 has been logged to track this issue.
