### ISSUE TITLE
Getting an error from execute action connector, type provided is of string but required is object

### ISSUE THREAD

**Issue by ishita53** [MicrosoftDocs/dynamics-365-unified-operations-public#2248]
Hi, I am receiving the following error:
The API 'dynamicsax' returned an invalid response for workflow operation 'Execute_action' of type 'OpenApiConnection'. Error details: 'The API operation 'ExecuteProcedure' requires the property 'body/value' to be of type 'Object' but is of type 'String'.'
Now I tried converting the WorkflowWorkItemInstance field to object, but then the connector is not accepting it. How can I resolve this?
Could anyone please help me.
Thanks in advance

**Comment by josaw1** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
