### ISSUE TITLE
𝐗+ 𝐰𝐫𝐢𝐭𝐭𝐞𝐧 𝐢𝐧𝐬𝐭𝐞𝐚𝐝 𝐨𝐟 𝐗++

### ISSUE THREAD

**Issue by samee-r** [MicrosoftDocs/dynamics-365-unified-operations-public#2250]
In "𝐁𝐚𝐜𝐤𝐰𝐚𝐫𝐝-𝐢𝐧𝐜𝐨𝐦𝐩𝐚𝐭𝐢𝐛𝐥𝐞 𝐜𝐡𝐚𝐧𝐠𝐞𝐬 𝐭𝐨 𝐗++" section, '𝐗+' is written instead of '𝐗++' in statement "𝐓𝐡𝐞 𝐬𝐢𝐠𝐧𝐢𝐟𝐢𝐜𝐚𝐧𝐭 𝐛𝐞𝐡𝐚𝐯𝐢𝐨𝐫𝐚𝐥 𝐝𝐢𝐟𝐟𝐞𝐫𝐞𝐧𝐜𝐞𝐬 𝐛𝐞𝐭𝐰𝐞𝐞𝐧 𝐗++ 𝐩-𝐜𝐨𝐝𝐞 𝐯𝐞𝐫𝐬𝐮𝐬 𝐗+ 𝐚𝐬 𝐂𝐈𝐋 𝐰𝐞𝐫𝐞 𝐚𝐬 𝐟𝐨𝐥𝐥𝐨𝐰𝐬".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1bbc2c7-22f5-3b21-978c-4ed5867e400c
* Version Independent ID: 7d53e2be-80a2-e576-31c0-447fb947a568
* Content: [Changes in X++ and the X++ compiler - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/programming-language-support?source=docs#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/programming-language-support.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-tools/programming-language-support.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @pvillads
* Microsoft Alias: **pvillads**

**Comment by josaw1** [comment]
Thanks for your feedback. @RobinARH can you please take a look?

**Comment by josaw1** [comment]
BUG 437599 created to track this.

**Comment by RobinARH** [comment]
Fixed. Should go live later today. - Robin
