### ISSUE TITLE
OpenApi specification request

### ISSUE THREAD

**Issue by dahirongm** [MicrosoftDocs/dynamics-365-unified-operations-public#2252]
It would be extremely helpful if an OpenApi specification is included for each of this API request/response.
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a33b4605-509f-bc52-fcba-eaa15fd75524
* Version Independent ID: 41810ae0-b52a-b250-88f0-d6a1fa7a5505
* Content: [Point of sale (POS) APIs - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/pos-apis)
* Content Source: [articles/commerce/dev-itpro/POS-APIs.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/dev-itpro/POS-APIs.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by josaw1** [comment]
Thanks for your feedback. @mugunthanm can you please take a look?

**Comment by mugunthanm** [comment]
Thanks for your feedback, we will update the documentation soon with description, version and samples. For now you can find the parameters and types information for these APIs in the Pos.Api.d.ts, which is part of the Retail SDK (...Retail SDK\POS\Extensions\Pos.Api.d.ts). Also the Retail SDK has sample for many of these APIs.

**Comment by dahirongm** [comment]
Thanks for your reply. Yes RetailSDK samples and Pos.Api.d.ts is what i have being using so far.

Thanks

**Comment by josaw1** [comment]
BUG 437596 created to track this work.
