### ISSUE TITLE
OpenApi specification request.

### ISSUE THREAD

**Issue by dahirongm** [MicrosoftDocs/dynamics-365-unified-operations-public#2253]
It would be extremely helpful if an OpenApi specification is included for each of this API request/response.
Maybe some use examples can be added also.
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90cf28cb-e5aa-edc4-f379-a500f94574dc
* Version Independent ID: 535bb4de-13cc-1ab0-d6a4-01e1589e3cee
* Content: [Commerce runtime (CRT) services - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/crt-services#crt-services)
* Content Source: [articles/commerce/dev-itpro/crt-services.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/dev-itpro/crt-services.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by josaw1** [comment]
Thanks for your feedback. @mugunthanm can you please take a look?

**Comment by mugunthanm** [comment]
Thanks for your feedback, we will update the documentation soon with specification, description, version and samples.

**Comment by josaw1** [comment]
BUG 437596 created to track this work.
