### ISSUE TITLE
SysTestTransaction documentation

### ISSUE THREAD

**Issue by soerenpc** [MicrosoftDocs/dynamics-365-unified-operations-public#2255]
Could you please add some doc. re. the SysTestTransaction attribute? 

I found this:

None
No protection, you need to clean up yourself.

LegacyRollback
As in AX2012 – test suites can be used to control the protection, for example a new company is created and deleted afterwards. See Inside Dynamics 2012 for details.

LegacyRollbackWithUpdateTracking
As LegacyRollback with a tracking of data inserts. Roll back will delete all rows with RecId &gt; “first inserted row”  
(Do not use)

Auto
A DB snapshot is taken before the test class is run, and restored afterwards.
UserConnections use the main transaction.
Preferred, as it is very hard to leak data.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83324e83-7153-34c1-4a79-2798a8939dd1
* Version Independent ID: c578b200-3c30-ddae-34d7-78898363ae7d
* Content: [Acceptance test library resources - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/perf-test/acceptance-test-library?source=docs#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/perf-test/acceptance-test-library.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/perf-test/acceptance-test-library.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @MichaelFruergaardPontoppidan
* Microsoft Alias: **MichaelFruergaardPontoppidan**

**Comment by josaw1** [comment]
Thank you for your feedback. @MichaelFruergaardPontoppidan can you please take a look?

**Comment by josaw1** [comment]
BUG 437594 created to track this request.

**Comment by josaw1** [comment]
The content will be updated in the next day or two.
