### ISSUE TITLE
Do BYOD users require a license to D365?

### ISSUE THREAD

**Issue by faridmason** [MicrosoftDocs/dynamics-365-unified-operations-public#2258]
Can you clarify whether the users that will be accessing the BYOD database are required or not to be licensed with D365 Finance or SCM? can users without D365 Finance or SCM, access the BYOD database after it's populated with D365 data?
Thanks,
F.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33f75161-0776-a6c1-dc10-dc20ea26973f
* Version Independent ID: 55a81394-4606-745a-9fd2-59fb257d1086
* Content: [Bring your own database (BYOD) - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/export-entities-to-your-own-database)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/export-entities-to-your-own-database.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/export-entities-to-your-own-database.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by RobinARH** [comment]
For questions about licensing, please see the licensing page:
https://dynamics.microsoft.com/en-us/pricing/

You can contact the sales team if you have additional questions:
https://dynamics.microsoft.com/en-us/contact-us/

-Robin
