### ISSUE TITLE
Office 365 ProPlus supported for Excel/Word add-ins?

### ISSUE THREAD

**Issue by SteveBurkettNZ** [MicrosoftDocs/dynamics-365-unified-operations-public#226]
Under Supported Microsoft Office Applications, it states 'To run the Microsoft Excel and Word add-ins, you must have Microsoft Office 2016'. Is Office 365 ProPlus also supported?  If so, can this be added please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48a9aeb7-1d83-3ea1-bc82-083c2c15c5eb
* Version Independent ID: 60294de4-5ff9-a757-6ace-63f59a6aab53
* Content: [System requirements for cloud deployments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/system-requirements)
* Content Source: [articles/fin-and-ops/get-started/system-requirements.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/system-requirements.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @sericks007
* Microsoft Alias: **sericks**

**Comment by ChrisGarty** [comment]
Excel/Office 2016 is the version.
Office 365 ProPlus is a license you can use to be able to install that version.
Adding licensing information here would only muddy the waters.

**Comment by SteveBurkettNZ** [comment]
Would have to disagree with this one. Office 365 ProPlus is a product suite like Office Professional Plus 2016, and it's getting feature updates every month as opposed to every service pack for 'Office 2016'?   When you look at your Apps & Features  control panel in Windows, the installed application is Microsoft Office 365 ProPlus.

The Dynamics 365 Customer Engagement guys are adding distinct references to Microsoft Office 365 in their requirements: 
https://docs.microsoft.com/en-us/dynamics365/customer-engagement/admin/web-application-requirements#supported-versions-of-office

… as are the Dynamics NAV 2018 team:

https://docs.microsoft.com/en-us/dynamics-nav/system-requirements-for-microsoft-dynamics-nav
