### ISSUE TITLE
Reduce a forecast by transactions

### ISSUE THREAD

**Issue by yxx-39** [MicrosoftDocs/dynamics-365-unified-operations-public#2260]
I can't find the Other FastTab in released product page, even in the new released version PU33.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f36dc1d-4d8e-0bb7-317e-6b3cad97b4f6
* Version Independent ID: 8afbf079-6620-a200-af81-4ed147d28dbf
* Content: [Forecast reduction keys - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/master-planning/reduction-keys#feedback)
* Content Source: [articles/supply-chain/master-planning/reduction-keys.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/master-planning/reduction-keys.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @roxanadiaconu
* Microsoft Alias: **roxanad**

**Comment by tonyafehr** [comment]
@ChristianRytt, please review this feedback. Thanks!

**Comment by tonyafehr** [comment]
Bug 438726 logged to track this issue. 
+ @kamaybac for visibility.

**Comment by ChristianRytt** [comment]
Thank you for reporting this issue! The Other FastTab is not on the Released product page but on the Coverage groups. There is an error in the above documentation, we will fix this to point to the correct page (Coverage groups):
"On the Coverage groups page, on the Other FastTab, in the Reduce forecast by field..."
