### ISSUE TITLE
Titles need to reflect the change from 'Retail and Commerce' to 'Commerce' 

### ISSUE THREAD

**Issue by rapraj** [MicrosoftDocs/dynamics-365-unified-operations-public#2262]
The following line - 

Open the Device page in HQ (Retail and commerce &gt; Channel setup &gt; POS setup &gt; Devices).

The label needs to get updated - 
In HQ -&gt; Workers -&gt; For selected worker -&gt; 'Commerce' Tab -&gt; POS Setup 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 955e07d6-ef6f-72d3-5b61-0032b5beaa31
* Version Independent ID: 527bd1f7-14dc-9856-09d8-0bb2d5b22a0b
* Content: [Manage activation accounts and validate devices - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/set-up-activation-accounts-validate-devices-hq#feedback)
* Content Source: [articles/commerce/set-up-activation-accounts-validate-devices-hq.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/set-up-activation-accounts-validate-devices-hq.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @athinesh99
* Microsoft Alias: **athinesh**

**Comment by sericks007** [comment]
@rapraj, thanks for making us aware of this!

@athinesh99, please update the content.

**Comment by sericks007** [comment]
Bug 438952 has been logged to track this issue.

**Comment by sericks007** [comment]
Labels have been updated.  The updated content will be published later today.
