### ISSUE TITLE
PCard Upload ability - #2151

### ISSUE THREAD

**Issue by ajb-hso** [MicrosoftDocs/dynamics-365-unified-operations-public#2263]
Hi:
I am still experiencing issues with the PCard upload capability.

We have enabled the PCard feature in update 33 (10.0.9) and we are able to use the feature.  However, I have reviewed the entities listed below and it looks as if the PCard fields have not been added:
- Vendor invoice header
- Vendor Parameters

Additionally, both PSN entities (BankPurchasingCardEntity and VendTransPurchasingCardEntity) are not listed.

Am I missing something??

_Originally posted by @ajb-hso in https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/issues/2151#issuecomment-607911005_

**Comment by sericks007** [comment]
@ajb-hso, thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

**Comment by sksinghbdo** [comment]
No one can write a worse documentation than this. This is useless documentation and I feel pity about the presentation.
