### ISSUE TITLE
ERROR: User must be in the master database.

### ISSUE THREAD

**Issue by oathgg** [MicrosoftDocs/dynamics-365-unified-operations-public#2267]
I've followed the steps from https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/dbmovement-scenario-debugdiag#add-your-ip-address-to-a-whitelist.

However, when I try to enter the query to add my IP address I receive the following message: "Msg 5001, Level 16, State 5, Procedure sp_set_firewall_rule, Line 1 [Batch Start Line 0]
User must be in the master database."

Last time I had this issue I had to do another refresh and then it somehow got solved?
I've verified that I'm using the axdbadmin account. Anything else for me to do or should I create a Microsoft ticket?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb08fb04-94d5-ef25-8162-a0d79f5ee70a
* Version Independent ID: 6d43b4b7-cc2e-49bc-564a-5eb5eacefa84
* Content: [Debug a copy of the production database - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/dbmovement-scenario-debugdiag#add-your-ip-address-to-a-whitelist)
* Content Source: [articles/fin-ops-core/dev-itpro/database/dbmovement-scenario-debugdiag.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/database/dbmovement-scenario-debugdiag.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laneswenka**

**Comment by oathgg** [comment]
Problem has been solved, I was using the incorrect SP. The one I was using was sp_set_firewall_rule, instead of the one described in the how-to: sp_set_database_firewall_rule.

**Comment by josaw1** [comment]
Great, thank you!
