### ISSUE TITLE
Incorrect instruction for enabling

### ISSUE THREAD

**Issue by brettchristiansen** [MicrosoftDocs/dynamics-365-unified-operations-public#2268]
In prior versions (10.0.8 and lower?) the steps to disable/enable configuration keys outlined here were correct.  In 10.0.9+ these no longer work.  the Trickle fee preview key is missing (if these steps were done previously and then you update you actually lose statement posting forms entirely).  In more recent releases trickle feed appears to be a feature that must be enabled through the Feature Management workspace

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f53eb353-455f-37e8-646b-500d9a5a6402
* Version Independent ID: 81c4d76f-ec29-877d-cb51-374c05741909
* Content: [Trickle feed-based order creation for retail store transactions - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/trickle-feed#feedback)
* Content Source: [articles/commerce/trickle-feed.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/trickle-feed.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by josaw1** [comment]
This is being fixed. Thanks.
