### ISSUE TITLE
Samples

### ISSUE THREAD

**Issue by amustafa91** [MicrosoftDocs/dynamics-365-unified-operations-public#227]
May you can add sample to use everything as it is a new client API, i am not able to understand how to use everything in this API

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3cb43f3-6ec3-f78b-cdeb-16c371d4e3e9
* Version Independent ID: f75a6df8-28c3-0f0d-b40f-47c7debe3c74
* Content: [PageData - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/mobile-apps/platform/client-apis/interfaces/services-business-logic-services-ipagedata)
* Content Source: [articles/dev-itpro/mobile-apps/platform/client-apis/interfaces/services-business-logic-services-ipagedata.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/mobile-apps/platform/client-apis/interfaces/services-business-logic-services-ipagedata.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @shadykdc
* Microsoft Alias: **kashea**

**Comment by ShylaThompson** [comment]
bug logged for investigation: 230852
