### ISSUE TITLE
This Article Needs to be Updated

### ISSUE THREAD

**Issue by JoelLeichty** [MicrosoftDocs/dynamics-365-unified-operations-public#2271]
The What's New 10.0.9 article links to the Release Plan 2020 Wave 1 Article which links to this article. None of these articles provide enough information about what is now in the product; it's not enough to even make educated guesses.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b80b95fb-b679-0e3e-7281-ce5753c0918a
* Version Independent ID: 34f97157-1631-11af-86ba-066faddb654c
* Content: [Credit and collections in Accounts receivable - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/accounts-receivable/collections-credit-accounts-receivable)
* Content Source: [articles/finance/accounts-receivable/collections-credit-accounts-receivable.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/accounts-receivable/collections-credit-accounts-receivable.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @ShivamPandey-msft
* Microsoft Alias: **shpandey**

**Comment by RobinARH** [comment]
@ShivamPandey-msft and @roschlom  - Can you take a look? Thanks.

**Comment by panolte** [comment]
The links are wrong in the what’s new Credit Management article.  

Right now we link to the Credit and collections in accounts receivable, but we should be linking to Credit and collections overview.  This page defines what can be done with credit management.

**Comment by roschlom** [comment]
I can update the link in the Release plans topic, which is the one that's being referred to. Please not that Release plans are published on their own schedule, and the change won't be live until later this month. Thank you for letting us know about the issue!
