### ISSUE TITLE
Response JSON

### ISSUE THREAD

**Issue by AurelienClere-365** [MicrosoftDocs/dynamics-365-unified-operations-public#2275]
Hello,

Just notice a little mistake in your JSON Response. The ProjectID property is an integer and not a string.

Looks better like this.
{
    "IsSuccess": true,
    "OperationActivityId": "6a90b45f-1764-4077-b924-3f4671540237",
    "ErrorMessage": null,
    "VersionEOL": "9999-12-31T23:59:59.9999999",
    "ProjectId": 12345,
    "EnvironmentId": "5362377c-bc37-4f92-b30e-fe0c1e664cc0",
    "ActivityId": "55eb4327-9346-4c7b-82bd-fe8ef15112c6",
    "CompletionDate": null,
    "OperationStatus": "InProgress"
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ffb6bfc-cb23-e573-c686-cdc55e314583
* Version Independent ID: 6cdf207d-110e-9258-90b7-626952bdbb64
* Content: [Database movement API - Reference - v1 - Get status - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/api/v1/reference-get-status#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/database/api/v1/reference-get-status.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/database/api/v1/reference-get-status.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by tonyafehr** [comment]
Thanks for the feedback. 
@laneswenka, please review.

**Comment by tonyafehr** [comment]
Bug #440967 has been logged to track this issue.
