### ISSUE TITLE
Output to .txt file

### ISSUE THREAD

**Issue by TylerHills** [MicrosoftDocs/dynamics-365-unified-operations-public#2277]
Is there anyway to output to .txt file vs .xml?

I know you can change the output method to text, but that doesn't resolve the file format, itself.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a56dd618-9180-ed71-fd8e-850153f35b59
* Version Independent ID: 6322764e-1b61-5148-024a-0d6b124c0512
* Content: [Set up and generate positive pay files - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/accounts-payable/set-up-generate-positive-pay-files#feedback)
* Content Source: [articles/finance/accounts-payable/set-up-generate-positive-pay-files.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/accounts-payable/set-up-generate-positive-pay-files.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @abruer
* Microsoft Alias: **shpandey**

**Comment by tonyafehr** [comment]
Thanks for the feedback. 
@abruer, please review.

**Comment by tonyafehr** [comment]
@panolte, reassigning.

**Comment by tonyafehr** [comment]
Bug #440970 has been logged to track this issue.

**Comment by panolte** [comment]
The export file type is determined by the transformation stylesheet.  The sample stylesheet in the documentation exports only to .txt format.

**Comment by TylerHills** [comment]
> The export file type is determined by the transformation stylesheet. The sample stylesheet in the documentation exports only to .txt format.

Did you test it? Because that's not what I'm seeing when I go to save a positive pay file generated with the sample stylesheet (output method ="xml") or my own custom sheet (output method="text"). In chrome the file is automatically downloaded as .xml. In IE I have the ability to choose the file format to save except the only option is .xml, as seen in the image.

![image](https://user-images.githubusercontent.com/7749624/80164018-b82b9100-858c-11ea-908b-078788ae7324.png)

**Comment by panolte** [comment]
Tyler you are correct, the output type is xml not txt on the sample sheet.  Any change to this output would be a development experience through the stylesheets and transformations.
