### ISSUE TITLE
Cannot setup this, as three's no fiels as explained in "Organization administration > Setup > Organization email templates"

### ISSUE THREAD

**Issue by BernhardRaether** [MicrosoftDocs/dynamics-365-unified-operations-public#2278]
To Whom it may concern

I have followed this document strictly, until I tried to setup these settings:
- there is no "Overview" Tab - mine are called

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e01fce0-6590-5ea4-ebbf-a8379d4f810b
* Version Independent ID: 7b4cc58e-392c-c85d-d604-394f45cd9b4a
* Content: [Send email receipts from Modern POS (MPOS) - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/email-receipts)
* Content Source: [articles/commerce/email-receipts.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/email-receipts.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @jashanno
* Microsoft Alias: **jashanno**

**Comment by BernhardRaether** [comment]
![grafik](https://user-images.githubusercontent.com/44842967/79194617-2950a300-7e2d-11ea-84ee-ceb4dd94d957.png)

no intructions on what to enter into Priority or batch group.

No chance to configure "in the lower grid" (Where?) an additional Email ID "EmailRecpt" and no chance to enter an XML but to upload a file.

Please verify correct possibility of input.

**Comment by tonyafehr** [comment]
Thanks for the feedback. 
@jashanno and @josaw1, please review.

**Comment by tonyafehr** [comment]
Bug #440983 has been logged to track this issue.

**Comment by tonyafehr** [comment]
This has been updated and will be published later today.
