### ISSUE TITLE
Customer credit groups are shared credit limit

### ISSUE THREAD

**Issue by Kelkane** [MicrosoftDocs/dynamics-365-unified-operations-public#2279]
This document reads as if all customers in a Customer credit group will receive the amount specified in the Customer credit group when in reality, the Customer credit groups allow sharing of the credit limit among the Customer accounts associated within the group. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5eba805a-e0d4-4304-681a-9e09c8a0f69b
* Version Independent ID: 7b3c7663-36c4-0b78-a719-2dfaecbfbbfa
* Content: [Customer credit groups - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/accounts-receivable/cm-customer-credit-groups#feedback)
* Content Source: [articles/finance/accounts-receivable/cm-customer-credit-groups.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/accounts-receivable/cm-customer-credit-groups.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @mikefalkner
* Microsoft Alias: **mfalkner**

**Comment by tonyafehr** [comment]
Thanks for the feedback. 
@panolte, please review.

**Comment by panolte** [comment]
Thank you for brining this forward.  We will update the document to reflect the shared nature of the credit limit when implementing a credit group.
