### ISSUE TITLE
Great work and article!

### ISSUE THREAD

**Issue by NataliiaNaumenko** [MicrosoftDocs/dynamics-365-unified-operations-public#2284]
Great work and article! It is really helpful and it works. We have almost done the same setup. In addition, it would be great if we have a link to an article that describes how to upload certificates (public and private) to Azure Key Vault because it is really tricky to upload them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5483a595-caed-a879-51b4-a4d707a003ae
* Version Independent ID: c912c9ff-463f-8b10-a33a-ee8aa9725368
* Content: [VAT declaration for the Netherlands - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/emea-nl-vat-declaration#feedback)
* Content Source: [articles/finance/localizations/emea-nl-vat-declaration.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/localizations/emea-nl-vat-declaration.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @v-lurodi
* Microsoft Alias: **AnnBe**

**Comment by sericks007** [comment]
@NataliiaNaumenko, thank you for the feedback!

@v-lurodi, please consider updating the content based on the suggestion.

**Comment by sericks007** [comment]
Bug 441222 has been logged to track this issue.

**Comment by Anasyash** [comment]
Thank you for your comment! We have updated the link **Set up the Azure Key Vault client** in this topic to the respective topic with setup.
