### ISSUE TITLE
Repeating sentence

### ISSUE THREAD

**Issue by Kelkane** [MicrosoftDocs/dynamics-365-unified-operations-public#2287]
The following sentence is repeated at the end of the first paragraph then at the beginning of the second: 

TCA is a method of calculating the cost between the main formula item for a batch order and the co-products that are defined for the formula. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac539690-eba4-bb20-caaa-60d11bb9e0ed
* Version Independent ID: 40d3c424-03f1-db9c-05f3-2367999ade4e
* Content: [Total cost allocation method - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/cost-management/methodology-total-cost-allocation)
* Content Source: [articles/supply-chain/cost-management/methodology-total-cost-allocation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/cost-management/methodology-total-cost-allocation.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @AndersGirke
* Microsoft Alias: **mguada**

**Comment by sericks007** [comment]
@Kelkane, thanks for making us aware of this!

@kamaybac, please update the content.

**Comment by kamaybac** [comment]
@sericks007 , I fixed this in the private repo and merged it to master already, so I'm closing it here.
