### ISSUE TITLE
Question regarding Generate test user request in integration with MTD for VAT (UK)

### ISSUE THREAD

**Issue by LyD001** [MicrosoftDocs/dynamics-365-unified-operations-public#2288]
Good day,

I was trying to Generate a test user request and received the text file as in the document. However, as per the attached image, in my text file I was unable to find any UserID or password or VRN. I tried to go through all the set-up again but still unable to find them. Can somebody please enlighten me? I really appreciate.
[image](https://user-images.githubusercontent.com/63725992/79343334-79785400-7f58-11ea-8eb3-3427484b727c.png)

**Comment by sericks007** [comment]
@LyD001, thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
