### ISSUE TITLE
Resource on how to setup

### ISSUE THREAD

**Issue by LMedbery** [MicrosoftDocs/dynamics-365-unified-operations-public#2289]
It would be helpful to provide a link to other resources for sequence of setup, dependencies between modules, etc.
This is long-awaited functionality however the 'how-to' is greatly needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13472e1b-6d55-1cba-164c-0df6d2939c25
* Version Independent ID: 8d2a0fbb-c025-1486-e282-740373cb15dc
* Content: [Hazardous materials - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/pim/hazardous-materials-pim#feedback)
* Content Source: [articles/supply-chain/pim/hazardous-materials-pim.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/pim/hazardous-materials-pim.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @lachlancashMS
* Microsoft Alias: **conradv**

**Comment by sericks007** [comment]
@LMedbery, thank you for the feedback!

@kamaybac, please consider the suggestion.

**Comment by sericks007** [comment]
Bug 441224 has been logged to track this issue.

**Comment by kamaybac** [comment]
@LMedbery , I see that you submitted this quite a long time ago. I just ran into it while cleaning up. The topic you responded to here is out of date and is no longer part of our table of contents (as you correctly pointed out). The new HazMat documentation provides full details and is available here: https://docs.microsoft.com/en-us/dynamics365/supply-chain/pim/hazmat-overview
