### ISSUE TITLE
Project Category/resource Project/resource validation not covered

### ISSUE THREAD

**Issue by RobertRudd** [MicrosoftDocs/dynamics-365-unified-operations-public#2290]
The new dynamics 365 documentation does not cover:Project Category/resource Project/resource validation not covered https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/about-validation-in-projects

In the new documentation can we please be clear about what is the scope of project validation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88bcbff2-abb8-2048-a2bf-a678cc499015
* Version Independent ID: caa795a5-ed74-408b-9958-e6b15c0344ae
* Content: [Project management and accounting overview - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/project-management/overview-project-management-accounting#feedback)
* Content Source: [articles/finance/project-management/overview-project-management-accounting.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/project-management/overview-project-management-accounting.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @KimANelson
* Microsoft Alias: **knelson**

**Comment by kfend** [comment]
@RobertRudd  - Thanks for your feedback. We are working to finish up all of the Project management and accounting documentation. I have added this to our list of work items, but I can't confirm when it will be completed. I am going to close this issue, but will comment back here when the topic is written and published. Thanks!
@Yowelle for awareness.
