### ISSUE TITLE
Create Email Template - path wrong

### ISSUE THREAD

**Issue by BernhardRaether** [MicrosoftDocs/dynamics-365-unified-operations-public#2292]
DOC says: In the navigation pane, go to Modules &gt; Retail and commerce &gt; Headquarters setup &gt; Parameters &gt; Organization email templates.
there's no such path on my system. 
I am running Installed product version : 10.0.9 (10.0.383.10010)
Installed platform version : Update33 (7.0.5559.35512)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90ad114e-bfab-ee83-2c83-a1a665bcd975
* Version Independent ID: 00dd5f4b-6dc9-b2fc-359b-3ae2bec6f315
* Content: [Set up an email notification profile - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/email-notification-profiles)
* Content Source: [articles/commerce/email-notification-profiles.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/email-notification-profiles.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @samjarawan
* Microsoft Alias: **samjar**

**Comment by BernhardRaether** [comment]
![grafik](https://user-images.githubusercontent.com/44842967/79427814-9008c480-7fc5-11ea-842e-2a2b0d64335f.png)

**Comment by kfend** [comment]
@BernhardRaether - thanks for the feedback. 
@samjarawan and @josaw1 - can you please take a look at and address this question? Thanks!

**Comment by samjarawan** [comment]
This should go to @Stuart Hargreaves<mailto:stuharg@microsoft.com>

Thanks,
Sam

**Comment by samjarawan** [comment]
@Stuart Hargreaves<mailto:stuharg@microsoft.com>

**Comment by bicyclingfool** [comment]
It's definitely there. And it should show up for Bernard - his screenshot cuts off the rest of the selections under Parameters

**Comment by samjarawan** [comment]
Commented in GitHub, replying here as well. Organization email templates is definitely there, the screenshot in the comments appears to not show the next column of menu items

[cid:image001.png@01D613FD.9407C880]

From: Sam Jarawan <Sam.Jarawan@microsoft.com>
Sent: Thursday, April 16, 2020 1:55 PM
To: MicrosoftDocs/dynamics-365-unified-operations-public <reply@reply.github.com>; MicrosoftDocs/dynamics-365-unified-operations-public <dynamics-365-unified-operations-public@noreply.github.com>; Stuart Hargreaves <stuharg@microsoft.com>
Cc: Assign <assign@noreply.github.com>
Subject: RE: [MicrosoftDocs/dynamics-365-unified-operations-public] Create Email Template - path wrong (#2292)

This should go to @Stuart Hargreaves<mailto:stuharg@microsoft.com>

Thanks,
Sam

**Comment by BernhardRaether** [comment]
Have updated the screenshot with "Headquarters setup" expanded - according to the Docs it should be under Parameters" - to show you my config.

I am ADMIN on this machine.

Please let me know if I cn be of help here.

Regards, Bernhard


![grafik](https://user-images.githubusercontent.com/44842967/79717466-ffd6c200-82d9-11ea-9a93-9fbc9959452d.png)
