### ISSUE TITLE
D365 path correction for Key vault parameters

### ISSUE THREAD

**Issue by npeter21** [MicrosoftDocs/dynamics-365-unified-operations-public#2296]
The correct path for key vault parameters is System Administration &gt; Setup &gt; Key Vault parameters

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e29843f-4b7d-5b4b-6a71-d468e504f63c
* Version Independent ID: f72648ff-10e0-340e-6f51-b8c3766e1b6f
* Content: [Dynamics 365 Fraud Protection integration with Dynamics 365 Commerce - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/DFP?toc=%2Fdynamics365%2Fcommerce%2Ftoc.json#feedback)
* Content Source: [articles/commerce/dev-itpro/DFP.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/dev-itpro/DFP.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @rubendel
* Microsoft Alias: **rubendel**

**Comment by josaw1** [comment]
Thank you for your feedback. @rubencdelgado can you please verify?

**Comment by rubencdelgado** [comment]
For Commerce SKU it is Retail and Commerce > Headquarters setup > Parameters > Key Vault parameters

For full F&O it is System Administration > Setup > Key Vault parameters
