### ISSUE TITLE
Incomplete or invalid steps

### ISSUE THREAD

**Issue by brettchristiansen** [MicrosoftDocs/dynamics-365-unified-operations-public#2297]
In the "Update Commerce headquarters with the new Azure AD B2C information" section, steps 5-8 do not make any sense.  Either you need extra information about which number sequence to edit, or these are some irrelevant information unrelated to the setup that should be removed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7807b1d-0012-5619-26a6-a11881ffc94d
* Version Independent ID: 204cf318-00d8-f3ef-86cf-08589cb126f1
* Content: [Set up a B2C tenant in Commerce - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/set-up-b2c-tenant#reply-urls)
* Content Source: [articles/commerce/set-up-B2C-tenant.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/set-up-B2C-tenant.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @BrianShook
* Microsoft Alias: **BriShoo**

**Comment by josaw1** [comment]
Thanks for the feedback. @BrianShook can you please take a look?

**Comment by josaw1** [comment]
@BrianShook I created BUG 441790 to track this issue.

**Comment by josaw1** [comment]
Updates to the topic were published. Thanks.
