### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by brettchristiansen** [MicrosoftDocs/dynamics-365-unified-operations-public#2298]
In the "Create a password reset user flow policy" section, the field "Email Addresses" that needs to be selected has a carriage return between Email and Addresses so it appears as two line items when it should be one

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7807b1d-0012-5619-26a6-a11881ffc94d
* Version Independent ID: 204cf318-00d8-f3ef-86cf-08589cb126f1
* Content: [Set up a B2C tenant in Commerce - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/set-up-b2c-tenant#reply-urls)
* Content Source: [articles/commerce/set-up-B2C-tenant.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/set-up-B2C-tenant.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @BrianShook
* Microsoft Alias: **BriShoo**

**Comment by josaw1** [comment]
Thanks for the feedback. I fixed the typo and it will be republished today.
