### ISSUE TITLE
Missing step

### ISSUE THREAD

**Issue by brettchristiansen** [MicrosoftDocs/dynamics-365-unified-operations-public#2299]
The "Enter your AAD B2C tenant application information into Commerce" section has steps to create a new B2C application and ends with "Click OK".   If you stop here, and go to configure the channel, the B2C Application is not shown and when you return, to view B2C Settings, the application is not present.  After the existing steps, you have to click OK one more time to get to B2C settings page, and then click "Save" to actually save the new B2C application.   For now this doc is wrong, but hopefully the site is fixed to just save when users click OK eventually.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7807b1d-0012-5619-26a6-a11881ffc94d
* Version Independent ID: 204cf318-00d8-f3ef-86cf-08589cb126f1
* Content: [Set up a B2C tenant in Commerce - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/set-up-b2c-tenant#reply-urls)
* Content Source: [articles/commerce/set-up-B2C-tenant.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/set-up-B2C-tenant.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @BrianShook
* Microsoft Alias: **BriShoo**

**Comment by josaw1** [comment]
Thanks for your feedback. @BrianShook can you please review?

**Comment by josaw1** [comment]
@BrianShook I created BUG 441791 to track this.

**Comment by josaw1** [comment]
Updates to the topic were published. Thanks.
