### ISSUE TITLE
Item model groups

### ISSUE THREAD

**Issue by vavd** [MicrosoftDocs/dynamics-365-unified-operations-public#230]
I cannot find any info about item model group setup. Is it missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c85626b5-b808-da48-143b-f2b3a38b151c
* Version Independent ID: a8a383ba-90af-d2d3-21dd-fabb8ef09ace
* Content: [Inventory management home page - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/inventory/inventory-home-page)
* Content Source: [articles/supply-chain/inventory/inventory-home-page.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/inventory/inventory-home-page.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @YuyuScheller
* Microsoft Alias: **perlynne**

**Comment by ShylaThompson** [comment]
We have the following topic in our India documentation:  [https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/localizations/tasks/apac-ind-create-inventory-model-group](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/localizations/tasks/apac-ind-create-inventory-model-group)

Is this what you need?

**Comment by vavd** [comment]
Hi @ShylaThompson,
Thank you for the reply.
Yes, I need information about "Inventory management > Setup > Inventory > Item model groups." But the page you provided is about settings for Indian specific **fixed asset** functionality. I need the description in regard to **inventory management** functionality which is used around the globe. That is about reservations, physical/financial postings, etc.

**Comment by 3DFO** [comment]
Item model groups are to define some inventory policies and costing method.  There should be plenty of documentation.  Try the 2012 training guide on customer source. Not much has changed in D365FO for item model groups.
