### ISSUE TITLE
Unable to load the Extension package.

### ISSUE THREAD

**Issue by vigneshkumar93** [MicrosoftDocs/dynamics-365-unified-operations-public#2302]
I have done all the steps to enable the StoreHoursSample service. Finally when am trying to open the Cloud POS, the below error occurs.

Error: "The extension package could not be loaded. Either the extension manifest.json is not included in the extension package or it’s not formatted correctly."

URL: Extensions/StoreHoursSample

Can you please guide the steps to resolve this issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e7be8b1-1d84-84fe-46c3-6b2c9105f53f
* Version Independent ID: 9141550b-eeda-d4b7-1816-6be213206913
* Content: [View POS extension package information - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/view-pos-extension-package-details#feedback)
* Content Source: [articles/commerce/dev-itpro/view-pos-extension-package-details.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/dev-itpro/view-pos-extension-package-details.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @mumani
* Microsoft Alias: **mumani**

**Comment by RobinARH** [comment]
@mugunthanm - Hi Mugunthan - Can you take a look? (Also, I fixed the GitHub author on this topic.) thanks -Robin

**Comment by mugunthanm** [comment]
Can you please check the Java script console in VS or F12 (Developer console) for more details. Also check your manifest.json for any error.

**Comment by vigneshkumar93** [comment]
In manifest.json file there is no error. i have checked the F12 (Developer console) in internet explorer there also no error. how to check the Java script console in VS?

**Comment by vigneshkumar93** [comment]
Hi all, 
Without solving the issue how did you close this issue???
