### ISSUE TITLE
RecordInsertList questions

### ISSUE THREAD

**Issue by smartczh** [MicrosoftDocs/dynamics-365-unified-operations-public#2306]
Suppose we have a large amount of data to insert and I use the RecordInsertList to do that. Is there some best practice about the size of the RecordInsertList to insert each time (should I do that)? Or I just add all data into it first and then call insertDatabase(). I am just afraid the memory can't hold the large data, which may cause the insert operation run slowly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc08c66f-6eca-8bc3-b248-5f36a5465656
* Version Independent ID: 62c0ad9a-0356-0b68-fc6a-41a3e17c8f62
* Content: [X++ data selection and manipulation - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-ref/xpp-data-query#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-ref/xpp-data-query.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-ref/xpp-data-query.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **rhaertle**

**Comment by RobinARH** [comment]
@jorisdg - Hi Joris - Can you take a look? Thanks.

**Comment by jorisdg** [comment]
I don't think there is a one-size-fits-all solution. Much depends on the size of the table (number of fields etc.). It's also not just an issue of local memory, if the code ends up with hundreds of thousands of rows how long will the database call take? It's a delicate balance.

I will ask the performance team if they have some general guidance based on their experience.

**Comment by jorisdg** [comment]
As expected there's no one-size-fits-all answer. The performance experts suggested that if you really start talking about several thousands of records, to review if you can use insert record set. Ultimately the record insert list is still a list of records, all causing SQL statements. Insert record set is always far superior.
