### ISSUE TITLE
Onebox envinronments

### ISSUE THREAD

**Issue by wimvanhoof** [MicrosoftDocs/dynamics-365-unified-operations-public#231]
Which sqluser and sqlpwd parameters should we use for a downloaded Onebox environment? On which I don't know the passwords. Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f2a8d7e-56e8-2ef5-b7a1-4ccf54a6ce1e
* Version Independent ID: 985efdc1-7b47-ad77-4eb9-7bd940547843
* Content: [Maintenance mode - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/sysadmin/maintenance-mode)
* Content Source: [articles/dev-itpro/sysadmin/maintenance-mode.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/sysadmin/maintenance-mode.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @manalidongre
* Microsoft Alias: **manado**

**Comment by ShylaThompson** [comment]
Thanks for contacting us. Unfortunately, we can't handle support requests for the product here. To contact support, consider one of the options described here:  [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support)
