### ISSUE TITLE
Workflow configuration

### ISSUE THREAD

**Issue by RobertRudd** [MicrosoftDocs/dynamics-365-unified-operations-public#2312]
This page provides very limited information about how to configure the workflows or links to how generic workflow is configured.  Key issues:
- How is line level versus header lever approval configured.
- How is the Expense line item auto posting configured.  This is a fairly unique aspect of Expense report workflow management and should be documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2a2984b-d4f6-598a-759b-f4727db31afe
* Version Independent ID: 6a0e4f85-2e80-fc7a-4f9b-009bb052a8cd
* Content: [Set up workflows for Expense management - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/expense-management/expense-workflows)
* Content Source: [articles/finance/expense-management/expense-workflows.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/expense-management/expense-workflows.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @ShylaThompson
* Microsoft Alias: **shylaw**

**Comment by tonyafehr** [comment]
@RobertRudd, thanks for the feedback. 
@roschlom, please review and make updates, if needed.

**Comment by tonyafehr** [comment]
Bug #443094 logged to track this issue.
