### ISSUE TITLE
Time taken for Step 9 and the sync in to the solution 

### ISSUE THREAD

**Issue by Neill-KPMG** [MicrosoftDocs/dynamics-365-unified-operations-public#2313]
In following these steps i think it should be mentioned in step 9 that once the dual write has been configured it will take some time for the solution packages to be created in powerapps solutions section and you just need to wait.  Step 9 will show up in the end if you have followed the guide then you can complete the steps.  It took about 30 minutes for me to see this solution once I tried to install it as i believe it was queued behind all the other solutions that are load as part of the other set up steps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df8e9efc-9258-3876-e05f-20d35c907274
* Version Independent ID: 4b5041ec-4a48-0565-e47a-b972e65a6d60
* Content: [System requirements and prerequisites - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/requirements-and-prerequisites#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/requirements-and-prerequisites.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/dual-write/requirements-and-prerequisites.md)
* Technology: ****
* GitHub Login: @sabinn-msft
* Microsoft Alias: **v-douklo**

**Comment by tonyafehr** [comment]
@Neill-KPMG, thanks for the feedback. 
@sabinn-msft and @robinarh, please review.

**Comment by tonyafehr** [comment]
Bug #443097 logged to track this issue.

**Comment by tonyafehr** [comment]
This topic will be updated based on your feedback. Thanks!
