### ISSUE TITLE
Admin consent not required for the second app (step 5c. can be removed)

### ISSUE THREAD

**Issue by jimlcl** [MicrosoftDocs/dynamics-365-unified-operations-public#2314]
It seems the dual-write application with App ID: 2e49aa60-1bd3-43b6-8ab6-03ada3d9f08b - "Dynamics Data Integration" doesn't require admin consent, because it doesn't have any "admin consented permissions" in the application page. So the step 5 c. "Repeat the previous two steps for application ID 2e49aa60-1bd3-43b6-8ab6-03ada3d9f08b." is not needed and should be removed. If we try the consent URL with this ID, we get an AADSTS65002 error. All health checks are working with consent granted only for the first app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df8e9efc-9258-3876-e05f-20d35c907274
* Version Independent ID: 4b5041ec-4a48-0565-e47a-b972e65a6d60
* Content: [System requirements and prerequisites - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/requirements-and-prerequisites#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/requirements-and-prerequisites.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/dual-write/requirements-and-prerequisites.md)
* Technology: ****
* GitHub Login: @sabinn-msft
* Microsoft Alias: **v-douklo**

**Comment by tonyafehr** [comment]
@jimlcl, thanks for the feedback. 
@sabinn-msft and @RobinARH, please review.

**Comment by tonyafehr** [comment]
Bug #443098 logged to track this issue.

**Comment by sabinn-msft** [comment]
With dual-write core solution version 1.0.16.0, step 5 is no longer required. We have completely eliminated this step.
