### ISSUE TITLE
Sensitive data

### ISSUE THREAD

**Issue by zivenarc** [MicrosoftDocs/dynamics-365-unified-operations-public#2315]
It is absolutely not clear how to identify sensitive data in the system. Any flag on the vendors/customers/journals?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e632884f-83b4-2891-8eaf-75a4507c346d
* Version Independent ID: 40bea88f-b55d-1590-e7e0-8f400fc41b10
* Content: [Manage access to sensitive data - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/gdpr/gdpr-auditing-sensitive-data#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/gdpr/gdpr-auditing-sensitive-data.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/gdpr/gdpr-auditing-sensitive-data.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @toddlefor
* Microsoft Alias: **tlefor**

**Comment by tonyafehr** [comment]
@zivenarc, thanks for the feedback. 
@TLeforMicrosoft, please review.

**Comment by TLeforMicrosoft** [comment]
We do not mark data as "senstive" or "not sensitive."  It is up to each individual organization to determine what data that they deem sensitive. Each organization collects different types of data, and hold themselves accountable to various industry and legal obligations.
