### ISSUE TITLE
Securing the generation of positive pay from Administrator user

### ISSUE THREAD

**Issue by vjevtani** [MicrosoftDocs/dynamics-365-unified-operations-public#2317]
Hi, 

Is there any way we can stop any user with Admin rights from generating the positive pay files ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a56dd618-9180-ed71-fd8e-850153f35b59
* Version Independent ID: 6322764e-1b61-5148-024a-0d6b124c0512
* Content: [Set up and generate positive pay files - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/accounts-payable/set-up-generate-positive-pay-files#feedback)
* Content Source: [articles/finance/accounts-payable/set-up-generate-positive-pay-files.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/accounts-payable/set-up-generate-positive-pay-files.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @abruer
* Microsoft Alias: **shpandey**

**Comment by tonyafehr** [comment]
@vjevtani, thanks for the feedback. 
@abruer, please review.

**Comment by tonyafehr** [comment]
Bug #443100 logged to track this issue.

**Comment by panolte** [comment]
This would be security controlled access.  Typically the system administrator has authorizations for everything, but that is not a requirement.  Making this change would remove the access from all admin users.  You might want to consider creating an alternate/modified admin user to provide the appropriate access levels.
