### ISSUE TITLE
Update the Azure Storage Emulator

### ISSUE THREAD

**Issue by sinner83** [MicrosoftDocs/dynamics-365-unified-operations-public#2318]
I do according to the instructions, point Update the Azure Storage Emulator.

The following error occurs when executing the command:

C: \ Program Files (x86) \ Microsoft SDKs \ Azure \ Storage Emulator&gt; AzureStorageEmulator.exe init -server unname
Windows Azure Storage Emulator 4.0.0.0 command line tool
Error: User-specified instance not found. Please correct this and re-run initialization.

tried another way
The error remains the same:
C: \ Program Files (x86) \ Microsoft SDKs \ Azure \ Storage Emulator> AzureStorageEmulator.exe init -sqlinstance "MSSQLSERVER"
Windows Azure Storage Emulator 4.0.0.0 command line tool
Error: User-specified instance not found. Please correct this and re-run initialization.

Found another way: AzureStorageEmulator.exe init -server localhost -forcecreate

Another error occurs:

C: \ Program Files (x86) \ Microsoft SDKs \ Azure \ Storage Emulator&gt; AzureStorageEmulator.exe init -server localhost -forcecreate
Windows Azure Storage Emulator 4.0.0.0 command line tool
Error: Cannot create database.

In all cases, the command line was run as administrator

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d830cc4d-4375-3d2a-65d2-5427d1e8acdd
* Version Independent ID: cab504a7-d2d4-8722-5dd1-71ff1c39d04e
* Content: [Rename a local development (VHD) environment - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/vso-machine-renaming?source=docs#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/migration-upgrade/vso-machine-renaming.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/migration-upgrade/vso-machine-renaming.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @MargoC
* Microsoft Alias: **tabell**

**Comment by tonyafehr** [comment]
@sinner83, thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
@tariqbell, please review.

**Comment by sinner83** [comment]
Ok. Thank's for help.
