### ISSUE TITLE
Class attributes missing

### ISSUE THREAD

**Issue by goshoom** [MicrosoftDocs/dynamics-365-unified-operations-public#2320]
The article omits attributes of ExchangeRateProviderOanda class, without any explanation.
My understanding is that ExportAttribute('Microsoft.Dynamics.ApplicationSuite.FinancialManagement.Currency.Framework.IExchangeRateProvider') is necessary for the provider to work - ExchangeRateProviderFactory.loadProviders() looks 
for it. It's called when adding a provider through GUI (General ledger &gt; Currencies &gt; Configure exchange rate providers &gt; New). Therefore the solution is incomplete.
I also believe (although I'm not completely sure) that ExportMetadataAttribute isn't needed anymore, therefore it's not something which must be added to demonstrated solution, but it would be good to mention why the article doesn't match actual code of F&O.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac12066f-98e2-9fa2-e27e-ffc00572a6c6
* Version Independent ID: a42faab9-c4e7-38c5-e2fc-fd20d32de8fe
* Content: [Create exchange rate providers - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/financial/create-exchange-rate-providers#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/financial/create-exchange-rate-providers.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/financial/create-exchange-rate-providers.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **jbye**

**Comment by sericks007** [comment]
@goshoom, thank you for this feedback.

@RobinARH, please review.

**Comment by sericks007** [comment]
Bug 443470 has been logged to track this issue.

**Comment by RyanCCarlson2** [comment]
updated doc.

**Comment by sericks007** [comment]
Closing, as Ryan updated the content.
