### ISSUE TITLE
Maximum page size is 10000

### ISSUE THREAD

**Issue by JeroenLeeflang** [MicrosoftDocs/dynamics-365-unified-operations-public#2321]
I see the following text on this page "The OData service supports serving driven paging with a maximum page size of 1,000."

I think this is not correct. Should be 10000. That is also the amount we actually see when using OData.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d7c8b45-1531-ebbf-d417-4e1fe5bf4f1b
* Version Independent ID: c543a5fc-90c9-9edb-11d7-6d6d0f2c10a9
* Content: [Open Data Protocol (OData) - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/odata)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/odata.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/odata.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by sericks007** [comment]
@JeroenLeeflang, thank you for this feedback.

@Sunil-Garg, please review and update the content as necessary.

**Comment by sericks007** [comment]
Bug 443478 has been logged to track this issue.

**Comment by sericks007** [comment]
@JeroenLeeflang, thanks for making us aware of this.  The PM has updated topic -- the updated topic will be published later today.
