### ISSUE TITLE
Under section 'Managing endpoints', Logic Apps is missing

### ISSUE THREAD

**Issue by JeroenLeeflang** [MicrosoftDocs/dynamics-365-unified-operations-public#2322]
Logic Apps is not mentioned under 'Managing endpoints'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0cd4aef-33f1-d647-85eb-1a055ef216bd
* Version Independent ID: 73febada-4141-88bf-7a55-e8cc375dde92
* Content: [Business events overview - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/business-events/home-page)
* Content Source: [articles/fin-ops-core/dev-itpro/business-events/home-page.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/business-events/home-page.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by sericks007** [comment]
@JeroenLeeflang, thank you for this feedback!

@Sunil-Garg, please review and update the content as necessary.

**Comment by sericks007** [comment]
Bug 443480 has been logged to track this issue.

**Comment by Sunil-Garg** [comment]
@JeroenLeeflang LA is not mentioned since, its not a direct end point type. Hope this clarifies. Thanks.
