### ISSUE TITLE
Replace Flow by Power Automate

### ISSUE THREAD

**Issue by JeroenLeeflang** [MicrosoftDocs/dynamics-365-unified-operations-public#2324]
Microsoft Flow is still mentioned on this page. Should be replaced by 'Power Automate'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0cd4aef-33f1-d647-85eb-1a055ef216bd
* Version Independent ID: 73febada-4141-88bf-7a55-e8cc375dde92
* Content: [Business events overview - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/business-events/home-page)
* Content Source: [articles/fin-ops-core/dev-itpro/business-events/home-page.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/business-events/home-page.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by sericks007** [comment]
@JeroenLeeflang, thanks for bringing this to our attention! We'll work to update this.

**Comment by sericks007** [comment]
The updated content will be published later today. Thanks again!

**Comment by JeroenLeeflang** [comment]
Thanks!
