### ISSUE TITLE
Standard cost now requires a close job to be ran

### ISSUE THREAD

**Issue by iangorman2020** [MicrosoftDocs/dynamics-365-unified-operations-public#2328]
As of 10.0.10 PU34, you must run the close job for all item model group costing methods if there has been an inventory transaction for the period.

You are about to change the status of ledger period Period 5 to On hold. No execution of Inventory close with a date 5/31/2020 matching period end has been registered. Please execute an inventory close as of 5/31/2020 matching the period end before changing the status. The valuation of inventories, cost of goods sold and variances may not be correct in Subledger or General ledger until this has been executed. Reported from legal entity XXX.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1da3a33-3988-e8de-8a7a-472760c710a9
* Version Independent ID: 4c71af1a-a898-7ee2-27ae-bb083b8a19dd
* Content: [Inventory close - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/cost-management/inventory-close#feedback)
* Content Source: [articles/supply-chain/cost-management/inventory-close.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/cost-management/inventory-close.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @AndersGirke
* Microsoft Alias: **shylaw**

**Comment by josaw1** [comment]
Thanks for the comment. @AndersEvenGirke can you please review?

**Comment by iangorman2020** [comment]
Josaw - Looks like the update went through to the page, we can probably close out the comment.
