### ISSUE TITLE
Add restrictions on Chain of Command for new method (constructor)

### ISSUE THREAD

**Issue by gertvdh** [MicrosoftDocs/dynamics-365-unified-operations-public#2329]
it doesn't seem possible to wrap the constructor, you get compiler warning "Can't define protected method new() in a final class"

Also when the constructor has a parameter, you get compiler error "an extension class can only have a parameterless constructor"

it has been described in https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/extensibility/class-extensions, but maybe it needs to be highlighted in the CoC page too

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4317fdb2-b37f-550d-f229-bfd8498ab073
* Version Independent ID: ecd0974c-0abc-c494-cc8c-e81e7cf096f9
* Content: [Class extension - Method wrapping and Chain of Command - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/extensibility/method-wrapping-coc)
* Content Source: [articles/fin-ops-core/dev-itpro/extensibility/method-wrapping-coc.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/extensibility/method-wrapping-coc.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @ChrisGarty
* Microsoft Alias: **cgarty**

**Comment by kfend** [comment]
@gertvdh - Thanks for the feedback.
@ChrisGarty  - Please review and update the content as necessary.
