### ISSUE TITLE
Finding "Report Designer" to export Building Block groups

### ISSUE THREAD

**Issue by beeporama** [MicrosoftDocs/dynamics-365-unified-operations-public#233]
If you're a tech guy who has never touched financial reports, are working with 7.0, and find yourself trying to figure out how the heck to get to "Report Designer" per the documentation: go to General ledger &gt; Inquiries and reports &gt; Financial reports, then click "New." A download will be required.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcccc152-564f-c7cb-ccbd-06686e3ae999
* Version Independent ID: ecbaf175-9401-36f5-d416-95b26823bf11
* Content: [Reset the Financial reporting data mart for Finance and Operations - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/reset-financial-reporting-datamart-after-restore?toc=/fin-and-ops/toc.json)
* Content Source: [articles/dev-itpro/analytics/reset-financial-reporting-datamart-after-restore.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/reset-financial-reporting-datamart-after-restore.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @aprilolson
* Microsoft Alias: **aolson**

**Comment by tonyafehr** [comment]
Thanks for taking the time to provide feedback. Your comment has been noted as a future enhancement to the documentation.
