### ISSUE TITLE
Number sequences setting update is missing target

### ISSUE THREAD

**Issue by GordonLam** [MicrosoftDocs/dynamics-365-unified-operations-public#2333]
In this section Update Commerce headquarters with the new Azure AD B2C information:
https://docs.microsoft.com/en-us/dynamics365/commerce/set-up-b2c-tenant#update-commerce-headquarters-with-the-new-azure-ad-b2c-information
Step 5-8 about update a setting on Number sequences, it doesn't specify what particular "Number sequences" should be updated. If Customer follow this, they will just update the 1st Number sequence setting only, which doesn't make sense.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7807b1d-0012-5619-26a6-a11881ffc94d
* Version Independent ID: 204cf318-00d8-f3ef-86cf-08589cb126f1
* Content: [Set up a B2C tenant in Commerce - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/set-up-b2c-tenant#feedback)
* Content Source: [articles/commerce/set-up-B2C-tenant.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/set-up-B2C-tenant.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @BrianShook
* Microsoft Alias: **BriShoo**

**Comment by RobinARH** [comment]
@BrianShook Hi Brian - Can you take a look? thanks.

**Comment by RobinARH** [comment]
We've updated the topic.
