### ISSUE TITLE
Wrong app mentioned in topic

### ISSUE THREAD

**Issue by obuurman** [MicrosoftDocs/dynamics-365-unified-operations-public#2337]
To view the CDS log files you need to login into the CE / CDS app, not the Finance and Operations app

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 036570ee-85fa-8449-be1c-a5e8755e175c
* Version Independent ID: 2468c8f9-0814-ded0-c6dd-879851a4b9e1
* Content: [Dual-write overview - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/dual-write-overview#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/dual-write-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/dual-write/dual-write-overview.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @RamaKrishnamoorthy
* Microsoft Alias: **ramasri**

**Comment by tonyafehr** [comment]
@obuurman, thanks for the feedback. 
@RobinARH and @RamaKrishnamoorthy, please review. Thank you!

**Comment by RamaKrishnamoorthy** [comment]
I don't see any text that says "log file" or a link on the overview page. Is this feedback given for a different page?

**Comment by obuurman** [comment]
The feedback is on this page:
https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/dual-write-troubleshooting

[cid:image004.jpg@01D61E01.364F5E20]

Sorry for the inconvenience if I was not clear enough …

Met vriendelijke groet, kind regards,​
Otto Buurman
Enterprise Solution Architect
[HSO]<https://www.hso.com/nl>
M +31653773816<tel:+31653773816>
T +31318509400

**Comment by RamaKrishnamoorthy** [comment]
Thank you for reporting, we will make change to the text.

**Comment by tonyafehr** [comment]
Bug #456968 logged to track this issue.
