### ISSUE TITLE
Import or Export?

### ISSUE THREAD

**Issue by wojzeh** [MicrosoftDocs/dynamics-365-unified-operations-public#2339]
These two phrases repeated twice; first time in Export section, second in Troubleshooting the System users entity. Either it is incorrect or we missed some detail here.

 - While importing the system users entity, you may receive an integrity violation error if there is a guest user in the exported package. The guest user must be deleted from the package in order for the entity to work.
- If a record already exists in the UserInfo table (the Admin record would most likely always exist), the import will fail for those records but work for other records

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1016eba2-a0f9-8890-beb4-7c9f9f6df4fc
* Version Independent ID: 57758813-9d36-975a-eb6f-551b7da3e276
* Content: [Data management overview - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/data-entities-data-packages)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/data-entities-data-packages.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/data-entities-data-packages.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by tonyafehr** [comment]
@wojzeh, thanks for the feedback. 
@Sunil-Garg, please review.

**Comment by Sunil-Garg** [comment]
@wojzeh thanks for highlighting that; we have removed that content from this doc as this was not the right doc for entity specific comments, anyway. Thanks again.
