### ISSUE TITLE
Clarify PEAPS

### ISSUE THREAD

**Issue by jawn** [MicrosoftDocs/dynamics-365-unified-operations-public#234]
PEAPS is mentioned in the diagram, but not in the text. Add it to the text with a brief explanation so it is clear how it matches the diagram.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1892de7-0902-054b-e430-8e23f714477b
* Version Independent ID: 20e0ff84-5f29-f5e3-ddde-288e52059ad0
* Content: [Standard and targeted platform releases - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/public-preview-releases#feedback)
* Content Source: [articles/fin-and-ops/get-started/public-preview-releases.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/public-preview-releases.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @kfend
* Microsoft Alias: **kfend**

**Comment by sericks007** [comment]
Bug 238418 was logged for tracking purposes.

**Comment by jawn** [comment]
Closing this issue since it's already fixed.
