### ISSUE TITLE
Documentation is incomplete

### ISSUE THREAD

**Issue by RobertRudd** [MicrosoftDocs/dynamics-365-unified-operations-public#2342]
This documentation in incomplete.  This process should either state the Fixed Asset needs to be created or have the process for creating a Fixed Asset.  A key piece of information left out of this documentation is for the acquisition journal to work, you must have a acquisition price on the fixed assets.    This should be documented here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6bd2315-361d-a269-e644-932d0e7d1136
* Version Independent ID: 3f6b368b-fa55-0a79-59af-1606caad0cc5
* Content: [Propose fixed asset acquisitions - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/fixed-assets/tasks/propose-fixed-asset-acquisitions)
* Content Source: [articles/finance/fixed-assets/tasks/propose-fixed-asset-acquisitions.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/fixed-assets/tasks/propose-fixed-asset-acquisitions.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @saraschi2
* Microsoft Alias: **saraschi**

**Comment by sericks007** [comment]
@RobertRudd, thank you for your feedback!

@roschlom, please assign to the appropriate PM.

**Comment by sericks007** [comment]
Bug 445543 has been logged to track this issue.
