### ISSUE TITLE
Select environment topology topic is not updated. 

### ISSUE THREAD

**Issue by d47447** [MicrosoftDocs/dynamics-365-unified-operations-public#2343]
[Enter feedback here]
Team,

This document is not updated as per the latest available steps in LCS. While landing to 'Select environment topology' step its showing attached image options not as per this document. Kindly check if update is required. 

Thanks
Deepak

 
![image](https://user-images.githubusercontent.com/10023144/80558750-0d3a2d80-89f9-11ea-9a30-1660f6c5a190.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe3913a6-4daa-9973-6f0b-d7ae4c1007c2
* Version Independent ID: f2cd311b-fcb8-cff4-57a3-47c3c52b19d6
* Content: [Deploy and access development environments - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/access-instances#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/access-instances.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-tools/access-instances.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @jorisdg
* Microsoft Alias: **jorisde**

**Comment by sericks007** [comment]
@d47447, thank you for this feedback.

@jorisdg, please review and update the content.

**Comment by sericks007** [comment]
@laneswenka, please review and update the content.

**Comment by sericks007** [comment]
Bug 7167875 has been logged to track this issue.
