### ISSUE TITLE
Extra semicolon gives an error

### ISSUE THREAD

**Issue by Halldor10** [MicrosoftDocs/dynamics-365-unified-operations-public#2344]
Is in the document: 
&lt;add name="ext.AppInsightsKey" value="xxxxxxx"/&gt;;
Should be without the semicolon, as the semicolon will give an arise to an error in the config file:
&lt;add name="ext.AppInsightsKey" value="xxxxxxx"/&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f659eadc-c39c-a5e4-cfe4-27fea2f77523
* Version Independent ID: 48e06663-f4a1-b540-db40-147b35a840f9
* Content: [Log extension events to Application Insights - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/commerce-application-insights#feedback)
* Content Source: [articles/commerce/dev-itpro/commerce-application-insights.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/dev-itpro/commerce-application-insights.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by sericks007** [comment]
@Halldor10, thanks for making us aware of the issue. I've updated the content, and the update will be published later today.
