### ISSUE TITLE
4. Select Create

### ISSUE THREAD

**Issue by Halldor10** [MicrosoftDocs/dynamics-365-unified-operations-public#2345]
Did not understand how the image "Create Deployment Package" was relevant in step 4.

A general information on how Application Insights" can be used for standard RetailServer, would be helpful for the general understanding on how it is related to the use in the customer extensions. 

Also more examples for other "Application Insights API" and usage could be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f659eadc-c39c-a5e4-cfe4-27fea2f77523
* Version Independent ID: 48e06663-f4a1-b540-db40-147b35a840f9
* Content: [Log extension events to Application Insights - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/commerce-application-insights#feedback)
* Content Source: [articles/commerce/dev-itpro/commerce-application-insights.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/dev-itpro/commerce-application-insights.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by sericks007** [comment]
@Halldor10, thank you for this feedback.

@mugunthanm, please review and update the content.

**Comment by mugunthanm** [comment]
Updated the doc to remove the wrong image.

**Comment by sericks007** [comment]
@mugunthanm, thanks!
