### ISSUE TITLE
Why only Hungary & Poland?

### ISSUE THREAD

**Issue by Marcob45** [MicrosoftDocs/dynamics-365-unified-operations-public#2346]
Why is this functionality only available for Hungary & Poland. Most companies would carry out this type of transaction if they have a customer that is also a supplier.
Functionality should be made more widely available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c85d41a-3795-ac2a-19fc-a1d3ce57b603
* Version Independent ID: 5b00762f-63ff-50e9-d9b6-4323e5e0ee27
* Content: [Set up customer and vendor compensation - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/emea-compensation-customer-vendor-transactions#feedback)
* Content Source: [articles/finance/localizations/emea-compensation-customer-vendor-transactions.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/localizations/emea-compensation-customer-vendor-transactions.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @mrolecki
* Microsoft Alias: **mrolecki**

**Comment by sericks007** [comment]
@Marcob45, thank you for this feedback.

@mrolecki, please review and comment.

**Comment by sericks007** [comment]
Bug 445545 has been logged to track this issue.

**Comment by mrolecki** [comment]
Thank you for finding time to share your feedback. We understand this functionality might applicable after some enhancements for multiple countries and opening it would be potentially beneficial but as of now it is not considered in the product roadmap. As it’s more of a feature request \ suggestion kind, I would encourage you to log a idea at [https://experience.dynamics.com/](https://experience.dynamics.com/) so other customers can review it and vote on. All the respective teams regularly review and evaluate suggestions and use number of votes as a data point to help with identifying candidates for our future work.
