### ISSUE TITLE
nice article

### ISSUE THREAD

**Issue by goyalsachingithub** [MicrosoftDocs/dynamics-365-unified-operations-public#2347]
good one

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb989a7c-badf-ef59-1d23-93cbd6eacf75
* Version Independent ID: 1d7975bb-0e0d-3d36-c422-117fd2539f15
* Content: [Configure SQL Server Reporting Services for on-premises deployments - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/configure-ssrs-on-premises)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/configure-ssrs-on-premises.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/configure-ssrs-on-premises.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @PeterRFriis
* Microsoft Alias: **perahlff**

**Comment by sericks007** [comment]
@goyalsachingithub, thank you for the feedback!
