### ISSUE TITLE
There is no longer an abort option available. The is no "batch tasks" tab. Please update with correct procedures.

### ISSUE THREAD

**Issue by ronsonntag54** [MicrosoftDocs/dynamics-365-unified-operations-public#2349]
This is critical for aborting a job where potentially multi-threaded tasks get caught in a deadly embrace. Need an abort option. Stopping and starting batch process does not fix this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 039578b3-090d-6a77-0332-8d395e778a4f
* Version Independent ID: 13efa978-3d01-eb57-4a65-e963692f8cc8
* Content: [Abort an executing batch job - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/batch-abort)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/batch-abort.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/sysadmin/batch-abort.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Peakerbl
* Microsoft Alias: **peakerbl**

**Comment by josaw1** [comment]
Thank you for your feedback. @Peakerbl please take a look.

**Comment by Peakerbl** [comment]
I'm not able to follow. There is a Batch Task tab and the Abort option will be enabled if the status is set to Canceling per the documentation. This is from the latest build: 
![image](https://user-images.githubusercontent.com/38867669/81340862-693e2b00-9065-11ea-83c2-8a726381414d.png)

**Comment by Peakerbl** [comment]
Just make sure to used the enhanced form, there is a Switch action to use this and this is expected to become the default version:
![image](https://user-images.githubusercontent.com/38867669/81341180-fb463380-9065-11ea-93de-abb8e111d8d3.png)
