### ISSUE TITLE
AI, ML in Cash flow forecasting

### ISSUE THREAD

**Issue by vaibhavagarwaljss** [MicrosoftDocs/dynamics-365-unified-operations-public#235]
I am looking for OOTB AI, ML scenarios in Cash flow forecasting. In this and Cash overview Power BI content I don't find any mention of Azure ML. Are you leveraging AI, ML in this scenario? If yes, please share details. If not, what are the plans to include it? 

Thanks
Vaibahv Agarwal
Microsoft Services 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 764b7a5e-d181-16fe-b544-d9a0cf4dd86d
* Version Independent ID: 82bab660-3c88-8b2d-0ae9-297fd6e458da
* Content: [Cash flow forecasting - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/cash-bank-management/cash-flow-forecasting)
* Content Source: [articles/financials/cash-bank-management/cash-flow-forecasting.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/cash-bank-management/cash-flow-forecasting.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @saraschi2
* Microsoft Alias: **saraschi**

**Comment by ShylaThompson** [comment]
Thanks for contacting us. For discussions about how to use features, we recommend that you post on the [Finance and Operations community forum](https://community.dynamics.com/365/financeandoperations/f/765). 

If this is a feature idea, please use the [Ideas site](https://experience.dynamics.com/ideas/list/?forum=16691718-61e2-e611-8101-5065f38b21f1) to submit it directly. If you submit an idea on the [Ideas site](https://experience.dynamics.com/ideas/list/?forum=16691718-61e2-e611-8101-5065f38b21f1),  you can receive notifications, vote, and monitor the progress of your idea more closely.
