### ISSUE TITLE
Shared Entity Backed Dimensions List

### ISSUE THREAD

**Issue by MMT0905** [MicrosoftDocs/dynamics-365-unified-operations-public#2352]
Is there a list of what entity-backed dimensions are capable of being shared, and which are not?

**Comment by josaw1** [comment]
Hi @MMT0905, are you commenting on a specific topic, or asking a general support question? Thanks.

**Comment by MMT0905** [comment]
General support.  I was thinking for discovery and testing purposes, it
would be beneficial to have a list of which entity backed dimensions can be
shared across companies or not, without just having to test by trial and
error.

**Comment by josaw1** [comment]
Thanks for your feedback. We will take it into consideration for updating the documentation. If you need support, though, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
