### ISSUE TITLE
Why is this document also under folder Replenishment

### ISSUE THREAD

**Issue by KarinaNormannJakobsen** [MicrosoftDocs/dynamics-365-unified-operations-public#2353]
Why is this document also under folder Replenishment

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e63190a-81d0-e49f-8e8a-ff3be8c99b12
* Version Independent ID: 4efd3b72-2359-a206-374f-95524ac0486a
* Content: [Set up a work template for purchase orders - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/warehousing/tasks/set-up-work-template-purchase-orders#feedback)
* Content Source: [articles/supply-chain/warehousing/tasks/set-up-work-template-purchase-orders.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/warehousing/tasks/set-up-work-template-purchase-orders.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @ShylaThompson
* Microsoft Alias: **shylaw**

**Comment by josaw1** [comment]
Thank you for your question. @kamaybac can you please take a look?

**Comment by kamaybac** [comment]
I agree. I don't think this belongs under replenishment. I removed that link. It's still listed under Receipts for registration and put-away.
