### ISSUE TITLE
Address Book security is not explained 

### ISSUE THREAD

**Issue by HenrikLevinsonAccigo** [MicrosoftDocs/dynamics-365-unified-operations-public#2354]
Add a description how you could restrict access to Address books via the teams. Or advise where documented om the Configure address books node.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c31a8e-d47d-7a38-3256-dd4c09a0945b
* Version Independent ID: 23e3b435-96a6-4c6d-be19-281f1f82df58
* Content: [Plan for the global address book and other address books - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/organization-administration/plan-configuration-global-address-book-additional-address-books?toc=%2Fdynamics365%2Ffinance%2Ftoc.json#feedback)
* Content Source: [articles/fin-ops-core/fin-ops/organization-administration/plan-configuration-global-address-book-additional-address-books.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/organization-administration/plan-configuration-global-address-book-additional-address-books.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @msftbrking
* Microsoft Alias: **brking**

**Comment by josaw1** [comment]
Thank you for your feedback. @msftbrking can you please review?

**Comment by msftbrking** [comment]
@josaw1 - The comment is regarding a feature we had in AX 2012 that we do not yet have in the Rainier versions. The 2012 version of this docs article has the details on these steps. I removed that information from this article until we have the feature delivered. It is detailed in the following article:
https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/ax-2012-features-not-implemented-but-not-deprecated?toc=/dynamics365/finance/toc.json.
