### ISSUE TITLE
CDS Premium requirement unclear

### ISSUE THREAD

**Issue by D365Princess** [MicrosoftDocs/dynamics-365-unified-operations-public#2355]
If you progress these steps on a tenant which does not have customer engagement licenses then you are unable to do the last step as your CDS instance does not have the dependencies which are resolved with the sales/field service add on which come with premium. This either needs to be clarified in the pre-steps to be made clear for tier1 &lt;&gt; CDS implementations you need to use CDS premium as part of a customer engagement license model or the contents of the other solutions which are deployed adjusted to remove this dependency gap.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df8e9efc-9258-3876-e05f-20d35c907274
* Version Independent ID: 4b5041ec-4a48-0565-e47a-b972e65a6d60
* Content: [System requirements and prerequisites - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/requirements-and-prerequisites)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/requirements-and-prerequisites.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/dual-write/requirements-and-prerequisites.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @sabinn-msft
* Microsoft Alias: **sabinn**

**Comment by josaw1** [comment]
Thank you for your feedback. @sabinn-msft can you please review?

**Comment by josaw1** [comment]
BUG 446373 created to track.

**Comment by josaw1** [comment]
As per @RamaKrishnamoorthy: it has been documented here - https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/requirements-and-prerequisites. Please follow the screenshot to identify the pre-requisites.
