### ISSUE TITLE
Mapping-specific notes incorrect for Finance

### ISSUE THREAD

**Issue by jwinkeler74** [MicrosoftDocs/dynamics-365-unified-operations-public#2358]
Mapping-specific notes 4 and 5 for finance have the exact same text, and look to be a combination of what they should be (the both reference Sales.Contact and msdyn_contactforvendor).  Both CDS Contacts V2 list the entity as Common Data Service.Contact, and going to the 'Details' tab is the only way to see which is for customers or vendors.  Based on what is delivered from the latest solution, the filter for the customer contacts should be: "msdyn_contactfor eq 'Customer' and msdyn_sellable eq false and msdyn_contactpersonid ne null".  For vendors it should be: "msdyn_contactforvendor eq true and msdyn_sellable eq false and msdyn_contactpersonid ne null"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b47748e-61d4-472c-a389-4914f7c99c62
* Version Independent ID: a15a8115-9b3a-ab4b-6089-d0692e880ae0
* Content: [Entity dependency chain (synchronization order) - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/initial-sync#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/initial-sync.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/dual-write/initial-sync.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @RamaKrishnamoorthy
* Microsoft Alias: **ramasri**

**Comment by josaw1** [comment]
Thank you for your feedback. @RamaKrishnamoorthy can you please review?

**Comment by RamaKrishnamoorthy** [comment]
Yes I have reviewed and applied correction. Thank you both!
