### ISSUE TITLE
Need to document Business Events Key Management best practices

### ISSUE THREAD

**Issue by grantph** [MicrosoftDocs/dynamics-365-unified-operations-public#2359]
The docs are good are describing how to set up Azure endpoints (e.g., Event Grid and Service Bus), however, there are no docs on how frequently business events accesses Azure keyVault to retrieve secrets (e.g., on demand, hourly, daily, etc?), or what would happen if keys were changed.

For example, as a security best practice many enterprises may need to rotate secrets in EG or SB. How would D365 Business events know that these changes have occurred? Are we expected to restart D365? Presumably this is not practical if there were a daytime security breach that forced an organisation to change keys.

Some guidance into how Business Events uses secrets would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0cd4aef-33f1-d647-85eb-1a055ef216bd
* Version Independent ID: 73febada-4141-88bf-7a55-e8cc375dde92
* Content: [Business events overview - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/business-events/home-page)
* Content Source: [articles/fin-ops-core/dev-itpro/business-events/home-page.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/business-events/home-page.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by kfend** [comment]
@grantph - thanks for the suggestion.
@Sunil-Garg - please review this request and consider adding it to the list of planned future content.
