### ISSUE TITLE
Add updated content from the "Implementing the Account and Financial Dimensions Framework for Microsoft  Dynamics AX 2012 Applications" white paper

### ISSUE THREAD

**Issue by FH-Inway** [MicrosoftDocs/dynamics-365-unified-operations-public#236]
To get a better understanding of the data structures and code patterns of the financial dimensions, it would be helpful if the content of the white paper "Implementing the Account and Financial Dimensions Framework for Microsoft  Dynamics AX 2012 Applications" were updated and added here. 
http://download.microsoft.com/download/4/E/3/4E36B655-568E-4D4A-B161-152B28BAAF30/Implementing_the_Account_and_Financial_Dimensions_Framework_AX2012.pdf

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43547f72-2002-8d31-5021-75fbe59904b9
* Version Independent ID: 20d13489-c250-c57b-42d9-7a56362ba7ba
* Content: [Financials development home page - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/financial/financial-dev-home-page)
* Content Source: [articles/dev-itpro/financial/financial-dev-home-page.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/financial/financial-dev-home-page.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RobinARH
* Microsoft Alias: **robinr**

**Comment by tonyafehr** [comment]
Thanks for taking the time to provide feedback. Your comment has been noted as a future enhancement to the documentation.

**Comment by tonyafehr** [comment]
I did some additional research and found that we have a series of blog posts created for both understanding the data model portion as well as the uptake code example area through defaulting scenarios. 

7 part series on dimensions data model (developer-level):
[(https://blogs.msdn.microsoft.com/ax_gfm_framework_team_blog/2013/02/15/ledger-account-combinations-part-1-dimensions/))]

7 part series on dimension defaulting / API’s used for that (support/developer-level):
[https://blogs.msdn.microsoft.com/ax_gfm_framework_team_blog/2014/09/12/dimension-defaulting-part-1-financial-dimensions-discovery/]

6 part series on dimension defaulting in accounting distributions (user/support-level):
[https://blogs.msdn.microsoft.com/ax_gfm_framework_team_blog/2013/12/16/dimension-defaulting-in-accounting-distributions-part-1-introduction/]

**Comment by FH-Inway** [comment]
Thanks for the information. Since these were written in 2013 and 2014, they are similarly outdated as the content from the white paper. The blog articles are also even harder to find than the white paper. I suggest making the content from both the white paper and the blog more visible and more current by incorporating it into the documentation.
