### ISSUE TITLE
Some Entities in wrong order or missing

### ISSUE THREAD

**Issue by Neill-KPMG** [MicrosoftDocs/dynamics-365-unified-operations-public#2360]
Hello,

1. The Entity Sales Tax Codes in the Finance section is not in the mapping solution.  This should be removed from here or added tot he solution.

2. A number of the items on the list are out of order due to dependencies.  So for example Default order settings in the SCM list is asked for before Sites and Warehouses which are dependant.  They then appear in the list later but they are already on.  Ideally all dependant entities are in the list before removing the need for this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b47748e-61d4-472c-a389-4914f7c99c62
* Version Independent ID: a15a8115-9b3a-ab4b-6089-d0692e880ae0
* Content: [Entity dependency chain (synchronization order) - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/initial-sync)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/initial-sync.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/dual-write/initial-sync.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @RamaKrishnamoorthy
* Microsoft Alias: **ramasri**

**Comment by RobinARH** [comment]
@RamaKrishnamoorthy Hi Rama - Can you take a look? Thanks.

**Comment by RamaKrishnamoorthy** [comment]
I am waiting for couple of responses from dual-write platform team and SCM team. Will make the change as soon as I hear from them.

**Comment by RobinARH** [comment]
We've removed that topic. Instead, see [Enable entity maps for dual-write](https://docs.microsoft.com/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/enable-entity-map). - Robin
