### ISSUE TITLE
Product Categories 

### ISSUE THREAD

**Issue by Neill-KPMG** [MicrosoftDocs/dynamics-365-unified-operations-public#2361]
Hello,

The official guidance for existing data on Product Categories is;

"Existing product categories needs to be manually synced (for example by updating the description of the category) in the right order (root category first, then children, then children of children)
Path: Product information management &gt; Setup &gt; Categories and attributes &gt; Category hierarchies form, from which you can select each hierarchy and see the product categories in it.

This is needed due to parent-child relations for categories."

I think this should be included in the page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b47748e-61d4-472c-a389-4914f7c99c62
* Version Independent ID: a15a8115-9b3a-ab4b-6089-d0692e880ae0
* Content: [Entity dependency chain (synchronization order) - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/initial-sync)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/initial-sync.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/dual-write/initial-sync.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @RamaKrishnamoorthy
* Microsoft Alias: **ramasri**

**Comment by RobinARH** [comment]
We've removed that topic. Instead, see [Enable entity maps for dual-write](https://docs.microsoft.com/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/enable-entity-map). - Robin
