### ISSUE TITLE
The paths have changed

### ISSUE THREAD

**Issue by dodiggitydag** [MicrosoftDocs/dynamics-365-unified-operations-public#2362]
Please double check the paths.  AP should reflect:
Accounts payable &gt; Payment setup &gt; Due date limits
Accounts payable &gt; Payment setup &gt; Terms of payment

I did not check AR.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1b3a606-6957-74a3-58c5-93de500f46a9
* Version Independent ID: 957a0ed2-9eee-3844-3059-d4f48f656530
* Content: [Calculate due dates and report on the average period of payments (Spain) - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/emea-esp-invoice-due-dates#feedback)
* Content Source: [articles/finance/localizations/emea-esp-invoice-due-dates.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/localizations/emea-esp-invoice-due-dates.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @ShylaThompson
* Microsoft Alias: **anasyash**

**Comment by tonyafehr** [comment]
@dodiggitydag, thank you for the feedback.
@Anasyash, please review and consider updating this topic.

**Comment by tonyafehr** [comment]
Bug #447425 logged to track this issue.

**Comment by v-oloski** [comment]
@dodiggitydag  thank you for the feedback.
You are right the correct path is 
Accounts payable > Payment setup > Due date limits
Accounts payable > Payment setup > Terms of payment
And the same in the AR
Accounts receivable > Payment setup > Due date limits
Accounts receivable > Payment setup > Terms of payment

I've created task for documentation  updating.
