### ISSUE TITLE
Registeration process - Step#3 sign on URL should be without trailing "/"... otherwise Power BI authroization throws error "The reply URL specified in the request does not match the reply URLs configured for the application"

### ISSUE THREAD

**Issue by mtariqrafique** [MicrosoftDocs/dynamics-365-unified-operations-public#2363]
Sign-on URL - URL example provided is incorrect and it leads to error message shown in subject. Remove trailing "/" from URL as specified below and Power BI authorization will work without any problem.

In step#3 of registration process enter sign-on URL value ending with /oauth as a suffix such as: "**https://contosoax7.cloud.dynamics.com/oauth**" or "**http://contosoax7.cloud.dynamics.com/oauth**".. 

Sample URL value(s) provided in page is incorrect "_**https://contosoax7.cloud.dynamics.com/oauth/**_" when try to do PowerBI authorization it throws error "The reply URL specified in the request does not match the reply URLs configured for the application". Please update the relevant section, thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2213414-926d-10e1-538b-efef09dc0181
* Version Independent ID: 03be53f7-c305-cb02-7627-2ea4f1c01bd4
* Content: [Configure PowerBI.com integration - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/configure-power-bi-integration#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/configure-power-bi-integration.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/configure-power-bi-integration.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by tonyafehr** [comment]
@mtariqrafique, thank you for the feedback.
@MilindaV2, please review and consider updating this topic.

**Comment by tonyafehr** [comment]
Bug #447429 logged to track this issue

**Comment by MilindaV2** [comment]
Adding TJ – he owns the PowerBI integration topic

M

**Comment by tonyafehr** [comment]
We've updated this topic and the changes should be live later today. Thank you!
