### ISSUE TITLE
Issues found with this page

### ISSUE THREAD

**Issue by JChandnani** [MicrosoftDocs/dynamics-365-unified-operations-public#2364]
1. In this its mentioned that SIRET no. needs to be mapped as registration number on Vendor, but report fetches it from the "French siret" field on Vendor purchase demographics
2. on Point 4 of Generate DAS-2 report its mentioned to select posting profile, but there is no option to select that
3. Also there is no mention of selecting Line of business on Vendor

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cf96275-ee7e-3469-5228-38484757148a
* Version Independent ID: e2c49412-9e52-e7e6-ab74-2a166cc1c166
* Content: [DAS-2 report - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/emea-fra-das2-report#feedback)
* Content Source: [articles/finance/localizations/emea-fra-das2-report.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/localizations/emea-fra-das2-report.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @sndray
* Microsoft Alias: **shylaw**

**Comment by tonyafehr** [comment]
@JChandnani, thank you for the feedback. 
@sndray, please review and consider updating this topic.

**Comment by sndray** [comment]
@JChandnani, thank you for the feedback. I will proceed with the update of  comments 1 and 3. In case of comment 2, please, log a support case since this issue is a know issue recently fixed.
