### ISSUE TITLE
Confusing information on Environments under Standard offer

### ISSUE THREAD

**Issue by manishmoothedath** [MicrosoftDocs/dynamics-365-unified-operations-public#2370]
As per the Environment Types section above : 
"Standard environments include the production environment, a Tier-2 Standard Acceptance Test environment, and one Tier-1 develop and test environment."
But in the environment-planning-2-purpose-complexity-matrix.png Standard project has Build (Tier 1), Test (Tier 2), Production and Development (Tier 1) environments
Please clarify if the Development environment is part of Standard offer now ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2402dfea-008a-c7bb-8a3b-1d0457a39665
* Version Independent ID: 4936afad-9a39-e65d-a00c-81246de632cb
* Content: [Environment planning - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/imp-lifecycle/environment-planning)
* Content Source: [articles/fin-ops-core/fin-ops/imp-lifecycle/environment-planning.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/imp-lifecycle/environment-planning.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @ClaudiaBetz-Haubold
* Microsoft Alias: **chaubold**

**Comment by sericks007** [comment]
@manishmoothedath, thank you for the feedback!

@ClaudiaBetz-Haubold, please review and update the content as necessary.

**Comment by ClaudiaBetz-Haubold** [comment]
@manishmoothedath, thank you for the feedback! When you purchase a subscription to Dynamics 365 Finance and Operation apps, the offer includes one Tier-1 environment which can be deployed with either DEV or BUILD topology, one Tier-2 environment, and one Production environment (when the project is ready for live operations). The table you are referring to tries to express that a standard project - i.e. a project with standard (usual) complexity - would require two Tier-1 environments, one for BUILD, and one for Development. Only one of those environments is included in the standard offer, the other one would need to be acquired either as an add-on, or a cloud-hosted environment, or a downloadable VM.
