### ISSUE TITLE
Documentation does not describe the setup require or process from end to end

### ISSUE THREAD

**Issue by RobertRudd** [MicrosoftDocs/dynamics-365-unified-operations-public#2372]
To achieve credit card importing as described above, there needs to be a number of setup items and then processing by the end user.

Setup
- Payment method of credit card
- Whether credit card payment method is allowed for particular categories or not
- Mapping of credit card code to Dynamics 365 Category to default the category based upon the transaction
- Setup of credit card number in employee setup
- Setup of whether the payment of credit card is directly against vendor (credit card company) or clearing account
Processing
- Once the credit card transactions are imported, how does the user import them into Expense report

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0090e306-e055-fe71-e4fb-015bf4b7aa42
* Version Independent ID: c10b8305-d68d-a92d-fb22-0ed42f0b26ea
* Content: [Import and maintain credit card transactions - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/expense-management/import-credit-card)
* Content Source: [articles/finance/expense-management/import-credit-card.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/expense-management/import-credit-card.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @KimANelson
* Microsoft Alias: **knelson**

**Comment by josaw1** [comment]
BUG 448947 created to track this issue.

**Comment by josaw1** [comment]
The program manager will update the documentation in a future update.
