### ISSUE TITLE
255/-1 exit error from the AOSSetupHybridCloud.exe

### ISSUE THREAD

**Issue by AkshayP56** [MicrosoftDocs/dynamics-365-unified-operations-public#2377]
Update Local Agent document specify that LA 2.4.0 has fixes 255/-1 exit error from the AOSSetupHybridCloud.exe. But I have the same issue even running from latest infrastructure scripts. As i mentioned https://community.dynamics.com/365/financeandoperations/f/dynamics-365-for-finance-and-operations-forum/383053/error-when-deploy-prod-environment-first-time-module-aos-failed-with-error-code-255/1040460. for Production and SAT environment.   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38d81ec9-52b0-5b29-282b-f5cf451ba746
* Version Independent ID: 6b1b4864-e2a8-d0f5-b0d1-5d04fa3e82ca
* Content: [Update the local agent - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/update-local-agent)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/update-local-agent.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/lifecycle-services/update-local-agent.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @faix
* Microsoft Alias: **osfaixat**

**Comment by AkshayP56** [comment]
Issue is not yet fixed in Local Agent 2.4.0.

**Comment by faix** [comment]
unfortunately we use this error code for most non successful exits from the AOSSetupHybridCloud installer. I will reword the text above so it clearly identifies the issue it resolves. Please open a support case in order to diagnose your issue.

Thanks

**Comment by AkshayP56** [comment]
Thanks for the quick response Faix, I will open a support ticket for sure. But as per above said, Same error is occurring on two different environment which is strange. Even I run .\Test-D365FOConfiguration.ps1 successfully on all VMs with new Scripts from LCS.

**Comment by faix** [comment]
@josaw1, doc has been updated. Please feel free to close.
