### ISSUE TITLE
Environment monitoring screen shot

### ISSUE THREAD

**Issue by Navneetkat** [MicrosoftDocs/dynamics-365-unified-operations-public#2381]
User activity part is not visible in screen shot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64b5b03d-9169-f94e-f999-63bc5a8e68ac
* Version Independent ID: 177eb187-6962-ba30-7a63-86b0bf3452d7
* Content: [Monitoring and diagnostics tools in Lifecycle Services (LCS) - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/monitoring-diagnostics#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/monitoring-diagnostics.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/lifecycle-services/monitoring-diagnostics.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @meeramahabala
* Microsoft Alias: **meeram**

**Comment by tonyafehr** [comment]
@Navneetkat, thank you for the feedback. 
@meeramahabala, please review.
