### ISSUE TITLE
Supported package types section needs a Note for merge packages

### ISSUE THREAD

**Issue by TeemuMiettinen** [MicrosoftDocs/dynamics-365-unified-operations-public#2382]
For to prevent confusion I think there should be a note in the Supported package types section about the topic of Self-service deployment does not support merge package for Tier2+ environments. This is common way of deploying for most of the partners in the old LCS project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f5ff8cf-5739-86d9-26e2-2804b2f37973
* Version Independent ID: 5ca5612d-f4ec-5e7d-222c-678962aa2da7
* Content: [Update an environment - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/updateenvironment-newinfrastructure#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/updateenvironment-newinfrastructure.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/deployment/updateenvironment-newinfrastructure.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by tonyafehr** [comment]
@TeemuMiettinen, thanks for the feedback. 
@laneswenka, please review.

**Comment by tonyafehr** [comment]
Bug #449010 has been logged to track this issue.

**Comment by laneswenka** [comment]
Hi Teemu, we have since fixed this and now support it in LCS.
