### ISSUE TITLE
Remove/Update the Condition for the same Azure Geo as this is not longer a limitation 

### ISSUE THREAD

**Issue by Angelos102** [MicrosoftDocs/dynamics-365-unified-operations-public#2383]
The limitation for "The databases must be hosted in the same Azure geographic region." is not longer applicable, verified with FastTrack and also I executed and tested this 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c989148-fff9-5aa9-c903-31e88e6b8019
* Version Independent ID: b669fca2-bf18-175b-14a2-371dbdb4ab25
* Content: [Point-in-time restore of the production database to a sandbox environment - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/database-pitr-prod-sandbox#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/database/database-pitr-prod-sandbox.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/database/database-pitr-prod-sandbox.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laneswenka**

**Comment by tonyafehr** [comment]
@Angelos102, thanks for the feedback. 
@laneswenka, please review.

**Comment by tonyafehr** [comment]
Bug #449011 has been logged to track this issue.
