### ISSUE TITLE
Incorrect description of Scope options in a delegation rule

### ISSUE THREAD

**Issue by Bhavleen-cloud** [MicrosoftDocs/dynamics-365-unified-operations-public#2384]
Point number 4 
Module – Delegate only the work items that are related to a specific type of workflow. If you select this option, you must select the type of workflow in the Name field.

Correction- if you select module option, then you are prompted to select the module name & not the workflow name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abcafcff-ef17-2833-31d1-8c5b4a41fda5
* Version Independent ID: 07f491db-ff11-266d-a17e-d4282d0ea6cc
* Content: [Delegate work items in a workflow - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/organization-administration/tasks/delegate-work-items-workflow#feedback)
* Content Source: [articles/fin-ops-core/fin-ops/organization-administration/tasks/delegate-work-items-workflow.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/organization-administration/tasks/delegate-work-items-workflow.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by kfend** [comment]
@Bhavleen-cloud - thanks for the feedback.
@jasongre - can you please review this feedback and update the topic as necessary?

**Comment by ChrisGarty** [comment]
Adjusted https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/pull/2567. Thanks!

**Comment by ChrisGarty** [comment]
Resolved Bug 449552: Docs issue: 2384 - Incorrect description of Scope options in a delegation rule
