### ISSUE TITLE
"Embrace the extensions mindset..." link leads to nowhere. 

### ISSUE THREAD

**Issue by anderson-joyle** [MicrosoftDocs/dynamics-365-unified-operations-public#2386]
https://blogs.msdn.microsoft.com/axinthefield/embrace-the-extensions-mindset-with-dynamics-365-for-finance-and-operations/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7526dd1-39d1-a882-8560-52c530ef5649
* Version Independent ID: 7dd2a62b-b310-595b-eeda-f746679bbf3c
* Content: [Extensibility home page - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/extensibility/extensibility-home-page#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/extensibility/extensibility-home-page.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/extensibility/extensibility-home-page.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @FrankDahl
* Microsoft Alias: **fdahl**

**Comment by RobinARH** [comment]
@RobinARH

**Comment by RobinARH** [comment]
Fixed, and should go live tonight.
