### ISSUE TITLE
OData used for system-to-system integrations doesn't need the user_impersonation 

### ISSUE THREAD

**Issue by Splaxi** [MicrosoftDocs/dynamics-365-unified-operations-public#2387]
The scenario described in the this article focuses on how to utilize the OData endpoint from an user centric approach. This is just one of the ways to utilize the OData endpoint.

If you are planning for a system centric approach, where you want a 3. Party system (or middle layer) to authenticate against the OData endpoint, you would need to do something like below:

1. Registered Application creation just like described, but with the user_impersonation API step.
2. Map the newly registered application inside the Human Resources instance, to an user account (to ensure security settings, nothing more) via "System Administration" -&gt; "Azure Active Directory applications".
3. Authenticate against the tenant with the following details:
URL = https://login.microsoftonline.com/[TenantNameOrTenantGuid]/oauth2/token
Payload =
grant_type:client_credentials
client_id:[ClientId]
client_secret:[ClientSecret]
resource:http://hr.talent.dynamics.com

My mention details works using the POSTMAN application, but reading the documentations / examples for the ADAL library it should be fairly easily for you to replicate the mentioned steps: https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Client-credential-flows

Please add a note or event better, a working example where you don't use the user_impersonation approach and show how to do this with the client_credentials flow instead. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8c75e10-013f-2597-9b4b-fcfa3665586c
* Version Independent ID: da3512fb-ce90-56e5-a287-d3be47f62451
* Content: [Authentication - Human Resources | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/human-resources/hr-developer-api-authentication#feedback)
* Content Source: [articles/human-resources/hr-developer-api-authentication.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/human-resources/hr-developer-api-authentication.md)
* Service: **dynamics-human-resources**
* Product: ****
* Technology: ****
* GitHub Login: @andreabichsel
* Microsoft Alias: **anbichse**

**Comment by RobinARH** [comment]
@andreabichsel Andrea - Can you take a look? Thanks.

**Comment by RobinARH** [comment]
Bug 450163 created to track this issue.

**Comment by RobinARH** [comment]
We won't be updating this topic.
