### ISSUE TITLE
Routes Versions

### ISSUE THREAD

**Issue by wojzeh** [MicrosoftDocs/dynamics-365-unified-operations-public#2388]
I guess in Setup if you use routes point 5 must be Routes versions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90a70666-74c8-cb14-f655-2ea665bd8b65
* Version Independent ID: 499e83f4-52c2-0292-b3d1-92dc69e957e3
* Content: [Production setup requirements - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/production-control/production-set-up-requirements)
* Content Source: [articles/supply-chain/production-control/production-set-up-requirements.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/production-control/production-set-up-requirements.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @johanhoffmann
* Microsoft Alias: **johanho**

**Comment by RobinARH** [comment]
@johanhoffmann Johan - Can you take a look? Thanks.

**Comment by RobinARH** [comment]
Bug 450162 created to track this issue.

**Comment by kamaybac** [comment]
@wojzeh , thank you for reporting this issue. The fix is now live:
https://docs.microsoft.com/en-us/dynamics365/supply-chain/production-control/production-set-up-requirements
