### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by LuisCano2202** [MicrosoftDocs/dynamics-365-unified-operations-public#2389]
how can is possible it in a standard element?
"element.dataHelper().RecordCreating += eventhandler(this.PreRecordCreate);"

i used chain of command but i cant implements because. 

the object FormRunServiceArgs is not initialized and the code doesn´t work and i dont undertsand VS expected other way to put this code.

My example was in VendTable form.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb47a9d9-a238-472a-4061-065982690b18
* Version Independent ID: 98d18aaf-cf3c-7b64-29ce-cc075d849b75
* Content: [System-defined buttons - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/user-interface/system-defined-buttons#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/user-interface/system-defined-buttons.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/user-interface/system-defined-buttons.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by RobinARH** [comment]
@jasongre Jason - Can you take a look? Thanks.

**Comment by RobinARH** [comment]
Bug 450161 created to track this issue.

**Comment by jasongre** [comment]
Hey @LuisCano2202, I would recommend you open a support case for assistance on technical issues like this. Thanks!
