### ISSUE TITLE
Multi-factor authentication (MFA) possible via ADFS?

### ISSUE THREAD

**Issue by shereen-yong** [MicrosoftDocs/dynamics-365-unified-operations-public#2390]
Hello! I am wondering if the multi-factor authentication (MFA) can be used for an on-premises implementation of Dynamics 365 for Finance and Operations? Would MFA still work and if so, would it be implemented via ADFS?  thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 903f0c12-ee21-2d66-dd29-bd3bbbf62ebf
* Version Independent ID: 6db6da1d-295a-4d1f-829e-9c54b9a9e548
* Content: [AD FS Office 365 compatibility - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/onprem-adfscompatibility)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/onprem-adfscompatibility.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/deployment/onprem-adfscompatibility.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @faix
* Microsoft Alias: **osfaixat**

**Comment by RobinARH** [comment]
@faix - Can you take a look? Thanks.

**Comment by faix** [comment]
Hello,

We have not tested a MFA authentication scenario, **so it is not officially supported,** but as long as you use ADFS it could work. You can also ask in the Yammer group if you want to know whether someone has gotten this to work.

**Comment by shereen-yong** [comment]
@faix thank you for your response. I will try asking the the Yammer group as well.

**Comment by shereen-yong** [comment]
@faix Also, while looking into the possibility of using MFA for an on-premises Dynamics 365  for Operations deployment I have come upon Microsoft docs for designing a Azure AD secure "hybrid" solution that seems to enable access security (including MFA) for legacy applications (such as Citrix, Kerberos) by integrating Azure AD with an existing application delivery controller or network (link to documentation I am referring to follows)
[https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/secure-hybrid-access](url)
Would this perhaps be a possible solution as well for an on-prem Dynamics 365 for Operations implementation or does it not apply in this case?

**Comment by faix** [comment]
No, i do not think that this approach would work. Please look at hybrid scenarios using AD FS. These could **maybe** work, but they are unsupported.

**Comment by shereen-yong** [comment]
@faix  alright thank you
