### ISSUE TITLE
Employment Categories 

### ISSUE THREAD

**Issue by manbhat07** [MicrosoftDocs/dynamics-365-unified-operations-public#2391]
Employment Categories in found under Personnel Management Workspace &gt; Set Up &gt; Employment Categories 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e444dcb-2490-60f7-cb14-5cc3ee98b4a4
* Version Independent ID: 45980903-8ef3-df0e-6ec1-8623843367a5
* Content: [Create employment categories - Human Resources | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/human-resources/hr-benefits-setup-employment-categories)
* Content Source: [articles/human-resources/hr-benefits-setup-employment-categories.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/human-resources/hr-benefits-setup-employment-categories.md)
* Service: **dynamics-human-resources**
* Product: ****
* Technology: ****
* GitHub Login: @andreabichsel
* Microsoft Alias: **anbichse**

**Comment by RobinARH** [comment]
@andreabichsel Andrea - Can you take a look? thanks.

**Comment by RobinARH** [comment]
Bug 450160 created to track this issue.
