### ISSUE TITLE
Missing limitation in the "Differences [...]"-section

### ISSUE THREAD

**Issue by mueckeflo** [MicrosoftDocs/dynamics-365-unified-operations-public#2396]
As per BUG # 445559 - "Requested ship/receipt date" cannot be used for calculating prices in a call center sales order = Retail.

Queot from Shalabh Jain in the mentioned bug: 
"[...]The issue here that the customer is using the "Requested ship date" and "Requested receipt date" for calculating the prices, but Retail pricing currently does not support these values. [...]"
=&gt; This is a price calculation paramter in the accounts receivable  paramters -&gt; prices, controlling which data shall be used for finding prices. Retail, as per Shalabh's statement is *always* using today's date to calculate a price.

Can you please update this docs site to refelct this limitation? Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b3c2d6a-371b-688d-b3a6-6e174b9f292a
* Version Independent ID: 6c90e91b-6ab7-e817-2a20-2d54c1da2bf2
* Content: [Retail sales price management - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/price-management#feedback)
* Content Source: [articles/commerce/price-management.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/price-management.md)
* Service: **dynamics-ax-retail**
* Product: ****
* Technology: ****
* GitHub Login: @ShalabhjainMSFT
* Microsoft Alias: **ShalabhjainMSFT**

**Comment by tonyafehr** [comment]
@mueckeflo, thanks for the feedback. 
@ShalabhjainMSFT, please review.

**Comment by tonyafehr** [comment]
Bug #472479 logged to track this issue.

**Comment by tonyafehr** [comment]
This topic has been updated. Thanks!
