### ISSUE TITLE
Phantom and route network

### ISSUE THREAD

**Issue by wojzeh** [MicrosoftDocs/dynamics-365-unified-operations-public#2397]
There is a mistype in the first illustruation for Phantom and route network
It should have been:

Part       Operation                            Input
G          10-Assembly product G        F,D

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8edfe78b-6486-5678-a171-95f81d2715ef
* Version Independent ID: 62a24546-bb3f-5194-43f0-0db144643ab7
* Content: [Phantom items - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/production-control/phantom-items)
* Content Source: [articles/supply-chain/production-control/phantom-items.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/production-control/phantom-items.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @ShylaThompson
* Microsoft Alias: **shylaw**

**Comment by tonyafehr** [comment]
@wojzeh, thanks for the feedback. 
@kamaybac, please review.

**Comment by kamaybac** [comment]
@wojzeh , is this the correction you are looking for?

![image](https://user-images.githubusercontent.com/26439921/81800303-f0324e00-9512-11ea-92f5-158ba681caa9.png)

**Comment by kamaybac** [comment]
@wojzeh , I suspect you may mean this:

![image](https://user-images.githubusercontent.com/26439921/81800781-adbd4100-9513-11ea-81bf-2eb64f99fa61.png)

**Comment by wojzeh** [comment]
The last one. There is no component D at all

**Comment by kamaybac** [comment]
@wojzeh , thanks for pointing this out. I fixed the image and the update should be live very soon.
