### ISSUE TITLE
Country specific

### ISSUE THREAD

**Issue by GauravGupta-MS** [MicrosoftDocs/dynamics-365-unified-operations-public#2400]
Hi, 
Is this a country specific feature. The page does not seem to mention that. 
I believe it may be RUS specific. 
Is there a plan to get this in other regions. They key requirement is to account for stock that is FOB and in-transit from the supplier. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46a4f6a4-1aad-d7ff-fec1-4d6cea54be34
* Version Independent ID: e784936c-9c13-926b-26bc-c6a024c0e15f
* Content: [Goods in transit from vendor - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/rus-goods-transit-vendor#feedback)
* Content Source: [articles/finance/localizations/rus-goods-transit-vendor.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/localizations/rus-goods-transit-vendor.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @Anasyash
* Microsoft Alias: **anasyash**

**Comment by sericks007** [comment]
@GauravGupta-MS, thank you for the feedback.

@Anasyash, please review and respond to the questions.

**Comment by sericks007** [comment]
Bug 451029 was logged to track this issue.

**Comment by Anasyash** [comment]
Hello
Thank you for feedback, I have created a task to update the title and to add (Russia) to the title. This feature is really RU-specific
