### ISSUE TITLE
Page Size limitation and drill-thru

### ISSUE THREAD

**Issue by axaeffect** [MicrosoftDocs/dynamics-365-unified-operations-public#2401]
With this new feature, how we overcome the needs to have wide / many columns report, in which preferable all placed in 1 row not in next page because Page Size ? For example Open Transaction Report, Aging Report.

In the SysReportAdministration menu, there is a check box to activate Drill Thru, is this new which not yet release ? coz it is needed. also it is the opposite of what written here saying Drill-thru not actioanable, and please elaborate what is the meaning of "not actionable"

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aceffbf0-523e-f054-e242-87cbd60b0b1c
* Version Independent ID: 6681cf81-8a8e-ea19-e0f2-35e88b31c59d
* Content: [Preview PDF documents using a PDF viewer - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/preview-pdf-documents#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/preview-pdf-documents.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/preview-pdf-documents.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by sericks007** [comment]
@axaeffect, thank you for the feedback.

@TJVass, please review and update the content, as needed.

**Comment by sericks007** [comment]
Bug 451058 has been logged to track this issue.

**Comment by TJVass** [comment]
In some cases, adjustments to the report designs are needed to ensure the output fits the target page size.
Support for embedded drill-thru links in the PDF viewer is now available for D365 F&O applications. HotFix packages are available on LCS for customers hosted on PU36 or later.
