### ISSUE TITLE
Specify when this workflow is used through activation conditions - Test button

### ISSUE THREAD

**Issue by SamRonchetti** [MicrosoftDocs/dynamics-365-unified-operations-public#2403]
Hiya,

The test button is not available in D365 F&O as mentioned in bullet point 6 onward in the "Specify when this workflow is used through activation conditions" section.

Regards

Sam :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3b1e278-d76d-5d8e-b247-0ba874f8a347
* Version Independent ID: 4554bc65-9fb6-c38c-d3df-fe967f10d456
* Content: [Configure workflow properties - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/organization-administration/configure-workflow-properties#feedback)
* Content Source: [articles/fin-ops-core/fin-ops/organization-administration/configure-workflow-properties.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/organization-administration/configure-workflow-properties.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @sericks007
* Microsoft Alias: **donaldc**

**Comment by sericks007** [comment]
@SamRonchetti, thanks for posting this!

@ChrisGarty, please review and update the content, as needed.

**Comment by sericks007** [comment]
Bug 451059 has been logged to track this issue.

**Comment by ChrisGarty** [comment]
Thanks @SamRonchetti !

**Comment by ChrisGarty** [comment]
Adjusted via https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/pull/2568. FYI @sericks007

**Comment by ChrisGarty** [comment]
Resolved bug 451059

**Comment by ChrisGarty** [comment]
Resolved Bug 451059: Docs issue #2403: Specify when this workflow is used through activation conditions - Test button
