### ISSUE TITLE
Broken link in "What is affected" section. 

### ISSUE THREAD

**Issue by rsantana123** [MicrosoftDocs/dynamics-365-unified-operations-public#2404]
The link to download the pre-requisite "sdk-2.1.513-windows-x64-installer" in the "Migrate to the SDK for Visual Studio 2017" section seems to be broken. All of the other links work correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 776f646a-f316-8c84-d190-57ecd88547a0
* Version Independent ID: 80208288-e39f-bacc-c8ad-7c51470e9cce
* Content: [Migrate the Retail SDK from Visual Studio 2015 to Visual Studio 2017 - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/retail-sdk/migrate-sdk#feedback)
* Content Source: [articles/commerce/dev-itpro/retail-sdk/migrate-sdk.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/dev-itpro/retail-sdk/migrate-sdk.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by josaw1** [comment]
Thank you for your feedback. @mugunthanm can you please update the link?

**Comment by mugunthanm** [comment]
Verified the links, its works fine. Can you please try again.

**Comment by rsantana123** [comment]
Probably an issue on my end then. Tried it again and seems to work now. Thanks.
