### ISSUE TITLE
Handling if <add name="ext.AppInsightsKey" value=""/>

### ISSUE THREAD

**Issue by Halldor10** [MicrosoftDocs/dynamics-365-unified-operations-public#2406]
If value is set as "" for the AppInsightsKey, in the config file, it creates a null value exception.

code now:
string key = context.Runtime.Configuration.GetSettingValue("ext.AppInsightsKey");
suggested code: 
string key = context.Runtime.Configuration.GetSettingValue("ext.AppInsightsKey") ?? "";

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f659eadc-c39c-a5e4-cfe4-27fea2f77523
* Version Independent ID: 48e06663-f4a1-b540-db40-147b35a840f9
* Content: [Log extension events to Application Insights - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/commerce-application-insights#feedback)
* Content Source: [articles/commerce/dev-itpro/commerce-application-insights.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/dev-itpro/commerce-application-insights.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by josaw1** [comment]
Thank you for your feedback. @mugunthanm can you please take a look?

**Comment by mugunthanm** [comment]
Thanks for the feedback. Updated the sample code.
