### ISSUE TITLE
Steps for Creating the Azure Application in the Azure Portal are no long accurate

### ISSUE THREAD

**Issue by bstorie** [MicrosoftDocs/dynamics-365-unified-operations-public#2407]
The steps for creating the Azure Application Registration are now longer accurate.   The Azure Portal no longer has a settings option after creating the Application.    This section of the document needs review and updating to reflect the changes that were introduced in the Azure Portal. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cde75a6-0a4d-8405-4b6d-f7e3cfd33094
* Version Independent ID: fa2a94bb-7a6f-1ca4-ce74-8bcd8a6929f7
* Content: [Device activation of a customized Modern POS - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/retail-POS-activation-changes#feedback)
* Content Source: [articles/commerce/dev-itpro/retail-POS-activation-changes.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/dev-itpro/retail-POS-activation-changes.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @jashanno
* Microsoft Alias: **jashanno**

**Comment by josaw1** [comment]
Thank you for your feedback. @jashanno can you please review?

**Comment by josaw1** [comment]
BUG 451927 created to track this issue.
