### ISSUE TITLE
Examples Need to be Updated

### ISSUE THREAD

**Issue by MaryAnnHand** [MicrosoftDocs/dynamics-365-unified-operations-public#241]
I tried using some of the examples listed here and I get "Invalid filter syntax" error. In particular, I want to search for examples of specific form properties. Even the simplest example "type:form property:formtemplate=listpage" gives the error. It appears that Filter name "Property:" does not work for any type at all.  If it should work, please correct the examples to illustrate how to use it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90ae3110-57a4-c409-21e3-790f8487cb7e
* Version Independent ID: 4e2be8bf-3483-a59d-08df-5aaf6f3e35b3
* Content: [Metadata search in Visual Studio - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-tools/metadata-search-visual-studio)
* Content Source: [articles/dev-itpro/dev-tools/metadata-search-visual-studio.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-tools/metadata-search-visual-studio.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RobinARH
* Microsoft Alias: **robadawy**

**Comment by tonyafehr** [comment]
Thanks for contacting us. Unfortunately, we can't handle support requests for the product here. To contact support, consider one of the options described here: https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support

**Comment by robadawy** [comment]
It is possible you are using the "Application Explorer" window instead of the metadata search window (Dynamics 365 > Metadata Search...)
