### ISSUE TITLE
How to open the report?

### ISSUE THREAD

**Issue by dodiggitydag** [MicrosoftDocs/dynamics-365-unified-operations-public#2416]
Where can I access this report in an LCS project for a customer?

Secondly, is this only available for production environments, or can it be run against a standard sandbox?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faa9525b-3195-3405-afe8-3e1545c178ad
* Version Independent ID: fd57a337-9b2f-69bd-8b90-ee9a761d1132
* Content: [Impact analysis report in Lifecycle Services (LCS) - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/impact-analysis-report)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/impact-analysis-report.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/lifecycle-services/impact-analysis-report.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @dfroslieMSFT
* Microsoft Alias: **dfroslie**

**Comment by RobinARH** [comment]
@dfroslieMSFT Hi Dave - Can you take a look? Thanks.

**Comment by RobinARH** [comment]
Bug 482147 created to track this issue. - Robin

**Comment by RobinARH** [comment]
I've updated the doc for the first question, adding "After accessing a project, the report can be accessed via the hamburger in Lifecycle Services (LCS)." It should go live this evening. 

For the second question, it's explained by this in the Usage section, "The second key measure in the report is the form-based usage of the product in the production environments that are associated with the active LCS project." - production environments.

-Robin

**Comment by charlesmoy** [comment]
It seems the responses in this string are after a user has the functionality with 'private preview' access.  How to I get private preview so that the impact analysis/churn usage report is showing in the hamburger of my LCS?

Please advise,
Chuck

**Comment by dfroslieMSFT** [comment]
Hi Chuck - Here's the link for the preview sign up:   https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR56j8lZs0FdAvwT75_WNFyxUMUpQQ1dOSUExUFpFS082MEZHQjhERjVVTi4u
