### ISSUE TITLE
Delivery date of a planned purchase order

### ISSUE THREAD

**Issue by djpejsen** [MicrosoftDocs/dynamics-365-unified-operations-public#2418]
In relation to the priority of coverage group calendar, I think you have mentioned incorrect priority in the note below 

Note that the coverage group calendar can be set in different pages and will take priority in the following order: 1. Item coverage group on the Released products details page 2. Item coverage group on the Item coverage page 3. Default item coverage group in Master planning parameters

The priorty must be as below, but please correct me if I am wrong
1. Item coverage group on the Item coverage page
2. Item coverage group on the Released products details page
3. Default item coverage group in Master planning parameters

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d69922ed-a310-ffd7-6dea-8ae2f6579353
* Version Independent ID: 015e23a3-0162-b33c-8c07-7751515f5928
* Content: [Calendars and master planning - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/master-planning/supply-chain-calendars-master-planning#feedback)
* Content Source: [articles/supply-chain/master-planning/supply-chain-calendars-master-planning.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/master-planning/supply-chain-calendars-master-planning.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @t-benebo
* Microsoft Alias: **t-benebo**

**Comment by RobinARH** [comment]
@t-benebo Hi Beatiz - Can you take a look? Thanks.

**Comment by RobinARH** [comment]
Bug 482146 created to track this issue.

**Comment by RobinARH** [comment]
This topic has been updated.
