### ISSUE TITLE
#MSDyn365FO tag on AX 2012 content

### ISSUE THREAD

**Issue by matejskubic** [MicrosoftDocs/dynamics-365-unified-operations-public#242]
Content under *AX 2012* should not have `#MSDyn365FO` in the html title.

 * `https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/ax-2012`
 * `https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/tree/live/articles/dev-itpro/lifecycle-services/ax-2012`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93ea0962-fb5c-638e-bb4b-3158d2a89d1a
* Version Independent ID: 89b055fa-bff2-c9b2-f8da-089191ebdf3c
* Content: [Import data from an ODBC data source (AX 2012) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/ax-2012/import-data-odbc-data-source-dixf)
* Content Source: [articles/dev-itpro/lifecycle-services/ax-2012/import-data-odbc-data-source-dixf.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/lifecycle-services/ax-2012/import-data-odbc-data-source-dixf.md)
* Product: **dynamics-ax-2012**
* GitHub Login: @kfend
* Microsoft Alias: **kfend**

**Comment by ShylaThompson** [comment]
Thanks for letting us know.
