### ISSUE TITLE
Extension scenario implementation

### ISSUE THREAD

**Issue by simonefinotti** [MicrosoftDocs/dynamics-365-unified-operations-public#2420]
I think that including some example code would really help.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec1a63f8-4e6a-d923-fbce-bbd28f2db7b6
* Version Independent ID: b2fc83c9-68ea-6aba-42fd-f041a1373476
* Content: [Extend table maps that are used for versioning - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/extensibility/maps-with-versioning)
* Content Source: [articles/fin-ops-core/dev-itpro/extensibility/maps-with-versioning.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/extensibility/maps-with-versioning.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @LarsBlaaberg
* Microsoft Alias: **lolsen**

**Comment by RobinARH** [comment]
@LarsBlaaberg Hi Lars - Can you take a look? thanks.

**Comment by RobinARH** [comment]
Bug 482145 created to track this issue.
