### ISSUE TITLE
Code sample is not correct for "Adding actions on OData entities"

### ISSUE THREAD

**Issue by d47447** [MicrosoftDocs/dynamics-365-unified-operations-public#2422]
Team,

The example under the section "Adding actions on OData entities" is returning an int value while the method signature is not correct for this. If an Action is returning any values than it should be like below
 [SysODataActionAttribute("&lt;MethodName&gt;", false), SysODataCollectionAttribute("return", Types::Record, "CarColor")].

Pl check and do the needful.

Thanks
Deepak

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d7c8b45-1531-ebbf-d417-4e1fe5bf4f1b
* Version Independent ID: c543a5fc-90c9-9edb-11d7-6d6d0f2c10a9
* Content: [Open Data Protocol (OData) - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/odata#adding-actions-on-odata-entities)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/odata.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/odata.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by tonyafehr** [comment]
@d47447, thanks for the feedback. 
@Sunil-Garg, please review.

**Comment by tonyafehr** [comment]
Bug #452519 logged to track this issue.

**Comment by tonyafehr** [comment]
The code presented is correct as it is, the SysODataCollectionAttribute attribute is only required when returning a list, not a singular value.
