### ISSUE TITLE
The license guide is from July 2019

### ISSUE THREAD

**Issue by FangyuanHou** [MicrosoftDocs/dynamics-365-unified-operations-public#2424]
please update to the latest licensing pdf.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e919a898-2ff3-73a4-0960-33264a0ab5f3
* Version Independent ID: 9a49ca3d-b872-cb63-7e53-a8a0db55d749
* Content: [Configure document management - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/organization-administration/configure-document-management#feedback)
* Content Source: [articles/fin-ops-core/fin-ops/organization-administration/configure-document-management.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/organization-administration/configure-document-management.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @ChrisGarty
* Microsoft Alias: **cgarty**

**Comment by sericks007** [comment]
@FangyuanHou, thank you for posting here! I've updated the link to the licensing guide -- so the licensing guide from April 2020 should be displayed.  This update will be published later today.
