### ISSUE TITLE
Clarification on "Entity store data in Azure Data Lake"

### ISSUE THREAD

**Issue by manishmoothedath** [MicrosoftDocs/dynamics-365-unified-operations-public#2426]
Quoting from above - "When this feature is turned on, Entity store data isn't populated in the relational Entity store database in the Microsoft subscription. Instead, it's populated in an Azure Data Lake Storage Gen2 account in your own subscription."

Does this mean the Embedded Power BI reports will stop working, since there is no more data in the entity store database ? or will the Power BI Embedded reports automatically read data from ADLS ?
Please clarify!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a344a5de-68fa-e9cf-28eb-51269c33b9b3
* Version Independent ID: 1b3ede62-3954-574b-5778-8cdee0ededfe
* Content: [Make Entity store available as a Data Lake - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/entity-store-data-lake)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/entity-store-data-lake.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/entity-store-data-lake.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by HeicoEricRupp** [comment]
Agreed.  Clarification on this would be greatly appreciated.

**Comment by josaw1** [comment]
Thanks for the feedback. @MilindaV2 or @sericks007 can you please review the comment?

**Comment by josaw1** [comment]
BUG 453465 created to track issue.

**Comment by MilindaV2** [comment]
Enabling Entity store in Data lake (currently in public preview) will refresh the data in the lake - not in entity store relational DB as stated in the document. This action doesn't delete the data in Entity store - existing Analytical workspaces will continue to work, with stale data.
We are working on enabling Analytical workspaces on Data lake. We will enable this feature in preview in the future. pl. see our session at the link below for an explanation and demo.
 [https://mymbas.microsoft.com/sessions/46c51e7e-f1bb-4424-8772-13f89a5e3c3b?source=sessions](url)
