### ISSUE TITLE
More info required for how to generate report

### ISSUE THREAD

**Issue by d47447** [MicrosoftDocs/dynamics-365-unified-operations-public#2429]
Hi Team,

Currently, you just mentioned the script syntax but this is not enough for everyone. YOu can add further details like;
Open CMD and go to C:\AOSService\PackagesLocalDirectory\Bin and run this script there.

It will mate it more clear to readers. 

Thanks
Deepak

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cbcd513-d8ab-ddc6-ce0d-43e03d4692c2
* Version Independent ID: d1119159-09e4-1aa1-d90e-c8f23552adbc
* Content: [Customization Analysis Report (CAR) - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/customization-analysis-report)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/customization-analysis-report.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-tools/customization-analysis-report.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **jorisde**

**Comment by josaw1** [comment]
Thank you for your feedback. @RobinARH can you please review? Thanks.

**Comment by jorisdg** [comment]
Thank you for the suggestion. It looks like the article does list the folder. The drive letter can vary based on VHD versus cloud, and sometimes even within cloud.
The CAR report is designed for a technical audience and specific purpose, namely ISVs that need to certify their solutions. There are currently no further investments in CAR as we will be moving on to other validation mechanisms for ISV solutions.
