### ISSUE TITLE
Change Drop User Syntax in Prepare the database

### ISSUE THREAD

**Issue by rudhra02** [MicrosoftDocs/dynamics-365-unified-operations-public#243]
Found the User values in the database has "-" in between  which makes the syntax error. This can be replaced by select 'DROP USER [' + name + ']'  in Prepare the database section

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3436fbc8-5bdd-dcdc-f5d3-51caf7b6cd76
* Version Independent ID: af78d3ef-b329-11e9-896a-aa3394f6c77c
* Content: [Copy a Finance and Operations database – Azure SQL to SQL Server - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/copy-database-from-azure-sql-to-sql-server#feedback)
* Content Source: [articles/dev-itpro/database/copy-database-from-azure-sql-to-sql-server.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/database/copy-database-from-azure-sql-to-sql-server.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @maertenm
* Microsoft Alias: **maertenm**

**Comment by tonyafehr** [comment]
Thanks for taking the time to provide this kind of feedback. I will pass this message on to the author and your suggestion will be noted as a future enhancement to this topic.

**Comment by rat-af** [comment]
Good post @rudhra02, was going to make the same comment myself.  There are users against the databases that have a '-' in them.

**Comment by ldallari** [comment]
otherwise use
select 'DROP USER ' + QUOTENAME(name)
