### ISSUE TITLE
Organization Email Templates is now in a different location

### ISSUE THREAD

**Issue by aleguerrero** [MicrosoftDocs/dynamics-365-unified-operations-public#2430]
In the following link: https://docs.microsoft.com/en-us/dynamics365/commerce/email-templates-transactions
Says the following: 
_"In Commerce headquarters, go to Retail and Commerce > Headquarters setup > Organization email templates."_

However, when looking for that in the application, it does not shows up:
![image](https://user-images.githubusercontent.com/27838418/82691827-ce744d80-9c1b-11ea-8230-38d8c8c43a9c.png)

When I search for it, is on a different location (App version 10.0.10, PU43) :
![image](https://user-images.githubusercontent.com/27838418/82691903-ef3ca300-9c1b-11ea-81f4-eafbc7cb5bf5.png)

The thing is to please change the location of the Organization email templates in the documentation.

**Comment by tonyafehr** [comment]
@aleguerrero, thanks for the feedback. 
@josaw1, please review.

**Comment by josaw1** [comment]
@bicyclingfool, please review.

**Comment by bicyclingfool** [comment]
FYI: It appears to depend on which sku you have. I'll update the doc to call out that the other location

![image](https://user-images.githubusercontent.com/10248868/83429489-f5373e80-a3e8-11ea-9af4-c0c8fdd7ac89.png)

**Comment by bicyclingfool** [comment]
Just submitted a pull request to address this: https://github.com/MicrosoftDocs/Dynamics-365-Operations/pull/8390
