### ISSUE TITLE
Step 4. h. systemadministrator to root team

### ISSUE THREAD

**Issue by Ballzer0** [MicrosoftDocs/dynamics-365-unified-operations-public#2431]
Hi, im conserned about step 4. h. Wont this make all the users of that team also into root administrators?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df8e9efc-9258-3876-e05f-20d35c907274
* Version Independent ID: 4b5041ec-4a48-0565-e47a-b972e65a6d60
* Content: [System requirements and prerequisites - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-gb/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/requirements-and-prerequisites#verify-requirements-and-grant-access)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/requirements-and-prerequisites.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/dual-write/requirements-and-prerequisites.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @sabinn-msft
* Microsoft Alias: **sabinn**

**Comment by JeroenLeeflang** [comment]
Totally agree. Why is this needed?

**Comment by tonyafehr** [comment]
@sabinn-msft, please review. Thank you!

**Comment by tonyafehr** [comment]
Bug #454567 logged to track this issue.

**Comment by sabinn-msft** [comment]
We updated documentation couple of weeks back wherein we now ask to select a preconfigured Security Role to grant a Read privilege with a User scope for each entity integrated through dual-write.
