### ISSUE TITLE
Instructions do not align with current azure portal menu

### ISSUE THREAD

**Issue by ja1m1n8hatt** [MicrosoftDocs/dynamics-365-unified-operations-public#2434]
When trying to follow the instructions to enable installation of a customized MPOS, they don't match with the current menu options and screen flow for azure portal. Please update to reflect the current azure portal menu and options.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cde75a6-0a4d-8405-4b6d-f7e3cfd33094
* Version Independent ID: fa2a94bb-7a6f-1ca4-ce74-8bcd8a6929f7
* Content: [Device activation of a customized Modern POS - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/retail-pos-activation-changes)
* Content Source: [articles/commerce/dev-itpro/retail-POS-activation-changes.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/dev-itpro/retail-POS-activation-changes.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @jashanno
* Microsoft Alias: **jashanno**

**Comment by tonyafehr** [comment]
@ja1m1n8hatt, thanks for the feedback. 
@josaw1, please review

**Comment by josaw1** [comment]
@jashanno, please review.

**Comment by tonyafehr** [comment]
Bug #454568 has been logged to track this issue.
