### ISSUE TITLE
How can I download multiple formulas in D365?

### ISSUE THREAD

**Issue by sunshinequery** [MicrosoftDocs/dynamics-365-unified-operations-public#2436]
Hi,

How can I download multiple formulas in D365?
I have a long list of products and each product have a different formula.
Appreciate any assistance.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94864413-110a-ef97-d6ec-ada50844dad4
* Version Independent ID: 6be61cb2-c5cc-e782-c878-95202abdff5e
* Content: [Bills of materials and formulas - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/production-control/bill-of-material-bom)
* Content Source: [articles/supply-chain/production-control/bill-of-material-bom.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/production-control/bill-of-material-bom.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @cvocph
* Microsoft Alias: **conradv**

**Comment by tonyafehr** [comment]
Thanks for contacting us. We're unable to handle Support requests for the product on this site. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
@kamaybac, for visibility.
