### ISSUE TITLE
Steps are unclear

### ISSUE THREAD

**Issue by manishmoothedath** [MicrosoftDocs/dynamics-365-unified-operations-public#2438]
Steps are unclear, which of these nodes are roots / siblings / child ? Please add screenshots if possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a7c3841-58f6-35eb-c7eb-a95fb3e40a63
* Version Independent ID: b32ff3b6-a7e5-baba-795e-44f21236ad5a
* Content: [ER Use financial dimensions as a data source (Part 1 - Design data model) - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/tasks/er-financial-dimensions-data-source-1?toc=/dynamics365/commerce/toc.json)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/tasks/er-financial-dimensions-data-source-1.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/tasks/er-financial-dimensions-data-source-1.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @NickSelin
* Microsoft Alias: **nselin**

**Comment by sericks007** [comment]
@manishmoothedath, thank you for the feedback.

@NickSelin, please review and consider updating the content.

**Comment by kfend** [comment]
@manishmoothedath - Thanks for your feedback. This topic, as well as the other three in this procedure set, are automatically generated from the task guide that can be uploaded from the LCS BPM library and played in Task recorder. When these guides are played, you can see all of the screens/pages that are referred to. However, the topics have been updated with some screenshots. Changes will be published today.
