### ISSUE TITLE
Missing documentation on using the new IExtensionController

### ISSUE THREAD

**Issue by Halldor10** [MicrosoftDocs/dynamics-365-unified-operations-public#2439]
Missing documentation using the new IExtensionController and information on in what version it is supported in. Would also nice to have a link to a source code examples directly in Github.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 430ab152-0cf0-695c-ec03-d4a63d720c4d
* Version Independent ID: a7239ae1-9ef6-f23c-267e-c2567fd26ee0
* Content: [Create a new Retail Server extension - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/retail-server-extension)
* Content Source: [articles/commerce/dev-itpro/retail-server-extension.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/dev-itpro/retail-server-extension.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by sericks007** [comment]
@Halldor10, thank you for your feedback.

@mugunthanm, please review and update the content.

**Comment by mugunthanm** [comment]
IExtensionController is not used, we introduced new controller IController in 10.0.12. Very soon we will publish a doc for that, 10.0.12 is not in PEAP yet.
