### ISSUE TITLE
Credit and Collections Management Update not reflected in this page or in the documentation

### ISSUE THREAD

**Issue by Mtcryer** [MicrosoftDocs/dynamics-365-unified-operations-public#2440]
The link that remains here has not been updated so that users know what the actual Credit and Collections functionality is and are currently left with no information regarding the functionality that has been released into their systems. There was an issue posted on this... but somehow that was "CLOSED" without any update to this page or to this area of the A/R Credit Management functionality documentation.

Please update this documentation ASAP. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b80b95fb-b679-0e3e-7281-ce5753c0918a
* Version Independent ID: 34f97157-1631-11af-86ba-066faddb654c
* Content: [Credit and collections in Accounts receivable - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/accounts-receivable/collections-credit-accounts-receivable)
* Content Source: [articles/finance/accounts-receivable/collections-credit-accounts-receivable.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/accounts-receivable/collections-credit-accounts-receivable.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @ShivamPandey-msft
* Microsoft Alias: **shpandey**

**Comment by sericks007** [comment]
@Mtcryer, thank you for providing this feedback.

@ShivamPandey-msft, please review and update the content.

**Comment by sericks007** [comment]
Bug 455249 has been logged to track this issue.

**Comment by panolte** [comment]
We believe all the documentation is present, but it may have been presented in a split manner.  We have renamed and re-organized a few items in the table of contents to make these items easier to identify and find.
