### ISSUE TITLE
FormAdaptors Not Used

### ISSUE THREAD

**Issue by dodiggitydag** [MicrosoftDocs/dynamics-365-unified-operations-public#2441]
We no longer us the generated FormAdaptors for new forms. Some of the old FormAdaptor classes are still in the product. New tests will be using type providers. For type providers you do not need to regenerate the FormAdaptor classes every time you change the form.

From code point of view the usage of FormAdaptor classes and type providers will look the same.

Example:
using MyFormFormAdaptor = Microsoft.Dynamics.AX.TypeProviders.FormAdaptors.FormAdaptorTypeProvider@[formStr(MyForm)];

In the test method:
        using (MyFormProfileFormAdaptor projRevProfileForm = ProjRevenueProfileFormAdaptor::open())
        {

        }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2673e0e6-36ff-72f9-11dd-bfcfa1916882
* Version Independent ID: 01b6cf39-57a3-c6ca-af2c-4b7c530e5fdf
* Content: [Testing and validations - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/perf-test/testing-validation#integration-of-the-test-module-with-build-process)
* Content Source: [articles/fin-ops-core/dev-itpro/perf-test/testing-validation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/perf-test/testing-validation.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @jorisdg
* Microsoft Alias: **jorisde**

**Comment by josaw1** [comment]
Thanks for the comment. @jorisdg can you please take a look?

**Comment by jorisdg** [comment]
Hi Dag,
I need to double check but I believe that sadly the task recorder imports are still generating code with form adaptors and not type providers. So unfortunately I believe it is still relevant.

**Comment by josaw1** [comment]
@jorisdg can you please confirm, then close this comment?

**Comment by jorisdg** [comment]
@josaw1 yes task recording import still uses form adaptors.
