### ISSUE TITLE
Wrong print screen under Payment methods set up

### ISSUE THREAD

**Issue by MariyaKoteva** [MicrosoftDocs/dynamics-365-unified-operations-public#2442]
The print screen shown under the section on adding Payment methods to the call center actually shows Payment methods assigned to Retail stores. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e482c177-8def-6c1f-2276-933b0772a4e1
* Version Independent ID: 07d08dab-6028-34bb-6016-86602a3cc51f
* Content: [Set up a call center channel - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/channel-setup-callcenter)
* Content Source: [articles/commerce/channel-setup-callcenter.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/channel-setup-callcenter.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @samjarawan
* Microsoft Alias: **samjar**

**Comment by josaw1** [comment]
Thanks for the comment.  @samjarawan can you please take a look?

**Comment by samjarawan** [comment]
Thanks for the catch Mariya, I've uploaded a new image, should be live soon...

Sam
