### ISSUE TITLE
Confusion - Migrate to the SDK for VS2017 

### ISSUE THREAD

**Issue by Halldor10** [MicrosoftDocs/dynamics-365-unified-operations-public#2444]
In the "Migrate to the SDK for Visual Studio **2017**" section one of the prerequisite is to download "TypeScript_Dev14Full"  

When starting the exe, the form says "TypeScript Tools for Microsoft Studio **2015** 2.2.2.0"

A bit confusing why a tool for VS2015 should be installed when migrating from VS2015 to VS2017.
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 776f646a-f316-8c84-d190-57ecd88547a0
* Version Independent ID: 80208288-e39f-bacc-c8ad-7c51470e9cce
* Content: [Migrate the Retail SDK from Visual Studio 2015 to Visual Studio 2017 - Commerce | Dynamics 365](https://docs.microsoft.com/en-gb/dynamics365/commerce/dev-itpro/retail-sdk/migrate-sdk)
* Content Source: [articles/commerce/dev-itpro/retail-sdk/migrate-sdk.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/dev-itpro/retail-sdk/migrate-sdk.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by josaw1** [comment]
Thanks for the comment. @mugunthanm can you please take a look?

**Comment by mugunthanm** [comment]
Thanks for the feedback. Updated the step with different option to install TS 2.2.2.
