### ISSUE TITLE
Set up required after enabling tax directive on sales tax code

### ISSUE THREAD

**Issue by RamuPalati** [MicrosoftDocs/dynamics-365-unified-operations-public#2445]
[Enter feedback here]

Accounts receivable > Setup > Forms > Form setup.
In that By changing sales tax specification from None to Registration currency we are able to get sales tax directive in sales tax invoice for sales orders.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69b030ce-28ef-5e51-6ef0-dd28ee73959b
* Version Independent ID: 2d1afb70-76e4-f5f5-ca0b-fbe1a00919d7
* Content: [Tax directives for Europe - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/emea-tax-directives)
* Content Source: [articles/finance/localizations/emea-tax-directives.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/localizations/emea-tax-directives.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @epodkolz
* Microsoft Alias: **epodkolz**

**Comment by josaw1** [comment]
Thank you for your comment. @epodkolz can you please review?

**Comment by josaw1** [comment]
BUG 456027 created to track the issue.

**Comment by josaw1** [comment]
This has been updated. Thanks.
