### ISSUE TITLE
No NuGet package available in shared asset library

### ISSUE THREAD

**Issue by ThomasWilke** [MicrosoftDocs/dynamics-365-unified-operations-public#2447]
What to do if there is no NuGet package available in the LCS - shared asset library?
![image](https://user-images.githubusercontent.com/32868226/83147006-5fa16380-a0f7-11ea-9cf3-a1e26483db34.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10459944-bcf8-c5fa-d180-9fb4bb3722da
* Version Independent ID: 29ae9d16-ed7c-92d8-0300-4fc46c777ddf
* Content: [Build automation that uses Microsoft-hosted agents and Azure Pipelines - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/hosted-build-automation)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/hosted-build-automation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-tools/hosted-build-automation.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @jorisdg
* Microsoft Alias: **jorisde**

**Comment by jorisdg** [comment]
PU36 was just made available today. The NuGet files should be available in the shared asset library shortly.
