### ISSUE TITLE
Instructions do not reflect updates for new Entity store continuous updates or self-service JIT connectivity

### ISSUE THREAD

**Issue by Angelos102** [MicrosoftDocs/dynamics-365-unified-operations-public#2448]
The instructions above only refer to the older version of Entity store updates using batch and not the continuous update mechanism introduced

Also the connectivity into the AXDW database for a Sandbox environment requires a JIT request before you can access the AXDW database

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da145b17-ccd8-7bf7-7495-0ddb1bf5829f
* Version Independent ID: 2a24d715-ecac-1c65-d2d4-8d14b55b8765
* Content: [Power BI integration with Entity store - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/power-bi-integration-entity-store?toc=/dynamics365/commerce/toc.json)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/power-bi-integration-entity-store.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/power-bi-integration-entity-store.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by josaw1** [comment]
Thank you for your feedback. @MilindaV2 can you please review?

**Comment by josaw1** [comment]
BUG 456028 created to track the issue.

**Comment by josaw1** [comment]
The article was updated by @TJVass.
