### ISSUE TITLE
Wrong Documentation in Data management package REST API

### ISSUE THREAD

**Issue by pocki** [MicrosoftDocs/dynamics-365-unified-operations-public#2450]
Please check the documentation, there are a lot of mistakes in it.

Some points I found, but not checked and tested every method:
* **executionId** / **Execution ID** is called **Job ID** in D365FO Web User Interface - this should be mentioned somewhere
* At [GetAzureWritableUrl](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/data-management-api#getazurewritableurl):
  * At description of Input parameters is **packageUrl** mentioned but it is **uniqueFileName**
  * Successful Response of the value is not a JSON Object, its a string with an encoded JSON object. Correct example:
```
{ 
  "@odata.context":"https://<baseurl>/data/$metadata#Edm.String", 
  "value":"{\"BlobId\":\"{<GUID>}\",\"BlobUrl\":\"https://<baseurl_id>.blob.core.windows.net/dmf/<uniqueFileName>?<SAS Token>\"}"
}
```
* At [ImportFromPackage](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/data-management-api#importfrompackage): The successful response contains directly the executionId in the value as string and not within a JSON object. Correct example:
```
{ 
  "@odata.context":"https://<baseurl>/data/$metadata#Edm.String", 
  "value":"<executionId>"
}
```
* At [GetExecutionSummaryStatus](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/data-management-api#getexecutionsummarystatus), the same wrong example for a successful response. Correct example:
```
{ 
 "@odata.context":"https://<baseurl>/data/$metadata#Microsoft.Dynamics.DataEntities.DMFExecutionSummaryStatus", 
 "value":"<executionStatus>"
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d963d4c-de1f-7730-bee2-016dcde40907
* Version Independent ID: 21b95d43-5ad9-0ffc-21b9-6a4ba9086a56
* Content: [Data management package REST API - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/data-management-api)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/data-management-api.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/data-management-api.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by kfend** [comment]
@pocki  - thanks for the feedback. 
@Sunil-Garg - can you please take a look at and address this feedback?

**Comment by Sunil-Garg** [comment]
Thank you @pocki for the feedback. The doc has been updated.
