### ISSUE TITLE
We cannot assign the same license more than once to one account.

### ISSUE THREAD

**Issue by kanagayo** [MicrosoftDocs/dynamics-365-unified-operations-public#2452]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a465cba-da38-a42a-495f-299b90f2d5cf
* Version Independent ID: 4e1952ae-622a-ba1d-5258-dc334c0c35db
* Content: [Multiple LCS projects and production environments on one Azure AD tenant - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/implement-multiple-projects-aad-tenant#licensing-requirements)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/implement-multiple-projects-aad-tenant.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/get-started/implement-multiple-projects-aad-tenant.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @ClaudiaBetz-Haubold
* Microsoft Alias: **chaubold**

**Comment by kanagayo** [comment]
In this document said:
> Users who access multiple environments in parallel must be licensed separately for each environment. For more licensing information, download the Licensing guide.

And, in [another document](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/tasks/create-new-users#associate-a-user-with-a-license-new-license-types-only) said:
> System admins can assign licenses to users in the Microsoft 365 admin center.

But, We cannot assign the same license more than once to one account.

These documents are inconsistent.
I propose two solutions.
1. Erase the wording of the original document.
2. Please include this information in the Disadvantages of the original document.

**Comment by tonyafehr** [comment]
@kanagayo, thanks for the feedback. 
@ClaudiaBetz-Haubold, please review and make updates as needed.

**Comment by tonyafehr** [comment]
Bug #456961 logged to track this issue.

**Comment by tonyafehr** [comment]
This topic has been updated and now states "A user can only be assigned one license for each product for each Azure AD tenant. This allocation of licensing requirements for LCS projects for specific users must be documented outside the system."
