### ISSUE TITLE
mistype Chat instead of Chart

### ISSUE THREAD

**Issue by wojzeh** [MicrosoftDocs/dynamics-365-unified-operations-public#2454]
Chart parts only contain OLAP charts
When a workspace contains a chat,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b39782c9-a0a3-940f-8ca8-c5ac3440ea01
* Version Independent ID: 5f6f25ed-67d3-3f46-a6d2-9dc92781b9e0
* Content: [Build operational workspaces - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/user-interface/build-workspaces)
* Content Source: [articles/fin-ops-core/dev-itpro/user-interface/build-workspaces.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/user-interface/build-workspaces.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by kfend** [comment]
@wojzeh - thanks for catching that. I have fixed the typo and the changes will publish today.
