### ISSUE TITLE
Retail parameters section is outdated

### ISSUE THREAD

**Issue by MariyaKoteva** [MicrosoftDocs/dynamics-365-unified-operations-public#2455]
The Retail parameters are now Commerce parameters and print screen is outdated. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e29843f-4b7d-5b4b-6a71-d468e504f63c
* Version Independent ID: f72648ff-10e0-340e-6f51-b8c3766e1b6f
* Content: [Dynamics 365 Fraud Protection integration with Dynamics 365 Commerce - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/dfp)
* Content Source: [articles/commerce/dev-itpro/DFP.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/dev-itpro/DFP.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @rubendel
* Microsoft Alias: **rubendel**

**Comment by kfend** [comment]
@MariyaKoteva - Thanks for the feedback.
@rubencdelgado - Can you please take a look at and address this?
