### ISSUE TITLE
Mention maxSize of enqueued message when using Recurring integrations

### ISSUE THREAD

**Issue by renebik** [MicrosoftDocs/dynamics-365-unified-operations-public#2467]
Can [this section](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/recurring-integrations#submitting-data-to-recurring-data-jobs) be appended with the maxSize of the enqueue message if any?
At the moment at least I am running into issues when submitting a message of approx 36MB and receive a HTTP 413 RequestEntityTooLarge exception.

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01b2cd6b-f885-7461-fbdf-cf81f9e50d86
* Version Independent ID: 8df7a6ae-67db-5d29-fb6a-0820704ff3ef
* Content: [Recurring integrations - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/recurring-integrations)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/recurring-integrations.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/recurring-integrations.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by tonyafehr** [comment]
@renebik, thanks for the feedback. 
@Sunil-Garg, please review.

**Comment by tonyafehr** [comment]
Bug #456970 logged to track this issue.

**Comment by Sunil-Garg** [comment]
@renebik the message that is sent to the queue is a system generated message. I am not sure, I understand when you say you are getting an error with sending a 36MB message? Are you referring to the file size that is to be imported? Can you clarify pls?

**Comment by renebik** [comment]
@Sunil-Garg When submitting a message from an HTTP action in a LogicApp to the enqueue endpoint (https://<base URL>/api/connector/enqueue/<activity ID>?entity=<entity name>) we receive an HTTP 413 Request entity too large response. The body of the HTTP POST is approx 36MB.

**Comment by renebik** [comment]
@tonyafehr Why is this closed?
