### ISSUE TITLE
Email legacy authentication retirement details

### ISSUE THREAD

**Issue by mrpnelson** [MicrosoftDocs/dynamics-365-unified-operations-public#2468]
The email configuration pages seems to lack detail regarding the underlying authentication mechanisms for the three email providers (SMTP, Exchange, EML) and the effects of planned changes in Office 365. 

In particular, as implemented today will these methods function uninterrupted with the retirement of legacy authentication support? 

For the _Exchange email server_ option, [this article](https://developer.microsoft.com/en-us/office/blogs/end-of-support-for-basic-authentication-access-to-exchange-online-apis-for-office-365-customers/) on the Office 365 Developer Blog suggests the potential for issues if these methods are dependent on legacy authentication. Per this document, EWS appears to be a dependency, as noted [in this section](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/organization-administration/configure-email?toc=/dynamics365/finance/toc.json#user-optional-how-would-you-like-to-send-email-dialog-box).

It would be helpful to:

1. Clarify any current dependencies on legacy authentication and/or confirm that services will not be interrupted as result of these changes.
2. Clearly define the authentication protocols and modern auth/OAuth 2.0 support status per-method (for the Exchange and SMTP methods). For client app workflows, it seems reasonable and necessary to defer support definitions to the relevant platform or application.

If there is documentation detailing these planned changes and their anticipated effects, it was not readily apparent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e46e3d2a-37fb-9961-84fe-0be6d9f0235b
* Version Independent ID: c4a46858-a79b-08b4-d81c-941490d42da3
* Content: [Configure and send email - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/organization-administration/configure-email)
* Content Source: [articles/fin-ops-core/fin-ops/organization-administration/configure-email.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/organization-administration/configure-email.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @ChrisGarty
* Microsoft Alias: **cgarty**

**Comment by tonyafehr** [comment]
@mrpnelson, thanks for the good feedback.
@ChrisGarty, please review.

**Comment by tonyafehr** [comment]
Bug #456981 logged to track this issue.

**Comment by ChrisGarty** [comment]
@mrpnelson, thanks for the questions. It is interesting that you know this much about the migration efforts
1. EML is not authenticated.
2. SMTP uses simple authentication so it isn't affected.
3. Exchange did need to be migrated and we did that back in October 2018 in PU22 :).

I'll remove the reference to EWS in the doc :)

**Comment by mrpnelson** [comment]
That's perfect and just the confirmation we needed - thanks @ChrisGarty + team! From my perspective, okay to close this issue. Cheers; Paul.

**Comment by mrpnelson** [comment]
As a note for others that land on this page, I think the key item to be aware of here is that after MS retirement of legacy auth _or_ after your own organization's disabling of legacy auth, that the Exchange method will become necessary (and any SMTP configurations would need to be adjusted).
