### ISSUE TITLE
Please be more explicit for steps 5 when opening management studio - see link provided

### ISSUE THREAD

**Issue by Angelos102** [MicrosoftDocs/dynamics-365-unified-operations-public#2469]
Need to be more explicit when using Management studio in the last steps

See instructions  below
[(https://cloudblogs.microsoft.com/dynamics365/it/2019/08/06/lifecycle-services-august-2019-release-1-release-notes/)]

Also in LCS you are provide with a Server/database connection string and this makes you assume it will log into specific DB, you must instead separate that string into server and db name and enter them individually in the steps linked above, else you will get an error

Lets be more explicit please, as it took me a while to hunt for this information and had to raise a support ticket

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42e51870-4f46-c1ae-4d85-2e74861c4314
* Version Independent ID: bea7397e-9977-47d7-5fb1-57c73b9bf510
* Content: [Maintenance operations for deployments - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/maintenanceoperationsguide-newinfrastructure)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/maintenanceoperationsguide-newinfrastructure.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/deployment/maintenanceoperationsguide-newinfrastructure.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by tonyafehr** [comment]
@Angelos102, thanks for the feedback. 
@laneswenka, please review.

**Comment by tonyafehr** [comment]
Bug #456982 logged to track this issue.
