### ISSUE TITLE
Mismatch between TOC (Template section) and actual content 

### ISSUE THREAD

**Issue by Moutasema** [MicrosoftDocs/dynamics-365-unified-operations-public#2470]
There is a mismatch between the table of content (Template section) and the actual content. You should update the Template section to match the actual mapping such as: 

- Sales tax groups to msdyn_taxgroups

- Item sales tax group to msdyn_taxitemgroups

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 827c4917-db78-1618-1e51-79219ec33fa7
* Version Independent ID: 8be37cc2-fcf0-e3c3-15ab-90c8e20eaae4
* Content: [Integrated tax - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/tax-mapping)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/tax-mapping.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/dual-write/tax-mapping.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: ****

**Comment by tonyafehr** [comment]
@RobinARH, please review. Thanks!

**Comment by RobinARH** [comment]
I fixed the topic. The new content should go live this evening. -Robin
