### ISSUE TITLE
Doc's for 'FIFO with the Include physical value option'

### ISSUE THREAD

**Issue by LeifX59** [MicrosoftDocs/dynamics-365-unified-operations-public#2473]
Doc's page:
https://docs.microsoft.com/en-us/dynamics365/supply-chain/cost-management/fifo-physical-value-marking#fifo-without-the-include-physical-value-option

Section:
FIFO without the Include physical value option

In the detailed example given on the page, the following is stated, which is not correct:
"5a. Inventory physical issue for a quantity of 1 at a cost price of USD 20.00 each (running average of financially updated transactions).
5b. Inventory financial issue for a quantity of 1 at a cost price of USD 20.00 each (running average of financially updated transactions)."
[Page feedback FIFO.docx](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/files/4721958/Page.feedback.FIFO.docx)

The correct amount should be  USD 15.00 each. (Not 20.)
My own calculation, and testing in D365, is in my attachment

[Page feedback FIFO.docx](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/files/4721955/Page.feedback.FIFO.docx)

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86ece8c8-fcea-0e14-9bb2-0544b62b17c1
* Version Independent ID: b2e81fea-7a8a-0f06-c760-b6abbbd07cea
* Content: [FIFO with physical value and marking - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/cost-management/fifo-physical-value-marking#fifo-with-the-include-physical-value-option)
* Content Source: [articles/supply-chain/cost-management/fifo-physical-value-marking.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/cost-management/fifo-physical-value-marking.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @AndersGirke
* Microsoft Alias: **shylaw**

**Comment by sericks007** [comment]
@LeifX59, thank you for this feedback.

@AndersEvenGirke, please review and update the content, as needed.

**Comment by sericks007** [comment]
Bug 457365 has been logged to track this issue.

**Comment by sericks007** [comment]
This addresses [2473](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/issues/2473).

**Comment by sericks007** [comment]
@LeifX59, thank you for bringing this issue to our attention!  The PM has updated the topic, and the update will be published later today.
