### ISSUE TITLE
Print Management data stripped when moving DB from T1 Golden to T2 Sandbox

### ISSUE THREAD

**Issue by dhand01** [MicrosoftDocs/dynamics-365-unified-operations-public#2474]
Should Print Management settings be stripped from the DB, when moving from a Tier1 Golden VM, to a Tier2 Sandbox (using the methods described in this article)? It seems that Print Management should be retained in a Golden DB.

---
#### Document Details

<span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://gaoflciahikhligngeccdecgfjngejlh/emoji-data/sheet_apple_32.png);background-position:95.94594594594594% 75.96944770857814%;background-size:5418.75% 5418.75%" data-codepoints="26a0-fe0f"></span></span> *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8eb7ed3e-f7b9-e384-7308-516deda06bcc
* Version Independent ID: 3cd2e0d0-24fd-c019-eecc-8af6e7e7e66c
* Content: [Golden configuration promotion - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/dbmovement-scenario-goldenconfig?source=docs)
* Content Source: [articles/fin-ops-core/dev-itpro/database/dbmovement-scenario-goldenconfig.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/database/dbmovement-scenario-goldenconfig.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laneswenka**

**Comment by josaw1** [comment]
@laneswenka 
BUG 458169 created to track this.
