### ISSUE TITLE
One version service update for Retail

### ISSUE THREAD

**Issue by fivefq** [MicrosoftDocs/dynamics-365-unified-operations-public#2484]
This article needs to be updated to mention what will be changes in package creation process as "All in one package" is being enforced. You cannot have separate packages anymore.

Ref: https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/aio-deployable-packages 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87cf260c-c307-64b7-d7ee-6ce67b73cac0
* Version Independent ID: 778eccaa-e998-ed63-1378-9a0a218a4871
* Content: [Create deployable packages - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/retail-sdk/retail-sdk-packaging)
* Content Source: [articles/commerce/dev-itpro/retail-sdk/retail-sdk-packaging.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/dev-itpro/retail-sdk/retail-sdk-packaging.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @mugunthanm
* Microsoft Alias: **sijoshi**

**Comment by josaw1** [comment]
Thank you for your feedback. @mugunthanm can you please review?

**Comment by mugunthanm** [comment]
Adding @laneswenka and @rashmansur to help with this.

**Comment by josaw1** [comment]
BUG 458171 created to track this issue.

**Comment by mugunthanm** [comment]
Commerce package goes to RCSU and it will not be bundled with F & O package. Commerce package need to be deployed separately.
