### ISSUE TITLE
Lead qualification docs

### ISSUE THREAD

**Issue by assofohdz** [MicrosoftDocs/dynamics-365-unified-operations-public#2487]
Where's the information about lead qualification and how to set it up ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0b18e33-4012-5d68-181f-4a70b608d086
* Version Independent ID: 58dc69d8-c12f-211c-f01d-1decd235d57b
* Content: [Sales and marketing overview - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/sales-marketing/overview-sales-marketing)
* Content Source: [articles/supply-chain/sales-marketing/overview-sales-marketing.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/sales-marketing/overview-sales-marketing.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **kfend**

**Comment by kamaybac** [comment]
Hi @assofohdz . I believe that this functionality still works the same way as it did in AX 2012. Please refer to the AX documentation, which starts here: https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/qualify-leads
