### ISSUE TITLE
Applying of ISV License packages in self-service environments

### ISSUE THREAD

**Issue by EvSeVo** [MicrosoftDocs/dynamics-365-unified-operations-public#2489]
It looks like self-service environments don't supported applying of ISV license packages (https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/isv-licensing#production-environments). It is not mentioned in the article.

**Comment by kfend** [comment]
@EvSeVo - than you for the feedback.
@jorisdg - can you please take a look at and address this?

**Comment by jorisdg** [comment]
Applying ISV licenses is the same across all types of environments. That is why self-service is not mentioned, but the older VM-based environments are also not mentioned.

The article talks about ensuring/how the ISV license can be included in the deployable package. That deployable package can then be deployed to your environments through LCS (~ regardless of the type of environment).
