### ISSUE TITLE
Wrong Link

### ISSUE THREAD

**Issue by Shind44** [MicrosoftDocs/dynamics-365-unified-operations-public#2490]
Link to access to page "Advanced ledger settlement: Settlement and reverse settlement processed separately" is broken :

https://docs.microsoft.com**s**/dynamics365-release-plan/2020wave1/dynamics365-finance/advanced-ledger-settlement-settlement-reverse-settlement-processed-separately

instead of (.coms -> .com)
https://docs.microsoft.com/dynamics365-release-plan/2020wave1/dynamics365-finance/advanced-ledger-settlement-settlement-reverse-settlement-processed-separately
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9114eb7a-c167-a856-66cc-15419a291289
* Version Independent ID: 0e8cc2c2-308b-a063-45c9-f2361c6d3cc0
* Content: [What's new or changed in Dynamics 365 Finance 10.0.12 (August 2020) - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/get-started/whats-new-changed-10-0-12)
* Content Source: [articles/finance/get-started/whats-new-changed-10-0-12.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/get-started/whats-new-changed-10-0-12.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @roschlom
* Microsoft Alias: **roschlom**

**Comment by RobinARH** [comment]
Hi Bob - Can you take a look? Thanks.

**Comment by RobinARH** [comment]
The link is fixed.
