### ISSUE TITLE
Is this section regarding optional parameters actually correct?

### ISSUE THREAD

**Issue by jonathonjoiner** [MicrosoftDocs/dynamics-365-unified-operations-public#2491]
[Enter feedback here]

In this section regarding optional parameters; is this actually correct?

The commented section indicates the next statement does not compile but it's the exact same as the one that is indicated as correct

// info(int2Str(Additions::AddThreeInts(1, 2, 99)));
vs
info(int2Str(Additions::AddThreeInts(1, 2, 99)));

public class Additions 
{
    static public int AddThreeInts(int _i1, int _i2 = 2,int _i3 = 3)
    {
        return _i1 + _i2 + _i3;
    }
}

// This code calls the AddThreeInts method.
// No way to skip the first optional parameter (so it can default)
// while also specifying the value of the second optional parameter.
// The next statement does not compile.
// info(int2Str(Additions::AddThreeInts(1, 2, 99)));

// Settle for overriding both optional parameters.
info(int2Str(Additions::AddThreeInts(1, 2, 99)));
// Output is "102".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2deb3461-0602-b91a-d92d-c2dc7c69c197
* Version Independent ID: 92e2d8ec-9543-ee7c-042c-524e03bf230e
* Content: [Classes and methods - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-ref/xpp-classes-methods)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-ref/xpp-classes-methods.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-ref/xpp-classes-methods.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **rhaertle**

**Comment by RobinARH** [comment]
I updated both code examples in that section and the new content should go live this evening. Thanks for letting us know. - Robin
