### ISSUE TITLE
Stop and Start option removed

### ISSUE THREAD

**Issue by jopankow** [MicrosoftDocs/dynamics-365-unified-operations-public#2505]
Hello,

This page is outdated with the changes to the start/stop button in LCS for MS managed environments (as posted here: https://www.yammer.com/dynamicsaxfeedbackprograms/#/threads/show?threadId=683009992425472). Please update the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9452234-62df-d7ed-1243-4f2a14553df3
* Version Independent ID: 14f785e5-da29-5cc9-bd8a-d548c93d15e9
* Content: [Restart environment services - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/restart-environment-services)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/restart-environment-services.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/lifecycle-services/restart-environment-services.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by kfend** [comment]
@jopankow - thanks for the feedback. 
@laneswenka - can you please take a look at this?

**Comment by laneswenka** [comment]
This change was reverted by the engineering team.  Customers can now do this activity again as-documented.
