### ISSUE TITLE
Data Encryption Rotation System Job

### ISSUE THREAD

**Issue by JameZJ** [MicrosoftDocs/dynamics-365-unified-operations-public#2508]
I don't see a data rotation encryption job anywhere. Can you provide more details of where I can monitor the success of this job? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eac091f6-4eb0-3174-d8ae-79ee922349a8
* Version Independent ID: b141a04f-324d-9050-59c8-2a761a99bdab
* Content: [Certificate rotation - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/certificate-rotation-on-prem)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/certificate-rotation-on-prem.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/deployment/certificate-rotation-on-prem.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @PeterRFriis
* Microsoft Alias: **perahlff**

**Comment by PeterRFriis** [comment]
Hi JameZJ
For onprem/LBD you need to rotate the certificates manually, per the documentation. 
When the new certificates are in place, you run the update settings with the new thumbprints, and a new deployment of the environment is triggered with new settings that contains the new thumbprints. During this deployment the new certs are being used. But it runs just like a normal deployment and the monitoring happens the same way. Success/failure can be seen in LCS as normal, and for deployment progress I would usually use Service fabric explorer.
/Peter

**Comment by PeterRFriis** [comment]
HI JamesZJ
Just adding to the explanation. If you are referring to the re-encryption of data in the AXDB then there is no visible way to see that it is done. it is being run by a batch job, and usually all is reencrypted with 24 hours, but if you leave the old cert there for 3-4 days. Then you should be completely safe.

**Comment by JameZJ** [comment]
I was referring to the re-encryption of data in the AXDB. Thank you for clarifying its visibility and approximate time of completion.
