### ISSUE TITLE
Missing information about suspended transactions getting lost in the process.

### ISSUE THREAD

**Issue by andreashofmann1** [MicrosoftDocs/dynamics-365-unified-operations-public#2511]
[Enter feedback here]
An important piece of information is missing: Please add that any suspended transactions will be lost and cannot be recalled. Ideally, it may be good to mention that those should be recalled and voided before.   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50f98d51-e924-ddfa-0613-738a5b22de92
* Version Independent ID: 42f8aca8-4569-8032-241f-5d3e25cf15a3
* Content: [Initialize Commerce Scale Unit (cloud) - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/initialize-retail-channels#additional-considerations-if-you-initialize-cloud-hosted-commerce-channel-components-in-an-existing-environment)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/Initialize-Retail-Channels.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/deployment/Initialize-Retail-Channels.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @AamirAllaq
* Microsoft Alias: **aamiral**

**Comment by tonyafehr** [comment]
Thank you for the feedback.
@AamirAllaq, please review.

**Comment by AamirAllaq** [comment]
Content has been updated to reflect this.
