### ISSUE TITLE
Missing Field Information for Units of measure

### ISSUE THREAD

**Issue by bzwick** [MicrosoftDocs/dynamics-365-unified-operations-public#2514]
Hi Microsoft. I believe there should be some more descriptions about what to use fields for on the Units of Measure. (Base unit and System unit) to be exact. 
![image](https://user-images.githubusercontent.com/66977526/84713803-c65cb480-af20-11ea-92d5-d68a1942bd1b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54259aca-1ed7-cc7a-c898-65f065aba0e7
* Version Independent ID: ae89e895-7f44-90f1-6cdf-1e434f3b7aae
* Content: [Manage unit of measure - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/pim/tasks/manage-unit-measure)
* Content Source: [articles/supply-chain/pim/tasks/manage-unit-measure.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/pim/tasks/manage-unit-measure.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @sorenva
* Microsoft Alias: **sorenand**

**Comment by tonyafehr** [comment]
Thanks for the feedback. 
@sorenva, please review.

**Comment by sorenva** [comment]
Thank you for the feedback. I will add to our backlog to improve this documentation topic with additional details. We will also evaluate whether we can add better field help directly in the application. 
Regards
... Søren Vagn Andersen, Principal Program Manager, Dynamics 365 Supply Chain Management
