### ISSUE TITLE
Release plan for possibility to use Feature management for ISV:s and Customisations

### ISSUE THREAD

**Issue by HenrikLevinson** [MicrosoftDocs/dynamics-365-unified-operations-public#2516]
We are currently looking into to use some kind of feature management for our own customizations. You say in the article that you have support to use feature management for ISV:s and customizations in the pipeline for future development of the feature management. Do you have any idea when this capability could be released?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51e63496-19e3-182e-c19d-027a0a5f6acf
* Version Independent ID: c8a51a1e-25e8-fbe3-4580-baca9046b7b0
* Content: [Feature management overview - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/feature-management/feature-management-overview)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/feature-management/feature-management-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/get-started/feature-management/feature-management-overview.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @mikefalkner
* Microsoft Alias: **mfalkner**

**Comment by tonyafehr** [comment]
Thanks for your question. @ChrisGarty, please review.

**Comment by tonyafehr** [comment]
Bug #462129 logged to track this issue.

**Comment by ChrisGarty** [comment]
We are working on making Feature Management more available to ISVs and Partners, but don't currently have a clear timeline. Stay tuned. @ParAkerblom may provide updates on this in the future.

**Comment by ChrisGarty** [comment]
Resolved Bug 462129: Docs issue #2516: Release plan for possibility to use Feature management for ISV:s and Customizations
