### ISSUE TITLE
Call out supported and unsupported CDS filters under "Filter your data" section

### ISSUE THREAD

**Issue by Moutasema** [MicrosoftDocs/dynamics-365-unified-operations-public#2521]
As per Chunke Yang chuyang@microsoft.com: 

Nested lookup is currently not supported in dual-write source filter. As of now, only standard filter operators (https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/query-data-web-api#standard-filter-operators) directly against entity fields are supported.

We should add this at the end of the **"Filter your data"** [section](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/customizing-mappings#filter-your-data)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1063123b-f794-e863-2cf2-231a499c68c6
* Version Independent ID: 8c0c29c2-e3a2-809d-ce9e-6ca3b51c1d1b
* Content: [Customize entity and field mappings - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/customizing-mappings)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/customizing-mappings.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/dual-write/customizing-mappings.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @sabinn-msft
* Microsoft Alias: **sabinn**

**Comment by josaw1** [comment]
Thank you for your feedback. @sabinn-msft can you please take a look.
