### ISSUE TITLE
Is note still valid

### ISSUE THREAD

**Issue by rabol** [MicrosoftDocs/dynamics-365-unified-operations-public#2524]
[Enter feedback here]
On the page there is this note:

"For on premise deployments, the only supported API is the Data management package REST API. This is currently available on 7.2, platform update 12 build 7.0.4709.41184."

Is this still valid? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2cdcdc3-398f-f785-d02e-cc784d91869c
* Version Independent ID: c7ec7a85-c489-f8c5-33c1-68f622108741
* Content: [Choose a data integration strategy - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/integration-overview)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/integration-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/integration-overview.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by Sunil-Garg** [comment]
Hi @rabol -- yes, this is still valid. The data package API is the supported integration API for on-premise. Thanks.
