### ISSUE TITLE
Outdated article 

### ISSUE THREAD

**Issue by MariyaKoteva** [MicrosoftDocs/dynamics-365-unified-operations-public#2525]
The information on the page is outdated, it only talks about connecting the online channel to a 3rd party solution for a web storefront and it does not mention the e-commerce site from Microsoft, while it is in the section for creating e-commerce site in Dynamics 365 Commerce. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad5037db-a285-90d6-2190-fee44897bd30
* Version Independent ID: 8bf15241-2bf6-433d-10d7-ed1f867bf056
* Content: [Set up an online store channel - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/online-stores)
* Content Source: [articles/commerce/online-stores.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/online-stores.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **meeram**

**Comment by josaw1** [comment]
@samjarawan can you please take a look at this feedback and topic? Thanks.

**Comment by samjarawan** [comment]
Thank you for the feedback.  This page is definitely outdated, we'll remove the page and add new link to another one that is more up to date: https://docs.microsoft.com/en-us/dynamics365/commerce/channel-setup-online .
thanks!
Sam
