### ISSUE TITLE
Table groups > table properties

### ISSUE THREAD

**Issue by ibruynin** [MicrosoftDocs/dynamics-365-unified-operations-public#253]
The link to "Table Groups" in this page refers to the AX 2012 values.
In D365FO the following are added:
* Reference
* Worksheet
* TransactionHeader
* TransactionLine
* Staging
These properties are currently not documented as far as I can see.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a55b1963-c3b1-f0d7-e072-84aeb7ac3dfe
* Version Independent ID: 54abeb7e-6606-2b15-c93e-369b30a55b0b
* Content: [Table properties - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/ax-2012/table-properties)
* Content Source: [articles/dev-itpro/lifecycle-services/ax-2012/table-properties.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/lifecycle-services/ax-2012/table-properties.md)
* Product: **dynamics-ax-2012**
* GitHub Login: @kfend
* Microsoft Alias: **kfend**

**Comment by ShylaThompson** [comment]
@ibruynin, the lifecycle services topic is an AX 2012 topic, so this is by design.
