### ISSUE TITLE
It is not quite clear when this feature should be used, in what scenario?

### ISSUE THREAD

**Issue by EgidijusZa** [MicrosoftDocs/dynamics-365-unified-operations-public#2531]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 903f0c12-ee21-2d66-dd29-bd3bbbf62ebf
* Version Independent ID: 6db6da1d-295a-4d1f-829e-9c54b9a9e548
* Content: [AD FS Office 365 compatibility - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/onprem-adfscompatibility)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/onprem-adfscompatibility.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/deployment/onprem-adfscompatibility.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @faix
* Microsoft Alias: **osfaixat**

**Comment by faix** [comment]
Hello,

As we state in the document: This topic explains how to use the same instance of Active Directory Federation Services (AD FS) for a Dynamics 365 Finance + Operations (on-premises) environment and for Microsoft Office 365. 

Before we introduced this compatibility mode, Dynamics required a specific configuration in AD FS which was not compatible with an AD FS used for authentication with Office 365.

**Comment by EgidijusZa** [comment]
ok, so it means, if we have Office365 it is better to have this parameter switched on. And ADFS configuration steps, described in https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/setup-deploy-on-premises-pu12#configureadfs,  can be also skipped, except  configuration of application group?

**Comment by EgidijusZa** [comment]
...

**Comment by faix** [comment]
You should skip step 1, however steps 2 and 3 you will most likely need. It will depend on your current AD FS configuration. You will need to configure the application group yes.

**Comment by EgidijusZa** [comment]
ok, thanks.
