### ISSUE TITLE
Sharing apps with external users

### ISSUE THREAD

**Issue by pturegano** [MicrosoftDocs/dynamics-365-unified-operations-public#2532]
Hello,
I have noticed the following behavior and I would like to suggest to update the page to reflect the same. 
 - A Power App is embedded in the UI and shared with external users of the instance.
 - External user: guest or not belonging to the O365 AD where the instance is deployed.

Behavior:
 - The external user is unable to use the embedded app but is able to use the Power App directly (via the app link).

Please check the support case 120041521000783 for further details. (Engineers: Davide Garghentini <dgarghen@microsoft.com>  and Emeka Monyei (Tek Experts) <v-emmony@microsoft.com>)

Thanks
Pere

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4f6f055-63b4-17e8-5d4d-27e298733e4e
* Version Independent ID: 9199a704-9504-eb02-bffa-12c414707b08
* Content: [Embed Power Apps - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/embed-power-apps?source=docs)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/embed-power-apps.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/get-started/embed-power-apps.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by tonyafehr** [comment]
@pturegano, thanks for the feedback.
@jasongre, please review.

**Comment by tonyafehr** [comment]
Bug #465771 logged to track this issue.

**Comment by jasongre** [comment]
Thanks for calling this out! The documentation should be updated to reflect this soon.
