### ISSUE TITLE
Update 

### ISSUE THREAD

**Issue by yxx-39** [MicrosoftDocs/dynamics-365-unified-operations-public#2533]
There is no praise source type in this page, please update it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7a27404-cc5d-6298-cf05-1bb7c8f9b156
* Version Independent ID: e735b173-6cf1-52b3-277c-e3965038343f
* Content: [Performance management - Human Resources | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/human-resources/hr-develop-performance-management-overview)
* Content Source: [articles/human-resources/hr-develop-performance-management-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/human-resources/hr-develop-performance-management-overview.md)
* Service: **dynamics-365-human-resources**
* Product: ****
* Technology: ****
* GitHub Login: @andreabichsel
* Microsoft Alias: **anbichse**

**Comment by tonyafehr** [comment]
@yxx-39, thanks for the feedback. 
@andreabichsel, please review.

**Comment by tonyafehr** [comment]
Bug #467973 logged to track this issue.

**Comment by andreabichsel** [comment]
I verified and fixed the topic per your feedback. Thank you for catching that!
