### ISSUE TITLE
Set model versions fails

### ISSUE THREAD

**Issue by rsammut** [MicrosoftDocs/dynamics-365-unified-operations-public#2535]
After following all steps, I am getting ##[error]Resolve-Path : Cannot find path 'C:\DynamicsSDK\VSOAgent\_work\1\s\Metadata' in the "Set Model Versions" step of the BUILD pipeline.

Same issue was reported here by another person: https://community.dynamics.com/365/financeandoperations/f/dynamics-365-for-finance-and-operations-forum/373773/build-fail-on-c-dynamicssdk-vsoagent-_work-2-s-metadata

Is this page up to date and includes all necessary steps?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0e507e9-ac8b-1fb7-d30d-94ce77749d1f
* Version Independent ID: ec678c46-f397-f09a-eff8-4fcd8b5296e5
* Content: [Merge the build systems for Commerce and Finance - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/retail-sdk/integrate-retail-sdk-continuous-build)
* Content Source: [articles/commerce/dev-itpro/retail-sdk/integrate-retail-sdk-continuous-build.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/dev-itpro/retail-sdk/integrate-retail-sdk-continuous-build.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @AndreasHassing
* Microsoft Alias: **andreash**

**Comment by tonyafehr** [comment]
@AndreasHassing, please review.

**Comment by andreashofmann1** [comment]
I am not sure what or how to review?  But the issue is likely that they is being run on a non-build environment.

**Comment by rsammut** [comment]
> I am not sure what or how to review? But the issue is likely that they is being run on a non-build environment.

It's a Build and Test environment deployed on 11/30/2018. Do you think re-deploying the BUILD environment will help since its more than a year and half old?

@andreashofmann1 btw, thanks for your retail blogs, they're very helpful!

**Comment by tonyafehr** [comment]
Bug #465780 logged to track this issue.
