### ISSUE TITLE
Debugging SAT copy - Guide missing domain name on the SQL server name

### ISSUE THREAD

**Issue by NFMynster** [MicrosoftDocs/dynamics-365-unified-operations-public#2537]
Hello, the guide states that you simply need to connect to the SQL server name you get within LCS.

> and note the server and database in the format {sqlServer\sqlDatabase}.

However, it doesn't mention that you have to suffix this with database.windows.net.

So it would become sqlServer.database.windows.net\sqlDatabase.
This would be a great addition [this particular section.](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/dbmovement-scenario-debugdiag#add-your-ip-address-to-a-safe-list)

Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb08fb04-94d5-ef25-8162-a0d79f5ee70a
* Version Independent ID: 6d43b4b7-cc2e-49bc-564a-5eb5eacefa84
* Content: [Debug a copy of the production database - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/dbmovement-scenario-debugdiag)
* Content Source: [articles/fin-ops-core/dev-itpro/database/dbmovement-scenario-debugdiag.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/database/dbmovement-scenario-debugdiag.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laneswenka**

**Comment by tonyafehr** [comment]
@NFMynster, thanks for the feedback. 
@laneswenk, please review.

**Comment by tonyafehr** [comment]
Bug #465779 logged to track this issue.

**Comment by NFMynster** [comment]
@laneswenka @tonyafehr any news? Thank you.
