### ISSUE TITLE
Confution when you read this document and you are trying to enable this feature

### ISSUE THREAD

**Issue by clugarte** [MicrosoftDocs/dynamics-365-unified-operations-public#2538]
[Enter feedback here]
In section "How to use trickle feed-based posting" the step 2 is referring to preview feature and if someone is trying to enable it, when you go to License parameters in 10.0.9 and above, it will not found this option and it is not necessary to do it, that's why this is causing confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f53eb353-455f-37e8-646b-500d9a5a6402
* Version Independent ID: 81c4d76f-ec29-877d-cb51-374c05741909
* Content: [Trickle feed-based order creation for retail store transactions - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/trickle-feed)
* Content Source: [articles/commerce/trickle-feed.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/trickle-feed.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by sericks007** [comment]
@clugarte, thank you for posting this feedback.

@josaw1, please review and consider updating the content.

**Comment by sericks007** [comment]
Bug 466223 has been logged to track this issue.

**Comment by josaw1** [comment]
@anpurush, please review and update the topic as needed. Thanks.

**Comment by sericks007** [comment]
This content has been updated and will be published later today. Thanks!
