### ISSUE TITLE
Partner option in LCS

### ISSUE THREAD

**Issue by ripannandy** [MicrosoftDocs/dynamics-365-unified-operations-public#254]
In our partner LCS Subscription, We are only getting **prospective presales** option while creating new project. **Migrate,create solutions and  learn Dynamics 365 Finance and Operations** options are unavailable which we used to get earlier while creating new project. Could anyone please tell me the reason of this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb7ada8a-99a7-aaad-5bbc-f7fde6ac751e
* Version Independent ID: eef2e9eb-6390-a3f5-ab89-53be2846d0e5
* Content: [Lifecycle Services for Finance and Operations partners - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/getting-started-lcs#feedback)
* Content Source: [articles/dev-itpro/lifecycle-services/getting-started-lcs.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/lifecycle-services/getting-started-lcs.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @manalidongre
* Microsoft Alias: **manado**

**Comment by ShylaThompson** [comment]
Thanks for contacting us. Unfortunately, we can't handle support requests for the product here. To contact support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support)
