### ISSUE TITLE
Where can I download the Visual Studio solution for Bootstrapping Company Code from D365 FO to CDS

### ISSUE THREAD

**Issue by bhlj** [MicrosoftDocs/dynamics-365-unified-operations-public#2541]
Can you tell me where I can download the Visual Studio solution for Bootstrapping Company Code from D365 FO to CDS, as described in this otherwise excellent article?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0891e384-80e8-5d40-8bde-24081e06876a
* Version Independent ID: b6ecc0cb-e827-80aa-934d-ef03d674c97e
* Content: [Bootstrap with company data FAQ - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/bootstrap-company-data)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/bootstrap-company-data.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/dual-write/bootstrap-company-data.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @RamaKrishnamoorthy
* Microsoft Alias: **ramasri**

**Comment by josaw1** [comment]
Thank you for your feedback. @RamaKrishnamoorthy can you please take a look?

**Comment by josaw1** [comment]
@RamaKrishnamoorthy: BUG 466758 created to track the issue.

**Comment by RamaKrishnamoorthy** [comment]
We have not provided the visual studio solution intentionally. You can create a blank solution and copy paste the c# sample code provided on the page. However, we are coming up with a well-defined guidelines for bootstrapping based on data volume. This should be published by mid of Aug'20.
