### ISSUE TITLE
Where can I get the VS solution mentioned in the article?

### ISSUE THREAD

**Issue by bhlj** [MicrosoftDocs/dynamics-365-unified-operations-public#2543]
I cant see any links to where I can download the VS solution described.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0891e384-80e8-5d40-8bde-24081e06876a
* Version Independent ID: b6ecc0cb-e827-80aa-934d-ef03d674c97e
* Content: [Bootstrap with company data FAQ - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/bootstrap-company-data)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/bootstrap-company-data.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/dual-write/bootstrap-company-data.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @RamaKrishnamoorthy
* Microsoft Alias: **ramasri**

**Comment by josaw1** [comment]
Thanks for your feedback. This looks like the same question as received earlier. I will close this issue and keep the other one open for feedback from the author.
