### ISSUE TITLE
How i can see the payment processor project ?

### ISSUE THREAD

**Issue by jalaliskandar** [MicrosoftDocs/dynamics-365-unified-operations-public#2544]
[Enter feedback here]

the section of "Write a payment processor " is not clear , the guide also.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8082a393-27b6-131d-b708-ddf23411fde9
* Version Independent ID: ffb5a30e-508b-5b65-2b0d-7e888063d85c
* Content: [Create an end-to-end payment integration for a payment terminal - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/end-to-end-payment-extension)
* Content Source: [articles/commerce/dev-itpro/end-to-end-payment-extension.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/dev-itpro/end-to-end-payment-extension.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @Reza-Assadi
* Microsoft Alias: **rassadi**

**Comment by rubencdelgado** [comment]
Hi @jalaliskandar. Additional details for implementing the IPaymentProcessor interface can be found in the whitepaper located here: https://download.microsoft.com/download/e/2/7/e2735c65-1e66-4b8d-8a3c-e6ef3a319137/The%20Guide%20to%20Implementing%20Payment%20Connector%20and%20Payment%20Device_update.pdf

Please email rubendel@microsoft.com and I will send an additional sample to help unblock you. Thanks!
