### ISSUE TITLE
Question regarding default development tool - VS 2017

### ISSUE THREAD

**Issue by DShukvaniProdware** [MicrosoftDocs/dynamics-365-unified-operations-public#2547]
I have a simple question, can VS 2017 be used for development of D365 FO?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3f86106-3c9a-21ce-421e-45d6520338bc
* Version Independent ID: add7e8ab-d635-a2f1-28d6-a21e95961f20
* Content: [Development tools in Visual Studio - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/development-tools-overview)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/development-tools-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-tools/development-tools-overview.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @jorisdg
* Microsoft Alias: **jorisde**

**Comment by tonyafehr** [comment]
@jorisdg, please review. Thanks!

**Comment by jorisdg** [comment]
Glad you asked! :-)

https://community.dynamics.com/365/financeandoperations/b/newdynamicsax/posts/action-required---net-version-and-visual-studio-2017

**Comment by jorisdg** [comment]
Replied. Please close.
