### ISSUE TITLE
Inconsistent documentation

### ISSUE THREAD

**Issue by jopankow** [MicrosoftDocs/dynamics-365-unified-operations-public#2548]
Inconsistent documentation in the following section:

Restore is denied for environments that run **Platform update 20 or earlier**
The restore database process cannot be completed if the environment is running **Platform update 3 or earlier**. For more information, see the list of currently supported Platform updates.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 805f3739-0cad-d6ab-7db0-175c972f189f
* Version Independent ID: 68be2d28-d5e9-471d-8648-a8cbae2e1e7d
* Content: [Database point-in-time restore (PITR) - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/database-point-in-time-restore)
* Content Source: [articles/fin-ops-core/dev-itpro/database/database-point-in-time-restore.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/database/database-point-in-time-restore.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laneswenka**

**Comment by tonyafehr** [comment]
@jopankow, thank you for the feedback. 
@laneswenka, please review.

**Comment by tonyafehr** [comment]
Bug #467895 logged to track this issue.
