### ISSUE TITLE
Page is outdated and generally needs refreshing

### ISSUE THREAD

**Issue by miham-aib** [MicrosoftDocs/dynamics-365-unified-operations-public#2549]
Several references on the page are outdated, and for example the service updates section doesn't go beyond PU32.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6d8ca90-dfbd-3698-0def-a3be85e9c850
* Version Independent ID: b8d5a864-57fb-9fc3-f36a-77c5f5c58a54
* Content: [Software lifecycle policy and cloud releases - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/versions-update-policy?toc=/dynamics365/commerce/toc.json)
* Content Source: [articles/fin-ops-core/dev-itpro/migration-upgrade/versions-update-policy.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/migration-upgrade/versions-update-policy.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RyanCCarlson2
* Microsoft Alias: **rcarlson**

**Comment by sericks007** [comment]
@miham-aib, thank you for making us aware of this issue.

@ShellyBakke, please update the content.

**Comment by sericks007** [comment]
Bug 468191 has been logged to track this issue.
