### ISSUE TITLE
Hyper-V Only Support

### ISSUE THREAD

**Issue by tomhig** [MicrosoftDocs/dynamics-365-unified-operations-public#255]
There is no mention in this article that Hyper-V is the supported virtualization configuration and really should be since this article is on System Requirements. This fact is indeed mentioned in the following article: https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/deployment/setup-deploy-on-premises-pu12#infrastructure

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48d2efea-f165-1f9b-ffdc-85c91f1f6c9a
* Version Independent ID: 950f0392-7d17-3188-ecd9-52b61bb61b32
* Content: [System requirements for on-premises deployments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/system-requirements-on-prem?toc=/dev-itpro/toc.json)
* Content Source: [articles/fin-and-ops/get-started/system-requirements-on-prem.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/system-requirements-on-prem.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @kfend
* Microsoft Alias: **kfend**

**Comment by cdz1126** [comment]
The latest version of Finance and Operations (on-premises) has included the Retail components, please update the system requirement

**Comment by sericks007** [comment]
@cdz1126, thanks for making us aware of that issue.

@AamirAllaq or @jashanno, can you please update this topic to add the Retail system requirements.
