### ISSUE TITLE
Unclear documentation

### ISSUE THREAD

**Issue by ramakrishnreddy** [MicrosoftDocs/dynamics-365-unified-operations-public#2550]
[Enter feedback here]
The point number 19 under "Design the format of an electronic document" is unclear. Also the rest of the steps as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfc51f70-ac31-3534-1ddb-6a1fa4308c80
* Version Independent ID: ee84e41d-abaa-069f-772e-046d9b586898
* Content: [Design ER configurations to fill in PDF templates - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/er-fillable-pdf?toc=/dynamics365/commerce/toc.json)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/er-fillable-pdf.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/er-fillable-pdf.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @NickSelin
* Microsoft Alias: **nselin**

**Comment by tonyafehr** [comment]
@ramakrishnreddy, can you provide more details as to what you feel is unclear in step 19, which states "Continue to design this format by importing the second PDF template, adding necessary bindings to data sources". Also, please identify what other steps need additional info. Thank you!
