### ISSUE TITLE
Wrong menu path described

### ISSUE THREAD

**Issue by brkyyldz** [MicrosoftDocs/dynamics-365-unified-operations-public#2551]
[Enter feedback here]
In document it is written as below;
Use the menu on the left to go to Modules > Retail and commerce > Headquarters setup > **Retail** scheduler > Channel database.
But it should be as below;
Use the menu on the left to go to Modules > Retail and commerce > Headquarters setup > **Commmerce** scheduler > Channel database.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67d6e0ac-7a61-78c4-cf4b-dd26a218f7bc
* Version Independent ID: f3ec5780-fe76-7ce2-cd2b-d2aec7877323
* Content: [Configure a Dynamics 365 Commerce preview environment - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/cpe-post-provisioning)
* Content Source: [articles/commerce/cpe-post-provisioning.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/cpe-post-provisioning.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @psimolin
* Microsoft Alias: **psimolin**

**Comment by josaw1** [comment]
Thank you for your feedback. We will fix this soon.
