### ISSUE TITLE
Unable to find "Business document management" on feature management page

### ISSUE THREAD

**Issue by artemt1** [MicrosoftDocs/dynamics-365-unified-operations-public#2552]
"Enable Business document management" seems outdated. 

Currently the web page says:
----------------------------------------------------
To start Business document management, you need to open the Feature management workspace and enable the Business document management feature.

Use the following procedure to enable Business document management functionality for all legal entities.

Open the Feature management workspace.
On the New tab, select the Business document management feature in the list.
Select Enable now to turn on the selected feature.
Refresh the page to access the new feature.
----------------------------------------------------

However, on Update35 there are not feature called "Business document management"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c9d868b-2b3b-26c9-f8ff-863e6f8cd9d4
* Version Independent ID: 9ea7a0a4-99ab-aca8-ca48-62ee8c02a92b
* Content: [Business document management overview - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/er-business-document-management#configure-er-parameters)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/er-business-document-management.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/er-business-document-management.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @NickSelin
* Microsoft Alias: **nselin**

**Comment by josaw1** [comment]
Thank you for your feedback. @NickSelin can you please take a look?

**Comment by josaw1** [comment]
@NickSelin, BUG 469227 created to track the issue.

**Comment by NickSelin** [comment]
@artemt1, can you click the **Check for updates** button to refresh the list of available features and make the **Business document management** feature available for enabling as described in the [Feature management overview](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/feature-management/feature-management-overview#check-for-updates) topic? Thank you!
