### ISSUE TITLE
Unable to find "Business document parameters" in main menu, only via search

### ISSUE THREAD

**Issue by artemt1** [MicrosoftDocs/dynamics-365-unified-operations-public#2553]
Currently web page says:
---------------------------------------
Use the following procedure to set up the basic parameters for all legal entities.

Sign in as a user with access to the Business document parameters page.
Go to Organization administration > Electronic reporting > Business document management > Business document parameters.
---------------------------------------

On Update35, the path "Organization administration > Electronic reporting > Business document management > Business document parameters" does not exists.

I could still find "Business document parameters" form via Search option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c9d868b-2b3b-26c9-f8ff-863e6f8cd9d4
* Version Independent ID: 9ea7a0a4-99ab-aca8-ca48-62ee8c02a92b
* Content: [Business document management overview - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/er-business-document-management#configure-er-parameters)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/er-business-document-management.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/er-business-document-management.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @NickSelin
* Microsoft Alias: **nselin**

**Comment by josaw1** [comment]
Thank you for your comment. @NickSelin can you please review?

**Comment by josaw1** [comment]
@NickSelin, bug 469227 created to track the issue.

**Comment by NickSelin** [comment]
@artemt1, you need to enable the **Business document management** feature in the [Feature management](https://docs.microsoft.com/dynamics365/fin-ops-core/fin-ops/get-started/feature-management/feature-management-overview#check-for-updates) workspace to see the **Business document parameters** menu item in the main menu. Thank you!
