### ISSUE TITLE
Business Event Extension.  New payload in catalog.

### ISSUE THREAD

**Issue by nspiteri** [MicrosoftDocs/dynamics-365-unified-operations-public#2554]
[Enter feedback here]
In the section about extending an existing contract.  Once a contract is extended, the Business Event will have the new payload when it runs, but it will still show the old payload in the Catalog and when it is downloaded.

This is because the decorator for the contract is on the extended class and not on the extension.  If I put the decorator on the extension, it becomes a new business event.

Is there way to fix this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11811157-3f2d-56d5-07d4-0f44ab2c9370
* Version Independent ID: 5bc47a47-4d27-aaf5-750f-72b47bb39fe1
* Content: [Business events developer documentation - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/business-events/business-events-dev-doc)
* Content Source: [articles/fin-ops-core/dev-itpro/business-events/business-events-dev-doc.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/business-events/business-events-dev-doc.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by josaw1** [comment]
Thank you for your question. @Sunil-Garg can you please take a look?

**Comment by josaw1** [comment]
BUG 469235 created to track the issue.

**Comment by Sunil-Garg** [comment]
@nspiteri -- we have taken this as a bug and will investigate. Thanks.
