### ISSUE TITLE
API to get the list of execution errors for Composite data entity

### ISSUE THREAD

**Issue by ripannandy** [MicrosoftDocs/dynamics-365-unified-operations-public#2555]
POST /data/DataManagementDefinitionGroups/Microsoft.Dynamics.DataEntities.GetExecutionErrors
BODY
{"executionId":"<executionId>"}

This API works fine for simple entity. But how to get the same output for composite data entity. While trying to use this API for composite entity, it's returning the below error

{
  "error": {
    "code": "",
    "message": "An error has occurred.",
    "innererror": {
      "message": "Exception occurred while executing action GetExecutionErrors on Entity DataManagementDefinitionGroup: Object reference not set to an instance of an object.",
      "type": "System.InvalidOperationException",
      "stacktrace": "   at Microsoft.Dynamics.Platform.Integration.Services.OData.Action.ActionInvokable.Invoke()\r\n   at Microsoft.Dynamics.Platform.Integration.Services.OData.Update.UpdateProcessor.ActionInvocation(ChangeOperationContext context, ActionInvokable action)\r\n   at Microsoft.Dynamics.Platform.Integration.Services.OData.Update.UpdateManager.<>c__DisplayClass14_0.<ScheduleInvokable>b__0(ChangeOperationContext context)\r\n   at Microsoft.Dynamics.Platform.Integration.Services.OData.Update.ChangeInfo.ExecuteActionsInCompanyContext(IEnumerable`1 actionList, ChangeOperationContext operationContext)\r\n   at Microsoft.Dynamics.Platform.Integration.Services.OData.Update.ChangeInfo.ExecuteActions(ChangeOperationContext context)\r\n   at Microsoft.Dynamics.Platform.Integration.Services.OData.Update.UpdateManager.SaveChanges()\r\n   at Microsoft.Dynamics.Platform.Integration.Services.OData.AxODataDelegatingHandler.<SaveChangesAsync>d__3.MoveNext()"
    }
  }
}
How to fix this issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01b2cd6b-f885-7461-fbdf-cf81f9e50d86
* Version Independent ID: 8df7a6ae-67db-5d29-fb6a-0820704ff3ef
* Content: [Recurring integrations - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/recurring-integrations?source=docs)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/recurring-integrations.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/recurring-integrations.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by josaw1** [comment]
Thanks for your comment. @Sunil-Garg can you please review?

**Comment by josaw1** [comment]
BUG 469237 created to track this issue.

**Comment by Sunil-Garg** [comment]
@ripannandy-- thanks for highlighting this issue. We are investigating if we can enable this API for composite entities as well. Thanks.

**Comment by Sunil-Garg** [comment]
@ripannandy -- quick update-- this is fixed in PU38.
