### ISSUE TITLE
View the import file that is pushed to D365 data mangement framework

### ISSUE THREAD

**Issue by sbaber82** [MicrosoftDocs/dynamics-365-unified-operations-public#2557]
Is it possible to view the XML message sent from external application to D365 import package setup using composite entity. In case if there are any errors, there is no way to view the XML message that was sent like we had in AX 2012. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01b2cd6b-f885-7461-fbdf-cf81f9e50d86
* Version Independent ID: 8df7a6ae-67db-5d29-fb6a-0820704ff3ef
* Content: [Recurring integrations - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/recurring-integrations)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/recurring-integrations.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/recurring-integrations.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by kfend** [comment]
@sbaber82 - Thanks for the question.
@Sunil-Garg - Can you answer this?

**Comment by Sunil-Garg** [comment]
@sababer82 -- can you share use cases where you were unable to debug? Once we understand the gaps, we can investigate further to fill those to enable troubleshooting in those cases. Thanks.

**Comment by sbaber82** [comment]
Hi Sunil,

Thanks for your response. I am not after debugging, as I can look at the errors by clicking on Manage messages button. Sometimes, the error is due to the format of the XML file that was sent to D365 from external application. If I can view the XML and able to download it, then I can fix the formatting error and then resubmit the message using Postman. But, currently, I have to email customer to send me the XML message that was failed to process in D365, so that I can resubmit. Hope this makes sense.

Please let me know if you need further clarification.

**Comment by Sunil-Garg** [comment]
Thanks for following up.

Good to know that you are able to view the errors in manage messages. As for XML errors, we have improved on XML error messages to be more precise. We would like to invest in improved error messages than add any functionality to download the original file as that could have security implications.

Can you share specific XML errors that were not clear? We can look at enhancing those.

Thanks again.

**Comment by sbaber82** [comment]
HI Sunil,

As we are using a custom composite entity, the errors are very specific to the structure of that entity.  There is one field inside the datasource within the composite entity, that is required despite it has some value or not. When the value for that specific field is not there in the message, external application is not passing that XML tag in the message, hence D365 gives formatting error in that case and message failed to process. I have recently added transformation file in D365 data project to add the tag conditionally to avoid this error. Hope this makes sense. 

The advantage of downloading and view the XML message coming from external sources is that, if you want to resubmit the message in case of any errors, you can do that yourself without requesting external parties to send you the XML. Hope you understand my point.
