### ISSUE TITLE
PowerShell line misses a line break

### ISSUE THREAD

**Issue by milivojevic** [MicrosoftDocs/dynamics-365-unified-operations-public#2558]
The following snippet is not correct (and the worse part is that it fails silently):

For each application that needs to be added, run the following commands to add the application to the Azure Active Directory.

`Connect-AzureAD New-AzureADServicePrincipal –AppId <AppId>`

It should be written as

```
Connect-AzureAD
New-AzureADServicePrincipal –AppId <AppId>
```

On top of it, when we are in the Azure Portal, clicking the Azure Shell icon is a faster way to get to the AzureAD PowerShell environment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c84e15d4-bcac-038a-2b1e-8c456ee25bd9
* Version Independent ID: 478b5f33-f745-1df2-8fe0-da9e64233165
* Content: [Configure export to Azure Data Lake - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/configure-export-data-lake#createsubscription)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/configure-export-data-lake.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/configure-export-data-lake.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by kfend** [comment]
@milivojevic - Thank you for the feedback.
@MilindaV2 - Can you please take a look at and address this comment?

**Comment by MilindaV2** [comment]
Thank you for the feedback

**Comment by kfend** [comment]
Closing as the topic has been updated.
