### ISSUE TITLE
Missing Steps @ Taking screenshots in Task recorder

### ISSUE THREAD

**Issue by EduardoVizcarra** [MicrosoftDocs/dynamics-365-unified-operations-public#2561]
At step 8. Browse to the folder that contains the Task recorder extension, select the folder, and then click OK.

Can be changed to this step description **8. Browse to the folder that contains the Task recorder extension, select the folder using this path FMLab-master > FMLab > TaskRecorderScreenshot, and then click "Select Folder".**

![image](https://user-images.githubusercontent.com/67812834/86503583-25ba2180-bd75-11ea-9236-305ffa6efd7e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5762f9e-d7f4-e7fc-49c7-6db64c01bc6a
* Version Independent ID: 2aab18ad-f2f1-c0ad-c109-38806c8491a3
* Content: [Task recorder resources - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/user-interface/task-recorder#taking-screenshots-in-task-recorder)
* Content Source: [articles/fin-ops-core/dev-itpro/user-interface/task-recorder.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/user-interface/task-recorder.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by tonyafehr** [comment]
@EduardoVizcarra, thanks for the feedback. 
@jasongre, please review.

**Comment by tonyafehr** [comment]
Bug #470083 logged to track this issue.

**Comment by jasongre** [comment]
Thanks for the suggested change! It should be available with the next round of publishing of this article.

**Comment by tonyafehr** [comment]
We expect that the updated topic will be published at the end of the July 2020. Thanks!

**Comment by EduardoVizcarra** [comment]
Thank you, I’m glad to help.

Enviado desde mi iPhone

El jul. 15, 2020, a la(s) 3:45 p. m., Tonya Fehr <notifications@github.com> escribió:

﻿

Closed #2561<https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/issues/2561>.
