### ISSUE TITLE
How to REMOVE / UPGRADE Best Practice Rules in Visual Studio?

### ISSUE THREAD

**Issue by DanielRisman** [MicrosoftDocs/dynamics-365-unified-operations-public#2562]
I just tested to add my own Best Practice Rules to Visual Studio using these instructions:
https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/author-best-practice-rules

How do I REMOVE (not only uncheck) the rules once installed?
(There is no UnInstall-button - only Install.)

Reason:
A, I want to clean up the system, having choosen a stupid name for the test-version. :-)

B, If I upgrade the rules, I can´t install the new version since "it already exists". It does not help to delete old DLL. I can rename the new DLL (and the classes within, to avoid duplicates), but the system vill get messier and messier for each new version. :-(

   Best Regards,

   / Daniel Risman

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68a08e21-dcff-f7be-1173-59496cef4038
* Version Independent ID: 4b1dc605-701d-151f-11f5-d8eb9cc8ae19
* Content: [Write best practice rules - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/author-best-practice-rules)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/author-best-practice-rules.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-tools/author-best-practice-rules.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @pvillads
* Microsoft Alias: **pvillads**

**Comment by tonyafehr** [comment]
@pvillads, please review.

**Comment by tonyafehr** [comment]
Bug #470084 logged to track this issue.

**Comment by DanielRisman** [comment]
Hello,
Just wanted you to know that I’ve found a working ”work-around”. I just have to close down Visual Studio and manually delete the old DLL from:
K:\AosService\PackagesLocalDirectory\bin\BPExtensions\
(Still it would have been nice to both install AND uninstall Best Practice-DLL:s from inside Visual Studio.)

Med vänliga hälsningar / Best regards

Daniel Risman

+46 73-629 09 01  Daniel.Risman@orango.se
Hornsgatan 174  SE-117 34 Stockholm

[cid:image005.png@01D65A21.6B718270]<http://www.orango.se/>
Från: Tonya Fehr <notifications@github.com>
Skickat: den 14 juli 2020 16:03
Till: MicrosoftDocs/dynamics-365-unified-operations-public <dynamics-365-unified-operations-public@noreply.github.com>
Kopia: Daniel Risman <Daniel.Risman@orango.se>; Author <author@noreply.github.com>
Ämne: Re: [MicrosoftDocs/dynamics-365-unified-operations-public] How to REMOVE / UPGRADE Best Practice Rules in Visual Studio? (#2562)


Bug #470084 logged to track this issue.

**Comment by tonyafehr** [comment]
Thanks for the update.
