### ISSUE TITLE
Documentation describes obsoleted call

### ISSUE THREAD

**Issue by michaelmesdag** [MicrosoftDocs/dynamics-365-unified-operations-public#2566]
The SysDaSearchStatement.next() call has been obsoleted for SysDaSearchStatement.findNext()

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2888e11c-17de-f90c-a48e-409baee04833
* Version Independent ID: b6f71c61-469e-46d8-9a7f-7cc5da547850
* Content: [Access data by using the SysDa classes - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-ref/sysda)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-ref/sysda.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-ref/sysda.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **rhaertle**

**Comment by tonyafehr** [comment]
@michaelmesdag, thanks for the feedback. 
@RobinARH, please review.

**Comment by tonyafehr** [comment]
Bug #470085 logged to track this issue.

**Comment by RobinARH** [comment]
I updated this doc, and the updated doc should go live this evening.
