### ISSUE TITLE
Not right Path

### ISSUE THREAD

**Issue by adinglee** [MicrosoftDocs/dynamics-365-unified-operations-public#2570]
[Enter feedback here]
Should this page be under of Globalization | Italy other than current path:D365 Finance | Account Receivable | Advance Notes Management? Because I think it is a localization feature of Italy. User might be confused that the function is general available function.
![image](https://user-images.githubusercontent.com/31424213/86834891-06671100-c061-11ea-9a48-3d88a00f62b0.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebe75f4e-4978-753a-3f96-1adf311c5f68
* Version Independent ID: 056150a1-5a31-8a94-0f36-39b64c53373b
* Content: [Advanced notes management - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/emea-ita-exil-structured-notes?source=docs#feedback)
* Content Source: [articles/finance/localizations/emea-ita-exil-structured-notes.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/localizations/emea-ita-exil-structured-notes.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @ilkond
* Microsoft Alias: **ilyako**

**Comment by tonyafehr** [comment]
@kfend, please review.
