### ISSUE TITLE
model file access

### ISSUE THREAD

**Issue by marilehis** [MicrosoftDocs/dynamics-365-unified-operations-public#2572]
Can not access file 1099model.xml on https://go.microsoft.com/fwlink/?linkid=852550
It requires partner credentials, other files are available for download without signing in to partner source.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5256385e-3b72-727c-43ef-9836adcb08c0
* Version Independent ID: 9fb0a749-b150-5607-3101-27c8795a7f09
* Content: [ER Create required configurations to import data from an external file - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/tasks/er-required-configurations-import-data?toc=/dynamics365/commerce/toc.json)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/tasks/er-required-configurations-import-data.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/tasks/er-required-configurations-import-data.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @NickSelin
* Microsoft Alias: **nselin**

**Comment by josaw1** [comment]
Thanks for your feedback. @NickSelin can you please take a look?

**Comment by josaw1** [comment]
BUG 471711 created to track.

**Comment by kfend** [comment]
Hi, this has been fixed. All of the files are now available to download without a log in.
