### ISSUE TITLE
ISV Dynamics 365/Power Apps solution

### ISSUE THREAD

**Issue by malkhawaja** [MicrosoftDocs/dynamics-365-unified-operations-public#2573]
Hi,
does this document apply also to Dynamics CE/Power Apps solutions? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69192df7-736f-1504-e8ab-d1ececb95800
* Version Independent ID: 7707373e-0ef6-ac6b-fcce-efce6a0ade73
* Content: [Independent software vendor (ISV) licensing - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/isv-licensing)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/isv-licensing.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-tools/isv-licensing.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @jorisdg
* Microsoft Alias: **jorisde**

**Comment by kfend** [comment]
Thanks for the question, @malkhawaja. I spoke with the author and the topic only applies to Dynamics 365 Finance and Operations apps. It doesn't apply to either of the apps you are asking about.
