### ISSUE TITLE
Contract within a contract UI needs to be improved

### ISSUE THREAD

**Issue by nspiteri** [MicrosoftDocs/dynamics-365-unified-operations-public#2577]
[Enter feedback here]
I have some business events for a table/line structure.  I've developed a contract with a child contract.

This works fine.  However it would be nice if in the UI and preview I can also also see the parent/child relationship.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11811157-3f2d-56d5-07d4-0f44ab2c9370
* Version Independent ID: 5bc47a47-4d27-aaf5-750f-72b47bb39fe1
* Content: [Business events developer documentation - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/business-events/business-events-dev-doc)
* Content Source: [articles/fin-ops-core/dev-itpro/business-events/business-events-dev-doc.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/business-events/business-events-dev-doc.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by roschlom** [comment]
Bug 565969 has been opened to track this.
