### ISSUE TITLE
Functionality Italian specific

### ISSUE THREAD

**Issue by MarkElenbaas** [MicrosoftDocs/dynamics-365-unified-operations-public#2578]
Where can I see if this functionality is still Italian specific?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebe75f4e-4978-753a-3f96-1adf311c5f68
* Version Independent ID: 056150a1-5a31-8a94-0f36-39b64c53373b
* Content: [Advanced notes management - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/emea-ita-exil-structured-notes)
* Content Source: [articles/finance/localizations/emea-ita-exil-structured-notes.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/localizations/emea-ita-exil-structured-notes.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @ilkond
* Microsoft Alias: **ilyako**

**Comment by ilkond** [comment]
This functionality was extended for all countries (staring from version 10.0.13).
The article was re-located to Accounts receivable (the last item):
![image](https://user-images.githubusercontent.com/27193524/87869075-443f3000-c9a5-11ea-8d26-13ae424ec6f1.png)
