### ISSUE TITLE
Table groups > table properties #253 [reopen]

### ISSUE THREAD

**Issue by ibruynin** [MicrosoftDocs/dynamics-365-unified-operations-public#258]
Hi @ShylaThompson / @kfend 

I'd like to reopen the issue (cfr. comments below)

Kind regards
--

## initial issue (#253 )
The link to "Table Groups" in this page refers to the AX 2012 values.
In D365FO the following are added:

    Reference
    Worksheet
    TransactionHeader
    TransactionLine
    Staging
    These properties are currently not documented as far as I can see.

## reply (resolved/closed)
@ibruynin, the lifecycle services topic is an AX 2012 topic, so this is by design.

## Comment to reopen the issue
@ShylaThompson Thanks for the quick reply.
Are there any plans to document this for Dynamics 365?
Or am I looking in the wrong place?
These are the steps to reach the page in question:

    docs.microsoft.com > Dynamics 365
    https://docs.microsoft.com/en-us/dynamics365/
    Search for "table properties"
    https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/ax-2012/table-properties
    Click "Table Groups"
    https://msdn.microsoft.com/library/3330d438-ab53-44db-9a9b-a044ed19608d(AX.60).aspx

**Comment by ShylaThompson** [comment]
@ibruynin Please see the following topics for information about tables in Microsoft Dynamics 365 for Finance and Operations.

- https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-ref/api-reference
- https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-ref/system-tables

Also, you can get a list of tables and more from the Technical reference reports which you can download from here:  https://mbs.microsoft.com/customersource/northamerica/AX/downloads/reports/axtechrefrep 

The reports included in the download are:

- Aggregate data entities​ ​
- Aggregate measures
- Configuration key groups ​​
- Configuration keys
- Data entities​
- Data entity fields
- Key performance indicators (KPIs)
- License codes
- Menu items
- SQL Server Reporting Services reports
- Tables
- Workflow types

**Comment by ibruynin** [comment]
![image](https://user-images.githubusercontent.com/15861800/42909205-97b3c474-8ae3-11e8-96eb-4808bdb2eb1e.png)

I hope this clarifies things...

I'm looking for the description of the values (that are added in Dynamics 365 FO) in the "Table group" field in the meta data in Visual Studio.
The current page only describes the fields available in AX 2012.

**Comment by ShylaThompson** [comment]
@ibruynin Thanks for providing more information. I've created a content deliverable for this work, but there is no ETA for when the content will be completed.

**Comment by ShylaThompson** [comment]
Content deliverable: 232415

**Comment by ibruynin** [comment]
@ShylaThompson Where can we find updates on that content deliverable?

We made an overview of the different properties in that metadata parameter.
Can someone confirm this is a correct interpretation?

![image](https://user-images.githubusercontent.com/15861800/45081001-74092580-b0f6-11e8-8ba4-32213302e888.png)
