### ISSUE TITLE
Outdated Link to Video

### ISSUE THREAD

**Issue by PeterGuth** [MicrosoftDocs/dynamics-365-unified-operations-public#2580]
Please correct the link to the video about branches. The current link is pointing to mbspartner, which only displays a message.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55c7ea05-69b5-1c5e-eb55-07066a1b2d17
* Version Independent ID: b75e9d43-6590-60bd-ca34-83c40abd9ae6
* Content: [Set up new environments, Azure DevOps, and branches for Commerce projects - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/new-environments-visual-studio-teams-branch-retail-projects)
* Content Source: [articles/commerce/dev-itpro/new-environments-visual-studio-teams-branch-retail-projects.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/dev-itpro/new-environments-visual-studio-teams-branch-retail-projects.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @AndreasHassing
* Microsoft Alias: **andreash**

**Comment by sericks007** [comment]
@PeterGuth, thanks for letting us know about this!

@andreashofmann1. please correct the link.

**Comment by sericks007** [comment]
Bug 475244 has been logged to track this issue.

**Comment by sericks007** [comment]
The incorrect link has been removed.
