### ISSUE TITLE
Incorrect connection string in error message for non-US english

### ISSUE THREAD

**Issue by shashisadasivan** [MicrosoftDocs/dynamics-365-unified-operations-public#2587]
When the BYOD fails to validate because of an incorrect connection string, the error message contains the connection string. However, this string is incorrect depending on the language the user is in.
When the users language is under en-au, en-nz the error message contains the connection string with "Initial Catalogue" instead of "Initial Catalog"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33f75161-0776-a6c1-dc10-dc20ea26973f
* Version Independent ID: 55a81394-4606-745a-9fd2-59fb257d1086
* Content: [Bring your own database (BYOD) - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/export-entities-to-your-own-database)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/export-entities-to-your-own-database.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/export-entities-to-your-own-database.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by roschlom** [comment]
Thank you for your comment. We'll look into the issue.

**Comment by roschlom** [comment]
Bug 565973 was created to track this issue.
