### ISSUE TITLE
Step 3 and 4 documents missing

### ISSUE THREAD

**Issue by RutvikMehta** [MicrosoftDocs/dynamics-365-unified-operations-public#2594]
Step 3 and 4 documents missing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2226001a-87a7-f60a-18c7-3434f992750e
* Version Independent ID: 46289059-2e26-05b4-6714-f4902834f05f
* Content: [Set up bar codes - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/set-up-bar-codes)
* Content Source: [articles/commerce/set-up-bar-codes.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/set-up-bar-codes.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @jblucher
* Microsoft Alias: **jeffbl**

**Comment by sericks007** [comment]
@RutvikMehta, thanks for posting feedback here.

@jblucher, please review.

**Comment by sericks007** [comment]
Bug 475247 has been logged to track this issue.

**Comment by ashishmsft** [comment]
https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/pull/2778

@sericks007  please help publish this pull request

**Comment by ashishmsft** [comment]
For configure bar-code setups - https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/configure-bar-code-setups - I have reached out to SCM team to assist with Dynamics 365 Version of the AX 2012 document - for us to be able to refer to that document.
