### ISSUE TITLE
An unexpected client error has occured

### ISSUE THREAD

**Issue by hugginssd** [MicrosoftDocs/dynamics-365-unified-operations-public#2595]
Whenever a user logs in to the system(D365FO) he receives the error message "An unexpected client error has occurred." An suggestion to resolve this error?? All users are now at stand still and no one can process anything in the system due to this error

**Comment by sericks007** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
