### ISSUE TITLE
Revise necessary to reflect the latest X++ features

### ISSUE THREAD

**Issue by fhoo** [MicrosoftDocs/dynamics-365-unified-operations-public#260]
This document reflects the X++ language up to version AX2012. There are some new features in D365FO like variable declaration anywhere or the finaly keword that should be updated here. Also D365FO doesn't have Jobs anymore, so examples should be provided with runnable classes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d90f60ed-891b-151d-c963-522a1b0b1c17
* Version Independent ID: f9ab9cef-beda-06fb-c5c0-dce07969fbd5
* Content: [X++ and C# comparison - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-ref/xpp-cs-comparison)
* Content Source: [articles/dev-itpro/dev-ref/xpp-cs-comparison.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-ref/xpp-cs-comparison.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RobinARH
* Microsoft Alias: **robinr**

**Comment by RobinARH** [comment]
Thanks for the feedback. Updating this topic is on our todo list, but I can't say when we'll complete the work. - Robin
