### ISSUE TITLE
How do you get license files into this single package?

### ISSUE THREAD

**Issue by tclayton72** [MicrosoftDocs/dynamics-365-unified-operations-public#2601]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: feb1c10e-1287-6db3-5ed6-315cb76fc1cd
* Version Independent ID: 85966417-fa61-ffa8-22e3-fa2bfa0e50ff
* Content: [All-in-one deployable packages - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/aio-deployable-packages)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/aio-deployable-packages.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-tools/aio-deployable-packages.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by sericks007** [comment]
@tclayton72, thanks for posting here! In the meantime, to get product help you can contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

@laneswenka, please review, and consider updating the content, as necessary.

**Comment by laneswenka** [comment]
Will do

Sent from my iPhone

On Jul 15, 2020, at 2:08 PM, Sally Erickson <notifications@github.com> wrote:

﻿

Assigned #2601<https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/issues/2601> to @laneswenka<https://github.com/laneswenka>.

**Comment by sericks007** [comment]
Bug 7831269 has been logged in LCS database.

**Comment by laneswenka** [comment]
Please assign to the DevTools team as this is in regards to deployable package generation, and perhaps tasks that are available in Azure DevOps pipelines

**Comment by sericks007** [comment]
@jorisdg, can you please take a look at this.

**Comment by jorisdg** [comment]
To do this from automation in Azure DevOps, there's a task you can use:  https://docs.microsoft.com/dynamics365/fin-ops-core/dev-itpro/dev-tools/pipeline-add-license-package

I'm not sure if the licensing team has a specific article on this, but essentially to do this manually just add the license text files inside an existing deployable package, inside the folders AosService\Scripts\License
