### ISSUE TITLE
Misleading and out of date information

### ISSUE THREAD

**Issue by D365Princess** [MicrosoftDocs/dynamics-365-unified-operations-public#2603]
This documentation relating to legal entity information being bootstrapped onto entities is now out of date with the new Duel Write set up solution packages provided in GA since April and needs updating to reflect the current solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0891e384-80e8-5d40-8bde-24081e06876a
* Version Independent ID: b6ecc0cb-e827-80aa-934d-ef03d674c97e
* Content: [Bootstrap with company data FAQ - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/bootstrap-company-data)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/bootstrap-company-data.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/dual-write/bootstrap-company-data.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @RamaKrishnamoorthy
* Microsoft Alias: **ramasri**

**Comment by josaw1** [comment]
Thanks for the feedback. @RamaKrishnamoorthy can you please take a look?

**Comment by josaw1** [comment]
BUG 473607 created to track the issue.

**Comment by RamaKrishnamoorthy** [comment]
Company bootstrapping is required for initial data a CE system contains before enabling dual-write. So, this document is not out -dated. However, we are coming with more bootstrapping options and guidelines by mid August.
