### ISSUE TITLE
Incorrect response type for the Certificate part of the sample code.

### ISSUE THREAD

**Issue by Pikhulya** [MicrosoftDocs/dynamics-365-unified-operations-public#2605]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d004befc-3177-5e88-450f-d25f2cdfaaab
* Version Independent ID: a00e0c93-f128-9bb4-f0a0-8171f27678e2
* Content: [Manage secrets for retail channels - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/manage-secrets)
* Content Source: [articles/commerce/dev-itpro/manage-secrets.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/dev-itpro/manage-secrets.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @AamirAllaq
* Microsoft Alias: **aamiral**

The part of the sample demonstrating how to load the certificate contains:

`X509Certificate2 response = request.RequestContext.Execute<GetUserDefinedSecretStringValueServiceRequest>(request).Certificate;
`

which is not correct because it specifies the generic parameter belonging to the _request_ but it must be a _response_. The response must be of the type `GetUserDefinedSecretCertificateServiceResponse`.

**Comment by tonyafehr** [comment]
@Pikhulya, thanks for the feedback. 
@AamirAllaq, please review.

**Comment by tonyafehr** [comment]
Bug #474786 logged to track this issue.

**Comment by mugunthanm** [comment]
Updated the sample code in the doc.
