### ISSUE TITLE
Process deprecated - Extend CDX Real-time Service

### ISSUE THREAD

**Issue by rphillips-newestech** [MicrosoftDocs/dynamics-365-unified-operations-public#261]
The description of the process associated with extending the real-time service - see [here](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/blob/7d040f9610d80e6b31b71a8a7888159bff5ab374/articles/retail/dev-itpro/extend-commerce-data-exchange.md) - has been deprecated since fin&ops v8.0 and no longer works as described. Specifically developers are unable to extend the Application Suite. Please update to include the most recent instructions.

**Comment by ShylaThompson** [comment]
@mugunthanm I've logged bug 239521 for investigation.

**Comment by ShylaThompson** [comment]
@rphillips-newestech the topic will be updated by the end of day tomorrow.

**Comment by snowcycle** [comment]
Thank you, @ShylaThompson!

**Comment by rphillips-newestech** [comment]
Thank you, @ShylaThompson!
