### ISSUE TITLE
Missing information about Modify table properties through extension

### ISSUE THREAD

**Issue by emreceylan-tr** [MicrosoftDocs/dynamics-365-unified-operations-public#2610]
Hi everyone,

In addition to the list in the document, we can change the TitleFields, FormRef and PreviewPartRef properties. But, we can not change the Country Region Codes property. I tried by practicing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d7100fd-69cb-b4a5-f143-28984592495f
* Version Independent ID: 18a58c5d-83a6-3547-e39d-a48361bdee59
* Content: [Modify table properties through extension - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/extensibility/modify-properties)
* Content Source: [articles/fin-ops-core/dev-itpro/extensibility/modify-properties.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/extensibility/modify-properties.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @ivanv-microsoft
* Microsoft Alias: **ivanv**

**Comment by tonyafehr** [comment]
@emreceylan-tr, thanks for the feedback. 
@RobinARH, please review.

**Comment by tonyafehr** [comment]
Bug #474788 logged to track this issue.

**Comment by emreceylan-tr** [comment]
@tonyafehr @RobinARH , When I checked again, I was able to add the country region code with the extension. In this case, there is no error in the document but there is missing information. It should be added that the TitleFields, FormRef and PreviewPartRef properties can also be changed with the extension.

**Comment by RobinARH** [comment]
I updated the doc using Platform Update 41, which looks to agree with what you found, plus Tags. Should go live tonight.
