### ISSUE TITLE
Is the Export to Azure Data Lake feature for Finance and Operations apps available in either of the Canadian Data Centers?

### ISSUE THREAD

**Issue by KranthiPakala-MSFT** [MicrosoftDocs/dynamics-365-unified-operations-public#2617]
Is the "Export to Azure Data Lake feature for Finance and Operations apps" available in either of the Canadian Data Centers?
The doc info was not clear as to which data centers support this feature. Could someone please confirm on this info?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c84e15d4-bcac-038a-2b1e-8c456ee25bd9
* Version Independent ID: 478b5f33-f745-1df2-8fe0-da9e64233165
* Content: [Configure export to Azure Data Lake - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/configure-export-data-lake)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/configure-export-data-lake.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/configure-export-data-lake.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by josaw1** [comment]
Thank you for your question. @MilindaV2 can you please help?

**Comment by KranthiPakala-MSFT** [comment]
@MilindaV2 Any update on the above ask? - Thanks

**Comment by RobinARH** [comment]
Created bug 477173 to track this issue.

**Comment by MilindaV2** [comment]
We are in limited preview at this point in time. Our previews are now closed. However, we are accepting requests from customers who would like to join previews in the future. pl. ask your customer to complete the survey below if this is something interesting. https://aka.ms/FnODataLakePreviewSurvey
