### ISSUE TITLE
Extensible Data Security Framework 

### ISSUE THREAD

**Issue by tomhig** [MicrosoftDocs/dynamics-365-unified-operations-public#262]
There is little mentioned in this article about the extensible data security framework. Need a more descriptive explanation of what this is. There is a whitepaper that describes the implementation in AX 2012 at the following: https://technet.microsoft.com/en-us/library/hh272862.aspx 

There is also a blog article on this, again based on AX 2012, at the following:
https://community.dynamics.com/ax/b/dynamics101trainingcenterax/archive/2016/01/25/implementing-role-based-extensible-data-security-xds-policies-in-microsoft-dynamics-ax-2012 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13fb1d17-679e-8b93-ffbe-eaa340050068
* Version Independent ID: 3fb88067-ab44-4bfb-729b-6191ee86f4cc
* Content: [Security architecture - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/sysadmin/security-architecture)
* Content Source: [articles/dev-itpro/sysadmin/security-architecture.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/sysadmin/security-architecture.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @sarvanisathish
* Microsoft Alias: **sarvanis**

**Comment by amadse** [comment]
So when can we expect to see some proper documentation for this?

**Comment by sericks007** [comment]
@ChrisGarty, please review and update the content as needed.

**Comment by josaw1** [comment]
BUG 438327 created to track the issue.

**Comment by ChrisGarty** [comment]
The documentation at https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/security-architecture#data-security mentions that record-level security was replaced by XDS (eXtensible Data Security), but, as this comment notes, there doesn't seem to be any documentation for XDS. I believe that @ParAkerblom is looking after the security space, so unfortunately I'm passing this hot potato on.
@sericks007 or @josaw1 , can you adjust the assignment?

**Comment by ChrisGarty** [comment]
Assigned 438327 to Par and moved to the FinOps\CDS\Storage\DataEngine\Authorization\XDS node

**Comment by sericks007** [comment]
@Peakerbl, this issue has been assigned to you. Please review and update the content as needed.
