### ISSUE TITLE
Descriptions are incorrect

### ISSUE THREAD

**Issue by WassupPavan** [MicrosoftDocs/dynamics-365-unified-operations-public#2621]
Description for below sections are same:
1. View your team calendar as an employee
2. View your team calendar as a manger 

Both menus are different.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21eca941-991c-da93-2f69-92d402ded710
* Version Independent ID: efcbb23f-40a7-0a38-7066-ed79e14d41ae
* Content: [Create a team calendar - Human Resources | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/human-resources/hr-employee-self-service-calendar)
* Content Source: [articles/human-resources/hr-employee-self-service-calendar.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/human-resources/hr-employee-self-service-calendar.md)
* Service: **dynamics-human-resources**
* Product: ****
* Technology: ****
* GitHub Login: @andreabichsel
* Microsoft Alias: **anbichse**

**Comment by tonyafehr** [comment]
@WassupPavan, thanks for the feedback. 
@andreabichsel, please review.

**Comment by andreabichsel** [comment]
Thank you for catching this! I updated the doc and the changes should go live a little later today.
