### ISSUE TITLE
Project timesheets are not part of D365 Human Resources

### ISSUE THREAD

**Issue by WassupPavan** [MicrosoftDocs/dynamics-365-unified-operations-public#2622]
Project timesheets are part of D365 finance and operations. There no information on integrations too,
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0951be8-3d1d-e72d-5962-4c4a11160a7e
* Version Independent ID: 71afcf21-d51e-7df5-ffc4-436d1dde8142
* Content: [Enter project timesheets - Human Resources | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/human-resources/hr-personnel-enter-project-timesheets)
* Content Source: [articles/human-resources/hr-personnel-enter-project-timesheets.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/human-resources/hr-personnel-enter-project-timesheets.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @andreabichsel
* Microsoft Alias: **anbichse**

**Comment by tonyafehr** [comment]
@WassupPavan, thanks for the feedback. 
@andreabichsel, please review.

**Comment by andreabichsel** [comment]
Thank you for catching this! I updated the doc and the changes should go live a little later today.

**Comment by andreabichsel** [comment]
Sorry, I responded to the wrong item. This issue is still open.

**Comment by RobinARH** [comment]
Bug 477174 created to track this issue.
