### ISSUE TITLE
the description in "How to I use the code sample?" does not provide clear view of how to run sample code. please elaborate.

### ISSUE THREAD

**Issue by Izmiyash** [MicrosoftDocs/dynamics-365-unified-operations-public#2623]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0891e384-80e8-5d40-8bde-24081e06876a
* Version Independent ID: b6ecc0cb-e827-80aa-934d-ef03d674c97e
* Content: [Bootstrap with company data FAQ - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/bootstrap-company-data)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/bootstrap-company-data.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/dual-write/bootstrap-company-data.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @RamaKrishnamoorthy
* Microsoft Alias: **ramasri**

**Comment by tonyafehr** [comment]
@RamaKrishnamoorthy, please review and if needed, make updates about how to use the code sample. Thanks!

**Comment by RamaKrishnamoorthy** [comment]
The code sample is just the contents of a .cs file. You need to be familiar with C# to use the code sample. Please use the guideline provided here (https://docs.microsoft.com/en-us/visualstudio/ide/quickstart-csharp-console?view=vs-2019) to create a C# console app and then copy paste the sample code in to the .cs file of the console app. Hope this helps!

**Comment by Izmiyash** [comment]
your comment and existing description "After unzipping and opening the solution in Visual Studio" is not consistent. What you are saying is not using any zipped solution.

**Comment by RobinARH** [comment]
Bug 477175 created to track this issue.

**Comment by RobinARH** [comment]
We have replaced the topic with a no-code solution. -Robin
