### ISSUE TITLE
Labels metadata example URL does not work

### ISSUE THREAD

**Issue by mattiferg** [MicrosoftDocs/dynamics-365-unified-operations-public#2624]
The example URL for the labels API does not work. It appears to be using a made up label:

`https://[baseURI\]/metadata/Labels(Id='@SVC\_ODataLabelFile:Label1',Language='en-us')`

None of the components of the URL, ("_@SVC_", "__ODataLabelFile_", "_Label1_"(, are explained, so finding appropriate substitutions is difficult.

Please change the example to something that will fetch a label that actually does exist in the base product.

eg.
How do I get the label that I would get if I used the "**@ApplicationPlatform:EmptyFileName**" markup from *x++*?
If I had that example, then I would expect the URL to contain "ApplicationPlatform" and "EmptyFileName", which I would then be able to substitute for my own label details.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 133cc363-a550-5cbf-622a-f0bd3da87eb6
* Version Independent ID: a7b1ce5d-ba20-b723-e3b0-23a9b79cde9d
* Content: [Service endpoints overview - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/services-home-page)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/services-home-page.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/services-home-page.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by tonyafehr** [comment]
@mattiferg, thanks for the feedback. 
@Sunil-Garg, please review.

**Comment by tonyafehr** [comment]
Bug #477428 logged to track this issue.
