### ISSUE TITLE
CI/CD - release to LCS and deployment

### ISSUE THREAD

**Issue by Halldor10** [MicrosoftDocs/dynamics-365-unified-operations-public#2629]
Thanks for this document. It's a good start. Maybe you should consider to change or remove the first image as does not contain the same tasks as in the other images for the pipline, shown in this documentation. 

One thing I find really missing is a another document for the "Release" part of the CI/CD that describes the upload of the artifacts to LCS and deployment to different environments and how to handle LCS 300 MB limitation and reduce the size for RSCU before deployment in a automatic way (see ["Deploy the deployable packes"](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/retail-sdk/retail-sdk-packaging) documentation.

A simple "Release" to Dev, with approvers to release to Test, as an example, should be enough.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd465bf3-be18-a1ac-76d1-23dc8ff06ea4
* Version Independent ID: f8c4ea31-1332-763b-ab5e-d5e7197f8a5f
* Content: [Set up Commerce SDK build pipeline - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/retail-sdk/sdk-build-pipeline)
* Content Source: [articles/commerce/dev-itpro/retail-sdk/SDK-build-pipeline.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/dev-itpro/retail-sdk/SDK-build-pipeline.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by tonyafehr** [comment]
@Halldor10, thanks for the feedback.
@mugunthanm, please review.

**Comment by mugunthanm** [comment]
Thanks for the feedback, removed the image for now.

300 MB was a recent bug in the product which increased the package size, hotfix released to fix that issue.

Soon we will update this document with the release pipeline to LCS.
