### ISSUE TITLE
Customer and Vendor sales tax direction diagrams inconsistent with descriptions

### ISSUE THREAD

**Issue by MartinWalkerDynSA** [MicrosoftDocs/dynamics-365-unified-operations-public#2631]
The descriptions and corresponding diagrams for Customer and Vendor sales tax direction appear to be in conflict, i.e. for some scenarios the descriptions and diagrams provide the opposite result for the sales tax direction.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3aaea6b3-d996-eb5c-0a4e-82454d5a1bf0
* Version Independent ID: 523a07d8-d3b5-eba1-4a5d-f5c6c3f90448
* Content: [Sales tax calculation on general journal lines - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/general-ledger/sales-tax-calculation-on-general-journal)
* Content Source: [articles/finance/general-ledger/sales-tax-calculation-on-general-journal.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/general-ledger/sales-tax-calculation-on-general-journal.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @ericwang
* Microsoft Alias: **vstehman**

**Comment by tonyafehr** [comment]
@MartinWalkerDynSA, thanks for the feedback. 
@rschloma, please review.

**Comment by tonyafehr** [comment]
Bug #477429 logged to track this issue.

**Comment by tonyafehr** [comment]
This topic will be updated today. Thank you!
