### ISSUE TITLE
Using 10.0.11 CONTOSO, I cannot configure as in Instruction - "Set up the main account"

### ISSUE THREAD

**Issue by BernhardRaether** [MicrosoftDocs/dynamics-365-unified-operations-public#2633]
Following the instructions, I used DEMF.

Instructions are: Go to General ledger > Chart of accounts > Accounts > Main accounts.
Use the Quick Filter to find records. For example, filter on the Main account field with a value of '170150'.
In the list, click the link in the selected row.
Click Edit.
Select or clear the Require payment reference check box.
Click Save.

I can find the Main Account '170150', but the "Require payment reference check box" is not visible for me.

Has this behaviour changed since the writing of this Document?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 598d636f-acab-3386-42c5-e28a85d2e60b
* Version Independent ID: 5c300c83-a872-6569-6748-64bcacc261d5
* Content: [Set up mandatory payment references - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/tasks/set-up-mandatory-payment-references?source=docs)
* Content Source: [articles/finance/localizations/tasks/set-up-mandatory-payment-references.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/localizations/tasks/set-up-mandatory-payment-references.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @EvgenyPopovMBS
* Microsoft Alias: **epopov**

**Comment by sericks007** [comment]
@BernhardRaether, thanks for providing this feedback.

@EvgenyPopovMBS, please update the content to address this feedback.

**Comment by EvgenyPopovMBS** [comment]
@neserovleo, please look at the documentation issue.

**Comment by sericks007** [comment]
Bug 477865 has been logged to track this issue.
