### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by challengelogic** [MicrosoftDocs/dynamics-365-unified-operations-public#2641]
[Enter feedback here]

How to use Environment Monitoring View Raw Logs

Dead URL Link

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64b5b03d-9169-f94e-f999-63bc5a8e68ac
* Version Independent ID: 177eb187-6962-ba30-7a63-86b0bf3452d7
* Content: [Monitoring and diagnostics tools in Lifecycle Services (LCS) - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/monitoring-diagnostics#raw-information-logs)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/monitoring-diagnostics.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/lifecycle-services/monitoring-diagnostics.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @meeramahabala
* Microsoft Alias: **meeram**

**Comment by RobinARH** [comment]
Sally - Can you check this link? Thanks.

**Comment by sericks007** [comment]
The dead link has been removed.
