### ISSUE TITLE
Bootcamp link refers to empty web page

### ISSUE THREAD

**Issue by dodiggitydag** [MicrosoftDocs/dynamics-365-unified-operations-public#2642]
The bootcamp link takes me to a page which is empty.  Can we update the destination page, or remove the link?
https://community.dynamics.com/365/b/events?c=Upcoming%20Events/posts/dynamics-365-fasttracks-bootcamp

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bb94e99-4299-6e0f-b599-8af73c9d73e0
* Version Independent ID: 6d9c742c-1c45-f46f-3f3c-a2d4802efbc1
* Content: [Solution Architects Learning Catalog - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/learning-catalog-solution-architect)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/learning-catalog-solution-architect.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/get-started/learning-catalog-solution-architect.md)
* GitHub Login: @loreleishannonmsft
* Microsoft Alias: **v-lshann**

**Comment by RobinARH** [comment]
Margo - Can you assign this to the current author? Thanks.

**Comment by RobinARH** [comment]
Bug 482144 created to track this issue.
