### ISSUE TITLE
Dual Write System Requirements

### ISSUE THREAD

**Issue by simondudding** [MicrosoftDocs/dynamics-365-unified-operations-public#2645]
On the system requirements DOCS page for Dual Write there's a line stating - "Dual-write setup is not supported on trial instances of Finance and Operations apps". Can you clarify trial in this context please? Does a trial instance include Demo environments for F&O Partners?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cdfc828-1858-2f25-2a41-524da2577ea0
* Version Independent ID: 2955b17e-f122-1f22-5380-1e7467af71d2
* Content: [System requirements for dual-write - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/dual-write-system-req)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/dual-write-system-req.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/dual-write/dual-write-system-req.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RamaKrishnamoorthy
* Microsoft Alias: **ramasri**

**Comment by tonyafehr** [comment]
@simondudding, thanks for the feedback.
@RamaKrishnamoorthy, please review.

**Comment by tonyafehr** [comment]
Bug #479878 logged to track this issue.

**Comment by RamaKrishnamoorthy** [comment]
Trial refers to the F&O trial experience you get through LCS. Trial does not refer to Dev/Test instance that comes with valid license.

**Comment by RamaKrishnamoorthy** [comment]
Trial is the well know term used for non-licensed instance. We cannot explain it more on the documentation.
