### ISSUE TITLE
Add instructions on debugging batch

### ISSUE THREAD

**Issue by qipengwu** [MicrosoftDocs/dynamics-365-unified-operations-public#2646]
This page has really good information on debugging UI issues. If one needs to debug a batch related issue, we need to add some instructions here to ask developer to make sure to also restart the batch service on the debugging machine, in order for the debugging machine to show up as one of the batch servers. Lastly, make sure the batch job runs on the debugging machine by creating a batch group with only the debugging machine, and use the same batch group to run the batch job.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb08fb04-94d5-ef25-8162-a0d79f5ee70a
* Version Independent ID: 6d43b4b7-cc2e-49bc-564a-5eb5eacefa84
* Content: [Debug a copy of the production database - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/dbmovement-scenario-debugdiag)
* Content Source: [articles/fin-ops-core/dev-itpro/database/dbmovement-scenario-debugdiag.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/database/dbmovement-scenario-debugdiag.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laneswenka**

**Comment by tonyafehr** [comment]
Bug #479881 logged to track this issue.
