### ISSUE TITLE
Automatic generation of extension class names

### ISSUE THREAD

**Issue by TrudAX** [MicrosoftDocs/dynamics-365-unified-operations-public#2647]
Just wanted to share a link(as a comment to this article) to my open-source VS add-in that can automate extension class generation [D365FO class extensions naming tool](https://denistrunin.com/d365utils-classextensionname/)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1eb14aee-fcc5-0b16-5e98-2b30febdce76
* Version Independent ID: d2e11166-cd39-ee9c-d27d-d85e23906c76
* Content: [Naming guidelines for extensions - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/extensibility/naming-guidelines-extensions)
* Content Source: [articles/fin-ops-core/dev-itpro/extensibility/naming-guidelines-extensions.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/extensibility/naming-guidelines-extensions.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @LarsBlaaberg
* Microsoft Alias: **pvillads**

**Comment by tonyafehr** [comment]
@TrudAX, thank you!
