### ISSUE TITLE
Table groups > table properties #253 [reopen] -- #258 [reopen]

### ISSUE THREAD

**Issue by ibruynin** [MicrosoftDocs/dynamics-365-unified-operations-public#265]
Hi @ShylaThompson 

it's me again.
Please have a look in my latest comment in issue #258.

I hope that clarifies what we're looking for exactly.

**Comment by ShylaThompson** [comment]
@ibruynin Closing this issue. I'll review the original issue's comment. Please only open a new issue if there is a new issue.
