### ISSUE TITLE
Extended the embedded pbix

### ISSUE THREAD

**Issue by davecope1982** [MicrosoftDocs/dynamics-365-unified-operations-public#2650]
Hi,

How do I go about downloading (and then extending) the personnel management Power BI report? I have followed the process we use in finance & operations (via the Asset Library in LCS) but cannot see any Power BI packages to download. 

I know I could connect PBI desktop upto the CDS entities but as the data model and pbix already exist in the OOB workspace this seems a nonsensical approach that would mean huge a duplication of effort top replicate the standard report before beginning extension work.

Also - once extensions are made I assume i can replace the existing analytics tab within the personnel management workspace in the same way we can within F&O?

Any advice would be great

Thanks,

Dave

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02a41087-2a11-d94a-6630-81e74a9ef256
* Version Independent ID: 6b869ada-9961-870f-4703-9adcdafdaed3
* Content: [Reporting options - Human Resources | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/human-resources/hr-admin-troubleshooting-reporting)
* Content Source: [articles/human-resources/hr-admin-troubleshooting-reporting.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/human-resources/hr-admin-troubleshooting-reporting.md)
* Service: **dynamics-365-human-resources**
* Product: ****
* Technology: ****
* GitHub Login: @andreabichsel
* Microsoft Alias: **anbichse**

**Comment by sericks007** [comment]
@davecope1982, thanks for posting this feedback!

@andreabichsel, please review and update the content, as needed.

**Comment by sericks007** [comment]
Bug 480527 has been logged to track this issue.

**Comment by davecope1982** [comment]
any update on this?

**Comment by andreabichsel** [comment]
Per our product team, these reports are locked down in Human Resources.
