### ISSUE TITLE
PowerBI.com Configuration 

### ISSUE THREAD

**Issue by Guide2Learn** [MicrosoftDocs/dynamics-365-unified-operations-public#2651]
in Dynamics 365 Finance and Operations Apps there is an issue starting from CU24 above regarding PowerBI.com configuration.

after enabling the PowerBI.com in the Dynamics 365 Finance and Operations Apps, and authenticating the Dynamics with Power BI, the dialogbox appears, but when the success message appears after accepting to grant permission the PowerBI disappears from the PowerBI.com configuration form and never been shown again, there is no way you can select any tile or content from PowerBI.

also Get Data from Power BI does not have any connector to the Dynamics 365 Finance and Operations. 

I have tried this many times from CU24 through the latest CU37 (10.0.13).

Anyone has the same issue? is there a bug? what is the road map for connecting to the Dynamics from Power BI.com?

the app registrations has been tried from both Azure and PowerBI dev portal.

anyone has the same issue?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2213414-926d-10e1-538b-efef09dc0181
* Version Independent ID: 03be53f7-c305-cb02-7627-2ea4f1c01bd4
* Content: [Configure PowerBI.com integration - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/configure-power-bi-integration)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/configure-power-bi-integration.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/configure-power-bi-integration.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by josaw1** [comment]
Thank you for your feedback. @MilindaV2 can you please take a look?

**Comment by josaw1** [comment]
BUG 481390created to track this issue.

**Comment by TJVass** [comment]
Thanks for reaching out for assistance. The PowerBI.com authorization process with F&O applications is a 1-time operation.  Once completed, content hosted on PowerBI.com can be pinned to application workspaces. Use the Options form to add tiles & links to reports directly to the form.

RE: PowerBI.com connector to Dynamics 365 F&O - a new CDS connector is available "PREVIEW" for customers that gives direct access to transactional data.
