### ISSUE TITLE
Wrong file name for text file

### ISSUE THREAD

**Issue by mirkobon** [MicrosoftDocs/dynamics-365-unified-operations-public#2652]
The name of the text file is not correct.

Using "ModuleToRemove.txt" will cause the Deployable Package in the Asset Library to be marked as invalid.

The real file name shoud be "ModulesToRemove.txt". Please fix this documentation page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f21baa4-903d-1a42-eaaf-4efe1ed1b951
* Version Independent ID: e8d91d54-a0f1-5958-0623-6c0c54ec0b8d
* Content: [Uninstall a package - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/uninstall-deployable-package)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/uninstall-deployable-package.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/deployment/uninstall-deployable-package.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by josaw1** [comment]
BUG 481391 created to track this issue.
