### ISSUE TITLE
Rename configuration file to package name to prevent error installing

### ISSUE THREAD

**Issue by HolgerAdolf** [MicrosoftDocs/dynamics-365-unified-operations-public#2653]
Hint: Before running the Commerce Scale Unit installer you should rename the configuration file to the to [Package Filename].xml and put both files in the same folder:

![image](https://user-images.githubusercontent.com/38324153/89523749-adb3a100-d7e3-11ea-9703-b8889f9898d2.png)

Otherwise you could get the following error running the installation:

![image](https://user-images.githubusercontent.com/38324153/89523625-747b3100-d7e3-11ea-8b59-d33b99d5eb00.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36235fea-cbfc-c300-7da8-9592b0906b57
* Version Independent ID: c27d2974-9c6f-3432-0521-e024b8defa8b
* Content: [Configure and install Commerce Scale Unit (self-hosted) - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/retail-store-scale-unit-configuration-installation)
* Content Source: [articles/commerce/dev-itpro/retail-store-scale-unit-configuration-installation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/dev-itpro/retail-store-scale-unit-configuration-installation.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @jashanno
* Microsoft Alias: **jashanno**

**Comment by josaw1** [comment]
Thanks for your feedback. @jashanno can you please take a look?

**Comment by josaw1** [comment]
BUG 481392 created to track.

**Comment by josaw1** [comment]
PR will be merged today with changes. Thanks.
