### ISSUE TITLE
Need the latest version of SQLPackage in order to export database to a bacpac file in command line

### ISSUE THREAD

**Issue by Tad1011** [MicrosoftDocs/dynamics-365-unified-operations-public#2656]
[Enter feedback here]
In the [Export the copied database to a bacpac file] section, there is the following description. 
>It's very important that you install the latest version of SQL Server Management Studio before you start this step. Although SQLPackage is present in earlier versions of Management Studio, it won't work correctly for this step unless you first install the latest version.

Actually, in order to execute the SQLPackage command, not only SSMS but also the latest version of SQLPackage is required.
When SQLPackage v18.5 build15.0 is installed, the command option [Command Timeout] is enabled and the command can be executed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6717d4f3-0b93-713a-6a61-405cce70dfe0
* Version Independent ID: 050db2bb-9dd4-82ff-3f27-ec7a8d0ea64c
* Content: [Upgrade from AX 2012 - Data upgrade in sandbox environments - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/upgrade-data-sandbox)
* Content Source: [articles/fin-ops-core/dev-itpro/migration-upgrade/upgrade-data-sandbox.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/migration-upgrade/upgrade-data-sandbox.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by josaw1** [comment]
Thanks for your feedback. @laneswenka can you please review?

**Comment by josaw1** [comment]
BUG 481393 created to track.
