### ISSUE TITLE
AddNode.Ps1 failure

### ISSUE THREAD

**Issue by Phineas019** [MicrosoftDocs/dynamics-365-unified-operations-public#266]
When i try to add another node of AOS It shows problem with internet connectivity How can i resolve that

Thanks in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d86d2857-6199-f3cb-208b-db4e1cd9f8e2
* Version Independent ID: d425ad9e-6c01-6145-dad5-2af32ffaaff0
* Content: [Troubleshoot Microsoft Dynamics 365 for Finance and Operations (on-premises) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/deployment/troubleshoot-on-prem)
* Content Source: [articles/dev-itpro/deployment/troubleshoot-on-prem.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/deployment/troubleshoot-on-prem.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @sarvanisathish
* Microsoft Alias: **sarvanis**

**Comment by tonyafehr** [comment]
Thanks for contacting us. Unfortunately, we are unable to handle support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support)

**Comment by Phineas019** [comment]
Hi Tonya i managed to find the solution Unfortunately the issue is closed !!
