### ISSUE TITLE
missing listgrid

### ISSUE THREAD

**Issue by drhexgit** [MicrosoftDocs/dynamics-365-unified-operations-public#2660]
2 of the wireframe layouts have a quick filter/listgrid on the left, but it is not present in the example screenshots, where did it go?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c235e8a-d3b6-5ebd-3822-f56a42899a2c
* Version Independent ID: 8b4812bf-bcf9-03dd-211e-09f7f1b58832
* Content: [Details Transaction form pattern - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/user-interface/details-transaction-form-pattern)
* Content Source: [articles/fin-ops-core/dev-itpro/user-interface/details-transaction-form-pattern.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/user-interface/details-transaction-form-pattern.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by josaw1** [comment]
Thanks for your feedback. @jasongre can you please review?

**Comment by josaw1** [comment]
BUG 481394 created to track.

**Comment by jasongre** [comment]
@drhexgit The side panel that contains the QuickFilter and list grid is initially invisible on the Details portion of these forms. You can toggle the visibility of the side panel using the "Show list" button on the left (below the Show filters button).
