### ISSUE TITLE
Status of instance is not Failed but Deleted

### ISSUE THREAD

**Issue by LyD001** [MicrosoftDocs/dynamics-365-unified-operations-public#2661]
Under remove a Human Resources environment from an existing Power Apps environment, in Step 7, the Deployment status is Deleted not Failed
![image](https://user-images.githubusercontent.com/63725992/89620142-68fa3980-d8b9-11ea-9086-04e7a77b9618.png)

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86f9cf92-fdf6-8a9d-4f3b-c8fed23df91f
* Version Independent ID: e027cb90-e677-da97-5c39-5d174c780dbb
* Content: [Remove an instance - Human Resources | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/human-resources/hr-admin-setup-remove-instance)
* Content Source: [articles/human-resources/hr-admin-setup-remove-instance.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/human-resources/hr-admin-setup-remove-instance.md)
* Service: **dynamics-human-resources**
* Product: ****
* Technology: ****
* GitHub Login: @andreabichsel
* Microsoft Alias: **anbichse**

**Comment by josaw1** [comment]
Thanks for your feedback. @andreabichsel can you please take a look?

**Comment by josaw1** [comment]
BUG 481396 created to track.
