### ISSUE TITLE
Currency Model Overlayering

### ISSUE THREAD

**Issue by gcamargo82** [MicrosoftDocs/dynamics-365-unified-operations-public#267]
Hello, anybody knows how to implement this without using the currency model? The first step states we need to create the class in the Currency model, which certainly goes against MSFT BPs to avoid at all cost Overlayering. Is there any way to implement this without doing it?

Cheers,

Gus

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4aa238e-aec2-0c37-7b86-e152befdaa4f
* Version Independent ID: 2dc4c20f-bf8f-3a46-2996-9f38dc7abf1f
* Content: [Create exchange rate providers - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/financial/create-exchange-rate-providers)
* Content Source: [articles/dev-itpro/financial/create-exchange-rate-providers.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/financial/create-exchange-rate-providers.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RobinARH
* Microsoft Alias: **jbye**

**Comment by tonyafehr** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support)
