### ISSUE TITLE
Power BI integration with Entity store

### ISSUE THREAD

**Issue by April-Cai** [MicrosoftDocs/dynamics-365-unified-operations-public#2670]
Hi,

This is an amazing solution for Power BI integration to AX.
I just want to know which way that Power BI load data from entity store, the SQL server or others?
Also, can you provide an example that I can follow to setup data, build my own report and embed to AX? 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da145b17-ccd8-7bf7-7495-0ddb1bf5829f
* Version Independent ID: 2a24d715-ecac-1c65-d2d4-8d14b55b8765
* Content: [Power BI integration with Entity store - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/power-bi-integration-entity-store?toc=/dynamics365/commerce/toc.json)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/power-bi-integration-entity-store.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/power-bi-integration-entity-store.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by tonyafehr** [comment]
@April-Cai, thanks for the feedback. 
@MilindaV2, please review.

**Comment by tonyafehr** [comment]
Bug #483141 logged to track this issue.

**Comment by MilindaV2** [comment]
Pl see the document here: https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/add-analytics-tab-workspaces?toc=/dynamics365/commerce/toc.json
