### ISSUE TITLE
The described app registration is deprecated.

### ISSUE THREAD

**Issue by kurthatlevik** [MicrosoftDocs/dynamics-365-unified-operations-public#2671]
The section covering "Register the app", do not seem to show the current way Azure Portal is working.  The described app registration is deprecated. See  https://developer.microsoft.com/en-us/identity/blogs/deprecation-of-app-registrations-legacy-experience-and-the-application-registration-portal-apps-dev-microsoft-com/

Can you walk through this section again, as I'm actually not able to conduct the steps as described.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a344a5de-68fa-e9cf-28eb-51269c33b9b3
* Version Independent ID: 1b3ede62-3954-574b-5778-8cdee0ededfe
* Content: [Make Entity store available as a Data Lake - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/entity-store-data-lake)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/entity-store-data-lake.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/entity-store-data-lake.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by tonyafehr** [comment]
@kurthatlevik, thanks for the feedback. 
@MilindaV2, please review.

**Comment by tonyafehr** [comment]
Bug #483143 logged to track this issue.
