### ISSUE TITLE
The navigation instructions in the 'Upload the Management Certificate' section are out dated.

### ISSUE THREAD

**Issue by scott-tucker** [MicrosoftDocs/dynamics-365-unified-operations-public#2674]
these two steps should be updated.
2. In the Azure classic portal, in the left pane, click Settings.
3. Filter to the Azure subscription that is used, and then, on the Management certificates tab, click Upload.

the link to the 'Azure classic portal' doesn't work as expected any more. it redirects to the new portal.

Replace 2 and 3 with one step that should be similar to step 1 of the 'Set the Contributor Workflow' section.  
2. In the Azure portal, on the Subscription tab, select the Azure subscription, and then click the Management certificates line item, click Upload.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 693bb4b2-92f2-2f0c-4fd3-6c9c1bb5894b
* Version Independent ID: 476f52d0-57a1-37e2-881f-857ce623bb03
* Content: [Complete the Azure Resource Manager (ARM) onboarding process - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/arm-onboarding)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/arm-onboarding.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/deployment/arm-onboarding.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @sarvanisathish
* Microsoft Alias: **sarvanis**

**Comment by tonyafehr** [comment]
@sarvanisathish, please review. Thanks!

**Comment by tonyafehr** [comment]
Bug #483157 logged to track this issue.
