### ISSUE TITLE
Responding to Vendor questions - Does it exist? 

### ISSUE THREAD

**Issue by Kelkane** [MicrosoftDocs/dynamics-365-unified-operations-public#2676]
Does this functionality even exist? Cannot find the specified fields that correspond with this documentation in multiple versions including 10.0.10, 10.0.11... 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c8e66cb-c9ee-71ed-1c34-132b8b53601a
* Version Independent ID: 49adb82f-76c6-6143-cd97-5ec619ef3b7a
* Content: [Responding to vendor questions on Request for quotations - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/procurement/rfq-question)
* Content Source: [articles/supply-chain/procurement/rfq-question.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/procurement/rfq-question.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @velofog
* Microsoft Alias: **v-alpavk**

**Comment by Kelkane** [comment]
Edited to add, can put the field on through personalization. 
![image](https://user-images.githubusercontent.com/63654741/89907010-19b65080-dbba-11ea-80ff-a82ec624a89a.png)

**Comment by tonyafehr** [comment]
@Kelkane, thanks for the feedback.
@kamaybac, please review.

**Comment by tonyafehr** [comment]
Bug #483146 logged to track this issue.

**Comment by tonyafehr** [comment]
Note that if you make an amendment just to allow vendor questions, then when sending the RFQ will clear existing responses.
