### ISSUE TITLE
Getting: "Microsoft Dynamics 365 for Finance and Operations: Document Routing -- Installation failed."

### ISSUE THREAD

**Issue by soerenpc** [MicrosoftDocs/dynamics-365-unified-operations-public#2678]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fe44c05-ed58-b554-859e-2da552dbbd9d
* Version Independent ID: e638edab-dd54-6008-f210-524fd52b0e5b
* Content: [Install the Document Routing Agent to enable network printing - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/install-document-routing-agent)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/install-document-routing-agent.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/install-document-routing-agent.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by soerenpc** [comment]
I´m getting this after uninstalling and re-installing..
I had to use an "unstaller" tool to get it uninstalled since someone apparently had removed install files on the server..

**Comment by sericks007** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
