### ISSUE TITLE
Windows Server 2019

### ISSUE THREAD

**Issue by dodiggitydag** [MicrosoftDocs/dynamics-365-unified-operations-public#2679]
Is the DRA software supported when running on Windows Server 2019?  This article does not address this version of Windows.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fe44c05-ed58-b554-859e-2da552dbbd9d
* Version Independent ID: e638edab-dd54-6008-f210-524fd52b0e5b
* Content: [Install the Document Routing Agent to enable network printing - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/install-document-routing-agent)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/install-document-routing-agent.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/install-document-routing-agent.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by sericks007** [comment]
@dodiggitydag, thanks for providing this feedback!

@TJVass, please consider updating the content to address this issue.

**Comment by sericks007** [comment]
Bug 483023 has been logged to track this issue.

**Comment by dodiggitydag** [comment]
Hello, do you have an update?

**Comment by sericks007** [comment]
@TJVass, can you please respond?
