### ISSUE TITLE
v9.0 update notification emails for Dynamics 365 Customer Engagement referencing this page

### ISSUE THREAD

**Issue by simes1** [MicrosoftDocs/dynamics-365-unified-operations-public#268]
Update notifications emails for Dynamics 365 **Customer Engagement** appear to be incorrectly referencing this page (which appears to be specific to Dynamics 365 **Finance & Opperations**):

"If you do not schedule an update in the timeframe mentioned above, Microsoft will schedule an automatic update for your organization on August 17, 2018 and communicate the dates. The automatic update would take place during your normal maintenance window [https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/planned-maintenance-window-faq]."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c045df4-a0dc-8ab8-0ed0-deb60ba2b827
* Version Independent ID: 8d40df93-3243-f645-6608-40cd0d49e5d8
* Content: [Planned maintenance window FAQ - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/planned-maintenance-window-faq)
* Content Source: [articles/dev-itpro/lifecycle-services/planned-maintenance-window-faq.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/lifecycle-services/planned-maintenance-window-faq.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @robadawy
* Microsoft Alias: **robadawy**

**Comment by tonyafehr** [comment]
Thanks for the feedback. We'll investigate and be sure that this gets updated.
