### ISSUE TITLE
On-premise deployment 

### ISSUE THREAD

**Issue by Alpa-Chino** [MicrosoftDocs/dynamics-365-unified-operations-public#2682]
Does the All-in One package requirement affect on-premise deployments as well or just the cloud deployments?  The article does not go into details around this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: feb1c10e-1287-6db3-5ed6-315cb76fc1cd
* Version Independent ID: 85966417-fa61-ffa8-22e3-fa2bfa0e50ff
* Content: [All-in-one deployable packages - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/aio-deployable-packages)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/aio-deployable-packages.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-tools/aio-deployable-packages.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by PeterRFriis** [comment]
Hi Alpa-Chino
All-in One package are supported on on-premises deployments as well.
On-premises deployments support(with the exception of a platform package) the same package types as D365 F&O in running on Service Fabric in Cloud.

**Comment by Alpa-Chino** [comment]
Hi Peter!

Thanks for the answer, the enforcement part  for All-in One is still not clear to me, when it will be enforced on on-prem?

**Comment by PeterRFriis** [comment]
Hi
We dont have a specific date yet, but I believe it will later this year. 
So I can confirm that on-prem will enforce it at some point and will align with cloud.
