### ISSUE TITLE
Confusion in Code for ViewCustomerSummaryCommand.ts

### ISSUE THREAD

**Issue by sanjay-lab** [MicrosoftDocs/dynamics-365-unified-operations-public#2685]
[Enter feedback here]
can You verify,whether code will be 
import MessageDialog from "../DialogSample/MessageDialog";
or 
import MessageDialog from "../../DialogSample/MessageDialog";

in ViewCustomerSummaryCommand.ts Files

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfef165f-aa45-f586-bffc-964ab04013fe
* Version Independent ID: abc97ef9-6408-d006-dea5-ab49a3dd2da0
* Content: [Extend POS views to add custom columns and app bar buttons - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/pos-view-extension)
* Content Source: [articles/commerce/dev-itpro/pos-view-extension.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/dev-itpro/pos-view-extension.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by mugunthanm** [comment]
Updated the sample code to:
"../../Controls/DialogSample/MessageDialog";

The full sample code is available in "\RetailSDK\POS\Extensions\SampleExtensions\ViewExtensions\Search\ViewCustomerSummaryCommand.ts"
