### ISSUE TITLE
Hint regarding Copy/Paste

### ISSUE THREAD

**Issue by alx-kpk** [MicrosoftDocs/dynamics-365-unified-operations-public#2688]
Would be glad to have a hint regarding issues with copy/paste. 

For example when you prepare an e-mail template and using dynamic values it will not work when you just copy and paste the template into the textbox of the email description field. You've to enter the dynamic values into the textbox directly without copy paste! When trying to use copy/paste the placeholders will not be replaced by the correct values.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3b1e278-d76d-5d8e-b247-0ba874f8a347
* Version Independent ID: 4554bc65-9fb6-c38c-d3df-fe967f10d456
* Content: [Configure workflow properties - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/organization-administration/configure-workflow-properties)
* Content Source: [articles/fin-ops-core/fin-ops/organization-administration/configure-workflow-properties.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/organization-administration/configure-workflow-properties.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @sericks007
* Microsoft Alias: **donaldc**

**Comment by sericks007** [comment]
@alx-kpk, thanks for providing this feedback!

@ChrisGarty, please review and update the content, as appropriate.

**Comment by sericks007** [comment]
Bug 485813 has been logged to track this issue.

**Comment by ChrisGarty** [comment]
Edited: https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/pull/3114

**Comment by sericks007** [comment]
The content has been updated.
