### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by kamarajuv** [MicrosoftDocs/dynamics-365-unified-operations-public#269]
Can you please elaborate this section with relevant examples for setting up the accounts for Sale/Scrap

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 767405ef-328a-9372-d7f6-ff66a3b62882
* Version Independent ID: c629c1ae-f83b-1151-afa6-e650455ce782
* Content: [Fixed asset disposal posting accounts - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/fixed-assets/fixed-asset-disposal-posting-accounts)
* Content Source: [articles/financials/fixed-assets/fixed-asset-disposal-posting-accounts.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/fixed-assets/fixed-asset-disposal-posting-accounts.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @twheeloc
* Microsoft Alias: **saraschi**

**Comment by sericks007** [comment]
Bug 238416 was logged for tracking purposes.
