### ISSUE TITLE
Wrong spelling for Table CustCustomerV3Entity

### ISSUE THREAD

**Issue by BernhardRaether** [MicrosoftDocs/dynamics-365-unified-operations-public#2691]
the Table name "CustCustomerV3Entity" is incorrectly spelled "CustomerCustomerV3Entity" on this page, please correct

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf664431-b092-8d49-567d-90245aa48c99
* Version Independent ID: 14fce919-2a2d-4eab-b190-375516f6f05b
* Content: [Integrated customer master - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/customer-mapping)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/customer-mapping.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/dual-write/customer-mapping.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @RamaKrishnamoorthy
* Microsoft Alias: **ramasri**

**Comment by tonyafehr** [comment]
@BernhardRaether, thanks for the feedback. 
@RamaKrishnamoorthy, please update this topic.

**Comment by tonyafehr** [comment]
Bug #485375 logged to track to this issue.

**Comment by RamaKrishnamoorthy** [comment]
fixed the issue and resolved the bug.
