### ISSUE TITLE
Expense categories

### ISSUE THREAD

**Issue by ksears87** [MicrosoftDocs/dynamics-365-unified-operations-public#2695]
We're having issue copying configurations for the Expense Management module, and wondering if it has something to do with the Expense Categories. I don't see Expense Categories mentioned anywhere here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9ca3366-fa7f-6cda-dfc6-672f032ccc3a
* Version Independent ID: 0bb7d0c2-467e-8a95-b7f1-51dbfe0b6b20
* Content: [Copy configuration data between companies or legal entities overview - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/copy-configuration)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/copy-configuration.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/copy-configuration.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @mikefalkner
* Microsoft Alias: **mfalkner**

**Comment by josaw1** [comment]
BUG 486839 created to track.

**Comment by sericks007** [comment]
@Sunil-Garg, please review and update the content, as needed.

**Comment by josaw1** [comment]
Please open a service request for this issue. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support).
