### ISSUE TITLE
Dynamics HR trial version link does not work- still points to Talent which then fails

### ISSUE THREAD

**Issue by magic1949** [MicrosoftDocs/dynamics-365-unified-operations-public#2696]
The link to the trial version for Dynamics 365 HR still points to Talent and does not work.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e50cd712-afc9-ddb9-9b1b-23c9c54a1eb0
* Version Independent ID: 411b7341-e286-fada-d54b-40631fd64b80
* Content: [Provision Human Resources - Human Resources | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/human-resources/hr-admin-setup-provision)
* Content Source: [articles/human-resources/hr-admin-setup-provision.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/human-resources/hr-admin-setup-provision.md)
* Service: **dynamics-human-resources**
* Product: ****
* Technology: ****
* GitHub Login: @andreabichsel
* Microsoft Alias: **anbichse**

**Comment by josaw1** [comment]
BUG 486841 created to track.
