### ISSUE TITLE
Confusing Sentence in the "Getting the Solution" part

### ISSUE THREAD

**Issue by BernhardRaether** [MicrosoftDocs/dynamics-365-unified-operations-public#2698]
Hi Tonya,

We have used this document to set up the Virtual Entities.

The part that's confusing is "Ensure the following solutions are installed in Common Data Service. These solutions must be extracted from the downloaded package."

Reading this, we were unsure if that's a manual step. Doing it, we found that the AppSource install will get all these listed solutions ready, no manual work needed. 

So please update: "Ensure the following solutions are installed in Common Data Service.", checking, no manual step.

Another small thing in "Enabling virtual entities"
at 2. Look for “Available Finance and Operations Entities” and select Results.
It would help to show that the "Result" means to run - best add a screenshot here. Then actual screnshot is perfect

Thanks in advance,
Regards,
Bernhard

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8065cd89-f253-c50b-ed2e-7b84e5b2409c
* Version Independent ID: 8c7e311a-582c-1ac6-328e-be817a62924c
* Content: [Finance and Operations and Common Data Service admin reference - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/power-platform/admin-reference)
* Content Source: [articles/fin-ops-core/dev-itpro/power-platform/admin-reference.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/power-platform/admin-reference.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by josaw1** [comment]
BUG 486844 created to track.
