### ISSUE TITLE
Great documentation of personalization

### ISSUE THREAD

**Issue by kellertine** [MicrosoftDocs/dynamics-365-unified-operations-public#2699]
MicrosoftDocs is highly useful in general, but the personalization pages are outstanding - thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad8be7cd-8a59-b385-2c6a-763ebd5956fa
* Version Independent ID: 7f1dde5c-a26c-55bf-118c-513b95fe07e8
* Content: [Personalize the user experience - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/personalize-user-experience?toc=/dynamics365/commerce/toc.json)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/personalize-user-experience.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/get-started/personalize-user-experience.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by sericks007** [comment]
@kellertine, thank you for the feedback!  It's always great to read feedback like this!

@jasongre, nice job!!
