### ISSUE TITLE
Broken link in Project tasks / Milestones resources

### ISSUE THREAD

**Issue by manishmoothedath** [MicrosoftDocs/dynamics-365-unified-operations-public#270]
Hi, Please update the link to the resources for project milestones and tasks. for e.g: It is pointing to https://ax.help.dynamics.com/wiki/&lt;resource&gt;/   this then redirects to the current dynamics 365 for operations home page https://docs.microsoft.com/en-au/dynamics365/unified-operations/fin-and-ops/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 839b8149-3604-a6e2-cb3a-63531a789de8
* Version Independent ID: 0293a176-32e9-156f-ad43-478544963e93
* Content: [Projects in Lifecycle Services (LCS) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/ax-2012/projects-lcs)
* Content Source: [articles/dev-itpro/lifecycle-services/ax-2012/projects-lcs.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/lifecycle-services/ax-2012/projects-lcs.md)
* Product: **dynamics-ax-2012**
* GitHub Login: @manalidongre
* Microsoft Alias: **manado**

**Comment by tonyafehr** [comment]
Thanks for your suggestion, however there aren't any links in the [Projects in Lifecycle Services](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/ax-2012/projects-lcs) topic that point to milestones or tasks. Can you provide specific information about where you are encountering broken links.

**Comment by manishmoothedath** [comment]
![lcs project resources](https://user-images.githubusercontent.com/23469109/43170704-be8360ea-8fe9-11e8-9eb9-7ac02c979d5a.PNG)
Please check the attached screenshot from LCS

**Comment by manishmoothedath** [comment]
Thanks

**Comment by tonyafehr** [comment]
This has been resolved
