### ISSUE TITLE
Thumprint and new version for cash registers for Norway

### ISSUE THREAD

**Issue by Halldor10** [MicrosoftDocs/dynamics-365-unified-operations-public#2703]
Trying to figure out the current status of the Norway localizations. 

Found following: 
"In 2020 release wave 1, we will extend the out-of-the-box Commerce localization by delivering fiscal service integration for Germany and moving the digital signing of retail transactions for France and Norway to the fiscal integration framework."

But not seeing this reflected in the documentation, and not sure which version this is in or will be in. Are we talking 10.0.12, 10.0.13 or later?

Any documentation upgrade here would help :)

Regards Halldor

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b76e6f66-7b8b-c4e3-c70a-0e73bf356709
* Version Independent ID: 0f33ea6f-8812-d823-27d4-5e807e793836
* Content: [Deployment guidelines for cash registers for Norway - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/localizations/emea-nor-loc-deployment-guidelines?tabs=retail-8-1-1)
* Content Source: [articles/commerce/localizations/emea-nor-loc-deployment-guidelines.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/localizations/emea-nor-loc-deployment-guidelines.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @AlexChern0v
* Microsoft Alias: **v-alexec**

**Comment by tonyafehr** [comment]
@Halldor10, thanks for the feedback.
@kfend, please review.

**Comment by AlexChern0v** [comment]
@EvgenyPopovMBS

**Comment by v-kikozl** [comment]
Hello colleagues,
Uptake of the fiscal integration sample for Norway to the Fiscal integration framework is partially done, but the rest part of it was postponed due to more urgent features, that our team is currently working on.
So, for now only legacy version of the Norwegian localization is available, and we don't have a confirmed release plans for updating it to the Fiscal integration framework.

Best regards,
Kirill Kozlov
