### ISSUE TITLE
Need to add the mention to use latest SQLPackage.exe, not only SQL management studio.

### ISSUE THREAD

**Issue by mutsun1** [MicrosoftDocs/dynamics-365-unified-operations-public#2704]
We need to add some sentence that ask Customer to use latest version SQLPackage.exe so that we can support latest version of Azure SQL.
For example, “GeneralPurpose”, “BusinessCritical”, “Hyperscale” are supported by SQLPackage.exe version 18.4 (15.0.4573.2) as Azure SQL Database Edition, although SQLPackage.exe that is installed on SANDBOX is 14.0.4127.1　as default.
So, User get an error when they try to import Database with SQLPackage.exe that is installed as default because version 14.0.4127.1 doesn’t support “GeneralPurpose” as /p:DatabaseEdtion.

Actually, our customer encountered this error and requested us to add the mention to use latest SQLPackage.exe on this document.

We should add note that need to use latest SQLPackage.exe as well as SQL management studio on this document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6717d4f3-0b93-713a-6a61-405cce70dfe0
* Version Independent ID: 050db2bb-9dd4-82ff-3f27-ec7a8d0ea64c
* Content: [Upgrade from AX 2012 - Data upgrade in sandbox environments - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/upgrade-data-sandbox)
* Content Source: [articles/fin-ops-core/dev-itpro/migration-upgrade/upgrade-data-sandbox.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/migration-upgrade/upgrade-data-sandbox.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by tonyafehr** [comment]
@mutsun1, thanks for the feedback.
@laneswenka, please review.

**Comment by laneswenka** [comment]
Document has been updated in latest PR.
