### ISSUE TITLE
Additional information requested for SAF-T tax code mapping

### ISSUE THREAD

**Issue by heikkikorkala** [MicrosoftDocs/dynamics-365-unified-operations-public#2705]
Could you please provide additional information regarding the saf-t tax code mapping as the documentation currently doesn't instruct how to handle scenarios in which multiple codes would be applicable. As an example, let's say a single tax code in Dynamics 365 was defined for full rate sales and purchases. A different SAF-T code would be applied depending on the direction. How would one correctly map SAF-T codes in this situation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8904993-84a8-8983-dcc5-4499b6e1e9d5
* Version Independent ID: f40dc67d-74a2-dab3-182c-fbbd6f0e46e0
* Content: [Standard Audit File for Tax (SAF-T) for Norway - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/emea-nor-satndard-audit-file-for-tax)
* Content Source: [articles/finance/localizations/emea-nor-satndard-audit-file-for-tax.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/localizations/emea-nor-satndard-audit-file-for-tax.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @liza-golub
* Microsoft Alias: **elgolu**

**Comment by tonyafehr** [comment]
@liza-golub, please review.

**Comment by liza-golub** [comment]
Hello,
Thank you for your feedback. Scenario described in the comment: “Scenarios, in which multiple codes would be applicable. As an example, let's say a single tax code in Dynamics 365 was defined for full rate sales and purchases. A different SAF-T code would be applied depending on the direction.” is out of scope of current implementation of Norwegian SAF-T report. Currently this is not in our roadmap; however, we are tracking ideas registered on ideas portal and if we get more feedback and votes, we may consider it in the future. We suggest registering this information in relation to the Norwegian SAF-T report. Alternatively, such requirement could be implemented via customization of “SAF-T Financial data model mapping” model mapping and “SAF-T Format (NO)” format configurations of the report to accommodate specific need of a company.
Sincerely,
Elizaveta Golub,
PM, Microsoft

**Comment by heikkikorkala** [comment]
Hello @liza-golub . Understand not in roadmap for my specific example scenario, but there are simpler ones as well and I would still request additional instruction for the SAF-T setup for tax codes. The article basically only says "set up the external codes for tax groups" but how?
- Is the standard code checkbox required to be set in order for the SAF-T report to work? 
- What if multiple tax codes use the same SAF-T code? The external codes form blocks duplicates, so is it ok to create another external code header record and have that as standard code too?

**Comment by liza-golub** [comment]
Hello,
Current implementation of External codes for Sales tax codes is limited to possibility to setup one “external” code value for one Sales tax code. As you correctly noted: “The external codes form blocks duplicates”. This behavior was inherited from the solution introduced for Norwegian SAF-T report in 2016th for AX 2012 R3, to not brake users experience in case some companies are migrating from 2012 R3 to Dynamics 365 Finance. Here you can find some description of this feature in AX 2012 R3: https://docs.microsoft.com/en-us/dynamicsax-2012//sales-tax-codes-form?redirectedfrom=MSDN
In general, “External codes” is not Norway specific or SAF-T specific feature – it is part of core tax module master data setup which is used in reporting. Different reports can use differently this functionality depending on in-market practices and particular report requirements. 
Specifically, for Norwegian SAF-T the algorithm is the following: system takes the value (ExtCodeValue) for the first found External code from the list of specified for a Sales tax code. 
FIRSTORNULL(FILTER(ExtCodeValueTable, AND(ExtCodeValueTable.ExtCodeRelationTableId=@.TableId,
ExtCodeValueTable.ExtCodeRelationRecId=@.RecId)))
Where @ = TaxCodes
Hope this information helps.
