### ISSUE TITLE
No Download Required?

### ISSUE THREAD

**Issue by JoelLeichty** [MicrosoftDocs/dynamics-365-unified-operations-public#2706]
"These solutions must be extracted from the downloaded package."

I went through these steps and it installed without downloading anything. App Source installed solutions directly into the environment. Perhaps the documentation was related to an earlier version of this process?

Joel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8065cd89-f253-c50b-ed2e-7b84e5b2409c
* Version Independent ID: 8c7e311a-582c-1ac6-328e-be817a62924c
* Content: [Finance and Operations and Common Data Service admin reference - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/power-platform/admin-reference)
* Content Source: [articles/fin-ops-core/dev-itpro/power-platform/admin-reference.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/power-platform/admin-reference.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by tonyafehr** [comment]
@Sunil-Garg, please review. Thanks!

**Comment by tonyafehr** [comment]
Bug 488533 logged to track this issue.

**Comment by Sunil-Garg** [comment]
That is correct @JoelLeichty . Just fixed it. Thanks!
