### ISSUE TITLE
Duplicate page

### ISSUE THREAD

**Issue by andyNewnham** [MicrosoftDocs/dynamics-365-unified-operations-public#2709]
This page appears in the 'Manage your financials' node twice, (both before and after the trickle-feed based order creation for retail store transactions' page).

Clicking on either link always takes you to the second link (after trickle-feed).

I believe one should be removed from the hierarchy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0300e2c-645c-cc93-5049-79e509d45b79
* Version Independent ID: add66212-7c10-c571-8c15-74b7913e9d6a
* Content: [Create, calculate, and post statements for a retail store - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/tasks/create-calculate-post-statement-retail-store)
* Content Source: [articles/commerce/tasks/create-calculate-post-statement-retail-store.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/tasks/create-calculate-post-statement-retail-store.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @jashanno
* Microsoft Alias: **jashanno**

**Comment by sericks007** [comment]
@andyNewnham, thanks for making us aware of this! I removed the first instance of this page from the hierarchy -- the update will be published later today.
