### ISSUE TITLE
Example selecting count of AccountNum in CustTable is not valid

### ISSUE THREAD

**Issue by tclayton72** [MicrosoftDocs/dynamics-365-unified-operations-public#2711]
The example code will not compile because the count function returns an integer which the AccountNum field is not.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc08c66f-6eca-8bc3-b248-5f36a5465656
* Version Independent ID: 62c0ad9a-0356-0b68-fc6a-41a3e17c8f62
* Content: [X++ data selection and manipulation - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-ref/xpp-data-query)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-ref/xpp-data-query.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-ref/xpp-data-query.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **rhaertle**

**Comment by sericks007** [comment]
@tclayton72, thanks posting this feedback!

@RobinARH, please review and update the content, as necessary.

**Comment by sericks007** [comment]
Bug 489233 has been logged to track this issue.

**Comment by RobinARH** [comment]
I replaced that page with updated content: https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-ref/xpp-data/xpp-data-home-page

I removed the old page and updated the links. Those updates will go live this evening.
