### ISSUE TITLE
Parameters Detail Page

### ISSUE THREAD

**Issue by crobertso** [MicrosoftDocs/dynamics-365-unified-operations-public#2712]
Is there a link to a Credit and Collections Parameters detail page that was, perhaps, excluded from this write up? I'm referring to a page that is easy to navigate, formatted similar to that for Accounts Payable Parameters at https://docs.microsoft.com/en-us/dynamicsax-2012//accounts-payable-parameters-form which discusses all of the detail behind each field and options for configurations.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3811d721-fe31-3a4e-394d-b6d546bc42c2
* Version Independent ID: 9a0581a7-d8ed-648e-e6eb-3f831755cd38
* Content: [Credit management parameters setup - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/accounts-receivable/cm-credit-mgmt-setup)
* Content Source: [articles/finance/accounts-receivable/cm-credit-mgmt-setup.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/accounts-receivable/cm-credit-mgmt-setup.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @mikefalkner
* Microsoft Alias: **mfalkner**

**Comment by josaw1** [comment]
Thanks for your feedback. @mikefalkner, can you please help?

**Comment by panolte** [comment]
At the introduction of credit management this actually got split into two topics.  The credit management help information is contained on the document page titled [Credit management setup](https://docs.microsoft.com/en-us/dynamics365/finance/accounts-receivable/cm-credit-mgmt-setup#credit-parameters).  The [Configure accounts receivable and credit and collections](https://docs.microsoft.com/en-us/dynamics365/finance/accounts-receivable/accounts-receivables-set-up-overview) document contains similar information for the collections tab of the credit and collections parameters.
