### ISSUE TITLE
LCS link

### ISSUE THREAD

**Issue by jimwillsher** [MicrosoftDocs/dynamics-365-unified-operations-public#2714]
[Enter feedback here]

The whole page is covering LCS and 21vianet for China. Would it not be helpful to mention that LCS for China implementations is lcs.dynamics.cn isntead fo the usual lcs.dynamics.com??? We found this out by pure luck,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7de3f44e-1ebe-3a22-6e9a-20aac09b0d1e
* Version Independent ID: 2f3b442f-e306-3c1e-c366-38fcf2bf9d25
* Content: [Dynamics 365 Finance operated by 21Vianet in China and Dynamics 365 Supply Chain Management operated by 21Vianet in China - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/china-local-deployment)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/china-local-deployment.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/deployment/china-local-deployment.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **shylaw**

**Comment by RobinARH** [comment]
@kfend Kristin - Can you take a look? Thanks.

**Comment by kfend** [comment]
I have added a note to the topic that calls this out. The changes will be published today.
