### ISSUE TITLE
The link under complete the private preview survey does not work

### ISSUE THREAD

**Issue by kesavadeekshitjedi** [MicrosoftDocs/dynamics-365-unified-operations-public#2715]
When I click on the link to complete the private preview survey, it takes me to a page that doesnt seem to exist
![image](https://user-images.githubusercontent.com/28644834/91578081-4c2cb100-e90f-11ea-988f-c40210ff44fa.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48aa991b-6ebf-f11c-f803-1baa0857cc90
* Version Independent ID: e20934b0-c4ff-0881-f45a-fd2cb957e469
* Content: [Database movement API - Reference - v1 - Overview - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/api/v1/dbmovement-api-v1-overview)
* Content Source: [articles/fin-ops-core/dev-itpro/database/api/v1/dbmovement-api-v1-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/database/api/v1/dbmovement-api-v1-overview.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by kfend** [comment]
@kesavadeekshitjedi - thanks for bringing this to our attention. 
@laneswenka - can you please take a look at this?

**Comment by laneswenka** [comment]
This is no longer in private preview, and the banner was removed.
