### ISSUE TITLE
Need some more examples with reference to ER configuration

### ISSUE THREAD

**Issue by Neeraj2912** [MicrosoftDocs/dynamics-365-unified-operations-public#2717]
I would like to suggest one thing, Example given in the document/page does not provide such understanding that new beginner or learner would be able to use the same. There can be some screenshots from Electronic reporting with example how to configure the same and then its output.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2899b82-adf3-0a38-5e73-3055d6cc323a
* Version Independent ID: 4804cfcb-ccfb-2b26-7f96-08ec920d9a36
* Content: [LISTJOIN ER function - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/er-functions-list-listjoin?toc=/dynamics365/commerce/toc.json)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/er-functions-list-listjoin.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/er-functions-list-listjoin.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @NickSelin
* Microsoft Alias: **nselin**

**Comment by kfend** [comment]
@Neeraj2912 - thanks for the feedback. 
@NickSelin - can you take a look at this?

**Comment by kfend** [comment]
Nick has updated the topic with some graphics. Changes will publish in a few hours.
