### ISSUE TITLE
Running LCS Updates during maintenance mode not possible

### ISSUE THREAD

**Issue by torbennehmer** [MicrosoftDocs/dynamics-365-unified-operations-public#272]
Be aware, that you must not activate maintenance mode at this time while installing LCS updates like installing a deployable package. The update itself runs fine, but when the package tries to restart the services again, it fails at the Batch Service.

According to the event logs, the Batch server simply throws a "MaintenanceModeBatchStartupException" (you don't get a clear error message), which indicates that this isn't possible to do. The runbook can't deal with this scenario.

So at least for various kinds of data migration jobs that might be involved in an update, Maintenance mode is not an option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f2a8d7e-56e8-2ef5-b7a1-4ccf54a6ce1e
* Version Independent ID: 985efdc1-7b47-ad77-4eb9-7bd940547843
* Content: [Maintenance mode - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/sysadmin/maintenance-mode)
* Content Source: [articles/dev-itpro/sysadmin/maintenance-mode.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/sysadmin/maintenance-mode.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @manalidongre
* Microsoft Alias: **manado**

**Comment by tonyafehr** [comment]
Thanks for taking the time to provide feedback. Your comment has been noted as a future enhancement to the documentation.
