### ISSUE TITLE
wrong naming of Button in chapter "Create an alert rule" step 2

### ISSUE THREAD

**Issue by BernhardRaether** [MicrosoftDocs/dynamics-365-unified-operations-public#2720]
Hello Document Team,

the Step 2 of the "Create an alert rule" says: 
On the Action Pane, on the **Options** tab, in the **Share** group, select **Create alert rule.**

My System has another text there - "**Create a customer Alert**", the ControlName: EventAlertRuleCreate

Tested both in VendTable and in EcoResProductDetailsExtended

The Step 3 then hast the correct text "Create Alert Rule"

My Version: 
Installed product version : 10.0.12 (10.0.507.10024)
Installed platform version : Update36 (7.0.5688.35584)

Thanks in advance for checking and fixing
Regards,
Bernhard

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ff6f2d2-3ff9-6e7d-999f-1da5ecf248ab
* Version Independent ID: 3f877db5-f3de-6ed3-0f8e-94b8361e444a
* Content: [Create alert rules - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/create-alerts)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/create-alerts.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/get-started/create-alerts.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by RobinARH** [comment]
@TJVass TJ - Can you take a look? Thanks.

**Comment by RobinARH** [comment]
Bug 506286 created to track this issue.

**Comment by BernhardRaether** [comment]
Any news on this one?
Regards,
Bernhard
