### ISSUE TITLE
Please mention CDX job 1090 should be run after configuration

### ISSUE THREAD

**Issue by GordonLam** [MicrosoftDocs/dynamics-365-unified-operations-public#2721]
Please mention CDX job 1090 should be run after configuration

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbad16a9-4173-1fff-ec50-c1d301653973
* Version Independent ID: 34a90d8b-e2be-22d2-49e1-128f235cdf90
* Content: [POS user interface visual configurations - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/pos-screen-layouts)
* Content Source: [articles/commerce/pos-screen-layouts.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/pos-screen-layouts.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @boycezhu
* Microsoft Alias: **boycezhu**

**Comment by tonyafehr** [comment]
@GordonLam, thanks for the feedback. 
@boycezhu, please review.

**Comment by tonyafehr** [comment]
Bug 507345 logged to track this issue.

**Comment by tonyafehr** [comment]
@GordonLam, this topic will be updated later today to reflect this feedback. Thank you!
