### ISSUE TITLE
Email from batch jobs not working

### ISSUE THREAD

**Issue by yuukiii** [MicrosoftDocs/dynamics-365-unified-operations-public#2724]
[Enter feedback here]
Did not work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 275371de-ef78-e9f5-101c-47b75d53fabc
* Version Independent ID: 87a3ce9d-423c-59cf-2787-008cf291f811
* Content: [Set up alerts - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/alerts)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/alerts.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/sysadmin/alerts.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @hasaid
* Microsoft Alias: **hasaid**

**Comment by sericks007** [comment]
@yuukiii, thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
