### ISSUE TITLE
Clarity needed on warning about updating Production

### ISSUE THREAD

**Issue by PeterJarret** [MicrosoftDocs/dynamics-365-unified-operations-public#2726]
There is a note at the bottom of the page:  "if the environment is already running on the same version or a later version, the scheduled update is canceled".

 I feel some additional clarity is needed here.

- Does the note only apply to Production or any environment?

- Does "version" mean application/platform?  Or the combination of "application/platform+customisations"?

- How is "same" or "later" version determined?

The specific scenario I'm thinking of is:  we need to patch a Production issue, and we push this to our Support sandbox for testing.  The Support sandbox is on the same application/platform as Production.  Will we be blocked from moving the resulting application/platform+customisation to Production?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f5ff8cf-5739-86d9-26e2-2804b2f37973
* Version Independent ID: 5ca5612d-f4ec-5e7d-222c-678962aa2da7
* Content: [Update an environment - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/updateenvironment-newinfrastructure)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/updateenvironment-newinfrastructure.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/deployment/updateenvironment-newinfrastructure.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by kfend** [comment]
@PeterJarret  - Thank you for the feedback.
@laneswenka - Can you please look at and address this?

**Comment by laneswenka** [comment]
Please assign this to @rashmansur
