### ISSUE TITLE
Missing Parameter for ISV license generation

### ISSUE THREAD

**Issue by TBR-YES** [MicrosoftDocs/dynamics-365-unified-operations-public#2729]
The Microsoft docs site is missing the parameter /signatureversion:1 which seems to be necessary to create a license file. Without this parameter the licenes generation throws the following error:
ERROR: Value cannot be null.
Parameter name: source

Only by a Yammer Thread i could find the missing parameters. So please update the docs page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69192df7-736f-1504-e8ab-d1ececb95800
* Version Independent ID: 7707373e-0ef6-ac6b-fcce-efce6a0ade73
* Content: [Independent software vendor (ISV) licensing - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/isv-licensing)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/isv-licensing.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-tools/isv-licensing.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @jorisdg
* Microsoft Alias: **jorisde**

**Comment by kfend** [comment]
@TBR-YES - Thank you for the feedback.
@jorisdg - Can you please take a look and address this?

**Comment by Peakerbl** [comment]
The the parameter /signatureversion:1 was mandatory, but it is not for currently supported version. I has been made optional and we see no reason to update the current content.
