### ISSUE TITLE
Update business event parameters path in system administration > setup

### ISSUE THREAD

**Issue by fraga** [MicrosoftDocs/dynamics-365-unified-operations-public#2730]
Confusing path to the parameters, suggestion change from:

```
In a non-production environment, you must update the parameters in System administration > Setup to set retry...
```
to

```
In a non-production environment, you must update the parameters in System administration > Setup > Business events > Business Events parameters to set retry...
```

There are more instances where the full path to business events are to be reviewed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5d9afcd-65f0-58fb-4e5c-faca467fa42e
* Version Independent ID: 6086b1cc-8c4a-9459-878c-d8dd05d7c694
* Content: [Troubleshoot business events - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/business-events/troubleshooting)
* Content Source: [articles/fin-ops-core/dev-itpro/business-events/troubleshooting.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/business-events/troubleshooting.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by fraga** [comment]
Sorry after reviewing it suggestion:

In a non-production environment, you must update the parameters in **System administration > Setup > Business Events > Business Events parameters** and reset to default settings by clicking on 'Restore default settings'. This will setup retry count = 3; End points allowed per event = 10 and wait time = 1000. After this update, restart the batch service and run IISReset to pick up the latest values.

**Comment by kfend** [comment]
@fraga - Thank you for the feedback.
@Sunil-Garg - Can you please take a look and address this?
