### ISSUE TITLE
What do the new Select and copy buttons do?

### ISSUE THREAD

**Issue by carstenhoeck** [MicrosoftDocs/dynamics-365-unified-operations-public#2732]
There are a couple of new buttons not covered in the documentation

- Select

- Copy and Revise

- Copy Line

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 322c2b3a-1716-96a4-de26-7f68b2558035
* Version Independent ID: 2353cddb-c330-bfb7-87fe-00a20780589b
* Content: [Create a new trade agreement - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/sales-marketing/tasks/create-new-trade-agreement)
* Content Source: [articles/supply-chain/sales-marketing/tasks/create-new-trade-agreement.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/sales-marketing/tasks/create-new-trade-agreement.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @omulvad
* Microsoft Alias: **omulvad**

**Comment by kfend** [comment]
@carstenhoeck - thank you for the feedback.
@kamaybac - can you please work with the new author of this topic to address this feedback?

**Comment by tonyafehr** [comment]
@kamaybac. please review
