### ISSUE TITLE
Exception in code sample maxSimulateRecordsPerBusinessUnit

### ISSUE THREAD

**Issue by jorisp** [MicrosoftDocs/dynamics-365-unified-operations-public#2733]
maxSimulateRecordsPerBusinessUnit should be changed to a lower number since TopCount for QueryExpression has to be a number between 0 and 5000

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0891e384-80e8-5d40-8bde-24081e06876a
* Version Independent ID: b6ecc0cb-e827-80aa-934d-ef03d674c97e
* Content: [Bootstrap with company data FAQ - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/bootstrap-company-data)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/bootstrap-company-data.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/dual-write/bootstrap-company-data.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @RamaKrishnamoorthy
* Microsoft Alias: **ramasri**

**Comment by kfend** [comment]
@jorisp - thank you for the feedback.
@RamaKrishnamoorthy - can you please look at and address this?
