### ISSUE TITLE
AddIn does not exist

### ISSUE THREAD

**Issue by fbruemmer73** [MicrosoftDocs/dynamics-365-unified-operations-public#2734]
Apparently, add ins can only be added in +T2 environments. However, this specific 'export to data lake' add in is not available to install on any of our T2/T3/T4 environments running 10.0.11.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c84e15d4-bcac-038a-2b1e-8c456ee25bd9
* Version Independent ID: 478b5f33-f745-1df2-8fe0-da9e64233165
* Content: [Configure export to Azure Data Lake - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/configure-export-data-lake)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/configure-export-data-lake.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/configure-export-data-lake.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by kfend** [comment]
@fbruemmer73 - thank you for the feedback.
@MilindaV2 - can you please look at and address this?
