### ISSUE TITLE
Typo in congig example - misspelled StoreHoursSamp1e

### ISSUE THREAD

**Issue by ivshch** [MicrosoftDocs/dynamics-365-unified-operations-public#2738]
The last config example contains a typo, <?xml version="1.0" encoding="utf-8"?> 
```
    <retailProxyExtensions> 
        <composition> 
            <add source="assembly" value="Contoso.RetailServer.StoreHoursSamp**1**e" /> 
        </composition> 
    </retailProxyExtensions>
```
StoreHoursSamp**1**e instead of StoreHoursSample.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fec50456-8109-3379-9573-e7a91ef2d84a
* Version Independent ID: c975ebcf-ad83-a734-a27b-f36b3fb3b595
* Content: [Create a new Retail Server API - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/retail-server-icontroller-extension)
* Content Source: [articles/commerce/dev-itpro/retail-server-icontroller-extension.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/dev-itpro/retail-server-icontroller-extension.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by mugunthanm** [comment]
Thanks for the feedback, updated the typo in the document.
