### ISSUE TITLE
Does not seem to work in 10.0.12.

### ISSUE THREAD

**Issue by torbennehmer** [MicrosoftDocs/dynamics-365-unified-operations-public#2739]
Activating the performance Timer in 10.0.12 doesn't work, a dev system with a similar DB but on 10.0.11 still shows the performance timer. Has there been a change in the URL parameter?

Steps to reproduce on a 10.0.12, use the performance timer as documented:

![image](https://user-images.githubusercontent.com/2812067/92461112-203fe400-f1c9-11ea-9117-33da53f92868.png)

Am I using this correct or does the documentation miss something?

Best regards, Torben Nehmer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 135281b4-08f4-fe51-60b1-257c3ee01037
* Version Independent ID: 5d07baaf-3c78-488d-a37c-177b1b5c2956
* Content: [Performance timer - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/perf-test/performance-timer)
* Content Source: [articles/fin-ops-core/dev-itpro/perf-test/performance-timer.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/perf-test/performance-timer.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **chwolf**

**Comment by sericks007** [comment]
@torbennehmer, thanks for posting this feedback.

@RobinARH, please review and update the content, as needed.

**Comment by sericks007** [comment]
Bug 507305 has been logged to track this issue.

**Comment by RobinARH** [comment]
We won't be updating this article. -Robin
