### ISSUE TITLE
Visual backup

### ISSUE THREAD

**Issue by aliveaydin** [MicrosoftDocs/dynamics-365-unified-operations-public#2740]
In need of visual backup to understand the system
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9f97509-0998-4701-9804-cac8ca6ffe82
* Version Independent ID: f41280dd-e85d-653e-a6d9-7e097a86699e
* Content: [Register items for an advanced warehousing enabled item using an item arrival journal - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/warehousing/tasks/register-items-advanced-warehousing)
* Content Source: [articles/supply-chain/warehousing/tasks/register-items-advanced-warehousing.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/warehousing/tasks/register-items-advanced-warehousing.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @ShylaThompson
* Microsoft Alias: **shylaw**

**Comment by sericks007** [comment]
@aliveaydin, thanks for providing this feedback.

@kamaybac, please review.

**Comment by sericks007** [comment]
Bug 507308 has been logged to track this issue.

**Comment by kamaybac** [comment]
@aliveaydin , we have expanded the topic a bit and added some illustrations to make the procedure more clear.
