### ISSUE TITLE
Create a copy of the source database (errors)

### ISSUE THREAD

**Issue by aaronstackpole** [MicrosoftDocs/dynamics-365-unified-operations-public#2743]
When executing the SQL script to RESTORE database, we get this error:

Msg 3234, Level 16, State 2, Line 4
 Logical file 'AXDBBuild_Data' is not part of database 'AxDB_CopyForExport'. Use RESTORE FILELISTONLY to list the logical file names.
 Msg 3013, Level 16, State 1, Line 4
 RESTORE DATABASE is terminating abnormally.

Please update the script as needed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8eb7ed3e-f7b9-e384-7308-516deda06bcc
* Version Independent ID: 3cd2e0d0-24fd-c019-eecc-8af6e7e7e66c
* Content: [Golden configuration promotion - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/dbmovement-scenario-goldenconfig)
* Content Source: [articles/fin-ops-core/dev-itpro/database/dbmovement-scenario-goldenconfig.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/database/dbmovement-scenario-goldenconfig.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laneswenka**

**Comment by sericks007** [comment]
@aaronstackpole, thanks for providing this feedback.

@laneswenka, please review and update the content, as needed.

**Comment by sericks007** [comment]
Bug 8305783 has been logged to track this issue.
