### ISSUE TITLE
BC deployment

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics-365-unified-operations-public#2745]
Can LCS be used for Business Central deployment?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: feb1c10e-1287-6db3-5ed6-315cb76fc1cd
* Version Independent ID: 85966417-fa61-ffa8-22e3-fa2bfa0e50ff
* Content: [All-in-one deployable packages - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/aio-deployable-packages)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/aio-deployable-packages.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-tools/aio-deployable-packages.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by sericks007** [comment]
@makdaddy8888, thanks for providing feedback here.  You might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your question from the Dynamics community. 

@laneswenka, please respond to the question.

**Comment by sericks007** [comment]
Bug 8305794 has been logged to track this issue.

**Comment by laneswenka** [comment]
These instructions are for Finance and Operations.  For information on Business Central please go to: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/?toc=/dynamics365/business-central/toc.json#resources-for-an-administrator
