### ISSUE TITLE
There is an extra 'that' in the artical 'build debug projects'

### ISSUE THREAD

**Issue by qiufozhe** [MicrosoftDocs/dynamics-365-unified-operations-public#2749]
[Enter feedback here]
We can see that[ in this artical](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/build-debug-project)， under the **add the validation code** part, there is a sentence **To solve the problem of expired credit cards, you’ll add an event handler, which you’ll use to verify that that the credit card isn’t expired.**

There are 2 'that' used here, and personaly I think this is not correct. Please help confirm and update if you agree with me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1abc350-6abd-b03b-7a76-2022928271ae
* Version Independent ID: 52c4a7e4-f0e0-6c41-5bbd-5ad2efce752f
* Content: [Build and debug projects - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/build-debug-project)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/build-debug-project.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-tools/build-debug-project.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @pvillads
* Microsoft Alias: **pvillads**

**Comment by kfend** [comment]
@qiufozhe - thank you for the feedback. We have updated the topic and the changes will be published today.
