### ISSUE TITLE
Incorrect approach (overlay vs extension)

### ISSUE THREAD

**Issue by jaestevan** [MicrosoftDocs/dynamics-365-unified-operations-public#275]
This phrase is not correct (or I don't understand the wording correctly):  "Create a project that belongs to the model where you must add the new label extension. For this example, the project is named ApplicationSuite."

Creating the label on the model where the label exists assumes overlayering. A new model (or an existing custom one) that references the original model must be used as an extension, as explained here: https://docs.microsoft.com/it-it/dynamics365/unified-operations/dev-itpro/extensibility/customization-overlayering-extensions#label-extensions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 233d83d4-b489-a31d-40da-35e4e29dc901
* Version Independent ID: ef9ca1d6-0af5-1a8e-31a7-b71bdc8a3dbf
* Content: [Change a label - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/extensibility/change-label)
* Content Source: [articles/dev-itpro/extensibility/change-label.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/extensibility/change-label.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @smithanataraj
* Microsoft Alias: **smnatara**

**Comment by ShylaThompson** [comment]
@jaestevan The following topic should have information that clears up the confusion. https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/extensibility/customization-overlayering-extensions#label-extensions
