### ISSUE TITLE
moving enviroment

### ISSUE THREAD

**Issue by jlabustro** [MicrosoftDocs/dynamics-365-unified-operations-public#2750]
is this article also applicable for the CE environment that we created?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f123c2b2-f125-19eb-85fc-7d216dacba26
* Version Independent ID: 6f249ad8-0852-356e-0612-13b8070b31c7
* Content: [Move licenses between agreement types - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/move-licenses-between-agreement-types)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/move-licenses-between-agreement-types.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/get-started/move-licenses-between-agreement-types.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @ClaudiaBetz-Haubold
* Microsoft Alias: **chaubold**

**Comment by kfend** [comment]
@jlabustro - thank you for the question. 
@ClaudiaBetz-Haubold - Can you answer this question?

**Comment by ClaudiaBetz-Haubold** [comment]
This article only pertains to Finance and Operations apps where environments are managed in Lifecycle Services.
Kind regards, Claudia Betz-Haubold
