### ISSUE TITLE
BYOD export job (from D365 F&O to Azure SQL DB) failed due to special characters in the SQL account password

### ISSUE THREAD

**Issue by rizal-ang** [MicrosoftDocs/dynamics-365-unified-operations-public#2753]
Hi there,

If this has not been raised before, I'd like to suggest a note to be included in the Microsoft Docs (around BYOD), suggesting not to use special characters (such as "~") as the password of the SQL account in the SQL DB. 

Even though publishing entity to the SQL DB was successful, the export job in D365 F&O failed and no information/logs exist to say what caused the problem, giving me so much headache.

Hopefully this suggestion is of any use.

Thanks.

RA
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33f75161-0776-a6c1-dc10-dc20ea26973f
* Version Independent ID: 55a81394-4606-745a-9fd2-59fb257d1086
* Content: [Bring your own database (BYOD) - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/export-entities-to-your-own-database)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/export-entities-to-your-own-database.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/export-entities-to-your-own-database.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by Sunil-Garg** [comment]
Hello rizal-ang-- thanks for catching this and reporting to us. We will investigate as to why the jobs fail when this happens. Thanks.
