### ISSUE TITLE
Term is confusing.

### ISSUE THREAD

**Issue by andyNewnham** [MicrosoftDocs/dynamics-365-unified-operations-public#2754]
The use of the term: Microsoft Dynamics 365 Commerce ratings and reviews moderation tool - is confusing as a separate tool for this does not exist - it is just part of and within e-commerce site builder. It is also referred to as 'Reviews administration tool' in the diagram on this page https://docs.microsoft.com/en-us/dynamics365/commerce/ratings-reviews-overview. Which is correct? The inconsistencies in terms make it difficult to train consultants and end users on the functionality.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60dea3e6-90a2-53cf-c932-ef8feb53a95f
* Version Independent ID: d8eb302d-fbb2-9858-d96e-833574993355
* Content: [Manage ratings and reviews - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/manage-reviews#feedback)
* Content Source: [articles/commerce/manage-reviews.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/manage-reviews.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @gvrmohanreddy
* Microsoft Alias: **gmohanv**

**Comment by RobinARH** [comment]
@gvrmohanreddy @v-chgri 

Can you take a look at this one? Thanks.

**Comment by RobinARH** [comment]
Bug 511421 created to track this issue.

**Comment by RobinARH** [comment]
This doc has been updated and published.
