### ISSUE TITLE
Typo on page?

### ISSUE THREAD

**Issue by jimwillsher** [MicrosoftDocs/dynamics-365-unified-operations-public#2755]
[Enter feedback here]
Hi, the purple box near the bottom refers to version 10.**1**.13. Currently released product is 10.**0**.13, with 10.0.14 in PEAP. Is this a typo?

Many thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85ad711b-bfb4-204c-1cde-322a20187f82
* Version Independent ID: 3cbbbe8c-2893-c449-598d-c22a4f1a9958
* Content: [Stay compliant with user licensing requirements - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/stay-compliant-user-license-requirement#additional-resources)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/stay-compliant-user-license-requirement.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/sysadmin/stay-compliant-user-license-requirement.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @Peakerbl
* Microsoft Alias: **chaubold**

**Comment by sericks007** [comment]
@jimwillsher, thank you for letting us know about the typo!  This had been fixed and the updated content will be published soon.
