### ISSUE TITLE
Azure Application permissions?

### ISSUE THREAD

**Issue by BSLATTER** [MicrosoftDocs/dynamics-365-unified-operations-public#2756]
Is it possible to get information on what permissions are required in the Azure Application?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c1841da-9abc-bad3-be64-6523be61ae70
* Version Independent ID: d7d6083b-8e1e-d439-91bc-d5dd8f5eddca
* Content: [Business events and Azure Service Bus - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/business-events/how-to/how-to-servicebus#register-a-new-application)
* Content Source: [articles/fin-ops-core/dev-itpro/business-events/how-to/how-to-servicebus.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/business-events/how-to/how-to-servicebus.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @ibenbouzid
* Microsoft Alias: **imbenbou**

**Comment by sericks007** [comment]
@BSLATTER, thank you for providing feedback here.

@Sunil-Garg, please review and update the content, as needed.

**Comment by ibenbouzid** [comment]
It is specified in documentation section Register an Application.You need Get and List Secret permision for your  KeyVault--ImadOn 14 Sep 2020 22:10, BSLATTER <notifications@github.com> wrote:

Is it possible to get information on what permissions are required in the Azure Application?



Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

ID: 1c1841da-9abc-bad3-be64-6523be61ae70Version Independent ID: d7d6083b-8e1e-d439-91bc-d5dd8f5eddcaContent: Business events and Azure Service Bus - Finance & Operations | Dynamics 365Content Source: articles/fin-ops-core/dev-itpro/business-events/how-to/how-to-servicebus.mdService: dynamics-ax-applicationsProduct: ****Technology: ****GitHub Login: @ibenbouzidMicrosoft Alias: imbenbou
