### ISSUE TITLE
Looking for explanation on asyncState parameter in the Global::runAsync method

### ISSUE THREAD

**Issue by ibruynin** [MicrosoftDocs/dynamics-365-unified-operations-public#2758]
There is no documentation on the asyncState parameter.
Can this be provided?

I hope this solves passing the return values of the method that was called asynchronously to the calling method.
Code below is simplified (hope it still makes the point)
```
A() 
{
  runAsync (B(), [i], callbackforB())
}

container B(int i) 
{
return [10];
}

void callbackforB(AsyncTaskResult _result) 
{
    container c = _result.getResult();
    int i = str2Int(conPeek(c, 1));
    // so far so good, we have i = 10 here
    // now how to pass it back to A?
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7a6baaa-f14c-87e6-50d0-e17cbba11bfc
* Version Independent ID: f58f2af9-0d54-dc2a-acea-7fcdb7212dbf
* Content: [xGlobal class - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-ref/system-classes/xglobal-class)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-ref/system-classes/xGlobal-class.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-ref/system-classes/xGlobal-class.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **rhaertle**

**Comment by RobinARH** [comment]
Hi Ian - I'm currently doing some work in these docs. I'll add this to my list of updates, but it's still going to take a couple of months. - Robin

Bug 506289 created to track this issue.

**Comment by RobinARH** [comment]
Hi - I'm not going to be updating this doc. - Robin
