### ISSUE TITLE
How do I connect to the SQL database on my Sandbox environment? --> Outdated

### ISSUE THREAD

**Issue by beefcake123** [MicrosoftDocs/dynamics-365-unified-operations-public#2759]
Section "How do I connect to the SQL database on my Sandbox environment?" is outdated after removal of 'RDP access'. This needs to be updated to support the new way-of-work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5080f3d7-0ad1-940c-284a-92008d7c19d5
* Version Independent ID: c911e39b-82ee-2ae3-4493-d2e39afccc2b
* Content: [Cloud deployment overview - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/cloud-deployment-overview)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/cloud-deployment-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/deployment/cloud-deployment-overview.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @AngelMarshall
* Microsoft Alias: **tsmarsha**

**Comment by RobinARH** [comment]
@AngelMarshall Can you take a look? Thanks.

**Comment by AngelMarshall** [comment]
Hi Robin,

Is it about the RDP removal?  If so, @Lane Swenka<mailto:Lane.Swenka@microsoft.com> would probably have better insight on this impact on SQL DB connection.


Thanks!
Angel

**Comment by sericks007** [comment]
@laneswenka, please review and update the content, as needed.

**Comment by RobinARH** [comment]
Bug 511436 created to track this issue.
