### ISSUE TITLE
Aging report is horrible to set-up !! It's unnecessarily confusing to set up parameters !

### ISSUE THREAD

**Issue by advent77** [MicrosoftDocs/dynamics-365-unified-operations-public#2762]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2905850a-1484-f4a7-b156-94fa0ddc3570
* Version Independent ID: 6bb2f10c-f60b-a2c8-45ca-b4d9a7992bb6
* Content: [Set up and generate accounts receivable aging information - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/accounts-receivable/tasks/set-up-accounts-receivable-aging-information)
* Content Source: [articles/finance/accounts-receivable/tasks/set-up-accounts-receivable-aging-information.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/accounts-receivable/tasks/set-up-accounts-receivable-aging-information.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @mikefalkner
* Microsoft Alias: **mfalkner**

**Comment by sericks007** [comment]
@advent77, thank you for providing feedback.

@roschlom, please review and assign to the appropriate PM.

**Comment by sericks007** [comment]
Bug 509455 has been logged to track this issue.

**Comment by sericks007** [comment]
The [Customer aging report](https://docs.microsoft.com/en-us/dynamics365/finance/accounts-receivable/customer-aging) has been updated to address this feedback.
