### ISSUE TITLE
Example are not useful enough to understand

### ISSUE THREAD

**Issue by Neeraj2912** [MicrosoftDocs/dynamics-365-unified-operations-public#2763]
[Enter feedback here]
Example given in the document is not explained with the purpose of using the formula. It would be better to include the real scenarios/ purposes where this function can be utilized. We use this formula to get the Enum values from label text, but example given is to compare the values and stored as boolean. It would be really helpful, if example can given for using it to get the enum values as a list from the formula and stored as record list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfb60b9a-b07f-64b5-5d60-03c7764051e5
* Version Independent ID: e4566fe2-0644-5a6b-fea9-a827831eff30
* Content: [GETENUMVALUEBYNAME ER function - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/er-functions-text-getenumvaluebyname)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/er-functions-text-getenumvaluebyname.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/er-functions-text-getenumvaluebyname.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @NickSelin
* Microsoft Alias: **nselin**

**Comment by sericks007** [comment]
@Neeraj2912, thank you for providing this feedback.

@NickSelin, please review and update the content, as needed.

**Comment by kfend** [comment]
@Neeraj2912  - The topic has been updated with more information. Thanks!
