### ISSUE TITLE
Would be useful to include a complete definition and description of FieldSize, Precision, and Scale in D365 F&O

### ISSUE THREAD

**Issue by ronsonntag54** [MicrosoftDocs/dynamics-365-unified-operations-public#2765]
[Enter feedback here]
Many real number fields inherit back many levels. At each level, there is a trade-off between the stated number of decimals (has an actual number or is Auto) and scale. I've been told and read that total FieldSize for Real numbers is a maximum of 16 even though SQL stores as numeric(36,6). Also, there are these rules that if No. of Decimals remains as Auto all the way to the top of the inheritance, we should assume a scale of 2. Nevermind that DMFDeinitionGroupEntityXMLFields are not populated correctly for Real FieldTypes!

Suggest a full treatment here to create a table that establishes once and for all how to determine the correct FieldSize, Scale and Precision of Real FieldTypes in D365 F&O by tracing fields through their inheritance and deciding what to do when encountering Auto, IsNotInheritable, Display Width, Scale, NoOfDecimals, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4be50ccc-ed32-eabe-c717-cf2b319d6d22
* Version Independent ID: 4f8d76c5-2ca7-b191-9317-15bfdbb7b3fc
* Content: [Extending decimal point precision for selected data types - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/extensibility/decimal-point-precision)
* Content Source: [articles/fin-ops-core/dev-itpro/extensibility/decimal-point-precision.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/extensibility/decimal-point-precision.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @LarsBlaaberg
* Microsoft Alias: **lolsen**

**Comment by josaw1** [comment]
Thanks for the feedback. @LarsBlaaberg can you please review?

**Comment by ronsonntag54** [comment]
It is now Sep 29 **2021** and no response? Really! Microsoft, please pay attention as this is an issue on EVERY PROJECT I have been on regarding D365 F&O. Other competing products do NOT have this level of lack of documentation and support. Please pay attention!

**Comment by josaw1** [comment]
@twheeloc can you please find a PM who can help with this? Thanks.

**Comment by twheeloc** [comment]
@MichaelFruergaardPontoppidan, would you please review and updated as needed?

**Comment by josaw1** [comment]
Closing as won't fix.
