### ISSUE TITLE
Why are all users except the admin will be set to Disabled status when exporting a DB?

### ISSUE THREAD

**Issue by alexander-lsretail** [MicrosoftDocs/dynamics-365-unified-operations-public#2767]
Why are all users except the admin set to Disabled status when exporting a DB? We do testing on our LCS environment and normally take a DB backup before we perform those tests. In many cases we'd like to import the DB back in after we perform our tests. We have a whole team that needs access to the environment and it's very inconvenient for the admin to have to enable users after a DB import. Is this going to change or are we expected to share one admin account? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60bd86ae-4fe1-1cb0-275b-11801c67a1d0
* Version Independent ID: a6110234-8568-8600-1c13-602f0c2d2d44
* Content: [Export a database - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/export-database#data-elements-that-arent-exported)
* Content Source: [articles/fin-ops-core/dev-itpro/database/export-database.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/database/export-database.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laneswenka**

**Comment by josaw1** [comment]
Thanks for the comment. @laneswenka can you please take a look?

**Comment by laneswenka** [comment]
Hello!  The principle is the same as when we copy a database between sandbox environments or between Production and UAT for example.  We lock the environment down to the administrator user who can then properly reconfigure the environment for use in the target, whether that is enabling specific users, all users, specific batch jobs, SMTP, and so forth.

**Comment by laneswenka** [comment]
Have you looked at the point-in-time restore functionality?  If you are testing every Wednesday for example, on Friday you could use point in time restore back to Tuesday.

**Comment by alexander-lsretail** [comment]
@laneswenka thanks for the reply. Your explanation for why you'd want to disable users when copying between environments makes sense to me.

For point-in-time restore, this page says that users are also disabled.

https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/database-pitr-prod-sandbox#data-elements-that-arent-copied-during-restore-copy

So will we run into the same problems as we did with exporting and restoring a DB backup? I noticed the section starts with an explanation for refreshes between environments -"When you refresh a production environment to a sandbox environment, or a sandbox environment to another sandbox environment, some elements of the database aren't copied over to the target environment."

If we're refreshing from and to the same environment, not between environments, will users still be disabled?

**Comment by josaw1** [comment]
BUG 510663 created to track the conversation.

**Comment by laneswenka** [comment]
That is the process to copy a PIT of PROD database over to Sandbox.  In that case, the users would be disabled.  But if you look at PITR functionality here the database is kept as-was and returned to you.  No users are enabled or disabled.https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/database-point-in-time-restore
