### ISSUE TITLE
Second paragraph states: "Although no out-of-box user interface (UI) for setting attribute values is available in the POS, you can extend the POS to add a new UI." However this UI was added in 8.1.3 as the specific section later in the document demonstrates

### ISSUE THREAD

**Issue by andyNewnham** [MicrosoftDocs/dynamics-365-unified-operations-public#2768]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: daca1f9e-c913-eb05-1a7d-23e6a54fc782
* Version Independent ID: f6ab1665-4c15-c2ed-9bf0-f5411295840a
* Content: [Define and set order attributes - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/order-attributes)
* Content Source: [articles/commerce/dev-itpro/order-attributes.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/dev-itpro/order-attributes.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by josaw1** [comment]
Thank you for your feedback. @mugunthanm can you please review?

**Comment by josaw1** [comment]
BUG 510669 created to track.

**Comment by josaw1** [comment]
The topic was updated. Thanks.
