### ISSUE TITLE
Adding RetailSDK to Source Control - cloaked items

### ISSUE THREAD

**Issue by RobvanB** [MicrosoftDocs/dynamics-365-unified-operations-public#2769]
The step to add the retailSDK to source control says to make sure there are no excluded items.
However, with my fresh 10.0.12 dev instance, there are a large number of items that are cloaked, and as such cannot be added.
Is that a problem with the VM, or does the documentation need updating?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55c7ea05-69b5-1c5e-eb55-07066a1b2d17
* Version Independent ID: b75e9d43-6590-60bd-ca34-83c40abd9ae6
* Content: [Set up new environments, Azure DevOps, and branches for Commerce projects - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/new-environments-visual-studio-teams-branch-retail-projects#prepare-the-development-environment)
* Content Source: [articles/commerce/dev-itpro/new-environments-visual-studio-teams-branch-retail-projects.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/dev-itpro/new-environments-visual-studio-teams-branch-retail-projects.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @andreashofmann1
* Microsoft Alias: **andreash**

**Comment by josaw1** [comment]
Thanks for your feedback. @andreashofmann1 please take a look.

**Comment by josaw1** [comment]
BUG 510672 created to track.

**Comment by josaw1** [comment]
The note was added to the topic. Thanks.
