### ISSUE TITLE
List of available methods is incomplete, covers only SysQueryRangeUtil

### ISSUE THREAD

**Issue by torbennehmer** [MicrosoftDocs/dynamics-365-unified-operations-public#277]
There are many more methods, which are supported by other classes then SysQueryRangeUtil with many useful methods. The listing here should be extended to cover as much as possible of these interfaces. For example HcmWorkerLookup::currentWorker().

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f307ed75-4498-8c54-13ed-a9c25d8a286b
* Version Independent ID: 8f4e1122-fa74-4e64-8a5d-80d6ddd58201
* Content: [Advanced filtering and query syntax - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/advanced-filtering-query-options)
* Content Source: [articles/fin-and-ops/get-started/advanced-filtering-query-options.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/advanced-filtering-query-options.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by tonyafehr** [comment]
Thanks for taking the time to provide feedback. Your comment has been noted as a future enhancement to the documentation.
