### ISSUE TITLE
incorrect information in step 29

### ISSUE THREAD

**Issue by XiaoliangHuang** [MicrosoftDocs/dynamics-365-unified-operations-public#2772]
There is a typo in the description.

in step 29: when set the trade agreement line, it should be the "Party code type", but not "Account type" that to set value "Group"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61ae039b-4b9a-7957-c5ae-e0dcb05a2879
* Version Independent ID: ccba2c88-c979-ec12-cb0e-37188f641e91
* Content: [Base price and trade agreements - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/tasks/base-price-trade-agreements)
* Content Source: [articles/commerce/tasks/base-price-trade-agreements.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/tasks/base-price-trade-agreements.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by RobinARH** [comment]
@josaw1 Can you take a look? Thanks.

**Comment by RobinARH** [comment]
Bug 511430 created to track this issue.

**Comment by josaw1** [comment]
Step updated. Will be published later today.
