### ISSUE TITLE
please correct sentence "...the apps from Finance and Operations will be synchronized"

### ISSUE THREAD

**Issue by BernhardRaether** [MicrosoftDocs/dynamics-365-unified-operations-public#2776]
The sentence is wrong:
With the dual-write functionality enabled, the apps from Finance and Operations will be synchronized in other Dynamics 365 apps in Draft state.

...Not the **Apps** from F&O will be synchronized, but the **Products**

Thanks for checking and fixing,
Bernhard

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a19d287f-1a09-4abb-1265-19d0be0bad1a
* Version Independent ID: 9b7eec43-2a44-fe69-7c9a-e6153fc115ee
* Content: [Unified product experience - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/product-mapping)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/product-mapping.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/dual-write/product-mapping.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @t-benebo
* Microsoft Alias: **ramasri**

**Comment by RobinARH** [comment]
@t-benebo Can you take a look? Thanks.

**Comment by RobinARH** [comment]
We updated this topic.
