### ISSUE TITLE
Deprecated the async import/export

### ISSUE THREAD

**Issue by FangyuanHou** [MicrosoftDocs/dynamics-365-unified-operations-public#2779]
With the new release of Dynamics 365 F&O Platform updates for 10.0.13, we have deprecated the async import/export, instead schedule a one-time batch for export and import and batch get scheduled without showing any batch UI.

Can you please update in the docs? Looks like PG only enable the DMFLegacyAsyncExport flighting with a strong business justification. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d35f4fb2-1296-20ef-56c2-a2c5aa00befe
* Version Independent ID: 0d515af9-9419-4f21-223e-25344cf1bfe8
* Content: [Data import and export jobs overview - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/data-import-export-job#run-the-import-or-export-job)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/data-import-export-job.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/data-import-export-job.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by tonyafehr** [comment]
@FangyuanHou, thanks for the feedback. 
@Sunil-Garg, please review.

**Comment by FangyuanHou** [comment]
@Sunil Garg<mailto:sunilg@microsoft.com>, could you please check on this?

Best Regards
Fangyuan Hou (Fang)

**Comment by Sunil-Garg** [comment]
@FangyuanHou thanks for the feedback. The doc update has been submitted. Thanks.
