### ISSUE TITLE
No link provided for the setup to make the data in Analytics available

### ISSUE THREAD

**Issue by Neeraj2912** [MicrosoftDocs/dynamics-365-unified-operations-public#2780]
In the document, features are described as available in the Bank Management Workspace, but it would be very useful, if the links for the required setup would be there like; how to enable the data/ refresh the data to make the Analytics available in the workspace. Because by default data comes blank in the Bank Management Workspace >> Analytics. 

Hope the link /additional resources can be added.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6fe4190-9d7a-6c3d-27e2-04c9c969a493
* Version Independent ID: dc80f40a-6315-2df9-3b33-8a59731bd5cd
* Content: [Bank management workspace - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/cash-bank-management/bank-management-workspace)
* Content Source: [articles/finance/cash-bank-management/Bank-management-workspace.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/cash-bank-management/Bank-management-workspace.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @saraschi2
* Microsoft Alias: **saraschi**

**Comment by tonyafehr** [comment]
@Neeraj2912, thanks for the feedback.
@rschloma, please assign this to the current topic author.

**Comment by tonyafehr** [comment]
Bug 511734 logged to track this issue.

**Comment by roschlom** [comment]
Thank you again for letting us know. We've added a link and it should be available in the topic within the next 24 hours. Have a great day!
