### ISSUE TITLE
Data entity naming restriction (no digits, no underscore) still valid?

### ISSUE THREAD

**Issue by DAXaholic** [MicrosoftDocs/dynamics-365-unified-operations-public#2782]
> The name of an entity must not have '_' or any numeric digits (0…9). Using these characters may result in mapping errors later.

Is this restriction still valid and necessary?  
There are numerous examples in the application which violates this (just search via `type:"data entity" (_|[0-9])` in the Application Explorer), especially all new revisions of existing entities like `CustCustomerV3Entity`.  

Background of the question
We use the prefix `WK_` for our own elements in order to avoid naming collisions as there are no namespaces in this product.  
Since an underscore is listed as a technical restriction in this document and as a bad practice in the document about entity naming, I am wondering whether we are still required to avoid it.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67eb6eeb-d9fc-4e83-6282-fff9783b1466
* Version Independent ID: f16158fb-2a9b-6429-dd3e-05d4d1e1650b
* Content: [Build and consume data entities - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/build-consuming-data-entities)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/build-consuming-data-entities.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/build-consuming-data-entities.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by tonyafehr** [comment]
@DAXaholic, thanks for the feedback. 
@Sunil-Garg, please review.

**Comment by tonyafehr** [comment]
Bug 511733 logged to track this issue.

**Comment by jboehm-cayman** [comment]
I have run into this issue as well, and I'm interested in the outcome.
