### ISSUE TITLE
Edge Chromium required ClickOnce flag setting

### ISSUE THREAD

**Issue by jopankow** [MicrosoftDocs/dynamics-365-unified-operations-public#2784]
Hello, 

Please add this additional information for steps on how to enable ClickOnce for the new Microsoft Edge based on Chromium under the "Issue 1: Report Designer doesn't start when you select New or Edit" section. Please change the text as needed for formatting consistency:

1. Open a new browser tab in Microsoft Edge.
2. Enter edge://flags and click enter.
3. Search for the **ClickOnce Support** option. You can search for it, or try this direct link: edge://flags/#edge-click-once
4. Set the drop-down to **Enabled**.
5. Click **Restart Browser** option.

Please let me know if you have any questions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 039e1ed0-5b6b-04b9-4a76-9588eeeefc65
* Version Independent ID: 0c019c41-e6b1-2ae6-89e5-cd4cddef1d3f
* Content: [Financial reporting overview - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/general-ledger/financial-reporting-getting-started#troubleshooting-issues-opening-report-designer)
* Content Source: [articles/finance/general-ledger/financial-reporting-getting-started.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/general-ledger/financial-reporting-getting-started.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @aprilolson
* Microsoft Alias: **aolson**

**Comment by tonyafehr** [comment]
@jopankow, thanks for the feedback.
@aprilolson, please re-assign, if needed.

**Comment by tonyafehr** [comment]
Bug 511735 logged to track this issue.

**Comment by jinniew** [comment]
@tonyafehr , I've added the suggested text above to the Content Source as noted below, please note that I added it to the bottom and left the instructions on how to do the same in IE.

* If you use the Microsoft Edge based on Chrome browser, you must install a ClickOnce extension in order to download the Report Designer client. If you are running incognito mode, make sure the ClickOnce extension is enabled for incognito mode. 
     1. Open a new browser tab in Microsoft Edge.
     2. Enter **edge://flags** and click enter.
     3. Search for the **ClickOnce Support** option. You can search for it, or try this direct link: **edge://flags/#edge-click-once**
     4. Set the drop-down to **Enabled**.
     5. Click **Restart Browser** option..

**Comment by jopankow** [comment]
Hi @jinniew and @tonyafehr . I didn't catch this before but I just noticed the steps are incorrect when reviewing the instructions for a customer.

These sentences are wrong: "_If you use the Microsoft Edge based on Chrome browser, you must install a ClickOnce extension in order to download the Report Designer client. If you are running incognito mode, make sure the ClickOnce extension is enabled for incognito mode._" 

It looks like two separate unrelated items got combined together. There needs to be two separate bullet points here:

1. For Chrome. Chrome does not have built-in support for ClickOnce. So you must install a Chrome ClickOnce extension. The bullet point for Chrome should read:

- If using the Chrome browser, you must install a ClickOnce extension in order to download the Report Designer client. If you are running Chrome in incognito mode, make sure the ClickOnce extension is enabled for incognito mode. Refer to the Note here https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/system-requirements for information on the Chrome ClickOnce Extension.

2. For the Microsoft Edge based on Chromium (not the legacy version of Edge) bullet point. You do not need to install a ClickOnce extension for Edge Chromium, but you must enable the ClickOnce flag. These steps are accurate for Edge Chromium:

- If using the Microsoft Edge based on Chromium browser, not Edge Legacy, you must enable the ClickOnce flag:

i. Open a new browser tab in Microsoft Edge based on Chromium.
ii. Enter edge://flags and click enter.
iii. Search for the ClickOnce Support option. You can search for it, or try this direct link: edge://flags/#edge-click-once
iv. Set the drop-down to Enabled.
v. Click Restart Browser option.

These two separate items need their own bullet points and cannot be combined.

**Comment by tonyafehr** [comment]
@jopankow, thanks for the info.  
@jinniew, please review. Thanks!
