### ISSUE TITLE
Deprecated features for update 15

### ISSUE THREAD

**Issue by AnaKazakova** [MicrosoftDocs/dynamics-365-unified-operations-public#279]
Hi, 
It's mentioned that no features have been removed or deprecated in the release 15, 14 and 13.
I can't help but notice that the customer v2 data entity is now obsolete, and there is the new version v3 compared to update 12. 
Is there any place where it is possible to find what objects are changed to the new ones?
I think it is important to know, as we have some extensions that will have to be moved manually to make sure that functionality stays the same...
Kind regards,
Ana

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d602e19-4bf5-d573-e2e6-8a147cb9db4a
* Version Independent ID: 5d9cc5b3-4c58-ae58-3690-3c25d7f20063
* Content: [Deprecated features - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/deprecated-features#dynamics-365-for-finance-and-operations-enterprise-edition-73-with-platform-update-12)
* Content Source: [articles/dev-itpro/migration-upgrade/deprecated-features.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/migration-upgrade/deprecated-features.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @sericks007
* Microsoft Alias: **sericks**

**Comment by sericks007** [comment]
Sunil, please indicate which data entities have been deprecated or removed. Thanks

**Comment by sericks007** [comment]
I discussed this with Sunil, and we added this note to the article: Detailed information about objects in Finance and Operations can be found in the Technical reference reports. You can compare the different versions of these reports to learn about objects that have changed or been removed in each version of Finance and Operations.  (The link to the Technical reference reports is: https://mbs.microsoft.com/customersource/northamerica/AX/downloads/reports/axtechrefrep)
