### ISSUE TITLE
Add Virtual Entities to Choose a data integration strategy

### ISSUE THREAD

**Issue by jawn** [MicrosoftDocs/dynamics-365-unified-operations-public#2790]
[Virtual Entities](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/power-platform/faq) support has recently been added.

Hence, it would be practical to add it to this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2cdcdc3-398f-f785-d02e-cc784d91869c
* Version Independent ID: c7ec7a85-c489-f8c5-33c1-68f622108741
* Content: [Choose a data integration strategy - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/integration-overview)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/integration-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/integration-overview.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by sericks007** [comment]
@jawn, thanks for the suggestion!

@Sunil-Garg, please update the content with this suggestion.

**Comment by sericks007** [comment]
Bug 512192 has been logged to track this issue.

**Comment by Sunil-Garg** [comment]
@jawn thanks for the feedback. The update to the guidance has been submitted. Thanks.
