### ISSUE TITLE
Get the list of upcoming updates udpated

### ISSUE THREAD

**Issue by abylkhatov** [MicrosoftDocs/dynamics-365-unified-operations-public#2793]
My customers are asking to get this page updated with a list of updates for the next 12 months from now, so that they can plan their projects. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7dcb285-f32c-c92e-fe49-1617f213066b
* Version Independent ID: 8f28c1a0-9da5-f853-90ee-d82a4c32df7e
* Content: [Service update availability - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/public-preview-releases)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/public-preview-releases.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/get-started/public-preview-releases.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @ShellyBakke
* Microsoft Alias: **smiller**

**Comment by sericks007** [comment]
@abylkhatov, thanks for sharing this feedback.

@ShellyBakke, please review and update the content.

**Comment by sericks007** [comment]
Bug 512195 has been logged to track this issue.

**Comment by lazejanev** [comment]
I agree with @abylkhatov this is very important for us so that the release management can be planned properly. Can we have the release calendar schedule for all of 2021? We don't need the features planned for the updates, just that update dates and also the end of service dates.

**Comment by lazejanev** [comment]
Hi @sericks007 can we please have some update on this?

**Comment by sericks007** [comment]
@ShellyBakke, please review and update the content.

**Comment by sericks007** [comment]
This content has been updated.
