### ISSUE TITLE
Error in URL

### ISSUE THREAD

**Issue by JulianMenn** [MicrosoftDocs/dynamics-365-unified-operations-public#2794]
In the section:
Enable debug mode to troubleshoot live synchronization issues in Finance and Operations apps

There is an error in the URL. It contains a character: ">" in the URL. It says:
https://XXXaos.cloudax.dynamics.com/?mi=SysTableBrowser&tableName=>DualWriteErrorLog
But should say:
https://XXXaos.cloudax.dynamics.com/?mi=SysTableBrowser&tableName=DualWriteErrorLog

Or better:
https://&lt;BaseFinanceandOperationsappsURL&gt;/?mi=SysTableBrowser&tableName=DualWriteErrorLog

As it uses that placeholder in the other docs as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac32a8bc-5c81-1b4c-5b7d-1700aa8847c4
* Version Independent ID: ba38f805-2126-4c7c-7ab5-c94fa1c65c90
* Content: [General troubleshooting - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/dual-write-troubleshooting)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/dual-write-troubleshooting.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/dual-write/dual-write-troubleshooting.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @RamaKrishnamoorthy
* Microsoft Alias: **ramasri**

**Comment by josaw1** [comment]
Thanks for your feedback. @RamaKrishnamoorthy can you please review?

**Comment by josaw1** [comment]
BUG 512809 created to track.

**Comment by josaw1** [comment]
URL is fixed.
