### ISSUE TITLE
"Copy the Sandbox database to Production" section does not cover Self-Service process

### ISSUE THREAD

**Issue by TeemuMiettinen** [MicrosoftDocs/dynamics-365-unified-operations-public#2795]
"Copy the Sandbox database to Production" section is for Microsoft-Hosted only for the new self-service process it needs to be updated. With self-service production you cant use Service Request anymore nor have an option to press +Add for creating one:
https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/dbmovement-scenario-goldenconfig#copy-the-sandbox-database-to-production

Correct route here is at LCS Production Environment Full detail page -> Maintain -> Move Database -> Refresh database (from other Environment) -> for Source Environment select GOLD or correspond Tier-2 environment.

Cheers,
Teemu

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8eb7ed3e-f7b9-e384-7308-516deda06bcc
* Version Independent ID: 3cd2e0d0-24fd-c019-eecc-8af6e7e7e66c
* Content: [Golden configuration promotion - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/dbmovement-scenario-goldenconfig)
* Content Source: [articles/fin-ops-core/dev-itpro/database/dbmovement-scenario-goldenconfig.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/database/dbmovement-scenario-goldenconfig.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by kfend** [comment]
@TeemuMiettinen - thank you for the feedback.
@laneswenka  - can you please take a look at and address this issue?

**Comment by laneswenka** [comment]
This has been updated.
