### ISSUE TITLE
Combination of backup and restore commands could lead to incorrect configuration promotion 

### ISSUE THREAD

**Issue by Ievgenm** [MicrosoftDocs/dynamics-365-unified-operations-public#2796]
Should it be INIT instead of "NOINIT"  in the backup database statement? Otherwise, if you already have a backup file since last run you will append it. Then with the next script that restores database you will restore first backup set in the file instead of one you've just created.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8eb7ed3e-f7b9-e384-7308-516deda06bcc
* Version Independent ID: 3cd2e0d0-24fd-c019-eecc-8af6e7e7e66c
* Content: [Golden configuration promotion - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/dbmovement-scenario-goldenconfig)
* Content Source: [articles/fin-ops-core/dev-itpro/database/dbmovement-scenario-goldenconfig.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/database/dbmovement-scenario-goldenconfig.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by kfend** [comment]
@Ievgenm - thank you for the feedback.
@laneswenka - can you please take a look at and address this issue?

**Comment by laneswenka** [comment]
We have removed the SQL script in favor of using SSMS backup/restore options.
