### ISSUE TITLE
How to manage custom fields for deliveries and dev

### ISSUE THREAD

**Issue by GeoffreyDelmee** [MicrosoftDocs/dynamics-365-unified-operations-public#280]
In a classic project, custom fields are really fine for protoyping.
Also, it gets close to the custom fields we can add in D365 Sales and already supports to be added into data entities. So it seems to be eligible for projects even with integration to manage.

But, by now, I don't see how I can move such elements from one environment to another one in order to manage it in test/UAT for prototyping and integration validation and then move it to the production.

Also, if further evolutions are required and business rules have to be written using those fields, how can we use those? Are those fields part of a special model/package we can reference in a dev environment?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 243a07df-1659-0c6e-6775-f6e86eabf287
* Version Independent ID: 1ef4dcc2-b1eb-7806-2eae-6db2951a7c12
* Content: [Custom fields - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/user-defined-fields)
* Content Source: [articles/fin-and-ops/get-started/user-defined-fields.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/user-defined-fields.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by tonyafehr** [comment]
Thanks for taking the time to provide this kind of feedback. I will pass this message on to the author and your suggestion will be noted as a future enhancement to this topic.

**Comment by leodas2004** [comment]
Any update on this?

**Comment by 3DFO** [comment]
Custom fields are ok for info only. You can't write code against them so their use is pretty limited in my opinion.

**Comment by federicocastro** [comment]
How could I add custom fields to other tables that are not shown in the list? e.g: Invoice Line.
