### ISSUE TITLE
I believe there is a wrong word used, which should be replaced

### ISSUE THREAD

**Issue by nmaroud** [MicrosoftDocs/dynamics-365-unified-operations-public#2800]
Dear all,

In my opinion the word "decreasing" (in <> in the text below), should instead be replaced with the word "increasing". What do you think?

_Main elements of the functionality
The auto-update shipment functionality relies primarily on the shipment status to determine whether the quantity on a load line should be changed when a change is made on a sales order line or transfer order line. It also relies primarily on the shipment status to determine when a new load line should automatically be added to an existing load. When the shipment status is Waved or higher, no automatic update occurs.

Wave status is also considered for automatic updates. When the wave that is related to the load line has a status of Held, Executing, Released, Picked, or Shipped, if a user tries to reduce the quantity on a load line (via a quantity decrease on the sales order line or transfer order line), the following error message is shown: "Reservations cannot be removed because there is work created which relies on the reservations." Additionally, when the wave has one of the previously mentioned wave statuses, if a user tries to indirectly increase the load line quantity by <decreasing> the quantity on the sales order line or transfer order line, the quantity on the load line isn't automatically increased. In this case, the load line must be manually updated._

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93e04a5a-e8ea-bc83-dd0a-54ec133f130b
* Version Independent ID: 7861128a-e964-4284-ca7c-5fd5fea80211
* Content: [Shipment auto-updates - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/warehousing/auto-update-shipment#feedback)
* Content Source: [articles/supply-chain/warehousing/auto-update-shipment.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/warehousing/auto-update-shipment.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @josaw1
* Microsoft Alias: **perlynne**

**Comment by RobinARH** [comment]
@kamaybac Can you take a look? Thanks.

**Comment by kamaybac** [comment]
@nmaroud , thank you for bringing this to our attention. You are entirely correct, the term should be "increasing". I have edited the page and the update should be live later today.
