### ISSUE TITLE
PBIX request

### ISSUE THREAD

**Issue by davecope1982** [MicrosoftDocs/dynamics-365-unified-operations-public#2801]
I was wondering if it was possible to get a copy of the Inventory Accounting Status pbix please? I can see that the doc here says this has been deprecated but the workspace still appears in V10.0.13 but is not available to download via LCS anywhere that i can see?

I have customers wanting to customise these reports but without access to the pbix this is practically impossible 

I can pull in the CostObjectStatementCacheMonthly aggregated measurement from the entity store into PBI deskstop but can see from the D365 front end web edit tool that a number of dax measures have been created within the pbix that i require access to 

Thanks

Dave

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2d5bfd3-1ddd-514b-0735-3ffac0a43787
* Version Independent ID: 575715a0-b64a-9a20-6212-cb304c7cd5c7
* Content: [Cost management Power BI content - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/cost-management-content-pack)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/cost-management-content-pack.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/cost-management-content-pack.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @ShylaThompson
* Microsoft Alias: **shylaw**

**Comment by RobinARH** [comment]
@kfend - Can you take a look? Thanks.

**Comment by RobinARH** [comment]
Bug 513696 created to track this issue.

**Comment by davecope1982** [comment]
any update on this please?

**Comment by kamaybac** [comment]
@davecope1982 , his issue landed in our backlog and I only just recently found it. I realize that this is very late in getting back to you, and unfortunately I don't have good news.  Support for those files was depreciated and then removed from the product in 2018. I looked into it and haven't been able to locate copies of those PBIX files, so I'm not able to help you with them. This topic describes the system that replaced that one, but I don't know whether it will do what you are looking for. If you need more help to customize the functionality, I recommend getting in touch with Microsoft Support.
