### ISSUE TITLE
Collections Status not disputed needs more detail.

### ISSUE THREAD

**Issue by ed-bcr** [MicrosoftDocs/dynamics-365-unified-operations-public#2802]
the documentation lists the definition of the status "Not disputed" as "No collections action has occurred for the transaction."
However when users select this option, no Collections History log item is created.  This should be mentioned in the document, as users are not aware that no log entry is created.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2e5f473-ffd5-c020-6ad3-cc93bc31e38c
* Version Independent ID: 104ef1a7-ad59-0ec8-6d27-b3b337bf261e
* Content: [Review collections information - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/accounts-receivable/tasks/review-collections-information)
* Content Source: [articles/finance/accounts-receivable/tasks/review-collections-information.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/accounts-receivable/tasks/review-collections-information.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @ShivamPandey-msft
* Microsoft Alias: **shpandey**

**Comment by tonyafehr** [comment]
@ed-bcr, thank you for the feedback. 
@ShivamPandeyMSFT, please review.

**Comment by panolte** [comment]
Thank you for your feedback.  We have updated the definition to include that collection history has not been created.
