### ISSUE TITLE
Article refers to an outdated agent version

### ISSUE THREAD

**Issue by VadimGoncharenko** [MicrosoftDocs/dynamics-365-unified-operations-public#2804]
'The latest version of the local agent is version 2.4.0, which was released in December 2019' statement is not up to date

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38d81ec9-52b0-5b29-282b-f5cf451ba746
* Version Independent ID: 6b1b4864-e2a8-d0f5-b0d1-5d04fa3e82ca
* Content: [Update the local agent - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/update-local-agent)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/update-local-agent.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/lifecycle-services/update-local-agent.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @faix
* Microsoft Alias: **osfaixat**

**Comment by tonyafehr** [comment]
@VadimGoncharenko, thank you for the feedback.
@faix, please review.

**Comment by faix** [comment]
@tonyafehr please close, a fix for this has already been merged
