### ISSUE TITLE
What is the name of the job history cleanup feature

### ISSUE THREAD

**Issue by rabol** [MicrosoftDocs/dynamics-365-unified-operations-public#2808]
[Enter feedback here]
It is stated that after update 29, one have to enable a feature to clean up the job history: Data management > Job history cleanup.

but what is the name of the feature ?

When looking at the Feature management it's not really clear which on to turn on

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d35f4fb2-1296-20ef-56c2-a2c5aa00befe
* Version Independent ID: 0d515af9-9419-4f21-223e-25344cf1bfe8
* Content: [Data import and export jobs overview - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/data-import-export-job)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/data-import-export-job.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/data-import-export-job.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by sericks007** [comment]
@rabol, thanks for providing this feedback.

@Sunil-Garg, please review and update the content, as needed.

**Comment by sericks007** [comment]
Bug 514265 has been logged to track this issue.

**Comment by Sunil-Garg** [comment]
@rabol thanks for the feedback, the feature name has been added in the doc and the update has been submitted. Thanks.
