### ISSUE TITLE
Time to deploy self-service environment varies in different pages

### ISSUE THREAD

**Issue by abylkhatov** [MicrosoftDocs/dynamics-365-unified-operations-public#2809]
In the ["Deploy a new environment page"](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/deployenvironment-newinfrastructure) it says "The environment deployment starts immediately and could take anywhere between **1-2 hours** to complete." But in ["Self-service deployment overview"](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/infrastructure-stack#whats-new-or-changed) page it says "Deployment is self-service and can be completed within an average time of **30 minutes**". Can we get the pages aligned? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c7f272b-4ea7-a285-4a9f-e67583a664e0
* Version Independent ID: 54ac0c3d-a2b5-6001-1581-167dd87a80c0
* Content: [Self-service deployment overview - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/infrastructure-stack#whats-new-or-changed)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/infrastructure-stack.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/deployment/infrastructure-stack.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @rashmansur
* Microsoft Alias: **rashmim**

**Comment by sericks007** [comment]
@abylkhatov, thanks for providing this feedback.

@rashmansur, please update the content, as appropriate.

**Comment by sericks007** [comment]
Bug 8514998 has been logged (in the LCS database) to track this issue.

**Comment by subglo** [comment]
good point, @abylkhatov i noticed this too

**Comment by josaw1** [comment]
This has been fixed.
