### ISSUE TITLE
Using Modes of Delivery in Retail implementation

### ISSUE THREAD

**Issue by ransoentjens** [MicrosoftDocs/dynamics-365-unified-operations-public#281]
This is a very clear, well written article on the best practices of implementing the Modes of Delivery. It's not a really complex topic, but having a couple of pretty realistic examples in the article is good for validation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ea69e87-44b0-9006-55a3-4463525e14fc
* Version Independent ID: a4f81153-17f2-605d-c7a3-ab71b25a04d1
* Content: [Configure call center delivery modes and charges - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/configure-call-center-delivery#feedback)
* Content Source: [articles/retail/configure-call-center-delivery.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/configure-call-center-delivery.md)
* Service: **dynamics-365-retail**
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by tonyafehr** [comment]
Thanks for taking the time to provide this kind of feedback. I will pass this message on to the author and your suggestion will be noted as a future enhancement to this topic.
