### ISSUE TITLE
What are the limits on external data mash ups?  This document contradicts itself

### ISSUE THREAD

**Issue by helloyesthisisdave** [MicrosoftDocs/dynamics-365-unified-operations-public#2812]
The **Overview** section states that:

>The integration of the application and Power BI enables data mash-up scenarios that require access to external data sources

however, the **Can I do data mash-ups by using external data in the embedded reports?** question in the FAQ states that:

>No, you can't currently do data mash-ups by using external data in the embedded reports.

Can this please be clarified?

Thanks.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 630034c6-dbcc-d365-d58b-36bef4277582
* Version Independent ID: ce5941a7-67bb-9c0a-c1ab-230fe8aff69f
* Content: [Power BI Embedded integration - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-gb/dynamics365/fin-ops-core/dev-itpro/analytics/power-bi-embedded-integration)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/power-bi-embedded-integration.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/power-bi-embedded-integration.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by josaw1** [comment]
Thank you for your feedback. @TJVass can you please take a look?

**Comment by josaw1** [comment]
BUG 514878 created to track.

**Comment by helloyesthisisdave** [comment]
Has there been an update on this?  All I am after is clarification on what is actually possible/supported and what is not.

**Comment by josaw1** [comment]
Removing the FAQ item.
