### ISSUE TITLE
Help make the docs more inclusive (dev-itpro)

### ISSUE THREAD

**Issue by RobinARH** [MicrosoftDocs/dynamics-365-unified-operations-public#2814]
Replace gendered pronouns in the dev docs according to our style guide.

Only work in this folder:
https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/tree/live/articles/fin-ops-core/dev-itpro

Using the instructions here:
https://docs.microsoft.com/en-us/style-guide/bias-free-communication

Please leave a note if you are working on this issue so that we don't duplicate effort.

Thanks!

**Comment by KaylaKremer** [comment]
Hi @RobinARH ,

I can work on this!

**Comment by bytemech** [comment]
Working on this :)

**Comment by RobinARH** [comment]
Hi - We're going to close this and work on it in-house.
