### ISSUE TITLE
Syntax (Finance and Operations query) (Finance and Operations query between parentheses) needs more illustration to make this feature more useful

### ISSUE THREAD

**Issue by Neeraj2912** [MicrosoftDocs/dynamics-365-unified-operations-public#2816]
The syntax (Finance and Operations query) (Finance and Operations query between parentheses) is highly useful feature, a separate section can be made for the same with more illustrations , this would definitely increase its usage as very few people use this awesome feature just because of lack of information in documents.

I can give an example like
When we try to filter out the field "Approved by" on the General Journal form, it doesn't support filter of not blank (!""). But using this syntax of matches
we can type ((LedgerJournalTable.Approvedby == 0)) and this filters out the records which are having blank value for "Approved by" field.

My suggestion is to provide more illustration from the experience of different industries. In case of any query related to this feedback, you can write me over mail "neeraj.kumar@acxiomconsulting.com".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e419ebf-7499-3448-bf9d-26136c551848
* Version Independent ID: 0ebeb915-82a6-63d6-98f2-ac4ce51b30f8
* Content: [Advanced filtering and query syntax - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/advanced-filtering-query-options)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/advanced-filtering-query-options.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/get-started/advanced-filtering-query-options.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by kfend** [comment]
@Neeraj2912 - thank you for this feedback. 
@jasongre - Can you take a look at this when you have a chance?
