### ISSUE TITLE
D365 Retail-POS-TypeScript- How to get customer search information in a custom control

### ISSUE THREAD

**Issue by phule80** [MicrosoftDocs/dynamics-365-unified-operations-public#282]
Hi there,

I have an issue and need your help.

By following the example(https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/dev-itpro/pos-view-extension ) I can get the customer information by extending POS view and app bar button. But my question is : in my custom control(Extensions), when I click on "Get Customer" button then the mouse will be focus on Search bar on the top to type CustomerID. After user selects the customer then I can get the customer information in my custom control.

If any one hv any idea, please help me. Thanks

**Comment by tonyafehr** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support)
