### ISSUE TITLE
Probably there is a sentence missing at Step 9

### ISSUE THREAD

**Issue by ReQ6W7rFnaBxyfb** [MicrosoftDocs/dynamics-365-unified-operations-public#2821]
In section Benefit eligibility policy, there should be a sentence item #9 describing a step involving the filtering field. There is a bullet point with an example of a filtering clause, but no *step* #9 to create a filter clause if desired.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e716afb8-75f1-de8c-9cd7-aaa0cd18565e
* Version Independent ID: 43c47ecc-907a-0aa1-e94c-c5aedb377b09
* Content: [Define benefit eligibility rules and policies - Human Resources | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/human-resources/hr-benefits-define-eligibility-rules)
* Content Source: [articles/human-resources/hr-benefits-define-eligibility-rules.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/human-resources/hr-benefits-define-eligibility-rules.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @andreabichsel
* Microsoft Alias: **anbichse**

**Comment by RobinARH** [comment]
@andreabichsel Can you take a look? Thanks.

**Comment by RobinARH** [comment]
Bug 516184 created to track this issue.
