### ISSUE TITLE
Documentation for label extensions

### ISSUE THREAD

**Issue by gertvdh** [MicrosoftDocs/dynamics-365-unified-operations-public#2825]
It's possible to extend labels too, can this be documented here too? And how to cope with multiple extensions on the same label file, how should the naming be done? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7526dd1-39d1-a882-8560-52c530ef5649
* Version Independent ID: 7dd2a62b-b310-595b-eeda-f746679bbf3c
* Content: [Extensibility home page - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/extensibility/extensibility-home-page?source=docs)
* Content Source: [articles/fin-ops-core/dev-itpro/extensibility/extensibility-home-page.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/extensibility/extensibility-home-page.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @FrankDahl
* Microsoft Alias: **fdahl**

**Comment by tonyafehr** [comment]
@gertvdh, thanks for the feedback.
@FrankDahl, please review.

**Comment by tonyafehr** [comment]
Bug 516073 logged to track this issue.

**Comment by tonyafehr** [comment]
This information is documented in the "Label extensions" section in  the [Customize through extension and overlayering](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/extensibility/customization-overlayering-extensions) topic. Thanks!
