### ISSUE TITLE
Navigation path is not correct

### ISSUE THREAD

**Issue by manbhat07** [MicrosoftDocs/dynamics-365-unified-operations-public#2826]
[Benefit Management Workspace > Set Up > Human Resources Parameters 
Benefit management Tab has the set up for "Benefit Verification" and "Auto Select Designess".]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6cb266b-f118-ce27-524f-c74813730934
* Version Independent ID: 12ac9119-ad6c-163e-91f3-b616167d4f00
* Content: [Set Benefits management parameters - Human Resources | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/human-resources/hr-benefits-setup-parameters)
* Content Source: [articles/human-resources/hr-benefits-setup-parameters.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/human-resources/hr-benefits-setup-parameters.md)
* Service: **dynamics-human-resources**
* Product: ****
* Technology: ****
* GitHub Login: @andreabichsel
* Microsoft Alias: **anbichse**

**Comment by tonyafehr** [comment]
@manbhat07, thanks for the update.
@andreabichsel, please update this topic.

**Comment by tonyafehr** [comment]
Bug 516075 logged to track this issue.

**Comment by andreabichsel** [comment]
Thank you! I fixed the navigation path.
