### ISSUE TITLE
LCS

### ISSUE THREAD

**Issue by jlabustro** [MicrosoftDocs/dynamics-365-unified-operations-public#2828]
When they redeploy the new environments under the new agreement, will it create a new LCS or not? if not, how do we know which sandbox is under the new agreement and which is under the old agreement? Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f123c2b2-f125-19eb-85fc-7d216dacba26
* Version Independent ID: 6f249ad8-0852-356e-0612-13b8070b31c7
* Content: [Move licenses between agreement types - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/move-licenses-between-agreement-types)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/move-licenses-between-agreement-types.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/get-started/move-licenses-between-agreement-types.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @ClaudiaBetz-Haubold
* Microsoft Alias: **chaubold**

**Comment by tonyafehr** [comment]
@jlabustro, thanks for the feedback. 
@ClaudiaBetz-Haubold, please review.

**Comment by ClaudiaBetz-Haubold** [comment]
Sandboxes are *not* tied to a specific agreement. Once a sandbox environment has been deployed, it will remain deployed until the customer deallocates and deletes it as long as the customer maintains the minimum license requirement for the service. However, the customer is obliged by the licensing agreement to deallocate and delete add-on sandboxes when they terminate the subscription for the add-on. When customer is simply transferring the subscription for the add-on between license types, they are still entitled to the sandbox and they do not have to take any action. However, in that case it is possible that an additional slot shows up, as the add-on under the old subscription will be in grace period, and the add-on under the new subscription is also available. Those additional slots will disappear once the customer deletes the deployed sandboxes. This is why Microsoft suggests that customers do stop, deallocate and delete add-on environments when they change the subscriptions and then redeploy them to ensure they do not see any extra slots that they are not expected to deploy. However, this is *not* a mandatory requirement.
