### ISSUE TITLE
Document Routing Agent Service Account

### ISSUE THREAD

**Issue by ddexter26** [MicrosoftDocs/dynamics-365-unified-operations-public#283]
It might be worth mentioning that the Service account used for the Agent should be the same as the Admin in d365 and local admin on the computer running the agent. In my last 3 deployments I had to do that to make it work.
Now the Documents are printing but the status window never shows any docs being printed.
I think a little cosmetic progress of things would help people like us wandering in dark.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2128b07d-7349-6642-f05f-c94fe800d104
* Version Independent ID: 0568d0d1-8035-3423-f791-7bd82a5d070f
* Content: [Install the Document Routing Agent to enable network printing - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/install-document-routing-agent?toc=/fin-and-ops/toc.json)
* Content Source: [articles/dev-itpro/analytics/install-document-routing-agent.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/install-document-routing-agent.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by robabb123** [comment]
Totally agree #ddexter26. Would have been nice to explicitly mention the SAME admin account that administers D365fO is also the same account to run the agent under.

**Comment by SteveBurkettNZ** [comment]
Agree with the service account needing to be a local admin on the computer running the agent as you seem to need to install the agent when logged in as the service account user. 

You definitely DON'T need to run the DRA using the Dynamics 365 admin account, it can just be an account with the Document Routing Client security role assigned in D365O.

I've found the main problem customers experience is they will install the DRA while logged in as their own user, then attempt to configure it to Run as a Windows service which results in an 'Error : AcquireToken failed' entry logged in the Microsoft.Dynamics.AX.Framework.DocumentRouting.log file every 5 seconds. I'm guessing it's something to do with the Azure access token's being acquired and stored under the user's name, which the service user doesn't have access to. Solution is to always install and configure DRA while logged in as the service account.

**Comment by ddexter26** [comment]
Awesome, if this = "Solution is to always install and configure DRA while logged in as the service account." Can be documented, we are golden.

**Comment by Rain-Runner** [comment]
I have another problem with this solution. If customers want to use service account, do they need one more license? Also it is needed to have one DRA for  each environment, due to generated Application ID (one for PROD, one for SBX, …)? This is not really effective when customer have more environments. Another thing is refreshing token every 90 days for running DRA as service?

**Comment by TJVass** [comment]
@ddexter26 - we have included this detail in the "What's important to know?" section at the top of the article.  Also, added insights to the FAQ section on Azure AD token expirations

**Comment by SteveBurkettNZ** [comment]
@Rain-Runner: No, the Document Routing Client role assigned to the service account user in D365O doesn't need a D365O license. (Does display it somewhere there when assigning the role that it doesn't need one).

And yes, need to have one DRA per environment that you wish to print from, preferably two or more for production.

**Comment by UmeshPandit** [comment]
just a try: check this file Microsoft.Dynamics.AX.Framework.DocumentRouting.config under "C:\ProgramData\Microsoft\Microsoft Dynamics 365 for Operations - Document Routing" check by changing the parameters.

AADInstance
ApplicationId
Tenant
AXResourceId

**Comment by ripannandy** [comment]
Production environment is running on ****.onmicrosoft.com account  Hence, unable to use admin account of D365FO as a service agent while configuring DRA as service. In this scenario, how to configure DRA as service for network printers. If it's possible through D365FO admin account then what should be the procedure?

**Comment by UmeshPandit** [comment]
Yes, you can use any System Admin Account. Same procedure you need to follow.
