### ISSUE TITLE
Job history clean up job needs to be enabled before it appears

### ISSUE THREAD

**Issue by f7a6875** [MicrosoftDocs/dynamics-365-unified-operations-public#2831]
It should be noted in the "Job history clean up" cleanup section that the "Execution history cleanup" feature needs to be enabled through Feature Management before it shows up in the Data Management workspace.   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d35f4fb2-1296-20ef-56c2-a2c5aa00befe
* Version Independent ID: 0d515af9-9419-4f21-223e-25344cf1bfe8
* Content: [Data import and export jobs overview - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/data-import-export-job)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/data-import-export-job.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/data-import-export-job.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by sericks007** [comment]
@f7a6875, thank you for providing this feedback.

@Sunil-Garg, please review and update the content, as needed.

**Comment by sericks007** [comment]
Bug 516452 has been logged to track this issue.

**Comment by Sunil-Garg** [comment]
@f7a6875 thanks for the feedback. The doc update has been submitted. Thanks again.
