### ISSUE TITLE
Add-in not available to choose

### ISSUE THREAD

**Issue by pmusiej** [MicrosoftDocs/dynamics-365-unified-operations-public#2833]
I do not see this add-in on the list with add-ins. Is this requires any additional steps?
Pawel 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 332ecc73-b911-de45-fd7c-4f2e1926db53
* Version Independent ID: 5057d69e-3e33-19c3-69e0-6aad0fff5e5e
* Content: [Electronic invoicing add-on overview - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/e-invoicing-service-overview?source=docs)
* Content Source: [articles/finance/localizations/e-invoicing-service-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/localizations/e-invoicing-service-overview.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @gionoder
* Microsoft Alias: **janeaug**

**Comment by sericks007** [comment]
@pmusiej, thank you for providing this feedback.

@gionoder, can you please respond to the question.

**Comment by gionoder** [comment]
Hi Pawel, thank for your message.

The Add-on is Public now. It should be available to everyone through LCS as Preview feature.

For details, please see the [link](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/e-invoicing-get-started#lcs-setup).

Thank you, Regards,
Gilberto.

**Comment by pmusiej** [comment]
Hi,
No it's not working yet.

Br,
Pawel

[image: image.png]

czw., 8 paź 2020 o 02:14 Gilberto <notifications@github.com> napisał(a):

**Comment by gionoder** [comment]
Hi Pavel,

You will need to switch on the add-on on LCS first. Please, follow this:
. go to LCS
. Click on "Preview feature management" tile
. On "Public Preview Features" field group, select BusinessDocumentSubmission
. On the right, enable the add-on.

The documentation was updated too ([link](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/e-invoicing-get-started#lcs-setup)).

Thank you, Regards,
Gilberto.

**Comment by pmusiej** [comment]
Hi,
My client wanted to test this solution and we noticed that the
BusinessDocumentSubmission feature disappeared. Something changed in terms
of this?
Br,
Pawel Musiej

[image: image.png]

śr., 14 paź 2020 o 14:17 Sally Erickson <notifications@github.com>
napisał(a):

**Comment by gionoder** [comment]
Hi Pawel, I will check and return to you. Thanks for letting me know.
Regards,
Gilberto.

**Comment by gionoder** [comment]
Hi Pawel, it was restored now. Please, check again.

Regards,
Gilberto.

**Comment by pmusiej** [comment]
HI,
Now I see. Thank you very much.

Br,
Pawel

czw., 19 lis 2020 o 17:21 Gilberto <notifications@github.com> napisał(a):
