### ISSUE TITLE
Asset management

### ISSUE THREAD

**Issue by LakshmiD365** [MicrosoftDocs/dynamics-365-unified-operations-public#2834]
Please include information about Enterprise Asset management like :
1. Is it supported for On-premise or not ??
2. If yes , please provide information about EAM On-premise.

**Comment by sericks007** [comment]
LakshmiD365, thank you for providing feedback.  To help our team address this feedback, please provide the URL of the article this feedback applies to.

**Comment by LakshmiD365** [comment]
Hi sericks007,
Thank you for your response.
Below is the URL of the article I'm referring to:
https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/cloud-prem-comparison

**Comment by sericks007** [comment]
@LakshmiD365, thank you! We'll look into this.

**Comment by sericks007** [comment]
@LakshmiD365, Asset management is not supported for on-premises environments.  I've updated the documentation to reflect this.  This update will be published later today.
