### ISSUE TITLE
Missing E-commerce supported browsers list

### ISSUE THREAD

**Issue by brettchristiansen** [MicrosoftDocs/dynamics-365-unified-operations-public#2835]
Missing a list of supported browsers for e-Commerce.  Based on the general system req's seen currently, assumption would be that IE is supported.  

Based on this doc, perhaps IE is not supported for e-commerce, but not clear since this is a doc specifically regarding a dev environment setup. https://docs.microsoft.com/en-us/dynamics365/commerce/e-commerce-extensibility/system-requirements

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 043a7336-3d71-14f2-9856-05e03e24cd80
* Version Independent ID: 60414540-f243-27e6-0494-28c4af78e0a4
* Content: [System requirements for cloud deployments of Dynamics 365 Commerece - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/get-started/system-requirements)
* Content Source: [articles/commerce/get-started/system-requirements.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/get-started/system-requirements.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @jashanno
* Microsoft Alias: **jashanno**

**Comment by sericks007** [comment]
@brettchristiansen, thanks for providing this feedback.

@jashanno, please review and update the content, as needed.

**Comment by sericks007** [comment]
Bug 516458 has been logged to track this issue.
