### ISSUE TITLE
Synchronous vs. Asynchronous paradigms table unclear

### ISSUE THREAD

**Issue by jspijkerboer** [MicrosoftDocs/dynamics-365-unified-operations-public#2838]
The table is a bit unclear comparing the paradigms. Maybe make it more that they are methods on classes and link to the corresponding pages?
(e.g. DataServiceContext.SaveChangesAsync, Http**Web**Request.GetResponse)

Took me a while to figure out that the table was referring to those methods.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2cdcdc3-398f-f785-d02e-cc784d91869c
* Version Independent ID: c7ec7a85-c489-f8c5-33c1-68f622108741
* Content: [Choose a data integration strategy - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/integration-overview)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/integration-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/integration-overview.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by kfend** [comment]
@jspijkerboer - thank you for the feedback.
@Sunil-Garg - can you take a look and update the content as needed?
