### ISSUE TITLE
Microsoft Edge versions?

### ISSUE THREAD

**Issue by subglo** [MicrosoftDocs/dynamics-365-unified-operations-public#2839]
Hello, 
Could you please elaborate on supported Microsoft edge versions? 
It is stated" Microsoft Edge (latest publicly available version) on Windows 10".
Does it mean Microsoft Edge 44.19041.1.0 (included in Windows 10 OS) or publicly available Microsoft Edge Version 85.0.564.70 (Official build) (64-bit) which is based on Chromium? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ad697b0-8c09-fd5e-9026-2960355bed0b
* Version Independent ID: 3f6fe592-c9d4-1123-6c3c-f09132d971ea
* Content: [System requirements for cloud deployments - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/system-requirements)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/system-requirements.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/get-started/system-requirements.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @sericks007
* Microsoft Alias: **sericks**

**Comment by sericks007** [comment]
@subglo, thanks for posting feedback here.

@jasongre, can you please answer the question and update the content, as necessary.

**Comment by sericks007** [comment]
Bug 516463 has been logged to track this issue.

**Comment by jasongre** [comment]
Thanks @subglo, the latest of legacy Edge and the chromium Edge are both currently supported.  Will update the docs to be more clear on this.

**Comment by sericks007** [comment]
This content has been updated and will be published later today.
