### ISSUE TITLE
Where is View --> Application Explorer in Visual Studio Community Edition? 

### ISSUE THREAD

**Issue by LouieInSeattle** [MicrosoftDocs/dynamics-365-unified-operations-public#284]
Where is View --&gt; Application Explorer in Visual Studio Community Edition? 
A note saying that that link is not available would be nice. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 244d40c1-ebf4-79c2-ad81-46ef85b28ac1
* Version Independent ID: 0ded2f72-1bba-51cf-5e81-ec7fab228e1b
* Content: [Application Explorer - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-tools/application-explorer#feedback)
* Content Source: [articles/dev-itpro/dev-tools/application-explorer.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-tools/application-explorer.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RobinARH
* Microsoft Alias: **robadawy**

**Comment by robadawy** [comment]
You cannot install Dynamics 365 for Finance and Operations on any Visual Studio installation. Development happens on cloud virtual machines (VM) that are deployed to Microsoft Azure via LCS or by downloading a development VHD. This is our current development and customization model.
