### ISSUE TITLE
Unit(s)of Measure and Product Name missing on this new aging report

### ISSUE THREAD

**Issue by schneider363** [MicrosoftDocs/dynamics-365-unified-operations-public#2846]
I dont understand how you can identify any product that you are referencing in an inventory report without the associated Product Name (from the Released Products page) and the Unit of Measure associated with the item as well as Unit of Measure that is associated with the weighted average for the inventory cost of the item. I.e. if you are selling frozen shrimp is should say site 1, item code 101, Frozen Shrimp 16/20, Pack Size=10 lbs/cs, cwqty=2 , cwunit=cs, qty=20, um=lbs,weighted average cost=$5.60, weighted average unit =lbs, Total Value= $112

This will drive and inventory manager or a finance person crazy because they can't identify a long list of inventory items if they have no idea what the names of the items are pack sizes,  or the units of measure....if this is truly meant to be a detailed reported that ties to the inventory control account i would highly recommend adding these fields so that it can be used throughout all industries . Your users would very much appreciate it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: beb7d505-9bdf-58a7-b67f-170539be7dae
* Version Independent ID: 719a0f4a-b6af-f035-e2d5-11ef7710f2fc
* Content: [Inventory aging report examples and logic - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/cost-management/inventory-aging-report)
* Content Source: [articles/supply-chain/cost-management/inventory-aging-report.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/cost-management/inventory-aging-report.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @RichardLuan
* Microsoft Alias: **riluan**

**Comment by tonyafehr** [comment]
@schneider363, thank you for the feedback. 
@kamaybac, please refview.

**Comment by yijialuan** [comment]
Thanks for your feedback! Just to avoid misunderstanding, are you talking about inventory value report or inventory aging report? In the inventory aging report, actually there is product name and the inventory UoM. 
![image](https://user-images.githubusercontent.com/10097645/96084662-0b561f00-0ef2-11eb-98b8-2f4b534f60c3.png)

**Comment by schneider363** [comment]
Richard,
Thanks for your quick response.

According to the dialog prompt (screenshot attached) the native Inventory
Aging is being deprecated and will be replaced with the inquiry Inventory
Aging Storage Report. My first question is when will this take place?
[image: image.png]

My concern is with the available fields on the new Inventory Aging Report
Storage (Inquiry List Grid). I am requesting Microsoft include all the
relevant fields such as Pack Size (nominal weight field truncated to 2
decimals from the item master), CW Qty, and CW Unit. When an
inventory manager looks at the report or list grid they need to see how
many cases (CW Qty and CW Unit) we have sitting on the shelf for a catch
weight item AND the associated total lbs for that item just in case that
they have to send a counter back out to reverify the inventory.When a
counter counts how many cases are sitting on the shelf then the software
does the applicable math to come up with the total lbs. It makes it very
difficult when they can't see it on the display because the column is not
eligible to be added.

My company refers to the Pack Size field as the Nominal Weight Field on the
Item Master (attached screenshot). This tells the inventory manager and
financial controller (how many lbs are in 1 case for a Catchweight Item).

Lastly, when you select Total for the Criteria in the report inquiry (see
attached) its doesn't total it in the list grid inquiry view when that
option is selected. You can enable the footer on the list grid it only
shows me the totals but the totals at the bottom cannot be exported with
the raw data to excel. This causes me to have to add another row in excel
for the actual subtotal value for all the inventory in a particular site.We
have to report invenotry totals to the bank every quarter with the
suppporting item level site level detail. If the subtotal are only to the
screen there isn't a way for me to export it so i can send it to the bank
it had to manipulated outside the system. Why not just include that in the
excel add-in to include the totals functionality at the bottom.
The say thing applis for when I select Total as a Criteria selection for
the Item Group.

[image: image.png]
[image: image.png]
[image: image.png].

Richard, thank you so much for looking into this for me.

**Comment by yijialuan** [comment]
Hi Schneider,

I cannot see the screen shots, can you please help to upload again? The storage version of inventory aging report is created for handling large volume transaction data and expect the users to export it into external system for further analysis. 

The old version will not be deprecated in next 12 months. 

If I understand it correctly, you want to additional three fields: CW Qty, CW Unit and the Nominal quantity (Released product > Manage inventory > CATCH WEIGHT > Nominal quantity). Please confirm.

As for the total, as explained and also documented. The storage version does not support it. If you do not have huge amount of data, and you feel comfortable about the old version, please continue with that one. If you use the storage version, we recommend you to export it into external tool, like excel to do further grouping, aggregation, etc.. In case, you want to view the total on the form, please enable features: _New grid control_ and _(Preview) Grouping in grids_ in the feature management. workspace. Then you can do the group & aggregation at any column.
Let me know if anything is not clear. 

Thanks for your feedback!

**Comment by schneider363** [comment]
Yes I would like those additional fields added because it would make sense
that an inventory manager or financial controller would want the necessary
detail for the number of cases for a particular catchweight item. What do
you think the chances are of getting those three fields added to the
inventory report storage column form view in the next D365 version release?

Three additional fields: CW Qty, CW Unit and the Nominal quantity (Released
product > Manage inventory > CATCH WEIGHT > Nominal quantity).

**Comment by yijialuan** [comment]
From your description, it looks like you are using inventory aging for counting purpose. While inventory aging is designed for users to understand how quickly the inventory moves, so it shows everything in inventory UoM. 

If you check the inventory relevant inquiries and reports, like On-hand list, you will be able to find catch weight relevant fields. Please log idea in our idea portal https://experience.dynamics.com/ideas/categories/list/?category=1e6c6fe0-a302-e711-8106-5065f38a3bb1&forum=515617a5-dedb-e911-a814-000d3a4f1244

**Comment by schneider363** [comment]
Why use two reports when one will suffice. The inventory aging is what
actually got posted to the ledger from the physical invwntory count that
took place.

If a finance amd inventory people have access to all the information and
they want to recheck something they don't need to pull another report
entirely. They need to use that same aging report as the guideline and my
point still remains the same you are not going to tell that counter how
many lbs are out there for a particular item .

 You are going to ask the counter to go back out and tell you exactly how
many cases (cw unit and cw qty) they see on the shelf. Therefore your
ending aging report should reflect that cw unit and cw qty information.

This is simply adding 3 fields to the report im unsure would take a
developer maybe 1 hr max and that a conservative estimate.
