### ISSUE TITLE
Description does not match path to System parameters and page sections

### ISSUE THREAD

**Issue by ronsonntag54** [MicrosoftDocs/dynamics-365-unified-operations-public#2847]
The navigation to change session timeout does not match the required navigation for the current version of D365 F&O.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c33ffb81-b152-64b8-01ef-6136299f0324
* Version Independent ID: dfd275dd-0249-b481-38b4-d61a617cbe6a
* Content: [Set the session idle timeout - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/session-idle-timeout)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/session-idle-timeout.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/sysadmin/session-idle-timeout.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @hasaid
* Microsoft Alias: **hasaid**

**Comment by tonyafehr** [comment]
@ronsonntag54, thank you for the feedback. 
@sericks007, please review.

**Comment by sericks007** [comment]
@ronsonntag54, thanks for the feedback! I adjusted the navigation, and the updated content will be published later today.
