### ISSUE TITLE
'Remove the extra backslash from the Principal username cofiguration value' part is confusing

### ISSUE THREAD

**Issue by VadimGoncharenko** [MicrosoftDocs/dynamics-365-unified-operations-public#2848]
Remove the extra backslash from the Principal username cofiguration value in the .json file before entering in the LCS UI. For example, **contoso\AXServiceUser** should be entered as **contoso\AXServiceUser** in LCS.

This part is a bit confusing as 'wrong' and 'right' values are no different

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3682abff-f1e6-336c-80b2-5c40ab3febd2
* Version Independent ID: 14250073-bcce-e22c-ef5b-1194fdf75c1f
* Content: [Redeploy on-premises environments - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/redeploy-on-prem)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/redeploy-on-prem.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/deployment/redeploy-on-prem.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @sarvanisathish
* Microsoft Alias: **sarvanis**

**Comment by tonyafehr** [comment]
@VadimGoncharenko, thank you for the feedback. 
@sericks007, please review.

**Comment by sericks007** [comment]
@VadimGoncharenko, thank you for pointing out the error.  The example should say: "For example, contoso\\AXServiceUser should be entered as contoso\AXServiceUser in LCS."

I've corrected this in the documentation. The updated topic will be published later today.
