### ISSUE TITLE
Further clarification required.

### ISSUE THREAD

**Issue by mrefalo90** [MicrosoftDocs/dynamics-365-unified-operations-public#285]
More clarification is need about the point Select a valid Secure Sockets Layer (SSL) certificate to use for HTTPS communication.  The Certificate is not available automatically on the hardware station.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6715d8b9-70ee-2e89-6154-0827f0393ab6
* Version Independent ID: 325d7547-0788-471e-8c4b-fc048a17b660
* Content: [Configure and install Retail hardware station - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/retail-hardware-station-configuration-installation)
* Content Source: [articles/retail/retail-hardware-station-configuration-installation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/retail-hardware-station-configuration-installation.md)
* Service: **dynamics-365-retail**
* GitHub Login: @jashanno
* Microsoft Alias: **jashanno**

**Comment by computerwizjared** [comment]
Hi- we are confused about how to generate the certificate for the Hardware Station. We're not able to find any documentation online about it either. Could you give me a quick rundown/overview of what I should do? Thanks!

**Comment by mrefalo90** [comment]
Hi- we had created the certificate on the aos server, downloaded it and installed it on the hardware station. The way we had done this is by no means the official way on how it should be done and hence why I asked for an official clarification.
