### ISSUE TITLE
The content is not available in app source site

### ISSUE THREAD

**Issue by JPremnath06** [MicrosoftDocs/dynamics-365-unified-operations-public#2852]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e8509d5-4ad0-27b7-5919-2d5ea22696c5
* Version Independent ID: 48287c70-4237-5b3b-6c97-a4d811c9c634
* Content: [Retail channel performance PowerBI.com solution - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/retail-channel-performance-dashboard-power-bi-data?toc=/dynamics365/commerce/toc.json)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/retail-channel-performance-dashboard-power-bi-data.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/retail-channel-performance-dashboard-power-bi-data.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @ashishmsft
* Microsoft Alias: **asharchw**

**Comment by tonyafehr** [comment]
@JPremnath06, Retail channel performance content packs, available on the Microsoft AppSource site, are deprecated as a consequence of product updates in Microsoft Power BI.
