### ISSUE TITLE
Data upgrade in development box cannot be performed if sandbox environment is spartan managed

### ISSUE THREAD

**Issue by jatomas** [MicrosoftDocs/dynamics-365-unified-operations-public#2853]
The bacpac generated in devbox cannot be imported if the sandbox is spartan managed. It should be noted at some point in the documentation because people can waste time not knowing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ae815e8-03c2-0769-5e6a-e36f57244651
* Version Independent ID: 5304a30a-ca52-0bb6-99c3-c7a5bb8ab36e
* Content: [Upgrade from AX 2012 - Data upgrade in development environments - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/data-upgrade-2012)
* Content Source: [articles/fin-ops-core/dev-itpro/migration-upgrade/data-upgrade-2012.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/migration-upgrade/data-upgrade-2012.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by tonyafehr** [comment]
@jatomas, thank you for the feedback. 
@laneswenka, please review.

**Comment by tonyafehr** [comment]
Bug 519383 logged to track this issue.

**Comment by laneswenka** [comment]
We have a new process for upgrade as is outlined on the following docs:
https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/upgrade-data-sandbox-dacpac
