### ISSUE TITLE
Container entity fields

### ISSUE THREAD

**Issue by mihavuk** [MicrosoftDocs/dynamics-365-unified-operations-public#286]
As a workaround for truncating strings longer than 32,768 characters on import it is suggested to use container entity fields.
But container entity fields cannot be exported. If I add it to mapping it returns Invalid data type.
Please explain this workaround.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fefee79b-aac3-6f4d-92bb-ffd7021a85a8
* Version Independent ID: 446e7928-558c-b72d-2b8f-e53f04f2ebd0
* Content: [Data management and integration by using data entities - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/data-management-integration-data-entity)
* Content Source: [articles/dev-itpro/data-entities/data-management-integration-data-entity.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/data-management-integration-data-entity.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by ShylaThompson** [comment]
Bug created for investigation: 237910

**Comment by mihavuk** [comment]
Where can I see the progress of the bug?

**Comment by Meenakshish** [comment]
I have the same requirement and couldn't map container field because of invalid data type error. Please let me know the work around for it.
