### ISSUE TITLE
Steps not specific enough to follow

### ISSUE THREAD

**Issue by MartinBubenheimer** [MicrosoftDocs/dynamics-365-unified-operations-public#2861]
Step 1. of section "How a Power BI report author can create reports that use financial dimensions" needs more specific instructions since there is no "entity store" connector in Power BI Desktop.

I would highly appreciate seeing this process in a video.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9960a2f-7eec-54d2-ee25-5d05eac8a333
* Version Independent ID: eb8585cc-6097-22fb-720b-d3d15cd07540
* Content: [Add financial dimensions to aggregate measurements - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/add-financial-dimensions-aggregate-measurements?toc=/dynamics365/commerce/toc.json)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/add-financial-dimensions-aggregate-measurements.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/add-financial-dimensions-aggregate-measurements.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by josaw1** [comment]
Thanks for your feedback. @MilindaV2 can you please take a look?

**Comment by josaw1** [comment]
BUG 519498 created to track.
