### ISSUE TITLE
Add new content regarding payment processing and authorizations

### ISSUE THREAD

**Issue by mueckeflo** [MicrosoftDocs/dynamics-365-unified-operations-public#2865]
Hi,

With the new payment processing features introduced in 10.0.13, partial payment processing is possible as well, which is not requiring a new authorization anymroe. I think this should get added here as this is a major imporvement.
Here is the related "What's new"-article:
[https://docs.microsoft.com/en-us/dynamics365-release-plan/2020wave2/commerce/dynamics365-commerce/extensibility-support-incremental-capture-during-back-office-invoicing]

Regards,
Florian

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ff48b0d-bf91-e425-3dfd-cb39f4706d71
* Version Independent ID: 57a2fc80-30fb-cbc2-de15-e486ef760fdf
* Content: [Credit card setup, authorization, and capture - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/accounts-receivable/credit-card-authorizations)
* Content Source: [articles/finance/accounts-receivable/credit-card-authorizations.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/accounts-receivable/credit-card-authorizations.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @ShivamPandey-msft
* Microsoft Alias: **shpandey**

**Comment by josaw1** [comment]
Thank you for your feedback. @ShivamPandey-msft can you please review?

**Comment by panolte** [comment]
Thank you for the suggestion.  This feature is an extensibility support feature that allows incremental capture of authorization.  

Dynamics 365 Finance credit card authorization continues to manage order payments as having an initial authorization for the full amount of the order. When the order is partially fulfilled, a portion of the original authorization is captured and a new authorization is created for the remaining amount.
