### ISSUE TITLE
Missing supported firmware information for 10.0.13

### ISSUE THREAD

**Issue by brettchristiansen** [MicrosoftDocs/dynamics-365-unified-operations-public#2868]
The "Supported Adyen Firmware versions" does not have details for version 10.0.13

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1a7bb73-c6c0-fc10-9369-04714ac8e6f0
* Version Independent ID: df6ebf95-7def-f3d5-04fc-8f412e314ee1
* Content: [Dynamics 365 Payment Connector for Adyen - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/adyen-connector?tabs=8-1-3)
* Content Source: [articles/commerce/dev-itpro/adyen-connector.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/dev-itpro/adyen-connector.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @rassadi
* Microsoft Alias: **rassadi**

**Comment by kfend** [comment]
@brettchristiansen - thanks for the feedback.
@Reza-Assadi - can you please take a look at and address this feedback?
