### ISSUE TITLE
Garnishment deduction is not being calculated when generating payroll statement

### ISSUE THREAD

**Issue by maleuch** [MicrosoftDocs/dynamics-365-unified-operations-public#287]
I do have my employees enrolled for garnishment and setup the amounts as appropriated but when I generate the payroll statement the Garnishment deductions do NOT calculated nor does the vendor invoice (Tax authority). I need help to solve this issues in way to demo to a customer, please. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc8066ca-68ae-5c4d-bb48-141c8b7ed691
* Version Independent ID: ec299cab-2311-8747-7757-48ce2778bc14
* Content: [Enroll workers in a garnishment or tax levy - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/hr/localizations/noam-usa-garnishment-tax-levy-enrollment-tasks)
* Content Source: [articles/fin-and-ops/hr/localizations/noam-usa-garnishment-tax-levy-enrollment-tasks.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/hr/localizations/noam-usa-garnishment-tax-levy-enrollment-tasks.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @rschloma
* Microsoft Alias: **brpotter**

**Comment by ShylaThompson** [comment]
@maleuch , thanks for contacting us. Unfortunately, we can't handle support requests for the product here. To contact support, consider one of the options described here:  https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support
