### ISSUE TITLE
Page needs an update to consider move to VS2017

### ISSUE THREAD

**Issue by turbozapekanka** [MicrosoftDocs/dynamics-365-unified-operations-public#2872]
C:\Users\<username>\Documents\Visual Studio 2015\Projects folder no longer exists in the 10.0.13 and newer versions of the environments.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e5b845d-9cd2-358d-3de9-bd15652ea746
* Version Independent ID: e52c5205-60de-4acf-2d21-ea0df760a49f
* Content: [Configure the Azure DevOps mapping during code migration - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/configure-vso-solution)
* Content Source: [articles/fin-ops-core/dev-itpro/migration-upgrade/configure-vso-solution.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/migration-upgrade/configure-vso-solution.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **jorisde**

**Comment by RobinARH** [comment]
@robinarh Please take a look.

**Comment by RobinARH** [comment]
Bug 520412 created to track this issue.

**Comment by jorisdg** [comment]
Looks like this doc was already updated. @tonyafehr please close this ticket.
