### ISSUE TITLE
Question about installing the Planning Optimization add-in

### ISSUE THREAD

**Issue by JOLSO** [MicrosoftDocs/dynamics-365-unified-operations-public#2873]
Do you have to install the add-in in all your environments (DEV, Build, Sandbox, PROD)?
Or do you install it just in a DEV environment, do a code build and move the code to Sandbox...does this code move then add the Planning Optimization model to Sandbox? Then move the code to PROD?
Or do you have to install the add-in to all environments?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a36c4831-276b-03c6-6f92-532746789338
* Version Independent ID: 5fdd62c5-5a0a-bf23-6dab-ad3717f5f70d
* Content: [Get started with Planning Optimization - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/master-planning/planning-optimization/get-started)
* Content Source: [articles/supply-chain/master-planning/planning-optimization/get-started.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/master-planning/planning-optimization/get-started.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @ChristianRytt
* Microsoft Alias: **crytt**

**Comment by sericks007** [comment]
@JOLSO, thanks for providing feedback here.

@ChristianRytt, please respond to the questions and update the content, as necessary.

**Comment by JOLSO** [comment]
Hi Sally,

Good to see you still have a hand in documentation!

I also opened a support ticker with the same question.  Please see attached reply.  Pasting here as well –

You are correct here “install it in a DEV environment, do a code build and move the code to Sandbox this code move then add the Planning Optimization model to Sandbox, then move the code to PROD”

I will assume that’s the correct answer unless I hear back from you!  😊


Thanks!
Jackie Olson | Senior Consultant
Stoneridge Software | Microsoft Gold Partner
D: 218.331.3383 C: 701.238.5632
stoneridgesoftware.com<http://stoneridgesoftware.com>

[Register Now...]<https://stoneridge.sigstr.net/uc/5c9ba3eae8b0ad019e9f4df4>

**Comment by sericks007** [comment]
@JOLSO, Hi Jackie - It's good to hear from you! Yes, please consider the answer from Support the definitive answer.

@ChristianRytt, please consider updating the content to clarify.

**Comment by sericks007** [comment]
Bug 521120 has been logged to track this issue.
