### ISSUE TITLE
Missing information about decommission of T1 Microsoft hosted environments

### ISSUE THREAD

**Issue by FH-Inway** [MicrosoftDocs/dynamics-365-unified-operations-public#2875]
This article is linked from LCS in the warning message "Sandbox Develop and Test environments will only be deployable as Cloud-hosted environments after November 2, 2020." However, the article only talks about removal of RDP access to these environments. Please add information that these environments can only deployed as CHEs and that existing Microsoft hosted T1 environments will be decommissioned starting next year and are not available for deployment anymore.
This should include the following information we received from Microsoft:

"Below you will find an updated timeline and FAQ:

November 1, 2020:

No additional Sandbox:  Develop & Test (Tier 1) Add-on purchases allowed
Empty Sandbox:  Develop & Test (Tier 1) slot in LCS will be removed
Existing Sandbox:  Develop & Test (Tier 1) environments will have no impact
Deleted Sandbox:  Develop & Test (Tier 1) environment will not be re-provisioned

Starting December 1, 2020:

RDP access will be removed for Sandbox:  Develop & Test environments that are managed by Microsoft

January 30, 2020:

Communication will be sent regarding deallocating and deleting of existing Sandbox:  Develop & Test."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5080f3d7-0ad1-940c-284a-92008d7c19d5
* Version Independent ID: c911e39b-82ee-2ae3-4493-d2e39afccc2b
* Content: [Cloud deployment overview - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/cloud-deployment-overview#remote-desktop)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/cloud-deployment-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/deployment/cloud-deployment-overview.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @AngelMarshall
* Microsoft Alias: **tsmarsha**

**Comment by sericks007** [comment]
@FH-Inway, thanks for providing feedback.

@AngelMarshall, please consider updating the content, as suggested.

**Comment by AngelMarshall** [comment]
HI Sally,

I’m not sure where’s the source for the FAQ content regarding tier1 and RDP removal. Looping in @Lane Swenka<mailto:Lane.Swenka@microsoft.com> who may have more docs context around this topics here.

Thanks!
Angel

**Comment by sericks007** [comment]
@laneswenka, please consider updating the content, as suggested.

**Comment by SASrudyalva** [comment]
@FH-Inway 
Does this affect on-prem for sandbox/prod deployments?

**Comment by FH-Inway** [comment]
> @FH-Inway
> Does this affect on-prem for sandbox/prod deployments?

@SASrudyalva I don't know, but I don't think so.

**Comment by sericks007** [comment]
Bug 8680557 has been logged in the LCS database to track this issue.

**Comment by laneswenka** [comment]
A note has been added regarding the removal of Tier1 from Nov 2020.
