### ISSUE TITLE
Unclear descriptions in setup information

### ISSUE THREAD

**Issue by Izmiyash** [MicrosoftDocs/dynamics-365-unified-operations-public#2876]
[Enter feedback here]
>Set up a discount rate schedule that uses current market discount rates to calculate ARO amounts
There is no menu item like "discount rate schedule". there is "Cashflow discount rates" in Fixed Asset setup menu and it seems this is the one to be used to setup discount rate. Please have someone confirm. As this is Japanese localization related page, correct Japanese page as well.

>Specify the type of ARO to use for an asset, and specify how often changes to the ARO amounts are posted
Specify exact menu path to perform this action. Please have someone confirm.

>Set up an estimated retirement cost plan for ARO, and simulate ARO amounts for each fiscal period of the asset’s service life
Totally no idea how to do this. specify menu path.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c1ecf2e-5b9a-c898-b336-3d3c518a15f5
* Version Independent ID: b7582fe1-b7a5-5602-1d32-45785dc43624
* Content: [Set up asset retirement obligation for fixed assets for Japan - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/apac-jpn-asset-retirement-obligation-fixed-assets)
* Content Source: [articles/finance/localizations/apac-jpn-asset-retirement-obligation-fixed-assets.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/localizations/apac-jpn-asset-retirement-obligation-fixed-assets.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @yijialuan
* Microsoft Alias: **riluan**

**Comment by sericks007** [comment]
@Izmiyash, thanks for providing this feedback.

@yijialuan, please consider updating the content, as suggested.

**Comment by sericks007** [comment]
Bug 521124 has been logged to track this issue.

**Comment by v-oloski** [comment]
Thank you for reporting this issue. The documentation [Set up asset retirement obligation for fixed assets for Japan](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/apac-jpn-asset-retirement-obligation-fixed-assets)  has been updated in this point:

- Set up a discount rate schedule (cashflow discount rate) that uses current market discount rates to calculate ARO amounts
