### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Mohammed-Raouf** [MicrosoftDocs/dynamics-365-unified-operations-public#2877]
[Enter feedback here]

Below link is broken from the page

Dynamics Financial Reporting Blog

https://blogs.msdn.com/b/dynamics_financial_reporting/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c67d799d-74ce-19dc-4610-ffd16d679d77
* Version Independent ID: ddd96d76-7d77-004d-2392-e58c07921aa4
* Content: [View and design financial reports - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/design-financial-reports)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/design-financial-reports.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/design-financial-reports.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @jcart1106
* Microsoft Alias: **jcart**

**Comment by sericks007** [comment]
@Mohammed-Raouf, thanks for letting us know about this.

@jcart1106, please fix the broken link.

**Comment by sericks007** [comment]
Bug 521129 has been logged to track this issue.

**Comment by sericks007** [comment]
This issue has been fixed. Thanks for letting us know about it!
