### ISSUE TITLE
Step 9 has mistake

### ISSUE THREAD

**Issue by blackjoker17** [MicrosoftDocs/dynamics-365-unified-operations-public#288]
In Step 9, of 'Implement a Trigger', it says to put the manifest file under the folder 'POSAPIExtension '.  Whereas I believe it should say to put it under the folder 'SuspendReceiptSample'.  My guess is this was a copy and paste error.  
Also, is this the correct place to make corrections to the articles?  And/or where can I contribute articles myself?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 205c9cdc-7229-ed08-63d2-166f7f9d7416
* Version Independent ID: 5f7574c0-e12f-785d-e7d9-0efbe67e5fec
* Content: [Retail Modern POS (MPOS) triggers and printing - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/dev-itpro/pos-trigger-printing)
* Content Source: [articles/retail/dev-itpro/pos-trigger-printing.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/dev-itpro/pos-trigger-printing.md)
* Service: **dynamics-365-retail**
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by ShylaThompson** [comment]
@blackjoker17,  Thanks for pointing this out. To update the content directly, click "Edit" in the upper right corner of any of our Docs.microsoft.com topics, make your changes and then propose the change. We'll review the change and publish it after it passes internal review. For more information about contributing, see our [Contributor's guide](https://docs.microsoft.com/en-us/contribute/).  

Definitely keep entering issues for when you see a gap in the documentation or you find a mistake in the documentation that you don't want to fix yourself by editing the topic.

**Comment by ShylaThompson** [comment]
Bug logged for investigation: 237905

**Comment by ShylaThompson** [comment]
This topic has been fixed and will be published by the end of this week.
