### ISSUE TITLE
missing menu path in Enter the asset retirement oblgiation amounts

### ISSUE THREAD

**Issue by Izmiyash** [MicrosoftDocs/dynamics-365-unified-operations-public#2880]
[Enter feedback here]

The step described is as follows. no menu path specified and thus no idea how to do this. Please add exact menu path to do this action.

1.Click Create to open the drop dialog.
2.In the Transaction date field, enter the date on which to recognize the asset retirement obligation
3.In the Estimated retirement cost adjustment field, enter the cash flow amount
4.Click OK.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b885986-9b2b-e4f5-c8d0-2aaaa988d80b
* Version Independent ID: bb3c912b-717e-dc6a-4bd5-8ee27433bc8f
* Content: [Set up asset retirement obligation documents and enter ARO amount on a fixed asset - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/tasks/set-up-asset-retirement-obligation)
* Content Source: [articles/finance/localizations/tasks/set-up-asset-retirement-obligation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/localizations/tasks/set-up-asset-retirement-obligation.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @ShylaThompson
* Microsoft Alias: **roschlom**

**Comment by josaw1** [comment]
Thanks for the feedback. @roschlom can you please review this?

**Comment by josaw1** [comment]
BUG 521994 created to track the issue.

**Comment by roschlom** [comment]
We've updated the topic to provide the navigation that was needed. Thank you for the spot-on feedback. We appreciate it! Have a great day!
