### ISSUE TITLE
Missing dual-write mapping information and other sections.

### ISSUE THREAD

**Issue by Moutasema** [MicrosoftDocs/dynamics-365-unified-operations-public#2881]
This integration requires two dual-write mappings to work which are not documented. We should include map details and how to activate them (E.g. Run map, Skip initial sync). The maps are:

- CDS inventory on-hand entries (msdyn_inventoryonhandentries)
- CDS inventory on-hand requests (msdyn_inventoryonhandrequests)

This page should also include how this integration works and Limitations, such as it's lack of supporting Power Portal scenarios.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0f2a03e-b77a-9f2b-0ba5-ffbab4a418cd
* Version Independent ID: c0c1e93f-d1a3-c62e-abb8-1be918017bad
* Content: [Inventory availability in dual-write - Finance & Operations | Dynamics 365](https://review.docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/inventory-availability)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/inventory-availability.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/dual-write/inventory-availability.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @yijialuan
* Microsoft Alias: **riluan**

**Comment by josaw1** [comment]
Thank you for your feedback. @yijialuan can you please review this request?

**Comment by josaw1** [comment]
BUG 521995 created to track the issue.

**Comment by josaw1** [comment]
Hi, the changes have been made in draft form and should be published shortly. Thank you!
