### ISSUE TITLE
Are there more videos like this for other Dynamics aspects 

### ISSUE THREAD

**Issue by JakeMackey** [MicrosoftDocs/dynamics-365-unified-operations-public#2882]
https://youtu.be/V-ExmHZ47Ac

**Comment by josaw1** [comment]
Hi. You can find other Dynamics Essentials videos [here](https://www.youtube.com/playlist?list=PLXtHYVsvn_b_YH2w_yHMRlnLPBcBY2ued).

Also, be sure to check out [this topic](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/videos?toc=/dynamics365/finance/toc.json).

**Comment by JakeMackey** [comment]
Oh awesome! Exactly what I was looking for. Thank you.
