### ISSUE TITLE
By moving to ADLS, is the embed through AOT and LCS still supported ?

### ISSUE THREAD

**Issue by axaeffect** [MicrosoftDocs/dynamics-365-unified-operations-public#2885]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a344a5de-68fa-e9cf-28eb-51269c33b9b3
* Version Independent ID: 1b3ede62-3954-574b-5778-8cdee0ededfe
* Content: [Make Entity store available as a Data Lake - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/entity-store-data-lake)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/entity-store-data-lake.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/entity-store-data-lake.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by RobinARH** [comment]
@MilindaV2 - Can you take a look? Thanks.

**Comment by MilindaV2** [comment]
In the current public preview of Entity store in Data lake, the data gets staged in the lake - we currently don't support moving PowerBI reports to Data lake. This will be enabled in the future. You can see the an overview below - more details will come in the future

https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/azure-data-lake-overview#how-you-can-use-data-lake-later-if-youre-currently-using-analytical-workspaces

**Comment by axaeffect** [comment]
Hi Millinda,

Thanks for your email, So having said that it will be enabled in the
future, and having said that the built-in report for analytics will later
be automatically re-directed to Data Lake, if we already have data in Data
Lake as of now and create our own Power BI report on it, can we still embed
it as AX Resources and create our own Analytics Workspace coding wise, not
by "pin" Power BI report from F&O frontend. What is your suggestion ?
Thanks

**Comment by MilindaV2** [comment]
You can "pin" a powerBI report authored with data in the lake as an Analytical workspace. We have not (yet) enabled the ability to create Analytical workspaces with data in the lake. they currently work with entity store.

**Comment by axaeffect** [comment]
Hi Millinda,

Thanks for your prompt reply. Highly anticipated for Analytical workspaces
in datta lake. Thanks again.
