### ISSUE TITLE
Help make the docs more inclusive (Finance)

### ISSUE THREAD

**Issue by RobinARH** [MicrosoftDocs/dynamics-365-unified-operations-public#2891]
Replace gendered pronouns in the dev docs according to our style guide.

Only work in this folder:
https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/tree/live/articles/finance

Using the instructions here:
https://docs.microsoft.com/en-us/style-guide/bias-free-communication

Please leave a note if you are working on this issue so that we don't duplicate effort.

Thanks!

**Comment by ReQ6W7rFnaBxyfb** [comment]
I'll work on this folder. Thanks!

**Comment by trncb** [comment]
Is this something I can work on, or is this only open to Microsoft employees?

**Comment by RobinARH** [comment]
Hi Terence - It's not limited to Microsoft employees. Please feel free to work on it!

Let me know if you are planning to work on it, so that we don't duplicate efforts.

Thanks!

**Comment by trncb** [comment]
Great! In that case, please put my name down as the person working on this issue, thank you.

**Comment by RobinARH** [comment]
It's all yours. 👍

**Comment by trncb** [comment]
@RobinARH PR #2898 shows the updates I made. Let me know if this is what was intended.

**Comment by RobinARH** [comment]
Look great. Thanks! Hoping it gets counted in time!
