### ISSUE TITLE
Import Users into D365

### ISSUE THREAD

**Issue by chornung** [MicrosoftDocs/dynamics-365-unified-operations-public#2892]
What users will this load?  How do you assign the Company?  How do yo assign roles?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f31ca8cb-1073-3cd9-ef12-473bce8cbea9
* Version Independent ID: 3b74d12c-fe74-7a3e-5048-e5ba84fface7
* Content: [Import users in bulk - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/tasks/import-bulk-users)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/tasks/import-bulk-users.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/sysadmin/tasks/import-bulk-users.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @maertenm
* Microsoft Alias: **sericks**

**Comment by tonyafehr** [comment]
@Peakerbl, please review. Thanks!

**Comment by Peakerbl** [comment]
A new updated version of the content is in process. This will cover both the Import user and Batch import. It will also make it clear that only the Import user option provides the possibility to select users. The default company for user imported will be based on the current session company when the process is initiated. User will only be assigned the System user role and it will be required to assign roles to users after the import.

**Comment by Peakerbl** [comment]
Update import-bulk-users.md
#9564
