### ISSUE TITLE
Same tenant required?

### ISSUE THREAD

**Issue by ChrisGarty** [MicrosoftDocs/dynamics-365-unified-operations-public#2893]
The assumption is that dual-write only works when the CDS and F&O environments are on the same tenant. Is that correct? If so, then that should be added as a requirement here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cdfc828-1858-2f25-2a41-524da2577ea0
* Version Independent ID: 2955b17e-f122-1f22-5380-1e7467af71d2
* Content: [System requirements for dual-write - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/dual-write-system-req)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/dual-write-system-req.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/dual-write/dual-write-system-req.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RamaKrishnamoorthy
* Microsoft Alias: **ramasri**

**Comment by sericks007** [comment]
@RamaKrishnamoorthy, please consider updating the content, as suggested.

**Comment by sericks007** [comment]
Bug 523369 has been logged to address this issue.

**Comment by sericks007** [comment]
The content has been updated.
