### ISSUE TITLE
Incorrect definition of Data Import/Export Framework (DIXF) 

### ISSUE THREAD

**Issue by lzangari** [MicrosoftDocs/dynamics-365-unified-operations-public#2895]
The Data Import/Export Framework (DIXF) is not present in AX 2009. The sentence "You can use the Data Import/Export Framework (DIXF) service in Microsoft Dynamics AX 2009 to retrieve data" is incorrect. The DIXF was introduced with AX 2012. This is stated in the "Applies to" section of "https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/data-import-export-framework-user-guide-dixf-dmf"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2261d4a-2102-e347-16cd-41bde3879fb1
* Version Independent ID: 001bbb8d-c97b-d64c-5360-44b77399e800
* Content: [AX 2009 migration - Export packages - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/ax2009-upgrade-export-package)
* Content Source: [articles/fin-ops-core/dev-itpro/migration-upgrade/ax2009-upgrade-export-package.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/migration-upgrade/ax2009-upgrade-export-package.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **kfend**

**Comment by sericks007** [comment]
@lzangari, thank you for providing this feedback.

@Sunil-Garg, please review and update the content, as needed.

**Comment by sericks007** [comment]
Bug 523370 has been logged to track this issue.

**Comment by josaw1** [comment]
This has been fixed.
