### ISSUE TITLE
You have to allow multiple transactions within one voucher parameter to use this functionality

### ISSUE THREAD

**Issue by abylkhatov** [MicrosoftDocs/dynamics-365-unified-operations-public#2896]
**Note**: you have to enable [Allow multiple transactions within one voucher](https://docs.microsoft.com/en-us/dynamics365/finance/general-ledger/one-voucher#why-use-one-voucher) parameter on the **General ledger parameters** page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 860bf92a-e579-b27b-211f-dae7dd46e8b4
* Version Independent ID: 61b2519e-20de-14e5-6ce9-e6facc25cf74
* Content: [Split a fixed asset - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/fixed-assets/tasks/split-fixed-asset)
* Content Source: [articles/finance/fixed-assets/tasks/split-fixed-asset.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/fixed-assets/tasks/split-fixed-asset.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @saraschi2
* Microsoft Alias: **saraschi**

**Comment by sericks007** [comment]
@abylkhatov, thank you for providing feedback here.

@roschlom, please review and assign to the appropriate PM.

**Comment by sericks007** [comment]
Bug 523372 has been logged to track this issue.
