### ISSUE TITLE
Unable to troubleshoot long running scenarios

### ISSUE THREAD

**Issue by TomaszFranczyk-Anegis** [MicrosoftDocs/dynamics-365-unified-operations-public#2899]
The article below has been used quite widely for complex scenarios:
https://cloudblogs.microsoft.com/dynamics365/no-audience/2017/11/15/collect-dynamics-365-for-finance-and-operations-event-traces-with-windows-performance-monitor/
LCS environment monitoring can't provide such a in-depth analysis. How to perform such an investigation with a self-service app?

**Comment by josaw1** [comment]
Hi, thank you for your comment. Unfortunately, we're unable to handle questions on blog content here. You might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your question from the Dynamics community.
