### ISSUE TITLE
Site information is missing

### ISSUE THREAD

**Issue by jtclements** [MicrosoftDocs/dynamics-365-unified-operations-public#290]
There is nothing mentioning the delivery site for the product.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0aef5f54-38e0-a555-8af0-ae439fad0da4
* Version Independent ID: 011616b5-5308-d4b5-60fe-e553d230ff3b
* Content: [Direct deliveries - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/sales-marketing/direct-deliveries)
* Content Source: [articles/supply-chain/sales-marketing/direct-deliveries.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/sales-marketing/direct-deliveries.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @YuyuScheller
* Microsoft Alias: **omulvad**

**Comment by tonyafehr** [comment]
Thanks for taking the time to provide this kind of feedback. I will pass this message on to the author and your suggestion will be noted as a future enhancement to this topic.
