### ISSUE TITLE
Regarding the applicability of the content

### ISSUE THREAD

**Issue by gagangarg** [MicrosoftDocs/dynamics-365-unified-operations-public#2909]
Hi, Does this page content also apply to Dynamics 365 Commerce, including the e-commerce functionality? Request you to clarify that on the page please. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5080f3d7-0ad1-940c-284a-92008d7c19d5
* Version Independent ID: c911e39b-82ee-2ae3-4493-d2e39afccc2b
* Content: [Cloud deployment overview - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/cloud-deployment-overview#availability)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/cloud-deployment-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/deployment/cloud-deployment-overview.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by RobinARH** [comment]
@laneswenka - Can you take a look? Thanks.

**Comment by RobinARH** [comment]
Bug 527460 created to track this issue.

**Comment by laneswenka** [comment]
Hello yes this applies to D365 Commerce as well, since it is based on Finance & Operations codebase today.

**Comment by laneswenka** [comment]
@RobinARH  this can be resolved.
