### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by RaduNegulescuMS** [MicrosoftDocs/dynamics-365-unified-operations-public#2912]
[Enter feedback here]
Theming overview and Create a new theme links are broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74e5d5fe-18d6-6f4c-eaa2-a34781678083
* Version Independent ID: 6a375b03-fcf1-45c0-8454-8ea8e23df25c
* Content: [Select a site theme - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/select-site-theme)
* Content Source: [articles/commerce/select-site-theme.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/select-site-theme.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @bicyclingfool
* Microsoft Alias: **StuHarg**

**Comment by RobinARH** [comment]
@bicyclingfool, @v-chgri  - Can you take a look? Thanks.

**Comment by RobinARH** [comment]
Bug 527459 created to track this issue.

**Comment by RobinARH** [comment]
Links are fixed. Thanks!
