### ISSUE TITLE
Payment hierarchy allocation

### ISSUE THREAD

**Issue by DavidDanks** [MicrosoftDocs/dynamics-365-unified-operations-public#292]
Hi 
within out organisation we need several payment hierarchies
1    is this possible
2    how do you allocate a user to a payment hierarchy?

cheers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 396d0db7-1ea6-3bdc-3744-3805207bfc8f
* Version Independent ID: f00f0a16-42e3-61f2-4b04-ec095364d8a6
* Content: [Set up centralized payments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/cash-bank-management/set-up-centralized-payments)
* Content Source: [articles/financials/cash-bank-management/set-up-centralized-payments.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/cash-bank-management/set-up-centralized-payments.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @kweekley
* Microsoft Alias: **kweekley**

**Comment by sericks007** [comment]
Thanks for contacting us. For discussions about how to use features, we recommend that you post on the Finance and Operations community forum: https://community.dynamics.com/365/financeandoperations/f/765 
Thanks!
