### ISSUE TITLE
The date of the latest change under "What's new or changed in Human Resources" is wrongly written as 2002

### ISSUE THREAD

**Issue by musezt** [MicrosoftDocs/dynamics-365-unified-operations-public#2923]
[Enter feedback here]

The date of the latest change under "What's new or changed in Human Resources" is wrongly written as 2002
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 402f1c79-9e36-23db-ac44-8374dfcff26a
* Version Independent ID: 37a7e675-1a12-00ea-f384-f810ef587291
* Content: [What's new or changed in Dynamics 365 Human Resources October 22, 2020 - Human Resources | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/human-resources/hr-whats-new-2020-10-22#feedback)
* Content Source: [articles/human-resources/hr-whats-new-2020-10-22.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/human-resources/hr-whats-new-2020-10-22.md)
* Service: **dynamics-human-resources**
* Product: ****
* Technology: ****
* GitHub Login: @jcart1106
* Microsoft Alias: **jcart**

**Comment by tonyafehr** [comment]
@andreabichsel, please update. Thanks!

**Comment by andreabichsel** [comment]
This issue was fixed. Thank you!!
