### ISSUE TITLE
Issue with the installer

### ISSUE THREAD

**Issue by affanfarooqi** [MicrosoftDocs/dynamics-365-unified-operations-public#2925]
Mostly working with Microsoft Edge or Chrome you may see an error after downloading the installer

"Application cannot be started. Contact the application vendor."
This can be resolved by downloading the installer from within Internet explorer.

Regards,
Affan Farooqi
[Dynamics Solution and Technology](https://dynamicssolution.com/)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb8dd6af-c1bf-e1fa-8a9d-ba656a48ae00
* Version Independent ID: acc0a0c2-aad7-5c8c-13b8-6a460bcb136c
* Content: [Install the POS layout designer - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/install-pos-layout-designer)
* Content Source: [articles/commerce/install-pos-layout-designer.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/install-pos-layout-designer.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @athinesh99
* Microsoft Alias: **athinesh**

**Comment by sericks007** [comment]
@affanfarooqi, thank you for reporting this!

@athinesh99, please consider adding this information to the content.

**Comment by sericks007** [comment]
Bug 525696 has been logged to track this issue.
