### ISSUE TITLE
Twice in the May updates list, it uses the work "Contract" in the title, but then uses the word Contact in the description. 

### ISSUE THREAD

**Issue by mjohnsonedxc** [MicrosoftDocs/dynamics-365-unified-operations-public#2926]
Twice in the June updates list, it uses the work "Contract" in the title, but then uses the word Contact in the description.  These are really important distinctions and not interchangeable at all. Can this be corrected please?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8043d72-1496-a79a-da5b-60dc1d24f561
* Version Independent ID: fa5f09b6-10d9-ab9a-6f65-da69252777c1
* Content: [What's new or changed in dual-write - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/whats-new-dual-write)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/whats-new-dual-write.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/dual-write/whats-new-dual-write.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **rhaertle**

**Comment by mjohnsonedxc** [comment]
Sorry, I meant May not June

**Comment by josaw1** [comment]
Thanks for your feedback. @RobinARH can you please take a look?

**Comment by josaw1** [comment]
BUG 528580 created to track.

**Comment by RobinARH** [comment]
Fixed, and will go live this evening.
