### ISSUE TITLE
PartnerSource link to sing-up is wrong and is confusing!

### ISSUE THREAD

**Issue by sshashi7** [MicrosoftDocs/dynamics-365-unified-operations-public#2927]
The PartnerSource link provided under Subscribe resolves to some other page and partners won't know what to do next. The link should be updated with the following link:
https://portal.microsoftonline.com/Signup/MainSignUp.aspx?OfferId=AA972CC1-91DB-4CF9-94A1-4A9163ED50C9&pc=2c50e379-9378-4761-84f9-e328da74e657&dl=ERP_INSTANCE_SKU

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 146a6e6a-4f26-195e-80fc-15b38d77b948
* Version Independent ID: 489070bf-affb-4d92-eeac-91cad7a2a889
* Content: [Sign up for preview subscriptions - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/sign-up-preview-subscription)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/sign-up-preview-subscription.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-tools/sign-up-preview-subscription.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **jorisde**

**Comment by josaw1** [comment]
Thank you for your feedback. @RobinARH can you please look into this?

**Comment by josaw1** [comment]
BUG 528581 created to track.

**Comment by RobinARH** [comment]
I updated this page with the correct link.
