### ISSUE TITLE
Confusing Article - Illustrations are Not Labeled (no caption or title on the illustration)

### ISSUE THREAD

**Issue by Bashar-Sadig** [MicrosoftDocs/dynamics-365-unified-operations-public#2931]
Article is confusing and not easy to follow as it references illustrations on the page that are not properly labeled (the illustration does not have a label), using cross-references to illustrations that are not labeled. So, the reader may wonder, is the paragraph linked to the above or the proceeding illustration.
Please Label the Illustrations or use Figures to ensure the reader is relating the context of the write up to the correct illustration.

For example:
1. Illustration can have a name "Engineering BOM Illustration" or "Phantom BOM Illustration"
2. The paragraph then refers to it as in "the Engineering BOM Illustration we use A, B, and C to note out whatever"

Overall, the grammar and write up is great, it is just loosing track of what a paragraph is what is confusing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8edfe78b-6486-5678-a171-95f81d2715ef
* Version Independent ID: 62a24546-bb3f-5194-43f0-0db144643ab7
* Content: [Phantom items - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/production-control/phantom-items)
* Content Source: [articles/supply-chain/production-control/phantom-items.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/production-control/phantom-items.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @ShylaThompson
* Microsoft Alias: **kamaybac**

**Comment by tonyafehr** [comment]
@Bashar-Sadig, thanks for the feedback. 
@kamaybac, please review.

**Comment by kamaybac** [comment]
@Bashar-Sadig , thank you for your insightful feedback. I am working now to get the topic updated along the lines you suggest.

**Comment by Bashar-Sadig** [comment]
Thank you and appreciate the efforts made on the article as it is a very
good article and insightful.

Bashar Sadig
312-342-0024

**Comment by kamaybac** [comment]
@tonyafehr , I am still working with the PM to get this topic updated. Reopening.

**Comment by kamaybac** [comment]
Created bug 569829 to track this issue.

**Comment by kamaybac** [comment]
@josaw1 , Yes! This was fixed last year, so I'm closing this issue.
