### ISSUE TITLE
there is no such menu fixed assets>Adjustment

### ISSUE THREAD

**Issue by Izmiyash** [MicrosoftDocs/dynamics-365-unified-operations-public#2932]
[Enter feedback here]
Though I can see following part in this page, I cannot even find Adjustment menu under Fixed assets menu. please show us correct menu.

Impairment recognition test
The primary page is Fixed assets > Adjustment. The sub-menus different, depending on whether Method I or Method II is applied. The first step of impairment is the recognition test. Future cash flow that isn't discounted is used as a standard that the carrying amount (or net book value) is compared against. If this future cash flow isn't enough to cover the net book value of the asset, the impairment measurement must recognize the journal amount.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e96bc99-19d3-5510-c13e-085778239910
* Version Independent ID: 7eceeba8-fa13-5b66-5a1e-4340f4e8496c
* Content: [Fixed asset impairment accounting on cash-generating units for Japan - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/apac-jpn-impairment-accounting-cash-generating-unit)
* Content Source: [articles/finance/localizations/apac-jpn-impairment-accounting-cash-generating-unit.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/localizations/apac-jpn-impairment-accounting-cash-generating-unit.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @yijialuan
* Microsoft Alias: **riluan**

**Comment by tonyafehr** [comment]
@Izmiyash, thanks for the feedback. 
@yijialuan, please review.

**Comment by tonyafehr** [comment]
Bug 527680 logged to track this issue.

**Comment by yijialuan** [comment]
Just assign the bug to @EricWangChen who is the owner now

**Comment by v-oloski** [comment]
[Content deliverable 529674 created](https://msdyneng.visualstudio.com/FinOps/_workitems/edit/529674)
