### ISSUE TITLE
Missing labels for binary ISV packages

### ISSUE THREAD

**Issue by ThomasZak** [MicrosoftDocs/dynamics-365-unified-operations-public#2934]
Has this pipeline build process been tested with binary ISV solutions?

I have a D365 solution that has multiple ISV solutions. Some are installed as models. Others are binary packages. On the development environment the system is working fine and looks great. All of the code is properly checked in to source control.

But, when I use the Azure pipeline for building, the labels for only the binary ISV packages are missing. All other labels are fine for standard MSFT code, local customizations and for model-based ISV packages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10459944-bcf8-c5fa-d180-9fb4bb3722da
* Version Independent ID: 29ae9d16-ed7c-92d8-0300-4fc46c777ddf
* Content: [Build automation that uses Microsoft-hosted agents and Azure Pipelines - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/hosted-build-automation)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/hosted-build-automation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-tools/hosted-build-automation.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @jorisdg
* Microsoft Alias: **jorisde**

**Comment by tonyafehr** [comment]
@ThomasZak, thanks for the feedback.
@jorisdg, please review.

**Comment by jorisdg** [comment]
There is actually a little bug here, but it's not what you think. You have to explicitly include the ISV in your package. The bug is that it partially does (it's not supposed to). I see that you are on the feedback Yammer group, I can discuss it there with you?

In either case, this is not a documentation issue.

**Comment by ThomasZak** [comment]
Well the odd thing is that the ISV package is making it in to the final product, at least partially.

In researching this issue, I noticed this setting in the pipeline setup

[cid:image003.jpg@01D6B769.4B75D1B0]

For the step “Copy Binary Dependencies to:” , it seems to have a default setting of looking in the Source directory and look for the BIN directory as a child of any contained folder. That presented itself as being the way that it recognized how to include binary packages.

But if there is a proper way to do this, I would be happy to hear it. Please feel free to put this on the Yammer board, since I know that many others will have binary ISV packages and could do the same missteps that I have.


[cid:image004.png@01D6B769.4B75D1B0]Tom Zak • Senior Technical Consultant
P: 260.312.8166 • W: www.saglobal.com<http://www.saglobal.com/> • Auburn, Indiana
