### ISSUE TITLE
Rename of the original database

### ISSUE THREAD

**Issue by rabol** [MicrosoftDocs/dynamics-365-unified-operations-public#2937]
Step 3, rename the original database, fails with this information:

Msg 5030, Level 16, State 2, Line 1
The database could not be exclusively locked to perform the operation.

Completion time: 2020-11-10T09:25:20.6979855+00:00

one way to do is:
ALTER DATABASE <original Dynamics 365 database> SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
ALTER DATABASE <original Dynamics 365 database> MODIFY NAME = <original Dynamics 365 database>_ORIG

Also be aware that renaming the database does not rename the files of the database.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe0d2c68-08ea-77b8-af74-cd889a8344ca
* Version Independent ID: d88b6646-49de-f7eb-3d7c-7d1e700131e1
* Content: [Upgrade data in development or demo environments - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/upgrade-data-to-latest-update)
* Content Source: [articles/fin-ops-core/dev-itpro/migration-upgrade/upgrade-data-to-latest-update.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/migration-upgrade/upgrade-data-to-latest-update.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by tonyafehr** [comment]
@rabol, thanks for the feedback. 
@laneswenka, please review.
