### ISSUE TITLE
Authentication and authorization - feedback

### ISSUE THREAD

**Issue by pturegano** [MicrosoftDocs/dynamics-365-unified-operations-public#2939]
In the section "Authentication and authorization" the below **highlighted** text is incorrect. In the CDS Wave 2 and Finance and Operations 10.0.13 / PU37 it needs to be a valid email account.

The next steps walk through this process in Finance and Operations apps.
1. In Finance and Operations, go to System Administration > Users > Users.
2. Select New to add a new user. Enter the following information:

- User ID - Enter cdsintegration (or a different value).
- User name - Enter cds integration (or a different value).
- Provider - Leave at the default value.
- Email - Enter cdsintegration (or a different value, **does not need to be a valid email account**).
- Assign the security role CDS virtual entity application to this user.
- Remove all other roles including System user.
- 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8065cd89-f253-c50b-ed2e-7b84e5b2409c
* Version Independent ID: 8c7e311a-582c-1ac6-328e-be817a62924c
* Content: [Finance and Operations and Common Data Service admin reference - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/power-platform/admin-reference)
* Content Source: [articles/fin-ops-core/dev-itpro/power-platform/admin-reference.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/power-platform/admin-reference.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by tonyafehr** [comment]
@Sunil-Garg, please review.

**Comment by tonyafehr** [comment]
Bug 527683 logged to track this issue.
