### ISSUE TITLE
Retail Payment model should be combined with existings models, then generate package, and not deployed by itself.

### ISSUE THREAD

**Issue by blackjoker17** [MicrosoftDocs/dynamics-365-unified-operations-public#2940]
Hi Mugunthan,
One issue we ran into is that if you just follow these steps and generate an AOS payment package file, and apply this to your environment, it will remove/replace any existing previous models you deployed as part of a previous package.  So the instructions only work if this is the ONLY AOS package you are applying to your environment.  So, while steps 9 and later are true for one scenario, it could be good to add some a section that gives you two sets of steps.  One if you don't have any other models.  And one, if you do have custom models that you need to include along with this payment model. 
So instead of steps 9 and later, we needed to add the model folder to our source control, check in the whole RetailPaymentConnectors* folder, then use the build server to build a complete package with all non-microsoft models included.  Then upload that package and apply it.  I imagine this will a common scenario for most people reading this article.  And while it should have been something I knew, I actually didn't at the time of reading this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27f678d1-840c-d7d3-1e97-ca80666328c2
* Version Independent ID: 2a0f90df-f8eb-d9e2-d5be-881734e72e21
* Content: [Create payment packaging for Application Explorer for self-service deployment - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/payment-connector-package)
* Content Source: [articles/commerce/dev-itpro/payment-connector-package.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/dev-itpro/payment-connector-package.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by tonyafehr** [comment]
@mugunthanm, please review this feedback.

**Comment by tonyafehr** [comment]
Bug 527685 logged to track this issue.

**Comment by tonyafehr** [comment]
This topic has been updated to better reflect this information.
