### ISSUE TITLE
Dynamics Financial Reporting Blog

### ISSUE THREAD

**Issue by vavd** [MicrosoftDocs/dynamics-365-unified-operations-public#2947]
The "Dynamics Financial Reporting Blog" link is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d3beb80-3fef-08aa-2a50-97378ab74497
* Version Independent ID: cc0a8ca9-66cd-0f5e-5c53-f8f65bb16a17
* Content: [Income statement financial report - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/general-ledger/income-statement-financial-report)
* Content Source: [articles/finance/general-ledger/income-statement-financial-report.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/general-ledger/income-statement-financial-report.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @jcart1106
* Microsoft Alias: **jcart**

**Comment by josaw1** [comment]
Thanks for the feedback. @jcart1106 can you please take a look?

**Comment by jcart1106** [comment]
This should be assigned to someone on the Finance team not me.

**Comment by josaw1** [comment]
@roschlom can you please take a look?

**Comment by josaw1** [comment]
BUG 528579 created to track.

**Comment by roschlom** [comment]
We've updated the link so that it should work now. Thanks again for the feedback. We really appreciate it!
