### ISSUE TITLE
Page Navigation Problem

### ISSUE THREAD

**Issue by ed-bcr** [MicrosoftDocs/dynamics-365-unified-operations-public#2949]
The section heading for this page is swapped with the one prior.  If a user is using the tree-level navigation they are unable to find this page. see screenshot.
![image](https://user-images.githubusercontent.com/11232979/98963630-affd5980-24bc-11eb-9ba6-d084f6dbe11d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3c8a870-46c2-9f85-b3fe-7ed537e4d59d
* Version Independent ID: b79fc1c6-5ee7-619b-d2ce-d3709eaa4431
* Content: [Maintenance attribute types - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/asset-management/setup-for-functional-locations/specification-types)
* Content Source: [articles/supply-chain/asset-management/setup-for-functional-locations/specification-types.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/asset-management/setup-for-functional-locations/specification-types.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @josaw1
* Microsoft Alias: **mkirknel**

**Comment by josaw1** [comment]
Thanks for your feedback. @kamaybac can you please fix this?

**Comment by kamaybac** [comment]
@ed-bcr , thank you for reporting this issue. It looks like we just had the links swapped in our table of contents. I have repaired the issue and the fix should go live later today.
