### ISSUE TITLE
How to offer the user multiple report designs?

### ISSUE THREAD

**Issue by JBlakeOfficial** [MicrosoftDocs/dynamics-365-unified-operations-public#295]
The users wanted to go into the print management screen and select the report design. I am not sure how to do this using the framework provided?

In the end I added a data event handler on insert to PrintMgmtReportFormat and when I inserted Design 1, I also inserted Design 2.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62563695-5ac8-7557-4221-19a7187d98c3
* Version Independent ID: 33eb8596-f9a9-c97b-fffc-d91c12b18ebd
* Content: [Create custom designs for business documents - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/custom-designs-business-docs)
* Content Source: [articles/dev-itpro/analytics/custom-designs-business-docs.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/custom-designs-business-docs.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by kfend** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). 
However, I have notified the author of the topic that we should consider clarifying the topic.
