### ISSUE TITLE
Please update ExportToExcelIGeneratedCustomExport section

### ISSUE THREAD

**Issue by andy2619** [MicrosoftDocs/dynamics-365-unified-operations-public#2953]
Please update the following section:

> How can an entity be added as an Open in Excel option on a form that doesn’t share the same root datasource?
> 
> A generated Open in Excel option can be added on any form by implementing the ExportToExcelIGeneratedCustomExport interface. When adding a generated option programmatically, the set of fields can be explicitly specified.

ExportToExcelIGeneratedCustomExport has been deprecated and OfficeIGeneratedWorkbookCustomExporter is now used. Please review and update this section accordingly.  Code examples would also be very helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 961239b1-2cab-7982-5198-71d85ab7a34c
* Version Independent ID: cc990680-89a4-41b9-9934-6a8a1047b5d4
* Content: [Create Open in Excel experiences - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/office-integration/office-integration-edit-excel)
* Content Source: [articles/fin-ops-core/dev-itpro/office-integration/office-integration-edit-excel.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/office-integration/office-integration-edit-excel.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @ChrisGarty
* Microsoft Alias: **cgarty**

**Comment by sericks007** [comment]
@andy2619, thank you for making us aware of this.  The content has been updated and will be published later today.
