### ISSUE TITLE
Why is this page under D365 Commerce?

### ISSUE THREAD

**Issue by weaveriski** [MicrosoftDocs/dynamics-365-unified-operations-public#2955]
This page is the general service availbility for D365 Finance or SCM etc, why is it hidden in the Commerce part?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7dcb285-f32c-c92e-fe49-1617f213066b
* Version Independent ID: 8f28c1a0-9da5-f853-90ee-d82a4c32df7e
* Content: [Service update availability - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/public-preview-releases)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/public-preview-releases.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/get-started/public-preview-releases.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @ShellyBakke
* Microsoft Alias: **smiller**

**Comment by sericks007** [comment]
@weaveriski, thanks for your question.  This page appears in help collections for Finance, SCM, and Commerce.  When searching for this page, you may get the page from the Commerce help because "Commerce" is first alphabetically.
