### ISSUE TITLE
Batch mode

### ISSUE THREAD

**Issue by nico-dangerous** [MicrosoftDocs/dynamics-365-unified-operations-public#2956]
Hello, I would like to know how to run the import in batch mode. There is no option for it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c82c1e8e-0ec7-7d75-de6a-1726b683fadc
* Version Independent ID: 5c805d7d-5df1-b9ab-f364-a0878144adf0
* Content: [Configure data import from SharePoint - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/er-configure-data-import-sharepoint?toc=/dynamics365/commerce/toc.json)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/er-configure-data-import-sharepoint.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/er-configure-data-import-sharepoint.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @NickSelin
* Microsoft Alias: **nselin**

**Comment by RobinARH** [comment]
@NickSelin  - Can you take a look? Thanks.

**Comment by NickSelin** [comment]
The topic has been updated with more information. See https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/er-configure-data-import-sharepoint?toc=/dynamics365/finance/toc.json#limitations for more details. Thanks!
