### ISSUE TITLE
Missing clear description of security roles

### ISSUE THREAD

**Issue by pturegano** [MicrosoftDocs/dynamics-365-unified-operations-public#2959]
This page needs an update as it is not reflecting the current status. It needs a clear description of the "Project security roles" and "Implementation roles". This is important because compliance with security and audit principles of customers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ee6629a-f1a4-b352-0b26-657a503d80a7
* Version Independent ID: dbe54d30-b73b-0446-7d80-922050825641
* Content: [Configure Lifecycle Services (LCS) security - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/configure-lcs-security)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/configure-lcs-security.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/lifecycle-services/configure-lcs-security.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **jorisde**

**Comment by tonyafehr** [comment]
@jorisdg, please review. Thanks!

**Comment by sericks007** [comment]
@AngelMarshall, please review and update this content appropriately.

**Comment by tonyafehr** [comment]
Bug 8867530 has been logged to track this issue.
