### ISSUE TITLE
is Source code valid?

### ISSUE THREAD

**Issue by truongda** [MicrosoftDocs/dynamics-365-unified-operations-public#296]
I follow this instruction but it seems confusing.
What is the purpose of this " FMPBIWorkspaceController controller = new FMPBIWorkspaceController();" ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc7d8a19-6471-c70f-0452-74df0eded2f7
* Version Independent ID: a357999b-0336-cf39-a6b2-7cce6164be9e
* Content: [Add analytics to workspaces by using Power BI Embedded - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/add-analytics-tab-workspaces?toc=/fin-and-ops/toc.json)
* Content Source: [articles/dev-itpro/analytics/add-analytics-tab-workspaces.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/add-analytics-tab-workspaces.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by ShylaThompson** [comment]
@TJVass  I've logged a bug for investigation: 239517

**Comment by ShylaThompson** [comment]
The topic has been updated to make it more clear.
