### ISSUE TITLE
Data backup and retention clarifications needed

### ISSUE THREAD

**Issue by lma1171** [MicrosoftDocs/dynamics-365-unified-operations-public#2961]
Hello,

A customer of mine pinged me for details of our database backup and retention policies due to a recent security breach and now going through a security audit of all their systems.  We ended up going in circles to what we provide between this Cloud Deployment page, the Service Description white paper you can download in section titled Service availability in Azure Regions, and the links from that white paper on page 14 to the Azure SQL generic page.

The Service Description white paper is dated Oct 2019 and some of other links are no longer valid.  Should that be updated or removed?

And could we better clarify that while Azure SQL DB transaction log for 35 days, however we limit F&O to 30 days due to GDPR.  And if customers want a LTR like referenced on the Azure SQL DB Data and recover page, they need to do it themselves via a database snapshot via LCS.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5080f3d7-0ad1-940c-284a-92008d7c19d5
* Version Independent ID: c911e39b-82ee-2ae3-4493-d2e39afccc2b
* Content: [Cloud deployment overview - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/cloud-deployment-overview#security-and-compliance)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/cloud-deployment-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/deployment/cloud-deployment-overview.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by josaw1** [comment]
Thank you for your comments. @laneswenka can you please take a look?

**Comment by josaw1** [comment]
BUG 533355 created to track.
