### ISSUE TITLE
Unclear how to specify Sign-on URL

### ISSUE THREAD

**Issue by pturegano** [MicrosoftDocs/dynamics-365-unified-operations-public#2963]
**Step 3** instructs to:
Sign-on URL - The base URL of your client. For example, https://contosoax7.cloud.dynamics.com.

Then there is a Note: 
**Note**
Depending on your version, you may need to add /oauth as a suffix to the URL, or use http instead of https as the protocol, such as: https://contosoax7.cloud.dynamics.com/oauth or http://contosoax7.cloud.dynamics.com/oauth.

**PROBLEM**: the instructions on step 3 are only correct sometimes as we may need to apply the url explained on the Note. For me the note is unclear and leads to trial and error .
**SUGGESTION**: make clear the instructions, the note is ambiguous and Step 3 is incorrect. This leads to confusion, not efficient work with customers and also leads to have a poor impression of the customer facing team. Take into account that most of the consultants do not have access to ADD and have to channel the request via the customer AAD team.
Technical instructions should be written in conditional terms as this is only introducing confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2213414-926d-10e1-538b-efef09dc0181
* Version Independent ID: 03be53f7-c305-cb02-7627-2ea4f1c01bd4
* Content: [Configure PowerBI.com integration - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/configure-power-bi-integration)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/configure-power-bi-integration.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/configure-power-bi-integration.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by josaw1** [comment]
Thank you for your feedback. @MilindaV2 can you please review?

**Comment by josaw1** [comment]
BUG 533360 created to track.

**Comment by josaw1** [comment]
This fix is underway, thank you.
