### ISSUE TITLE
Updating environments - no longer tier 1 offered

### ISSUE THREAD

**Issue by robabb123** [MicrosoftDocs/dynamics-365-unified-operations-public#2964]
You might want to update the section as the tier 1 environments are no longer offered as part of the subscription:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5080f3d7-0ad1-940c-284a-92008d7c19d5
* Version Independent ID: c911e39b-82ee-2ae3-4493-d2e39afccc2b
* Content: [Cloud deployment overview - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/cloud-deployment-overview?toc=/dynamics365/commerce/toc.json)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/cloud-deployment-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/deployment/cloud-deployment-overview.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by kfend** [comment]
@robabb123 - thanks for the feedback.
@laneswenka - Can you please update the topic based on this feedback?

**Comment by laneswenka** [comment]
A PR is out for this that solves another reported issue.  @kfend this can be resolved.
