### ISSUE TITLE
Link to "Virtual Entities" is broken

### ISSUE THREAD

**Issue by JulijaLudvigaELCA** [MicrosoftDocs/dynamics-365-unified-operations-public#2966]
Current link to the Virtual Entities for the Power Platform integration pattern is to https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/power-platform/overview.md and returns an 404 error.

**Comment by kfend** [comment]
@JulijaLudvigaELCA - thanks for the feedback. Can you let us know what page you were on when you found this link so that we can get it updated? Thanks!

**Comment by JulijaLudvigaELCA** [comment]
@kfend It is here: https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/integration-overview
in the "Choose a data integration strategy" section, the first line of the table listing availale integration patterns.

**Comment by JulijaLudvigaELCA** [comment]
@kfend there is also other broken link on the same page: https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/power-platform/overview.md in the sentence: "For detailed information, see Microsoft Power platform integration."

**Comment by sericks007** [comment]
@JulijaLudvigaELCA, thank you for making us aware of these errors!  The links have been fixed.  The updated content will be published later today.
