### ISSUE TITLE
Standard Cloud offering & tier1 - as of November tier1 change?

### ISSUE THREAD

**Issue by vonHussa** [MicrosoftDocs/dynamics-365-unified-operations-public#2968]
Hi, 
noticed that the Standard Cloud offering section still mention tier1 environment. Didn't this change in beginning of November? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2402dfea-008a-c7bb-8a3b-1d0457a39665
* Version Independent ID: 4936afad-9a39-e65d-a00c-81246de632cb
* Content: [Environment planning - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/imp-lifecycle/environment-planning?toc=/dynamics365/finance/toc.json)
* Content Source: [articles/fin-ops-core/fin-ops/imp-lifecycle/environment-planning.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/imp-lifecycle/environment-planning.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @ClaudiaBetz-Haubold
* Microsoft Alias: **chaubold**

**Comment by ClaudiaBetz-Haubold** [comment]
Thanks for raising your concern! Yes, it did change, and we are in the process of updating the documentation.

Kind regards,

Claudia Betz-Haubold
Principal Solution Architect | FastTrack for Dynamics 365<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdynamics.microsoft.com%2Fen-us%2Ffasttrack%2F&data=02%7C01%7CClaudia.Betz-Haubold%40microsoft.com%7Cd192fd01713c484fe2f408d7bf3ed5ac%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637188148920801232&sdata=WLLIFrSoEMMgZj511nQIFskNlVc85QW4ojfuetk8ET4%3D&reserved=0>
office:  +49.89.3176.2804 |  mobile:  +49.151.4401.2309
[Microsoft]
