### ISSUE TITLE
Could you please clarify the eligibility for Fasttrack for Dynamics? I believe environment SKUs, storage do not count. What about order lines, assets (for asset management), digital messaging and other options added recently? Thank you.

### ISSUE THREAD

**Issue by RaphaelTagliani** [MicrosoftDocs/dynamics-365-unified-operations-public#2972]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fe767aa-ae4b-d5b2-323c-80b3b6ad0bff
* Version Independent ID: ee427dc9-9bf1-4595-0bb1-d247f578fe04
* Content: [Microsoft FastTrack - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/fasttrack-dynamics-365-overview)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/fasttrack-dynamics-365-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/get-started/fasttrack-dynamics-365-overview.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @Jeff-Luo-MSFT
* Microsoft Alias: **jeluo**

**Comment by tonyafehr** [comment]
@RaphaelTagliani, thanks for the feedback. 
@Jeff-Luo-MSFT, please review.

**Comment by tonyafehr** [comment]
Bug 532042 logged to track this issue.
