### ISSUE TITLE
Change Project settings for Project onboarding when talking about "legacy system"

### ISSUE THREAD

**Issue by jatomas** [MicrosoftDocs/dynamics-365-unified-operations-public#2973]
At the end of the document, in the following section:
https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/upgrade-data-sandbox#run-the-data-upgrade-deployable-package

The documentation says: "If no data upgrade packages appear in the list, go to your project settings in LCS, and make sure that your legacy system is set to AX2012 Upgrade."

But, this options is not on the project settings in LCS, but in the Project Onboarding in LCS, in the Project Overview tab, so, it must be:

"If no data upgrade packages appear in the list, go to your project onboarding in LCS, to the project overview tab, and make sure that your legacy system is set to AX2012 Upgrade."

Thanks 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6717d4f3-0b93-713a-6a61-405cce70dfe0
* Version Independent ID: 050db2bb-9dd4-82ff-3f27-ec7a8d0ea64c
* Content: [Upgrade from AX 2012 - Data upgrade in sandbox environments - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/upgrade-data-sandbox)
* Content Source: [articles/fin-ops-core/dev-itpro/migration-upgrade/upgrade-data-sandbox.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/migration-upgrade/upgrade-data-sandbox.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by tonyafehr** [comment]
@jatomas, thanks for the feedback. 
@laneswenka, please review.

**Comment by tonyafehr** [comment]
Bug 532040 created to track this issue.
