### ISSUE TITLE
This is not building a new workspace, this is customising a exiting

### ISSUE THREAD

**Issue by rabol** [MicrosoftDocs/dynamics-365-unified-operations-public#2977]
The title is: Build Workspaces, but in fact this is about modifying an existing one

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7de231ed-06c6-cb84-721c-f2853047c9e4
* Version Independent ID: 3aaf74d5-43be-9ebc-e726-7d60a1351911
* Content: [Build workspaces - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/user-interface/build-workspace)
* Content Source: [articles/fin-ops-core/dev-itpro/user-interface/build-workspace.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/user-interface/build-workspace.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by RobinARH** [comment]
I'll take a look. - Robin

**Comment by RobinARH** [comment]
I updated the topic, and the new content should go live tonight. Thanks for the feedback!

**Comment by rabol** [comment]
So where do I find information on how to create a new Workspace and add it to the Dashboard - for a new module, not just personalization

**Comment by RobinARH** [comment]
I'll investigate.

**Comment by RobinARH** [comment]
Bug 533988 created to track this issue.

**Comment by RobinARH** [comment]
Please checkout this topic: https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/user-interface/build-workspaces

An workspace is navigation, form, or overview. We have relevant topics here: https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/user-interface/build-rental-charge-type-form
