### ISSUE TITLE
should bootstrapping do something about Party ID?

### ISSUE THREAD

**Issue by mdtahoe** [MicrosoftDocs/dynamics-365-unified-operations-public#2978]
I imported account records into a CE+F&O environment.  I was planning to bootstrap them so, no Dual Write integration was running other than Company.  Now turning on the customer integration fails for lack of Party ID (msdyn_party lookup field.)

I verified that all the Party Numbers (autogenerated text field) existed on the account records.  However, there are no Parties in the msdyn_party table.  Pretty hard to populate a lookup from an empty table.

From where should they come?  What process needs to run for them to be created (and copied into the lookup?)

TIA

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0891e384-80e8-5d40-8bde-24081e06876a
* Version Independent ID: b6ecc0cb-e827-80aa-934d-ef03d674c97e
* Content: [Bootstrap with company data FAQ - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/bootstrap-company-data)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/bootstrap-company-data.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/dual-write/bootstrap-company-data.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @RamaKrishnamoorthy
* Microsoft Alias: **ramasri**

**Comment by RobinARH** [comment]
@RamaKrishnamoorthy Can you take a look? Thanks.

**Comment by RobinARH** [comment]
We updated this topic today, but I don't think is addresses your question:
https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/bootstrap-company-data

**Comment by RobinARH** [comment]
Bug 538984 created to track this issue.

**Comment by RobinARH** [comment]
We updated the docs to address this.
