### ISSUE TITLE
Still Getting error changes to Microsoft models

### ISSUE THREAD

**Issue by gprodware** [MicrosoftDocs/dynamics-365-unified-operations-public#298]
The model 'Foundation' belongs to the package 'ApplicationSuite' that is blocked from customization. You cannot have more than one model in this package.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a9a3c24-d654-c61f-1c78-64aa5be9eb10
* Version Independent ID: faa489e6-18a0-1a1a-6a4b-3725ed5c97d8
* Content: [Relax model restrictions to refactor overlayering into extensions - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/extensibility/refactoring-over-layering)
* Content Source: [articles/dev-itpro/extensibility/refactoring-over-layering.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/extensibility/refactoring-over-layering.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @cgarty
* Microsoft Alias: **CGarty**

**Comment by ShylaThompson** [comment]
@gprodware. Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support).
