### ISSUE TITLE
Add clarifications

### ISSUE THREAD

**Issue by teryokhin** [MicrosoftDocs/dynamics-365-unified-operations-public#2981]
I've spent a couple of hours debugging a few nasty issues. Please update the following sections:

### Step 2:
> Add a relation to parent entity in the relations node. Example – MySalesLineEntity has relationship to MySalesTableEntity.

Add that **the relationship must involve natural keys only, not RecIds.**

### Step 4:
> Create a cluster index on the staging tables which includes RowId, ParentRowid,DefinitionGroup, and ExecutionId. This is for performance reasons.

Add that **this index must have Allow duplicates set to Yes.**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0198d960-ca6c-4d08-36e0-b5061e13a784
* Version Independent ID: 6e445b8a-8906-f8a8-5dda-d177ae12e3db
* Content: [Develop composite data entities - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/develop-composite-data-entities)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/develop-composite-data-entities.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/develop-composite-data-entities.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by RobinARH** [comment]
@Sunil-Garg Can you take a look? Thanks.

**Comment by RobinARH** [comment]
Bug 538988 created to track this issue.
