### ISSUE TITLE
Screen Shot is Misleading

### ISSUE THREAD

**Issue by dodiggitydag** [MicrosoftDocs/dynamics-365-unified-operations-public#2982]
I believe the "account number key" screen shot should show: company,accountnum instead of just accountnumber.
"In Common Data Service, accountnumber is defined as the key for the Account entity."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f1b7454-dbe7-515b-e060-048c15581d19
* Version Independent ID: 85b90c52-8e7e-de92-13a8-3b9bab72fe58
* Content: [Enable entity maps for dual-write - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/enable-entity-map#example-enabling-the-customers-v3contacts-entity-map)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/enable-entity-map.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/dual-write/enable-entity-map.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @sabinn-msft
* Microsoft Alias: **sabinn**

**Comment by RobinARH** [comment]
@sabinn-msft Can you take a look? Thanks.

**Comment by RobinARH** [comment]
Bug 538989 created to track this issue.

**Comment by sabinn-msft** [comment]
You mean account number, msdyn_company. The screenshots were taken before we installed the company solution. So, they aren't necessarily wrong as the main goal here is to let our customers know that the value of the alternative key in Dataverse must match the key that is defined in the Finance and Operations app. Please let me know if this doesn't help. Much thanks for reporting.

**Comment by sabinn-msft** [comment]
Note: We will be updating the screenshots with the company solution

**Comment by dodiggitydag** [comment]
Thank you!!

Get Outlook<https://aka.ms/qtex0l> for iOS
________________________________

**Comment by RobinARH** [comment]
The new images are published now.
