### ISSUE TITLE
FIK751 and FIK752 Payment Slip setup for Configurable Business Documents

### ISSUE THREAD

**Issue by bhlj** [MicrosoftDocs/dynamics-365-unified-operations-public#2984]
I have a customer where we would like to implement Configurable Business Documents (CBD) for Free Text Invoice and Sales Invoice.

We have setup everything in relation to Free Text Invoice, and it works with CBD, but if I setup on the invoice or the customer to print FIK751 payment slip, it prints the same free text invoice regardless, which results in no payment slip being printed.

Also in the "Free Text Invoice (Excel)" template I havent found anything related to this.

Is there a separate template for this, and also any advise on how to implement this functionality which i guess should be related to danish globalisation.

With regards
Bo Jensen

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0928bf9e-9734-1099-0eb1-a41407fa4647
* Version Independent ID: a670e9fb-684d-a01d-9bca-f7bf767a62b0
* Content: [Set up payment slip format - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/tasks/set-up-payment-slip-format)
* Content Source: [articles/finance/localizations/tasks/set-up-payment-slip-format.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/localizations/tasks/set-up-payment-slip-format.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @EvgenyPopovMBS
* Microsoft Alias: **epopov**

**Comment by ilkond** [comment]
Thank you for the feedback. The described issue is a known functional gap. It is already registered in the backlog for a further product improvement. 

Best regards,
Ilya Kondratenko

_An internal reference: https://msdyneng.visualstudio.com/FinOps/_workitems/edit/446462._
