### ISSUE TITLE
Note field containing planned orders seems to contradict itself

### ISSUE THREAD

**Issue by SXDJoe** [MicrosoftDocs/dynamics-365-unified-operations-public#2985]
Reading through the website it appears that the 'Note' contradicts' itself. Given that the majority of production related planning functionality is not planned to be available before October 20201 its is not feasible for any discrete, lean or process manufacturer using the planning optimization.

Also companies relying on Intercompany calculation will be hit hard.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a36c4831-276b-03c6-6f92-532746789338
* Version Independent ID: 5fdd62c5-5a0a-bf23-6dab-ad3717f5f70d
* Content: [Get started with Planning Optimization - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/master-planning/planning-optimization/get-started?source=docs)
* Content Source: [articles/supply-chain/master-planning/planning-optimization/get-started.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/master-planning/planning-optimization/get-started.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @ChristianRytt
* Microsoft Alias: **crytt**

**Comment by tonyafehr** [comment]
@SXDJoe, thanks for the feedback.  
@ChristianRytt, please review.

**Comment by ChristianRytt** [comment]
@SXDJoe, please point to the exact text that you believe contradict it self. Thanks.

Text in Note is: "You need to request an exception from migration to Planning Optimization if your master planning process does not include production (master planning generated planned production orders) and you require the built-in master planning engine beyond version 10.0.15. Starting in version 10.0.16, an error will be shown in environments when running built-in master planning without generation of planned production orders. Planning Optimization should be used for all new deployments that do not generate planned production orders during master planning. Owners of existing environments running the built-in master planning engine without generation of Planned production orders, will receive a mail with details about the exception process. We recommend that you work with a partner to evaluate and plan the migration to Planning Optimization."

**Comment by SXDJoe** [comment]
Hello,

I believe these two are in contradiction.
You need to request an exception from migration to Planning Optimization if your master planning process does not include production (master planning generated planned production orders) and you require the built-in master planning engine beyond version 10.0.15.


Planning Optimization should be used for all new deployments that do not generate planned production orders during master planning.

Best regards

Joe Gramann
[cid:image002.png@01D6C8EA.9B498F00]
