### ISSUE TITLE
Sample Calculations for the Adjusted Forecast 

### ISSUE THREAD

**Issue by Karandeepbedi041** [MicrosoftDocs/dynamics-365-unified-operations-public#2989]
Request to please share some more details on the sample calculations for the Adjusted Forecast suggested by Machine Learning.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e5d0e5-6293-10a2-bd86-36815589bab0
* Version Independent ID: ae3a0cdd-93e5-5f26-1b5f-679d90f8d0b4
* Content: [Demand forecasting setup - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/master-planning/demand-forecasting-setup)
* Content Source: [articles/supply-chain/master-planning/demand-forecasting-setup.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/master-planning/demand-forecasting-setup.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @roxanadiaconu
* Microsoft Alias: **kamaybac**

**Comment by sericks007** [comment]
@Karandeepbedi041, thanks for providing feedback here.

@roxanadiaconu or @kamaybac, please review and consider updating the content.

**Comment by sericks007** [comment]
Bug 534658 has been logged for this issue.
