### ISSUE TITLE
Additional scenarios would be helpful

### ISSUE THREAD

**Issue by GaborJF** [MicrosoftDocs/dynamics-365-unified-operations-public#299]
As an example, why can't we add a Project ID after confirmation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d09ece69-12d2-04e0-016c-f92d207f0d0c
* Version Independent ID: 077bc53d-fa09-d4c8-083f-2ecc53a1a667
* Content: [Approve and confirm purchase orders - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/procurement/purchase-order-approval-confirmation)
* Content Source: [articles/supply-chain/procurement/purchase-order-approval-confirmation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/procurement/purchase-order-approval-confirmation.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @FrankDahl
* Microsoft Alias: **fdahl**

**Comment by ShylaThompson** [comment]
@GaborJF, Thanks for your feedback. We've added this work to our planned future work.
