### ISSUE TITLE
Dual-write currently has a limit of 40 legal entities.

### ISSUE THREAD

**Issue by ItRefresh** [MicrosoftDocs/dynamics-365-unified-operations-public#2991]
If you have more than 40 customers/accounts, are they not integrated?

**Comment by sericks007** [comment]
Closing this issue.  We'll work from [issue #2992](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/issues/2992).

**Comment by ItRefresh** [comment]
Sorry, it's not accounts, it's entities.

> Fechando esta edição. Trabalharemos a partir de [problemas #2992.](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/issues/2992)
