### ISSUE TITLE
If you have more than 40 customers/accounts, are they not integrated?

### ISSUE THREAD

**Issue by ItRefresh** [MicrosoftDocs/dynamics-365-unified-operations-public#2992]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cdfc828-1858-2f25-2a41-524da2577ea0
* Version Independent ID: 2955b17e-f122-1f22-5380-1e7467af71d2
* Content: [System requirements for dual-write - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/dual-write-system-req)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/dual-write-system-req.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/dual-write/dual-write-system-req.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RamaKrishnamoorthy
* Microsoft Alias: **ramasri**

**Comment by sericks007** [comment]
@ItRefresh, thanks for logging this feedback.

@RamaKrishnamoorthy, can you please answer this question, and consider updating the content, as necessary.

**Comment by CaptainCowell** [comment]
Hi Guilherme,

I believe you may be confusing Legal Entities - the registered companies that make up your organisation - with Customers your organisation does business with.

Take for example an organisation made up of a group/parent company (A) and two subsidiaries (B & C), each registered separately with the appropriate government and tax authorities. If the parent company chose to run the accounts and operations of all three companies on a single instance of Dynamics 365 for Finance & Operations, then each company would be a different Legal Entity within that system - Company A, Company B, and Company C - three Legal Entities. The businesses or individuals that each company sells to would be set up as Customer Accounts within the respective Legal Entity, possibly hundreds or thousands of them.

When the Microsoft article about the system requirements for dual-write states that there is a limit of 40 Legal Entities, it means it would work not just for the 3 companies in the example above, but for up to 40 companies/Legal Entities, and it would work for all the hundreds or thousands of customer accounts within those Legal Entities.

Most organisations using Dynamics 365 for Finance & Operations will not have more than 40 Legal Entities and so this limit will not become a problem for them.

I hope this helps.

Best regards,

Andrew Cowell

**Comment by ItRefresh** [comment]
Obrigado.
