### ISSUE TITLE
Wrong screen shot on revenue recognition schedule 

### ISSUE THREAD

**Issue by MarcioMartineli** [MicrosoftDocs/dynamics-365-unified-operations-public#2993]
The screenshot for Revenue Recognition Schedule detail is showing the Revenue Schedule setup. Please, change because it make confusion when you go to sales order and periodic tasks and see different screen. 

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa35ab95-235c-a9ee-c8c3-638ac5a46000
* Version Independent ID: 6438b40a-a552-e6d7-b4e1-2b8597446a94
* Content: [Revenue recognition overview - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/accounts-receivable/revenue-recognition-overview)
* Content Source: [articles/finance/accounts-receivable/revenue-recognition-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/accounts-receivable/revenue-recognition-overview.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @kweekley
* Microsoft Alias: **kweekley**

**Comment by josaw1** [comment]
Thank you for your feedback. @kweekley can you please take a look?

**Comment by josaw1** [comment]
BUG 535340 created to track the issue.

**Comment by josaw1** [comment]
Screenshot is being updated, thanks.
