### ISSUE TITLE
IIS Rest Typo

### ISSUE THREAD

**Issue by retailrealm-tony** [MicrosoftDocs/dynamics-365-unified-operations-public#2995]
Hi, I think there is a typo in this page, it talks about an IIS Rest, as opposed to an IIS Reset
?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3d823bc-f2d5-4089-56dc-f852ae20ed53
* Version Independent ID: 0e79b5b3-c153-ede0-ee72-f8bcc3c77a6f
* Content: [Support for external gift cards - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/gift-card)
* Content Source: [articles/commerce/dev-itpro/gift-card.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/dev-itpro/gift-card.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @rubencdelgado
* Microsoft Alias: **ivanv**

**Comment by josaw1** [comment]
Thanks for your feedback. I will fix this!

**Comment by josaw1** [comment]
Fixed the typo, thanks. The fix will be published in a few hours.
