### ISSUE TITLE
Please improve the update documentation

### ISSUE THREAD

**Issue by jopankow** [MicrosoftDocs/dynamics-365-unified-operations-public#2996]
Hello team!

The documentation in this section https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/updateenvironment-newinfrastructure#production-environment does not appear accurate any longer with the current structure of a self-service environment.

According to a good explanation posted from a Partner here https://www.yammer.com/dynamicsaxfeedbackprograms/#/threads/show?threadId=727603441950720 : 

_"When you update a production self-service environment it's not being updated with the deployable package you apply, but the state of a sandbox environment. So, when you apply a DP to a sandbox environment you give a name to that update (this will be the state), and then in prod you select this state to be promoted as the production environment."_

Based on recent customer and internal team feedback, what is described above appears to be a more accurate description of the update process. Meaning that steps such as step #4 "In the grid, select the update to apply to the production environment. This grid shows only updates that have been marked as release candidates." is not correct and leads to confusion why a customer cannot select a previous package.

Please update the documentation to provide customers with an improved explanation of how updating production is performed along with appropriate steps.

Please let me know if you have any questions.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f5ff8cf-5739-86d9-26e2-2804b2f37973
* Version Independent ID: 5ca5612d-f4ec-5e7d-222c-678962aa2da7
* Content: [Update an environment - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/updateenvironment-newinfrastructure)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/updateenvironment-newinfrastructure.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/deployment/updateenvironment-newinfrastructure.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by josaw1** [comment]
Thank you for your feedback. @laneswenka can you please review?

**Comment by josaw1** [comment]
BUG 535336 created to track the issue.
