### ISSUE TITLE
[Question] For query cookbook "List most expensive queries", what is the type of time in the output?

### ISSUE THREAD

**Issue by AndreasHassing** [MicrosoftDocs/dynamics-365-unified-operations-public#2997]
Hi, when using the "List most expensive queries", what is the type of time in the output? Is it milliseconds? Nanoseconds?

I'm seeing numbers in an environment that I would not expect for those queries, but I can't figure out if the numbers are normal or not since I'm not sure which unit they're in.

It would be useful to have it in the documentation or annotated on the column names 😊.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b75b1a49-8365-0fc4-5c27-677ff4b26325
* Version Independent ID: 98fcce36-1717-a210-0bb6-5c7f48bdf36f
* Content: [Query cookbook - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/querycookbook#list-most-expensive-queries)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/querycookbook.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/lifecycle-services/querycookbook.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @meeramahabala
* Microsoft Alias: **meeram**

**Comment by sericks007** [comment]
@meeramahabala, please update the content to address this issue.
