### ISSUE TITLE
The Developers tool addin project cannot compile

### ISSUE THREAD

**Issue by rabol** [MicrosoftDocs/dynamics-365-unified-operations-public#2998]
If you create a new project in Visual studio and select the 'Developer Tools addin', a new project is created via the template, but it is not possible to build the project due to the fact that a lot is missing.

Is there a new template or som documentation on how to fix the errors

(Please have in mind that this is happening on a VM that is provisioned and configured by Microsoft)

these are the errors:

`1>------ Build started: Project: TestDeveloperToolsAddin, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3274: The primary reference "Microsoft.Dynamics.Framework.Tools.Core, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL" could not be resolved because it was built against the ".NETFramework,Version=v4.7.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5.2".

1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3275: The primary reference "Microsoft.Dynamics.Framework.Tools.MetaModel.Core" could not be resolved because it has an indirect dependency on the assembly "Microsoft.Dynamics.Framework.Tools.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" which was built against the ".NETFramework,Version=v4.7.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5.2".

1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3275: The primary reference "Microsoft.Dynamics.Framework.Tools.Extensibility, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the assembly "Microsoft.Dynamics.Framework.Tools.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" which was built against the ".NETFramework,Version=v4.7.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5.2".

1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3275: The primary reference "Microsoft.Dynamics.Framework.Tools.Configuration, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the assembly "Microsoft.Dynamics.Framework.Tools.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" which was built against the ".NETFramework,Version=v4.7.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5.2".

1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3275: The primary reference "Microsoft.Dynamics.Framework.Tools.AutomationObjects, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the assembly "Microsoft.Dynamics.Framework.Tools.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" which was built against the ".NETFramework,Version=v4.7.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5.2".

1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3274: The primary reference "Microsoft.Dynamics.Framework.Tools.Extensibility, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL" could not be resolved because it was built against the ".NETFramework,Version=v4.7.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5.2".

1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3275: The primary reference "Microsoft.Dynamics.Framework.Tools.MetaModel.Core" could not be resolved because it has an indirect dependency on the assembly "Microsoft.Dynamics.Framework.Tools.Extensibility, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" which was built against the ".NETFramework,Version=v4.7.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5.2".

1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3275: The primary reference "Microsoft.Dynamics.Framework.Tools.AutomationObjects, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the assembly "Microsoft.Dynamics.Framework.Tools.Extensibility, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" which was built against the ".NETFramework,Version=v4.7.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5.2".

1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3274: The primary reference "Microsoft.Dynamics.Framework.Tools.MetaModel.Core" could not be resolved because it was built against the ".NETFramework,Version=v4.7.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5.2".

1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3275: The primary reference "Microsoft.Dynamics.Framework.Tools.AutomationObjects, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the assembly "Microsoft.Dynamics.Framework.Tools.MetaModel.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" which was built against the ".NETFramework,Version=v4.7.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5.2".

1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3274: The primary reference "Microsoft.Dynamics.Framework.Tools.AutomationObjects, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL" could not be resolved because it was built against the ".NETFramework,Version=v4.7.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5.2".

1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3274: The primary reference "Microsoft.Dynamics.Framework.Tools.Configuration, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL" could not be resolved because it was built against the ".NETFramework,Version=v4.7.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5.2".

1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3275: The primary reference "Microsoft.Dynamics.Framework.Tools.AutomationObjects, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the assembly "Microsoft.Dynamics.Framework.Tools.Configuration, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" which was built against the ".NETFramework,Version=v4.7.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5.2".

1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3274: The primary reference "Microsoft.Dynamics.Framework.Tools.Integration, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL" could not be resolved because it was built against the ".NETFramework,Version=v4.7.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5.2".

1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3275: The primary reference "Microsoft.Dynamics.Framework.Tools.MetaModel.Core" could not be resolved because it has an indirect dependency on the assembly "Microsoft.Dynamics.Framework.Tools.Integration, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" which was built against the ".NETFramework,Version=v4.7.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5.2".

1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3275: The primary reference "Microsoft.Dynamics.Framework.Tools.AutomationObjects, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the assembly "Microsoft.Dynamics.Framework.Tools.Integration, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" which was built against the ".NETFramework,Version=v4.7.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5.2".

1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3275: The primary reference "Microsoft.Dynamics.Framework.Tools.AutomationObjects, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the assembly "Microsoft.Dynamics.Framework.Tools.ProjectSupport, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" which was built against the ".NETFramework,Version=v4.7.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5.2".

1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3275: The primary reference "Microsoft.Dynamics.Framework.Tools.MetaModel.Core" could not be resolved because it has an indirect dependency on the assembly "Microsoft.Dynamics.Framework.Tools.ProjectSupport, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" which was built against the ".NETFramework,Version=v4.7.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5.2".

1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3275: The primary reference "Microsoft.Dynamics.Framework.Tools.AutomationObjects, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the assembly "Microsoft.Dynamics.AX.Framework.BestPracticeFramework, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" which was built against the ".NETFramework,Version=v4.7.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5.2".

1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3275: The primary reference "Microsoft.Dynamics.Framework.Tools.MetaModel.Core" could not be resolved because it has an indirect dependency on the assembly "Microsoft.Dynamics.AX.Framework.BestPracticeFramework, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" which was built against the ".NETFramework,Version=v4.7.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5.2".

1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3275: The primary reference "Microsoft.Dynamics.Framework.Tools.AutomationObjects, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the assembly "Microsoft.Dynamics.Framework.Tools.MetaModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" which was built against the ".NETFramework,Version=v4.7.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5.2".

1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3275: The primary reference "Microsoft.Dynamics.Framework.Tools.AutomationObjects, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the assembly "Microsoft.Dynamics.Framework.Tools.BrowserWrapper, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" which was built against the ".NETFramework,Version=v4.7.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5.2".

1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3275: The primary reference "Microsoft.Dynamics.Framework.Tools.AutomationObjects, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the assembly "Microsoft.Dynamics.Framework.Tools.MetaModel.ModelConverter, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" which was built against the ".NETFramework,Version=v4.7.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5.2".

1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3275: The primary reference "Microsoft.Dynamics.Framework.Tools.AutomationObjects, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the assembly "Microsoft.Dynamics.Framework.Tools.SourceControl, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" which was built against the ".NETFramework,Version=v4.7.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5.2".

1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3275: The primary reference "Microsoft.Dynamics.Framework.Tools.MetaModel.Core" could not be resolved because it has an indirect dependency on the assembly "Microsoft.Dynamics.Framework.Tools.SourceControl, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" which was built against the ".NETFramework,Version=v4.7.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5.2".

1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3275: The primary reference "Microsoft.Dynamics.Framework.Tools.AutomationObjects, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the assembly "Microsoft.Dynamics.AX.Framework.BestPracticeExtensions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" which was built against the ".NETFramework,Version=v4.7.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5.2".

1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3275: The primary reference "Microsoft.Dynamics.Framework.Tools.MetaModel.Core" could not be resolved because it has an indirect dependency on the assembly "Microsoft.Dynamics.AX.Framework.BestPracticeExtensions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" which was built against the ".NETFramework,Version=v4.7.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5.2".

1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3275: The primary reference "Microsoft.Dynamics.Framework.Tools.AutomationObjects, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the assembly "Microsoft.Dynamics.Framework.Tools.Labels.Resolvers, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" which was built against the ".NETFramework,Version=v4.7.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5.2".

1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3275: The primary reference "Microsoft.Dynamics.Framework.Tools.MetaModel.Core" could not be resolved because it has an indirect dependency on the assembly "Microsoft.Dynamics.Framework.Tools.Labels.Resolvers, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" which was built against the ".NETFramework,Version=v4.7.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5.2".

1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3275: The primary reference "Microsoft.Dynamics.Framework.Tools.AutomationObjects, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the assembly "Microsoft.Dynamics.AX.Metadata.ApplicationService, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" which was built against the ".NETFramework,Version=v4.7.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5.2".

1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3275: The primary reference "Microsoft.Dynamics.Framework.Tools.AutomationObjects, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the assembly "Microsoft.Dynamics.Framework.Tools.LanguageService.Parser, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" which was built against the ".NETFramework,Version=v4.7.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5.2".

1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3275: The primary reference "Microsoft.Dynamics.Framework.Tools.AutomationObjects, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the assembly "Microsoft.Dynamics.Framework.Tools.MetaModelStrings, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" which was built against the ".NETFramework,Version=v4.7.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5.2".

1>C:\Users\Admin1bd4f5190c\Documents\Visual Studio 2015\Projects\TestDeveloperToolsAddin\TestDeveloperToolsAddin\MainMenuAddIn.cs(9,46,9,59): error CS0234: The type or namespace name 'Extensibility' does not exist in the namespace 'Microsoft.Dynamics.Framework.Tools' (are you missing an assembly reference?)

1>C:\Users\Admin1bd4f5190c\Documents\Visual Studio 2015\Projects\TestDeveloperToolsAddin\TestDeveloperToolsAddin\DesignerContextMenuAddIn.cs(7,46,7,59): error CS0234: The type or namespace name 'Extensibility' does not exist in the namespace 'Microsoft.Dynamics.Framework.Tools' (are you missing an assembly reference?)

1>C:\Users\Admin1bd4f5190c\Documents\Visual Studio 2015\Projects\TestDeveloperToolsAddin\TestDeveloperToolsAddin\DesignerContextMenuAddIn.cs(8,56,8,66): error CS0234: The type or namespace name 'Automation' does not exist in the namespace 'Microsoft.Dynamics.Framework.Tools.MetaModel' (are you missing an assembly reference?)

1>C:\Users\Admin1bd4f5190c\Documents\Visual Studio 2015\Projects\TestDeveloperToolsAddin\TestDeveloperToolsAddin\DesignerContextMenuAddIn.cs(9,56,9,66): error CS0234: The type or namespace name 'Automation' does not exist in the namespace 'Microsoft.Dynamics.Framework.Tools.MetaModel' (are you missing an assembly reference?)

1>C:\Users\Admin1bd4f5190c\Documents\Visual Studio 2015\Projects\TestDeveloperToolsAddin\TestDeveloperToolsAddin\DesignerContextMenuAddIn.cs(10,56,10,66): error CS0234: The type or namespace name 'Automation' does not exist in the namespace 'Microsoft.Dynamics.Framework.Tools.MetaModel' (are you missing an assembly reference?)

1>C:\Users\Admin1bd4f5190c\Documents\Visual Studio 2015\Projects\TestDeveloperToolsAddin\TestDeveloperToolsAddin\MainMenuAddIn.cs(17,34,17,46): error CS0246: The type or namespace name 'MainMenuBase' could not be found (are you missing a using directive or an assembly reference?)

1>C:\Users\Admin1bd4f5190c\Documents\Visual Studio 2015\Projects\TestDeveloperToolsAddin\TestDeveloperToolsAddin\DesignerContextMenuAddIn.cs(22,45,22,61): error CS0246: The type or namespace name 'DesignerMenuBase' could not be found (are you missing a using directive or an assembly reference?)

1>C:\Users\Admin1bd4f5190c\Documents\Visual Studio 2015\Projects\TestDeveloperToolsAddin\TestDeveloperToolsAddin\MainMenuAddIn.cs(16,20,16,29): error CS0246: The type or namespace name 'IMainMenu' could not be found (are you missing a using directive or an assembly reference?)

1>C:\Users\Admin1bd4f5190c\Documents\Visual Studio 2015\Projects\TestDeveloperToolsAddin\TestDeveloperToolsAddin\MainMenuAddIn.cs(53,38,53,52): error CS0246: The type or namespace name 'AddinEventArgs' could not be found (are you missing a using directive or an assembly reference?)

1>C:\Users\Admin1bd4f5190c\Documents\Visual Studio 2015\Projects\TestDeveloperToolsAddin\TestDeveloperToolsAddin\MainMenuAddIn.cs(27,32,27,39): error CS0115: 'MainMenuAddIn.Caption': no suitable method found to override

1>C:\Users\Admin1bd4f5190c\Documents\Visual Studio 2015\Projects\TestDeveloperToolsAddin\TestDeveloperToolsAddin\MainMenuAddIn.cs(38,32,38,36): error CS0115: 'MainMenuAddIn.Name': no suitable method found to override

1>C:\Users\Admin1bd4f5190c\Documents\Visual Studio 2015\Projects\TestDeveloperToolsAddin\TestDeveloperToolsAddin\MainMenuAddIn.cs(53,30,53,37): error CS0115: 'MainMenuAddIn.OnClick(AddinEventArgs)': no suitable method found to override

1>C:\Users\Admin1bd4f5190c\Documents\Visual Studio 2015\Projects\TestDeveloperToolsAddin\TestDeveloperToolsAddin\DesignerContextMenuAddIn.cs(20,6,20,32): error CS0246: The type or namespace name 'DesignerMenuExportMetadataAttribute' could not be found (are you missing a using directive or an assembly reference?)

1>C:\Users\Admin1bd4f5190c\Documents\Visual Studio 2015\Projects\TestDeveloperToolsAddin\TestDeveloperToolsAddin\DesignerContextMenuAddIn.cs(20,6,20,32): error CS0246: The type or namespace name 'DesignerMenuExportMetadata' could not be found (are you missing a using directive or an assembly reference?)

1>C:\Users\Admin1bd4f5190c\Documents\Visual Studio 2015\Projects\TestDeveloperToolsAddin\TestDeveloperToolsAddin\DesignerContextMenuAddIn.cs(21,6,21,32): error CS0246: The type or namespace name 'DesignerMenuExportMetadataAttribute' could not be found (are you missing a using directive or an assembly reference?)

1>C:\Users\Admin1bd4f5190c\Documents\Visual Studio 2015\Projects\TestDeveloperToolsAddin\TestDeveloperToolsAddin\DesignerContextMenuAddIn.cs(21,6,21,32): error CS0246: The type or namespace name 'DesignerMenuExportMetadata' could not be found (are you missing a using directive or an assembly reference?)

1>C:\Users\Admin1bd4f5190c\Documents\Visual Studio 2015\Projects\TestDeveloperToolsAddin\TestDeveloperToolsAddin\DesignerContextMenuAddIn.cs(16,20,16,33): error CS0246: The type or namespace name 'IDesignerMenu' could not be found (are you missing a using directive or an assembly reference?)

1>C:\Users\Admin1bd4f5190c\Documents\Visual Studio 2015\Projects\TestDeveloperToolsAddin\TestDeveloperToolsAddin\DesignerContextMenuAddIn.cs(20,33,20,51): error CS0246: The type or namespace name 'AutomationNodeType' could not be found (are you missing a using directive or an assembly reference?)

1>C:\Users\Admin1bd4f5190c\Documents\Visual Studio 2015\Projects\TestDeveloperToolsAddin\TestDeveloperToolsAddin\DesignerContextMenuAddIn.cs(20,61,20,66): error CS0246: The type or namespace name 'IForm' could not be found (are you missing a using directive or an assembly reference?)

1>C:\Users\Admin1bd4f5190c\Documents\Visual Studio 2015\Projects\TestDeveloperToolsAddin\TestDeveloperToolsAddin\DesignerContextMenuAddIn.cs(21,33,21,51): error CS0246: The type or namespace name 'AutomationNodeType' could not be found (are you missing a using directive or an assembly reference?)

1>C:\Users\Admin1bd4f5190c\Documents\Visual Studio 2015\Projects\TestDeveloperToolsAddin\TestDeveloperToolsAddin\DesignerContextMenuAddIn.cs(21,61,21,67): error CS0246: The type or namespace name 'ITable' could not be found (are you missing a using directive or an assembly reference?)

1>C:\Users\Admin1bd4f5190c\Documents\Visual Studio 2015\Projects\TestDeveloperToolsAddin\TestDeveloperToolsAddin\DesignerContextMenuAddIn.cs(57,38,57,60): error CS0246: The type or namespace name 'AddinDesignerEventArgs' could not be found (are you missing a using directive or an assembly reference?)

1>C:\Users\Admin1bd4f5190c\Documents\Visual Studio 2015\Projects\TestDeveloperToolsAddin\TestDeveloperToolsAddin\DesignerContextMenuAddIn.cs(32,32,32,39): error CS0115: 'DesignerContextMenuAddIn.Caption': no suitable method found to override

1>C:\Users\Admin1bd4f5190c\Documents\Visual Studio 2015\Projects\TestDeveloperToolsAddin\TestDeveloperToolsAddin\DesignerContextMenuAddIn.cs(43,32,43,36): error CS0115: 'DesignerContextMenuAddIn.Name': no suitable method found to override

1>C:\Users\Admin1bd4f5190c\Documents\Visual Studio 2015\Projects\TestDeveloperToolsAddin\TestDeveloperToolsAddin\DesignerContextMenuAddIn.cs(57,30,57,37): error CS0115: 'DesignerContextMenuAddIn.OnClick(AddinDesignerEventArgs)': no suitable method found to override
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c0fd67d-3893-4c9f-6557-d6bbb35612be
* Version Independent ID: 20f7e397-b928-6db1-67a5-26158fa301c1
* Content: [Tools add-ins for Visual Studio - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/developer-tools-add-ins)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/developer-tools-add-ins.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-tools/developer-tools-add-ins.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **jorisde**

**Comment by jorisdg** [comment]
This is not a docs issue but a product issue. Please use support for these types of questions/problems.
That said, we're aware of this problem. It will take time to roll out this SDK on the VMs, however, plus it would require you to redeploy. I suggest you just manually install the SDK for 4.7.2.
@kfend please close this ticket.
