### ISSUE TITLE
Update of the tips section required

### ISSUE THREAD

**Issue by mueckeflo** [MicrosoftDocs/dynamics-365-unified-operations-public#2999]
Hi,

In the tips section it should be mentioned to "Initialize Commerce" after an update, because only this step will have the correct seed data available for the "Initialize commerce scheduler" step, which should be executed afterwards.

In addition, probably the environment provisioning step is obsolete in the menatime, as a DB move will AFAIK run the provisioning automatically.

Best regards,
Florian

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c7b3c63-e35a-98b5-6711-7dd53e948a47
* Version Independent ID: cd9fb3c9-3fa9-3336-d904-e75e27235d84
* Content: [Update code and environments for Commerce projects - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/updating-environments)
* Content Source: [articles/commerce/dev-itpro/updating-environments.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/dev-itpro/updating-environments.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @andreashofmann1
* Microsoft Alias: **andreash**

**Comment by kfend** [comment]
@mueckeflo - thank you for the feedback.
@andreashofmann1 - can you please take a look and update the topic as necessary?

**Comment by tonyafehr** [comment]
@josaw1, please review.

**Comment by josaw1** [comment]
@jashanno can you please do a quick review of this feedback? Thanks.

**Comment by josaw1** [comment]
Closing as won't fix.
