### ISSUE TITLE
Section heading is too small

### ISSUE THREAD

**Issue by brettchristiansen** [MicrosoftDocs/dynamics-365-unified-operations-public#300]
The heading for the section titled "How to generate C# proxy (this applicable for both POS and Ecommerce) for 7.3" should be larger, to match that of the other sections.  It is easy to miss and appears that everything after the  "Generate the C# proxy (7.1 and 7.2) - These steps are not applicable for version 7.3 and higher" section is irrelevant to newer versions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a867b6d-203b-02c9-13b0-cd628a278738
* Version Independent ID: ac581ae9-19fa-f20b-c09d-bfa79e6b3e35
* Content: [Typescript and C# proxies for Retail point of sale (POS) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/dev-itpro/typescript-proxy-retail-pos)
* Content Source: [articles/retail/dev-itpro/typescript-proxy-retail-pos.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/dev-itpro/typescript-proxy-retail-pos.md)
* Service: **dynamics-365-retail**
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by kfend** [comment]
Thanks for the feedback. The topic formatting has been updated.
