### ISSUE TITLE
Feature "Recommended fields" not mentioned here Feature added 5/15/2020

### ISSUE THREAD

**Issue by BernhardRaether** [MicrosoftDocs/dynamics-365-unified-operations-public#3001]
To Whom it may concern

I found this page when checking above Feature Recommended Fields "Learn more" Link: https://docs.microsoft.com/en-us/dynamics365-release-plan/2020wave1/finance-operations-crossapp-capabilities/recommended-fields

that gives this page as the "See also" link.

Unfortunately, this Feature is not described, neither in the spelling "Recommended Field" nor "Suggested Fields"

From the description it seems to me that this feature needs to be added here, see Text
"Description
Users often need to add fields to a grid or page; however, with the large number of available fields, this can be difficult. Instead of having to search through a large list, this feature enables the system to surface a set of recommended fields based on what other users most often add in similar scenarios."

Thanks in advance,
Bernhard

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad8be7cd-8a59-b385-2c6a-763ebd5956fa
* Version Independent ID: 7f1dde5c-a26c-55bf-118c-513b95fe07e8
* Content: [Personalize the user experience - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/personalize-user-experience)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/personalize-user-experience.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/get-started/personalize-user-experience.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by RobinARH** [comment]
@jasongre @sericks007 Can you take a look? Thanks.

**Comment by sericks007** [comment]
@jasongre, what is your recommendation here?

**Comment by RobinARH** [comment]
Bug 538991 created to track this issue.

**Comment by BernhardRaether** [comment]
Any News on this one?
Regards,
Bernhard

**Comment by jasongre** [comment]
Adding a reference in the "Add fields" tool section to field recommendations
