### ISSUE TITLE
TSP100 printer does not work.

### ISSUE THREAD

**Issue by n2aQFc8** [MicrosoftDocs/dynamics-365-unified-operations-public#3002]
you say the TSP100 printer works, as long as you use the TSP650II drivers (Requires TSP650II drivers...) and OPOS

This is false. I have a TSP143U printer attached. I then change the printer driver to use TSP650II driver. Then, in the Star Micronics Printer Utility i configure the printer as an OPOS object. Printer does not response to checkhealth even though it shows success. I suspect someone tested this in a virtual peripheral and not with the printer to see that even though on the screen it works, it doesnt physically print anything, and no errors are apparent.

If I am mistaken, PLEASE provide how you made this work with TSP100 series printers.. That would save us a massive amount of money.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b7320ce-06d2-0dea-0077-c87e0c0a5e07
* Version Independent ID: 95ff0b85-b3a2-df8e-a0d2-ed85cc0ad3fe
* Content: [Peripherals - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/retail-peripherals-overview)
* Content Source: [articles/commerce/retail-peripherals-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/retail-peripherals-overview.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @rubencdelgado
* Microsoft Alias: **rubendel**

**Comment by RobinARH** [comment]
@rubencdelgado Can you take a look? Thanks.

**Comment by RobinARH** [comment]
Bug 538992 to track this issue.

**Comment by rubencdelgado** [comment]
The workaround to use the TSP 650 OPOS driver for the TSP 100 was suggested by Star Micronics and tested internally at the time. Much time has passed and the person who performed the testing is no longer working for Microsoft. So I am unable to share notes on how to perform the workaround. 

That said, it appears Star has published a TSP 100 specific OPOS driver. That documentation can be found here: https://www.starmicronics.com/help-center/knowledge-base/how-to-install-opos-or-javapos-on-tsp100-series-on-windows-os/

For questions related to the driver, please contact Star Micronics. The reference to the workaround will be removed from the Microsoft Docs article and the TSP 100 will be listed as "Tested" once we have the opportunity to test the TSP-specific driver.

**Comment by RobinARH** [comment]
The doc update will go live later today.
