### ISSUE TITLE
Consolidations that involve eliminations picture is not matching text

### ISSUE THREAD

**Issue by sheko89** [MicrosoftDocs/dynamics-365-unified-operations-public#3005]
Hi, the picture showing under the sectio:
Consolidations that involve eliminations

is not matching text explanation in terms of column names D, E etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b756c251-5255-35b7-bf32-522f738b526d
* Version Independent ID: 257f9aa2-1914-0715-f9de-4d0ab2b0369f
* Content: [Generate consolidated financial statements - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/general-ledger/generating-consolidated-financial-statements)
* Content Source: [articles/finance/general-ledger/generating-consolidated-financial-statements.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/general-ledger/generating-consolidated-financial-statements.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @aprilolson
* Microsoft Alias: **aolson**

**Comment by RobinARH** [comment]
@aprilolson Can you take a look? Thanks.

**Comment by aprilolson** [comment]
@Jinnie Wong<mailto:jiwo@microsoft.com> is PM

April Olson
(She/her/hers)
Our workforce allows for a flexible schedule. I am sending his now as its convenient for me. I do not expect you to read or respond until it’s convenient to you.

**Comment by RobinARH** [comment]
Bug 538995 created to track this issue.
