### ISSUE TITLE
Incorrect feature name

### ISSUE THREAD

**Issue by jopankow** [MicrosoftDocs/dynamics-365-unified-operations-public#3006]
The feature name "Reset draft status for the vendor invoice workflow" is incorrect in the section:

This feature is available if the _**Reset draft status for the vendor invoice workflow**_ parameter on the Feature management page is turned on.

Section link: https://docs.microsoft.com/en-us/dynamics365/finance/accounts-payable/vendor-invoices-overview#resetting-the-workflow-status-for-vendor-invoices-from-unrecoverable-to-draft

The actual feature name is "**Resetting the workflow status for vendor invoices from Unrecoverable to Draft**". 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c98ee491-2235-4add-5e8f-239fd12f2a01
* Version Independent ID: 48a82238-dab1-ac14-24f3-ec675698ad4c
* Content: [Vendor invoices overview - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/accounts-payable/vendor-invoices-overview#resetting-the-workflow-status-for-vendor-invoices-from-unrecoverable-to-draft)
* Content Source: [articles/finance/accounts-payable/vendor-invoices-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/accounts-payable/vendor-invoices-overview.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @abruer
* Microsoft Alias: **abruer**

**Comment by RobinARH** [comment]
@abruer Can you take a look? Thanks.

**Comment by abruer** [comment]
Thank you very much for your feedback. We have updated the topic. The changes should be published within the next day.
