### ISSUE TITLE
Error in auto update date

### ISSUE THREAD

**Issue by kasperrytter** [MicrosoftDocs/dynamics-365-unified-operations-public#3007]
In the auto-update for 10.0.15 you have written January 2020. It should be 2021.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a81f2d2a-8eac-df73-bf48-2a59ad0ff5ac
* Version Independent ID: 26eb9087-c4d9-85e4-957c-9144269800ee
* Content: [What's new or changed in Dynamics 365 Finance - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/get-started/whats-new-home-page)
* Content Source: [articles/finance/get-started/whats-new-home-page.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/get-started/whats-new-home-page.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @roschlom
* Microsoft Alias: **roschlom**

**Comment by tonyafehr** [comment]
@kasperrytter, thanks for the feedback. 
@roschlom, please review.

**Comment by tonyafehr** [comment]
This has been fixed, thanks!
