### ISSUE TITLE
No release notes publicly available for Supply Chain Management

### ISSUE THREAD

**Issue by kasperrytter** [MicrosoftDocs/dynamics-365-unified-operations-public#3008]
Hi,

For Finance and for Commerce the release notes for version 10.0.15 are available in the overview. For supply chain management they are not. Have you forgot to update this page (considering 10.0.15 is generally available the release notes should be there)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c023fc2-87cd-c17b-5578-dc830ab6b015
* Version Independent ID: 73ff0eda-6e9c-f859-da8a-01acf5c31908
* Content: [What's new or changed in Dynamics 365 Supply Chain Management - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/get-started/whats-new-home-page)
* Content Source: [articles/supply-chain/get-started/whats-new-home-page.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/get-started/whats-new-home-page.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @kamaybac
* Microsoft Alias: **kamaybac**

**Comment by tonyafehr** [comment]
@kasperrytter, thanks for the feedback. 
@kamaybac, please review.

**Comment by kamaybac** [comment]
@kasperrytter , thank you for pointing out this oversight. We have now updated the page.
