### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by brettchristiansen** [MicrosoftDocs/dynamics-365-unified-operations-public#301]
Step 5 of the "How to generate C# proxy (this applicable for both POS and Ecommerce) for 7.3" section is missing the names of the nodes that need to be updated in the .csproj file.  I think it should have these node names showing:

&lt;RootNamespace&gt; - Update it with your custom namespace
&lt;AssemblyName&gt; - Update it with your custom output library name for the proxy
&lt;RetailServerExtensionLibraryNoPrefixForRetailProxyCSharpExtensionGeneration&gt; - Update it with your retail server extension library name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a867b6d-203b-02c9-13b0-cd628a278738
* Version Independent ID: ac581ae9-19fa-f20b-c09d-bfa79e6b3e35
* Content: [Typescript and C# proxies for Retail point of sale (POS) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/dev-itpro/typescript-proxy-retail-pos)
* Content Source: [articles/retail/dev-itpro/typescript-proxy-retail-pos.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/dev-itpro/typescript-proxy-retail-pos.md)
* Service: **dynamics-365-retail**
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by ShylaThompson** [comment]
Bug # 239513 logged for investigation.

**Comment by mugunthanm** [comment]
Step 5  of  "How to generate C# proxy (this applicable for both POS and Ecommerce) for 7.3" section is updated with the right nodes.

**Comment by ShylaThompson** [comment]
@brettchristiansen  Thanks for raising this issue. The topic has been updated and will be republished to reflect the change by the end of this week.
