### ISSUE TITLE
Update documentation with a note about environment availability for pausing

### ISSUE THREAD

**Issue by lma1171** [MicrosoftDocs/dynamics-365-unified-operations-public#3020]
Customers are complaining that right now they are unable to "Pause up to 3 consecutive updates".  We have validated with a Customer Engineer (Dynamics Support Engineer) that in current scenario where a customer is on 10.0.14 and trying to pause 10.0.15, 10.0.16 and 10.0.17 - they are unable to pause 10.0.17 as the environment is not yet available with PEAP date of Feb 1, 2021.  Could you please add a "Note" box to help clarify this.  

And, could you please update the environment version examples to be more current?  10.0.1x and greater?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 878313ed-a9b2-797f-b483-142df974639c
* Version Independent ID: 6fa7a7f2-3fd5-477f-3340-9b13789949d8
* Content: [Pause service updates through Lifecycle Services (LCS) - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/pause-service-updates)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/pause-service-updates.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/lifecycle-services/pause-service-updates.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @AngelMarshall
* Microsoft Alias: **tsmarsha**

**Comment by josaw1** [comment]
Thank you for your detailed feedback. @AngelMarshall, can you please review this request?

**Comment by josaw1** [comment]
BUG 537411 created to track.
