### ISSUE TITLE
paramMap parameter's missing in the second code

### ISSUE THREAD

**Issue by maroweh** [MicrosoftDocs/dynamics-365-unified-operations-public#3024]
In this code on the line below the paramMap parameter is missing.
var results= statement.executeQueryWithParameters(sqlStatementText);

Correct version:
    var results= statement.executeQueryWithParameters(sqlStatementText, paramMap);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d92be4b4-05f4-c8a1-c788-43b2c60f561f
* Version Independent ID: ba5bbde1-9bc7-63f1-8b36-405db7ba6400
* Content: [Mitigate a SQL injection attack - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-ref/query-with-parameters)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-ref/query-with-parameters.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-ref/query-with-parameters.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @pvillads
* Microsoft Alias: **rhaertle**

**Comment by kfend** [comment]
@maroweh - thank you for the feedback.
@RobinARH and @pvillads - can one of you please take a look at this and make the necessary updates?

**Comment by pvillads** [comment]
Confirming problem. Please fix as indicated, passing the paramsMap as a second parameter.

BR PV

**Comment by RobinARH** [comment]
I fixed the topic, and the updated topic will be live later today. - Robin
