### ISSUE TITLE
Need to address what impact on D365 Services going into maintenance mode has

### ISSUE THREAD

**Issue by ronsonntag54** [MicrosoftDocs/dynamics-365-unified-operations-public#3025]
Maintenance mode has a number of consequences. However, this page does not talk about what impact on D365 services like DXF and Batch services maintenance mode has. Please include this information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91ae449b-ec59-28d4-1934-6909e77ee4f3
* Version Independent ID: df6ae442-3466-4c69-aa11-ed35e20a629f
* Content: [Maintenance mode - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/maintenance-mode)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/maintenance-mode.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/sysadmin/maintenance-mode.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by tonyafehr** [comment]
@ronsonntag54, thanks for the feedback. 
@laneswenka, please review.

**Comment by tonyafehr** [comment]
Bug 541330 logged to track this issue.

**Comment by laneswenka** [comment]
@ronsonntag54 what impacts are you referring to?  I am not readily aware of any adverse impact by turning maintenance mode on and then off again, that would continue to affect batch or DIXF.  The article does state "While maintenance mode is on, only system administrators and users who have the Maintenance mode user role can sign in to the system"

**Comment by ronsonntag54** [comment]
Sorry, this is so long ago that I don't remember the context. Might as well close this if there are no consequences.
