### ISSUE TITLE
Limitation on earning points in the same transaction, where they are redeemed.

### ISSUE THREAD

**Issue by ganroman** [MicrosoftDocs/dynamics-365-unified-operations-public#3026]
Is it still not possible to earn the points for the rest of transaction while paying part of transaction with the loyalty card (redemption)? See the following [discussion](https://community.dynamics.com/ax/f/microsoft-dynamics-ax-forum/222379/loyalty-points-earning-and-redemption-in-same-transaction)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69cf7390-d31f-2a76-e67d-2da06cf14ea2
* Version Independent ID: 935e3abe-97b8-0a9c-bb33-ed4489400d4b
* Content: [Loyalty extension sample - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/retail-sdk/loyalty-extension-sample)
* Content Source: [articles/commerce/dev-itpro/retail-sdk/loyalty-extension-sample.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/dev-itpro/retail-sdk/loyalty-extension-sample.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @ShalabhjainMSFT
* Microsoft Alias: **shajain**

**Comment by tonyafehr** [comment]
@ganroman, thanks for the feedback. 
@ShalabhjainMSFT, please review.

**Comment by ShalabhjainMSFT** [comment]
No, this capability has not yet been added to the product, but a few customers have customized the code to do so.
