### ISSUE TITLE
No documentation on where to purchase a subscription to Finance And Operations

### ISSUE THREAD

**Issue by beefcake123** [MicrosoftDocs/dynamics-365-unified-operations-public#3027]
`After your organization has purchased a subscription to Finance and Operations, it must be activated on your organization's Azure Active Directory (Azure AD) tenant by your Tenant Administrator, who completes the following steps:`

This article starts after the step of purchasing a subscription to Finance and Operations. But I can't find any documentation on where we are supposed to purchase this subscription. 

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 6492678f-1cb1-d385-5ea0-28d0a969b865
* Version Independent ID: 786d8b8c-88cd-101c-702b-b9b781957508
* Content: [Onboard an implementation project - Finance & Operations | Dynamics 365](https://docs.microsoft.com/nl-be/dynamics365/fin-ops-core/fin-ops/imp-lifecycle/onboard?toc=/dynamics365/finance/toc.json)
* Content Source: [articles/fin-ops-core/fin-ops/imp-lifecycle/onboard.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/imp-lifecycle/onboard.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @ClaudiaBetz-Haubold
* Microsoft Alias: **chaubold**

**Comment by ClaudiaBetz-Haubold** [comment]
Please refer to this article for different purchasing options: Before you buy - Finance & Operations | Dynamics 365 | Microsoft Docs<https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/before-you-buy?toc=/dynamics365/finance/toc.json>
Kind regards, Claudia Betz-Haubold
