### ISSUE TITLE
Additional information would be helpful.

### ISSUE THREAD

**Issue by rsantana123** [MicrosoftDocs/dynamics-365-unified-operations-public#3028]
Hi, 

Referring specifically to this section of the document: 

> For example, in the error at the top of this page, ITEMTAXGROUPID is the read-only property with the error. You can search to see this is part of CartLine and CartLineData. The configuration name/value pair would look like this:

> RetailReadOnlyExempt_CartLineData : ITEMTAXGROUPID

Where can we "search to see this is part of CartLine and CartLineData" ? 

The document does not specify where we can search for the EntityName and the ColumName values.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f2dc625-8b1a-5f7c-cff5-e723f6e446dd
* Version Independent ID: e03bbb80-6bfb-a6aa-dbeb-334a5bc70b8b
* Content: [Retail SDK FAQ - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/retail-sdk/sdk-faq#how-do-i-handle-a-readonly-cartvalidationexception-error-in-sdk-version-1000-and-later)
* Content Source: [articles/commerce/dev-itpro/retail-sdk/sdk-faq.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/dev-itpro/retail-sdk/sdk-faq.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by tonyafehr** [comment]
@rsantana123, thanks for the feedback. 
@mugunthanm, please review.

**Comment by tonyafehr** [comment]
Bug 541333 logged to track this issue.

**Comment by tonyafehr** [comment]
This topic will be updated later today.
