### ISSUE TITLE
Need more information

### ISSUE THREAD

**Issue by artemt1** [MicrosoftDocs/dynamics-365-unified-operations-public#303]
How to enable PowerBI Embedded integration?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 007a29aa-32bb-bc2e-8c92-aba6cd87aa5d
* Version Independent ID: 8fb71831-2bd7-2d08-9505-0af1e071eb34
* Content: [Power BI Embedded integration - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/power-bi-embedded-integration?toc=/fin-and-ops/toc.json)
* Content Source: [articles/dev-itpro/analytics/power-bi-embedded-integration.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/power-bi-embedded-integration.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by tonyafehr** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support).
