### ISSUE TITLE
Location of admin user provisioning is incorrect

### ISSUE THREAD

**Issue by bgege** [MicrosoftDocs/dynamics-365-unified-operations-public#3030]
The location of the admin user provisioning tool is incorrect, its in K:\AosService\PackagesLocalDirectory\bin, not on the desktop 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe3913a6-4daa-9973-6f0b-d7ae4c1007c2
* Version Independent ID: f2cd311b-fcb8-cff4-57a3-47c3c52b19d6
* Content: [Deploy and access development environments - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/access-instances)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/access-instances.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-tools/access-instances.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by tonyafehr** [comment]
@bgege, thanks for the feedback. 
@laneswenka, please review.

**Comment by tonyafehr** [comment]
Bug 541331 logged to track this issue.

**Comment by laneswenka** [comment]
@tonyafehr  I don't manage the location of this file.  Could you work with @jorisdg  on this please?

**Comment by jorisdg** [comment]
On the VHD there is a shortcut on the desktop. It appears this topic here is under the "vm running local" section but it's not very clear. I can clarify it in the doc that on a VM deployed through LCS there is no shortcut on the desktop.

**Comment by RobinARH** [comment]
The updated doc will go live this evening.
