### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by JJ431** [MicrosoftDocs/dynamics-365-unified-operations-public#3031]
[Point 6 says 'In the Assigned hierarchies sectiom, click Add.' in stead of 'section']

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47255864-7134-164c-d1dd-c2dafde92c53
* Version Independent ID: 59d4618f-49c3-a61c-e993-26af59c4a551
* Content: [Create an organization hierarchy - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/organization-administration/tasks/create-organization-hierarchy)
* Content Source: [articles/fin-ops-core/fin-ops/organization-administration/tasks/create-organization-hierarchy.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/organization-administration/tasks/create-organization-hierarchy.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @sericks007
* Microsoft Alias: **sericks**

**Comment by sericks007** [comment]
@JJ431, thanks for letting us know!  I've fixed the typo, and the updated content will be published later today.
