### ISSUE TITLE
License required for an External user

### ISSUE THREAD

**Issue by ripannandy** [MicrosoftDocs/dynamics-365-unified-operations-public#3032]
As a apart of Vendor collaboration process, Do we need to consume any license for an external user who will be performing the tasks related to vendor collaboration process from vendor end?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cd5c06b-a32f-0052-1fea-ed75bc64bdbb
* Version Independent ID: 0b2f2773-60d1-4522-3e0b-00f0801fed1f
* Content: [Set up and maintain vendor collaboration - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/procurement/set-up-maintain-vendor-collaboration)
* Content Source: [articles/supply-chain/procurement/set-up-maintain-vendor-collaboration.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/procurement/set-up-maintain-vendor-collaboration.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @mkirknel
* Microsoft Alias: **mkirknel**

**Comment by tonyafehr** [comment]
@ripannandy, thanks for the feedback. 
@MaiKirknel, please review.

**Comment by tonyafehr** [comment]
@ShellyBakke, please review. Thanks!

**Comment by UmerBajwaSA** [comment]
No
