### ISSUE TITLE
Trial license detail link URL is disconnected

### ISSUE THREAD

**Issue by DKobayashi-ykgw** [MicrosoftDocs/dynamics-365-unified-operations-public#3034]
In Step one: "Try out Finance and Operations free for 30 days", there's link to www.microsoft.com/dynamics365/operations to get details of trial license, but linked page is not exists.
Where can my customer add trial license to their test AAD?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3be02eb7-47ec-11ee-6170-8e35f653eb32
* Version Independent ID: d493e3d3-a003-f681-9cb1-7f80aea9be37
* Content: [Before you buy - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/before-you-buy?source=docs)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/before-you-buy.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/get-started/before-you-buy.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @ShellyBakke
* Microsoft Alias: **smiller**

**Comment by RobinARH** [comment]
Hi - I'll update that page, but in the meantime, you can find the link for the trial version on this page: https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/sign-up-preview-subscription#subscribe
-Robin

**Comment by RobinARH** [comment]
Updated.
