### ISSUE TITLE
Server Error in '/' Application. The link is not working.

### ISSUE THREAD

**Issue by AntonVenter** [MicrosoftDocs/dynamics-365-unified-operations-public#3043]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5103263-c61e-38db-e6a6-354ed41ee61e
* Version Independent ID: ea0e7fef-f321-5f74-465e-e72accc046ed
* Content: [Dynamics Symbol font - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/user-interface/symbol-font)
* Content Source: [articles/fin-ops-core/dev-itpro/user-interface/symbol-font.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/user-interface/symbol-font.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **bensm**

**Comment by tonyafehr** [comment]
The link to [Dynamics Symbol Font](https://mbs.microsoft.com/customersource/Global/AX/downloads/hot-fixes/AXSymbolFont) opens the correct page,, so please note if there's something not working for you.
