### ISSUE TITLE
Nuget push to feed will show error "503 (Service Unavailable)"

### ISSUE THREAD

**Issue by MZade** [MicrosoftDocs/dynamics-365-unified-operations-public#3045]
Nuget push to feed will show error "503 (Service Unavailable)"

Uploading of large nuget packages is still an issue and therefor this way of working is not yet possible for many of us.
See details in my problem report on https://github.com/microsoft/azure-pipelines-tasks/issues/13548#issuecomment-749652324

Would be great if the package can be split in smaller chuncks or if the Azure DevOps team can increase the max. limits

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10459944-bcf8-c5fa-d180-9fb4bb3722da
* Version Independent ID: 29ae9d16-ed7c-92d8-0300-4fc46c777ddf
* Content: [Build automation that uses Microsoft-hosted agents and Azure Pipelines - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/hosted-build-automation)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/hosted-build-automation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-tools/hosted-build-automation.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @jorisdg
* Microsoft Alias: **jorisde**

**Comment by sericks007** [comment]
@MZade, thank you for providing this feedback.

@jorisdg, please review and consider updating the content based on this issue.

**Comment by jorisdg** [comment]
This is not a documentation issue. @sericks007 please close the issue.

To not leave the question hanging anyway: we're looking at long-term solutions for the nuget packages. Splitting them up is the obvious choice, however it requires more features to be built into the nuget restore features of our pipeline. That work is being reviewed.
You can upload the nugets from a dev VM you have hosted in Azure (which will be fast).
