### ISSUE TITLE
Data Migration worker addresses and positions

### ISSUE THREAD

**Issue by EdwinBaghaei** [MicrosoftDocs/dynamics-365-unified-operations-public#3048]
Does anyone experience the export Human Resource package from finance and operation and import on HRIS by order?
•	If a  worker has more than one Worker Contact record in FinOps with the same Description(Purpose) – (e.g. Business) the Data Management Framework export job reports it as an error and only exports the first contact record with that Description(Purpose)
•	If worker address record from FinOps with ADDRESSLOCATIONROLES =  Real Location is the same as worker address record from FinOps with ADDRESSLOCATIONROLES = Business, then worker address record with ADDRESSLOCATIONROLES = Business is updated to have ADDRESSLOCATIONROLES = Real Location instead of creating a second address record in HRIS. 3154 worker address records exported from FinOps, only 2678 imported to HR. 
•	Of the 2678 worker address record from FinOps that were imported to HR only 1600 exist in the Common Data Service Worker Addresses entity.
•	Open Positions is wrong – All retired positions are showing as open(active) positions. It is because each retired position has an Activation date of 08/12/20 and that’s why it is showing up as Open Positions.

**Comment by sericks007** [comment]
@EdwinBaghaei, thank you for posting here.  Is this feedback related to a specific documentation article?  If so, could you please provide the URL of that article?

**Comment by sericks007** [comment]
Closing due to no response.
