### ISSUE TITLE
Can't get this to work at all

### ISSUE THREAD

**Issue by manishmoothedath** [MicrosoftDocs/dynamics-365-unified-operations-public#305]
I have generated a sample XML from the XSD file and tried importing it into the vendor catalog, Keep getting the error as "There are no valid products to import"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80aa4fdc-6fd6-ed14-7cb7-016360bfa9d8
* Version Independent ID: b46cbc5c-99a6-a096-8d4e-8c7b3f0e87d5
* Content: [Import vendor catalogs - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/procurement/vendor-catalogs-import)
* Content Source: [articles/supply-chain/procurement/vendor-catalogs-import.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/procurement/vendor-catalogs-import.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @mkirknel
* Microsoft Alias: **mkirknel**

**Comment by sericks007** [comment]
Thanks for contacting us! Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support
