### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by bonomo1** [MicrosoftDocs/dynamics-365-unified-operations-public#3050]
bacpacs is spelled wrong on this page

![image](https://user-images.githubusercontent.com/32522922/103316899-7e4e3c80-49ef-11eb-8de3-5ac50dd8997a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60bd86ae-4fe1-1cb0-275b-11801c67a1d0
* Version Independent ID: a6110234-8568-8600-1c13-602f0c2d2d44
* Content: [Export a database - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/export-database)
* Content Source: [articles/fin-ops-core/dev-itpro/database/export-database.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/database/export-database.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by josaw1** [comment]
Thank you for your comment. I fixed the typo.
