### ISSUE TITLE
Key words / freeze

### ISSUE THREAD

**Issue by PaulineMF** [MicrosoftDocs/dynamics-365-unified-operations-public#3051]
I like using the metadata search, however, I have some questions.

- Could you please add a list of keywords that can be used in the metadata searches? I realize the complete list is probably not possible, but a list of the higher level keywords would be most useful.
- Could you make it possible to freeze the results? When I start the metadata search it will keep running until it has gone through all the code. That can take quite a long time. But often, just a few results is already enough. This is often the case when I am looking for an example of how a property, method etc is used. In those cases it would be useful to stop the search from running, but still keep the found results available to look at.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17b1f3ab-dd65-bb8d-6b7d-3a6c1d19c672
* Version Independent ID: 2859401b-a524-18b4-0889-17623906a1fb
* Content: [Metadata search in Visual Studio - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/metadata-search-visual-studio)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/metadata-search-visual-studio.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-tools/metadata-search-visual-studio.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **jorisde**

**Comment by RobinARH** [comment]
I'll see if I can find a list. - Robin

**Comment by RobinARH** [comment]
The keywords you can use are listed in the topic in the Filter Names section - Name, Type, Model, Property, and Code.

For adding a freeze option, we can't take requests for the product here. Consider adding your request to the [Ideas site](https://experience.dynamics.com/ideas/).

Thanks-
Robin
