### ISSUE TITLE
Missing Information.

### ISSUE THREAD

**Issue by radinm** [MicrosoftDocs/dynamics-365-unified-operations-public#3052]
How do you enable the Design Tabs Button ? I do not have that option or the tab selection section in the configure production floor execution page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44378fdb-8720-b289-06e7-80b2b8ab446b
* Version Independent ID: cd88f6f2-0558-9ed5-e83c-2db55030f135
* Content: [Design the production floor execution interface - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/production-control/production-floor-execution-tabs)
* Content Source: [articles/supply-chain/production-control/production-floor-execution-tabs.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/production-control/production-floor-execution-tabs.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @johanhoffmann
* Microsoft Alias: **johanho**

**Comment by tonyafehr** [comment]
@kamaybac, please review.
