### ISSUE TITLE
Financial reporting transaction data version 3

### ISSUE THREAD

**Issue by maroweh** [MicrosoftDocs/dynamics-365-unified-operations-public#3055]
Hi there,

In FnO 10.0.14 we get a "Can't display the visuals" error from power BI even though we refreshed the 6 mentioned entities.
I think that I need to refresh the "Financial reporting transaction data version 3" too to see data in reports.

Regards,
István Márovics

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84992dbc-779a-2e46-de21-556a6031c561
* Version Independent ID: 04d7cf2c-f55e-8765-d3ed-44502e259bc2
* Content: [Financial Insights - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/financial-insights#entity-store)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/financial-insights.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/financial-insights.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @kweekley
* Microsoft Alias: **kweekley**

**Comment by RobinARH** [comment]
Bug 548895 created to track this issue.

**Comment by jinniew** [comment]
The document has been updated to add "Financial reporting transaction data version 3" to the list of items to be updated.

**Comment by roschlom** [comment]
Thank you for your question! We appreciate the input on our content. Hope you have a good week!
