### ISSUE TITLE
Unauthorized to modify model 'Currency'

### ISSUE THREAD

**Issue by gprodware** [MicrosoftDocs/dynamics-365-unified-operations-public#306]
Getting error on "In the Currency model, create a class that implements the IExchangeRateProvider interface."
Unauthorized to modify model 'Currency'
 or if i create a new model  for "Currency"
The model 'IsraelLocalizationCurrency' belongs to the package 'Currency' that is blocked from customization. You cannot have more than one model in this package.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8905d0f-fc3d-80e2-d129-9de396a3c0d7
* Version Independent ID: c4854df8-d31c-c3ed-ff6f-c67f81035468
* Content: [Create exchange rate providers in Finance and Operations version 8.0 - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/financial/create-exchange-rate-8)
* Content Source: [articles/dev-itpro/financial/create-exchange-rate-8.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/financial/create-exchange-rate-8.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @aolson
* Microsoft Alias: **jbye**

**Comment by sericks007** [comment]
Thanks for contacting us! Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support
