### ISSUE TITLE
Shouldn't the Pick Information Module be listed in the section for what modules can be added to the Checkout along with the others?  All I see is a link at the bottom for cross reference, but not listed in the section.

### ISSUE THREAD

**Issue by chadaberle** [MicrosoftDocs/dynamics-365-unified-operations-public#3061]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2844d397-0226-e91b-bcd0-ff0ac7e8412f
* Version Independent ID: 6669b7bd-bd18-063f-bd8c-111d8c62af06
* Content: [Checkout module - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/add-checkout-module)
* Content Source: [articles/commerce/add-checkout-module.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/add-checkout-module.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @anupamar-ms
* Microsoft Alias: **anupamar**

**Comment by tonyafehr** [comment]
@anupamar-ms, please review.

**Comment by tonyafehr** [comment]
Bug 543946 has been logged to track this issue.

**Comment by tonyafehr** [comment]
This module is documented along with other Checkout modules here: https://docs.microsoft.com/en-us/dynamics365/commerce/pickup-info-module
