### ISSUE TITLE
Clarification on MPos config change

### ISSUE THREAD

**Issue by RobvanB** [MicrosoftDocs/dynamics-365-unified-operations-public#3065]
[Enter feedback here]
Regarding this section: 
https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/retail-POS-activation-changes#update-the-modern-pos-configuration

Do you need to execute that for EVERY Mpos deployment? There must be a way to automate this or make it part of the build?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cde75a6-0a4d-8405-4b6d-f7e3cfd33094
* Version Independent ID: fa2a94bb-7a6f-1ca4-ce74-8bcd8a6929f7
* Content: [Device activation of a customized Modern POS - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/retail-POS-activation-changes)
* Content Source: [articles/commerce/dev-itpro/retail-POS-activation-changes.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/dev-itpro/retail-POS-activation-changes.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @jashanno
* Microsoft Alias: **jashanno**

**Comment by josaw1** [comment]
Thank you for your comment. @jashanno can you please take a look?

**Comment by josaw1** [comment]
BUG 546038 created to track this issue.

**Comment by sericks007** [comment]
This content has been updated.
