### ISSUE TITLE
Licence package validation error on production

### ISSUE THREAD

**Issue by ivan-zakharov** [MicrosoftDocs/dynamics-365-unified-operations-public#307]
Created own package with license file and tried to add it to asset library, with no luck:
Validation status: Invalid - HotfixInstallationInfo.xml could not be found or is invalid

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce6f5dff-10da-6b04-bd4d-af056f772acc
* Version Independent ID: 075f0d3a-de0e-a434-c645-bc7c4689e930
* Content: [Independent software vendor (ISV) licensing - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-tools/isv-licensing#production-environments)
* Content Source: [articles/dev-itpro/dev-tools/isv-licensing.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-tools/isv-licensing.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @robadawy
* Microsoft Alias: **robadawy**

**Comment by ivan-zakharov** [comment]
It seems that documentation missed some important step

**Comment by ivan-zakharov** [comment]
It was my mistake - packed ZIP filed with additional subdirectory. Closing the issue.

**Comment by rabol** [comment]
What mistake ?
I have the same issue
