### ISSUE TITLE
Too soon statement.close

### ISSUE THREAD

**Issue by ScuroGuardiano** [MicrosoftDocs/dynamics-365-unified-operations-public#3070]
The code from first and second example is not working. It's because statement is closed before calling ```result.getString``` and I get SQL Invalid Handle error. I suggest correcting it like that in both examples:
```cs
public str GetFirstName(str name)
{
    str sqlStatementText = "SELECT TOP(1) firstName FROM Customer WHERE customer.Name = '" + name + "'";

    // Create a connection to the SQL Server
    var connection = new Connection();

    // Create a statement and submit the sql statement to the server:
    Statement statement = connection.createStatement();
    var results= statement.executeQuery(sqlStatementText);

    // Get the first record:
    results.next();
    
    // Harvest the results.
    var result = results.getString(1);
    
    // Close statement
    statement.close();
    
    return result;
}
```

Wasted like 30 minutes figuring out why it's not working, because official documentation cannot be wrong, right?
Wrong!

I hope you will fix it and no more lost souls will have to think why it's not working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d92be4b4-05f4-c8a1-c788-43b2c60f561f
* Version Independent ID: ba5bbde1-9bc7-63f1-8b36-405db7ba6400
* Content: [Mitigate a SQL injection attack - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-ref/query-with-parameters)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-ref/query-with-parameters.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-ref/query-with-parameters.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @pvillads
* Microsoft Alias: **rhaertle**

**Comment by kfend** [comment]
@ScuroGuardiano - thank you for the feedback.
@RobinARH and @pvillads - can one of you take a look at the topic and update as necessary?

**Comment by kfend** [comment]
Bug 558329 created to track this issue

**Comment by josaw1** [comment]
@twheeloc can you please review and update/close as needed?

**Comment by twheeloc** [comment]
The topic was updated with suggested change. The changes will be live later today.
