### ISSUE TITLE
Dynamics 365 customer engagement

### ISSUE THREAD

**Issue by lubergst** [MicrosoftDocs/dynamics-365-unified-operations-public#3071]
Where can I find the Cloud deployment documents for Dynamics 365 Customer Engagement (SaaS Model-driven apps).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5080f3d7-0ad1-940c-284a-92008d7c19d5
* Version Independent ID: c911e39b-82ee-2ae3-4493-d2e39afccc2b
* Content: [Cloud deployment overview - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/cloud-deployment-overview?source=docs)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/cloud-deployment-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/deployment/cloud-deployment-overview.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by kfend** [comment]
@lubergst - thanks for your question. At this time, there is only Dynamics 365 Customer Engagement for on-premises and not the cloud. However, here are some links to topics that might have the information you are looking for if you are interested in customer engagement apps:

- [Administering a PowerApps enterprise deployment](https://docs.microsoft.com/en-us/power-platform/admin/admin-powerapps-enterprise-deployment)
- [Plan for deployment and administration](https://docs.microsoft.com/en-us/power-platform/admin/plan-for-deployment-and-administration)
