### ISSUE TITLE
Instead of link the page shows text [systest-filtering.md]

### ISSUE THREAD

**Issue by maroweh** [MicrosoftDocs/dynamics-365-unified-operations-public#3072]
[Enter feedback here]
In the advanced options section in the sentence there is an .md instead of a link to the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60782905-2f9f-a018-04a2-fada4ad982b0
* Version Independent ID: d31e7f48-99fc-bb22-ec10-8714043d12a2
* Content: [Test projects in Visual Studio - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/perf-test/testing-support)
* Content Source: [articles/fin-ops-core/dev-itpro/perf-test/testing-support.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/perf-test/testing-support.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **shailesn**

**Comment by RobinARH** [comment]
I published a fix for this and it should go live later today. Thanks for letting us know. - Robin
