### ISSUE TITLE
Download the Modern POS installer button not available

### ISSUE THREAD

**Issue by pkrawczykObj** [MicrosoftDocs/dynamics-365-unified-operations-public#3073]
When I follow this manual on my trial version https://d365rtrialha48.retail.dynamics.com/, the "Download" button is not visible, after selecting the HOUSTON-3 or any other device.
![image](https://user-images.githubusercontent.com/44259511/104185203-f287d780-5414-11eb-9516-51dd0c6baa63.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf852cc9-52e2-f142-3c73-41f0bc3740e0
* Version Independent ID: 13b843db-7f5a-6398-2eba-26427269375d
* Content: [Configure, install, and activate Modern POS (MPOS) - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/retail-modern-pos-device-activation)
* Content Source: [articles/commerce/retail-modern-pos-device-activation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/retail-modern-pos-device-activation.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @jashanno
* Microsoft Alias: **jashanno**

**Comment by tonyafehr** [comment]
@pkrawczykObj, thanks for the feedback. @jashanno, please review.

**Comment by jashanno** [comment]
Hello @pkrawczykObj ,

Trial environments do not allow for the download and use of Modern POS.  It would be best to procure a demo environment from sales or solution architecture teams to get a fully functional environment where you can test any scenario you desire.
