### ISSUE TITLE
Feedback on changed documentation as requested by @Peakerbl

### ISSUE THREAD

**Issue by Dynamicspedia** [MicrosoftDocs/dynamics-365-unified-operations-public#3075]
[Enter feedback here]
Thanks Par, for asking to review the updated documentation. I do have some questions and comments.

In the introduction, it might be an idea to mention the requirement for an organizational account and link to the Authentication document: https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/security-architecture

Question: Has the option to have users automatically added the first time they log in been deprecated. The former documentation page mentioned this. Now, this section has been removed. I spent a blog post on the automatic Azure AD sync options: https://dynamicspedia.com/2019/09/how-to-use-azure-active-directory-for-managing-users-and-security-in-dynamics-365-for-finance-and-operations/

Section: Assign a license to a user
Here it is mentioned that users can be added via the Microsoft 365 Admin center. In fact, there is a choice that will all end up by adding users in Azure AD. The other not mentioned portals are: Azure Portal and Office 365 Admin Center.

Section: Add an external user in Azure AD and assign a license
The link to invite a guest user is mentioning to do this via the Azure Portal. Here is the same comment as above. There are multiple ways to achieve it. It would be confusing to first share a link to the Microsoft 365 Admin portal where the next step is explaining how to do it in the Azure Portal.
Also, in this section, I do miss the explanation that the external user should also be an organizational user known in another Azure AD tenant. The link is showing an example of how to add a user with a gmail account.

Section: Import new users from Azure AD
The note is mentioning: "current session company for the admin". This is not correct. The company field remains empty. Or is there a new upcoming feature for this? I created a blog post in the past for the defaulting of certain user options and how to extend this with a customization. https://dynamicspedia.com/2019/06/how-to-select-a-default-language-for-new-users-in-microsoft-dynamics-365-for-finance-and-operations/
There is also the next comment: "The values for Identity provider and Telemetry ID will be updated based on a graph call". Many people will not understand the "graph call". Probably, this should also be briefly explained with a link to the Microsoft Graph documentation?

Section: Change a user ID
The note section is not formatted correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ee79acf-064c-cad4-d19b-9f55ea862899
* Version Independent ID: 02b9e913-4295-dd20-cbb6-b12fa4c7b39c
* Content: [Create new users - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/tasks/create-new-users?source=docs)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/tasks/create-new-users.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/sysadmin/tasks/create-new-users.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @Peakerbl
* Microsoft Alias: **peakerbl**

**Comment by tonyafehr** [comment]
@Peakerbl, please review.
