### ISSUE TITLE
General availability (self-update):  is set to January 2020 but it should be January 2021

### ISSUE THREAD

**Issue by suedriscoll** [MicrosoftDocs/dynamics-365-unified-operations-public#3077]
General availability (self-update):  is set to January 2020 but it should be January 2021

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb2c851e-b3c3-f1cb-e89b-146ad4bbb02b
* Version Independent ID: 2dea676c-d08a-e3b7-52d9-3caeec66f494
* Content: [What's new or changed in Dynamics 365 Finance 10.0.16 (February 2021) - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/get-started/whats-new-changed-10-0-16)
* Content Source: [articles/finance/get-started/whats-new-changed-10-0-16.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/get-started/whats-new-changed-10-0-16.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @roschlom
* Microsoft Alias: **roschlom**

**Comment by tonyafehr** [comment]
@suedriscoll, thanks for noting this. @roschlom, please fix.

**Comment by roschlom** [comment]
As Tonya said, thank you for letting us know about the mistake. It's been fixed and should going through the publishing process as I write this. Have a great day!
