### ISSUE TITLE
wrong sql script

### ISSUE THREAD

**Issue by andreash1** [MicrosoftDocs/dynamics-365-unified-operations-public#308]
the sql script is not quite correct. 
Url: https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/copy-database-from-azure-sql-to-sql-server
sub heading: Update the database
wrong line: CREATE USER axdeployextuser WITH PASSWORD = '<password from LCS>'
correct line: CREATE USER axdeployextuser FROM LOGIN axdeployextuser

the reason is that in SQL server we use Windows auth, we do not use LCS accounts with passwords.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3436fbc8-5bdd-dcdc-f5d3-51caf7b6cd76
* Version Independent ID: af78d3ef-b329-11e9-896a-aa3394f6c77c
* Content: [Copy Finance and Operations databases from Azure SQL Database to SQL Server environments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/copy-database-from-azure-sql-to-sql-server)
* Content Source: [articles/dev-itpro/database/copy-database-from-azure-sql-to-sql-server.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/database/copy-database-from-azure-sql-to-sql-server.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @maertenm
* Microsoft Alias: **maertenm**

**Comment by sericks007** [comment]
Thanks for letting us know. We are investigating this issue.

**Comment by laneswenka** [comment]
PR created for resolution.  Thanks @andreash1
