### ISSUE TITLE
Document does not match current UI dialogs

### ISSUE THREAD

**Issue by RobvanB** [MicrosoftDocs/dynamics-365-unified-operations-public#3081]
It looks like the portal UI has been updated and the steps in the article no longer match the steps in the portal, which makes it very confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cde75a6-0a4d-8405-4b6d-f7e3cfd33094
* Version Independent ID: fa2a94bb-7a6f-1ca4-ce74-8bcd8a6929f7
* Content: [Device activation of a customized Modern POS - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/retail-POS-activation-changes#create-the-customized-modern-pos-azure-ad-application)
* Content Source: [articles/commerce/dev-itpro/retail-POS-activation-changes.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/dev-itpro/retail-POS-activation-changes.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @jashanno
* Microsoft Alias: **jashanno**

**Comment by tonyafehr** [comment]
@RobvanB, thanks for the feedback. @jashanno, please review.

**Comment by tonyafehr** [comment]
Bug 546530 logged to track this issue.

**Comment by tonyafehr** [comment]
This topic has been updated.
