### ISSUE TITLE
X++ subStr - incorrect code example

### ISSUE THREAD

**Issue by sfrey2** [MicrosoftDocs/dynamics-365-unified-operations-public#3085]
There are syntax and logical errors in the [X++ subStr documentation](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-ref/xpp-string-run-time-functions#substr).

Under "Remarks", the code is as follows:
`subStr("ABCDEFGHIJ",3,5); //Returns the string "CDEFG".`
`subStr("ABCDEFGHIJ",7,-4); //Returns the string "DEFG".`
`subStr("abcdef"),2,99) //Returns the string "cdef".` <- incorrect syntax and incorrect result.
`subStr("abcdef",2,3) //Returns the string "bcd".`
`subStr("abcdef",2,-3); //Returns the string "ab".`

Instead, it should be something like this:
`subStr("ABCDEFGHIJ", 3,  5); //Returns the string "CDEFG".`
`subStr("ABCDEFGHIJ", 7, -4); //Returns the string "DEFG".`
`subStr("abcdef",     2, 99); //Returns the string "bcdef".`
`subStr("abcdef",     2,  3); //Returns the string "bcd".`
`subStr("abcdef",     2, -3); //Returns the string "ab".`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14881d23-dbd7-a265-abee-c34d14f49f5a
* Version Independent ID: 67a102a3-25cf-189b-1426-5e46e9e68f6c
* Content: [X++ string runtime functions - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-ref/xpp-string-run-time-functions#strlen)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-ref/xpp-string-run-time-functions.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-ref/xpp-string-run-time-functions.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **rhaertle**

**Comment by josaw1** [comment]
Thanks for your feedback. @RobinARH can you please take a look?

**Comment by josaw1** [comment]
BUG 547811 created to track.

**Comment by RobinARH** [comment]
Fixed. Should go live this evening.
