### ISSUE TITLE
Please update this page to current experience.

### ISSUE THREAD

**Issue by gusgallows** [MicrosoftDocs/dynamics-365-unified-operations-public#3086]
Page is dated. Steps can not be followed as written. Need this process updated for current environment.
Steps start falling apart at Step 4 under Create the Commerce Scale Unit Azure AD application. This in turn leads to all other steps to not work,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cde75a6-0a4d-8405-4b6d-f7e3cfd33094
* Version Independent ID: fa2a94bb-7a6f-1ca4-ce74-8bcd8a6929f7
* Content: [Device activation of a customized Modern POS - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/retail-POS-activation-changes#create-the-customized-modern-pos-azure-ad-application)
* Content Source: [articles/commerce/dev-itpro/retail-POS-activation-changes.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/dev-itpro/retail-POS-activation-changes.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @jashanno
* Microsoft Alias: **jashanno**

**Comment by josaw1** [comment]
Thanks for your feedback. @jashanno can you please review?

**Comment by josaw1** [comment]
BUG 547810 created to track the issue.

**Comment by josaw1** [comment]
This article has been updated.
