### ISSUE TITLE
how many sandbox environment can we deploy? but the licenses are cloud subscription

### ISSUE THREAD

**Issue by jlabustro** [MicrosoftDocs/dynamics-365-unified-operations-public#3088]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6c7e467-87c9-70c8-c819-b1f5c0057352
* Version Independent ID: 0feef83a-6d18-8685-2c6c-6225c0db03e5
* Content: [Plan and prepare for on-premises deployments - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/plan-onprem-deployment)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/plan-onprem-deployment.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/deployment/plan-onprem-deployment.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @sericks007
* Microsoft Alias: **sericks**

**Comment by sericks007** [comment]
@PeterRFriis or @faix, can you answer the question?  (The question is in the title of this issue.)

**Comment by faix** [comment]
this would be a question for @PeterRFriis  or @cabeln. @jlabustro can you please elaborate on your question?
Are you asking how many onprem sandboxes you can deploy if you have a cloud subscription?
Are you a cloud customer? If so why do you want to deploy onprem sandboxes?

**Comment by PeterRFriis** [comment]
Yes, please provide the information raised from Oscar and I will look into your options and elaborate.
Thank you.

**Comment by jlabustro** [comment]
Hello Peter, Oscar,

My apologies. If I am a customer and I purchase cloud subscription through CSP, how many on-premise sandboxes can I create or deploy? I already created one environment but I still need one more sandbox.

If in case cloud subscription restrict creating more than 1 sandbox, does it mean I have to buy a license to allow me to create additional sandbox? What kind of license? onpremise sandbox or cloud sandbox?

Thank you in advance.


If you have any other question or concerns, don't hesitate to email us.

Warmest regards,

JOVELYN LABUSTRO
Senior Software Licensing Specialist
Hitachi Solutions Asia Pacific
D: +63 (2) 8823-1672 | C: +63 (998) 474-5444
E: jlabustro@hitachisolutions.com<mailto:jlabustro@hitachisolutions.com>

[Hitachi Solutions logo]

[Hitachi Solutions LinkedIn]<https://www.linkedin.com/company/hitachi-asia-pacific> [Hitachi Solutions Twitter] <https://twitter.com/hitachisolapac>   [Hitachi Solutions Facebook] <https://www.facebook.com/HitachiSolutionsAPAC>   [Hitachi Solutions Instagram] <https://www.instagram.com/hitachisolutionsapac/>   [Hitachi Solutions YouTube] <https://www.youtube.com/channel/UCEjOyglyM9RGku_Aba4rI7g>   [Hitachi Solutions Medium] <https://medium.com/hitachisolutions-braintrust>

**Comment by faix** [comment]
Hi @jlabustro is your production slot a cloud environment or is it an onprem environment? If your production environment is a cloud environment then you should not be deploying onprem environments as there are fundamental differences between cloud and onpremise environments.

**Comment by sericks007** [comment]
Closing this issue, as I believe the question has been answered.  If not, please reopen.
