### ISSUE TITLE
Documentation is out of date.

### ISSUE THREAD

**Issue by brainman75** [MicrosoftDocs/dynamics-365-unified-operations-public#309]
1. You can no longer "Customize" the RetailTransactionServiceEx class - you must create an extension. (As of App 8.0 PU15)
2. The return of the transactionService.InvokeExtensionMethod method is a ReadOnlyCollection&lt;object&gt; AND (most importantly) it does NOT contain the full container returned by the extension method. It only contains the "data" portion. 
3. If the extension method is not successful then the call in CRT will result in an exception of type Microsoft.Dynamics.Commerce.Runtime.HeadquarterTransactionServiceException. The Message property of that exception will contain the error from the extension method.

It would be beneficial to have better documentation/samples regarding this extension pattern. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 427fcfe5-f11b-0efc-bcb4-acfa285f37f1
* Version Independent ID: 633ffbd9-7fd7-6e31-be58-e7272ebb9df3
* Content: [Extend Commerce Data Exchange - Real-time Service - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/dev-itpro/extend-commerce-data-exchange)
* Content Source: [articles/retail/dev-itpro/extend-commerce-data-exchange.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/dev-itpro/extend-commerce-data-exchange.md)
* Service: **dynamics-365-retail**
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by sericks007** [comment]
Thanks for letting us know. We are investigating the issues you listed.

**Comment by ShylaThompson** [comment]
@brainman75 the topic will be updated by the end of day tomorrow. Thanks for raising this issue!

**Comment by RobvanB** [comment]
I think the message at the top should be more clear. Isn't it so that this article is only valid for versions lower than 8 ?
