### ISSUE TITLE
Missing information in regards to mapping

### ISSUE THREAD

**Issue by IvanLarsen87** [MicrosoftDocs/dynamics-365-unified-operations-public#3090]
Hello

This is a very interesting subject, but some critical information is missing:
1. Line mapping definitions are missing for most of the table mappings
2. "One-way, and data is transformed in the process." is used in the above for many mappings, but you say nothing about how the data is being transformed. please explain further.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5034c9f1-31bf-9649-f8f8-af7cca2da37e
* Version Independent ID: ecd0db96-4b9a-7d65-986c-523fa42f6ce0
* Content: [Integrate procurement between Supply Chain Management and Field Service - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/scm-field-service-procurement)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/scm-field-service-procurement.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/dual-write/scm-field-service-procurement.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @mkirknel
* Microsoft Alias: **mkirknel**

**Comment by kfend** [comment]
@IvanLarsen87 - thank you for the feeback.
@kamaybac - can you please take a look and assign this to the correct PM?

**Comment by kamaybac** [comment]
@RichardLuan,  please review this customer feedback and consider whether we could update this topic to meet this request. Thanks.

**Comment by josaw1** [comment]
BUG 552834 created to track.

**Comment by josaw1** [comment]
This has been fixed.
