### ISSUE TITLE
Missing step to update Shared working directory in Dataimport/export framework parameters

### ISSUE THREAD

**Issue by Ievgenm** [MicrosoftDocs/dynamics-365-unified-operations-public#3095]
On-prem system may have shared folder specified in "Shared working directory". After migration this field is not editable for cloud hosted environments, so cannot be changed through UI. Having shared folder there will cause an error during any export or import via data management. SQL script should be updated to include update to this value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52e9b65e-a05e-73c4-6e78-280c8068e0e2
* Version Independent ID: b640a8a7-2ff9-bca6-7317-beba3a5d48d1
* Content: [Move LCS implementation projects from on-premises to the cloud - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/move-on-prem-to-cloud)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/move-on-prem-to-cloud.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/lifecycle-services/move-on-prem-to-cloud.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @MartinWalkerDynSA
* Microsoft Alias: **marwalke**

**Comment by tonyafehr** [comment]
@Ievgenm, thank you for the feedback. 
@MartinWalkerDynSA, please review.

**Comment by tonyafehr** [comment]
Bug 549283 logged to track this issue.
