### ISSUE TITLE
DNS Name changed to Vault URI

### ISSUE THREAD

**Issue by JimDaly** [MicrosoftDocs/dynamics-365-unified-operations-public#3096]
In Procedure 2 it says:

> Select **Overview**, then copy and save the **DNS Name** 

Looks like the UI in Azure has changed. **DNS Name** has been replaced by  **Vault URI**.

These instructions should reflect that change.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 055168f2-4423-1246-9663-1d0b14696666
* Version Independent ID: 2ec22b82-5bc0-bdb1-b630-ffcbaf1180dd
* Content: [Business events and Azure Event Grid - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/business-events/how-to/how-to-eventgrid#procedure-2-create-a-key-vault)
* Content Source: [articles/fin-ops-core/dev-itpro/business-events/how-to/how-to-eventgrid.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/business-events/how-to/how-to-eventgrid.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by tonyafehr** [comment]
@Sunil-Garg, please review. Thanks!

**Comment by tonyafehr** [comment]
Bug 549254 logged to track this issue.
