### ISSUE TITLE
Compose working time

### ISSUE THREAD

**Issue by Millekyl** [MicrosoftDocs/dynamics-365-unified-operations-public#3097]
When I create a new Calendar and select the "compose working time" no matter how far back I set my "from date" when its done processing and were back on the ( standard view for working time ) the dates cut off on 12/19/2020 ? even though I set my from date as 1/1/2018? This is causing random date errors when trying to work with projects

**Comment by tonyafehr** [comment]
@Millekyl, thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
