### ISSUE TITLE
Service module

### ISSUE THREAD

**Issue by magic1949** [MicrosoftDocs/dynamics-365-unified-operations-public#3100]
The Dynamics SCM Service module  was dependent on Project Accounting module -now we have Project Operations license is the Service module still available in SCM?
If not then what is the alternative, if it is then is there any dependency on project operations license?
Can the features of Service be used in SCM with an enterprise SCM or finance license without need for a Project operation license ?

- Can the features of Project Accounting be used in SCM with an enterprise SCM or finance license without need for a Project operation license?

Its very confusing to explain to clients or to architect solutions. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18107774-aebe-69da-79f7-8a12f87bf6f4
* Version Independent ID: e5138760-dc65-0552-4c0d-580aadbce407
* Content: [Service management overview - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/service-management/service-management-home-page)
* Content Source: [articles/supply-chain/service-management/service-management-home-page.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/service-management/service-management-home-page.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @ShylaThompson
* Microsoft Alias: **kamaybac**

**Comment by tonyafehr** [comment]
@magic1949, thanks for the feedback. 
@sigitac, please review.

**Comment by tonyafehr** [comment]
Bug 549257 logged to track this issue.

**Comment by tonyafehr** [comment]
We license users, not functionality. This means that an SCM or Activity user license is sufficient for using the service management functionality as described on page 30 in the Dec 2020 edition of the Dynamics 365 Licensing Guide.

![image](https://user-images.githubusercontent.com/20996931/106283512-a657d800-6207-11eb-9464-24e10d40a84f.png)

You may need a Project Operations attach license for one or more of the service management users to perform necessary project configuration -- similar to how Finance attach user licenses are needed for setting up finance data that is prerequisite for SCM business processes.

**Comment by magic1949** [comment]
That was not the really question. 
There are dependencies of Service on Finance and Operations Project Accounting.
 However  that module is now replaced by Project Operations,
The question was not about field service -  but about the Service module in SCM (or formerly Ax 2012)
So
 1: are SCM users able to use Service in SCM  without a Project Operations license?
2.  are there deprecations of Project Accounting features  that prevent Service module being used? 
3. Either a  Project Operation attach license is needed to use Service module or it isn't?.
