### ISSUE TITLE
Need to know how to edit historical external demand records after they have been imported.

### ISSUE THREAD

**Issue by ronsonntag54** [MicrosoftDocs/dynamics-365-unified-operations-public#3102]
The page shows how to import the historical external demand records, but, it you find out there is a duplicate or an error in any of the imported records, there is no instruction on how to edit this list of imported records to fix errors.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3f17fae-150d-e5c8-77bb-f3c8e142272f
* Version Independent ID: d49c5d4c-ae4d-8ad2-6e96-255cfe88f978
* Content: [Import historical data for demand forecasts - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/master-planning/import-historical-data)
* Content Source: [articles/supply-chain/master-planning/import-historical-data.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/master-planning/import-historical-data.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @roxanadiaconu
* Microsoft Alias: **kamaybac**

**Comment by sericks007** [comment]
@ronsonntag54, thank you for providing this feedback.

@roxanadiaconu, please consider updating the content based on this feedback.

**Comment by sericks007** [comment]
@kamaybac, please assign to the appropriate PM.

**Comment by kamaybac** [comment]
@ChristianRytt , please consider this documentation request for master planning. Thanks.

**Comment by ChristianRytt** [comment]
@kamaybac , I suggest to add a link to the data management documentation (https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/data-import-export-job) for details on importing the data. Seems like we should not include data import specific information under planning.

**Comment by kamaybac** [comment]
@ronsonntag54 , thank you for your feedback. We decided to add a link from this topic to the general topic about how to work with imports.
