### ISSUE TITLE
Sales tax code, step no 3 needs clarifications

### ISSUE THREAD

**Issue by bjool** [MicrosoftDocs/dynamics-365-unified-operations-public#3103]
[Enter feedback here]
The expected input in the fields in the form "External codes" in the form groups "Overview" and "Value" should be explained in more detail.  What is the relation between the Overview and Value? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8904993-84a8-8983-dcc5-4499b6e1e9d5
* Version Independent ID: f40dc67d-74a2-dab3-182c-fbbd6f0e46e0
* Content: [Standard Audit File for Tax (SAF-T) for Norway - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/emea-nor-satndard-audit-file-for-tax)
* Content Source: [articles/finance/localizations/emea-nor-satndard-audit-file-for-tax.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/localizations/emea-nor-satndard-audit-file-for-tax.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @liza-golub
* Microsoft Alias: **elgolu**

**Comment by sericks007** [comment]
@bjool, thank you for providing this feedback.

@liza-golub, please consider enhancing the content based on this feedback.

**Comment by sericks007** [comment]
Bug 549605 has been logged to track this issue.

**Comment by sericks007** [comment]
This content has been updated.
