### ISSUE TITLE
Delivery data control

### ISSUE THREAD

**Issue by Kelkane** [MicrosoftDocs/dynamics-365-unified-operations-public#3105]
[Enter feedback here]
It states Delivery data control instead of delivery date control on this page. 
![image](https://user-images.githubusercontent.com/63654741/105247645-1b117f00-5b43-11eb-8504-0dbc00ec7090.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8fb9008-7860-4bfa-d5b1-f45d231dc010
* Version Independent ID: b1217351-f880-580f-f857-7d21df60e66c
* Content: [Delivery alternatives - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/sales-marketing/delivery-alternatives)
* Content Source: [articles/supply-chain/sales-marketing/delivery-alternatives.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/sales-marketing/delivery-alternatives.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @ChristianRytt
* Microsoft Alias: **crytt**

**Comment by ChristianRytt** [comment]
Thank you for reporting!

This is an odd typo, I actually found 3 places where we incorrectly have data instead of date on this page – see below screenshot.

@Karl Maybach<mailto:Karl.Maybach@microsoft.com> can you fix this?

[cid:image002.png@01D6EFF3.5B3E76C0]

Thanks,
/Christian

**Comment by kamaybac** [comment]
@ChristianRytt , @Kelkane , thank you for reporting this issue. I have fixed the typos in the repo. The fix should go live later today.
