### ISSUE TITLE
Correcting historical external demand imports still not explained correctly

### ISSUE THREAD

**Issue by ronsonntag54** [MicrosoftDocs/dynamics-365-unified-operations-public#3107]
The reference to the import/export DMF is not sufficient and not even correct. For example: Many Data Entities CANNOT be reloaded because the records are duplicated and that results in incorrect calculations. Other entities CANNOT be truncated, so you cannot even start over by using Truncate (e.g. the GAL).

My comment is SPECIFICALLY on how to fix bad data after an import of historical external demand has been done. The additional links you provided DO NOT provide that information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3f17fae-150d-e5c8-77bb-f3c8e142272f
* Version Independent ID: d49c5d4c-ae4d-8ad2-6e96-255cfe88f978
* Content: [Import historical data for demand forecasts - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/master-planning/import-historical-data)
* Content Source: [articles/supply-chain/master-planning/import-historical-data.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/master-planning/import-historical-data.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @roxanadiaconu
* Microsoft Alias: **kamaybac**

**Comment by josaw1** [comment]
Thanks for your feedback. @kamaybac can you please review?

**Comment by kamaybac** [comment]
@ChristianRytt , we got some more feedback regarding the import documentation for master planning. The reader is not satisfied with the link we provided yesterday. Do you have another suggestion for how we could address this?

**Comment by josaw1** [comment]
BUG 550571 created to track.

**Comment by josaw1** [comment]
@kamaybac please review this feedback.

**Comment by josaw1** [comment]
Closing as won't fix.
