### ISSUE TITLE
Need a clearer description of what the SQL Rebuilding Indexes batch job does

### ISSUE THREAD

**Issue by ronsonntag54** [MicrosoftDocs/dynamics-365-unified-operations-public#3110]
The statement: "In some cases, you may find that the before and after fragmentation number is the same or even higher. This is typical because Microsoft uses a less intrusive online rebuild option. In the future, we plan to introduce an optional offline rebuild option." is ambiguous. What does "Microsoft uses a less intrusive online rebuild option" mean?

Are the indexes rebuild less well? Are the statistics wrong because they haven't been refreshed yet? Do we need to rerun the batch job if the numbers don't make sense?

This is a very badly constructed outcome and needs specific and clear definitions of what works, what doesn't, what are the exceptions, and what are the remediations.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee1ecd08-b417-33b6-46d9-9be22c92ed23
* Version Independent ID: 6082162f-3c1a-bce2-8f7a-c5b16223accd
* Content: [Batch job to handle SQL index defragmentation - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/batch-job-sql-defragmentation)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/batch-job-SQL-defragmentation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/sysadmin/batch-job-SQL-defragmentation.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @Peakerbl
* Microsoft Alias: **ganas**

**Comment by gammelgaard52** [comment]
Also, it lacks explanation of the latest options in it - like "PRIORITISE THESE TABLES FOR INDEX DEFRAGMENTATION".
Does that mean, that even indexes that are not fragmented enough, will be defragmented regardless - or will it prioritize the specific index and include it in the "top 500 (Count of indexes)"?

**Comment by sericks007** [comment]
@sarvanisathish, can you please review and comment on this?

**Comment by RobinARH** [comment]
Bug 553712 created to track this issue.

**Comment by sericks007** [comment]
The "Batch job to handle SQL index defragmentation" content has been removed, as the feature has been removed. Please see the [Removed or deprecated platform features](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/get-started/removed-deprecated-features-platform-updates#batch-job-to-handle-sql-index-defragmentation) content for more information.
