### ISSUE TITLE
new API "statement.executeQueryWithParameters" is not availabe in Plattform Updates 10.0.16

### ISSUE THREAD

**Issue by chicinho** [MicrosoftDocs/dynamics-365-unified-operations-public#3111]
I have just read the release information for the Plattfrom Updates 10.0.16. One update ist about "Mitigate a SQL injection attack". So we have on our Sandboxes the Platform Updates 10.0.16 installed and I wanted to test this new method "executeQueryWithParameters". Guess what, it is not available? I can't find it in the Intellisense nor in the AOT Explorer. Why not?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d92be4b4-05f4-c8a1-c788-43b2c60f561f
* Version Independent ID: ba5bbde1-9bc7-63f1-8b36-405db7ba6400
* Content: [Mitigate a SQL injection attack - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-ref/query-with-parameters)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-ref/query-with-parameters.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-ref/query-with-parameters.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @pvillads
* Microsoft Alias: **rhaertle**

**Comment by RobinARH** [comment]
@pvillads Can you take a look? Thanks.

**Comment by RobinARH** [comment]
Bug 553714 created to track this issue.

**Comment by pvillads** [comment]
The changes were checked into main on Nov 18 last year.

Pull request 100257: First version of simplified SQL Injectionattack strategy that does not need C++ changes - Repos (visualstudio.com)<https://msdyneng.visualstudio.com/FinOps/_git/Platform/pullrequest/100257>

Currently my box does have the changes. @Marcos Calderon Macias<mailto:marcosc@microsoft.com> do you have ideas as to why they would not be available in 10.0.16?

BR PV

**Comment by pvillads** [comment]
The changes went into platform update (PU) 41 which corresponds to 10.0.17, not in 10.0.16, which is platform update 40. We will not do a hotfix to port this back to PU 40.

@Robin Reynolds-Haertle<mailto:rhaertle@microsoft.com>  I have resolved the bug. Please do anything needed from your side.

BR PV

From: Peter Villadsen
Sent: Monday, February 8, 2021 4:40 PM
To: MicrosoftDocs/dynamics-365-unified-operations-public <reply@reply.github.com>; MicrosoftDocs/dynamics-365-unified-operations-public <dynamics-365-unified-operations-public@noreply.github.com>; Marcos Calderon Macias <marcosc@microsoft.com>
Cc: Assign <assign@noreply.github.com>
Subject: RE: [MicrosoftDocs/dynamics-365-unified-operations-public] new API "statement.executeQueryWithParameters" is not availabe in Plattform Updates 10.0.16 (#3111)

The changes were checked into main on Nov 18 last year.

Pull request 100257: First version of simplified SQL Injectionattack strategy that does not need C++ changes - Repos (visualstudio.com)<https://msdyneng.visualstudio.com/FinOps/_git/Platform/pullrequest/100257>

Currently my box does have the changes. @Marcos Calderon Macias<mailto:marcosc@microsoft.com> do you have ideas as to why they would not be available in 10.0.16?

BR PV

**Comment by RobinARH** [comment]
I updated the topic to include the release platform. It'll go live later today.
