### ISSUE TITLE
Offline MPOS no longer installs SQL prerequisite

### ISSUE THREAD

**Issue by brettchristiansen** [MicrosoftDocs/dynamics-365-unified-operations-public#3112]
The "Run the installer on a windows computer" section of this document states that if you have Offline support that the installer will handle installation of SQL Server 2014.  I believe this has changed and should no longer be expected.  Document should reflect the changes requiring a manual install SQL and current supported versions

https://docs.microsoft.com/en-us/dynamics365/commerce/retail-modern-pos-device-activation#run-the-installer-on-a-windows-computer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf852cc9-52e2-f142-3c73-41f0bc3740e0
* Version Independent ID: 13b843db-7f5a-6398-2eba-26427269375d
* Content: [Configure, install, and activate Modern POS (MPOS) - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/retail-modern-pos-device-activation#download-and-install-modern-pos)
* Content Source: [articles/commerce/retail-modern-pos-device-activation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/retail-modern-pos-device-activation.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @jashanno
* Microsoft Alias: **jashanno**

**Comment by RobinARH** [comment]
@jashanno Can you take a look? Thanks.

**Comment by RobinARH** [comment]
Bug 553715 created to track this issue.

**Comment by sericks007** [comment]
This content was recently updated.
