### ISSUE TITLE
Error in the section: Example of a while loop

### ISSUE THREAD

**Issue by almouattaz** [MicrosoftDocs/dynamics-365-unified-operations-public#3115]
[Enter feedback here]
The counter should start from 1. 
Starting from 0 would return **0, "one", "two", "three"** instead of **"one", "two", "three"**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8296542b-fdb9-1fbf-4134-f05c5915d527
* Version Independent ID: 5794b9ca-8c09-f8b7-fef9-a764b7f32a61
* Content: [X++ loop statements - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-ref/xpp-loops)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-ref/xpp-loops.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-ref/xpp-loops.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **rhaertle**

**Comment by tonyafehr** [comment]
@almouattaz, thanks for the feedback. 
@RobinARH, please review.

**Comment by tonyafehr** [comment]
Bug 551876 logged to track this issue.

**Comment by RobinARH** [comment]
I fixed the loop counter. The update should go live later today.
