### ISSUE TITLE
Exception details page

### ISSUE THREAD

**Issue by HugoDJesus** [MicrosoftDocs/dynamics-365-unified-operations-public#3116]
The docs says: 

"When you start edit mode, the exception details page for the invoice that has issues appears. If there are any attachments, the invoice and the default attachment appear side by side on the exception details page."

But testing the functionality if you upload a invoice header with a wrong data (ex. wrong currency) the attachment throw error because the the header id does not exits: Results. Matching record with key 'TableRefId': 012396 for the data source 'VendInvoiceInfoTable' does not exists 

and therefore, contrary to what the documentation indicates, the attachment is not displayed on the Vendor invoices that failed to import screen
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a352b90-7b38-da25-ed1c-c95030d86100
* Version Independent ID: 79dccc0f-8ea1-e4a6-8b05-4144e61c7965
* Content: [Invoice automation for scanned documents - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/accounts-payable/vendor-invoice-automation)
* Content Source: [articles/finance/accounts-payable/vendor-invoice-automation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/accounts-payable/vendor-invoice-automation.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @abruer
* Microsoft Alias: **shpandey**

**Comment by tonyafehr** [comment]
@HugoDJesus, thanks for the great feedback. If you need to contact Support regarding this, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). 
@abruer, please review and consider updating this topic.

**Comment by HugoDJesus** [comment]
Hi Tonya,

Thanks you for your feedback, I already submitted the issue in LCS related with this topic and I reviewed with a support engineer.
She is investigating it too.

**Comment by tonyafehr** [comment]
Bug 551877 logged to track this issue.

**Comment by tonyafehr** [comment]
This topic has been updated. Thanks!
