### ISSUE TITLE
Wrong number of standard environments mentioned 

### ISSUE THREAD

**Issue by Ievgenm** [MicrosoftDocs/dynamics-365-unified-operations-public#3117]
Article says: "Subscriptions come with three standard environments: one production environment, one Tier-2 Standard Acceptance Test environment, and one Tier-1 developer environment. "

Should Tier - 1 be removed as it is not provided anymore?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f123c2b2-f125-19eb-85fc-7d216dacba26
* Version Independent ID: 6f249ad8-0852-356e-0612-13b8070b31c7
* Content: [Move licenses between agreement types - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/move-licenses-between-agreement-types?toc=/dynamics365/supply-chain/toc.json)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/move-licenses-between-agreement-types.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/get-started/move-licenses-between-agreement-types.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @ClaudiaBetz-Haubold
* Microsoft Alias: **chaubold**

**Comment by ClaudiaBetz-Haubold** [comment]
Thank you for the feedback, Ievgen, much appreciated. Article has been corrected.

Kind regards,

Claudia Betz-Haubold

**Comment by sericks007** [comment]
The updated article will be published later today.
