### ISSUE TITLE
Out of Date

### ISSUE THREAD

**Issue by BrianBennet** [MicrosoftDocs/dynamics-365-unified-operations-public#3118]
This document is out of date with current self service environments

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6465b985-b976-a032-6f05-e540ef844f30
* Version Independent ID: d13d8e4c-36cd-21ea-1113-99774093458f
* Content: [Batch processing and batch servers - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/batch-server-overview)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/batch-server-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/sysadmin/batch-server-overview.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Peakerbl
* Microsoft Alias: **peakerbl**

**Comment by sericks007** [comment]
@BrianBennet, thanks for making us aware of this issue.

@Peakerbl, please update the content.

**Comment by Peakerbl** [comment]
I'm no longer the PM for Batch. Right now I do not think there even is one after Reva moved on. @karimelazzouni might now the right person for this task.

**Comment by karimelazzouni** [comment]
Hi @sericks007 , can you please let us know what is the required changes? Just to make the document SF-friendly?

**Comment by karimelazzouni** [comment]
Hi @BrianBennet , I have reviewed the page in question and I cannot see any sections that would not apply to self-service environments. Can you please point out the portions which you thought were outdated?

**Comment by BrianBennet** [comment]
Sure
Self service environments run batch jobs on new BatchAOS server
There are no AOS1 or 2 to select

[cid:6dab6b95-aa45-4742-9198-27912af13f2f]

Brian Bennet
IT Manager

Email: Brian.Bennet@cbg.co.uk
Tel: +44 (0) 1243 792600
DDI: +44 (0) 1243 792515
Mob: +44 (0) 7764 960147

________________________________

**Comment by sericks007** [comment]
Bug 552137 has been logged to track this issue.

**Comment by karimelazzouni** [comment]
Hey @BrianBennet , thanks for the feedback. Please note that in self-service environment; the batch instances are prefixed with `BATCHAOS`; but they are still enumerated as such `BATCHAOS1`, `BATCHAOS2`, etc...
There are actually environments which have more than one batch node.

The description in the documentation is **only given as an example of the naming of multiple batch servers**; but the concept of having more than one batch server still applies for self-servicing environments as well.
