### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by JuraRabol** [MicrosoftDocs/dynamics-365-unified-operations-public#3119]
[Dear Sir or Madam, 

I am trying to import Aisino file but it is not possible. The OK button is greyed out. In Accounts receivable > Periodic> VAT invoice integration. What can I do?]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af243e84-e229-f05a-4213-207f097d1434
* Version Independent ID: bfee9b6c-ff12-3b34-8853-6402f9f4b8a2
* Content: [Configure tax integration for China - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/apac-chn-tax-integration)
* Content Source: [articles/finance/localizations/apac-chn-tax-integration.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/localizations/apac-chn-tax-integration.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @ShylaThompson
* Microsoft Alias: **leguo**

**Comment by sericks007** [comment]
@JuraRabol, thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

**Comment by JuraRabol** [comment]
Hello,

So what should I do if documentation is not correct?

Kind Regards

Jura Rabøl
Senior Consultant | CuroGens<http://www.curogens.com/>
M +34630870523

**Comment by sericks007** [comment]
@juraRabol, I've reopened this issue. 

@kfend, please assign this to the appropriate PM for review.

**Comment by sericks007** [comment]
Bug 552134 has been assigned to the PM.

**Comment by JuraRabol** [comment]
Hello,

When can I have a solution how to import the file for Aisino software? It is a legal requirement and I need it no later than this week.

Thank you

Kind Regards

Jura Rabøl
Senior Consultant | CuroGens<http://www.curogens.com/>
M +34630870523

**Comment by sericks007** [comment]
Bug 552134 has been assigned to the PM for review of the documentation.  

If you are having issues with the product, you need to log a support request. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

**Comment by v-oloski** [comment]
Hello,
To import a response file, please follow the next steps (after clicking **Import** button):
1. Select model mapping GTS Import format (Aisino) (CN) 
2. Click **Browse**  button to find file you want to upload
3. Click **Upload** button. After uploading the file, the **OK** button is available.

_Best regards,
Olga_

**Comment by JuraRabol** [comment]
Dear Olga,

What kind of file I should Import?

This is a setup so I cannot really import anything I would like.

Kind Regads

Jura Rabøl
Senior Consultant | CuroGens<http://www.curogens.com/>
M +34630870523

**Comment by v-oloski** [comment]
Hello Jura,

The file format is the same as a user export from Aisino/BaiWang system.
The process is following:

  1.  A user export files from the VAT invoice integration page list (D365)
  2.  A user import the exported file into Aisino/BaiWang application and the application assigns every invoice the system invoice number
  3.  A user export  invoices from Aisino/BaiWang application and these invoices have invoice numbers from Aisino/BaiWang application
  4.  A user import invoices exported from Aisino/BaiWang application into D365 and invoice numbers from Aisino/BaiWang application are fill in into External invoice number field (VAT invoice integration)
If you have any more questions please let me know.

Best regards,
Olga
