### ISSUE TITLE
Wrong documentation title

### ISSUE THREAD

**Issue by iroby** [MicrosoftDocs/dynamics-365-unified-operations-public#312]
As my understanding, this is just to configure http proxy for .net application, not reverse proxy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0ec145b-37e3-39d7-f7ef-2ea43a3a9b3a
* Version Independent ID: 30705b5a-301b-63d9-45df-91b1910990cf
* Content: [Configure reverse proxies for on-premises environments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/deployment/onprem-reverseproxy#feedback)
* Content Source: [articles/dev-itpro/deployment/onprem-reverseproxy.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/deployment/onprem-reverseproxy.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @sarvanisathish
* Microsoft Alias: **sarvanis**

**Comment by sericks007** [comment]
The topic has been renamed.
