### ISSUE TITLE
Grammatical Mistake

### ISSUE THREAD

**Issue by mattgo79-MSFT** [MicrosoftDocs/dynamics-365-unified-operations-public#3120]
Hi, Team. In the Privileges section below, there's a slight grammatical error.  Instead of "which makes it easier maintenance," it should be "which makes it easier to maintain."

Privileges
In the security model, a privilege specifies the level of access that is required to perform a job, solve a problem, or complete an assignment. Privileges can be assigned directly to roles, however we recommend that you only assign duties to roles. This is so that the privileges are first grouped together into a duty, which makes it easier maintenance.

My alias is GOMATT and am an FTE.  Thank you!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9907d444-3d05-f72e-7a7d-9e667c344987
* Version Independent ID: 4d757287-4674-dddf-1761-c57d0abe3530
* Content: [Role-based security - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/role-based-security)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/role-based-security.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/sysadmin/role-based-security.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Peakerbl
* Microsoft Alias: **peakerbl**

**Comment by sericks007** [comment]
@mattgo79-MSFT, thanks for making us aware of this issue! I've corrected the typo.
