### ISSUE TITLE
Environment Planning Tech Talk link broken

### ISSUE THREAD

**Issue by gunavs** [MicrosoftDocs/dynamics-365-unified-operations-public#3121]
Environment Planning Tech Talk link broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2402dfea-008a-c7bb-8a3b-1d0457a39665
* Version Independent ID: 4936afad-9a39-e65d-a00c-81246de632cb
* Content: [Environment planning - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/imp-lifecycle/environment-planning)
* Content Source: [articles/fin-ops-core/fin-ops/imp-lifecycle/environment-planning.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/imp-lifecycle/environment-planning.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @petryo
* Microsoft Alias: **petryo**

**Comment by sericks007** [comment]
@gunavs, thanks for making us aware of the broken link.  The link has been removed -- the updated content will be published soon.
