### ISSUE TITLE
Suggestion to update page with Org Roles

### ISSUE THREAD

**Issue by twhite-coles** [MicrosoftDocs/dynamics-365-unified-operations-public#3124]
Currently there are only explanations of Project Roles for LCS on this page. It would be helpful to document the **Admin** and **Contributor** Roles at an Org level and their associated permissions within LCS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ee6629a-f1a4-b352-0b26-657a503d80a7
* Version Independent ID: dbe54d30-b73b-0446-7d80-922050825641
* Content: [Configure Lifecycle Services (LCS) security - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/configure-lcs-security)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/configure-lcs-security.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/lifecycle-services/configure-lcs-security.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @AngelMarshall
* Microsoft Alias: **tsmarsha**

**Comment by kfend** [comment]
@twhite-coles - thank you for the feedback.

**Comment by sericks007** [comment]
@AngelMarshall, please update the content as suggested.

**Comment by josaw1** [comment]
BUG 552829 created to track.

**Comment by twhite-coles** [comment]
Was this done? I can't see the updates on the page?
