### ISSUE TITLE
Financial Dimensions Configuration

### ISSUE THREAD

**Issue by advent77** [MicrosoftDocs/dynamics-365-unified-operations-public#3125]
This article misses an opportunity to properly explain the mystique of Financial Dimensions. In particular, it is misleading and does NOT adequately explain the differences between DEFAULT dimension format and LEDGER dimension format ... and WHY they can be different. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e429cac-5092-03ec-71e4-425af9623908
* Version Independent ID: b88220bd-7b7c-2f9b-1eb2-212d7b9a3448
* Content: [Financial dimension configuration - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/financial/financial-dimension-configuration-integration)
* Content Source: [articles/fin-ops-core/dev-itpro/financial/financial-dimension-configuration-integration.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/financial/financial-dimension-configuration-integration.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @aprilolson
* Microsoft Alias: **aolson**

**Comment by kfend** [comment]
@advent77 - thank you for the feedback.
@aprilolson - please consider updating the topic based on this feedback from advent77

**Comment by aprilolson** [comment]
Can we assigned to @Ryan Carlson<mailto:Ryan.Carlson@microsoft.com> please?

April Olson
(She/her/hers)
Our workplace allows for a flexible schedule. I am sending this now as its convenient for me. I do not expect you to read or respond until it's convenient to you.

**Comment by josaw1** [comment]
@ryanCcarlson can you please review this?

**Comment by josaw1** [comment]
BUG 552830 created to track.

**Comment by RyanCCarlson2** [comment]
https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/issues/3125 
To update this doc.
