### ISSUE TITLE
Method described does not work for Microsoft hosted scale unit

### ISSUE THREAD

**Issue by andyNewnham** [MicrosoftDocs/dynamics-365-unified-operations-public#3126]
As per recent discussions on the insider program yammer group with @mugunthanm and @sepism - This document is not up to date and the method described does not work. 

An update is required to match the method used in the following blog post: https://community.dynamics.com/ax/b/axforretail/posts/support-for-service-to-service-authentication-in-retail-server - where 2x App Registrations are required on the customer tenant, to prevent errors obtaining a token such as: 
AADSTS500011: The resource principal named [Retail Server URL] was not found in the tenant named [Customer Tenant Id].

Reference to the yammer discussions: https://www.yammer.com/dynamicsaxfeedbackprograms/threads/1056454178512896

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2aaab0fa-b1ac-51c0-2329-73ab077477b2
* Version Independent ID: dc8cf3fc-4c9f-731c-a99e-d70b8b940428
* Content: [Consume Retail Server APIs in external applications - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/consume-retail-server-api)
* Content Source: [articles/commerce/dev-itpro/consume-retail-server-api.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/dev-itpro/consume-retail-server-api.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by tonyafehr** [comment]
@andyNewnham, thanks for the feedback. 
@mugunthanm, please review.

**Comment by tonyafehr** [comment]
The documentation for this will be updated later this week.
