### ISSUE TITLE
There should be note about IE11 support depreciation

### ISSUE THREAD

**Issue by Izmiyash** [MicrosoftDocs/dynamics-365-unified-operations-public#3127]
[Enter feedback here]
seeing inconsistency between this page and https://docs.microsoft.com/en-us/dynamics365/commerce/get-started/removed-deprecated-features-commerce#internet-explorer-11-support-for-dynamics-365-is-deprecated

There must be additional note about IE11 support depreciation. 

see below link as reference. there should be something similar in Commerce page as well.
https://docs.microsoft.com/en-us/dynamics365/commerce/get-started/removed-deprecated-features-commerce

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 043a7336-3d71-14f2-9856-05e03e24cd80
* Version Independent ID: 60414540-f243-27e6-0494-28c4af78e0a4
* Content: [System requirements for cloud deployments of Dynamics 365 Commerce - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/get-started/system-requirements)
* Content Source: [articles/commerce/get-started/system-requirements.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/get-started/system-requirements.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @jashanno
* Microsoft Alias: **jashanno**

**Comment by tonyafehr** [comment]
@Izmiyash, thanks for the feedback.
@jashanno , please review.

**Comment by tonyafehr** [comment]
Bug 554065 logged to track this issue.

**Comment by jashanno** [comment]
@Izmiyash You caught me just before we updated.  Good catch.

**Comment by Izmiyash** [comment]
I prefer having a note just below "Supported web browsers" part as well. (not just only after "Supported web browsers for Cloud POS")
