### ISSUE TITLE
Is Windows 7 still a valid choice???

### ISSUE THREAD

**Issue by Izmiyash** [MicrosoftDocs/dynamics-365-unified-operations-public#3128]
[Enter feedback here]
I don't believe windows 7 is one of supported OS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 043a7336-3d71-14f2-9856-05e03e24cd80
* Version Independent ID: 60414540-f243-27e6-0494-28c4af78e0a4
* Content: [System requirements for cloud deployments of Dynamics 365 Commerce - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/get-started/system-requirements)
* Content Source: [articles/commerce/get-started/system-requirements.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/get-started/system-requirements.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @jashanno
* Microsoft Alias: **jashanno**

**Comment by tonyafehr** [comment]
@Izmiyash, thanks for the feedback.
@jashanno , please review.

**Comment by tonyafehr** [comment]
Bug 554065 logged to track this issue.

**Comment by jashanno** [comment]
@Izmiyash Again, good job.  Caught it before I could get the updates completed.  They are now updated.

**Comment by Izmiyash** [comment]
I still can see "Windows 7" in some place in this page and am afraid these may make confusion. appreciate if you can consider these part as well.
e.g. 
https://docs.microsoft.com/en-us/dynamics365/commerce/get-started/system-requirements#supported-web-browsers
https://docs.microsoft.com/en-us/dynamics365/commerce/get-started/system-requirements#supported-web-browsers-for-cloud-pos

**Comment by jashanno** [comment]
@Izmiyash Thank you again.  I have a note for the second link you listed for Cloud POS regarding support removal in the .17 release and beyond, but I had not copied that note into the Headquarters browser section.  I will make a quick update for that hopefully this week as I'm currently quite busy on other priorities at the moment.
