### ISSUE TITLE
Update limitations for "last delivery date" Date of VAT Register option

### ISSUE THREAD

**Issue by vadalmon** [MicrosoftDocs/dynamics-365-unified-operations-public#3129]
Need to add this statement or similar to Date of VAT Register option "last delivery date":

Scenario when an invoice is posted based on several SOs is out of scope for "Last delivery date" option of Date of VAT register.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2051ccc-2d3a-563f-5d85-0947083341fa
* Version Independent ID: e2120a5f-4802-daaf-97a6-94296c0a86d5
* Content: [Tax point date (Date of VAT register) - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/emea-tax-point-date)
* Content Source: [articles/finance/localizations/emea-tax-point-date.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/localizations/emea-tax-point-date.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @LizaGolub
* Microsoft Alias: **kfend**

**Comment by tonyafehr** [comment]
@vadalmon, thanks for the feedback. 
@LizaGolub, please review.

**Comment by liza-golub** [comment]
@tonyafehr, Please review the suggested updated: https://github.com/MicrosoftDocs/Dynamics-365-Operations/pull/10382
