### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by jopankow** [MicrosoftDocs/dynamics-365-unified-operations-public#3130]
There is a typo at the top of the page. The important note heading is typed as "[!IMPORTAMT]" which I assume should be the word "important" (or possibly "[!Note]" -- I don't know all of the available formatting tags). This typo causes the formatting to be incorrect. Here is a screenshot:

![image](https://user-images.githubusercontent.com/43622120/106499471-40c54f00-6486-11eb-8027-6b100ca3fc75.png)

Please correct.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c22acc0-d42d-fa69-10ea-5b89b288078f
* Version Independent ID: 017d4f5a-c236-adda-ae8b-7848c1d8a873
* Content: [Flowcharts in Business process modeler (BPM) - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/flowcharts-business-process-modeler)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/flowcharts-business-process-modeler.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/lifecycle-services/flowcharts-business-process-modeler.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @AngelMarshall
* Microsoft Alias: **tsmarsha**

**Comment by sericks007** [comment]
@jopankow, thanks for letting us know! This has been fixed.  The updated content will be published soon.
