### ISSUE TITLE
Slight Grammatical Mistake

### ISSUE THREAD

**Issue by mattgo79-MSFT** [MicrosoftDocs/dynamics-365-unified-operations-public#3131]
Hello, in the third paragraph, it says, "...scheduled to run, the job exit early without rebuilding any indexes."  But it should really say, "...scheduled to run, the job **exits** early without rebuilding any indexes."

I am a Microsoft FTE and my alias is GOMATT.

Thank you!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee1ecd08-b417-33b6-46d9-9be22c92ed23
* Version Independent ID: 6082162f-3c1a-bce2-8f7a-c5b16223accd
* Content: [Batch job to handle SQL index defragmentation - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/batch-job-sql-defragmentation?source=docs)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/batch-job-SQL-defragmentation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/sysadmin/batch-job-SQL-defragmentation.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @Peakerbl
* Microsoft Alias: **ganas**

**Comment by sericks007** [comment]
@mattgo79-MSFT, thanks for letting us know about the typo!  It's been fixed. The updated content will be published soon.
