### ISSUE TITLE
What about existing CE and new F&O?

### ISSUE THREAD

**Issue by mdtahoe** [MicrosoftDocs/dynamics-365-unified-operations-public#3133]
This documentation says, "If an account exists in Dataverse, but it doesn't exist in the Finance and Operations app, it won't be initialized as part of this flow."

So, I might import them to F&O before the process except that I can't modify the account numbers to match the company code requirement in F&O because Dual Write requires the party exist.

How do I go about having parties on the account BEFORE this procedure?

-md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0891e384-80e8-5d40-8bde-24081e06876a
* Version Independent ID: b6ecc0cb-e827-80aa-934d-ef03d674c97e
* Content: [Initialize company data - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/bootstrap-company-data)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/bootstrap-company-data.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/dual-write/bootstrap-company-data.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RamaKrishnamoorthy
* Microsoft Alias: **rhaertle**

**Comment by tonyafehr** [comment]
@RamaKrishnamoorthy, please review.

**Comment by tonyafehr** [comment]
Bug 554067 logged to track this issue.

**Comment by tonyafehr** [comment]
The documentation will be updated shortly.
