### ISSUE TITLE
Develop and Test environment is no longer available as part of subscription.

### ISSUE THREAD

**Issue by sbaber82** [MicrosoftDocs/dynamics-365-unified-operations-public#3134]
As part of the subscription, customers just get one Production and one Sandbox environment. Why did it say that Customers are provided with one free "develop and test" environment hosted in Microsoft's Azure subscription?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe3913a6-4daa-9973-6f0b-d7ae4c1007c2
* Version Independent ID: f2cd311b-fcb8-cff4-57a3-47c3c52b19d6
* Content: [Deploy and access development environments - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/access-instances)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/access-instances.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-tools/access-instances.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by tonyafehr** [comment]
@laneswenka, please review.

**Comment by tonyafehr** [comment]
Bug 554068 logged to track this issue.

**Comment by laneswenka** [comment]
Made some minor changes, out in PR
