### ISSUE TITLE
Clarification needed.

### ISSUE THREAD

**Issue by freekwillem92** [MicrosoftDocs/dynamics-365-unified-operations-public#3135]
Can this be clarified: 

"Generate the beta keys for your offering in LCS."  **How?**
Enable the beta keys for your offering for your user in LCS. **How?**
Contact the Microsoft Inventory Visibility product team and provide an environment ID where you want to deploy the Inventory Visibility Add-in. **What email address??**
If you have any questions about these prerequisites, please contact the Inventory Visibility product team.
**What email address??**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bc1dd32-4ce4-a24a-83ee-3a941cda699c
* Version Independent ID: e03279d2-3b8a-bbd7-9c0f-ab566ad20057
* Content: [Inventory Visibility Add-in - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/inventory/inventory-visibility)
* Content Source: [articles/supply-chain/inventory/inventory-visibility.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/inventory/inventory-visibility.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @chuzheng
* Microsoft Alias: **chuzheng**

**Comment by tonyafehr** [comment]
@freekwillem92, thanks for the feedback. 
@kamaybac, please assign to the appropriate author.

**Comment by kamaybac** [comment]
@sherry-zheng , please take a look at this documentation feedback, thanks.

**Comment by tonyafehr** [comment]
Bug 554069 logged to track this issue.

**Comment by kamaybac** [comment]
@freekwillem92 , we have updated the topic to include the requested information. Thank you for pointing out these issues.
