### ISSUE TITLE
Please update Writage description

### ISSUE THREAD

**Issue by sheremetyeva** [MicrosoftDocs/dynamics-365-unified-operations-public#3139]
Hi there,

Currently, this page contains a recommendation to not use Writage for editing Markdown files in Word because of the possibility of lost metadata tags and some formatting. 

Please note, that the latest version of Writage supports metadata tags in Markdown files. Writage was tested on Microsoft Dynamics documentation available on the GitHub (https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-public) and it works well. All the metadata tags are preserved, and no formatting is lost.

Could you possibly try the latest version from: https://www.writage.com/download/ and update Writage description on this webpage.

Many thanks,
Elena 

@jowilco @edupont04 @RobinARH @christophernread

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 433cd9a4-e3e6-1e46-eab8-59f503ce6c70
* Version Independent ID: debe7c1d-8ad4-eed9-26bc-0400158b14f8
* Content: [Extend, customize, and collaborate on the Help - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/help/contributor-guide)
* Content Source: [articles/fin-ops-core/dev-itpro/help/contributor-guide.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/help/contributor-guide.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by josaw1** [comment]
Thanks for the feedback. @RobinARH can you please review?

**Comment by josaw1** [comment]
This will be updated in the next few days.

**Comment by edupont04** [comment]
@sheremetyeva Thank you for alerting us to this! We'll get the wording updated where applicable.
