### ISSUE TITLE
Download Link

### ISSUE THREAD

**Issue by Daniel-Guenter** [MicrosoftDocs/dynamics-365-unified-operations-public#314]
Could we please have a link or a note on how to acquire the upgrade analyzer tool?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba5f7f18-9507-3798-c4f6-731622a71001
* Version Independent ID: 94624fbf-dd2e-d3aa-c1e3-cf6cc7c05609
* Content: [Upgrade from AX 2012 - Plan by using the Upgrade analyzer tool - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/upgrade-analyzer-tool)
* Content Source: [articles/dev-itpro/migration-upgrade/upgrade-analyzer-tool.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/migration-upgrade/upgrade-analyzer-tool.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @tariqbell
* Microsoft Alias: **tabell**

**Comment by tonyafehr** [comment]
The topic has been updated with the correct information. 

To access the Upgrade analyzer report, go to https://diag.lcs.dynamics.com/UpgradeAnalysisReport/Report/"ProjectID" (Replace "ProjectID" with your current project ID which is an integer that can be found in the URL of your current LCS project)
