### ISSUE TITLE
Transformation is not specified

### ISSUE THREAD

**Issue by MattijsMIN** [MicrosoftDocs/dynamics-365-unified-operations-public#3140]
In the mapping between tables "CDS inventory on-hand requests" and "msdyn_inventoryonhandrequests" it is specified that data should be transformed when mapping following fields: "ISATPCALCULATION" <<  "msdyn_isatpcalculation"
However, the actual transformation is not specified. 
How should this data be transformed? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0f2a03e-b77a-9f2b-0ba5-ffbab4a418cd
* Version Independent ID: c0c1e93f-d1a3-c62e-abb8-1be918017bad
* Content: [Inventory availability in dual-write - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/inventory-availability)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/inventory-availability.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/dual-write/inventory-availability.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @yijialuan
* Microsoft Alias: **riluan**

**Comment by kfend** [comment]
@RamaKrishnamoorthy - is this something you can take a look at and possibly address?
