### ISSUE TITLE
Explain usage of Active from / Active to fields and impact on overlap / validation

### ISSUE THREAD

**Issue by Smeedijzer** [MicrosoftDocs/dynamics-365-unified-operations-public#3141]
Missing explanation on usage of Active from / Active to fields and their impact on overlap / validation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6d5f2af-279f-a76f-285e-361f67524006
* Version Independent ID: ed9c2f1f-61bf-8b12-6198-a17931fa9c7c
* Content: [Configure account structures - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/general-ledger/configure-account-structures)
* Content Source: [articles/finance/general-ledger/configure-account-structures.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/general-ledger/configure-account-structures.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @aprilolson
* Microsoft Alias: **aolson**

**Comment by kfend** [comment]
@Smeedijzer - thank you for the feedback.
@aprilolson - can you please take a look and consider updating the topic with this feedback? Thanks!

**Comment by kfend** [comment]
@RyanCCarlson2 - can you please take a look and consider updating the topic with this feedback? Thanks!

**Comment by RyanCCarlson2** [comment]
Yes, got it.

Ryan Carlson
Principal PM - Dynamics 365 for Operations | GFM team | 701.492.3568 (w)

**Comment by kfend** [comment]
Bug 558331 created to track this issue.
