### ISSUE TITLE
Excel Add-In support for Office for Mac

### ISSUE THREAD

**Issue by KheeChan** [MicrosoftDocs/dynamics-365-unified-operations-public#3142]
Information at "[Office client application and platform availability for Office Add-ins](url)" indicates the Excel Add-In is indeed support for Office for Mac for Office with M365 subscription and Office 2019 (local installed) as at Jan 26 2021.

Given that the last update of this page is April 26 2020, can we assume that the answer to the above question "[Does the Excel Add-in support Office for Mac?](url)" is NO LONGER "NO"? In other words, this page will eventually be updated to reflect the current status that **"Yes, Excel Add-In is support for Office M365 and Office 2019"**?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb4baa3a-54a6-4159-f762-a9ad10706256
* Version Independent ID: ea906dbf-88ad-fe2d-c9ef-dcd28f1a6729
* Content: [Troubleshoot the Office integration - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/office-integration/office-integration-troubleshooting?source=docs)
* Content Source: [articles/fin-ops-core/dev-itpro/office-integration/office-integration-troubleshooting.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/office-integration/office-integration-troubleshooting.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @ChrisGarty
* Microsoft Alias: **cgarty**

**Comment by jasongre** [comment]
@KheeChan the Finance and Operations Excel add-in would still have additional work to add Mac support, so the current documentation is still correct.
