### ISSUE TITLE
Error in instructions

### ISSUE THREAD

**Issue by jkbirch** [MicrosoftDocs/dynamics-365-unified-operations-public#3144]
"Empty location with no incoming work – Use this strategy to locate empty locations. A location is considered empty if it has no physical inventory and no expected incoming work. You can use this strategy only for location directives that have a work type of Pick."

Empty location with no incoming work requires a location with a work type of PUT, not pick. You cannot pick material from an empty location, but oftentimes will want to find an empty location for PUT work. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc5a7dca-01c4-4cfa-87fe-1106d0214ec4
* Version Independent ID: 57d17ce4-5b6a-3e51-deb0-293cac09278b
* Content: [Work with location directives - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/warehousing/create-location-directive)
* Content Source: [articles/supply-chain/warehousing/create-location-directive.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/warehousing/create-location-directive.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @Mirzaab
* Microsoft Alias: **mirzaab**

**Comment by tonyafehr** [comment]
@jkbirch, thanks for the feedback. 
@Mirzaab, please review.

**Comment by tonyafehr** [comment]
Bug 555831 logged to track this issue.

**Comment by tonyafehr** [comment]
We've updated the instructions. These updates will be published shortly.
