### ISSUE TITLE
This page is possibly outdated 

### ISSUE THREAD

**Issue by apierre2000** [MicrosoftDocs/dynamics-365-unified-operations-public#3145]
I had a customer who asked where is the 'Financial Insights' in D365FO.  It appears that this page is probably outdated based on the link below.

https://docs.microsoft.com/en-us/dynamics365-release-plan/2020wave2/finance-operations/dynamics365-finance/financials-embedded-powerbi-enhanced-renamed
![image](https://user-images.githubusercontent.com/78810698/107390761-a1bfd900-6abd-11eb-8071-334451e00600.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84992dbc-779a-2e46-de21-556a6031c561
* Version Independent ID: 04d7cf2c-f55e-8765-d3ed-44502e259bc2
* Content: [Financial Insights - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/financial-insights)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/financial-insights.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/financial-insights.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @kweekley
* Microsoft Alias: **kweekley**

**Comment by tonyafehr** [comment]
@apierre2000, thanks for the feedback.  
@kweekley and @roschlom, please review.

**Comment by tonyafehr** [comment]
Bug 555833 logged to track this issue.

**Comment by jinniew** [comment]
I have edited the Financial Insights document and updated it to reflect the current Financial Analysis dashboard. 

https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/financial-analysis
