### ISSUE TITLE
Apply a package to a production environment by using LCS > On Self-Service type environments

### ISSUE THREAD

**Issue by christophewyns** [MicrosoftDocs/dynamics-365-unified-operations-public#3146]
Hello,

Can you please update the section "Apply a package to a production environment by using LCS" for Self-service type PRODUCTION environments ?
The change being that you need to mark the deployable package as "Release candidate" from the "Environment change history" on the Standard acceptance test environment where it was deployed, in place of doing it from the Asset library.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bcf4a74-1317-2f29-a9a6-3eb4c20c431f
* Version Independent ID: 9ce93e91-c55a-708b-bc9c-95a34bbf5b7b
* Content: [Apply updates to cloud environments - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/apply-deployable-package-system#apply-a-package-to-a-production-environment-by-using-lcs)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/apply-deployable-package-system.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/deployment/apply-deployable-package-system.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by sericks007** [comment]
@christophewyns, thank you for providing this feedback.

@laneswenka, please review and update the content, as suggested.

**Comment by sericks007** [comment]
Bug 9347979 has been logged to track this issue.
