### ISSUE TITLE
Slight Typo

### ISSUE THREAD

**Issue by mattgo79-MSFT** [MicrosoftDocs/dynamics-365-unified-operations-public#3147]
Hi.  Towards the beginning of this documentation, it states that "A data entity is a conceptual abstraction and encapsulation of one OF more underlying tables."  It should be "...of one OR more underlying tables."

I am a Microsoft FTE and my alias is GOMATT.  Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1016eba2-a0f9-8890-beb4-7c9f9f6df4fc
* Version Independent ID: 57758813-9d36-975a-eb6f-551b7da3e276
* Content: [Data management overview - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/data-entities-data-packages?source=docs#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/data-entities-data-packages.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/data-entities-data-packages.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by sericks007** [comment]
@mattgo79-MSFT, thanks for letting us know about this! I've corrected the typo -- the updated content will be published later today. Thanks again!
