### ISSUE TITLE
There is no information about the linked Common Data Service (CDS) Environment on FSCM Database refresh

### ISSUE THREAD

**Issue by valerymoskalenko** [MicrosoftDocs/dynamics-365-unified-operations-public#3148]
There is no information about the linked Common Data Service (CDS) Environment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d28e8cc-5110-f01b-db76-94479ec2fa91
* Version Independent ID: f0710707-9ff2-84a1-30c7-1f0d44e3a0d7
* Content: [Refresh database - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/database-refresh)
* Content Source: [articles/fin-ops-core/dev-itpro/database/database-refresh.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/database/database-refresh.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by josaw1** [comment]
Thanks for your feedback. @laneswenka, can you please review?

**Comment by josaw1** [comment]
BUG 562253 created to track.

**Comment by laneswenka** [comment]
Added context for dual-write linking for all of the database movement operations.  This will go out in the next publishing wave.
