### ISSUE TITLE
Feature release version ?

### ISSUE THREAD

**Issue by andypicking** [MicrosoftDocs/dynamics-365-unified-operations-public#3154]
Hi, can you identify which version of D365FO this new feature appears in - we have checked 10.0.16 and cannot see it ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18ac9c7f-45bb-f8b0-5a28-7dc36ff312b1
* Version Independent ID: 45a7f839-cf3e-4cdb-1c01-d901dad2e74b
* Content: [Manage standard cost updates - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/cost-management/manage-standard-cost-updates)
* Content Source: [articles/supply-chain/cost-management/manage-standard-cost-updates.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/cost-management/manage-standard-cost-updates.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @AndersGirke
* Microsoft Alias: **mguada**

**Comment by kfend** [comment]
@andypicking - thanks for the question. 
@kamaybac - can you address this question?

**Comment by kamaybac** [comment]
@andypicking , the feature was [released in 10.0.17](https://docs.microsoft.com/en-us/dynamics365/supply-chain/get-started/whats-new-scm-10-0-17), which is why you don't see it. As mentioned in this topic, you'll need to enable it in feature management in 10.0.17.
