### ISSUE TITLE
Note about Dev environment "hosted by Microsoft" is out of date

### ISSUE THREAD

**Issue by danielzook** [MicrosoftDocs/dynamics-365-unified-operations-public#3158]
The note below the heading "Download and restore the backup to the development environment" states: "Developer environments that are hosted by Microsoft.  Developer environments that are hosted by Microsoft have limited drive space. We recommend that most AX 2012 customers host their own developer environment by using cloud-hosted environments."

This is out of date.  Per this article: https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/cloud-deployment-overview#remote-desktop

"With each Enterprise offer, two environments are included by default:

One Tier 2 sandbox (multi-box environment) for user acceptance testing (UAT).
One production environment with high availability (HA).
Additional environments may be purchased as add-ons. "

So *all* dev environments are now cloud-based, so this note is meaningless and should be removed so that it doesn't cause further confusion.  (Microsoft already causes enough confusion as it is...)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ae815e8-03c2-0769-5e6a-e36f57244651
* Version Independent ID: 5304a30a-ca52-0bb6-99c3-c7a5bb8ab36e
* Content: [Upgrade from AX 2012 - Data upgrade in development environments - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/data-upgrade-2012)
* Content Source: [articles/fin-ops-core/dev-itpro/migration-upgrade/data-upgrade-2012.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/migration-upgrade/data-upgrade-2012.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by andreabichsel** [comment]
@laneswenka Can you take a look? Thanks!

**Comment by laneswenka** [comment]
This was resolved in June, reassigning.

**Comment by laneswenka** [comment]
@andreabichsel  / @sericks007 please close as needed.
