### ISSUE TITLE
Casing in XML and XSLT

### ISSUE THREAD

**Issue by JimChw** [MicrosoftDocs/dynamics-365-unified-operations-public#3163]
Not everyone is XML/XSLT wizards.  For debugging, it may be nice to mention that XML names in the XSLT must match the casing of  the nodes in the XML.  At some point in the past, the casing of the Positive Pay XML in D365FO changed from mixed-case to all uppercase.  Positive Pay XSLT transformations stopped working because of this.  It was difficult to debug since a working XSLT seems to be required.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a56dd618-9180-ed71-fd8e-850153f35b59
* Version Independent ID: 6322764e-1b61-5148-024a-0d6b124c0512
* Content: [Set up and generate positive pay files - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/accounts-payable/set-up-generate-positive-pay-files)
* Content Source: [articles/finance/accounts-payable/set-up-generate-positive-pay-files.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/accounts-payable/set-up-generate-positive-pay-files.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @panolte
* Microsoft Alias: **shpandey**

**Comment by andreabichsel** [comment]
@panolte Can you take a look? Thanks!

**Comment by roschlom** [comment]
Bug 3163 was created to track this.

**Comment by roschlom** [comment]
The topic was updated to include the information that was suggested. Thanks again for the input. Please feel free to send us feedback any time!
