### ISSUE TITLE
The section about in-grid filtering is not correct

### ISSUE THREAD

**Issue by MichaelFruergaardPontoppidan** [MicrosoftDocs/dynamics-365-unified-operations-public#3167]
Repro:
1. Use USMF
2. Apply a filter on ItemId=M0003
3. Notice OnOrder = 1405.  
4. In the grid, apply a filter on OnOrder where OnOder "Greater than or equal" 600
5. Notice OnOrder is = 871

I.e. this kind of filter applies to the source records, and not to the aggregated values, as this doc suggests.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5815c391-19d5-d867-1993-109e8c3f7612
* Version Independent ID: a375dfbc-9f5b-c2ca-0d5f-9521c7fa96ca
* Content: [Inventory on-hand list - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/inventory/inventory-on-hand-list)
* Content Source: [articles/supply-chain/inventory/inventory-on-hand-list.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/inventory/inventory-on-hand-list.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @sherry-zheng
* Microsoft Alias: **chuzheng**

**Comment by roschlom** [comment]
Thanks for the feedback, Michael. We'll look into it.

**Comment by roschlom** [comment]
Bug 565971 was opened to track this issue.

**Comment by tonyafehr** [comment]
@kamaybac, please review.
