### ISSUE TITLE
Extract SYSFLIGHTING documentation to its own page, with more clear instructions

### ISSUE THREAD

**Issue by fredmd-msft** [MicrosoftDocs/dynamics-365-unified-operations-public#3169]
I needed to find an official documentation on how to enable a flight and the only one that I could see under the Microsoft official docs is a section within some other documentation.

I would like to suggest that we extract that section as a standalone document that we can refer customers to when they need to make changes to their flight configuration. This will not only help us documenting bug fixes that ship disabled by default, but also help reducing unnecessary calls to support just for us to perform changes that the customer would have been able to perform themselves, if there was appropriate documentation.

In particular, it would be important to clarify the explanations of the Partition and RecID. The content is confusing and uses a language customers won't be familiar with ("this can be partition ID + 'n'", what is 'n'? please give examples).

Thanks,

Fred
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1016eba2-a0f9-8890-beb4-7c9f9f6df4fc
* Version Independent ID: 57758813-9d36-975a-eb6f-551b7da3e276
* Content: [Data management overview - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/data-entities-data-packages)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/data-entities-data-packages.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/data-entities-data-packages.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by roschlom** [comment]
Bug 565975 was opened to track this issue.
