### ISSUE TITLE
Missing Sales tax reporting code for K_34

### ISSUE THREAD

**Issue by kosciraf** [MicrosoftDocs/dynamics-365-unified-operations-public#317]
There is missing Sales tax reporting code that should be attached to Tag name in SAF-T VAT: K_34

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2ff4506-80d6-fde6-3daf-1c4a2a372ae9
* Version Independent ID: 79aca9a5-2631-3df2-88fa-1cab02844cbd
* Content: [Standard audit file (SAF) for Poland - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/localizations/emea-pol-standard-audit-file-saf)
* Content Source: [articles/financials/localizations/emea-pol-standard-audit-file-saf.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/localizations/emea-pol-standard-audit-file-saf.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @LizaGolub
* Microsoft Alias: **v-elgolu**

**Comment by sericks007** [comment]
Thanks for letting us know about this! We'll investigate the issue.

**Comment by ShylaThompson** [comment]
The topic will be updated by the end of this week with the necessary change.

**Comment by kosciraf** [comment]
HI 
As I see there is a change made for 11301 and 11304. There was a change from K_31 to K_34.
Please take into account, that there is a need to report K_31, as well as K_34.
In Polish tax declaration (VAT-7) there is a need to report ReverseCharge in both situation: when transaction is posted as a seller, and as a buyer. 
So there is a need to have to different sales tax reporting codes for ReverseCharge Taxable sales: one reported to field K_31, other one reported to K_34.
Please take a look in definition of VAT-7 (18): https://www.finanse.mf.gov.pl/pp/e-deklaracje/formularze/vat
Fields: C.13, C.15
