### ISSUE TITLE
Link to Symbol Font page is broken

### ISSUE THREAD

**Issue by dhand01** [MicrosoftDocs/dynamics-365-unified-operations-public#3173]
Link to symbol font page is broken. Need a way to view the font release documentation.

[Enter feedback here]

---
#### Document Details

<span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://gaoflciahikhligngeccdecgfjngejlh/emoji-data/sheet_apple_32.png);background-position:95.94594594594594% 75.96944770857814%;background-size:5418.75% 5418.75%" data-codepoints="26a0-fe0f"></span></span> *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5103263-c61e-38db-e6a6-354ed41ee61e
* Version Independent ID: ea0e7fef-f321-5f74-465e-e72accc046ed
* Content: [Dynamics Symbol font - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/user-interface/symbol-font)
* Content Source: [articles/fin-ops-core/dev-itpro/user-interface/symbol-font.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/user-interface/symbol-font.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **bensm**

**Comment by RobinARH** [comment]
The symbol font files are here: https://docs.microsoft.com/en-us/dynamics/s-e/ax/axsymbolfont_60.

I'll update the topic.
