### ISSUE TITLE
Slight Typo

### ISSUE THREAD

**Issue by mattgo79-MSFT** [MicrosoftDocs/dynamics-365-unified-operations-public#3177]
Good morning, 

There is a slight typo towards the beginning of the documentation.  In the bullet point that defines what the Primary Table is, it reads, "In the above example, the **CustGrouptable** would be the primary table."  It should read, "In the above example, the CustGroup table would be the primary table."  There should be a space in between Group and table. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a953fbe-ec7f-9984-42f8-3c88248761a1
* Version Independent ID: 4b40257c-e071-b131-31ac-1dcdbe8d995b
* Content: [Extensible data security policies - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/extensible-data-security-policies)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/extensible-data-security-policies.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/sysadmin/extensible-data-security-policies.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @Peakerbl
* Microsoft Alias: **peakerbl**

**Comment by roschlom** [comment]
Thank you letting us know about the issue. We appreciate the feedback!

**Comment by roschlom** [comment]
This issue has been addressed now. Thanks again for the feedback!
