### ISSUE TITLE
LCS Restart service references this page but there is no "restart" explanation

### ISSUE THREAD

**Issue by ronsonntag54** [MicrosoftDocs/dynamics-365-unified-operations-public#3178]
When using LCS Maintain > Restart service and then in right-panel select the link ... "restart services" topic, it links to this page. But, this page does not have any explanation on restarting services and does not explain the recent changes to the list of services that can be restarted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c7f272b-4ea7-a285-4a9f-e67583a664e0
* Version Independent ID: 54ac0c3d-a2b5-6001-1581-167dd87a80c0
* Content: [Self-service deployment overview - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/infrastructure-stack)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/infrastructure-stack.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/deployment/infrastructure-stack.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @rashmansur
* Microsoft Alias: **rashmim**

**Comment by roschlom** [comment]
Thanks for your input on this topic. We appreciate the feedback!

**Comment by roschlom** [comment]
Bug 565987 has been opened to track this issue.
