### ISSUE TITLE
Link Demo data scripts is outdated

### ISSUE THREAD

**Issue by vavd** [MicrosoftDocs/dynamics-365-unified-operations-public#3179]
The link "Demo data scripts" in the [Scenario scripts](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/generate-demo-data-packages#scenario-scripts) section is outdated.
It refers to the CustomerSource portal which has been retired.
Please update the link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d608dae5-a2fc-0cfb-0eb7-f7b3c8db73c3
* Version Independent ID: be73116b-7628-2b43-169f-d6efd52931b3
* Content: [Generate demo data by using data packages - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/generate-demo-data-packages)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/generate-demo-data-packages.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/generate-demo-data-packages.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @panolte
* Microsoft Alias: **panolte**

**Comment by roschlom** [comment]
Thank for the input on our documentation. We really appreciate it!

**Comment by roschlom** [comment]
Bug 565988 was opened to track this issue.
