### ISSUE TITLE
Page  "Purchase requisition consolidation" not found in D365 

### ISSUE THREAD

**Issue by boonsongcha** [MicrosoftDocs/dynamics-365-unified-operations-public#3180]
Page  "Purchase requisition consolidation" not found in D365 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64e0b952-06c2-1c2c-aa04-dd972d200a2b
* Version Independent ID: a98addf4-b0e2-f503-b40b-4ae182114c78
* Content: [Purchase requisition overview - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/procurement/purchase-requisitions-overview)
* Content Source: [articles/supply-chain/procurement/purchase-requisitions-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/procurement/purchase-requisitions-overview.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @RichardLuan
* Microsoft Alias: **riluan**

**Comment by boonsongcha** [comment]
It's "Consolidation opportunities" at Procurement and Sourcing > Purchase requisitions > Approved purchase requisition processing in D365

**Comment by roschlom** [comment]
Thank you for the input on our documentation. We really appreciate it.

**Comment by RobinARH** [comment]
Created bug 582857 to track this issue.
