### ISSUE TITLE
No description of zip, packageheader and manifest file

### ISSUE THREAD

**Issue by jdefesche1** [MicrosoftDocs/dynamics-365-unified-operations-public#3182]
There is no documentation on how the zip file should look like, particularly the packageheader and manifest files. There is no way to tell what each attributes means and if they are mandatory or not.

Any proper product should be accompanied with solid documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01b2cd6b-f885-7461-fbdf-cf81f9e50d86
* Version Independent ID: 8df7a6ae-67db-5d29-fb6a-0820704ff3ef
* Content: [Recurring integrations - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/recurring-integrations)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/recurring-integrations.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/recurring-integrations.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by roschlom** [comment]
Thank you for the input on our documentation. We really appreciate it.

**Comment by RobinARH** [comment]
Created bug 582880 to track this issue.

**Comment by kfend** [comment]
Thank you for the feedback. 
I believe the documentation you are looking for is in the topic, [Process and consume data packages in Dynamics 365 Finance and Operations apps solution](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lcs-solutions/process-data-packages-lcs-solutions). The recommended approach is to automatically create the data package, zip file, as described in step 6-10 in the beginning of the above topic. There is no need to try to manually create the data package file.
