### ISSUE TITLE
Incorrect link?

### ISSUE THREAD

**Issue by RobvanB** [MicrosoftDocs/dynamics-365-unified-operations-public#3183]
See snippet below - I don't think the link to 'Alerts as business events' below is valid for D365 Human Resources.
I think that link is only valid for D365 F&O.
If it *is* valid, then it is not clear at all on how to get the Power Automate Flow linked to the business event.

If you want to configure a workflow for the address changes, you can select the Send externally option on your alert rule, and then use Power Automate to trigger the business event and configure a workflow. For more information, see Alerts as business events.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 011ee20d-1afb-ef83-9bda-1981d7e73edc
* Version Independent ID: f73902f8-16ab-0065-e2e5-53ac14deacf4
* Content: [View and manage address changes - Human Resources | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/human-resources/hr-personnel-view-address-changes#view-and-monitor-address-changes)
* Content Source: [articles/human-resources/hr-personnel-view-address-changes.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/human-resources/hr-personnel-view-address-changes.md)
* Service: **dynamics-365-human-resources**
* Product: ****
* Technology: ****
* GitHub Login: @andreabichsel
* Microsoft Alias: **anbichse**

**Comment by andreabichsel** [comment]
@jcart1106 Can you take a look? Thanks!
