### ISSUE TITLE
"Object reference not set to an instance of an object" error during data entity publishing

### ISSUE THREAD

**Issue by artemt1** [MicrosoftDocs/dynamics-365-unified-operations-public#3185]
Columstore indexes are supported from S3 Azure SQL tier level and if you want to use S0 (or basic) for development/testing, you need to disable this option, or upgrade Azure SQL to S3
Else you will get "Object reference not set to an instance of an object" error during data entity publishing.

More details here:
https://community.dynamics.com/365/financeandoperations/f/dynamics-365-for-finance-and-operations-forum/393593/publishing-entity-to-byod-giving-object-reference-not-set-to-an-instance-of-an-object-error

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33f75161-0776-a6c1-dc10-dc20ea26973f
* Version Independent ID: 55a81394-4606-745a-9fd2-59fb257d1086
* Content: [Bring your own database (BYOD) - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/export-entities-to-your-own-database)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/export-entities-to-your-own-database.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/export-entities-to-your-own-database.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by roschlom** [comment]
Thanks for commenting on our documentation. We appreciate the feedback.

**Comment by RobinARH** [comment]
Created bug 582883 to track this issue.
