### ISSUE TITLE
Error in texts

### ISSUE THREAD

**Issue by kurthatlevik-inspirit365** [MicrosoftDocs/dynamics-365-unified-operations-public#3187]
There are a error on the caching option description.  I think it should be defined that the caching option should be set to enabled on the caching rule in Azure Front Door Service:

In the text saying : 
To set up a caching rule in Azure Front Door Service, follow these steps.
.
.
10. Set the Caching option to Disabled. <-- this should be "Enabled"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55cd17ff-3399-8090-a664-0774e49f9a20
* Version Independent ID: 2617f5a7-c6f9-7da6-21c7-844c78218d97
* Content: [Add support for a content delivery network (CDN) - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/add-cdn-support)
* Content Source: [articles/commerce/add-cdn-support.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/add-cdn-support.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @BrianShook
* Microsoft Alias: **brshoo**

**Comment by BrianShook** [comment]
Reviewed with engineering team. The "Set up a Caching Rule" section is being removed; "Set up rules in Azure Front Door Service" will remain as relevant section.
