### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by AmiyaKumarBhanj** [MicrosoftDocs/dynamics-365-unified-operations-public#319]
Very informative

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d17272c7-faee-7843-25f2-67134a2a8a53
* Version Independent ID: d8feaaf3-e429-2763-f89d-c95f1f07fd4b
* Content: [Cloud platform monthly updates FAQ - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/sysadmin/faq-platform-monthly-updates#how-can-i-get-early-access-to-the-platform-bits-for-validation)
* Content Source: [articles/dev-itpro/sysadmin/faq-platform-monthly-updates.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/sysadmin/faq-platform-monthly-updates.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @manalidongre
* Microsoft Alias: **meeram**

**Comment by sericks007** [comment]
Thank you for taking the time to comment! We appreciate your feedback!
