### ISSUE TITLE
Link provided in 'Golden configuration promotion' is broken

### ISSUE THREAD

**Issue by harishmohanbabu** [MicrosoftDocs/dynamics-365-unified-operations-public#3190]
Hello,

In the middle of this page, there is a link to '**Golden configuration promotion**'  (Under section _When refreshing from sandbox environment to production environment_);   this link is broken.  

Can this be resolved please.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d28e8cc-5110-f01b-db76-94479ec2fa91
* Version Independent ID: f0710707-9ff2-84a1-30c7-1f0d44e3a0d7
* Content: [Refresh database - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/database-refresh)
* Content Source: [articles/fin-ops-core/dev-itpro/database/database-refresh.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/database/database-refresh.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by sericks007** [comment]
@harishmohanbabu, thanks for making us aware of this issue!  I've fixed the link.  The update will be published soon.  

The link goes to this topic: [Golden configuration promotion](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/dbmovement-scenario-goldenconfig).
