### ISSUE TITLE
Global administrator in place ofAzure Active Directory tenant administrator rights 

### ISSUE THREAD

**Issue by jeevanbalanmanoj** [MicrosoftDocs/dynamics-365-unified-operations-public#3194]
[Enter feedback here]
"You will need Azure Active Directory tenant administrator rights to perform these steps" doesn't clarify what role is needed to create the first-party service principal. Please change it You will need Azure Active Directory Global administrator rights to perform these steps. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c84e15d4-bcac-038a-2b1e-8c456ee25bd9
* Version Independent ID: 478b5f33-f745-1df2-8fe0-da9e64233165
* Content: [Configure export to Azure Data Lake - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/configure-export-data-lake#createServicePrinciple)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/configure-export-data-lake.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/configure-export-data-lake.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by kfend** [comment]
@jeevanbalanmanoj - thank you for this feedback.
@MilindaV2 - can you please take a look at this and update the topic?

**Comment by jeevanbalanmanoj** [comment]
@MilindaV2  Can you please resolve this at the earliest?

**Comment by sericks007** [comment]
@MilindaV2 updated the content to address this issue.  His update will be published soon.
