### ISSUE TITLE
Microsoft Managed VM's are no longer available

### ISSUE THREAD

**Issue by kurthatlevik-inspirit365** [MicrosoftDocs/dynamics-365-unified-operations-public#3200]
Microsoft Managed VM's are no longer available, so this page is out-of-date.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af500682-8f80-9045-bba6-4c7214ec2ba7
* Version Independent ID: 93452b64-0d32-6be7-529f-e7cba806a5df
* Content: [Development in cloud-hosted environments without admin access - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/cloud-dev-box)
* Content Source: [articles/commerce/dev-itpro/cloud-dev-box.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/dev-itpro/cloud-dev-box.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by mugunthanm** [comment]
Updated the doc.

**Comment by kfend** [comment]
@kurthatlevik-inspirit365 - thanks for this feedback.
@mugunthanm - thank you for updating the topic so quickly!
