### ISSUE TITLE
Partner Trial link is dead

### ISSUE THREAD

**Issue by turbozapekanka** [MicrosoftDocs/dynamics-365-unified-operations-public#3202]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a274fef-425c-141b-d664-ef23d19ef50a
* Version Independent ID: cd2c69ea-ad19-2313-e22e-eda706ceff9e
* Content: [Get evaluation copies - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/get-evaluation-copy)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/get-evaluation-copy.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-tools/get-evaluation-copy.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **jorisde**

**Comment by RobinARH** [comment]
I updated the link and the updated topic will go live tonight.
