### ISSUE TITLE
Deprecation date is misleading when compared to planning optimisation fit analysis

### ISSUE THREAD

**Issue by andypicking** [MicrosoftDocs/dynamics-365-unified-operations-public#3207]
The article states that the deprecation date for master planning in manufacturing scenarios is October 2021. However this is misleading since many of the features required in manufacturing scenarios (I counted 16) have an expected availability of October 2021 to April 2021 according to this page - https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/public-preview-releases. Customers could read the deprecation notice and subsequently find that the features they need for Business As Usual are expected to be available up to 6 months after the deprecation notice - this causes concern with where they stand from a support perspective.

I've had one customer ask me how such a key area of the product can be deprecated before they are able to switch to using it, because they will still be waiting for the outstanding features which may not be available to them ? Effectively this means they could be in a position of running unsupported software from Microsoft, and the reason its unsupported is because the BAU features they need are yet available.

Please can the article be updated to address the concerns I have been receiving from some of our customers ?

Thanks in advance
Andy Barnett-Picking

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60ff0ecf-cab1-5665-554e-ec493c3a6159
* Version Independent ID: e02b7a35-a15f-9205-d084-b3498eddc842
* Content: [Removed or deprecated features in Dynamics 365 Supply Chain Management - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/get-started/removed-deprecated-features-scm-updates)
* Content Source: [articles/supply-chain/get-started/removed-deprecated-features-scm-updates.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/get-started/removed-deprecated-features-scm-updates.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @kamaybac
* Microsoft Alias: **kamaybac**

**Comment by CaptainCowell** [comment]
I concur. The situation for customers using Master planning with production scenarios is currently very confusing and unclear - both in Microsoft's documents and in recent TechTalks, etc. - and leaves such customers unable to make any firm plans for testing and migration activities and timescales. Much more clarity is needed from Microsoft on this.

Regards,
Andrew Cowell

**Comment by kfend** [comment]
Bug 563719 created to track this.

**Comment by kfend** [comment]
The topic has been updated with updated date information.
