### ISSUE TITLE
Please add prerequisites

### ISSUE THREAD

**Issue by PeterKCinteros** [MicrosoftDocs/dynamics-365-unified-operations-public#3208]
After investigation we found out that the batch job "Process automation polling system job" must be running for the Process automation to work. It would be good if that is mentioned in the document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c450d3f-251f-d2cb-beac-aa299906a2f7
* Version Independent ID: ad04c997-13fc-6c0e-a44f-dbafe11c5197
* Content: [Process automation - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/process-automation)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/process-automation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/sysadmin/process-automation.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @RyanCCarlson2
* Microsoft Alias: **rcarlson**

**Comment by kfend** [comment]
Bug 563715 created to track this.
