### ISSUE TITLE
please update the release schedule

### ISSUE THREAD

**Issue by pfoolen** [MicrosoftDocs/dynamics-365-unified-operations-public#3211]
Hi,

We are plannig a go-live with 5 iterations. Therefor we need to know when updates are available after july.
Can you please update the release schedule so we can make a proper descision on when to adopt which update.

Kind Regards,
Pieter Foolen

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7dcb285-f32c-c92e-fe49-1617f213066b
* Version Independent ID: 8f28c1a0-9da5-f853-90ee-d82a4c32df7e
* Content: [Service update availability - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/public-preview-releases?toc=/dynamics365/commerce/toc.json#feedback)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/public-preview-releases.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/get-started/public-preview-releases.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @ShellyBakke
* Microsoft Alias: **smiller**

**Comment by kfend** [comment]
Bug 563716 created to track this.

**Comment by sericks007** [comment]
This content has been updated and will be published later today.
