### ISSUE TITLE
Documentation not updated with impact from Service Fabric migration

### ISSUE THREAD

**Issue by mpburtt** [MicrosoftDocs/dynamics-365-unified-operations-public#3213]
The LCS pages on diagnostic environment monitoring doesn't seem to have been updated following the loss of a number of features arising from the migration to service fabric. There's a number of features included that are no longer available and there's no information on what alternatives we have available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a59d9fd-8c46-120c-efb1-ef73b158ac33
* Version Independent ID: 6ec54ef7-cbbb-32f3-42c7-ac695d3b94bd
* Content: [Performance troubleshooting using tools in Lifecycle Services (LCS) - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/performancetroubleshooting)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/performancetroubleshooting.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/lifecycle-services/performancetroubleshooting.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by josaw1** [comment]
Hi, thank you for your feedback. BUG 9484337 created to track the issue.

**Comment by josaw1** [comment]
@laneswenka please review.

**Comment by josaw1** [comment]
Closed as won't fix.
