### ISSUE TITLE
Wrong link for CSS?

### ISSUE THREAD

**Issue by RobvanB** [MicrosoftDocs/dynamics-365-unified-operations-public#3214]
This snippet
Modify the module CSS to change any of a module's styling.

links to the same page as this (which is 2 lines above it):

CSS overrides are used to override any module's Cascading Style Sheets (CSS).

Not sure if that is intentional or if it is supposed to be a different link?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5256b323-4a21-b51b-26aa-dcb13832235f
* Version Independent ID: 5034bca0-a934-b9d4-0534-d1a5c48fe461
* Content: [Modules overview - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/e-commerce-extensibility/modules-overview)
* Content Source: [articles/commerce/e-commerce-extensibility/modules-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/e-commerce-extensibility/modules-overview.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @samjarawan
* Microsoft Alias: **samjar**

**Comment by josaw1** [comment]
The link was updated and the fix will go live today. Thanks!
