### ISSUE TITLE
Misunderstood Open/Closed principle

### ISSUE THREAD

**Issue by mcronqvist** [MicrosoftDocs/dynamics-365-unified-operations-public#3216]
Regarding the SOLID Open/Closed principle, you write that "Closed for modification" can be handled by code access modifiers. Thus, I think you have misunderstood this principle. Code access modifiers is merely a mechanism to provide the correct interface to the surrounding functionality and has nothing to do with this principle.

Closed for modification means that the functionality is finished/sealed in a way that you do not need to modify a class or method’s functionality to be able to extend it. This also falls back to the Single Responsibility principle. If the Single Responsibility principle is broken, most of the time the Open/Closed principle is also broken, as it will not be closed for modification. Thus, a method can be private, but still not closed for modification.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e838346-684b-e837-32be-97ec1db6adfb
* Version Independent ID: 7aa17e48-1021-53f3-f3ae-e6c0dbdc8184
* Content: [Write extensible code - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/extensibility/writing-extensible-code)
* Content Source: [articles/fin-ops-core/dev-itpro/extensibility/writing-extensible-code.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/extensibility/writing-extensible-code.md)
* Service: **dynamics-365-crossapp**
* Product: ****
* Technology: ****
* GitHub Login: @MichaelFruergaardPontoppidan
* Microsoft Alias: **mfp**

**Comment by MichaelFruergaardPontoppidan** [comment]
Thank you for the feedback.

As you can see here, there are several interpretations of this principle:  Open–closed principle - Wikipedia<https://en.wikipedia.org/wiki/Open%E2%80%93closed_principle>

I’d be interested in learning more, can you point to some material explaining cases where a private method is considered not-closed for modification? As I see it, only the code author/owner can modify a private method, and as such that is not an extension scenario.


Thank you,

[Microsoft Logo]
Michael Fruergaard Pontoppidan
Principal Group Engineering Manager
Dynamics 365 SCM Warehouse Team
Mobile: +45 29 22 95 62
***@***.*** ***@***.***>
***@***.***D714F6.B7512DE0]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdk.linkedin.com%2Fin%2Fmichael-pontoppidan-a0ab691&data=02%7C01%7Cmfp%40microsoft.com%7Cddc58ebd6e854139900808d808a4b5f4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637268850819114464&sdata=PbEJeHx0fH634tjzs70KRl6pv21kzbvQgb8im6uVvSc%3D&reserved=0>  ***@***.***D714F6.B7512DE0] <https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcommunity.dynamics.com%2F365%2Ffinanceandoperations%2Fb%2Fmfp&data=02%7C01%7Cmfp%40microsoft.com%7Cddc58ebd6e854139900808d808a4b5f4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637268850819114464&sdata=PY125yTD4zOgbECpL%2BCzMj3aMiRGQ9WiJRFxtzA2BIk%3D&reserved=0>




From: mcronqvist ***@***.***>
Sent: Tuesday, 9 March 2021 14.47
To: MicrosoftDocs/dynamics-365-unified-operations-public ***@***.***>
Cc: Michael Fruergaard Pontoppidan ***@***.***>; Mention ***@***.***>
Subject: [MicrosoftDocs/dynamics-365-unified-operations-public] Misunderstood Open/Closed principle (#3216)


Regarding the SOLID Open/Closed principle, you write that "Closed for modification" can be handled by code access modifiers. Thus, I think you have misunderstood this principle. Code access modifiers is merely a mechanism to provide the correct interface to the surrounding functionality and has nothing to do with this principle.

Closed for modification means that the functionality is finished/sealed in a way that you do not need to modify a class or method’s functionality to be able to extend it. This also falls back to the Single Responsibility principle. If the Single Responsibility principle is broken, most of the time the Open/Closed principle is also broken, as it will not be closed for modification. Thus, a method can be private, but still not closed for modification.

________________________________
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

  *   ID: 7e838346-684b-e837-32be-97ec1db6adfb
  *   Version Independent ID: 7aa17e48-1021-53f3-f3ae-e6c0dbdc8184
  *   Content: Write extensible code - Finance & Operations | Dynamics 365<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fdynamics365%2Ffin-ops-core%2Fdev-itpro%2Fextensibility%2Fwriting-extensible-code&data=04%7C01%7Cmfp%40microsoft.com%7Cae1ff47d74f140b6d4e708d8e301dfea%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637508944499249902%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=SP2eP1nM2uZP8ORthexRD8BQKLSpniUEfpPCkkBWl%2BQ%3D&reserved=0>
  *   Content Source: articles/fin-ops-core/dev-itpro/extensibility/writing-extensible-code.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FDynamics-365-Unified-Operations-Public%2Fblob%2Flive%2Farticles%2Ffin-ops-core%2Fdev-itpro%2Fextensibility%2Fwriting-extensible-code.md&data=04%7C01%7Cmfp%40microsoft.com%7Cae1ff47d74f140b6d4e708d8e301dfea%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637508944499259895%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3v5OabWHcxfMVKTPyOveGolJG7da%2F87Xj3HUkOOdT9Y%3D&reserved=0>
  *   Service: dynamics-365-crossapp
  *   Product: ****
  *   Technology: ****
  *   GitHub Login: @MichaelFruergaardPontoppidan<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMichaelFruergaardPontoppidan&data=04%7C01%7Cmfp%40microsoft.com%7Cae1ff47d74f140b6d4e708d8e301dfea%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637508944499259895%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=GmsmYY%2F1nrRCv6NY%2B%2FwvMGkQSNS9DXp2EkP9CEh6U9Q%3D&reserved=0>
  *   Microsoft Alias: mfp

**Comment by mcronqvist** [comment]
Yeah, I see it can be interpreted that way. Generally, the Open/Closed principle is the most difficult SOLID principle to comprehend. Thus, I think people have been looking for another way to define this principle, to have a simpler, more understandable principle. And I can understand why. This principle is always up for discussion in specific scenarios.

As I understand the principle, it is all about the functionality. So, what this principle say is, we should be able to add new functionality without touching the existing code (functionality) for the class. This is because whenever we modify the existing code, we are taking the risk of creating potential bugs. So, we should avoid touching the tested and reliable code if possible.

Code access modifiers is some of the “tools” you use when making solid design patterns, but it is, in my opinion, not what defines the Open/Closed principle.  

The below example illustrates it. 

![image](https://user-images.githubusercontent.com/80334001/110597641-1e0f1000-8181-11eb-83a8-8281754f836a.png)

If I were to extend “Screen”, which can only have black or white background, with a “ColoredScreen”, I would have to modify “Screen”. Because we have a method “Print”, that contains a condition and a call to another private method, we would have to modify that method and even worse maybe restructuring part of the class. We are not able to extend Screen if we just set the Print method to protected, since we would also have to come up with our own implementation of the PrintText method, easily violation the Liskov principle. 

Thus, the Screen class violates OCP, since it is not Closed for modification. We must modify the Screen class to be able to extend it. And this is the main definition for OCP. Notice that the Print method also violates SRP. This is a common scenario. If something violates SRP it is typically also violating OCP as it will not be closed for modification.

A solution could be to have a Screen interface or abstract class which dictates that implementations must be responsible for setting their background color.

I hope I made my point and I reckon that there may be several interpretations of the Open/Closed principle 😊

I am sure you will find a lot of AX class with private methods that violates OCP 😉

**Comment by mcronqvist** [comment]
The Open/Closed principle is one principle and, in my opinion, must be explained like that. You cannot have a class that is open for extension, but not closed for modification and vice versa. So, when people try to explain this principle by segregating the Open from the Closed subprinciple, that is when it gets complicated to understand and easy to misinterpret.

Again, this is of course my opinion and people may see it otherwise, but I am glad we had this little chat. There is nothing like a good profession debate regarding OOP principles 😊
