### ISSUE TITLE
The image displayed in the article make Cx confused 

### ISSUE THREAD

**Issue by lilachh** [MicrosoftDocs/dynamics-365-unified-operations-public#3218]
Hi sir / madam,

The image make Cx assumed that this was configurable for bidirectional interaction
![image](https://user-images.githubusercontent.com/19548576/110606069-ca261a80-81c4-11eb-940c-d599add878d4.png)

but below state :
Product receipts (purchase order receipts in Dataverse) are managed by Supply Chain Management and can't be created from Dataverse if Supply Chain Management is installed. The product receipts from Supply Chain Management are synced from Supply Chain Management to Dataverse.

if I understand correct the Dual-Write mapping type for PO receipts with One-Way sync from FinOps to CE.

so could you please correct the illustration to avoid reader misunderstanding?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5034c9f1-31bf-9649-f8f8-af7cca2da37e
* Version Independent ID: ecd0db96-4b9a-7d65-986c-523fa42f6ce0
* Content: [Integrate procurement between Supply Chain Management and Field Service - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/scm-field-service-procurement#supported-scenarios)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/scm-field-service-procurement.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/dual-write/scm-field-service-procurement.md)
* Service: **dynamics-365-crossapp**
* Product: ****
* Technology: ****
* GitHub Login: @RichardLuan
* Microsoft Alias: **riluan**

**Comment by josaw1** [comment]
Thanks for your feedback. @RichardLuan can you please review this comment?

**Comment by josaw1** [comment]
@kamaybac can you please assign this issue to the correct person? Thanks.

**Comment by josaw1** [comment]
BUG 564237 creted to track this.

**Comment by kamaybac** [comment]
I was contacted about this issue by email last week and have fixed it already. I'll close the bug too.
