### ISSUE TITLE
This how to guide is obsolete, it uses Over layering and not creating an Extension. 

### ISSUE THREAD

**Issue by Bijan-Ghofranian** [MicrosoftDocs/dynamics-365-unified-operations-public#3220]
There is a major shortcoming in D365 F&O related to missing Financial dimensions when opening GL journal lines in Excel. Users want to be ale to enter journal lines including entering Financial Dimensions and saving it back to AX.
The how to article below was written in 2017 when over layering was still permitted i.e. adding a static method to DimensionCombinationEntity.  The issue is these instructions are now wrong since over-layering in not allowed.
So, will you update the document and the code using Extensions?  Do we have to do anything other than converting this code to Extension?  Will we be able to update the Financial dimensions in Excel and publish back to AX?

Thank you,
Bijan Ghofranian
 
https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/financial/dimensions-overview

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b6af178-e094-74c1-c692-497b88dd7f1f
* Version Independent ID: 23ca232c-73e0-a88c-0b4a-5931fc7f945a
* Content: [Add dimensions to Excel templates - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/financial/dimensions-overview)
* Content Source: [articles/fin-ops-core/dev-itpro/financial/dimensions-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/financial/dimensions-overview.md)
* Service: **dynamics-365-crossapp**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **rbrow**

**Comment by josaw1** [comment]
Thank you for your feedback. @RobinARH can you please take a look?

**Comment by Bijan-Ghofranian** [comment]
I found the solution. The over layering code is not required. No need to convert that to extension. Just take it out and it works.
