### ISSUE TITLE
Unable to "Open RSAT from your desktop"

### ISSUE THREAD

**Issue by krettig** [MicrosoftDocs/dynamics-365-unified-operations-public#3221]
[Enter feedback here]
Under "Configuration", the first step is "Open RSAT from your desktop."

When I double-click the shortcut on the desktop, I get a Windows 10 pop-up asking me what application should handle the VBS file.  Need to add instructions on this page of what the user is supposed to do

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2458b41-99e9-53ff-b898-cdd957c1c924
* Version Independent ID: 9aad0fcb-b367-136a-9fb0-d8d04a2cfc33
* Content: [Regression suite automation tool installation and configuration - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/perf-test/rsat/rsat-install-configure)
* Content Source: [articles/fin-ops-core/dev-itpro/perf-test/rsat/rsat-install-configure.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/perf-test/rsat/rsat-install-configure.md)
* Service: **dynamics-365-crossapp**
* Product: ****
* Technology: ****
* GitHub Login: @robadawy
* Microsoft Alias: **robadawy**

**Comment by josaw1** [comment]
Thanks for your feedback. @sericks007 can you please assign to the correct person?

**Comment by FrankDahl** [comment]
This message is not what users normally will experience. I presume this may occur if the user is restricted on the machine. Currently RSAT does not support restricted used that do not have access for running VBS scripts. With RSAT version 2.2 we will introduce an option to configure the machine to allow users that are do not have full access to run RSAT, this remove the need for running VBS scripts. Please hold for an update on this to be published in the next few weeks.
