### ISSUE TITLE
Referenced methods are obsolete.

### ISSUE THREAD

**Issue by d3fr0g** [MicrosoftDocs/dynamics-365-unified-operations-public#3222]
SysDaInsertStatement.executeQuery is marked as obsolete. There might be other methods in the SysDa fw that are also marked as such.

The documentation would use some update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2888e11c-17de-f90c-a48e-409baee04833
* Version Independent ID: b6f71c61-469e-46d8-9a7f-7cc5da547850
* Content: [Access data by using the SysDa classes - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-ref/sysda)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-ref/sysda.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-ref/sysda.md)
* Service: **dynamics-365-crossapp**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **rhaertle**

**Comment by josaw1** [comment]
Thank you for your feedback. @RobinARH can you please take a look?

**Comment by josaw1** [comment]
BUG 564238 created to track the issue.

**Comment by josaw1** [comment]
@twheeloc please review and update.

**Comment by twheeloc** [comment]
@jasongre, would you please review and update as needed?

**Comment by josaw1** [comment]
Closed as won't fix.
