### ISSUE TITLE
One-voucher article does not consider localization needs for Norway

### ISSUE THREAD

**Issue by Eshaghzadeha** [MicrosoftDocs/dynamics-365-unified-operations-public#3223]
There are several business routines that are important with the use of one-voucher in Norway:

1-Payments in / out
We sum up deposits and payments per. file received as the number of payments is many and the amount must correspond to the amounts the bank delivers on bank statements. As an example a customer which has thousands of payments per. day and many hundreds of payments per. day.

2-One-voucher prevents posting of vouchers such as incoming invoice against several postings. One voucher does provide the opportunity to split an posting of incoming invoices on several project categories or several projects, several fixed assets, etc. This happens quite often with our customers per. Today.

3-Some customers used One-Voucher on the old ERP solution that they had and the ERP solution that they have right now. Example that is common in the shipping industry: the need to post to both customer and supplier on the same document: D customer, K supplier, K finance.

4-Accruals and periodic journal are common routines done with One-Voucher

5-Customers which have moved from AX2009 and AX2012 to D365FO, They still use One-Voucher according to their business routines.

6-Several integrations are built up according to One-Voucher as the request of customers. For example. Incoming invoice approval. We use Arrival registration and invoice approval journal in D365FO where we in the approval journal differentiate costs against several financial accounts, financial account per financial dimensions, projects or project categories 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30b6b8f5-d1d2-f29f-3dcb-dd9c7cc80c7a
* Version Independent ID: c4176052-4b46-b7a9-2901-8b94572e97c8
* Content: [One voucher - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/general-ledger/one-voucher)
* Content Source: [articles/finance/general-ledger/one-voucher.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/general-ledger/one-voucher.md)
* Service: **dynamics-ax-applications**
* Product: Dynamics 365 Finance & Operations
* Technology: ****
* GitHub Login: @kweekley
* Microsoft Alias: **kweekley**

**Comment by kamaybac** [comment]
@Eshaghzadeha , thank you for your detailed input. I am passing it on for consideration.

**Comment by Eshaghzadeha** [comment]
Regarding point 2, This should/must be taken into consideration that companies using Project Management & Accounting must be able to split the invoice amount into several projects. One cannot expect the vendor to split invoices pr. project that are supposed to "share" the invoice amount. They have not necessarily the knowledge of how their customer will do the accounting. This is also a relevant scenario on Fixed Assets. Example is an invoice regarding 100 computers, where each and one of them are supposed to be separate assets. The ability to split vendor invoices must kept for several sub-ledgers

**Comment by kamaybac** [comment]
Bug 568853 created for this issue.

**Comment by Eshaghzadeha** [comment]
Hi @kamaybac , Just let me know you need more clarification for this issue.

**Comment by kamaybac** [comment]
@Eshaghzadeha , thank you for following up and offering more info. I created a bug for this issue, and it is currently under consideration. I passed on your offer for more clarification.

**Comment by kweekley** [comment]
Thank you for the feedback, which is really relevant to many customers outside of Norway also.  All of the scenarios you mentioned are on our radar for addressing with the One voucher issue.  The key to remember is that we aren't going to take away the functionality for these business requirements, but instead either:
1 - Allow the entry the same in the voucher, but with more data
2 - Provide a better, new solution for the business requirement so One voucher isn't necessary.

For example, scenario 2 is a very common requirement which is to allow 'lines' of the invoice to have multiple projects or assets.  The problem is that when this is entered through a general journal, we don't know the type of transaction being entered. The solution may be to add a 'Voucher type' which Dynamics 365 can use to determine the rules for the transaction. So if the Voucher type = Vendor invoice, you can only enter one Vendor in the voucher, but multiple assets, projects, ledger accounts, etc. 

We are still working through each business requirement to determine the best solution. And when we finally have a solution for each business requirement, then each customer can start to address changes to any integrations, which we know is not a quick change.  That is why this won't be deprecated for a while, allowing customers and ISVs to react.

**Comment by Eshaghzadeha** [comment]
Hi @kweekley 
Thanks for the feedback. I have tried to clarify customers' need based on how they do business specifically in Norway.
As an example. Customers need to use one-voucher on payment part and bank module since it will paves the way while they start reconciliation against the bank.
We have already a suggestion for this issue. I would be glad to help in this issue if needed so just let med know :) @kamaybac @kweekley

**Comment by Eshaghzadeha** [comment]
Hi @kamaybac  and @kweekley 

As a consequence of this issue, SAF-T report does not work properly. I have several issues that Microsoft resources take the One-Voucher article as a source that one-voucher is not allowed to use in D365FO and If it comes any fail based on this on SAF-T(NO) report will not be supported by Microsoft.
I mean that Microsoft can managed this report, SAF-T(NO), different based on its priority for the customer and we can have solution here.

N.b. SAF-T should be delivered by Norwegian companies to the Tax Administration (https://www.skatteetaten.no/en/business-and-organisation/start-and-run/rutiner-regnskap-og-kassasystem/saf-t-financial/)
Regards,
Alireza Eshaghzadeh
alireza.eshaghzadeh@cgi.com 
CGI

**Comment by Eshaghzadeha** [comment]
> There are several business routines that are important with the use of one-voucher in Norway:
> 
> 1-Payments in / out We sum up deposits and payments per. file received as the number of payments is many and the amount must correspond to the amounts the bank delivers on bank statements. As an example a customer which has thousands of payments per. day and many hundreds of payments per. day.
> 
> 2-One-voucher prevents posting of vouchers such as incoming invoice against several postings. One voucher does provide the opportunity to split an posting of incoming invoices on several project categories or several projects, several fixed assets, etc. This happens quite often with our customers per. Today.
> 
> 3-Some customers used One-Voucher on the old ERP solution that they had and the ERP solution that they have right now. Example that is common in the shipping industry: the need to post to both customer and supplier on the same document: D customer, K supplier, K finance.
> 
> 4-Accruals and periodic journal are common routines done with One-Voucher
> 
> 5-Customers which have moved from AX2009 and AX2012 to D365FO, They still use One-Voucher according to their business routines.
> 
> 6-Several integrations are built up according to One-Voucher as the request of customers. For example. Incoming invoice approval. We use Arrival registration and invoice approval journal in D365FO where we in the approval journal differentiate costs against several financial accounts, financial account per financial dimensions, projects or project categories
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 30b6b8f5-d1d2-f29f-3dcb-dd9c7cc80c7a
> * Version Independent ID: c4176052-4b46-b7a9-2901-8b94572e97c8
> * Content: [One voucher - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/general-ledger/one-voucher)
> * Content Source: [articles/finance/general-ledger/one-voucher.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/general-ledger/one-voucher.md)
> * Service: **dynamics-ax-applications**
> * Product: Dynamics 365 Finance & Operations
> * Technology: ****
> * GitHub Login: @kweekley
> * Microsoft Alias: **kweekley**

Correction for Point 2:
2-One-voucher prevents posting of vouchers such as incoming invoice against several postings. One voucher does **NOT** provide the opportunity to split an posting of incoming invoices on several project categories or several projects, several fixed assets, etc. This happens quite often with our customers per. Today.
