### ISSUE TITLE
Request to update docs about Self-service Production PITR

### ISSUE THREAD

**Issue by zhenfangyan** [MicrosoftDocs/dynamics-365-unified-operations-public#3224]
There is PITR PROD to PROD feature available for Self-service environment, however this is no mentioned in the docs. 

Further, in another doc. It still ask customer to submit a PIRT SR for it. 
https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/database-point-in-time-restore
![image](https://user-images.githubusercontent.com/18294106/111109099-08d91d80-8595-11eb-8e6f-7e821f264dc3.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 805f3739-0cad-d6ab-7db0-175c972f189f
* Version Independent ID: 68be2d28-d5e9-471d-8648-a8cbae2e1e7d
* Content: [Database point-in-time restore (PITR) - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/database-point-in-time-restore)
* Content Source: [articles/fin-ops-core/dev-itpro/database/database-point-in-time-restore.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/database/database-point-in-time-restore.md)
* Service: **dynamics-365-crossapp**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by kamaybac** [comment]
@zhenfangyan , thank you for bringing this issue to our attention. I am passing it on for consideration.

**Comment by kamaybac** [comment]
Bug 568878 raised to address this issue.

**Comment by laneswenka** [comment]
This was updated a while back, we can close this issue.

**Comment by kamaybac** [comment]
@laneswenka , thanks. Closing.
