### ISSUE TITLE
Wrong Currency in Example

### ISSUE THREAD

**Issue by elviscooper** [MicrosoftDocs/dynamics-365-unified-operations-public#3225]
In the example for revaluation on Jan 31st, it gives the New accounting currency amount as 
833.33 EUR (500 x 1.666667) but that amount should actually USD not EUR for the math to make sense

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a14ab42c-bbd3-d732-9106-477af7248391
* Version Independent ID: 5ab5197d-5aaf-7720-8610-af0b4ef0463b
* Content: [Foreign currency revaluation for General ledger - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/general-ledger/foreign-currency-revaluation-general-ledger)
* Content Source: [articles/finance/general-ledger/foreign-currency-revaluation-general-ledger.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/general-ledger/foreign-currency-revaluation-general-ledger.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @kweekley
* Microsoft Alias: **kweekley**

**Comment by kamaybac** [comment]
@elviscooper thank you for bringing this issue to our attention. It should be fixed soon.

**Comment by kamaybac** [comment]
@roschlom , this looks like a straightforward fix, so I'm assigning it directly to you.

**Comment by kamaybac** [comment]
Created bug 568879 to track this issue.

**Comment by roschlom** [comment]
Thanks for letting us know about the issue. It's been fixed and the updated topic will be visible later this evening (Monday, 29 March). Have a great day!

**Comment by elviscooper** [comment]
That's great! And thanks for keeping these docs updated. I work in
consulting and couldn't do my job without great resources like these!

Elvis
