### ISSUE TITLE
Technical reference report download page for 10.0.16

### ISSUE THREAD

**Issue by JOLSO** [MicrosoftDocs/dynamics-365-unified-operations-public#3226]
[https://docs.microsoft.com/en-us/dynamics/s-e/global/axtechrefrep_61 - do you have the download for 10.0.16? I see the latest download is for 10.0.13.  TIA!  Jackie Olson ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a857d13c-e3dc-2c43-c49f-3d94675ca768
* Version Independent ID: 7e5ad255-936d-fad8-8e44-f161ab94ef8d
* Content: [License codes and configuration keys report - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/license-codes-configuration-keys-report)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/license-codes-configuration-keys-report.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/sysadmin/license-codes-configuration-keys-report.md)
* Service: **dynamics-365-crossapp**
* Product: ****
* Technology: ****
* GitHub Login: @sericks007
* Microsoft Alias: **sericks**

**Comment by sericks007** [comment]
@JOLSO - Hi Jackie! Thanks for posting your question here.

@RobinARH, can you please respond?

**Comment by RobinARH** [comment]
We run these reports on the developer VHDs that are released twice a year. The next report will go out after the April release.

If you want to run the reports more often, the PowerShell scripts are on GitHub: https://github.com/microsoft/fin-ops-doc-scripts.

There’s a link to the GitHub repo on this page: https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/data-entities-report.

Thanks-
Robin
