### ISSUE TITLE
The 'Technical Reference Reports' link on this page may be incomplete (?)

### ISSUE THREAD

**Issue by CaptainCowell** [MicrosoftDocs/dynamics-365-unified-operations-public#3228]
The 'Technical Reference Reports' link on this page is:  https://docs.microsoft.com/en-us/dynamics/s-e/ 

I believe it should be as follows (?) :  https://docs.microsoft.com/en-us/dynamics/s-e/global/axtechrefrep_61 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04fb7618-b5ce-b783-04d6-5f97a80b77d1
* Version Independent ID: dfaaabf0-0413-ae6d-e2a2-7a67c48a7023
* Content: [API, class, and table resources - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-ref/api-reference)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-ref/api-reference.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-ref/api-reference.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **rhaertle**

**Comment by RobinARH** [comment]
This is fixed and will go live tonight. - Robin
