### ISSUE TITLE
regional settings for AXSERVICEUSER should not be changed

### ISSUE THREAD

**Issue by arnoldvanwageningen** [MicrosoftDocs/dynamics-365-unified-operations-public#3230]
Hi,

We sometimes see customers raising issues with Regional formatting in On-Premise environments. These mostly are issues with Decimal separators and perhaps date formats.
In Cloud environments this is not causing issues, since AXSERVICEUSER is not altered. But we see issues with On-Prem environments which are using AXSERVICEUSER with for example European regional settings.
System requirement for On-prem shows EN-US Windows server OS is required. This should default user account for AXSERVICEUSER to EN-US regional settings also. It seems this is sometimes changed by customers and partners.
Could you please add a note to this page that warns customers and partners from changing AXSERVICEUSER settings? 

Kindest regards,

Arnold

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90c38ada-6070-96ce-ff10-f910d5364b36
* Version Independent ID: dbcf436b-fecc-70bd-8e86-85c59e2a48df
* Content: [Set up and deploy on-premises environments (Platform update 12 and later) - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/setup-deploy-on-premises-pu12)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/setup-deploy-on-premises-pu12.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/deployment/setup-deploy-on-premises-pu12.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @PeterRFriis
* Microsoft Alias: **peterfriis**

**Comment by kamaybac** [comment]
@arnoldvanwageningen , thank you for bringing this issue to our attention. I am passing it on for consideration.

**Comment by PeterRFriis** [comment]
Hi @arnoldvanwageningen 
Thank you for bringing this to our attention. You are right that we have strict descriptions on the OS version to ensure the product runs correctly.
We will look into this and update the documentation based on the internal talks.
@cabeln, @faix  Bringing this to your attention.

We will update this bug.
Thank you.
Peter

**Comment by arnoldvanwageningen** [comment]
Thanks for your confirmation.

**Comment by kamaybac** [comment]
Bug 568882 created to track this issue.

**Comment by kamaybac** [comment]
@arnoldvanwageningen , thank you for bringing this issue to our attention. We have updated the documentation, and the update should go live later today.
