### ISSUE TITLE
"Use system pricing calculation" parameter has to be set to "No", instead of "Yes"

### ISSUE THREAD

**Issue by JulijaLudvigaELCA** [MicrosoftDocs/dynamics-365-unified-operations-public#3231]
1) It is stated in this article, that "Use system pricing calculation" parameter in D365 Sales has to be set to Yes. But actually "Price Quote"/"Price Order" functions do not work like that. For those functions to work the required value of this parameter is "No". 
And another tiny detail - there is a typo in the parameter name, in the text of the article it is called "Use system pri**z**ing calculation". 

2) In my scenario we didn't actually need to duplicate sales quotations created in D365 Sales to the D365 SCM, so initially I didn't enable those to maps. But without copying the data "Price Quote" function does not work. I didn't find it stated anywhere, that having data copied over is actually a mandatory prerequisite to get a price from the trade agreement (I could easily imagine a "Price Quote" functon which just finds a matching price using given parameters, without relying on the existing record in D365 SCM, and it was also my expectation, but apparently it is implemented differenty and existing records are required.)

Best regards,
Julija Ludviga

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc903201-84fc-ebac-9c31-78b0310f52ec
* Version Independent ID: 44c60119-d2c0-f1f6-77fa-47b3d98c1fea
* Content: [Prospect-to-cash in dual-write - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/dual-write-prospect-to-cash)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/dual-write-prospect-to-cash.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/dual-write/dual-write-prospect-to-cash.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @RamaKrishnamoorthy
* Microsoft Alias: **ramasri**

**Comment by kamaybac** [comment]
@JulijaLudvigaELCA , thank you for bringing this issue to our attention. I will forward it to the page author.

**Comment by kamaybac** [comment]
Created bug 568881 to track this issue.

**Comment by kamaybac** [comment]
@JulijaLudvigaELCA , We looked into this, and found that the parameter must be set to Yes. Otherwise the Totals don't get calculated on the quote/sales header unless the user presses the "Price Quote"/"Price Order" button.
