### ISSUE TITLE
Provisioning links are not working

### ISSUE THREAD

**Issue by jopankow** [MicrosoftDocs/dynamics-365-unified-operations-public#3232]
These two links in the "Get started with Lifecycle Services (LCS)" section do not work after the retirement of mbs.microsoft.com:

Provisioning guide on CustomerSource
https://go.microsoft.com/fwlink/?linkid=852080

Provisioning guide on PartnerSource
https://mbs.microsoft.com/partnersource/global/deployment/documentation/user-guides/D365Ops_OnPremEEProvisionGuide

Please correct the links to where these documents have been moved to.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebcc370e-5c3e-a7ed-bece-6d23bbc5e01b
* Version Independent ID: aef5c71b-ab31-a0d8-0eaf-c32e1b9aab9b
* Content: [Buy Finance + Operations (on-premises) - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/purchase-on-premises)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/purchase-on-premises.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/get-started/purchase-on-premises.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @maertenm
* Microsoft Alias: **sericks**

**Comment by kamaybac** [comment]
@jopankow , thank you for bringing this issue to our attention. I will forward it to the page author.

**Comment by sericks007** [comment]
@jopankow, thanks for making us aware of the issue!  A new link to the Provisioning Guide is provided in the updated article, which will be published later today.
