### ISSUE TITLE
Step 8 has incorrect information.  There is no "Code" folder

### ISSUE THREAD

**Issue by danielzook** [MicrosoftDocs/dynamics-365-unified-operations-public#3233]
Step 8 on this page begins with "Double-click the Code folder...".  There is no folder called "Code" in the project.
![image](https://user-images.githubusercontent.com/30128768/112147513-2c165500-8bb3-11eb-89d3-c3a5f60faab4.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1abc350-6abd-b03b-7a76-2022928271ae
* Version Independent ID: 52c4a7e4-f0e0-6c41-5bbd-5ad2efce752f
* Content: [Build and debug projects - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/build-debug-project)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/build-debug-project.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-tools/build-debug-project.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @pvillads
* Microsoft Alias: **pvillads**

**Comment by RobinARH** [comment]
Created bug 571647 to track this issue.

**Comment by pvillads** [comment]
Also: Note typo in FMRentailCheckoutProcessor
The solution file shown is huge! As far as I can surmise, the user should double click on Classes in this case.

**Comment by RobinARH** [comment]
Fixed. Should go live today. Thanks!
