### ISSUE TITLE
"Run to a breakpoint" Is missing a step

### ISSUE THREAD

**Issue by danielzook** [MicrosoftDocs/dynamics-365-unified-operations-public#3234]
Visual Studio can't run/debug the code unless a startup object is also selected.  The article does not include this step, but it should.

![image](https://user-images.githubusercontent.com/30128768/112151582-c6789780-8bb7-11eb-8328-372bc20f5079.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1abc350-6abd-b03b-7a76-2022928271ae
* Version Independent ID: 52c4a7e4-f0e0-6c41-5bbd-5ad2efce752f
* Content: [Build and debug projects - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/build-debug-project)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/build-debug-project.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-tools/build-debug-project.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @pvillads
* Microsoft Alias: **pvillads**

**Comment by RobinARH** [comment]
Created bug 571648 to track this issue.

**Comment by pvillads** [comment]
Agree. It should. At the same time as you set the startup project, you should set the startup item (form, menu item or class).
