### ISSUE TITLE
Article refers to Code Map, but that is not an option in the Dev box

### ISSUE THREAD

**Issue by danielzook** [MicrosoftDocs/dynamics-365-unified-operations-public#3235]
Code Map is only available in Visual Studio Enterprise:
See: https://docs.microsoft.com/en-us/visualstudio/debugger/map-methods-on-the-call-stack-while-debugging-in-visual-studio?view=vs-2019

The Dev box that is deployed by LCS only includes VS Professional.
Please remove the reference to "Code Map" on step 13 under "Add the validation code."

Might be good to have someone at Microsoft try the steps in this article themselves, using a dev box created from LCS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1abc350-6abd-b03b-7a76-2022928271ae
* Version Independent ID: 52c4a7e4-f0e0-6c41-5bbd-5ad2efce752f
* Content: [Build and debug projects - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/build-debug-project)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/build-debug-project.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-tools/build-debug-project.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @pvillads
* Microsoft Alias: **pvillads**

**Comment by RobinARH** [comment]
Created bug 571649 to track this issue.

**Comment by pvillads** [comment]
Agree, remove bullet 13

**Comment by RobinARH** [comment]
I updated to text to note that code maps are available in the Enterprise edition.

**Comment by pvillads** [comment]
Codemaps ae availabe for C#, but not or X++

**Comment by RobinARH** [comment]
I removed it.
