### ISSUE TITLE
Full Build Options listed in article doesn't match form

### ISSUE THREAD

**Issue by danielzook** [MicrosoftDocs/dynamics-365-unified-operations-public#3236]
The article mentions "Build Aggregate Measurements" in the "Build a model's package" section, paragraph 4, but there is no such option.

One option that exists but is missing from the article is the "Run app checks."

![image](https://user-images.githubusercontent.com/30128768/112174637-f1b9b180-8bcc-11eb-8814-3628f46cf577.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 100aa46c-bf78-3cf6-489e-7b5958e9c82d
* Version Independent ID: ede10385-deba-5de6-cf88-1160ce7ecc22
* Content: [Build operations - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/build-operations)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/build-operations.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-tools/build-operations.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **jorisde**

**Comment by RobinARH** [comment]
Created bug 571650 to track this issue.

**Comment by RobinARH** [comment]
We'll catch these as we do screenshot updates. For now, we'll leave the doc as is. Thanks.
