### ISSUE TITLE
There is no "Dynamics 365 window"

### ISSUE THREAD

**Issue by danielzook** [MicrosoftDocs/dynamics-365-unified-operations-public#3237]
Step 2 in the "Create the Fleet Management tutorial model" section begins: "From the Dynamics 365 window..."

There is no "Dynamics 365 window."  I think you meant the **Dynamics 365 Menu**
![image](https://user-images.githubusercontent.com/30128768/112175930-09de0080-8bce-11eb-8e81-520477b8fff7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71438101-e8d0-6636-a397-64b039c85a39
* Version Independent ID: 9db6265c-437c-75d2-be92-131273a8ca56
* Content: [Create models and data model elements overview - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/create-data-model-elements)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/create-data-model-elements.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-tools/create-data-model-elements.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **jorisde**

**Comment by RobinARH** [comment]
Fixed. Should go live tonight.
