### ISSUE TITLE
There is no longer a "UnifiedOPerations" template

### ISSUE THREAD

**Issue by danielzook** [MicrosoftDocs/dynamics-365-unified-operations-public#3238]
Step 11 in section "Create the Fleet Management tutorial model" states "Select the Unified Operations template."  This name no longer exists.

![image](https://user-images.githubusercontent.com/30128768/112176675-aef8d900-8bce-11eb-847f-3aea02e67a8b.png)

I'm assuming the author meant the "Finance Operations" template.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71438101-e8d0-6636-a397-64b039c85a39
* Version Independent ID: 9db6265c-437c-75d2-be92-131273a8ca56
* Content: [Create models and data model elements overview - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/create-data-model-elements)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/create-data-model-elements.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-tools/create-data-model-elements.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **jorisde**

**Comment by RobinARH** [comment]
Created bug 571652 to track this issue.

**Comment by RobinARH** [comment]
We'll catch these as we do branding updates. For now, we'll leave it as is.
