### ISSUE TITLE
The steps in "Map Azure DevOps to your development box" are out of date

### ISSUE THREAD

**Issue by danielzook** [MicrosoftDocs/dynamics-365-unified-operations-public#3240]
The article refers to steps that no longer match the version of Visual Studio that comes with the Dev one-box.
![image](https://user-images.githubusercontent.com/30128768/112202666-02c3ec00-8be8-11eb-8314-e6b65ce8dd3c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e5b845d-9cd2-358d-3de9-bd15652ea746
* Version Independent ID: e52c5205-60de-4acf-2d21-ea0df760a49f
* Content: [Configure the Azure DevOps mapping during code migration - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/configure-vso-solution#key-concepts)
* Content Source: [articles/fin-ops-core/dev-itpro/migration-upgrade/configure-vso-solution.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/migration-upgrade/configure-vso-solution.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **jorisde**

**Comment by RobinARH** [comment]
Created bug 571654 to track this issue.

**Comment by tonyafehr** [comment]
This topic will be updated with new content later today. Thanks!
