### ISSUE TITLE
Missing some details on what the DOM run changes on the order line

### ISSUE THREAD

**Issue by danielzook** [MicrosoftDocs/dynamics-365-unified-operations-public#3241]
The section "Results of DOM runs" lists some information on the results from the run, but it doesn't specify exactly what the DOM run changes on an order line that forces the system to ship from an alternate location.

For example, does the DOM run change the site/warehouse on the sales line?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b89b3109-e935-4ba8-db24-a7f553eec599
* Version Independent ID: e50c0b90-9348-3f1c-02da-362af63e683f
* Content: [Distributed order management (DOM) - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dom)
* Content Source: [articles/commerce/dom.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/dom.md)
* Service: **dynamics-365-commerce **
* Product: ****
* Technology: ****
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by RobinARH** [comment]
@josaw1 - Can you take a look? Thanks.

**Comment by josaw1** [comment]
@anpurush please take a look.

**Comment by RobinARH** [comment]
Created bug 572045 to track this issue.
