### ISSUE TITLE
Update SSRS Documentation Extensibility Page to encompass adding custom data sets

### ISSUE THREAD

**Issue by alaskancode** [MicrosoftDocs/dynamics-365-unified-operations-public#3242]
Microsoft's own documentation on the extensibility of SSRS reports lays out 4 scenarios where someone might want to extend an SSRS report.

https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/customize-app-suite-reports-with-extensions?toc=/dynamics365/commerce/toc.json

*Expand an existing data set attached to a current SSRS report
*Extend report menu items to redirect users to new reports
*Customize the design of an existing SSRS report
***Add new, custom data sets to an existing SSRS report**

Microsoft documented the first three scenarios. The final scenario (bold above), which is arguably the most complex, because it potentially involves extending both the data provider class and the data contract classes, was left completely unexplained. This stub of text is the complete documentation of that scenario by Microsoft:

Composing custom datasets – Add more data to application reports by extending an existing RDP class to return a custom dataset.
[The page in question can be found here](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/customize-app-suite-reports-with-extensions?toc=/dynamics365/commerce/toc.json)

This is totally unacceptable from a documentation perspective. This area of D365 is, in my opinion, already overly complex with regard to pulling in additional data, designs and menus. It does not help when Microsoft does not document their own stuff. Someone on the D365 team, please get someone on this.

Thank you,
Jonathan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96d7d2cb-d661-2153-51a2-70193d80e7aa
* Version Independent ID: f48e2cf4-e3fd-4a6e-7080-2e468a8d68bd
* Content: [Customize App Suite reports by using extensions - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/customize-app-suite-reports-with-extensions?toc=/dynamics365/commerce/toc.json)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/customize-app-suite-reports-with-extensions.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/customize-app-suite-reports-with-extensions.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by RobinARH** [comment]
@TJVass - Can you take a look? Thanks.

**Comment by alaskancode** [comment]
Ok I gotta ask. @TJVass - are you related: https://www.seattletimes.com/seattle-news/tj-vassar-pioneering-african-american-educator/?

**Comment by RobinARH** [comment]
@RichdiMSFT - Can you take a look? Thanks.

**Comment by RichdiMSFT** [comment]
@alaskancode Thanks for pointing out the issue. We will review the article and see if we can add the requested topic. This may take some time.

**Comment by RobinARH** [comment]
Created bug 572044 to track this issue.
