### ISSUE TITLE
F&O - OData: Contains OData example format is wrong

### ISSUE THREAD

**Issue by Bhawk90** [MicrosoftDocs/dynamics-365-unified-operations-public#3243]
Example for Contains OData call is defined wrong in section **OData Services/Filter Details**.

`http://host/service/EntitySet?$filter=StringField eq '\*retail\*'`
should be 
`http://host/service/EntitySet?$filter=StringField eq '*retail*'`

The asterisk character shouldn't be escaped in the query string.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d7c8b45-1531-ebbf-d417-4e1fe5bf4f1b
* Version Independent ID: c543a5fc-90c9-9edb-11d7-6d6d0f2c10a9
* Content: [Open Data Protocol (OData) - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/odata#querying-or-browsing-an-odata-endpoint)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/odata.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/data-entities/odata.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by RobinARH** [comment]
@Sunil-Garg - Can you take a look? Thanks.

**Comment by RobinARH** [comment]
Created bug 572048 to track this issue.
