### ISSUE TITLE
Enable access does expire

### ISSUE THREAD

**Issue by steevegilbert** [MicrosoftDocs/dynamics-365-unified-operations-public#3244]
The doc says that the entry will not expire but in the UI there is a expiration date.

![image](https://user-images.githubusercontent.com/2894655/112536998-887c9e80-8d84-11eb-9417-00e7e973e484.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e01673a-0cf0-b6bd-2a93-efb0427f8d3e
* Version Independent ID: 52f65831-75b9-5ffd-2c2f-0582f7cca2a6
* Content: [Enable just-in-time database access - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/database-just-in-time-jit-access)
* Content Source: [articles/fin-ops-core/dev-itpro/database/database-just-in-time-JIT-access.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/database/database-just-in-time-JIT-access.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by RobinARH** [comment]
@laneswenka - Can you take a look? Thanks.

**Comment by RobinARH** [comment]
Created bug 572049 to track this issue.

**Comment by laneswenka** [comment]
Updated, this will go out in the next scheduled docs publish wave.
