### ISSUE TITLE
 The budget register entry line now will default to expense when the main account type is expense; will default to revenue when the main account type is expense; and will default to expense for all other account types.

### ISSUE THREAD

**Issue by kvictoriano** [MicrosoftDocs/dynamics-365-unified-operations-public#3245]
Would like to clarify if this is correct? Shouldn't it be defaulted to Revenue if the main account type is Revenue?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01a25607-253f-46d7-1557-8eab56aff7b9
* Version Independent ID: 1eeb5aba-abb3-0967-4990-0b098269b091
* Content: [Budgeting overview - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/budgeting/basic-budgeting-overview-configuration)
* Content Source: [articles/finance/budgeting/basic-budgeting-overview-configuration.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/budgeting/basic-budgeting-overview-configuration.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @ShylaThompson
* Microsoft Alias: **sigitac**

**Comment by kvictoriano** [comment]
![image](https://user-images.githubusercontent.com/76980168/112775906-c45b8080-9070-11eb-8b07-29ac49135285.png)

**Comment by sericks007** [comment]
@kvictoriano, thank you for posting this feedback.

@roschlom, please update the metadata and assign to the appropriate PM.

**Comment by sericks007** [comment]
Bug 573218 has been logged to track this issue.

**Comment by roschlom** [comment]
Thanks again for the input. This has been corrected now.
