### ISSUE TITLE
TypeScript 2.2.2

### ISSUE THREAD

**Issue by rabol** [MicrosoftDocs/dynamics-365-unified-operations-public#3246]
[Enter feedback here]
On the page it say that one need to use typescript 2.2.2, but that is impossible to download, are sure that is is TypeScript 2.2.2 and not typeScript 3.2.2 ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 776f646a-f316-8c84-d190-57ecd88547a0
* Version Independent ID: 80208288-e39f-bacc-c8ad-7c51470e9cce
* Content: [Migrate the Retail SDK from Visual Studio 2015 to Visual Studio 2017 - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/retail-sdk/migrate-sdk)
* Content Source: [articles/commerce/dev-itpro/retail-sdk/migrate-sdk.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/dev-itpro/retail-sdk/migrate-sdk.md)
* Service: **dynamics-365-commerce **
* Product: ****
* Technology: ****
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by sericks007** [comment]
@rabol, thank you for posting this feedback!

@mugunthanm, please review and update the content, as needed.

**Comment by mugunthanm** [comment]
As mentioned in the document, you can install Typescript version 2.2 from Visual Studio. 
Open Visual Studio, go to Tools > Get Tools and Features. Select the Individual components tab and select the TypeScript 2.2 SDK from SDKs, libraries, and frameworks section and install it.
