### ISSUE TITLE
Fist Issue Topic

### ISSUE THREAD

**Issue by sigitsup1771** [MicrosoftDocs/dynamics-365-unified-operations-public#3247]
on the capture screen on First Issue Topic below , "The following illustration shows an example for coverage code Period."
I think for fullfill minmum is Fisrt Issue not todays date
![Safety Stock Replenishment](https://user-images.githubusercontent.com/72779964/112915040-abfa6d00-9127-11eb-978a-c434d03ad2db.jpg)

sigit.suprayitno@intikom.co.id

https://docs.microsoft.com/en-us/dynamics365/supply-chain/master-planning/safety-stock-replenishment
--

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08f6ecb2-3b60-ec64-f1ae-66fe973dfb14
* Version Independent ID: bf15ecc2-7f3c-eaff-f872-77c19d83130d
* Content: [Safety stock fulfillment for items - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/master-planning/safety-stock-replenishment)
* Content Source: [articles/supply-chain/master-planning/safety-stock-replenishment.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/master-planning/safety-stock-replenishment.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @roxanadiaconu
* Microsoft Alias: **kamaybac**

**Comment by sericks007** [comment]
Bug 573221 has been logged to track this issue.

**Comment by sericks007** [comment]
This issue will be fixed with [PR 10920](https://github.com/MicrosoftDocs/Dynamics-365-Operations/pull/10920)/
