### ISSUE TITLE
dynamics 365 updates

### ISSUE THREAD

**Issue by jansenrf** [MicrosoftDocs/dynamics-365-unified-operations-public#3249]
[Enter feedback here]
I can see that the updates are going to 10.0.20. 
What is the next step after 10.0.20. 
Is this the last one or are there coming more updates later this year?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7dcb285-f32c-c92e-fe49-1617f213066b
* Version Independent ID: 8f28c1a0-9da5-f853-90ee-d82a4c32df7e
* Content: [Service update availability - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/public-preview-releases)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/public-preview-releases.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/get-started/public-preview-releases.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @ShellyBakke
* Microsoft Alias: **smiller**

**Comment by sericks007** [comment]
@jansenrf, thank you for this feedback.

@ShellyBakke, please review and update the content.

**Comment by sericks007** [comment]
This content has been updated and will be published later today.
