### ISSUE TITLE
Table Sync error : msodbcsql17 cannot be found

### ISSUE THREAD

**Issue by manishmoothedath** [MicrosoftDocs/dynamics-365-unified-operations-public#325]
The description for Event ID 1 from source msodbcsql17 cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.
After Re-installing driver, Issue was fixed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b2b729d-d0a8-4957-99c5-23b301af585c
* Version Independent ID: 068600d8-3803-8a96-2b46-4c6605381741
* Content: [Troubleshoot package application issues - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/deployment/deployable-package-troubleshooting)
* Content Source: [articles/dev-itpro/deployment/deployable-package-troubleshooting.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/deployment/deployable-package-troubleshooting.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @manalidongre
* Microsoft Alias: **manado**

**Comment by kfend** [comment]
Thanks for letting us know. We are looking into this.
