### ISSUE TITLE
Unclear sections

### ISSUE THREAD

**Issue by vavd** [MicrosoftDocs/dynamics-365-unified-operations-public#3250]
The "Link to reports" section is seemed to be irrelevant to Dynamics 365 Finance.
The "Identify the report in a reporting tree" section refferences to the "Worksheet Link" cell which is not available in the reporting tree definition. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e634ffca-a4b9-9779-d755-289dfd1c1285
* Version Independent ID: 99ccf85d-fe75-4afe-da79-219613cc5bcb
* Content: [Reporting tree definitions in financial reports - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/financial-reporting-tree-definitions?toc=/dynamics365/finance/toc.json#link-toreports)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/financial-reporting-tree-definitions.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/financial-reporting-tree-definitions.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @ShylaThompson
* Microsoft Alias: **aolson**

**Comment by sericks007** [comment]
@vavd, thank you for providing this feedback!

@aprilolson, please review and update the content, as needed.

**Comment by sericks007** [comment]
@jinniew, please review and update the content, as needed.

**Comment by jinniew** [comment]
Updated and created PR https://github.com/MicrosoftDocs/Dynamics-365-Operations/pull/10823. I took out references to features that were previously available in MR but not in FR.
