### ISSUE TITLE
Create an LCS connection in Azure Pipelines : Prerequisites

### ISSUE THREAD

**Issue by MZade** [MicrosoftDocs/dynamics-365-unified-operations-public#3252]
[Enter feedback here]
Related to:
https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/pipeline-lcs-connection#prerequisites

The Azure App registration should be configured to allow public client flows.
This can be done by:
    Under the Azure App Registration
    Authentication > Advanced settings > Allow public client flows > Set to YES

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3402c27-86a5-02f6-da5e-c49a614b2e67
* Version Independent ID: a574bc29-b33c-8eeb-ca04-983e6e08f7ea
* Content: [Create an LCS connection in Azure Pipelines - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/pipeline-lcs-connection#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/pipeline-lcs-connection.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-tools/pipeline-lcs-connection.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @jorisdg
* Microsoft Alias: **jorisde**

**Comment by sericks007** [comment]
@MZade, thanks for providing this feedback.

@jorisdg, please review and update the content, as needed.

**Comment by sericks007** [comment]
Bug 573226 has been logged to track this issue.
