### ISSUE TITLE
Needs an example on how to address the elements of the container

### ISSUE THREAD

**Issue by mpburtt** [MicrosoftDocs/dynamics-365-unified-operations-public#3253]
The SPLIT function page contains no information on how to address each element of the container returned. We knew that we needed to use SPLIT to get at the bits of data within a field that we needed but couldn't work out how to address the _n_th element of the container. After logging a support call, this led us to the INDEX function which does include examples expressly using the SPLIT function.

The SPLIT documentation seems to only tell us half the story. There really needs to be something that would take someone from there to using it in combination with INDEX.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d84b91f-9a99-c1bc-0d3b-930e6e98f3bc
* Version Independent ID: d0b5450e-8810-d8ad-886a-6aff35416069
* Content: [SPLIT ER function - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/er-functions-list-split?toc=/dynamics365/commerce/toc.json)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/er-functions-list-split.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/er-functions-list-split.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @NickSelin
* Microsoft Alias: **nselin**

**Comment by sericks007** [comment]
The content has been updated and will be published later today! Thanks!

**Comment by mpburtt** [comment]
Superb! Thanks.

Malcolm
