### ISSUE TITLE
Clarification / code change for doc page

### ISSUE THREAD

**Issue by RobvanB** [MicrosoftDocs/dynamics-365-unified-operations-public#3255]
Some feedback on this page:
The instructions call for creating an App Registration for the Retail Server, and one for the Client.
However, throughout the article I find it very confusing if the 'Server' or 'Client' App ID is referred to. I think it would be a lot clearer if any mention of an App ID would refer to the 'server registration' or the 'client registration'

Furthermore, the code examples need to be adjusted like this, otherwise they did not work for me:

In step 6, this line did not work:
Console.WriteLine(orderHistory.FirstOrDefault<SalesOrder>().Id);

There is no FirstOrDefault method?
I made it work like this:

 static void Main(string[] args)
        {
            GetConfiguration();
            Microsoft.Dynamics.Commerce.RetailProxy.PagedResult<SalesOrder> orderHistory = Task.Run(async() => await GetOrderHistory("2001")).Result;
            IEnumerator orderEnum = orderHistory.Results.GetEnumerator();

            while (orderEnum.MoveNext())
            {
                SalesOrder order = orderEnum.Current as SalesOrder;
                Console.WriteLine(order.SalesId);
            }
            
            Console.WriteLine("Press Enter");
            Console.ReadLine();
        }

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2aaab0fa-b1ac-51c0-2329-73ab077477b2
* Version Independent ID: dc8cf3fc-4c9f-731c-a99e-d70b8b940428
* Content: [Consume Retail Server APIs in external applications - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/consume-retail-server-api)
* Content Source: [articles/commerce/dev-itpro/consume-retail-server-api.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/dev-itpro/consume-retail-server-api.md)
* Service: **dynamics-365-commerce **
* Product: ****
* Technology: ****
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by sericks007** [comment]
@RobvanB, thank you for providing this feedback!

@mugunthanm, please review and update the content accordingly.

**Comment by sericks007** [comment]
Bug 573228 has been logged to track this issue.

**Comment by mugunthanm** [comment]
Thanks for the feedback, updated the document .
