### ISSUE TITLE
What is the alternative if BPM is being deprecated, need link and new direction

### ISSUE THREAD

**Issue by sing-ideas** [MicrosoftDocs/dynamics-365-unified-operations-public#3256]
Hi, 
If BPM is being deprecated, then there is no mention about the one being replaced.

Point us to the new alternative.

regards,
Singaravelu S

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd5ee7aa-fd2c-c53c-11d2-eeb9c8a1d31e
* Version Independent ID: 99feeea5-a8ec-c9d2-1084-9870e6b51fa8
* Content: [Removed or deprecated features in Lifecycle Services (LCS) - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/removed-deprecated-features#flowchart-diagrams-in-business-process-modeler)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/removed-deprecated-features.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/lifecycle-services/removed-deprecated-features.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @AngelMarshall
* Microsoft Alias: **tsmarsha**

**Comment by sericks007** [comment]
@sing-ideas, to clarify, BPM (meaning, the entire tool) is not deprecated.  Just the flowchart diagrams component of BPM is deprecated.
