### ISSUE TITLE
Missing step: Descriptor files need deleted as well

### ISSUE THREAD

**Issue by danielzook** [MicrosoftDocs/dynamics-365-unified-operations-public#3257]
In the list of steps after the paragraph that starts "If your model belongs to a package with multiple models....", there is a step missing.  After step 2, "delete the model folder", you also need to delete the file in the \Descriptor folder(s) that corresponds to the model.  If you don't, the models are not deleted.  Instead, the model folders are recreated when the models are reloaded in VS.

See https://community.dynamics.com/365/supply-chain-management/f/dynamics-365-supply-chain-management-forum/372041/removing-models-created-by-2012-d365-code-upgrade

Please have someone review your D365 documentation every time a major update is released.  Microsoft's documentation is usually the best, but in the case of D365 it is embarrassingly incomplete or out of date.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4415555b-d436-8e95-b68f-72a3104544bf
* Version Independent ID: 4d92f8ec-70fe-3651-e5a2-038438d24c2a
* Content: [Models and packages - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/models#deleting-a-model)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/models.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-tools/models.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @jorisdg
* Microsoft Alias: **jorisde**

**Comment by sericks007** [comment]
@danielzook, thanks for providing this feedback!

@jorisdg, please review and update the content, as needed.

**Comment by jorisdg** [comment]
Sent a PR to correct. This is not new or changed, this article was incorrect when it was first written.

**Comment by sericks007** [comment]
@jorisdg, Great, thanks so much!
