### ISSUE TITLE
GrantAzViewChangeTracking script name incorrect

### ISSUE THREAD

**Issue by Bigglesuk** [MicrosoftDocs/dynamics-365-unified-operations-public#3258]
There is a typo on the script location where it says GrantAzViewChangeTracking.zip it should actually be GrantAxViewChangeTracking.zip

Andrew
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fd6f761-42ef-48b4-7d33-59d90e6cf053
* Version Independent ID: 0fedd77b-c9dc-6cc8-1366-ccd52678d94c
* Content: [Reset the Financial reporting data mart - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/reset-financial-reporting-datamart-after-restore)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/reset-financial-reporting-datamart-after-restore.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/reset-financial-reporting-datamart-after-restore.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @aprilolson
* Microsoft Alias: **aolson**

**Comment by sericks007** [comment]
@Bigglesuk, thanks for letting us know about this!  I've fixed the typo -- the updated content will be published later today.  Thanks again!
