### ISSUE TITLE
Documentation  is outdated, please update the doc.

### ISSUE THREAD

**Issue by maverick21k** [MicrosoftDocs/dynamics-365-unified-operations-public#326]
I think the doc is outdated because.
1 .I wasnt able to use LINQ until and unless I added Microsoft.Dynamics.AX.Xpp.AxShared in references of DriverLicenseEvaluator
2. After adding DriverLicenseEvaluator reference in Fleet management (Also known as Fleet Management migrated project ) . I am getting warnings to add bindings . These warnings cannot be ignored as I cannot complete the build without addressing these warnings.
Pls refer to https://community.dynamics.com/365/financeandoperations/f/765/t/291834
for complete details of error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 292aba1a-611d-3c57-b6b3-4ad4c1f609c6
* Version Independent ID: a85180de-f264-3a6a-cd6c-51bb019cecac
* Content: [Write business logic by using C# and X++ source code - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-tools/write-business-logic)
* Content Source: [articles/dev-itpro/dev-tools/write-business-logic.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-tools/write-business-logic.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @pvillads
* Microsoft Alias: **pvillads**

**Comment by maverick21k** [comment]
It has been 14 days, any update on this would be really helpful.

**Comment by sericks007** [comment]
Bug 246523 has been logged to track this issue.
