### ISSUE TITLE
Missing Service

### ISSUE THREAD

**Issue by ItCommitsTheCode** [MicrosoftDocs/dynamics-365-unified-operations-public#3260]
The following services are not documented on this page:

EmployeeService
FormattingService
GiftCardService
LoyaltyService
NotificationService

Service documentation jumps the alphabet from "CustomerService" directly to "PricingService".

Please reconcile.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90cf28cb-e5aa-edc4-f379-a500f94574dc
* Version Independent ID: 535bb4de-13cc-1ab0-d6a4-01e1589e3cee
* Content: [Commerce runtime (CRT) services - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/crt-services)
* Content Source: [articles/commerce/dev-itpro/crt-services.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/crt-services.md)
* Service: **dynamics-365-commerce **
* Product: ****
* Technology: ****
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by sericks007** [comment]
@ItCommitsTheCode, thank you for providing this feedback!

@mugunthanm, please review and update the content, as needed.

**Comment by sericks007** [comment]
Bug 573230 has been logged to track this issue.

**Comment by sericks007** [comment]
The documentation has been updated.
