### ISSUE TITLE
Incorrect information re: Azure costs

### ISSUE THREAD

**Issue by danielzook** [MicrosoftDocs/dynamics-365-unified-operations-public#3261]
In the section: "Switch to the LCS implementation project"

...it states: "The Azure subscription that is associated with the project is managed by Microsoft. Therefore, there is no separate billing for Azure costs. The costs are covered by your subscription."  

This is incorrect.  Only the simple Sandbox environment and Production environment are included in the subscription.  All other Azure costs are billed separately and *not* included in the subscription (Dev environment(s), higher tier sandboxes, storage, etc.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4c106-c0e3-81ba-db99-1fcdaa5158dd
* Version Independent ID: 0f4a76f7-d071-e9ee-4271-866a4ae417f9
* Content: [Upgrade from AX 2012 to Finance and Operations - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/upgrade-overview-2012)
* Content Source: [articles/fin-ops-core/dev-itpro/migration-upgrade/upgrade-overview-2012.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/migration-upgrade/upgrade-overview-2012.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by tonyafehr** [comment]
@danielzook, thanks for the feedback. 
@laneswenka, please review.

**Comment by tonyafehr** [comment]
Bug 573547 logged to track this issue.

**Comment by laneswenka** [comment]
This has been updated, it will go out during the next scheduled publish wave.
