### ISSUE TITLE
Poll instead of pull

### ISSUE THREAD

**Issue by thedynamicsgirl** [MicrosoftDocs/dynamics-365-unified-operations-public#3262]
[status.
Manage scheduled data jobs
Submitting data to recurring data jobs
You can use integration REST endpoints to integrate with the client, submit documents (import), or **_poll_** available documents for download (export). These endpoints support OAuth.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01b2cd6b-f885-7461-fbdf-cf81f9e50d86
* Version Independent ID: 8df7a6ae-67db-5d29-fb6a-0820704ff3ef
* Content: [Recurring integrations - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/recurring-integrations)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/recurring-integrations.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/recurring-integrations.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by tonyafehr** [comment]
@thedynamicsgirl, thanks for the feedback. I'll update this right away.
