### ISSUE TITLE
Renamed DEV Box not working anymore ?

### ISSUE THREAD

**Issue by GeorgeSasDK** [MicrosoftDocs/dynamics-365-unified-operations-public#3263]
Until a few days ago ( as it was Easter we had no developers working) I have used this method to run several development machines.
Renamed them as ax7dev1 to ax7dev8 for example.
Beside the steps in this documentation I have also altered : 
- IIS to reflect the new name
- HOSTS file to point the ax7dev1 , 2 ...x to the local machine.
- Edited the C:\AOSService\webroot\wif.services.config to reflect the new name and new domain - 
reply="https://ax7dev8.cloud.onebox.dynamics.com/" requireHttps="true" />
    <cookieHandler requireSsl="true" domain="ax7dev8.cloud.onebox.dynamics.com" path="/" />
- Changed the Azurestorage emulator to point to the local machine.

EVERYTHING worked perfect until today when one of the developers tried to log on the web interface using his usual url : 
https://ax7dev8.cloud.onebox.dynamics.com/

After authentication he received the reply : 

**AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: '00000015-0000-0000-c000-000000000000'.**

Now developers can log on the web interface ONLY LOCALLY (log in via RDP)  on the dev machine and only with the default URL : 
https://usnconeboxax1aos.cloud.onebox.dynamics.com/

So, what changed and why can't I use the alternative names to log on the web interface of Dynamics from outside the box ?
Worked perfect until "today" .
I see the return URL in the Microsoft Dynamics ERP in Azure is not customizable as this is an MS application and not something we registered.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d830cc4d-4375-3d2a-65d2-5427d1e8acdd
* Version Independent ID: cab504a7-d2d4-8722-5dd1-71ff1c39d04e
* Content: [Rename a local development (VHD) environment - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/vso-machine-renaming)
* Content Source: [articles/fin-ops-core/dev-itpro/migration-upgrade/vso-machine-renaming.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/migration-upgrade/vso-machine-renaming.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @MargoC
* Microsoft Alias: **sericks**

**Comment by tonyafehr** [comment]
@GeorgeSasDK, thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

**Comment by GeorgeSasDK** [comment]
This is not a support request. This is a "bug" to your guide on renaming the development box, it does not work as per guidance.

**Comment by tonyafehr** [comment]
@sericks007, can you look into this issue and make updates, as appropriate. Thanks!

**Comment by sericks007** [comment]
@RobinARH, please assign this to the appropriate PM.

**Comment by jorisdg** [comment]
The VHD box URL has never been reachable outside the VHD without extensive changes to the VM configuration, which I don't believe is documented anywhere. As you pointed out, the reply URL for application '00000015-0000-0000-c000-000000000000' is not changeable of course, so a custom URL had never been possible unless you create your own application ID and update all the config files for the AOS (again, not documented or supported).

I understand you are manually updating IIS etc. which is not part of the steps. If this worked for you before that is very surprising to me but likely something on your end made that work and could be part of what is causing issues for you now.

We're not planning to document changing the AOS application ID officially as that would require supporting this scenario which we are not planning to do. However, many people to this successfully if you are willing to venture on that unsupported path yourself.

As far as I know, the document pointed to here still works as outlined.

**Comment by GeorgeSasDK** [comment]
Ok, so changing the box name does not imply changing also the URL of the application ?
How would a development team test on multiple boxes with same URL for the application ?

I have 12 developers working on 12  dev boxes and I also have a team of 20-50 people that need to test different apps and API's being developed  on this 12 boxes. 

How would the TEST team test different development apps on 12 dev boxes using same URL , as this TEST team is not allowed to log on the dev boxes , they just test code implementation phases  on the dev boxes before we push them out to Sandbox.

I am just curious how Microsoft envisioned this without changing the URL of the dev boxes.
