### ISSUE TITLE
Include a reference to Commerce Scale Unit deployable package when discussing Commerce in the context of all-in-one packaging

### ISSUE THREAD

**Issue by andreesteve** [MicrosoftDocs/dynamics-365-unified-operations-public#3264]
The section that says "If you currently use Microsoft Dynamics 365 Commerce functionality for the retail point of sale..." should be updated to include a link to package deployments to Commerce Scale Unit: https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/retail-sdk/retail-sdk-packaging#deploy-the-package-to-csu

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: feb1c10e-1287-6db3-5ed6-315cb76fc1cd
* Version Independent ID: 85966417-fa61-ffa8-22e3-fa2bfa0e50ff
* Content: [All-in-one deployable packages - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/aio-deployable-packages)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/aio-deployable-packages.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/dev-tools/aio-deployable-packages.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by tonyafehr** [comment]
@andreesteve, thanks for the feedback. @laneswenka, please make appropriate updates. Thanks!

**Comment by tonyafehr** [comment]
Bug 573553 logged to track this issue.

**Comment by laneswenka** [comment]
This has been updated, it will go out in the next scheduled publish wave.
