### ISSUE TITLE
GAB Setup Step

### ISSUE THREAD

**Issue by VenkiK** [MicrosoftDocs/dynamics-365-unified-operations-public#3267]
Hi Rama,

Adding a step to go to Dual Write in Finance & Operations and using Apply Solution "Dynamics 365 GAB Dual Write Entity Maps" solution would make things clearer for people who are new to Dual Write. 
https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/party-gab#setup-instructions

Thanks,
Venki

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28c9f029-f84b-7ae9-b0a0-257a1cb70683
* Version Independent ID: 7218e9bc-56df-da30-509e-1e9ac08ec6eb
* Content: [Party and global address book - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/party-gab)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/party-gab.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/dual-write/party-gab.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @RamaKrishnamoorthy
* Microsoft Alias: **ramasri**

**Comment by tonyafehr** [comment]
@VenkiK, thanks for the feedback. @RamaKrishnamoorthy, please review.

**Comment by tonyafehr** [comment]
The documentation will be updated shortly.
