### ISSUE TITLE
Page seems to be not up-to-date

### ISSUE THREAD

**Issue by Alpa-Chino** [MicrosoftDocs/dynamics-365-unified-operations-public#3268]
Hi!

I navigated to this page from the service update availability page where this page is referred and it seems that it is out of date, newer releases not yet included, KB numbers to release notes, VHD, released platform versions etc. Can you please update this?
In many cases in discussions with customers we are referring to the Microsoft documentations and if they are out of date, we need to explain the differences compared to the current cases.
Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6d8ca90-dfbd-3698-0def-a3be85e9c850
* Version Independent ID: b8d5a864-57fb-9fc3-f36a-77c5f5c58a54
* Content: [Software lifecycle policy and cloud releases - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/versions-update-policy)
* Content Source: [articles/fin-ops-core/dev-itpro/migration-upgrade/versions-update-policy.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/migration-upgrade/versions-update-policy.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @ShellyBakke
* Microsoft Alias: **smiller**

**Comment by tonyafehr** [comment]
@Alpa-Chino, thanks for the feedback. @ShellyBakke, please review.

**Comment by tonyafehr** [comment]
Bug 573579 created to track this issue.
