### ISSUE TITLE
Incorrect information re: customer's dev environment

### ISSUE THREAD

**Issue by danielzook** [MicrosoftDocs/dynamics-365-unified-operations-public#3269]
The section titled "Should I use a customer's dev environment?"
states: "All customer subscriptions come with at least one development VM."

This is incorrect.  Customer subscriptions only include two environments: Sandbox (UAT) and Production.  Customers are required to purchase an Azure subscription for any other environments.

See https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/cloud-deployment-overview#remote-desktop

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a61360d4-73b1-104e-dfd4-7584c485cd0d
* Version Independent ID: 1f7c0203-4b68-9df2-a33e-69a2cf2b3b90
* Content: [Development and continuous delivery FAQ - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/continuous-delivery-faq)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/continuous-delivery-faq.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/dev-tools/continuous-delivery-faq.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @RobinARH
* Microsoft Alias: **jorisde**

**Comment by tonyafehr** [comment]
Closing, as this is a duplicate.
