### ISSUE TITLE
Unable to find the menu

### ISSUE THREAD

**Issue by aamirsohail19** [MicrosoftDocs/dynamics-365-unified-operations-public#327]
Couldn't find the Machine learning tab in the form Retail and commerce &gt; Headquarters setup &gt; Parameters &gt; Retail parameters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e89ea54-de91-9841-9df5-541bf8fd0acf
* Version Independent ID: 1e5dd2a4-0f6d-1dad-c368-843aa26eefc4
* Content: [Configure machine learning-powered product recommendations - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/tasks/configure-machine-learning-product-recommendations)
* Content Source: [articles/retail/tasks/configure-machine-learning-product-recommendations.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/tasks/configure-machine-learning-product-recommendations.md)
* Service: **dynamics-365-retail**
* GitHub Login: @ashishmsft
* Microsoft Alias: **asharchw**

**Comment by josaw1** [comment]
Hi, thanks for the feedback. We're removing the current version of the product recommendation service as we redesign this feature with a better algorithm and newer retail-oriented capabilities. For more information see; Removed or deprecated features (https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/deprecated-features?toc=/fin-and-ops/toc.json).
