### ISSUE TITLE
Out of date information re: customer environments

### ISSUE THREAD

**Issue by danielzook** [MicrosoftDocs/dynamics-365-unified-operations-public#3270]
Section "How many sandbox environments do I need within an LCS customer implementation project?" is out of date.
It states: "A customer subscription comes with three environments by default: a dev or build environment, a tier-2 sandbox environment, and a production environment. "

See https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/cloud-deployment-overview#remote-desktop

Customer implementation projects only include two environments: Tier-2 Sandbox and Production.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a61360d4-73b1-104e-dfd4-7584c485cd0d
* Version Independent ID: 1f7c0203-4b68-9df2-a33e-69a2cf2b3b90
* Content: [Development and continuous delivery FAQ - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/continuous-delivery-faq)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/continuous-delivery-faq.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/dev-tools/continuous-delivery-faq.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @RobinARH
* Microsoft Alias: **jorisde**

**Comment by tonyafehr** [comment]
@jorisdg, please review. Thanks!

**Comment by tonyafehr** [comment]
Bug 573557 logged to track this issue.

**Comment by laneswenka** [comment]
This has been updated, it will go out in the next scheduled publishing wave.
