### ISSUE TITLE
enable Asset Leasing through Feature Management. 

### ISSUE THREAD

**Issue by ErikJohnMSFT** [MicrosoftDocs/dynamics-365-unified-operations-public#3272]
It would be nice to mention that you need to first enable Asset Leasing through Feature Management. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 711a62b9-9929-466e-b58b-c56d832deeef
* Version Independent ID: b482ae02-f63c-ee8d-2f23-0f57a241f48a
* Content: [Asset leasing home page - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/asset-leasing/asset-leasing-homepage)
* Content Source: [articles/finance/asset-leasing/asset-leasing-homepage.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/asset-leasing/asset-leasing-homepage.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @moaamer
* Microsoft Alias: **moaamer**

**Comment by tonyafehr** [comment]
@ErikJohnMSFT, thanks for the feedback. @moaamer, please review and consider making updates.

**Comment by moaamer** [comment]
@tonyafehr I agree to indicate the asset leasing is under feature management. I will work with @roschlom to get this update. Thanks.

**Comment by tonyafehr** [comment]
Bug 573565 logged to track this issue.

**Comment by moaamer** [comment]
@tonyafehr this have been addressed in CONTENT DELIVERABLE 572925 Update -  Asset leasing home page.
I've resolved bug 573565  as duplicated.
Thanks @roschlom  for your help here.
