### ISSUE TITLE
Incorrect navigation/path

### ISSUE THREAD

**Issue by thedynamicsgirl** [MicrosoftDocs/dynamics-365-unified-operations-public#3276]
[Go to Navigation pane > Modules > Product information management > Released product maintenance does not exist in D365 anymore. 
![image](https://user-images.githubusercontent.com/81991433/114063297-5ee96a00-9890-11eb-98c7-cd8e281655a1.png)
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54259aca-1ed7-cc7a-c898-65f065aba0e7
* Version Independent ID: ae89e895-7f44-90f1-6cdf-1e434f3b7aae
* Content: [Manage unit of measure - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/pim/tasks/manage-unit-measure)
* Content Source: [articles/supply-chain/pim/tasks/manage-unit-measure.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/pim/tasks/manage-unit-measure.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @sorenva
* Microsoft Alias: **sorenand**

**Comment by tonyafehr** [comment]
@sorenva, please review.

**Comment by tonyafehr** [comment]
Bug 573578 created to track this issue.

**Comment by kamaybac** [comment]
@thedynamicsgirl , thank you for reporting this issue. We have updated that detail in the topic and also updated and expanded it with more information.
