### ISSUE TITLE
Directed Graph Markup Language (.dgml) editor now is called DGML editor in VS installer

### ISSUE THREAD

**Issue by dmz1990** [MicrosoftDocs/dynamics-365-unified-operations-public#3279]
[Enter feedback here]

Directed Graph Markup Language (.dgml) editor now is called DGML editor in VS installer
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab16cabb-05a1-4239-3e13-58394994e3a7
* Version Independent ID: 35af4de6-7f28-1f56-d99c-a52e4852cdd1
* Content: [Visual Studio 2017 requirements for X++ - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/developer-tools-vs2017)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/developer-tools-vs2017.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/dev-tools/developer-tools-vs2017.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @jorisdg
* Microsoft Alias: **jorisde**

**Comment by tonyafehr** [comment]
@jorisdg, please review.

**Comment by jorisdg** [comment]
The original proposed doc said DGML Editor, this must have been mistakenly changed per policy to avoid acronyms. Thanks for pointing it out, we'll fix it.
