### ISSUE TITLE
Page discusses to re-enable SQL change tracking but the actual SQL is missing

### ISSUE THREAD

**Issue by andreash1** [MicrosoftDocs/dynamics-365-unified-operations-public#328]
page: https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/copy-database-from-sql-server-to-azure-sql

heading: Enable change tracking

SQL code to be added:
ALTER DATABASE [your database name] SET CHANGE_TRACKING = ON (CHANGE_RETENTION = 6 DAYS, AUTO_CLEANUP = ON) 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cef28a03-9759-ae74-20ba-2ec089c43d5b
* Version Independent ID: 1b085a75-6c84-c2a8-1ce8-60c272e8bfaf
* Content: [Copy Finance and Operations databases from SQL Server to production Azure SQL Database environments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/copy-database-from-sql-server-to-azure-sql)
* Content Source: [articles/dev-itpro/database/copy-database-from-sql-server-to-azure-sql.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/database/copy-database-from-sql-server-to-azure-sql.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @maertenm
* Microsoft Alias: **maertenm**

**Comment by sericks007** [comment]
Thanks for letting us know about this issue.  We'll investigate.

**Comment by sericks007** [comment]
Bug 246526 has been logged to track this issue.
