### ISSUE TITLE
Please read the text and correct

### ISSUE THREAD

**Issue by jmertens1** [MicrosoftDocs/dynamics-365-unified-operations-public#3281]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35765cda-23fb-5b94-0856-7002e37dadd3
* Version Independent ID: 82c39d58-a4e3-4562-53ab-131b831ec987
* Content: [Archive inventory transactions - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/inventory/archive-inventory-transactions)
* Content Source: [articles/supply-chain/inventory/archive-inventory-transactions.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/inventory/archive-inventory-transactions.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @sherry-zheng
* Microsoft Alias: **chuzheng**

**Comment by tonyafehr** [comment]
@jmertens1, thanks for the feedback. Can you provide additional information about what is incorrect in this topic.

**Comment by jmertens1** [comment]
For each archived record it must be

**For each archive** in the grid, the following information is provided:  

    Active – A check mark indicates that the archive is active.
    From date – The date of the oldest transaction that can be included in the archive.
    To date – The date of the latest transaction that can be included in the archive.
    Scheduled by – The user account that created the archive.
    Executed – The date when the archive was created.
    Reverse – A check mark indicates that the archive has been reversed.
    Stop current update – A check mark indicates that the archive is in progress, but it has been paused.
    State – The processing status of the archive. The possible values are Waiting, In progress, and Finished.

**Comment by kamaybac** [comment]
@jmertens1 , I don't think those are archived records that are listed there. The rows don't indicate records that were archived--each row is itself an archive that contains a collection of archived records (each of which is a transaction that occurred during the dates shown for the archive). When you open an archive, then you see the list of archived records that belong to that archive. Please let me know if that sounds incorrect and I will look into it further.
