### ISSUE TITLE
D365 release schedule table not covering old versions that are still supported

### ISSUE THREAD

**Issue by jorgferreira** [MicrosoftDocs/dynamics-365-unified-operations-public#3283]
Hi, since customers can choose to pause up to 3 consecutive updates at a time, we should still show version history to cover older versions.
We do advise customers whether their current version had its end of service on date X or not, for projects with updates that are not serviceable anymore and if its update is still valid on this allowed pause cadence. Hence, we should still leave all versions until they become out of support.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7dcb285-f32c-c92e-fe49-1617f213066b
* Version Independent ID: 8f28c1a0-9da5-f853-90ee-d82a4c32df7e
* Content: [Service update availability - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/public-preview-releases?toc=/dynamics365/commerce/toc.json)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/public-preview-releases.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/public-preview-releases.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @ShellyBakke
* Microsoft Alias: **smiller**

**Comment by andreabichsel** [comment]
@jorgferreira, thanks for the feedback. @sericks007, please review and consider making updates.

**Comment by sericks007** [comment]
@ShellyBakke, please review and update the content.
