### ISSUE TITLE
uat 7 or 14 days 

### ISSUE THREAD

**Issue by jansenrf** [MicrosoftDocs/dynamics-365-unified-operations-public#3285]
Is the PITR for the UAT 7 of 14 days
I see several messages.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 805f3739-0cad-d6ab-7db0-175c972f189f
* Version Independent ID: 68be2d28-d5e9-471d-8648-a8cbae2e1e7d
* Content: [Database point-in-time restore (PITR) - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/database-point-in-time-restore)
* Content Source: [articles/fin-ops-core/dev-itpro/database/database-point-in-time-restore.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/database/database-point-in-time-restore.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by andreabichsel** [comment]
@jansenf, thanks for the feedback. @damienmaspero, please review and consider making updates.
