### ISSUE TITLE
CustomerSource and PartnerSource are retired.

### ISSUE THREAD

**Issue by scott-tucker** [MicrosoftDocs/dynamics-365-unified-operations-public#3286]
This docs page references CustomerSource and PartnerSource a bunch and those site are retired and https://mbs.microsoft.com/ is no longer responding to requests.  The page should be updated with the new customer and partner destinations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ee6629a-f1a4-b352-0b26-657a503d80a7
* Version Independent ID: dbe54d30-b73b-0446-7d80-922050825641
* Content: [Configure Lifecycle Services (LCS) security - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/configure-lcs-security)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/configure-lcs-security.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/lifecycle-services/configure-lcs-security.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @AngelMarshall
* Microsoft Alias: **tsmarsha**

**Comment by sericks007** [comment]
@scott-tucker, thanks for bringing this to our attention.  We'll work to correct this.

**Comment by sericks007** [comment]
The links to CustomerSource and PartnerSource have been removed.
