### ISSUE TITLE
 Create clustered column Indexes supported with BYOD 

### ISSUE THREAD

**Issue by avinashrj19** [MicrosoftDocs/dynamics-365-unified-operations-public#3289]
[Enter feedback here]

Customer needs to understand the different SQL tries for which the BYOD export is supported with CCI's ,
as we do not have any system design information on the same.
eg: how much cost will be incurred if customer is using Sql premium database is used by the customer.
How can we ensure the feasibility while using the CCI's with BYOD.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33f75161-0776-a6c1-dc10-dc20ea26973f
* Version Independent ID: 55a81394-4606-745a-9fd2-59fb257d1086
* Content: [Bring your own database (BYOD) - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/export-entities-to-your-own-database)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/export-entities-to-your-own-database.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/analytics/export-entities-to-your-own-database.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by andreabichsel** [comment]
@Sunil-Garg can you take a look?
