### ISSUE TITLE
Normalize v DeNormalized

### ISSUE THREAD

**Issue by Joseph-Conrad** [MicrosoftDocs/dynamics-365-unified-operations-public#3292]
Under Data Entities the sentence that ends "were de-normalized and split into multiple tables." should read normalized. De-normalized table lead to inefficiencies in database operations.

Tom Morris

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1016eba2-a0f9-8890-beb4-7c9f9f6df4fc
* Version Independent ID: 57758813-9d36-975a-eb6f-551b7da3e276
* Content: [Data management overview - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/data-entities-data-packages)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/data-entities-data-packages.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/data-entities-data-packages.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by andreabichsel** [comment]
@Sunil-Garg can you take a look?
