### ISSUE TITLE
Wrong info in the article - Instead of CostObjectStatementCache should be CostStatementCacheDataSet

### ISSUE THREAD

**Issue by NataliiaNaumenko** [MicrosoftDocs/dynamics-365-unified-operations-public#3293]
Hello,

I have faced the issue that I cannot find the CostObjectStatementCache in the Data cache configuration. I have figured out that it might be wrong info in the article and Instead of CostObjectStatementCache should be CostStatementCacheDataSet in it.

Thank you!

![2021-04-19_12-19-59](https://user-images.githubusercontent.com/31509063/115212878-a631ef00-a109-11eb-8859-d8fbaeef8af7.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2d5bfd3-1ddd-514b-0735-3ffac0a43787
* Version Independent ID: 575715a0-b64a-9a20-6212-cb304c7cd5c7
* Content: [Cost management Power BI content - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/cost-management-content-pack)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/cost-management-content-pack.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/analytics/cost-management-content-pack.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @ShylaThompson
* Microsoft Alias: **kfend**

**Comment by josaw1** [comment]
@johnmichalak this topic is old. Can you please make sure it is part of your freshness review? Can you also please address the feedback above?

**Comment by josaw1** [comment]
Closing as won't fix.
