### ISSUE TITLE
Extending eletronic report in 2021

### ISSUE THREAD

**Issue by Poetkaj** [MicrosoftDocs/dynamics-365-unified-operations-public#3296]
The class mentioned in this doc is not available in version 10.0.15.
How can create new Electronic reporting functions in newer versions of D365 FO.

Kind regards
Kaj Schougaard
Electronic reporting fanatic

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de60d22f-2871-0dba-26b4-10be911e2517
* Version Independent ID: 8b08f0da-0f71-e419-a43f-2f53e54709a3
* Content: [Extend the list of Electronic reporting (ER) functions - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/general-electronic-reporting-formulas-list-extension)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/general-electronic-reporting-formulas-list-extension.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/analytics/general-electronic-reporting-formulas-list-extension.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @NickSelin
* Microsoft Alias: **nselin**

**Comment by NickSelin** [comment]
Hello Kaj Schougaard,
This functionality was introduced in version 7.0. It was deprecated starting from the version 7.3 (see the [API changes 7.3](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/er-apis-app73?toc=/dynamics365/finance/toc.json) page where it is mentioned that some classes were marked as internal) as part of code sealing process to deliver the OneVersion (aka v10). Alternatively, you can introduce your X++ classes the public methods of which can be called from ER by using data sources of the **Dynamics 365 / Class** type.
Best regards,
Nick Selin

**Comment by Poetkaj** [comment]
Thanks NickSelin.
