### ISSUE TITLE
Offline Capabilities

### ISSUE THREAD

**Issue by KimANel** [MicrosoftDocs/dynamics-365-unified-operations-public#3298]
Can you document whether offline works or not? The scenario is that a maintenance request needs to be entered but there is no connectivity. Can we still create the maintenance request and then when my phone is back online, will it sync?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a630f1b4-29ee-6867-6ba5-497237b6391b
* Version Independent ID: 619de03d-f6d8-3491-2e47-94e852949efe
* Content: [Use the Asset management mobile workspace - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/asset-management/asset-management-mobile-workspace)
* Content Source: [articles/supply-chain/asset-management/asset-management-mobile-workspace.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/asset-management/asset-management-mobile-workspace.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @johanhoffmann
* Microsoft Alias: **johanho**

**Comment by kfend** [comment]
@KimANel - thanks for your question.
@johanhoffmann - can you please take a look and address this?

**Comment by kfend** [comment]
Bug 579372 created to track this issue.

**Comment by josaw1** [comment]
@kamaybac please review and update accordingly.

**Comment by josaw1** [comment]
Closing as won't fix.
