### ISSUE TITLE
Field "DNS name" expects key vault's URI 

### ISSUE THREAD

**Issue by De-stack** [MicrosoftDocs/dynamics-365-unified-operations-public#3299]
The picture and description shown in "DNS name: Enter the DNS name of Key Vault." on page https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/entity-store-data-lake expects the key vault's URI. 

A DNS name is something different than a URI. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a344a5de-68fa-e9cf-28eb-51269c33b9b3
* Version Independent ID: 1b3ede62-3954-574b-5778-8cdee0ededfe
* Content: [Make Entity store available as a Data Lake - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/entity-store-data-lake)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/entity-store-data-lake.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/entity-store-data-lake.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by kfend** [comment]
@De-stack - thank you for the feedback.
@MilindaV2 - can you please take a look at and address this feedback?

**Comment by kfend** [comment]
Bug 579380 created to track this issue.
