### ISSUE TITLE
Escaping user names

### ISSUE THREAD

**Issue by RaphaelTagliani** [MicrosoftDocs/dynamics-365-unified-operations-public#33]
Line :
select 'DROP USER ' + name
Should be replaced by :
select 'DROP USER [' + name + ']'

Database names and table names should also be escaped the same way.

Thank you.

**Comment by MargoC** [comment]
Hi Raphael, 

Please file your issue as a pull request on a specific topic. I'll be closing it, as because we aren't using issues at this point.

**Comment by RaphaelTagliani** [comment]
Hi Margo,

Ok, I'm not familiar with pull requests, but I'll try that.
I'm currently going through the procedure and I see a few minor updates that should be made.
Another one : 
cd C:\Program Files (x86)\Microsoft SQL Server\130\DAC\bin
should be replaced by 
cd C:\Program Files (x86)\Microsoft SQL Server\140\DAC\bin
Because going to SSMS 17.4 (current) will create a new folder.

Maybe we should create powershell scripts for the whole procedure. 
I started a while ago (before this post existed), but the scripts are not well packaged:
http://blog.zealots.solar/?p=94

**Comment by MargoC** [comment]
Raphael, are your changes on this topic? https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/request-point-in-time-restore

To file a pull request on any topic, click the edit button at the upper right. You'll then see the topic on GitHub. Click the next edit button, and make the changes that you're suggesting in the file in the GitHub UI. When you are done, click Propose file change--that will start a pull request.

**Comment by RaphaelTagliani** [comment]
Margo, it was on this topic : https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/copy-database-from-azure-sql-to-sql-server?toc=dynamics365/unified-operations/fin-and-ops/toc.json 
Thank you for your guidance regarding pull requests. I registered the pull request, and commented the changes.
Have a nice day,
