### ISSUE TITLE
Misleading example reference?

### ISSUE THREAD

**Issue by tacklers** [MicrosoftDocs/dynamics-365-unified-operations-public#3301]
The second bullet point refers to the 'above' example, should it be the below example?
It also makes reference to the 'CustGroup' table but that is not shown either above or below. 
Maybe I just don't get it but the conceptual table diagram doesn't match the text, it shows the primary table supplying the constrained table. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a953fbe-ec7f-9984-42f8-3c88248761a1
* Version Independent ID: 4b40257c-e071-b131-31ac-1dcdbe8d995b
* Content: [Extensible data security policies - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/extensible-data-security-policies)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/extensible-data-security-policies.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/sysadmin/extensible-data-security-policies.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Peakerbl
* Microsoft Alias: **peakerbl**

**Comment by kfend** [comment]
@tacklers - thank you for the feedback.
@Peakerbl - can you please take a look at and address this feedback?

**Comment by kfend** [comment]
This topic has been updated and the changes will publish later today.
