### ISSUE TITLE
Link to developer changes

### ISSUE THREAD

**Issue by rsudworth** [MicrosoftDocs/dynamics-365-unified-operations-public#3304]
There needs to be a connection between these release notes and the e-commerce development FAQ. There is a page at https://docs.microsoft.com/en-us/dynamics365/commerce/e-commerce-extensibility/sdk-faq under the steps to upgrade e-commerce that is not in anyway connected to this feature list, even though one of the FAQs is about a feature in 10.0.17 (quick view module I think). With the web side of things being so open and extensible, the effect of these changes needs to be highlighted and properly connected to a release. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5914677-9720-ad39-babc-d2a0528dea4c
* Version Independent ID: b3d9070e-b760-27ee-9b22-9da78815cc82
* Content: [What's new or changed in Dynamics 365 Commerce - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/get-started/whats-new-home-page)
* Content Source: [articles/commerce/get-started/whats-new-home-page.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/get-started/whats-new-home-page.md)
* Service: **dynamics-365-commerce **
* Product: ****
* Technology: ****
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by rsudworth** [comment]
It would also be very helpful if release notes where part of the repo for the web side of things at https://github.com/microsoft/Msdyn365.Commerce.Online

**Comment by kfend** [comment]
@rsudworth - thanks for the feedback.
@josaw1 - can you please take a look at this feedback?

**Comment by josaw1** [comment]
Thanks for the feedback. I added a link to the FAQ from the What's New topic.
