### ISSUE TITLE
Critique on accuracy

### ISSUE THREAD

**Issue by lbagleybhs** [MicrosoftDocs/dynamics-365-unified-operations-public#3305]
[Enter feedback here]

In section: "Create and call a new extension method", the code boxes are marked as "C#" code, when this is "X++". 
Also, there is a ttsbegin/ttscommit pair outside of the try/catch block which renders the catch useless in this example. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 541407d5-1fb2-f9ea-d7d9-1e0ab78c2793
* Version Independent ID: a41c077f-a2f6-d197-f705-1809a5a5b0eb
* Content: [Extend Commerce Data Exchange - Real-time Service - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/extend-commerce-data-exchange?source=docs)
* Content Source: [articles/commerce/dev-itpro/extend-commerce-data-exchange.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/extend-commerce-data-exchange.md)
* Service: **dynamics-365-commerce **
* Product: ****
* Technology: ****
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by kfend** [comment]
Bug 579367 created to track this issue.

**Comment by mugunthanm** [comment]
Thanks for the feedback, updated the document.
