### ISSUE TITLE
Explanation required for note (not clear) 

### ISSUE THREAD

**Issue by omar-kishk** [MicrosoftDocs/dynamics-365-unified-operations-public#3307]
i need an explanation for note of the products must also be assorted to a product, under Add products to category nodes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0c7f3e5-5cff-3b3a-8876-48bf006e9c60
* Version Independent ID: 9dde0656-917e-f6f5-1c44-1ac7fb5aecdd
* Content: [Create a channel navigation hierarchy - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/create-channel-hierarchy)
* Content Source: [articles/commerce/create-channel-hierarchy.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/create-channel-hierarchy.md)
* Service: **dynamics-365-commerce **
* Product: ****
* Technology: ****
* GitHub Login: @samjarawan
* Microsoft Alias: **samjar**

**Comment by samjarawan** [comment]
Looks like the text is wrong, the note should read, "products must be assorted to a channel".  More details can be found here: https://docs.microsoft.com/en-us/dynamics365/commerce/assortments

**Comment by kfend** [comment]
Thanks for the quick turnaround @samjarawan.
@omar-kishk - the topic has been updated and the changes will go live later today.
