### ISSUE TITLE
AX 2012 demo environment deployment

### ISSUE THREAD

**Issue by sbaber82** [MicrosoftDocs/dynamics-365-unified-operations-public#3308]
Hi,

Using the steps described in this page, I cannot deploy AX 2012 demo environment. When I click Add button on cloud hosted environment page, it shows me the Platform update to select which is relevant for D365 Finance. There is no option showing related to AX 2012 versions as mentioned in this docs site.

Am I missing something ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d390b25f-7fdc-62e8-cbd6-70657c4a2ea4
* Version Independent ID: 9007a010-2810-5724-5a5d-cfc2d3ec35ac
* Content: [Deploy AX 2012 R3 or AX 2012 R3 CU8 demo environments on Azure - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/ax-2012/deploy-ax-2012-r3-ax-2012-r3-cu8-demo-environment-azure)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/ax-2012/deploy-ax-2012-r3-ax-2012-r3-cu8-demo-environment-azure.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/lifecycle-services/ax-2012/deploy-ax-2012-r3-ax-2012-r3-cu8-demo-environment-azure.md)
* Service: ****
* Product: **dynamics-ax-2012**
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **kfend**

**Comment by sericks007** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
