### ISSUE TITLE
Amount are displayed in Transaction currency in report

### ISSUE THREAD

**Issue by JChandnani** [MicrosoftDocs/dynamics-365-unified-operations-public#3309]
Hi, report is generating data in transactional currency, however as per the model and source setup of report, it should be in accounting currency.

Can you please help, if this is standard or some bug

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73deae8d-c248-76f5-8772-ae716556357f
* Version Independent ID: 2b2fe1f0-b294-20e2-78ab-f7c3533cb334
* Content: [Trial balance with transactional detail report - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/public-sector/general-ledger-public-sector-trial-balance)
* Content Source: [articles/finance/public-sector/general-ledger-public-sector-trial-balance.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/public-sector/general-ledger-public-sector-trial-balance.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @v-kiarnd
* Microsoft Alias: **v-kiarnd**

**Comment by roschlom** [comment]
Thank you for the question. We appreciate the input and will look into it.

**Comment by RobinARH** [comment]
Created bug 582884 to track this issue.
