### ISSUE TITLE
Geting TS2306 applicationinsights-web.d.ts is not module error

### ISSUE THREAD

**Issue by Halldor10** [MicrosoftDocs/dynamics-365-unified-operations-public#3310]
When following the instructions [Log events to Application Insights in the POS extension projects](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/commerce-application-insights#log-events-to-application-insights-in-the-pos-extension-projects), to use Application Insights logging for the POS, the compiler ends up by showing the error: TS2306	Build:File 'K:/<MyFilePath>/POS/Extensions/Libraries/node_modules/@microsoft/applicationinsights-web/dist/applicationinsights-web.d.ts' is not a module.

Not sure if it's related to configuration that is to be added to Pos.Extensions.csproj as I put it like this or something else.

>   <Target Name="CopyPosExtensionsFiles" AfterTargets="AfterBuild">
    <ItemGroup>
      <JavaScriptFileList Include="Libraries\\**\\*.js">
        <InProject>false</InProject>
        <Visible>false</Visible>
      </JavaScriptFileList>
      <JavaScriptFileList Include="@(TypeScriptCompile->'%(RelativeDir)%(Filename).js')">
        <InProject>false</InProject>
        <Visible>false</Visible>
      </JavaScriptFileList>

Any update of the documentation that could explain the TS2306 error would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f659eadc-c39c-a5e4-cfe4-27fea2f77523
* Version Independent ID: 48e06663-f4a1-b540-db40-147b35a840f9
* Content: [Log extension events to Application Insights - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/commerce-application-insights)
* Content Source: [articles/commerce/dev-itpro/commerce-application-insights.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/commerce-application-insights.md)
* Service: **dynamics-365-commerce **
* Product: ****
* Technology: ****
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by roschlom** [comment]
Thank you for the input. We do appreciate it and use it to improve our content.

**Comment by RobinARH** [comment]
Created bug 582885 to track this issue.
