### ISSUE TITLE
CRT / AppInsights doc needs updating

### ISSUE THREAD

**Issue by RobvanB** [MicrosoftDocs/dynamics-365-unified-operations-public#3313]
Documentation is somewhat outdated. The Azure portal UI is different from what is described in the doc (there are workspaces fields now when creating the App Insights in Azure. Also, when creating the project in Visual studio, you now need to use NuGet packages rather than references to actual DLLs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f659eadc-c39c-a5e4-cfe4-27fea2f77523
* Version Independent ID: 48e06663-f4a1-b540-db40-147b35a840f9
* Content: [Log extension events to Application Insights - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/commerce-application-insights)
* Content Source: [articles/commerce/dev-itpro/commerce-application-insights.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/commerce-application-insights.md)
* Service: **dynamics-365-commerce **
* Product: ****
* Technology: ****
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by roschlom** [comment]
Thank you for the input. We do appreciate it and use it to improve our content.

**Comment by RobinARH** [comment]
Created bug 582888 to track this issue.

**Comment by josaw1** [comment]
Updated.
