### ISSUE TITLE
Where is the Dynamics App Manifest?

### ISSUE THREAD

**Issue by tacklers** [MicrosoftDocs/dynamics-365-unified-operations-public#3317]
Export to Word/Create a Word template/
refers ' File Share that contains the Microsoft Dynamics App Manifest' ?
I don't know where the manifest is in an online world, is it referring to an on-prem setup.
Thanks, Richard  
[Enter feedback here]
 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c128127a-d4df-96d3-dbc9-8d68a70b1ba0
* Version Independent ID: b146be00-9f2e-81d8-540f-e0b45fb34b5b
* Content: [Office integration tutorial - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/office-integration/office-integration-tutorial)
* Content Source: [articles/fin-ops-core/dev-itpro/office-integration/office-integration-tutorial.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/office-integration/office-integration-tutorial.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by roschlom** [comment]
Thanks for the input on our content. We appreciate it!

**Comment by RobinARH** [comment]
Created bug 582890 to track this issue.

**Comment by jasongre** [comment]
@tacklers The part about the manifest file is out of date. An updated version of the article should be available shortly.
