### ISSUE TITLE
Broken link to Microsoft Download Center. 

### ISSUE THREAD

**Issue by pturegano** [MicrosoftDocs/dynamics-365-unified-operations-public#3318]
The link to Microsoft Download Center is broken

Microsoft Download Center 
https://mbs.microsoft.com/customersource/northamerica/AX/learning/documentation/how-to-articles/d365finopelecreptg81

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ff1470e-2d85-a116-5fd5-d20d99456162
* Version Independent ID: a0d52ef3-4fdf-78b4-b22b-e0b58b921f58
* Content: [Import Electronic reporting (ER) configurations from Regulatory Configuration Services (RCS) - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/rcs-download-configurations)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/rcs-download-configurations.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/analytics/rcs-download-configurations.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @NickSelin
* Microsoft Alias: **nselin**

**Comment by kfend** [comment]
@pturegano - thank you for the feedback. I have updated the topic with the correct link and the changes will be published later today.
