### ISSUE TITLE
Published views and legal entities

### ISSUE THREAD

**Issue by jopankow** [MicrosoftDocs/dynamics-365-unified-operations-public#3319]
Hello,

The documentation here about publishing a view to legal entities is different than current behavior. For example, the existing documentation indicates that legal entities are respected. I had a customer support case where publishing a view to a specific LE did not respect the LE. According to https://fix.lcs.dynamics.com/Issue/Details?kb=4574778, it says "This issue is partially fixed in 10.0.13". 

I also believe there is a new feature planned to improve this. Can this documentation be updated to reflect the current behavior as well as what the behavior may be in the future?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 765bcdc1-4de0-f2f4-0af2-d6c856cd7cb2
* Version Independent ID: dc184e5c-611c-520a-784c-7007dc51b2c3
* Content: [Saved views - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/saved-views#managing-personalizations-at-an-organizational-level-with-views)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/saved-views.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/saved-views.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by roschlom** [comment]
Thanks for making the request. We appreciate the input!

**Comment by RobinARH** [comment]
Created bug 582892 to track this issue.

**Comment by jasongre** [comment]
Hey @jopankow, thanks for the feedback! The 2nd bullet in the Note at the bottom of the Publishing views section describes exactly how the current publish to legal entity works. I will adjust the article to try and make this clearer. 

As for any new features in this area, keep an eye out for upcoming release plan entries for details on how this may work in the future. I will update this documentation with those details when that feature is closer to being available.
