### ISSUE TITLE
More Information on Cloud Service Operations

### ISSUE THREAD

**Issue by tomhig** [MicrosoftDocs/dynamics-365-unified-operations-public#332]
There's a more detailed white paper on Dynamics 365 Finance and Operations Cloud Service Operations at the following: https://aka.ms/D365-Cloud-Service-Operations. A number of topics are addressed in this document, including the Operating Model, System Configuration, Service Operations, and SLA.

Suggest that a link to this white paper be included in this particular Docs article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 230ae369-93c3-90a0-cf0a-078afb39e621
* Version Independent ID: 22f367a5-3954-11c8-2e72-94a9990d89f3
* Content: [Cloud deployment option - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/deployment/cloud-deployment-overview?toc=/fin-and-ops/toc.json#frequently-asked-questions)
* Content Source: [articles/dev-itpro/deployment/cloud-deployment-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/deployment/cloud-deployment-overview.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @kfend
* Microsoft Alias: **kfend**

**Comment by tonyafehr** [comment]
Thanks for the suggestion! We really appreciate feedback that helps us to improve our documentation. I will add a link to the white paper.
