### ISSUE TITLE
Directions in section for Demo/Test hosted in customer subscription are incomplete

### ISSUE THREAD

**Issue by JimMorrisonAXMojo** [MicrosoftDocs/dynamics-365-unified-operations-public#3321]
[Enter feedback here]
Three problems:
1. This section doesn't mention resetting IIS. The section above on how to handle a Microsoft subscription hosted environment includes that direction, but the Customer subscription section left it out.
2. The console command line example skips the value needed for --bindir. That's given in the table below, but unlike the --metadatadir which uses the same value, and all the parameters, it's show as no value.
3. The screen capture makes it look as though the second line is entered separately, starting with --sqlserver, and not that the line is actually a continuation of a single command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91ae449b-ec59-28d4-1934-6909e77ee4f3
* Version Independent ID: df6ae442-3466-4c69-aa11-ed35e20a629f
* Content: [Maintenance mode - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/maintenance-mode)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/maintenance-mode.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/sysadmin/maintenance-mode.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by josaw1** [comment]
Thanks for your feedback. @laneswenka can you please review this?

**Comment by josaw1** [comment]
@sericks007 can you help with this?

**Comment by josaw1** [comment]
BUG 583265 created to track this issue.

**Comment by laneswenka** [comment]
Updated, this will go out on the next scheduled docs publish wave.
