### ISSUE TITLE
This information is wildly wrong

### ISSUE THREAD

**Issue by Joseph-Conrad** [MicrosoftDocs/dynamics-365-unified-operations-public#3322]
The procedure to set the date/time is not correct. Not even close. 

The article references "Source Date Format" column. That does not exist. And actually, if you examine the article graphic, the column heading is "Source Data Format".

Grade: D-

Tom

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff2642da-229f-1814-246f-713979598b45
* Version Independent ID: 93117dbd-7e95-df78-6004-f10f0ae478ea
* Content: [Synchronize date and time in import jobs - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/data-synchronize-date-and-time)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/data-synchronize-date-and-time.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/data-synchronize-date-and-time.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by josaw1** [comment]
Thanks for your feedback. @Sunil-Garg can you please review this?

**Comment by josaw1** [comment]
BUG 583267 created to track issue.
