### ISSUE TITLE
Syntax shows LIST instead of LISTJOIN

### ISSUE THREAD

**Issue by SST1982** [MicrosoftDocs/dynamics-365-unified-operations-public#3324]
In the syntax part of this article, the function  "LIST" is showed. Judging by the GIFs later, it should be LISTJOIN
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2899b82-adf3-0a38-5e73-3055d6cc323a
* Version Independent ID: 4804cfcb-ccfb-2b26-7f96-08ec920d9a36
* Content: [LISTJOIN ER function - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/er-functions-list-listjoin?toc=/dynamics365/commerce/toc.json)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/er-functions-list-listjoin.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/analytics/er-functions-list-listjoin.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @NickSelin
* Microsoft Alias: **nselin**

**Comment by josaw1** [comment]
Thanks for your feedback. @NickSelin please take a look.

**Comment by josaw1** [comment]
Fix going live today.
