### ISSUE TITLE
Revenue recognition setup page needs updates

### ISSUE THREAD

**Issue by sheko89** [MicrosoftDocs/dynamics-365-unified-operations-public#3326]
Hi, thank you for the great content!

Kindly, the revenue recognition setup page needs to be updated with the changes applied in the module, specially the Recognition basis and Recognition convention values.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49ee1703-51fa-03cb-cb6c-d13c59ec0dc3
* Version Independent ID: be390b47-7972-c0d5-aa66-ac74ad24473f
* Content: [Revenue recognition setup - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/accounts-receivable/revenue-recognition-setup)
* Content Source: [articles/finance/accounts-receivable/revenue-recognition-setup.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/accounts-receivable/revenue-recognition-setup.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @kweekley
* Microsoft Alias: **kweekley**

**Comment by josaw1** [comment]
Thanks for your feedback. @roschlom can you please review?

**Comment by josaw1** [comment]
BUG 583268 created to track the issue.

**Comment by kfend** [comment]
This topic was updated a few months ago. Closing the issue now.
