### ISSUE TITLE
Link to video fails

### ISSUE THREAD

**Issue by tacklers** [MicrosoftDocs/dynamics-365-unified-operations-public#3327]
On the first page, after point 4 there is a video link. It breaks
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf51a7e8-9ae4-5b55-c61c-2dc31abe6621
* Version Independent ID: 934ab5eb-0b75-c8de-a76d-efd2ded27609
* Content: [Data task automation - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/data-task-automation)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/data-task-automation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/data-task-automation.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by sericks007** [comment]
@tacklers, thanks for making us aware of this issue.  I've fixed the link.  The updated article will be published later today.
