### ISSUE TITLE
Documentation "Extensible Controls - Public JavaScript APIs." is unavailable.

### ISSUE THREAD

**Issue by xu747** [MicrosoftDocs/dynamics-365-unified-operations-public#3328]
[Enter feedback here]
The Reference Documentation "Extensible Controls - Public JavaScript APIs." is unavailable.
When I open https://mbs.microsoft.com/Files/public/CS/AX/DynamicsAX_JavaScript_API_Documentation_Update2_07_2016.pdf,
it will response ERR_CONNECTION_CLOSED.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f818e01a-8e7d-cd40-0d2d-92b5ffe1a804
* Version Independent ID: 0ba98368-711a-2a90-faaf-d2f1378083f2
* Content: [Public JavaScript APIs for extensible controls - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/user-interface/public-javascript-apis)
* Content Source: [articles/fin-ops-core/dev-itpro/user-interface/public-javascript-apis.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/user-interface/public-javascript-apis.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by josaw1** [comment]
Thanks for your feedback. @jasongre can you please review?

**Comment by josaw1** [comment]
BUG 583269 created to track.

**Comment by RobinARH** [comment]
I fixed the link and the new content will go live tonight. - Robin
