### ISSUE TITLE
Path to import task recorder references nonexistent menu

### ISSUE THREAD

**Issue by rrhkpmg** [MicrosoftDocs/dynamics-365-unified-operations-public#3329]
I believe the menu item described as **Finance and Operations** > **Addins** > **Import Task Recording** should be **Dynamics 365** > **Addins** > **Import Task Recording**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2673e0e6-36ff-72f9-11dd-bfcfa1916882
* Version Independent ID: 01b6cf39-57a3-c6ca-af2c-4b7c530e5fdf
* Content: [Testing and validations - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/perf-test/testing-validation)
* Content Source: [articles/fin-ops-core/dev-itpro/perf-test/testing-validation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/perf-test/testing-validation.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @jorisdg
* Microsoft Alias: **jorisde** s

**Comment by jorisdg** [comment]
Thanks. I'm updating.
