### ISSUE TITLE
This page should be revised

### ISSUE THREAD

**Issue by d3fr0g** [MicrosoftDocs/dynamics-365-unified-operations-public#3330]
The _Important_ sections are out of date.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c7f272b-4ea7-a285-4a9f-e67583a664e0
* Version Independent ID: 54ac0c3d-a2b5-6001-1581-167dd87a80c0
* Content: [Self-service deployment overview - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/infrastructure-stack)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/infrastructure-stack.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/deployment/infrastructure-stack.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @rashmansur
* Microsoft Alias: **rashmim**

**Comment by josaw1** [comment]
Thanks for your feedback. @rashmansur please review.

**Comment by josaw1** [comment]
BUG 583270 created to track.
