### ISSUE TITLE
Email requirements not listed

### ISSUE THREAD

**Issue by TCM-NEPT** [MicrosoftDocs/dynamics-365-unified-operations-public#3331]
[Enter feedback here]

Set up offers just enough to get though, but leaves some key information out. Main issue I'm referring to here are the email requirements - these appear to need to be Microsoft based (Outlook, Hotmail, Outlook based Work) but doe not work for external addresses, seriously hampering capability. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cd5c06b-a32f-0052-1fea-ed75bc64bdbb
* Version Independent ID: 0b2f2773-60d1-4522-3e0b-00f0801fed1f
* Content: [Set up and maintain vendor collaboration - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/procurement/set-up-maintain-vendor-collaboration)
* Content Source: [articles/supply-chain/procurement/set-up-maintain-vendor-collaboration.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/procurement/set-up-maintain-vendor-collaboration.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @kamaybac
* Microsoft Alias: **dabourq**

**Comment by kamaybac** [comment]
@TCM-NEPT , thank you for reporting this issue. I have passed it on for consideration.

**Comment by kamaybac** [comment]
Bug 586367 created to track this issue.

**Comment by kamaybac** [comment]
@TCM-NEPT , our engineers have looked into this issue and they tell me that we don't require email addresses that relate to Microsoft services. You should be able to use any email addresses that you like. It could be that your issue has some other root cause. I recommend that  you contact Microsoft Support for assistance.
