### ISSUE TITLE
Related blog post

### ISSUE THREAD

**Issue by yukonpeegs** [MicrosoftDocs/dynamics-365-unified-operations-public#3332]
See this related blog post

https://community.dynamics.com/365/financeandoperations/b/dynamics-365-finance-blog/posts/best-practices-for-updating-financial-dimension-set-dimension-sets

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2139b773-9052-bc07-7611-35255cbecde7
* Version Independent ID: 403401c3-4752-dddc-d511-12f832907741
* Content: [Financial dimension sets - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/general-ledger/financial-dimension-sets?source=docs)
* Content Source: [articles/finance/general-ledger/financial-dimension-sets.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/general-ledger/financial-dimension-sets.md)
* Service: **dynamics-365-finance**
* Technology: ****
* GitHub Login: @yukonpeegs
* Microsoft Alias: **epegors**

**Comment by kamaybac** [comment]
@yukonpeegs, you appear to be the author of this topic, is that right? If so, you're welcome to edit it as needed and submit a PR. Otherwise, I'll ask Bob to get in touch with you.

**Comment by kamaybac** [comment]
Bug 586387 created to track this issue

**Comment by yukonpeegs** [comment]
In reading the blog I don't think anything is needed. We can close this with no change.

**Comment by kamaybac** [comment]
@yukonpeegs thanks for following up. I'll close both this and the bug.
