### ISSUE TITLE
"Path" parameter in example seems wrong

### ISSUE THREAD

**Issue by dgriffiths-bd** [MicrosoftDocs/dynamics-365-unified-operations-public#3334]
I think the "path" parameter in the code example for the definition seems wrong. 

It currently reads 

    "path": "../../actions/get-product",

and I think it needs to read

    "path": "../../actions/get-product.action",

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90329178-f512-40f7-84c2-1a434a0588bb
* Version Independent ID: d9059d68-ba79-2fdc-6d12-36da4b1fa16a
* Content: [Page load data actions - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/e-commerce-extensibility/page-load-data-action)
* Content Source: [articles/commerce/e-commerce-extensibility/page-load-data-action.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/e-commerce-extensibility/page-load-data-action.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @samjarawan
* Microsoft Alias: **samjar**

**Comment by kamaybac** [comment]
@dgriffiths-bd , thank you for reporting this issue. I have passed it on for consideration.

**Comment by samjarawan** [comment]
Good catch, at one point the add-data-action did not append the '.action' to the doc, will get this fixed up...

**Comment by kamaybac** [comment]
Bug 586392 created to track this issue

**Comment by kamaybac** [comment]
This issue has been addressed. Closing.
