### ISSUE TITLE
No longer in preview?

### ISSUE THREAD

**Issue by andyNewnham** [MicrosoftDocs/dynamics-365-unified-operations-public#3335]
I believe this feature is no longer restricted to preview? (as it is in all my environments and I am not aware of being part of a private preview!). Therefore the note at the top of the page should be removed. 'This feature is available only in a restricted preview as part of Platform update 31.'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed582d22-c839-8438-6374-dfe11788d4ea
* Version Independent ID: fb380959-ce9b-e590-76c9-112c1a72d1c7
* Content: [Priority-based batch scheduling - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/priority-based-batch-scheduling)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/priority-based-batch-scheduling.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/sysadmin/priority-based-batch-scheduling.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Peakerbl
* Microsoft Alias: **peakerbl**

**Comment by kamaybac** [comment]
@andyNewnham , thank you for reporting this issue. I have passed it on for consideration.

**Comment by Peakerbl** [comment]
Sorry, but I'm not sure who is the PM for Batch any longer. After me it was Reva Chauchan. Sunil Garg might know.

**Comment by kamaybac** [comment]
Bug 586406 created to track this issue

**Comment by MicroSri** [comment]
Priority based scheduling is still not in GA. So this comment should stay; we have some more issues to be fixed here.
