### ISSUE TITLE
Obsolete page?

### ISSUE THREAD

**Issue by andyNewnham** [MicrosoftDocs/dynamics-365-unified-operations-public#3336]
I believe most if not all of the information in this article is now obsolete;

1. There is no longer the ability to 'Publish' an online store from the online stores form.
2. The E-Commerce functionality does not use the old SharePoint publishing functionality - even if the capability still exists in the background, this may be confusing to readers. If the doc remains, perhaps a note can be added stating the OOTB E-Commerce storefront does not use it
3. The link to 'Setup and Online store' goes to the AX 2012 docs pages
4. The components 'Commerce Data Exchange: Async Server' and 'Commerce Data Exchange: Real-time Service' no longer exist / names/branding has changed
5. Microsoft SharePoint 2013?

I had a customer this week start asking me questions and getting concerned their e-commerce implementation was running on SharePoint behind the scenes!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0bad4f6-81db-e901-b788-0e6b7115573f
* Version Independent ID: ec7729ea-d9bb-f4bc-1a36-a30d80372f1b
* Content: [Online store publishing architecture - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/retail-online-store-publishing-architecture)
* Content Source: [articles/commerce/dev-itpro/retail-online-store-publishing-architecture.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/retail-online-store-publishing-architecture.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **meeram**

**Comment by kamaybac** [comment]
@andyNewnham , thank you for reporting this issue. I have passed it on for consideration.

**Comment by kamaybac** [comment]
BUG 586408 created to track this issue

**Comment by josaw1** [comment]
@samjarawan can you help with this?

**Comment by mugunthanm** [comment]
Thanks for the feedback, we removed the online store publishing content from the doc site because it's not applicable anymore.
