### ISSUE TITLE
Move content to relevant pages

### ISSUE THREAD

**Issue by ransoentjens** [MicrosoftDocs/dynamics-365-unified-operations-public#3337]
This page is already a couple years old and not all information is up te date. I think it's best to 

- remove this page and, 
- bring the content up-to-date with the latest features
- move the section to the relevant related pages in the "Manage your financials" section

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63bd04cd-0ceb-8d00-8dc0-49d49305d65c
* Version Independent ID: 4ed86b9b-3f3f-0d62-ccfc-67677be18eec
* Content: [Improvements to statement posting functionality - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/statement-posting-eod)
* Content Source: [articles/commerce/statement-posting-EOD.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/statement-posting-EOD.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @josaw1
* Microsoft Alias: **anpurush**

**Comment by kamaybac** [comment]
@ransoentjens , thank you for reporting this issue. I have passed it on for consideration.

**Comment by kamaybac** [comment]
BUG 586413 created to track this issue.

**Comment by josaw1** [comment]
Closed as won't fix.
