### ISSUE TITLE
Project in 'Executing' status

### ISSUE THREAD

**Issue by rat-af** [MicrosoftDocs/dynamics-365-unified-operations-public#334]
Sometime for export projects, an error is displayed in the action centre, then the project stays in 'Executing' status and does not exit this status.  I've had this on a number of occasions, it would be good if this document can detail what to do in that situation.  I simply close the page and remove the history record of that.  I'm assuming it's not really in an executing status.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c6788e8-dfb0-6108-71ae-e265bad542a2
* Version Independent ID: 68a26703-3d8c-4d46-6f3f-37c30aa79373
* Content: [Data management - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/data-entities-data-packages)
* Content Source: [articles/dev-itpro/data-entities/data-entities-data-packages.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/data-entities-data-packages.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by sericks007** [comment]
Thanks for letting us know! We'll look into adding the information you suggested.

**Comment by sericks007** [comment]
Bug 246529 has been logged to track this issue.

**Comment by Sunil-Garg** [comment]
This is an issue with the job which is stuck in executing status. We are looking into a few bugs related to status issues on the job which should help such cases. We will update the documentation if there is any changes we make to the state model of the jobs. Thanks!
