### ISSUE TITLE
Missing information on option to group by purchase agreement

### ISSUE THREAD

**Issue by izjaman** [MicrosoftDocs/dynamics-365-unified-operations-public#3345]
When describing parameters for firming this page does not describe the option to "Group by purchase agreement".

![image](https://user-images.githubusercontent.com/15834482/118357632-7694cc00-b57b-11eb-8065-84e47768f41c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a8e85bd-173e-f04f-7670-4674ef67d233
* Version Independent ID: d1ec81fa-8635-5e85-07af-f5bfe8e21ce6
* Content: [Firm planned orders - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/master-planning/planning-optimization/planned-order-firming)
* Content Source: [articles/supply-chain/master-planning/planning-optimization/planned-order-firming.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/master-planning/planning-optimization/planned-order-firming.md)
* Service: **dynamics-365-supply-chain**
* GitHub Login: @ChristianRytt
* Microsoft Alias: **crytt**

**Comment by tonyafehr** [comment]
@izjaman , thanks for the feedback. @ChristianRytt, please review.

**Comment by ChristianRytt** [comment]
We are planning to include this information as part a larger update for the Firm planned orders page under Planning Optimization. This is expected to happen within a few weeks.
