### ISSUE TITLE
Clarity on link between pick-up delivery mode and retail channel assignment

### ISSUE THREAD

**Issue by andyNewnham** [MicrosoftDocs/dynamics-365-unified-operations-public#3346]
The documentation is not clear on the correct requirements for assigning the retail channel to pick-up delivery modes. And I cannot see this information in any other docs pages.

Following confirmation via Yammer, for 'pickup' delivery modes, the retail channels assigned to that mode of delivery should be locations where that pickup option is available for the pickup. It should not be assigned to channels where the 'order can be placed'. 

So for example, if you have an online store and a retail store. And the retail store is a pick up location, the only channel that should be assigned to the pickup mode of delivery is the retail store, and not the online store.

See yammer thread: https://www.yammer.com/dynamicsaxfeedbackprograms/threads/1206848489422848 

This is quite important as it enables a number of business scenarios and is different to the 'norm' that we are used to when assigning delivery methods.

Other possibly related pages: 
https://docs.microsoft.com/en-us/dynamics365/commerce/customer-orders-overview
https://docs.microsoft.com/en-us/dynamics365/commerce/configure-call-center-delivery

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82b27783-8930-ee46-f914-51a264f7c465
* Version Independent ID: 1692446e-7e56-b710-11fb-933dadb32d41
* Content: [Enable multiple pickup delivery modes for customer orders - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/multiple-pickup-modes)
* Content Source: [articles/commerce/multiple-pickup-modes.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/multiple-pickup-modes.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @hhainesms
* Microsoft Alias: **hhaines**

**Comment by tonyafehr** [comment]
@andyNewnham, thanks for the feedback. @hhainesms, please review.

**Comment by tonyafehr** [comment]
Bug 585608 logged to track this issue.

**Comment by josaw1** [comment]
Topic will be updated later today. Thanks.
