### ISSUE TITLE
will there be any technical issue in case we will create 3 environments (Japan O365 & D365, APAC D365) together under the same tenant? For example if they use outlook integration between Japan O365 and Japan D365, is it going to be a problem for them to add APAC D365 environment under the same tenant? Will APAC D365 do any bad to the existing integration between Japan D365 & O365? Please advise.

### ISSUE THREAD

**Issue by jlabustro** [MicrosoftDocs/dynamics-365-unified-operations-public#3347]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a465cba-da38-a42a-495f-299b90f2d5cf
* Version Independent ID: 4e1952ae-622a-ba1d-5258-dc334c0c35db
* Content: [Multiple LCS projects and environments on one Azure AD tenant - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/implement-multiple-projects-aad-tenant)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/implement-multiple-projects-aad-tenant.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/implement-multiple-projects-aad-tenant.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @ClaudiaBetz-Haubold
* Microsoft Alias: **chaubold**

**Comment by tonyafehr** [comment]
@ClaudiaBetz-Haubold, please review.

**Comment by tonyafehr** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
