### ISSUE TITLE
Add the model descriptor file to source control refers to right-click when right-click is not needed.

### ISSUE THREAD

**Issue by danielzook** [MicrosoftDocs/dynamics-365-unified-operations-public#3348]
https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/version-control-metadata-navigation#add-the-model-descriptor-file-to-source-control

In the section "Add the model descriptor file to source control", step one states "... and then right-click on the metadata folder...", but the next step does not refer to the context menu.  Instead, it states "In the Source Control Explorer toolbar, click Add Item to Folder."

It seems like step 1 should just be "click on the...", not "right-click...".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1486907-b279-d1c2-9cac-acf009a20d26
* Version Independent ID: debe77cc-b887-0033-9c68-92c1d5ba1b39
* Content: [Version control, metadata search, and navigation - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/version-control-metadata-navigation)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/version-control-metadata-navigation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/dev-tools/version-control-metadata-navigation.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @RobinARH
* Microsoft Alias: **jorisde**

**Comment by tonyafehr** [comment]
@jorisdg, please review.

**Comment by jorisdg** [comment]
Pull request sent.

**Comment by RobinARH** [comment]
The updated content will go live later today.
