### ISSUE TITLE
Is an org modelling hierarchy the same as a customer hierarchy?

### ISSUE THREAD

**Issue by andyNewnham** [MicrosoftDocs/dynamics-365-unified-operations-public#3349]
I am confused by why we have two terms for the same thing? This makes training etc. much more difficult.

From what I have seen there is nothing in the D365 application with the name/label of 'Organization modelling hierarchy' - everything just refers to customer hierarchies. Is there a specific reason we use the two different terms or a separation between them that is not clear?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f05e4ac6-efad-298f-9b69-c0be39245891
* Version Independent ID: 2e8b56bf-fb6d-3631-2c33-91bf9a666e29
* Content: [Create org modeling hierarchies for B2B organizations - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/b2b/org-model)
* Content Source: [articles/commerce/b2b/org-model.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/b2b/org-model.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by tonyafehr** [comment]
@andyNewnham, thanks for the feedback. @josaw1, please review.

**Comment by tonyafehr** [comment]
Bug 585601 logged to track this issue.

**Comment by josaw1** [comment]
@anpurush please help with this. Thanks.
