### ISSUE TITLE
Add dimensions to Excel templates is not clear and causing confusion

### ISSUE THREAD

**Issue by trentone1** [MicrosoftDocs/dynamics-365-unified-operations-public#3350]
The following section needs to be re-vamped as the instructions use Over-Layering that is obsolete.
"Add dimensions before Dynamics 365 for Finance and Operations"

Customers are having issues adding dimensions to F&O that they can use with the Excel Add-in.
Doc needs to clearly specify the best steps and if custom dimensions can be used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b6af178-e094-74c1-c692-497b88dd7f1f
* Version Independent ID: 23ca232c-73e0-a88c-0b4a-5931fc7f945a
* Content: [Add dimensions to Excel templates - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/financial/dimensions-overview?source=docs)
* Content Source: [articles/fin-ops-core/dev-itpro/financial/dimensions-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/financial/dimensions-overview.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **rbrow**

**Comment by kamaybac** [comment]
@trentone1 , thank you for reporting this issue. I have passed it on for consideration.

**Comment by kamaybac** [comment]
BUG 586417 created to track this issue

**Comment by RyanCCarlson2** [comment]
@RobinARH and @kfend  this is related to CD https://msdyneng.visualstudio.com/FinOps/_workitems/edit/586417 which has an open PR to remove all the old content. thanks.

**Comment by kfend** [comment]
Changes have published.
