### ISSUE TITLE
customer suggestion

### ISSUE THREAD

**Issue by raulmondra28** [MicrosoftDocs/dynamics-365-unified-operations-public#3351]
After customer set up the return policy  they don't know that they need to run the Retail Initializations after enabling the new features and synced down data again, customer suggest to add this information in the documentation.

Regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2fd324f-8636-61a3-0acb-5f533da93d5c
* Version Independent ID: ff6b4fbd-536c-f514-2848-928d914f1e97
* Content: [Create and update a returns and refunds policy for a channel - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/refund_policy_returns)
* Content Source: [articles/commerce/refund_policy_returns.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/refund_policy_returns.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @ShalabhjainMSFT
* Microsoft Alias: **rapraj**

**Comment by kamaybac** [comment]
@raulmondra28 , thank you for reporting this issue. I have passed it on for consideration.

**Comment by kamaybac** [comment]
BUG 586419 created to track this issue

**Comment by kamaybac** [comment]
The topic has been updated.
