### ISSUE TITLE
Missing steps

### ISSUE THREAD

**Issue by danielzook** [MicrosoftDocs/dynamics-365-unified-operations-public#3352]
There are some steps in the deployment that are missing in the article.  (This may not be a complete list...)

- "Publish this environment to Dynamics 365 home page"
- "Configure Power Platform Environment"
- Signature

It would be helpful if all of the steps were listed in the article with short explanations.  

Also, step 7 states: 

> Select from a list of available AOT packages (customization packages) on the Software Deployable tabs in the Asset Library if you want to apply customizations. Only packages generated from a build environment on version 8.1 and above should be selected. Applying a package from an incompatible version will have an adverse effect on the environment.

... but I don't recall that step being in the deployment when I ran it just now.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9d684ec-511b-b80e-bc2f-700804abe720
* Version Independent ID: 72f50796-990d-d9c0-7e52-52f12d24af90
* Content: [Deploy a new environment - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/deployenvironment-newinfrastructure)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/deployenvironment-newinfrastructure.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/deployment/deployenvironment-newinfrastructure.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @rashmansur
* Microsoft Alias: **rashmim**

**Comment by tonyafehr** [comment]
@danielzook, thanks for the feedback. @rashmansur, please review and consider making updates.

**Comment by tonyafehr** [comment]
Bug 585606 logged to track this issue.
