### ISSUE TITLE
Missing controllers

### ISSUE THREAD

**Issue by andyNewnham** [MicrosoftDocs/dynamics-365-unified-operations-public#3353]
It would be great if this documentation could be updated to include some of the missing or recently released controllers, such as;

- Wishlist (Commerce Lists)
- Business Partners
- Inventory Inbound/Outbound Documents
- Task Management (Checklists)
- Recommendations(?)
- It would be useful if GetProductAvailabilty API's are listed as deprecated (or just removed) - at least I believe they are deprecated?

(there may be more I haven't picked up on)

If course what we would all really love is full API documentation with req/resp examples and test stubs - but I suspect that is a bit much to ask!

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d421ed99-0ff4-6ef0-543e-894f4f30f00d
* Version Independent ID: 2b4d9bab-0003-2123-d236-4e99b5f89eb3
* Content: [Commerce Scale Unit customer and consumer APIs - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/retail-server-customer-consumer-api)
* Content Source: [articles/commerce/dev-itpro/retail-server-customer-consumer-api.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/retail-server-customer-consumer-api.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by tonyafehr** [comment]
@andyNewnham, thanks for the great feedback. @mugunthanm, please review.

**Comment by tonyafehr** [comment]
Bug 585611 logged to track this issue.

**Comment by tonyafehr** [comment]
@andyNewnham, your feedback has generated a discussion about adding this content. I am closing this request, but please know that we're working on plans to make these updates in the future. Thank you!
