### ISSUE TITLE
why is the field Mask ID not explained?

### ISSUE THREAD

**Issue by TommyLanger** [MicrosoftDocs/dynamics-365-unified-operations-public#3354]
why is the field Mask ID not explained?
[Enter feedback here]
why is the field Mask ID not explained?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 110f5f5f-a8a5-29f1-81f7-1af929cd3644
* Version Independent ID: eedf7d61-9615-2c54-437d-aac1996faae5
* Content: [Maintain barcode types - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/inventory/tasks/maintain-barcode-types#feedback)
* Content Source: [articles/supply-chain/inventory/tasks/maintain-barcode-types.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/inventory/tasks/maintain-barcode-types.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @perlynne
* Microsoft Alias: **perlynne**

**Comment by tonyafehr** [comment]
@TommyLanger, thanks for the suggestion. @perlynne, please review.

**Comment by tonyafehr** [comment]
Bug 585607 logged to track this issue.

**Comment by tonyafehr** [comment]
This explanation has been added. Thanks!
