### ISSUE TITLE
Further Examples Needed

### ISSUE THREAD

**Issue by dgriffiths-bd** [MicrosoftDocs/dynamics-365-unified-operations-public#3355]
There is no example of how to use a data-action from inside the module code. It talks about how to register it, but once registered how do we then get the underlying data?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90329178-f512-40f7-84c2-1a434a0588bb
* Version Independent ID: d9059d68-ba79-2fdc-6d12-36da4b1fa16a
* Content: [Page load data actions - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/e-commerce-extensibility/page-load-data-action)
* Content Source: [articles/commerce/e-commerce-extensibility/page-load-data-action.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/e-commerce-extensibility/page-load-data-action.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @samjarawan
* Microsoft Alias: **samjar**

**Comment by tonyafehr** [comment]
@dgriffiths-bd, thanks for the feedback. @samjarawan, please review.

**Comment by tonyafehr** [comment]
Bug 585612 logged to track this issue.

**Comment by samjarawan** [comment]
Hi, if you look at the "Event based data actions" document you'll see a code sample for embedding a data action call from within a modules code: https://docs.microsoft.com/en-us/dynamics365/commerce/e-commerce-extensibility/event-based-data-actions .

I hope that helps,
Sam

**Comment by dgriffiths-bd** [comment]
Hi Sam,

I was trying to help you improve the documentation, not asking for help
specifically with an issue.

... And I'm afraid the link you sent didn't help as it is not an event
based data action I'm implementing, it's a page load data action. Event
based data actions are called in a very different way to page load data
actions - this is not clear from the documentation and I had to learn
through trial and error.

I think the documentation would be improved if you describe the lines of
code that also need to be added into {module}.data.ts to be able to call a
page load data action and successfully leverage it's caching mechanism.

I hope that helps,

*Daniel Griffiths*


T: +44 (0) 1202 800 994
M: +44 (0) 7756 393 728


BournemouthDigital.co.uk
