### ISSUE TITLE
Where is the "Enable POS recommendations." ?

### ISSUE THREAD

**Issue by kurthatlevik-inspirit365** [MicrosoftDocs/dynamics-365-unified-operations-public#3357]
If you look at https://docs.microsoft.com/en-us/dynamics365/commerce/product there is a text saying:
Configure Commerce to enable POS recommendations
To set up product recommendations, follow these steps:
...
**Go to Commerce parameters, select Machine-learning, select Yes under Enable POS recommendations.**
---
The problem is that I cannot seem to find any tabs in the Commerce parameters named "Machine-learning" or any possibility to "Enable POS recommendations."

I'm using V 10.0.19

Can you check if the docs here is right ?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04a5b479-108b-ca8f-84f0-7e8907f5260b
* Version Independent ID: bbd8c53a-557a-69a9-7c25-4836ceb6ead0
* Content: [Add product recommendations on POS - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/product)
* Content Source: [articles/commerce/product.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/product.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @bebeale
* Microsoft Alias: **asharchw**

**Comment by tonyafehr** [comment]
@kurthatlevik-inspirit365, thanks for the feedback. @josaw1, can you help with this issue.

**Comment by bsokolov** [comment]
Hi @kurthatlevik-inspirit365. Indeed the documentation is being updated to reflect the latest changes in the user experience. The new experience goes through the "Feature Management" workspace. When you navigate to it, please search for "Product Recommendations" and "Personalized Recommendations" features and enable them.

As a reminder, Recommendations are an omnichannel solution and do not need to be enabled specifically for POS. More details here - https://docs.microsoft.com/en-us/dynamics365/commerce/product-recommendations.
