### ISSUE TITLE
Product recommendation

### ISSUE THREAD

**Issue by kurthatlevik-inspirit365** [MicrosoftDocs/dynamics-365-unified-operations-public#3358]
I think it would be fair to inform here that product recommendations are requiring an additional SKU/license : "Dynamics 365 Commerce Recommendations".  This because the licensing costs for ML/AI recommendations is quite significant, and there are limitations to the number of transactions per month that is included.

So a reference to the D365 Licensing guide would solve this. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a768396-fbe8-3662-b70a-60a728b09e98
* Version Independent ID: c55b7310-ee39-7d03-42d2-cb33490e217e
* Content: [Product recommendations overview - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/product-recommendations)
* Content Source: [articles/commerce/product-recommendations.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/product-recommendations.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @moonma
* Microsoft Alias: **moonma**

**Comment by tonyafehr** [comment]
@kurthatlevik-inspirit365, we'll consider making this change. @josaw1, please help with this. Thanks!

**Comment by josaw1** [comment]
@moonma can you please help?

**Comment by moonma** [comment]
I think it makes sense to at least mention that it's an additional SKU. As for pointing them to a public licensing doc... I don't know where such a document lives but will work with our biz team to find out.

**Comment by tonyafehr** [comment]
Bug 585602 logged to track this issue.

**Comment by bebeale** [comment]
Hey @tonyafehr Are you aware of what licensing doc we can reference? I'm happy to make the change quick and easy. But I don't have a reference.

**Comment by tonyafehr** [comment]
@kurthatlevik-inspirit365, the information you are looking for should be in the [Licensing Guide](https://go.microsoft.com/fwlink/?LinkId=866544).
