### ISSUE TITLE
wrong max value for utcdatetime

### ISSUE THREAD

**Issue by yeltson** [MicrosoftDocs/dynamics-365-unified-operations-public#3364]
the min and max value for utcdatetime is given the same value
_"The minimum value is 1900-01-01T00:00:00, and the maximum value is 1900-01-01T00:00:00"_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65d8f16f-8485-af7c-328f-d93e4a9f9c0a
* Version Independent ID: 82ec6b85-db95-7c4b-1f67-37395a137206
* Content: [X++ Primitive data types - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-ref/xpp-data-primitive)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-ref/xpp-data-primitive.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/dev-ref/xpp-data-primitive.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @RobinARH
* Microsoft Alias: **rhaertle**

**Comment by sericks007** [comment]
@yeltson, thanks for providing this feedback.

@RobinARH, please review.

**Comment by sericks007** [comment]
Bug 588188 has been logged to track this issue.

**Comment by RobinARH** [comment]
I updated the topic and the new content will go live later today.
