### ISSUE TITLE
Page not updated since 2017

### ISSUE THREAD

**Issue by gagangarg** [MicrosoftDocs/dynamics-365-unified-operations-public#3366]
The page indicates that Commerce Scale unit supports MPOS but I think it now mandatory for both MPOS and CPOS. Wondering if there has been no change in architecture since 2017 and if this can be updated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d8a2537-5c77-cb33-2bf5-0788c584b7c6
* Version Independent ID: b323e224-a8c7-0fa8-37a0-6f8382e32804
* Content: [Commerce Scale Unit architecture - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/retail-server-architecture)
* Content Source: [articles/commerce/dev-itpro/retail-server-architecture.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/retail-server-architecture.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **meeram**

**Comment by sericks007** [comment]
@gagangarg, thanks for providing this feedback.

@RobinARH, please review.

**Comment by sericks007** [comment]
Bug 588191 has been logged to track this issue.

**Comment by mugunthanm** [comment]
Updated the document, hopefully it will reviewed and published soon.

**Comment by RobinARH** [comment]
We published the update in June.
