### ISSUE TITLE
Where should the latest version of SSMS be installed?

### ISSUE THREAD

**Issue by danielzook** [MicrosoftDocs/dynamics-365-unified-operations-public#3367]
This article has an important note that states: "It's very important that you install the latest version of SQL Server Management Studio before you start this process: Download SQL Server Management Studio."

... but it doesn't specify *where* this version should be installed.  On the D365 Dev VM?  On the machine where the AX database is located?  Both?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ae815e8-03c2-0769-5e6a-e36f57244651
* Version Independent ID: 5304a30a-ca52-0bb6-99c3-c7a5bb8ab36e
* Content: [Upgrade from AX 2012 - Data upgrade in development environments - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/data-upgrade-2012)
* Content Source: [articles/fin-ops-core/dev-itpro/migration-upgrade/data-upgrade-2012.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/migration-upgrade/data-upgrade-2012.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by sericks007** [comment]
@danielzook, thanks for providing this feedback.

@laneswenka, please review and update the documentation as needed.

**Comment by sericks007** [comment]
Bug 10059249 has been logged to track this issue.
