### ISSUE TITLE
Export to Data Lake Installed but Enablement wont persist

### ISSUE THREAD

**Issue by geortan** [MicrosoftDocs/dynamics-365-unified-operations-public#3368]
I have installed the Export to Data Lake Add-in to my uat environment. I have then proceeded to set up the data connections necessary for the export to data lake function. I get a successful Test to Azure Key Vault as well as to Azure Storage. I click the "Enable Data Lake Integration" toggle to yes and then save. If I refresh the screen the toggle is then set back to No? Furthermore when go to add table to the export to Data Lake they attempt to initialize and then error out with Error (StatusCode:432). Please help.

**Comment by sericks007** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
