### ISSUE TITLE
Need comprehensive list of Data Entity loading order - templates do not cover enough

### ISSUE THREAD

**Issue by ronsonntag54** [MicrosoftDocs/dynamics-365-unified-operations-public#3369]
[Enter feedback here]
The loading order for Data Entities is critical. Even though Microsoft indicates that the default templates contain the loading order for Data Entities, many entities are missing and some have the wrong loading order.

The reports section of this page should list a report that comprehensively presents the Unit, Level, and Sequence for each Data Entity and this needs to be kept up to date by Microsoft. This missing piece of information is critical for smooth data migration and governs data integrations as well when multiple Data Entities are involved.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d5216b9-6405-4bfc-04ad-dd9e8ec43a02
* Version Independent ID: c32d61d8-87b9-071c-d402-fcc74e21ddb7
* Content: [Find information about standard data entities - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/data-entities-report)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/data-entities-report.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/data-entities-report.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **rhaertle**

**Comment by sericks007** [comment]
@ronsonntag54, thank you for providing this feedback.

@RobinARH, please review.

**Comment by sericks007** [comment]
Bug 588194 has been logged to track this issue.

**Comment by ronsonntag54** [comment]
I opened this in May and it is now November. The best that Microsoft can do on this issue in 5 months is close a duplicate item?

**Comment by sericks007** [comment]
@Sunil-Garg, please review and address the feedback.

**Comment by Sunil-Garg** [comment]
@***@***.***> pls have @***@***.***> as the owner for Data management areas.

Thanks.

**Comment by sericks007** [comment]
@peakerbl, please review and address this feedback.

**Comment by josaw1** [comment]
Closed as won't fix.
