### ISSUE TITLE
POS not Pos

### ISSUE THREAD

**Issue by thedynamicsgirl** [MicrosoftDocs/dynamics-365-unified-operations-public#3370]
[HQ Device Setup

For Store Commerce, a new application type named Store Commerce is added to Retail and Commerce > Channel Setup > Pos Setup > ……. Can we change the Pos to POS???]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45ebad3c-1d63-3e3d-4b0c-84acb7cb84ef
* Version Independent ID: b5a17324-a2fc-48a6-28e0-db115a722469
* Content: [Store Commerce app in Microsoft Dynamics 365 Commerce (Preview) - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/store-commerce?WT.mc_id=linkedin)
* Content Source: [articles/commerce/dev-itpro/store-commerce.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/store-commerce.md)
* Service: **dynamics-365-commerce**
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by sericks007** [comment]
@thedynamicsgirl, thanks for pointing that out!  I've changed that reference to "POS".  That change will be published later today.  Thanks again!
