### ISSUE TITLE
UAE region availability

### ISSUE THREAD

**Issue by Praveenkumarboy** [MicrosoftDocs/dynamics-365-unified-operations-public#3371]
Provide some more information on other regions availability roadmap.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df8e9efc-9258-3876-e05f-20d35c907274
* Version Independent ID: 4b5041ec-4a48-0565-e47a-b972e65a6d60
* Content: [System requirements and prerequisites - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/requirements-and-prerequisites)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/requirements-and-prerequisites.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/dual-write/requirements-and-prerequisites.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @sabinn-msft
* Microsoft Alias: **sabinn**

**Comment by sericks007** [comment]
@Praveenkumarboy, thank you for providing this feedback.

@sabinn-msft, please review and update the content appropriately.

**Comment by sericks007** [comment]
Bug 588199 has been logged to track this issue.

**Comment by sabinn-msft** [comment]
@Praveen - We already have an email thread on this, right? Not sure why it warrants a duplicate effort.

**Comment by sericks007** [comment]
The content was updated.
