### ISSUE TITLE
Note in "Download and restore the backup to the development environment" section is out of date

### ISSUE THREAD

**Issue by danielzook** [MicrosoftDocs/dynamics-365-unified-operations-public#3374]
https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/data-upgrade-2012#download-and-restore-the-backup-to-the-development-environment

The note at the top of this section states "Developer environments that are hosted by Microsoft have limited drive space."  As of November 2020, Microsoft no longer hosts Dev environments and instead customers need to pay to have Azure hosting for Dev environments, per the notice in LCS: "Sandbox Develop and Test environments will only be deployable as Cloud-hosted environments after November 1, 2020."  which links to this: https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/cloud-deployment-overview#remote-desktop

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ae815e8-03c2-0769-5e6a-e36f57244651
* Version Independent ID: 5304a30a-ca52-0bb6-99c3-c7a5bb8ab36e
* Content: [Upgrade from AX 2012 - Data upgrade in development environments - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/data-upgrade-2012)
* Content Source: [articles/fin-ops-core/dev-itpro/migration-upgrade/data-upgrade-2012.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/migration-upgrade/data-upgrade-2012.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by sericks007** [comment]
@danielzook, thank you for providing this feedback.

@laneswenka, please review and update the content, as needed.

**Comment by sericks007** [comment]
Bug 10059276 has been logged to track this issue.
