### ISSUE TITLE
Incorrect Key Vault Secret Config

### ISSUE THREAD

**Issue by curtiswatson** [MicrosoftDocs/dynamics-365-unified-operations-public#3375]
Under Procedure 2, step 4, it states incorrectly that the "connection string" should be placed under the key vault secret when it should be the "key 1" value.

"Select BE-key vault > Secrets > Generate/Import. Enter a name for your secret, and paste the event grid connection string that you saved earlier."

should be

"Select BE-key vault > Secrets > Generate/Import. Enter a name for your secret, and paste the event grid key 1 string that you saved earlier."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 055168f2-4423-1246-9663-1d0b14696666
* Version Independent ID: 2ec22b82-5bc0-bdb1-b630-ffcbaf1180dd
* Content: [Business events and Azure Event Grid - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/business-events/how-to/how-to-eventgrid)
* Content Source: [articles/fin-ops-core/dev-itpro/business-events/how-to/how-to-eventgrid.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/business-events/how-to/how-to-eventgrid.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by sericks007** [comment]
@curtiswatson, thank you for providing this feedback!

@Sunil-Garg, please review and update the content, as needed.

**Comment by sericks007** [comment]
Bug 588200 has been logged to track this issue.

**Comment by jaredha** [comment]
Submitted PR 14305 to make this change.

**Comment by sericks007** [comment]
Thanks for updating the content, @jaredha!

This change will be published later today.
