### ISSUE TITLE
Conflicting directions between this article and another article this one refers to

### ISSUE THREAD

**Issue by danielzook** [MicrosoftDocs/dynamics-365-unified-operations-public#3376]
In the section "Download and restore the backup to the development environment"
https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/data-upgrade-2012#download-and-restore-the-backup-to-the-development-environment

The last sentence states: "Finally, rename the newly restored AX 2012 database AXDB."

However, in the next section, titled "Run the data upgrade deployable package", you refer to this article for more information:
https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/upgrade-data-to-latest-update

In this article, the instructions state: "...name your new database imported_new."
(This is step 2 in the "Upgrade the database" section: https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/upgrade-data-to-latest-update#upgrade-the-database)

May I suggest an alignment between these two articles so that they are consistent with what the restored database should be called?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ae815e8-03c2-0769-5e6a-e36f57244651
* Version Independent ID: 5304a30a-ca52-0bb6-99c3-c7a5bb8ab36e
* Content: [Upgrade from AX 2012 - Data upgrade in development environments - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/data-upgrade-2012)
* Content Source: [articles/fin-ops-core/dev-itpro/migration-upgrade/data-upgrade-2012.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/migration-upgrade/data-upgrade-2012.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by sericks007** [comment]
@danielzook, thank you for providing this feedback!

@laneswenka, please review and update the content, as needed.

**Comment by sericks007** [comment]
Bug 10059315 has been logged to track this issue.
