### ISSUE TITLE
Power BI setup on Azure is out of date

### ISSUE THREAD

**Issue by tacklers** [MicrosoftDocs/dynamics-365-unified-operations-public#3377]
The text refers 
Click Settings > Required permissions > Add > Select an API > Power BI Service (Power BI).
Settings does not now exist
It should be API Permissions>Add a permission>Find Power BI Service etc.
Same thing with Settings Keys, it should be certificates and secrets. 
Thanks Richard 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2213414-926d-10e1-538b-efef09dc0181
* Version Independent ID: 03be53f7-c305-cb02-7627-2ea4f1c01bd4
* Content: [Configure PowerBI.com integration - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/configure-power-bi-integration)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/configure-power-bi-integration.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/analytics/configure-power-bi-integration.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by sericks007** [comment]
@tacklers, thank you for providing this feedback!

@MilindaV2, please review and update the content.

**Comment by tacklers** [comment]
Hi,

Please also correct the experience for adding tiles and dashboards as it’s also changed. See attached.

Cheers, Richard

**Comment by sericks007** [comment]
Bug 588202 has been logged to track this issue.

**Comment by josaw1** [comment]
Closing as won't fix.
