### ISSUE TITLE
List of services for a self-service environment are different

### ISSUE THREAD

**Issue by jopankow** [MicrosoftDocs/dynamics-365-unified-operations-public#3378]
Hello team! I have a few suggestions for this page:

1. For a self-service environment, the only options available are: AX, DIXF and MR. Please update list of services. For customers still not on self-service, you may wish to maintain two separate lists.
2. It would also be good to add details about what each selection does. For example, the "AX" option would be the equivalent of restarting the AOS (or using the "IIS" option for a non-self-service environment).
3. Since the Batch service is no longer an option for self-service, it would be good to link to details on how to address a scenario where a batch restart would have been used. One suggestion is to link to this content: https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/batch-abort

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9452234-62df-d7ed-1243-4f2a14553df3
* Version Independent ID: 14f785e5-da29-5cc9-bd8a-d548c93d15e9
* Content: [Restart environment services - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/restart-environment-services)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/restart-environment-services.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/lifecycle-services/restart-environment-services.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by sericks007** [comment]
@jopankow, thank you for providing these suggestions!

@laneswenka, please review and update the content, as suggested.

**Comment by sericks007** [comment]
Bug 10059327 has been logged to track this issue.

**Comment by jopankow** [comment]
FYI I did find a Doc for which services can be restarted on a self-service environment: https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/maintenanceoperationsguide-newinfrastructure#restart-services 

Maybe we can combine the two articles (the original one I mentioned plus this one) to avoid people finding just one or the other and creating confusion?
