### ISSUE TITLE
Distribution - Ledger Account

### ISSUE THREAD

**Issue by CCollum3984** [MicrosoftDocs/dynamics-365-unified-operations-public#338]
I am able to get all the fields to work except for the Ledger Account.  I get an error that says "The file cannot be imported because the following column headings in the file do not match the expected column headings: Ledger account"

What should the header be?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18d2d376-dcb9-e41f-9792-8963948f0cc3
* Version Independent ID: 03f399c5-4bf6-ca56-7eff-313d8d6a65c4
* Content: [Plan for one-time vendors in the public sector - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/public-sector/plan-one-time-vendors-public-sector)
* Content Source: [articles/financials/public-sector/plan-one-time-vendors-public-sector.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/public-sector/plan-one-time-vendors-public-sector.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @ShylaThompson
* Microsoft Alias: **brpotter**

**Comment by kfend** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support).
