### ISSUE TITLE
Does the attract export contain resumes? This isn't mentioned in the doc. Thanks.

### ISSUE THREAD

**Issue by jprattCanada** [MicrosoftDocs/dynamics-365-unified-operations-public#3381]
Does the attract export contain resumes? This isn't mentioned in the doc. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a56a5922-3d15-f788-ba50-891221209439
* Version Independent ID: 64297d62-f194-00f3-9daf-badc6ce88b09
* Content: [Export data from Attract and Onboard - Talent | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/talent/attract-onboard-export-data)
* Content Source: [articles/talent/attract-onboard-export-data.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/talent/attract-onboard-export-data.md)
* Service: **dynamics-365-talent**
* Product: ****
* Technology: ****
* GitHub Login: @andreabichsel
* Microsoft Alias: **anbichse**

**Comment by jprattCanada** [comment]
If the export doesn't included resumes, is there a tool to extract them? thanks.

**Comment by RobinARH** [comment]
@tonyafehr - Hi Tonya - Can you take a look? Thanks.

**Comment by hasrivas** [comment]
In summary, we do export all candidate attachments as part of the data export, the location of the attachment depends on a couple of factors: a) if the candidate hasnt been deleted b) how was candidate added to a job. We can update the doc to make it clearer.

@tonyafehr can we add to this doc in the table describing the zip folder contents, for the line-item: "job openings" - "All created jobs. Deleted jobs aren't exported. The sub-folders contain candidate applications, with sub-folders for candidate application attachments and offer packages, where applicable. If the candidates had themselves applied for the job via the Talent jobs portal using attachments, the candidate applications sub-folder will contain those attachments used at the time of application as well. If the candidate was manually added to the job, to find the associated attachments for the candidates, please use the Candidates folder in the root of the downloaded zip to locate the candidate using the "Auto-number" value found in the candidate json in the job applications sub-folder. The candidate sub-folder will not be present if the candidate was deleted from the job."

**Comment by hasrivas** [comment]
Assigning the issue back to @tonyafehr for the corresponding doc update.

**Comment by tonyafehr** [comment]
This topic will be updated later today.
