### ISSUE TITLE
Missing cookie lifetimes

### ISSUE THREAD

**Issue by jdippenaar** [MicrosoftDocs/dynamics-365-unified-operations-public#3382]
Would be really helpful to get the cookie lifetimes like here:
https://docs.microsoft.com/en-us/powerapps/maker/portals/admin/portal-cookies

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3fa3aab-af7f-f64a-9e2d-a21ea89bb8a9
* Version Independent ID: f83579fe-bc30-0c4d-2b75-84db59835e16
* Content: [Cookie compliance - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/cookie-compliance)
* Content Source: [articles/commerce/cookie-compliance.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/cookie-compliance.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @BrianShook
* Microsoft Alias: **brshoo**

**Comment by RobinARH** [comment]
@BrianShook - Can you take a look? Thanks.

**Comment by RobinARH** [comment]
Created bug 594446 to track this issue.

**Comment by RobinARH** [comment]
Cookie lifetime has been added to the doc.
