### ISSUE TITLE
Please update SSRS information

### ISSUE THREAD

**Issue by jopankow** [MicrosoftDocs/dynamics-365-unified-operations-public#3383]
Hello,

The "SQL Server Reporting Services" section here:

https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/hardware-sizing-on-premises-environments#sql-server-reporting-services

Is no longer accurate with the new support for SSRS high availability as described here:

https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/onprem-ssrsha

Also tagging @faix for awareness

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8dadf2b-038b-f098-8670-ca580a3cc442
* Version Independent ID: 04c44292-1ebf-a7e1-dddb-3b57a1474c80
* Content: [Hardware sizing requirements for on-premises environments - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/hardware-sizing-on-premises-environments#sql-server-reporting-services)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/hardware-sizing-on-premises-environments.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/hardware-sizing-on-premises-environments.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @sericks007
* Microsoft Alias: **chwolf**

**Comment by RobinARH** [comment]
@faix @sericks007 - Is this fixed now? If so, please close this issue. Thanks!

**Comment by faix** [comment]
yes, its addressed by the linked PR @RobinARH . I don't have permissions to close.

**Comment by RobinARH** [comment]
Thanks for the quick reply, I'll close it.
