### ISSUE TITLE
Incorrect place holder for portal URL

### ISSUE THREAD

**Issue by atardiftmx** [MicrosoftDocs/dynamics-365-unified-operations-public#3384]
In the section : https://docs.microsoft.com/en-us/dynamics365/supply-chain/procurement/set-up-maintain-vendor-collaboration#branch-to-provision-new-users

Step 5 recommends inserting a place holder for the portal URL. It is not valid. it should be without any space. 

Correct place holder: %portalURL%

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cd5c06b-a32f-0052-1fea-ed75bc64bdbb
* Version Independent ID: 0b2f2773-60d1-4522-3e0b-00f0801fed1f
* Content: [Set up and maintain vendor collaboration - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/procurement/set-up-maintain-vendor-collaboration)
* Content Source: [articles/supply-chain/procurement/set-up-maintain-vendor-collaboration.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/procurement/set-up-maintain-vendor-collaboration.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @kamaybac
* Microsoft Alias: **dabourq**

**Comment by kamaybac** [comment]
@atardiftmx , thank you for reporting this issue. I have updated the file and the change should go live later today.
