### ISSUE TITLE
This link to the documentation is no longer valid

### ISSUE THREAD

**Issue by TimoTenni** [MicrosoftDocs/dynamics-365-unified-operations-public#3385]
For more information, see SAF-T - VMI.

The updated one is https://www.vmi.lt/evmi/en/home 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 132df4cc-1a93-896a-5551-dbed3cc7f4af
* Version Independent ID: b37b12a7-ea57-57f3-59c4-585630c85b40
* Content: [Standard Audit File for Tax (SAF-T) for Lithuania - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/emea-ltu-saf-t)
* Content Source: [articles/finance/localizations/emea-ltu-saf-t.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/emea-ltu-saf-t.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @liza-golub
* Microsoft Alias: **elgolu**

**Comment by RobinARH** [comment]
@liza-golub and @kfend  - Can you verify and replace the link? Thanks.

**Comment by RobinARH** [comment]
Created bug 594447 to track this issue.

**Comment by RobinARH** [comment]
The link is fixed.
