### ISSUE TITLE
Documentation incorrect

### ISSUE THREAD

**Issue by miursu** [MicrosoftDocs/dynamics-365-unified-operations-public#3387]
Dear Team
Please correct the documentation, section
Create a number sequence for the simulated general journal transfer
Go to General ledger > Ledger setup > General ledger parameters.
On the Number sequences tab, set the sequence to Simulation general journal transfer.

There is no sequence to  Simulation general journal transfer option in GL parameters. The user needs to create a continuous number sequence from Organization administration> Number sequences> Number sequences and then attach it to a daily journal name.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2e5b9cc-1005-f2c4-6371-5c509166feb1
* Version Independent ID: d3529cb4-e0c6-4c69-f081-c4c2ea43f38b
* Content: [General ledger simulations (Italy) - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/emea-ita-exil-general-ledger-simulations)
* Content Source: [articles/finance/localizations/emea-ita-exil-general-ledger-simulations.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/emea-ita-exil-general-ledger-simulations.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @Anasyash
* Microsoft Alias: **ilyako**

**Comment by RobinARH** [comment]
@Anasyash - Can you take a look? Thanks.

**Comment by Anasyash** [comment]
Hello. When you enable the feature **General ledger simulations**, you should be able to see the line **Simulation general journal transfer**
