### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by andreash1** [MicrosoftDocs/dynamics-365-unified-operations-public#339]
[Enter feedback here]

Hi, please correc the first link:
paragraph:
Typically, cloud-hosted environments are used to provide more control over a development or build environment. For more details, see Choose a data integration (import/export) strategy.

wrong link:
https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/integration-overview

correct link:
https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-user-guide

Thanks,
Andreas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b9cd3cc-5f85-3f61-4670-83e050cb30e4
* Version Independent ID: 313ff91b-902d-7f27-f9b1-6aa4d2370945
* Content: [Set up new environments, VSTS, and branches for Retail projects - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/dev-itpro/new-environments-visual-studio-teams-branch-retail-projects)
* Content Source: [articles/retail/dev-itpro/new-environments-visual-studio-teams-branch-retail-projects.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/dev-itpro/new-environments-visual-studio-teams-branch-retail-projects.md)
* Service: **dynamics-365-retail**
* GitHub Login: @andreash1
* Microsoft Alias: **andreash**

**Comment by kfend** [comment]
Thanks for the feedback. We have updated the topic.
