### ISSUE TITLE
Where is 'get-active-cart'?

### ISSUE THREAD

**Issue by ItCommitsTheCode** [MicrosoftDocs/dynamics-365-unified-operations-public#3391]
This article mentions the data action `get-active-cart`, yet this action is not distributed with @msdyn365-commerce-modules.  Curious.  Perhaps its alternative can be recommended?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6b45b40-e138-dfda-8228-095eec6eda77
* Version Independent ID: c457312c-aea5-eb84-ed5b-e2f318848d90
* Content: [Core data actions - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/e-commerce-extensibility/core-data-actions)
* Content Source: [articles/commerce/e-commerce-extensibility/core-data-actions.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/e-commerce-extensibility/core-data-actions.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @samjarawan
* Microsoft Alias: **samjar**

**Comment by tonyafehr** [comment]
@josaw1, please review.

**Comment by josaw1** [comment]
@samjarawan can you please review this?

**Comment by josaw1** [comment]
BUG 649791 created to track.

**Comment by samjarawan** [comment]
You can find most of the core data actions in the \\node\_modules\\@msdyn365-commerce-modules and \\node\_modules\\@msdyn365-commerce directories. Many can be found under the \\node\_modules\\@msdyn365-commerce-modules\\retail-actions\\dist\\lib directory or some within specific sub directories such as the cart state data actions which can be found under the \\node\_modules\@msdyn365-commerce\global-state\src\cart-state directory.

We'll update the documentation to call out this additional directories.
