### ISSUE TITLE
"Match all price groups"-feature is not mentioned in the discount documentation

### ISSUE THREAD

**Issue by mueckeflo** [MicrosoftDocs/dynamics-365-unified-operations-public#3394]
Hi,
This article doesn't yet contain information regarding the "Match all price groups" feature:

![image](https://user-images.githubusercontent.com/3601605/121491124-f58fef80-c9d5-11eb-90cb-aedfa29346bb.png)

Can you please add this to the article?

Thanks and best regards,
Florian

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa683505-0769-81b1-0f59-ece418a52f82
* Version Independent ID: 3eb28e2d-7329-c35a-fd9d-190d83cf4f40
* Content: [Define channel-specific discounts - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/define-channel-specific-discounts)
* Content Source: [articles/commerce/define-channel-specific-discounts.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/define-channel-specific-discounts.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @scott-tucker
* Microsoft Alias: **scotttuc**

**Comment by tonyafehr** [comment]
@josaw1, please review.

**Comment by josaw1** [comment]
Hi @mueckeflo -- you can find the information you requested in the topic [Retail discounts](https://docs.microsoft.com/en-us/dynamics365/commerce/retail-discounts-overview). Thanks.
