### ISSUE TITLE
Powerplatform integration on Tier1 machines

### ISSUE THREAD

**Issue by nspiteri** [MicrosoftDocs/dynamics-365-unified-operations-public#3395]
I tried following the options for setting up Powerplatform integration.  The environment was deployed but there was no new dataverse environment created.  Also when I go to environment details, I do not see the option to set it up.

The machine I deployed was a tier 1, Customer Managed.  If I check our tier 2, self-service environment, I do have the option to set up Powrplatform integration in lcs.

Can you clarify if the option is supposed to work for both tiers?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39b247a8-1e40-07d0-f44b-46f3f362a02d
* Version Independent ID: 09725d7e-90ea-f6a9-3edb-28ff4bcc7510
* Content: [Microsoft Power Platform integration with Finance and Operations apps - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/power-platform/overview#enabling-the-microsoft-power-platform-integration)
* Content Source: [articles/fin-ops-core/dev-itpro/power-platform/overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/power-platform/overview.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by Sunil-Garg** [comment]
@***@***.***> can you have a look pls?

________________________________
From: Norbert Spiteri ***@***.***>
Sent: Thursday, June 10, 2021 1:58:08 AM
To: MicrosoftDocs/dynamics-365-unified-operations-public ***@***.***>
Cc: Sunil Garg ***@***.***>; Mention ***@***.***>
Subject: [MicrosoftDocs/dynamics-365-unified-operations-public] Powerplatform integration on Tier1 machines (#3395)


I tried following the options for setting up Powerplatform integration. The environment was deployed but there was no new dataverse environment created. Also when I go to environment details, I do not see the option to set it up.

The machine I deployed was a tier 1, Customer Managed. If I check our tier 2, self-service environment, I do have the option to set up Powrplatform integration in lcs.

Can you clarify if the option is supposed to work for both tiers?

________________________________
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

  *   ID: 39b247a8-1e40-07d0-f44b-46f3f362a02d
  *   Version Independent ID: 09725d7e-90ea-f6a9-3edb-28ff4bcc7510
  *   Content: Microsoft Power Platform integration with Finance and Operations apps - Finance & Operations | Dynamics 365<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fdynamics365%2Ffin-ops-core%2Fdev-itpro%2Fpower-platform%2Foverview%23enabling-the-microsoft-power-platform-integration&data=04%7C01%7Csunilg%40microsoft.com%7Cbc3f8548eac34d546ccf08d92bedde64%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637589122908619055%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=iylk0yxeZ3P2UcQsYcq3xLcJo%2BNGmakS3ntXc1ImTPg%3D&reserved=0>
  *   Content Source: articles/fin-ops-core/dev-itpro/power-platform/overview.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FDynamics-365-Unified-Operations-Public%2Fblob%2Fmain%2Farticles%2Ffin-ops-core%2Fdev-itpro%2Fpower-platform%2Foverview.md&data=04%7C01%7Csunilg%40microsoft.com%7Cbc3f8548eac34d546ccf08d92bedde64%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637589122908629042%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=YiB3vYbAYfuD48h%2B7VBbuGia0j63z6makBINiOHHRIc%3D&reserved=0>
  *   Service: dynamics-365-cross-app
  *   Product: ****
  *   Technology: ****
  *   GitHub Login: @Sunil-Garg<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSunil-Garg&data=04%7C01%7Csunilg%40microsoft.com%7Cbc3f8548eac34d546ccf08d92bedde64%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637589122908629042%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=HbkdQ20XWzKV04KWH5DDpFjdbaMfNNiUDuH8QzqLUN4%3D&reserved=0>
  *   Microsoft Alias: sunilg

**Comment by RobinARH** [comment]
Created bug 594528 to track this issue.
