### ISSUE TITLE
"Cheat Sheet" hypelink is not valid

### ISSUE THREAD

**Issue by hburgh1** [MicrosoftDocs/dynamics-365-unified-operations-public#3396]
The "Cheat Sheet" reference does not have a valid URL.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55c7ea05-69b5-1c5e-eb55-07066a1b2d17
* Version Independent ID: b75e9d43-6590-60bd-ca34-83c40abd9ae6
* Content: [Set up new environments, Azure DevOps, and branches for projects - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/new-environments-visual-studio-teams-branch-retail-projects?source=docs)
* Content Source: [articles/commerce/dev-itpro/new-environments-visual-studio-teams-branch-retail-projects.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/new-environments-visual-studio-teams-branch-retail-projects.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @andreashofmann1
* Microsoft Alias: **andreash**

**Comment by RobinARH** [comment]
Created bug 594529 to track this issue.

**Comment by RobinARH** [comment]
I removed the link, looks like that website is gone.
