### ISSUE TITLE
Select Open to view list of global ER configurations results in authentication error

### ISSUE THREAD

**Issue by ronsonntag54** [MicrosoftDocs/dynamics-365-unified-operations-public#3398]
[Enter feedback here]
Step 6 of the Open Configurations Repository instructions results in an authentication failure. What account, exactly, are you looking for when the dialog pops up to authenticate? Corporate account, personal account, educational account? You need to address the pop-up that requires authentication:

[Click here to connect to Regulatory Configuration Service](https://login.windows.net/93f33571-550f-43cf-b09f-cd331338d086/oauth2/authorize?redirect_uri=https%3A%2F%2Fusnconeboxax1aos.cloud.onebox.dynamics.com%2Foauth&response_type=code&client_id=00000015-0000-0000-c000-000000000000&resource=http%3A%2F%2Fconfigure.global.dynamics.com&state=http%3A%2F%2Fconfigure.global.dynamics.com)

Note: I am running on a local onebox that authenticates with my work email address that also has access to our corporate LCS and Azure subscriptions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37df3c73-e1a7-d14d-ef19-9dc2e87e99ec
* Version Independent ID: acd2d382-bb9e-ca3d-d792-9b8a4cc5d33a
* Content: [Download ER configurations from the Global repository of Configuration service - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/er-download-configurations-global-repo)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/er-download-configurations-global-repo.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/analytics/er-download-configurations-global-repo.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @NickSelin
* Microsoft Alias: **nselin**

**Comment by NickSelin** [comment]
Hello @ronsonntag54.
Thank you for your feedback. You must use the same account as you used to sign-in to Finance.
You have not provided the exact error message and application version details. Possibly, it happens due to the following platform code defect: https://fix.lcs.dynamics.com/Issue/Details?kb=4603542&bugId=546672&dbType=3. For more details and assistance in resolving this issue, please, report it as a service request.
Best regards,
Nick Selin

**Comment by RobinARH** [comment]
Created bug 594530 to track this issue.
