### ISSUE TITLE
More metadata info available

### ISSUE THREAD

**Issue by gertvdh** [MicrosoftDocs/dynamics-365-unified-operations-public#3400]
This endpoint is now also giving more information:

- Public entities
- Public enumerations

documentation should be appended for this

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 133cc363-a550-5cbf-622a-f0bd3da87eb6
* Version Independent ID: a7b1ce5d-ba20-b723-e3b0-23a9b79cde9d
* Content: [Service endpoints overview - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/services-home-page#rest-metadata-service)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/services-home-page.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/services-home-page.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by RobinARH** [comment]
Created bug 594541 to track this issue.

**Comment by josaw1** [comment]
Closed as won't fix.
