### ISSUE TITLE
Dev environment info

### ISSUE THREAD

**Issue by elenchence** [MicrosoftDocs/dynamics-365-unified-operations-public#3401]
There's a sentence: One Tier 1 environment is free with your Dynamics 365 subscription. - Since this is no longer the case, it creates confusion with customers. Please update the content.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55c7ea05-69b5-1c5e-eb55-07066a1b2d17
* Version Independent ID: b75e9d43-6590-60bd-ca34-83c40abd9ae6
* Content: [Set up new environments, Azure DevOps, and branches for projects - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/new-environments-visual-studio-teams-branch-retail-projects)
* Content Source: [articles/commerce/dev-itpro/new-environments-visual-studio-teams-branch-retail-projects.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/new-environments-visual-studio-teams-branch-retail-projects.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @andreashofmann1
* Microsoft Alias: **andreash**

**Comment by RobinARH** [comment]
Created bug 594543 to track this issue.

**Comment by tonyafehr** [comment]
@josaw, please review.

**Comment by josaw1** [comment]
Updated topic. Should go live this week.
