### ISSUE TITLE
Fixed unit assignment, Fixed unit

### ISSUE THREAD

**Issue by pbonny1** [MicrosoftDocs/dynamics-365-unified-operations-public#3402]
It would be great to have descriptions of functionality for Fixed unit assignment and Fixed unit fields on the Organisation Administration>Setup>Units>Units> General tab. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54259aca-1ed7-cc7a-c898-65f065aba0e7
* Version Independent ID: ae89e895-7f44-90f1-6cdf-1e434f3b7aae
* Content: [Manage units of measure - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/pim/tasks/manage-unit-measure)
* Content Source: [articles/supply-chain/pim/tasks/manage-unit-measure.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/pim/tasks/manage-unit-measure.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @sorenva
* Microsoft Alias: **sorenand**

**Comment by josaw1** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle requests for the product here. Consider adding your request to the [Ideas site](https://experience.dynamics.com/ideas/).

**Comment by pbonny1** [comment]
Hi again,
My request was not a product request as those fields are in the product already.
But there is no documentation about them in the article

Thanks

**Comment by josaw1** [comment]
BUG 593865 created to track.

**Comment by josaw1** [comment]
Closed as won't fix.
