### ISSUE TITLE
Replace ADAL code example with MSAL

### ISSUE THREAD

**Issue by steevegilbert** [MicrosoftDocs/dynamics-365-unified-operations-public#3403]
Since it's recommended to move from ADAL to MSAL, I think example provided should be MSAL.
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 133cc363-a550-5cbf-622a-f0bd3da87eb6
* Version Independent ID: a7b1ce5d-ba20-b723-e3b0-23a9b79cde9d
* Content: [Service endpoints overview - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/services-home-page?WT.mc_id=Portal-Microsoft_AAD_RegisteredApps)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/services-home-page.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/services-home-page.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by josaw1** [comment]
Thanks for the feedback. @Sunil-Garg can you please consider this input? Thanks.

**Comment by josaw1** [comment]
BUG 593868 created to track.

**Comment by josaw1** [comment]
Updated.
