### ISSUE TITLE
Broken 'request a callback' link

### ISSUE THREAD

**Issue by Doriano** [MicrosoftDocs/dynamics-365-unified-operations-public#3404]
Hi, 

There's a broken link
https://dynamics.microsoft.com/en-gb/get-started/?appname=fraudprotection

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e29843f-4b7d-5b4b-6a71-d468e504f63c
* Version Independent ID: f72648ff-10e0-340e-6f51-b8c3766e1b6f
* Content: [Dynamics 365 Fraud Protection integration with Dynamics 365 Commerce - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/dfp)
* Content Source: [articles/commerce/dev-itpro/DFP.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/DFP.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @rubendel
* Microsoft Alias: **rubendel**

**Comment by josaw1** [comment]
Thanks for the feedback! I'll get this fixed soon.

**Comment by josaw1** [comment]
@samjarawan can you please help with this?

**Comment by josaw1** [comment]
BUG 593869 created to track.

**Comment by josaw1** [comment]
This is fixed.

**Comment by Doriano** [comment]
Thanks
