### ISSUE TITLE
HistoricalDemandData Sample File Link is Broken

### ISSUE THREAD

**Issue by jwilliams-bhsolutions** [MicrosoftDocs/dynamics-365-unified-operations-public#3406]
The link to the document on this page is broken.  See the example section: https://docs.microsoft.com/en-us/dynamics365/supply-chain/master-planning/import-historical-data#example where it says "Download the HistoricalDemandData.".  HistoricalDemandData is supposed to be a sample but redirects to https://docs.microsoft.com/en-us/dynamics/s-e/ which is a blank page.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3f17fae-150d-e5c8-77bb-f3c8e142272f
* Version Independent ID: d49c5d4c-ae4d-8ad2-6e96-255cfe88f978
* Content: [Import historical data for demand forecasts - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/master-planning/import-historical-data)
* Content Source: [articles/supply-chain/master-planning/import-historical-data.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/master-planning/import-historical-data.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @roxanadiaconu
* Microsoft Alias: **kamaybac**

**Comment by josaw1** [comment]
Thanks for the feedback. @kamaybac can you please address this issue?

**Comment by josaw1** [comment]
BUG 593870 created to track.

**Comment by kamaybac** [comment]
@jwilliams-bhsolutions , unfortunately, that sample file is no longer available. I am updating the topic to remove the reference to it.
