### ISSUE TITLE
Update Configure PowerBI.com integration

### ISSUE THREAD

**Issue by Strikx** [MicrosoftDocs/dynamics-365-unified-operations-public#3409]
Configure Power BI.com integration documentation is outdated and it needs to be updated, Enable API permission in Registration process (https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/configure-power-bi-integration#registration-process) contains the old screenshot of API permission from Azure Portal.
Some of the permission mentioned in the document no longer available in the Azure. 
Please update the document with latest configuration.
![Power BI Configuration 1](https://user-images.githubusercontent.com/85994049/122206181-22e70c80-ceb2-11eb-8a64-7b3a800ce4ea.png)
![Power BI Configuration azure](https://user-images.githubusercontent.com/85994049/122206189-24183980-ceb2-11eb-98c0-273c6026509a.png)
![Power BI Configuration](https://user-images.githubusercontent.com/85994049/122206196-25496680-ceb2-11eb-8fa2-844d41d9ab5e.png)
![Power BI Configuration2](https://user-images.githubusercontent.com/85994049/122206199-25496680-ceb2-11eb-9a29-ed5ab7cd0b83.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2213414-926d-10e1-538b-efef09dc0181
* Version Independent ID: 03be53f7-c305-cb02-7627-2ea4f1c01bd4
* Content: [Configure PowerBI.com integration - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/configure-power-bi-integration)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/configure-power-bi-integration.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/analytics/configure-power-bi-integration.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by josaw1** [comment]
Thank you for your feedback. @MilindaV2 can you please take a look?

**Comment by josaw1** [comment]
BUG 593871 created to track.

**Comment by josaw1** [comment]
Closed as won't fix.
