### ISSUE TITLE
EnableRequestProtection and Non incremetal capture payment methods in Adyen payment connector Payment services

### ISSUE THREAD

**Issue by thedynamicsgirl** [MicrosoftDocs/dynamics-365-unified-operations-public#3411]
[I can see two new fields EnableRequestProtection & Non incremetal capture payment methods
have been added to the payment services screen / Hardware profile > EFT services in the 10.0.18 update of D365. Can some information around these fields be included in this article]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1a7bb73-c6c0-fc10-9369-04714ac8e6f0
* Version Independent ID: df6ebf95-7def-f3d5-04fc-8f412e314ee1
* Content: [Dynamics 365 Payment Connector for Adyen - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/adyen-connector?tabs=10-0-9)
* Content Source: [articles/commerce/dev-itpro/adyen-connector.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/adyen-connector.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @rassadi
* Microsoft Alias: **rassadi**

**Comment by josaw1** [comment]
Thank you for your feedback. @Reza-Assadi can you please take a look?

**Comment by josaw1** [comment]
BUG 593872 created to track.

**Comment by josaw1** [comment]
PR created. Will be updated soon.
