### ISSUE TITLE
Hi Dear Team! When I am checking for a new sealed POS installer, all versions are marked with Preview. Does it mean that new installers should not be used in Production yet?  

### ISSUE THREAD

**Issue by OksanaKovaliova** [MicrosoftDocs/dynamics-365-unified-operations-public#3416]
****
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c22f987b-3d20-554d-467a-cdcdf404b0bd
* Version Independent ID: 0160ae8d-09c7-d54c-83bf-10fbec9842e9
* Content: [Mass deployment of sealed Commerce self-service components - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/enhanced-mass-deployment)
* Content Source: [articles/commerce/dev-itpro/Enhanced-Mass-Deployment.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/Enhanced-Mass-Deployment.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @jashanno
* Microsoft Alias: **jashanno**

**Comment by kamaybac** [comment]
@OksanaKovaliova , thank you for contacting us regarding this help topic. I have passed your comment on for consideration.

**Comment by kamaybac** [comment]
BUG 606543 created to track this issue.
