### ISSUE TITLE
Configure the maximum number of batch threads

### ISSUE THREAD

**Issue by peteregliambit** [MicrosoftDocs/dynamics-365-unified-operations-public#3418]
According Microsoft Ticket 2106160050000151 the number batch threads is 16.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 587b06db-be99-4869-b8b9-977464b63f74
* Version Independent ID: 3e925d7e-eafc-1158-92e2-992d72d8f934
* Content: [Optimize data migration for Finance and Operations apps - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/optimize-data-migration)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/optimize-data-migration.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/sysadmin/optimize-data-migration.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @skaue-ms
* Microsoft Alias: **toskaue**

**Comment by kamaybac** [comment]
@peteregliambit  , thank you for contacting us regarding this help topic. I have passed your comment on for consideration.

**Comment by skaue-ms** [comment]
The default values for new environments for batch threads per AOS is still 4, even if the number of virtual cores is higher. Let me check with product group before I modify the guidance here. Setting the value to 8 and then increase by 2 with testing is still a valid approach.

**Comment by kamaybac** [comment]
BUG 606549 created to track this issue.

**Comment by kamaybac** [comment]
The topic is now updated.
