### ISSUE TITLE
Maybe the example should be a form that actually use the described pattern, and not Custom pattern.

### ISSUE THREAD

**Issue by jesperdybdahl** [MicrosoftDocs/dynamics-365-unified-operations-public#3420]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7767de52-def6-7972-065a-77a531830135
* Version Independent ID: f0185847-9d92-073b-2497-cd2311a9bba6
* Content: [Advanced selection form pattern - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/user-interface/advanced-selection-form-pattern)
* Content Source: [articles/fin-ops-core/dev-itpro/user-interface/advanced-selection-form-pattern.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/user-interface/advanced-selection-form-pattern.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by kamaybac** [comment]
@jesperdybdahl  , thank you for contacting us regarding this help topic. I have passed your comment on for consideration.

**Comment by kamaybac** [comment]
BUG 606551 created to track this issue.

**Comment by kamaybac** [comment]
There are only a few instances of this form pattern in the OOB product and none of them display with data by default. Resolving this as Won't Fix since the point of the article is to show the general idea.

**Comment by jesperdybdahl** [comment]
Exactly the reason for refering to an example that excually implements the pattern described. Refer to one of those few instances so you can actually see all the properties that is missed in the documentation. The value of the example is useless.
