### ISSUE TITLE
Undocumented -packagesroot parameter

### ISSUE THREAD

**Issue by glenturnbullazure** [MicrosoftDocs/dynamics-365-unified-operations-public#3421]
Where a custom model references an ISV model, if the -PackagesRoot parameter is not included, the following error occurs:
The source for referenced module '<referenced module name>' is missing from the model store. Please specify the -packagesRoot parameter to instead use binary metadata for referenced modules.

The solution was to add the following to the command line: -packagesroot=K:\AosService\PackagesLocalDirectory

However this was not immediately obvious from the available documentation. I think this page should mention it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cbcd513-d8ab-ddc6-ce0d-43e03d4692c2
* Version Independent ID: d1119159-09e4-1aa1-d90e-c8f23552adbc
* Content: [Customization Analysis Report (CAR) - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/customization-analysis-report)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/customization-analysis-report.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/dev-tools/customization-analysis-report.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @RobinARH
* Microsoft Alias: **jorisde**

**Comment by kamaybac** [comment]
@glenturnbullazure  , thank you for contacting us regarding this help topic. I have passed your comment on for consideration.

**Comment by kamaybac** [comment]
BUG 606554 opened to track this issue

**Comment by RobinARH** [comment]
I updated the topic and the new content should go live this evening.
