### ISSUE TITLE
Update section API to get the list of execution errors - information incorrect

### ISSUE THREAD

**Issue by KlaasDeforche** [MicrosoftDocs/dynamics-365-unified-operations-public#3424]
Please update this section: 
https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/recurring-integrations#api-to-get-the-list-of-execution-errors 
Recurring Integrations do not use execution id's so it is not possible to get the execution errors with this API out of the box. 
The documentation makes it look like it's possible, so when designing integrations this is assumed to be true. 
Either an API should be added to make this possible, or it should clearly state that this is not possible and in fact does not work for RI. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01b2cd6b-f885-7461-fbdf-cf81f9e50d86
* Version Independent ID: 8df7a6ae-67db-5d29-fb6a-0820704ff3ef
* Content: [Recurring integrations - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/recurring-integrations#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/recurring-integrations.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/recurring-integrations.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by kamaybac** [comment]
@KlaasDeforche , thank you for contacting us regarding this help topic. I have passed your comment on for consideration.

**Comment by kamaybac** [comment]
BUG 606556 opened to track this issue

**Comment by kfend** [comment]
Thank you for letting us know. We have done more investigating, and we will be making an update to the functionality based on this feedback.
