### ISSUE TITLE
The Download ETWManifest.zip link does not work

### ISSUE THREAD

**Issue by jopankow** [MicrosoftDocs/dynamics-365-unified-operations-public#3425]
Hello team,

Under the "Management Reporter" heading, the "Download ETWManifest.zip" link points to:

https://go.microsoft.com/fwlink/?linkid=864672

This link resolves to

https://mbs.microsoft.com/customersource/northamerica/365Enterprise/downloads/hot-fixes/365fopttroubleshootingdep

Which no longer works as the site has been decommissioned. Please update the link.

Tagging @faix as well for awareness

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41f27bdd-7361-5030-a00d-db0674f6f9bf
* Version Independent ID: 228e03d2-5dc7-e428-d475-aecde408edfa
* Content: [Troubleshoot on-premises deployments - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/troubleshoot-on-prem#management-reporter)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/troubleshoot-on-prem.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/deployment/troubleshoot-on-prem.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @PeterRFriis
* Microsoft Alias: **peterfriis**

**Comment by kamaybac** [comment]
@jopankow  , thank you for contacting us regarding this help topic. I have passed your comment on for consideration.

**Comment by kamaybac** [comment]
BUG 606557 opened to track this issue.

**Comment by faix** [comment]
@kamaybac , could you please close this issue? The issue was addressed.
