### ISSUE TITLE
Incorrect spelling of "principal"

### ISSUE THREAD

**Issue by bvpb** [MicrosoftDocs/dynamics-365-unified-operations-public#3428]
"principle" is used multiple times on this page incorrectly. It should instead be "principal"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c84e15d4-bcac-038a-2b1e-8c456ee25bd9
* Version Independent ID: 478b5f33-f745-1df2-8fe0-da9e64233165
* Content: [Configure export to Azure Data Lake - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/configure-export-data-lake)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/configure-export-data-lake.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/configure-export-data-lake.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by sericks007** [comment]
@bvpb, thank you for bringing this to our attention!  I've corrected the incorrect spellings -- the updated content will be published later today.
