### ISSUE TITLE
EMEA VAT EXCHANGE RATE is just available for these countries: **Czech republic CZ, Poland PL and Hungary HU.**

### ISSUE THREAD

**Issue by Ccarcelen** [MicrosoftDocs/dynamics-365-unified-operations-public#3429]
Functionality described in this link (https://docs.microsoft.com/en-us/dynamics365/finance/localizations/emea-vat-exchange-rate) is just available for these countries: **Czech republic CZ, Poland PL and Hungary HU.**
It should be mentioned at the begining of the article, otherwise customers and partners might think that this funcionality applies to all European Countries.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87921fb5-9edd-180e-6e0c-22c63783d708
* Version Independent ID: b956d1bd-154d-542d-f0d2-123b65c6efac
* Content: [VAT exchange rate overview - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/emea-vat-exchange-rate#feedback)
* Content Source: [articles/finance/localizations/emea-vat-exchange-rate.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/emea-vat-exchange-rate.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @ShylaThompson
* Microsoft Alias: **mrolecki**

**Comment by kfend** [comment]
The topic has been updated and the changes will go live later today.
