### ISSUE TITLE
Remove "Preview" from the title

### ISSUE THREAD

**Issue by PalleAgermark** [MicrosoftDocs/dynamics-365-unified-operations-public#3431]
I guess you can remove the word "Preview" from title by now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: caa7bcc6-0bba-b6f3-d20e-92ac4cccdb32
* Version Independent ID: 0b2db86c-e326-febc-1443-cbac2f776887
* Content: [What's new or changed in Dynamics 365 Finance 10.0.19 (June 2021) - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/get-started/whats-new-changed-10-0-19)
* Content Source: [articles/finance/get-started/whats-new-changed-10-0-19.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/get-started/whats-new-changed-10-0-19.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @roschlom
* Microsoft Alias: **roschlom**

**Comment by kfend** [comment]
@PalleAgermark - thank you for the feedback. I have updated the topic and the changes will be published later today.
