### ISSUE TITLE
RSS Feeds

### ISSUE THREAD

**Issue by DanBurkeMSFT** [MicrosoftDocs/dynamics-365-unified-operations-public#3438]
For several years I have had an RSS feed for any new or changed documentation.  Recently, it has not been giving any feeds.  I have not had an RSS feed update since April.  Does something need to be updated for it to continue to work?  

Dan.  
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2784be5-5cfc-88bd-6780-b41caad193fe
* Version Independent ID: ff9b7f83-e8f1-2ed7-fb0a-eea5626f9f86
* Content: [Help system - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/help-overview)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/help-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/help-overview.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by kfend** [comment]
@DanBurkeMSFT - Thank you for the question.
@edupont04 - can you please take a look at and address this question?

**Comment by edupont04** [comment]
Hello Dan,
Thank you for your feedback! You're right that the RSS feed is currently broken. We're working on a new version. Until then, you can get a very rough idea of what is going on by watching our GitHub repo here: https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public

In the mean while, we'll remove the mention of an RSS feed and reintroduce it once we have things working again.
I realize that this is not the answer you are looking for, but it's the best one I have right now.
