### ISSUE TITLE
Details about exceptions and finally/using missing

### ISSUE THREAD

**Issue by torbennehmer** [MicrosoftDocs/dynamics-365-unified-operations-public#3439]
I am missing the explicit statement, that finally clauses will be executed even in transaction scope. As this is opposed to any catches in the call tree, this should be mentioned.

Also, I would recommend mentioning that the dispose calls that using statements trigger will also be executed inside exceptions. This does work for X++ classes implementing System.IDisposable as well, which can also help if X++ classes encapsulate external resources.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e34c172-4541-ebaf-058e-66b4b1e9e5b5
* Version Independent ID: ce270ef7-3fd5-d154-60b8-bed38b33cb8e
* Content: [X++ exception handling - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-ref/xpp-exceptions)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-ref/xpp-exceptions.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/dev-ref/xpp-exceptions.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @RobinARH
* Microsoft Alias: **rhaertle**

**Comment by kfend** [comment]
@torbennehmer - thank you for the feedback. 
@RobinARH - can you take a look at and address this?

**Comment by RobinARH** [comment]
I'll take a look.

**Comment by RobinARH** [comment]
Created bug 602398 to track this issue.

**Comment by RobinARH** [comment]
I've updated the topic. The changes will go live later today.
