### ISSUE TITLE
Spelling mistake in method name

### ISSUE THREAD

**Issue by sbaber82** [MicrosoftDocs/dynamics-365-unified-operations-public#344]
The Personalization spelling in both method names are incorrect. Its written Presonalization, whereas it should be Personalization

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1661c21-712d-2ac1-d9df-23c11da4fcb1
* Version Independent ID: 1e6b4ab1-bde9-6b3c-5be4-32c7965a503d
* Content: [Embed PowerApps apps - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/embed-power-apps)
* Content Source: [articles/fin-and-ops/get-started/embed-power-apps.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/embed-power-apps.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by sericks007** [comment]
Thanks for letting us know!  I've updated the topic.
