### ISSUE TITLE
Vendor admin role needs new privileges

### ISSUE THREAD

**Issue by HugoDJesus** [MicrosoftDocs/dynamics-365-unified-operations-public#3440]
Hi, 

We tested the new functionality but using the standard Vendor admin role, the external vendor user don't have access to add new banks accounts.

We reviewed the privileges associated with menu items and we did not find any standard privileges:

![image](https://user-images.githubusercontent.com/46756250/123815798-107bc280-d8f7-11eb-9698-f82e97629b3a.png)

BR
---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 925689eb-7471-5cc7-cc5c-f51225ba1764
* Version Independent ID: 41d9cd03-4580-52e6-5ee4-391ab52c8975
* Content: [Maintain vendor bank account information - Finance | Dynamics 365](https://docs.microsoft.com/es-es/dynamics365/finance/accounts-payable/maintain-vendor-bank-info)
* Content Source: [articles/finance/accounts-payable/maintain-vendor-bank-info.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/accounts-payable/maintain-vendor-bank-info.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @v-kiarnd
* Microsoft Alias: **brpotter**

**Comment by v-kiarnd** [comment]
We will file a bug for this and get it taken care of.

From: HugoDJesus ***@***.***>
Sent: Tuesday, June 29, 2021 7:37 AM
To: MicrosoftDocs/dynamics-365-unified-operations-public ***@***.***>
Cc: Kim Arndtson (TYLER TECHNOLOGIES INC) ***@***.***>; Mention ***@***.***>
Subject: [MicrosoftDocs/dynamics-365-unified-operations-public] Vendor admin role needs new privileges (#3440)


Hi,

We tested the new functionality but using the standard Vendor admin role, the external vendor user don't have access to add new banks accounts.

We reviewed the privileges associated with menu items and we did not find any standard privileges:

[image]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F46756250%2F123815798-107bc280-d8f7-11eb-9698-f82e97629b3a.png&data=04%7C01%7Cv-kiarnd%40microsoft.com%7C0b5a4538d059482e95ae08d93b0b4a05%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637605741946849107%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=HhYBe207G89BK1Tgz%2Bua09jHMjwDFSPzXzawd0HyicU%3D&reserved=0>

BR
Detalles del documento

⚠ No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.

  *   ID: 925689eb-7471-5cc7-cc5c-f51225ba1764
  *   Version Independent ID: 41d9cd03-4580-52e6-5ee4-391ab52c8975
  *   Content: Maintain vendor bank account information - Finance | Dynamics 365<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fes-es%2Fdynamics365%2Ffinance%2Faccounts-payable%2Fmaintain-vendor-bank-info&data=04%7C01%7Cv-kiarnd%40microsoft.com%7C0b5a4538d059482e95ae08d93b0b4a05%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637605741946849107%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9BzVH6ziESyQD2rKGvboj26OgID6Wanj3SFXBhwpbWA%3D&reserved=0>
  *   Content Source: articles/finance/accounts-payable/maintain-vendor-bank-info.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FDynamics-365-Unified-Operations-Public%2Fblob%2Fmain%2Farticles%2Ffinance%2Faccounts-payable%2Fmaintain-vendor-bank-info.md&data=04%7C01%7Cv-kiarnd%40microsoft.com%7C0b5a4538d059482e95ae08d93b0b4a05%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637605741946859061%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=6o8YIBvct4t3GWkOEZhSIYaxXUo1pSkc8nXnucBrHMs%3D&reserved=0>
  *   Service: dynamics-365-finance
  *   Product: ****
  *   Technology: ****
  *   GitHub Login: @v-kiarnd<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fv-kiarnd&data=04%7C01%7Cv-kiarnd%40microsoft.com%7C0b5a4538d059482e95ae08d93b0b4a05%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637605741946859061%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ts0Dd43KKNuYauVZ23Dt4VlA%2BCbuQZ98F10orsiDMAA%3D&reserved=0>
  *   Microsoft Alias: brpotter

**Comment by RobinARH** [comment]
Created bug 602399 to track this issue.

**Comment by kfend** [comment]
Closing as this was being tracked in another bug.
