### ISSUE TITLE
Second code block says it's X++, but it's JSON, like the first code block.

### ISSUE THREAD

**Issue by NathanDL** [MicrosoftDocs/dynamics-365-unified-operations-public#3442]
[Enter feedback here]
Second code block says it's X++, but it's JSON, like the first code block.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e59e1e94-0908-6c59-40b9-1cd9b9f9ef9a
* Version Independent ID: 5a684e15-decb-784b-74d0-4d8330fc1577
* Content: [Extend a module definition file - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/e-commerce-extensibility/extend-module-definition)
* Content Source: [articles/commerce/e-commerce-extensibility/extend-module-definition.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/e-commerce-extensibility/extend-module-definition.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @samjarawan
* Microsoft Alias: **samjar**

**Comment by kfend** [comment]
@NathanDL - thank you for the feedback.
@samjarawan - can you please take a look at this and update the topic as necessary?

**Comment by RobinARH** [comment]
Created bug 602400 to track this issue.

**Comment by RobinARH** [comment]
Thanks for catching this! I fixed it and the update should go live this evening.
