### ISSUE TITLE
[VAGA HOME OFFICE] ANALISTA DESENVOLVEDOR ERP - MICROSOFT DYNAMICS 

### ISSUE THREAD

**Issue by patyandreolli** [MicrosoftDocs/dynamics-365-unified-operations-public#3444]
ANALISTA DESENVOLVEDOR ERP - MICROSOFT DYNAMICS
Plataformas: Microsoft Dynamics AX 2012 e Dynamics 365 F&O
Vivência  em desenvolvimentos em projetos ou suporte nas plataformas  AX 2012/D365
Domínio da linguagem X++

Prazo: Indeterminado
Local: 100% Home Office 
Envio de currículo: recrutamento@infovagas.com indicando no assunto “Dynamics - GS”
Em caso de dúvida ou informações=>  WhatsApp: https://wa.me/message/BVQ5K5OO3AWEC1

**Comment by kfend** [comment]
There doesn't seems to be an issue provided here so closing this.
