### ISSUE TITLE
Outdated / Misleading

### ISSUE THREAD

**Issue by jaestevan** [MicrosoftDocs/dynamics-365-unified-operations-public#3445]
This topic is outdated. Batch Groups are not very relevant anymore and referring to different software being installed o the servers is heavily on-prem based. Would be nice to have this review rewritten to highlight changes to batch framework since AX 2012 and best practices to setup batches in the new cloud infrastructure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95243cdc-2f9f-ac62-4b0f-e6c2e180adbf
* Version Independent ID: 84917732-1cac-0029-9666-36eb00979c65
* Content: [Batch processing overview - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/batch-processing-overview)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/batch-processing-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/sysadmin/batch-processing-overview.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Peakerbl
* Microsoft Alias: **peakerbl**

**Comment by kfend** [comment]
@jaestevan - thank you for the feedback.
@Peakerbl - can you please take a look at and address this as needed?

**Comment by RobinARH** [comment]
Created bug 602401 to track this issue.
