### ISSUE TITLE
This first version supports only the String attribute type

### ISSUE THREAD

**Issue by pwmsdn** [MicrosoftDocs/dynamics-365-unified-operations-public#3447]
In the article you say "This first version supports only the String attribute type"... Its been nearly a year since this article was published. Any progress on making more options available? Specifically, we really need to be able to attach order attributes of fixed list/text types so we can associate each sale with a specific source. We dont want cashiers having to manually type the source each time. We've tried to do this with info codes, but you cant display info codes on the screen, or change them without voiding, unless you want to customize the POS. We dont want to customize, and the order attributes would be perfect, IF, fixed lists could be used like they are in customer attributes. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: daca1f9e-c913-eb05-1a7d-23e6a54fc782
* Version Independent ID: f6ab1665-4c15-c2ed-9bf0-f5411295840a
* Content: [Define and set order attributes - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/order-attributes)
* Content Source: [articles/commerce/dev-itpro/order-attributes.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/order-attributes.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by RobinARH** [comment]
@mugunthanm - Can you take a look? Thanks.

**Comment by RobinARH** [comment]
Created bug 602395 to track this issue.

**Comment by mugunthanm** [comment]
Unfortunately, the feature to support additional data types in attributes is not prioritized yet, it's still in the backlog so we will not be able to commit any timeline on this, for now please customize the solution.

**Comment by pwmsdn** [comment]
That's too bad. Seems like a MUCH better solution for tracking transaction specific data than info codes (which aren't searchable, not changeable without voiding the transaction, and not displayed on the POS screen without customizations).... No out of the box option for tracking customer source, etc. is a big step backwards from previous Microsoft POS offerings and from competing products. 365 does a lot right, but not having stuff like this possible out of the box is so frustrating.

Thanks,
