### ISSUE TITLE
Link directs to parent

### ISSUE THREAD

**Issue by Roozle** [MicrosoftDocs/dynamics-365-unified-operations-public#3448]
I tried accessing the following link to retrieve Microsofts' policy on creating multiple users on the development machines (At one point in time, this was restricted) The link for 'Create new users on development machines' goes to the parent link 'Deploy and access development environments' instead of to a unique page

https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/enable-development-machine
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af690052-1160-9bf9-5f77-fc894910bd96
* Version Independent ID: 1717e34b-dc2b-2745-787c-bccd9e92839b
* Content: [Development and build VMs that don't allow admin access FAQ - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/vms-no-admin-access)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/VMs-no-admin-access.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/sysadmin/VMs-no-admin-access.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @yukonpeegs
* Microsoft Alias: **epegors**

**Comment by RobinARH** [comment]
@sericks007 @yukonpeegs - Can you take a look? Thanks.

**Comment by RobinARH** [comment]
Created bug 602396 to track this issue.

**Comment by RobinARH** [comment]
I fixed the table of contents and the update should go live tonight.
