### ISSUE TITLE
Reverse journal posting

### ISSUE THREAD

**Issue by BenLCastellow** [MicrosoftDocs/dynamics-365-unified-operations-public#3450]
1. URL.....https://docs.microsoft.com/en-us/dynamics365/finance/general-ledger/reverse-journal-posting
2. Need to add note that feature management "Mass reversals for multiple documents' must be enabled.
2. Under Reversing journals section, change "Open the financial journal and filter on posted journals." to "Filter on the posted journals and open the lines on the applicable journal.".
3. Change "Under Reversing journals section",  change "Select the Reverse menu at the top of the page." to "Select the dropdown Reverse entire journal menu at the top of the page.".
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dd9106c-fb51-ebc5-5d99-4a0195caded9
* Version Independent ID: 5a93ad30-f334-4a96-3113-f0a43dbff675
* Content: [Reverse journal posting - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/general-ledger/reverse-journal-posting)
* Content Source: [articles/finance/general-ledger/reverse-journal-posting.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/general-ledger/reverse-journal-posting.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @mikefalkner
* Microsoft Alias: **roschlom**

**Comment by RobinARH** [comment]
@mikefalkner - Can you take a look? Thanks.

**Comment by RobinARH** [comment]
@roschlom - Can you take a look? GitHub doesn't recognize Mike Falkner. Thanks - Robin

**Comment by RobinARH** [comment]
Created bug 602397 to track this issue.

**Comment by roschlom** [comment]
The topic has been updated. Thank your input; we really appreciate it!
