### ISSUE TITLE
Link to technical reference is broken

### ISSUE THREAD

**Issue by VolkerDeuss** [MicrosoftDocs/dynamics-365-unified-operations-public#3451]
The link "ObsoleteElementsPerVersion.xslx" (https://mbs2.microsoft.com/fileexchange/?fileID=d6b5589b-c2c7-4cdd-a6b9-87e080cb2f05) is broken, which basically was the most useful thing on the page...

It is the same with all the technical reference links in https://docs.microsoft.com/en-us/dynamics/s-e/global/axtechrefrep_61 btw. Can't create an issue item for that one easily though.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 621625f6-225e-a807-9a8a-c62e4275d23b
* Version Independent ID: 17cbcd8c-7638-0e62-2bc3-432b4bc2c660
* Content: [Deprecation of methods and metadata elements - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/deprecation-deletion-apis?source=docs)
* Content Source: [articles/fin-ops-core/dev-itpro/migration-upgrade/deprecation-deletion-apis.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/migration-upgrade/deprecation-deletion-apis.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @jorisdg
* Microsoft Alias: **jorisde**

**Comment by jorisdg** [comment]
Hi Volker, we're actually working on a revamp of the deprecation article and other compatibility articles as well. Unfortunately the spreadsheet is no longer in the plans and the link will be removed.

**Comment by RobinARH** [comment]
The downloads on https://docs.microsoft.com/en-us/dynamics/s-e/global/axtechrefrep_61 are working for me.
