### ISSUE TITLE
No instructions for deploying modern report designs to production

### ISSUE THREAD

**Issue by danielzook** [MicrosoftDocs/dynamics-365-unified-operations-public#3454]
There are no instructions or guidance on how to deploy the modern report designs to production after importing the model into the Dev environment.  Are there specific steps, or is the model considered a custom modification and should be treated as such?  (e.g., checked-in to source control, built into an AIO deployment package, etc.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 586f12ef-881e-1e4d-13e7-6b355e5e53eb
* Version Independent ID: 85382ffd-3e2f-a98e-3620-1cdc2ebcd7df
* Content: [Install modern report design templates - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/install-modern-report-design-templates)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/install-modern-report-design-templates.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/analytics/install-modern-report-design-templates.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @RichdiMSFT
* Microsoft Alias: **richdi**

**Comment by tonyafehr** [comment]
@danielzook, thanks for the feedback. @RichdiMSFT, please review.

**Comment by tonyafehr** [comment]
Bug 603468 logged to track this issue.
