### ISSUE TITLE
"Apply the modern designs" section refers to J:\AOSService, but it is on K: in recent one-box deployments

### ISSUE THREAD

**Issue by danielzook** [MicrosoftDocs/dynamics-365-unified-operations-public#3455]
My demo environment was deployed in the last six months or so, and it has the AOSService on drive K: instead of J:.  You may want to update the instructions to match the new drive letters in one-box deployments.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 586f12ef-881e-1e4d-13e7-6b355e5e53eb
* Version Independent ID: 85382ffd-3e2f-a98e-3620-1cdc2ebcd7df
* Content: [Install modern report design templates - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/install-modern-report-design-templates)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/install-modern-report-design-templates.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/analytics/install-modern-report-design-templates.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @RichdiMSFT
* Microsoft Alias: **richdi**

**Comment by tonyafehr** [comment]
@danielzook, thanks for the feedback. @RichdiMSFT, please review.

**Comment by tonyafehr** [comment]
Bug 603470 logged to track this issue.

**Comment by RichdiMSFT** [comment]
Thanks for the comment. I have removed the hardcoded value and have referenced the <AOSservicedrive> so that documentation doesn't have to change when drives change.
