### ISSUE TITLE
Duplicated content

### ISSUE THREAD

**Issue by kitaly** [MicrosoftDocs/dynamics-365-unified-operations-public#3457]
The content of this page is duplicated of another page:
https://docs.microsoft.com/en-us/dynamics365/supply-chain/procurement/tasks/create-purchase-release-order-creating-purchase-order

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3e054d1-e653-9948-fc87-ed3547ecee7e
* Version Independent ID: 4491c03d-49f1-d108-b932-fa2ca1adbdc6
* Content: [Create a purchase release order from a purchase agreement - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/procurement/tasks/create-purchase-release-order-purchase-agreement)
* Content Source: [articles/supply-chain/procurement/tasks/create-purchase-release-order-purchase-agreement.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/procurement/tasks/create-purchase-release-order-purchase-agreement.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @kamaybac
* Microsoft Alias: **dabourq**

**Comment by tonyafehr** [comment]
@kitaly, thanks for noting this. @kamaybac, please review.

**Comment by kamaybac** [comment]
@kitaly , thank you for reporting this issue. I am in the process of fixing it. The fix should go live in a day or so.
