### ISSUE TITLE
Connection names and navigation text changes

### ISSUE THREAD

**Issue by rrhkpmg** [MicrosoftDocs/dynamics-365-unified-operations-public#3458]
Step 3c - **Dynamics 365 for Fin & Ops** appears to be **Fin & Ops Apps (Dynamics 
365)**
Step 3c - **Dynamics 365** connection is deprecated. Doesn't mean it can't be used, but with the documentation only being 4 months old, it's a sign of how quickly things move :)

Step 4a - navigation link (at least in my environment: don't know if localisation/translation may affect this?) is **Data integration**, not **Data integrator**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b2c80b9-3567-7464-dee3-2f09423892b8
* Version Independent ID: 21a8cf2f-a2e5-e688-b256-48c0a544dfb6
* Content: [Create a data integrator project (preview) - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/finance-insights/create-data-integrate-project)
* Content Source: [articles/finance/finance-insights/create-data-integrate-project.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/finance-insights/create-data-integrate-project.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @ShivamPandey-msft
* Microsoft Alias: **shpandey**

**Comment by tonyafehr** [comment]
@rrhkpmg, this is helpful feedback. @ShivamPandeyMSFT  , please review.

**Comment by tonyafehr** [comment]
Bug 603471 logged to track this issue.

**Comment by Shivampnd** [comment]
@tonyafehr, FYI, you assigned the issue to wrong Shivam Pandey. Please correct it.

**Comment by tonyafehr** [comment]
This topic has been updated to reflect these changes.
