### ISSUE TITLE
Tax value not being replicated

### ISSUE THREAD

**Issue by Neill-KPMG** [MicrosoftDocs/dynamics-365-unified-operations-public#3459]
Currently there is an issue around the tax value on the broker line being added to the journal line once the claim is approved.  The issue is that no tax is being respected on the journal. TrackingID#2107120050001204 has been created for this

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d44a365-31d8-bd1d-cfc5-77aff5cdcfe3
* Version Independent ID: 79d3d531-787c-70d0-f5bc-d0c430bf7323
* Content: [Broker contract management - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/accounts-payable/broker-contract)
* Content Source: [articles/finance/accounts-payable/broker-contract.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/accounts-payable/broker-contract.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @t-benebo
* Microsoft Alias: **benebotg**

**Comment by tonyafehr** [comment]
@Neill-KPMG, thanks for noting this. There is nothing that needs to be updated in the documentation, as this is a Support issue, so we're going to close this comment. This will be directed to the topic author for further review.
