### ISSUE TITLE
Hi Team, I have a question about the configuration setup of product recommendations, how could I get the information of required field like application secret, dns name and secret name, and also is there anymore document about how to enable product recommendation modules?

### ISSUE THREAD

**Issue by Chainize** [MicrosoftDocs/dynamics-365-unified-operations-public#3463]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a16dd6be-c948-0264-80db-5dc8123485e6
* Version Independent ID: 325c0c4d-9f52-ffa7-393b-cd3ec87eb32a
* Content: [Enable Azure Data Lake Storage in a Dynamics 365 Commerce environment - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/enable-adls-environment)
* Content Source: [articles/commerce/enable-ADLS-environment.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/enable-ADLS-environment.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @bebeale
* Microsoft Alias: **bebeale**

**Comment by sericks007** [comment]
@Chainize, thanks for providing this feedback.

@bebeale, please consider updating the content to incorporate this information.

**Comment by josaw1** [comment]
This fix will go live later today. Thanks!
