### ISSUE TITLE
Request for official documentation on assigning AAD Security Group to the Back Office.

### ISSUE THREAD

**Issue by kevinkabatra** [MicrosoftDocs/dynamics-365-unified-operations-public#3465]
Howdee,

I would like to suggest that you include content that explains that the Azure Active Directory Security Group must be added to the back office. Maybe this is obvious but I could not find any official documentation on this requirement or even how to go about doing so. I found this article helpful: https://dynamicspedia.com/2019/09/how-to-use-azure-active-directory-for-managing-users-and-security-in-dynamics-365-for-finance-and-operations/. But I would imagine that you will want to produce official documentation and link to that. Additionally you could also link to the official documentation for creating such a group: https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-groups-create-azure-portal. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0737e52e-d1fc-a719-3fa3-5feef38ab9c3
* Version Independent ID: c8b1264a-2b1d-708c-29e5-48718736c117
* Content: [Provision a Dynamics 365 Commerce evaluation environment - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/provisioning-guide)
* Content Source: [articles/commerce/provisioning-guide.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/provisioning-guide.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @psimolin
* Microsoft Alias: **psimolin**

**Comment by sericks007** [comment]
@kevinkabatra, thank you for providing these suggestions.

@psimolin, please consider updating the content based on these suggestions.

**Comment by sericks007** [comment]
Bug 603412 has been opened to track this issue.

**Comment by sericks007** [comment]
According to the PM, the provisioning guide will be going through an overhaul in the following weeks, during which we will consider this information/links to be included.
