### ISSUE TITLE
In-app support for LCS - there is no "Support" option under Help

### ISSUE THREAD

**Issue by suedriscoll** [MicrosoftDocs/dynamics-365-unified-operations-public#3466]
I am trying to solve an issue with LCS itself, and the help documentation reads

"Select the Help button (?) in the upper-right corner of the app, and then select Support. Issues are reported on the Active issues tab in LCS. There, admins can determine whether they should provide in-house support or submit the issues to Microsoft."

However there is no Support option available under the Help button. 

![image](https://user-images.githubusercontent.com/77308421/126394202-b2e4b070-2792-4448-a8e8-18bbaf5f42a8.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32debc65-d382-465c-f0fd-a1aa5a7f9d48
* Version Independent ID: 31eb7664-5472-4fee-db0f-ac63ee2ca3ac
* Content: [Get support for Finance and Operations apps or Lifecycle Services (LCS) - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/lcs-support)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/lcs-support.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/lifecycle-services/lcs-support.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @EricMoos
* Microsoft Alias: **anupams**

**Comment by sericks007** [comment]
@suedriscoll, thanks for reporting this issue.  I'll look into it.

**Comment by sericks007** [comment]
Bug 603414 has been logged to track this issue.

**Comment by sericks007** [comment]
Hi @suedriscoll - the text that says "Select the Help button (?) in the upper-right corner of the app" was referring to the Finance and Operations app, not LCS.  I'll update the text to clarify that.  Thanks!
