### ISSUE TITLE
.23 and .24 Auto-update schedule (via LCS Update Settings) production start date 

### ISSUE THREAD

**Issue by jake-ms** [MicrosoftDocs/dynamics-365-unified-operations-public#3469]
The dates in this column do not align with the start date that we have for a project in LCS.  Have raised a support ticket as well. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7dcb285-f32c-c92e-fe49-1617f213066b
* Version Independent ID: 8f28c1a0-9da5-f853-90ee-d82a4c32df7e
* Content: [Service update availability - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/public-preview-releases#release-cadence)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/public-preview-releases.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/public-preview-releases.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @ShellyBakke
* Microsoft Alias: **smiller**

**Comment by sericks007** [comment]
@jake-ms, thanks for letting us know!

@ShellyBakke, can you please address this?

**Comment by sericks007** [comment]
@jake-ms, I just heard from @ShellyBakke.  She said the dates won't align, you have the option in LCS to select the exact date for when the update will be applied.  Hope the helps you!

**Comment by jake-ms** [comment]
Thanks for the quick response.  @ShellyBakke. It doesn’t make sense as the date in our project is prior to the auto release date.  I know they won’t be the same. For more info you can see tracking Id: 2107200040005252

**Comment by ShellyBakke** [comment]
Thank you!  I see you referenced a support case you have open with our team.  I'll follow-up directly with them the understand your exact situation.
