### ISSUE TITLE
selectedMenuOption isn't working via registerOverrideMethod

### ISSUE THREAD

**Issue by SysC0mp** [MicrosoftDocs/dynamics-365-unified-operations-public#3474]
I have a form where all the UI controls are dynamically created on runtime. Each of these controls needs a custom context menu with actions related to the control. To do that, I call `registerOverrideMethod` for each of these controls to override `getContextMenuOptions` and `selectedMenuOption`. The first method is executed correctly when I right click on the control and the custom items are displayed in the context menu, but clicking on one of the context menu items does not execute the second method (`selectedMenuOption`).

Can you please validate if there is a bug in the default system code and if not,  can you add a code example of how to make it work via `registerOverrideMethod` in the documentation? In typical manner for Dynamics AX and X++, I can't find any detailed information for `registerOverrideMethod`, so maybe the error is coupled to the usage of that method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26465c3a-9179-5103-3566-b2cd6922e7f9
* Version Independent ID: 05cee104-dbca-bc04-15d3-e3e015598544
* Content: [Code migration - Context menu code - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/code-migration-context-menus)
* Content Source: [articles/fin-ops-core/dev-itpro/migration-upgrade/code-migration-context-menus.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/migration-upgrade/code-migration-context-menus.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by josaw1** [comment]
Thank you for your question. @jasongre can you please take a look?

**Comment by RobinARH** [comment]
Created bug 610089 to track this issue.

**Comment by jasongre** [comment]
Thanks, @SysC0mp. This bug is fixed in 10.0.22 / Platform update 46 via KB 4642983.
