### ISSUE TITLE
missing info on already supported Windows 2019 

### ISSUE THREAD

**Issue by EgidijusZa** [MicrosoftDocs/dynamics-365-unified-operations-public#3485]
Hi,

seems this specific page is missing info on already supported Windows Server 2019 (from 10.0.17). On on-premises deployment page it is mentioned already, but here only Windows Serve 2016 is stated as supported. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc242273-ee42-3973-cc47-aece5771ca1f
* Version Independent ID: 0cf0f65b-6187-104a-8228-3c1431225267
* Content: [System requirements for on-premises deployments - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/system-requirements-on-prem?toc=/dynamics365/finance/toc.json)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/system-requirements-on-prem.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/system-requirements-on-prem.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @PeterRFriis
* Microsoft Alias: **peterfriis**

**Comment by sericks007** [comment]
@EgidijusZa, thanks for letting us know about this.

@faix, please update the content.

**Comment by sericks007** [comment]
This content has been updated and will be published later today.
