### ISSUE TITLE
Grammatical error

### ISSUE THREAD

**Issue by NathanDL** [MicrosoftDocs/dynamics-365-unified-operations-public#3487]
[Enter feedback here]
Your Note section reads:
_Errored records will be available in the queue for 7 days after which will the queue will be purged._

It should read something like:
_Errored records will be available in the queue for 7 days after which time they will by purged._

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d65d744-12cc-2c15-4bb5-0fdaa8a05e16
* Version Independent ID: 61505bbf-365d-f7a9-4270-9a1e2e36d660
* Content: [Error management and alert notifications - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/errors-and-alerts#alert-notifications)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/errors-and-alerts.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/dual-write/errors-and-alerts.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **sabinn**

**Comment by sabinn-msft** [comment]
approved
