### ISSUE TITLE
DevTest/Demo environments hosted in a Microsoft subscription doesn't exist anymore

### ISSUE THREAD

**Issue by JeroenLeeflang** [MicrosoftDocs/dynamics-365-unified-operations-public#3488]
On this page, there is a section about DevTest/Demo environments hosted in a Microsoft subscription. This is not applicable anymore as all Tier 1 environments must be hosted in the customers' subscription.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91ae449b-ec59-28d4-1934-6909e77ee4f3
* Version Independent ID: df6ae442-3466-4c69-aa11-ed35e20a629f
* Content: [Maintenance mode - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/maintenance-mode)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/maintenance-mode.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/sysadmin/maintenance-mode.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by laneswenka** [comment]
This is a duplicate issue.  The article is updated and will go out on the next publishing wave.  Thanks!
