### ISSUE TITLE
RPO and RTO need to be added to this article

### ISSUE THREAD

**Issue by tomhig** [MicrosoftDocs/dynamics-365-unified-operations-public#3489]
RTO (Recovery Time Objective) and RPO (Recovery Point Objective) are common metrics used in the SLA. These are not included in this article.

**Comment by sericks007** [comment]
Hi @tomhig, can you please provide a link to the article that your comment applies to.  Thanks!

**Comment by tomhig** [comment]
https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/business-continuity-disaster-recovery

**Comment by sericks007** [comment]
@tomhig, thanks!

@MicroSri, please consider updating this content with information about Recovery Time Objective (RTO) and Recovery Point Objective (RPO).

**Comment by sericks007** [comment]
Bug 606221 has been logged to track this issue.

**Comment by sericks007** [comment]
According to @MicroSri, we don't plan to include RPO and RTO timelines in technical documentation. It is called out in the SLA/Service description documentation and we would like to keep it there since there are legal implications and I want to avoid duplicating it in multiple places.
