### ISSUE TITLE
Full dataset generation interval in days was depricated in Commerce 10.0.17 release

### ISSUE THREAD

**Issue by kurthatlevik-inspirit365** [MicrosoftDocs/dynamics-365-unified-operations-public#3490]
You may remove the section describing "Full dataset generation interval in days" as it was deprecated in 10.0.17 - See also 
 https://docs.microsoft.com/en-us/dynamics365/commerce/get-started/removed-deprecated-features-commerce 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e572be35-7bb2-3c5d-2cae-7514a5278b0f
* Version Independent ID: a3295333-50b2-9c02-2c67-77bd75e437b2
* Content: [Commerce Data Exchange best practices - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/cdx-best-practices)
* Content Source: [articles/commerce/dev-itpro/CDX-Best-Practices.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/CDX-Best-Practices.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @jashanno
* Microsoft Alias: **jashanno**

**Comment by tonyafehr** [comment]
@josaw1, please review.

**Comment by josaw1** [comment]
Thanks for the feedback. I'm removing the section today.
