### ISSUE TITLE
Schemas are insufficient

### ISSUE THREAD

**Issue by gregsdennis** [MicrosoftDocs/dynamics-365-unified-operations-public#3491]
The subschemas of dependentProperties need a type declaration of object as well.  Otherwise arrays and other types will be accepted by the validation.

**Comment by josaw1** [comment]
Hi, @gregsdennis, thank you for your feedback. Are you referring to a specific topic? If so, can you please let me know which one?

**Comment by gregsdennis** [comment]
This issue was opened as a result of me providing feedback on a docs page. I'd have thought it would provide a link.  I'll see if I can find it in a bit.

**Comment by RobinARH** [comment]
Created bug 610090 to track this issue.

**Comment by samjarawan** [comment]
Thanks for the feedback, I've spoken with the dev team and they note this is a custom dependentSchema and should not require a type declaration.

**Comment by gregsdennis** [comment]
If you say so, but this schema will pass all sorts of values that probably don't represent what the model needs.  For example, this schema will pass for booleans, numbers, strings, arrays, and even null.  But it looks like it's really expecting an object.  I'd expect it to fail for the others.

**Comment by spacether** [comment]
Then how about putting type definitions in the oneOf schemas? Unset type allows every type
