### ISSUE TITLE
edit-cash-trans

### ISSUE THREAD

**Issue by kurthatlevik-inspirit365** [MicrosoftDocs/dynamics-365-unified-operations-public#3493]
There is a statement here : "**In a future release, capability will be added so that users can fix the records that failed through the user interface.**"

I this this is already available through the Edit Cash transactions as described here : https://docs.microsoft.com/en-us/dynamics365/commerce/edit-cash-trans

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb55971a-2b34-b03b-89f9-d5ab1da7c851
* Version Independent ID: 24c3e9d4-9021-629f-6d53-5994ae3da8d7
* Content: [Retail transaction consistency checker - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/valid-checker)
* Content Source: [articles/commerce/valid-checker.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/valid-checker.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by josaw1** [comment]
Thank you for your feedback. @anpurush can you please take a look?

**Comment by RobinARH** [comment]
Created bug 610091 to track this issue.

**Comment by analpert** [comment]
Updated article sent for content review. Once published, this work item can be closed.
