### ISSUE TITLE
Office add-in login Issue with 1809 and earlier versions of Windows 10

### ISSUE THREAD

**Issue by JohnLBevan** [MicrosoftDocs/dynamics-365-unified-operations-public#3494]
There's a reasonably common issue encountered consistently by users on older versions of Windows (i.e. pre 1909), which is not documented here.

Symptom:  When users attempt to sign in to the D365FO Office add-in, they see an empty page pop up instead of the expected logon dialogue (i.e. same symptoms as described n https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/office-integration/office-integration-troubleshooting?toc=/dynamics365/finance/toc.json#fixed-issue-the-excel-add-in-doesnt-correctly-run-or-enable-sign-in).

Resolution: Upgrade Windows tp 1909 or above (or install patch KB5003635.)  More info here: https://docs.microsoft.com/en-us/windows/release-health/resolved-issues-windows-10-1909#1610msgdesc 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb4baa3a-54a6-4159-f762-a9ad10706256
* Version Independent ID: ea906dbf-88ad-fe2d-c9ef-dcd28f1a6729
* Content: [Troubleshoot the Office integration - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/office-integration/office-integration-troubleshooting?toc=/dynamics365/finance/toc.json)
* Content Source: [articles/fin-ops-core/dev-itpro/office-integration/office-integration-troubleshooting.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/office-integration/office-integration-troubleshooting.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by josaw1** [comment]
Thank you for your feedback. @jasongre can you please take a look?

**Comment by RobinARH** [comment]
Created bug 610092 to track this issue.

**Comment by jasongre** [comment]
Thanks for reporting this. We'll get this added to the documentation.
