### ISSUE TITLE
Why isn't bundling supported in Commerce / Call Center?

### ISSUE THREAD

**Issue by danielzook** [MicrosoftDocs/dynamics-365-unified-operations-public#3496]
This article states: "Microsoft Dynamics 365 Commerce channels, such as online, point of sale (POS), and call centers, don't support revenue recognition (including the bundle functionality)... Items that are configured to use revenue recognition should not be added to orders or transactions that are created in Commerce channels..."

...but does not explain why?

The bundling feature is exactly what our company (and many other direct sales retailers) need, since we sell many items as "sales kits", where a pretend item is sold on the website, but in the warehouse it is fulfilled as two or more different items that are stocked in different locations and it would not make sense to pre-assemble.

Why isn't the bundling feature supposed to be used in Commerce / Call Center?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2e759b4-ee7e-56e5-6b32-3981042c6331
* Version Independent ID: 7d1125a1-71b2-d0dc-f826-f9c472606223
* Content: [Revenue recognition bundles - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/accounts-receivable/rev-rec-bundles)
* Content Source: [articles/finance/accounts-receivable/rev-rec-bundles.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/accounts-receivable/rev-rec-bundles.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @kweekley
* Microsoft Alias: **kweekley**

**Comment by josaw1** [comment]
Thank you for your feedback. @kweekley can you please take a look?

**Comment by RobinARH** [comment]
Created bug 610094 to track this issue.
