### ISSUE TITLE
10.0.20 has been released.  Is Store Commerce App still in preview?

### ISSUE THREAD

**Issue by danielzook** [MicrosoftDocs/dynamics-365-unified-operations-public#3497]
10.0.20 has been released.  Is Store Commerce App still in preview?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45ebad3c-1d63-3e3d-4b0c-84acb7cb84ef
* Version Independent ID: b5a17324-a2fc-48a6-28e0-db115a722469
* Content: [Store Commerce app in Microsoft Dynamics 365 Commerce (Preview) - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/store-commerce)
* Content Source: [articles/commerce/dev-itpro/store-commerce.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/store-commerce.md)
* Service: **dynamics-365-commerce**
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by josaw1** [comment]
Thank you for your question. The Store Commerce app is still in preview at this time.
