### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Ievgenm** [MicrosoftDocs/dynamics-365-unified-operations-public#3498]
There is a typo in next sentence 
"_Generate trial balance iwth pending type transactions_"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0cb4fd0-bd55-41d1-3a5d-4b8e23341222
* Version Independent ID: 6599993a-b69b-a530-f3de-03aa9b05a5fb
* Content: [What's new or changed in Dynamics 365 Finance 10.0.21 (October 2021) - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/get-started/whats-new-changed-10-0-21)
* Content Source: [articles/finance/get-started/whats-new-changed-10-0-21.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/get-started/whats-new-changed-10-0-21.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **kfend**

**Comment by josaw1** [comment]
Thank you for your feedback. This typo has been fixed.
