### ISSUE TITLE
SPED REINF - 2055

### ISSUE THREAD

**Issue by betespadula** [MicrosoftDocs/dynamics-365-unified-operations-public#3499]
[REMOVER - SERIE ENTRE 920 E 969]

Na documentação para o evento R-2055 consta que temos o range da Série 920 a 969, porém no layout 1.5.1 do SPED REINF removemos essa validação.

**_O modelo de documento fiscal é 04 ou 55 (um número de série entre 920 e 969)._**
---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: b9408285-78ac-f1db-f32b-9471e58bc9fc
* Version Independent ID: f0837934-3afd-c665-2487-7b94b2d0c1ae
* Content: [Eventos SPED-Reinf - Finance | Dynamics 365](https://docs.microsoft.com/pt-br/dynamics365/finance/localizations/latam-bra-sped-reinf)
* Content Source: [articles/finance/localizations/latam-bra-sped-reinf.md](https://github.com/MicrosoftDocs/Dynamics-365-Operations.pt-br/blob/live/articles/finance/localizations/latam-bra-sped-reinf.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @sndray
* Microsoft Alias: **sndray**

**Comment by josaw1** [comment]
Thank you for your feedback. @sndray can you please take a look?

**Comment by sndray** [comment]
@josaw1, the request is correct. We should remove "um número de série entre 920 e 969"

**Comment by kfend** [comment]
The English version of this topic has been updated to remove the incorrect statement and the changes will be published later today. Updated versions of this topic in additional languages will be available in the near future. Closing this issue.
