### ISSUE TITLE
Wrong excel template..?

### ISSUE THREAD

**Issue by Karppa1976** [MicrosoftDocs/dynamics-365-unified-operations-public#3500]
[Hi!
I tried to follow the instructions with cheque example. The excel template which can be downloaded via link is wrong, I think.
It does not contain the cell for a barcode.
Best regards
Kari ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b73b61fe-eb05-0a29-c2c8-2fca8ac0604c
* Version Independent ID: 442ffff2-343a-75b3-d2fb-db65a56f98fc
* Content: [Use Barcode data sources to generate bar code images - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/er-barcode-data-sources?toc=%2Fdynamics365%2Ffinance%2Ftoc.json%2F%3Fazure-portal%3Dtrue)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/er-barcode-data-sources.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/analytics/er-barcode-data-sources.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @NickSelin
* Microsoft Alias: **nselin**

**Comment by NickSelin** [comment]
Hello @Karppa1976,
The provided [link](https://download.microsoft.com/download/1/f/6/1f671963-73aa-48d5-ae69-45f21fe7dfb4/Cheque%20template.xlsx) returns the correct Excel template to me - it contains the SignatureImage picture that is located in the bottom right corner of the check mockup. Please, verify the downloaded template once more.
Best regards,
Nick

**Comment by Karppa1976** [comment]
Hi Nick!
Thanks for quick reply!
I am referring to this part.

![Text barcode excel](https://user-images.githubusercontent.com/75791143/128333514-db89c6c2-f9fb-4185-b26a-57886633d504.jpg)

The link in text previously is downloading the Excel version without the place for AmountBarcode.
In don't know which link is downloading the version "Cheque template Excel.xlsx.
Only link I can find is to file "Cheque template.xlsx (even if the hyperlink says Cheque template Excel.xlsx)


<html>
<body>
<p style="box-sizing: inherit; margin: 1rem 0px 0px; padding: 0px; outline-color: inherit; overflow-wrap: break-word; color: rgb(23, 23, 23); font-family: &quot;Segoe UI&quot;, SegoeUI, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Additionally, download the following Excel file that contains the modified template for the provided ER solution.</p><div class="table-scroll-wrapper" style="box-sizing: inherit; outline-color: inherit; overflow: auto hidden; color: rgb(23, 23, 23); font-family: &quot;Segoe UI&quot;, SegoeUI, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Content description | File name
-- | --
Report template | Check template Excel.xlsx

</div>
</body>
</html>

**Comment by NickSelin** [comment]
Hello @Karppa1976,
Yes, I confirmed that the wrong template is provided. It has been reported as a documentation issue. Please, use this [link](https://fix.lcs.dynamics.com/Issue/Details/?bugId=606497&dbType=3) to trace the progress of fixing this issue.
Best regards,
Nick

**Comment by Karppa1976** [comment]
Hi Nick,
Thanks for your kind help!
Best regards
Kari

**Comment by NickSelin** [comment]
Hello @Karppa1976,
The link on the documentation page has been updated to provide the proper Excel template. You can use it now.
Best regards,
Nick
