### ISSUE TITLE
Internet Explorer typo in heading

### ISSUE THREAD

**Issue by rrhkpmg** [MicrosoftDocs/dynamics-365-unified-operations-public#3502]
Heading (and anchor) at https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/system-requirements#internal-explorer-deprecation refers to _Intern**al** Explorer_ when the content makes it clear it should be _Intern**et** Explorer_ 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ad697b0-8c09-fd5e-9026-2960355bed0b
* Version Independent ID: 3f6fe592-c9d4-1123-6c3c-f09132d971ea
* Content: [System requirements for cloud deployments - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/system-requirements)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/system-requirements.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/system-requirements.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @sericks007
* Microsoft Alias: **sericks**

**Comment by sericks007** [comment]
@rrhkpmg, thanks for letting us know about this!  I really appreciate it!  I've fixed the issue, and the updated content will be published soon.
