### ISSUE TITLE
Confusing Steps

### ISSUE THREAD

**Issue by ItCommitsTheCode** [MicrosoftDocs/dynamics-365-unified-operations-public#3503]
In the heading [Register the app in the Finance and Operations app so that Retail Server trusts it](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/consume-retail-server-api#register-the-app-in-the-finance-and-operations-app-so-that-retail-server-trusts-it), step 3 uses the following text:

"On the Relying parties FastTab, select Add. Enter the client ID that was generated _during the Retail server app registration_ in Azure. Set the Type field to Confidential and the UserType field to Application."

Emphasis mine.

This statement should be revised to state the following; again, emphasis mine:

"On the Relying parties FastTab, select Add. Enter the client ID that was generated _during the app registration for the client_ in Azure. Set the Type field to Confidential and the UserType field to Application."

The reason for this changes is that the "Retail server app registration" client ID is different from the "app registration for the client" client ID, and using the incorrect one leads to failure in configuration.  These quoted names are the same used by prior headings--leading to the confusion.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2aaab0fa-b1ac-51c0-2329-73ab077477b2
* Version Independent ID: dc8cf3fc-4c9f-731c-a99e-d70b8b940428
* Content: [Consume Retail Server APIs in external applications - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/consume-retail-server-api)
* Content Source: [articles/commerce/dev-itpro/consume-retail-server-api.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/consume-retail-server-api.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by mugunthanm** [comment]
Thanks for the feedback, updated the document.

**Comment by ItCommitsTheCode** [comment]
Thanks!
