### ISSUE TITLE
Enabling the flight DMFEnableExecutionHistoryCleanupSystemJob in D365FO

### ISSUE THREAD

**Issue by Eshaghzadeha** [MicrosoftDocs/dynamics-365-unified-operations-public#3508]
It seems that Microsoft docs article "URL: https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/data-import-export-job#job-history-clean-up-and-archival-available-for-preview-in-platform-update-39-or-version-10015" is not updated. 

There is no need to activate this on 10.0.20 and newer update while those who use D365FO with older version than 10.0.20 need to register a support case to enable the flight DMFEnableExecutionHistoryCleanupSystemJob.

Regards,
Alireza Eshaghzadeh

**Comment by kfend** [comment]
@Eshaghzadeha - Thank you for the feedback.
@Peakerbl  - can you please take a look and update the topic?

**Comment by kfend** [comment]
Topic has been updated and changes published.
