### ISSUE TITLE
Location of the XML element is important

### ISSUE THREAD

**Issue by ibruynin** [MicrosoftDocs/dynamics-365-unified-operations-public#3513]
The location of the XML element is very important.
If it is not exactly after //Publisher all seems well, but it does not have any effect in ISV studio.

Using powershell this can be achieved automatically (in case you have several models)

```
              # $_ is the descriptor xml file
              [xml]$XmlDocument = Get-Content -Path $_
              while ($xmlDocument.AxModelInfo.SolutionId.Count -gt 0) 
              {
                  Write-Host "Removing SolutionId"
                  $node = $xmlDocument.SelectSingleNode("//SolutionId")
                  [Void]$node.ParentNode.RemoveChild($node)
              }
              $e=$XmlDocument.CreateElement("SolutionId")
              $e.set_InnerText("<< ADD ID HERE >>")

                $axmodelinfo=$XmlDocument.AxModelInfo
                $pubElement = $axmodelinfo.SelectSingleNode('//Publisher')
                $axmodelinfo.InsertAfter($e, $pubElement)

              # Enable this when you want readable xml
              # cfr. https://devblogs.microsoft.com/powershell/format-xml/
              #Format-XML $XmlDocument.InnerXml | Set-Content -Path $_
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 004ff9c3-7bd6-320a-4142-3f5bdd682090
* Version Independent ID: d1fb3726-a506-a5bb-8fa8-9c1617061e17
* Content: [Link X++ modules from ISV packages by using ISV Studio - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/isv-studio-solutions)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/isv-studio-solutions.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/dev-tools/isv-studio-solutions.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @jorisdg
* Microsoft Alias: **jorisde**

**Comment by kfend** [comment]
@ibruynin - Thank you for the feedback.
@jorisdg - Can you please take a look and update the topic with a note that calls this out if needed?

**Comment by RobinARH** [comment]
I updated the doc to let people know the order of elements does matter. It will go live later today. If you want your code sample added to the docs, please submit a PR. Thanks!
