### ISSUE TITLE
Admin reference could be clear on no cross-tenant support

### ISSUE THREAD

**Issue by rrhkpmg** [MicrosoftDocs/dynamics-365-unified-operations-public#3515]
The configuration for "The next step in the process is to provide Dataverse with the Finance and Operations instance to connect to. The following steps walk through this part of the process." including the **Tenant ID** suggests the possibility that Dataverse in one tenant can connect to an F&O instance in a different tenant, particularly given that the **Information** box only states that "The AAD application must be created on the same tenant as Finance and Operations.", without stating that the CE environment must be on the same tenant.  Having spent some time trying to configure-cross tenant virtul entities, we logged a support call (2108180050002372) and were quickly told that virtual entities aren't supported cross-tenant. If this is the case, would it be worth making that clearer in the documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8065cd89-f253-c50b-ed2e-7b84e5b2409c
* Version Independent ID: 8c7e311a-582c-1ac6-328e-be817a62924c
* Content: [Finance and Operations and Dataverse admin reference - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/power-platform/admin-reference#enabling-virtual-entities)
* Content Source: [articles/fin-ops-core/dev-itpro/power-platform/admin-reference.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/power-platform/admin-reference.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by kfend** [comment]
@rrhkpmg - Thank you for the feedback.
@Sunil-Garg - Can you please take a look and update the topic as necessary?

**Comment by sericks007** [comment]
PR 14087 has been merged and will be published soon -- so closing this issue.
