### ISSUE TITLE
SPED CONTRIBUICOES - REGISTROS A110-A111

### ISSUE THREAD

**Issue by betespadula** [MicrosoftDocs/dynamics-365-unified-operations-public#3516]
[Insira comentários aqui]

O escopo da localização informa que atendemos os registros A110-A111, porém não suportamos.

Solicito alterar tal REMOVER esses registros da obrigação do SPED Contribuições.
---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 37344ff4-2d58-847a-1b2c-227a5776152b
* Version Independent ID: 96b381ef-f0d5-5f2a-c459-404e0050fe91
* Content: [Escopo da localização brasileira - Finance | Dynamics 365](https://docs.microsoft.com/pt-br/dynamics365/finance/localizations/latam-bra-scope)
* Content Source: [articles/finance/localizations/latam-bra-scope.md](https://github.com/MicrosoftDocs/Dynamics-365-Operations.pt-br/blob/live/articles/finance/localizations/latam-bra-scope.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @sndray
* Microsoft Alias: **sndray**

**Comment by kfend** [comment]
@sndray - Can you please take a look at this issue and address as needed?

**Comment by sndray** [comment]
The current content is valid. We currently support these records A110 and A111 in SPED Contributions feature. I've already talked with the user who has logged the feedback and I received a confirmation that it was a mistake. The suggestion is not applicable.

**Comment by kfend** [comment]
@sndray - Thanks for the quick resolution!
