### ISSUE TITLE
autocharge

### ISSUE THREAD

**Issue by Kirknel** [MicrosoftDocs/dynamics-365-unified-operations-public#3519]
The Chapter for describing autocharges should aslo mention that you need to set the procurement and sourcing parameters > Price tab: Find autocharge for header = Yes and find Autochage for line = Yes; otherwise no charges will automatically be added to the PO header or lines..
Cheers, Mai

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c38848d-a6f7-c225-468c-c7d7a9884b06
* Version Independent ID: 8dbdb7c5-13f2-3c42-d0b0-b46460d29bd7
* Content: [Automatic allocation of charges - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/procurement/automatic-charges-allocation)
* Content Source: [articles/supply-chain/procurement/automatic-charges-allocation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/procurement/automatic-charges-allocation.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @dasani-madipalli
* Microsoft Alias: **damadipa**

**Comment by kfend** [comment]
@Kirknel - Thank you for the feedback.
@dasani-madipalli - Can you please take a look and update the topic as needed?

**Comment by dasani-madipalli** [comment]
@kfend I am no longer on this team and moved over to windows so I won't be maintaining this.

**Comment by kfend** [comment]
@dasani-madipalli - Thank you for letting me know.
@kamaybac - can you please take a look at this and assign it to the new author?

**Comment by kamaybac** [comment]
@Kirknel , thank you for reporting this issue. We have updated the topic.
