### ISSUE TITLE
Personalization and Updates?

### ISSUE THREAD

**Issue by jillchapman** [MicrosoftDocs/dynamics-365-unified-operations-public#352]
Hi, we are just implementing and our consultants are telling us that making explicit personalizations through the front end of the application are not supported when you update or take a patch.  Is that correct?  They are saying we need to make modifications through the back end to support field moves and custom fields?  Thanks in advance.

**Comment by ShylaThompson** [comment]
Hi @jillchapman, thanks for your question. We'll get back to you soon with some clarification.

**Comment by jasongre** [comment]
@jillchapman , in Dynamics 365 for Finance and Operations, personalizations ARE maintained across updates and should still exist after an update or patch. This was not true for some previous AX versions, but the personalization system was rewritten for Finance and Operations to allow this.

**Comment by jillchapman** [comment]
Thank you for verifying that for us!
