### ISSUE TITLE
Incorrect D365 Path for Configuration Key

### ISSUE THREAD

**Issue by JS876** [MicrosoftDocs/dynamics-365-unified-operations-public#3522]
The D365 path to setup the configuration keys listed under the section below is incorrect:

`Recommended configurations (with up-to-date maturity information to denote confidence of functionality)` 

It currently lists: 

`Retail and Commerce > Headquarters setup > Parameters > Commerce parameters`

When it should be:

`Retail and Commerce > Headquarters setup > Parameters > Commerce shared parameters`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e572be35-7bb2-3c5d-2cae-7514a5278b0f
* Version Independent ID: a3295333-50b2-9c02-2c67-77bd75e437b2
* Content: [Commerce Data Exchange best practices - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/cdx-best-practices)
* Content Source: [articles/commerce/dev-itpro/CDX-Best-Practices.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/CDX-Best-Practices.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @jashanno
* Microsoft Alias: **jashanno**

**Comment by tonyafehr** [comment]
@josaw1, please review.

**Comment by josaw1** [comment]
Adding @mugunthanm.

BUG 649244 created to track.

**Comment by mugunthanm** [comment]
Thanks for the feedback, the doc is updated.
