### ISSUE TITLE
Title for item out of date

### ISSUE THREAD

**Issue by NathanDL** [MicrosoftDocs/dynamics-365-unified-operations-public#3525]
In section **Deploy a package**, item 3 has title

_Select the **E-Commerce (Preview)** tab._

this should be amended to 

_Select the **E-Commerce** tab._

This is to align with the screenshot in this section, and the new LCS tab name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dd9dc1b-79a4-fd01-cd96-4d045a6d0049
* Version Independent ID: 0bf64cdb-0710-c8b1-d35f-50c055c8d2f1
* Content: [Package configurations and deploy them to an online environment - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/e-commerce-extensibility/package-deploy)
* Content Source: [articles/commerce/e-commerce-extensibility/package-deploy.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/e-commerce-extensibility/package-deploy.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @samjarawan
* Microsoft Alias: **samjar**

**Comment by tonyafehr** [comment]
@josaw1, please review.

**Comment by josaw1** [comment]
Thanks for your feedback. This change will go live today.
