### ISSUE TITLE
Real life examples should be added

### ISSUE THREAD

**Issue by Neeraj2912** [MicrosoftDocs/dynamics-365-unified-operations-public#3526]
Real life examples should be given for this method of depreciation - consumption

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd02b400-3cbf-67f2-4fa5-42e86b5ec788
* Version Independent ID: a4e02360-8369-4496-cb68-b5007df90d5d
* Content: [Consumption depreciation - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/fixed-assets/consumption-depreciation)
* Content Source: [articles/finance/fixed-assets/consumption-depreciation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/fixed-assets/consumption-depreciation.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @ShylaThompson
* Microsoft Alias: **saraschi**

**Comment by tonyafehr** [comment]
@moaamer, please review.

**Comment by moaamer** [comment]
We will consider add examples in addition to what we have in this article to give it more insights.
