### ISSUE TITLE
Do not have an option to Select Variants Suggestions as described.  

### ISSUE THREAD

**Issue by amit-365** [MicrosoftDocs/dynamics-365-unified-operations-public#3527]
Hi, 

I am testing the new variant creation for an engineering product. I am on 10.0.21 PEAP version.

I created the engineering product as per steps 1 to 10 shown in the document. Step 11 asks to Select Variants suggestions menu option. This option is missing from my form. 

Am I missing something or the document is referring to something not included in the 10.0.21 PEAP version. 

![image](https://user-images.githubusercontent.com/74725901/130757149-f9a50715-8cc5-4858-875d-35a2eda027f9.png)

Look forward to hearing from you,

Regards,

Amit

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: caf84e31-08bf-6cbf-d41f-f8151ea56545
* Version Independent ID: bc104a8e-095a-38fb-f9a4-fe29d9f6d748
* Content: [Generate variants for engineering products - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/engineering-change-management/engineering-variants)
* Content Source: [articles/supply-chain/engineering-change-management/engineering-variants.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/engineering-change-management/engineering-variants.md)
* Service: **dynamics-365-supply-chain**
* GitHub Login: @t-benebo
* Microsoft Alias: **benebotg**

**Comment by tonyafehr** [comment]
@kamaybac, please review.
