### ISSUE TITLE
Editing and creating a workflow

### ISSUE THREAD

**Issue by CharlieNZSmithandSmith** [MicrosoftDocs/dynamics-365-unified-operations-public#353]
Adding to the documentation above, in order to edit/create the workflows per the "Canvas" mentioned.
You won't be able to open the "canvas" application in Chrome as of 6/Sep/2018 version Version 68.0.3440.106 (Official Build) (64-bit).

You should be able to edit the workflows via Internet Explorer 11, or Edge.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79542580-63b5-ee7f-7faf-f9727b80aedf
* Version Independent ID: d730568b-b04a-5ac5-1d43-f4720369c7ea
* Content: [Create workflows - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/organization-administration/create-workflow)
* Content Source: [articles/fin-and-ops/organization-administration/create-workflow.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/organization-administration/create-workflow.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @sericks007
* Microsoft Alias: **donaldc**

**Comment by sericks007** [comment]
Thanks for letting us know!  I've assigned this to the PM to verify.

**Comment by sericks007** [comment]
Bug 246536 has been logged to track this issue.

**Comment by ChrisGarty** [comment]
Updated the [System Requirements](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/system-requirements) documentation to point at the need to install an Chrome extension to get ClickOnce working in Chrome browsers.

**Comment by CharlieNZSmithandSmith** [comment]
The documentation doesn’t clarify the following points:

  *   What a ClickOnce application is.
  *   What the official/recommended extension to download for Chrome is called.
  *   Where a user can download it.

What happens if the extension is discontinued? Is there an alternative? There’s a big assumption made on what browsers most users will be on.

The ticket shouldn’t be closed without user verification.

**Comment by ChrisGarty** [comment]
The system requirements updated note will mention the Edge, IE, and Chrome browsers, will mention that a 64-bit OS is needed (no iOS/Safari), will link to the extension, and will say that ClickOnce is what is used to run the Workflow designer. If the extension is discontinued then we’ll update to link to a different suggested extension. 
Chrome is greater than 60% of our browser usage so it was great that you prompted us to clarify the ClickOnce extension need for Chrome in the docs. 
Thanks! Keep the feedback coming!
