### ISSUE TITLE
Where is the Landed Cost module?

### ISSUE THREAD

**Issue by ronsonntag54** [MicrosoftDocs/dynamics-365-unified-operations-public#3531]
[Enter feedback here]
I looked for it in the current 10.0.20 version and nothing comes up. Please provide the exact steps to access this module. It is not in the left-hand list anywhere!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6f88889-6f15-6aaf-5afd-b8618520d620
* Version Independent ID: d730b31a-4d2f-7e87-273b-1e23d7170f00
* Content: [Landed cost parameters setup - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/landed-cost/landed-cost-parameters#general-tab)
* Content Source: [articles/supply-chain/landed-cost/landed-cost-parameters.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/landed-cost/landed-cost-parameters.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @sherry-zheng
* Microsoft Alias: **chuzheng**

**Comment by sericks007** [comment]
@ronsonntag54, thanks for providing this feedback.

@sherry-zheng, please review and provide the information requested.

**Comment by RobinARH** [comment]
Created bug 620268 to track this issue.

**Comment by EpimetheusJohnson** [comment]
@ronsonntag54 did you tried to enable the landed cost feature at the beginning?

**Comment by ronsonntag54** [comment]
Where do I enable this feature?

**Comment by EpimetheusJohnson** [comment]
@ronsonntag54 
![image](https://user-images.githubusercontent.com/14008006/134791521-355ace46-3dc1-416d-bc11-88c31444247a.png)
![image](https://user-images.githubusercontent.com/14008006/134791551-05335933-9136-473c-bfe7-b530595694ca.png)

**Comment by kamaybac** [comment]
@ronsonntag54 , we have now updated the documentation by adding a topic about how to enable the module:
https://docs.microsoft.com/en-us/dynamics365/supply-chain/landed-cost/landed-cost-enable 

Thank you, @EpimetheusJohnson , for providing the instructions here already.
