### ISSUE TITLE
Call center refund methods allow manually typing/adding and Saving of cash payments.

### ISSUE THREAD

**Issue by thedynamicsgirl** [MicrosoftDocs/dynamics-365-unified-operations-public#3533]
[As per Microsoft documentation, Call center refund methods do not allow CASH payments or show it in the dropdown. But if we type the number for cash payment in the Retail payment field and SAVE it, it saves ok and does not throw an error]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3c9ff31-6d72-a2cf-9b6c-0d43cd654ccc
* Version Independent ID: cd9b6f87-4be4-f46b-a32d-36f41bbf7318
* Content: [Refund payment processing in call centers - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/call-center-refund-payments)
* Content Source: [articles/commerce/call-center-refund-payments.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/call-center-refund-payments.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @hhainesms
* Microsoft Alias: **hhaines**

**Comment by sericks007** [comment]
@thedynamicsgirl, thanks for providing this feedback.

@hhainesms, please considering updating the content based on this feedback.

**Comment by RobinARH** [comment]
Created bug 620269 to track this issue.

**Comment by sericks007** [comment]
@thedynamicsgirl, this issue has been fixed.  Thanks for reporting this!
