### ISSUE TITLE
human resources import via rest api

### ISSUE THREAD

**Issue by amarco** [MicrosoftDocs/dynamics-365-unified-operations-public#3534]
I see there is a nice example dealing the exporting data from dynamics human resources, however it would be nice to try and get a detailed example/explanation on how to do a import into dynamics human resource using the rest api.

**Comment by RobinARH** [comment]
Created bug 620270 to track this issue.

**Comment by josaw1** [comment]
@twheeloc bumping this back up for you.

**Comment by twheeloc** [comment]
@amarco, you can find more information regarding importing here: https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/data-management-api
