### ISSUE TITLE
Exact definitions need for Scale, NoOfDecimals, and Precision. This page is still confusing!

### ISSUE THREAD

**Issue by ronsonntag54** [MicrosoftDocs/dynamics-365-unified-operations-public#3536]
[Enter feedback here]
In Visual Studio, when you lookup a real number field from any Data Entity, it always refers to 

For example: LINENUM is inherited (in this example) from LineNum. LineNum shows the properties of: Scale=16, NoOfDecimals=10 and is the top-level object. Scale normally refers to the number of decimals to the right of the decimal point. Precision is the total number of digits of precision to the left + right of the decimal point.

Your article page uses terms like "maximum precision of six decimal places". You just merged two separate concepts. Does this mean that D365 F&O can only handle 6 digits of precision, or, are you saying that you can really only have a MAXIMUM of SCALE=6 no matter what Visual Studio says?

We really need Microsoft to pin this down and use the terms PRECISION, SCALE, and Number of Decimals in a consistent way and fully indicate what happens when Visual Studio says that a real object (at any level of inheritance) has SCALE=16, and default NoOfDecimals, or, SCALE=2 and nothing for NoOfDecimals, for example.

As it stands, neither Visual Studio nor this page provides a consistent and non-conflicting explanation of what is going on.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4be50ccc-ed32-eabe-c717-cf2b319d6d22
* Version Independent ID: 4f8d76c5-2ca7-b191-9317-15bfdbb7b3fc
* Content: [Extending decimal point precision for selected data types - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/extensibility/decimal-point-precision)
* Content Source: [articles/fin-ops-core/dev-itpro/extensibility/decimal-point-precision.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/extensibility/decimal-point-precision.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @MichaelFruergaardPontoppidan
* Microsoft Alias: **mfp**

**Comment by sericks007** [comment]
@ronsonntag54, thank you for providing this feedback.

@MichaelFruergaardPontoppidan, please review and consider updating the documentation as requested.

**Comment by MichaelFruergaardPontoppidan** [comment]
Thank you for the feedback.

This page is describes how to extend the "NoOfDecimals" property.  In the first paragraph on the page we introduce the term "decimal point precision" to describe the meaning of the property.  This is different than the "Scale" property, which is not extensible, but defined on the root EDT in the hierarchy.  That is why the topic also lists the maximum precision possible.

I've rewritten the topic to avoid the term "precision" when referring to NoOfDecimals as that is confusing.

This page is not about how these properties manifests themselves under the covers, but high level NoOfDecimals is rounding applied at the UI control level, whereas Scale applies at the DB/Storage level.

**Comment by sericks007** [comment]
MFP's update to the content will be published soon.
