### ISSUE TITLE
1 GB 

### ISSUE THREAD

**Issue by Alpa-Chino** [MicrosoftDocs/dynamics-365-unified-operations-public#3539]
Hi!

We just received this from MSFT support after we filed a support ticket about why a 1 Gb Power Platform Environment was deployed during the deployment of an FNO Tier 2, because we did not set the Configure Pplatform Environment to Yes.
I think the documentation should reflect this information.

"Regard the bizarre situation, it is turn out that the Power Platform Integration is a requirement for all F&O environments going forward. This resulted in the 1GB for an empty Power Platform Environment (it won’t have DV deployed yet) is happening because these environments can still house resources such as Power Apps and Power Automate flows even without a DV database deployed." 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9d684ec-511b-b80e-bc2f-700804abe720
* Version Independent ID: 72f50796-990d-d9c0-7e52-52f12d24af90
* Content: [Deploy a new environment - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/deployenvironment-newinfrastructure)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/deployenvironment-newinfrastructure.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/deployment/deployenvironment-newinfrastructure.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @rashmansur
* Microsoft Alias: **rashmim**

**Comment by sericks007** [comment]
@Alpa-Chino, thank you for providing this feedback.

@rashmansur, please update the documentation based on this feedback.

**Comment by RobinARH** [comment]
Created bug 620272 to track this issue.
