### ISSUE TITLE
Wrong link for redirecting to .NET Framework 4.6.2.

### ISSUE THREAD

**Issue by JonatanTorino** [MicrosoftDocs/dynamics-365-unified-operations-public#3540]
On https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/retail-sdk/migrate-sdk#what-is-affected
Both .net framework 4.51 and 4.6.2, link to same framework 4.5.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 776f646a-f316-8c84-d190-57ecd88547a0
* Version Independent ID: 80208288-e39f-bacc-c8ad-7c51470e9cce
* Content: [Migrate the Retail SDK from Visual Studio 2015 to Visual Studio 2017 - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/retail-sdk/migrate-sdk)
* Content Source: [articles/commerce/dev-itpro/retail-sdk/migrate-sdk.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/retail-sdk/migrate-sdk.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by sericks007** [comment]
@JonatanTorino, thank you for providing this feedback.

@mugunthanm, please fix the links.

**Comment by mugunthanm** [comment]
Thanks for providing the feedback, updated the download the link in the documentation.
