### ISSUE TITLE
clarify Key vault requirements for Azure Data Lake

### ISSUE THREAD

**Issue by mshyx** [MicrosoftDocs/dynamics-365-unified-operations-public#3543]
Hi Team,
I confuse on  paragraph [Add secrets to the key vault](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/configure-export-data-lake#addsecrets)
As doc mentioned add three key vaults, however missed step : enter the connection string which obtained from the storage account.  If CX only follow this doc, the Test Azure Storage in FnO will be failed.
And didn't explain these three key vaults used for. because if didn't add [app-id] & [app-secret] the test is workable as well.

Ref. correct document [Create a Key Vault and a secret](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/entity-store-data-lake#create-a-key-vault-and-a-secret)

Please correct me, if there is anything mistake. 

regards
Henry

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c84e15d4-bcac-038a-2b1e-8c456ee25bd9
* Version Independent ID: 478b5f33-f745-1df2-8fe0-da9e64233165
* Content: [Configure export to Azure Data Lake - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/configure-export-data-lake#addsecrets)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/configure-export-data-lake.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/configure-export-data-lake.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by sericks007** [comment]
@mshyx, thank you for providing this feedback.

@MilindaV2, please review and update the content if needed.

**Comment by RobinARH** [comment]
Created bug 620273 to track this issue.
