### ISSUE TITLE
Misleading statement, MS managed should be changed to Self-service

### ISSUE THREAD

**Issue by terabaitas** [MicrosoftDocs/dynamics-365-unified-operations-public#3545]
in Prerequisites second paragraph it is a wrong statement:

Create a self-service environment in LCS. The environment should be in a Deployed state. It must be a **Microsoft-managed** environment. Cloud-hosted, development environments can be used only for the Upgrade from AX 2012 - Data upgrade in development environments procedure.

should be 

Create a self-service environment in LCS. The environment should be in a Deployed state. It must be a **Self-service** environment. Cloud-hosted, development environments can be used only for the Upgrade from AX 2012 - Data upgrade in development environments procedure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42eeda26-b0da-fe66-ef03-a26dbf16d923
* Version Independent ID: 5cb45351-842a-b98b-1120-6eb2f657fe47
* Content: [Upgrade from AX 2012 - Data upgrade in self-service environments - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/data-upgrade-self-service)
* Content Source: [articles/fin-ops-core/dev-itpro/migration-upgrade/data-upgrade-self-service.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/migration-upgrade/data-upgrade-self-service.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @sarvanisathish
* Microsoft Alias: **sarvanis**

**Comment by sericks007** [comment]
@terabaitas, thanks for providing this feedback!

@rashmansur, please update the content.

**Comment by sericks007** [comment]
@veeravendhan-s, please review and update the content.

**Comment by RobinARH** [comment]
Created bug 620274 to track this issue.
