### ISSUE TITLE
Unclear what happens with 

### ISSUE THREAD

**Issue by ryanwwhittaker** [MicrosoftDocs/dynamics-365-unified-operations-public#3546]
Hi,
The page talks about three common planned maintenance activities:

- Operating system (OS) security updates
- Security hotfixes
- Microsoft package updates

However the rest of the page then only goes on to describe what happens for operating system updates.

What happens with security hotfixes and MS package updates?
I'm guessing that security hotfixes are part of OS security updates (?) - but this should be made clear.

I'm also then guessing that the package updates are platform updates - is there documentation on downtime etc for this elsewhere?  If so it should be linked to, otherwise I feel it should be clarified here.

What about software deployable packages - do these fall into same category as MS package updates?

Just needs a little more clarifying.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fcc1802-115b-4ac2-f34f-aa73eac426f4
* Version Independent ID: d758bfc6-245e-43d6-8bde-31282cea0a64
* Content: [Planned maintenance in self-service environments FAQ - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/plannedmaintenance-selfservice)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/plannedmaintenance-selfservice.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/deployment/plannedmaintenance-selfservice.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @sarvanis
* Microsoft Alias: **sarvanis**

**Comment by sericks007** [comment]
@ryanwhittake, thank you for providing this feedback.

@rashmansur, please review and update the content as needed.

**Comment by RobinARH** [comment]
Created bug 620275 to track this issue.
