### ISSUE TITLE
Issue with Screen recorder code

### ISSUE THREAD

**Issue by owlkeeper** [MicrosoftDocs/dynamics-365-unified-operations-public#3548]
[I am trying to install the screen recording extension from : https://github.com/microsoft/FMLab/tree/master/FMLab/TaskRecorderScreenshot. In both Chrome and Edge, it rejects with an error message : manifest is not valid json]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5762f9e-d7f4-e7fc-49c7-6db64c01bc6a
* Version Independent ID: 2aab18ad-f2f1-c0ad-c109-38806c8491a3
* Content: [Task recorder resources - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/user-interface/task-recorder?toc=/dynamics365/finance/toc.json#taking-screenshots-in-task-recorder)
* Content Source: [articles/fin-ops-core/dev-itpro/user-interface/task-recorder.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/user-interface/task-recorder.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by RobinARH** [comment]
Created bug 620276 to track this issue.

**Comment by jasongre** [comment]
@owlkeeper What version of Chrome/Edge are you testing on? I was able to successfully load and use the extension from that location today in both browsers.

**Comment by owlkeeper** [comment]
***@***.***

***@***.***
