### ISSUE TITLE
Security report display is not correct.

### ISSUE THREAD

**Issue by WayneLi001** [MicrosoftDocs/dynamics-365-unified-operations-public#3549]
Hi Par,

 My customer have concern that the security report in Microsoft Document is different with the one they run in D365.
Can you please help to check, is the report changed, but doc is not the latest?
Let's take Security role access report as an example:
In the document https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/security-reports, it is:

![image](https://user-images.githubusercontent.com/89968206/131805750-10353bae-987c-4c33-a380-334340549714.png)

But when you go to run it in D365, the format is different, it could not be expanded:
![image](https://user-images.githubusercontent.com/89968206/131805970-ecf9c88f-ddfe-4749-acf2-969a11dc0167.png)

I checked in internal instance, it's the same format with customer.
Also, for Role to User assignment, it's the same.
Can you please help confirm whether it's document issue? 

Thanks
Wayne
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66aaa30f-ed7f-0436-845f-c2cad2022b78
* Version Independent ID: 4d0add4b-63a4-520b-d22e-a512203f8439
* Content: [Out-of-box security reports - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/security-reports#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/security-reports.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/sysadmin/security-reports.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Peakerbl
* Microsoft Alias: **peakerbl**

**Comment by sericks007** [comment]
@WayneLi001, thanks for providing this feedback.

@Peakerbl, please review and update the content, if needed.

**Comment by RobinARH** [comment]
Created bug 620277 to track this issue.

**Comment by Peakerbl** [comment]
@WayneLi001 thanks for reporting this. This is a bug and you can track the fix here: [Details for issue 616017](https://fix.lcs.dynamics.com/Issue/Details?bugId=616017&dbType=3&qc=9515f02771ac4a24a1b0b13765201e38d205b9b1285f6db36548bf54e704c973)
