### ISSUE TITLE
Application 8.0

### ISSUE THREAD

**Issue by rat-af** [MicrosoftDocs/dynamics-365-unified-operations-public#355]
It would be good to have an update which indicates that this is not possible for a subscription DEV box on application 8.0.  Application 8.0 removed administrator access on the DEV boxes in a subscription, as such, the script mentioned can only be run for 'cloud hosted environments'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e3053c7-726c-6c40-2f7c-88d2fb306d37
* Version Independent ID: 7308c618-304e-2699-8d2a-eb54d7a53a9a
* Content: [Create new users on development machines - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-tools/enable-development-machine)
* Content Source: [articles/dev-itpro/dev-tools/enable-development-machine.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-tools/enable-development-machine.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RobinARH
* Microsoft Alias: **robadawy**

**Comment by robadawy** [comment]
Yes. The article needs this note:
"This is not supported on development environment running in the Microsoft subscription where developers have no administrator access to the VM (Platform update 12 deployments or newer)"
