### ISSUE TITLE
Snapshot config name changed

### ISSUE THREAD

**Issue by d3fr0g** [MicrosoftDocs/dynamics-365-unified-operations-public#3550]
Under the Screenshots section the docs mention Microsoft.Dynamics.RegressionSuite.WindowsApp.exe.config, in the actual folder it is called Microsoft.Dynamics.RegressionSuite.WpfApp.exe.config currently.

It should be also explicit if the ConsoleApp supports this or not. The Microsoft.Dynamics.RegressionSuite.ConsoleApp.exe.config  also contains this config element.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a89192ad-bcdc-5e3b-15d6-20fac6d5d29f
* Version Independent ID: 5b278db8-9a7f-523d-0ebe-eec9004f9779
* Content: [Regression suite automation tool tutorial - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/perf-test/rsat/rsat-tutorial)
* Content Source: [articles/fin-ops-core/dev-itpro/perf-test/rsat/rsat-tutorial.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/perf-test/rsat/rsat-tutorial.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **rhaertle**

**Comment by sericks007** [comment]
@d3fr0g, thanks for providing this feedback!

@RobinARH, please review and make any necessary updates.

**Comment by RobinARH** [comment]
@FrankDahl - Can you take a look? Thanks - Robin

**Comment by RobinARH** [comment]
Created bug 620278 to track this issue.
