### ISSUE TITLE
Enabling virtual entities should specify that Dataverse user must also be F&O user

### ISSUE THREAD

**Issue by rrhkpmg** [MicrosoftDocs/dynamics-365-unified-operations-public#3556]
The page details setting up an F&O user for the AAD app registration, so it would seem reasonable that the process of enabling virtual entities would use this app registration credentials when querying available entities. Apparently that isn't the case, and the credentials with which the administrator is accessing Dataverse must also be an F&O user. It would be helpful if the documentation specified this as a prerequisite & listed the necessary F&O security roles.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8065cd89-f253-c50b-ed2e-7b84e5b2409c
* Version Independent ID: 8c7e311a-582c-1ac6-328e-be817a62924c
* Content: [Finance and Operations and Dataverse admin reference - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/power-platform/admin-reference#enabling-virtual-entities)
* Content Source: [articles/fin-ops-core/dev-itpro/power-platform/admin-reference.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/power-platform/admin-reference.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by twheeloc** [comment]
@rrhkpmg, Thanks for the feedback. 

@Sunil-Garg Please review and update the content as needed.
