### ISSUE TITLE
SIRET number for legal entity information

### ISSUE THREAD

**Issue by anboudin** [MicrosoftDocs/dynamics-365-unified-operations-public#3557]
Hi,

Some customer asked where to input SIRET number on legal entity. 
There is no information on this page regarding SIRET number and as D365 wording for SIRET has not been changed, answer is not obvious. 

Could you please add on last part of document that SIRET number should be setup on Legal entity Tax registration number?

thank you
Annaick

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd3ff60f-633a-f311-aaf9-3741b5b5217d
* Version Independent ID: 499b0357-154f-6470-22a3-bef418f57fcb
* Content: [FR-00003 NAF codes and Siret numbers - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/tasks/fr-00003-naf-codes-siret-numbers)
* Content Source: [articles/finance/localizations/tasks/fr-00003-naf-codes-siret-numbers.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/tasks/fr-00003-naf-codes-siret-numbers.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @EvgenyPopovMBS
* Microsoft Alias: **epopov**

**Comment by EvgenyPopovMBS** [comment]
@epodkolz, please have a look.

**Comment by epodkolz** [comment]
PR: https://github.com/MicrosoftDocs/Dynamics-365-Operations/pull/12186
