### ISSUE TITLE
Need a note on which environments this doesn't apply to

### ISSUE THREAD

**Issue by bstorie** [MicrosoftDocs/dynamics-365-unified-operations-public#3558]
[Enter feedback here]
Can you add a comment/note/section that says this does not apply to non-azure deployed environments such as the VHD and on-premises. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c9fa18d-6a11-681c-b5e4-e38f7b2af06e
* Version Independent ID: 983af4fc-39c9-6527-fb6a-8c5f858dff39
* Content: [Synchronize self-service installers in Dynamics 365 Commerce - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/synchronize-installers)
* Content Source: [articles/commerce/dev-itpro/Synchronize-installers.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/Synchronize-installers.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @jashanno
* Microsoft Alias: **jashanno**

**Comment by twheeloc** [comment]
@bstorie, thank you for the feedback.

@jashanno Please review and update the content as needed.

**Comment by sericks007** [comment]
This content has been updated.
