### ISSUE TITLE
I would like to know the source tables for the CostObjectStatementCache table

### ISSUE THREAD

**Issue by ArnaudLherondel** [MicrosoftDocs/dynamics-365-unified-operations-public#356]
I know very well the Dynamics Tables, when I want to see a data in this Power Bi Cost administration and Cost analysis workspaces I would like to know and to be able to explain to customers what are the datas sources. (InventTrans ? ledgerTrans ? etc.).
On the other Power Bi content workspaces pages on docs.microsoft.com the D365 original data source is given but not for those ones. Could you add it ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89d2f6b4-6c94-c779-fadf-456df811a453
* Version Independent ID: 112535c7-d29d-2b3d-1f5b-f96080044981
* Content: [Cost management Power BI content - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/cost-management-content-pack#feedback)
* Content Source: [articles/dev-itpro/analytics/cost-management-content-pack.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/cost-management-content-pack.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @ShylaThompson
* Microsoft Alias: **shylaw**

**Comment by ShylaThompson** [comment]
@ArnaudLherondel Thanks for the question. The topic does have that information included but it was erroneously placed under an H3 heading instead of an H2 heading. I've updated the heading now, so you can see the "Understanding the data model and entities" link and navigate to that section of the topic.

**Comment by ArnaudLherondel** [comment]
Hi Shyla, Sorry but I don't understand the modification you done. The subject is I would like to know how the CostObjectStatementCache Table is filled and I stilll don't find it
![image](https://user-images.githubusercontent.com/43032406/45312822-6c4de480-b52d-11e8-95e0-d706a732ffda.png)
