### ISSUE TITLE
SPED FISCAL - add novos registros K260, K265, K270, K275, K280, K290

### ISSUE THREAD

**Issue by betespadula** [MicrosoftDocs/dynamics-365-unified-operations-public#3560]
[Insira comentários aqui]
No Layout 013 do SPED Fiscal, foram adicionados os novos registros **K260, K265, K270, K275, K280, K290**,
---
#### Detalhes do documento
Será necessário atualizarmos o escopo na Área:  SPED Fiscal (ICMS, IPI), os registros abaixo:
Block K: Inclusion of following new records:
K260 and K265 = Reword orders
K270, K275, K280 = Corrections
K290 = Joint production order

Conforme link liberado no LCS: [https://fix.lcs.dynamics.com/Issue/Details?kb=4483962&bugId=272148&qc=cbb62adb69bce562284f6898fecfe67a22ebb887463c5783ae0ceb000c4a63de] 

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 37344ff4-2d58-847a-1b2c-227a5776152b
* Version Independent ID: 96b381ef-f0d5-5f2a-c459-404e0050fe91
* Content: [Escopo da localização brasileira - Finance | Dynamics 365](https://docs.microsoft.com/pt-br/dynamics365/finance/localizations/latam-bra-scope)
* Content Source: [articles/finance/localizations/latam-bra-scope.md](https://github.com/MicrosoftDocs/Dynamics-365-Operations.pt-br/blob/live/articles/finance/localizations/latam-bra-scope.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @sndray
* Microsoft Alias: **sndray**

**Comment by twheeloc** [comment]
@betespadula, thank you for the feedback.

@sndray  Please review and update the content as needed.
