### ISSUE TITLE
Why are bundles not supported in call center?

### ISSUE THREAD

**Issue by danielzook** [MicrosoftDocs/dynamics-365-unified-operations-public#3562]
It is **very frustrating** to see that bundles are not supported in call center.  Direct sales companies need this feature... it is there in D365, but yet we have to re-create it as a customization... crazy.

You should explicitly state in the article *why* bundles are not supported on call center orders, and what options customers have instead that achieves the exact same functionality.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2e759b4-ee7e-56e5-6b32-3981042c6331
* Version Independent ID: 7d1125a1-71b2-d0dc-f826-f9c472606223
* Content: [Revenue recognition bundles - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/accounts-receivable/rev-rec-bundles)
* Content Source: [articles/finance/accounts-receivable/rev-rec-bundles.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/accounts-receivable/rev-rec-bundles.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @kweekley
* Microsoft Alias: **kweekley**

**Comment by twheeloc** [comment]
@danielzook, thank you for the feedback.

@kweekley Please review and update the content as needed.

**Comment by twheeloc** [comment]
The call center sales order flow is different from the standard Accounts receivable sales order flow. Call center sales orders do not go through a confirmation step which is required for explosion of a bundle.
