### ISSUE TITLE
Images for products with configurations do not work following the documented format.

### ISSUE THREAD

**Issue by brettchristiansen** [MicrosoftDocs/dynamics-365-unified-operations-public#3563]
The format listed here for Product variant images with configuration seems incorrect.  Following the formatting specified does now work.  Using web debugging tools, the correct expected format seems to be:

/Products/{ProductNumber} ^ {Configuration} ^ {Style} ^ {Size} ^ {Color} ^_000_001.png

Either there is a bug in how the product is searching for images when configuration dimension is used or this documentation is incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d8c889e-fd24-912c-61bd-40abaa7a18ca
* Version Independent ID: 79ac40fe-2a63-07f0-24ac-4c61d56d25ef
* Content: [Upload images - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dam-upload-images#naming-conventions-for-omni-channel-images)
* Content Source: [articles/commerce/dam-upload-images.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dam-upload-images.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @psimolin
* Microsoft Alias: **psimolin**

**Comment by psimolin** [comment]
Hello Brett,

Thank you for your feedback.

Yes the documentation should state product master configurations, not variants with configuration, will update.

It is good to keep in mind that these are just examples and they can be different depending on the configurations (media template, dimensions, etc.)
