### ISSUE TITLE
Add sample request for authentication

### ISSUE THREAD

**Issue by FH-Inway** [MicrosoftDocs/dynamics-365-unified-operations-public#3564]
The article does not show how to create a request for the authentication. Since this differes from other requests that authenticate using an app registration, users of the API are struggling with the authentication. It would be helpful to include some guidance and a sample request for the authentication.
The guidance should include the information from the prerequisites section of https://docs.microsoft.com/de-de/dynamics365/fin-ops-core/dev-itpro/dev-tools/pipeline-lcs-connection

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b014312-e07f-6869-17f0-59788e4b1181
* Version Independent ID: 04ac364a-5807-cebe-3a55-5ccb2827f799
* Content: [Database movement API - Authentication - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/api/dbmovement-api-authentication#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/database/api/dbmovement-api-authentication.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/database/api/dbmovement-api-authentication.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by tonyafehr** [comment]
@FH-Inway, thank you for the feedback. 
@laneswenka, please review and consider making updates.

**Comment by tonyafehr** [comment]
Bug 621004 created to track this issue.
