### ISSUE TITLE
Planned update schedule

### ISSUE THREAD

**Issue by ph1lzb** [MicrosoftDocs/dynamics-365-unified-operations-public#3565]
Please review the dates for planned maintenance for December 2021, January 2022 and February 2022 as these do not appear to be correct.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fcc1802-115b-4ac2-f34f-aa73eac426f4
* Version Independent ID: d758bfc6-245e-43d6-8bde-31282cea0a64
* Content: [Planned maintenance in self-service environments FAQ - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/plannedmaintenance-selfservice)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/plannedmaintenance-selfservice.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/deployment/plannedmaintenance-selfservice.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @sarvanis
* Microsoft Alias: **sarvanis**

**Comment by tonyafehr** [comment]
@ph1lzb, thank you for the feedback. 
@rashmansur, please review.

**Comment by tonyafehr** [comment]
Bug 621009 created to track this issue.
