### ISSUE TITLE
Add section for Enabling Azure Product Search

### ISSUE THREAD

**Issue by bstorie** [MicrosoftDocs/dynamics-365-unified-operations-public#3568]
[Enter feedback here]
Can we add a note/section that customers need to enable Productsearch.AzureSearch = True in   Commerce Parameters > Configuration Parameters   in order for  Refiners to work on the Ecom site with Demo data. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67d6e0ac-7a61-78c4-cf4b-dd26a218f7bc
* Version Independent ID: f3ec5780-fe76-7ce2-cd2b-d2aec7877323
* Content: [Configure a Dynamics 365 Commerce evaluation environment - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/cpe-post-provisioning)
* Content Source: [articles/commerce/cpe-post-provisioning.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/cpe-post-provisioning.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @psimolin
* Microsoft Alias: **psimolin**

**Comment by tonyafehr** [comment]
@bstorie, thank you for the feedback. 
@psimolin, please review.

**Comment by tonyafehr** [comment]
Bug 621010 created to track this issue.

**Comment by tonyafehr** [comment]
An update to this topic will be published later today.
