### ISSUE TITLE
Map ISV2PurchLineVersionedFieldSet 

### ISSUE THREAD

**Issue by jspijkerboer** [MicrosoftDocs/dynamics-365-unified-operations-public#357]
I think the new map should be named ISV2PurchLineMap in the diagram, instead of ISV2PurchLineVersionedFieldSet? 
Because there is already a class called ISV2PurchLineVersioningFieldSet, which makes it a bit confusing. And it makes the difference between these two more clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c49540ec-9be0-49a5-e795-377984c406b4
* Version Independent ID: a7ae6f12-fe91-31d8-704c-489f98662eac
* Content: [Extend table maps that are used for versioning - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/extensibility/maps-with-versioning)
* Content Source: [articles/dev-itpro/extensibility/maps-with-versioning.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/extensibility/maps-with-versioning.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @LarsBlaaberg
* Microsoft Alias: **lolsen**

**Comment by LarsBlaaberg** [comment]
You are right. Thank you for the feedback.
