### ISSUE TITLE
Check year in schedule for 2022

### ISSUE THREAD

**Issue by yeuruparaghoo** [MicrosoftDocs/dynamics-365-unified-operations-public#3573]
Dates for 2022 has 2021 as the year.  Please correct.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fcc1802-115b-4ac2-f34f-aa73eac426f4
* Version Independent ID: d758bfc6-245e-43d6-8bde-31282cea0a64
* Content: [Planned maintenance in self-service environments FAQ - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-gb/dynamics365/fin-ops-core/dev-itpro/deployment/plannedmaintenance-selfservice#what-is-the-schedule-for-operating-system-maintenance)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/plannedmaintenance-selfservice.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/deployment/plannedmaintenance-selfservice.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @rashmansur
* Microsoft Alias: **rashmim**

**Comment by josaw1** [comment]
Thanks for your feedback. @rashmansur please take a look.

**Comment by RobinARH** [comment]
Created bug 623420 to track this issue.
