### ISSUE TITLE
Additional resource Link not working

### ISSUE THREAD

**Issue by Navneetkat** [MicrosoftDocs/dynamics-365-unified-operations-public#3576]
Additional resources
Separating tactical and operative planning for master scheduling
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c4d47af-bae9-f30f-874a-7afeff66c62d
* Version Independent ID: a8c18f50-39fa-46f3-0add-f00518260cfe
* Content: [Master plans overview - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/master-planning/master-plans)
* Content Source: [articles/supply-chain/master-planning/master-plans.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/master-planning/master-plans.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @roxanadiaconu
* Microsoft Alias: **kamaybac**

**Comment by RobinARH** [comment]
Created bug 623425 to track this issue.

**Comment by kamaybac** [comment]
@Navneetkat , thank you for reporting this issue. I have fixed the link.
