### ISSUE TITLE
Party GAB solution causing issues with passing parameters in functions.

### ISSUE THREAD

**Issue by mjohnsonedxc** [MicrosoftDocs/dynamics-365-unified-operations-public#3577]
I recently raised a case (#2109070050001667) due to the Party & GAB solution breaking my environment. It was required for me to go through and enable parameter passthrough for lots of functions. Then after I'd fixed them an updates was released and more were broken. I think it's a good idea to inform users that this might happen and how to fix it if it does. Obviously it would be idea if it didn't happen but it it happened to me with hardly any customisations in an out of the box system, it is likely to happen to others. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28c9f029-f84b-7ae9-b0a0-257a1cb70683
* Version Independent ID: 7218e9bc-56df-da30-509e-1e9ac08ec6eb
* Content: [Party and global address book - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/party-gab)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/party-gab.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/dual-write/party-gab.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @RamaKrishnamoorthy
* Microsoft Alias: **ramasri**

**Comment by josaw1** [comment]
Thank you for your feedback. @RamaKrishnamoorthy can you please take a look?

**Comment by RobinARH** [comment]
Created bug 623426 to track this issue.
