### ISSUE TITLE
How to connect as a contoso user in D365 F&O ?

### ISSUE THREAD

**Issue by ArnaudLherondel** [MicrosoftDocs/dynamics-365-unified-operations-public#358]
Hi, 
In previous versions of D365 F&O demo packages it was easy to connect as Alicia or Susan..with the same password (Pass1Word).

Since the 8° version of D365 F&O it looks like the password has changed ? 
Nobody around me knows how to use those users now. Could you help me

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a60926e-bdb8-9b05-630c-197af915aee5
* Version Independent ID: d9f2eba1-677d-4b23-9b6b-4c9aa1455787
* Content: [Create a purchase order with a delivery schedule - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/procurement/tasks/create-purchase-order-delivery-schedule#process-product-receipt-using-delivery-schedules)
* Content Source: [articles/supply-chain/procurement/tasks/create-purchase-order-delivery-schedule.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/procurement/tasks/create-purchase-order-delivery-schedule.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @FrankDahl
* Microsoft Alias: **fdahl**

**Comment by FrankDahl** [comment]
We stopped providing support of out of the box users and passwords authentication. The guidance is that you use your own AAD and associate users/passwords with this for users you need.
