### ISSUE TITLE
VHD releases out dated

### ISSUE THREAD

**Issue by asalah1987** [MicrosoftDocs/dynamics-365-unified-operations-public#3580]
VHD releases are not accurate please to update

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6d8ca90-dfbd-3698-0def-a3be85e9c850
* Version Independent ID: b8d5a864-57fb-9fc3-f36a-77c5f5c58a54
* Content: [Software lifecycle policy and cloud releases - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/versions-update-policy)
* Content Source: [articles/fin-ops-core/dev-itpro/migration-upgrade/versions-update-policy.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/migration-upgrade/versions-update-policy.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @ShellyBakke
* Microsoft Alias: **smiller**

**Comment by josaw1** [comment]
Thank you for your feedback. @ShellyBakke can you please take a look?

**Comment by RobinARH** [comment]
Created bug 623427 to track this issue.

**Comment by sericks007** [comment]
The [Software lifecycle policy and cloud releases](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/versions-update-policy) content has been updated.
