### ISSUE TITLE
Missing step when configuring Ecommerce site

### ISSUE THREAD

**Issue by jmeijering** [MicrosoftDocs/dynamics-365-unified-operations-public#3581]
In step 4 of https://docs.microsoft.com/en-us/dynamics365/commerce/cpe-post-provisioning#set-up-your-site-in-commerce you have to tell that you have to link the on-line channel to the DB and do a full sync

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67d6e0ac-7a61-78c4-cf4b-dd26a218f7bc
* Version Independent ID: f3ec5780-fe76-7ce2-cd2b-d2aec7877323
* Content: [Configure a Dynamics 365 Commerce evaluation environment - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/cpe-post-provisioning)
* Content Source: [articles/commerce/cpe-post-provisioning.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/cpe-post-provisioning.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @psimolin
* Microsoft Alias: **psimolin**

**Comment by josaw1** [comment]
Thank you for your feedback. @psimolin can you please take a look?

**Comment by RobinARH** [comment]
Created bug 623428 to track this issue.

**Comment by psimolin** [comment]
Hello,

I reviewed this item. Full data synchronization step comes at the very last step in this guide so that it covers all the changes done earlier. For preview environments the channels are already linked to the DB.

**Comment by jmeijering** [comment]
Ok, right I created this comment as I was creating a B2B website were we made a copy of the Fabrikam extended online store and was folloing these steps and forgot to add it to the channel DB, basis error of course when you know what you are doing, but for people that are new, it could be benifitial to have a remark like (and check whether you channel is selected on the channel DB
