### ISSUE TITLE
Please add "If status is withhold, change the status into waiting".

### ISSUE THREAD

**Issue by jmeijering** [MicrosoftDocs/dynamics-365-unified-operations-public#3582]
https://docs.microsoft.com/en-us/dynamics365/commerce/cpe-post-provisioning#enable-jobs
Please add "If status is withhold, change the status into waiting".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67d6e0ac-7a61-78c4-cf4b-dd26a218f7bc
* Version Independent ID: f3ec5780-fe76-7ce2-cd2b-d2aec7877323
* Content: [Configure a Dynamics 365 Commerce evaluation environment - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/cpe-post-provisioning)
* Content Source: [articles/commerce/cpe-post-provisioning.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/cpe-post-provisioning.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @psimolin
* Microsoft Alias: **psimolin**

**Comment by josaw1** [comment]
Thanks for the feedback. @psimolin please review.

**Comment by RobinARH** [comment]
Created bug 623430 to track this issue.

**Comment by josaw1** [comment]
@psimolin replied "full data synchronization step comes at the very last step in this guide so that it covers all the changes done earlier. For preview environments the channels are already linked to the DB."
