### ISSUE TITLE
Information in this article is outdated  

### ISSUE THREAD

**Issue by user-pass** [MicrosoftDocs/dynamics-365-unified-operations-public#3583]
[Enter feedback here]

Part of a page describing 'Open entity data in Excel when you start from Excel' is outdated. After installing add-in DESIGN BUTTON DO NOT APPEARS. I'm really so tired about your outdated and incorrect documentation, so it would be better just to delete this useless information. I'm so angry and tired, just wanna stop using all of your products forever and become Apple fan. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c40f89cb-2263-7841-97fe-e6b24437b746
* Version Independent ID: 3672b2fd-08e8-5c6f-6c47-411dc6977d71
* Content: [View and update entity data with Excel - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/office-integration/use-excel-add-in?toc=/dynamics365/commerce/toc.json)
* Content Source: [articles/fin-ops-core/dev-itpro/office-integration/use-excel-add-in.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/office-integration/use-excel-add-in.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by josaw1** [comment]
Thank you for the feedback. @jasongre can you please review this?

**Comment by RobinARH** [comment]
Created bug 623432 to track this issue.

**Comment by jasongre** [comment]
@user-pass The instructions worked as described for me. The Design button is at the bottom of the add-in pane. What were you seeing? Did the add-in load?
