### ISSUE TITLE
Correction Transfer tab not Transport tab

### ISSUE THREAD

**Issue by Navneetkat** [MicrosoftDocs/dynamics-365-unified-operations-public#3584]
The Reserve items automatically option on the _**Transport tab**_ determines the default setting if items are automatically reserved for transfer orders. The default setting can be overridden on individual transfer orders.[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bff6533-1ef7-0c04-1010-2a8017abd44d
* Version Independent ID: ed3a0366-a7f6-8f92-4950-10514c3528f4
* Content: [Reserve inventory quantities - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/inventory/reserve-inventory-quantities)
* Content Source: [articles/supply-chain/inventory/reserve-inventory-quantities.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/inventory/reserve-inventory-quantities.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @perlynne
* Microsoft Alias: **perlynne**

**Comment by josaw1** [comment]
Thanks for your feedback. @kamaybac can you please take a look?

**Comment by RobinARH** [comment]
Created bug 623433 to track this issue.
