### ISSUE TITLE
B2B setup page is missing important information

### ISSUE THREAD

**Issue by jmeijering** [MicrosoftDocs/dynamics-365-unified-operations-public#3587]
This whole page is a bit confusing. You would expect to get an explainaintion what you need to do to setup a B2B website, but directly after the prerequistes, the setup of Site level settings are explained, but as long as you do not have a B2B site configured you don't have access to such a site.

I would have expected first a short description that you have to enabled the B2B Feature in feature management and to setup a on-line stores and describe what is the specific setup for b2b, like the Customer type which needs to be set to B2B.

And also that you currently need to submit a support request to get copy of the B2B demo site and which information you need to provide to the support team so it can quickly create it for you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb11a9fe-94ad-02a3-a911-0f58e1cad41d
* Version Independent ID: 87215e08-819f-e66a-2aa0-0ab8d9c8e646
* Content: [Set up a B2B e-commerce site - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/b2b/set-up-b2b-site#site-level-settings)
* Content Source: [articles/commerce/b2b/set-up-b2b-site.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/b2b/set-up-b2b-site.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by josaw1** [comment]
Thanks for the feedback. @anpurush or @BrianShook can you please review?

**Comment by RobinARH** [comment]
Created bug 623435 to track this issue.

**Comment by josaw1** [comment]
@anupamar-ms can you please review this feedback? We should do a doc update to address.

**Comment by josaw1** [comment]
Closing as won't fix.
