### ISSUE TITLE
Public preview / GA

### ISSUE THREAD

**Issue by kurthatlevik-inspirit365** [MicrosoftDocs/dynamics-365-unified-operations-public#3591]
Please evaluate what is in public preview, and what is GA related to Entity Store in Data Lake.   Because of the public preview statement here, customers are reluctant to use it....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a344a5de-68fa-e9cf-28eb-51269c33b9b3
* Version Independent ID: 1b3ede62-3954-574b-5778-8cdee0ededfe
* Content: [Make Entity store available as a Data Lake - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/entity-store-data-lake)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/entity-store-data-lake.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/entity-store-data-lake.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by tonyafehr** [comment]
@MilindaV2, please review.
