### ISSUE TITLE
Issue with additional Tiered environments being auto-updated by Microsoft

### ISSUE THREAD

**Issue by ph1lzb** [MicrosoftDocs/dynamics-365-unified-operations-public#3592]
I can see the logic for Microsoft auto-updating additional Sandboxes (Tier 2+) in a customer's subscription to reduce the overhead placed on Customers/Partners, but this will not always be acceptable.  The approach ignores multi-phase projects whereby the customer is testing functionality in a separate Tier 2 environment for a future rollout.  That additional tier 2 environment may have ISV solutions that are not compatible with the update that the Microsoft team will push into the environment.  While a workaround is for the customer to manage these by self-updating, for complex projects it is easier for the Customer/Partner to manage which versions are deployed when to additional tier 2 environments, including when to apply the latest updates.  This change will make the whole planning very difficult.  Often the need for a second Tier 2 environment is due to features not being supported on a Tier 1 environment, e.g. LCS add-ins.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcff93b4-d765-642b-f4ba-911b05344216
* Version Independent ID: be01a4e8-ba6f-8ac4-fbe3-7db75de310e8
* Content: [Configure service updates through Lifecycle Services (LCS) - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/configure-service-updates?toc=/dynamics365/commerce/toc.json#additional-sandbox-environments)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/configure-service-updates.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/lifecycle-services/configure-service-updates.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @AngelMarshall
* Microsoft Alias: **tsmarsha**

**Comment by roschlom** [comment]
Thank you for the feedback!
