### ISSUE TITLE
Set up the fiscal registration process (files: SubmitConnector.xml /ContingencyConnector.xml)

### ISSUE THREAD

**Issue by betespadula** [MicrosoftDocs/dynamics-365-unified-operations-public#3593]
When partners/clients try to access the link: Commerce Fiscal Integration repository (repo) to download xmls:  SubmitConnector.xml  /  ContingencyConnector.xml error message stating that they do not have access.

[https://docs.microsoft.com/en-us/dynamics365/commerce/localizations/latam-bra-deployment#set-up-the-fiscal-registration-process](url)

We need to check this link for customers to download 

Below excerpt of the article where the xmls reports:
Set up the fiscal registration process
To set up the fiscal registration process in Commerce headquarters, follow these steps. For more information, see Set up the fiscal integration for Commerce channels.
1.	Go to Retail and Commerce > Headquarters setup > Parameters > Commerce shared parameters.
2.	On the General tab, set the Enable fiscal integration option to Yes.
3.	Go to Retail and Commerce > Channel setup > Fiscal integration > Fiscal connectors.
4.	Load the connector configuration from the Commerce Fiscal Integration repository (repo). The following files are located under Configurations\Connectors:
o	SubmitConnector.xml
o	ContingencyConnector.xml
5.	Go to Retail and Commerce > Channel setup > Fiscal integration > Fiscal document providers.
6.	Load the document provider configurations from the Commerce Fiscal Integration repo. The following configuration files are located under Configurations\DocumentProviders:
o	SubmitProvider.xml
o	ContingencyProvider.xml
![error_commerce](https://user-images.githubusercontent.com/88406309/135127117-cf85f496-5243-45f8-a4ab-2037e0129749.JPG)
![error_commerce](https://user-images.githubusercontent.com/88406309/135127134-e82d2f3f-ab9b-49cf-99af-c4fa6f344106.JPG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2309d63d-5e54-e87b-9c5c-38a0e1acd57e
* Version Independent ID: 68bd7155-a13d-f99b-9cb6-9764239b8950
* Content: [Set up and deploy the Dynamics 365 Commerce localization for Brazil - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/localizations/latam-bra-deployment)
* Content Source: [articles/commerce/localizations/latam-bra-deployment.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/localizations/latam-bra-deployment.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @akviklis
* Microsoft Alias: **akviklis**

**Comment by josaw1** [comment]
This issue was fixed and will go live today. Thank you.
