### ISSUE TITLE
html markup is visible

### ISSUE THREAD

**Issue by kitaly** [MicrosoftDocs/dynamics-365-unified-operations-public#3598]
See the below image. Note that <a name="queued-records-insights-and-error-management"> html tag is visible.

![image](https://user-images.githubusercontent.com/45222/135377266-28aa27aa-4ff2-4fc1-9e32-823ff95ca0b3.png)

Link:
https://docs.microsoft.com/ja-jp/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/errors-and-alerts#a-namequeued-records-insights-and-error-management%E3%82%AD%E3%83%A5%E3%83%BC%E3%81%AB%E5%85%A5%E3%82%8C%E3%82%89%E3%82%8C%E3%81%9F%E3%83%AC%E3%82%B3%E3%83%BC%E3%83%89%E3%81%AE%E3%82%A4%E3%83%B3%E3%82%B5%E3%82%A4%E3%83%88%E3%81%A8%E3%82%A8%E3%83%A9%E3%83%BC%E7%AE%A1%E7%90%86

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 3d65d744-12cc-2c15-4bb5-0fdaa8a05e16
* Version Independent ID: 61505bbf-365d-f7a9-4270-9a1e2e36d660
* Content: [エラー管理と警告通知 - Finance & Operations | Dynamics 365](https://docs.microsoft.com/ja-jp/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/errors-and-alerts#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/errors-and-alerts.md](https://github.com/MicrosoftDocs/Dynamics-365-Operations.ja-jp/blob/live/articles/fin-ops-core/dev-itpro/data-entities/dual-write/errors-and-alerts.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @NHelgren
* Microsoft Alias: **nhelgren**

**Comment by vinceno** [comment]
Thx @roschlom - @rosacek could you please have thsi corrected - thx

**Comment by rosacek** [comment]
@roschlom @vinceno I'm looking into it and will have the topic fixed.

**Comment by rosacek** [comment]
@roschlom @RobinARH @vinceno [fix is live](https://docs.microsoft.com/ja-jp/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/errors-and-alerts)

**Comment by RobinARH** [comment]
Thanks for the quick update!
