### ISSUE TITLE
Minor correction when creating a new  Warehouse 

### ISSUE THREAD

**Issue by Bijan-Ghofranian** [MicrosoftDocs/dynamics-365-unified-operations-public#3599]
Please change the wording in step 5 from "In the Site field, type a value."  to "In the Site field, **select** a value from drop down."
Obviously they can not type anything so the sentence gives a false impression that they can think of a site on the fly and AX will create that site.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67cb777c-3e51-ca6d-10aa-f813f08c99f1
* Version Independent ID: 8e7a6426-4a9d-821e-aa46-f4cb0d8bd3c0
* Content: [Configure locations in a WMS-enabled warehouse - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/warehousing/tasks/configure-locations-wms-enabled-warehouse)
* Content Source: [articles/supply-chain/warehousing/tasks/configure-locations-wms-enabled-warehouse.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/warehousing/tasks/configure-locations-wms-enabled-warehouse.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @perlynne
* Microsoft Alias: **perlynne**

**Comment by tonyafehr** [comment]
@kamaybac, please review.

**Comment by kfend** [comment]
@Bijan-Ghofranian - Thank you for the feedback. While the field is a drop-down, you can still type in the value for the site if you prefer to do so.
