### ISSUE TITLE
Monthly updates on 8.0 are not cumulative.  

### ISSUE THREAD

**Issue by MichaelFruergaardPontoppidan** [MicrosoftDocs/dynamics-365-unified-operations-public#360]
Fixes in 8.0.1 are *not* included in 8.0.2.   We should make that transparent - as it is pretty odd.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcdefbcf-c3ad-9b1f-0988-452cea3e2108
* Version Independent ID: 7e002437-1ad9-ca29-7844-87e6709fe0fe
* Content: [Software lifecycle policy and cloud releases - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/versions-update-policy)
* Content Source: [articles/dev-itpro/migration-upgrade/versions-update-policy.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/migration-upgrade/versions-update-policy.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RyanCCarlson2
* Microsoft Alias: **rcarlson**

**Comment by FH-Inway** [comment]
created PR 361 for this
https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/pull/361

**Comment by sericks007** [comment]
Thanks for letting us know!  I've reached out to the PM to get approval for the change to the article.

**Comment by sericks007** [comment]
The Software Lifecycle Policy has been updated: https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/versions-update-policy?toc=/fin-and-ops/toc.json
