### ISSUE TITLE
Clarity on roll out and use in Data Migration

### ISSUE THREAD

**Issue by weaveriski** [MicrosoftDocs/dynamics-365-unified-operations-public#3603]
Hi

The **Constraint** entitled "Data migration slow-down with enabled dual-write" requires clarity. 

I believe the presumption here is on the FIRST legal entity, i.e. do not have the maps enabled whilst running the data migration element. However where you have mutliple roll outs you cannot disable the dual-write maps, they are in production. Naturally you do not have to add the legal entity into the synch prior to the data migration, but this needs to be made clear. 

We should be able to run a data migration plan into legal entity AB2 whilst dual-write is active in legal entity AA1. 

It this is not the case then this needs highlighting, and if this is the case clarity on the advice is needed. 

Thanks
Steve
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: caa6a38c-03b6-7949-e383-aaaa4ca05ff9
* Version Independent ID: 0bf0e3d4-33b7-d54b-e2bc-1531bfbeee6e
* Content: [Considerations for initial synchronization - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/initial-sync-guidance)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/initial-sync-guidance.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/dual-write/initial-sync-guidance.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @RamaKrishnamoorthy
* Microsoft Alias: **ramasri**

**Comment by kfend** [comment]
@weaveriski - Thank you for the feedback.
@RamaKrishnamoorthy - Can you please take a look at this and update the topic as needed? Thanks!

**Comment by weaveriski** [comment]
@josaw1 looking at the constraint section of the page the original issue persists with the statement made. What am I missing?
