### ISSUE TITLE
where are the images? they not in the exported word doc

### ISSUE THREAD

**Issue by markandersonus** [MicrosoftDocs/dynamics-365-unified-operations-public#3606]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5762f9e-d7f4-e7fc-49c7-6db64c01bc6a
* Version Independent ID: 2aab18ad-f2f1-c0ad-c109-38806c8491a3
* Content: [Task recorder resources - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/user-interface/task-recorder)
* Content Source: [articles/fin-ops-core/dev-itpro/user-interface/task-recorder.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/user-interface/task-recorder.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by kfend** [comment]
@markandersonus - Thank you for the feedback.
@jasongre - Can you please take a look and address this feedback.

**Comment by kfend** [comment]
Created bug 629764 to track this issue.
