### ISSUE TITLE
Excellent example, but conflicts

### ISSUE THREAD

**Issue by markandersonus** [MicrosoftDocs/dynamics-365-unified-operations-public#3615]
This is an excellent article, I'd make one improvement: show re-use of a test. For example have two sections that use the same test.

Also the advice on selecting from choice lists conflicts other best practice from MS (but having done it both ways, yours makes more sense). Other docs say do NOT type the value but select from the list with mouse

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a89192ad-bcdc-5e3b-15d6-20fac6d5d29f
* Version Independent ID: 5b278db8-9a7f-523d-0ebe-eec9004f9779
* Content: [Regression suite automation tool tutorial - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/perf-test/rsat/rsat-tutorial)
* Content Source: [articles/fin-ops-core/dev-itpro/perf-test/rsat/rsat-tutorial.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/perf-test/rsat/rsat-tutorial.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @FrankDahl
* Microsoft Alias: **fdahl**

**Comment by MarkGTI** [comment]
So it's  fixed?

**Comment by markandersonus** [comment]
Shocking. So Microsoft is happy with documentation that says one thing and tool tips in the software that says the exact opposite?
    On Thursday, February 23, 2023 at 12:21:53 PM EST, josaw1 ***@***.***> wrote:  
 
 


Hi @MarkGTI, this was closed as "won't fix". Thanks.
