### ISSUE TITLE
Update the minimum requirement of the PAT's scopes FULL ACCESS needed when deploy and continuous use of BUILD environment

### ISSUE THREAD

**Issue by JanNguyenMS** [MicrosoftDocs/dynamics-365-unified-operations-public#3618]
Currently, in this document https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/perf-test/continuous-build-test-automation#set-up-azure-devops-1
It just mentioned to create PAT to configure the VSTS on LCS but not mention the minimum requirement of the PAT's scope.
Without FULL ACCESS of scope, we cannot deploy BUILD environment. And we also have the confirmation from Tech Global team that the minimum requirement of the PAT's scope to deploy BUILD environment is FULL ACCESS.

We need this information to be stated in the official document, customers need it to deploy BUILD environment and get the official confirmation from MS in case they cannot use FULL ACCESS scope.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8de1092-e5f1-e33c-6e53-bb3d09d01c6f
* Version Independent ID: 1464611a-1ac2-19eb-c517-9b59c7c06c70
* Content: [Deploy and use a continuous build and test automation environment - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/perf-test/continuous-build-test-automation#set-up-azure-devops-1)
* Content Source: [articles/fin-ops-core/dev-itpro/perf-test/continuous-build-test-automation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/perf-test/continuous-build-test-automation.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **shailesn**

**Comment by kamaybac** [comment]
Bug 649726 created to track this issue.
