### ISSUE TITLE
Version wrong?

### ISSUE THREAD

**Issue by phual** [MicrosoftDocs/dynamics-365-unified-operations-public#362]
The document indicates that "This feature is available in Platform update 15 (7.0.4841) or later." However, we're non that version and do not have the "edit" button on the Entity Store page. When looking at this page:

https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/incremental-refresh-entity-store-models#incremental-refresh

it say that this feature is not available until platform update 16.

Is this document wrong as to which version incremental refresh is available for?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f11c232-e0cc-d5ac-7d11-5671dc2ba6b2
* Version Independent ID: 5a799243-a027-83d3-3262-c8c4c33a339f
* Content: [Schedule updates of entity store models - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/aggregate-measurements-refreshed-incrementally)
* Content Source: [articles/dev-itpro/analytics/aggregate-measurements-refreshed-incrementally.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/aggregate-measurements-refreshed-incrementally.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by ShylaThompson** [comment]
@TJVass, I've logged bug #247399 for investigation.

**Comment by sericks007** [comment]
The article was removed, so closing this issue.
