### ISSUE TITLE
Need Youtube video or documentation of the UX.  Real world Implementation?

### ISSUE THREAD

**Issue by JTApps-1** [MicrosoftDocs/dynamics-365-unified-operations-public#3623]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bec8cf0-1b55-139f-7a1c-9101fd39ea1e
* Version Independent ID: 1265581f-6c8c-6681-f3da-8c45bc87bbc1
* Content: [Develop email experiences by using the SysMailer framework - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/sysmailer-develop)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/sysmailer-develop.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/dev-tools/sysmailer-develop.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @ChrisGarty
* Microsoft Alias: **cgarty**

**Comment by kamaybac** [comment]
Bug 652661 created to track this issue
