### ISSUE TITLE
Needs to be revised

### ISSUE THREAD

**Issue by psimolin** [MicrosoftDocs/dynamics-365-unified-operations-public#3628]
Hello,

There is no alert module anymore.

Kindly review the article and make the required changes / take it offline.

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e86a0fdb-2798-ae95-abb9-ce6c21c4b57d
* Version Independent ID: a5fa67b9-23dd-5c5d-b2c8-2a783360313e
* Content: [Add a welcome message - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/add-welcome-message)
* Content Source: [articles/commerce/add-welcome-message.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/add-welcome-message.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @psimolin
* Microsoft Alias: **psimolin**

**Comment by tonyafehr** [comment]
@josaw1, please review.

**Comment by josaw1** [comment]
Thanks for the feedback. This topic needs to be rewritten. Removing the topic for now.
