### ISSUE TITLE
Senthil Raj

### ISSUE THREAD

**Issue by senthilrajm** [MicrosoftDocs/dynamics-365-unified-operations-public#363]
Much needed article!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a0fa0ba-209a-e457-06b6-30d496593f86
* Version Independent ID: d276a668-9296-d713-61e2-6d204f9181e9
* Content: [Write extensible code - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/extensibility/writing-extensible-code)
* Content Source: [articles/dev-itpro/extensibility/writing-extensible-code.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/extensibility/writing-extensible-code.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @mfp
* Microsoft Alias: **mfp**

**Comment by kfend** [comment]
Thanks for the feedback!

**Comment by mfp** [comment]
On Fri, Sep 07, 2018 at 10:14:29AM -0700, senthilrajm wrote:
> Much needed article!
> 
> ---
> #### Document Details
> 
> ⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*
(...)
> * GitHub Login: @mfp

Not sure it matters, but just in case...
I'm @mfp, and I'm not related in any way to this document.

There might be some metadata in need of correction somewhere.
-- 
Mauricio Fernández
