### ISSUE TITLE
The Azure AD domain that is configured must be the same domain that you used for your PowerBI.com account

### ISSUE THREAD

**Issue by DrGee-gethub** [MicrosoftDocs/dynamics-365-unified-operations-public#3631]
[Enter feedback here]

Is this correctly stated:
"The Azure AD domain that is configured must be the same domain that you used for your PowerBI.com account. For example, if you provisioned the application in the Contoso.com domain, you must have Power BI accounts in that domain, such as Tim@ContosoAX7.onmicrosoft.com."
Reference https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/configure-power-bi-integration#things-you-must-know-before-you-start

Or is this right?
For example, if you provisioned the application in the Contoso.com domain, you must have Power BI accounts in that domain, such as Tim@Contoso.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2213414-926d-10e1-538b-efef09dc0181
* Version Independent ID: 03be53f7-c305-cb02-7627-2ea4f1c01bd4
* Content: [Configure PowerBI.com integration - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/configure-power-bi-integration)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/configure-power-bi-integration.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/analytics/configure-power-bi-integration.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by kfend** [comment]
@DrGee-gethub - Thank you for the question. I spoke with the author and what is written is correct with regard to the domain.
