### ISSUE TITLE
Moving the CSU, any impact on the Receipt No, Transaction No, Shift Id, etc needs to be highlighted

### ISSUE THREAD

**Issue by praveenzp** [MicrosoftDocs/dynamics-365-unified-operations-public#3632]
Moving the CSU between the regions will it impact the running numbers for the Receipt, Trans, Shift Id, etc. Is there a requirement to run the POS ReDeployment Checklist. Please advise else Customers might just move the CSU and expect the running numbers to continue as expected.
As it is a business risk, this should be highlighted to indicate it is automatically handled or this needs to be mitigated before by Partners/Customers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 083f5051-a328-f1e7-5d65-0f11fac5c304
* Version Independent ID: 3d0ae350-6705-0009-fd1a-9fac44b4e83b
* Content: [Migrate channels to a different Commerce Scale Unit - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/reassign-csu)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/Reassign-CSU.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/deployment/Reassign-CSU.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @AamirAllaq
* Microsoft Alias: **aamiral**

**Comment by tonyafehr** [comment]
@AamirAllaq, please review. Thanks!
