### ISSUE TITLE
unable to create new variants if version numbering rule is set to "manual"

### ISSUE THREAD

**Issue by Nick-etz** [MicrosoftDocs/dynamics-365-unified-operations-public#3641]
[Enter feedback here]

Everything on the learning page was helpful for Engineering Products that use a Version Numbering rule that is not manual. 

However, If the product master is setup as an engineering product and has a version number rule that is manual (requires the user to provide a Version ID each time) I was not able to create new variants. 

When using the "suggest variants" feature on an item that has manual versioning, an error is thrown. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: caf84e31-08bf-6cbf-d41f-f8151ea56545
* Version Independent ID: bc104a8e-095a-38fb-f9a4-fe29d9f6d748
* Content: [Generate variants for engineering products - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/engineering-change-management/engineering-variants#feedback)
* Content Source: [articles/supply-chain/engineering-change-management/engineering-variants.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/engineering-change-management/engineering-variants.md)
* Service: **dynamics-365-supply-chain**
* GitHub Login: @t-benebo
* Microsoft Alias: **benebotg**

**Comment by tonyafehr** [comment]
@Nick-etz, thank you for the feedback. 
@kamaybac, please assign an appropriate owner.

**Comment by tonyafehr** [comment]
Bug #633668 logged to track this issue.
