### ISSUE TITLE
Make distinction between retryable and restartable

### ISSUE THREAD

**Issue by gertvdh** [MicrosoftDocs/dynamics-365-unified-operations-public#3644]
Maybe it's a good idea to make a distinction between retryable and restartable, since by default the batch framework restarts batch tasks at least 1 time on any exception occurring (aka parmRetriesOnFailure())

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a0878ca-257d-9ec4-eab0-8a570635cca2
* Version Independent ID: b5f3068c-b880-b5b9-3f82-ac3326a6dd7b
* Content: [Enable automatic retries on batch jobs - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/retryable-batch)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/retryable-batch.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/sysadmin/retryable-batch.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @matapg007
* Microsoft Alias: **matgupta**

**Comment by tonyafehr** [comment]
@gertvdh, thank you for the feedback. 
@matapg007, please review and consider making updates.

**Comment by tonyafehr** [comment]
Bug #633670 logged to track this issue.
