### ISSUE TITLE
Broken link for item requirements in Projects

### ISSUE THREAD

**Issue by AXSHAH** [MicrosoftDocs/dynamics-365-unified-operations-public#3646]
Broken link for item requirements in Projects:
https://docs.microsoft.com/en-us/dynamics365/project-operations/prod-pma/receive-items-purchase-order-item-requirement

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84af346c-a558-2b30-c625-eda3db2f24c0
* Version Independent ID: c8022d18-a8b0-fdcc-41c7-62455b732bff
* Content: [Finance home page - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/)
* Content Source: [articles/finance/index.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/index.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @roschlom
* Microsoft Alias: **roschlom**

**Comment by tonyafehr** [comment]
@roschlom, please fix. Thanks!

**Comment by tonyafehr** [comment]
Bug #633671 logged to track this issue.

**Comment by kfend** [comment]
@AXSHAH - Is this link in a topic and it's broken? If so, can you tell me where? The link you posted above is missing part of the file path. "tasks" should be between "prod-pma" and "receive-items-purchase-order-item-requirement. 
Here is the correct link:
https://docs.microsoft.com/en-us/dynamics365/project-operations/prod-pma/tasks/receive-items-purchase-order-item-requirement

**Comment by AXSHAH** [comment]
@kfend , the link is now appears to be fixed. Before when navigating to this topic "Receive items on purchase order from item requirement" the error page was appearing. Thanks for the support.
