### ISSUE TITLE
Add feature information 

### ISSUE THREAD

**Issue by SEPO2** [MicrosoftDocs/dynamics-365-unified-operations-public#3647]
[Enter feedback here]
Please add more information about the Workload History Data Cleanup feature: 
![image](https://user-images.githubusercontent.com/93311498/139205112-2e36b972-da9d-4ccf-9c12-ccd651a2ae42.png)

Also, what are the options for: 
![image](https://user-images.githubusercontent.com/93311498/139205177-299be8fa-157a-4bf2-a14c-0c39d34302f2.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 926b5538-8734-b2cf-7d77-21f35dbf0e98
* Version Independent ID: 219ba487-1689-e78c-773e-42d019f779f1
* Content: [Cleanup routines in Dynamics 365 Finance and Dynamics 365 Supply Chain Management - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/cleanuproutines)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/cleanuproutines.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/sysadmin/cleanuproutines.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @dvliegen
* Microsoft Alias: **dvliegen**

**Comment by tonyafehr** [comment]
@SEPO2, thanks for the suggestion. 
@dvliegen, please consider making updates.

**Comment by tonyafehr** [comment]
Bug #633676 logged to track this issue.
