### ISSUE TITLE
Bing for Commerce

### ISSUE THREAD

**Issue by breusche** [MicrosoftDocs/dynamics-365-unified-operations-public#3649]
Please remove Bing for Commerce from this graphic. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d8a2537-5c77-cb33-2bf5-0788c584b7c6
* Version Independent ID: b323e224-a8c7-0fa8-37a0-6f8382e32804
* Content: [Headless commerce architecture - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/retail-server-architecture)
* Content Source: [articles/commerce/dev-itpro/retail-server-architecture.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/retail-server-architecture.md)
* Service: **dynamics-365-commerce**
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by mugunthanm** [comment]
Thanks for the feedback. Updated the diagram, it will be refreshed in few days.
