### ISSUE TITLE
Incorrect order?

### ISSUE THREAD

**Issue by JoPe72** [MicrosoftDocs/dynamics-365-unified-operations-public#365]
At the end of the guide we are performing the following steps:

- Update the database
- Enable change tracking
- Re-provision the target environment
- Reset the Financial Reporting database
- Start to use the new database

Don't we need to have the database in place before we are doing at least re-provisioning and maybe also reset of Fianncial Reporting?

/Johan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3436fbc8-5bdd-dcdc-f5d3-51caf7b6cd76
* Version Independent ID: af78d3ef-b329-11e9-896a-aa3394f6c77c
* Content: [Copy Finance and Operations databases from Azure SQL Database to SQL Server environments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/copy-database-from-azure-sql-to-sql-server)
* Content Source: [articles/dev-itpro/database/copy-database-from-azure-sql-to-sql-server.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/database/copy-database-from-azure-sql-to-sql-server.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @maertenm
* Microsoft Alias: **maertenm**

**Comment by ShylaThompson** [comment]
Thanks for your feedback. I'll be following up with our product team to get some clarity for you.

**Comment by sericks007** [comment]
Tracking bug logged: 247974

**Comment by laneswenka** [comment]
@JePe72 I am not sure I understand what you mean.  By the time you reach "Update the database" the database is already in place. Can you please clarify?

**Comment by JoPe72** [comment]
The complete order is (according to https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/copy-database-from-azure-sql-to-sql-server) is :

- Import the database
- Update the database
-- Enable change tracking
-- Re-provision the target environment
- Start to use the new database
- Re-enter data from encrypted and environment-specific fields in the target database

What I mean is: Don't we need to do "Start to use the new database" before we do "Re-provision the target environment"? How does the deployable package know which database to use... the refreshed one is not in use yet? I might have misunderstood something and in that case I would love to be corrected.

**Comment by laneswenka** [comment]
Hi @JoPe72 thanks for the inline list, I see how the reprovisioning for retail is out of place here in many of our documents around database movements.  We would indeed need to swap out the Orig with the new DB prior to applying any packages.  I'll have these updates checked in today.

**Comment by JoPe72** [comment]
Great... thanks
