### ISSUE TITLE
Belgium CODA

### ISSUE THREAD

**Issue by NataliaFLeal** [MicrosoftDocs/dynamics-365-unified-operations-public#3651]
There is not any information on how to setup CODA. It is good to know what steps to follow to import CODA files but without details about settings to define previously, CODA file will never be imported.
Please add documentation about how to setup CODA.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 807f96bd-9269-1541-0516-ee905e0003d7
* Version Independent ID: a263d611-d029-927b-16b6-a9e2a23000db
* Content: [CODA bank statement - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/emea-bel-coda-bank-statement-import)
* Content Source: [articles/finance/localizations/emea-bel-coda-bank-statement-import.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/emea-bel-coda-bank-statement-import.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @Anasyash
* Microsoft Alias: **anasyash**

**Comment by tonyafehr** [comment]
@NataliaFLeal, thanks for the feedback. 
@kfend, please assign an appropriate owner.

**Comment by tonyafehr** [comment]
Bug #633676 logged to track this issue.
