### ISSUE TITLE
Details on caching table metadata properties and indexes

### ISSUE THREAD

**Issue by lbagleybhs** [MicrosoftDocs/dynamics-365-unified-operations-public#3652]
One note: It seems like in the Reservation Management the cache table has been renamed to "FMPickupAndReturnTable" from "FMPickupAndReturnCache" (Checked in 10.0.18).  

Do the normal best practices around table caching apply for tables used in the SysDataSetCacheTableExtension framework, or does the framework set this up for us? 
(e.g. Cache Lookup and Table Group properties as well as Indexes) 

In the example above, there didn't seem to have caching nor indexing set up on the example table. Some other examples in the AOT did have some of this caching/performance elements configured so wanted to have a greater understanding of what this is or isn't doing. Thanks! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d85b9ad-03d1-12b0-b014-cad9419d2c55
* Version Independent ID: 4c82d868-14fa-4012-0bf0-d80c639c1472
* Content: [Tile and list caching for workspaces - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/user-interface/tile-list-caching-workspaces#workspace-lists)
* Content Source: [articles/fin-ops-core/dev-itpro/user-interface/tile-list-caching-workspaces.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/user-interface/tile-list-caching-workspaces.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by tonyafehr** [comment]
@lbagleybhs, thanks for the feedback. 
@jasongre, please review and consider making updates.

**Comment by tonyafehr** [comment]
Bug #633680 logged to track this issue.

**Comment by jasongre** [comment]
@lbagleybhs You can think of these workspace "cache tables" as regular tables that interface with the SysDataSetCache framework, and so any best practices for tables in general would apply here. Thanks for calling out the typo in the documentation; I'll get that updated!
