### ISSUE TITLE
App.config does not exist

### ISSUE THREAD

**Issue by wojzeh** [MicrosoftDocs/dynamics-365-unified-operations-public#3653]
App.config does not exist, I guess that it must be AX2012DataMigration.exe.config file

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42eeda26-b0da-fe66-ef03-a26dbf16d923
* Version Independent ID: 5cb45351-842a-b98b-1120-6eb2f657fe47
* Content: [Upgrade from AX 2012 - Data upgrade in self-service environments - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/data-upgrade-self-service)
* Content Source: [articles/fin-ops-core/dev-itpro/migration-upgrade/data-upgrade-self-service.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/migration-upgrade/data-upgrade-self-service.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @veeravendhan-s
* Microsoft Alias: **vesakkar**

**Comment by twheeloc** [comment]
@wojzeh  - Thank you for the feedback.
@veeravendhan-s  - Will you please take a look and address this feedback?
