### ISSUE TITLE
How do I find complete series?

### ISSUE THREAD

**Issue by iamJoshKnox** [MicrosoftDocs/dynamics-365-unified-operations-public#3654]
This article says it is the 2nd of 6...where can I find all 6 together?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd004c74-1197-8592-2842-14f34a3e151a
* Version Independent ID: a50ee0f9-8817-5116-24e5-14ca2f0c246f
* Content: [Set up OIOUBL electronic invoicing - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/tasks/set-up-oioubl-electronic-invoicing)
* Content Source: [articles/finance/localizations/tasks/set-up-oioubl-electronic-invoicing.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/tasks/set-up-oioubl-electronic-invoicing.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @mrolecki
* Microsoft Alias: **mrolecki**

**Comment by twheeloc** [comment]
@iamjoshknox - You can find the rest of the series [here](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/denmark):
