### ISSUE TITLE
Reusing the same vendor ID requires some additional steps

### ISSUE THREAD

**Issue by GitHubSil** [MicrosoftDocs/dynamics-365-unified-operations-public#3657]
**Reusing the same vendor ID requires some additional steps**
Please see below ticket from MS support

**Problem**
When shared number sequence for vendor accounts in multiple Legal entities is setup and the action "Add vendor to another legal entity" is copying one vendor to another then the account number of the new vendor is not the same as the vendor account it was copied from.

**REMARKS**
Microsoft has evaluated this issue and determined that this functionality is working as designed. 

The  "Add vendor to another legal entity" is legacy functionality and working on the "old" way of copying vendors. However when following an alternative path the vendor account can be created with same account numbers.
Setup shared number series for vendor accounts
Goto the Legal entity where the new vendor account is to be created
Click New 
use the dropdown in the name field to find the vendor in the other company
notice the "Existing Vendor. Copy vendor ?" toggle bar   set to YES
Select company
Now the vendors are created with same account number 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe8e427f-127e-a2c0-c2fe-01e2b9786ffe
* Version Independent ID: 192ea382-04bd-e893-a0d7-c11688b31c78
* Content: [Copy vendors by using shared number sequences - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/accounts-payable/vendor-copy)
* Content Source: [articles/finance/accounts-payable/vendor-copy.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/accounts-payable/vendor-copy.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @mikefalkner
* Microsoft Alias: **roschlom**

**Comment by josaw1** [comment]
Thanks for posting this! Closing due to lack of traction.
