### ISSUE TITLE
Add the following note in points 5 and 7 that explains how to setup enterprise number in legal entity and customer

### ISSUE THREAD

**Issue by NataliaFLeal** [MicrosoftDocs/dynamics-365-unified-operations-public#3658]
Please add the following note in points 5 and 7 that explains how to setup enterprise number in legal entity and customer

_Note: Assure that in General tab, effective date is former than date when customer invoice were posted._

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1ee0706-e3da-da9f-e5ec-b992cb01f65c
* Version Independent ID: 7f769461-7b26-6cad-dbc4-bdea3f5c33a8
* Content: [Annual VAT listing of domestic sales - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/emea-bel-annual-vat-listing-of-domestic-sales?source=docs#setup)
* Content Source: [articles/finance/localizations/emea-bel-annual-vat-listing-of-domestic-sales.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/emea-bel-annual-vat-listing-of-domestic-sales.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @Andosip
* Microsoft Alias: **anasyash**

**Comment by twheeloc** [comment]
@NataliaFLeal - Thank you for the feedback.
@Andosip - please review and consider making updates.

**Comment by josaw1** [comment]
Closed as won't fix.
