### ISSUE TITLE
LocalAgent installation timeout

### ISSUE THREAD

**Issue by fordummie** [MicrosoftDocs/dynamics-365-unified-operations-public#366]
Anyone?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d86d2857-6199-f3cb-208b-db4e1cd9f8e2
* Version Independent ID: d425ad9e-6c01-6145-dad5-2af32ffaaff0
* Content: [Troubleshoot on-premises deployments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/deployment/troubleshoot-on-prem#stateful-and-stateless-services-how-to-identify-nodes-for-log-review)
* Content Source: [articles/dev-itpro/deployment/troubleshoot-on-prem.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/deployment/troubleshoot-on-prem.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @sarvanisathish
* Microsoft Alias: **sarvanis**

**Comment by sericks007** [comment]
@fordummie, can you please provide more information about your question. Thanks!

**Comment by fordummie** [comment]
@sericks007 sorry for not reply before. 
I did already fix the issue.

Tks

**Comment by fordummie** [comment]
I did run the Test-D365FOConfiguration.ps1 inside the Infrascruture folder and saw that some VM's had a few erros. After fix this errors and reinstall Service Fabric the error was resolved.
