### ISSUE TITLE
Typo in a header

### ISSUE THREAD

**Issue by sebastianstrefel** [MicrosoftDocs/dynamics-365-unified-operations-public#3661]
Typo in the header **Dynamics 365: 2021 release wave 1 plan**. It should be called Dynamics 365: 2021 release wave 2 plan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06d5501d-4dba-a376-91fb-828ed6de0f67
* Version Independent ID: a8b3294e-2bc5-1fcb-0c80-866c917c0644
* Content: [Platform updates for version 10.0.22 of Finance and Operations apps (November 2021) - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/get-started/whats-new-platform-updates-10-0-22)
* Content Source: [articles/fin-ops-core/dev-itpro/get-started/whats-new-platform-updates-10-0-22.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/get-started/whats-new-platform-updates-10-0-22.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @sericks007
* Microsoft Alias: **sericks**

**Comment by sericks007** [comment]
@sebastianstrefel, thank you for bringing this to our attention!  I've corrected the typo, and the updated topic will be published soon.  Thanks again!
