### ISSUE TITLE
Suggestion to provide reach and valuable dual write filters examples in F&O and CE

### ISSUE THREAD

**Issue by sheko89** [MicrosoftDocs/dynamics-365-unified-operations-public#3662]
Hi, can you please verify, correct and amend the following examples then add it to this page if you find it reasonable and helpful for the page visitors:

1.	FO side filters:

A.	Equal:

Single Enum filter: (FieldName == EnumType::Test)	
Multiple Enum filters: ((FieldName == EnumType::Test) && (FieldName != EnumType::Test))

Single String filter: (FieldName like "Test")
Multiple String filters: ((FieldName like "Test") && (!(FieldName like "Test")))

B.	Not equal:

Enum filter: (FieldName != EnumType::None)
String filter: (!(FieldName like "Test"))

2.	CE side filters:

A.	Equal:

Single Enum filter: FieldName == ‘Test’
Multiple Enum filters: FieldName == ‘Test’ and FieldName == ‘Test’

Single String filter: FieldName eq ‘Test’
Multiple String filters: FieldName eq ‘Test’ and FieldName eq ‘Test’

B.	Not equal:
Enum filter: FieldName != ‘Test’ (not sure)
String filter: FieldName ne ‘Test’

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1063123b-f794-e863-2cf2-231a499c68c6
* Version Independent ID: 8c0c29c2-e3a2-809d-ce9e-6ca3b51c1d1b
* Content: [Customize table and column mappings - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/customizing-mappings)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/customizing-mappings.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/dual-write/customizing-mappings.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @NHelgren
* Microsoft Alias: **nhelgren**

**Comment by sericks007** [comment]
@sheko89, thank you for providing this feedback!

@NHelgren, please consider updating the content based on this feedback.

**Comment by sericks007** [comment]
Bug 637838 has been logged to track this issue.

**Comment by josaw1** [comment]
Closed as won't fix.
