### ISSUE TITLE
emea-multiple-vat-registration-numbers cannot be activated 

### ISSUE THREAD

**Issue by frederic-aubry-ELCA** [MicrosoftDocs/dynamics-365-unified-operations-public#3666]
cannot "Enable" it. Asked to enable another feature "Tax calculation service" but it's already enable!
@epodkolz
Check screenshot below
![image](https://user-images.githubusercontent.com/94107717/141305519-726561ed-efc5-4e1e-89a9-ff951843c21f.png)

**Comment by sericks007** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
