### ISSUE TITLE
Question related to Role access for Costing Sheets

### ISSUE THREAD

**Issue by msidbanks** [MicrosoftDocs/dynamics-365-unified-operations-public#3667]
[My question is related to what role is needed to maintain costing sheets? If there is a general guide for security accross the board for F&O that would be great.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: babfe5d4-e5f9-555e-ec2e-c19a909aeaf8
* Version Independent ID: bc447a7b-583f-4229-8cde-4944d17ff03f
* Content: [Costing sheets - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/cost-management/costing-sheets)
* Content Source: [articles/supply-chain/cost-management/costing-sheets.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/cost-management/costing-sheets.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @AndersGirke
* Microsoft Alias: **aevengir**

**Comment by sericks007** [comment]
@msidbanks, thank you for providing this feedback.

@AndersEvenGirke, please consider updating the content based on this feedback.

**Comment by sericks007** [comment]
Bug 637839 has been logged to track this issue.

**Comment by msidbanks** [comment]
Hello again. I saw the commentary of what out of box roles have access to the costing sheet and I appreciate the feedback very much. I am able to edit the costing sheet, but the issues I am still facing is that within this application I am still unable to edit, add, etc the "Rates" within the costing sheet. What user role needs access to this application?
![Costing Sheet - Rate Locked](https://user-images.githubusercontent.com/94127753/142444794-df520d75-3f27-4eea-a64c-18abfaa790af.PNG)
!

**Comment by msidbanks** [comment]
Hello I was curious if someone looked into this?

**Comment by josaw1** [comment]
Maintain cost sheet needs Accounting manager role (LedgerAccountingManager). 

View cost sheet needs role Inventory accountant clerk or Inventory accountant.
