### ISSUE TITLE
It should be needed to specify the exact certificate name when Encrypt credentials.

### ISSUE THREAD

**Issue by ans1148** [MicrosoftDocs/dynamics-365-unified-operations-public#3668]
In Step17 Encrypt credentials, it should be needed to specify the exact certificate name.
Because there are two credentials to use encrypt, axdataenciphermentcert and DataEncryption.
I think this is confused to understand.

Thanks for reading.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14409653-d5a8-bf1b-8772-97832acfe6af
* Version Independent ID: 331d5d92-1601-ed2e-0dd9-4d68beddebff
* Content: [Set up and deploy on-premises environments (Platform update 41 and later) - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/setup-deploy-on-premises-pu41)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/setup-deploy-on-premises-pu41.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/deployment/setup-deploy-on-premises-pu41.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @faix
* Microsoft Alias: **osfaixat**

**Comment by sericks007** [comment]
@ans1148, thank you for providing this feedback.

@faix, please consider updating the content based on this feedback.

**Comment by sericks007** [comment]
This content has been updated and will be published later today!
