### ISSUE TITLE
FEC more information on design is requested

### ISSUE THREAD

**Issue by anboudin** [MicrosoftDocs/dynamics-365-unified-operations-public#3669]
Hello,

Information on how is populated each box and Microsoft design is requested

Example
**JournalCode**     Electronic method can help but not auditors. They do not care regarding ER. 
                      
A column should be added to define what the method is doing:   retrieve text part of voucher number.

**JournalLib**         When journal name is used, decription is showing but for other transactions such as Free text invoice, the module name is retrieved as journalLib....

This for most of transactions. Customer as auditors needs to get how Microsoft build the tool.

**EcritureNum**       Voucher from general ledger

**Ecrituredate**        Transaction date (posting date)

**ComptNum**    Main account retrieved from legal entity chart of account

**CompteLib**            Description from main account (not from translation) should be setup in French

**ComptAux**             Retrieve from customer/vendor transactions when ledger account is linked to posting profile

**PieceRef**                 Document number (invoice). If empty this field will retrieve voucher number (as mandatory field)

**PieceDate**               Document date (invoice). If empty this field will report transaction date (as mandatory field)

**ValidateDate**               Created date from transactions in general ledger

.....

Some explanation should be more complex to describ we we should try (such as Let

Kind regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63edf6c2-6935-7df1-3efe-c7f3566a7753
* Version Independent ID: 4d6bd056-8c7a-5b10-109d-7dda67dfdd3f
* Content: [Structure of Dynamics 365 Finance data sources for the FEC - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/emea-fra-fec-audit-file-structure)
* Content Source: [articles/finance/localizations/emea-fra-fec-audit-file-structure.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/emea-fra-fec-audit-file-structure.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @liza-golub
* Microsoft Alias: **elgolu**

**Comment by kfend** [comment]
@anboudin - Thank you for the feedback.
@liza-golub - Can you please take a look at and address this? Thanks!

**Comment by kfend** [comment]
The topic was updated. Please let us know if you still have questions. Thanks!
