### ISSUE TITLE
Subledger batches 

### ISSUE THREAD

**Issue by anboudin** [MicrosoftDocs/dynamics-365-unified-operations-public#3670]
HI,

Partner contacted me regarding subledger transfer to General ledger. I shared this link but information seems not that clear on what should be done

_Asynchronous transfer of subledger batches requires that the batch server be set up, online, and working. Otherwise, the Asynchronous transfer option won't work._

Can we bring some clarification on this part?
Where can customer setup batch?
how can customer setup batch (what are the option and best way to setup batches)?
....

Bug has been also created but not published
https://msdyneng.visualstudio.com/FinOps/_queries/edit/569698/?triage=true

Need to specify clearly that Asynchronous option is NO more an option and batch job is somehow the only option. 

Kind regards
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9043d35-d539-a24c-3802-55e4fc7ad04c
* Version Independent ID: e6298f3e-7706-cd1f-79d8-88da48ae345a
* Content: [Subledger transfer to the general ledger - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/general-ledger/subledger-transfer)
* Content Source: [articles/finance/general-ledger/subledger-transfer.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/general-ledger/subledger-transfer.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @rcarlson
* Microsoft Alias: **peakerbl**

**Comment by kfend** [comment]
@anboudin - Thank you for the questions.
@Peakerbl - Can you please take a look and address these questions? Thanks!

**Comment by kfend** [comment]
created bug 642439 to track this issue.

**Comment by RyanCCarlson2** [comment]
https://github.com/MicrosoftDocs/Dynamics-365-Operations/pull/12750

**Comment by kfend** [comment]
This topic has been updated. The changes will be published in the next few hours. Thanks!
