### ISSUE TITLE
Japanese version of this document is behind English version

### ISSUE THREAD

**Issue by kitaly** [MicrosoftDocs/dynamics-365-unified-operations-public#3671]
English version contains an update on the September 2021 release while the Japanese version doesn't. Please, update the Japanese version to be on par with the English content.

English page:
https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/whats-new-dual-write

Japanese page:
https://docs.microsoft.com/ja-jp/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/whats-new-dual-write

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: b8043d72-1496-a79a-da5b-60dc1d24f561
* Version Independent ID: fa5f09b6-10d9-ab9a-6f65-da69252777c1
* Content: [二重書き込みの新機能および変更された機能 - Finance & Operations | Dynamics 365](https://docs.microsoft.com/ja-jp/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/whats-new-dual-write)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/whats-new-dual-write.md](https://github.com/MicrosoftDocs/Dynamics-365-Operations.ja-jp/blob/live/articles/fin-ops-core/dev-itpro/data-entities/dual-write/whats-new-dual-write.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @RobinARH
* Microsoft Alias: **rhaertle**

**Comment by vinceno** [comment]
@rosacek to confirm translation lead time for updates to this topic - I don't seem to have permission to actually assign this issue - cc @kfend

**Comment by rosacek** [comment]
@vinceno @kfend @kitaly the article is in localization and should be live by the end of next week. I'll provide update by Nov 26th.

**Comment by rosacek** [comment]
@kfend @kitaly @vinceno Japanese topic is up to date with the above changes
