### ISSUE TITLE
Project setup

### ISSUE THREAD

**Issue by masaldanag** [MicrosoftDocs/dynamics-365-unified-operations-public#3672]
The project setup part should explain that if you use this functionality you will not be having subledger entries when transferring deferred revenue to actual revenue.
WE have many customer complaining on this so to make it visible for them will certainly help them and will help MS too

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49ee1703-51fa-03cb-cb6c-d13c59ec0dc3
* Version Independent ID: be390b47-7972-c0d5-aa66-ac74ad24473f
* Content: [Revenue recognition setup - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/accounts-receivable/revenue-recognition-setup#project-setup)
* Content Source: [articles/finance/accounts-receivable/revenue-recognition-setup.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/accounts-receivable/revenue-recognition-setup.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @kweekley
* Microsoft Alias: **kweekley**

**Comment by kfend** [comment]
@masaldanag - Thank you for the feedback. 
@kweekley - Can you please take a look at and address this question. Thanks!

**Comment by kfend** [comment]
Created bug 642873 to track this issue.
