### ISSUE TITLE
How to specify from which company data should be retrieved from?

### ISSUE THREAD

**Issue by SysC0mp** [MicrosoftDocs/dynamics-365-unified-operations-public#3673]
I am currently working on a custom service consumed via JSON, but I could not find any information on how to specify the company account from which data should be retrieved from? Do I need to pass in the company I want as parameter and handle it in X++?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b48cdcd6-bda2-2676-71b8-e0d51e5e746b
* Version Independent ID: 90adcd3c-b494-5e93-588c-8816dc0dbf79
* Content: [Custom service development - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/custom-services)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/custom-services.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/custom-services.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Peakerbl
* Microsoft Alias: **peakerbl**

**Comment by kfend** [comment]
@SysC0mp - Thank you for the questions.
@Peakerbl - Can you please answer this question? Thanks!

**Comment by kfend** [comment]
Bug 642875 created to track this issue.

**Comment by SysC0mp** [comment]
@josaw1 Why was this closed?

**Comment by SysC0mp** [comment]
@josaw1 Any information why this was closed? Documentation isn't updated yet to include instructions for this.
