### ISSUE TITLE
Credit and collections

### ISSUE THREAD

**Issue by Grayman1881** [MicrosoftDocs/dynamics-365-unified-operations-public#3674]
Hello,

I am checking the page to have an overview of the solution components of Dynamics 365 Finance and Operations. 
However, I cannot see some modules like consolidations, credit and collections, expense management, retail and commerce, etc.

Are you planning to include them?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da30cb1c-cdec-8d0a-92d4-cef0cd34ecc7
* Version Independent ID: bbdccbb0-c648-bdbb-3a59-eb2ec497ceec
* Content: [Finance and Operations application documentation - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/)
* Content Source: [articles/fin-ops-core/fin-ops/index.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/index.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @tonyafehr
* Microsoft Alias: **tfehr**

**Comment by tonyafehr** [comment]
@Grayman1881- Thanks for your question. Some of the areas you asked about, aren't their own modules in our documentation, while others have been moved from the Finance application set into their own space. Here are links to the areas you have listed above. If you are still looking for other content, please let me know. 
[Consolidations](https://docs.microsoft.com/en-us/dynamics365/finance/general-ledger/financial-consolidations-currency-translation#consolidations)
[Credit and collections](https://docs.microsoft.com/en-us/dynamics365/finance/accounts-receivable/cm-credit-and-collections-overview)
[Expense management](https://docs.microsoft.com/en-us/dynamics365/project-operations/prod-exp/expense-management)
[Commerce (formerly Retail)](https://docs.microsoft.com/en-us/dynamics365/commerce/)
