### ISSUE TITLE
Need details / example for "hook downstream processes into the trigger"

### ISSUE THREAD

**Issue by manishmoothedath** [MicrosoftDocs/dynamics-365-unified-operations-public#3675]
The documentation talks about
Quote - "The Enable triggers in target database option sets export jobs to enable SQL triggers in the target database. This option lets you hook downstream processes into the trigger to orchestrate actions that must be started after records have been inserted"

There is no mention of how this downstream process can be hooked into the BYOD trigger, and no good examples available in Azure database docs as well.

**Comment by kfend** [comment]
@manishmoothedath - Thanks for your question. Can you tell me what topic you are referring to? Thanks!

**Comment by manishmoothedath** [comment]
Sorry Kristin, I thought the docs page will get mapped to the issue automatically. 
Issue is related to this article on BYOD database :
https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/export-entities-to-your-own-database

**Comment by kfend** [comment]
Created bug 642876 to track this issue.

**Comment by josaw1** [comment]
Closed as won't fix.
