### ISSUE TITLE
Is production database backup retained for 35 days or 28 days?

### ISSUE THREAD

**Issue by Izmiyash** [MicrosoftDocs/dynamics-365-unified-operations-public#3676]
[Enter feedback here]

https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/imp-lifecycle/go-live-faq?toc=/dynamics365/commerce/toc.json#how-often-is-my-production-database-backed-up

I found there is "Automatic backups are retained for 35 days."
This is not consistent with the other source like below docs page. It says 28 days for production backup .
https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/database-point-in-time-restore
Please correct wrong one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c8dccad-b805-ed0d-26e3-7f6c18981421
* Version Independent ID: 2c01af71-c81a-68a3-0977-c5a9e9c6e953
* Content: [Go-live for implementation projects FAQ - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/imp-lifecycle/go-live-faq?toc=/dynamics365/commerce/toc.json)
* Content Source: [articles/fin-ops-core/fin-ops/imp-lifecycle/go-live-faq.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/imp-lifecycle/go-live-faq.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @sshashi7
* Microsoft Alias: **sshashi**

**Comment by kfend** [comment]
@Izmiyash - Thank you for the question.
@sshashi7 - Can you please take a look and answer the question and update the documentation as necessary? Thanks!

**Comment by kfend** [comment]
Created bug 642877 to track this issue.

**Comment by surekota** [comment]
Correct days is 28 for production backups, thanks for raising the issue
