### ISSUE TITLE
localagent-config.json buggy ?

### ISSUE THREAD

**Issue by GeorgeSasDK** [MicrosoftDocs/dynamics-365-unified-operations-public#3677]
When upgrading LocalAgent from Version 2.6 up to version 3.0 to my OnPremise environment I am getting an error.

PS C:\Temp\LocalAgent-1051074\LocalAgent-1051074> .\LocalAgentCLI.exe install .\localagent-config.json
LocalAgentCLI.exe Error: 0 : Exception Newtonsoft.Json.JsonReaderException: Could not convert string to boolean: {Enable
EdgeValue}. Path 'components[2].isEnabled', line 129, position 34.
   at Newtonsoft.Json.JsonReader.ReadBooleanString(String s)
   at Newtonsoft.Json.JsonTextReader.ReadAsBoolean()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, B
oolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, Jso
nObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonCo
ntract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object exis
tingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayCo
ntract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonCont
ract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter p
ropertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object tar
get)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, Jso
nObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonCo
ntract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object exis
tingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean
 checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at LocalAgentCLI.Program.Main(String[] args)

If I am using OLD localagent-config.json I can upgrade the agent.
I can see line 128 starts with : 

"name": "AlmOrchestrator",
		"isEnabled": "{EnableEdgeValue}",
		"placementCriteria": "(IsOrchestratorEnabled == True)",

In my old  localagent-config.json I do not have any "AlmOrchestrator" configuration ... I assume this is for Hybrid configs ?

So as the documentation for the localagent-config.json is non existing and the localagent-config.json is generated by LCS I am not sure if this is a BUG or is something you guys forgot to include in the config when the localagent-config.json is generated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38d81ec9-52b0-5b29-282b-f5cf451ba746
* Version Independent ID: 6b1b4864-e2a8-d0f5-b0d1-5d04fa3e82ca
* Content: [Update the local agent - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/update-local-agent)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/update-local-agent.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/lifecycle-services/update-local-agent.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @faix
* Microsoft Alias: **osfaixat**

**Comment by faix** [comment]
Hello @GeorgeSasDK,

Yes, this is a known issue that will be fixed with the next release of LCS. Should be in about a week. There is a very simple workaround to this problem. In LCS go to your project settings, on-premises connectors, edit your connector, open "Enter Configuration" and save without changing anything and download the Local Agent configuration file again.

And yes, you are correct those are new settings specifically for our Hybrid Topologies.

**Comment by GeorgeSasDK** [comment]
I have only upgraded my Sandbox for now using old localagent-config.json file and it worked.
I will try the "save" config you suggested and see if the file modifies, then I am sure I can use it for PROD.
Thanks.

**Comment by GeorgeSasDK** [comment]
Tried to open config on Sandbox , enter config , save config , download config. 
localagent-config.json does not change so I guess my LocalAgent installation will still fail if localagent-config.json does not change.

**Comment by faix** [comment]
Interesting, that workaround worked for another customer. In any case, you can manually replace {EnableEdgeValue} with false and that will enable you to use the new localagent-config.json

**Comment by GeorgeSasDK** [comment]
Ok, that can do, thanks.
If I installed agent using old localagent-config.json do I have to remove it and re install using new localagent-config.json or I can just leave it like it is now and just use the new confi for PROD ?

**Comment by faix** [comment]
For this particular version, we made sure that the localagent-config.json from 2.7.0 was compatible with the 3.0.0 installer if you didn't require the new hybrid functionalities. So it should be fine.

**Comment by GeorgeSasDK** [comment]
Thank you. You guys should post a small note on this so people don't start running around :)

**Comment by faix** [comment]
There is a thread on the LBD yammer for this. I would suggest you join it if you are not a member yet. That's where we usually post announcements as well as help troubleshoot issues and provide general support: https://www.yammer.com/dynamicsaxfeedbackprograms/#/threads/inGroup?type=in_group&feedId=13595809&view=all
