### ISSUE TITLE
Snapshot of the measurements in Reviews

### ISSUE THREAD

**Issue by zenkiddo** [MicrosoftDocs/dynamics-365-unified-operations-public#3678]
Dear Support team,
   I was testing the Review functionality in D365 HR and from what I see the measurements aren't froze once a review is complete. They continue to be updated as the referenced records change, which can be quite confusing. 

This is the phrase I'm refering to from the documentation:
"After the review is finalized, a snapshot of the measurements is stored to retain the history of those items at the time of the review."

Am I missing something or is the documentation wrong?

It would be actually great if a snapshot were generated from the progress of the Goals and their Measurements when the Sign off occurs.. If the report isn't printed after the Review took place, then as soon a Goal or Measurement changes, it won't reflect the reality.

Thank you!
Best regards,
Adrian Nastase

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7a27404-cc5d-6298-cf05-1bb7c8f9b156
* Version Independent ID: e735b173-6cf1-52b3-277c-e3965038343f
* Content: [Performance management - Human Resources | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/human-resources/hr-develop-performance-management-overview)
* Content Source: [articles/human-resources/hr-develop-performance-management-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/human-resources/hr-develop-performance-management-overview.md)
* Service: **dynamics-365-human-resources**
* Product: ****
* Technology: ****
* GitHub Login: @twheeloc
* Microsoft Alias: **twheeloc**

**Comment by kfend** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: Support contact options. In particular, you might want to go to the Dynamics 365 community page to get help with your questions from the Dynamics community.
