### ISSUE TITLE
Stepped calculation with quantity

### ISSUE THREAD

**Issue by echofive0706** [MicrosoftDocs/dynamics-365-unified-operations-public#3679]
It would be helpful to mention that the stepped calculation method with quantity thresholds is calculating the average value for all quantities sold and not the actual values of the first quantities invoiced.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1646986-d690-52b3-d567-e962a2715d7b
* Version Independent ID: ab20269c-b0b3-6d4c-5afc-afd9b24a8e14
* Content: [Rebate management deals - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/rebate-management/rebate-management-deals#calc-methods)
* Content Source: [articles/supply-chain/rebate-management/rebate-management-deals.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/rebate-management/rebate-management-deals.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @sherry-zheng
* Microsoft Alias: **chuzheng**

**Comment by kfend** [comment]
Bug 642878 created to track this issue.

**Comment by josaw1** [comment]
Closed as won't fix.
