### ISSUE TITLE
Additional fields for conditional statements

### ISSUE THREAD

**Issue by LorraineFrancke** [MicrosoftDocs/dynamics-365-unified-operations-public#368]
Needs correction from 'Departements' to Departments.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8920480b-1ca9-df92-5e8f-c2bb7f5732df
* Version Independent ID: af834991-1673-3039-3bc1-058263ca6f69
* Content: [What's new or changed in Dynamics 365 for Talent Core HR (September 10, 2018) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/talent/whats-new-talent-september-10)
* Content Source: [articles/talent/whats-new-talent-september-10.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/talent/whats-new-talent-september-10.md)
* Service: **dynamics-365-talent**
* GitHub Login: @DarinKramer
* Microsoft Alias: **dkrame**

**Comment by sericks007** [comment]
Thank you for letting us know! I've fixed the typos.
