### ISSUE TITLE
Ask to add Document Routing History cleanup

### ISSUE THREAD

**Issue by TakumaSai** [MicrosoftDocs/dynamics-365-unified-operations-public#3680]
[フィードバックをこちらに入力してください]
Could you please add Document Routing History cleanup in this Docs?
Path : https://[host_adress]/?mi=DocumentRoutingHistoryCleanupConfig
Batch job : Document Routing History cleanup
---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 926b5538-8734-b2cf-7d77-21f35dbf0e98
* Version Independent ID: 219ba487-1689-e78c-773e-42d019f779f1
* Content: [Dynamics 365 Finance と Dynamics 365 Supply Chain Management のクリーンアップ ルーチン - Finance & Operations | Dynamics 365](https://docs.microsoft.com/ja-jp/dynamics365/fin-ops-core/dev-itpro/sysadmin/cleanuproutines#system-administration)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/cleanuproutines.md](https://github.com/MicrosoftDocs/Dynamics-365-Operations.ja-jp/blob/live/articles/fin-ops-core/dev-itpro/sysadmin/cleanuproutines.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @dvliegen
* Microsoft Alias: **dvliegen**

**Comment by tonyafehr** [comment]
@TakumaSai, thanks for the feedback. 
@dvliegen, please review and consider making updates.

**Comment by dvliegen** [comment]
@TakumaSai I will make the change but need help with a few things:

1.  I struggle to find how to navigate to this cleanup form. I can only find it by adding the menu item name to the URL.
2.  Can you review the proposed description (see below)

**Document routing history cleanup configuration**
This cleanup routine is used to delete data visible in Document Routing Status form. [Document Routing Agent](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/install-document-routing-agent?toc=/dynamics365/commerce/toc.json) (DRA) is a downloadable application that you can use to enable network printing scenarios.
