### ISSUE TITLE
Cost Management missing clean up jobs

### ISSUE THREAD

**Issue by jopankow** [MicrosoftDocs/dynamics-365-unified-operations-public#3681]
This page is missing these clean up jobs:

Cost Management > Manufacturing accounting > Clean up > Production orders cleanup

Cost Management > Manufacturing accounting > Clean up > Production recalculation

Cost Management > Manufacturing accounting > Clean up > Clean up the costing sheet cache

The costing sheet cache job is documented here: https://community.dynamics.com/ax/b/axinthefield/posts/f-o-data-management-reviewing-large-tables-and-database-growth

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 926b5538-8734-b2cf-7d77-21f35dbf0e98
* Version Independent ID: 219ba487-1689-e78c-773e-42d019f779f1
* Content: [Cleanup routines in Dynamics 365 Finance and Dynamics 365 Supply Chain Management - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/cleanuproutines)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/cleanuproutines.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/sysadmin/cleanuproutines.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @dvliegen
* Microsoft Alias: **dvliegen**

**Comment by tonyafehr** [comment]
@dvliegen, please review and consider making updates.

**Comment by dvliegen** [comment]
@jopankow  I want to make the requested change but need help with a description of these cleanup actions. Can you provide it to me? If not, do you know the responsible PM so I can reach out to him/her. thank you

Cost Management > Manufacturing accounting > Clean up > Production orders cleanup
Cost Management > Manufacturing accounting > Clean up > Production recalculation
Cost Management > Manufacturing accounting > Clean up > Clean up the costing sheet cache
