### ISSUE TITLE
It's not possible to take screenshots anymore using task recorder

### ISSUE THREAD

**Issue by orichardt** [MicrosoftDocs/dynamics-365-unified-operations-public#3683]
It's not possible to take screenshots anymore using task recorder, the extension to Chrome or Edge is taken out and is not accessible anymore!
Please review and update the documentation.
Please indicate another way of doing the screenshots or provide a tool for it as it is a very valuable option

Ole

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5762f9e-d7f4-e7fc-49c7-6db64c01bc6a
* Version Independent ID: 2aab18ad-f2f1-c0ad-c109-38806c8491a3
* Content: [Task recorder resources - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/user-interface/task-recorder?toc=%2Fdynamics365%2Fsupply-chain%2Ftoc.json)
* Content Source: [articles/fin-ops-core/dev-itpro/user-interface/task-recorder.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/user-interface/task-recorder.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by josaw1** [comment]
Thank you for your feedback. @jasongre can you please take a look.

**Comment by josaw1** [comment]
BUG 641738 created to track.

**Comment by jasongre** [comment]
@orichardt I just verified that the pre-release extension referred to in our documentation does indeed still work. Please try to reload the extension based on the github link provided in the "Taking screenshots in Task recorder" section.

**Comment by orichardt** [comment]
HI Jason, thank you for this. I tried again and got it to work on Chrome.

Ole

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
