### ISSUE TITLE
D365 Ecom B2C tenant setup documentation outdated

### ISSUE THREAD

**Issue by RobvanB** [MicrosoftDocs/dynamics-365-unified-operations-public#3684]
This documentation no longer matches the Azure Portal pages, and this makes it very confusing.
Specifically the app registration piece.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7807b1d-0012-5619-26a6-a11881ffc94d
* Version Independent ID: 204cf318-00d8-f3ef-86cf-08589cb126f1
* Content: [Set up a B2C tenant in Commerce - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/set-up-b2c-tenant)
* Content Source: [articles/commerce/set-up-B2C-tenant.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/set-up-B2C-tenant.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @BrianShook
* Microsoft Alias: **brshoo**

**Comment by josaw1** [comment]
Thank you for your feedback. @BrianShook can you please take a look?

**Comment by josaw1** [comment]
BUG 641729 create to track.

**Comment by josaw1** [comment]
Fixed.
