### ISSUE TITLE
How to debug a copy of production environment (AxDBAdmin credentials not available anymore in Sandboxes)

### ISSUE THREAD

**Issue by manishmoothedath** [MicrosoftDocs/dynamics-365-unified-operations-public#3685]
[As per the documentation , we need to use the axdbadmin credentials to connect to the sandbox from a dev environment inorder to debug a copy of production database. but now there is no axdbadmin credentials available in the LCS anymore. Pls advice how to debug a copy of the production database. 
My scenario has an issue with Power platform "Planning optimisation" engine which cannot be analysed in development environments.
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb08fb04-94d5-ef25-8162-a0d79f5ee70a
* Version Independent ID: 6d43b4b7-cc2e-49bc-564a-5eb5eacefa84
* Content: [Debug a copy of the production database - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/dbmovement-scenario-debugdiag)
* Content Source: [articles/fin-ops-core/dev-itpro/database/dbmovement-scenario-debugdiag.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/database/dbmovement-scenario-debugdiag.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by josaw1** [comment]
Thank you for the feedback. @laneswenka can you please take a look?

**Comment by josaw1** [comment]
Closed as won't fix.

**Comment by SysC0mp** [comment]
@josaw1 Why "Won't fix"? This is a simple and valid question, as the information on the documentation is deprecated for the current process. Shouldn't it be a high priority for Microsoft to keep their documentation up to date?
