### ISSUE TITLE
Not working for me - must be missing something?

### ISSUE THREAD

**Issue by MeragoJert** [MicrosoftDocs/dynamics-365-unified-operations-public#3688]
I'm trying to get the new RCS method to work but, firstly the text in this doc seems to be missing sections (it just states to select the model, add a description and click OK, the step for marking the model as complete before those options are presented is missing).  I have an RCS repo but I cannot get anything shared back to it - the Upload to repository button is permanently greyed out - I suspect I'm missing something that's missing from the document?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0974205-2a3c-163a-000e-af17aa664a7c
* Version Independent ID: 6e7f6297-fc2b-2127-6904-530e374809a7
* Content: [Create ER configurations in RCS and upload them to the Global repository - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/rcs-global-repo-upload?toc=/dynamics365/finance/toc.json)
* Content Source: [articles/finance/localizations/rcs-global-repo-upload.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/rcs-global-repo-upload.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @JaneA07
* Microsoft Alias: **janeaug**

**Comment by josaw1** [comment]
Thank you for your feedback. @JaneA07 please review.

**Comment by josaw1** [comment]
BUG 641735 created to track.
