### ISSUE TITLE
Additional explanations for extending the Ecom-site

### ISSUE THREAD

**Issue by fdittgen** [MicrosoftDocs/dynamics-365-unified-operations-public#3689]
It's impossible to follow the explanation for the Ecom-implementation:
"Use this code to set values for order attributes in the cart."
Some more information about what to extend (DataAction/Module/...) would be really helpful. This code-snipplet is without additional explanations useless.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: daca1f9e-c913-eb05-1a7d-23e6a54fc782
* Version Independent ID: f6ab1665-4c15-c2ed-9bf0-f5411295840a
* Content: [Define and set order attributes - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/order-attributes)
* Content Source: [articles/commerce/dev-itpro/order-attributes.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/order-attributes.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by josaw1** [comment]
Thank you for the feedback. @mugunthanm please review.

**Comment by mugunthanm** [comment]
Thanks for the feedback, this document shows a quick snippet of how you can set attribute value in e-Commerce, please refer to the detailed documentation on modules or data action for the E2E flow.
https://docs.microsoft.com/en-us/dynamics365/commerce/e-commerce-extensibility/sdk-getting-started
