### ISSUE TITLE
Azure AD Auth with MFA Enabled

### ISSUE THREAD

**Issue by sayanghosh123** [MicrosoftDocs/dynamics-365-unified-operations-public#369]
Hi, if the Azure AD instance backing the D365FO instance has MFA set up for user accounts, will this work? Is there a specific workaround / trick to make it work? We have seen our tests failing after MFA was rolled out to our AAD tenant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 221bcbdf-2c16-ee9d-f289-75980e35b17a
* Version Independent ID: 6377db2c-d7b7-82bb-baeb-8f2311a9fb87
* Content: [Test services by using third-party utilities - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/third-party-service-test#prerequisites)
* Content Source: [articles/dev-itpro/data-entities/third-party-service-test.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/third-party-service-test.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by sericks007** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle questions for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the Dynamics 365 for Finance and Operations community page to get help with your questions from the Dynamics community.
