### ISSUE TITLE
deutsche Übersetzung ist unverständlich

### ISSUE THREAD

**Issue by akaradagi** [MicrosoftDocs/dynamics-365-unified-operations-public#3692]
die Übersetzung der Seite process-rebates-payment ins Deutsche ist nicht verständlich. Beispiel: "Legen Sie Häkchen im Markengebiet für die Ansprüche fest, die Sie in Gutschrift einbezogen werden sollen."
Es fehlt auch die Beschreibung des Einstiegspunkts (MenuItem).

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: ab8c543b-4b94-217f-fc41-03f9dc370137
* Version Independent ID: 4bb9f0b5-1dcc-7be5-927f-5a43b75e156b
* Content: [Zahlungsnachlässe verarbeiten - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/de-de/dynamics365/supply-chain/sales-marketing/tasks/process-rebates-payment)
* Content Source: [articles/supply-chain/sales-marketing/tasks/process-rebates-payment.md](https://github.com/MicrosoftDocs/Dynamics-365-Operations.de-de/blob/live/articles/supply-chain/sales-marketing/tasks/process-rebates-payment.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @Henrikan
* Microsoft Alias: **henrikan**

**Comment by josaw1** [comment]
Thank you for the feedback. @henrikan please review.

**Comment by josaw1** [comment]
BUG 641734 created to track.

**Comment by josaw1** [comment]
Closed as won't fix.
