### ISSUE TITLE
Use of Feature is not provided. Only steps are given.

### ISSUE THREAD

**Issue by Neeraj2912** [MicrosoftDocs/dynamics-365-unified-operations-public#3693]
Nothing is mentioned about the features. Only the process is given on how to use this. All doc link should first explain about the feature/ its uses with scenarios if possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57abc820-7d4c-913e-7c1b-92ce568f0079
* Version Independent ID: 7f1fb434-f6fc-493d-df73-3861a328c48b
* Content: [Journalize posted journal entries - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/general-ledger/tasks/journalize-posted-journal-entries)
* Content Source: [articles/finance/general-ledger/tasks/journalize-posted-journal-entries.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/general-ledger/tasks/journalize-posted-journal-entries.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @aprilolson
* Microsoft Alias: **aolson**

**Comment by josaw1** [comment]
Thank you for the feedback. @aprilolson please review.

**Comment by josaw1** [comment]
BUG 641739 created to track.

**Comment by RyanCCarlson2** [comment]
@kfend can this be closed? The changes are published. I've just closed the bug in ADO.

**Comment by kfend** [comment]
Thanks for taking care of this  @RyanCCarlson2! I will close this issue.
