### ISSUE TITLE
Wrong Example -> Enable disambiguation behavior for custom lookup scenarios

### ISSUE THREAD

**Issue by SteffenEngelhardt** [MicrosoftDocs/dynamics-365-unified-operations-public#3694]
Hi,

the example for the part "Enable disambiguation behavior for custom lookup scenarios" is wrong.

it is currently -> 
public str resolveAmbiguousReference()
{
    FormControlAmbiguousReferenceResolver::resolveAmbiguousReferenceForControl (this, true);
}

Should be 

public str resolveAmbiguousReference()
{
    return FormControlAmbiguousReferenceResolver::resolveAmbiguousReferenceForControl(this, true);
}

as it is missing the return parameter.

Best regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 531f06b4-5c5b-44e8-79a0-6d712a473742
* Version Independent ID: 6377d0f5-e8d6-bdd5-64ab-eb190f817c93
* Content: [Contextual data entry for lookups - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/user-interface/contextual-data-entry-lookups)
* Content Source: [articles/fin-ops-core/dev-itpro/user-interface/contextual-data-entry-lookups.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/user-interface/contextual-data-entry-lookups.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by kamaybac** [comment]
@SteffenEngelhardt  , thank you for contacting us regarding this help topic. I have passed your comment on for consideration.

**Comment by kamaybac** [comment]
Bug 652683 created to track this issue

**Comment by jasongre** [comment]
Thanks, @SteffenEngelhardt, for reporting this! The corrected documentation should be available shortly.
