### ISSUE TITLE
Redirect URL is not complete

### ISSUE THREAD

**Issue by fastianumair** [MicrosoftDocs/dynamics-365-unified-operations-public#3696]
Under section **Registration process**, in **Redirect URL**, URL should have /oauth. Otherwise, authentication will fail.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2213414-926d-10e1-538b-efef09dc0181
* Version Independent ID: 03be53f7-c305-cb02-7627-2ea4f1c01bd4
* Content: [Configure PowerBI.com integration - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/configure-power-bi-integration#register-your-finance-and-operations-deployment-as-a-web-app-in-the-azure-portal)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/configure-power-bi-integration.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/analytics/configure-power-bi-integration.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by kamaybac** [comment]
@fastianumair  , thank you for contacting us regarding this help topic. I have passed your comment on for consideration.

**Comment by kamaybac** [comment]
Bug 652686 created to track this issue.

**Comment by sericks007** [comment]
@fastianumair, thanks for letting us know!  I've updated that line.  The update will be published soon.
