### ISSUE TITLE
Public feed link broken

### ISSUE THREAD

**Issue by epereyra82** [MicrosoftDocs/dynamics-365-unified-operations-public#3697]
On the public feed link under this section the link sends this message (https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/retail-sdk/migrate-commerce-sdk#crt-extensions)

{"@context":{"@vocab":"http://schema.nuget.org/services#","comment":"http://www.w3.org/2000/01/rdf-schema#comment","label":"http://www.w3.org/2000/01/rdf-schema#label"},"resources":[{"@id":"https://pkgs.dev.azure.com/commerce-partner/803bdde2-a918-4b56-806f-0f3b7546b1be/_packaging/aa42c2b9-2268-4106-9152-0108e4f0e843/nuget/v2/","@type":"PackagePublish/2.0.0"},{"@id":"https://pkgs.dev.azure.com/commerce-partner/803bdde2-a918-4b56-806f-0f3b7546b1be/_packaging/aa42c2b9-2268-4106-9152-0108e4f0e843/nuget/v2/","@type":"LegacyGallery/2.0.0"},{"@id":"https://pkgs.dev.azure.com/commerce-partner/803bdde2-a918-4b56-806f-0f3b7546b1be/_packaging/aa42c2b9-2268-4106-9152-0108e4f0e843/nuget/v3/registrations2/","@type":"RegistrationsBaseUrl/3.0.0-beta"},{"@id":"https://pkgs.dev.azure.com/commerce-partner/803bdde2-a918-4b56-806f-0f3b7546b1be/_packaging/aa42c2b9-2268-4106-9152-0108e4f0e843/nuget/v3/registrations2-semver2/","@type":"RegistrationsBaseUrl/3.6.0","comment":"This base URL includes SemVer 2.0.0 packages."},{"@id":"https://pkgs.dev.azure.com/commerce-partner/803bdde2-a918-4b56-806f-0f3b7546b1be/_packaging/aa42c2b9-2268-4106-9152-0108e4f0e843/nuget/v3/registrations2-semver2/","@type":"RegistrationsBaseUrl/Versioned","comment":"This base URL includes SemVer 2.0.0 packages."},{"@id":"https://pkgs.dev.azure.com/commerce-partner/803bdde2-a918-4b56-806f-0f3b7546b1be/_packaging/aa42c2b9-2268-4106-9152-0108e4f0e843/nuget/v3/query2/","@type":"SearchQueryService/3.0.0-beta"},{"@id":"https://pkgs.dev.azure.com/commerce-partner/803bdde2-a918-4b56-806f-0f3b7546b1be/_packaging/aa42c2b9-2268-4106-9152-0108e4f0e843/nuget/v3/flat2/","@type":"PackageBaseAddress/3.0.0"},{"@id":"https://pkgs.dev.azure.com/commerce-partner/","@type":"VssBaseUrl"},{"@id":"urn:uuid:aa42c2b9-2268-4106-9152-0108e4f0e843","@type":"VssFeedId","label":"dynamics365-commerce"},{"@id":"com.visualstudio.feeds.feedview:aa42c2b9-2268-4106-9152-0108e4f0e843","@type":"VssQualifiedFeedViewId","label":"dynamics365-commerce"},{"@id":"urn:uuid:803bdde2-a918-4b56-806f-0f3b7546b1be","@type":"AzureDevOpsProjectId","label":"Registry"}],"version":"3.0.0-beta"}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a07b0d94-2f96-7b3a-9848-0a4e652b205c
* Version Independent ID: a07b0d94-2f96-7b3a-9848-0a4e652b205c
* Content: [Migrate to the Commerce SDK - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/retail-sdk/migrate-commerce-sdk)
* Content Source: [articles/commerce/dev-itpro/retail-sdk/migrate-commerce-sdk.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/retail-sdk/migrate-commerce-sdk.md)
* Service: **dynamics-365-commerce**
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by mugunthanm** [comment]
Thanks for the feedback, the public feed link is not a browsable link, you can add this to the NuGet config file in your solution and consume the packages/browse the packages using the NuGet manager.
