### ISSUE TITLE
Reference to DB sync errors section uses different wording to section header

### ISSUE THREAD

**Issue by rrhkpmg** [MicrosoftDocs/dynamics-365-unified-operations-public#3699]
Section [Issue: A step failed with errors](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/deployable-package-troubleshooting#issue-a-step-failed-with-errors) refers the reader to **Common DB Sync Failures** but there is no such section: relevant header appears to be [Typical database synchronization issues](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/deployable-package-troubleshooting#typical-database-synchronization-issues)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b955529-8696-80d2-380b-e98432369ba7
* Version Independent ID: d8f6e4b6-c6ab-8645-75f3-6b91ef645ad4
* Content: [Troubleshoot package application issues - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/deployable-package-troubleshooting)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/deployable-package-troubleshooting.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/deployment/deployable-package-troubleshooting.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by kamaybac** [comment]
@rrhkpmg , thank you for contacting us regarding this help topic. I have passed your comment on for consideration.

**Comment by kamaybac** [comment]
Bug 652687 created to track this issue.

**Comment by sericks007** [comment]
@rrhkpmg, thanks for letting us know about this!  I've corrected the text as you suggested.  This update will be published later today.
