### ISSUE TITLE
content is duplicated

### ISSUE THREAD

**Issue by B-rade** [MicrosoftDocs/dynamics-365-unified-operations-public#3700]
content is duplicated within this page. remove duplicated content.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60570f5b-1289-9474-0119-efd0ab01ca42
* Version Independent ID: 9f5104bd-b586-250c-608e-b9b5b9556bda
* Content: [Back up the databases for Finance and Operations apps - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lcs-solutions/database-backup-lcs-solutions)
* Content Source: [articles/fin-ops-core/dev-itpro/lcs-solutions/database-backup-lcs-solutions.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/lcs-solutions/database-backup-lcs-solutions.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **omarc**

**Comment by kamaybac** [comment]
@B-rade , thank you for contacting us regarding this help topic. I have passed your comment on for consideration.

**Comment by sericks007** [comment]
@B-rade, thanks for letting us know about this.  I've removed the duplicated content.
