### ISSUE TITLE
Link Additional resources / Microsoft Dynamics Localization Portal: Czech Republic report is broken.

### ISSUE THREAD

**Issue by MrHenrikLevinson** [MicrosoftDocs/dynamics-365-unified-operations-public#3701]
Hi
Link Additional resources / Microsoft Dynamics Localization Portal: Czech Republic report is broken.
https://mbs.microsoft.com/files/customer/AX/Support/supportnews/CzechRepublic.html
Regards
Henrik Levinson

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95cb5d47-0ded-929a-7673-99fdf4008481
* Version Independent ID: bb3c65fb-36f2-9afa-3553-9f2bce352a66
* Content: [Czech Republic overview - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/czech-republic)
* Content Source: [articles/finance/localizations/czech-republic.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/czech-republic.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @ShylaThompson
* Microsoft Alias: **roschlom**

**Comment by kamaybac** [comment]
@MrHenrikLevinson , thank you for contacting us regarding this help topic. I have passed your comment on for consideration.
