### ISSUE TITLE
Small errors on email notification tag names

### ISSUE THREAD

**Issue by NBC1000** [MicrosoftDocs/dynamics-365-unified-operations-public#3702]
Couple of errors on tag names:

pickupstorehourfrom -> should be pickupstoreopenfrom (the corresponding description should be changed too)
pickupstorehourto -> should be pickupstoreopento (the corresponding description should be changed too)
giftcardbalance -> presumably should be availablebalance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ef943c1-f092-fcd4-45d3-ef124979252a
* Version Independent ID: 562b85fc-b76a-732a-ecd5-c586e9ad8d10
* Content: [Create email templates for transactional events - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/email-templates-transactions)
* Content Source: [articles/commerce/email-templates-transactions.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/email-templates-transactions.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @bicyclingfool
* Microsoft Alias: **stuharg**

**Comment by kamaybac** [comment]
@NBC1000 , thank you for contacting us regarding this help topic. I have passed your comment on for consideration.

**Comment by kamaybac** [comment]
Bug 652690 created to track this issue

**Comment by kamaybac** [comment]
These fixes have been applies
