### ISSUE TITLE
Sales order recap > Order > Modify for cancelled orders

### ISSUE THREAD

**Issue by thedynamicsgirl** [MicrosoftDocs/dynamics-365-unified-operations-public#3704]
[There is no mention anywhere of a removed functionality which we were using in 10.0.18 and is no longer available in 10.0.21. 
For Sales Orders (created using call centre functionality) with status =Cancelled, in 10.0.18 we had in Functions section in action pane Sales order recap > Order > MODIFY, but with 10.0.21 Sales order recap > Order > MODIFY is no longer available for a cancelled sales order. We were widely using this functionality for a specific requirement and I do not see any mention of this being removed in 10.0.19/20/21. Apologies if this is not the right place to raise this.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47f9c30f-1820-9a82-e881-669778641bd8
* Version Independent ID: ca1e9b31-60e2-5dbc-ac31-b55c2e280a2f
* Content: [Platform updates for version 10.0.21 of Finance and Operations apps (October 2021) - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/get-started/whats-new-platform-updates-10-0-21)
* Content Source: [articles/fin-ops-core/dev-itpro/get-started/whats-new-platform-updates-10-0-21.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/get-started/whats-new-platform-updates-10-0-21.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @sericks007
* Microsoft Alias: **sericks**

**Comment by kamaybac** [comment]
@thedynamicsgirl , thank you for contacting us regarding this help topic. I have passed your comment on for consideration.  Please note that this isn't really a support channel, so if you're looking for a quick answer to your question, I recommend you follow up with Microsoft Support. If this turns out to be a documentation issue, we'll try to fix it soon, but there could go a week or more.

**Comment by kamaybac** [comment]
Bug 652698 created to track this issue
