### ISSUE TITLE
Information on introduction refers to a specific 3rd party tool CEGID

### ISSUE THREAD

**Issue by anboudin** [MicrosoftDocs/dynamics-365-unified-operations-public#3705]
Hi

Information on introduction refers to a specific 3rd party tool CEGID. 
On customer comment on this and ask if Microsoft has any specific contract with CEGID.  I am not sure about it or why it refers to CEGID.

if there are other tools available on market, it may be good to less specific.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cf96275-ee7e-3469-5228-38484757148a
* Version Independent ID: e2c49412-9e52-e7e6-ab74-2a166cc1c166
* Content: [DAS-2 report - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/emea-fra-das2-report)
* Content Source: [articles/finance/localizations/emea-fra-das2-report.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/emea-fra-das2-report.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @sndray
* Microsoft Alias: **roschlom**

**Comment by kamaybac** [comment]
@anboudin , thank you for contacting us regarding this help topic. I have passed your comment on for consideration.

**Comment by sndray** [comment]
CEGID was an example. We don't have any additional contract. I will suggest to remove and replace by third party software
