### ISSUE TITLE
Adding information how to deal with FO user when “Active Directory Security Group“ configuration key is enabled 

### ISSUE THREAD

**Issue by ReneVolkmer** [MicrosoftDocs/dynamics-365-unified-operations-public#3708]
Hello Markus,
could you please update this article with information how to proceed in case that “Active Directory Security Group“ configuration key is enabled? We discovered (via MS Support request TrackingID#2112020050002043) that in this case the FO user representing WHS App (and connected to Registered App in System administration > Setup > Azure Active Directory applications. as mentioned at https://docs.microsoft.com/en-us/dynamics365/supply-chain/warehousing/install-configure-warehouse-management-app#user-azure-ad) needs to have real AAD user email address otherwise connection from WHS App fails with errror “please verify that the user is valid and setup correctly”. I believe this would safe some time to some users and MS support as well. Thank you.

Best regards
Rene Volkmer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc2ac844-c345-707a-b2e9-5d4edf7c8541
* Version Independent ID: ae6e65c3-c1e1-c4cc-e05c-1c2ebd4bafc6
* Content: [Install and connect the Warehouse Management mobile app - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/warehousing/install-configure-warehouse-management-app)
* Content Source: [articles/supply-chain/warehousing/install-configure-warehouse-management-app.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/warehousing/install-configure-warehouse-management-app.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @MarkusFogelberg
* Microsoft Alias: **mafoge**

**Comment by kfend** [comment]
@ReneVolkmer - Thank you for your feedback.
@kamaybac - Can you please take a look and this and assign it to the correct PM to update?

**Comment by josaw1** [comment]
Closed as won't fix.

**Comment by ReneVolkmer** [comment]
@josaw1 why won't fix? This kind of approaching is not very encouraging community in contributing

**Comment by jaredtbates** [comment]
Hi there, we are running into this issue and are wondering why service accounts need to have "real" AAD email addresses. Could someone provide clarity?
