### ISSUE TITLE
Hope that docs described each field (in Header, Lines and Footer) in Receipt Layout Designer will be published

### ISSUE THREAD

**Issue by Tad1011** [MicrosoftDocs/dynamics-365-unified-operations-public#3713]
[Enter feedback here]
We hope that docs described each field (in Header, Lines and Footer) in Receipt Layout Designer will be published. It is inconvenience for the customer because they don't know what effect unless they actually try to use those fields.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07e88dc1-d955-4b9b-9fc3-b948ba111452
* Version Independent ID: dfd4a02e-bac0-e60a-f076-363d8d1fd3c3
* Content: [Set up and design receipt formats - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/receipt-templates-printing)
* Content Source: [articles/commerce/receipt-templates-printing.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/receipt-templates-printing.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @BrianShook
* Microsoft Alias: **brshoo**

**Comment by kfend** [comment]
@Tad1011 - Thank you for the feedback.
@BrianShook - Can you please take a look and consider updating the topic?

**Comment by josaw1** [comment]
Closed as won't fix.
