### ISSUE TITLE
Please adjust sentences to localized label in section "Overview of possible results from the fit analysis"

### ISSUE THREAD

**Issue by DKobayashi-ykgw** [MicrosoftDocs/dynamics-365-unified-operations-public#3714]
In section "overview-of-possible-results-from-the-fit-analysis", please adjust all sentences to localized label. It's a little bit cumbersome to compare warning messages and docs.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: b375bd7e-0a71-3253-e6f9-e7ad4a4bf05f
* Version Independent ID: 18cca7a1-7c0c-76f3-0bbb-73dcb3f34e47
* Content: [計画の最適化フィット分析 - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/ja-jp/dynamics365/supply-chain/master-planning/planning-optimization/planning-optimization-fit-analysis)
* Content Source: [articles/supply-chain/master-planning/planning-optimization/planning-optimization-fit-analysis.md](https://github.com/MicrosoftDocs/Dynamics-365-Operations.ja-jp/blob/live/articles/supply-chain/master-planning/planning-optimization/planning-optimization-fit-analysis.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @ChristianRytt
* Microsoft Alias: **crytt**

**Comment by kamaybac** [comment]
@DKobayashi-ykgw , thank you for letting us know about this issue. I have forwarded your comment to our localization team.

**Comment by vinceno** [comment]
Thx @DKobayashi-ykgw, @kamaybac and @ChristianRytt for getting this issue to us - we're working to get it fixed and will update thread when done - cc @vivimills @rosacek

**Comment by rosacek** [comment]
@DKobayashi-ykgw @kamaybac @ChristianRytt @vivimills @vinceno sorry this has been reviewed and updated. Japanese as well as all other language updates has been published live since Dec 23rd
