### ISSUE TITLE
Missing reference in "Create an invoices list page" section

### ISSUE THREAD

**Issue by gallant-dev** [MicrosoftDocs/dynamics-365-unified-operations-public#3718]
**Create an invoices list page**

9. Go to the account management landing page (My Account) that you created earlier.
10. In the properties pane for the Account invoices tile module, under Links, configure a link to the invoices list page that you just created.
11. Select Save, select Finish editing to check in the page, and then select Publish to publish it.

The above part of these instructions are referencing a module that wasn't added to the account management landing page in the earlier steps. It should probably be added to the earlier steps?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb11a9fe-94ad-02a3-a911-0f58e1cad41d
* Version Independent ID: 87215e08-819f-e66a-2aa0-0ab8d9c8e646
* Content: [Set up a B2B e-commerce site - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/b2b/set-up-b2b-site)
* Content Source: [articles/commerce/b2b/set-up-b2b-site.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/b2b/set-up-b2b-site.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by josaw1** [comment]
Assigned to @anpurush.

**Comment by josaw1** [comment]
Closed as won't fix.
