### ISSUE TITLE
Assigning Application User did not work

### ISSUE THREAD

**Issue by d3fr0g** [MicrosoftDocs/dynamics-365-unified-operations-public#3720]
During "Verify requirements and grant access" point 4 the assignment of Application Users in Dataverse step did not work following the steps. The problem was that the new UI to add the Application users will use the graph _applications_ API which returns AAD Application Objects but the applications are not present as such. They can be retrieved as SPs. The "legacy" page still works or the systemusers API of CRM. There are also 3rd party blog posts which explain legacy creation approach but would be good to follow the docs site from start to end.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df8e9efc-9258-3876-e05f-20d35c907274
* Version Independent ID: 4b5041ec-4a48-0565-e47a-b972e65a6d60
* Content: [System requirements and prerequisites - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/requirements-and-prerequisites)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/requirements-and-prerequisites.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/dual-write/requirements-and-prerequisites.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @NHelgren
* Microsoft Alias: **nhelgren**

**Comment by sericks007** [comment]
@d3fr0g, thank you for providing this feedback.

@NHelgren, please update the topic as appropriate.

**Comment by NHelgren** [comment]
I will review

**Comment by sericks007** [comment]
Bug 647691 has been logged to track this issue.

**Comment by paulliew** [comment]
This has been logged and a work item has been assigned to the PAuth User Sync team.  See ICM Incident-277906449 Details - IcM (microsofticm.com) to
