### ISSUE TITLE
日本語訳の修正 売上認識→収益認識

### ISSUE THREAD

**Issue by hiromichif** [MicrosoftDocs/dynamics-365-unified-operations-public#3722]
[フィードバックをこちらに入力してください]

売上認識ではなく、収益認識が正しいと思います。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 49ee1703-51fa-03cb-cb6c-d13c59ec0dc3
* Version Independent ID: be390b47-7972-c0d5-aa66-ac74ad24473f
* Content: [売上認識の設定 - Finance | Dynamics 365](https://docs.microsoft.com/ja-jp/dynamics365/finance/accounts-receivable/revenue-recognition-setup)
* Content Source: [articles/finance/accounts-receivable/revenue-recognition-setup.md](https://github.com/MicrosoftDocs/Dynamics-365-Operations.ja-jp/blob/live/articles/finance/accounts-receivable/revenue-recognition-setup.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @kweekley
* Microsoft Alias: **kweekley**

**Comment by sericks007** [comment]
@hiromichif, thank you for providing this feedback.

@kweekley, please review and update the content, as needed.  I believe the feedback says, "I think the revenue recognition is correct, not the sales recognition."

**Comment by sericks007** [comment]
Bug 647692 has been logged to track this issue.

**Comment by vivimills** [comment]
Submitted [Translation Feedback](https://dev.azure.com/bagie/Production/_workitems/edit/60971/) to partner LSP. Waiting for evaluation from the linguists.

**Comment by vivimills** [comment]
The ja-JP linguists evaluated this issue and categorized it as a stylistic preference. They have suggested keeping the term as updating means extensive changes to the localized material.
