### ISSUE TITLE
Documentation incorrect for getting recurring data job errors through REST API?

### ISSUE THREAD

**Issue by Asgardi** [MicrosoftDocs/dynamics-365-unified-operations-public#3724]
The documentation suggest

POST /data/DataManagementDefinitionGroups/Microsoft.Dynamics.DataEntities.GetExecutionErrors
BODY
{"executionId":"<executionId>"}

to get execution errors for recurring data job execution, but the documentation does not tell where the "executionId" comes from or how to get it? Or what it even is? All other APIs seem to work with "messageId" and that seem not to work for this API call.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01b2cd6b-f885-7461-fbdf-cf81f9e50d86
* Version Independent ID: 8df7a6ae-67db-5d29-fb6a-0820704ff3ef
* Content: [Recurring integrations - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/recurring-integrations)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/recurring-integrations.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/recurring-integrations.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Peakerbl
* Microsoft Alias: **peakerbl**

**Comment by sericks007** [comment]
@Asgardi, thank you for providing this feedback.

@Peakerbl, please review and update the content, as needed.

**Comment by sericks007** [comment]
Bug 647693 has been logged to track this issue.

**Comment by kfend** [comment]
Thank you for letting us know. We have done more investigating, and we will be making an update to the functionality based on this feedback.
