### ISSUE TITLE
Typo under depreciation methods

### ISSUE THREAD

**Issue by DaConfusedSoul** [MicrosoftDocs/dynamics-365-unified-operations-public#3728]
There is a typo in the straight line service life. There is a 0 typed in it which is wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed925d33-ef75-a817-28f2-b5ba0694156c
* Version Independent ID: 0c159e1b-39c6-7e2e-9aea-567aae20bc22
* Content: [Depreciation methods and conventions - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/fixed-assets/depreciation-methods-conventions)
* Content Source: [articles/finance/fixed-assets/depreciation-methods-conventions.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/fixed-assets/depreciation-methods-conventions.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @moaamer
* Microsoft Alias: **moaamer**

**Comment by sericks007** [comment]
@DaConfusedSoul, thank you for pointing this out.  I have removed that 0 -- the updated content will be published later today.  Thanks!
