### ISSUE TITLE
not "モノシリック"

### ISSUE THREAD

**Issue by rioriost** [MicrosoftDocs/dynamics-365-unified-operations-public#3729]
[フィードバックをこちらに入力してください]
「 モノシリック コード ベース」
ではなく
「モノリシック コードベース」
です。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 95ff4e46-37be-93dc-9e69-07aec039a44d
* Version Independent ID: ec6d8af1-6598-94a9-006e-0a52663325a7
* Content: [ローカライズ モデルの分類 - Finance & Operations | Dynamics 365](https://docs.microsoft.com/ja-jp/dynamics365/fin-ops-core/dev-itpro/lcs-solutions/separate-localization-models)
* Content Source: [articles/fin-ops-core/dev-itpro/lcs-solutions/separate-localization-models.md](https://github.com/MicrosoftDocs/Dynamics-365-Operations.ja-jp/blob/live/articles/fin-ops-core/dev-itpro/lcs-solutions/separate-localization-models.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @ShylaThompson
* Microsoft Alias: **filatovm**

**Comment by sericks007** [comment]
@rioriost, thank you for providing this feedback.  We are investigating.

**Comment by vinceno** [comment]
@rioriost @sericks007 thx both., the holiday period may add some delay but we will get this adjusted - thx again - CC @vivimills

**Comment by sericks007** [comment]
Bug 647724 has been logged to track this issue.

**Comment by josaw1** [comment]
Closed as won't fix.
