### ISSUE TITLE
WMS User

### ISSUE THREAD

**Issue by Chybes** [MicrosoftDocs/dynamics-365-unified-operations-public#3730]
on my environment 10.0.22 (10.0.995.51) it works only with the administrator user ID and not with a user dedicated to the WMS application

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 24ad63f4-807c-fc88-58b6-33514bd034d0
* Version Independent ID: d727eb59-1162-f195-031a-5400301c8e5b
* Content: [Installer et connecter l’application d’entrepôt - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/fr-fr/dynamics365/supply-chain/warehousing/install-configure-warehousing-app)
* Content Source: [articles/supply-chain/warehousing/install-configure-warehousing-app.md](https://github.com/MicrosoftDocs/Dynamics-365-Operations.fr-fr/blob/live/articles/supply-chain/warehousing/install-configure-warehousing-app.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @MarkusFogelberg
* Microsoft Alias: **mafoge**

**Comment by sericks007** [comment]
@Chybes, thanks for providing this feedback.

@MarkusFogelberg, please review and update the content, as needed.

**Comment by sericks007** [comment]
@Mirzaab, please review and update the content, as needed.

**Comment by sericks007** [comment]
Bug 647925 has been logged to track this issue.

**Comment by MichaelFruergaardPontoppidan** [comment]
The documentation is correct.  It is not clear why this only works for an administrator for the user reporting this problem.  Either there is a product bug, or the user's environment has other issues. The documentation is correct.
