### ISSUE TITLE
Removal of header/lines proxy buttons

### ISSUE THREAD

**Issue by hussainih** [MicrosoftDocs/dynamics-365-unified-operations-public#3732]
In Update 47, for Pending vendor invoices (VendEditInvoice) the restyled radio buttons are gone when I enable the feature but I do not see any "header/lines" native tabs. Just for confirmation I tried to find these tab in purchase order (PurchTable form) and they appear there. I have issue only with the Pending invoice form. I tried deleting the Usage data for the user as well but no benefit.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c235e8a-d3b6-5ebd-3822-f56a42899a2c
* Version Independent ID: 8b4812bf-bcf9-03dd-211e-09f7f1b58832
* Content: [Details Transaction form pattern - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/user-interface/details-transaction-form-pattern)
* Content Source: [articles/fin-ops-core/dev-itpro/user-interface/details-transaction-form-pattern.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/user-interface/details-transaction-form-pattern.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by sericks007** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
