### ISSUE TITLE
This instruction must be supported with pictures.

### ISSUE THREAD

**Issue by okayakdeniz** [MicrosoftDocs/dynamics-365-unified-operations-public#3734]
[Enter feedback here]
We could not understand this document's steps. Because instructions didn't define clearly. For Instance, "Go to your Customer Insights instance and search for the name of the application created above (in this example, "CI_Access_name")." 
The Article says, Please search & find out the "Application name" in Customer Insights. The question is "where?" There is no search place for "Application name".  we found the right place, in the **security part**. But, there was no guidance for this. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5e95ccb-3c5a-278c-222a-3fa4897db843
* Version Independent ID: b21a2eb2-45fa-7693-4e53-2e6f398461cc
* Content: [Clienteling overview - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/clienteling-overview)
* Content Source: [articles/commerce/clienteling-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/clienteling-overview.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @bebeale
* Microsoft Alias: **shajain**

**Comment by sericks007** [comment]
@okayakdeniz, thank you for providing this feedback.

@bebeale, please clarify this content to address the feedback.

**Comment by bebeale** [comment]
This should be assigned to: shajain.


Cheers,
Benita
________________________________

**Comment by sericks007** [comment]
Bug 647927 has been logged to track this issue.

**Comment by josaw1** [comment]
Closed as won't fix.
