### ISSUE TITLE
The xml files on the prerequisites section cannot be downloaded

### ISSUE THREAD

**Issue by hendyb** [MicrosoftDocs/dynamics-365-unified-operations-public#3735]
[Enter feedback here]
The xml files on the prerequisites section cannot be downloaded as they are referencing to the mbs.microsoft.com that is no longer available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 402b49a9-0a90-885a-c4a6-0df70feac573
* Version Independent ID: 0c40e0e4-97b4-4410-6b3f-e0362eef7fc3
* Content: [Support parameterized calls of ER data sources of the Calculated field type - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/er-calculated-field-type?toc=/dynamics365/commerce/toc.json)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/er-calculated-field-type.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/analytics/er-calculated-field-type.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @NickSelin
* Microsoft Alias: **nselin**

**Comment by NickSelin** [comment]
Hello [hendyb](https://github.com/hendyb),
Thank you for reporting this issue. It has been registered as a documentation issue. Please, use this [link](https://fix.lcs.dynamics.com/Issue/Details/?bugId=646247&dbType=3) to trace the progress of its fixing. Meanwhile, use the files from the attached archive to complete the steps of the referred example.
Best regards,
Nick Selin

[Support parameterized calls of ER data sources of CALCULATED FIELD type.zip](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/files/7779194/Support.parameterized.calls.of.ER.data.sources.of.CALCULATED.FIELD.type.zip)
