### ISSUE TITLE
Add reference to additional steps  for printing QR code on OPOS printers

### ISSUE THREAD

**Issue by 5fq** [MicrosoftDocs/dynamics-365-unified-operations-public#3736]
It will be good if you can add a reference to the below article so that users will be clear about the piece of code they have to include to get this working on the OPOS printers. Other the printing will fail with error "ExceptionMessage: 'OPOS printer failed to execute 'PrintMemoryBitmap' with error '114', extended error code - 0."

https://docs.microsoft.com/en-us/dynamics365/commerce/localizations/ind-generate-qr-code-print-receipt#printing-qr-code-images-on-opos-printers

Ref:  Case 2112280060001189

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa377324-5397-4669-2ed2-de02c8891396
* Version Independent ID: fa377324-5397-4669-2ed2-de02c8891396
* Content: [Generate QR codes and print them on receipts for Saudi Arabia - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/localizations/emea-sau-qr-code)
* Content Source: [articles/commerce/localizations/emea-sau-qr-code.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/localizations/emea-sau-qr-code.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @EvgenyPopovMBS
* Microsoft Alias: **epopov**

**Comment by tonyafehr** [comment]
@5fq, thank you for the feedback. @EvgenyPopovMBS, please review and consider making updates to this topic.

**Comment by tonyafehr** [comment]
Bug 649117 has been logged to track this issue.

**Comment by EvgenyPopovMBS** [comment]
The documentation has been updated: [Print QR code images on OPOS printers](https://docs.microsoft.com/en-us/dynamics365/commerce/localizations/emea-sau-qr-code?tabs=commerce-10-0-25#print-qr-code-images-on-opos-printers).
