### ISSUE TITLE
Major releases

### ISSUE THREAD

**Issue by e9325827** [MicrosoftDocs/dynamics-365-unified-operations-public#3737]
The page mentions major releases, I find no (recent) information from Microsoft which releases are considered major and which not?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51e63496-19e3-182e-c19d-027a0a5f6acf
* Version Independent ID: c8a51a1e-25e8-fbe3-4580-baca9046b7b0
* Content: [Feature management overview - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/feature-management/feature-management-overview#on-by-default-features-optional)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/feature-management/feature-management-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/feature-management/feature-management-overview.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Peakerbl
* Microsoft Alias: **peakerbl**

**Comment by sericks007** [comment]
@e9325827, thank you for providing this feedback.

@Peakerbl, please clarify what is meant by "major releases".

**Comment by sericks007** [comment]
We've updated the [Service update availability](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/public-preview-releases) content to indicate the major releases.
