### ISSUE TITLE
Mandatory, not Released is the final state for features.

### ISSUE THREAD

**Issue by e9325827** [MicrosoftDocs/dynamics-365-unified-operations-public#3738]
This page has the sentence, Released is the final state for features.
This is wrong, as Mandatory is the final state for features.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51e63496-19e3-182e-c19d-027a0a5f6acf
* Version Independent ID: c8a51a1e-25e8-fbe3-4580-baca9046b7b0
* Content: [Feature management overview - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/feature-management/feature-management-overview#on-by-default-features-optional)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/feature-management/feature-management-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/feature-management/feature-management-overview.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Peakerbl
* Microsoft Alias: **peakerbl**

**Comment by sericks007** [comment]
@e9325827, thank you for providing this feedback.

@Peakerbl, please update the topic, as noted.
