### ISSUE TITLE
Cannot find the IncomingDocumentToLearnHowToHandleOptionalAttributes.xml file

### ISSUE THREAD

**Issue by lanjunmm** [MicrosoftDocs/dynamics-365-unified-operations-public#3739]
[Enter feedback here]
The file IncomingDocumentToLearnHowToHandleOptionalAttributes.xml doesn't exist in the dowloaded Zip file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7c69e2a-5d2c-fb3b-970b-13e93b42fc6e
* Version Independent ID: 1a65e651-a70a-d993-88db-c4d14d40d6df
* Content: [Import files in XML format with optional attributes - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/rcs-optional-attributes?toc=/dynamics365/finance/toc.json)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/rcs-optional-attributes.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/analytics/rcs-optional-attributes.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @NickSelin
* Microsoft Alias: **nselin**

**Comment by NickSelin** [comment]
Hello [lanjunmm](https://github.com/lanjunmm),
Thank you for reporting this issue. It has been registered as a documentation defect. Please, use this [link](https://fix.lcs.dynamics.com/Issue/Details?bugId=646832&dbType=3) to trace the progress of its fixing. Meanwhile, use the following [link](https://download.microsoft.com/download/0/4/e/04e13839-e423-442b-a6c2-dd35b1045c2d/Dynamics%20365%20for%20Finance%20and%20Operations%208.1%20Electronic%20reporting%20task%20guides.zip) to get the missing file.
Best regards,
Nick Selin
