### ISSUE TITLE
Links to Odata examples

### ISSUE THREAD

**Issue by timschwallie** [MicrosoftDocs/dynamics-365-unified-operations-public#374]
The links to Odata examples appear to go to WCF pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64b023ab-59fb-87d9-d935-d60d0e9e4139
* Version Independent ID: 10120c96-a72d-60fd-63ff-db9f77e05817
* Content: [Open Data Protocol (OData) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/odata)
* Content Source: [articles/dev-itpro/data-entities/odata.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/odata.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by sericks007** [comment]
Thanks for letting us know.  @Sunil-Garg, can you please review to see if the links to to the intended pages?

**Comment by timschwallie** [comment]
OData: Data access for the web, the cloud, mobile devices, and more | http://msdn.microsoft.com/en-us/data/hh237663.aspx
-- | --
OData through examples | http://msdn.microsoft.com/en-us/library/ff478141.aspx

these links go to WCF pages. I don't know the correct links so that they go to Odata pages.

**Comment by vishram2997** [comment]
I am getting time out error when sending more than 500 line in journalEntity. Is there any timeout setting for Odata.

**Comment by prodev42** [comment]
OData: Data access for the web, the cloud, mobile devices, and more | http://msdn.microsoft.com/en-us/data/hh237663.aspx
-- | --
OData through examples | http://msdn.microsoft.com/en-us/library/ff478141.aspx

Both go to WCF, still not correct.

**Comment by tonyafehr** [comment]
This link will be published later today. Thank you!
