### ISSUE TITLE
Retail Channel not Commerce Channel

### ISSUE THREAD

**Issue by andyNewnham** [MicrosoftDocs/dynamics-365-unified-operations-public#3740]
The operating unit type is still labelled in D365 as a 'Retail Channel'. Please update (either docs or in the application!) to ensure consistency. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bc0b18d-10eb-b4f6-5b38-3668e737c726
* Version Independent ID: 767da595-baa2-6216-85e0-ed44267117a8
* Content: [Organizations and organizational hierarchies overview - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/organization-administration/organizations-organizational-hierarchies)
* Content Source: [articles/fin-ops-core/fin-ops/organization-administration/organizations-organizational-hierarchies.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/organization-administration/organizations-organizational-hierarchies.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @sericks007
* Microsoft Alias: **sericks**

**Comment by andyNewnham** [comment]
Also, 'Online Marketplace' no longer exists in Commerce as a type of retail channel. It should really mention call center as the other channel type.

**Comment by tonyafehr** [comment]
@andyNewnham, thanks for the feedback. @sericks007, please review.

**Comment by sericks007** [comment]
Thanks for noticing this!  I've updated the content, which will be published later today.
