### ISSUE TITLE
Update to include new POS operations

### ISSUE THREAD

**Issue by andyNewnham** [MicrosoftDocs/dynamics-365-unified-operations-public#3741]
This page is used regularly by all consultants to validate which operations are available when offline and to confirm where/how the operations are used. It does not seem to have been updated for quite a while and a lot of new operations have been added. Can they be added to the list please.

Missing operations include:
133 | Add warranty
140 | Add line charges
144 | Add warranty to existing transaction
215 | Cash out gift card
645 | View all discounts
646 | View available discounts
658 | Change pickup lines
712 | View customers in client book
713 | View customers from store client books
714 | Add customer to client book
715 | Remove customers from client book
716 | Reassign customers to a client book
717 | Health check
806 | Stock adjustment
807 | Stock movement
1220 | Manage safes
1221 | Void suspended transactions
1300 | Skip fiscal registration
1301 | Mark fiscal event registered
1302 | Complete fiscal registration process
1303 | Skip health check error
1304 | Postpone fiscal registration
1400 | Task management

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5d9e89d-0605-6ebe-3645-7b94b6ea3ca5
* Version Independent ID: 9a8b3159-4682-01a3-1052-be84064ffbc0
* Content: [Online and offline point of sale (POS) operations - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/pos-operations)
* Content Source: [articles/commerce/pos-operations.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/pos-operations.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @jblucher
* Microsoft Alias: **jeffbl**

**Comment by tonyafehr** [comment]
@andyNewnham, thank you for the detailed feedback. @jblucher, please review and consider making updates.
