### ISSUE TITLE
menu reference is wrong

### ISSUE THREAD

**Issue by hhainesms** [MicrosoftDocs/dynamics-365-unified-operations-public#3742]
The menu reference on this document is incorrect - there is no "openID providers" menu option in Commerce shared parameters - the correct menu option is "Identity Providers"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 803d3e98-0d4d-ccfd-dccb-d3686d497fa7
* Version Independent ID: b8ea5de9-6c54-9adb-9291-8d80c40447a7
* Content: [Configure authentication providers - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/configure-authentication-providers)
* Content Source: [articles/commerce/dev-itpro/configure-authentication-providers.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/configure-authentication-providers.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **meeram**

**Comment by tonyafehr** [comment]
@josaw1, can you look into this. Thanks!

**Comment by josaw1** [comment]
Fix will be published today.
