### ISSUE TITLE
Debug Modern POS by using Visual Studio 2017

### ISSUE THREAD

**Issue by cekrice** [MicrosoftDocs/dynamics-365-unified-operations-public#3743]
Hi,

Item 2 under this heading "Install the Universal Windows Platform (UWP) app by selecting the shortcut on the desktop." is not clear. What is this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d25974f-661e-2b24-2ac6-795c40c1047e
* Version Independent ID: bb01166a-2998-0755-15f1-02872d18786b
* Content: [Debug POS extensions - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/pos-extension/debug-pos-extension)
* Content Source: [articles/commerce/dev-itpro/pos-extension/debug-pos-extension.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/pos-extension/debug-pos-extension.md)
* Service: **dynamics-365-commerce**
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by sericks007** [comment]
@cekrice, thank you for providing this feedback.

@mugunthanm, please update the content as requested.

**Comment by mugunthanm** [comment]
Thanks for the update, updated the doc:
https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/pull/3749
