### ISSUE TITLE
Create a Modern POS extension package

### ISSUE THREAD

**Issue by cekrice** [MicrosoftDocs/dynamics-365-unified-operations-public#3744]
Hi,

In Item 5 under this heading, Adding reference should be opposite, shouldn't be?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52282adf-3347-d738-9aa7-412a1fe89b7a
* Version Independent ID: e28a330c-28f0-9bc4-2b59-13892d774907
* Content: [Create a Modern POS extension package - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/pos-extension/mpos-extension-packaging)
* Content Source: [articles/commerce/dev-itpro/pos-extension/mpos-extension-packaging.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/pos-extension/mpos-extension-packaging.md)
* Service: **dynamics-365-commerce**
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by sericks007** [comment]
@cekrice, thank you for providing this feedback.

@mugunthanm, please update this content to address this feedback.

**Comment by mugunthanm** [comment]
Thanks for the feedback, updated the doc.
https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/pull/3748
