### ISSUE TITLE
Step 10 Shared Library File Names Update Needed

### ISSUE THREAD

**Issue by aaronstackpole** [MicrosoftDocs/dynamics-365-unified-operations-public#3745]
In LCS, go to the Shared asset library, select Retail Self-service package as the asset type, and find the file that ends with Commerce Scale Unit (PREVIEW). Be sure to select the version for the release that you require (for example, version 10.0.22 or 10.0.23). Download the file, and put it in the Download folder in the Scale Unit GitHub repo that you cloned or downloaded in the previous step

This text needs to be updated, the packages in the Asset Library are now named "Commerce Scale Unit" and "Commerce Scale Unit (SEALED)". Please provide details on which package should be used. My assumption is that one is for the local CSU and one is for the IIS CSU, but the description of the package, nor the documentation clarifies. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8844b7a4-22c9-bb5b-0af5-e12b2734c3d8
* Version Independent ID: c5d12c3a-9d9f-0ab9-3bba-28228238ffad
* Content: [Set up a local development environment - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/setup-local-dev-env)
* Content Source: [articles/commerce/dev-itpro/setup-local-dev-env.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/setup-local-dev-env.md)
* Service: **dynamics-365-commerce**
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by tonyafehr** [comment]
@aaronstackpole, thanks for the feedback. @mugunthanm, please review and consider making updates.

**Comment by mugunthanm** [comment]
Thanks for the feedback, updated the document. Please use the Commerce Scale Unit (SEALED).
https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/pull/3747
