### ISSUE TITLE
Add requirement for Carry Out Mode of Delivery as pre-requisite

### ISSUE THREAD

**Issue by 5fq** [MicrosoftDocs/dynamics-365-unified-operations-public#3750]
The QR code will only work if the Carry out the mode of delivery is configured in Commerce Parameters. Please add this as a mandatory requirement.

Ref: MS Support ticket #2201040060001383

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa377324-5397-4669-2ed2-de02c8891396
* Version Independent ID: fa377324-5397-4669-2ed2-de02c8891396
* Content: [Generate QR codes and print them on receipts for Saudi Arabia - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/localizations/emea-sau-qr-code)
* Content Source: [articles/commerce/localizations/emea-sau-qr-code.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/localizations/emea-sau-qr-code.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @EvgenyPopovMBS
* Microsoft Alias: **epopov**

**Comment by tonyafehr** [comment]
@EvgenyPopovMBS, please review.

**Comment by EvgenyPopovMBS** [comment]
Thank you for the feedback. This product issue is fixed in the monthly update 10.0.25, that is, starting from 10.0.25, it is not required to specify Carry-out delivery mode in Commerce parameters to make QR codes for Saudi Arabia working.
