### ISSUE TITLE
Adjust posting date automatically during invoice posting.

### ISSUE THREAD

**Issue by D365AndyHunter** [MicrosoftDocs/dynamics-365-unified-operations-public#3751]
Was excited to see this feature added in release 10.0.23 however having enabled in feature management and tested have found that it is actually updating the invoice date and not the posting date
The invoice date should remain as detailed on the suppliers invoice as this is important for tax and sox compliance
The posting date remained as originally entered and was not updated to first day of next period as specified in the parameters

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd4cc58-4617-78b2-8807-573f4b5a81fb
* Version Independent ID: 5c64dde6-0cdc-804e-70de-d770c8e3970d
* Content: [Vendor invoice dates - Finance | Dynamics 365](https://docs.microsoft.com/en-gb/dynamics365/finance/accounts-payable/vendor-invoice-dates)
* Content Source: [articles/finance/accounts-payable/vendor-invoice-dates.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/accounts-payable/vendor-invoice-dates.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @sunfzam
* Microsoft Alias: **shpandey**

**Comment by tonyafehr** [comment]
@D365AndyHunter, thanks for the feedback. If you need immediate assistance, consider one of these options: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community. 

@sunfzam, please review and consider making updates to this topic.
