### ISSUE TITLE
Personalization Required option is only working for particular Master (ie. for single item field)

### ISSUE THREAD

**Issue by lokesh9769610709** [MicrosoftDocs/dynamics-365-unified-operations-public#3753]
Previously this feature of Personalizing Required Field was working fine. Id one of the field is make mandatory on Item master that particular field is mandatory for all the item and provides Warning but now after latest update system is not behaving as expected. now if any field is set to required it is mandatory for that particular item.

**Comment by tonyafehr** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
