### ISSUE TITLE
Create BOMs in Product information management instead of Inventory management

### ISSUE THREAD

**Issue by ryanlish** [MicrosoftDocs/dynamics-365-unified-operations-public#3754]
Should the Inventory management be Product information management in "Create bills of materials (BOMs) and BOM versions in Inventory management."?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90a70666-74c8-cb14-f655-2ea665bd8b65
* Version Independent ID: 499e83f4-52c2-0292-b3d1-92dc69e957e3
* Content: [Production setup requirements - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/production-control/production-set-up-requirements)
* Content Source: [articles/supply-chain/production-control/production-set-up-requirements.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/production-control/production-set-up-requirements.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @johanhoffmann
* Microsoft Alias: **johanho**

**Comment by tonyafehr** [comment]
@ryanlish, thanks for the feedback. @johanhoffmann, please review and consider updating this topic.

**Comment by tonyafehr** [comment]
Bug 649124 logged to track this issue.

**Comment by tonyafehr** [comment]
Appropriate updates have been made to this topic and will be live later today.
