### ISSUE TITLE
storage-account-name secret

### ISSUE THREAD

**Issue by stevej-arbela** [MicrosoftDocs/dynamics-365-unified-operations-public#3756]
Hi Team,

When I set the value of the storage account secret to the storage account name, I always encounter an error. After some digging it appears that the setup script is expecting a connection string. I then create a key vault secret named "storage-account-connection" with a value of the storage account's primary connection string, and this works as expected. If this can be reviewed, please update the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c84e15d4-bcac-038a-2b1e-8c456ee25bd9
* Version Independent ID: 478b5f33-f745-1df2-8fe0-da9e64233165
* Content: [Install Export to Azure Data Lake add-in - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/configure-export-data-lake#addsecrets)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/configure-export-data-lake.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/configure-export-data-lake.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by josaw1** [comment]
Thanks for your feedback. @sericks007 can you please take a look?

**Comment by sericks007** [comment]
@MilindaV2, please update the documentation based on this feedback.

**Comment by josaw1** [comment]
BUG 653382 created to track.

**Comment by josaw1** [comment]
Closed as won't fix.
