### ISSUE TITLE
Guidance on virtual data entities versus Dual Write missing

### ISSUE THREAD

**Issue by KheeChan** [MicrosoftDocs/dynamics-365-unified-operations-public#3757]
The link https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/power-platform/faq?source=docs#is-there-guidance-on-when-to-use-a-virtual-entity-and-when-to-use-dual-write does not provide any content on guidance on when to use virtual data entities versus Dual Write.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 631342c7-d7a0-1fdf-1422-215fdf4b35b1
* Version Independent ID: bbe5a482-10f8-eb68-c1ab-c12e152d313a
* Content: [Finance and Operations virtual entities FAQ - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/power-platform/faq?source=docs)
* Content Source: [articles/fin-ops-core/dev-itpro/power-platform/faq.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/power-platform/faq.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by josaw1** [comment]
Thank you for your feedback. @Sunil-Garg can you please review?

**Comment by sericks007** [comment]
@jaredha, can you please review this feedback and update the content, if necessary.

**Comment by josaw1** [comment]
BUG 653383 created to track.

**Comment by josaw1** [comment]
Closed as won't fix.
