### ISSUE TITLE
What are the FULL constraints for naming Data Entity field names?

### ISSUE THREAD

**Issue by ronsonntag54** [MicrosoftDocs/dynamics-365-unified-operations-public#3759]
[Enter feedback here]
The page indicates certain pre and postfixes to avoid and also states not to use underscores in field names. My question is: What about other punctuation? Can I have a field name "TPayor.Description" or "TPayor:Description", etc. What punctuation is allowed and not allowed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 396b1d1e-59d9-18e2-f10f-258ca6ddd01f
* Version Independent ID: ccf80ee0-9132-5bee-a3cf-9f9e218fd728
* Content: [Design principles and best practices for data entities - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/design-best-practices)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/design-best-practices.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/dev-tools/design-best-practices.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @Peakerbl
* Microsoft Alias: **peakerbl**

**Comment by josaw1** [comment]
Thank you for your feedback. @Peakerbl can you please review?

**Comment by josaw1** [comment]
BUG 653388 created to track.

**Comment by josaw1** [comment]
Closed as won't fix.
