### ISSUE TITLE
FIFO without the Include physical value option - 5a, 5b and diagram incorrect / not matching

### ISSUE THREAD

**Issue by blangero** [MicrosoftDocs/dynamics-365-unified-operations-public#3760]
[Enter feedback here]
FIFO without the Include physical value option - 5a, 5b and diagram incorrect / not matching

I know that we change cost in 5b from 20 to 15 in a history fix, but the fix should also be applied on 5a
Besides that, the initial cost - 20, should be calculated based on the assumption that 2a and 2b are with qty = 1 and unit cost = 20 - which can be found in other segments of this page ( with include physical value option and marking ).
The diagram is not matching the statements, which is really confusing especially for beginners.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86ece8c8-fcea-0e14-9bb2-0544b62b17c1
* Version Independent ID: b2e81fea-7a8a-0f06-c760-b6abbbd07cea
* Content: [FIFO with physical value and marking - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/cost-management/fifo-physical-value-marking)
* Content Source: [articles/supply-chain/cost-management/fifo-physical-value-marking.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/cost-management/fifo-physical-value-marking.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @AndersGirke
* Microsoft Alias: **aevengir**

**Comment by josaw1** [comment]
Thank you for your feedback. @AndersEvenGirke can you please review?

**Comment by josaw1** [comment]
BUG 653389 created to track.

**Comment by kamaybac** [comment]
@blangero , I believe we have fixed this issue. We corrected the diagram and the numbers for item 5a. However, it looks like 2a and 2b should indeed be qty=1, cost=20, which matches the diagram, even though those values are different in the other examples.

**Comment by blangero** [comment]
Thank you kamaybac for the update, I think it is already good enough!
