### ISSUE TITLE
Certificate renewal is not every 90 days but every 60 days. 

### ISSUE THREAD

**Issue by FrankDahl** [MicrosoftDocs/dynamics-365-unified-operations-public#3764]
This page (https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/perf-test/perfsdk-multi-user-testing) mention that self-service environment will see their certificate update by rotation about every 90 days. This is not accurate the timing between the automated renewal of certificates is about every 60 days. You may confirm this with the team, but I have done so already and believe is is safe to change the mentioned 90 days to 60 days.

This documentation page is owned by the performance team as part of PerfSDK documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0b04519-4802-eaaa-c5ed-b13e8979d36d
* Version Independent ID: a4ebe802-e7fd-fd99-00a1-aa0ebf8fcb48
* Content: [Run multi-user testing by using the Performance SDK - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/perf-test/perfsdk-multi-user-testing)
* Content Source: [articles/fin-ops-core/dev-itpro/perf-test/perfsdk-multi-user-testing.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/perf-test/perfsdk-multi-user-testing.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @kennysaelen
* Microsoft Alias: **kesaelen**

**Comment by kamaybac** [comment]
@FrankDahl , thanks for letting us know. 

@tonyafehr, Frank is PM for SCM. Looks like he has already verified his input, so I think it's safe to implement it.

**Comment by kamaybac** [comment]
@tonyafehr , I went ahead and implemented this as Frank suggested and closed this issue.
