### ISSUE TITLE
Issue with Subcontracted transfer activities

### ISSUE THREAD

**Issue by amdz81** [MicrosoftDocs/dynamics-365-unified-operations-public#3766]
[Enter feedback here]
There is an issue with the documentation as two very different processes have the same description:

See the specific session

Subcontracted transfer activities
A transfer activity is configured as a subcontracted activity, depending on the Freighted by setting of the transfer activity. The following options are available:

Shipper – The activity is subcontracted if the transfer from the warehouse is managed by a vendor (as defined by a property of the warehouse). All selected purchase agreements for services must have the same vendor ID as the warehouse.
Recipient – The activity is subcontracted if the transfer to the warehouse is managed by a vendor (as defined by a property of the warehouse). All selected purchase agreements for services must have the same vendor ID as the warehouse.

Seems that even one only of the two actions is performed by a 3rd party a vendor is always involved. 

I would welcome a correction in this
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b500115f-6264-143e-6fa8-fc3cbe1cb1f1
* Version Independent ID: 6b3b39be-5690-99f9-80bf-24d488fff81a
* Content: [Activity-based subcontracting - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/production-control/activity-based-subcontracting)
* Content Source: [articles/supply-chain/production-control/activity-based-subcontracting.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/production-control/activity-based-subcontracting.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @johanhoffmann
* Microsoft Alias: **johanho**

**Comment by kamaybac** [comment]
@amdz81 , thank you for contacting us regarding this help topic. I have passed your comment on for consideration.

**Comment by kamaybac** [comment]
Bug 662870 created to track this issue.

**Comment by josaw1** [comment]
Closed as won't fix.
