### ISSUE TITLE
Section details missing on Set up contact information for a customer

### ISSUE THREAD

**Issue by KristianNyholm** [MicrosoftDocs/dynamics-365-unified-operations-public#3767]
Hi,
The section on "Set up contact information for a customer" appears to missing guidelines/instruction on how to set up contact information.

/Kristian
[Enter feedback here]
![GitHub - OIOUBL - customer accounts section missing](https://user-images.githubusercontent.com/61979647/149923770-1e627d64-4541-4403-a455-7e154fd97abf.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ae3f221-94ae-4d51-967e-3ac32adeec29
* Version Independent ID: f77a6f33-9e10-bb07-51f4-a18ead06c3db
* Content: [Set up customer accounts for OIOUBL electronic invoicing - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/tasks/set-up-customer-accounts-oioubl-electronic-invoicing)
* Content Source: [articles/finance/localizations/tasks/set-up-customer-accounts-oioubl-electronic-invoicing.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/tasks/set-up-customer-accounts-oioubl-electronic-invoicing.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @mrolecki
* Microsoft Alias: **mrolecki**

**Comment by kamaybac** [comment]
@KristianNyholm  , thank you for contacting us regarding this help topic. I have passed your comment on for consideration.

**Comment by mrolecki** [comment]
@ilkond , please review this reported issue

**Comment by ilkond** [comment]
@mrolecki, @kamaybac, @KristianNyholm, the recommendation is to use the following new article for Danish OIOUBL e-invoices: https://docs.microsoft.com/en-gb/dynamics365/finance/localizations/emea-dnk-e-invoices.

The mentioned "buggy" article will be discontinued with a couple of related article in the scope of this Content Deliverable: https://msdyneng.visualstudio.com/FinOps/_queries/edit/652953/?action=new&triage=true

**Comment by KristianNyholm** [comment]
Hi all,
Thanks for the update. The information currently available from the “old” article is still relevant, and I don’t see that the “new” article describes how the customer account should be setup (incl. the missing “Set up contact information for a customer) 😉
Cheers
Kristian Nyholm

**Comment by ilkond** [comment]
@mrolecki, @kamaybac, @KristianNyholm, The new article contains all the required steps for Danish electronic invoices (OIOUBL), Including customer account: https://docs.microsoft.com/en-gb/dynamics365/finance/localizations/emea-dnk-e-invoices#configure-customer-parameters
Customer contacts has no DK specifics and is a part of standard functionality. It also mentioned in the new article that customer contacts must be defined in advance:
 
![image](https://user-images.githubusercontent.com/27193524/150766179-e4dc9311-265c-454f-93a9-0dbef7b7713c.png)

**Comment by kamaybac** [comment]
The "buggy" article for which this issue applies has been replaced with a link to the updated version, as suggested in this conversation thread. Therefore, I am closing this issue.
