### ISSUE TITLE
Page not in TOC

### ISSUE THREAD

**Issue by kamaybac** [MicrosoftDocs/dynamics-365-unified-operations-public#3769]
This page isn't in the table of contents, so it's hard to find. Is that the intention?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 715be324-c37c-b327-5ca5-724003813f01
* Version Independent ID: 715be324-c37c-b327-5ca5-724003813f01
* Content: [Separated Dual-write Application Orchestration package - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/separated-solutions#dual-write-application-core)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/separated-solutions.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/dual-write/separated-solutions.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @RamaKrishnamoorthy
* Microsoft Alias: **ramasri**

**Comment by RamaKrishnamoorthy** [comment]
Looks like TOC is a missing piece. Here is how it is placed on the home page.
Hi @Tonya ***@***.***> can you please add the page to the TOC?

***@***.***

Thank you,
Rama.

From: Karl Maybach ***@***.***>
Sent: Wednesday, January 19, 2022 12:53 AM
To: MicrosoftDocs/dynamics-365-unified-operations-public ***@***.***>
Cc: Rama Krishnamoorthy ***@***.***>; Mention ***@***.***>
Subject: [MicrosoftDocs/dynamics-365-unified-operations-public] Page not in TOC (Issue #3769)


This page isn't in the table of contents, so it's hard to find. Is that the intention?

________________________________
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

  *   ID: 715be324-c37c-b327-5ca5-724003813f01
  *   Version Independent ID: 715be324-c37c-b327-5ca5-724003813f01
  *   Content: Separated Dual-write Application Orchestration package - Finance & Operations | Dynamics 365<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fdynamics365%2Ffin-ops-core%2Fdev-itpro%2Fdata-entities%2Fdual-write%2Fseparated-solutions%23dual-write-application-core&data=04%7C01%7Cramasri%40microsoft.com%7Cf70b862410c54490ebe108d9db2922ff%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637781792005110794%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=1XeOa6%2FV78cL0tF78Wo8wu6eibVqH5hpA17mXQH0iiI%3D&reserved=0>
  *   Content Source: articles/fin-ops-core/dev-itpro/data-entities/dual-write/separated-solutions.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FDynamics-365-Unified-Operations-Public%2Fblob%2Fmain%2Farticles%2Ffin-ops-core%2Fdev-itpro%2Fdata-entities%2Fdual-write%2Fseparated-solutions.md&data=04%7C01%7Cramasri%40microsoft.com%7Cf70b862410c54490ebe108d9db2922ff%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637781792005160793%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=bNy43Yp42BYrtiXB5Ile8qCDQbKPBK3Qq%2Fu67sAJ96E%3D&reserved=0>
  *   Service: dynamics-365-cross-app
  *   GitHub Login: @RamaKrishnamoorthy<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRamaKrishnamoorthy&data=04%7C01%7Cramasri%40microsoft.com%7Cf70b862410c54490ebe108d9db2922ff%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637781792005160793%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=mx5o3UNKqM6crP1GLjMS9vnyxeTQ5Q%2BSnyHpaaTF16Y%3D&reserved=0>
  *   Microsoft Alias: ramasri

—
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fdynamics-365-unified-operations-public%2Fissues%2F3769&data=04%7C01%7Cramasri%40microsoft.com%7Cf70b862410c54490ebe108d9db2922ff%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637781792005160793%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2FgbiUWI2Q1rpt5U0ThBlxn0bl8sDF33k7oexsXwT8qo%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAIM55KN5NH4OP3CSFR6WEFTUWZ3X3ANCNFSM5MJKCDUA&data=04%7C01%7Cramasri%40microsoft.com%7Cf70b862410c54490ebe108d9db2922ff%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637781792005160793%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=BBEuISd5vvpTmwYVg1P393OcmsdLK1AbWEIHNnWdxgg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cramasri%40microsoft.com%7Cf70b862410c54490ebe108d9db2922ff%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637781792005160793%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=d0BCCOFNKM8iwndPrENbh2grU9BFhFDq1D08QTev9Vk%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cramasri%40microsoft.com%7Cf70b862410c54490ebe108d9db2922ff%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637781792005160793%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=wR%2BbhOPqJ04%2FkZgLTsrCtkF1aHwk1wcRs7DO1QDwRRM%3D&reserved=0>.

**Comment by sericks007** [comment]
This article has been added to the TOC.  The updated TOC will be published soon.
