### ISSUE TITLE
Installing SSIS 2016, not any higher version

### ISSUE THREAD

**Issue by Sigvelli** [MicrosoftDocs/dynamics-365-unified-operations-public#3771]
Our experience is to install SSIS 2016, and not any higher version. 
Step 10. “Set up SSIS” should recommend SSIS 2016. 
Our environment is D365FO version 10.0.22, with a higher version of SSIS: When trying to import data using Data Management, we got this error:
«Could not load file or assembly 'Microsoft.SqlServer.ManagedDTS, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified. 
Solution: We had to uninstall SSIS and install SSIS 2016

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14409653-d5a8-bf1b-8772-97832acfe6af
* Version Independent ID: 331d5d92-1601-ed2e-0dd9-4d68beddebff
* Content: [Set up and deploy on-premises environments (Platform update 41 and later) - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/setup-deploy-on-premises-pu41)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/setup-deploy-on-premises-pu41.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/deployment/setup-deploy-on-premises-pu41.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @faix
* Microsoft Alias: **osfaixat**

**Comment by faix** [comment]
Hello @Sigvelli ,

SSIS 2019 is supported starting with 10.0.21. Did you try configuring the localagent for deploying with the appropriate SQL server version? https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/onprem-localagent-options

**Comment by Sigvelli** [comment]
Hi
Thanks for the information. This is exactly the information that I would have liked to have in the "Setup and deploy ..." guide. We will follow your suggestion when installing the Prod environment.

**Comment by faix** [comment]
No problem. I have added a reference to that document on the setup deploy page. Changes will be live soon.
