### ISSUE TITLE
Hide no longer used items from item selection lookups

### ISSUE THREAD

**Issue by lukasnimberger** [MicrosoftDocs/dynamics-365-unified-operations-public#3774]
Hi, could you add another parameter to the lifecycle state settings so it can hide no longer used items from item selection lookups? 
E.g. from drop downs when creating BOMs? Little tweak that would solve a lot of issues, though.

Cheers,
Lukas

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ef9e198-57b9-6847-7351-e429196ff822
* Version Independent ID: 257d4f38-3968-9ba3-6926-98febee51e6b
* Content: [Product lifecycle state overview - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/pim/product-lifecycle)
* Content Source: [articles/supply-chain/pim/product-lifecycle.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/pim/product-lifecycle.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @t-benebo
* Microsoft Alias: **benebotg**

**Comment by kamaybac** [comment]
@lukasnimberger , thank you for contacting Microsoft. It looks like you are submitting a feature request, but this forum is for discussing documentation issues so we can't process feature requests here. However, I'm sure our team would very much like to hear about your feature idea so they can consider whether to implement it in a future update. Please submit it again by going to https://experience.dynamics.com/ideas/.
