### ISSUE TITLE
Columns that can be filtered

### ISSUE THREAD

**Issue by simonefinotti** [MicrosoftDocs/dynamics-365-unified-operations-public#3775]
In the [Grid column header filtering/sorting](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/user-interface/filtering#grid-column-header-filteringsorting) paragraph you say "_for columns that can be filtered_" but it's not stated **when** a column can be filtered. 

It would be nice if there was some additional details to this statement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d636f921-c6d6-25c3-c1e8-15332844eb6d
* Version Independent ID: 657c8193-2829-2c9d-65d0-f0dab5547756
* Content: [Filtering options - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/user-interface/filtering)
* Content Source: [articles/fin-ops-core/dev-itpro/user-interface/filtering.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/user-interface/filtering.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by kamaybac** [comment]
@simonefinotti  , thank you for contacting us regarding this help topic. I have passed your comment on for consideration.

**Comment by kamaybac** [comment]
Bug 662877 created to track this issue

**Comment by jasongre** [comment]
@simonefinotti Thanks for the feedback. I've added some more details to the article. In particular, columns who values are computed by code (and aren't represented as fields in a SQL table) are not filterable or sortable. Display/data methods are prime examples of columns that cannot be filtered or sorted on.
