### ISSUE TITLE
Manage International Bank Account Number (IBAN) account validation

### ISSUE THREAD

**Issue by Anmadu** [MicrosoftDocs/dynamics-365-unified-operations-public#3776]
In section Set up IBAN structures it is mentioned that the structures for specific countries can be edited. 
This is not true, IBAN structures are regulated by the countries, length and other details cannot be changed. 
Additionally the form can be changed, but when setting up the bank account including IBAN to the changed structure an error occurs. 
This leads us to believe that the IBAN structure is hardcoded, 
The IBAN structure should only be treated as a lookup form as the structure itself is regulated by the countries. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 389168a0-4db9-64a8-ca27-81e8a629efd3
* Version Independent ID: fc4f9d07-c618-c3bc-fc4b-cfab54321df3
* Content: [Manage International Bank Account Number (IBAN) account validation - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/cash-bank-management/iban-validation)
* Content Source: [articles/finance/cash-bank-management/iban-validation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/cash-bank-management/iban-validation.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @roschlom
* Microsoft Alias: **roschlom**

**Comment by kamaybac** [comment]
@Anmadu  , thank you for contacting us regarding this help topic. I have passed your comment on to the author for consideration.
