### ISSUE TITLE
Linked cost type calculation in error on Cost Estimates

### ISSUE THREAD

**Issue by Sleekcircle** [MicrosoftDocs/dynamics-365-unified-operations-public#3779]
On Auto costs, set up a cost type with a linked cost type with following:

1) Amount on Apportionment method & 
2) Percent on Category 
3) linked cost type stated.

Run Cost Estimate (under Periodic tasks) 

The cost type with a linked cost type calculated a percentage of the product cost rather than a percentage of the linked cost type. Expect system to calculate a percentage of the linked cost type total cost.

Please advise

**Comment by kamaybac** [comment]
@Sleekcircle 

Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
