### ISSUE TITLE
Old comments

### ISSUE THREAD

**Issue by fordummie** [MicrosoftDocs/dynamics-365-unified-operations-public#378]
Where can I find the old comments that existed on this page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a58e8553-ea84-749e-edd6-fb62c0f0f458
* Version Independent ID: c323529d-896b-25e3-2c7a-e175cc218f27
* Content: [Set up and deploy on-premises environments (Platform update 12) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/deployment/setup-deploy-on-premises-pu12#plansvcacct)
* Content Source: [articles/dev-itpro/deployment/setup-deploy-on-premises-pu12.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/deployment/setup-deploy-on-premises-pu12.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @sarvanisathish
* Microsoft Alias: **sarvanis**

**Comment by sericks007** [comment]
I'll look into if we can make the old comments available.

**Comment by sericks007** [comment]
@fordummie, I'll work to get the comments published.  The document is very long, so it will take some time to prepare it for publication.  In the meantime, was there a specific issue you were looking for?  I can try to look for comments related to that issue and send them to you.

**Comment by fordummie** [comment]
@sericks007 Sally, I can imagine. I'm looking for LocalAgent error, "Application fabric:/LocalAgent is not OK after 5 minutes".

**Comment by sericks007** [comment]
There were many long threads about this error.  Here are some suggestions:

**Comment:**
Check the AX-LocalAgent Events through the Orch1 e Orch2 Nodes.
Probably is an issue related the Certificates, especially the OnPrem thumbprint.

**Comment:**
I had this issue to on my installation. Check if NT SERVICES\ALL SERVICES have the right to log on as a Service in local policy

**Comment:**
Through the Connector, on the Connection Endpoint set the IP Address of the first Orchestrator. Should work.

If this doesn't work, please let me know. I may be able to send you a pre-release version of the comments.

**Comment by fordummie** [comment]
@sericks007 Thx for your support. I did resolve this issue. I remade this steps:

**First of all, I deleted all GMSA accounts and remade again, using this command on PowerShell (must be in Domain Controller machine)**

#Create svc-LocalAgent
New-ADServiceAccount -Name svc-LocalAgent -DNSHostName domainControleMachine.yourDomain.com
Set-ADServiceAccount -Identity svc-LocalAgent$ -PrincipalsAllowedToRetrieveManagedPassword MACHINE_1$,MACHINE_2$,MACHINE_3$,MACHINE_4$,MACHINE_5$,MACHINE_6$,MACHINE_7$,MACHINE_8,MACHINE_9$
#Create svc-AXSF
New-ADServiceAccount -Name svc-AXSF -DNSHostName domainControleMachine.yourDomain.com
Set-ADServiceAccount -Identity svc-AXSF$ -PrincipalsAllowedToRetrieveManagedPassword MACHINE_1$,MACHINE_2$,MACHINE_3$,MACHINE_4$,MACHINE_5$,MACHINE_6$,MACHINE_7$,MACHINE_8,MACHINE_9$
#Create svc-FRPS
New-ADServiceAccount -Name svc-FRPS -DNSHostName domainControleMachine.yourDomain.com
Set-ADServiceAccount -Identity svc-FRPS$ -PrincipalsAllowedToRetrieveManagedPassword MACHINE_1$,MACHINE_2$,MACHINE_3$,MACHINE_4$,MACHINE_5$,MACHINE_6$,MACHINE_7$,MACHINE_8,MACHINE_9$
#Create svc-FRCO
New-ADServiceAccount -Name svc-FRCO -DNSHostName domainControleMachine.yourDomain.com
Set-ADServiceAccount -Identity svc-FRCO$ -PrincipalsAllowedToRetrieveManagedPassword MACHINE_1$,MACHINE_2$,MACHINE_3$,MACHINE_4$,MACHINE_5$,MACHINE_6$,MACHINE_7$,MACHINE_8,MACHINE_9$
#Create svc-FRAS
New-ADServiceAccount -Name svc-FRAS -DNSHostName domainControleMachine.yourDomain.com
Set-ADServiceAccount -Identity svc-FRAS$ -PrincipalsAllowedToRetrieveManagedPassword MACHINE_1$,MACHINE_2$,MACHINE_3$,MACHINE_4$,MACHINE_5$,MACHINE_6$,MACHINE_7$,MACHINE_8,MACHINE_9$

**After that, install on all machines:**

Install-ADServiceAccount -Identity svc-LocalAgent
Install-ADServiceAccount -Identity svc-FRPS
Install-ADServiceAccount -Identity svc-FRCO
Install-ADServiceAccount -Identity svc-AXSF
Install-ADServiceAccount -Identity svc-FRAS

**After that, put all GMSA accounts on Administrator group, on all machines.**

**After that, I used the WinHttpCertCfg tool to put all GMSA accounts inside of Manage Private Key of all certificates.**

cd "C:\Program Files (x86)\Windows Resource Kits\Tools"
#Set privatekeyAcces to GMSA svc-LocalAgent$
.\WinHttpCertCfg.exe -g -c LOCAL_MACHINE\MY -s *.d365.iimak.com  -a "svc-LocalAgent$"
.\WinHttpCertCfg.exe -g -c LOCAL_MACHINE\MY -s OnPrem365.ServiceFabricClient -a "svc-LocalAgent$"
.\WinHttpCertCfg.exe -g -c LOCAL_MACHINE\MY -s OnPrem365.DataEncryption -a "svc-LocalAgent$"
.\WinHttpCertCfg.exe -g -c LOCAL_MACHINE\MY -s OnPrem365.DataSigning -a "svc-LocalAgent$"
.\WinHttpCertCfg.exe -g -c LOCAL_MACHINE\MY -s OnPrem365.FinancialReporting -a "svc-LocalAgent$"
.\WinHttpCertCfg.exe -g -c LOCAL_MACHINE\MY -s OnPrem365.ServiceFabricEncryption -a "svc-LocalAgent$"
.\WinHttpCertCfg.exe -g -c LOCAL_MACHINE\MY -s OnPrem365.ReportingService -a "svc-LocalAgent$"
.\WinHttpCertCfg.exe -g -c LOCAL_MACHINE\MY -s OnPrem365.SessionAuthentication -a "svc-LocalAgent$"
.\WinHttpCertCfg.exe -g -c LOCAL_MACHINE\MY -s OnPrem365.Orchestrator -a "svc-LocalAgent$"
#Set privatekeyAcces to GMSA svc-FRAS$
.\WinHttpCertCfg.exe -g -c LOCAL_MACHINE\MY -s *.d365.iimak.com  -a "svc-FRAS$"
.\WinHttpCertCfg.exe -g -c LOCAL_MACHINE\MY -s OnPrem365.ServiceFabricClient -a "svc-FRAS$"
.\WinHttpCertCfg.exe -g -c LOCAL_MACHINE\MY -s OnPrem365.DataEncryption -a "svc-FRAS$"
.\WinHttpCertCfg.exe -g -c LOCAL_MACHINE\MY -s OnPrem365.DataSigning -a "svc-FRAS$"
.\WinHttpCertCfg.exe -g -c LOCAL_MACHINE\MY -s OnPrem365.FinancialReporting -a "svc-FRAS$"
.\WinHttpCertCfg.exe -g -c LOCAL_MACHINE\MY -s OnPrem365.ServiceFabricEncryption -a "svc-FRAS$"
.\WinHttpCertCfg.exe -g -c LOCAL_MACHINE\MY -s OnPrem365.ReportingService -a "svc-FRAS$"
.\WinHttpCertCfg.exe -g -c LOCAL_MACHINE\MY -s OnPrem365.SessionAuthentication -a "svc-FRAS$"
.\WinHttpCertCfg.exe -g -c LOCAL_MACHINE\MY -s OnPrem365.Orchestrator -a "svc-FRAS$"
#Set privatekeyAcces to GMSA svc-FRPS$
.\WinHttpCertCfg.exe -g -c LOCAL_MACHINE\MY -s *.d365.iimak.com  -a "svc-FRPS$"
.\WinHttpCertCfg.exe -g -c LOCAL_MACHINE\MY -s OnPrem365.ServiceFabricClient -a "svc-FRPS$"
.\WinHttpCertCfg.exe -g -c LOCAL_MACHINE\MY -s OnPrem365.DataEncryption -a "svc-FRPS$"
.\WinHttpCertCfg.exe -g -c LOCAL_MACHINE\MY -s OnPrem365.DataSigning -a "svc-FRPS$"
.\WinHttpCertCfg.exe -g -c LOCAL_MACHINE\MY -s OnPrem365.FinancialReporting -a "svc-FRPS$"
.\WinHttpCertCfg.exe -g -c LOCAL_MACHINE\MY -s OnPrem365.ServiceFabricEncryption -a "svc-FRPS$"
.\WinHttpCertCfg.exe -g -c LOCAL_MACHINE\MY -s OnPrem365.ReportingService -a "svc-FRPS$"
.\WinHttpCertCfg.exe -g -c LOCAL_MACHINE\MY -s OnPrem365.SessionAuthentication -a "svc-FRPS$"
.\WinHttpCertCfg.exe -g -c LOCAL_MACHINE\MY -s OnPrem365.Orchestrator -a "svc-FRPS$"
#Set privatekeyAcces to GMSA svc-FRCO
.\WinHttpCertCfg.exe -g -c LOCAL_MACHINE\MY -s *.d365.iimak.com  -a "svc-FRCO$"
.\WinHttpCertCfg.exe -g -c LOCAL_MACHINE\MY -s OnPrem365.ServiceFabricClient -a "svc-FRCO$"
.\WinHttpCertCfg.exe -g -c LOCAL_MACHINE\MY -s OnPrem365.DataEncryption -a "svc-FRCO$"
.\WinHttpCertCfg.exe -g -c LOCAL_MACHINE\MY -s OnPrem365.DataSigning -a "svc-FRCO$"
.\WinHttpCertCfg.exe -g -c LOCAL_MACHINE\MY -s OnPrem365.FinancialReporting -a "svc-FRCO$"
.\WinHttpCertCfg.exe -g -c LOCAL_MACHINE\MY -s OnPrem365.ServiceFabricEncryption -a "svc-FRCO$"
.\WinHttpCertCfg.exe -g -c LOCAL_MACHINE\MY -s OnPrem365.ReportingService -a "svc-FRCO$"
.\WinHttpCertCfg.exe -g -c LOCAL_MACHINE\MY -s OnPrem365.SessionAuthentication -a "svc-FRCO$"
.\WinHttpCertCfg.exe -g -c LOCAL_MACHINE\MY -s OnPrem365.Orchestrator -a "svc-FRCO$"
#Set privatekeyAcces to GMSA svc-AXSF$
.\WinHttpCertCfg.exe -g -c LOCAL_MACHINE\MY -s *.d365.iimak.com  -a "svc-AXSF$"
.\WinHttpCertCfg.exe -g -c LOCAL_MACHINE\MY -s OnPrem365.ServiceFabricClient -a "svc-AXSF$"
.\WinHttpCertCfg.exe -g -c LOCAL_MACHINE\MY -s OnPrem365.DataEncryption -a "svc-AXSF$"
.\WinHttpCertCfg.exe -g -c LOCAL_MACHINE\MY -s OnPrem365.DataSigning -a "svc-AXSF$"
.\WinHttpCertCfg.exe -g -c LOCAL_MACHINE\MY -s OnPrem365.FinancialReporting -a "svc-AXSF$"
.\WinHttpCertCfg.exe -g -c LOCAL_MACHINE\MY -s OnPrem365.ServiceFabricEncryption -a "svc-AXSF$"
.\WinHttpCertCfg.exe -g -c LOCAL_MACHINE\MY -s OnPrem365.ReportingService -a "svc-AXSF$"
.\WinHttpCertCfg.exe -g -c LOCAL_MACHINE\MY -s OnPrem365.SessionAuthentication -a "svc-AXSF$"
.\WinHttpCertCfg.exe -g -c LOCAL_MACHINE\MY -s OnPrem365.Orchestrator -a "svc-AXSF$"

After this steps, my issue was resolved.
