### ISSUE TITLE
GL postings on Landed cost module do not seem right

### ISSUE THREAD

**Issue by Sleekcircle** [MicrosoftDocs/dynamics-365-unified-operations-public#3780]
GL postings seem to post variance to clearing account and vice-versa.

Please advise

**Comment by kamaybac** [comment]
@Sleekcircle 

Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
