### ISSUE TITLE
Redirect URI is incorrect

### ISSUE THREAD

**Issue by mikecaterino** [MicrosoftDocs/dynamics-365-unified-operations-public#3781]
In the section Registration process, the line "Redirect URI – Enter the base URL of your client, such as https://contosoax7.cloud.dynamics.com." is incorrect. It should state something similar to "Redirect URI – Enter the base URL of your client with oauth appended to the end, such as https://contosoax7.cloud.dynamics.com/oauth"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2213414-926d-10e1-538b-efef09dc0181
* Version Independent ID: 03be53f7-c305-cb02-7627-2ea4f1c01bd4
* Content: [Configure PowerBI.com integration - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/configure-power-bi-integration)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/configure-power-bi-integration.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/analytics/configure-power-bi-integration.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @RichdiMSFT
* Microsoft Alias: **RICHDI**

**Comment by sericks007** [comment]
@mikecaterino, thanks for letting us know!  I've updated that line as you suggested.  The update will be published soon.
