### ISSUE TITLE
As the evaluation environments are no longer available, this section should be removed.

### ISSUE THREAD

**Issue by babaknahh** [MicrosoftDocs/dynamics-365-unified-operations-public#3782]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8c0097e-bb5b-0154-a812-0cd090232df4
* Version Independent ID: 09289554-3a50-b9ae-b52a-b09a15207904
* Content: [Dynamics 365 Commerce evaluation environment overview - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/cpe-overview?source=docs)
* Content Source: [articles/commerce/cpe-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/cpe-overview.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @v-chgri
* Microsoft Alias: **josaw**

**Comment by kfend** [comment]
@babaknahh - Than you for the suggestion.
@v-chgri and @josaw1 - Can you please take a look at this and update the topic as needed?

**Comment by kfend** [comment]
Created bug 656120 to track this issue.

**Comment by josaw1** [comment]
@samjarawan does this topic need to be removed?

**Comment by josaw1** [comment]
@jashanno does this article need to be removed?

**Comment by josaw1** [comment]
This issue has been fixed.
