### ISSUE TITLE
Is this Customer Electronic Invoice has any limitations in number of Transactions?

### ISSUE THREAD

**Issue by liamneesan** [MicrosoftDocs/dynamics-365-unified-operations-public#3783]
we are running super markets, I have read that '100 Transaction limitations' in Electronic Invoicing which is documented in 'Dynamics Licensing Guidline'. please give us proper guidline regarding this. even partners never give any proper updates regarding this limitations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee29cc0e-a9f8-26ae-3b74-452485e5bf0c
* Version Independent ID: ee29cc0e-a9f8-26ae-3b74-452485e5bf0c
* Content: [Customer electronic invoices in Saudi Arabia - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/emea-sau-e-invoices)
* Content Source: [articles/finance/localizations/emea-sau-e-invoices.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/emea-sau-e-invoices.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @ikondo
* Microsoft Alias: **ilyako**

**Comment by kfend** [comment]
@liamneesan - Thank you for the question.
@ilkond - Can you please take a look and answer this question?

**Comment by ilkond** [comment]
@liamneesan, @kfend, There is no limitation for number of electronic invoices. The question was probably caused by pricing information for electronic invoicing service. Here, the first 100 invoices per moth are free of charge, the rest will be chargeable.
fyi @mrolecki
