### ISSUE TITLE
Get executionId by messageId for recurring integration status check

### ISSUE THREAD

**Issue by puneetdarji** [MicrosoftDocs/dynamics-365-unified-operations-public#3784]
While sending data to D365 via recurring integration batch api, in return D365 provides message Id. This messageId is sufficient to get the overall status of the message but if you want to get list of execution errors i.e. error message for each row you require execution id. In this case how external system can get execution id against the message id they have? At the moment this is not clear in the documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01b2cd6b-f885-7461-fbdf-cf81f9e50d86
* Version Independent ID: 8df7a6ae-67db-5d29-fb6a-0820704ff3ef
* Content: [Recurring integrations - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/recurring-integrations)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/recurring-integrations.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/recurring-integrations.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Peakerbl
* Microsoft Alias: **peakerbl**

**Comment by kfend** [comment]
@puneetdarji - Thank you for the question.
@Peakerbl - Can you please take a look at this question?

**Comment by kfend** [comment]
Created bug 656123 to track this issue.

**Comment by kfend** [comment]
Thank you for letting us know. We have done more investigating, and we will be making an update to the functionality based on this feedback.
