### ISSUE TITLE
The Azure portal link is outdated.

### ISSUE THREAD

**Issue by zhenfangyan** [MicrosoftDocs/dynamics-365-unified-operations-public#3785]
![image](https://user-images.githubusercontent.com/18294106/151111605-645eacfb-2617-4b84-b6b0-2991953769fa.png)
The Azure portal link is still using the classic manage portal which is outdated. Please help to update to Azure portal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 693bb4b2-92f2-2f0c-4fd3-6c9c1bb5894b
* Version Independent ID: 476f52d0-57a1-37e2-881f-857ce623bb03
* Content: [Complete the Azure Resource Manager onboarding process - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/arm-onboarding#upload-the-management-certificate)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/arm-onboarding.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/deployment/arm-onboarding.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @saurabhsurana
* Microsoft Alias: **sasurana**

**Comment by kfend** [comment]
@zhenfangyan - Thank you for the feedback.
@saurabhsurana - Can you please take a look and update the topic?

**Comment by kfend** [comment]
Created bug 656126 to track this issue.

**Comment by josaw1** [comment]
Closed as won't fix.
