### ISSUE TITLE
The document needs to address environment that already has Retail Server and Channel database

### ISSUE THREAD

**Issue by Halldor10** [MicrosoftDocs/dynamics-365-unified-operations-public#3787]
This document should address the setup for a Dev box that has Retail Server and Channel database already installed also and not just a CSU.

As written in another document for setting up CSU it says:" Do not install a CSU on a developer environment, which typically already has a configured Retail Server and Channel database."

And for Norway it applies as written in this document:
"Because of limitations of the new independent packaging and extension model, it can't currently be used for this localization functionality." 

So the default for Norway would be a developement boks that already has Retail Server and a Channel database..

One thing I found out when implementing this is that the current standard code and setup does not support that the certificate has a password.  So I had to update the TryGetCertificateFromKeyVault method in the CertificateProvider Class to work around this. Would have been better if the password for ceriticate would be part of the setup, done in the same way as the certificate setup.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32819466-5d8f-cbab-d5b6-b972668f8cf6
* Version Independent ID: 32819466-5d8f-cbab-d5b6-b972668f8cf6
* Content: [Deployment guidelines for cash registers for Norway - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/localizations/emea-nor-fi-deployment)
* Content Source: [articles/commerce/localizations/emea-nor-fi-deployment.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/localizations/emea-nor-fi-deployment.md)
* Service: **dynamics-365-commerce**
* GitHub Login: @EvgenyPopovMBS
* Microsoft Alias: **epopov**

**Comment by kfend** [comment]
Created bug 656127 to track this issue.

**Comment by EvgenyPopovMBS** [comment]
@Halldor10, thanks for the feedback. We will update this documentation when we implement the support for the new independent packaging and extension model, which is planned for one of the next updates.
As for the support of certificates with passwords, that's correct: the functionality does not support such certificates. If you need to use a certificate with a password, you have to implement a customization.
