### ISSUE TITLE
Suggestion to link or note additional information

### ISSUE THREAD

**Issue by jdterrington** [MicrosoftDocs/dynamics-365-unified-operations-public#3789]
I would suggest that it would be beneficial specifically note that the CREDIT INVOICING function is only available for ITALY.

https://docs.microsoft.com/en-us/dynamics365/finance/localizations/emea-ita-credit-invoicing

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d42fb9b-30ef-7398-5369-57fbeba9e516
* Version Independent ID: fe08be8e-4f9d-fedd-ee4c-7737245dd581
* Content: [References to original invoices in credit notes - Finance | Dynamics 365](https://docs.microsoft.com/en-gb/dynamics365/finance/accounts-receivable/original-invoice-numbers-credit-notes)
* Content Source: [articles/finance/accounts-receivable/original-invoice-numbers-credit-notes.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/accounts-receivable/original-invoice-numbers-credit-notes.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @ilkond
* Microsoft Alias: **ilyako**

**Comment by ilkond** [comment]
@jdterrington, @kfend, Credit invoicing is available not only for Italy but for other countries as well.

**Comment by jdterrington** [comment]
The Microsoft link suggests that it is only available for the Italy region.

Happy for you to provide a link that tells me otherwise :)

https://docs.microsoft.com/en-us/dynamics365/finance/localizations/emea-ita-credit-invoicing

**Comment by ilkond** [comment]
@jdterrington for example these links:

- https://docs.microsoft.com/en-us/dynamics365/finance/localizations/emea-corrective-invoice
- https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/correct-a-posted-free-text-invoice
- https://docs.microsoft.com/en-us/dynamics365/finance/localizations/tasks/emea-esp-credit-invoicing
- https://docs.microsoft.com/en-us/dynamics365/finance/accounts-receivable/correct-free-text-invoice

**Comment by jdterrington** [comment]
I am sorry but I 100% disagree with you.  However I am going to now give up trying to resolve this as you are obviously set in your assumptions.  I will say that if you check with MS, you will not be correct.

1) Link one - this is not the "CREDIT INVOICE" function that I am talking about.  This is a completely different function for "CORRECTIVE INVOICE".  

2) Link two - This is an old link for AX 2012 and is not relevant for D365FO at all.  And again, it is not the functionality that I am referring to.

3) Link 3 - this is talking about the "CORRECTIVE INVOICE" functionality, and not the "CREDIT INVOICE" function that I am referring to.

4) Link 4 - this is talking about the "CORRECTIVE INVOICE" functionality, and not the "CREDIT INVOICE" function that I am referring to.

Regards
James

**Comment by ilkond** [comment]
@jdterrington let's return to your initial concern. Was it about this article https://docs.microsoft.com/en-gb/dynamics365/finance/accounts-receivable/original-invoice-numbers-credit-notes?
You state that it is available only for Italy, correct?

**Comment by ilkond** [comment]
@jdterrington This article is mainly about **printing** of the references to original invoices in credit notes created for Free text invoices, Customer Invoices or Project invoices.
"Credit invoicing" for Free text invoices (which intersects with Italy-specific article that you provided) is available not only for Italy but also for Austria, Belgium, Denmark, Finland, France, Germany, Iceland, Ireland, Netherlands, Norway, Spain, Sweden, Switzerland and Great Britain. Or for any other country if the mentioned feature "Credit invoicing layout for sales and project invoice reports" is enabled.
So, it is not "beneficial" and even wrong to say that CREDIT INVOICING function is only available for ITALY.
