### ISSUE TITLE
Example automatically pause dual-write

### ISSUE THREAD

**Issue by DiSae** [MicrosoftDocs/dynamics-365-unified-operations-public#3791]
It would be nice if we had an example or linked document on "how to automatically pause dual-write for maintenance". Preferably via a PowerShell script.
I haven't been able to find any example so far. The document says it is possible via rules, but I'm not sure where to start.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55bef827-5708-7c14-6ad2-ac2060f5f65a
* Version Independent ID: 55bef827-5708-7c14-6ad2-ac2060f5f65a
* Content: [Pause dual-write for maintenance - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/pause-for-maintenance)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/pause-for-maintenance.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/dual-write/pause-for-maintenance.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @NHelgren
* Microsoft Alias: **nhelgren**

**Comment by kfend** [comment]
Created bug 656111 to track this issue.

**Comment by josaw1** [comment]
Closed as won't fix.
