### ISSUE TITLE
Known issues section out-of-date

### ISSUE THREAD

**Issue by e9325827** [MicrosoftDocs/dynamics-365-unified-operations-public#3792]
Hi,

it would be helpful if this list of known issues was maintained: https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/grid-capabilities#known-issues

I know of fixes around the new grid control since 10.0.16 which do not show up, and I assume some further open issues are known / worked on.

Best regards,
Martin
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75388071-94ef-d7e9-cbc1-a910621ef20e
* Version Independent ID: 6be15ff3-b119-2be7-535d-b0caa7072b5b
* Content: [Grid capabilities - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/grid-capabilities#known-issues)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/grid-capabilities.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/grid-capabilities.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by kfend** [comment]
@e9325827 - Thank you for your feedback. 
@jasongre - Can you please take a look at this?

**Comment by kfend** [comment]
Created bug 656106 to track this issue.

**Comment by josaw1** [comment]
Issue fixed by product manager.
