### ISSUE TITLE
Update page to reflect the security changes from bug: 645488

### ISSUE THREAD

**Issue by ErikJohnMSFT** [MicrosoftDocs/dynamics-365-unified-operations-public#3793]
Hello, 

I am a Sr. Support SE on D365FO and there was a change to 10.0.24 for security bug: 645488 and removed the XSLT file upload, can this page be updated to reflect that change as well as the steps to use/configure ER to now upload the XSLT file?

Thank you, 

Erik Johnson
ErikJohn

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a56dd618-9180-ed71-fd8e-850153f35b59
* Version Independent ID: 6322764e-1b61-5148-024a-0d6b124c0512
* Content: [Set up and generate positive pay files - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/accounts-payable/set-up-generate-positive-pay-files)
* Content Source: [articles/finance/accounts-payable/set-up-generate-positive-pay-files.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/accounts-payable/set-up-generate-positive-pay-files.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @panolte
* Microsoft Alias: **shpandey**

**Comment by kfend** [comment]
@ErikJohnMSFT - Thank you for the feedback.
@panolte - Can you work with Erik to update the topic as needed?

**Comment by josephkmcohio** [comment]
Erik - do you have the steps you can send me to configure the xml upload for positive pay?  We are testing 10.0.24 and need to validate the positive pay generating.

**Comment by kfend** [comment]
Created bug 656130 to track this issue.

**Comment by kfend** [comment]
Closing this as it has been sent to support.
