### ISSUE TITLE
link to page "Run custom X++ scripts with zero downtime" is wrong

### ISSUE THREAD

**Issue by gertvdh** [MicrosoftDocs/dynamics-365-unified-operations-public#3801]
it's going to https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/organization-administration/run-custom-scripts.md

instead of https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/run-custom-scripts

so the "organization-administration" 'sub folder' is different

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7dacb957-d7e0-977a-3357-2bab8398e090
* Version Independent ID: 7dacb957-d7e0-977a-3357-2bab8398e090
* Content: [Platform updates for version 10.0.25 of Finance and Operations apps (April 2022) - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/get-started/whats-new-platform-updates-10-0-25)
* Content Source: [articles/fin-ops-core/dev-itpro/get-started/whats-new-platform-updates-10-0-25.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/get-started/whats-new-platform-updates-10-0-25.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @sericks007
* Microsoft Alias: **sericks**

**Comment by sericks007** [comment]
@gertvdh, thanks for letting us know!  The link has been fixed and will be published soon!
