### ISSUE TITLE
Wrong hyperlink

### ISSUE THREAD

**Issue by codingeugene** [MicrosoftDocs/dynamics-365-unified-operations-public#3802]
Hyperlink to the section "Run custom X++ scripts with zero downtime" is not working - leads to "Page not found"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7dacb957-d7e0-977a-3357-2bab8398e090
* Version Independent ID: 7dacb957-d7e0-977a-3357-2bab8398e090
* Content: [Platform updates for version 10.0.25 of Finance and Operations apps (April 2022) - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/get-started/whats-new-platform-updates-10-0-25)
* Content Source: [articles/fin-ops-core/dev-itpro/get-started/whats-new-platform-updates-10-0-25.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/get-started/whats-new-platform-updates-10-0-25.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @sericks007
* Microsoft Alias: **sericks**

**Comment by sericks007** [comment]
@codingeugene, thanks for letting us know! The link has been fixed and will be published soon!
