### ISSUE TITLE
Can we remove the copy button from the code sample that is an 'example of what not to do'?  

### ISSUE THREAD

**Issue by scott-tucker** [MicrosoftDocs/dynamics-365-unified-operations-public#3805]
Can we remove the copy button from the code sample that is an 'example of what not to do'?  We shouldn't make it easy to copy code we don't want implemented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 530a3254-1e49-4d8d-f251-adb5285027a6
* Version Independent ID: a8d2499a-865c-a573-42f6-e32cbce7790f
* Content: [Channel database extensions - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/channel-db-extensions)
* Content Source: [articles/commerce/dev-itpro/channel-db-extensions.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/channel-db-extensions.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by sericks007** [comment]
@mugunthanm, please review and update the content, as needed.  Bug 656388 has been logged to track this issue.

**Comment by mugunthanm** [comment]
@scott-tucker - Not sure there is an easy way to disable the copy button, these are auto generated.
