### ISSUE TITLE
when will this available for preview?

### ISSUE THREAD

**Issue by Sihongf** [MicrosoftDocs/dynamics-365-unified-operations-public#3807]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f09e8fa-e5dc-2e5d-3613-c6b4f6d7191a
* Version Independent ID: 2f09e8fa-e5dc-2e5d-3613-c6b4f6d7191a
* Content: [Run custom X++ scripts with zero downtime - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/run-custom-scripts)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/run-custom-scripts.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/deployment/run-custom-scripts.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @AndersGirke
* Microsoft Alias: **aevengir**

**Comment by sericks007** [comment]
This feature is available with version 10.0.25, which is available for preview now.  For more information, see [Platform updates for version 10.0.25 of Finance and Operations apps  (April 2022)](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/get-started/whats-new-platform-updates-10-0-25).

**Comment by Sihongf** [comment]
thanks, I have 10.0.25. Is there any configuration/feature to enable it?

**Comment by sericks007** [comment]
@AndersEvenGirke, please answer the questions above.

**Comment by FunctionalConsultantsthatCode** [comment]
I see the code in 10.0.25 preview release and the AppConsistencyCustomScriptFlight is enabled in Flighting in the database. but looking at the code they have not added it to the main menu structure. Note I am using a one box environment. you can open forms directly but they are missing objects
?f=appconsistencycustomscriptlistpage 
?f=appconsistencycustomscriptupload&cmp=USMF
?f=appconsistencycustomscriptdetails&cmp=USMF (missing workflowobjects)

Installed product version : 10.0.25 (10.0.1149.21)
Installed platform version : Update49 (7.0.6316.18)
