### ISSUE TITLE
BAI2 Set up for 10.0.24

### ISSUE THREAD

**Issue by josephkmcohio** [MicrosoftDocs/dynamics-365-unified-operations-public#3808]
Is this documentation up to date for 10.0.24?  We have applied this release to a UAT environment and I am unable to get the Bank Statement format to load as a new filed called "Import format configuration" is required but the underlying drop down table is blank.

**Comment by sericks007** [comment]
@josephkmcohio, which documentation article are you referring to?  Could you please provide a link to the article.

**Comment by josephkmcohio** [comment]
https://docs.microsoft.com/en-us/dynamics365/finance/cash-bank-management/set-up-advanced-bank-reconciliation-import-process

I’m following the instructions in this article in 10.0.24 and am being required to enter an Import format configuration but the drop down in the field is blank.



***@***.***

**Comment by sericks007** [comment]
@josephkmcohio, thank you for providing the link!

@panolte, please respond and update the content, if needed.

**Comment by sericks007** [comment]
Bug 656390 has been logged to track this work.

**Comment by sericks007** [comment]
Please contact Microsoft Support for your issue.  To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support).
