### ISSUE TITLE
Title and content indicates Europe, first line indicates Brazil

### ISSUE THREAD

**Issue by MarkElenbaas** [MicrosoftDocs/dynamics-365-unified-operations-public#381]
Pleas change Brazil to Europe.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd14df17-76ba-883b-7a17-c50c7c87af0f
* Version Independent ID: c3560cb9-c651-3425-d2ee-34df04335a7f
* Content: [Europe - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/localizations/europe)
* Content Source: [articles/financials/localizations/europe.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/localizations/europe.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @ShylaThompson
* Microsoft Alias: **shylaw**

**Comment by ShylaThompson** [comment]
Thanks @MarkElenbaas  for pointing out this error. This will be fixed by end of day today.
