### ISSUE TITLE
Bad formatting leads to steps being difficult to follow

### ISSUE THREAD

**Issue by NCramProdware** [MicrosoftDocs/dynamics-365-unified-operations-public#3811]
[Enter feedback here]
"Set up functional location lifecycle states" from point 6 is embedded in the Note

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0d710a0-e7ea-efcc-c72a-2ca81477e2a7
* Version Independent ID: fb14fb88-8fc9-cd1e-4a98-8f07f69041eb
* Content: [Functional location lifecycle states - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/asset-management/setup-for-functional-locations/functional-location-stages)
* Content Source: [articles/supply-chain/asset-management/setup-for-functional-locations/functional-location-stages.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/asset-management/setup-for-functional-locations/functional-location-stages.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @johanhoffmann
* Microsoft Alias: **johanho**

**Comment by twheeloc** [comment]
@NCramProdware, thank you for providing this feedback.

The topic will be updated.
