### ISSUE TITLE
"Dispose off" should read "Dispose of" in architecture diagram

### ISSUE THREAD

**Issue by NCramProdware** [MicrosoftDocs/dynamics-365-unified-operations-public#3812]
[Enter feedback here]
"Dispose off fixed assets" in the "Retire" column should read "Dispose of fixed assets" (English vocabulary error).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c114fcd0-5df8-6b4d-bd96-909e62dc3267
* Version Independent ID: af3b83d7-2bcf-38c3-1974-c8f0da8ad032
* Content: [Asset management overview - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/asset-management/)
* Content Source: [articles/supply-chain/asset-management/index.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/asset-management/index.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @johanhoffmann
* Microsoft Alias: **johanho**

**Comment by twheeloc** [comment]
@NCramProdware, thank you for providing this feedback.

@johanhoffmann, please review and update the content, as needed.
