### ISSUE TITLE
Incorrect link tot sysflighting

### ISSUE THREAD

**Issue by BasvGMRN** [MicrosoftDocs/dynamics-365-unified-operations-public#3813]
In the prerequisites section a link is shared which brings the user to the Data Management sysflighting documentation - it does not link to generic or asset management sysflighting documentation.

"
[Turn on flight](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/data-entities-data-packages#features-flighted-in-data-management-and-enabling-flighted-features) for the MRGuidesFeature feature. (For production environments, you must first submit a support ticket to have your tenant added to the flighting group.)
"

Also, no documentation on how to enable sysflighting for tier 2 (sandboxes) - can this please be added?
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 748a1a7d-a96c-06bc-fbfb-ec67a561c326
* Version Independent ID: db590555-00e5-5dfc-2df5-710c8aa707cc
* Content: [Integrate Dynamics 365 Supply Chain Management (Asset management) with Dynamics 365 Guides - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/asset-management/asset-management-guides-integration)
* Content Source: [articles/supply-chain/asset-management/asset-management-guides-integration.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/asset-management/asset-management-guides-integration.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @johanhoffmann
* Microsoft Alias: **johanho**

**Comment by twheeloc** [comment]
@BasvGMRN, thank you for providing this feedback.

@johanhoffmann, please review and update the content, as needed.
