### ISSUE TITLE
New-AzureADServicePrincipal -AppId 0cdb527f-a8d1-4bf8-9436-b352c68682b2 gives Authorization_RequestDenied

### ISSUE THREAD

**Issue by BasvGMRN** [MicrosoftDocs/dynamics-365-unified-operations-public#3814]
Following the steps for validating/creating App ID

In the Azure portal, on the toolbar, select the button to open Azure Cloud Shell.
Run the command Install-Module AzureAD. Enter Y to install the module.
Run the command Get-InstalledModule -Name "AzureAD" to verify that the module is installed.
Run the command Connect-AzureAD -Confirm to run the authentication.
Run the command New-AzureADServicePrincipal -AppId 0cdb527f-a8d1-4bf8-9436-b352c68682b2.

PS /home/system> Install-Module AzureAD
PS /home/system> Get-InstalledModule -Name "AzureAD"

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
2.0.2.140            AzureAD                             PSGallery            Azure Active Directory V2 General Availability Module.…

PS /home/system> Connect-AzureAD -Confirm
PS /home/system> New-AzureADServicePrincipal -AppId 0cdb527f-a8d1-4bf8-9436-b352c68682b2
New-AzureADServicePrincipal: Error occurred while executing NewServicePrincipal
Code: Authorization_RequestDenied
Message: Insufficient privileges to complete the operation.
RequestId: f1c7fb5b-bb2b-44d4-b1ba-e109ff89c6c6
DateTimeStamp: Mon, 07 Feb 2022 13:36:00 GMT
HttpStatusCode: Forbidden
HttpStatusDescription: Forbidden
HttpResponseStatus: Completed

Result: unable to create App ID ( 0cdb527f-a8d1-4bf8-9436-b352c68682b2) - unable to proceed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e06b1a81-1915-8f90-d28d-1f895d2bb870
* Version Independent ID: 46729ec6-7fa8-6f19-9eaf-832638b35d86
* Content: [Set up Azure resources for IoT Intelligence - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/iot/iot-azure-setup)
* Content Source: [articles/supply-chain/iot/iot-azure-setup.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/iot/iot-azure-setup.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @tonyafehr
* Microsoft Alias: **tfehr**

**Comment by twheeloc** [comment]
@BasvGMRN, thank you for providing this feedback.

@kamaybac, please review and updated the content as needed.
