### ISSUE TITLE
Diagram uses "Common data service" - should be "Dataverse"

### ISSUE THREAD

**Issue by RicLund** [MicrosoftDocs/dynamics-365-unified-operations-public#3816]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 036570ee-85fa-8449-be1c-a5e8755e175c
* Version Independent ID: 2468c8f9-0814-ded0-c6dd-879851a4b9e1
* Content: [Dual-write overview - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/dual-write-overview)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/dual-write-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/dual-write/dual-write-overview.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @RamaKrishnamoorthy
* Microsoft Alias: **ramasri**

**Comment by twheeloc** [comment]
@RicLund, thank you for the feedback.

@RamaKrishnamoorthy, please review and updated the content, as needed.
