### ISSUE TITLE
Enable loopback exemption for sealed MPOS

### ISSUE THREAD

**Issue by cn12xewo** [MicrosoftDocs/dynamics-365-unified-operations-public#3817]
Hello dear team,

We wanted to install the sealed MPOS in a VM with self-hosted CSU. The problem we had for a long time was that the sealed MPOS could not connect to the retail server. To fix this problem we had to enable a loopback exemption. Maybe this should be mentioned in the doc. 

Many greetings

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c22f987b-3d20-554d-467a-cdcdf404b0bd
* Version Independent ID: 0160ae8d-09c7-d54c-83bf-10fbec9842e9
* Content: [Mass deployment of sealed Commerce self-service components - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/enhanced-mass-deployment#feedback)
* Content Source: [articles/commerce/dev-itpro/Enhanced-Mass-Deployment.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/Enhanced-Mass-Deployment.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @jashanno
* Microsoft Alias: **jashanno**

**Comment by twheeloc** [comment]
@cn12xewo, thank you for providing this feedback.

@jashanno, please review and updated the content as needed.
