### ISSUE TITLE
Validating Blank Dates

### ISSUE THREAD

**Issue by torbennehmer** [MicrosoftDocs/dynamics-365-unified-operations-public#3819]
Please validate the section about validating against blank dates. You're stating that one should compare against 1900, but this doesn't seem to work always, one example for this can be seen on Yammer these days:

https://www.yammer.com/dynamicsaxfeedbackprograms/#/Threads/show?threadId=1594212369743872

Maybe different Excel settings or locales make a difference here, I've had very strange effects in my own Excel parsing code over the years.

Any insight in how to do this best would be appreciated, based on how RSAT actually reads those values.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3333aae9-4afa-d53f-13f8-e495a451c3c3
* Version Independent ID: 59e4ae15-534b-eb98-84be-23de51d02241
* Content: [Troubleshoot the Regression suite automation tool - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/perf-test/rsat/rsat-troubleshooting#validating-blank-dates)
* Content Source: [articles/fin-ops-core/dev-itpro/perf-test/rsat/rsat-troubleshooting.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/perf-test/rsat/rsat-troubleshooting.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @FrankDahl
* Microsoft Alias: **fdahl**

**Comment by twheeloc** [comment]
@torbennehmer, thank you for providing this feedback.

@FrankDahl, please review and updated the content as needed.

**Comment by josaw1** [comment]
Closed as won't fix.
