### ISSUE TITLE
Step 1 needs to be reviewed.

### ISSUE THREAD

**Issue by rat-af** [MicrosoftDocs/dynamics-365-unified-operations-public#382]
The 'Description' here seems to be incorrect for step 1.  When I use that description in my DEV box, I get the following message:  The keyword 详见销售清单 cannot be used here. 
It doesn't make sense that the description is been validated in this way, but it clearly doesn't like it.  Please update the document to be more accurate for the setup, as this can't be followed in it's current state.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9677314d-cfbb-77ed-5df9-b475abe0a4db
* Version Independent ID: f53343d4-7188-49be-d332-f559e555ce88
* Content: [Configure tax integration for China - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/localizations/apac-chn-tax-integration)
* Content Source: [articles/financials/localizations/apac-chn-tax-integration.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/localizations/apac-chn-tax-integration.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @ShylaThompson
* Microsoft Alias: **leguo**

**Comment by ShylaThompson** [comment]
@rat-af Thanks for bringing this to our attention. The topic will be updated later today with the correct description text "设备"
