### ISSUE TITLE
Mention the possibility to catch .net Exceptions for X++ Exception ENum

### ISSUE THREAD

**Issue by torbennehmer** [MicrosoftDocs/dynamics-365-unified-operations-public#3820]
It is possible to catch an Exception::Error using a construct like this one:

```
Microsoft.Dynamics.Ax.Xpp.ErrorException xppEx;
 
try
{
    throw error("It's broken!");
}
catch (xppEx)
{
    this.log(xppEx.StackTrace);
}
```

Curtesy of http://dev.goshoom.net/2017/06/catching-exceptions-in-ax-7/

It would be great if this would be added to the docs as it allows more elaborate exception tracing when you don't have the throwing side under your control. Good for error reporting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e34c172-4541-ebaf-058e-66b4b1e9e5b5
* Version Independent ID: ce270ef7-3fd5-d154-60b8-bed38b33cb8e
* Content: [X++ exception handling - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-ref/xpp-exceptions)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-ref/xpp-exceptions.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/dev-ref/xpp-exceptions.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @RobinARH
* Microsoft Alias: **tfehr**

**Comment by twheeloc** [comment]
@torbennehmer, thank you for providing this feedback.

@jorisdg, please review and updated the content as needed.
