### ISSUE TITLE
Admin user provisioning tool should not have been removed from LCS deployments.

### ISSUE THREAD

**Issue by DevinSharp** [MicrosoftDocs/dynamics-365-unified-operations-public#3821]
[Enter feedback here]

Why was the admin user provisioning tool removed from LCS deployed environments? If we perform a database restore from a higher environment where we don't have access (such as from prod), we lose access to our development environment and have to go add ourselves back in manually via SQL like it's 2012 again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe3913a6-4daa-9973-6f0b-d7ae4c1007c2
* Version Independent ID: f2cd311b-fcb8-cff4-57a3-47c3c52b19d6
* Content: [Deploy and access development environments - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/access-instances)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/access-instances.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/dev-tools/access-instances.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by twheeloc** [comment]
@DevinSharp, thank you for providing this feedback.

@laneswenka, can you answer the above question?
