### ISSUE TITLE
Need to know what Data Entity has the information indicating if a worker is a time registration worker or not

### ISSUE THREAD

**Issue by ronsonntag54** [MicrosoftDocs/dynamics-365-unified-operations-public#3822]
[Enter feedback here]
Please provide the Data Entity that contains this time registration status (Yes/No? Something else?) Need to load thousands of records and need to know what Data Entity and what Field holds the information to indicate if a worker is time registration worker or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5dba412-dd58-e872-f935-71d0f3edf5c1
* Version Independent ID: edfaef7a-1b8e-a0a3-ee25-d0c307711970
* Content: [Time and attendance registration overview - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/production-control/time-attendance-registrations)
* Content Source: [articles/supply-chain/production-control/time-attendance-registrations.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/production-control/time-attendance-registrations.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @johanhoffmann
* Microsoft Alias: **johanho**

**Comment by twheeloc** [comment]
Please contact Microsoft Support for your issue. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support).
