### ISSUE TITLE
Getting permission Denied. 

### ISSUE THREAD

**Issue by oliverremo** [MicrosoftDocs/dynamics-365-unified-operations-public#3826]
[Enter feedback here]

We are getting error trying to use the API. 
![image](https://user-images.githubusercontent.com/95265056/153137076-50057dcc-4da6-464f-a2a3-3521778da7b7.png)
we used reference: https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/api/dbmovement-api-authentication to generate the bearer token but still getting issue
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19a4a56e-f1d8-4185-a78c-31e265c069cf
* Version Independent ID: 111c0ca3-6ae7-ce89-6e76-d108eac6699b
* Content: [Fetch an environment's RSAT certificate in a zip file - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/api/v1/reference-download-rsat-certificate)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/api/v1/reference-download-rsat-certificate.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/lifecycle-services/api/v1/reference-download-rsat-certificate.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @jorichar
* Microsoft Alias: **jorichar**

**Comment by twheeloc** [comment]
Please contact Microsoft Support for your issue. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support).
