### ISSUE TITLE
A few pieces of information in this article are wrong

### ISSUE THREAD

**Issue by touraji** [MicrosoftDocs/dynamics-365-unified-operations-public#3828]
Currently, the article shows the following information that is wrong:

Create > Movement – Create and post a movement journal for the selected transaction. For under transactions, a movement journal is automatically created and posted for the difference between the expected and actual received quantity. **Select this command for over transactions if you want the vendor to realize the cost difference.**

Create > Purchase order – Create a purchase order for the difference between the expected and actual received quantity of the selected transaction. **Select this command for over transactions if your organization will realize the cost difference.**

The article should be corrected to show the following:

Create > Movement – Create and post a movement journal for the selected transaction. For under transactions, a movement journal is automatically created and posted for the difference between the expected and actual received quantity. **Select this command for over transactions if your organization will realize the cost difference.**

Create > Purchase order – Create a purchase order for the difference between the expected and actual received quantity of the selected transaction. **Select this command for over transactions if you want the vendor to realize the cost difference.**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4687f34-942a-38df-24c6-c52cc700b16e
* Version Independent ID: 9487eeeb-4138-8027-74f1-26b667dadb49
* Content: [Over/under transactions - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/landed-cost/over-under-transactions)
* Content Source: [articles/supply-chain/landed-cost/over-under-transactions.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/landed-cost/over-under-transactions.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @sherry-zheng
* Microsoft Alias: **chuzheng**

**Comment by twheeloc** [comment]
@touraji, thank you for providing this feedback.

@sherry-zheng, please review and update the content as needed.

**Comment by josaw1** [comment]
Closed as won't fix.
