### ISSUE TITLE
super() call missing

### ISSUE THREAD

**Issue by BeatVogel** [MicrosoftDocs/dynamics-365-unified-operations-public#3829]
I believe in Step 3 in the example of the delete() method, the super call is missing.
It should be before the ttscommit.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4d9c70c-d7e3-9c58-7b78-bdd04dde4dfe
* Version Independent ID: 8ac8877f-3968-3f5f-d05e-cf01aa42c358
* Content: [Make backing tables consumable as financial dimensions - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/financial/dimensionable-entities)
* Content Source: [articles/fin-ops-core/dev-itpro/financial/dimensionable-entities.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/financial/dimensionable-entities.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @RyanCCarlson2
* Microsoft Alias: **rcarlson**

**Comment by twheeloc** [comment]
@BeatVogel, thank you for providing this feedback.

@RyanCCarlson2, please review the feedback and update the content as needed.
