### ISSUE TITLE
How to cancel a support case I created?

### ISSUE THREAD

**Issue by diab-mossa** [MicrosoftDocs/dynamics-365-unified-operations-public#383]
How to cancel a support case that I created, and before Microsoft started handling it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e58250c-39f9-1f28-4681-7fd34758a274
* Version Independent ID: 63aa15c7-6030-5d32-9405-5a2453ef2a8e
* Content: [Manage Finance and Operations support experiences - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/cloud-powered-support-lcs)
* Content Source: [articles/dev-itpro/lifecycle-services/cloud-powered-support-lcs.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/lifecycle-services/cloud-powered-support-lcs.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @kfend
* Microsoft Alias: **anupams**

**Comment by ShylaThompson** [comment]
@diab-mossa Thanks for your question. I reached out to my colleagues about this question and this was the response: 

"Currently there’s no UI control from LCS for user to cancel a submitted support case. 

Each support case is assigned to a support engineer who will send out an initial response email within a couple hours, customer will work with the assigned support engineer to resolve or cancel the support case via email."

Please consider suggesting this feature as an Idea on the [Ideas site](https://experience.dynamics.com/ideas/list/?forum=16691718-61e2-e611-8101-5065f38b21f1).
