### ISSUE TITLE
Enter comment to reset Data Mart

### ISSUE THREAD

**Issue by mrlopezco** [MicrosoftDocs/dynamics-365-unified-operations-public#3830]
After changing the financial dimension sequence, it is required to reset the Data Mart in order to see the changes in the reports.
Would be great to add this to the documentation. Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e429cac-5092-03ec-71e4-425af9623908
* Version Independent ID: b88220bd-7b7c-2f9b-1eb2-212d7b9a3448
* Content: [Financial dimension configuration - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/financial/financial-dimension-configuration-integration)
* Content Source: [articles/fin-ops-core/dev-itpro/financial/financial-dimension-configuration-integration.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/financial/financial-dimension-configuration-integration.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @RyanCCarlson2
* Microsoft Alias: **rcarlson**

**Comment by twheeloc** [comment]
@gersp, thank you for providing this feedback.

@RyanCCarlson2, please review the feedback and update the content as needed.

**Comment by RyanCCarlson2** [comment]
Got it. Agree with the suggested comment. I'll review with the engineer to verify any other
