### ISSUE TITLE
Evento R-2020

### ISSUE THREAD

**Issue by inove22** [MicrosoftDocs/dynamics-365-unified-operations-public#3831]
Por gentileza, detalhar a configuração do INSS - setup de código de imposto utilizado:

Evento R-2020 - Serviços fornecidos
O evento periódico R-2020 é usado para relatar, ao sistema da autoridade fiscal, as informações sobre os valores de retenção para a previdência social que estão presentes em notas fiscais de serviço emitidas pelos estabelecimentos fiscais de uma organização fiscal.

Esse evento funciona como o evento R-2010, mas você deve considerar as contas de cliente e o modelo de nota fiscal SE (saída) que é emitido pelo estabelecimento fiscal.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: b9408285-78ac-f1db-f32b-9471e58bc9fc
* Version Independent ID: f0837934-3afd-c665-2487-7b94b2d0c1ae
* Content: [Eventos SPED-Reinf - Finance | Dynamics 365](https://docs.microsoft.com/pt-br/dynamics365/finance/localizations/latam-bra-sped-reinf)
* Content Source: [articles/finance/localizations/latam-bra-sped-reinf.md](https://github.com/MicrosoftDocs/Dynamics-365-Operations.pt-br/blob/live/articles/finance/localizations/latam-bra-sped-reinf.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @sndray
* Microsoft Alias: **sndray**

**Comment by josaw1** [comment]
Closing as won't fix.
