### ISSUE TITLE
Evento R-2060 – INSS CPRB

### ISSUE THREAD

**Issue by inove22** [MicrosoftDocs/dynamics-365-unified-operations-public#3832]
Favor detalhar o setup do imposto para INSS CPBR a forma de cálculo pela apuração.

Evento R-2060 – INSS CPRB

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: b9408285-78ac-f1db-f32b-9471e58bc9fc
* Version Independent ID: f0837934-3afd-c665-2487-7b94b2d0c1ae
* Content: [Eventos SPED-Reinf - Finance | Dynamics 365](https://docs.microsoft.com/pt-br/dynamics365/finance/localizations/latam-bra-sped-reinf)
* Content Source: [articles/finance/localizations/latam-bra-sped-reinf.md](https://github.com/MicrosoftDocs/Dynamics-365-Operations.pt-br/blob/live/articles/finance/localizations/latam-bra-sped-reinf.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @sndray
* Microsoft Alias: **sndray**

**Comment by twheeloc** [comment]
@inove22, thank you for providing this feedback.

@sndray, please review the feedback and update the content as needed.

**Comment by josaw1** [comment]
Closing as won't fix.
