### ISSUE TITLE
warehouse app store link dead

### ISSUE THREAD

**Issue by RobvanB** [MicrosoftDocs/dynamics-365-unified-operations-public#3833]
The link to the app store brings up the app, but when you click to install it says it cannot find it.
[Warehouse Management on Microsoft Store](https://www.microsoft.com/store/apps/9pd35cdqcmg3)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc2ac844-c345-707a-b2e9-5d4edf7c8541
* Version Independent ID: ae6e65c3-c1e1-c4cc-e05c-1c2ebd4bafc6
* Content: [Install and connect the Warehouse Management mobile app - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/warehousing/install-configure-warehouse-management-app)
* Content Source: [articles/supply-chain/warehousing/install-configure-warehouse-management-app.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/warehousing/install-configure-warehouse-management-app.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @Mirzaab
* Microsoft Alias: **mirzaab**

**Comment by twheeloc** [comment]
@RobvanB, thank you for providing this feedback.

@Mirzaab, please review the feedback and update the content as needed.
