### ISSUE TITLE
Purchase requisition schema sample is not generated from sample in Parse Json as described in this page

### ISSUE THREAD

**Issue by sisbio** [MicrosoftDocs/dynamics-365-unified-operations-public#3834]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91d6f12b-8071-1e29-67e1-82d47562ee61
* Version Independent ID: e2c186f8-0701-fab1-c806-32632e8ad8b5
* Content: [Business events and workflow approvals - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/business-events/how-to/how-to-workflow)
* Content Source: [articles/fin-ops-core/dev-itpro/business-events/how-to/how-to-workflow.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/business-events/how-to/how-to-workflow.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by Sunil-Garg** [comment]
@Jared ***@***.***>
________________________________
From: sisbio ***@***.***>
Sent: Sunday, February 13, 2022 9:40:07 PM
To: MicrosoftDocs/dynamics-365-unified-operations-public ***@***.***>
Cc: Sunil Garg ***@***.***>; Mention ***@***.***>
Subject: [MicrosoftDocs/dynamics-365-unified-operations-public] Purchase requisition schema sample is not generated from sample in Parse Json as described in this page (Issue #3834)


[Enter feedback here]

________________________________
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

  *   ID: 91d6f12b-8071-1e29-67e1-82d47562ee61
  *   Version Independent ID: e2c186f8-0701-fab1-c806-32632e8ad8b5
  *   Content: Business events and workflow approvals - Finance & Operations | Dynamics 365<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fdynamics365%2Ffin-ops-core%2Fdev-itpro%2Fbusiness-events%2Fhow-to%2Fhow-to-workflow&data=04%7C01%7Csunilg%40microsoft.com%7Cadfefabb3e564324fd5f08d9ef7c75b6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637804140112256631%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=W2uZwPdO1rUsGZcjqq5Cx7Am3fiCpTbXuvjWtRp0y%2Fc%3D&reserved=0>
  *   Content Source: articles/fin-ops-core/dev-itpro/business-events/how-to/how-to-workflow.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FDynamics-365-Unified-Operations-Public%2Fblob%2Fmain%2Farticles%2Ffin-ops-core%2Fdev-itpro%2Fbusiness-events%2Fhow-to%2Fhow-to-workflow.md&data=04%7C01%7Csunilg%40microsoft.com%7Cadfefabb3e564324fd5f08d9ef7c75b6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637804140112256631%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=7gVhxenxMjrf0lUuy1b6JH30jAAn77WSSL9Om6TZvPU%3D&reserved=0>
  *   Service: dynamics-365-cross-app
  *   Product: ****
  *   Technology: ****
  *   GitHub Login: @Sunil-Garg<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSunil-Garg&data=04%7C01%7Csunilg%40microsoft.com%7Cadfefabb3e564324fd5f08d9ef7c75b6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637804140112306630%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Seyp0vot5Cumgngq8bMZ1R6O8sJOVISUAYDdvTm7r6Y%3D&reserved=0>
  *   Microsoft Alias: sunilg

—
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fdynamics-365-unified-operations-public%2Fissues%2F3834&data=04%7C01%7Csunilg%40microsoft.com%7Cadfefabb3e564324fd5f08d9ef7c75b6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637804140112306630%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=dljX4taBNZEZ8hJUHVF0Vm%2B9bLWFoT146yACe3t%2BFvE%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHNKDWYL5H52AZTIBGJRDWDU3CITPANCNFSM5OKM6UQA&data=04%7C01%7Csunilg%40microsoft.com%7Cadfefabb3e564324fd5f08d9ef7c75b6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637804140112306630%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=YZTPzqNy6UdVsmdQH77Y7sAcKWX5N9gJM2wqpU7mmhE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Csunilg%40microsoft.com%7Cadfefabb3e564324fd5f08d9ef7c75b6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637804140112306630%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=PWlCJxpH%2FQl1OxZLQmtSq%2FwyjQOus0gUP244gWygjm4%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Csunilg%40microsoft.com%7Cadfefabb3e564324fd5f08d9ef7c75b6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637804140112306630%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=jCPjdLB69uA5lQ66S%2FcMgda%2FkF0eEQUv0RmqqJSbOQg%3D&reserved=0>.

**Comment by sisbio** [comment]
Ok, I got it. Schema is downloaded from D365 Finance and Operation in business events.


Jun Zeng | D365FO & Dynamics AX

Irvine, CA 92620, USA | +1 949.208.6170

***@***.***>/blog


 [cid:f7822f17-3f89-4f9e-a496-837e6f1844b2] <https://www.linkedin.com/in/junzeng/>




________________________________
