### ISSUE TITLE
Error on Account receivable with reverse charge

### ISSUE THREAD

**Issue by anboudin** [MicrosoftDocs/dynamics-365-unified-operations-public#3835]
in document,  it is written **_If the sales tax code is reverse charge, then sales tax direction is Sales Tax Receivable._**
I reverse charge is setup, no tax direction is modified. 
from PM feedback, the document is wrong. 

can you please update the document to avoid customer confusion and misused on reverse charge?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3aaea6b3-d996-eb5c-0a4e-82454d5a1bf0
* Version Independent ID: 523a07d8-d3b5-eba1-4a5d-f5c6c3f90448
* Content: [Sales tax calculation on general journal lines - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/general-ledger/sales-tax-calculation-on-general-journal)
* Content Source: [articles/finance/general-ledger/sales-tax-calculation-on-general-journal.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/general-ledger/sales-tax-calculation-on-general-journal.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @EricWangChen
* Microsoft Alias: **wangchen**

**Comment by tonyafehr** [comment]
@anboudin, thanks for the feedback. @EricWangChen, please review and make needed updates to this topic.

**Comment by tonyafehr** [comment]
Bug 660437 created to track this issue.

**Comment by Kai-Cloud** [comment]
Hi, the related statement (and diagram) has been removed via [PR 13216](https://github.com/MicrosoftDocs/Dynamics-365-Operations/pull/13216)
