### ISSUE TITLE
Limited role for Power Platform integration

### ISSUE THREAD

**Issue by harishmohanbabu** [MicrosoftDocs/dynamics-365-unified-operations-public#3836]
The 'Note' section in this article states _**" a more limited role for this integration will eventually be added to Azure AD ... "**._

Can you advise when this new role would be made available, please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae234693-3a0a-d25c-ecd1-abd01ad7580f
* Version Independent ID: ae234693-3a0a-d25c-ecd1-abd01ad7580f
* Content: [Enable the Microsoft Power Platform integration - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/power-platform/enable-power-platform-integration)
* Content Source: [articles/fin-ops-core/dev-itpro/power-platform/enable-power-platform-integration.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/power-platform/enable-power-platform-integration.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @jaredha
* Microsoft Alias: **jaredha**

**Comment by tonyafehr** [comment]
@jaredha, please review this feedback. Thanks!

**Comment by tonyafehr** [comment]
Bug 660438 created to track this issue.

**Comment by jaredha** [comment]
@laneswenka, can you take a look at this?
