### ISSUE TITLE
Resources in Visual Studio

### ISSUE THREAD

**Issue by lukasnimberger** [MicrosoftDocs/dynamics-365-unified-operations-public#3837]
Hello,

this page says "You can find the required resource files under the Resources node in Application Explorer in Microsoft Visual Studio." Could you please add more details about where exactly I can find the necessary files in Visual Studio? Or add a link to some other manual?

Thank you,
Lukas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f6257c7-8c1f-f00a-4f51-2f8f20f1f09e
* Version Independent ID: c793b57d-f984-bb4d-d014-e2bf2da43f68
* Content: [Set up the advanced bank reconciliation import process - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/cash-bank-management/set-up-advanced-bank-reconciliation-import-process)
* Content Source: [articles/finance/cash-bank-management/set-up-advanced-bank-reconciliation-import-process.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/cash-bank-management/set-up-advanced-bank-reconciliation-import-process.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @panolte
* Microsoft Alias: **panolte**

**Comment by tonyafehr** [comment]
@lukasnimberger, thanks for your inquiry. @panolte, please review.

**Comment by tonyafehr** [comment]
Bug 660442 created to track this issue.

**Comment by tonyafehr** [comment]
@lukasnimberger, this was reviewed. The documentation is correct and Microsoft Visual Studio works as expected. The details can be found in the "Samples files" section of [Set up the advanced bank reconciliation import process](https://docs.microsoft.com/dynamics365/finance/cash-bank-management/set-up-advanced-bank-reconciliation-import-process).
