### ISSUE TITLE
Extensions?

### ISSUE THREAD

**Issue by soerenpc** [MicrosoftDocs/dynamics-365-unified-operations-public#3839]
What about a section on how-to extend this (with code)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35765cda-23fb-5b94-0856-7002e37dadd3
* Version Independent ID: 82c39d58-a4e3-4562-53ab-131b831ec987
* Content: [Archive inventory transactions - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/inventory/archive-inventory-transactions)
* Content Source: [articles/supply-chain/inventory/archive-inventory-transactions.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/inventory/archive-inventory-transactions.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @yufeihuang
* Microsoft Alias: **yufeihuang**

**Comment by tonyafehr** [comment]
@soerenpc, thanks for the feedback. @yufei-huang, please review and make updates as needed.

**Comment by tonyafehr** [comment]
Bug 660444 created to track this issue.
