### ISSUE TITLE
Dual-write organization hierarchy wording update

### ISSUE THREAD

**Issue by cschreuderhsoint** [MicrosoftDocs/dynamics-365-unified-operations-public#3841]
Just some content to be fixed.

1. Description under **Templates** header refers to products.
2. First row in table, legal entities to cdm_companies; the description is wrong as this is not a bidirectional sync.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f50014f8-3ee8-a3ba-e5aa-41c83ec1ba41
* Version Independent ID: a2a2259c-e95c-158a-6dfb-c58da4b23937
* Content: [Organization hierarchy in Dataverse - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/organization-mapping)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/organization-mapping.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/dual-write/organization-mapping.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @RamaKrishnamoorthy
* Microsoft Alias: **ramasri**

**Comment by tonyafehr** [comment]
Bug 660445 created to track this issue.

**Comment by tonyafehr** [comment]
This topic has been updated. Thanks!
