### ISSUE TITLE
Documentation Incorrect - Grace days may be simultaneously set up and not set up for posting checkpoints

### ISSUE THREAD

**Issue by jkbirch** [MicrosoftDocs/dynamics-365-unified-operations-public#3842]
[Enter feedback here]
The documentation on the page appears to be incorrect or out of date. The following statement does not appear to be true: "You can't specify grace days for some posting checkpoints but not for others. You must set up all posting checkpoints so that they have grace days, or you must set them all up so that they don't have grace days." In the Contoso environment in the USMF company, grace days are set up for some posting checkpoints and not others.

Cheers,
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3811d721-fe31-3a4e-394d-b6d546bc42c2
* Version Independent ID: 9a0581a7-d8ed-648e-e6eb-3f831755cd38
* Content: [Credit management parameters setup - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/accounts-receivable/cm-credit-mgmt-setup)
* Content Source: [articles/finance/accounts-receivable/cm-credit-mgmt-setup.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/accounts-receivable/cm-credit-mgmt-setup.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
![Credit and Collection Doc Issue](https://user-images.githubusercontent.com/78776874/154285925-ffbc4044-5b5d-474a-81b1-4771113b50f4.jpg)

* GitHub Login: @JodiChristiansen
* Microsoft Alias: **roschlom**

**Comment by tonyafehr** [comment]
@jkbirch, thank you for the feedback. @JodiChristiansen, please review.

**Comment by JodiChristiansen** [comment]
Thank you for the feedback. The documentation has been updated to make this more clear.
