### ISSUE TITLE
Comment we recieved several cases where customer apply reverse charge directly on ledger account.

### ISSUE THREAD

**Issue by anboudin** [MicrosoftDocs/dynamics-365-unified-operations-public#3848]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 687a84b6-c1d1-6141-4175-8aa8860d05db
* Version Independent ID: f70b95f2-8312-7165-6673-f353d0627d81
* Content: [Reverse charge mechanism for VAT/GST scheme - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/emea-reverse-charge)
* Content Source: [articles/finance/localizations/emea-reverse-charge.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/emea-reverse-charge.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @epodkolz
* Microsoft Alias: **epodkolz**

**Comment by tonyafehr** [comment]
@anboudin, thanks for the feedback. @epodkolz, please review and consider making updates.

**Comment by epodkolz** [comment]
@anboudin, Could you please elaborate on the limitation? The reverse charge functionality is built on top of the core tax – and in core tax engine supports posting to ledger account.
Thank you!

**Comment by anboudin** [comment]
We explain to customer that tax calculation will be done correctly if vendor is in journal.

As we have several cases with same scenario reported, may be could be good to specify it
I know process is not expected, but can be good to add it on MS documentation.

***@***.***
***@***.***

Cordialement/Best Regards
Annaick
Tel: +33 15775 7012

[MSFT_logo_Gray DE sized SIG1.png]

Team Manager | Marwa Ibrahim Ali  ***@***.******@***.***>)
