### ISSUE TITLE
does the Warehouse mobile device user role require a dynamics 365 license?

### ISSUE THREAD

**Issue by jlabustro** [MicrosoftDocs/dynamics-365-unified-operations-public#3851]
does the Warehouse mobile device user role require a dynamics 365 license? Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5522e9c-48f4-0185-3e23-d56b9fd37e03
* Version Independent ID: 871c5530-6c5c-95ac-1df5-3ee5f0934e48
* Content: [Mobile device user settings - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/warehousing/mobile-device-user-settings)
* Content Source: [articles/supply-chain/warehousing/mobile-device-user-settings.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/warehousing/mobile-device-user-settings.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @Mirzaab
* Microsoft Alias: **mirzaab**

**Comment by twheeloc** [comment]
@jlabustro, Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support).
