### ISSUE TITLE
Wrong section/title and update for deprecation of vs2017-win2016 build agent

### ISSUE THREAD

**Issue by andyNewnham** [MicrosoftDocs/dynamics-365-unified-operations-public#3852]
Title of the article is 'Commerce SDK' however the content is specifically for the legacy 'RetailSDK'. I believe the article should also be moved under the folder 'Retail SDK (Legacy)' to avoid confusion.

The first paragraph states: 'To generate the build for Retail SDK, a dedicated build machine isn't required' - As of March 2022, with the deprecation of the vs2017-win2016 build agent, this is no longer true, as documented here: https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/retail-sdk/mpos-build-agent#why-cant-i-use-an-azure-devops-hosted-agent

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd465bf3-be18-a1ac-76d1-23dc8ff06ea4
* Version Independent ID: f8c4ea31-1332-763b-ab5e-d5e7197f8a5f
* Content: [Set up Commerce SDK build pipeline - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/retail-sdk/sdk-build-pipeline)
* Content Source: [articles/commerce/dev-itpro/retail-sdk/SDK-build-pipeline.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/retail-sdk/SDK-build-pipeline.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by twheeloc** [comment]
@andyNewnham, thank you for providing this feedback.

@mugunthanm, please review the feedback and update the content as needed.

**Comment by mugunthanm** [comment]
@andyNewnham - Thanks for the feedback, updated the docs.
