### ISSUE TITLE
Setting order attribute issue. 

### ISSUE THREAD

**Issue by UbaidUrRehmannn** [MicrosoftDocs/dynamics-365-unified-operations-public#3853]
I had a task where I have to change the order attribute on click or before checking out. I used OnClick on checkout as a guest button and used the code mentioned in this article label as JavaScript. when I used that function it gave me too many errors. 

I solved all of them most of them are imports but the main issue is "GetCheckoutCartInput(this.props.context.request.apiSettings), newCart)" this thing. it is an API call that was working in the previous version of the code. but now this API is removed and to change order attributes there is a built-in function that we can access by using "this.props.data.cart.result?.updateAttributeValues( )". I am suggesting that you should update the code in JavaScript with this code below that is working.

`private _addOrUpdateSalesOrderAttributes = async ( ) => {
        const attributeArr: AttributeValueBase[ ] = [ ];

        let attributeObj = {
            '@odata.type': '#Microsoft.Dynamics.Commerce.Runtime.DataModel.AttributeTextValue',
            Name: 'First Attribute',
            ExtensionProperties: [ ],
            TextValue: 'Value of first attribute',
            TextValueTranslations: [ ]
        };
        attributeArr.push(attributeObj);

        attributeObj = {
            '@odata.type': '#Microsoft.Dynamics.Commerce.Runtime.DataModel.AttributeTextValue',
            Name: 'Second Attribute',
            ExtensionProperties: [ ],
            TextValue: 'Value of second attribute',
            TextValueTranslations: [ ]
        };
        attributeArr.push(attributeObj);

        this.props.data.cart.result?.updateAttributeValues({
            newAttributeValues: attributeArr
        });
    }; `

I used this function in the cart page on the guest checkout button also I removed its href URL so I can stay at this page and observe the change. I am working on fabrikam code in sl training environment.

Now after using this code and this function in onClick I can change order attributes that are coming from finance and operations to my custom attributes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: daca1f9e-c913-eb05-1a7d-23e6a54fc782
* Version Independent ID: f6ab1665-4c15-c2ed-9bf0-f5411295840a
* Content: [Define and set order attributes - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/order-attributes)
* Content Source: [articles/commerce/dev-itpro/order-attributes.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/order-attributes.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by twheeloc** [comment]
@UbaidUrRehmannn, thank you for providing this feedback.

@mugunthanm, please review the feedback and update the content as needed.

**Comment by mugunthanm** [comment]
Adding @samjarawan to help with this.

**Comment by josaw1** [comment]
Closing as won't fix.
