### ISSUE TITLE
rebate management method "Rate"

### ISSUE THREAD

**Issue by akaradagi** [MicrosoftDocs/dynamics-365-unified-operations-public#3854]
[Feedback:  I propose to alter the following for the rebate management method documentation. The "rate" rebate management method seems to work per article in an order:
old:
<html>
<body>

Rebate management method | This field is available only for deals where the Rebate output field on the header is set to Financial. Select the method to use to calculate the rebate:Fixed – A fixed price amount is used for the line.Percent – A percentage of the sale amount is used.Rate – _A fixed price amount per order is used._
-- | --

</body>
</html>]
new:
<html>
<body>

Rebate management method | This field is available only for deals where the Rebate output field on the header is set to Financial. Select the method to use to calculate the rebate:Fixed – A fixed price amount is used for the line.Percent – A percentage of the sale amount is used.Rate – A fixed price amount per _order item_ is used.
-- | --

</body>
</html>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1646986-d690-52b3-d567-e962a2715d7b
* Version Independent ID: ab20269c-b0b3-6d4c-5afc-afd9b24a8e14
* Content: [Rebate management deals - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/rebate-management/rebate-management-deals)
* Content Source: [articles/supply-chain/rebate-management/rebate-management-deals.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/rebate-management/rebate-management-deals.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @sherry-zheng
* Microsoft Alias: **chuzheng**

**Comment by twheeloc** [comment]
@akaradagi, thank you for providing this feedback.

@sherry-zheng, please review this feedback and update the content as needed.

**Comment by josaw1** [comment]
Closing as won't fix.
