### ISSUE TITLE
Old information - 

### ISSUE THREAD

**Issue by MSFTRANDY** [MicrosoftDocs/dynamics-365-unified-operations-public#3855]
I believe this page is for the old way of publishing products to our SharePoint integrated online store solution and not the new ecommerce solution.  This should be pointed out as to not confuse customers and Partners who are trying to follow this document to configure catalogs with our newer ecommerce solution only to find out it doesn't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0bad4f6-81db-e901-b788-0e6b7115573f
* Version Independent ID: ec7729ea-d9bb-f4bc-1a36-a30d80372f1b
* Content: [Publish an online store catalog - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/retail-online-store-publishing-architecture)
* Content Source: [articles/commerce/dev-itpro/retail-online-store-publishing-architecture.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/retail-online-store-publishing-architecture.md)
* Service: **dynamics-365-commerce**
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by twheeloc** [comment]
@MSFTRANDY, thank you for providing this feedback.

@mugunthanm, please review the feedback and update the content as needed.

**Comment by mugunthanm** [comment]
Adding @ashishmsft to help with this.

**Comment by josaw1** [comment]
Closing as won't fix.
