### ISSUE TITLE
Parallell imports explanation is incorrect, or at the very least misleading

### ISSUE THREAD

**Issue by danbudimir** [MicrosoftDocs/dynamics-365-unified-operations-public#3856]
[Parallel imports](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/data-import-export-job#parallel-imports)

This explanation is incorrect, or at the very least, misleading, it leads the reader to believe that the threshold is actually the number of records that will be processed by each task.  There are several blog posts, etc. by non MS folks out there that are incorrect.  We are also interchanging the term “Task” and “Thread”, one is the same as the other in this documentation's context, but it can be confusing.

•	In the **Import threshold record count** field, enter the threshold record count for import. This determines the record count to be processed by a thread. If a file has 10K records, a record count of 2500 with a task count of 4 will mean, each thread will process 2500 records.

The example we provide further gets misinterpreted that each task would always process 2500 records because 10K is evenly divisible by 2500 and the task count is 4, this is exactly 10,000.  This leads some readers to think, if my import **Task count** was 4, my **Import threshold record count** was 2500 and I uploaded 3000 records, one task would process 2500, one would process 500, the other 2 would do nothing.  This is not the case.

I’m submitting that we change it to

•	In the **Import threshold record count** field, enter the threshold record count for import. This determines the number of records that need to be in the import file for an **Entity import execution parameter** to go into effect. (e.g. If a file has 14264 records, your execution parameter has an **Import threshold record count** of 2500 with a **Task count** of 4, each task will process 3566 (14264 divided by 4) records.)  In the event a file with a record count that is not evenly divisible by the number of tasks is processed, the last task will handle the modulus. (e.g.  If the file had 14263 records, tasks 1, 2 and 3 would process 3565 records, task 4 would process 3568.)

You can also set different thresholds and task counts for the same entity, this enables you to assign larger task counts to larger input files.

![image](https://user-images.githubusercontent.com/8561771/155594097-abf18a18-f590-4c37-919e-9be5ba57fb99.png)
 
Using the setup above
1. Any file with 2000 or more records, but less than 4000, would process on 4 tasks.
2. Any file with 4000 or more records, but less than 6000, would process on 6 tasks.
3. Any file with 6000 or more records would process on 8 tasks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d35f4fb2-1296-20ef-56c2-a2c5aa00befe
* Version Independent ID: 0d515af9-9419-4f21-223e-25344cf1bfe8
* Content: [Data import and export jobs overview - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/data-import-export-job)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/data-import-export-job.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/data-import-export-job.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Peakerbl
* Microsoft Alias: **peakerbl**

**Comment by twheeloc** [comment]
@danbudimir, thank you for providing this feedback.

@Peakerbl, please review the feedback and update the content as needed.

**Comment by danbudimir** [comment]
@Peakerbl , where are we at with this?  Inquiring minds want to know. :-)

**Comment by josaw1** [comment]
Closing as won't fix.
