### ISSUE TITLE
Wrong reference of "Enabel access"

### ISSUE THREAD

**Issue by d47447** [MicrosoftDocs/dynamics-365-unified-operations-public#3857]
[Enter feedback here]

In this page section ""Environment lifecycle operations". There is point for "Enable access" on dev box which is not availabel any more on LCS. Please check and udpa the article accordingly. 

Many Thanks
Deepak
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5080f3d7-0ad1-940c-284a-92008d7c19d5
* Version Independent ID: c911e39b-82ee-2ae3-4493-d2e39afccc2b
* Content: [Cloud deployment overview - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/cloud-deployment-overview)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/cloud-deployment-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/deployment/cloud-deployment-overview.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by twheeloc** [comment]
@d47447, thank you for providing feedback.

@laneswenka, please review this feedback and update the content as needed.

**Comment by josaw1** [comment]
@twheeloc can you please have this entire article reviewed? Thanks.

**Comment by josaw1** [comment]
Closed as won't fix.
