### ISSUE TITLE
Deprecation notice is inconsistent with replacement feature availability

### ISSUE THREAD

**Issue by andypicking** [MicrosoftDocs/dynamics-365-unified-operations-public#3858]
The notice at this point on the page https://docs.microsoft.com/en-us/dynamics365/supply-chain/get-started/removed-deprecated-features-scm-updates#use-of-built-in-supply-chain-management-master-planning-engine-for-manufacturing-scenarios 

is inconsistent with  replacement feature availability on this page 

https://docs.microsoft.com/en-us/dynamics365/supply-chain/master-planning/planning-optimization/planning-optimization-fit-analysis

and the note at the top of this page -

https://docs.microsoft.com/en-us/dynamics365/supply-chain/master-planning/planning-optimization/get-started

If you are a cloud deployment and using master planning and generating planned production orders you have to continue using the existing engine and evaluate your ability to migrate.

Looking at the replacement feature availability on this page 

There are many features, including for example, batch disposition codes that many process manufacturers use that won't be supported until at least October 2022.

If you are a customer that needs those features (I have several customers in this position), you have Microsoft telling you that the software you are currently using is deprecated and isn't supported (unless you are an on premise customer) and yet you can't use the replacement features either as they don't exist yet.

Microsoft should clarify the deprecation and 'unsupported' points to indicate that existing customers who are dependent on features in the existing planning engine and who are waiting for new features to be made available will still be supported until the new features are available to test.

I have several customers who are concerned that Microsoft is leaving them 'in limbo'.

Hoping you can add some clarifying wording to suit all requriements.

Thanks
Andy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60ff0ecf-cab1-5665-554e-ec493c3a6159
* Version Independent ID: e02b7a35-a15f-9205-d084-b3498eddc842
* Content: [Removed or deprecated features in Dynamics 365 Supply Chain Management - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/get-started/removed-deprecated-features-scm-updates)
* Content Source: [articles/supply-chain/get-started/removed-deprecated-features-scm-updates.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/get-started/removed-deprecated-features-scm-updates.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @kamaybac
* Microsoft Alias: **kamaybac**

**Comment by twheeloc** [comment]
@andypicking, thank you for providing this feedback.

@kamaybac, please review this feedback and update the content as needed.
