### ISSUE TITLE
Mandatory fields for VAT declaration (CZ)

### ISSUE THREAD

**Issue by lukasnimberger** [MicrosoftDocs/dynamics-365-unified-operations-public#3864]
Hello,
 I am currently defining VAT declaration for CZ and even though some mandatory fields are part of the configuration (e.g. zast_kod, zast_typ etc.), they are disabled and I don't know why and how to potentially bring them out. 
These fields are not even specified in this documentation.
E.g. when the taxpayer type is Organization, we must define also type of the signatory person details zast_typ etc.

Could you please advise and potentially add this to the page I am referring to? 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2825361e-b3da-9b9d-16f2-90974b964d36
* Version Independent ID: d80229a2-8acc-ef01-4155-4f50b6bfe9dc
* Content: [VAT declaration (Czech Republic) - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/emea-cze-vat-declaration-tax-declaration-model#taxabletransactions)
* Content Source: [articles/finance/localizations/emea-cze-vat-declaration-tax-declaration-model.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/emea-cze-vat-declaration-tax-declaration-model.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @Anasyash
* Microsoft Alias: **anasyash**

**Comment by lukasnimberger** [comment]
Hi,

could you please direct me to the page where I can raise the service request? Thank you.

**Comment by Anasyash** [comment]
I think you should open it in LCS https://lcs.dynamics.com/v2

**Comment by kamaybac** [comment]
@lukasnimberger , thank you for sending your feedback. It looks like this is actually a service request, so I am closing this as a documentation issue. Please let us know if there is still a documentation issue here that you would like to have addressed. Thanks.
