### ISSUE TITLE
Further clarification needed for cloud powered search overview

### ISSUE THREAD

**Issue by Kielkenny** [MicrosoftDocs/dynamics-365-unified-operations-public#3865]
"Product discoverability helps guarantee that customers can quickly and easily find products by browsing categories, searching, and filtering. Retailers consider product discovery a primary tool for customer interaction across all channels."

should be changed to something like:

"Product discoverability helps guarantee that customers can quickly and easily find products by browsing categories, searching, and filtering. Retailers consider product discovery a primary tool for customer interaction across POS and ecommerce channels."

and then:
The cloud-powered product discoverability in Dynamics 365 Commerce helps retailers continue to increase consumer retention and conversion rates across all channels, both e-Commerce channels and point of sale (POS) channels.

Should be changed to: 
The cloud-powered product discoverability in Dynamics 365 Commerce helps retailers continue to increase consumer retention and conversion rates across both e-Commerce channels and point of sale (POS) channels.

Background is that call center channel is not part of "all channels". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5a637ab-c379-1f22-1635-8366be0ec84c
* Version Independent ID: 52cea183-e6aa-b4eb-7f60-e53c77533d3c
* Content: [Cloud-powered search overview - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/cloud-powered-search-overview#faceted-navigation-and-choice-summary)
* Content Source: [articles/commerce/cloud-powered-search-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/cloud-powered-search-overview.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @ashishmsft
* Microsoft Alias: **asharchw**

**Comment by kamaybac** [comment]
@Kielkenny  , thank you for contacting us regarding this help topic. I have passed your comment on to the author for consideration.
