### ISSUE TITLE
Calculate average unit cost description is incorrect

### ISSUE THREAD

**Issue by iangorman2020** [MicrosoftDocs/dynamics-365-unified-operations-public#3868]
[Enter feedback here]

You have this statement for calculate average unit cost:

Calculate average unit cost – Set this option to Yes to display a column that shows the average unit cost. The average unit cost is the total quantity divided by the total amount.

It is the total amount / total quantity, not quantity / total amount.

e.g., 10 units @ $50 each = $500

$500/10 = $50/ea

Not

10/$500 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d20ffe0-4e0a-4327-8211-84f8f903e914
* Version Independent ID: 59e5d7a9-05d7-ce98-59bf-18dc8c52ab96
* Content: [Inventory value reports - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/cost-management/inventory-value-report-storage)
* Content Source: [articles/supply-chain/cost-management/inventory-value-report-storage.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/cost-management/inventory-value-report-storage.md)
* Service: **dynamics-365-supply-chain**
* GitHub Login: @banluo-ms
* Microsoft Alias: **banluo**

**Comment by kamaybac** [comment]
@iangorman2020 , thank you for reporting that error. I have updated the topic as you suggested and the fix should go live later today.
