### ISSUE TITLE
customer.driversLicense

### ISSUE THREAD

**Issue by sisbio** [MicrosoftDocs/dynamics-365-unified-operations-public#3869]
[Enter feedback here]
FMLabCustomerEntity > field > DriversLicense  ( in this page, missing "S" in copy coding for testing this entity, it is not DriverLicense, should be DriversLicense

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67eb6eeb-d9fc-4e83-6282-fff9783b1466
* Version Independent ID: f16158fb-2a9b-6429-dd3e-05d4d1e1650b
* Content: [Build and consume data entities - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/build-consuming-data-entities)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/build-consuming-data-entities.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/build-consuming-data-entities.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Peakerbl
* Microsoft Alias: **peakerbl**

**Comment by sericks007** [comment]
@sisbio, thank you for pointing this out! The content has been updated to correct this issue. Thanks again!
