### ISSUE TITLE
Application users

### ISSUE THREAD

**Issue by alneacsu** [MicrosoftDocs/dynamics-365-unified-operations-public#3870]
As Application users are no longer available in Security > Users this page needs to be updated.
How can we check the application users now?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41b5f77e-bafb-cd00-8d36-76f3a8c9ef20
* Version Independent ID: 4a17fd17-39c6-7dd8-82ed-858c6ddaec73
* Content: [Set up the mapping for the sales order status columns - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/sales-status-map#setup)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/sales-status-map.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/dual-write/sales-status-map.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @dasani-madipalli
* Microsoft Alias: **damadipa**

**Comment by kamaybac** [comment]
@alneacsu  , thank you for contacting us regarding this help topic. I have passed your comment on to the author for consideration.

**Comment by josaw1** [comment]
Closed as won't fix.
