### ISSUE TITLE
The described method in the article how to debug is not working you get an authentication failure

### ISSUE THREAD

**Issue by illese** [MicrosoftDocs/dynamics-365-unified-operations-public#3873]
[Enter feedback here]
If you follow this article, you will get a AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: '00000015-0000-0000-c000-000000000000'
Most probably the reply address needs to be modified in AAD

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb08fb04-94d5-ef25-8162-a0d79f5ee70a
* Version Independent ID: 6d43b4b7-cc2e-49bc-564a-5eb5eacefa84
* Content: [Debug a copy of the production database - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/dbmovement-scenario-debugdiag)
* Content Source: [articles/fin-ops-core/dev-itpro/database/dbmovement-scenario-debugdiag.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/database/dbmovement-scenario-debugdiag.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by kamaybac** [comment]
@illese, thank you for contacting us regarding this help topic. I have passed your comment on to the author for consideration.

**Comment by josaw1** [comment]
Closed as won't fix.
