### ISSUE TITLE
Build pipeline .\BuildTools\nugetRestore.ps1 fails if path to msbuild is not at the top of the list for the Path environment variable.

### ISSUE THREAD

**Issue by danbudimir** [MicrosoftDocs/dynamics-365-unified-operations-public#3874]
https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/retail-sdk/sdk-build-pipeline#set-up-an-azure-devops-build-pipeline-that-uses-a-build-machine

**Nuget restore** that runs in .\BuildTools\nugetRestore.ps1 relies on msbuild.  Even if you have set the msbuild step in the pipeline to use **"15.0"** and added an entry to the environment path to include C:\Program Files(x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\,  **Nuget restore** will resolve to an old version of msbuild.  This will cause nuget restore to fail.

This is an example from my pipeline

**MSBuild auto-detection: using msbuild version '3.5.30729.9034 built by: WinRelRS5' from 'C:\Windows\Microsoft.NET\Framework\v3.5'.
Error parsing solution file at C:\DynamicsSDK\VSOAgent\_work\1\s\RetailSDK\mypathtomysolution.sln: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)**

**Solution:** You have to move the entry to the Path environment variable to the top of the list to ensure nuget restore uses the correct msbuild.

Step 3, should read

3. In the build machine add the msbuild path to the **Path** environment variable.  Open **System Properties > Environment Variables > System variables**.  Select **Path**, click **New**, and add the path variable to msbuild, then use the **Move Up** button to move the new entry to the top of the list.  An example of the path is **'C:\Program Files(x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\'**.  The path depends on where you installed Visual Studio 2017.  To get the path for msbuild, open the **Developer Command Prompt for Visual Studio 2017**, and run the command **where msbuild**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd465bf3-be18-a1ac-76d1-23dc8ff06ea4
* Version Independent ID: f8c4ea31-1332-763b-ab5e-d5e7197f8a5f
* Content: [Set up Retail SDK build pipeline - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/retail-sdk/sdk-build-pipeline)
* Content Source: [articles/commerce/dev-itpro/retail-sdk/SDK-build-pipeline.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/retail-sdk/SDK-build-pipeline.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by mugunthanm** [comment]
Thanks for the feedback, updated the doc:
https://github.com/MicrosoftDocs/Dynamics-365-Operations/commit/8710ed6c137fc5fa26b2ea8312e1066d2f108421
