### ISSUE TITLE
Couple of inaccuracies in the system setup for coupons section

### ISSUE THREAD

**Issue by andypicking** [MicrosoftDocs/dynamics-365-unified-operations-public#3880]
For Step 5 there is no bar code tab, you have to add the Coupon bar code mask on the Coupons fast tab , on the prices and discounts tab within Commerce parameters.
For step 6 - the 3 number sequence codes are on the number sequence tab on the commerce parameters page and not on the commerce shared parameters page

The above apply to product version 10.0.22

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 731c7f9e-32cb-958e-23e2-88e834c1dd63
* Version Independent ID: 8b2d21fc-9a0d-d0b4-55bd-f0b0b99baf46
* Content: [Set up coupons for retail sales - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/retail-coupons)
* Content Source: [articles/commerce/retail-coupons.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/retail-coupons.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by kfend** [comment]
@andypicking - Thank you for the feedback.
@josaw1 - Can you please take a look at this and update the topic as needed? Thanks!

**Comment by josaw1** [comment]
Closed as won't fix.
