### ISSUE TITLE
Typo Link text to 10.0.26

### ISSUE THREAD

**Issue by DKobayashi-ykgw** [MicrosoftDocs/dynamics-365-unified-operations-public#3881]
Typo Link text to 10.0.26. Please fix "Platform updates for version 10.0.25 of Finance and Operations apps" to  "Platform updates for version 10.0.26 of Finance and Operations apps".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70e7efc9-280c-45da-2540-48441132e59f
* Version Independent ID: 38352051-813f-ee76-bcdb-490ac20ebb03
* Content: [What's new or changed in Platform updates - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/get-started/whats-new-home-page)
* Content Source: [articles/fin-ops-core/dev-itpro/get-started/whats-new-home-page.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/get-started/whats-new-home-page.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @sericks007
* Microsoft Alias: **tfehr**

**Comment by sericks007** [comment]
@DKobayashi-ykgw, thank you for pointing this out!  I've fixed the typo and the update will be published soon.
