### ISSUE TITLE
In Validate expected values using operators section, I try to use less than (<) and greater than (>) but RSAT is not recognized for comparison operations.

### ISSUE THREAD

**Issue by P-Chon** [MicrosoftDocs/dynamics-365-unified-operations-public#3883]
Hi feedback team,

I have a problem in Validate expected values using operators section.

I try to use less than (<) and greater than (>) but RSAT is not recognized for comparison operations.

I need to know sign that use in case less than and greater than on RSAT.

Error message:
Status: Test case failed.

(Details are also in the attached base log file (Test)_Create_customer_v3_297_BaseLog.txt)

Steps:
Navigate to: CustTable ("custtablelistpage")
Click New.
In the Customer account field, type a value. (Value used in this run = "PTC0011")
In the First name field, type a value. (Value used in this run = "Name0011")
In the Customer group field, enter or select a value. (Value used in this run = "99")
In the Sales tax group field, enter or select a value. (Value used in this run = "All")
Click Save.
On the Action Pane, click Options.
In the Department value field, enter or select a value. (Value used in this run = "024")
In the Taxbranch value field, enter or select a value. (Value used in this run = "00000")
Click OK.
Click Save.
Note the value in the Account field to reference later (Value saved in this run = "PTC0011")
Validate that the value for Customer group is '99'. (Value used in this run > "99")

ERROR:
<Message>The operator '&gt;' is not recoginized for comparison operations</Message>

DEBUG INFO:
<?xml version="1.0" encoding="utf-16"?>
<Error xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <ExceptionType>MS.Dynamics.TestTools.TestLogging.EvaluateException</ExceptionType>
  <Message>The operator '&gt;' is not recoginized for comparison operations</Message>
  <StackTrace>   at MS.Dynamics.Performance.Application.TaskRecorder.Test__Create_customer_v3Base.CompareString(String actualValue, String expectedValue, String comparisonOperator)
   at MS.Dynamics.Performance.Application.TaskRecorder.Test__Create_customer_v3Base.Test__Create_customer_v3()</StackTrace>
</Error>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84480f6c-693c-f9dc-f518-40327bee20f0
* Version Independent ID: 3544a89a-79ef-2467-d787-9ed717faeeb1
* Content: [Validate expected values - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/perf-test/rsat/rsat-validate-expected)
* Content Source: [articles/fin-ops-core/dev-itpro/perf-test/rsat/rsat-validate-expected.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/perf-test/rsat/rsat-validate-expected.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @FrankDahl
* Microsoft Alias: **fdahl**

**Comment by kfend** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
