### ISSUE TITLE
Is DMFBatchExporter class retry-able?

### ISSUE THREAD

**Issue by alneacsu** [MicrosoftDocs/dynamics-365-unified-operations-public#3885]
The class can be used to retry as it implements the interface
 
![image](https://user-images.githubusercontent.com/95413886/157634821-90b4c85f-ee85-4318-bcb8-b69360d1acf5.png)

But we return false in the method which will not allow this to retry.
 
![image](https://user-images.githubusercontent.com/95413886/157634892-fa4611fb-ce58-4cc4-878f-a0b3489250e6.png)

So to confirm, rather confusingly, this will allow  to set this up to retry, but this won't work anyway. 
Is that correct? 

Are there any plans to change this, as this class causes the most problems when we have batch severs restarting as typically these can be longer running jobs. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a0878ca-257d-9ec4-eab0-8a570635cca2
* Version Independent ID: b5f3068c-b880-b5b9-3f82-ac3326a6dd7b
* Content: [Enable batch retries - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/retryable-batch)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/retryable-batch.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/sysadmin/retryable-batch.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @matapg007
* Microsoft Alias: **matgupta**

**Comment by kfend** [comment]
@alneacsu - Thank you for the feedback.
@matapg007 - Can you please take a look at this? Thanks!

**Comment by alneacsu** [comment]
Hello!

Can you please help us with your feedback?

Thanks and regards,
Alex

Alexandru Adrian Neacșu
Senior Support Engineer
Dynamics 365 Finance & Operations (AX)
Customer Services and Support
Office: + 40 31 133 1622
***@***.******@***.***>
Working hours: 09:00-18:00 UTC +2:00
***@***.***
If you have any feedback about my work, please let either me or my manager know
Team Manager | Cezary Stola ***@***.******@***.***>)

**Comment by matapg007** [comment]
Yes, the class has been implemented with isretryable as false that means it will not be retried due to teh nature of the tasks.
If still user wants task to be retried, they should be implementing retry count on the task rather for retry. Hope this helps.
