### ISSUE TITLE
Data on this page will be outdated today (10th of February)

### ISSUE THREAD

**Issue by TimoTenni** [MicrosoftDocs/dynamics-365-unified-operations-public#3886]
Please add on this page clear statement like:
This page describes the VAT reporting setup for sales tax posted in year 2021 and earlier. Norway got new VAT declaration starting in 01.01.2022 - [VAT return with direct submission to Altinn](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/emea-nor-vat-return)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84009518-c6eb-f8f4-9591-78dbb24d9f03
* Version Independent ID: b02bae38-1660-fbb9-9456-f33d3cd50e1e
* Content: [VAT statement for Norway - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/emea-nor-sales-tax-payment-report)
* Content Source: [articles/finance/localizations/emea-nor-sales-tax-payment-report.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/emea-nor-sales-tax-payment-report.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @epodkolz
* Microsoft Alias: **epodkolz**

**Comment by kfend** [comment]
@TimoTenni - Thank you for the feedback.
@epodkolz - Can you please take a look and update the topic as necessary? Thanks!

**Comment by kfend** [comment]
@epodkolz - Thank you for the clarification.
@liza-golub - Can you please take a look and update the topic as necessary? Thanks!

**Comment by liza-golub** [comment]
this request will be covered in scope of the https://msdyneng.visualstudio.com/web/wi.aspx?pcguid=a1559462-dfa9-4e8b-8925-9299fe8a88ab&id=661987
