### ISSUE TITLE
Wrong link to release plan on feature 'Planning Optimization centralized calendar maintenance'

### ISSUE THREAD

**Issue by DKobayashi-ykgw** [MicrosoftDocs/dynamics-365-unified-operations-public#3889]
Wrong link to release plan on feature 'Planning Optimization centralized calendar maintenance'.
The link (//dynamics365-release-plan/2022wave1/finance-operations/dynamics365-supply-chain-management/planning-optimization-centralized-calendar-maintenance)
should fix to (/dynamics365-release-plan/2022wave1/finance-operations/dynamics365-supply-chain-management/planning-optimization-centralized-calendar-maintenance).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b04ba1b0-8f03-c6b0-6141-766188dfe8cc
* Version Independent ID: 6218142a-5715-e78f-82cb-22798a5bb8cb
* Content: [Preview of Dynamics 365 Supply Chain Management 10.0.25 (April 2022) - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/get-started/whats-new-scm-10-0-25)
* Content Source: [articles/supply-chain/get-started/whats-new-scm-10-0-25.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/get-started/whats-new-scm-10-0-25.md)
* Service: **dynamics-365-supply-chain**
* GitHub Login: @kamaybac
* Microsoft Alias: **kamaybac**

**Comment by sericks007** [comment]
@DKobayashi-ykgw, thanks for making us aware of this!  I've fixed the link.  The updated article will be published soon.
