### ISSUE TITLE
Typo under Open/Closed definition

### ISSUE THREAD

**Issue by pwinje** [MicrosoftDocs/dynamics-365-unified-operations-public#389]
Under Open/Closed it currently says "Open for modification" and "Closed for modification", but I assume you meant "Open for extension" and "Closed for modification".  Just a small typo, but an important one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a0fa0ba-209a-e457-06b6-30d496593f86
* Version Independent ID: d276a668-9296-d713-61e2-6d204f9181e9
* Content: [Write extensible code - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/extensibility/writing-extensible-code)
* Content Source: [articles/dev-itpro/extensibility/writing-extensible-code.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/extensibility/writing-extensible-code.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @MichaelFruergaardPontoppidan
* Microsoft Alias: **mfp**

**Comment by tonyafehr** [comment]
Thanks for the suggestion! We really appreciate feedback that helps us to improve our documentation.
