### ISSUE TITLE
RetailSDK Deprecation date update

### ISSUE THREAD

**Issue by andyNewnham** [MicrosoftDocs/dynamics-365-unified-operations-public#3892]
The date of deprecation of the legacy Retail SDK has been updated to April 2023. Please update the FAQ section accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a07b0d94-2f96-7b3a-9848-0a4e652b205c
* Version Independent ID: a07b0d94-2f96-7b3a-9848-0a4e652b205c
* Content: [Migrate to the Commerce SDK - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/retail-sdk/migrate-commerce-sdk)
* Content Source: [articles/commerce/dev-itpro/retail-sdk/migrate-commerce-sdk.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/retail-sdk/migrate-commerce-sdk.md)
* Service: **dynamics-365-commerce**
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by sericks007** [comment]
@andyNewnham, thank you for providing this feedback.

@mugunthanm, please update the content.

**Comment by mugunthanm** [comment]
@andyNewnham - Thanks for the feedback, updated the document.

**Comment by mugunthanm** [comment]
https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/pull/3893

**Comment by sericks007** [comment]
Bug 666500 has been logged to track this issue.

**Comment by sericks007** [comment]
Content has been updated.
