### ISSUE TITLE
Export database - environment availability

### ISSUE THREAD

**Issue by petrjanikac** [MicrosoftDocs/dynamics-365-unified-operations-public#3895]
There is a difference between info on Docs "The environment will be unavailable for other servicing operations, such as Sandbox refresh or package deployment during this time. **The source environment will be usable from a Dynamics user perspective**." and the reality in LCS
![image](https://user-images.githubusercontent.com/57525616/158365232-10099a77-4d6f-4dd7-9cce-821b54311e63.png)
![image](https://user-images.githubusercontent.com/57525616/158365377-3de69686-8017-4377-a72d-0ba4c3329aa5.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60bd86ae-4fe1-1cb0-275b-11801c67a1d0
* Version Independent ID: a6110234-8568-8600-1c13-602f0c2d2d44
* Content: [Export a database - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/export-database)
* Content Source: [articles/fin-ops-core/dev-itpro/database/export-database.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/database/export-database.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by sericks007** [comment]
LCS bug 13886373 has been logged to track this issue.

**Comment by josaw1** [comment]
Closed as won't fix.
