### ISSUE TITLE
Outdated note

### ISSUE THREAD

**Issue by d3fr0g** [MicrosoftDocs/dynamics-365-unified-operations-public#3896]
The first note on the page says that "Currently, you must use configuration keys to turn it on."
Here
https://docs.microsoft.com/en-us/dynamics365/finance/accounts-receivable/revenue-recognition-setup
the note says:
"The Revenue recognition feature is now enabled by default through Feature management. If your organization doesn't use this feature, you can turn it off in the Feature management workspace."

In 10.0.24 there is not config key but the feature is there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa35ab95-235c-a9ee-c8c3-638ac5a46000
* Version Independent ID: 6438b40a-a552-e6d7-b4e1-2b8597446a94
* Content: [Revenue recognition overview  (contains video) - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/accounts-receivable/revenue-recognition-overview)
* Content Source: [articles/finance/accounts-receivable/revenue-recognition-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/accounts-receivable/revenue-recognition-overview.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @kweekley
* Microsoft Alias: **kweekley**

**Comment by sericks007** [comment]
@d3fr0g, thanks for bringing this to our attention.

@kfend will work with @kweekley to address this issue.

**Comment by kfend** [comment]
I have updated the topic. The changes should be published in the next few hours. Thanks!
