### ISSUE TITLE
Provide Alternate Instructions to Build Commerce SDK

### ISSUE THREAD

**Issue by aaronstackpole** [MicrosoftDocs/dynamics-365-unified-operations-public#3899]
Windows Server 2016 - Visual Studio 2017 agent is no longer available. Please provide instructions on how to build and package the solution as these instructions are no longer valid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6d7fd83-5b1b-2f29-7182-562f45da942c
* Version Independent ID: 31f3df2c-312e-6728-e73a-41fbbd9dbf7e
* Content: [Set up Azure DevOps code sharing and create a build pipeline - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/e-commerce-extensibility/set-up-code-sharing-build-pipeline)
* Content Source: [articles/commerce/e-commerce-extensibility/set-up-code-sharing-build-pipeline.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/e-commerce-extensibility/set-up-code-sharing-build-pipeline.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @samjarawan
* Microsoft Alias: **samjar**

**Comment by sericks007** [comment]
@aaronstackpole, thank you for providing this feedback.

@samjarawan, please review and update the content, as needed.

**Comment by sericks007** [comment]
Bug 666501 has been logged to track this issue.

**Comment by samjarawan** [comment]
With "Windows Server 2016 - Visual Studio 2017" agent no longer supported, the default is now "windows-2019" which pre-installs Node version 16.x.  Version 10.0.26 and earlier of the online SDK requires Node version 12.x, so a task is needed prior to the Powershell to install the correct version of node.  Online SDK version 10.0.27 will have support for Node version 12.  The document will be updated to call this out.
