### ISSUE TITLE
漢字の訂正依頼 紹介⇒照会

### ISSUE THREAD

**Issue by takumatsuchida** [MicrosoftDocs/dynamics-365-unified-operations-public#3900]
[バッチ ジョブの作成 https://docs.microsoft.com/ja-jp/dynamics365/fin-ops-core/dev-itpro/sysadmin/tasks/create-batch-job#create-the-batch-job

以下の通りご訂正を依頼いたします。

<誤>
ナビゲーション ウィンドウ > モジュール > システム管理 > **紹介** > バッチ ジョブ の順に移動します。

<正>
ナビゲーション ウィンドウ > モジュール > システム管理 > **照会** > バッチ ジョブ の順に移動します。

以上]

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: c4a1c591-b562-739a-ddc7-2e662ee070e1
* Version Independent ID: 73035248-3d2a-520d-5783-a3cd33f5c72e
* Content: [バッチ ジョブの作成 - Finance & Operations | Dynamics 365](https://docs.microsoft.com/ja-jp/dynamics365/fin-ops-core/dev-itpro/sysadmin/tasks/create-batch-job)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/tasks/create-batch-job.md](https://github.com/MicrosoftDocs/Dynamics-365-Operations.ja-jp/blob/live/articles/fin-ops-core/dev-itpro/sysadmin/tasks/create-batch-job.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @maertenm
* Microsoft Alias: **sericks**

**Comment by sericks007** [comment]
@takumatsuchida, thank you for providing this feedback.  We'll look into it.

**Comment by vinceno** [comment]
@vivimills - could you please move this forward with LIOX and update here as progressed., thx

**Comment by sericks007** [comment]
Bug 666502 has been logged to track this issue.

**Comment by josaw1** [comment]
Closed as won't fix.

**Comment by vivimills** [comment]
@josaw1 this has been fixed.
