### ISSUE TITLE
Adobe Acrobat 32bit requirement missing

### ISSUE THREAD

**Issue by silicon359** [MicrosoftDocs/dynamics-365-unified-operations-public#3902]
After trying and failing to set up DRA with an error that Adobe PDF Reader was not detected, I contacted support via LCS.  I was informed it had to be 32bit Acrobat Reader. This should be mentioned in the article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fe44c05-ed58-b554-859e-2da552dbbd9d
* Version Independent ID: e638edab-dd54-6008-f210-524fd52b0e5b
* Content: [Install the Document Routing Agent to enable network printing - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/install-document-routing-agent)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/install-document-routing-agent.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/analytics/install-document-routing-agent.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @RichdiMSFT
* Microsoft Alias: **richdi**

**Comment by sericks007** [comment]
The content has been updated, and will be published soon.  Thanks again!
