### ISSUE TITLE
タイルの表記は「コンフィギュレーション」です。〇コンフィギュレーション ×構成

### ISSUE THREAD

**Issue by takumatsuchida** [MicrosoftDocs/dynamics-365-unified-operations-public#3903]
[https://docs.microsoft.com/ja-jp/dynamics365/fin-ops-core/dev-itpro/analytics/export-entities-to-your-own-database#configuring-the-entity-export-option
タイルの表記は「コンフィギュレーション」です。
〇コンフィギュレーション 
×構成
エンティティのエクスポート オプションのコンフィギュレーションクライアントを起動し、データ管理 ワークスペースで、データベースへのエンティティ エクスポートの**構成** タイルを選択します。]

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 33f75161-0776-a6c1-dc10-dc20ea26973f
* Version Independent ID: 55a81394-4606-745a-9fd2-59fb257d1086
* Content: [自分のデータベースの持ち込み (BYOD) - Finance & Operations | Dynamics 365](https://docs.microsoft.com/ja-jp/dynamics365/fin-ops-core/dev-itpro/analytics/export-entities-to-your-own-database)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/export-entities-to-your-own-database.md](https://github.com/MicrosoftDocs/Dynamics-365-Operations.ja-jp/blob/live/articles/fin-ops-core/dev-itpro/analytics/export-entities-to-your-own-database.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Peakerbl
* Microsoft Alias: **peakerbl**

**Comment by sericks007** [comment]
@takumatsuchida, thank you for this feedback.

@vivimills, please check the translation of this article.

**Comment by sericks007** [comment]
Bug 666503 has been logged to track this issue.

**Comment by josaw1** [comment]
Closed as won't fix.
