### ISSUE TITLE
Which version MS will investigate or troubleshoot

### ISSUE THREAD

**Issue by YujiImaoka** [MicrosoftDocs/dynamics-365-unified-operations-public#3904]
The different descriptions of these documents make it difficult to know to which version MS will investigate or troubleshoot.
If [a version that's older than 3 service updates] is correct. Please show actual example.(e.g. latest version 10.0.24, MS does not investigate issue happens at older than 10.0.21　)
Update (A) or (B) to correct description.

(A)https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/one-version#what-does-end-of-service-mean
Microsoft will also not investigate or troubleshoot any issue that you may encounter on a version that's older than 3 service updates.

(B)https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/versions-update-policy
Microsoft will also not investigate or troubleshoot any issue that you may encounter on an older version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23fde63f-0f6f-b1a0-50c8-e1bf5f6a48c4
* Version Independent ID: 59a1f734-87cb-f34c-afd5-9f14de877584
* Content: [One Version service updates FAQ - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/one-version#what-does-end-of-service-mean)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/one-version.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/one-version.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @ShellyBakke
* Microsoft Alias: **smiller**

**Comment by sericks007** [comment]
@YujiImaoka, thank you for providing this feedback.  I'm waiting to hear back about who will review this issue.

**Comment by sericks007** [comment]
@YujiImaoka, the [One Version service updates FAQ] article was updated yesterday.  Does the updated content answer your question?

**Comment by YujiImaoka** [comment]
@sericks007 I cannot find any change on [One Version service updates FAQ].

Could you please update both (A) or (B) as like below DRAFT?

(Draft)
Microsoft also won't investigate or troubleshoot any issue that you encounter on a version that is older than three service updates.
(e.g. If latest version is 10.0.24, Microsoft does not investigate issue happens at older than 10.0.21)

**Comment by sericks007** [comment]
The [Software lifecycle policy and cloud releases](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/versions-update-policy) content has been updated.  The [One Version service updates FAQ](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/one-version) article was updated recently, as well.
