### ISSUE TITLE
configure global address books refers to a recording ?

### ISSUE THREAD

**Issue by andypicking** [MicrosoftDocs/dynamics-365-unified-operations-public#3905]
Hi,

This page refers to a recording but there is no link to any form of recording ?

Thanks
andy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 648592cf-60d0-7c8c-43ab-19668b719236
* Version Independent ID: 6f1cb23a-4a80-a16d-e6d2-2f5eda1f2a4c
* Content: [Configure address books - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/organization-administration/tasks/address-books?toc=/dynamics365/supply-chain/toc.json)
* Content Source: [articles/fin-ops-core/fin-ops/organization-administration/tasks/address-books.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/organization-administration/tasks/address-books.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @msftbrking
* Microsoft Alias: **brking**

**Comment by sericks007** [comment]
@andypicking, thanks for letting us know about this.

@msftbrking, please add the link to the recording.  If no recording is available, please remove the reference to it.

**Comment by sericks007** [comment]
Bug 666504 has been logged to track this issue.

**Comment by sericks007** [comment]
There is no recording, so the reference to the recording has been removed.  The updated content will be published soon.
