### ISSUE TITLE
Title is incorrectly indicates Preview

### ISSUE THREAD

**Issue by MarcRohde** [MicrosoftDocs/dynamics-365-unified-operations-public#3906]
The version is released so should not be a Preview

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b04ba1b0-8f03-c6b0-6141-766188dfe8cc
* Version Independent ID: 6218142a-5715-e78f-82cb-22798a5bb8cb
* Content: [Preview of Dynamics 365 Supply Chain Management 10.0.25 (April 2022) - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/get-started/whats-new-scm-10-0-25)
* Content Source: [articles/supply-chain/get-started/whats-new-scm-10-0-25.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/get-started/whats-new-scm-10-0-25.md)
* Service: **dynamics-365-supply-chain**
* GitHub Login: @kamaybac
* Microsoft Alias: **kamaybac**

**Comment by sericks007** [comment]
@MarcRohde, thanks for point this out.  We're working on it!

@kamaybac, please update this.
