### ISSUE TITLE
10.0.25 indicates preview in the link text

### ISSUE THREAD

**Issue by MarcRohde** [MicrosoftDocs/dynamics-365-unified-operations-public#3907]
10.0.25 is released so it should not indicate it is a preview anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c023fc2-87cd-c17b-5578-dc830ab6b015
* Version Independent ID: 73ff0eda-6e9c-f859-da8a-01acf5c31908
* Content: [What's new or changed in Dynamics 365 Supply Chain Management - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/get-started/whats-new-home-page)
* Content Source: [articles/supply-chain/get-started/whats-new-home-page.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/get-started/whats-new-home-page.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @kamaybac
* Microsoft Alias: **kamaybac**

**Comment by sericks007** [comment]
@MarcRohde, thanks for point this out. We're working on it!

@kamaybac, please update this.

**Comment by kamaybac** [comment]
Topic is updated
