### ISSUE TITLE
Drop user owner of full text catalog

### ISSUE THREAD

**Issue by ldallari** [MicrosoftDocs/dynamics-365-unified-operations-public#391]
On preparation of database drop of user axdeployuser fails because it is the owner of a full text catalog

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3436fbc8-5bdd-dcdc-f5d3-51caf7b6cd76
* Version Independent ID: af78d3ef-b329-11e9-896a-aa3394f6c77c
* Content: [Copy Finance and Operations databases from Azure SQL Database to SQL Server environments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/copy-database-from-azure-sql-to-sql-server#feedback)
* Content Source: [articles/dev-itpro/database/copy-database-from-azure-sql-to-sql-server.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/database/copy-database-from-azure-sql-to-sql-server.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @maertenm
* Microsoft Alias: **maertenm**

**Comment by sericks007** [comment]
Thanks for letting us know. We'll investigate this issue.

**Comment by laneswenka** [comment]
@ldallari I am following up on this with our retail team.  Can you please provide the name of the fulltext catalog you are hitting?  Is it COMMERCEFULLTEXTCATALOG ?

**Comment by ldallari** [comment]
It wasn't COMMERCEFULLTEXTCATALOG, that had dbo as owner.
I've extracted the database from the "STANDARD ACCEPTANCE TEST" environment and the name catalog owned by axdeployuser was composed by the name of the Production environment in LCS followed by "_axdb_3bcce6a7465ddabd_catalog"

**Comment by laneswenka** [comment]
Thanks @ldallari  - this also appears to be a known issue we have documented:
https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/copy-database-from-azure-sql-to-sql-server#i-cant-drop-users-in-source-database

We'll look to add dynamic SQL to move owners of the catalogs to DBO prior to their removal.

**Comment by sericks007** [comment]
The updated topic will be published later today. Thanks!
