### ISSUE TITLE
issue with footer visibility formula

### ISSUE THREAD

**Issue by yabwah** [MicrosoftDocs/dynamics-365-unified-operations-public#3921]
Hi, 
There is a issue with page footer visibility formula. 

(
COUNT(Total.Page.Amount.Result)-Total.Running.Lines2.Sum(false)+
**0*Total.Running.Lines2.Collect(COUNT(Total.Page.Amount.Result))**
)<>0

The zero in " 0*Total.Running.Lines2.Collect(COUNT(Total.Page.Amount.Result))" section will always generate 0

Can you please check and advise ?

Thanks
Younes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 147854ad-10c3-6c04-38f7-2848a8213f42
* Version Independent ID: 034817b6-581d-cd67-8764-3bdb01ccfeb1
* Content: [Design an ER format to paginate generated documents in Excel - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/er-paginate-excel-reports)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/er-paginate-excel-reports.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/analytics/er-paginate-excel-reports.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @NickSelin
* Microsoft Alias: **nselin**

**Comment by NickSelin** [comment]
Hello [yabwah](https://github.com/yabwah),
Thank you for your question! ER uses the [lazy reading](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/er-groupby-data-sources#debug-the-added-model-mapping-component) approach. Therefore, this part of the ER expression has been added intentionally - to force the **Total.Running.Lines2** collection memorizing the **COUNT(Total.Page.Amount.Result)** value but do not affect the result of the calculation of the current expression..
Best regards,
Nick

**Comment by yabwah** [comment]
Hi Nick,
Thank you for reply. I don't get the relevance between the lazy reading and multiplying by 0. Can you please elaborate on this further?
Thanks 
Younes

**Comment by NickSelin** [comment]
Hello Younes,
As it is described in the notes of this page, the `0*Total.Running.Lines2.Collect(COUNT(Total.Page.Amount.Result))` construction is used not to calculate whether the **Report page footer** component is visible on the current page as the multiplication to zero always returns zero value. It is used to append the `Total.Running.Lines2` collection with the `COUNT(Total.Page.Amount.Result)` value AFTER the execution of the `COUNT(Total.Page.Amount.Result)-Total.Running.Lines2.Sum(false)` construction. To use the `Total.Running.Lines2` collection value for the enabling calculation on the next page.
Best regards,
Nick

**Comment by yabwah** [comment]
Got it.
Thankyou
