### ISSUE TITLE
輸出/エキスポート  > エクスポート

### ISSUE THREAD

**Issue by takumatsuchida** [MicrosoftDocs/dynamics-365-unified-operations-public#3927]
[https://docs.microsoft.com/ja-jp/dynamics365/fin-ops-core/dev-itpro/data-entities/data-entities-data-packages#export
× 輸出
△エキスポート
〇 エクスポート]

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 1016eba2-a0f9-8890-beb4-7c9f9f6df4fc
* Version Independent ID: 57758813-9d36-975a-eb6f-551b7da3e276
* Content: [データ管理の概要 - Finance & Operations | Dynamics 365](https://docs.microsoft.com/ja-jp/dynamics365/fin-ops-core/dev-itpro/data-entities/data-entities-data-packages)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/data-entities-data-packages.md](https://github.com/MicrosoftDocs/Dynamics-365-Operations.ja-jp/blob/live/articles/fin-ops-core/dev-itpro/data-entities/data-entities-data-packages.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Peakerbl
* Microsoft Alias: **peakerbl**

**Comment by josaw1** [comment]
@takumatsuchida, thank you for this feedback.

@takumatsuchida, thank you for this feedback.

@vivimills, please check the translation of this article.

**Comment by josaw1** [comment]
Closed as won't fix.
