### ISSUE TITLE
Missing File

### ISSUE THREAD

**Issue by hammr5900** [MicrosoftDocs/dynamics-365-unified-operations-public#3929]
This [page](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/blob/1e62b05da00bd2bbd18250896769437d924e83cd/articles/dev-itpro/analytics/financial-performance-power-bi-content-pack.md) references an Excel workbook that has the default data model that was used to create the content of the reports listed here. 

The link on the page is: https://mbs.microsoft.com/customersource/global/AX/downloads/reports/msdaxfinpercontentpowerbi

Where can we get a copy of this spreadsheet?

Thank you.

Mike

**Comment by josaw1** [comment]
Thank you for your comment. @kweekley can you please review?

**Comment by kweekley** [comment]
As noted at the top of the documentation, the referenced Power BI content pack in this document was deprecated on build Dynamics Finance and Operations 7.3.  I no longer have access to the Excel spreadsheet.

**Comment by hammr5900** [comment]
I saw that its deprecated but having access to the document is still valuable…or an updated one.

Mike

**Comment by josaw1** [comment]
Closed as won't fix.
