### ISSUE TITLE
Update to Step 15. Set up SQL Server to flow with script updates

### ISSUE THREAD

**Issue by trentone1** [MicrosoftDocs/dynamics-365-unified-operations-public#3933]
Step 15. Set up SQL Server
   - Step 3. a. through d. does not flow with the updates that have been made to the .\New-ADCS-SQLCert-AllVMs.ps1 script.

Processes should state and possible give example of the single SQL certificate that is created by this script and the resulting Subject Alternative Name. (Nodes, Instances)

Please note that the Subject Alternative Name must match the Nodes\Instances FQDN.

Where and how to install this certificate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14409653-d5a8-bf1b-8772-97832acfe6af
* Version Independent ID: 331d5d92-1601-ed2e-0dd9-4d68beddebff
* Content: [Set up and deploy on-premises environments (Platform update 41 and later) - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/setup-deploy-on-premises-pu41#setupsql)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/setup-deploy-on-premises-pu41.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/deployment/setup-deploy-on-premises-pu41.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @faix
* Microsoft Alias: **osfaixat**

**Comment by josaw1** [comment]
Thank you for your comment. @faix can you please review?

**Comment by faix** [comment]
@josaw1 i have a PR open for this. Will link it shortly.

**Comment by faix** [comment]
@josaw1 please close this issue. It has been merged in already.
