### ISSUE TITLE
Page to be adjusted for France

### ISSUE THREAD

**Issue by bcaillet** [MicrosoftDocs/dynamics-365-unified-operations-public#3934]
It will be great to add the right acronym for French language as this costing model is well known as "PMP" for Prix Moyen Pondéré. That will help the search. 

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 4fa882cb-d260-6ff0-dcfe-0319a88bb61b
* Version Independent ID: 00d1058a-d550-3f04-1f4a-947d92dee7d9
* Content: [Moyenne pondérée avec valeur physique et marquage - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/fr-fr/dynamics365/supply-chain/cost-management/weighted-average-physical-value-marking)
* Content Source: [articles/supply-chain/cost-management/weighted-average-physical-value-marking.md](https://github.com/MicrosoftDocs/Dynamics-365-Operations.fr-fr/blob/live/articles/supply-chain/cost-management/weighted-average-physical-value-marking.md)
* Service: **dynamics-365-supply-chain**
* GitHub Login: @AndersGirke
* Microsoft Alias: **aevengir**

**Comment by josaw1** [comment]
Closed as won't fix.
