### ISSUE TITLE
No reference to Point in time restore on production

### ISSUE THREAD

**Issue by hasaid** [MicrosoftDocs/dynamics-365-unified-operations-public#3936]
cannot find any details on the point in time restore on production and customers need this scenario during cut-over and mock cutover, can we add the point in time restore on production ?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53e754f9-eb0d-98d0-fedc-b6e5f403695e
* Version Independent ID: e631ba39-fd00-828f-d848-75cd7addbff2
* Content: [Database movement operations home page - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/dbmovement-operations)
* Content Source: [articles/fin-ops-core/dev-itpro/database/dbmovement-operations.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/database/dbmovement-operations.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by josaw1** [comment]
Closed as won't fix.
