### ISSUE TITLE
Import Fails with Schema error 

### ISSUE THREAD

**Issue by SGick** [MicrosoftDocs/dynamics-365-unified-operations-public#3937]
When you export the raw log from lcs, open it in excel, save and then ingest in Data Explorer you get a schema error
because of commas " , " in some of the columns. 

Error Message:
Couldn't infer file schema. Error: Input (format: 'Csv') source cannot be read due to: 'Columns number is not consistent'.

Solution: If you just open the exported CSV with notepad and delete the first line with "SEP=," then you can import without any problems. Just dont open it in Excel and save. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5ff6b0b-7df1-bafd-cbf8-2613a704cd1c
* Version Independent ID: e7445fad-0895-d168-a98a-5b89afa6e7ac
* Content: [Use Azure Data Explorer to query raw information logs - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/azure-data-explorer)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/azure-data-explorer.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/lifecycle-services/azure-data-explorer.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @andreashofmann1
* Microsoft Alias: **andreash**

**Comment by torbennehmer** [comment]
@josaw1 @andreashofmann1 One addition, please try to avoid all tricks with Excel opening/saving CSV. Excel changes its behavoir based on the locale it is living in. So the way a Excel in a regular German environment "improves" on the data can be significantly different then one in an English environment. Especially Dates and Numbers are usually completely broken once a non-English Excel works on Data formatted in an English manner.
