### ISSUE TITLE
Change text "new root business unit" to "new parent business unit"

### ISSUE THREAD

**Issue by Vixseboxse** [MicrosoftDocs/dynamics-365-unified-operations-public#3939]
Change text "new root business unit" to "new parent business unit". The root business unit at the top stays the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a546217f-20c0-3cc4-021b-a2a260789894
* Version Independent ID: cd0bb5ad-4a97-85f4-0a01-212249498cbf
* Content: [Company concept in Dataverse - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/company-data)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/company-data.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/dual-write/company-data.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @RamaKrishnamoorthy
* Microsoft Alias: **ramasri**

**Comment by josaw1** [comment]
Thank you for your feedback. @RamaKrishnamoorthy can you please review?
