### ISSUE TITLE
New version after 10.0.30

### ISSUE THREAD

**Issue by jansenrf** [MicrosoftDocs/dynamics-365-unified-operations-public#3944]
[Voer hier feedback in]
Do you already have new versions after 10.0.30?

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: e7dcb285-f32c-c92e-fe49-1617f213066b
* Version Independent ID: 8f28c1a0-9da5-f853-90ee-d82a4c32df7e
* Content: [Service update availability - Finance & Operations | Dynamics 365](https://docs.microsoft.com/nl-nl/dynamics365/fin-ops-core/fin-ops/get-started/public-preview-releases?#targeted-release-schedule-dates-subject-to-change)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/public-preview-releases.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/public-preview-releases.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @ShellyBakke
* Microsoft Alias: **smiller**

**Comment by sericks007** [comment]
@jansenrf, thank you for providing this feedback.

@hmahl, please update the release schedule.

**Comment by sericks007** [comment]
This article was updated yesterday.
