### ISSUE TITLE
According to support the Full Reset batch job needs to be in Waiting status  So, it is still required.  

### ISSUE THREAD

**Issue by JOLSO** [MicrosoftDocs/dynamics-365-unified-operations-public#3945]
[Vendor Payment Workspace (Embedded BI) no longe... - TrackingID#2203290040007573.docx](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/files/8420247/Vendor.Payment.Workspace.Embedded.BI.no.longe.-.TrackingID.2203290040007573.docx)

According to support the Full Reset batch job needs to be in Waiting status  So, it is still required.  Could you document that here? The document since to imply otherwise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f75deef1-a768-5c65-e14d-3d3ee054bb39
* Version Independent ID: 5fb6f92f-c560-a90e-417b-dbcc47236cd5
* Content: [Automated Entity store refresh - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/automated-entity-store-refresh)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/automated-entity-store-refresh.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/analytics/automated-entity-store-refresh.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav*
[Vendor Payment Workspace (Embedded BI) no longe... - TrackingID#2203290040007573.docx](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/files/8420250/Vendor.Payment.Workspace.Embedded.BI.no.longe.-.TrackingID.2203290040007573.docx)
[Vendor Payment Workspace (Embedded BI) no longe... - TrackingID#2203290040007573.docx](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/files/8420251/Vendor.Payment.Workspace.Embedded.BI.no.longe.-.TrackingID.2203290040007573.docx)
*

**Comment by josaw1** [comment]
Closed as won't fix.
