### ISSUE TITLE
Need additional documentation for API GetDimensionValuesWithEstimatedAvailabilities

### ISSUE THREAD

**Issue by utlars** [MicrosoftDocs/dynamics-365-unified-operations-public#3946]
Internal wiki has this information for the API GetDimensionValuesWithEstimatedAvailabilities but is not found publicly.

https://msazure.visualstudio.com/D365/_wiki/wikis/D365.wiki/195503/Inventory-Availability-API-Specifications?anchor=products/getdimensionvalueswithestimatedavailabilities

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d421ed99-0ff4-6ef0-543e-894f4f30f00d
* Version Independent ID: 2b4d9bab-0003-2123-d236-4e99b5f89eb3
* Content: [Commerce Scale Unit customer and consumer APIs - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/retail-server-customer-consumer-api#products-controller)
* Content Source: [articles/commerce/dev-itpro/retail-server-customer-consumer-api.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/retail-server-customer-consumer-api.md)
* Service: **dynamics-365-commerce**
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by josaw1** [comment]
Thanks for your comment. @mugunthanm can you please review?

**Comment by josaw1** [comment]
Closed as won't fix.
