### ISSUE TITLE
Email distribution batch process use and related feature and function 

### ISSUE THREAD

**Issue by abkady** [MicrosoftDocs/dynamics-365-unified-operations-public#3949]
Can we add some remarks on the Email distribution batch process, where is it used, which feature \ functionality does need this job to run. currently I can see this is used to process the workflow email notifications, is there any other feature or function does need this job to be running ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e46e3d2a-37fb-9961-84fe-0be6d9f0235b
* Version Independent ID: c4a46858-a79b-08b4-d81c-941490d42da3
* Content: [Configure and send email - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/organization-administration/configure-email)
* Content Source: [articles/fin-ops-core/fin-ops/organization-administration/configure-email.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/organization-administration/configure-email.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by kamaybac** [comment]
@abkady, thank you taking the time to send us your suggestion. I am forwarding it to the page author for consideration.

**Comment by josaw1** [comment]
Closed as won't fix.
