### ISSUE TITLE
Out of date - deprecated features

### ISSUE THREAD

**Issue by MichaelSlipp** [MicrosoftDocs/dynamics-365-unified-operations-public#3950]
[Enter feedback here]
This process is no longer possible to to the deprecation of XSLT transformation as described here:

https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/get-started/removed-deprecated-features-platform-updates#xslt-scripting-in-data-management

The section with "After the format processing group is set up, the next step is to define the bank statement format rules for BAI2 bank statements." is not possible - in the bank statement format screen the fields for processing group and file format have been hidden, the Generic electronic field is now always set to Yes and cannot be changed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f6257c7-8c1f-f00a-4f51-2f8f20f1f09e
* Version Independent ID: c793b57d-f984-bb4d-d014-e2bf2da43f68
* Content: [Set up the advanced bank reconciliation import process - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/cash-bank-management/set-up-advanced-bank-reconciliation-import-process)
* Content Source: [articles/finance/cash-bank-management/set-up-advanced-bank-reconciliation-import-process.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/cash-bank-management/set-up-advanced-bank-reconciliation-import-process.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @panolte
* Microsoft Alias: **panolte**

**Comment by panolte** [comment]
Angela Ding is the PM for this topic.

**Comment by bishalgoswami** [comment]
Bug 712761 has been logged to address this issue.

**Comment by panolte** [comment]
Please reassign to angelad116 as the owner of this content.

**Comment by angelad116** [comment]
@MichaelSlipp 
If customers want to use existing XSLT function, need raise IcM ticket to Microsoft support, to open the flight. All MS supports all were informed how is the process

**Comment by MichaelSlipp** [comment]
@angelad116 if the documentation is still going to refer to the XSLT method then that fact should be updated into the public facing document.  However if the recommended bank statement import solution is something else - Electronic Reporting - then the setup for that should be published and this topic should not be the apparent solution.

**Comment by angelad116** [comment]
@MichaelSlipp Hi Michael, we have updated external document of Electronic Reporting, and inserted a link into this document. Due to security issue, MS wants to monitor how many users/companies are still using XSLT method, so please kindly follow other users' practice, that raise a ticket to MS to open the flight, for XSLT. Thank you!
