### ISSUE TITLE
The documentation on this subject is missing detailed information on settings

### ISSUE THREAD

**Issue by rpouwels** [MicrosoftDocs/dynamics-365-unified-operations-public#3952]
Very poor setup information. Many details missing at all. Like "coda definitions" and "coda journal" like what are the settings for. I keep getting an error message and I am not the only one, but there is no troubleshooting chapter either.

Please complete the documentation. 

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 807f96bd-9269-1541-0516-ee905e0003d7
* Version Independent ID: a263d611-d029-927b-16b6-a9e2a23000db
* Content: [CODA-bankafschrift - Finance | Dynamics 365](https://docs.microsoft.com/nl-nl/dynamics365/finance/localizations/emea-bel-coda-bank-statement-import)
* Content Source: [articles/finance/localizations/emea-bel-coda-bank-statement-import.md](https://github.com/MicrosoftDocs/Dynamics-365-Operations.nl-nl/blob/live/articles/finance/localizations/emea-bel-coda-bank-statement-import.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @Anasyash
* Microsoft Alias: **anasyash**

**Comment by josaw1** [comment]
@kfend, can you please look into this? Thanks.
