### ISSUE TITLE
Old Features are Still in Docs Site

### ISSUE THREAD

**Issue by mattgo79-MSFT** [MicrosoftDocs/dynamics-365-unified-operations-public#3953]
Hello, we should remove any references to Performance Metrics and Index Analysis since these features were deprecated last fall, but they still exist here in the Docs site.  This causes confusion to our customers.  My alias is GOMATT.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a59d9fd-8c46-120c-efb1-ef73b158ac33
* Version Independent ID: 6ec54ef7-cbbb-32f3-42c7-ac695d3b94bd
* Content: [Performance troubleshooting using tools in Lifecycle Services (LCS) - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/performancetroubleshooting)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/performancetroubleshooting.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/lifecycle-services/performancetroubleshooting.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by josaw1** [comment]
@twheeloc, this article is outdated. Can you please work with PM to get it updated?

**Comment by twheeloc** [comment]
@mattgo79-MSFT, the topic has been updated. Thank you!
