### ISSUE TITLE
Active Retail Cloud POS

### ISSUE THREAD

**Issue by SalesAppAx** [MicrosoftDocs/dynamics-365-unified-operations-public#3955]
AFTER SET UP PREVIOUS REQUIREMENTS RUN ACTIVE RETAIL CLOUD POS ONEBOX AND SHOW THIS ISSUES

Retrieving the stores failed.

DA1023 - Could not resolve identity. The Azure AD account is not mapped to an employee in Retail headquarters.
Application session ID
13e83c69-95e6-8eb6-ec36-c69548567200

NEED OTHER SETUP OR CONFIGURATION TO WORKS THAT MODULE

**Comment by kfend** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
