### ISSUE TITLE
Wrong Image in the top of the page

### ISSUE THREAD

**Issue by Shind44** [MicrosoftDocs/dynamics-365-unified-operations-public#3956]
Wrong Image in the top of the page
![image](https://user-images.githubusercontent.com/40988263/162967231-8bfb8da0-66b1-445d-97e8-7e024a6b5690.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e35cbedf-51f8-cf26-76a6-6c3ef586f214
* Version Independent ID: 538fa39d-b217-9c3c-2e6f-55fe189174eb
* Content: [Design-time metadata for Segmented Entry controls - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/financial/segmented-entry-control-metadata-specification)
* Content Source: [articles/fin-ops-core/dev-itpro/financial/segmented-entry-control-metadata-specification.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/financial/segmented-entry-control-metadata-specification.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @RyanCCarlson2
* Microsoft Alias: **rcarlson**

**Comment by kfend** [comment]
@Shind44 - Thank you for this feedback. 
@RyanCCarlson2 - Can you please take a look at this and update the topic as needed? Thanks!

**Comment by kfend** [comment]
@RyanCCarlson2 - Thank you for the quick update! I have merged the changes and the updated graphic will go live later today. Closing this issue as it has been resolved.
