### ISSUE TITLE
License for Azure B2B user

### ISSUE THREAD

**Issue by gunavs** [MicrosoftDocs/dynamics-365-unified-operations-public#3960]
[Enter feedback here]
I am trying to understand how license consumption would be in this scenario for the guest user. For instance, Power BI doc states that the external user can be licenses in their tenant or the shared tenant https://docs.microsoft.com/en-us/power-bi/enterprise/service-admin-azure-ad-b2b#:~:text=Power%20BI%20enables%20sharing%20content%20with%20external%20guest,By%20default%2C%20external%20guests%20have%20mostly%20consumption%20experiences.
Would that apply for Dynamics asl well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4e7f6ac-cc86-d8aa-d68e-9ecb048cbae7
* Version Independent ID: b83a8a3b-40c3-4349-885d-7a865a25be08
* Content: [Export business-to-business (B2B) users to Azure Active Directory - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/implement-b2b)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/implement-b2b.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/sysadmin/implement-b2b.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @sarvanisathish
* Microsoft Alias: **sarvanis**

**Comment by sericks007** [comment]
@gunavs, thank you for providing this feedback.  The author of this article has left the team, so I'm working to find a new author for this article.

**Comment by sericks007** [comment]
@paulliew, please respond.

**Comment by paulliew** [comment]
assigned to @Ritesh Pandey

**Comment by sericks007** [comment]
Bug 693415 has been logged to track this issue.

**Comment by ritesh** [comment]
Wrong ritesh

**Comment by sericks007** [comment]
Assigning to @ritesp.

**Comment by josaw1** [comment]
Closing as won't fix.
