### ISSUE TITLE
Upload Certificate incorrect

### ISSUE THREAD

**Issue by jbromelow** [MicrosoftDocs/dynamics-365-unified-operations-public#3962]
[Enter feedback here]
Part about uploading the LCS certificate (https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/arm-onboarding#upload-the-management-certificate) is incorrect.
Link to 'clasic Azure Portal' is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 693bb4b2-92f2-2f0c-4fd3-6c9c1bb5894b
* Version Independent ID: 476f52d0-57a1-37e2-881f-857ce623bb03
* Content: [Complete the Azure Resource Manager onboarding process - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/arm-onboarding)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/arm-onboarding.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/deployment/arm-onboarding.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @saurabhsurana
* Microsoft Alias: **sasurana**

**Comment by kfend** [comment]
@jbromelow - Thank you for the feedback.
@saurabhsurana - Can you please take a look and update the topic? Thanks!
