### ISSUE TITLE
Text and images around environment topologies for developent and build is outdated

### ISSUE THREAD

**Issue by PalleAgermark** [MicrosoftDocs/dynamics-365-unified-operations-public#397]
The naming, menus and generally experience has changed significantly since the present content was released.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a74ae963-aca1-5622-b27a-05e40e40554c
* Version Independent ID: 64745ceb-8444-d806-6a3c-a695c288d07a
* Content: [Deploy topologies that support continuous build and test automation - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/perf-test/continuous-build-test-automation)
* Content Source: [articles/dev-itpro/perf-test/continuous-build-test-automation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/perf-test/continuous-build-test-automation.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RobinARH
* Microsoft Alias: **shailesn**

**Comment by kfend** [comment]
Thanks for the feedback. We are working on updating this topic.

**Comment by leo9912** [comment]
The build VM contains the vNext build agent which was released as part of TFS 2015. When you deploy the Build VM, the build agent is configured by default to connect and sync with the Azure DevOps project.
This does not work for me. The Pipeline > Builds section in VSTS (Azure DevOps) is empty with message No builds were found.
Please could you provide troubleshooting section?
