### ISSUE TITLE
Please update page with new dates

### ISSUE THREAD

**Issue by jimwillsher** [MicrosoftDocs/dynamics-365-unified-operations-public#3970]
[Enter feedback here]

Please could this page be updated? The page only shows the next four planned releases, and that is too short a timeframe for enterprises who are deploying or planning D365 F&O. We really need to see a rolling twelve months. Many thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7dcb285-f32c-c92e-fe49-1617f213066b
* Version Independent ID: 8f28c1a0-9da5-f853-90ee-d82a4c32df7e
* Content: [Service update availability - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/public-preview-releases)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/public-preview-releases.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/public-preview-releases.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @ShellyBakke
* Microsoft Alias: **smiller**

**Comment by sericks007** [comment]
@jimwillsher, thank you for providing this feedback.

@hmahl, please update the content.

**Comment by sericks007** [comment]
This article was updated yesterday.
