### ISSUE TITLE
Duplicated links in documentation

### ISSUE THREAD

**Issue by hpvanzyl** [MicrosoftDocs/dynamics-365-unified-operations-public#3973]
Duplicated links in the documentation:

Page:
https://docs.microsoft.com/en-us/dynamics365/supply-chain/landed-cost/landed-cost-vs-tms#intercompany-reports

Snippet:
The following reports don't work in conjunction with the goods in transit feature that Landed cost provides:

[Intercompany goods in transit totals report](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/intercompany-goods-in-transit-totals-report-intercompanygoodsintransittotals)
[Intercompany goods in transit totals report](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/intercompany-goods-in-transit-totals-report-intercompanygoodsintransittotals)

Regards,
hpvanzyl
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f85f0889-baee-fce5-c546-1fee78ef0c84
* Version Independent ID: 71b3e524-bd5a-d155-01b7-449c249189a9
* Content: [Landed cost vs. Transportation management - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/landed-cost/landed-cost-vs-tms)
* Content Source: [articles/supply-chain/landed-cost/landed-cost-vs-tms.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/landed-cost/landed-cost-vs-tms.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @sherry-zheng
* Microsoft Alias: **chuzheng**
*

**Comment by twheeloc** [comment]
@hpvanzyl, Thank you for this feedback.
@sherry-zheng, please review and update as needed.

**Comment by josaw1** [comment]
Closing as won't fix.
