### ISSUE TITLE
Workflow Test Condition

### ISSUE THREAD

**Issue by iamJoshKnox** [MicrosoftDocs/dynamics-365-unified-operations-public#3975]
Do F&O workflows still have a test condition button?  It no longer seems to be visible in my workflow editor forms.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07dd83e3-7b83-2db8-602b-26152f3d772d
* Version Independent ID: 49892b38-1256-2459-90df-c43db87af15b
* Content: [Configure conditional decisions in a workflow - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/organization-administration/configure-conditional-decision-workflow?toc=/dynamics365/commerce/toc.json)
* Content Source: [articles/fin-ops-core/fin-ops/organization-administration/configure-conditional-decision-workflow.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/organization-administration/configure-conditional-decision-workflow.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @ChrisGarty
* Microsoft Alias: **cgarty**

**Comment by twheeloc** [comment]
@iamJoshKnox, thank you for this question.
@ChrisGarty, please review and update the content as needed.

**Comment by josaw1** [comment]
@twheeloc can you please review this?

**Comment by josaw1** [comment]
Closed as won't fix.
