### ISSUE TITLE
Timeframe of the unsupported setup

### ISSUE THREAD

**Issue by Yavillan** [MicrosoftDocs/dynamics-365-unified-operations-public#3976]
Is there a possibility to know an estimated date or timeframe in which this will be supported?
Some setup isn't added in the fit analysis, in which there is a timeframe

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aad34759-589f-24db-cf35-7664646a7ff3
* Version Independent ID: f2d59d91-7d54-ef2a-65c5-bc5f1541d122
* Content: [Parameters not used by Planning Optimization - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/master-planning/planning-optimization/not-used-parameters)
* Content Source: [articles/supply-chain/master-planning/planning-optimization/not-used-parameters.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/master-planning/planning-optimization/not-used-parameters.md)
* Service: **dynamics-365-supply-chain**
* GitHub Login: @t-benebo
* Microsoft Alias: **benebotg**

**Comment by twheeloc** [comment]
@Yavillan, thank you for the feedback.
@t-benebo, please review and updated the content as needed.

**Comment by josaw1** [comment]
Closing as won't fix.
