### ISSUE TITLE
DeploySsrsExtension.ps1 script issue

### ISSUE THREAD

**Issue by AnatolyZan** [MicrosoftDocs/dynamics-365-unified-operations-public#3978]
Hello Robin!

Hope everything is going well!

We need to update SSRS in one of our OneBoxes and faced with an issue with DeploySsrsExtension.ps1 script. 
The script is not included into DeployablePackage we can get from LCS. 

And without this script to make a proper update is just impossible. 

BR, 
Anatoly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cb4d381-4818-1a60-49e9-e77ef29f3719
* Version Independent ID: d74dd374-bf6b-da8c-e8a5-e4c4a4737607
* Content: [Patch SQL Server Reporting Services (SSRS) in one-box environments - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/patch-reporting-service-environment)
* Content Source: [articles/fin-ops-core/dev-itpro/migration-upgrade/patch-reporting-service-environment.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/migration-upgrade/patch-reporting-service-environment.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **shailesn**

**Comment by sericks007** [comment]
@AnatolyZan, thank you for providing this feedback.

@josaw1, please assign to the appropriate PM.

**Comment by sericks007** [comment]
@RichdiMSFT, can you please review this comment and either make a doc fix or assign it to the correct person? Thanks.

**Comment by josaw1** [comment]
Closed as won't fix.
