### ISSUE TITLE
Enhanced e-Commerce product discovery to be inventory-aware doesn't support multiple fulfillment location

### ISSUE THREAD

**Issue by 5fq** [MicrosoftDocs/dynamics-365-unified-operations-public#3982]
Enhanced e-Commerce product discovery to be inventory-aware considers stock of  warehouse assigned to Online store only. If you use DOM or have multiple fulfillment warehouses or use aggregate of stock from multiple warehouses to calculate inventory availability in Ecommerce this feature will not provide the accurate information. To avoid confusion, the article should be updated to explain how the attributes will be updated to show an item as available or out of stock.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b49084e9-8f21-21f2-bff0-f9cdcd62bd4a
* Version Independent ID: 216ebb58-9e0d-295a-3396-ca0e3bd3af7c
* Content: [Search results module - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/search-result-module#enable-inventory-awareness-for-the-search-results-module)
* Content Source: [articles/commerce/search-result-module.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/search-result-module.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @anupamar-ms
* Microsoft Alias: **anupamar**

**Comment by sericks007** [comment]
@5fq, thank you for providing this feedback.

@anupamar-ms, please update the content as suggested.

**Comment by sericks007** [comment]
Bug 693419 has been logged to track this issue.

**Comment by josaw1** [comment]
Closed as won't fix.
