### ISSUE TITLE
Shipping carrier > Services > Load template field not explained

### ISSUE THREAD

**Issue by MarisRe** [MicrosoftDocs/dynamics-365-unified-operations-public#3985]
Shipping carrier > Services > Load template Id field not explained

What is the purpose of entering Load template Id field in Shipping carrier > Services tab?
This field is not explained in documentation.

![image](https://user-images.githubusercontent.com/104499854/165501091-0ff0a234-ee68-4af6-aba5-bc4a79dd845c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a15cf904-0ed6-640f-1ac2-987e40d44296
* Version Independent ID: 80f5226d-05a1-22bd-6559-37f40b077602
* Content: [Set up shipping carriers - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/transportation/tasks/set-up-shipping-carriers)
* Content Source: [articles/supply-chain/transportation/tasks/set-up-shipping-carriers.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/transportation/tasks/set-up-shipping-carriers.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @Henrikan
* Microsoft Alias: **henrikan**

**Comment by Henrikan** [comment]
You will need to engage the PM for Transportation management. That is not I.

Best regards,
Henrik Andersen
Senior Product Manager SCM
Microsoft Dynamics 365 For Finance & Operations

Microsoft Development Center Copenhagen APS
Kanalvej 7
DK-2800 Kongens Lyngby
CVR: 76247218

Mobile: +45 29 22 94 76
***@***.******@***.***>
 [View my profile on LinkedIn] <https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fdk.linkedin.com%2Fpub%2Fhenrik-andersen%2F2%2F372%2F364&data=04%7C01%7Chenrikan%40microsoft.com%7Cbbb9b77ee9fe4284b9fa08d9710e8628%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637665129465764888%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kWp9whxl8aH%2FWf22uMVT0zffPROYYHLioEFqM4cRXCc%3D&reserved=0>

***@***.***



This communication may contain privileged and confidential information. Use, disclosure, or retention of this information is prohibited if you are not the intended recipient. If you have received this message in error, please delete the message from
your system. Thank you.



From: MarisRe ***@***.***>
Sent: 27. april 2022 12:44
To: MicrosoftDocs/dynamics-365-unified-operations-public ***@***.***>
Cc: Henrik Andersen ***@***.***>; Mention ***@***.***>
Subject: [MicrosoftDocs/dynamics-365-unified-operations-public] Shipping carrier > Services > Load template field not explained (Issue #3985)


Shipping carrier > Services > Load template Id field not explained

What is the purpose of entering Load template Id field in Shipping carrier > Services tab?
This field is not explained in documentation.

[image]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F104499854%2F165501091-0ff0a234-ee68-4af6-aba5-bc4a79dd845c.png&data=05%7C01%7CHENRIKAN%40microsoft.com%7Cc1ed755132a44791342208da283ad741%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637866530472167019%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=1nlu00Exj7ikhzwxxslWCyV0qEGF5GoEFjThY%2BgMZww%3D&reserved=0>

________________________________
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

  *   ID: a15cf904-0ed6-640f-1ac2-987e40d44296
  *   Version Independent ID: 80f5226d-05a1-22bd-6559-37f40b077602
  *   Content: Set up shipping carriers - Supply Chain Management | Dynamics 365<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fdynamics365%2Fsupply-chain%2Ftransportation%2Ftasks%2Fset-up-shipping-carriers&data=05%7C01%7CHENRIKAN%40microsoft.com%7Cc1ed755132a44791342208da283ad741%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637866530472167019%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=R8XLcQBHdgNeZEsO4ZA3mwspINVbxfHeRXUEnnrqBmw%3D&reserved=0>
  *   Content Source: articles/supply-chain/transportation/tasks/set-up-shipping-carriers.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FDynamics-365-Unified-Operations-Public%2Fblob%2Fmain%2Farticles%2Fsupply-chain%2Ftransportation%2Ftasks%2Fset-up-shipping-carriers.md&data=05%7C01%7CHENRIKAN%40microsoft.com%7Cc1ed755132a44791342208da283ad741%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637866530472217459%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BGqMoJS13xa65ExFxv%2BTgC1OryLKOinUKPIqXLshDKI%3D&reserved=0>
  *   Service: dynamics-365-supply-chain
  *   Product: ****
  *   Technology: ****
  *   GitHub Login: @Henrikan<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FHenrikan&data=05%7C01%7CHENRIKAN%40microsoft.com%7Cc1ed755132a44791342208da283ad741%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637866530472217459%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=yt%2FPPU0BqKBJqpVf2s3Ar4kWS3m47ZDphhtE8%2Fc6koM%3D&reserved=0>
  *   Microsoft Alias: henrikan

**Comment by MarisRe** [comment]
> 

What do you mean? I am looking for documumentation of this field as it is not documented in official MS documentation page.

**Comment by Henrikan** [comment]
You have called me out in an issue in Github. Please explain the reason why - thanks in advance.

Best regards,
Henrik Andersen
Senior Product Manager SCM
Microsoft Dynamics 365 For Finance & Operations

Microsoft Development Center Copenhagen APS
Kanalvej 7
DK-2800 Kongens Lyngby
CVR: 76247218

Mobile: +45 29 22 94 76
***@***.******@***.***>
 [View my profile on LinkedIn] <https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fdk.linkedin.com%2Fpub%2Fhenrik-andersen%2F2%2F372%2F364&data=04%7C01%7Chenrikan%40microsoft.com%7Cbbb9b77ee9fe4284b9fa08d9710e8628%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637665129465764888%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kWp9whxl8aH%2FWf22uMVT0zffPROYYHLioEFqM4cRXCc%3D&reserved=0>

***@***.***



This communication may contain privileged and confidential information. Use, disclosure, or retention of this information is prohibited if you are not the intended recipient. If you have received this message in error, please delete the message from
your system. Thank you.

**Comment by MarisRe** [comment]
> You have called me out in an issue in Github. Please explain the reason why - thanks in advance. Best regards, Henrik Andersen Senior Product Manager SCM Microsoft Dynamics 365 For Finance & Operations Microsoft Development Center Copenhagen APS Kanalvej 7 DK-2800 Kongens Lyngby CVR: 76247218 Mobile: +45 29 22 94 76 ***@***.******@***.***> [View my profile on LinkedIn] <https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fdk.linkedin.com%2Fpub%2Fhenrik-andersen%2F2%2F372%2F364&data=04%7C01%7Chenrikan%40microsoft.com%7Cbbb9b77ee9fe4284b9fa08d9710e8628%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637665129465764888%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kWp9whxl8aH%2FWf22uMVT0zffPROYYHLioEFqM4cRXCc%3D&reserved=0> ***@***.*** This communication may contain privileged and confidential information. Use, disclosure, or retention of this information is prohibited if you are not the intended recipient. If you have received this message in error, please delete the message from your system. Thank you. From: MarisRe ***@***.***> Sent: 27. april 2022 13:12 To: MicrosoftDocs/dynamics-365-unified-operations-public ***@***.***> Cc: Henrik Andersen ***@***.***>; Mention ***@***.***> Subject: Re: [MicrosoftDocs/dynamics-365-unified-operations-public] Shipping carrier > Services > Load template field not explained (Issue #3985) What do you mean? I am looking for documumentation of this field as it is not documented in official MS documentation page. - Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fdynamics-365-unified-operations-public%2Fissues%2F3985%23issuecomment-1110874484&data=05%7C01%7CHENRIKAN%40microsoft.com%7Cd2e63bb29d854919ac3208da283eae6c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637866546941618939%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=gGA04xR7wYRgW36lHWoWNvfntMh%2ByBowYGv7ksKi%2BWY%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALFFYIBYRV5MBODSM3YARGLVHEOGFANCNFSM5UOWL33Q&data=05%7C01%7CHENRIKAN%40microsoft.com%7Cd2e63bb29d854919ac3208da283eae6c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637866546941618939%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=nnIkZCj%2BNrA6i%2FDyxnBF17I19kShCHk4cM0PwI8HllM%3D&reserved=0>. You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

Ok, I was exploring the setup of Shipping carrier service in D365. Noticed, there is a Load template Id field. Looked for the documentation of this field and how it works in conjuction with Shipping carrier setup.
Opened documentation from D365 Help menu. I was directed to this this page: https://docs.microsoft.com/en-us/dynamics365/supply-chain/transportation/tasks/set-up-shipping-carriers which is MS official documentation.
This page doesn't contain documentation about Load template Id field.

At the bottom of page I used Feedback button.

![image](https://user-images.githubusercontent.com/104499854/165511699-6b442863-1bb5-48cd-8695-5e2afd7d3015.png)

Feedback button directed me to this GitHub channel and I reported my question here accordingly.

**Comment by sericks007** [comment]
@kamaybac, could you please help resolve this issue?

**Comment by kamaybac** [comment]
@MarisRe , thank you for contacting us regarding this help topic. I will forward this issue to the correct author for consideration, and we will seek to add documentation for this field. 

In the meantime, I can tell you that you can use this field to assign a load template for each of the carrier services listed here. The load template defines maximum measurements for weight and volume of an entire load. For example, the load template might represent the size of a container or truck.

You can read a bit more about how to set up load templates here: https://docs.microsoft.com/en-us/dynamics365/supply-chain/transportation/tasks/load-template

**Comment by kamaybac** [comment]
@Weijiesa, can you comment on how load templates are used by shipping carrier services?

**Comment by MarisRe** [comment]
Hi,

Thank you for your answer. I see your second e-mail now and that’s the main question does it has some functionality behind as well or it is just informative field on carrier service.

Maris Reinfelds
Lead Solution Consultant
TietoEvry Transform, Latvia

Mobile +37128382732
Gustava Zemgala gatve 76, Rīga, Latvia, LV1039
***@***.******@***.***>

**Comment by Weijiesa** [comment]
@MarisRe 

The load template not just an informative field, it can be used to setup loading building template which could be used in load building workbench to help user apply load building strategies when create loads.

You can find some information at: 
https://docs.microsoft.com/en-us/dynamics365/supply-chain/transportation/tasks/load-building-workbench

Furthermore, below blog might be helpful:
https://ellipsesolutions.com/dynamics-365-the-load-workbenches-part-2-load-building/

B.R
Roger
