### ISSUE TITLE
SRU now has 4 digits in Sweden

### ISSUE THREAD

**Issue by klofskar** [MicrosoftDocs/dynamics-365-unified-operations-public#3986]
[Enter feedback here]

In Sweden there is the use nowadays to use the 4 digit SRU-codes. It was several years ago that 3 digits were commonly in use. 
It is good however to see this but it certainly would be a great improvement if this could be updated to the new versions of 4 digits, then the system would be even more useful in Sweden for accounting issues. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb860ee3-23e2-cd0f-c67a-772dcbe85f4f
* Version Independent ID: 0de27640-e45c-2fec-0b40-049c3e42abe8
* Content: [Export financial information for auditors in Sweden - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/emea-swe-sie-standard-report)
* Content Source: [articles/finance/localizations/emea-swe-sie-standard-report.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/emea-swe-sie-standard-report.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @ShylaThompson
* Microsoft Alias: **roschlom**

**Comment by sericks007** [comment]
Bug 693432 has been logged to track this issue.

**Comment by klofskar** [comment]
Hello

The thing is that in Sweden you need to enter a 4 Digit SRU-code to be able to do the export to work properly. Microsoft is by default only support the very old 3-digit code so
in most cases the export of a SIE-file does not work in order to be used in 3rd party systems if not the correct 4-digit code is added.

Please add in the article that it is only the old 3-digit code that is working in the system and not the new 4-digit code that is standard now in Sweden and for the Swedish Tax Authority.





***@***.***

Kristina Klöfskär| Sr Consultant
D365
Avanade Sweden
Alströmergatan 12, Stockholm
mobile: +46 730 74 22 76
www.avanade.com/se-no<http://www.avanade.com/se-no>
***@***.***

From: Sally Erickson ***@***.***>
Sent: Wednesday, 25 May 2022 13:46
To: MicrosoftDocs/dynamics-365-unified-operations-public ***@***.***>
Cc: Kristina Klöfskär ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [MicrosoftDocs/dynamics-365-unified-operations-public] SRU now has 4 digits in Sweden (Issue #3986)

You don't often get email from ***@***.******@***.***>. Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

@klofskar<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fklofskar&data=05%7C01%7Ckristina.klofskar%40avanade.com%7C165a18c533694332728108da3e4434ad%7Ccf36141cddd745a7b073111f66d0b30c%7C0%7C0%7C637890759917177890%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mp89gGyzxhfJ%2FqbLv9rPJJIouV%2BJh47bh4qVJOk4wjE%3D&reserved=0>, please provide a more specific example of how the documentation should be changed. Thank you!

**Comment by sericks007** [comment]
@klofskar, thank you for clarifying!  

@Anasyash, please update the content as advised.

**Comment by Anasyash** [comment]
@klofskar in my opinion this is a gap in the system, could you please create a support ticket and explain this requirement with links to legislation so that MS support team can contact MS product team and request a feature update to 4-digit codes. We should not update current topic explaining that we have a feature that cannot be used.
