### ISSUE TITLE
Windows Server 2022 Support

### ISSUE THREAD

**Issue by pgub** [MicrosoftDocs/dynamics-365-unified-operations-public#3987]
Support for Windows Server 2022 is requested

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fe44c05-ed58-b554-859e-2da552dbbd9d
* Version Independent ID: e638edab-dd54-6008-f210-524fd52b0e5b
* Content: [Install the Document Routing Agent to enable network printing - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/install-document-routing-agent#is-the-document-routing-agent-supported-on-microsoft-windowsserver2019)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/install-document-routing-agent.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/analytics/install-document-routing-agent.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @RichdiMSFT
* Microsoft Alias: **richdi**

**Comment by sericks007** [comment]
@pgub, thank you for providing this feedback.

@RichdiMSFT, please update the content as requested.

**Comment by sericks007** [comment]
Bug 693434 has been logged to track this issue.

**Comment by josaw1** [comment]
Closed as won't fix.
