### ISSUE TITLE
Insufficient info on behavior when importing data

### ISSUE THREAD

**Issue by sglickliddicoat** [MicrosoftDocs/dynamics-365-unified-operations-public#3991]
there's a note "This information applies only to the application of default dimensions in the application. If you import data by using Microsoft Excel or the Data Management Framework, the behavior differs." but no link to where information on the behavior when you are importing data, which is what I'm looking for.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f869f0f-afc1-e32b-94d0-aeb31ebb0dbb
* Version Independent ID: d8896ca5-32ad-5847-e131-815e140c8471
* Content: [Financial dimensions and posting - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/general-ledger/default-dimensions)
* Content Source: [articles/finance/general-ledger/Default-dimensions.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/general-ledger/Default-dimensions.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @aprilolson
* Microsoft Alias: **aolson**

**Comment by josaw1** [comment]
Thank you for your comment. @aprilolson can you please review?

**Comment by josaw1** [comment]
Closed as won't fix.
