### ISSUE TITLE
How to access "Purchase in bulk" screen

### ISSUE THREAD

**Issue by ricdlee** [MicrosoftDocs/dynamics-365-unified-operations-public#3992]
Hello,

In the doc https://docs.microsoft.com/en-us/dynamics365/commerce/b2b/quick-bulk-orders and in the section titled "Bulk order by variant," there is no explanation on how the screen shown in this section is come upon. Can that detail be provided?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 918c4ec5-3bae-6efd-f25f-41d80f769b11
* Version Independent ID: 918c4ec5-3bae-6efd-f25f-41d80f769b11
* Content: [Place B2B website orders quickly - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/b2b/quick-bulk-orders)
* Content Source: [articles/commerce/b2b/quick-bulk-orders.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/b2b/quick-bulk-orders.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @shajain
* Microsoft Alias: **shajain**

**Comment by josaw1** [comment]
Thank you for your feedback. @ShalabhjainMSFT can you please review?

**Comment by ricdlee** [comment]
Update: Using Site Builder for the B2B Adventure Works site, I had to first add it as a module within a container. Unless your environment comes with this enabled, it has to be manually added in Site Builder. It'd be nice to have a link on the doc to another doc explaining this.
