### ISSUE TITLE
Suggestions for "Checklist to follow before activation"

### ISSUE THREAD

**Issue by Sigvelli** [MicrosoftDocs/dynamics-365-unified-operations-public#3993]
Suggestion 6:
6. "Make sure that the worker is set up as a user in the Manager role (checked by validation)."
It could save the next reader some time if he knew that you are referring to the "POS permissions" form. (and not the User form as I first believed)

Suggestion 12 and 13 would be easier if this were AX 2012. Could you please point to where the Real-time Service profile is found in D365?
12. "Make sure that the language is set up for the Commerce Data Exchange: Real-time Service user profile (JBB in the demo data)."
13. "Make sure that the Real-time Service profile has the correct access."

Suggestion 14 was also difficult to locate for a person who hasn't set up electronic funds before. Which form are you referring to?
14. "Make sure that the electronic funds transfer (EFT) configuration value is present."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfe62687-b97a-369a-8b3f-80c712a5aca3
* Version Independent ID: bfc751c1-3f68-be7d-04e8-99c5575fdec9
* Content: [Point of sale (POS) device activation - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/retail-device-activation)
* Content Source: [articles/commerce/dev-itpro/retail-device-activation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/retail-device-activation.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @athinesh99
* Microsoft Alias: **athinesh**

**Comment by josaw1** [comment]
Thank you for your feedback. @bicyclingfool can you please review?

**Comment by josaw1** [comment]
Closed as won't fix.
