### ISSUE TITLE
Independent packaging and "Log events to Application Insights in the POS extension projects" documentation

### ISSUE THREAD

**Issue by Halldor10** [MicrosoftDocs/dynamics-365-unified-operations-public#3994]
Under the section: "Log events to Application Insights in the POS extension projects," in step 9, it does no longer apply to the new independent packaging extension project.  An updated documentation is needed on what to add to the project file, so the applicationInsights files are copied as part of the installation process when installing the extension for an independent package

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f659eadc-c39c-a5e4-cfe4-27fea2f77523
* Version Independent ID: 48e06663-f4a1-b540-db40-147b35a840f9
* Content: [Log extension events to Application Insights - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/commerce-application-insights)
* Content Source: [articles/commerce/dev-itpro/commerce-application-insights.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/commerce-application-insights.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by josaw1** [comment]
Thank you for your feedback. @mugunthanm can you please review this?

**Comment by josaw1** [comment]
Closed as won't fix.
