### ISSUE TITLE
Which are the preview features and which release contains the preview?

### ISSUE THREAD

**Issue by KheeChan** [MicrosoftDocs/dynamics-365-unified-operations-public#3996]
It is mentioned at the top of this page that "Some or all of the functionality noted in this topic is available as part of a preview release.". My requests:
1. Please provide information on exactly which of the functionality is actually part of a preview release.
2. Please provide information on which release the preview first appeared in.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 480efd0a-174d-dae4-4bea-4ed51e393644
* Version Independent ID: 54c317b9-7f64-fc0c-03dd-b4c54121d23a
* Content: [Archive credit card transaction data - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/archive-cc-data?source=docs)
* Content Source: [articles/commerce/dev-itpro/archive-cc-data.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/archive-cc-data.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @BrianShook
* Microsoft Alias: **brshoo**

**Comment by josaw1** [comment]
Thank you for your feedback. @BrianShook can you please take a look?
