### ISSUE TITLE
Please update timetable for operating system maintenance

### ISSUE THREAD

**Issue by DKobayashi-ykgw** [MicrosoftDocs/dynamics-365-unified-operations-public#3999]
In topic "What is the schedule for operating system maintenance?", we would appreciate it if you could update the timetable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fcc1802-115b-4ac2-f34f-aa73eac426f4
* Version Independent ID: d758bfc6-245e-43d6-8bde-31282cea0a64
* Content: [Planned maintenance in self-service environments FAQ - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/plannedmaintenance-selfservice)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/plannedmaintenance-selfservice.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/deployment/plannedmaintenance-selfservice.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @rashmansur
* Microsoft Alias: **rashmim**

**Comment by twheeloc** [comment]
@DKobayashi-ykgw, thank you for the question. 
@rashmansur, please review the feedback and update as needed.

**Comment by DKobayashi-ykgw** [comment]
Hi @twheeloc, @rashmansur,
How is the progress of this matter?

**Comment by sericks007** [comment]
Hi @DKobayashi-ykgw,

@matapg007 is in the process of updating this content.  @matapg007, can you update the "What is the schedule for operating system maintenance?" to add more dates?

**Comment by sericks007** [comment]
@DKobayashi-ykgw, this content will be updated later today.

**Comment by DKobayashi-ykgw** [comment]
@sericks007, @matapg007, Thank you for update contents.

In section "What are the planned maintenance windows?", there described as
---quote---
Microsoft recommends that you avoid the following activities during the maintenance window:
 - Non-retryable batch jobs
 - No servicing actions
---end of quote---
In other hands, in notes there described as 
---quote---
Effective July 2022 through September 2022, Microsoft will start to roll out updates to the production environment during any weekend, and outside of normal business hours, to help minimize any potential impact on your environments.
---end of quote---
and the maintenance dates are not specified.

How can we avoid 'Non-retryable batch jobs' and 'Servicing actions' during maintenance?

**Comment by matapg007** [comment]
Thanks for feedback! I will add more details in documentation. We recommend setting batch retry to make batch jobs resilience so that during servicing batch job fails due to transient issues then can be retried.  If there is ongoing servicing displayed on LCS, we recommend not to trigger any servicing actions while servicing is in progress.  we have published servicing window for each Geo for reference.

Request you to follow how to enable batch retries document to make batch jobs retry-able. https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/retryable-batch
Hope above details help.
