### ISSUE TITLE
XSLT scripting in Data management - Deprecated

### ISSUE THREAD

**Issue by Stuart-Honour-HCL** [MicrosoftDocs/dynamics-365-unified-operations-public#4000]
Seems this article leads the user to use a deprecated feature.

When using this article and at Step 15 of Section Set up the import of MT940 bank statements the following error is displayed 

Execution of scripts was prohibited. Use the XsltSettings.EnableScript property to enable it. An error occurred at (516,7).

Deprecated Feature.: https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/get-started/removed-deprecated-features-platform-updates#feature-deprecation-effective-march-14-2022

Has this whole process now been replaced by using Electronic reporting?

https://docs.microsoft.com/en-us/dynamics365/finance/accounts-payable/import-BAI2-ER

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f6257c7-8c1f-f00a-4f51-2f8f20f1f09e
* Version Independent ID: c793b57d-f984-bb4d-d014-e2bf2da43f68
* Content: [Set up the advanced bank reconciliation import process - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/cash-bank-management/set-up-advanced-bank-reconciliation-import-process?source=docs)
* Content Source: [articles/finance/cash-bank-management/set-up-advanced-bank-reconciliation-import-process.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/cash-bank-management/set-up-advanced-bank-reconciliation-import-process.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @panolte
* Microsoft Alias: **panolte**

**Comment by twheeloc** [comment]
@Stuart-Honour-HCL, thank you for the question.
@sunfzam, please review this feedback and update the content as needed.

**Comment by sunfzam** [comment]
@twheeloc @Stuart-Honour-HCL , this is a Bank&Cash topic. Previously, colleagues have done enhancement to leverage electronic reporting to replace XSLT due to security issue. 

Will let team take a look
