### ISSUE TITLE
Steps for Sequencing Planned orders for Process manufacturing 

### ISSUE THREAD

**Issue by Navneetkat** [MicrosoftDocs/dynamics-365-unified-operations-public#4001]
[Steps given for sequence generations with Demo data in USPI company not working, Please confirm what is the issue either in demo data or instruction steps.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43b5b0fb-dfc2-eac7-2af6-da068b7fdb50
* Version Independent ID: 91e768e1-7563-1c7d-1059-dc91842bfaf1
* Content: [Sequence production jobs for process manufacturing - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/production-control/tasks/sequence-production-jobs-process-manufacturing)
* Content Source: [articles/supply-chain/production-control/tasks/sequence-production-jobs-process-manufacturing.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/production-control/tasks/sequence-production-jobs-process-manufacturing.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @johanhoffmann
* Microsoft Alias: **johanho**

**Comment by twheeloc** [comment]
@Navneetkat, thank you for the feedback.
@johanhoffmann, please review the feedback and update the content as needed.

**Comment by josaw1** [comment]
Closing as won't fix.
