### ISSUE TITLE
Clarify the steps to be "In dataverse"

### ISSUE THREAD

**Issue by Kai-Cloud** [MicrosoftDocs/dynamics-365-unified-operations-public#4002]
Our customer/partner reported that they didn't know how to be "in dataverse" per [point 1](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/power-platform/enable-virtual-entities#generate-virtual-entities).

Could you please add just a few more guidance like:
- "Go to Power platform admin center, in the Environment module, and get the Environment URL. Click the URL to get in dataverse..." 

Thanks, Kai

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc844b0c-c603-a69c-9387-1f56ddd875ac
* Version Independent ID: cc844b0c-c603-a69c-9387-1f56ddd875ac
* Content: [Enable Microsoft Dataverse virtual entities - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/power-platform/enable-virtual-entities)
* Content Source: [articles/fin-ops-core/dev-itpro/power-platform/enable-virtual-entities.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/power-platform/enable-virtual-entities.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @jaredha
* Microsoft Alias: **jaredha**

**Comment by jaredha** [comment]
Thanks for the recommendation. I've submitted documentation updates to include more detail on the steps to get up to the point of the Advanced Find page.

**Comment by sericks007** [comment]
The documentation has been updated and will be published later today.
