### ISSUE TITLE
User-based service protection API limits

### ISSUE THREAD

**Issue by d3fr0g** [MicrosoftDocs/dynamics-365-unified-operations-public#4003]
The User-based service protection API limits section starts with "Two of the" and then there are 3 factors. Do we know which 2 or random?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc0a8dff-9a51-bd7b-bc9a-841acba03aba
* Version Independent ID: cc0a8dff-9a51-bd7b-bc9a-841acba03aba
* Content: [Service protection API limits - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/service-protection-api-limits)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/service-protection-api-limits.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/service-protection-api-limits.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @jaredha
* Microsoft Alias: **jaredha**

**Comment by jaredha** [comment]
Yes, this is detailed in the table in that section of the topic. The "Number of requests" and "Execution time" limits are measured within a five-minute sliding window.
