### ISSUE TITLE
Option Not Available to View Marked Transactions

### ISSUE THREAD

**Issue by PayneNathan** [MicrosoftDocs/dynamics-365-unified-operations-public#4006]
This page references to go to the following location:
**(Accounts receivable > Periodic tasks > Customer marked transaction details)**

However, no such option can be found on our system and we recently upgraded to 10.0.25. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b2a4651-651e-c969-43e4-44cdf8af81d6
* Version Independent ID: a74845f6-6a8a-bc14-d3a0-61118a2a8f66
* Content: [Settlement overview - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/cash-bank-management/settlement-overview)
* Content Source: [articles/finance/cash-bank-management/settlement-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/cash-bank-management/settlement-overview.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @panolte
* Microsoft Alias: **panolte**

**Comment by twheeloc** [comment]
@PayneNathan, thank you for the feedback.
@panolte, please review this feedback and update the content as needed.

**Comment by panolte** [comment]
There is a feature called Marked transaction detail form.  This feature will need to be enabled to use this functionality.
