### ISSUE TITLE
Data Lake Connection String Stored in KeyVault

### ISSUE THREAD

**Issue by AndyStout** [MicrosoftDocs/dynamics-365-unified-operations-public#4007]
This article glosses over the fact that the connection string is needed from the data lake storage account and that it must be stored in the keyvault before being referenced on the System Parameters page in Dynamics FO.  It is not obvious how to acquire the connection string

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a344a5de-68fa-e9cf-28eb-51269c33b9b3
* Version Independent ID: 1b3ede62-3954-574b-5778-8cdee0ededfe
* Content: [Make Entity store available as a Data Lake - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/entity-store-data-lake)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/entity-store-data-lake.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/entity-store-data-lake.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by twheeloc** [comment]
@AndyStout, thank you for the feedback.
@MilindaV2, please review the feedback and update the content as needed.

**Comment by josaw1** [comment]
Closing as won't fix.
