### ISSUE TITLE
Incorrect offer type name?

### ISSUE THREAD

**Issue by emuench** [MicrosoftDocs/dynamics-365-unified-operations-public#4008]
I think the three new terms are:

- Dynamics 365 apps on Dataverse and Power Apps
- Dynamics 365 Operations Apps
- Dynamics 365 Business Central

I believe finance is now in Biz Central.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27899f77-9cc9-1831-fa16-9c0c71f8f1c3
* Version Independent ID: 4bfcb1d6-3e1d-b24b-4429-ab3b8f31eb3e
* Content: [What's new or changed in Finance and Operations apps home page - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/whats-new-changed)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/whats-new-changed.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/whats-new-changed.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by kfend** [comment]
@emuench - Thanks for the feedback. Finance has not become Biz Central or Business Central. It is still Dynamics 365 Finance. Thanks!
