### ISSUE TITLE
MSbuild and VS 2019 version

### ISSUE THREAD

**Issue by Alpa-Chino** [MicrosoftDocs/dynamics-365-unified-operations-public#4009]
Hi!

Since the new VHD came with VS2019, the recommendation/ version match to msbuild version is missing. Can you please update the doc that azure pipelines which msbuild we should use depending on the VHD/VS version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3f216bf-8601-a605-f70a-0cd21dec87d3
* Version Independent ID: a21ab2a4-d06a-0c89-0f10-4961a79e4035
* Content: [Update a legacy pipeline in Azure Pipelines - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/pipeline-msbuild-update)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/pipeline-msbuild-update.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/dev-tools/pipeline-msbuild-update.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @jorisdg
* Microsoft Alias: **jorisde**

**Comment by kfend** [comment]
@Alpa-Chino - Thank you for the feedback.
@jorisdg - Can you please take a look and update the topic as needed? Thanks!

**Comment by kfend** [comment]
Created bug 695526 to track this issue - it is currently being worked on.

**Comment by sericks007** [comment]
This content has been updated. The updated content will be published later today.
