### ISSUE TITLE
Adyen Merchant account ID

### ISSUE THREAD

**Issue by oysbre** [MicrosoftDocs/dynamics-365-unified-operations-public#4010]
If the Merchant account ID from Adyen contains underscore and/or dash and use this in the Adyen Payment connector, MPOS cannot communicate with the terminal stating "NotFound".

**Comment by kfend** [comment]
@oysbre - Thank you for the feedback. Can you please let me know what topic you are referring to? Thank you.

**Comment by kfend** [comment]
Closing this issue as I don't have enough information to work with. @oysbre - if you want to reopen and provide more information about the topic you are referring to, please do. Thanks!
