### ISSUE TITLE
Wrong steps

### ISSUE THREAD

**Issue by Doriano** [MicrosoftDocs/dynamics-365-unified-operations-public#4012]
Steps 11 onwards does not makes sense. 
Can you please check, and perhaps add screenshots.

Thanks, 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3353bfbb-1523-7788-d74d-d3a0ffbb6edb
* Version Independent ID: 9cdf1e1e-c410-27b0-9032-0afb3d6f7465
* Content: [Create call center orders - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/tasks/create-call-center-orders)
* Content Source: [articles/commerce/tasks/create-call-center-orders.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/tasks/create-call-center-orders.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by kfend** [comment]
@Doriano - Thank you for the feedback.
@josaw1 - Can you please take a look and update the topic as needed? Thanks!

**Comment by josaw1** [comment]
@ashishmsft can you please address this issue?

**Comment by ashishmsft** [comment]
@ShalabhjainMSFT would be right owner for content related to 'Order creation'

**Comment by kfend** [comment]
Created bug 695595 to track this issue.
