### ISSUE TITLE
Request following correction to clarify the difference between [End of service] and [End of support]

### ISSUE THREAD

**Issue by YujiImaoka** [MicrosoftDocs/dynamics-365-unified-operations-public#4013]
[Enter feedback here]

We would like to request following correction in document (A) and (B)to clarify the difference between [End of service] and [End of support] and the corresponding versions of each.
(A) https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/one-version#what-does-end-of-service-mean
(B) https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/versions-update-policy

Request for (A) 
Please change [What does end of service mean?] section as follows. And add [What does end of support mean?] section as like follows.

What does end of service mean?
Microsoft won't provide any fixes to issues on versions that have reached their end of service(Version N-2 or older than Version N-2). 
If you encounter an issue on a version that has reached its end of service, you must update to the latest update and then report the issue if it persists.
(Version that are being serviced)
Version N is the latest version
Version N-1 is one version older than N
 
End of service date of each version.
[https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/public-preview-releases#targeted-release-schedule-dates-subject-to-change](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fdynamics365%2Ffin-ops-core%2Ffin-ops%2Fget-started%2Fpublic-preview-releases%23targeted-release-schedule-dates-subject-to-change&data=05%7C01%7Cyuji.imaoka%40microsoft.com%7C83f9935ec6d64fcf8a3708da37e1658b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637883738465672925%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=d8TVzeu8Xze2EBhuUbf7qbuac8bzeGPUy0pHFsTKVKs%3D&reserved=0)
 
What does end of support mean?
Microsoft will investigate or troubleshoot any issue that you encounter on a version that complies with one version update policy(which is Version N-3 or newer than Version N-3 ).
And Microsoft will not investigate or troubleshoot any issue that you encounter on a version that does not comply with one version update policy(which is Version N-4 or older than Version N-4 ).
(Example)
Version N-2: MS will investigate or trouble shoot
Version N-3: MS will investigate or trouble shoot
Version N-4: MS won’t investigate or trouble shoot

Request for (B) 
Please remove this sentence [Microsoft also won't investigate or troubleshoot any issue that you encounter on a version that is older than three service updates.], because document (A) also has this sentence. Maintaining both documents is not efficient.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23fde63f-0f6f-b1a0-50c8-e1bf5f6a48c4
* Version Independent ID: 59a1f734-87cb-f34c-afd5-9f14de877584
* Content: [One Version service updates FAQ - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/one-version#what-does-end-of-service-mean)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/one-version.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/one-version.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by sericks007** [comment]
@YujiImaoka, thank you for your feedback.  I'll have our PMs take a look at this.
