### ISSUE TITLE
Database Storage clarifications is causing confusion between the production and Sandbox environments. 

### ISSUE THREAD

**Issue by Chrisslima** [MicrosoftDocs/dynamics-365-unified-operations-public#4014]
Hi all, 

The Database storage clarifications is causing confusion at https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/imp-lifecycle/environment-planning#:~:text=Database%20storage%3A,365%20pricing.

It's attached only to "Production Environments" in Docs page, but in the D365 Licensing Guide, the Operations Database capacity included is indicated "by Tenant" in the table at page 41. 

Looking to this documentation, we are led to believe that only the production environment will consume capacity. Would you please check? 

Thank you, 

Christiane (Microsoft Alias: chdelima)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2402dfea-008a-c7bb-8a3b-1d0457a39665
* Version Independent ID: 4936afad-9a39-e65d-a00c-81246de632cb
* Content: [Environment planning - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/imp-lifecycle/environment-planning)
* Content Source: [articles/fin-ops-core/fin-ops/imp-lifecycle/environment-planning.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/imp-lifecycle/environment-planning.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by kfend** [comment]
Bug 695598 created to track this issue.

**Comment by josaw1** [comment]
Closed as won't fix.
