### ISSUE TITLE
I think the metioned 27.50 amount is wrong in running average calculations.

### ISSUE THREAD

**Issue by justobc** [MicrosoftDocs/dynamics-365-unified-operations-public#4015]
[Enter feedback here]

I think the metioned 27.50 amount is wrong in running average calculations. In "LIFO with marking" example. Please verify. My calculations es 20.00 instead of 27.50. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7408496e-94bc-ae85-2038-8f803e00c6bd
* Version Independent ID: 9a33650a-b839-8484-013a-3d0a581e4116
* Content: [LIFO with physical value and marking - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/cost-management/lifo-physical-value-marking)
* Content Source: [articles/supply-chain/cost-management/lifo-physical-value-marking.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/cost-management/lifo-physical-value-marking.md)
* Service: **dynamics-365-supply-chain**
* GitHub Login: @JennySong-SH
* Microsoft Alias: **yanansong**

**Comment by kfend** [comment]
@justobc - Thank you for the feedback.
@JennySong-SH - Can you please take a look at this and update the topic as needed? Thanks!

**Comment by kfend** [comment]
Bug 695597 created to track this issue.

**Comment by josaw1** [comment]
Fixed.
