### ISSUE TITLE
Update Previous Version Video with latest TechTalk released

### ISSUE THREAD

**Issue by Chrisslima** [MicrosoftDocs/dynamics-365-unified-operations-public#4016]
Dear all, 

We have recently released great TechTalks but our D365 SCM landing page still makes reference to previous versions videos, it would be great if you could keep this documentation updated with our latest TechTalk resources.

D365 SCM landing page: https://docs.microsoft.com/en-us/dynamics365/supply-chain/#:~:text=The%20following%20tech,Blogs

Example of updated TechTalk series for WMS/TMS: https://community.dynamics.com/365/dynamics-365-fasttrack/b/techtalks/posts/techtalk-series-warehouse-management

Thank you, 

Christiane (chdelima)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc3403f8-b1b4-d6b8-09c6-0f1ed6660006
* Version Independent ID: cac73139-b8d5-6fe8-d7f6-81ad8afb1695
* Content: [Supply Chain Management home page - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/)
* Content Source: [articles/supply-chain/index.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/index.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @kamaybac
* Microsoft Alias: **kamaybac**

**Comment by kfend** [comment]
Bug 695596 created to track this issue.

**Comment by josaw1** [comment]
Closed as won't fix.
