### ISSUE TITLE
Confusion on the countries where the feature is unavailable

### ISSUE THREAD

**Issue by thedynamicsgirl** [MicrosoftDocs/dynamics-365-unified-operations-public#4017]
[In D365 it says that this feature "**_Cloud powered customer search_**" is unavailable in the regions: Brazil, UK, India and Canada, where as in the docs it says only Brazil and India. Which one is correct?
![image](https://user-images.githubusercontent.com/81991433/169506025-2a8ec2ae-e16e-40c4-b24c-96c2f515e8c1.png)

![image](https://user-images.githubusercontent.com/81991433/169506232-43832d3f-1a12-4818-9fbb-39d824ef584d.png)

]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e80a4782-4d57-4167-f16f-f48043a5fbdb
* Version Independent ID: d88a8284-a2da-2d84-1abd-d49ea9c55d59
* Content: [Product search and customer search in the point of sale (POS) - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/POS-search-improvements#cloud-powered-customer-search)
* Content Source: [articles/commerce/POS-search-improvements.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/POS-search-improvements.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @ShalabhjainMSFT
* Microsoft Alias: **shajain**

**Comment by kfend** [comment]
Created bug 695594 to track this issue.

**Comment by kfend** [comment]
From what I understand, the documentation is correct and it's the Description field that needs to be updated. That is currently happening, so I am closing this issue.
