### ISSUE TITLE
Customization analysis report issue

### ISSUE THREAD

**Issue by ripannandy** [MicrosoftDocs/dynamics-365-unified-operations-public#402]
After running the command, Customization analysis report excel file is not recording extensions and EDT. Is there any other parameter to be added in the command to include these in excel output?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc23ac42-43d6-d82f-01c0-efa3f0823247
* Version Independent ID: 3adb9236-8cbb-2429-8e56-363ad76a4a43
* Content: [Customization Analysis Report (CAR) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-tools/customization-analysis-report)
* Content Source: [articles/dev-itpro/dev-tools/customization-analysis-report.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-tools/customization-analysis-report.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RobinARH
* Microsoft Alias: **robadawy**

**Comment by jorisdg** [comment]
The CAR report currently does not list extensions, which is a limitation in the tool itself.
