### ISSUE TITLE
move "note" section from 1 chapter

### ISSUE THREAD

**Issue by Simon-Syd** [MicrosoftDocs/dynamics-365-unified-operations-public#4020]
[Enter feedback here]
hello,

we just used the documentation to rotate cert, and this chapter is not very user friendly, maybe the "note" section could be better at the top of the chapter not at the end ?
![image](https://user-images.githubusercontent.com/60176428/169563501-19ff4eaa-7332-4676-87d3-1418bd262213.png)

the next chapter has the "note" at the beginning !

![image](https://user-images.githubusercontent.com/60176428/169563561-446004b3-a940-4852-9ceb-c5d35030ce5d.png)

thanks for your answer !

Simon

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eac091f6-4eb0-3174-d8ae-79ee922349a8
* Version Independent ID: b141a04f-324d-9050-59c8-2a761a99bdab
* Content: [Certificate rotation - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/certificate-rotation-on-prem#update-deployment-settings-in-lcs)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/certificate-rotation-on-prem.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/deployment/certificate-rotation-on-prem.md)
* Service: ****
* Product: **dynamics-365**
* Technology: ****
* GitHub Login: @PeterRFriis
* Microsoft Alias: **peterfriis**

**Comment by kfend** [comment]
@Simon-Syd - Thank you for the feedback.
@PeterRFriis - Can you please take a look at this and update the topic? Thanks!

**Comment by sericks007** [comment]
@faix, please review and consider updating the content, as suggested. Thanks!
