### ISSUE TITLE
Error code not covered

### ISSUE THREAD

**Issue by Alpa-Chino** [MicrosoftDocs/dynamics-365-unified-operations-public#4022]
Hi!

I was checking some of the dual write table map health checks, and i have found one with Error Code 1900. Can you please update this page with the new Error codes and their detailed explanation?

Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e86b1e0-0759-24c4-67f9-189c67246c80
* Version Independent ID: 2e86b1e0-0759-24c4-67f9-189c67246c80
* Content: [Errors codes for the table map health check - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/table-map-health-check)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/table-map-health-check.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/dual-write/table-map-health-check.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @NHelgren
* Microsoft Alias: **nhelgren**

**Comment by twheeloc** [comment]
@Alpa-Chino, thank you for the feedback.
@NHelgren, please review this feedback and update the content as needed.

**Comment by NHelgren** [comment]
@Alpa-Chino, @twheeloc  I am no longer the owner of this area. 

@RamaKrishnamoorthy Could you please review?

**Comment by RamaKrishnamoorthy** [comment]
Following PR has been created to fix this issue - https://github.com/MicrosoftDocs/Dynamics-365-Operations/pull/13987

**Comment by RamaKrishnamoorthy** [comment]
Sure Nathan, I am on it.

Thank you,
Rama.
