### ISSUE TITLE
Docs Page Clarification

### ISSUE THREAD

**Issue by aaronstackpole** [MicrosoftDocs/dynamics-365-unified-operations-public#4023]
There appear to be possibly instructions for more than one process here. I'm trying to install a deployable package in a VM, do I need to only follow the steps in that one section, or do I have to do all of the sections afterwards that describe creating a runbook and all that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d33c85d3-b6ce-09c0-0283-ea0dca89b605
* Version Independent ID: 489e8c40-65e8-a558-5934-27b677fa2f6f
* Content: [Install deployable packages from the command line - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/install-deployable-package)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/install-deployable-package.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/deployment/install-deployable-package.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @jorisdg
* Microsoft Alias: **jorisde**

**Comment by josaw1** [comment]
Closing as won't fix.
