### ISSUE TITLE
Insufficient documentation for creation of application id for recurring integrations

### ISSUE THREAD

**Issue by FH-Inway** [MicrosoftDocs/dynamics-365-unified-operations-public#4025]
The documentation for recurring integrations in Dynamics 365 contains the section [Authorization for the integration REST API](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/recurring-integrations#authorization-for-the-integration-rest-api). This section states the following: 

https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/blob/11ca071d681d200291269378c19c1af8c50e9365/articles/fin-ops-core/dev-itpro/data-entities/recurring-integrations.md?plain=1#L47

However, no information is provided how this application ID can be created and what the "appropriate" permissions are. 

Please provide detailed instructions on how to set up the app registration in Azure with all necessary configurations (e.g. permissions, authentication settings, is a secret required, ...)

Note that the general documentation on [how to create app registrations](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app) is not sufficient, because it lacks required information.

**Comment by twheeloc** [comment]
@FH-Inway, thank you for the feedback.
@Sunil-Garg, please review the feedback and update as needed.

**Comment by josaw1** [comment]
Closed as won't fix.
