### ISSUE TITLE
Integration keys order

### ISSUE THREAD

**Issue by maveloso** [MicrosoftDocs/dynamics-365-unified-operations-public#4028]
on the integration keys section, it would be good to specify that they need to be entered in the exact order of the article, if any of the pairs are reversed, you will get errors

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 710d0b0c-bd96-ca64-0e46-225dc6653c72
* Version Independent ID: a678c3e8-d98f-4c8d-8800-9ce3d983a17c
* Content: [Party and global address book troubleshooting - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/dual-write-troubleshooting-party-gab)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/dual-write-troubleshooting-party-gab.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/dual-write/dual-write-troubleshooting-party-gab.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @RamaKrishnamoorthy
* Microsoft Alias: **ramasri**

**Comment by twheeloc** [comment]
@maveloso, thank you for the feedback.
@RamaKrishnamoorthy, please review this feedback and update the content as needed.

**Comment by josaw1** [comment]
Closed as won't fix.
