### ISSUE TITLE
UI Changes

### ISSUE THREAD

**Issue by JoelLeichty** [MicrosoftDocs/dynamics-365-unified-operations-public#403]
The UI changes (e.g. Ribbon bar color, filtering) are the most noticeable thing in Platform 20. This document should reflect all those changes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f38b490-1c3b-51fd-bcb0-d4fdac44b98f
* Version Independent ID: 3ca286f6-7da8-798f-8fb4-b6ea57357109
* Content: [What's new or changed in Dynamics 365 for Finance and Operations platform update 20 (September 2018) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/whats-new-platform-update-20)
* Content Source: [articles/fin-and-ops/get-started/whats-new-platform-update-20.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/whats-new-platform-update-20.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @tonyafehr
* Microsoft Alias: **tfehr**

**Comment by tonyafehr** [comment]
Thanks for the suggestion! I've reached out to the PM to let him know about your request (bug #252244 has been logged to track this issue).

**Comment by jasongre** [comment]
Good catch, Joel! The updates should be in this article soon.

**Comment by ShylaThompson** [comment]
The updates to the topic should be published by the end of day today. Closing issue.
