### ISSUE TITLE
Where to find the Legal entity of HQUS for subcontracting setup referred on the page

### ISSUE THREAD

**Issue by Navneetkat** [MicrosoftDocs/dynamics-365-unified-operations-public#4031]
[This page describes using a Legal entity of HQUS for subcontracting setup, and i don't find this legal entity in my demo data. Is this a correct legal entity or how can i get the demo setup data in other legal entities?
Thanks ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fcbfaeb-97bd-7fc6-111c-6a18ac95bf3d
* Version Independent ID: 720a7fea-8b61-d9bf-238e-7b15c3065e26
* Content: [Subcontracting - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/production-control/subcontracting?msclkid=eac8afb1c5c411ecb1a8b530ba1d4fa7)
* Content Source: [articles/supply-chain/production-control/subcontracting.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/production-control/subcontracting.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @johanhoffmann
* Microsoft Alias: **johanho**

**Comment by kamaybac** [comment]
@Navneetkat , thank you for contacting us regarding this help topic. I have passed your comment on to the author for consideration. 

I am not completely sure whether the HQUS demo data is still available, but if it is, this topic might help you: [Generate demo data by using data packages](https://docs.microsoft.com/dynamics365/fin-ops-core/dev-itpro/data-entities/generate-demo-data-packages).
