### ISSUE TITLE
Name of feature "Populate financial dimensions to the realized currency adjustment profits/loss accounts for sales tax settlement"

### ISSUE THREAD

**Issue by MrHenrikLevinson** [MicrosoftDocs/dynamics-365-unified-operations-public#4035]
Hi 

The feature named "Enter financial dimensions in the realized currency adjustment profit/loss accounts for sales tax settlement" in the article should be changed to: "Populate financial dimensions to the realized currency adjustment profits/loss accounts for sales tax settlement" to reflect the name in Feature management.

/Henrik

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5670ecf1-f036-383b-bf70-cd097eb1b784
* Version Independent ID: 333dea20-f29e-8245-97e8-9678e4aa9a75
* Content: [Dual currency support for tax - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/general-ledger/dual-currency-for-tax)
* Content Source: [articles/finance/general-ledger/dual-currency-for-tax.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/general-ledger/dual-currency-for-tax.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @ericwang
* Microsoft Alias: **wangchen**

**Comment by kamaybac** [comment]
@MrHenrikLevinson , thank you for reporting this issue. I have forwarded it to the page author for consideration.

**Comment by josaw1** [comment]
@kfend can you please verify?

**Comment by kfend** [comment]
I have updated the article with the correct feature name. Changes should be live later today.
