### ISSUE TITLE
Typo on heading

### ISSUE THREAD

**Issue by g-chap** [MicrosoftDocs/dynamics-365-unified-operations-public#4038]
Small typo on the heading "[Turn Warehouse Management mobile app features or or off in Supply Chain Management](https://docs.microsoft.com/en-us/dynamics365/supply-chain/warehousing/install-configure-warehouse-management-app#turn-warehouse-management-mobile-app-features-or-or-off-in-supply-chain-management)" 

Should be "Turn Warehouse Management mobile app features **on** or off".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc2ac844-c345-707a-b2e9-5d4edf7c8541
* Version Independent ID: ae6e65c3-c1e1-c4cc-e05c-1c2ebd4bafc6
* Content: [Install and connect the Warehouse Management mobile app - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/warehousing/install-configure-warehouse-management-app)
* Content Source: [articles/supply-chain/warehousing/install-configure-warehouse-management-app.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/warehousing/install-configure-warehouse-management-app.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @Mirzaab
* Microsoft Alias: **mirzaab**

**Comment by kamaybac** [comment]
@g-chap , thank you for reporting this issue. I have fixed the topic as suggested. The update should go live later today.
