### ISSUE TITLE
Near real-time change feature (preview vs GA)

### ISSUE THREAD

**Issue by jawn** [MicrosoftDocs/dynamics-365-unified-operations-public#4039]
Is it correct that the Near real time change feature is still in preview? If not, can all docs be updated to reflect this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f6ba603-2306-85f5-9eae-c71523326291
* Version Independent ID: 2f6ba603-2306-85f5-9eae-c71523326291
* Content: [Export to Azure Data Lake overview - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/azure-data-lake-ga-version-overview)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/Azure-Data-Lake-GA-version-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/Azure-Data-Lake-GA-version-overview.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by josaw1** [comment]
Thank you for your feedback. @MilindaV2 can you please confirm?

**Comment by jawn** [comment]
Kind reminder @MilindaV2

**Comment by jawn** [comment]
Turns out this was fixed in [commit](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/commit/1ad9c63de68ca4e3dc85167a7ec022bb1e2885bb)
