### ISSUE TITLE
Location of SCDPBundleInstall.exe

### ISSUE THREAD

**Issue by MZade** [MicrosoftDocs/dynamics-365-unified-operations-public#404]
It seems that the file is moved to [SERVICE_VOLUME]:\AosService\PackagesLocalDirectory\Bin\SCDPBundleInstall.exe
(Ref: PU15)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66b4c899-c7e0-0406-0d39-d32fc41b6104
* Version Independent ID: 5d015069-177d-e33c-094c-257df088a7c0
* Content: [Install metadata hotfixes in development environments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/install-metadata-hotfix-package)
* Content Source: [articles/dev-itpro/migration-upgrade/install-metadata-hotfix-package.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/migration-upgrade/install-metadata-hotfix-package.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RobinARH
* Microsoft Alias: **robadawy**

**Comment by tonyafehr** [comment]
Thanks for the feedback! I will update the topic to reflect that the file is now in the Bin folder. These changes should be live later today.
