### ISSUE TITLE
Exam link is old as exam page says that exam has retired.

### ISSUE THREAD

**Issue by ramanagarwal2005** [MicrosoftDocs/dynamics-365-unified-operations-public#4040]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1bcd2b9-d75a-e8ba-eebc-a9a397930e97
* Version Independent ID: 44135730-6a5f-9c84-70ab-4c6b5c7a34aa
* Content: [Learning catalog for users of Dynamics 365 Finance - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/get-started/learning-catalog-business-user)
* Content Source: [articles/finance/get-started/learning-catalog-business-user.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/get-started/learning-catalog-business-user.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @MargoC
* Microsoft Alias: **margoc**

**Comment by josaw1** [comment]
Thank you for your feedback. @twheeloc can you please update or remove link?

**Comment by twheeloc** [comment]
Thank you for the feedback, the exam link has been updated.
