### ISSUE TITLE
Clarify, which user is the "batch user"

### ISSUE THREAD

**Issue by torbennehmer** [MicrosoftDocs/dynamics-365-unified-operations-public#4041]
In the section "Exchange mail provider" the following is statet:

> When used as the Batch email provider, the batch account will be used.

It is unclear, which account is meant here, searches for batch account did not yield anything helpful. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e46e3d2a-37fb-9961-84fe-0be6d9f0235b
* Version Independent ID: c4a46858-a79b-08b4-d81c-941490d42da3
* Content: [Configure and send email - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/organization-administration/configure-email#verify-all-email-accounts-have-appropriate-send-as-permissions)
* Content Source: [articles/fin-ops-core/fin-ops/organization-administration/configure-email.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/organization-administration/configure-email.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by josaw1** [comment]
Thank you for your comment. @jasongre can you please review?

**Comment by josaw1** [comment]
Closed as won't fix.
