### ISSUE TITLE
Please update the documentation for cloud hosted environments

### ISSUE THREAD

**Issue by v-yoyord** [MicrosoftDocs/dynamics-365-unified-operations-public#4042]
[Enabling BusinessEvents endpoint in cloud hosted environment was failing with below error:

Azure Service Bus TopicResponse status code does not indicate success: 400 ({"error":"invalid_client","error_description":"AOS environment 45062e0a-6aa0-4c1e-aaba-1d1cac5f5d95 does not exist."}).

The issue was solved by running the following script to add a flight to the AXDB:
ICM #312927239
 
DECLARE @flightName NVARCHAR(100) = 'BusinessEventsCDSIntegration_KillSwitch';
IF NOT EXISTS (SELECT TOP 11FROM SysFlighting WHERE flightName = @flightName)
INSERTINTO SYSFLIGHTING(FLIGHTNAME,ENABLED, FLIGHTSERVICEID,PARTITION)
SELECT @flightName, 1, 12719367,RECID FROM DBO.[PARTITIONS];
ELSE
UPDATE SysFlighting SET enabled = 1, flightServiceId = 12719367WHERE flightName = @flightName;]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0cd4aef-33f1-d647-85eb-1a055ef216bd
* Version Independent ID: 73febada-4141-88bf-7a55-e8cc375dde92
* Content: [Business events overview - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/business-events/home-page)
* Content Source: [articles/fin-ops-core/dev-itpro/business-events/home-page.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/business-events/home-page.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by jaredha** [comment]
The suggested SQL script turns off the Power Platform Integration for business events by enabling the "BusinessEventsCDSIntegration_KillSwitch" flight for the environment. This isn't our typical recommendation for resolving errors with the Power Platform Integration, and shouldn't be included in documentation.
