### ISSUE TITLE
Issue with uploading CSV

### ISSUE THREAD

**Issue by Anders-Dahlin** [MicrosoftDocs/dynamics-365-unified-operations-public#4043]
Set-TeamTargetingHierarchy is not part of the latest power shell module so CSV cannot be uploaded. No needed action is described on Doc links. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7e3862f-3f71-a079-5924-c8722b3ddd4d
* Version Independent ID: 202de913-76cf-5459-436a-3afec7b3a74a
* Content: [Provision Microsoft Teams from Dynamics 365 Commerce - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/provision-teams-from-commerce)
* Content Source: [articles/commerce/provision-teams-from-commerce.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/provision-teams-from-commerce.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @gvrmohanreddy
* Microsoft Alias: **gmohanv**

**Comment by sericks007** [comment]
@Anders-Dahlin, thank you for providing this feedback.

@gvrmohanreddy, please review and update the content, as needed.

**Comment by sericks007** [comment]
Bug 701117 has been logged to address this issue.
