### ISSUE TITLE
what happened with disable/enable page locks?

### ISSUE THREAD

**Issue by gertvdh** [MicrosoftDocs/dynamics-365-unified-operations-public#4045]
in the list of removed actions, the action to disable/enable page locks and lock escalation is not mentioned? Is this replaced with something else or automated process or just removed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b75b1a49-8365-0fc4-5c27-677ff4b26325
* Version Independent ID: 98fcce36-1717-a210-0bb6-5c7f48bdf36f
* Content: [Query cookbook - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/querycookbook)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/querycookbook.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/lifecycle-services/querycookbook.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @meeramahabala
* Microsoft Alias: **meeram**

**Comment by sericks007** [comment]
@gertvdh, thank you for providing this feedback. I've sent this on to a program manager for a response.

**Comment by sericks007** [comment]
@gertvdh, according to the PM:

The reason that customers do not need to do anything on page locks is that the platform is responsible for:
- Optimizing the database's workload and handling any blocking that may occur.
- Managing intermittent connectivity issues and providing retries to avoid any concerns with such actions.
- Internal monitoring and detection is done.
