### ISSUE TITLE
Promoting deprecated logic

### ISSUE THREAD

**Issue by jimwillsher** [MicrosoftDocs/dynamics-365-unified-operations-public#4046]
[Enter feedback here]
Hello, please can you advise why this page is still heavily promoting the use of XSLT to manipulate the MT940 files, when XSLT scripting is being deprecated by Microsoft in September?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f6257c7-8c1f-f00a-4f51-2f8f20f1f09e
* Version Independent ID: c793b57d-f984-bb4d-d014-e2bf2da43f68
* Content: [Set up the advanced bank reconciliation import process - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/cash-bank-management/set-up-advanced-bank-reconciliation-import-process)
* Content Source: [articles/finance/cash-bank-management/set-up-advanced-bank-reconciliation-import-process.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/cash-bank-management/set-up-advanced-bank-reconciliation-import-process.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @panolte
* Microsoft Alias: **panolte**

**Comment by panolte** [comment]
Hi Sally,

All the cash and bank topics should be assigned to Angela Ding (angelad116).

Could you reassign this to her?

Thanks
Pat
