### ISSUE TITLE
10.0.26 has wrong build number

### ISSUE THREAD

**Issue by dynamics365musings** [MicrosoftDocs/dynamics-365-unified-operations-public#4047]
The 'Build number' next to version 10.0.26 reads '10.0.119'.
I think this is missing a '2'.

If you look at this page:
https://docs.microsoft.com/en-us/dynamics365/finance/get-started/whats-new-home-page

The build number associated with 10.0.26 is 10.0.1192.

Hope that helps.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5914677-9720-ad39-babc-d2a0528dea4c
* Version Independent ID: b3d9070e-b760-27ee-9b22-9da78815cc82
* Content: [What's new or changed in Dynamics 365 Commerce - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/get-started/whats-new-home-page)
* Content Source: [articles/commerce/get-started/whats-new-home-page.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/get-started/whats-new-home-page.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by sericks007** [comment]
@dynamics365musings, thanks for letting us know! I've made the correction, and it will be published soon.
