### ISSUE TITLE
Uninstall failed

### ISSUE THREAD

**Issue by Anders-Dahlin** [MicrosoftDocs/dynamics-365-unified-operations-public#4048]
Hi,

When following uninstall procedure in the documentation I get an error that the last solution cannot be deleted because of a fallback form.
Dynamics 365 FNO SCM Inventory Visibility Base Solution

Thanks
Br
Anders

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bddc6757-997f-f662-f4df-950fca150102
* Version Independent ID: 618ddfab-e488-e69b-bf3a-ddee12471c8f
* Content: [Install the Inventory Visibility Add-in - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/inventory/inventory-visibility-setup)
* Content Source: [articles/supply-chain/inventory/inventory-visibility-setup.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/inventory/inventory-visibility-setup.md)
* Service: **dynamics-365-supply-chain**
* GitHub Login: @yufeihuang
* Microsoft Alias: **yufeihuang**

**Comment by sericks007** [comment]
@Anders-Dahlin, thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
