### ISSUE TITLE
Add a client secret should be for the client not for the server

### ISSUE THREAD

**Issue by jmeijering** [MicrosoftDocs/dynamics-365-unified-operations-public#4049]
In this document you mentioned:

The client secret is also known as an application password. It's a string value that your app can use instead of a certificate to identity itself.

In the Azure portal, in App registrations, select your application (App registered for the Retail server).
Select Certificates & secrets > New client secret.
Add a description for your client secret.
Select a duration.
Select Add.
Be sure to record the secret's value so that you can use it in your client application code.

The phrase App registered for the Retail server should be App registered for the Retail client.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2aaab0fa-b1ac-51c0-2329-73ab077477b2
* Version Independent ID: dc8cf3fc-4c9f-731c-a99e-d70b8b940428
* Content: [Consume Retail Server APIs in external applications - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/consume-retail-server-api#register-the-application-in-azure-app-registration)
* Content Source: [articles/commerce/dev-itpro/consume-retail-server-api.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/consume-retail-server-api.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by johnmichalak** [comment]
@jmeijering Thank you for the feedback.

@mugunthanm Can you please take a look at the suggestion and make any appropriate changes?
