### ISSUE TITLE
ACS

### ISSUE THREAD

**Issue by OksanaKovaliova** [MicrosoftDocs/dynamics-365-unified-operations-public#405]
Currently, Access Control Service (ACS) doesn't support a mechanism for non-interactive authentication - is it still valid point?
We can use Azure app registration with secret key to create Apps that can access D365 without entering user credentials - cannot we? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44045a16-e5bc-365a-45a3-5ddbc61f018b
* Version Independent ID: 85872ae7-e67e-6932-aaca-b9bcf9df3a86
* Content: [Application stack and server architecture - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-tools/application-stack-server-architecture)
* Content Source: [articles/dev-itpro/dev-tools/application-stack-server-architecture.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-tools/application-stack-server-architecture.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @kfend
* Microsoft Alias: **meeram**

**Comment by tonyafehr** [comment]
Thanks for the suggestion! I've reached out to the PM to let her know about your request (bug #252249 has been logged to track this issue).
