### ISSUE TITLE
Need more info on Subscribe Module for D365 Commerce

### ISSUE THREAD

**Issue by AnandDixit2011** [MicrosoftDocs/dynamics-365-unified-operations-public#4050]
The MS Docs page for Subscribe Module in D365 Commerce deals with how to add the module to a specific page on the webstore.
However, it does not address what needs to be done once the module is visible to end users. 
- If a user enters their email ID and clicks on 'Sign Me Up' button, what is the expected behaviour?
- Where can the merchant's team see the list of all users who have shared their email IDs and signed up / subscribed for newsletters?
- are there any specific distribution schedules that need to run?
Such details would be helpful in all pages, wherever needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4eac9bec-1eac-bdaa-20dc-1596983dc958
* Version Independent ID: f3362e79-78f6-6bf7-7a22-4f3a92ded94d
* Content: [Subscribe module - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/subscribe-module)
* Content Source: [articles/commerce/subscribe-module.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/subscribe-module.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @anupamar-ms
* Microsoft Alias: **anupamar**

**Comment by johnmichalak** [comment]
@AnandDixit2011 Thank you for the feedback.

@anupamar-ms Can you please take a look at the questions and review the topic to see if any changes can be made to assist.

**Comment by anupamar-ms** [comment]
Hi there, as called out in the documentation, you need to extend this module and add the necessary business logic to capture the email and process it. The module itself does not provide any out-of-box integration to capture and process this information.

"The subscribe module requires a data action extension to work with some marketing email providers, so that newsletter or promotional emails can be sent after customer information is captured."

**Comment by AnandDixit2011** [comment]
Thanks Anupama.

So there's no default mechanism in D365 Commerce that just captures and
saves the email addresses collected through the subscribe module? If a user
just wishes to view a list of who has subscribed, it is not possible?

Warm regards,

Anand
