### ISSUE TITLE
Import and export processes - Wrong Azure File Upload http status code

### ISSUE THREAD

**Issue by primeitbr** [MicrosoftDocs/dynamics-365-unified-operations-public#4051]
The "Uploads File to Blob Storage" http return code in case of Success is 201, not 200 ;)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d963d4c-de1f-7730-bee2-016dcde40907
* Version Independent ID: 21b95d43-5ad9-0ffc-21b9-6a4ba9086a56
* Content: [Data management package REST API - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/data-management-api)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/data-management-api.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/data-management-api.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Peakerbl
* Microsoft Alias: **peakerbl**

**Comment by johnmichalak** [comment]
@primeitbr Thank you for letting us know.

@Peakerbl can you please review this suggestion and updated the content if required?

**Comment by josaw1** [comment]
Closed as won't fix.
