### ISSUE TITLE
No field for switching IBAN/SWIFT requirement on AP parameters when feature enabled

### ISSUE THREAD

**Issue by jmaden** [MicrosoftDocs/dynamics-365-unified-operations-public#4052]
I have enabled the feature but I cannot turn off the IBAN/SWIFT requirement for non-US legal entities because the relevant option is not appearing in AP parameters

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 925689eb-7471-5cc7-cc5c-f51225ba1764
* Version Independent ID: 41d9cd03-4580-52e6-5ee4-391ab52c8975
* Content: [Maintain vendor bank account information - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/accounts-payable/maintain-vendor-bank-info)
* Content Source: [articles/finance/accounts-payable/maintain-vendor-bank-info.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/accounts-payable/maintain-vendor-bank-info.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @v-kiarnd
* Microsoft Alias: **brpotter**

**Comment by johnmichalak** [comment]
@jmaden Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
