### ISSUE TITLE
Wrong path mentioned in the article

### ISSUE THREAD

**Issue by MaheshReddy19** [MicrosoftDocs/dynamics-365-unified-operations-public#4053]
Path for email templates should be from Organization administration not as mentioned in organization templates 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ef943c1-f092-fcd4-45d3-ef124979252a
* Version Independent ID: 562b85fc-b76a-732a-ecd5-c586e9ad8d10
* Content: [Create email templates for transactional events - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/email-templates-transactions#create-an-email-template)
* Content Source: [articles/commerce/email-templates-transactions.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/email-templates-transactions.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @bicyclingfool
* Microsoft Alias: **stuharg**

**Comment by johnmichalak** [comment]
@MaheshReddy19 Thank you for the feedback!

@bicyclingfool Can you please review and update the topic as appropriate?

**Comment by josaw1** [comment]
Fixed.
