### ISSUE TITLE
How does this option actually work?

### ISSUE THREAD

**Issue by mrsalonen** [MicrosoftDocs/dynamics-365-unified-operations-public#4055]
The page tells that an option exists, but pretty much nothing else. I'm interested in knowing how it works, code-wise, if it can  be extended etc. Where does the invoice id editing happen in the code - metadata search doesn't turn up anything relating to the parameters found in the Accounts receivable parameters page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2fbd082-e871-da6d-f568-d6c834e6be34
* Version Independent ID: afaefd1c-bb43-89ff-9f33-4a4e8a991df1
* Content: [Edit invoice IDs on sales orders for Eastern Europe - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/emea-edit-invoice-id-sales-orders)
* Content Source: [articles/finance/localizations/emea-edit-invoice-id-sales-orders.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/emea-edit-invoice-id-sales-orders.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @ShylaThompson
* Microsoft Alias: **kfend**

**Comment by johnmichalak** [comment]
@mrsalonen  Thanks for posting this! In the meantime, to get product help you can contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community. 

@ShylaThompson Please review the suggestion and update the article as appropriate.

**Comment by josaw1** [comment]
Closed as won't fix.
