### ISSUE TITLE
Please update

### ISSUE THREAD

**Issue by rat-af** [MicrosoftDocs/dynamics-365-unified-operations-public#4056]
When will the SQL in this be updated???  How long do we have to wait for updates to the SQL?  This is clearly taking far too long.  When I use this, I get errors on Roles and errors on the Retail.

Can you please update the SQL.

Current errors with the script are:

Msg 15151, Level 16, State 1, Line 1
Cannot alter the role 'DataSyncUsersRole', because it does not exist or you do not have permission.
Msg 15151, Level 16, State 1, Line 1
Cannot alter the role 'UsersRole', because it does not exist or you do not have permission.
Msg 15151, Level 16, State 1, Line 1
Cannot alter the role 'ReportUsersRole', because it does not exist or you do not have permission.
Msg 15151, Level 16, State 1, Line 1
Cannot alter the role 'DeployExtensibilityRole', because it does not exist or you do not have permission.

(0 rows affected)
Msg 515, Level 16, State 2, Line 69
Cannot insert the value NULL into column 'DATAGROUP', table 'FromProd_20220622.dbo.RETAILCONNDATABASEPROFILE'; column does not allow nulls. INSERT fails.
The statement has been terminated.

(0 rows affected)

(0 rows affected)

Completion time: 2022-06-22T03:24:54.2446629+00:00

These errors have been around for quite sometime and it's about time that the scripts are updated so that these errors are mitigated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c5e8701-e1d4-25f8-d76a-ee7870b915e1
* Version Independent ID: 624211c7-2eb4-7154-d38f-236dc6f8f7a9
* Content: [Export a copy of the standard user acceptance testing (UAT) database - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/dbmovement-scenario-exportuat)
* Content Source: [articles/fin-ops-core/dev-itpro/database/dbmovement-scenario-exportuat.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/database/dbmovement-scenario-exportuat.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by kfend** [comment]
@rat-af - Thank you for the feedback.
@laneswenka - Can you please take a look at this and update the topic?

**Comment by josaw1** [comment]
Fixed.
