### ISSUE TITLE
wasn't the build number supposed to be 10.0.1264 ?

### ISSUE THREAD

**Issue by dogan-adiyaman** [MicrosoftDocs/dynamics-365-unified-operations-public#4057]
Hi,

I think the build number for the page is wrong and it is supposed to be 10.0.1264, not  10.0.1227.
--

</body>

</html>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ad712ca-a6bc-50f1-ce2a-90873b4c50dc
* Version Independent ID: 7ad712ca-a6bc-50f1-ce2a-90873b4c50dc
* Content: [What's new or changed in Dynamics 365 Commerce 10.0.28 (July 2022) - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/get-started/whats-new-commerce-10-0-28)
* Content Source: [articles/commerce/get-started/whats-new-commerce-10-0-28.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/get-started/whats-new-commerce-10-0-28.md)
* Service: **dynamics-365-commerce**
* Technology: ****
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by kfend** [comment]
@dogan-adiyaman - Thank you for the feedback. I have updated the topic and the changes will show later today.
