### ISSUE TITLE
CAAP Nomination Site

### ISSUE THREAD

**Issue by nicklakasas** [MicrosoftDocs/dynamics-365-unified-operations-public#406]
Hi there,
The CAAP nomination site link redirects to https://experience.dynamics.com/ with no instructions from there. Can more instructions be added or if it's a broken link, be fixed please?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1892de7-0902-054b-e430-8e23f714477b
* Version Independent ID: 20e0ff84-5f29-f5e3-ddde-288e52059ad0
* Content: [Standard and targeted platform releases - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/public-preview-releases)
* Content Source: [articles/fin-and-ops/get-started/public-preview-releases.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/public-preview-releases.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @kfend
* Microsoft Alias: **kfend**

**Comment by sericks007** [comment]
This topic has been updated and there is no longer a CAAP nomination site link -- so closing this issue.
