### ISSUE TITLE
Please confirm responsibility for Sandbox environments as its unclear from the text

### ISSUE THREAD

**Issue by andypicking** [MicrosoftDocs/dynamics-365-unified-operations-public#4060]
This page states - For a managed cloud service such as Finance and Operations, Microsoft is responsible for actively monitoring the health of production environments at all times.... However, you're responsible for proactively or reactively monitoring and troubleshooting the health of non-production environments.

For managed cloud service sandboxes (i.e. Tier 2 environment(s)) these aren't as accessible to either partner or customer in the same way as Tier 1 non production environments, and yet the Tier 2 environment is hosted by Microsoft. Its reasonable to expect that Microsoft is monitoring the environments that are managed, but the wording suggests that it is **only** production and not the other provided (as part of the D365FO subscription) UAT/non production sandbox - can the wording be changed to clarify this - whichever way round it is please ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64b5b03d-9169-f94e-f999-63bc5a8e68ac
* Version Independent ID: 177eb187-6962-ba30-7a63-86b0bf3452d7
* Content: [Monitoring and diagnostics tools in Lifecycle Services (LCS) - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/monitoring-diagnostics)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/monitoring-diagnostics.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/lifecycle-services/monitoring-diagnostics.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @AngelMarshall
* Microsoft Alias: **tsmarsha**

**Comment by josaw1** [comment]
Fixed.
