### ISSUE TITLE
Docs needs updating to match current state of D365 Commerce 

### ISSUE THREAD

**Issue by bstorie** [MicrosoftDocs/dynamics-365-unified-operations-public#4064]
Under the Checklist section of this Doc, steps 12 and 13 say to check RTS setup.    These steps only apply to 2012 N-1 as RTS setup is all hidden/automated with the Deployment of HQ now.      Additionally, this doc should be reviewed to ensure it links/fits in with our other documents about POS activation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfe62687-b97a-369a-8b3f-80c712a5aca3
* Version Independent ID: bfc751c1-3f68-be7d-04e8-99c5575fdec9
* Content: [Point of sale (POS) device activation - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/retail-device-activation#checklist-to-follow-before-activation)
* Content Source: [articles/commerce/dev-itpro/retail-device-activation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/retail-device-activation.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @athinesh99
* Microsoft Alias: **athinesh**

**Comment by kfend** [comment]
@bstorie - Thank you for the feedback.
@athinesh99 - Can you please take a look at this and update the topic as necessary? Thanks!

**Comment by josaw1** [comment]
@bicyclingfool can you please review this feedback?

**Comment by josaw1** [comment]
Fixed.
