### ISSUE TITLE
Add information about IAM Access Role needed for KeyVault VM

### ISSUE THREAD

**Issue by Pistoler00z** [MicrosoftDocs/dynamics-365-unified-operations-public#4065]
In the documentation, we have no information about IAM Access role that we must add to our KeyVault Ressource else if we received following error.
error": {
            "code": "AuthorizationFailed",
            "message": "The client 'XXXX' with object id 'XXXX' does not have authorization to perform action 'Microsoft.EventGrid/eventSubscriptions/write' over scope '/subscriptions/XXX/resourceGroups/XXX_Dynamics/providers/Microsoft.Web/sites/D365FO-EventGrid-ESB-Product/providers/Microsoft.EventGrid/eventSubscriptions/XXX' or the scope is invalid. If access was recently granted, please refresh your credentials."
        }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 055168f2-4423-1246-9663-1d0b14696666
* Version Independent ID: 2ec22b82-5bc0-bdb1-b630-ffcbaf1180dd
* Content: [Business events and Azure Event Grid - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/business-events/how-to/how-to-eventgrid)
* Content Source: [articles/fin-ops-core/dev-itpro/business-events/how-to/how-to-eventgrid.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/business-events/how-to/how-to-eventgrid.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by Sunil-Garg** [comment]
@Jared ***@***.***>
________________________________
From: Pistoler00z ***@***.***>
Sent: Tuesday, July 5, 2022 12:44:58 AM
To: MicrosoftDocs/dynamics-365-unified-operations-public ***@***.***>
Cc: Sunil Garg ***@***.***>; Mention ***@***.***>
Subject: [MicrosoftDocs/dynamics-365-unified-operations-public] Add information about IAM Access Role needed for KeyVault VM (Issue #4065)


In the documentation, we have no information about IAM Access role that we must add to our KeyVault Ressource else if we received following error.
error": {
"code": "AuthorizationFailed",
"message": "The client 'XXXX' with object id 'XXXX' does not have authorization to perform action 'Microsoft.EventGrid/eventSubscriptions/write' over scope '/subscriptions/XXX/resourceGroups/XXX_Dynamics/providers/Microsoft.Web/sites/D365FO-EventGrid-ESB-Product/providers/Microsoft.EventGrid/eventSubscriptions/XXX' or the scope is invalid. If access was recently granted, please refresh your credentials."
}

________________________________
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

  *   ID: 055168f2-4423-1246-9663-1d0b14696666
  *   Version Independent ID: 2ec22b82-5bc0-bdb1-b630-ffcbaf1180dd
  *   Content: Business events and Azure Event Grid - Finance & Operations | Dynamics 365<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fdynamics365%2Ffin-ops-core%2Fdev-itpro%2Fbusiness-events%2Fhow-to%2Fhow-to-eventgrid&data=05%7C01%7Csunilg%40microsoft.com%7Ccc73ee46e5bc40c9582d08da5e5a42b5%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637926039009730298%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=d7whqclHCrAPYpgvUJny25Yg8JVf6%2FPbFUWGKDUI3kM%3D&reserved=0>
  *   Content Source: articles/fin-ops-core/dev-itpro/business-events/how-to/how-to-eventgrid.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FDynamics-365-Unified-Operations-Public%2Fblob%2Fmain%2Farticles%2Ffin-ops-core%2Fdev-itpro%2Fbusiness-events%2Fhow-to%2Fhow-to-eventgrid.md&data=05%7C01%7Csunilg%40microsoft.com%7Ccc73ee46e5bc40c9582d08da5e5a42b5%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637926039009730298%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JUmbg3NTtmpVlgQ4h5vG3By1ouQGF0G2c%2FHnNux3bqI%3D&reserved=0>
  *   Service: dynamics-365-cross-app
  *   Product: ****
  *   Technology: ****
  *   GitHub Login: @Sunil-Garg<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSunil-Garg&data=05%7C01%7Csunilg%40microsoft.com%7Ccc73ee46e5bc40c9582d08da5e5a42b5%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637926039009730298%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2FxOsqFByB4%2FK%2FTvA0O1ClBUX%2FjmKUZ%2BL4Pmc%2FDkzBgo%3D&reserved=0>
  *   Microsoft Alias: sunilg

**Comment by Pistoler00z** [comment]
Hi Jared,

To resolve this error, we had to add a azure role to our KeyVault ressource, access policies was not enough.
![image](https://user-images.githubusercontent.com/108720725/177485573-afb054ae-4a7c-459d-9f3b-481f6cf075fb.png)
