### ISSUE TITLE
Scalability recommendations exacerbate consistency issues due to D365 design limitations

### ISSUE THREAD

**Issue by DawMatt** [MicrosoftDocs/dynamics-365-unified-operations-public#4066]
Hi,

I've recently been advised by Microsoft support/product engineering that there is a long standing design limitation impacting OData queries. If multiple AOS are in use then if any entity being returned by an OData call has caching enabled, it can take a minute before all of the AOS are consistent and will return the same results. We've encountered issues where business events are published by D365 FinOps but stale data is returned when we use OData to query the remaining details of the entity.

The only "solution" (really a workaround) offered for this is to wait for 1 minute before processing the business event that was published. 

Apparently a documentation bug/deliverable (#703177) has been created for this.

The feedback specific to this page: the tips for improving scalability (switching off AOS affinity, increasing parallelism, etc) will all stress this design limitation even more. This page should be updated to make people aware they need to consider whether their entities are cached and if so use the appropriate mechanism to address scalability without creating eventual consistency issues.

Thanks, Matt

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0320c7c8-e4d9-d62c-625f-371f860cd267
* Version Independent ID: 0320c7c8-e4d9-d62c-625f-371f860cd267
* Content: [Maximize API throughput - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/service-protection-maximizing-api-throughput)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/service-protection-maximizing-api-throughput.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/service-protection-maximizing-api-throughput.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @jaredha
* Microsoft Alias: **jaredha**

**Comment by josaw1** [comment]
Thank you for your feedback. Closing as won't fix at this time.
