### ISSUE TITLE
The web application not compatible with Macbook

### ISSUE THREAD

**Issue by Shimara-G** [MicrosoftDocs/dynamics-365-unified-operations-public#4067]
[The page states that the web application can run in Apple Safari (latest publicly available version) web browser but it cannot run on a  macos] and Windows 7 and older when Onboarding a Vendor in D365 FO
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 043a7336-3d71-14f2-9856-05e03e24cd80
* Version Independent ID: 60414540-f243-27e6-0494-28c4af78e0a4
* Content: [System requirements for cloud deployments of Dynamics 365 Commerce - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/get-started/system-requirements)
* Content Source: [articles/commerce/get-started/system-requirements.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/get-started/system-requirements.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @jashanno
* Microsoft Alias: **jashanno**

**Comment by twheeloc** [comment]
@Shimara-G, thank you for the feedback.
@jashanno - please review the feedback and update the content as needed.
