### ISSUE TITLE
Can't see the RDP access link

### ISSUE THREAD

**Issue by sbaber82** [MicrosoftDocs/dynamics-365-unified-operations-public#4068]
I requested the access on Sandbox environment details page, but no link appears to download the RDP file. I can only see the SQLserver\Database name with User name and Password. The docs site says to RDP to the machine and then open SQL server management studio. I am looking to access the entity store database.

Please advise, if I am missing anything.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da145b17-ccd8-7bf7-7495-0ddb1bf5829f
* Version Independent ID: 2a24d715-ecac-1c65-d2d4-8d14b55b8765
* Content: [Power BI integration with Entity store - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/power-bi-integration-entity-store)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/power-bi-integration-entity-store.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/analytics/power-bi-integration-entity-store.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by joengelhart** [comment]
You can't rdp to a tier 2 or above, only SQL access.
