### ISSUE TITLE
Deprecated XSLT Functionality & Advanced Bank Reconciliation

### ISSUE THREAD

**Issue by tbarron2** [MicrosoftDocs/dynamics-365-unified-operations-public#4069]
What is the plan for Advanced Bank Reconciliation now that XSLT transforms are no long supported after version 30? Would this require customization? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f6257c7-8c1f-f00a-4f51-2f8f20f1f09e
* Version Independent ID: c793b57d-f984-bb4d-d014-e2bf2da43f68
* Content: [Set up the advanced bank reconciliation import process - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/cash-bank-management/set-up-advanced-bank-reconciliation-import-process)
* Content Source: [articles/finance/cash-bank-management/set-up-advanced-bank-reconciliation-import-process.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/cash-bank-management/set-up-advanced-bank-reconciliation-import-process.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @panolte
* Microsoft Alias: **panolte**

**Comment by twheeloc** [comment]
@tbarron2, thank you for your feedback. You can check out [Set up advanced bank reconciliation import using Electronic reporting](https://docs.microsoft.com/en-us/dynamics365/finance/accounts-payable/import-bai2-er).
