### ISSUE TITLE
KB Article

### ISSUE THREAD

**Issue by JoelLeichty** [MicrosoftDocs/dynamics-365-unified-operations-public#407]
It's not clear if the LCS KB article referenced in this article also covers Platforms 16-20, or only Platform 20.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f38b490-1c3b-51fd-bcb0-d4fdac44b98f
* Version Independent ID: 3ca286f6-7da8-798f-8fb4-b6ea57357109
* Content: [What's new or changed in Dynamics 365 for Finance and Operations platform update 20 (September 2018) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/whats-new-platform-update-20)
* Content Source: [articles/fin-and-ops/get-started/whats-new-platform-update-20.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/whats-new-platform-update-20.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @tonyafehr
* Microsoft Alias: **tfehr**

**Comment by tonyafehr** [comment]
The link to the LCS KB article covers only Platform update 20.

**Comment by JoelLeichty** [comment]
Can we get links to all the KB articles that cover platforms 16-20 in this article? Most users will be going from Platform 15 to 20.

**Comment by tonyafehr** [comment]
I'm adding KB article links to each platform update listed in this topic. The updates will be published on Wednesday.
