### ISSUE TITLE
Please add sample code using MSAL not ADAL

### ISSUE THREAD

**Issue by DKobayashi-ykgw** [MicrosoftDocs/dynamics-365-unified-operations-public#4072]
Please add sample code using MSAL not ADAL.
Because of ADAL will EoS in Dec. 2022, please add code based MSAL.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 133cc363-a550-5cbf-622a-f0bd3da87eb6
* Version Independent ID: a7b1ce5d-ba20-b723-e3b0-23a9b79cde9d
* Content: [Service endpoints overview - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/services-home-page#client-sample-code)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/services-home-page.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/services-home-page.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Peakerbl
* Microsoft Alias: **peakerbl**

**Comment by josaw1** [comment]
Thank you for your feedback. @Peakerbl can you please review?

**Comment by josaw1** [comment]
Closed as won't fix.
