### ISSUE TITLE
Hi, Some more information should be added on how CODA process information.   For example on customer side, MS supports only structure message starting by 101 and 102. this can change but should be mentioned somewhere for customer

### ISSUE THREAD

**Issue by anboudin** [MicrosoftDocs/dynamics-365-unified-operations-public#4073]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 807f96bd-9269-1541-0516-ee905e0003d7
* Version Independent ID: a263d611-d029-927b-16b6-a9e2a23000db
* Content: [CODA bank statement - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/emea-bel-coda-bank-statement-import)
* Content Source: [articles/finance/localizations/emea-bel-coda-bank-statement-import.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/emea-bel-coda-bank-statement-import.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @Anasyash
* Microsoft Alias: **anasyash**

**Comment by josaw1** [comment]
Thank you for your feedback. @anasyash can you please review?

**Comment by josaw1** [comment]
Closed as won't fix.
