### ISSUE TITLE
Block Formula approval removal and editing

### ISSUE THREAD

**Issue by gmazzetto** [MicrosoftDocs/dynamics-365-unified-operations-public#4074]
The functionalities of blocking editing and approval removal applies only to routes in the production control parameters as mentioned in the document.
For Formulas and BOMs the parameters are placed in the inventory and warehouse management parameters instead.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 035fd941-6a25-ec06-0da5-bb99aef21ec0
* Version Independent ID: b3578b59-0b39-befa-4c0e-37551e415a41
* Content: [Formulas and formula versions - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/production-control/formulas-versions)
* Content Source: [articles/supply-chain/production-control/formulas-versions.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/production-control/formulas-versions.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @johanhoffmann
* Microsoft Alias: **johanho**

**Comment by josaw1** [comment]
Thank you for your feedback. @kamaybac can you please assign to the correct author?

**Comment by josaw1** [comment]
Closed as won't fix.
