### ISSUE TITLE
Dead link to customersource document

### ISSUE THREAD

**Issue by mpburtt** [MicrosoftDocs/dynamics-365-unified-operations-public#4078]
The link on the page "[Microsoft Dynamics Localization Portal: Australia report (requires CustomerSource account)](https://mbs.microsoft.com/files/customer/AX/Support/supportnews/Australia.html)" is an invalid/dead URL.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 111bada3-a333-b517-5907-28f7b9436da4
* Version Independent ID: 0b322b8d-a9bb-98d4-fbc9-e706de3f8a5f
* Content: [Australia overview - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/australia)
* Content Source: [articles/finance/localizations/australia.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/australia.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **roschlom**

**Comment by sericks007** [comment]
Bug 725470 has been assigned to track this bug.  @kfend, please resolve this issue/bug, or assign to the appropriate PM.

**Comment by kfend** [comment]
I have removed the broken link.
