### ISSUE TITLE
Base64-encoded X.509 not working

### ISSUE THREAD

**Issue by Rain-Runner** [MicrosoftDocs/dynamics-365-unified-operations-public#408]
We try sign our solution with exported public part of certificate in Base64-encoded X.509, but this not working. Only Binary X.509 works as expected. Please check it and edit manual, if you find it relevant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce6f5dff-10da-6b04-bd4d-af056f772acc
* Version Independent ID: 075f0d3a-de0e-a434-c645-bc7c4689e930
* Content: [Independent software vendor (ISV) licensing - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-tools/isv-licensing)
* Content Source: [articles/dev-itpro/dev-tools/isv-licensing.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-tools/isv-licensing.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @robadawy
* Microsoft Alias: **robadawy**

**Comment by tonyafehr** [comment]
Thanks for the feedback. We're investigating this.

**Comment by AndrewJonesA1X** [comment]
Hi I'm getting an issue with the Microsoft.Dynamics.AX.Deployment.Setup.exe --setupmode importlicensefile step, when trying to get ISV licensing working on a onebox development environment. It gives the following error:

Infolog diagnostic message: 'The certificate associated with license XXX Licence is not a trusted certificate.' on category 'Error'.

It's a DigiCert certificate that has a certificate status "This certificate is OK" when imported to the development box.

Any ideas?

**Comment by AndrewJonesA1X** [comment]
Sorry that should have been a new entry not a reply!

**Comment by Rain-Runner** [comment]
Hi Andrew,

this was exact our issue. Try to export .cer from your signing .pfx as Binary X.509. This solve our issue and signing ends correct as expected.

Marek
