### ISSUE TITLE
Visuals would improve the doc and consumption of feature greatly

### ISSUE THREAD

**Issue by Ciosull** [MicrosoftDocs/dynamics-365-unified-operations-public#4080]
This page could be a lot more valuable and entice end users more if it had visuals highlighting the capability, as I have seen in the XR

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75388071-94ef-d7e9-cbc1-a910621ef20e
* Version Independent ID: 6be15ff3-b119-2be7-535d-b0caa7072b5b
* Content: [Grid capabilities - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/grid-capabilities)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/grid-capabilities.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/grid-capabilities.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by sericks007** [comment]
@Ciosull, thank you for providing this feedback.  I'll send this on to our documentation leaders for consideration.  At this time, we don't include screen shots unless they are critical for understanding, as screen shots easily get out-dated and require maintenance.

**Comment by sericks007** [comment]
@Ciosull, I talked with the author and he will add some images!

@jasongre, please add images, as we discussed.

**Comment by sericks007** [comment]
Bug 725471 has been logged to track this issue.

**Comment by sericks007** [comment]
This content has been updated.
