### ISSUE TITLE
Hi, we should provide more information on this page on 

### ISSUE THREAD

**Issue by anboudin** [MicrosoftDocs/dynamics-365-unified-operations-public#4081]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63edf6c2-6935-7df1-3efe-c7f3566a7753
* Version Independent ID: 4d6bd056-8c7a-5b10-109d-7dda67dfdd3f
* Content: [Structure of Dynamics 365 Finance data sources for the FEC - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/emea-fra-fec-audit-file-structure#fec-detailed-datasources)
* Content Source: [articles/finance/localizations/emea-fra-fec-audit-file-structure.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/emea-fra-fec-audit-file-structure.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @liza-golub
* Microsoft Alias: **elgolu**

**Comment by sericks007** [comment]
@kfend, please re-assign issue, as necessary.

**Comment by sericks007** [comment]
Bug 725474 has been logged to track this issue.

**Comment by bishalgoswami** [comment]
Bug 734209 has been logged to address this issue.

**Comment by josaw1** [comment]
Closed as won't fix.
