### ISSUE TITLE
Guidance of TierX may confuse readers.

### ISSUE THREAD

**Issue by kesun1** [MicrosoftDocs/dynamics-365-unified-operations-public#4082]
[Enter feedback here]
Hi,

One of my Partner got confused difference between TierX guidance and provisioned production env.
I worked a partner who followed the TierX guidance of this page (see following link) and did complex performance test in Tier 5 env because the customer had 180 users and 140K SO trans/hour.

https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/imp-lifecycle/environment-planning#selecting-the-correct-tier-2-or-higher-environment

The tier 5 env had 6 AOS servers and 6 AOS batch servers. however, they got the production provisioned with 4 AOS servers and 2 AOS batch servers even though they provided above numbers of users & transactions during Go-Live review.

I know there is a description in this document said "Tier2 and above are same architecture of production but sizing and DR is difference" would mean production env is more high spec. However, that description was very short wards and gave just an expectation. 
https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/imp-lifecycle/environment-planning#tier-1-vs-tier-2-and-higher

It would be much appreciated if you could consider to update this doc with more accurate information for env planning. 

Thanks.
Keisuke

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2402dfea-008a-c7bb-8a3b-1d0457a39665
* Version Independent ID: 4936afad-9a39-e65d-a00c-81246de632cb
* Content: [Environment planning - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/imp-lifecycle/environment-planning)
* Content Source: [articles/fin-ops-core/fin-ops/imp-lifecycle/environment-planning.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/imp-lifecycle/environment-planning.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by sericks007** [comment]
Bug 15046952 has been logged to track this issue.

**Comment by josaw1** [comment]
Closed as won't fix.
