### ISSUE TITLE
Where can I find the BankReconiliation-to-Composite.xsl file?

### ISSUE THREAD

**Issue by primeitbr** [MicrosoftDocs/dynamics-365-unified-operations-public#4084]
;)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84ddda24-328c-d279-f2e2-f0a61d0ad639
* Version Independent ID: 67df07ad-1695-b69a-dbcf-00de259afb25
* Content: [Advanced bank reconciliation MT940 Import – Composite data entity upgrade - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/cash-bank-management/advanced-bank-reconciliation-mt940-data-entity-upgrade-steps)
* Content Source: [articles/finance/cash-bank-management/advanced-bank-reconciliation-mt940-data-entity-upgrade-steps.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/cash-bank-management/advanced-bank-reconciliation-mt940-data-entity-upgrade-steps.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @angelad116
* Microsoft Alias: **angelading**

**Comment by sericks007** [comment]
@primeitbr, thanks for providing this feedback.

@angelad116, please answer this question and update the content, as needed.

**Comment by sericks007** [comment]
Bug 725475 has been logged to track this issue.

**Comment by angelad116** [comment]
@primeitbr Hello,, please kindly refer to this document for sample files: https://docs.microsoft.com/en-us/dynamics365/finance/cash-bank-management/set-up-advanced-bank-reconciliation-import-process.
Meanwhile as mentioned in the document, XSLT will be deprecated, so need to raise ticket to Microsoft support to use this function currently. We suggest to use ER functionality to import bank statement.
