### ISSUE TITLE
Update .NET Requirement

### ISSUE THREAD

**Issue by mikecaterino** [MicrosoftDocs/dynamics-365-unified-operations-public#4085]
Hello,
    When installing the DRA from Dynamics 365 version 10.0.28, it states that .NET 4.7.2 is required. This doc states that 4.6.2 is required. Just a heads up

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fe44c05-ed58-b554-859e-2da552dbbd9d
* Version Independent ID: e638edab-dd54-6008-f210-524fd52b0e5b
* Content: [Install the Document Routing Agent to enable network printing - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/install-document-routing-agent?toc=%2Fdynamics365%2Fcommerce%2Ftoc.json)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/install-document-routing-agent.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/analytics/install-document-routing-agent.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @RichdiMSFT
* Microsoft Alias: **richdi**

**Comment by sericks007** [comment]
@mikecaterino, thanks for making us aware of this.

@RichdiMSFT, please update the content, as needed.

**Comment by sericks007** [comment]
Bug 725476 has been logged to track this issue.
