### ISSUE TITLE
SRU codes are not 3 digit in Swedish companies. It is a 4 digit code. Almost all accounting persons in Sweden are using the SIE 4 digit format for reporting, month end closing work, year end statutory work etc. So it would be a good thing to have for big Swedish companies with a large number of legal entities using D365.

### ISSUE THREAD

**Issue by feodala99** [MicrosoftDocs/dynamics-365-unified-operations-public#4086]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb860ee3-23e2-cd0f-c67a-772dcbe85f4f
* Version Independent ID: 0de27640-e45c-2fec-0b40-049c3e42abe8
* Content: [Export financial information for auditors in Sweden - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/emea-swe-sie-standard-report)
* Content Source: [articles/finance/localizations/emea-swe-sie-standard-report.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/emea-swe-sie-standard-report.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @ShylaThompson
* Microsoft Alias: **roschlom**

**Comment by sericks007** [comment]
Bug 725487 has been logged to track this issue.

**Comment by kfend** [comment]
Updated the topic to remove the mention of a three-digit code. Changes will go live later today.
