### ISSUE TITLE
The section "Installation Steps" contains contradicting steps

### ISSUE THREAD

**Issue by Pikhulya** [MicrosoftDocs/dynamics-365-unified-operations-public#4089]
The section [Installation Steps](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/deploy-retail-onprem#installation-steps)  contains a step #2 saying:

![image](https://user-images.githubusercontent.com/11545082/180310302-f03076aa-7680-473e-9e99-c60dc17262e5.png)
 
And then Step #4 says:
![image](https://user-images.githubusercontent.com/11545082/180310471-fe0b3870-1823-4aac-a6d9-bc8b16539da8.png)

Note that these steps speak about 2 different folders - C:/selfservicepackages and  C:\RetailSelfService\Packages

The step #6, by the way, also points to C:/selfservicepackages:
![image](https://user-images.githubusercontent.com/11545082/180311127-410fc123-d710-46ca-a34d-7d7f60f0adb4.png)

Those different folders in different steps don't look right as the created folder's path must be used in the command. In addition, C:/selfservicepackages contains wrong slash.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4e9b59c-8b2b-e2bc-a342-2289bb99a066
* Version Independent ID: 3237f2a5-90cb-e041-2a08-369ef38a8c4b
* Content: [Installation steps for Retail channel components in an on-premises environment - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/deploy-retail-onprem)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/deploy-retail-onprem.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/deployment/deploy-retail-onprem.md)
* Service: ****
* Product: **dynamics-365**
* Technology: ****
* GitHub Login: @jashanno
* Microsoft Alias: **jashanno**

**Comment by sericks007** [comment]
@Pikhulya, thanks for providing this feedback.

@jashanno, please review and update content, as needed.

**Comment by sericks007** [comment]
Bug 725488 has been logged to track this issue.

**Comment by josaw1** [comment]
Closed as won't fix.
