### ISSUE TITLE
Is the "you" the customer or partner?

### ISSUE THREAD

**Issue by weaveriski** [MicrosoftDocs/dynamics-365-unified-operations-public#409]
There needs to be more clarity on who the "you" is in these scenarios. If a package is applied to production the service request is closed and set to successful. Is this a task for the customer? This is the commercial sign off for the process to Microsoft that the deployment is successful it feels that this must be the customer because the partner is involved light touch here, but at the same time it is a process many partners oversee. Commercially partners might be reluctant to sign this off, but what are the implications of this task not being undertaken?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4008b2e3-4d1a-e146-8bdb-f39280124e9f
* Version Independent ID: 22f8390d-bb4d-1755-515c-7e7ebf1ddaae
* Content: [Apply updates to cloud environments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/deployment/apply-deployable-package-system)
* Content Source: [articles/dev-itpro/deployment/apply-deployable-package-system.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/deployment/apply-deployable-package-system.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @manalidongre
* Microsoft Alias: **manado**

**Comment by tonyafehr** [comment]
Thanks for the helpful feedback. We're investigating this and will provide more clarity to this topic, as requested (bug # 252259 has been written to address this issue).
