### ISSUE TITLE
Technical Reference Reports page is outdated

### ISSUE THREAD

**Issue by VPranith** [MicrosoftDocs/dynamics-365-unified-operations-public#4092]
[The technical reference reports page that is linked in this page seems to be outdated. It has details from PU 17 and none after that. It may be useful to enhance it further as the last update in 2021 July. ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60ff0ecf-cab1-5665-554e-ec493c3a6159
* Version Independent ID: e02b7a35-a15f-9205-d084-b3498eddc842
* Content: [Removed or deprecated features in Dynamics 365 Supply Chain Management - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/get-started/removed-deprecated-features-scm-updates)
* Content Source: [articles/supply-chain/get-started/removed-deprecated-features-scm-updates.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/get-started/removed-deprecated-features-scm-updates.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @kamaybac
* Microsoft Alias: **kamaybac**

**Comment by josaw1** [comment]
Hi, thank you for the comment. I'm seeing the last update was made for 10.0.19. This article will only be updated as needed. + @kamaybac for awareness.
