### ISSUE TITLE
Option for custom MT system

### ISSUE THREAD

**Issue by gertvdh** [MicrosoftDocs/dynamics-365-unified-operations-public#4094]
There is no option to enable custom MT system from the API/DevOps task. Will this be added in time? If so this might need some adjustments on the task since it should not wait on the processing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 839812be-657e-e82b-1b8d-a2d45e4a60eb
* Version Independent ID: 72b1cacf-9fbc-f099-caff-a0c4f9f581ab
* Content: [Dynamics 365 Translation Service overview - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/translation-service-overview#custom-trained-mt-model)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/translation-service-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/lifecycle-services/translation-service-overview.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @abmotgi
* Microsoft Alias: **abmotgi**

**Comment by josaw1** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle requests for the product here. Consider adding your request to the [Ideas site](https://experience.dynamics.com/ideas/).

**Comment by bishalgoswami** [comment]
Bug 15336081 has been logged to address this issue.

**Comment by sericks007** [comment]
@gertvdh, thanks for contacting us. Unfortunately, we're unable to handle requests for the product here. Consider adding your request to the [Ideas site](https://experience.dynamics.com/ideas/).

**Comment by arianapadilla** [comment]
Hi @gertvdh, thank you very much for your feedback.  We appreciate the time you took to leave us the comment!  

Unfortunately, we don't have a plan to support custom MT option through any of the DTS extensions at this point.  However, we will keep it in our backlog in case it becomes feasible in the future. 

If you have any more feedback or questions, please do not hesitate to contact us at dtssup@microsoft.com.
