### ISSUE TITLE
Misleading sentence

### ISSUE THREAD

**Issue by XStamatiou** [MicrosoftDocs/dynamics-365-unified-operations-public#4095]
The sentence below is rather misleading:
"All customer subscriptions come with at least one development VM. Customers can pay for add-on dev VMs or run local dev VMs."

As far as I know, apart from the UAT and Prod environment (both of which cannot be used for development), there is no other environment or VM provided. Therefore what is this "at least one development VM" referring to? Additional dev VMs are always an option, but of course they cost extra, and are not part of the subscription.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a61360d4-73b1-104e-dfd4-7584c485cd0d
* Version Independent ID: 1f7c0203-4b68-9df2-a33e-69a2cf2b3b90
* Content: [Development and continuous delivery FAQ - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/continuous-delivery-faq#should-i-use-a-customers-dev-environment)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/continuous-delivery-faq.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/dev-tools/continuous-delivery-faq.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by josaw1** [comment]
Thank you for your feedback. @laneswenka can you please review?

**Comment by josaw1** [comment]
Closed as won't fix.
