### ISSUE TITLE
Correct the link in Move Production Environments section

### ISSUE THREAD

**Issue by tomhig** [MicrosoftDocs/dynamics-365-unified-operations-public#4100]
The link to the Service Description is not correct that is in this section:

https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/move-environments-data-center?context=%2Fdynamics365%2Fcontext%2Ffinance#move-production-environments

The link is directing to the now outdated service description PDF.

Please use this vanity URL for the link:

https://aka.ms/D365-Cloud-Service-Operations

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f44ca5d-f623-51e3-1ec3-0b02f5215dce
* Version Independent ID: cc895276-ae7f-3508-877b-084c2cf3e159
* Content: [Move environments between data centers - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/move-environments-data-center?context=%2Fdynamics365%2Fcontext%2Ffinance)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/move-environments-data-center.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/move-environments-data-center.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @ClaudiaBetz-Haubold
* Microsoft Alias: **chaubold**

**Comment by josaw1** [comment]
Thank you for your feedback. @ClaudiaBetz-Haubold can you please take a look?

**Comment by sericks007** [comment]
I've corrected the link.  The updated content will be published soon.
