### ISSUE TITLE
May we ask when the what's new public doc will be updated for the new version 10.0.29? 

### ISSUE THREAD

**Issue by FangyuanHou** [MicrosoftDocs/dynamics-365-unified-operations-public#4102]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27899f77-9cc9-1831-fa16-9c0c71f8f1c3
* Version Independent ID: 4bfcb1d6-3e1d-b24b-4429-ab3b8f31eb3e
* Content: [What's new or changed in finance and operations apps home page - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/whats-new-changed)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/whats-new-changed.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/whats-new-changed.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by johnmichalak** [comment]
@FangyuanHou Hello, that content should publish today (or possibly tomorrow to be safe).
