### ISSUE TITLE
incorrect version listed

### ISSUE THREAD

**Issue by deansteg** [MicrosoftDocs/dynamics-365-unified-operations-public#4104]
The Note on this page includes this last bullet point

Version N-4 is four versions older than N, such as 10.0.22 (In this example, customers on version 10.0.22 can't pause updates.)

This should list version 10.0.21 like this

Version N-4 is four versions older than N, such as 10.0.21 (In this example, customers on version 10.0.21 can't pause updates.)

The same Note is on the FAQ article here - https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/one-version?context=%2Fdynamics365%2Fcontext%2Ffinance.  On this page it is correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 878313ed-a9b2-797f-b483-142df974639c
* Version Independent ID: 6fa7a7f2-3fd5-477f-3340-9b13789949d8
* Content: [Pause service updates through Lifecycle Services (LCS) - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/pause-service-updates)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/pause-service-updates.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/lifecycle-services/pause-service-updates.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by sericks007** [comment]
@deansteg, thank you for pointing out this typo!  I've corrected the text.  The updated text will be published soon.
