### ISSUE TITLE
French fiscal integration setup omits need for 'Use advanced certificate store' = YES for cloud-based PROD environments

### ISSUE THREAD

**Issue by timpcooper** [MicrosoftDocs/dynamics-365-unified-operations-public#4106]
There is a crucial piece of required setup for Azure Key Vault client that is not mentioned, or linked here from this page.
 
Per this doc:
https://support.microsoft.com/en-us/topic/setting-up-azure-key-vault-client-84e53cef-99d6-3f35-9dc5-fa855b309f5b
 
A cloud-based PROD Environment MUST have the following field set: System Parameters > Use Advanced Certificate Store = YES
Otherwise, the Commerce Parameters > Digital signatures > drop down will NOT show Key Vault certs.

If 'Use advanced certificate store' = NO for a cloud-based prod environment, then the 'Certificate' drop down on the Digital Signatures page will show some unknown set of certificates from 'local storage' and the user will not be able to successfully setup the French Fiscal integration.

Suggest that the fiscal integration documentation include at the minimum a link to the 'setting up azure key vault client' page in  'Recommended content', or better yet, a (!) Note box that mentions the 'setting up azure key vault client' link and/or the 'Use advanced certificate store' setting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7767a19-6e66-4ea4-9be7-6e69e9028bc3
* Version Independent ID: aa974e50-898f-af5b-4045-c9c16747c8d7
* Content: [Cash register functionality for France - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/localizations/emea-fra-cash-registers#configure-the-digital-signature-parameters)
* Content Source: [articles/commerce/localizations/emea-fra-cash-registers.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/localizations/emea-fra-cash-registers.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @EvgenyPopovMBS
* Microsoft Alias: **epopov**

**Comment by johnmichalak** [comment]
@timpcooper Thank you for the feedback. I will contact the author and ask them to review your suggestions and make changes as appropriate.

**Comment by johnmichalak** [comment]
@EvgenyPopovMBS Please take a look at this suggestion and update the article as appropriate.

**Comment by EvgenyPopovMBS** [comment]
Thanks, I will review the suggestion and make appropriate changes.

-------------------------
Best regards,
Evgeny.

**Comment by josaw1** [comment]
@EvgenyPopovMBS any updates required?

**Comment by josaw1** [comment]
BUG 734208

**Comment by EvgenyPopovMBS** [comment]
Yes, I’m working on a big functional update for France (Content Deliverable 684499<https://msdyneng.visualstudio.com/FinOps/_workitems/edit/684499>/Deliverable 684496<https://msdyneng.visualstudio.com/FinOps/_workitems/edit/684496>), and will add this change to the update.

-------------------------
Best regards,
Evgeny.

**Comment by KendalBond007** [comment]
@EvgenyPopovMBS  - Following up: any additional work needed on this, or can we slate it to close?

@josaw1
@johnmichalak
