### ISSUE TITLE
Duplicate words

### ISSUE THREAD

**Issue by jje210** [MicrosoftDocs/dynamics-365-unified-operations-public#4110]
[The second where in: "No matter where where" may be removed]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf664431-b092-8d49-567d-90245aa48c99
* Version Independent ID: 14fce919-2a2d-4eab-b190-375516f6f05b
* Content: [Integrated customer master - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/customer-mapping)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/customer-mapping.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/dual-write/customer-mapping.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @RamaKrishnamoorthy
* Microsoft Alias: **ramasri**

**Comment by sericks007** [comment]
@jje210, thanks for letting us know about this!  I've fixed that sentence.  The updated content will be published later today.
