### ISSUE TITLE
Duplicate contact-record when creating a contactperson in F&O first, and then a customer for that party

### ISSUE THREAD

**Issue by jje210** [MicrosoftDocs/dynamics-365-unified-operations-public#4111]
[Do you have any idea why a seperate contact-record in PP is created if you first create a contactperson in F&O, and then a customer of type person in F&O for the same party? If you first create a customer of type person in F&O, and then a contactperson in F&O, only one contact-record is created in PP, with the number sequence of the customer.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc903201-84fc-ebac-9c31-78b0310f52ec
* Version Independent ID: 44c60119-d2c0-f1f6-77fa-47b3d98c1fea
* Content: [Prospect-to-cash in dual-write - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/dual-write-prospect-to-cash)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/dual-write-prospect-to-cash.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/dual-write/dual-write-prospect-to-cash.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @RamaKrishnamoorthy
* Microsoft Alias: **ramasri**

**Comment by johnmichalak** [comment]
@jje210 Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
