### ISSUE TITLE
Missing powershell Execution Mode prerequisites

### ISSUE THREAD

**Issue by Pikhulya** [MicrosoftDocs/dynamics-365-unified-operations-public#4113]
The page's section Prerequisites is missing an information that the Powershell's execution policy should be RemoteSigned. By default it is restricted and as a result the deployment will fail. The Execution Policy can be checked with [Get-ExecutionPolicy](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/get-executionpolicy?view=powershell-7.2) and then if it is Restricted or more strict - the following should be executed in Powershell: `Set-ExecutionPolicy -RemoteSigned`. The cmd let is mentioned [here](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-executionpolicy?view=powershell-7.2).
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45ebad3c-1d63-3e3d-4b0c-84acb7cb84ef
* Version Independent ID: b5a17324-a2fc-48a6-28e0-db115a722469
* Content: [Store Commerce app - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/store-commerce)
* Content Source: [articles/commerce/dev-itpro/store-commerce.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/store-commerce.md)
* Service: **dynamics-365-commerce**
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by kfend** [comment]
@Pikhulya - Thank you for the feedback.
@josaw1 - Can you please assign this to the correct PM for updating? Thanks!

**Comment by josaw1** [comment]
@mugunthanm can you please review this feedback?

**Comment by KendalBond007** [comment]
@mugunthanm - Following up: any additional work needed on this, or can we slate it to close?

@josaw1
