### ISSUE TITLE
New Discount concurrency mode option Always apply is not described

### ISSUE THREAD

**Issue by jmeijering** [MicrosoftDocs/dynamics-365-unified-operations-public#4117]
In this page the new discount concurrency mode option Always apply is not described. What does it do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 446bde34-336d-f791-b24f-c5b13f0ed685
* Version Independent ID: 2f358f3a-acdd-e710-beef-24e19d154617
* Content: [Retail discounts - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/retail-discounts-overview)
* Content Source: [articles/commerce/retail-discounts-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/retail-discounts-overview.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @shajain
* Microsoft Alias: **shajain**

**Comment by kfend** [comment]
@jmeijering - Thank you for the question.
@josaw1 - Can you please assign this to the correct PM to address? Thanks!

**Comment by josaw1** [comment]
@ShalabhjainMSFT please review.

**Comment by ShalabhjainMSFT** [comment]
@josaw1 please assign this to @boycezhu-zz

**Comment by bishalgoswami** [comment]
Bug 734207 has been logged to address this issue.

**Comment by josaw1** [comment]
@boycez can you please review?

**Comment by boycez** [comment]
@josaw1 I'll publish an updated doc to address this issue. Authoring in progress.

**Comment by sericks007** [comment]
Closing this issue as a duplicate.  This will be addressed when #4118 is addressed.
