### ISSUE TITLE
 In this page the new discount concurrency mode option Always apply is not explained in the examples

### ISSUE THREAD

**Issue by jmeijering** [MicrosoftDocs/dynamics-365-unified-operations-public#4119]
In this page the new discount concurrency mode option Always apply is not explained in the expamles, please add an example for it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ed31de6-6f28-8607-9537-dc7d7de2fbac
* Version Independent ID: e9f952d3-bbeb-c566-f89d-49a141794807
* Content: [Apply multiple Retail discounts to a product - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/apply-multiple-retail-discounts)
* Content Source: [articles/commerce/Apply-multiple-retail-discounts.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/Apply-multiple-retail-discounts.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @shajain
* Microsoft Alias: **shajain**

**Comment by kfend** [comment]
@jmeijering - Thank you for this feedback.
@josaw1 - Can you please assign this to the correct PM for update? Thanks!

**Comment by josaw1** [comment]
@ShalabhjainMSFT please review.

**Comment by ShalabhjainMSFT** [comment]
@boycezhu-zz is the new owner for this area

**Comment by josaw1** [comment]
@boycez please review this comment.

**Comment by sericks007** [comment]
Closing this issue as a duplicate.  This will be covered when GitHub issue #4118 is addressed.
