### ISSUE TITLE
onFindingEntityDataSource duplicate

### ISSUE THREAD

**Issue by OksanaKovaliova** [MicrosoftDocs/dynamics-365-unified-operations-public#412]
Hi,
onFindingEntityDataSource event is repeated 5 times in the table. Looks like there is not difference between these 5 rows

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac5bd5e3-de75-79f0-1a00-4d9267032eba
* Version Independent ID: 28f1623d-c6db-5b5b-f2fe-9728a3c370e7
* Content: [Customize through extension and overlayering - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/extensibility/customization-overlayering-extensions#label-extensions)
* Content Source: [articles/dev-itpro/extensibility/customization-overlayering-extensions.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/extensibility/customization-overlayering-extensions.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @robadawy
* Microsoft Alias: **robadawy**

**Comment by tonyafehr** [comment]
Thanks for pointing this out! We really appreciate feedback that helps us to improve our documentation. I will update the table, these changes should be live later today.
