### ISSUE TITLE
Advanced Bank Rec BAI2 ER Configuration Not Working on Available Version

### ISSUE THREAD

**Issue by JFerg523** [MicrosoftDocs/dynamics-365-unified-operations-public#4128]
The latest ER configurations for the ABR BAI2 Model Mapping fails.  It is requiring version 10.0.1283 but the latest release available for us is 10.0.1635.  This is an issue as the model mapping configuration will not import from the global repository.  LCS shows our version is the latest available.  

In addition, the prerequisites for the BAI2 Model Mapping in ER lists package and KBs that are not available in LCS.

![BAI2 Model Mapping Prerequisite Updates](https://user-images.githubusercontent.com/111589020/185661762-eb1c48dd-78b8-4184-82d2-7ffd756d8306.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33ed78e0-bbee-3178-b448-2d86790f20bf
* Version Independent ID: 33ed78e0-bbee-3178-b448-2d86790f20bf
* Content: [Set up advanced bank reconciliation import by using Electronic reporting - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/accounts-payable/import-bai2-er)
* Content Source: [articles/finance/accounts-payable/import-BAI2-ER.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/accounts-payable/import-BAI2-ER.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @panolte
* Microsoft Alias: **shpandey**

**Comment by bishalgoswami** [comment]
Bug 734203 has been logged to address this issue.

**Comment by angelad116** [comment]
@JFerg523 Hello, we have fixed this issue.
