### ISSUE TITLE
Parameter für Lager- und Lagerortverwaltung*

### ISSUE THREAD

**Issue by verna-avanade** [MicrosoftDocs/dynamics-365-unified-operations-public#4132]
[Hier Feedback eingeben]

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 9cb0e8c4-73ae-3514-49cb-47457297343e
* Version Independent ID: 7e0278ce-0637-386e-fdcc-79ba3f4baa16
* Content: [Ermöglicht Qualitäts- und Qualitätsmangel-Management - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/de-de/dynamics365/supply-chain/inventory/enable-quality-management)
* Content Source: [articles/supply-chain/inventory/enable-quality-management.md](https://github.com/MicrosoftDocs/Dynamics-365-Operations.de-de/blob/live/articles/supply-chain/inventory/enable-quality-management.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @yufeihuang
* Microsoft Alias: **yufeihuang**

**Comment by sericks007** [comment]
@verna-avanade, please indicate the issue in the documentation that you want corrected. Thanks!

**Comment by verna-avanade** [comment]
Wrong translation: 
Bestandsverwaltung > Einrichtung > Bestands- und Lagerverwaltungsparameter
should be:
Lagerverwaltung > Einstellungen > Parameter für Lager- und Lagerortverwaltung

**Comment by kamaybac** [comment]
This issue has been forwarded to our localization team, who are tracking it here: https://dev.azure.com/bagie/Production/_workitems/edit/70479/

**Comment by kamaybac** [comment]
This has been reported as resolved by our translation team.
