### ISSUE TITLE
Bundle Qty roll-up calculation of components on Invoice

### ISSUE THREAD

**Issue by Wolfram66** [MicrosoftDocs/dynamics-365-unified-operations-public#4133]
When a Bundle item has 3 components of Qty 1 ea
We are seeing the InvoiceLine entity return roll-up qty = 0.99999 rather than 1.00000
    {
      **"@odata.etag":"W/\"JzEsNTYzNzE0NjA3Nzs4ODY1MDMwODMsNTYzNzE4MzI2Mic=\"","dataAreaId":"","RecIdLine":5637183262,"Qty":0.999999,"RequestDate":"","PriceRatio":0,"ShippedDate":"","RecIdHeader":5637217867,"EdiTransferred":0,"RequestedShipdate":"","InvoiceNo":"","LineTaxAmt":0,"ExtendedTaxAmount":"","UOM":"EA","yearLastDay":"2019-12-31 01:00:00.000","TaxPercent":0,"PromiseDate":"","ItemDesc":"MAKERSPACE 6-8 STEMLAB MATERIALS 3BX","LinUser3":0,"QtyToShip":3,"LineTaxableAmt":1499.99,"LocAdd2":"","LocAdd3":"","ReasonCd":"","LocAdd1":"","ExtendedPrice":1499.99,"QtyReturntoStk":0,"TaxState":"","LineTaxSched":"","LocState":"","CusItemId":"","LocName":"","LinUser4":0,"LinUser1":"","ItemId":"92931","LocZip":"","TaxFlag":"ITM","LineNo":3,"LinUser5":3,"LinUser2":0,"Price":1499.99,"LocCity":"","RecordType":"ITM","InventTransId":"LOT000003429","Taxable":"","LineTaxCd":"","LocCountry":"","InventDimId":"#00000001500005DD","LocId":"","ItemDesc2":"MAKERSPACE 6-8 STEMLAB MATERIALS 3BX"
    }
Is this an issue of how this field is configured on the entity using an attribute or parameter? Calculated vs Roll-up?
Invoiced Qty isnt matching for 3 way matching validations
---**
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2e759b4-ee7e-56e5-6b32-3981042c6331
* Version Independent ID: 7d1125a1-71b2-d0dc-f826-f9c472606223
* Content: [Revenue recognition bundles - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/accounts-receivable/rev-rec-bundles)
* Content Source: [articles/finance/accounts-receivable/rev-rec-bundles.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/accounts-receivable/rev-rec-bundles.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @kweekley
* Microsoft Alias: **kweekley**

**Comment by bishalgoswami** [comment]
Bug 734548 has been logged to address this issue.

**Comment by brkingmsft** [comment]
Hi Wolfram66 - can you provide more context or detail so we can investigate further? The specific entity you are seeing this behavior in would be important here. Based on what I'm reading here this doesn't seem to be an issue with the documentation but potentially a product issue. I'd also recommend opening this as a support incident for proper traction and handling.

**Comment by brkingmsft** [comment]
I am resolving this item as it is not a documentation issue. Please open a support request for your issue to be investigated further.
