### ISSUE TITLE
Topic DYN558PAL2 link is broken

### ISSUE THREAD

**Issue by dsteinkepcl** [MicrosoftDocs/dynamics-365-unified-operations-public#4137]
The topic "finance and operations: Extending Dynamics 365 Finance with PowerApps (DYN558PAL2)"
link is broken. (https://community.dynamics.com/365/b/techtalks/posts/finance-and-operations-extending-dynamics-365-with-powerapps-2-6-2019)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 888a4451-c840-625a-d0da-63cc3fe1f55c
* Version Independent ID: f75e81ed-7ba4-123e-5405-99704aaf98d1
* Content: [Learning catalog for Dynamics 365 Finance developers - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/get-started/learning-catalog-developer)
* Content Source: [articles/finance/get-started/learning-catalog-developer.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/get-started/learning-catalog-developer.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @MargoC
* Microsoft Alias: **margoc**

**Comment by bishalgoswami** [comment]
Bug 735258 has been logged to address this issue.

**Comment by cstorega** [comment]
Bug 735258 _ this has been fixed by margo - a redirect is in place.
