### ISSUE TITLE
Missing Friend Package information

### ISSUE THREAD

**Issue by ThomasZak1** [MicrosoftDocs/dynamics-365-unified-operations-public#4138]
There is a new Friend Package feature (starting 10.0.27?). But Microsoft has not documented it here yet.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4415555b-d436-8e95-b68f-72a3104544bf
* Version Independent ID: 4d92f8ec-70fe-3651-e5a2-038438d24c2a
* Content: [Models and packages - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/models)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/models.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/dev-tools/models.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @gianugo
* Microsoft Alias: **gianura**

**Comment by bishalgoswami** [comment]
Bug 735257 has been logged to address this issue.

**Comment by KendalBond007** [comment]
As noted above, Bug 735257 has been filed on this issue and has been resolved/closed. If you have additional issues, please contact Support; consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
