### ISSUE TITLE
Entity security should be mentioned under the When will an entity show as an Open in Excel option

### ISSUE THREAD

**Issue by dechanan** [MicrosoftDocs/dynamics-365-unified-operations-public#4139]
[Enter feedback here]

I think a note should be added with a link to this page 

https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/security-data-entities 

Should be noted that customer will need Data management entry point access  (this is very important for custom entities

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 961239b1-2cab-7982-5198-71d85ab7a34c
* Version Independent ID: cc990680-89a4-41b9-9934-6a8a1047b5d4
* Content: [Open in Excel experiences FAQ - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/office-integration/office-integration-edit-excel?context=%2Fdynamics365%2Fcontext%2Fcommerce)
* Content Source: [articles/fin-ops-core/dev-itpro/office-integration/office-integration-edit-excel.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/office-integration/office-integration-edit-excel.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by bishalgoswami** [comment]
Bug 735339 has been logged to address this issue.

**Comment by johnmichalak** [comment]
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.
