### ISSUE TITLE
Why not using just Semantic Versioning

### ISSUE THREAD

**Issue by Vall0n** [MicrosoftDocs/dynamics-365-unified-operations-public#4141]
[Enter feedback here]
Why not using [Semantic Versioning](https://semver.org)... Why use a asterisks for major releases... I don't get it...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7dcb285-f32c-c92e-fe49-1617f213066b
* Version Independent ID: 8f28c1a0-9da5-f853-90ee-d82a4c32df7e
* Content: [Service update availability - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/public-preview-releases)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/public-preview-releases.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/public-preview-releases.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @hmahl
* Microsoft Alias: **hmahl**

**Comment by bishalgoswami** [comment]
Bug 735439 has been logged to address this issue.

**Comment by sericks007** [comment]
@Vall0n, thank you for your feedback! This is not a high-priority issue at this time, so closing this issue.  Consider adding your request to the [Ideas site](https://experience.dynamics.com/ideas/).
