### ISSUE TITLE
Missing info about Natura codes and application specific parameters

### ISSUE THREAD

**Issue by mkowalka** [MicrosoftDocs/dynamics-365-unified-operations-public#4143]
Hi, 
there is missing information how to setup application specific parameters for Vendor Invoice (IT)
It's on customer electronic invoice, but even there is no info about minimum setup for *blank* and *not blank* for Others lookup result. 

Please add the details for vendor invoice page. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94047218-6b10-b23b-d2c7-0ecf90f5de0e
* Version Independent ID: 94047218-6b10-b23b-d2c7-0ecf90f5de0e
* Content: [Vendor electronic invoices - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/emea-ita-vend-e-invoices)
* Content Source: [articles/finance/localizations/emea-ita-vend-e-invoices.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/emea-ita-vend-e-invoices.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @mrolecki
* Microsoft Alias: **mrolecki**

**Comment by bishalgoswami** [comment]
Bug 744554 has been logged to address this issue.

**Comment by kfend** [comment]
@mkowalka - Thank you for the feedback. This article has been updated and the changes will go live later today.
