### ISSUE TITLE
Will Microsoft implement Saudi Zatca E-Invoicing phase II before 2023?

### ISSUE THREAD

**Issue by liamneesangamer** [MicrosoftDocs/dynamics-365-unified-operations-public#4147]
We are in the implementation stage of dynamics 365. Could you clarify 2 short questions

1. Will Microsoft implement of E-Invoice(ZATCA PHASE II) before jan-2023?
2. Is there any limitations for E-Invoicing number of transactions per month/tenant basis? Because we are in the Retail hypermarket business. So, the number of transactions are higher than any other business model. the below contents are found in "Dynamics 365 License Guide"

"_Electronic invoicing is the process of creating, presenting, and exchanging structured,
transactional invoice documents between businesses and governments for tax
reporting purposes, or trading partners in an integrated electronic format.
Dynamics 365 Commerce, Finance, Project Operations, and Supply Chain Management applications include 100
electronic invoice transactions/tenant/month. This included capacity does not rollover and is 100 transactions
per tenant, regardless of the number of Dynamics 365 licensed applications.
If you need additional transactions, you can buy the Electronic Invoicing additional capacity license for 1K
electronic invoice transactions/tenant/month. The transaction capacity is use-it-or-lose-it on a monthly basis,
and customers will need to purchase for peak capacity._"

Please kindly clarify these both 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 332ecc73-b911-de45-fd7c-4f2e1926db53
* Version Independent ID: 5057d69e-3e33-19c3-69e0-6aad0fff5e5e
* Content: [Electronic invoicing overview - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/e-invoicing-service-overview)
* Content Source: [articles/finance/localizations/e-invoicing-service-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/e-invoicing-service-overview.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @gionoder
* Microsoft Alias: **gionoder**

**Comment by bishalgoswami** [comment]
Bug 744759 has been logged to address this issue.

**Comment by gionoder** [comment]
Hi,

**Question #1:** Will Microsoft implement of E-Invoice (ZATCA PHASE II) before jan-2023?
**Answer:** Yes, for details about scope and timelines, please consult the release plan available at: https://docs.microsoft.com/en-us/dynamics365-release-plan/2022wave2/finance-operations/dynamics365-finance/access-saudi-arabia-e-invoice-integration.

The Electronic Invoicing phase 2 for Saudi Arabia is already in Public Preview, general resources about Electronic Invoicing are available at:

Electronic invoicing overview: https://docs.microsoft.com/en-us/dynamics365/finance/localizations/e-invoicing-service-overview?context=%2Fdynamics365%2Fcontext%2Ffinance)

And the Country specific resources are available at:

Electronic invoicing onboarding in Saudi Arabia: https://docs.microsoft.com/en-us/dynamics365/finance/localizations/e-invoicing-sa-onboarding
Get started with Electronic invoicing for Saudi Arabia: https://docs.microsoft.com/en-us/dynamics365/finance/localizations/e-invoicing-sa-get-started

You are welcome to join the Preview Community, where you will have access to the Preview for Saudi Arabia phase 2, and others upcoming Electronic Invoicing features.

**Question #2:** Is there any limitations for E-Invoicing number of transactions per month/tenant basis? Because we are in the Retail hypermarket business. So, the number of transactions are higher than any other business model. the below contents are found in "Dynamics 365 License Guide"

**Answer:** There is no technical limitations, but it is advisable to consult the "Dynamics 365 License Guide" for more information about the licensing policy for Electronic Invoicing. Also please, consult the release plan for more information about the supported scope of electronic invoicing for Retail in Saudi Arabia.

**Comment by liamneesangamer** [comment]
> Hi,
> 
> **Question #1:** Will Microsoft implement of E-Invoice (ZATCA PHASE II) before jan-2023? **Answer:** Yes, for details about scope and timelines, please consult the release plan available at: https://docs.microsoft.com/en-us/dynamics365-release-plan/2022wave2/finance-operations/dynamics365-finance/access-saudi-arabia-e-invoice-integration.
> 
> The Electronic Invoicing phase 2 for Saudi Arabia is already in Public Preview, general resources about Electronic Invoicing are available at:
> 
> Electronic invoicing overview: https://docs.microsoft.com/en-us/dynamics365/finance/localizations/e-invoicing-service-overview?context=%2Fdynamics365%2Fcontext%2Ffinance)
> 
> And the Country specific resources are available at:
> 
> Electronic invoicing onboarding in Saudi Arabia: https://docs.microsoft.com/en-us/dynamics365/finance/localizations/e-invoicing-sa-onboarding Get started with Electronic invoicing for Saudi Arabia: https://docs.microsoft.com/en-us/dynamics365/finance/localizations/e-invoicing-sa-get-started
> 
> You are welcome to join the Preview Community, where you will have access to the Preview for Saudi Arabia phase 2, and others upcoming Electronic Invoicing features.
> 
> **Question #2:** Is there any limitations for E-Invoicing number of transactions per month/tenant basis? Because we are in the Retail hypermarket business. So, the number of transactions are higher than any other business model. the below contents are found in "Dynamics 365 License Guide"
> 
> **Answer:** There is no technical limitations, but it is advisable to consult the "Dynamics 365 License Guide" for more information about the licensing policy for Electronic Invoicing. Also please, consult the release plan for more information about the supported scope of electronic invoicing for Retail in Saudi Arabia.

Thank you for reply,

**Question #1:** I got it, 

**Question #2:** Sorry, I didn't get your point, could you please elaborate more?.  In the "Dynamics 365 License Guide" 

It mentioned that **Dynamics 365 Commerce, Finance, Project Operations, and Supply Chain Management applications include 100
electronic invoice transactions/tenant/month, If you need additional transactions, you can buy the Electronic Invoicing additional capacity license for 1K
electronic invoice transactions/tenant/month** 

That's the point we need some clarification. Our business is hypermarket. Our daily transaction Invoices are around 7K to 10K per day. I hope each invoice should be considered as Electronic Invoice as per **Saudi Zatca E-Invoicing phase II**. So,

How this 100 or 1000 transaction limitations will be applicable to Hyper market business like us?
or Is this transaction limitation which is mentioned in "Dynamics 365 License Guide" are not relevant to  **E-Invoice of Saudi Zatca phase II**?.

![E-Invoice](https://user-images.githubusercontent.com/45831368/188261844-3ca3014c-8718-4f73-abcc-4e0ae1b744c5.jpg)

**Comment by gionoder** [comment]
Hi,
Typically, in retail business the invoices will be sent to ZATCA for reporting purposes, not for clearance. Then, for the summarized invoice submission, it will depend how often you submit transaction invoices to the service, and not necessarily how many retail invoices you are going to report. In another words, if you encompass multiple retail invoices in one submission to the service, that will count as one invoice transaction.

Thank you. Regards,

**Comment by gionoder** [comment]
Hi,

This information about encompassing several retail invoices in the same submission to ZATCA is not accurate and I would like to clarify. As is now, under the Retail scenarios, the submission of retail invoices to ZATCA are still for reporting purposes, however, differently that initially said, it will be submitted one by one, similarly to electronic invoices issued from a regular B2B sales.

We are working internally to mitigate the impact this approach might have for retails businesses, and close to the GA we will announce more details.

Thank you. Regards.

**Comment by liamneesangamer** [comment]
Hello Gionoder,

Do you mean that, As it was before "Multiple retail invoices(Summarized invoice) submission to Zatca counted as ONE", But now It will be "For B2C Each invoice will be submitted one by one, same like B2B sales". Is it?.

**Comment by liamneesangamer** [comment]
Hi Gionoder,

It's clear now for submission of E-Invoice. So, what about the **100 transactions limitation per month/tenant in hyper market business?**.  As you mentioned above, each invoices will be submitted one by one. So, If Microsoft considered one invoice submission will be counted as one, then this 100 transaction limitation it will not even cover for 30 min of sales invoice,

 or Is there any changes in limitations for Hyper market business?.

Microsoft must reconsider it for Retail business, In a peek days its reaching from 15K to 18K invoices in a day. we are in the implementation stage right now.
