### ISSUE TITLE
Demo environment

### ISSUE THREAD

**Issue by swordiuss** [MicrosoftDocs/dynamics-365-unified-operations-public#4148]
Where is HQUS legal entity?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fcbfaeb-97bd-7fc6-111c-6a18ac95bf3d
* Version Independent ID: 720a7fea-8b61-d9bf-238e-7b15c3065e26
* Content: [Subcontracting - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/production-control/subcontracting)
* Content Source: [articles/supply-chain/production-control/subcontracting.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/production-control/subcontracting.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @johanhoffmann
* Microsoft Alias: **johanho**

**Comment by johanhoffmann** [comment]
@swordiuss Unfortunately, the HQUS legal entity is no longer available. We will therefore remove this topic.
