### ISSUE TITLE
Missing documentation for Solution management tile in LCS

### ISSUE THREAD

**Issue by xDynaMike** [MicrosoftDocs/dynamics-365-unified-operations-public#4149]
Please provide documentation regarding Solution management tile - how this view is build, who can add records with "Global" scope and why users are able to see them and so on.

Thanks,
Michal
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 786fc060-d324-2e48-d4db-787895b8df3e
* Version Independent ID: d37abcc6-f7f7-5752-7d24-28f17b5d78aa
* Content: [Asset library in Lifecycle Services (LCS) - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/asset-library#help-us-understand)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/asset-library.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/lifecycle-services/asset-library.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by bishalgoswami** [comment]
Bug 15444735 has been logged to address this issue.
