### ISSUE TITLE
Additional Azure App Registration is required but not listed

### ISSUE THREAD

**Issue by finopsfuntimes** [MicrosoftDocs/dynamics-365-unified-operations-public#4152]
On this page, we have some prerequisites listed including a requirement to have a specific Azure App ID be enabled in the tenant.
(This is under the section 'Configure your Azure AD tenant')

In the scenario where a customer wishes to install the Add-In, but does not bring their own data lake, the Add-In will deploy a 'managed' data lake instead. In this scenario, a customer would not have completed the steps described here:
https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/configure-export-data-lake#createServicePrincipal

This causes add-in installation to fail because the service principle is still required but has not been configured. (A support ticket was required to determine the missing app registration as the cause.)

This page should be updated to add the App ID as a pre-requisite:
Application | App ID
Microsoft Dynamics ERP Microservices | 0cdb527f-a8d1-4bf8-9436-b352c68682b2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d45d1c62-6273-1eed-432e-0c2db98c4d95
* Version Independent ID: 1c0777b6-6c96-f02f-a2c3-73332ad456bc
* Content: [Configuration for Finance insights - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/finance-insights/configure-for-fin-insites)
* Content Source: [articles/finance/finance-insights/configure-for-fin-insites.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/finance-insights/configure-for-fin-insites.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @ShivamPandey-msft
* Microsoft Alias: **shpandey**

**Comment by bishalgoswami** [comment]
Bug 746872 has been logged to address this issue.

**Comment by alexeiantao** [comment]
During the installation of the Finance Insights Add-In, the Managed Data Lake is automatically deployed along with any other required applications/microservices. There is no requirement to independently install any other application to run Finance Insights. The anomaly experienced in this situation was not because a step was missed in the setup process.
