### ISSUE TITLE
Expired certificate 2021.12

### ISSUE THREAD

**Issue by d3fr0g** [MicrosoftDocs/dynamics-365-unified-operations-public#4156]
![image](https://user-images.githubusercontent.com/11015743/188859701-7fb797d4-6c90-4ef7-b220-92082e0185c8.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da30cb1c-cdec-8d0a-92d4-cef0cd34ecc7
* Version Independent ID: bbdccbb0-c648-bdbb-3a59-eb2ec497ceec
* Content: [Finance and operations application documentation - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/)
* Content Source: [articles/fin-ops-core/fin-ops/index.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/index.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by d3fr0g** [comment]
I was coming from https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/performance-benchmark-software-development-toolkit-sdk-for-microsoft-dynamics-ax-2012
to https://ax.help.dynamics.com/en/wiki/performance-benchmark-software-development-toolkit-sdk-for-microsoft-dynamics-ax-2012/
which landed on the main page. So the root cause might be the invalid links.

**Comment by josaw1** [comment]
@d3fr0g do you have a specific question on an article? Thanks.

**Comment by d3fr0g** [comment]
no specific question. The link in the article was pointing to a site with
an expired certificate. It has been fixed.

**Comment by josaw1** [comment]
Thank you!
