### ISSUE TITLE
Purchase order prepayment functionality

### ISSUE THREAD

**Issue by brkyyldz** [MicrosoftDocs/dynamics-365-unified-operations-public#4162]
Hi,
Enabling purchase order prepayment functionality functionality is also for Russian localization. But it's not written on list.
When I search for the label "Use prepayment invoice" on Development environment it is only referenced to VendParameters UseVendAdvanceInvoice_RU  field.

![image](https://user-images.githubusercontent.com/67732989/189748884-d373e265-6d5f-4f9d-9b10-a8e55cba3e65.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53aade45-7eb6-5af4-6c85-a09b26908ff6
* Version Independent ID: 53aade45-7eb6-5af4-6c85-a09b26908ff6
* Content: [What's new or changed in Dynamics 365 Finance 10.0.28 (August 2022) - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/get-started/whats-new-changed-10-0-28#feedback)
* Content Source: [articles/finance/get-started/whats-new-changed-10-0-28.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/get-started/whats-new-changed-10-0-28.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **kfend**

**Comment by bishalgoswami** [comment]
Bug 747998 has been logged to address this issue.

**Comment by mrolecki** [comment]
@brkyyldz , Could you please be more specific what information in what's new is incorrect or insufficient? What do you expect to be changed? _RU suffix is often used for Eastern Europe shared functionality. Here, in your screenshot the parameter is for Russia, Czech Republic, Hungary, Estonia, Latvia, Lithuania and Poland. The article does not contain information about any countries\regions.

**Comment by kfend** [comment]
Closing as we haven't received clarification regarding the question. Please reopen if you have more information.
