### ISSUE TITLE
Public key does not match with private key zatca 

### ISSUE THREAD

**Issue by mohanmanakkal** [MicrosoftDocs/dynamics-365-unified-operations-public#4164]
[I had generated csr,ccsid but in production csid i got theerror "No cert in -in file 'PCSID.pem' matches private key
2C980000:error:05800074:x509 certificate routines:X509_check_private_key:key values mismatch:crypto\x509\x509_cmp.c:405:"]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e7e40bd-7c12-ce0d-16db-984430e2db4f
* Version Independent ID: 2e7e40bd-7c12-ce0d-16db-984430e2db4f
* Content: [Electronic invoicing onboarding in Saudi Arabia - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/e-invoicing-sa-onboarding?context=%2Fdynamics365%2Fcontext%2Ffinance)
* Content Source: [articles/finance/localizations/e-invoicing-sa-onboarding.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/e-invoicing-sa-onboarding.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @mrolecki
* Microsoft Alias: **mrolecki**

**Comment by bishalgoswami** [comment]
Bug 748103 has been logged to address this issue.

**Comment by mrolecki** [comment]
@bishalgoswami , it's not a comment to the article but issue that should be raised to support. how to contact the submitter to pass that information?

**Comment by mrolecki** [comment]
@mohanmanakkal , we are adding clarification in a new paragraph to the article (pasted below). it's to be followed after obtaining CCSID but prior PCSID. It might not be the exact reason of your issue so if it is not solved, please contact preview support team at d365einvoicesupport@microsoft.com .

### Compliance check

After obtaining Compliance CSID using the PowerShell script, ZATCA requires completion of certain compliance checks by submitting sample invoices. This step is a prerequisite for requesting a Production CSID.

Ensure that all types of sample invoices that were configured in the Certificate Signing Request (CSR) configuration file, are successfully submitted to ZATCA (refer Note for more information). Use the standard process for issuing electronic invoices. For more information, see [Issue electronic invoices in Finance and Supply Chain Management](e-invoicing-issuing-electronic-invoices-finance-supply-chain-management.md).

To do so, use the **"Saudi Arabian ZATCA compliance check (SA)"** feature in RCS and follow the steps mentioned under the Country Specific Configuration section of [Get Started with Electronic invoicing for Saudi Arabia](e-invoicing-sa-get-started.md) along with using of the obtained Compliance CSID.

Once compliance checks are successfully completed, the PowerShell script can be used to obtain Production CSID (refer on-boarding script).

> [!NOTE]
> If the document type (field: title) in the configuration file is set to "1000", then 3 sample invoices need to be submitted for the compliance check:
> 1. Standard Tax Invoice
> 2. Standard Debit Note
> 3. Standard Credit Note
> 
> If the document type (field: title) in the configuration file is set to "0100", then 3 sample invoices need to be submitted for the compliance check:
> 1. Simplified Tax Invoice
> 2. Simplified Debit Note
> 3. Simplified Credit Note
> 
> If is set to "1100", then all 6 sample invoices need to be submitted for the compliance check.

**Comment by bishalgoswami** [comment]
Bug 748185 has been logged to address this issue.

**Comment by mrolecki** [comment]
@mohanmanakkal , please take a look into the article. Your error is expected when you use Sanbox API when onboarding for production. It's described in the article in a comment- see below. As written in other comment, you have to update URL(s) to Zatca production one when onboarding for prod.


        # Sandbox API will get error: openssl : No certificate matches private key
        openssl pkcs12 -inkey privatekey.pem -in PCSID.pem -export -passout pass:$password -out PCSID.pfx

**Comment by mohanmanakkal** [comment]
@mrolecki , Thank you for your response, The signing process will work only in production environment ,right?

**Comment by mohanmanakkal** [comment]
@mrolecki ,ok thank you ,then clerarence and reporting api also works with CCSID?

**Comment by mohanmanakkal** [comment]
@mrolecki , I cannot sign the B2C invoices with CCSID, is there any other options?

**Comment by mrolecki** [comment]
@mohanmanakkal   Clearance should work. The reporting API is not available yet - https://learn.microsoft.com/en-us/dynamics365-release-plan/2022wave2/commerce/dynamics365-commerce/saudi-arabia-simplified-e-invoice-integration-retail-stores .
As this conversation does seem to lead to any further adjustment to the article, to get answers to your questions please better contact preview support team at [d365einvoicesupport@microsoft.com](mailto:d365einvoicesupport@microsoft.com) or make a post at https://www.yammer.com/dynamicsaxfeedbackprograms/#/threads/inGroup?type=in_group&feedId=109360488448&view=all .
