### ISSUE TITLE
I believe the sentence logic is incorrect for extensions

### ISSUE THREAD

**Issue by scott-tucker** [MicrosoftDocs/dynamics-365-unified-operations-public#4167]
### Current text in docs article: 
Extension packages must be compiled against **the same version as, or a newer version than, the target component** that the extension applies to.

For example, if the deployed **Commerce Scale Unit is on version 10.0.27, the corresponding extension packages must be compiled against version 10.0.27 or earlier** (for example, 10.0.26 or 10.0.25).

### My comment:
It is my experience that when talking about software versioning 'earlier' and 'newer' go in opposite directions in time. Earlier means a version before the subject version and Newer means a version after the subject version.

-scott  scotttuc@microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48746126-f146-6c6d-d8da-307f819896c6
* Version Independent ID: 73cdd013-3569-b678-26f3-75679d84e4f6
* Content: [Dynamics 365 Commerce component versioning requirements - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/arch-component-versioning)
* Content Source: [articles/commerce/arch-component-versioning.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/arch-component-versioning.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @Reza-Assadi
* Microsoft Alias: **rassadi**

**Comment by josaw1** [comment]
Thanks, @scott-tucker. I'll fix this right away.
