### ISSUE TITLE
Link not working on Provision Human Resources in the stand-alone infrastructure updates process page

### ISSUE THREAD

**Issue by DarrenIPH** [MicrosoftDocs/dynamics-365-unified-operations-public#4168]
Hi,

I've just noticed that one of the links on this page - https://docs.microsoft.com/en-us/dynamics365/human-resources/hr-admin-setup-update-process does not work.

The link (https://docs.microsoft.com/en-us/hr-admin-setup-provision-fo.md) returns a 404 error

Thought you might like to fix it up.

Darren
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb22daa0-dab6-d65d-43be-16f7953d6de8
* Version Independent ID: 3bda9eb1-c794-320a-c7e2-bb8a1b387a69
* Content: [Update process - Human Resources | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/human-resources/hr-admin-setup-update-process)
* Content Source: [articles/human-resources/hr-admin-setup-update-process.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/human-resources/hr-admin-setup-update-process.md)
* Service: **dynamics-365-human-resources**
* Product: ****
* Technology: ****
* GitHub Login: @twheeloc
* Microsoft Alias: **twheeloc**

**Comment by twheeloc** [comment]
@DarrenIPH, thank you for the information. The updated link will be live later today.
