### ISSUE TITLE
docs on Product comparison preview panel is missing

### ISSUE THREAD

**Issue by kurthatlevik-inspirit365** [MicrosoftDocs/dynamics-365-unified-operations-public#4171]
I think there are some missing documentation on the Product comparison preview panel that also needs to be added to this documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc5cd112-fa3d-65cb-0f7f-ccb46ea61c95
* Version Independent ID: dc5cd112-fa3d-65cb-0f7f-ccb46ea61c95
* Content: [Product comparison modules - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/product-comparison-modules)
* Content Source: [articles/commerce/product-comparison-modules.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/product-comparison-modules.md)
* Service: **dynamics-365-commerce**
* GitHub Login: @ashishmsft
* Microsoft Alias: **asharchw**

**Comment by bishalgoswami** [comment]
Bug 751247 has been logged to address this issue.

**Comment by josaw1** [comment]
This section has been added. Thanks.
