### ISSUE TITLE
Add logo company on ER

### ISSUE THREAD

**Issue by vereden** [MicrosoftDocs/dynamics-365-unified-operations-public#4172]
I follow the step on  "Design an ER format to generate a report in Excel format with embedded images in page headers or footers"
section "Edit the custom format"

I can't find :  10.
![Find company logo data source](https://user-images.githubusercontent.com/113829055/190896727-06836a4a-b9b9-4ff7-bf4b-51d3d59f597a.jpg)
![Find company logo data source](https://user-images.githubusercontent.com/113829055/190896744-25e30fbd-ed9f-4b18-b5db-18409c12427a.jpg)
Expand model.Payment > model.InvoiceBase > model.InvoiceBase.CompanyInfo, and then select the model.InvoiceBase.CompanyInfo.Logo data source field. The data source field of the [Container](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/er-formula-supported-data-types-composite#container) type exposes the company logo image as media content.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75e888e6-7cac-ee1d-700f-8b60ada6fc65
* Version Independent ID: 1a67e9ce-939f-9ab8-00c0-05b5879b7d60
* Content: [Design an ER format to generate a report in Excel format with embedded images in page headers or footers - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/er-embed-images-header-footer-excel-reports)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/er-embed-images-header-footer-excel-reports.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/analytics/er-embed-images-header-footer-excel-reports.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **filatovm**

**Comment by bishalgoswami** [comment]
Bug 751246 has been logged to address this issue.

**Comment by NickSelin** [comment]
Hello [vereden](https://github.com/vereden),
The improper state of the view mode can cause the issue that has been described in the defect [751246](https://fix.lcs.dynamics.com/Issue/Details/?bugId=751246&dbType=3).  Please, make sure that the view mode of the Electronic reporting (ER) designer is set to the state **Show all**. Notice that when it is set to the state **Show mapped only**, any data source field that is not bound yet to a format element is hidden on the **Mapping** tab.
Best regards,
Nick Selin
