### ISSUE TITLE
Remove unnecessary A tag in section "What are the planned maintenance windows?".

### ISSUE THREAD

**Issue by DKobayashi-ykgw** [MicrosoftDocs/dynamics-365-unified-operations-public#4176]
Please Remove unnecessary A tag in section "What are the planned maintenance windows?".
\#\# \<a name="windows"\>\</name\>What are the planned maintenance windows?
should be
\#\# What are the planned maintenance windows?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1fcc1802-115b-4ac2-f34f-aa73eac426f4
* Version Independent ID: d758bfc6-245e-43d6-8bde-31282cea0a64
* Content: [Maintenance in self-service environments FAQ - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/plannedmaintenance-selfservice#what-are-the-planned-maintenance-windows)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/plannedmaintenance-selfservice.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/deployment/plannedmaintenance-selfservice.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @matapg007
* Microsoft Alias: **matgupta**

**Comment by bishalgoswami** [comment]
Bug 751243 has been logged to address this issue.

**Comment by johnmichalak** [comment]
Marked as resolved by PM.
