### ISSUE TITLE
Issue in the title 

### ISSUE THREAD

**Issue by OlgaPetrovaFT** [MicrosoftDocs/dynamics-365-unified-operations-public#4177]
I believe we should fix the title to say "finance and operations app" as otherwise title is missing HR and Project Ops which are also in this mix
 This link explains what is the right way to call all FO apps https://styleguides.azurewebsites.net/StyleGuide/Read?id=2696&topicid=48217

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d2fd431-c11f-d562-e81e-c41ee7987720
* Version Independent ID: 2d2fd431-c11f-d562-e81e-c41ee7987720
* Content: [Dynamics 365 Finance, Supply Chain Management, and Commerce in local geographies - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-gb/dynamics365/fin-ops-core/dev-itpro/deployment/deployment-options-geo)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/deployment-options-geo.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/deployment/deployment-options-geo.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @Shailesh4all
* Microsoft Alias: **shailesn**

**Comment by bishalgoswami** [comment]
Bug 751242 has been logged to address this issue.
