### ISSUE TITLE
Credit Card Security details

### ISSUE THREAD

**Issue by thinkmax-sgilbert** [MicrosoftDocs/dynamics-365-unified-operations-public#4179]
Please add a comment on credit card number security to this document.  I hope the credit card number is not actually stored anywhere in D365.  When we add a credit card number it appears only the last 4 digits are recorded along with a card token which I assume is provided by the CreditCardProcessor.  Then it is only the token that is used on future transactions to get authorizations?  Does that Cardtoken ever expire?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6ff48b0d-bf91-e425-3dfd-cb39f4706d71
* Version Independent ID: 57a2fc80-30fb-cbc2-de15-e486ef760fdf
* Content: [Credit card setup, authorization, and capture - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/accounts-receivable/credit-card-authorizations)
* Content Source: [articles/finance/accounts-receivable/credit-card-authorizations.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/accounts-receivable/credit-card-authorizations.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @ShivamPandey-msft
* Microsoft Alias: **shpandey**

**Comment by bishalgoswami** [comment]
Bug 751520 has been logged to address this issue.

**Comment by sericks007** [comment]
@ShivamPandeyMSFT, please update the content to address this feedback.

**Comment by angelad116** [comment]
@thinkmax-sgilbert Hello, there are 2 kinds of token. One is card on file, this is about saving a credit card information, which will be kept for a long time. Another one is authorization token, which is for certain transaction, and will expire after transaction completed. For credit card itself, D365 persist the encrypted information, it's a long-term token, and for each transaction, the auth-token will be expired, usually set as 7days of window for authorization-capture.

**Comment by johnmichalak** [comment]
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.
