### ISSUE TITLE
Issue: Module reportingservices failed with error code -532462766.

### ISSUE THREAD

**Issue by noetico** [MicrosoftDocs/dynamics-365-unified-operations-public#4180]
While installing Dynamics Finance and Operations I Have this error. Please kindly clarify what this error code represents and how to resolve. All service fabric VMs are good and SF has no warnings, retrying the deployment neatly cleans installed applications, restarts and fails at this point.

**Comment by twheeloc** [comment]
@noetico,  thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options]https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
