### ISSUE TITLE
Component Dependencies - Service Updates - Poor English

### ISSUE THREAD

**Issue by segibson77** [MicrosoftDocs/dynamics-365-unified-operations-public#4183]
Hi,

I believe that the English on the Service Updates section in the Component Dependencies section is incorrect. 
I think the wording is actually the wrong way round compared to the examples given

**Current sentence and example**
Commerce headquarters and finance and operations apps must be on the same version as, or an earlier version than, Commerce Scale Unit (both cloud and self-hosted).

For example, if Commerce headquarters and finance and operations apps are on version 10.0.29, Commerce Scale Unit must be on version 10.0.29 or earlier (for example, 10.0.28 or 10.0.27).

**Potential Correction ** 
If the logic is that F&O must be on the same or _higher_ version that CSU (i.e., F&O version >= CSU) then the English should be:

"Commerce headquarters and finance and operations apps must be on the same or newer version than the Commerce Scale Unit (both cloud and self-hosted).

_could use later rather than higher_

**Second Current sentence and example**
Commerce Scale Unit must be on the same version as, or an earlier version than, Modern Point of Sale (POS), Hardware Station, and the Commerce software development kit (SDK) and associated local site configurations (such as modules, data actions, and themes).

For example, if Commerce Scale Unit is on version 10.0.29, Modern POS, Hardware Station, and the Commerce storefront must be on version 10.0.29 or earlier (for example, 10.0.28 or 10.0.27).

**Potential Correction 2** 

If the logic is that CSU must be on the same or _higher_ version than MPOS, Hardware Station, SDK (i.e., CSU >= MPOS, Hardware Station, SDK) then the English should be:

"Commerce Scale Unit must be on the same or a newer version than Modern Point of Sale (POS), Hardware Station, and the Commerce software development kit (SDK) and associated local site configurations (such as modules, data actions, and themes)."

_could use later rather than higher_

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 48746126-f146-6c6d-d8da-307f819896c6
* Version Independent ID: 73cdd013-3569-b678-26f3-75679d84e4f6
* Content: [Dynamics 365 Commerce component versioning requirements - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/arch-component-versioning#current-supported-versions)
* Content Source: [articles/commerce/arch-component-versioning.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/arch-component-versioning.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @Reza-Assadi
* Microsoft Alias: **rassadi**

**Comment by bishalgoswami** [comment]
Bug 751968 has been logged to address this issue.

**Comment by josaw1** [comment]
Thank you for your feedback. @scott-tucker can you please review the wording in the topic?

**Comment by scott-tucker** [comment]
@josaw1, am I reviewing the wording in the comment from segibson77?  If so, then both potential corrections sound good to me.  Jarad owns deployment now, I'm not sure who owns the SDK now. When I view the content source it is still the original. That's why I am assuming I should review the comment.

Potential Correction 1

"Commerce headquarters and finance and operations apps must be on the same or newer version than the Commerce Scale Unit (both cloud and self-hosted)."

Potential Correction 2

"Commerce Scale Unit must be on the same or a newer version than Modern Point of Sale (POS), Hardware Station, and the Commerce software development kit (SDK) and associated local site configurations (such as modules, data actions, and themes)."

**Comment by josaw1** [comment]
The corrections were made and will be published shortly.
