### ISSUE TITLE
www.gotlkhat.com

### ISSUE THREAD

**Issue by hussein2500** [MicrosoftDocs/dynamics-365-unified-operations-public#4184]
[اكتب ملاحظاتك هنا]

---
#### تفاصيل المستند

⚠ *تجنب تحرير هذا القسم. مطلوب لـ learn.microsoft.com ➟ ربط مشكلة GitHub.*

* ID: ecf89fb2-aa69-ab0c-441c-d74cfabfda54
* Version Independent ID: da576e84-86dd-c9a2-d336-2e4abd10c812
* Content: [إنشاء عنوان URL لصفحة - Commerce | Dynamics 365](https://learn.microsoft.com/ar-sa/dynamics365/commerce/create-page-url)
* Content Source: [articles/commerce/create-page-URL.md](https://github.com/MicrosoftDocs/Dynamics-365-Operations.ar-sa/blob/live/articles/commerce/create-page-URL.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @bicyclingfool
* Microsoft Alias: **StuHarg**

**Comment by hussein2500** [comment]
`مهكر مواقع ماليه `

**Comment by hussein2500** [comment]
تجرنت يعمل على نضام الوينديز ولا ندريود

**Comment by hussein2500** [comment]
يعمل على شكل 5 دقائق

**Comment by hussein2500** [comment]
- [5،9،4،7 ] القوائم

**Comment by bishalgoswami** [comment]
Bug 752013 has been logged to address this issue.

**Comment by josaw1** [comment]
Thank you for your feedback. @vinceno can you please take a look?

**Comment by vinceno** [comment]
@vivimills can you please work with LIOX to have this assessed/addressed - thx

**Comment by josaw1** [comment]
Closed as won't fix.
