### ISSUE TITLE
Missing features in What's new documentation

### ISSUE THREAD

**Issue by LindaJEriksen** [MicrosoftDocs/dynamics-365-unified-operations-public#4187]
When reviewing the documentation for What's new in D365 F&O we can see that a lot of features that are available in the Feature management section in D365 F&O is not listed in the documentation. For example feature "New vendor balance list report to reflect posting profile changes" is not explained/documented in the What's new for 10.0.28. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a81f2d2a-8eac-df73-bf48-2a59ad0ff5ac
* Version Independent ID: 26eb9087-c4d9-85e4-957c-9144269800ee
* Content: [What's new or changed in Dynamics 365 Finance - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/get-started/whats-new-home-page)
* Content Source: [articles/finance/get-started/whats-new-home-page.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/get-started/whats-new-home-page.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **kfend**

**Comment by bishalgoswami** [comment]
Bug 752363 has been logged to address this issue.

**Comment by raynezou** [comment]
Vendor balance list report enhancement to reflect posting profile changes
This feature enhances the existing vendor transaction table to persist the posted main accounts. Then Vendor balance list report can correctly reflect vendor balance after main accounts are changed in the vendor posting profile.

**Comment by kfend** [comment]
I have updated the What's new article with the new feature.
