### ISSUE TITLE
The application specific parameters setup need to be corrected

### ISSUE THREAD

**Issue by mkowalka** [MicrosoftDocs/dynamics-365-unified-operations-public#4189]
[Enter feedback here]
On the page , section: Set up application-specific parameters for formats there is point 5 with below: 

Lookup result | Tax code (Code) | Name
Other | *Not blank* | *Not blank*

Issue 1. Name column does not exist anymore, it changed to: Transaction classifier (TransactionClassifier)
Issue 2. If we set *not blank* in both columns, user is still getting an error about not matched condition. 
The last line should be 
Lookup result | Tax code (Code) | Name
Other | *Not blank* | (empty)

Also, I have noticed that description for other countries is different than for CZE. So, if these VAT declarations work the same for all countries - description should be consistent. 
Please check for Sweden or Finland:
SE: https://learn.microsoft.com/en-us/dynamics365/finance/localizations/emea-swe-vat-declaration-sweden#set-up-application-specific-parameters-for-vat-declaration-boxes 
FIN: https://learn.microsoft.com/en-us/dynamics365/finance/localizations/emea-fin-vat-declaration#set-up
 

BR, 
Monika
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2825361e-b3da-9b9d-16f2-90974b964d36
* Version Independent ID: d80229a2-8acc-ef01-4155-4f50b6bfe9dc
* Content: [VAT declaration (Czech Republic) - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/localizations/emea-cze-vat-declaration-tax-declaration-model)
* Content Source: [articles/finance/localizations/emea-cze-vat-declaration-tax-declaration-model.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/emea-cze-vat-declaration-tax-declaration-model.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @AdamTrukawka
* Microsoft Alias: **atrukawk**

**Comment by bishalgoswami** [comment]
Bug 752385 has been logged to address this issue.

**Comment by johnmichalak** [comment]
Thank you for the suggestions, they have been noted and will be considered for possible inclusion in the future.
