### ISSUE TITLE
Clarification on Consolidation date under Currency translation

### ISSUE THREAD

**Issue by ErikJohnMSFT** [MicrosoftDocs/dynamics-365-unified-operations-public#4192]
[Enter feedback here]
 for the "Currency translation" section on bullet point "Consolidation date" it would be nice if it mentioned that the consolidation date that would be used is the "To" date on the Criteria | Consolidation period.

Erik Johnson
MSFT
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f1a05511-997d-1077-3a59-c73dea38960c
* Version Independent ID: 5a024b81-d0cb-ff92-36e9-adc507f15791
* Content: [Online financial consolidations - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/general-ledger/consolidate-online?source=docs#currency-translation)
* Content Source: [articles/finance/general-ledger/consolidate-online.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/general-ledger/consolidate-online.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @aprilolson
* Microsoft Alias: **aolson**

**Comment by bishalgoswami** [comment]
Bug 752406 has been logged to address this issue.

**Comment by twheeloc** [comment]
@ErikJohnMSFT, thank you for the feedback. The topic has been updated.
