### ISSUE TITLE
Store Commerce app availability means the Note needs an update

### ISSUE THREAD

**Issue by finopsfuntimes** [MicrosoftDocs/dynamics-365-unified-operations-public#4194]
There is currently a note on this page:
"It is critical to note that Commerce Scale Unit (self-hosted) does not replace offline. Currently, Retail Modern POS with an offline database is the **only way** to have offline capabilities."

I believe this needs to be updated now that the Store Commerce app is available, as that also supports offline capabilities if configured for it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b3904172-4dc3-3602-05a6-6bc0fcd1c7e3
* Version Independent ID: 2eaac493-f165-5f34-8d05-e441e741a8b8
* Content: [Commerce Scale Unit (self-hosted) - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/dev-itpro/retail-store-system-begin)
* Content Source: [articles/commerce/dev-itpro/retail-store-system-begin.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/retail-store-system-begin.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by bishalgoswami** [comment]
Bug 752904 has been logged to address this issue.

**Comment by josaw1** [comment]
@anupamar-ms please take a look. Thanks.

**Comment by bicyclingfool** [comment]
The blurb about offline needs to be updated as follows:

It is critical to note that Commerce Scale Unit (self-hosted) does not replace offline. Currently, the point of sale apps for Windows (Retail Modern POS or Store Commerce App) with an offline database is the only way to have offline capabilities.

There was no associated bug - I created the following CD for tracking: https://msdyneng.visualstudio.com/FinOps/_workitems/edit/759447
