### ISSUE TITLE
No longer in preview

### ISSUE THREAD

**Issue by MichaelFruergaardPontoppidan** [MicrosoftDocs/dynamics-365-unified-operations-public#4195]
This feature GAed in 10.0.25 - please remove:

"Some or all of the functionality noted in this article is available as part of a preview release. The content and the functionality are subject to change. For more information about preview releases, see [Service update availability](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/public-preview-releases)."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2f09e8fa-e5dc-2e5d-3613-c6b4f6d7191a
* Version Independent ID: 2f09e8fa-e5dc-2e5d-3613-c6b4f6d7191a
* Content: [Run custom X++ scripts with zero downtime - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/run-custom-scripts)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/run-custom-scripts.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/deployment/run-custom-scripts.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @AndersGirke
* Microsoft Alias: **aevengir**

**Comment by bishalgoswami** [comment]
Bug 753106 has been logged to address this issue.

**Comment by kamaybac** [comment]
Fixed.
