### ISSUE TITLE
Payment id setup

### ISSUE THREAD

**Issue by TimoTenni** [MicrosoftDocs/dynamics-365-unified-operations-public#4198]
Please add following link to this page:
https://learn.microsoft.com/en-us/dynamics365/finance/localizations/tasks/no-00002-customer-payment-based-payment-id

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 66477445-de96-fff2-7543-a6e14a39c7da
* Version Independent ID: b0c1985d-1d8f-78b1-d08d-ea6aa645a101
* Content: [Payment slip report for Europe - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/localizations/emea-eur-payment-slip-report-giro)
* Content Source: [articles/finance/localizations/emea-eur-payment-slip-report-giro.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/emea-eur-payment-slip-report-giro.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @EvgenyPopovMBS
* Microsoft Alias: **epopov**

**Comment by EvgenyPopovMBS** [comment]
@mrolecki could you please look at this?

**Comment by bishalgoswami** [comment]
Bug 753176 has been logged to address this issue.

**Comment by mrolecki** [comment]
Added information to https://msdyneng.visualstudio.com/FinOps/_workitems/edit/753176

**Comment by kfend** [comment]
I have added the link to the article. Changes will go live later today.
