### ISSUE TITLE
Please add important feature on this page

### ISSUE THREAD

**Issue by TimoTenni** [MicrosoftDocs/dynamics-365-unified-operations-public#4199]
Link to the payment id setup now available also for Finland
https://learn.microsoft.com/en-us/dynamics365/finance/localizations/tasks/no-00002-customer-payment-based-payment-id

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0e5d1e20-e075-7ccd-8a95-3fa96aeac13c
* Version Independent ID: 65293808-0bd6-255d-360b-adf92fbd9d73
* Content: [Finland overview - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/localizations/finland)
* Content Source: [articles/finance/localizations/finland.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/finland.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **kfend**

**Comment by bishalgoswami** [comment]
Bug 753175 has been logged to address this issue.

**Comment by johnmichalak** [comment]
Thank you for the suggestions, they have been noted and will be considered for possible inclusion in the future.
