### ISSUE TITLE
I believe the outbound IP addresses for Self Service tier2+ AOS in West Europe are incorrect.

### ISSUE THREAD

**Issue by jespernohr** [MicrosoftDocs/dynamics-365-unified-operations-public#4200]
I believe the outbound IP addresses for Self Service tier2+ AOS in West Europe are incorrect.

We have used these IP ranges in our azure storage account firewall whitelist, but connections are not being allowed.
Europe | North Europe | 52.155.160.192/26
Europe | West Europe | 20.61.88.128/26 , 51.105.159.192/26
![Screenshot 2022-09-30 111659](https://user-images.githubusercontent.com/11901812/193237499-89cccd2a-52c7-4180-92b4-09d9fd146be7.png)
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 98ef3846-e354-a28e-c904-3ea201f7ad3b
* Version Independent ID: 548d4b90-e614-d0c9-8faa-90df3c80d1c6
* Content: [Self-service deployment FAQ - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/deploymentfaq#for-my-microsoft-managed-environments-i-have-external-components-that-have-dependencies-on-an-explicit-outbound-ip-safe-list-how-can-i-ensure-my-service-is-not-impacted-after-the-move-to-self-service-deployment)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/deploymentFAQ.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/deployment/deploymentFAQ.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @rashmansur
* Microsoft Alias: **rashmim**

**Comment by bishalgoswami** [comment]
Bug 754630 has been logged to address this issue.
