### ISSUE TITLE
English translation of the SWE VAT report example

### ISSUE THREAD

**Issue by RalucaLucia** [MicrosoftDocs/dynamics-365-unified-operations-public#4203]
[Enter feedback here]
On the page section: Report VAT declaration to the Tax authority
- could you please add the English translation for all the fields in the report?
![image](https://user-images.githubusercontent.com/114916397/193574064-058f8202-c352-4f06-a0e5-52e6b355b663.png)
![image](https://user-images.githubusercontent.com/114916397/193574147-df2421bf-ea83-453a-a538-edf71b08faf3.png)
thank you.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6892225e-76a8-be68-7fb6-1f41dd8d4c95
* Version Independent ID: 6abeb12f-700e-1746-35c9-cc4a72d7166c
* Content: [Sales tax report for Sweden - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/localizations/emea-swe-sales-tax-payment-report-sweden)
* Content Source: [articles/finance/localizations/emea-swe-sales-tax-payment-report-sweden.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/emea-swe-sales-tax-payment-report-sweden.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @AdamTrukawka
* Microsoft Alias: **atrukawk**

**Comment by bishalgoswami** [comment]
Bug 754629 has been logged to address this issue.

**Comment by johnmichalak** [comment]
Thank you for the suggestions, they have been noted and will be considered for possible inclusion in the future.
