### ISSUE TITLE
Explanation of the Lookup results logic

### ISSUE THREAD

**Issue by RalucaLucia** [MicrosoftDocs/dynamics-365-unified-operations-public#4204]
[Enter feedback here]
On the page section: VAT declaration overview
Could you please explain the logic of the values in the parenthesis means (The figures added in the lookups, the name of the values of the boxes)? 
Example 5/10 - means the amount should appear in the VAT report under the box 5 and 10. 
box 5- the entire transaction amount
box 10- the vat paid by the company

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0245c952-f236-ba60-5f24-d2b829b97c0d
* Version Independent ID: 6054964f-4c7a-ac48-92c6-35be838bc76b
* Content: [VAT declaration (Sweden) - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/localizations/emea-swe-vat-declaration-sweden)
* Content Source: [articles/finance/localizations/emea-swe-VAT-declaration-Sweden.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/emea-swe-VAT-declaration-Sweden.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @AdamTrukawka
* Microsoft Alias: **atrukawk**

**Comment by bishalgoswami** [comment]
Bug 754628 has been logged to address this issue.

**Comment by johnmichalak** [comment]
Thank you for the suggestions, they have been noted and will be considered for possible inclusion in the future.
