### ISSUE TITLE
Small text update - missing "> Setup"

### ISSUE THREAD

**Issue by Halldor10** [MicrosoftDocs/dynamics-365-unified-operations-public#4206]
The text is:  "2. Go to System administration > Operational Insights."

The text should be : "2. Go to System administration > Setup >Operational Insights."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1ea563b0-eb9c-bc38-f17a-f24913eb426f
* Version Independent ID: 1f9c1430-a53c-9a63-77fe-dc4b44b7c3a7
* Content: [Commerce component events for diagnostics and troubleshooting - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/dev-itpro/retail-component-events-diagnostics-troubleshooting#enable-diagnostic-events-in-application-insights)
* Content Source: [articles/commerce/dev-itpro/retail-component-events-diagnostics-troubleshooting.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/retail-component-events-diagnostics-troubleshooting.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @ShalabhjainMSFT
* Microsoft Alias: **shajain**

**Comment by bishalgoswami** [comment]
Bug 754626 has been logged to address this issue.

**Comment by ShalabhjainMSFT** [comment]
This should likely be assigned to Jarad Shannon.

**Comment by bishalgoswami** [comment]
Bug 757246 has been logged to address this issue.

**Comment by josaw1** [comment]
This update will be published today. Thank you.
