### ISSUE TITLE
How to make sales return policy with expiry date?

### ISSUE THREAD

**Issue by liamneesangamer** [MicrosoftDocs/dynamics-365-unified-operations-public#4210]
Is it possible to make return policy that the product can return within number of days?.

For example, some department product are allowed to return in 7 days. not allowed to return more than 7 days.
There are some other department (Dairy department) are allowed to return in 1 day. so not to allow to return more than 1 days

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e2fd324f-8636-61a3-0acb-5f533da93d5c
* Version Independent ID: ff6b4fbd-536c-f514-2848-928d914f1e97
* Content: [Create and update a returns and refunds policy for a channel - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/refund_policy_returns)
* Content Source: [articles/commerce/refund_policy_returns.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/refund_policy_returns.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @ShalabhjainMSFT
* Microsoft Alias: **shajain**

**Comment by bishalgoswami** [comment]
Bug 756035 has been logged to address this issue.

**Comment by josaw1** [comment]
@ShalabhjainMSFT can you please take a look?

**Comment by ShalabhjainMSFT** [comment]
This is a functional clarification ask vs a content change request. To answer the question - No, we do not have a way to configure the return window for items. This needs to be manually controlled by the cashier processing the returns.
