### ISSUE TITLE
Leave & Absence "Feature" settings

### ISSUE THREAD

**Issue by mpburtt** [MicrosoftDocs/dynamics-365-unified-operations-public#4213]
This page refers to Leave & Absence being a preview feature until 10.0.26 - this is now GA. Even with 10.0.26, in order to access the Leave & Absence module in F&SCM Features need to be enabled but I cannot find a list of features that specifically must be enabled to allow access to this module as, unhelpfully, there is no Feature called "Leave & Absence". This page really needs to list the prerequisite features that must be enabled in order to use the Leave & Absence module.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 85a778ff-621e-f49b-5668-b6940e76d9ed
* Version Independent ID: bb81615d-871a-a7a8-4a69-8c5f2664e09a
* Content: [Configure leave and absence parameters - Human Resources | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/human-resources/hr-leave-and-absence-parameters)
* Content Source: [articles/human-resources/hr-leave-and-absence-parameters.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/human-resources/hr-leave-and-absence-parameters.md)
* Service: **dynamics-365-human-resources**
* Product: ****
* Technology: ****
* GitHub Login: @twheeloc
* Microsoft Alias: **twheeloc**

**Comment by bishalgoswami** [comment]
Bug 756620 has been logged to address this issue.

**Comment by twheeloc** [comment]
@mpburtt, thank you for the feedback. You can find additional information about leave and absence features here: [What's new](https://learn.microsoft.com/en-us/dynamics365/human-resources/get-started/hr-whats-new-changed-10-0-32).
