### ISSUE TITLE
How to prevent to return at pos on partial discounted/Promotion/Quantity break?

### ISSUE THREAD

**Issue by liamneesangamer** [MicrosoftDocs/dynamics-365-unified-operations-public#4215]
For example, 

Case 1:
      Customer can **buy product X at 5$**, **Buy 5 quantity of x product at 3$**, Incase customer bought 5 quantity at each 3$ by quantity break, so when customer wants to return 4 quantity, POS should not allow to return the 4 quantity, instead system should allow to return 5 quantity only.

Case 2:
     If customer bought buy 2 get 1 free on promotion, POS should not allow to return that 2 product which customer paid early and walk away with free goods.

**Any promotion/discounted/quantity break must not allowed to return partially, either allowed to return complete promotion/discounted/quantity break or NOT ALLOWED to return LOGICALLY**

How can to prevent those cases in Dynamics 365 commerce?.
 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 446bde34-336d-f791-b24f-c5b13f0ed685
* Version Independent ID: 2f358f3a-acdd-e710-beef-24e19d154617
* Content: [Retail discounts - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/retail-discounts-overview)
* Content Source: [articles/commerce/retail-discounts-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/retail-discounts-overview.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @ShalabhjainMSFT
* Microsoft Alias: **shajain**

**Comment by bishalgoswami** [comment]
Bug 756904 has been logged to address this issue.

**Comment by Adrian-Zhang** [comment]
This would need to be achieved via customization, as majority of users prefer not to have such constraints. Each CartLine has DiscountLines object which contains info of discounts applied to the line. One possible approach is for user to customize RecallSalesInvoiceRequest to prevent partial recalling.
