### ISSUE TITLE
Information how SysSetup is actually called is missing

### ISSUE THREAD

**Issue by torbennehmer** [MicrosoftDocs/dynamics-365-unified-operations-public#4218]
Please add a chapter about how this infrastructure is invoked. It took me a while to realize, that normal VS DB Sync on Dev VMs don't kick in. The actual important point is moving to Microsoft.Dynamics.AX.Deployment.Setup.exe as outlined in the last post in the community: 

https://community.dynamics.com/365/financeandoperations/f/dynamics-365-for-finance-and-operations-forum/450253/how-to-move-existing-methods-subscribed-to-by-the-ondbsynchronize-event-to-a-syssetup-extended-class

The interesting part is the reply from Víðir Reyr Björgvinssonresponded on 19 Aug 2022 2:46 AM

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 55927241-9d0d-19f8-3e5a-a81184d387e6
* Version Independent ID: 55927241-9d0d-19f8-3e5a-a81184d387e6
* Content: [SysSetupConfigAttribute attribute - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/syssetupconfigattribute)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/syssetupconfigattribute.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/dev-tools/syssetupconfigattribute.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @josaw1
* Microsoft Alias: **najaidee**

**Comment by bishalgoswami** [comment]
Bug 758102 has been logged to address this issue.

**Comment by johnmichalak** [comment]
These docs were updated.
