### ISSUE TITLE
Document routing client can't access agent installation links

### ISSUE THREAD

**Issue by SteveBurkettNZ** [MicrosoftDocs/dynamics-365-unified-operations-public#422]
"Yes. To access the agent installation links, the user must be part of the Document routing client security role."

This statement in the FAQs appears to be inaccurate. If you only have the Document Routing Client security role assigned, you can see the Organisation administration view but with only really limited submenus, the Network printers submenu not being one of them. Hence you can't get to the download link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2128b07d-7349-6642-f05f-c94fe800d104
* Version Independent ID: 0568d0d1-8035-3423-f791-7bd82a5d070f
* Content: [Install the Document Routing Agent to enable network printing - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/install-document-routing-agent)
* Content Source: [articles/dev-itpro/analytics/install-document-routing-agent.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/install-document-routing-agent.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by SteveBurkettNZ** [comment]
Also applicable to the **Verify security roles** point in the **Troubleshooting tips** section on the [Run the Document Routing Agent as a Windows service](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/run-document-routing-agent-as-windows-service?toc=/fin-and-ops/toc.json#verify-security-roles) page.

**Comment by gasimon** [comment]
Checking the GitHub page, there is no progress in solving this bug. Any idea when this will be fixed? Having a service account assigned as "Information Technology manager" just to register printers and manage them is much more than really required (and far away from a good practice).

Thank you,
Gus

**Comment by TJVass** [comment]
Thanks, Steve. 
Correct, the Document routing client role is one of the security roles required to manage service access to network printer devices.

**Comment by SteveBurkettNZ** [comment]
Hi TJVass, the point I was trying to make is that the Document Routing Client role does not have rights to view the Network Printers menu, and cannot be used to download the DRA agent. Hence the statement in the FAQ is incorrect. Typically (third-party) IT support staff will have access to the DRA service account credentials (with the Document Routing client role assigned) as they install the DRA on the servers they manage, with that they do not have access to the right pages on the D365FO portal to be able to download the installer.

**Comment by TJVass** [comment]
Point taken.  Users need appropriate permissions to access the Network printers menu before getting access to the DRA installation links.
