### ISSUE TITLE
New ER format for Advanced bank reconciliation

### ISSUE THREAD

**Issue by Anmadu** [MicrosoftDocs/dynamics-365-unified-operations-public#4221]
Hi All,

Please consider updating the docs related to Advanced bank reconciliation as the model, model mapping and format has changed from Bank statement model to Advanced bank reconciliation statement model for all 3 valid formats BAI2, MT940 and ISO20022.
In ER the formats are now available as follows:

![image](https://user-images.githubusercontent.com/78029965/195521870-11b6e7fd-f8a9-4988-b13b-71ea26c5ad11.png)

Bank statement model should not be used any longer.

Thank you!

Kind Regards,
Anke

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 33ed78e0-bbee-3178-b448-2d86790f20bf
* Version Independent ID: 33ed78e0-bbee-3178-b448-2d86790f20bf
* Content: [Set up advanced bank reconciliation import by using Electronic reporting - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/accounts-payable/import-bai2-er#set-up-the-electronic-reporting-configuration)
* Content Source: [articles/finance/accounts-payable/import-BAI2-ER.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/accounts-payable/import-BAI2-ER.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @angelad116
* Microsoft Alias: **shpandey**

**Comment by bishalgoswami** [comment]
Bug 758100 has been logged to address this issue.

**Comment by angelad116** [comment]
@Anmadu Hello, we will update external document about this part
