### ISSUE TITLE
display row and column header on multiple page on electronic reporting excel designer

### ISSUE THREAD

**Issue by vereden** [MicrosoftDocs/dynamics-365-unified-operations-public#4227]
I try to present  row and column header on  report which contain multiple page
the line table is cut off on the next page and the header didn't appear

![Cutting lines on next page](https://user-images.githubusercontent.com/113829055/196359372-ec691864-be04-4752-bed0-3ba67bac1f77.jpg)

**Comment by twheeloc** [comment]
@vereden, thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
