### ISSUE TITLE
Add Store Commerce App system requirements to the page

### ISSUE THREAD

**Issue by 5fq** [MicrosoftDocs/dynamics-365-unified-operations-public#4230]
It will be good add Store Commerce App requirements to this page so that all information for commerce components are available in one page.

https://learn.microsoft.com/en-us/dynamics365/commerce/dev-itpro/store-commerce#setup-and-installation 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 043a7336-3d71-14f2-9856-05e03e24cd80
* Version Independent ID: 60414540-f243-27e6-0494-28c4af78e0a4
* Content: [System requirements for cloud deployments of Dynamics 365 Commerce - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/get-started/system-requirements)
* Content Source: [articles/commerce/get-started/system-requirements.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/get-started/system-requirements.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @jashanno
* Microsoft Alias: **jashanno**

**Comment by bishalgoswami** [comment]
Bug 759154 has been logged to address this issue.

**Comment by josaw1** [comment]
This update will be published today. Thanks.
