### ISSUE TITLE
Store Commerce App reference missing

### ISSUE THREAD

**Issue by 5fq** [MicrosoftDocs/dynamics-365-unified-operations-public#4231]
Store Commerce App is completely missing in the article. With all customers moving to Store Commerce App from MPOS, version requirements for Commerce app is not available anywhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 48746126-f146-6c6d-d8da-307f819896c6
* Version Independent ID: 73cdd013-3569-b678-26f3-75679d84e4f6
* Content: [Dynamics 365 Commerce component versioning requirements - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/arch-component-versioning)
* Content Source: [articles/commerce/arch-component-versioning.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/arch-component-versioning.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @Reza-Assadi
* Microsoft Alias: **rassadi**

**Comment by bishalgoswami** [comment]
Bug 759153 has been logged to address this issue.

**Comment by bicyclingfool** [comment]
Please update the bullet that mentions MPOS to read as follows:

Commerce Scale Unit must be on the same version as, or a later version than the Store Commerce App and/or Modern Point of Sale (MPOS), Hardware Station, and the Commerce software development kit (SDK) and associated local site configurations (such as modules, data actions, and themes).

NOTE: This edit does not have an associated bug. Created the following CD for tracking: https://msdyneng.visualstudio.com/FinOps/_workitems/edit/759445
