### ISSUE TITLE
Windows 10 supported editions missing

### ISSUE THREAD

**Issue by 5fq** [MicrosoftDocs/dynamics-365-unified-operations-public#4232]
"Windows 10 version 17763.0 or later, Windows 11 (Pro, Enterprise, LTSC, and IOT Enterprise editions), or Windows Server 2019 (Standard, Essentials)"

Could you please define the exact editions of Windows 10 that is supported ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 45ebad3c-1d63-3e3d-4b0c-84acb7cb84ef
* Version Independent ID: b5a17324-a2fc-48a6-28e0-db115a722469
* Content: [Store Commerce app - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/dev-itpro/store-commerce)
* Content Source: [articles/commerce/dev-itpro/store-commerce.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/store-commerce.md)
* Service: **dynamics-365-commerce**
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by bishalgoswami** [comment]
Bug 759152 has been logged to address this issue.

**Comment by josaw1** [comment]
@anupamar-ms can you please take a look at this question?
