### ISSUE TITLE
Need screenshots or additional detail

### ISSUE THREAD

**Issue by dse917** [MicrosoftDocs/dynamics-365-unified-operations-public#4236]
This page is not clear on where or how to get to the Admin Setting to create the connection.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: eab7955b-7cac-cb2a-c115-ae3036feb244
* Version Independent ID: eab7955b-7cac-cb2a-c115-ae3036feb244
* Content: [Invoice capture solution advanced settings - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/accounts-payable/invoice-capture-advanced-settings)
* Content Source: [articles/finance/accounts-payable/invoice-capture-advanced-settings.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/accounts-payable/invoice-capture-advanced-settings.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @sunfzam
* Microsoft Alias: **zezhangzhao**

**Comment by bishalgoswami** [comment]
Bug 759448 has been logged to address this issue.

**Comment by raynezou** [comment]
1. Go to Admin system -> Default solution, click “New” and select “Connection Reference” again. On the Connection creation page, in the Connection type field, select Office 365 Outlook.

![image](https://user-images.githubusercontent.com/115514221/199995209-c9c4a66f-dea2-4c3c-95dc-ada69a325281.png)
