### ISSUE TITLE
How to extend Dynamics 365 Finance trial

### ISSUE THREAD

**Issue by rojedai** [MicrosoftDocs/dynamics-365-unified-operations-public#4237]
Would it be possible to extend Dynamics 365 Finance trial?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3be02eb7-47ec-11ee-6170-8e35f653eb32
* Version Independent ID: d493e3d3-a003-f681-9cb1-7f80aea9be37
* Content: [Before you buy - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/before-you-buy)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/before-you-buy.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/before-you-buy.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @sericks007
* Microsoft Alias: **sericks**

**Comment by bishalgoswami** [comment]
Bug 759629 has been logged to address this issue.

**Comment by sericks007** [comment]
@twheeloc, can you take a look at this one, please?  Thanks!

**Comment by twheeloc** [comment]
@rojedai, thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
