### ISSUE TITLE
The date of expected release for 10.0.31 is in the past

### ISSUE THREAD

**Issue by 5fq** [MicrosoftDocs/dynamics-365-unified-operations-public#4238]
The date of expected release for 10.0.31 is in the past.

![image](https://user-images.githubusercontent.com/47292229/197195500-4f1e1fe2-00fe-463f-8461-5197c7d4b5de.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1fcfc5c3-3e01-c909-dab5-180497a18c21
* Version Independent ID: 1fcfc5c3-3e01-c909-dab5-180497a18c21
* Content: [Preview of Dynamics 365 Commerce 10.0.31 (February 2023) - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/get-started/whats-new-commerce-10-0-31)
* Content Source: [articles/commerce/get-started/whats-new-commerce-10-0-31.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/get-started/whats-new-commerce-10-0-31.md)
* Service: **dynamics-365-commerce**
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by josaw1** [comment]
Thank you for the call-out. I'll fix this now.
