### ISSUE TITLE
Need to fix class names

### ISSUE THREAD

**Issue by TrudAX** [MicrosoftDocs/dynamics-365-unified-operations-public#424]
Provided examples are not in accordance with recommended "Naming guidelines for model extensions".  - https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/extensibility/naming-guidelines-extensions 

1. First class should be named "final class InventTableMy_Extension" (instead of "final class MyInventTable_Extension"), 
2. method should be named "public void myDefaultInventLocationId()" (instead "public void defaultMyInventLocationId()" )
3. last example - "class InventTableMy_EventHandler" (instead "class MyInventTable_EventHandler")

This may not seem like a big deal for you, but examples like these add some mess when developers start using the same wrong approach and refer to such articles. If possible, please correct 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4f7d271-3537-3533-465b-a0e8b96d588c
* Version Independent ID: 43594c5e-abc4-c5b9-0363-6bfdee9ef1e5
* Content: [Add methods to tables through extension - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/extensibility/add-method-table)
* Content Source: [articles/dev-itpro/extensibility/add-method-table.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/extensibility/add-method-table.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @ivanv-microsoft
* Microsoft Alias: **ivanv**

**Comment by sericks007** [comment]
Bug 255843 has been logged to track this issue.

**Comment by sericks007** [comment]
We updated the "Add methods to tables through extension" topic now.  Thanks for reporting the issue!

**Comment by TrudAX** [comment]
Text was not updated properly - 
1.
"To encapsulate that action, you will create a new method on InventTable and name that method defaultMyInventLocationId."
should be changed to 
"To encapsulate that action, you will create a new method on InventTable and name that method myDefaultInventLocationId."
2.
last code line
"inventTable.defaultMyInventLocationId();"

should be changed to 
"inventTable.myDefaultInventLocationId()"

**Comment by sericks007** [comment]
Thanks for letting us know.  I'll re-activate the bug that was tracking this issue.

**Comment by kfend** [comment]
We have updated the topic per your feedback. Changes will be reflected later today.
