### ISSUE TITLE
ZATCA SANDBOX INTEGRATION FAILED

### ISSUE THREAD

**Issue by itsmeVIE** [MicrosoftDocs/dynamics-365-unified-operations-public#4240]
pls give input on this :
CCSID AND PCSID's were obtained successfully.
when submitting xml files via Reporting/Clearance API fails. "User only allowed to use the vat number that exists in the authentication certificate". 
I decoded PCSID (x509issuername,x509serialnumber,vatid) is different from submitted CSR.
XML files are using the vatid sumitted in CSR.
Kindly confirm, is the obtained PCSID from zatca will serve as cert.pem when signing,generating qr and submitting to portal.
Any work around on this,Thanks

**Comment by twheeloc** [comment]
@itsmeVIE, thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
