### ISSUE TITLE
https://learn.microsoft.com/pt-br/dynamics365/commerce/localizations/latam-bra-deployment#configure-crt-extension-components

### ISSUE THREAD

**Issue by betespadula** [MicrosoftDocs/dynamics-365-unified-operations-public#4241]
[A documentação não é clara como executar o processo do Configure CRT extension qual diretório, qual pasta. Seria melhor detalhar todo o processo. ]

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação de problema do learn.microsoft.com ➟ GitHub.*

* ID: 2309d63d-5e54-e87b-9c5c-38a0e1acd57e
* Version Independent ID: 68bd7155-a13d-f99b-9cb6-9764239b8950
* Content: [Set up and deploy the Dynamics 365 Commerce localization for Brazil - Commerce | Dynamics 365](https://learn.microsoft.com/pt-br/dynamics365/commerce/localizations/latam-bra-deployment)
* Content Source: [articles/commerce/localizations/latam-bra-deployment.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/localizations/latam-bra-deployment.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @EvgenyPopovMBS
* Microsoft Alias: **josaw**

**Comment by bishalgoswami** [comment]
Bug 759710 has been logged to address this issue.

**Comment by kfend** [comment]
Closing this issue. According to PMs, the documentation will not be updated because the steps become obsolete after moving from the legacy Retail SDK to the Commerce SDK. This has already been done for many Commerce localizations and is currently pending for Brazil.
