### ISSUE TITLE
Is the tier 1 build environment still required in a project ?

### ISSUE THREAD

**Issue by 5fq** [MicrosoftDocs/dynamics-365-unified-operations-public#4244]
Microsoft removed the tier1 build environment (that used to come with the license subscription) stating we should be using Azure pipelines. Do we still need to consider a tier 1 environment for build as shown below ?

![image](https://user-images.githubusercontent.com/47292229/198237954-1bb649b0-c966-4fe0-b13f-62b91d31a617.png)
 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2402dfea-008a-c7bb-8a3b-1d0457a39665
* Version Independent ID: 4936afad-9a39-e65d-a00c-81246de632cb
* Content: [Environment planning - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/imp-lifecycle/environment-planning)
* Content Source: [articles/fin-ops-core/fin-ops/imp-lifecycle/environment-planning.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/imp-lifecycle/environment-planning.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @skaue-ms
* Microsoft Alias: **toskaue**

**Comment by bishalgoswami** [comment]
Bug 760871 has been logged to address this issue.

**Comment by skaue-ms** [comment]
The tier1 build environment comes with a runtime (AOS) which enables post-build testing that is not possible on a hosted built. The hosted build will only be able to do compile-time verification and check that the code can successfully compile. You can combine this with making sure the successfully built package gets deployed to a tier2+ sandbox as a next step, and run test against the sandbox if you prefer.

**Comment by 5fq** [comment]
> The tier1 build environment comes with a runtime (AOS) which enables post-build testing that is not possible on a hosted built. The hosted build will only be able to do compile-time verification and check that the code can successfully compile. You can combine this with making sure the successfully built package gets deployed to a tier2+ sandbox as a next step, and run test against the sandbox if you prefer.

Thanks for the clarification @skaue-ms, that makes sense.
