### ISSUE TITLE
Not enough details about products accounting for 80% of purchase

### ISSUE THREAD

**Issue by darione2178** [MicrosoftDocs/dynamics-365-unified-operations-public#4247]
[Enter feedback here]
Hi,

I wanted to recreate the list of products accounting for 80% of purchase but the formula explanation is nowhere to be found.

Would it be possible to add an explanation for it?

Thank you,

Dario

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c9fddaaf-67d7-17ff-0615-5bef40c2c25a
* Version Independent ID: 8701de31-e680-61f9-876f-2115f1d92d43
* Content: [Purchase spend analysis Power BI content - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/purchase-content-pack-for-power-bi)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/purchase-content-pack-for-power-bi.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/analytics/purchase-content-pack-for-power-bi.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @FrankDahl
* Microsoft Alias: **fdahl**

**Comment by bishalgoswami** [comment]
Bug 760984 has been logged to address this issue.
