### ISSUE TITLE
payment terminal integration documentation

### ISSUE THREAD

**Issue by Halldor10** [MicrosoftDocs/dynamics-365-unified-operations-public#4248]
Regarding the https://learn.microsoft.com/en-us/dynamics365/commerce/dev-itpro/end-to-end-payment-extension

The information on this page is good, but the problem is that gives only part of the information needed.

The code example in the "Implement the IPaymentProcessor interface", is not good, as the code in the example is referring to alot of code that is part of a code base in the older SDK. Not everyone will make the connection with the old SDK.

This code should be part of the github example: /src/HardwareStationSample/PaymentDevice/ or something similar

I tried to follow the example to see where it would take me.

The shortest way I found to implement the IPaymentProcessor interface was take an example from the old SDK and comment out the things that were not needed.

If figured out that I needed to put it under the K:\AosService\PackagesLocalDirectory\bin\Connectors on the Dev box so I could select it in D365FO in the Hardwareprofile. 

The "Payment connector" example compiled as was installed as an extension to a HWS (Sealed)

But when testing out the cardpayment in POS, an error dialog came not giving any good information on what was wrong But Fiddler showed it failed when calling "GetCardPaymentAcceptPoint" with a reply 
"{`
  "TypeName": "PaymentConfigurationException",
  "Exception": "{\r\n  \"PaymentConfigurationSdkErrors\": [],\r\n  \"ErrorResourceId\": \"Microsoft_Dynamics_Commerce_Runtime_PaymentConnectorFilesNotFoundWhileLoadingAssemblies\",\r\n  \"LocalizedMessage\": \"Finner ikke betalingskoblingsfiler under innlasting av samlinger. Kontroller utvidelsespakken for å identifisere avhengighetene som mangler.\"\r\n}",
  "CorrelationId": "d1287807-611b-4775-8cb8-1451d0db431d"
}

But I am still not sure why the POS is calling RetailServer for this information and why it failed and what files RetailServer is trying to load. I am running a setup with Store Commerce POS, RetailServer and HWS running on IIS 

And the new extension code for the payment terminal integration was never called when a debugger was attached.

Another thing is that is should be a better way to extend the PayCardView without using IFrame.

The question is also why IPaymentProcessor is needed in the first place.

So basically there should be a walkthrough that refers to a github example code and information how to configure things and where to copy/install files, and with an example on how to extend the CPOS without using IFrame, so the whole thing can work together as one.

Another that would be nice, is if the HWS could support Dependency Injection so it would be possible to do something like:
    services.AddSingleton<ICardTerminalService, CardTerminalService>();

It would also be great if the HWS would support SingalR and the POS could communitcate with the POS via SignalR, so the HWS could raise events for like card authorized or new display text on terminal, instead of needing all this long polling. The same could be also used for the barcode scanner instead of the long polling.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8082a393-27b6-131d-b708-ddf23411fde9
* Version Independent ID: ffb5a30e-508b-5b65-2b0d-7e888063d85c
* Content: [Create an end-to-end payment integration for a payment terminal - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/dev-itpro/end-to-end-payment-extension)
* Content Source: [articles/commerce/dev-itpro/end-to-end-payment-extension.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/end-to-end-payment-extension.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @Reza-Assadi
* Microsoft Alias: **rassadi**

**Comment by bishalgoswami** [comment]
Bug 761216 has been logged to address this issue.
