### ISSUE TITLE
Add D365 Human Resources to the list

### ISSUE THREAD

**Issue by finopsfuntimes** [MicrosoftDocs/dynamics-365-unified-operations-public#4249]
The first paragraph of this page should also include D365 Human Resources, now that the infrastructure merge is completed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 90265dfd-3035-a591-fbb4-4265024186b7
* Version Independent ID: 374ae0ff-ce77-54d5-f16c-2faf3fc6e7bb
* Content: [Deploy a demo environment - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/deploy-demo-environment)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/deploy-demo-environment.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/deployment/deploy-demo-environment.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by bishalgoswami** [comment]
Bug 761259 has been logged to address this issue.

**Comment by twheeloc** [comment]
@finopsfuntimes, thank you for the feedback. The topic will be updated.
