### ISSUE TITLE
Badge ID is not present in the Production floor execution landing page

### ISSUE THREAD

**Issue by darione2178** [MicrosoftDocs/dynamics-365-unified-operations-public#4250]
Hi,

When opening the landing page for production floor execution, instead of badge ID it asks for personnel number. You should add a section on setting up this option.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 17fe109b-0191-fae3-c120-608f709208c3
* Version Independent ID: 2ae7d13f-c34e-53de-3265-c1c508c3703e
* Content: [How workers use the production floor execution interface - Supply Chain Management | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/supply-chain/production-control/production-floor-execution-use)
* Content Source: [articles/supply-chain/production-control/production-floor-execution-use.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/production-control/production-floor-execution-use.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @johanhoffmann
* Microsoft Alias: **johanho**

**Comment by bishalgoswami** [comment]
Bug 761326 has been logged to address this issue.
