### ISSUE TITLE
More specific details needed regarding how to migrate to an existing F&SCM environment 

### ISSUE THREAD

**Issue by GlenTurnbullD365** [MicrosoftDocs/dynamics-365-unified-operations-public#4252]
Although the document mentions that customers are expected to migrate to existing Finance & SCM environments in their own time using DMF (as the tooling is for migration to new environments only), It would be great to have some additional information with regards to the mapping between existing HR and existing F&SCM entities on the latest builds.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 31c070c6-1b9a-8bae-687c-4137e922a123
* Version Independent ID: 31c070c6-1b9a-8bae-687c-4137e922a123
* Content: [Dynamics 365 Human Resources customer migration to the finance and operations infrastructure - Human Resources | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/human-resources/hr-cust-migration)
* Content Source: [articles/human-resources/hr-cust-migration.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/human-resources/hr-cust-migration.md)
* Service: **dynamics-365-human-resources**
* Product: ****
* Technology: ****
* GitHub Login: @twheeloc
* Microsoft Alias: **twheeloc**

**Comment by bishalgoswami** [comment]
Bug 762028 has been logged to address this issue.

**Comment by twheeloc** [comment]
@GlenTurnbullD365, thank you for the feedback. Content will be updated in the future.
