### ISSUE TITLE
Documentation on v1.0.38

### ISSUE THREAD

**Issue by bhatvarun** [MicrosoftDocs/dynamics-365-unified-operations-public#4253]
The version available in Admin Center is 1.0.38, but this page only talks about 1.0.37, and there is no documentation on what's new between 1.0.37 and 1.0.38. We need to install 1.0.37, but since only v38 is available, we are stuck with a version that has no details documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b8043d72-1496-a79a-da5b-60dc1d24f561
* Version Independent ID: fa5f09b6-10d9-ab9a-6f65-da69252777c1
* Content: [What's new or changed in dual-write - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/whats-new-dual-write)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/whats-new-dual-write.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/dual-write/whats-new-dual-write.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @RamaKrishnamoorthy
* Microsoft Alias: **ramasri**

**Comment by bishalgoswami** [comment]
Bug 762456 has been logged to address this issue.

**Comment by bhatvarun** [comment]
The documentation is still at 1.0.37, while our instances were auto-updated to 1.0.38. Is there a timeline on when we can see the release notes for 1.0.38?
