### ISSUE TITLE
Missing information for LCS EU

### ISSUE THREAD

**Issue by hubertwillberger** [MicrosoftDocs/dynamics-365-unified-operations-public#4255]
Please add also informations for LCS EU. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a6d1de99-13f8-e025-c0b6-48ab63702eed
* Version Independent ID: 7a518d3c-9bff-305a-38ae-07be1457cc19
* Content: [Configure proxies for on-premises environments - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/onprem-reverseproxy)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/onprem-reverseproxy.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/deployment/onprem-reverseproxy.md)
* Service: ****
* Product: **dynamics-365**
* Technology: ****
* GitHub Login: @faix
* Microsoft Alias: **osfaixat**

**Comment by bishalgoswami** [comment]
Bug 762900 has been logged to address this issue.
