### ISSUE TITLE
Unable to follow instructions from step 6

### ISSUE THREAD

**Issue by artemt-yavica** [MicrosoftDocs/dynamics-365-unified-operations-public#4257]
Step 6 says:
After the package is successfully imported, open Dynamics 365 Invoice capture – Installation Tools.

I can't find "Dynamics 365 Invoice capture – Installation Tools", could you please provide more details where it is located?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cb7e15d7-810e-01e0-01e4-a96780be9b28
* Version Independent ID: cb7e15d7-810e-01e0-01e4-a96780be9b28
* Content: [Install the Invoice capture solution - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/accounts-payable/install-invoice-capture)
* Content Source: [articles/finance/accounts-payable/Install-invoice-capture.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/accounts-payable/Install-invoice-capture.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @sunfzam
* Microsoft Alias: **zezhangzhao**

**Comment by bishalgoswami** [comment]
Bug 762940 has been logged to address this issue.

**Comment by raynezou** [comment]
It could be found under Power Apps -> Solution.

**Comment by artemt-yavica** [comment]
I still can't find it. Is it on Power Platform admin center or in the environment itself.
Do you have a screenshot?

**Comment by raynezou** [comment]
You need to install the assistant tool first. 
![image](https://user-images.githubusercontent.com/115514221/199986858-e3e7f3e6-83c6-4bbb-aec2-e53c30109946.png)

**Comment by raynezou** [comment]
You need to install the assistant tool first. 
![image](https://user-images.githubusercontent.com/115514221/199986858-e3e7f3e6-83c6-4bbb-aec2-e53c30109946.png)

**Comment by artemt-yavica** [comment]
I do have solutions installed on my environment.
How to do the following "open Dynamics 365 Invoice capture – Installation Tools" from step 6 ?

![image](https://user-images.githubusercontent.com/117354593/200334778-a9d47c50-eedb-4382-ae81-1593af06e5ea.png)

**Comment by artemt-yavica** [comment]
Any updates?

**Comment by raynezou** [comment]
Please go from Home -> Solution -> Default solution -> Cloud flow -> Click the flow "Setup Connection to Dynamics 365 Finance and Operation"

![image](https://user-images.githubusercontent.com/115514221/202644526-fbd9aec5-3fad-46d4-91a5-5f94bdc4c096.png)

And click the run button on the flow page.

**Comment by artemt-yavica** [comment]
Found it, thank you!

However, when I run the Flow, the following error appears. Any ideas how to fix it?

Error from token exchange: Permission denied due to missing connection ACL: User = cf033b42-3e37-4c34-b2e7-ff7c570148d1@94cf2c48-2b38-4e48-9b02-df607a861cdd appid=7df0a125-d3be-4c96-aa54-591f83ff541c, connection=europe-002/logicflows/7633c38a-880c-bdc2-8299-417bde94d7bb

<img width="418" alt="image" src="https://user-images.githubusercontent.com/117354593/202655448-30109050-0fe1-4754-9239-72ceeb1da961.png">

**Comment by raynezou** [comment]
Please refresh the browser and try again. If the issue is still there, please contact me directly via raynezou@microsoft.com.
