### ISSUE TITLE
Old reference URL

### ISSUE THREAD

**Issue by fidobeast** [MicrosoftDocs/dynamics-365-unified-operations-public#4258]
[Enter feedback here]
the URL link is refering to the platform 12-40 install scripts and might need updateing. 
![image](https://user-images.githubusercontent.com/36621868/199708416-9ffd1c8c-9394-4dae-81a0-1a2a823d7cf3.png)

to that, old scripts are referenced and serve to confuse the user following it using the : 
![image](https://user-images.githubusercontent.com/36621868/199708629-52a12732-fb6d-41b7-a9c4-4ffde75fe92b.png)

Might just need an overhaul! :)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5368663a-10f3-3d71-f958-776515e3ddbe
* Version Independent ID: ddc21833-3622-a844-db5c-88efaee919cc
* Content: [Remove and reinstall, or add an AOS node - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/onprem-remove-reinstall-aos-node#option-2-use-service-fabric-explorer)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/onprem-remove-reinstall-AOS-node.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/deployment/onprem-remove-reinstall-AOS-node.md)
* Service: ****
* Product: **dynamics-365**
* Technology: ****
* GitHub Login: @ttreen
* Microsoft Alias: **ttreen**

**Comment by bishalgoswami** [comment]
Bug 762952 has been logged to address this issue.

**Comment by ttreen** [comment]
Created pull request with edits - https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/issues/4258

**Comment by twheeloc** [comment]
@fidobeast, thank you for the feedback. Update to the topic will be published soon.
