### ISSUE TITLE
Typo in architecture in sidebar

### ISSUE THREAD

**Issue by Vanseeuw** [MicrosoftDocs/dynamics-365-unified-operations-public#4260]
Typo in the naming of "architecture" in the navigation pane 
<img width="138" alt="image" src="https://user-images.githubusercontent.com/93705359/199978221-dd1bb5db-17fd-44ca-ae43-bcdeadc5f365.png">]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 58e0c8fc-6697-6a35-ba3f-0986916db4e6
* Version Independent ID: 7dd13d5d-314e-97a4-5154-cea0e588f99e
* Content: [Master planning system architecture - Supply Chain Management | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/supply-chain/master-planning/master-planning-architecture)
* Content Source: [articles/supply-chain/master-planning/master-planning-architecture.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/master-planning/master-planning-architecture.md)
* Service: **dynamics-365-supply-chain**
* GitHub Login: @t-benebo
* Microsoft Alias: **benebotg**

**Comment by kamaybac** [comment]
@Vanseeuw , thank you for reporting this typo. I am fixing it now and it should go live very soon.
