### ISSUE TITLE
"Audit data" form should be documented under Security.

### ISSUE THREAD

**Issue by xDynaMike** [MicrosoftDocs/dynamics-365-unified-operations-public#4261]
"Audit data" form is accessible from Security Configuration form and there is no documentation for that matter.
The form itself is providing a lot of valuable informations in terms of changes applied to all the security roles - it really should be documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9907d444-3d05-f72e-7a7d-9e667c344987
* Version Independent ID: 4d757287-4674-dddf-1761-c57d0abe3530
* Content: [Role-based security - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/role-based-security)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/role-based-security.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/sysadmin/role-based-security.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Peakerbl
* Microsoft Alias: **peakerbl**

**Comment by bishalgoswami** [comment]
Bug 768917 has been logged to address this issue.

**Comment by johnmichalak** [comment]
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.
