### ISSUE TITLE
Are there newer versions of the configuration data packages?

### ISSUE THREAD

**Issue by KheeChan** [MicrosoftDocs/dynamics-365-unified-operations-public#4265]
Are there newer version of the configuration data packages? The ones referenced here and in LCS were released in July 2017.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 78b77c99-653c-362c-28d1-d6139d05dbe0
* Version Independent ID: 6786eb0c-9785-96c4-64ee-794aaf0bfa3d
* Content: [Configuration data packages - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/configuration-data-packages?source=docs)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/configuration-data-packages.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/configuration-data-packages.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @rcarlson
* Microsoft Alias: **rcarlson**

**Comment by bishalgoswami** [comment]
Bug 768916 has been logged to address this issue.

**Comment by johnmichalak** [comment]
@KheeChan Thank you for your question. I am checking with the content author to see if I can get an answer for you.
