### ISSUE TITLE
Localized LCS Support

### ISSUE THREAD

**Issue by WarnierT** [MicrosoftDocs/dynamics-365-unified-operations-public#4266]
Hi Currently the Upload and deploy options only work against the Standard LCS not with the multiple Local LCS like ch.lcs.dynamics.com.

When can we have an option on the Dynamics 365 Finance and Operations Tools to define the LCS URL?
The powershell Tools D365 Tools offer this already.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 11517278-6719-1766-c2fa-8b7e346f0269
* Version Independent ID: 8b63f7e5-e6e8-b917-3cff-111158c91a24
* Content: [Upload assets by using Azure Pipelines - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/pipeline-asset-upload)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/pipeline-asset-upload.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/dev-tools/pipeline-asset-upload.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @gianugo
* Microsoft Alias: **gianura**

**Comment by bishalgoswami** [comment]
Bug 768915 has been logged to address this issue.
