### ISSUE TITLE
Change title of "Open Vendor Transaction report"

### ISSUE THREAD

**Issue by mrlopezco** [MicrosoftDocs/dynamics-365-unified-operations-public#4270]
The title of the page says "Open Vendor Transaction Report", but the report in Dynamics is "Vendor open transaction report"

Would be helpful to change the title to avoid any confussions. Thanks!

https://learn.microsoft.com/en-us/dynamics365-release-plan/2021wave2/finance-operations/dynamics365-finance/open-vendor-transaction-report?source=docs

**Comment by josaw1** [comment]
Thank you for the suggestion. @alexbuckgit can you please review?
