### ISSUE TITLE
How to add filter on unstriped contact(contact for)

### ISSUE THREAD

**Issue by swapnilekhe** [MicrosoftDocs/dynamics-365-unified-operations-public#4275]
We have installed the Dual Write and Global address book solution. Here we can filter the stripped Contacts as we have Customer V3 (Contact) mapping with Dataverse.contact. But for unstripped contact need to know the filtering process?. After installing GAB solution we disabled CDS Contact V2(Contacts) mapping, do we need to enable it to filter unstripped contacts? Please help.

**Comment by twheeloc** [comment]
@swapnilekhe, thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
