### ISSUE TITLE
Does the hyperlink "Complete the design of the model mapping" take me to the wrong location?

### ISSUE THREAD

**Issue by DavidHBallantyne** [MicrosoftDocs/dynamics-365-unified-operations-public#4276]
While the hyperlink includes the following URL:

**https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/er-quick-start3-customize-report#add-a-custom-data-model-configuration**

When I search the internet for "**Complete the design of the data model**", I am given the following URL:

**https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/er-quick-start1-new-solution**
---
#### Document Details

To me, the latter seems more accurate.

...and even more precise:

**https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/er-quick-start1-new-solution#CompleteDataModel**

Thanks.
⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1942f465-8b35-5d43-e4a8-3867bce7e065
* Version Independent ID: 1942f465-8b35-5d43-e4a8-3867bce7e065
* Content: [Group records and aggregate calculations by using GROUPBY data sources - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/er-groupby-data-sources)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/er-groupby-data-sources.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/analytics/er-groupby-data-sources.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **filatovm**

**Comment by bishalgoswami** [comment]
Bug 768912 has been logged to address this issue.

**Comment by kfend** [comment]
@DavidHBallantyne - Thanks for the feedback. Because the link goes to the same topic, just a different section, we have decided to keep it as is.
