### ISSUE TITLE
Verbiage is improper

### ISSUE THREAD

**Issue by iangorman2020** [MicrosoftDocs/dynamics-365-unified-operations-public#4288]
URL: https://learn.microsoft.com/en-us/dynamics365/finance/general-ledger/change-mdfy-clndr-to-ledger#change-an-existing-fiscal-calendar

It appears that as of a recent update, we can no longer delete periods that contain transactions in them. 

Recorded transactions exist in ledger 'XXX', in organization 'XXX:', for the selected fiscal period. The Period Period 10 cannot be deleted

This is occurring when we try to delete October 2022 so we can recreate the period via division. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 87c86bac-ba37-c1f2-dcab-3ccfb92564b2
* Version Independent ID: 14161b11-6ccc-f7c4-1bb5-494517de7a27
* Content: [Change or reassign a ledger calendar - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/general-ledger/change-mdfy-clndr-to-ledger)
* Content Source: [articles/finance/general-ledger/change-mdfy-clndr-to-ledger.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/general-ledger/change-mdfy-clndr-to-ledger.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @kweekley
* Microsoft Alias: **kweekley**

**Comment by bishalgoswami** [comment]
Bug 769779 has been logged to address this issue.

**Comment by twheeloc** [comment]
@iangorman2020, thank you for the feedback. The content has been updated and will be live in the next couple of days.
