### ISSUE TITLE
Need field explanations

### ISSUE THREAD

**Issue by brentlincoln** [MicrosoftDocs/dynamics-365-unified-operations-public#429]
It would be very helpful if you could bring back the field explanations for every form.  This was very helpful in previous versions.  If that exists somewhere (particularly for Category hierarchies), could you direct me to the correct place?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22648dc4-c5ea-0eb6-f04a-aeb87dc495d5
* Version Independent ID: 6c48676d-e728-2b3d-9a84-15e35c859bcc
* Content: [Create a hierarchy of product classification - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/pim/tasks/create-hierarchy-product-classification)
* Content Source: [articles/supply-chain/pim/tasks/create-hierarchy-product-classification.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/pim/tasks/create-hierarchy-product-classification.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @ShylaThompson
* Microsoft Alias: **shylaw**

**Comment by ShylaThompson** [comment]
@brentlincoln , Thanks for your comment. We have the following topic that describes where you can find field descriptions:  https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/view-export-field-descriptions  

Please, also note that we're in the process of adding field descriptions to various forms across the product. If you have specific fields that you find confusing and would like field descriptions for, please let us know by replying to this comment. I'll make sure that we get that work planned for future releases.  

One tip for now, until we can get field descriptions updated in Finance and Operations, is to review the AX 2012 documentation to see if the field descriptions there provide context that might help you. Here is a link to the Category hierarchy form topic for AX 2012:  https://technet.microsoft.com/en-us/library/hh209524.aspx 

Please note that there are differences between AX 2012 and Finance and Operations, and not all fields or field descriptions in AX 2012 apply to Finance and Operations.

**Comment by ShylaThompson** [comment]
@brentlincoln I am going to close this issue as it has been over a month without a response.
