### ISSUE TITLE
Order of elements in TABLE not the same as the example JSON

### ISSUE THREAD

**Issue by metkhoo** [MicrosoftDocs/dynamics-365-unified-operations-public#4293]
It would be great if you could match the order of the TABLE describing the elements to be that of the JSON example also given on the same page.

Thanks

/Marcus

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4fa15354-2ca9-4655-e0ca-fe7f7ef40010
* Version Independent ID: 9da76202-6974-1319-1ce5-40d0b9f0fcbe
* Content: [Person certificate - Human Resources | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/human-resources/hr-admin-integration-ats-api-person-certificate)
* Content Source: [articles/human-resources/hr-admin-integration-ats-api-person-certificate.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/human-resources/hr-admin-integration-ats-api-person-certificate.md)
* Service: **dynamics-365-human-resources**
* Product: ****
* Technology: ****
* GitHub Login: @jaredha
* Microsoft Alias: **jaredha**

**Comment by bishalgoswami** [comment]
Bug 770141 has been logged to address this issue.

**Comment by twheeloc** [comment]
@metkhoo, thank you for the feedback, I'll have the PM review.
