### ISSUE TITLE
Query use of the word 'Minimum'

### ISSUE THREAD

**Issue by tomstalentblog** [MicrosoftDocs/dynamics-365-unified-operations-public#4295]
This line:
The minimum age of an eligible personal contact for the benefit plan. 

Seems misleading - should this be maximum age, rather than minimum? The Contoso data suggests it works in this way.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fcef9515-22f9-f710-f69f-d9525c6cf57d
* Version Independent ID: 51858208-a56c-8f05-eb1e-6dd7d00a2d7e
* Content: [Configure personal contact eligibility options - Human Resources | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/human-resources/hr-benefits-setup-contact-eligibility-options)
* Content Source: [articles/human-resources/hr-benefits-setup-contact-eligibility-options.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/human-resources/hr-benefits-setup-contact-eligibility-options.md)
* Service: **dynamics-365-human-resources**
* Product: ****
* Technology: ****
* GitHub Login: @twheeloc
* Microsoft Alias: **twheeloc**

**Comment by bishalgoswami** [comment]
Bug 770355 has been logged to address this issue.

**Comment by twheeloc** [comment]
@tomstalentblog, thank you for the feedback. The topic will be updated with additional clarification later today.
