### ISSUE TITLE
Errors in JSON and explanation table

### ISSUE THREAD

**Issue by metkhoo** [MicrosoftDocs/dynamics-365-unified-operations-public#4297]
Three errors on this page:

The JSON example does not cotain the element _mshr_fk_screeningtype_id_value which IS included in the TABLE 
The JSON example contains the element mshr_primaryfield which IS NOT included in the TABLE

The TABLE row for "Status" is malformed and the text is not in the correct columns

Also, could you have the SAME ORDER in the JSON and the table for ease of reference?

Thanks
/Marcus

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bd8199a5-e34d-14eb-37cf-d7a392f81e76
* Version Independent ID: 957ce226-c80d-036d-2c49-fce76a64940e
* Content: [Person screening - Human Resources | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/human-resources/hr-admin-integration-ats-api-person-screening)
* Content Source: [articles/human-resources/hr-admin-integration-ats-api-person-screening.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/human-resources/hr-admin-integration-ats-api-person-screening.md)
* Service: **dynamics-365-human-resources**
* Product: ****
* Technology: ****
* GitHub Login: @jaredha
* Microsoft Alias: **jaredha**

**Comment by bishalgoswami** [comment]
Bug 770576 has been logged to address this issue.

**Comment by twheeloc** [comment]
@metkhoo, thank you for the feedback. The topic has been updated.
