### ISSUE TITLE
JSON invalid characters and TABLE mismatch

### ISSUE THREAD

**Issue by metkhoo** [MicrosoftDocs/dynamics-365-unified-operations-public#4298]
Errors found on the page:

JSON has invalid inverted commas for the last line _mshr_fk_recruitingrequestlocation_id_value

JSON data says _mshr_fk_recruitingrequestlocation_id_value but TABLE has element name as _mshr_fk_recruitinglocation_id_value

Thanks
/Marcus

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a858005d-4d6f-b864-2839-a77772abf4af
* Version Independent ID: d4b34bf1-4850-3334-c175-47c1b0d2c8c4
* Content: [Recruiting request - Human Resources | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/human-resources/hr-admin-integration-ats-api-recruiting-request)
* Content Source: [articles/human-resources/hr-admin-integration-ats-api-recruiting-request.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/human-resources/hr-admin-integration-ats-api-recruiting-request.md)
* Service: **dynamics-365-human-resources**
* Product: ****
* Technology: ****
* GitHub Login: @jaredha
* Microsoft Alias: **jaredha**

**Comment by bishalgoswami** [comment]
Bug 770584 has been logged to address this issue.

**Comment by jaredha** [comment]
@tulsijhaveri

**Comment by bishalgoswami** [comment]
Bug 771152 has been logged to address this issue.

**Comment by bishalgoswami** [comment]
Bug 771225 has been logged to address this issue.

**Comment by twheeloc** [comment]
@metkhoo, thank you for the feedback. The topic will be updated with the changes.
