### ISSUE TITLE
Small spelling mistake 

### ISSUE THREAD

**Issue by Anders-Dahlin** [MicrosoftDocs/dynamics-365-unified-operations-public#4299]
Hi,

A small spelling mistake in section:

Replenishment category access policy rule
The replenishment category access policy **rile** is an optional rule that determines the products that are available to fulfill requisition demand for a specific legal entity when the requisition purpose is Replenishment.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6f396b06-4223-f6d8-7a14-9f38de17d40d
* Version Independent ID: c23dec68-d813-3dcd-48f2-e43727bf63bb
* Content: [Purchasing policies overview - Supply Chain Management | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/supply-chain/procurement/purchase-policies)
* Content Source: [articles/supply-chain/procurement/purchase-policies.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/procurement/purchase-policies.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @GalynaFedorova
* Microsoft Alias: **gfedorova**

**Comment by bishalgoswami** [comment]
Bug 770693 has been logged to address this issue.

**Comment by GalynaFedorova** [comment]
Spelling mistake is fixed, pull request has been submitted for review to Karl

**Comment by kamaybac** [comment]
This was resolved a while ago. Closing this issue.
