### ISSUE TITLE
Autoapproval for managers

### ISSUE THREAD

**Issue by HugoDJesus** [MicrosoftDocs/dynamics-365-unified-operations-public#4300]
Hi,

If you want to autoapprove in case the manager enters the skill and send it to the line manager in the case the employee enters the skill, the condition in the workflow should be: workflow.originator <> relationship user to person.person .

Best regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ef65c6c1-b64b-3827-b29b-a6ae3e50ac8f
* Version Independent ID: f647d3eb-b3db-06b6-f571-3131d2df3795
* Content: [Enter skills - Human Resources | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/human-resources/hr-develop-enter-skills)
* Content Source: [articles/human-resources/hr-develop-enter-skills.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/human-resources/hr-develop-enter-skills.md)
* Service: **dynamics-365-human-resources**
* Product: ****
* Technology: ****
* GitHub Login: @twheeloc
* Microsoft Alias: **twheeloc**

**Comment by bishalgoswami** [comment]
Bug 770724 has been logged to address this issue.

**Comment by twheeloc** [comment]
@HugoDJesus, thank you for the feedback. The content will be updated.
