### ISSUE TITLE
Changes to SQLPackage security - update to command line needed

### ISSUE THREAD

**Issue by rikm69** [MicrosoftDocs/dynamics-365-unified-operations-public#4301]
[Enter feedback here]
According to [https://aka.ms/dacfx-connection](url) we now need to add the following command line parameter on the SQLPackage Import:

/TargetTrustServerCertificate

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7c5e8701-e1d4-25f8-d76a-ee7870b915e1
* Version Independent ID: 624211c7-2eb4-7154-d38f-236dc6f8f7a9
* Content: [Export a copy of the standard user acceptance testing (UAT) database - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/dbmovement-scenario-exportuat)
* Content Source: [articles/fin-ops-core/dev-itpro/database/dbmovement-scenario-exportuat.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/database/dbmovement-scenario-exportuat.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by bishalgoswami** [comment]
Bug 771151 has been logged to address this issue.

**Comment by johnmichalak** [comment]
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.
