### ISSUE TITLE
Provisioning guide link is not available

### ISSUE THREAD

**Issue by ysong163** [MicrosoftDocs/dynamics-365-unified-operations-public#4303]
cannot download the Provisioning guide through the link in this page.
Gateway Exception Response
[在此处输入反馈]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 learn.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: ebcc370e-5c3e-a7ed-bece-6d23bbc5e01b
* Version Independent ID: aef5c71b-ab31-a0d8-0eaf-c32e1b9aab9b
* Content: [Buy Finance + Operations (on-premises) - Finance & Operations | Dynamics 365](https://learn.microsoft.com/zh-cn/dynamics365/fin-ops-core/fin-ops/get-started/purchase-on-premises)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/purchase-on-premises.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/purchase-on-premises.md)
* Service: ****
* Product: **dynamics-365**
* Technology: ****
* GitHub Login: @faix
* Microsoft Alias: **osfaixat**

**Comment by bishalgoswami** [comment]
Bug 771844 has been logged to address this issue.

**Comment by faix** [comment]
Hi,

The server is serving request correctly:
![image](https://user-images.githubusercontent.com/7562660/205058607-a3523bde-4693-4dfd-8a2d-3520167bb802.png)

**Comment by faix** [comment]
@johnmichalak please feel free to close.

**Comment by ysong163** [comment]
Dear Team，

I tried to click the link，it still shows gateway exception response after the counting page.

***@***.***
Thanks
Best Regards
Yajing Song 宋亚京
License Administrator  |  HSO China
***@***.***<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.hso.com%2F&data=04%7C01%7C%7C8a977bf028e34ec0f50f08d9eb6faa29%7C9bc096abf225476e8e92260401469868%7C0%7C0%7C637799687117651345%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Yku6TSv8JuJaNikyRYsSXV0UWtKidlQzDeYMTW6rO4w%3D&reserved=0>
M +86 (0)13261634788 | W www.hso.com<https://eur01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.hso.com%2F&data=04%7C01%7C%7C8a977bf028e34ec0f50f08d9eb6faa29%7C9bc096abf225476e8e92260401469868%7C0%7C0%7C637799687117651345%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=uKxecvUYmKFkSAjrJ7FAJkaVUg7JuYaYUpbVsFneaj0%3D&reserved=0>

E ***@***.******@***.***>
Disclaimer
This email and any attachment are for authorized use by the intended recipient(s) only. It may contain proprietary material, confidential information and/or be subject to legal privilege. It may not be copied, disclosed to, forwarded to, retained or used by any other party. If you are not an intended recipient, then kindly delete this email and any attachment plus all copies immediately and inform the sender.

发件人: Oscar Faixat ***@***.***>
发送时间: 2022年12月1日 20:59
收件人: MicrosoftDocs/dynamics-365-unified-operations-public ***@***.***>
抄送: Yajing Song ***@***.***>; Author ***@***.***>
主题: Re: [MicrosoftDocs/dynamics-365-unified-operations-public] Provisioning guide link is not available (Issue #4303)

你通常不会收到来自 ***@***.******@***.***> 的电子邮件。了解这一点为什么很重要<https://aka.ms/LearnAboutSenderIdentification>

@johnmichalak<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjohnmichalak&data=05%7C01%7C%7C8f377cfb3c364ef30d1e08dad39bda2a%7C9bc096abf225476e8e92260401469868%7C0%7C0%7C638054963581360931%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Yib7ZUosEdBuZZxn%2Ff3bPq3Jlwf3OhrKmW3WC%2Fd13Ac%3D&reserved=0> please feel free to close.

―

**Comment by faix** [comment]
@ysong163 can you please share a screenshot of the issue you are facing?

**Comment by ysong163** [comment]
Dear Team,

Below are the screenshots,

Screenshot 1 :  Click the provisioning guide
***@***.***

Screenshot 2 : The website skips to the counting page

***@***.***

Screenshot 3: When the countdown is over, it shows  “gateway exception response”, and my download is empty.
***@***.***
Thanks
Best Regards
Yajing Song 宋亚京
License Administrator  |  HSO China
***@***.***<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.hso.com%2F&data=04%7C01%7C%7C8a977bf028e34ec0f50f08d9eb6faa29%7C9bc096abf225476e8e92260401469868%7C0%7C0%7C637799687117651345%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Yku6TSv8JuJaNikyRYsSXV0UWtKidlQzDeYMTW6rO4w%3D&reserved=0>
M +86 (0)13261634788 | W www.hso.com<https://eur01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.hso.com%2F&data=04%7C01%7C%7C8a977bf028e34ec0f50f08d9eb6faa29%7C9bc096abf225476e8e92260401469868%7C0%7C0%7C637799687117651345%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=uKxecvUYmKFkSAjrJ7FAJkaVUg7JuYaYUpbVsFneaj0%3D&reserved=0>

E ***@***.******@***.***>
Disclaimer
This email and any attachment are for authorized use by the intended recipient(s) only. It may contain proprietary material, confidential information and/or be subject to legal privilege. It may not be copied, disclosed to, forwarded to, retained or used by any other party. If you are not an intended recipient, then kindly delete this email and any attachment plus all copies immediately and inform the sender.

发件人: Oscar Faixat ***@***.***>
发送时间: 2022年12月1日 21:40
收件人: MicrosoftDocs/dynamics-365-unified-operations-public ***@***.***>
抄送: Yajing Song ***@***.***>; Mention ***@***.***>
主题: Re: [MicrosoftDocs/dynamics-365-unified-operations-public] Provisioning guide link is not available (Issue #4303)

你通常不会收到来自 ***@***.******@***.***> 的电子邮件。了解这一点为什么很重要<https://aka.ms/LearnAboutSenderIdentification>

@ysong163<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fysong163&data=05%7C01%7C%7Ca08c004fa30b42adf9e108dad3a180da%7C9bc096abf225476e8e92260401469868%7C0%7C0%7C638054987853420070%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=GkBoJZTIXmpCGcncGufG37jakEk4OKIX%2FxFYDm0t3zs%3D&reserved=0> can you please share a screenshot of the issue you are facing?

―

**Comment by faix** [comment]
@ysong163 if you reply with an email we can't see the screenshots you shared. Please reply directly on the issue: https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/issues/4303

**Comment by ysong163** [comment]
Screenshot 1 :  Click the provisioning guide
![1](https://user-images.githubusercontent.com/119558686/205531452-9ef40be6-2de1-42d2-b0bc-497c2961588d.png)
Screenshot 2 : The website skips to the counting page
![2](https://user-images.githubusercontent.com/119558686/205531455-92f239db-3228-44c9-a93b-34491f15b741.png)
Screenshot 3: When the countdown is over, it shows “gateway exception response”, and my download is empty.
![3](https://user-images.githubusercontent.com/119558686/205531459-e659e1c7-843d-4114-8ce0-3a7b01a6f413.png)

**Comment by faix** [comment]
Hi @ysong163,

Thanks for the screenshots. I have raised an incident with the team owning the FileExchange service. If you need the provisioning guide urgently please open a support case and mention this github issue.

**Comment by faix** [comment]
@ysong163 is your issue resolved?

**Comment by ysong163** [comment]
Hello,
Thank you for your help.
The document still cannot be downloaded directly through the website, but I got it from IT support team.
