### ISSUE TITLE
Is there a Yammer group for the Vendor Invoice Capture solution preview?

### ISSUE THREAD

**Issue by fwilkinson** [MicrosoftDocs/dynamics-365-unified-operations-public#4305]
Is there a Yammer group for the Vendor Invoice Capture solution preview?  I've got some feedback and questions..

Thank you,

Ford

**Comment by josaw1** [comment]
Thank you for your feedback. @twheelock can you please look into this?

**Comment by twheeloc** [comment]
@fwilkinson, you can find the Yammer group for Invoice capture here: https://www.yammer.com/dynamicsaxfeedbackprograms/#/threads/inGroup?type=in_group&feedId=84296204288
