### ISSUE TITLE
How to call Enqueue or Dequeue api using APIM 

### ISSUE THREAD

**Issue by dnyaneshwar-surywanshi** [MicrosoftDocs/dynamics-365-unified-operations-public#4307]
Currently working both API using azure function but I want to call both api through Azure APIM . can someone help me on this or any links which I can refer  .

**Comment by twheeloc** [comment]
@dnyaneshwar-surywanshi, thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
