### ISSUE TITLE
-replace for standard models

### ISSUE THREAD

**Issue by jaestevan** [MicrosoftDocs/dynamics-365-unified-operations-public#431]
If you're still on an old version you can use the -replace parameter to replace standard models (like Foundation) for overlayering.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1f45940-fe9f-2ac0-4e80-6783ca868f98
* Version Independent ID: b1022b6b-28ab-642c-a7d5-f2f2e4628101
* Content: [Export and import models - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-tools/models-export-import)
* Content Source: [articles/dev-itpro/dev-tools/models-export-import.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-tools/models-export-import.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RobinARH
* Microsoft Alias: **robadawy**

**Comment by ShylaThompson** [comment]
@jaestevan , Thanks for the information. If you want to add content to a topic directly in the future, you can click "Edit" on any topic to modify it and and submit a change request.  I've updated the topic and the changes will go live later today.
