### ISSUE TITLE
Is it true to have two entities for call reason and case in CRM separately?

### ISSUE THREAD

**Issue by Maralmf** [MicrosoftDocs/dynamics-365-unified-operations-public#4314]
There are calls that close in a few seconds and it seems they can have a separate entity named Call Reason.
In the incident entity or case, we track a customer request, question, or problem that does not close in the first call.
#dynamics-365

**Comment by josaw1** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle requests for the product here. Consider adding your request to the [Ideas site](https://experience.dynamics.com/ideas/). Also, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
