### ISSUE TITLE
Is fiddler part still working?

### ISSUE THREAD

**Issue by akasparas** [MicrosoftDocs/dynamics-365-unified-operations-public#4315]
[Enter feedback here]
I followed instructions in the fiddler part. But when copied contents of code variable to base64 website, it decoded to rubbish and I was not able to find out SID required.

I was able to recover SID required from SQL server query history, put into UserInfo table, logged in into the system. I captured these packets, got code=value, pasted value to base64decode.org website, and once again I got rubbish.

Therefore could you please check if this part is still working, and if not, please provide alternative way to achieve the same results. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 41f27bdd-7361-5030-a00d-db0674f6f9bf
* Version Independent ID: 228e03d2-5dc7-e428-d475-aecde408edfa
* Content: [Troubleshoot on-premises deployments - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/troubleshoot-on-prem)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/troubleshoot-on-prem.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/deployment/troubleshoot-on-prem.md)
* Service: ****
* Product: **dynamics-365**
* Technology: ****
* GitHub Login: @faix
* Microsoft Alias: **osfaixat**

**Comment by bishalgoswami** [comment]
Bug 774000 has been logged to address this issue.
