### ISSUE TITLE
Latest version of SqlPackage require additional command line parameters

### ISSUE THREAD

**Issue by artemt-yavica** [MicrosoftDocs/dynamics-365-unified-operations-public#4318]
This article should be updated based on new command line parameters 
https://techcommunity.microsoft.com/t5/azure-sql-blog/connection-security-improvements-in-sqlpackage-161/ba-p/3672758

Currently you will get an error while trying to export or import bacpac file using the latest version of SqlPackage 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8eb7ed3e-f7b9-e384-7308-516deda06bcc
* Version Independent ID: 3cd2e0d0-24fd-c019-eecc-8af6e7e7e66c
* Content: [Golden configuration promotion - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/dbmovement-scenario-goldenconfig)
* Content Source: [articles/fin-ops-core/dev-itpro/database/dbmovement-scenario-goldenconfig.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/database/dbmovement-scenario-goldenconfig.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by bishalgoswami** [comment]
Bug 774115 has been logged to address this issue.
