### ISSUE TITLE
Itemname in forecast dimensions

### ISSUE THREAD

**Issue by kurthatlevik-inspirit365** [MicrosoftDocs/dynamics-365-unified-operations-public#4320]
One question;  Why isn't item name possible to be shown in the forecast dimensions?  Very difficult to remember what a item number is.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 93e2a8a1-9d5d-d6b9-461e-aa7d6c3fecc6
* Version Independent ID: 6d605c6a-65d7-3eca-37a6-663236f5dec6
* Content: [Make manual adjustments to the baseline forecast - Supply Chain Management | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/supply-chain/master-planning/manual-adjustments-baseline-forecast)
* Content Source: [articles/supply-chain/master-planning/manual-adjustments-baseline-forecast.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/master-planning/manual-adjustments-baseline-forecast.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @t-benebo
* Microsoft Alias: **benebotg**

**Comment by bishalgoswami** [comment]
Bug 774395 has been logged to address this issue.

**Comment by kamaybac** [comment]
@kurthatlevik-inspirit365 , This appears to be a feature request, so we have added it as such to our ideas portal. No documentation update is needed for now, so I'll close this issue here.
