### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by Kenneth202212** [MicrosoftDocs/dynamics-365-unified-operations-public#4322]
ExportToPackage JSON response says value: {value: ""} but it should be only one value node.

Also there are two "I will be required" that I suspect should be "it"

**Comment by johnmichalak** [comment]
12/14/22 - emailed Par and asked him to review the suggestions and update as appropriate.

**Comment by johnmichalak** [comment]
1/9/23 Followed up with PM again today to check on status of potential changes.
