### ISSUE TITLE
Minimum required permissions

### ISSUE THREAD

**Issue by fgehrke** [MicrosoftDocs/dynamics-365-unified-operations-public#4324]
The document [System requirements and prerequisites](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/dual-write/requirements-and-prerequisites.md) have no clear information about the minimum required permissions to dual-write work.

For example, on item 3.ii, when it says to add the app in the Azure Active Directory application on FnO. It is not clear which user ID should be used. We have already seen several issues because customers set any user and the integration will not work. Using the Admin user works. 

My request is that the documentation be clear about the minimum required permissions are required for these applications.

**Comment by johnmichalak** [comment]
12/14/22 Emailed Nathan asking him to review the suggestions to see if changes can be made.

**Comment by johnmichalak** [comment]
@fgehrke Thank you for letting us know. The author has published some changes to improve the documentation and has more changes on the way. Hopefully these will be helpful for you.
