### ISSUE TITLE
misleading text could cause confusion.  'transaction' should be 'payment token'

### ISSUE THREAD

**Issue by scott-tucker** [MicrosoftDocs/dynamics-365-unified-operations-public#4325]
This text is incorrect, I think.
**Delete data without archiving** - When this parameter is set to **Yes**, Commerce will delete (not archive) the transaction and signature capture data for all transactional records

It should say
**Delete data without archiving** - When this parameter is set to **Yes**, Commerce will delete (not archive) the payment tokens and signature capture data for all transactional records

It would improve clarity if the first usage of _transaction_ was also replaced with _payment token_. It's not as critical as it isn't saying that we will delete a transaction.  it's this text:

This article describes an archival job in Microsoft Dynamics 365 Commerce that can help free up space in the database by archiving credit card **transactions**. (payment tokens) is a better fit here also

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 480efd0a-174d-dae4-4bea-4ed51e393644
* Version Independent ID: 54c317b9-7f64-fc0c-03dd-b4c54121d23a
* Content: [Archive credit card transaction data - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/dev-itpro/archive-cc-data)
* Content Source: [articles/commerce/dev-itpro/archive-cc-data.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/archive-cc-data.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @BrianShook
* Microsoft Alias: **brshoo**

**Comment by bishalgoswami** [comment]
Bug 774996 has been logged to address this issue.

**Comment by BrianShook** [comment]
Pull Request 15358 created to resolve this item.
