### ISSUE TITLE
How can I add product Description in Vendor Rebate/ Trade Agreement/ Purchase Agreement?

### ISSUE THREAD

**Issue by liamneesangamer** [MicrosoftDocs/dynamics-365-unified-operations-public#4326]
Once I add the line by selecting **ItemCode = Table** and **Item Selection = 0018(Product Number)**, How user can see the Product Name/ Description

Lets say, I have created vendor agreement by adding 100 items, as a user how can he see the Product Name, Even in Trade Agreement and also purchase agreement

Microsoft need to consider this, once the user to open any agreement, **user need to know what is the product name. That's the main purpose and higher priority**

I could not find the **Product name field in Insert column**. If i am wrong, please let me know.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fc013240-a3e2-f617-1100-fd7da91b7fa4
* Version Independent ID: 731c8752-d1e9-3a39-63e1-c29eaa158579
* Content: [Vendor rebates - Supply Chain Management | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/supply-chain/procurement/vendor-rebates)
* Content Source: [articles/supply-chain/procurement/vendor-rebates.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/procurement/vendor-rebates.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @GalynaFedorova
* Microsoft Alias: **gfedorova**

**Comment by bishalgoswami** [comment]
Bug 774995 has been logged to address this issue.

**Comment by bishalgoswami** [comment]
Bug 778023 has been logged to address this issue.

**Comment by GalynaFedorova** [comment]
It is not a bug. It's a feature request. There is already idea logged about it, you can vote: https://experience.dynamics.com/ideas/idea/?ideaid=682db9d3-9124-ed11-b5cf-0003ff45cf23
