### ISSUE TITLE
"Enable bank revaluation globally without a parameter" is the correct feature name

### ISSUE THREAD

**Issue by MrHenrikLevinson** [MicrosoftDocs/dynamics-365-unified-operations-public#4328]
Change from:
If you are assigned to the System Administrator role or Feature Manager role, you can eliminate this step by enabling the feature named Enable bank revaluation without a parameter in the Feature management workspace.
To:
If you are assigned to the System Administrator role or Feature Manager role, you can eliminate this step by enabling the feature named Enable bank revaluation globally without a parameter in the Feature management workspace.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5db8339d-d413-8c75-8114-43232b17b1b0
* Version Independent ID: e985afc9-3536-504f-89b2-e61492e157aa
* Content: [Bank foreign currency revaluation - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/cash-bank-management/bank-revaluation)
* Content Source: [articles/finance/cash-bank-management/bank-revaluation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/cash-bank-management/bank-revaluation.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @angelad116
* Microsoft Alias: **angelading**

**Comment by bishalgoswami** [comment]
Bug 774994 has been logged to address this issue.

**Comment by twheeloc** [comment]
@MrHenrikLevinson, thank you for the feedback. The topic has been updated.
