### ISSUE TITLE
Straight line depreciation of a modified fixed asset example needs an update

### ISSUE THREAD

**Issue by gebaluta** [MicrosoftDocs/dynamics-365-unified-operations-public#4330]
Notice that in the table for "Example: Straight line depreciation of a modified fixed asset" section, the Net Book Value is 10.000 in the second column, but 11.000 in the 3rd one.
Please, either add 1000 to the Net Book Value amount noted in the 2nd column or remove 1000 from the 3rd column and make sure to update all rows; accordingly, otherwise, the calculations become a bit confusing.

![image](https://user-images.githubusercontent.com/120671509/207923600-738bbbe5-af5a-4f90-8271-f504b914d911.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4c1edb75-2175-e4e7-037d-ca464907e91a
* Version Independent ID: e0880194-76a1-baa6-7d4c-1876909ce05a
* Content: [Straight line service life depreciation - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/fixed-assets/straight-line-service-life-depreciation)
* Content Source: [articles/finance/fixed-assets/straight-line-service-life-depreciation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/fixed-assets/straight-line-service-life-depreciation.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @moaamer
* Microsoft Alias: **moaamer**

**Comment by moaamer** [comment]
There is no issue the table, the example is based on the above example, and the first record in the second example is consistent with the above example. 

We showed the detailed calculation in the first example, however in the second example we showed the net effect only. 
Please check the example from execution on D365F.
![image](https://user-images.githubusercontent.com/28600824/208940674-83ea64bc-838b-44fb-96c8-245d73c10f7f.png)
