### ISSUE TITLE
Possibility to restrict access to transactions without XDS

### ISSUE THREAD

**Issue by MathildeCramer** [MicrosoftDocs/dynamics-365-unified-operations-public#4337]
Right now it is not possible to restrict what invoices you can see as a user when you have access to vendors and customer transactions. It can be solved by using XDS, but if you do not wish to use XDS it is not possible to restrict this access. Furthermore, it is not possible for the system to track/log who has viewed an invoice. 

Because you can't restrict who can see what invoices, you are risking having a GDPR breach. Meaning that right now, everyone can see all invoices if you have the access to view invoices. If any of these invoices have some sensitive information in them, it is a GDPR breach that everyone can see this information and not just the person who has approved the invoice

Therefore, I think this is a development point you should look into and should be a part of the standard system to be GDPR compliant. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3a953fbe-ec7f-9984-42f8-3c88248761a1
* Version Independent ID: 4b40257c-e071-b131-31ac-1dcdbe8d995b
* Content: [Extensible data security policies - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/extensible-data-security-policies)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/extensible-data-security-policies.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/sysadmin/extensible-data-security-policies.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Peakerbl
* Microsoft Alias: **peakerbl**

**Comment by bishalgoswami** [comment]
Bug 775616 has been logged to address this issue.

**Comment by Peakerbl** [comment]
XDS is currently the only supported option for record/row level security and this would make it possible to comply with regulations etc. when this is required. 

For information about who has accessed sensitive data. Here is the current capability: [Manage access to sensitive data](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/gdpr/gdpr-auditing-sensitive-data). This will not meet your requirements, so please consider voting for this idea to influence our roadmap: [Log read-access to sensitive data](https://experience.dynamics.com/ideas/idea/?ideaid=6e316ec9-5513-e911-9461-0003ff688f4c#).
