### ISSUE TITLE
Incorporating better scenario/example including more than 1 month and financial close is being performed and what if financial period close is not performed.

### ISSUE THREAD

**Issue by Harsh-Vaid** [MicrosoftDocs/dynamics-365-unified-operations-public#4341]
The current example explains the scenario of the initial month. Assuming after the Inventory period closure at month end and further transactions are posted to the following month, how the recalculation and cost adjustment will be performed? Will it take the closed period financial receipt transaction or will it take the closing period financial qty and cost, then look for the financial receipt transaction posted in the open period and then post the cost adjustment?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4fa882cb-d260-6ff0-dcfe-0319a88bb61b
* Version Independent ID: 00d1058a-d550-3f04-1f4a-947d92dee7d9
* Content: [Weighted average with physical value and marking - Supply Chain Management | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/supply-chain/cost-management/weighted-average-physical-value-marking)
* Content Source: [articles/supply-chain/cost-management/weighted-average-physical-value-marking.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/cost-management/weighted-average-physical-value-marking.md)
* Service: **dynamics-365-supply-chain**
* GitHub Login: @JennySong-SH
* Microsoft Alias: **yanansong**

**Comment by bishalgoswami** [comment]
Bug 776106 has been logged to address this issue.
