### ISSUE TITLE
XML file not found

### ISSUE THREAD

**Issue by AnandGoel813** [MicrosoftDocs/dynamics-365-unified-operations-public#4343]
Hi Team,

It is mentioned on the page that the XML file should be uploaded to the 'fiscal document provider' and 'fiscal connector'. But where can we get the XML file from is not mentioned? Request to kindly help in getting the source from where we can download the XML file.

Thanks,
Anand Goel
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fc461976-7d1e-a329-750e-3eda7779be8d
* Version Independent ID: ac0058ae-56b9-5660-209f-b1ad6727ca57
* Content: [Set up the fiscal integration for Commerce channels - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/localizations/setting-up-fiscal-integration-for-retail-channel)
* Content Source: [articles/commerce/localizations/setting-up-fiscal-integration-for-retail-channel.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/localizations/setting-up-fiscal-integration-for-retail-channel.md)
* Service: **dynamics-365-commerce**
* GitHub Login: @EvgenyPopovMBS
* Microsoft Alias: **josaw**

**Comment by EvgenyPopovMBS** [comment]
Hello,
For fiscal integration samples provided by Microsoft, the configuration files can be found in Commerce SDK on GitHub. The exact location depends on the sample and is noted in the corresponding documentation article. For example, for Italy it can be found via the following link:  [Set up the registration process](https://learn.microsoft.com/en-us/dynamics365/commerce/localizations/emea-ita-fpi-sample#set-up-the-registration-process).
Hope this helps.
Best regards,
Evgeny.
