### ISSUE TITLE
prerequisites 

### ISSUE THREAD

**Issue by vaidotasr** [MicrosoftDocs/dynamics-365-unified-operations-public#4344]
Global prerequisities required for all channel types  -- prerequisites not prerequisities 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9188d5e4-c6f8-d08d-d301-e361d1d1206c
* Version Independent ID: d95ec046-aa84-a704-8ae0-4d95f0799356
* Content: [Channel setup prerequisites - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/channels-prerequisites)
* Content Source: [articles/commerce/channels-prerequisites.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/channels-prerequisites.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @samjarawan
* Microsoft Alias: **samjar**

**Comment by bishalgoswami** [comment]
Bug 776262 has been logged to address this issue.

**Comment by josaw1** [comment]
Thank you for your comment. I fixed the typo and it will go live today.
