### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by vaidotasr** [MicrosoftDocs/dynamics-365-unified-operations-public#4346]
In the navigation pane, go to Modules > Retail and commerce > Channel Setup > Organization hierarchies.

No Organization hierarchies in Channel Setup

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0b50b086-841c-6d20-9b83-76f4649e459b
* Version Independent ID: 04ba3e71-d141-feea-606d-10c3b187a18d
* Content: [Set up organization hierarchies - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/channels-org-hierarchies)
* Content Source: [articles/commerce/channels-org-hierarchies.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/channels-org-hierarchies.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @samjarawan
* Microsoft Alias: **samjar**

**Comment by bishalgoswami** [comment]
Bug 776279 has been logged to address this issue.

**Comment by josaw1** [comment]
@ashishmsft can you please review?

**Comment by josaw1** [comment]
This will be updated later today. Thank you!
