### ISSUE TITLE
Deprecated 

### ISSUE THREAD

**Issue by abueiddev** [MicrosoftDocs/dynamics-365-unified-operations-public#4349]
Hello, 

This document is out of date, using sqlpackage.exe is not supporting anymore!! wasting 8 days with the support team just to find out sqlpackage.exe is not supporting to migrate the data, we should use ax2102 data upgrade utility.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 52e9b65e-a05e-73c4-6e78-280c8068e0e2
* Version Independent ID: b640a8a7-2ff9-bca6-7317-beba3a5d48d1
* Content: [Move LCS implementation projects from on-premises to the cloud - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/move-on-prem-to-cloud)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/move-on-prem-to-cloud.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/lifecycle-services/move-on-prem-to-cloud.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @MartinWalkerDynSA
* Microsoft Alias: **marwalke**

**Comment by bishalgoswami** [comment]
Bug 16668782 has been logged to address this issue.
