### ISSUE TITLE
How to define physical dimension for product variant?

### ISSUE THREAD

**Issue by liamneesangamer** [MicrosoftDocs/dynamics-365-unified-operations-public#4352]
I saw in D365 docs to define physical dimension for Product/ product master level. 

I need to define physical dimension (height, width, weight, depth, volume) for product variant level, for some product each variant may have same physical dimension. 

But most of the product's variant the physical dimensions will not be the same. so, where I define those things to maintain in the warehouse management and delivery services 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0b91cd85-29f2-583e-f577-90ba7b80b7ec
* Version Independent ID: a0d49357-1c3f-d25d-cb30-7261916b5190
* Content: [Set different dimensions for packing and storage - Supply Chain Management | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/supply-chain/warehousing/packing-vs-storage-dimensions)
* Content Source: [articles/supply-chain/warehousing/packing-vs-storage-dimensions.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/warehousing/packing-vs-storage-dimensions.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @Mirzaab
* Microsoft Alias: **mirzaab**

**Comment by bishalgoswami** [comment]
Bug 776829 has been logged to address this issue.

**Comment by kamaybac** [comment]
@liamneesangamer , thank you for contacting us about this issue. Unfortunately, the functionality you are asking about isn't currently available in the system. We already have a request for this functionality on our ideas portal, so we are considering it for a future version. You can view, vote, and comment on this idea here: https://experience.dynamics.com/ideas/idea/?ideaid=6cfc9748-ab2d-e811-bbd3-0003ff68ba15
