### ISSUE TITLE
Mistake in "Create a warranty item"

### ISSUE THREAD

**Issue by vaidotasr** [MicrosoftDocs/dynamics-365-unified-operations-public#4358]
https://learn.microsoft.com/en-us/dynamics365/commerce/extended-warranty#create-a-warranty-item 

5. In the Product service type field, select Service.  --- should be Warranty,  not Service type. 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 590de02f-38f7-eba4-e260-e65c4ab48420
* Version Independent ID: 64b21090-1074-18f5-957f-f5d498c6db3e
* Content: [Create and configure extended warranties - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/extended-warranty)
* Content Source: [articles/commerce/extended-warranty.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/extended-warranty.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by bishalgoswami** [comment]
Bug 777587 has been logged to address this issue.

**Comment by josaw1** [comment]
Thank you for your feedback. This will be fixed today.
