### ISSUE TITLE
code example of the keyword flush is invaid

### ISSUE THREAD

**Issue by sebastianstrefel** [MicrosoftDocs/dynamics-365-unified-operations-public#4359]
The code example of the keyword **flush** is invaid and will occurs a compiler error.

It should be **flush YourTable;** instead **YourTable ytBuffer; flush ytBuffer;**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f5857659-f5cd-b687-8f59-d619bfa0595b
* Version Independent ID: 7ce52bf5-267f-d135-908e-e3ea1cdbcb91
* Content: [X++ syntax - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-ref/xpp-syntax)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-ref/xpp-syntax.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/dev-ref/xpp-syntax.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by bishalgoswami** [comment]
Bug 777597 has been logged to address this issue.

**Comment by v-emilypr** [comment]
Hi @twheeloc, I removed DhurataJ' from the assignees list. I think you were looking for someone else perhaps. Thank you :)

**Comment by josaw1** [comment]
This fix will be published today. Thank you.
