### ISSUE TITLE
Mapping of CRM entity (custom lookup field) giving error

### ISSUE THREAD

**Issue by ibrahim-87** [MicrosoftDocs/dynamics-365-unified-operations-public#436]
When we try to map CRM entity custom fields of type "Lookup" from D365 for Sales(CRM) to D365 finance and operation(AX) it's always giving this error on exporting "CRM export failure - Object reference not set to an instance of an object".

Note: it only happens for CRM Entity custom fields of type "Lookup", for other custom fields its working fine and synced to AX successfully.
![crm custom lookup field export error](https://user-images.githubusercontent.com/39947982/46300213-caf60380-c5ab-11e8-83db-0e68faf7d4b3.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00a92571-a3b9-1d9f-438f-12725913b08f
* Version Independent ID: 331fd24c-17ce-1851-5ca6-123e085d756a
* Content: [Synchronization of sales orders directly between Sales and Finance and Operations - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/sales-marketing/sales-order-template-mapping-direct-two-ways)
* Content Source: [articles/supply-chain/sales-marketing/sales-order-template-mapping-direct-two-ways.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/sales-marketing/sales-order-template-mapping-direct-two-ways.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @ChristianRytt
* Microsoft Alias: **crytt**

**Comment by tonyafehr** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support).
