### ISSUE TITLE
Duplicated step in "Configure channels to use Commerce Scale Unit" section

### ISSUE THREAD

**Issue by cesh13** [MicrosoftDocs/dynamics-365-unified-operations-public#4369]
In section: **Configure channels to use Commerce Scale Unit**

Step 3 contains a section that gets repeated on step 4, here is how it is:

3. On the Retail channel FastTab, select Add, and then select your retail channel in the drop-down list.
4. Select Add, and then select your online channel in the drop-down list.

I think that step 4 could be removed, since it contains the exact same procedure described in step 3.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 50f98d51-e924-ddfa-0613-738a5b22de92
* Version Independent ID: 42f8aca8-4569-8032-241f-5d3e25cf15a3
* Content: [Initialize Commerce Scale Unit (cloud) - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/initialize-retail-channels)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/Initialize-Retail-Channels.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/deployment/Initialize-Retail-Channels.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @jashanno
* Microsoft Alias: **jashanno**

**Comment by cesh13** [comment]
I see step 4 mentions online channel, which I would assume is the difference between step 3 and step 4, so I think this might not be an issue after all.

**Comment by bishalgoswami** [comment]
Bug 778022 has been logged to address this issue.

**Comment by josaw1** [comment]
Fix will be published today.
