### ISSUE TITLE
Azure DevOps sync 

### ISSUE THREAD

**Issue by OksanaKovaliova** [MicrosoftDocs/dynamics-365-unified-operations-public#437]
Hi, pictures for 'Azure DevOps sync' operations are still 'VSTS sync' :) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1804282-0c48-6305-c6b2-b31dec2727df
* Version Independent ID: 2650812b-ab37-47ef-c103-a8a094cc8fce
* Content: [Synchronize BPM libraries with Azure DevOps - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/synchronize-bpm-vsts)
* Content Source: [articles/dev-itpro/lifecycle-services/synchronize-bpm-vsts.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/lifecycle-services/synchronize-bpm-vsts.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @kfend
* Microsoft Alias: **ntecklu**

**Comment by tonyafehr** [comment]
Thank you bringing this to our attention. We'll be sure to update these screenshots to reflect the branding change.
