### ISSUE TITLE
Lithuanian feature LT-00007 is not listed

### ISSUE THREAD

**Issue by TimoTenni** [MicrosoftDocs/dynamics-365-unified-operations-public#4378]
Lithuanian feature LT-00007 Customer vendor inter reconciliation report (LT) must be listed on this page including instructions how to use the feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d36a31dd-ae4b-57f3-ea89-2cfa0db14f42
* Version Independent ID: 7d0aeb6e-296d-15ce-0904-de2c7a3311d0
* Content: [Lithuania overview - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/localizations/lithuania)
* Content Source: [articles/finance/localizations/lithuania.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/lithuania.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **kfend**

**Comment by bishalgoswami** [comment]
Bug 0 has been logged to address this issue.
