### ISSUE TITLE
hi, under account type is ledger, paragraph to override tax direction is confusing. user was thinking that is vendor/customer account type was included in journal tax direction will not be override. 

### ISSUE THREAD

**Issue by anboudin** [MicrosoftDocs/dynamics-365-unified-operations-public#4379]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3aaea6b3-d996-eb5c-0a4e-82454d5a1bf0
* Version Independent ID: 523a07d8-d3b5-eba1-4a5d-f5c6c3f90448
* Content: [Sales tax calculation on general journal lines - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/general-ledger/sales-tax-calculation-on-general-journal)
* Content Source: [articles/finance/general-ledger/sales-tax-calculation-on-general-journal.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/general-ledger/sales-tax-calculation-on-general-journal.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @EricWangChen
* Microsoft Alias: **wangchen**

**Comment by anboudin** [comment]
override tax direction will work for all journal transaction whatever account type selected. 

Override tax direction does not work on sales order nor on purchase order. 

Whatever the tax direction setup on ledger account it will be applied on journal transactions.

**Comment by bishalgoswami** [comment]
Bug 785591 has been logged to address this issue.

**Comment by kfend** [comment]
@anboudin - Thanks for the feedback. The article has been updated and the changes will go live later today.
