### ISSUE TITLE
Maintain Planned Orders

### ISSUE THREAD

**Issue by MCFCMOOSE** [MicrosoftDocs/dynamics-365-unified-operations-public#438]
This article is supposed to be relevant to D365 but the last paragraph suggests you can 'Right-click on a planned order .....', which is incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5be450a-a347-1c64-cfe6-b7e61bece0ea
* Version Independent ID: a63778a5-7e69-2cd1-423d-99d04b59d654
* Content: [Maintain planned orders - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/master-planning/maintain-planned-orders)
* Content Source: [articles/supply-chain/master-planning/maintain-planned-orders.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/master-planning/maintain-planned-orders.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @roxanadiaconu
* Microsoft Alias: **roxanad**

**Comment by tonyafehr** [comment]
Thank you for bringing this to our attention. I will remove the incorrect reference to "right-click" so that the procedure reflects the current Dynamics 365 for Finance & Operations user experience.
