### ISSUE TITLE
Incorrect job numbers

### ISSUE THREAD

**Issue by altf4forhelp** [MicrosoftDocs/dynamics-365-unified-operations-public#4384]
"and then run the Registers (1070) and Channel configuration (1090) jobs." has job numbers swapped.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: da67f7f4-fccf-05ad-31ac-123cc2f95eb3
* Version Independent ID: da67f7f4-fccf-05ad-31ac-123cc2f95eb3
* Content: [Migrate Modern POS to Store Commerce - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/dev-itpro/pos-extension/migrate-mpos-store-commerce)
* Content Source: [articles/commerce/dev-itpro/pos-extension/migrate-mpos-store-commerce.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/pos-extension/migrate-mpos-store-commerce.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by bishalgoswami** [comment]
Bug 785588 has been logged to address this issue.

**Comment by josaw1** [comment]
Thank you for the feedback.
@bicyclingfool can you please confirm?

**Comment by johnmichalak** [comment]
@altf4forhelp Thank you for your feedback. The changes have been published.
