### ISSUE TITLE
MT940 is moved to ER reporting now.

### ISSUE THREAD

**Issue by d47447** [MicrosoftDocs/dynamics-365-unified-operations-public#4385]
[Enter feedback here]

Dear Team, I am not sure if this process is still valid as MT940 bank recon moved to ER reporting. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 84ddda24-328c-d279-f2e2-f0a61d0ad639
* Version Independent ID: 67df07ad-1695-b69a-dbcf-00de259afb25
* Content: [Advanced bank reconciliation MT940 Import – Composite data entity upgrade - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/cash-bank-management/advanced-bank-reconciliation-mt940-data-entity-upgrade-steps)
* Content Source: [articles/finance/cash-bank-management/advanced-bank-reconciliation-mt940-data-entity-upgrade-steps.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/cash-bank-management/advanced-bank-reconciliation-mt940-data-entity-upgrade-steps.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @angelad116
* Microsoft Alias: **angelading**

**Comment by bishalgoswami** [comment]
Bug 785587 has been logged to address this issue.

**Comment by sunfzam** [comment]
@twheeloc , I checked with team, this whole document should be deleted. As reporter mentioned, MT940 bank recon moved to ER reporting. The configuration in this document is not needed any more.

**Comment by twheeloc** [comment]
@d47447, thank you for the feedback. This topic will be removed.
