### ISSUE TITLE
Please use Links 

### ISSUE THREAD

**Issue by JuergenRoos** [MicrosoftDocs/dynamics-365-unified-operations-public#4386]
This description is not helpfull. Its a web portal so please give me the link and let me noth wounder about which vavigation pane you are talking....

"Go to Navigation pane > Modules > Organization administration > Organizations > Organization hierarchies."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 47255864-7134-164c-d1dd-c2dafde92c53
* Version Independent ID: 59d4618f-49c3-a61c-e993-26af59c4a551
* Content: [Create an organization hierarchy - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/organization-administration/tasks/create-organization-hierarchy)
* Content Source: [articles/fin-ops-core/fin-ops/organization-administration/tasks/create-organization-hierarchy.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/organization-administration/tasks/create-organization-hierarchy.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @sericks007
* Microsoft Alias: **sericks**

**Comment by josaw1** [comment]
Thanks for the feedback. We currently don't support links from documentation to the product.
