### ISSUE TITLE
Translation in Japanese

### ISSUE THREAD

**Issue by ShuheiKajii** [MicrosoftDocs/dynamics-365-unified-operations-public#4387]
[フィードバックをこちらに入力してください]
The translation for "over delivery" is not same as the real name in d365.
d365 Japanese translation is 超過 ,not 過剰.
Thank you.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 learn.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: e4687f34-942a-38df-24c6-c52cc700b16e
* Version Independent ID: 9487eeeb-4138-8027-74f1-26b667dadb49
* Content: [過剰/過少トランザクション - Supply Chain Management | Dynamics 365](https://learn.microsoft.com/ja-jp/dynamics365/supply-chain/landed-cost/over-under-transactions)
* Content Source: [articles/supply-chain/landed-cost/over-under-transactions.md](https://github.com/MicrosoftDocs/Dynamics-365-Operations.ja-jp/blob/live/articles/supply-chain/landed-cost/over-under-transactions.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @Weijiesa
* Microsoft Alias: **weijiesa**

**Comment by bishalgoswami** [comment]
Bug 785586 has been logged to address this issue.

**Comment by vivimills** [comment]
I have submitted this feedback to my vendor for linguistic evaluation.
