### ISSUE TITLE
AX2012

### ISSUE THREAD

**Issue by Arsenia** [MicrosoftDocs/dynamics-365-unified-operations-public#439]
A bit strange, that AX2012 content is mixed together with D365 F&O topics

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3d645ca-b551-53d7-6156-86c6822975da
* Version Independent ID: 814c625e-202e-ba34-3120-99265859e78c
* Content: [Track user sign-ins - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/user-logins)
* Content Source: [articles/dev-itpro/lifecycle-services/user-logins.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/lifecycle-services/user-logins.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @manalidongre
* Microsoft Alias: **sarvanis**

**Comment by OksanaKovaliova** [comment]
Sorry, opened a case by mistake - did not understand from the beginning, that the next part of the article is about D365. Please, close the case
