### ISSUE TITLE
Article suggests that route can be created without specifying a site. This appears not to be possible

### ISSUE THREAD

**Issue by amit-365** [MicrosoftDocs/dynamics-365-unified-operations-public#4391]
In the sharing routes across sites section of this article, it is suggested that to create a shared route, the user shouldn't specify a site on the route itself. This doesn't appear to be possible and site is a mandatory field while creating a new route and a route cannot be created by keeping this field empty. This statement needs to be clarified.

**Comment by josaw1** [comment]
Thank you for your feedback. Can you please let us know which article you are referring to?
