### ISSUE TITLE
API methods

### ISSUE THREAD

**Issue by prorook** [MicrosoftDocs/dynamics-365-unified-operations-public#4392]
Removing the Internal access modifier on the API methods would be cool

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bc713847-41b4-039b-a2fe-90485769e96d
* Version Independent ID: a8a6d8ce-3f98-b83d-2644-2e0e8e51a5f4
* Content: [Build forms that fully utilize saved views - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/user-interface/understanding-saved-views)
* Content Source: [articles/fin-ops-core/dev-itpro/user-interface/understanding-saved-views.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/user-interface/understanding-saved-views.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by bishalgoswami** [comment]
Bug 785582 has been logged to address this issue.

**Comment by jasongre** [comment]
@prorook Thanks for the feedback! We would need more information about what you're trying to do and which APIs in particular you are referencing to evaluate whether we want to open any existing internal methods to be public.
