### ISSUE TITLE
Store Commerce Setup Missing

### ISSUE THREAD

**Issue by Vekto** [MicrosoftDocs/dynamics-365-unified-operations-public#4393]
Hi, One thing not mentioned in these Doc's is the need for a dedicated hardware station to be configured in the stores for a Store Commerce application.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 38e79bc4-83cd-699b-8c3d-b713c909b90f
* Version Independent ID: 884433cd-c391-0018-9eb6-abfb494b99e5
* Content: [Set up Dynamics 365 Payment Connector for Adyen - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/dev-itpro/adyen-connector-setup#set-up-a-dynamics-365-register)
* Content Source: [articles/commerce/dev-itpro/adyen-connector-setup.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/adyen-connector-setup.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @Reza-Assadi
* Microsoft Alias: **rassadi**

**Comment by bishalgoswami** [comment]
Bug 785581 has been logged to address this issue.

**Comment by johnmichalak** [comment]
@Vekto Thank you for your feedback. Updates have been made to the documentation.
