### ISSUE TITLE
Low importance:   Images are from 2016! 

### ISSUE THREAD

**Issue by PGroothedde** [MicrosoftDocs/dynamics-365-unified-operations-public#4394]
[Voer hier feedback in]
The pictures shows are dated from 2016.
You can see that the images compared to D365F&O are old.
New environment images so it looks fresh and give the feeling of 2023!

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist voor de koppeling learn.microsoft.com ➟ GitHub-probleem.*

* ID: 89c1a6d1-3461-82e7-964d-54aa95a1ad93
* Version Independent ID: 7d9a39de-37e5-5d58-d6e6-bf705835b10f
* Content: [Create and automate user acceptance tests - Finance & Operations | Dynamics 365](https://learn.microsoft.com/nl-nl/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/using-task-guides-and-bpm-to-create-user-acceptance-tests?context=%2Fdynamics365%2Fcontext%2Fcommerce)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/using-task-guides-and-bpm-to-create-user-acceptance-tests.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/lifecycle-services/using-task-guides-and-bpm-to-create-user-acceptance-tests.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @gianugo
* Microsoft Alias: **gianura**

**Comment by josaw1** [comment]
@gianugo can you please review this article and images? Thanks.

**Comment by josaw1** [comment]
Thank you for your feedback. Due to lower priority, we are closing this issue.
