### ISSUE TITLE
Need “Subscribing” functionality to this page when new version are ready for use.

### ISSUE THREAD

**Issue by vicvon88** [MicrosoftDocs/dynamics-365-unified-operations-public#4396]
[Need “Subscribing” functionality to this page when new version are ready for use.]

Need “Subscribing” functionality to this page when new version are ready for use.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bdae22ec-65bb-17c1-dacc-e11b8ce3732c
* Version Independent ID: b5babe56-a72c-59c2-5ade-65dcbec2dd76
* Content: [What's new or changed in the Warehouse Management mobile app - Supply Chain Management | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/supply-chain/warehousing/whats-new-wma)
* Content Source: [articles/supply-chain/warehousing/whats-new-wma.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/warehousing/whats-new-wma.md)
* Service: **dynamics-365-supply-chain**
* GitHub Login: @Mirzaab
* Microsoft Alias: **mirzaab**

**Comment by bishalgoswami** [comment]
Bug 785951 has been logged to address this issue.

**Comment by josaw1** [comment]
Thank you for your feedback. This is a feature request that the team is aware of, but unfortunately, we don't have a timeline at this point.
