### ISSUE TITLE
Change description

### ISSUE THREAD

**Issue by pmjmg** [MicrosoftDocs/dynamics-365-unified-operations-public#4397]
In Default reason code, select a default reason code. The reason codes must have already been set up in Accounts receivable > Setup > Customer write-off reason codes or Accounts payable > Setup > Customer write-off reason codes. The Default settle remainder account will default to the account assigned to the write-off reason code.

Change to:

In Default reason code, select a default reason code. The reason codes must have already been set up in Accounts receivable > Setup > Customer write-off reason codes or Accounts payable > Setup > Vendor write-off reason codes. The Default settle remainder account will default to the account assigned to the write-off reason code.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3c8635ed-273e-839d-2f47-7f96cbe8324b
* Version Independent ID: 1c546cbd-7db6-a30e-b2e7-0e63d6d0e55d
* Content: [Settle remainder - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/cash-bank-management/settle-remainder)
* Content Source: [articles/finance/cash-bank-management/settle-remainder.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/cash-bank-management/settle-remainder.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @angelad116
* Microsoft Alias: **angelading**

**Comment by bishalgoswami** [comment]
Bug 785982 has been logged to address this issue.

**Comment by sericks007** [comment]
@twheeloc, can you find the appropriate owner for this.  Thanks!

**Comment by sunfzam** [comment]
> @twheeloc, can you find the appropriate owner for this. Thanks!

@twheeloc, I confirm the suggested change is valid.  Will you change it or I shall do it?

**Comment by twheeloc** [comment]
@pmjmg, thank you for the feedback. The content will be updated.
