### ISSUE TITLE
No such feature - Enable use of a numpad on the sign-in page

### ISSUE THREAD

**Issue by andypicking** [MicrosoftDocs/dynamics-365-unified-operations-public#4398]
Regarding Enable use of a numpad on the sign-in page mentioned in the article - there is no such feature in feature management (at least as of version 10.0.29). The documentation should be udpate to reflect what has happened to this feature.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bed68a7a-c3e1-09b2-0c44-e93fd3baaf27
* Version Independent ID: 893ade52-86f3-d847-9dc9-34e12a4c22b2
* Content: [Configure the production floor execution interface - Supply Chain Management | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/supply-chain/production-control/production-floor-execution-configure)
* Content Source: [articles/supply-chain/production-control/production-floor-execution-configure.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/production-control/production-floor-execution-configure.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @johanhoffmann
* Microsoft Alias: **johanho**

**Comment by bishalgoswami** [comment]
Bug 786268 has been logged to address this issue.

**Comment by johanhoffmann** [comment]
Hi @andypicking. This feature is available in release 10.0.31. You will see it when you upgrade to that version.
