### ISSUE TITLE
Mistake in example 2

### ISSUE THREAD

**Issue by MarianoAlcaraz** [MicrosoftDocs/dynamics-365-unified-operations-public#4401]
V is missing in line 7  : 
WHSInboundLoadPackingStructureLine3Entity must be WHSInboundLoadPackingStructureLine**V**3Entity

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 28fb49b8-8af5-f273-b3cb-65a12161afb9
* Version Independent ID: 5fb0a55d-5604-eb4d-8d9a-e4f89e53d6f7
* Content: [Import inbound ASNs through the V3 data entity - Supply Chain Management | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/supply-chain/warehousing/import-asn-data-entity)
* Content Source: [articles/supply-chain/warehousing/import-asn-data-entity.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/warehousing/import-asn-data-entity.md)
* Service: **dynamics-365-supply-chain**
* GitHub Login: @GalynaFedorova
* Microsoft Alias: **gfedorova**

**Comment by bishalgoswami** [comment]
Bug 786424 has been logged to address this issue.
