### ISSUE TITLE
MS Learn, Electronic Reporting Overview page: Supported scenarios, Building a data model section: Improvement request

### ISSUE THREAD

**Issue by JTWWI** [MicrosoftDocs/dynamics-365-unified-operations-public#4403]
For new learners, the direction:
"To become familiar with the details of this scenario, play the ER Design domain specific data model task guide (part of the 7.5.4.3 Acquire/Develop IT service/solution components (10677) business process)." yet providing no links leads to a difficult search through the entire Microsoft D365 documentation system.  Can a knowledgeable person please provide a direct link to:

- Can you use these task guides on a test system without impact to that system?
- Where is section 7.5.4.3 in what documentation system?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 76bee9cb-75ce-8b32-3f20-2b2b7d6fa75c
* Version Independent ID: ce4c6e71-365d-c08e-661e-df34ee1c5baa
* Content: [Electronic reporting (ER) overview - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/general-electronic-reporting?source=docs)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/general-electronic-reporting.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/analytics/general-electronic-reporting.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **filatovm**

**Comment by bishalgoswami** [comment]
Bug 786461 has been logged to address this issue.

**Comment by kfend** [comment]
I have updated this article with links to the task mentioned. Changes will show later today. Closing this as fixed.
