### ISSUE TITLE
Example 1 and Example 2 are showing same results in comparison to calculation as per system

### ISSUE THREAD

**Issue by Neeraj2912** [MicrosoftDocs/dynamics-365-unified-operations-public#4405]
Example 1 and Example 2 given in the page are showing same result. but as per the base consumer price index, the actual calculation done by the system is 

Example 1

On the Recurring contract billing parameters page, you set the Consumer price index calculation field to Base Consumer price index.

For the period January 1, 2021, the first escalation amount is calculated in the following way, based on the initial amount:

1,000 + (110.5 – 105.65) ÷ 105.65 × 1,000 = 1,045.91

For the period January 1, 2022, the escalation amount is calculated in the following way:

1,045.91+ (114.25 – 105.65) ÷ 105.65 × 1,000 = 1,127.31

The example 2 is working as per the system. 

Please verify the same at your end and make necessary changes.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 57d56d04-fe2b-063c-08a2-5cdc3c6d03cb
* Version Independent ID: 57d56d04-fe2b-063c-08a2-5cdc3c6d03cb
* Content: [Consumer price index schedule - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/accounts-receivable/cpischedules)
* Content Source: [articles/finance/accounts-receivable/cpischedules.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/accounts-receivable/cpischedules.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @JodiChristiansen
* Microsoft Alias: **jchrist**

**Comment by bishalgoswami** [comment]
Bug 787049 has been logged to address this issue.

**Comment by twheeloc** [comment]
@Neeraj2912, thank you for the feedback. The content will be updated.
