### ISSUE TITLE
Update for Store Commerce App

### ISSUE THREAD

**Issue by RobvanB** [MicrosoftDocs/dynamics-365-unified-operations-public#4406]
I think this page needs to be updated now that the Store Commerce App is released ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5fe3b43f-4c0c-8faf-e042-9a2aa5d15a42
* Version Independent ID: 45761895-ff98-5c6c-6aa3-ae27dacfaaeb
* Content: [Manage finance and operations updates and your custom code lifecycle - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/update-guide?context=%2Fdynamics365%2Fcontext%2Fcommerce)
* Content Source: [articles/fin-ops-core/dev-itpro/migration-upgrade/update-guide.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/migration-upgrade/update-guide.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by bishalgoswami** [comment]
Bug 787158 has been logged to address this issue.

**Comment by josaw1** [comment]
Thank you for your feedback. We are reviewing this article in its entirety and will update when ready.

**Comment by josaw1** [comment]
Fix will be published today.
