### ISSUE TITLE
White Paper link not working

### ISSUE THREAD

**Issue by Navneetkat** [MicrosoftDocs/dynamics-365-unified-operations-public#4409]
White paper link for - [Lean manufacturing: Capable to promise and kanban job scheduling](https://learn.microsoft.com/en-us/dynamics/s-e/) not working 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fc3403f8-b1b4-d6b8-09c6-0f1ed6660006
* Version Independent ID: cac73139-b8d5-6fe8-d7f6-81ad8afb1695
* Content: [Supply Chain Management home page - Supply Chain Management | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/supply-chain/)
* Content Source: [articles/supply-chain/index.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/index.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @kamaybac
* Microsoft Alias: **kamaybac**

**Comment by josaw1** [comment]
@kamaybac can you please fix the link mentioned above? Thanks.

**Comment by josaw1** [comment]
@kamaybac bumping this back onto your radar. Thanks.
