### ISSUE TITLE
Link to the Regression Suite Automation Tool installer

### ISSUE THREAD

**Issue by PalleAgermark** [MicrosoftDocs/dynamics-365-unified-operations-public#441]
Something is wrong with the way the link to the installer is rendered. Is shows as: [tool installer](&lt;http://download.microsoft.com/download/0/E/F/0EFA1032-EE5F-484E-A40A-7BF38561DE62/Regression Suite Automation Tool Installer.msi&gt;)

I can't see that anything is wrong in the markup, so maybe it is because the link points to an msi file!?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18d6a0b7-38dc-ddcd-c495-67e3b7498a7c
* Version Independent ID: 36a6bc94-6939-9daf-ad3d-4e0064258172
* Content: [Create user acceptance test libraries by using task guides and BPM - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/using-task-guides-and-bpm-to-create-user-acceptance-tests)
* Content Source: [articles/dev-itpro/lifecycle-services/using-task-guides-and-bpm-to-create-user-acceptance-tests.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/lifecycle-services/using-task-guides-and-bpm-to-create-user-acceptance-tests.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @kfend
* Microsoft Alias: **ntecklu**

**Comment by tonyafehr** [comment]
Thank you for bringing this to our attention. I will update the link so that it points to the correct file. It should be: http://download.microsoft.com/download/0/E/F/0EFA1032-EE5F-484E-A40A-7BF38561DE62/Regression%20Suite%20Automation%20Tool%20Installer.msi
