### ISSUE TITLE
Currency code for collection letter

### ISSUE THREAD

**Issue by MrHenrikLevinson** [MicrosoftDocs/dynamics-365-unified-operations-public#4419]
Hi

Point 7 "The default currency for the fee is the currency of the legal entity. This currency code can be different than the invoice currency." is not according to current design. You must set up a collection letter sequence for every currency that you what to create a collection. The system only creates collection letters for transaction in the currencies that are specified in a collection letter sequenze even if no fee is specified. 

Reference:
https://fix.lcs.dynamics.com/Issue/Details?bugId=638358&dbType=3&qc=bd3fd8dc0dee16c471fc76370001e7f2bde09b8406e9262aa0c9e6effa0d9bab 

/Henrik
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3cfba87c-a90a-7622-c9c0-0a454ff0708c
* Version Independent ID: f740a0a0-87a5-26f6-5c10-db50428e7d16
* Content: [Create a collection letter sequence - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/accounts-receivable/tasks/create-collection-letter-sequence)
* Content Source: [articles/finance/accounts-receivable/tasks/create-collection-letter-sequence.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/accounts-receivable/tasks/create-collection-letter-sequence.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @JodiChristiansen
* Microsoft Alias: **twheeloc**

**Comment by bishalgoswami** [comment]
Bug 788972 has been logged to address this issue.

**Comment by twheeloc** [comment]
@MrHenrikLevinson, thank you for the feedback. The topic has been updated.
