### ISSUE TITLE
Update emea-nor-satndard-audit-file-for-tax.md

### ISSUE THREAD

**Issue by niniculita** [MicrosoftDocs/dynamics-365-unified-operations-public#4421]
-If the Organization number is missing or the output XML file does not contain <RegistrationNumber>NA</RegistrationNumber>
        -Navigate to Org administration > Organizations > Legal entities- Select your legal entity > Bank account information and assign the Org number to Routing code field

**Comment by josaw1** [comment]
Hi @niniculita, do you have a specific comment on this article?

**Comment by niniculita** [comment]
Hello,
Under **Generate the Norwegian SAF-T Financial data report** at the bottom
could you add a note 
 -If the Organization number is missing or the output XML file does not contain <RegistrationNumber>NA</RegistrationNumber> Navigate to > Org administration > Organizations > Legal entities- Select your legal entity > Bank account information and assign the Org number to Routing code field

**Comment by kfend** [comment]
@liza-golub - Can you please take a look at this issue and update the article as needed? Thanks!

**Comment by johnmichalak** [comment]
Reached out to PM for guidance.

**Comment by liza-golub** [comment]
CD# [Content Deliverable 926460](https://msdyneng.visualstudio.com/FinOps/_workitems/edit/926460): NO - SAF-T documentation issue 4421
PR: https://github.com/MicrosoftDocs/Dynamics-365-Operations/pull/17976

**Comment by johnmichalak** [comment]
@niniculita Thank you for the feedback. This article has been updated. The changes should be available soon.
