### ISSUE TITLE
Omni-channel payments tab missing from version 10.0.29

### ISSUE THREAD

**Issue by MWC-Colin** [MicrosoftDocs/dynamics-365-unified-operations-public#4423]
This page and other pages makes reference to enabling the omni-channel payments on the Retail and Commerce > Headquarters setup > Parameters > Commerce shared parameters page. however this option is missing in version 10.0.29.

Is this a bug in 10.0.29 or has the option been moved or deprecated?

Can this page be updated to reflect how to set this option in 10.0.29 onwards?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: afc32bd1-d8ea-aff8-aa80-8c668dd26582
* Version Independent ID: 0f24c912-b1cf-3fd8-6a4e-5d57635d3513
* Content: [Linked refunds of previously approved and confirmed transactions - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/dev-itpro/linked-refunds)
* Content Source: [articles/commerce/dev-itpro/linked-refunds.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/linked-refunds.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @josaw1
* Microsoft Alias: **anupamar**

**Comment by josaw1** [comment]
Thank you for your feedback. @anupamar-ms can you please review?

**Comment by BrianShook** [comment]
@josaw1 I have PR 16101 created to address this request.
