### ISSUE TITLE
The solution P2C Version after installed showed 15.0.0.1 instead of 15.0.0.2

### ISSUE THREAD

**Issue by AmaryllisNguyen** [MicrosoftDocs/dynamics-365-unified-operations-public#4425]
Hi team, 
Regarding the package P2C Version 15.0.0.2 you shared on Github, we have installed the package in their environment, indeed the msdynce_AccountNumber index is removed but the version show is 15.0.0.1 instead of 15.0.0.2. Is there any other new version package for this solution or just mismatch of display only?
![POC_P2C_15 0 0 1](https://user-images.githubusercontent.com/82942425/217504975-c4bf869c-2bfc-42a4-8a4a-fcb7b178a670.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e03f9142-79d1-5b9f-cf2b-7e7d05009be5
* Version Independent ID: 732f7084-03fb-7a50-15a2-bedcc2ee7f6d
* Content: [Migrate Prospect to cash data from Data Integrator to dual-write - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/migrate-prospect-to-cash#install-the-last-dorman-version-of-the-data-integrator-prospect-to-cash-solution)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/migrate-prospect-to-cash.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/dual-write/migrate-prospect-to-cash.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @RamaKrishnamoorthy
* Microsoft Alias: **ramasri**

**Comment by bishalgoswami** [comment]
Bug 789626 has been logged to address this issue.
