### ISSUE TITLE
SQL MI

### ISSUE THREAD

**Issue by mundayn** [MicrosoftDocs/dynamics-365-unified-operations-public#4429]
Hi,

Instead of a Azure SQL DB, can I use a SQL MI?

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 33f75161-0776-a6c1-dc10-dc20ea26973f
* Version Independent ID: 55a81394-4606-745a-9fd2-59fb257d1086
* Content: [Bring your own database (BYOD) - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/export-entities-to-your-own-database#creating-a-sql-database)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/export-entities-to-your-own-database.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/analytics/export-entities-to-your-own-database.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Peakerbl
* Microsoft Alias: **peakerbl**

**Comment by bishalgoswami** [comment]
Bug 790211 has been logged to address this issue.
