### ISSUE TITLE
an error occurred. contact your administrator dynamics 365 fno ios

### ISSUE THREAD

**Issue by Hammanmohd** [MicrosoftDocs/dynamics-365-unified-operations-public#4430]
an error occurred. contact your administrator dynamics 365 fno ios
![image](https://user-images.githubusercontent.com/42575021/218304193-3e9b19a0-be51-4f56-aff9-5e8bd8f1b8f0.png)

**Comment by josaw1** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
