### ISSUE TITLE
Proactive quality update upcoming 10.0.31 Release-1 train schedule - table is not rendered correctly

### ISSUE THREAD

**Issue by maroweh** [MicrosoftDocs/dynamics-365-unified-operations-public#4432]
![image](https://user-images.githubusercontent.com/7677850/218419562-93e4c474-6966-41c6-8e17-b5199d9720ea.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6edd9a5f-8212-173c-16fb-8868c5d4b4d9
* Version Independent ID: 6edd9a5f-8212-173c-16fb-8868c5d4b4d9
* Content: [Proactive quality updates - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/quality-updates?context=%2Fdynamics365%2Fcontext%2Fcommerce#schedule)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/quality-updates.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/quality-updates.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @rashmansur
* Microsoft Alias: **rashmim**

**Comment by bishalgoswami** [comment]
Bug 790778 has been logged to address this issue.

**Comment by josaw1** [comment]
Fixed.
