### ISSUE TITLE
Commerce: Clean up email notification logs

### ISSUE THREAD

**Issue by anst84** [MicrosoftDocs/dynamics-365-unified-operations-public#4436]
https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/cleanuproutines

Documentation refer to this path, that do not exist in 10.0.31
Retail and Commerce > Retail and Commerce IT > Email and notifications > Clean up email notification logs

Is the cleanup feature removed, embedded into another job or missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 926b5538-8734-b2cf-7d77-21f35dbf0e98
* Version Independent ID: 219ba487-1689-e78c-773e-42d019f779f1
* Content: [Cleanup routines in Dynamics 365 Finance and Dynamics 365 Supply Chain Management - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/cleanuproutines)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/cleanuproutines.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/sysadmin/cleanuproutines.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @dvliegen
* Microsoft Alias: **dvliegen**

**Comment by bishalgoswami** [comment]
Bug 792585 has been logged to address this issue.

**Comment by DinahK-2SO** [comment]
Hello @anst84 , the feature "Clean up email notification logs" is available from 10.0.32
