### ISSUE TITLE
Doc page bug

### ISSUE THREAD

**Issue by meenulaul** [MicrosoftDocs/dynamics-365-unified-operations-public#4437]
[Enter feedback here]
In this session needs to be updated with below things https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/dual-write-troubleshooting-finops-upgrades#missing-table-columns-issue-on-maps

1 . Sign in to the VM needs to finance and operation app - we should remove VM from here
2.  Go to Workspaces > Data management, select the Framework parameters tile, and then, on the Table settings tab, select Refresh table list to refresh the tables.  -In this, refresh table list should be refresh entity page/

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0871caa7-dc4d-be11-ba10-63b985970c2e
* Version Independent ID: bf399f93-83a6-2d46-859c-6f192e44a442
* Content: [Troubleshoot dual-write issues in finance and operations apps - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/dual-write-troubleshooting-dual-write-module)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/dual-write-troubleshooting-dual-write-module.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/dual-write/dual-write-troubleshooting-dual-write-module.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @RamaKrishnamoorthy
* Microsoft Alias: **ramasri**

**Comment by bishalgoswami** [comment]
Bug 792652 has been logged to address this issue.

**Comment by josaw1** [comment]
@pvillads, can you please investigate.

**Comment by johnmichalak** [comment]
Reached out to PM for guidance.

**Comment by w-azure** [comment]
Article has been updated. Thank you.
