### ISSUE TITLE
Report generation limit not mentioned in public documentation

### ISSUE THREAD

**Issue by ipetrescu** [MicrosoftDocs/dynamics-365-unified-operations-public#4439]
[Enter feedback here]
Please consider adding the following section "What to expect once report generation request is submitted?" from the TSG to the public documentation: https://dev.azure.com/msdyneng/FinOps/_wiki/wikis/FinOps.wiki/43761/Monitor-report-generation-process-using-Report-Queue-Status?anchor=what-to-expect-once-report-generation-request-is-submitted%3F

Customers are not aware of the 5 reports running concurrently per environment and they raise performance related requests.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7c7fbb5d-08c2-e195-cda8-3aa141f51e6a
* Version Independent ID: 3789dfe4-495a-57d3-d4fc-d5684749cf08
* Content: [Generate financial reports - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/generate-financial-report?toc=%2Fdynamics365%2Ffinance%2Ftoc.json)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/generate-financial-report.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/analytics/generate-financial-report.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @jinniew
* Microsoft Alias: **aolson**

**Comment by bishalgoswami** [comment]
Bug 792907 has been logged to address this issue.

**Comment by twheeloc** [comment]
@ipetrescu, thank you for the feedback. The topic has been updated.
