### ISSUE TITLE
What is the difference between a Build environment and a Development Tier 1 environment?

### ISSUE THREAD

**Issue by JTWWI** [MicrosoftDocs/dynamics-365-unified-operations-public#4442]
This page has a table that lists the different types of environments and how they relate to the different tiers.
Would it be helpful to have a link to talk about the difference between a 'Build' environment and a 'Development' environment?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2402dfea-008a-c7bb-8a3b-1d0457a39665
* Version Independent ID: 4936afad-9a39-e65d-a00c-81246de632cb
* Content: [Environment planning - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/imp-lifecycle/environment-planning)
* Content Source: [articles/fin-ops-core/fin-ops/imp-lifecycle/environment-planning.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/imp-lifecycle/environment-planning.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @skaue-ms
* Microsoft Alias: **toskaue**

**Comment by bishalgoswami** [comment]
Bug 793613 has been logged to address this issue.

**Comment by johnmichalak** [comment]
The change has been reviewed and merged and will go live later today.
