### ISSUE TITLE
how to create your first order template

### ISSUE THREAD

**Issue by MSFTRANDY** [MicrosoftDocs/dynamics-365-unified-operations-public#4443]
There is no documentation on how to create your first order template as the "Create order template" does not show up under My Account > Order templates until you go through an items PDP page and add it to a template but are instead prompted to create an order template.  This is confusing and is NOT discussed anywhere on how to create your first one. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 918c4ec5-3bae-6efd-f25f-41d80f769b11
* Version Independent ID: 918c4ec5-3bae-6efd-f25f-41d80f769b11
* Content: [Place B2B website orders quickly - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/b2b/quick-bulk-orders)
* Content Source: [articles/commerce/b2b/quick-bulk-orders.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/b2b/quick-bulk-orders.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @ShalabhjainMSFT
* Microsoft Alias: **shajain**

**Comment by bishalgoswami** [comment]
Bug 793636 has been logged to address this issue.
