### ISSUE TITLE
Why are the F&O NuGet packages not hosted on a public endpoint?

### ISSUE THREAD

**Issue by ianjensenisme** [MicrosoftDocs/dynamics-365-unified-operations-public#4445]
Why are the F&O NuGet packages buried in the LCS asset library instead of exposed on a public endpoint? It seems a bit unreasonable to ask the X++ code admin to manually move the F&O NuGet packages from LCS to their own artifact endpoint every time there's an update, when the overwhelming majority of other package dependencies in a developer's world can be automatically updated just by referencing public package hosts, such as nuget.org.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 10459944-bcf8-c5fa-d180-9fb4bb3722da
* Version Independent ID: 29ae9d16-ed7c-92d8-0300-4fc46c777ddf
* Content: [Build automation that uses Microsoft-hosted agents and Azure Pipelines - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/hosted-build-automation)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/hosted-build-automation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/dev-tools/hosted-build-automation.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @gianugo
* Microsoft Alias: **gianura**

**Comment by bishalgoswami** [comment]
Bug 793926 has been logged to address this issue.

**Comment by twheeloc** [comment]
Thanks for your feedback. We have passed this feedback onto the product team for consideration.
