### ISSUE TITLE
Limitations that was solved in 10.0.17

### ISSUE THREAD

**Issue by kurthatlevik-inspirit365** [MicrosoftDocs/dynamics-365-unified-operations-public#4446]
I think it is save to remove described limitations that was solved in 10.0.17 :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 12a6fc14-5802-043a-299c-4c3a7f6ac438
* Version Independent ID: 68118450-ee3b-7e3e-8d6a-d27ada70bd26
* Content: [Revenue recognition reallocation - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/accounts-receivable/rev-rec-reallocation)
* Content Source: [articles/finance/accounts-receivable/rev-rec-reallocation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/accounts-receivable/rev-rec-reallocation.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @bking
* Microsoft Alias: **bking**

**Comment by bishalgoswami** [comment]
Bug 793925 has been logged to address this issue.

**Comment by twheeloc** [comment]
@kurthatlevik-inspirit365, thank you for the feedback. The topic has been updated.
