### ISSUE TITLE
Unable to load the extension package

### ISSUE THREAD

**Issue by mmoalla** [MicrosoftDocs/dynamics-365-unified-operations-public#4449]
Hello,
I'm facing issue in cloud pos : I download scale unit sample and build the project but when i put generated package files from scale unit project  for both RetailServer and CloudPos i get an error **Unable to load the extension package**

I copy the manifest created by Microsoft in extensions CloudPos folder without controls, views and so on 
but sill get the same error.

Could you please how to load extended package in Commerce SDK ?

**Comment by josaw1** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
