### ISSUE TITLE
Content update

### ISSUE THREAD

**Issue by OksanaKovaliova** [MicrosoftDocs/dynamics-365-unified-operations-public#445]
Hi, 

I followed this guide with open LCS project and found some differences:

1) User interaction chart - was not able to find it anywhere 
2) The User load section shows all the system users - do you mean all D365 users or such users as Batch service user, Retail server user, etc.?
3) SQL now tool - does not exist, I see 'Live View' and 'Queries' tabs instead
4) Looks like 'Environment' tab on 'Environment diagnostics' has been replaced with Health metrics
5) System diagnostic - is it called 'Full system diagnostics' now or ?
6) Would be good to have updated pictures 

Question:
Picture shows that Monitoring is smth within 60 seconds, why 'total number of deadlocks in a five-minute period' is related to Monitoring and not to diagnostics then?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c73b0eff-ab53-afb9-b3e2-40f94cb71a3e
* Version Independent ID: 069fa33b-6a69-2d29-908d-fca5ca0dc516
* Content: [Monitoring and diagnostics tools in Lifecycle Services (LCS) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/monitoring-diagnostics)
* Content Source: [articles/dev-itpro/lifecycle-services/monitoring-diagnostics.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/lifecycle-services/monitoring-diagnostics.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @manalidongre
* Microsoft Alias: **manado**

**Comment by tonyafehr** [comment]
Thanks for the feedback. I've asked the author to review your questions and comments. We'll work to enhance this topic and provide the information that you're looking for in a future update.
