### ISSUE TITLE
Base URL for No Altinn

### ISSUE THREAD

**Issue by RalucaLucia** [MicrosoftDocs/dynamics-365-unified-operations-public#4450]
Hi Team,

In the documentation we have here: https://learn.microsoft.com/en-us/dynamics365/finance/localizations/emea-nor-vat-return-setup#internet-address the Base URL we have to use for NO Altinn is: 
https://platform.tt02.altinn.no/authentication/api/v1/exchange/id-porten - for Sandbox and
https://platform.altinn.no/authentication/api/v1/exchange/id-porten - for Production

Since the test user has been changed, we are receiving an error message when we go to No Altinn and try to generate the access token if we use the Base URL: https://platform.tt02.altinn.no/authentication/api/v1/exchange/id-porten.
If we use the Base URL provided for NO ID-Porten: https://oidc-ver2.difi.no/idporten-oidc-provider, the issue is resolved and we can get the access.

Can you please check if this URL has to be changed in the documentation?
If this is the case, can you please check the Production URL as well? Should this be updated as well?

Please find attached the error we receive when we use the Base URL provided in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fad59b08-93b4-a4e7-471c-2d5043afdc48
* Version Independent ID: fad59b08-93b4-a4e7-471c-2d5043afdc48
* Content: [Prepare your environment to interoperate with ID-porten and Altinn web services - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/localizations/emea-nor-vat-return-setup)
* Content Source: [articles/finance/localizations/emea-nor-vat-return-setup.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/emea-nor-vat-return-setup.md)
* Service: **dynamics-365-finance**
* Product: ****
<img width="706" alt="2MmP8Zm6DH" src="https://user-images.githubusercontent.com/114916397/221546544-32c45301-8889-4db5-ae69-032e7fa16982.png">

* Technology: ****
* GitHub Login: @AdamTrukawka
* Microsoft Alias: **atrukawk**

**Comment by josaw1** [comment]
Thank you for your feedback. @AdamTrukawka can you please review?

**Comment by johnmichalak** [comment]
Reached out to PM for guidance.

**Comment by liza-golub** [comment]
This topic was recently updated with actual information.
Information in the comment is outdated
