### ISSUE TITLE
Code is not valid

### ISSUE THREAD

**Issue by mekins-cs** [MicrosoftDocs/dynamics-365-unified-operations-public#4455]
It seems there's a mistake on your page. When I followed the steps to the letter, E-commerce threw errors about the newly created container module.  Should probably review these to be sure everything is accurate.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 72dced52-f106-b96d-db59-2ffec6c35170
* Version Independent ID: 5da1de7b-6657-54aa-98a9-6ac30f9b2473
* Content: [Create a layout container module - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/e-commerce-extensibility/create-layout-container)
* Content Source: [articles/commerce/e-commerce-extensibility/create-layout-container.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/e-commerce-extensibility/create-layout-container.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @samjarawan
* Microsoft Alias: **samjar**

**Comment by bishalgoswami** [comment]
Bug 795477 has been logged to address this issue.
