### ISSUE TITLE
Wrong reference to AX2012

### ISSUE THREAD

**Issue by d47447** [MicrosoftDocs/dynamics-365-unified-operations-public#4458]
[Enter feedback here]

This article talks about D365FO but in content its referring to AX2012. 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0271ffd0-13d5-3fe8-587a-5d3bbefa5c87
* Version Independent ID: ea735bbd-b214-c017-d376-8528876fc1cc
* Content: [Consume external web services - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/consume-external-web-service)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/consume-external-web-service.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/consume-external-web-service.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Peakerbl
* Microsoft Alias: **peakerbl**

**Comment by bishalgoswami** [comment]
Bug 796043 has been logged to address this issue.

**Comment by johnmichalak** [comment]
@d47447 The content if just contrasting with the way it used to work in AX2012. All the steps etc. are specific to D365.
