### ISSUE TITLE
URGENT fix required to link on this page

### ISSUE THREAD

**Issue by jimwillsher** [MicrosoftDocs/dynamics-365-unified-operations-public#4462]
[Enter feedback here]
Under Additional Resources section there is a link to Official GDPR site. Click it, it's probably not the site you thought you were looking for :) :) :)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 846e96c4-bb7a-f267-e099-1cbe76be5132
* Version Independent ID: 1e9e6e32-da47-f24e-e0f6-0929b566d6c7
* Content: [GDPR data requests for Lifecycle Services (LCS) - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/gdpr/gdpr-lcs)
* Content Source: [articles/fin-ops-core/dev-itpro/gdpr/gdpr-lcs.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/gdpr/gdpr-lcs.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by josaw1** [comment]
Thank you for the correction. This fix will go live today.
