### ISSUE TITLE
Best practices for editing Main account category values

### ISSUE THREAD

**Issue by gebaluta** [MicrosoftDocs/dynamics-365-unified-operations-public#4463]
Dear team,

I work in Microsoft Support for Dynamics 365 Finance and Operations.
A customer raised a support ticket, ID 2303030010001887, reporting that, after changing the Main Account Categories, the Row Definition for default Financial Reporting reports was not updated automatically.
I know that this is not possible since the values on those default FR reports are static (text fields), not dynamics fields. However, can we add a note on this documentation to officially state the Financial Reporting Report Definitions will have to be manually changed when you edit the Main Account Category name.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 847735ec-bba5-3d0c-e68c-20b457b07708
* Version Independent ID: 930742dc-0d0b-a5dc-15e5-4079450ac367
* Content: [Set up main account categories - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/general-ledger/tasks/set-up-main-account-categories)
* Content Source: [articles/finance/general-ledger/tasks/set-up-main-account-categories.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/general-ledger/tasks/set-up-main-account-categories.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @aprilolson
* Microsoft Alias: **aolson**

**Comment by bishalgoswami** [comment]
Bug 797255 has been logged to address this issue.

**Comment by twheeloc** [comment]
@gebaluta, thank you for the feedback. The topic has been updated and changes will be live later today.
