### ISSUE TITLE
Enable the page caching feature in picture

### ISSUE THREAD

**Issue by kurthatlevik-inspirit365** [MicrosoftDocs/dynamics-365-unified-operations-public#4467]
The checkfield "Enable the page caching feature" in Commerce site builder has been moved, so the picture does not reflect what is seen.  My recommendation is to just remove the picture showing where to find this "Enable render caching"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c90eb021-92b2-952c-6322-acb8e60934c6
* Version Independent ID: 79bff52e-fe46-e4c9-09d1-d54ab281015f
* Content: [Configure page caching - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/e-commerce-extensibility/page-caching)
* Content Source: [articles/commerce/e-commerce-extensibility/page-caching.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/e-commerce-extensibility/page-caching.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @samjarawan
* Microsoft Alias: **samjar**

**Comment by bishalgoswami** [comment]
Bug 797873 has been logged to address this issue.

**Comment by kurthatlevik-inspirit365** [comment]
PS!   Sam have moved to another team :-)

**Comment by josaw1** [comment]
Fix will go live today. Thanks.

**Comment by johnmichalak** [comment]
Reached out to PM for guidance.
