### ISSUE TITLE
When a project is imported from the Global scope to another project

### ISSUE THREAD

**Issue by OksanaKovaliova** [MicrosoftDocs/dynamics-365-unified-operations-public#447]
When a project is imported from the Global scope to another project, it's set to the Project scope - should it be 'when an asset is imported'? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2263405c-3c49-c28b-2e3e-b2a6acf850c4
* Version Independent ID: 5270e40a-07e2-1d0b-faff-f55c87c22ecb
* Content: [Asset library in Lifecycle Services (LCS) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/asset-library)
* Content Source: [articles/dev-itpro/lifecycle-services/asset-library.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/lifecycle-services/asset-library.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @manalidongre
* Microsoft Alias: **manado**

**Comment by tonyafehr** [comment]
Thanks for the feedback. I've asked the author to review your questions and comments. We'll work to enhance this topic and provide the information that you're looking for in a future update.

**Comment by tonyafehr** [comment]
Tracking bug logged: 255740
