### ISSUE TITLE
Wrong SDK referenced?

### ISSUE THREAD

**Issue by RobvanB** [MicrosoftDocs/dynamics-365-unified-operations-public#4472]
The first line of the article says:
"This article explains how to set up a build pipeline for the Retail software development kit (SDK) "

Should this not read like this:
This article explains how to set up a build pipeline for the COMMERCE software development kit (SDK)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d9cf3583-4ed2-d65e-967f-d5a9d6483365
* Version Independent ID: ec10375f-07f9-e027-d4ee-d6832c65d30e
* Content: [Set up a build pipeline for the independent-packaging SDK - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/dev-itpro/build-pipeline)
* Content Source: [articles/commerce/dev-itpro/build-pipeline.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/build-pipeline.md)
* Service: **dynamics-365-commerce**
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by josaw1** [comment]
Thank you for your comment. The changes will go live today.
