### ISSUE TITLE
Typo in the page

### ISSUE THREAD

**Issue by Lionel35000** [MicrosoftDocs/dynamics-365-unified-operations-public#4478]
Hello,

I think there is a little typo in the page. At the end of the page :
it is written : 
To set up the financial reconciliation functionality in headquarters, follow these steps.

it should be in my opinion : 
To set up the financial reconciliation functionality in store, follow these steps.

Best regards,
Lionel

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0943fd65-d4f5-2e3a-7ba1-98a8db9660db
* Version Independent ID: 75f6a0c0-b7ff-6836-464b-2dd4144ef994
* Content: [Cash management overview - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/cash-mgmt)
* Content Source: [articles/commerce/cash-mgmt.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/cash-mgmt.md)
* Service: **dynamics-365-commerce**
* GitHub Login: @ShalabhjainMSFT
* Microsoft Alias: **shajain**

**Comment by bishalgoswami** [comment]
Bug 800312 has been logged to address this issue.

**Comment by josaw1** [comment]
Thank you for your feedback. The topic is correct as written.
