### ISSUE TITLE
Realized gain formatting error

### ISSUE THREAD

**Issue by JoelLeichty** [MicrosoftDocs/dynamics-365-unified-operations-public#448]
" **"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06d9461f-5c28-c2ec-940a-514e206dda58
* Version Independent ID: 0785b254-f019-8b4c-abf7-94da7ddb2ca5
* Content: [Currency revaluation in a consolidation company - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/general-ledger/currency-revaluation-consolidation-company)
* Content Source: [articles/financials/general-ledger/currency-revaluation-consolidation-company.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/general-ledger/currency-revaluation-consolidation-company.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @ShylaThompson
* Microsoft Alias: **hminzner**

**Comment by tonyafehr** [comment]
Thanks Joel, I've updated the topic. We really appreciate feedback that helps us to improve our documentation.
