### ISSUE TITLE
Require clarity on the extensibility of Store Commerce App in Offline mode

### ISSUE THREAD

**Issue by 5fq** [MicrosoftDocs/dynamics-365-unified-operations-public#4488]
![image](https://user-images.githubusercontent.com/47292229/229556848-5b0bf435-aefd-4f90-8928-d8269d86e9c6.png)

Require clarity on the highlighted text. Based on the store commerce app documentation offline is supported. Does it mean the extension is not supported if the Store Commerce app is running in offline mode?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fcfc4928-bdf2-e112-bbb7-64605c80ba72
* Version Independent ID: 06fa8533-d429-9c15-b8a5-d7473fd8a292
* Content: [POS extension overview - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/dev-itpro/pos-extension/pos-extension-overview)
* Content Source: [articles/commerce/dev-itpro/pos-extension/pos-extension-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/pos-extension/pos-extension-overview.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by bishalgoswami** [comment]
Bug 802557 has been logged to address this issue.

**Comment by johnmichalak** [comment]
@5fq Thank you for the feedback. This document has been updated.
