### ISSUE TITLE
Instructed about formats to select confusing at setup section.

### ISSUE THREAD

**Issue by JTWWI** [MicrosoftDocs/dynamics-365-unified-operations-public#4489]
On this page, the initial section is "Set up the Electronic reporting configuration".
Step 5 is: "In the configuration list, find Advanced bank reconciliation statement model > ABR BAI2 format."

When you do this the Configurations FastTab table moves to show Configuration name "ABR BAI2 format".  This lives in data model "Advanced bank reconciliation statement model"

Step 6 instruction is "Select the BAI2 format."

Here is where confusion starts, the BAI2 format in the Configurations FastTab table belongs to the Data model called "Bank Statement Model for BAI2" under the "Bank statement model"

Note how the general sense of this section of the instruction is to pick a mapping format, but between Step 5 and Step 6 we're told to select two _different_ mappings from two _different_ models:
Model "Advanced bank reconciliation statement model" compared to "Bank Statement Model for BAI2"

Not sure if they want us to add both?  Or if we should just be picking the ABR BAI2 format.

When on a call with MS Support, the support person suggested I did not need the Bank Statement model.

Might be good to review this page and add some clarity perhaps?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 33ed78e0-bbee-3178-b448-2d86790f20bf
* Version Independent ID: 33ed78e0-bbee-3178-b448-2d86790f20bf
* Content: [Set up advanced bank reconciliation import by using Electronic reporting - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/accounts-payable/import-BAI2-ER)
* Content Source: [articles/finance/accounts-payable/import-BAI2-ER.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/accounts-payable/import-BAI2-ER.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @angelad116
* Microsoft Alias: **shpandey**

**Comment by bishalgoswami** [comment]
Bug 802624 has been logged to address this issue.

**Comment by twheeloc** [comment]
@JTWWI, thank you for the feedback. The article has been updated.

**Comment by JTWWI** [comment]
Excellent! Happy to help.
