### ISSUE TITLE
Some found issues/questions

### ISSUE THREAD

**Issue by OksanaKovaliova** [MicrosoftDocs/dynamics-365-unified-operations-public#449]
Some questions:
1) Merged package - can we use Retail package there? It was earlier reported, that Retail packages cannot be merged
2) For Release candidate package steps 2 and 4 contain 'Click Release candidate' - do we need to click this button twice? 
3) 'Sign off with issues' - is it the same as button 'Close with issues' from the screenshot? 
4) "if the folder name is ExecuteRunbook-b0c5c413-dae3-4a7a-a0c4-d558614f7e98-1_I0_R0, the step number is highlighted and is the number after the globally unique identifier (GUID)"  - is '1_I0_R0' used as Step number? I checked some logs and this number is always the same

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4008b2e3-4d1a-e146-8bdb-f39280124e9f
* Version Independent ID: 22f8390d-bb4d-1755-515c-7e7ebf1ddaae
* Content: [Apply updates to cloud environments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/deployment/apply-deployable-package-system)
* Content Source: [articles/dev-itpro/deployment/apply-deployable-package-system.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/deployment/apply-deployable-package-system.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @manalidongre
* Microsoft Alias: **manado**

**Comment by tonyafehr** [comment]
Thanks for the feedback. I've asked the author to review your questions and comments. We'll work to enhance this topic and provide the information that you're looking for in a future update.

**Comment by tonyafehr** [comment]
Tracking bug logged: 255739
