### ISSUE TITLE
Refresh database vs Point In Time restore

### ISSUE THREAD

**Issue by JOLSO** [MicrosoftDocs/dynamics-365-unified-operations-public#4496]
On this page it says -  Important

Copying production data during business hours or peak hours could have an impact on the production system. It's highly recommended to do the refresh database operation during off-peak hours and limit only one refresh operation at a time.

Copying production data to your sandbox environment for the purpose of production reporting is not supported.

So, is it true statement that the above comment does not apply if we choose PIT instead? So, refreshing UAT using PIT during the day would not impact or cause perf issue in PROD. If this is true, could you please add this info to the page?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9d28e8cc-5110-f01b-db76-94479ec2fa91
* Version Independent ID: f0710707-9ff2-84a1-30c7-1f0d44e3a0d7
* Content: [Refresh database - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/database-refresh)
* Content Source: [articles/fin-ops-core/dev-itpro/database/database-refresh.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/database/database-refresh.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by bishalgoswami** [comment]
Bug 803062 has been logged to address this issue.

**Comment by twheeloc** [comment]
@JOLSO, thank you for your feedback. We have passed this feedback onto the product team for consideration.
