### ISSUE TITLE
Will this page be updated? Some aspects seem out of date with current D365 Finance and Operations

### ISSUE THREAD

**Issue by JTWWI** [MicrosoftDocs/dynamics-365-unified-operations-public#4501]
For instance Step 11 instructs us to 'Select the Unified Operations template'.  I think now we would select Finance and Operations, as I can't find Unified Operations in the 'Create a new project' dialog box.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 71438101-e8d0-6636-a397-64b039c85a39
* Version Independent ID: 9db6265c-437c-75d2-be92-131273a8ca56
* Content: [Create models and data model elements overview - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/create-data-model-elements)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/create-data-model-elements.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/dev-tools/create-data-model-elements.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @gianugo
* Microsoft Alias: **gianura**

**Comment by bishalgoswami** [comment]
Bug 803364 has been logged to address this issue.
