### ISSUE TITLE
Request changes in the engineering product

### ISSUE THREAD

**Issue by SajeerAssiz** [MicrosoftDocs/dynamics-365-unified-operations-public#4502]
[Enter feedback here]
While creating engineering change order requested by details are coming as empty , dur to this we cant move forward on change order management scenarios

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b14b6f89-ec69-0681-a1c0-0610d86d5093
* Version Independent ID: 8d263a48-f14f-c68c-cce6-0cdc15086ea9
* Content: [Engineering change management feature walkthrough - Supply Chain Management | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/supply-chain/engineering-change-management/engineering-scenarios)
* Content Source: [articles/supply-chain/engineering-change-management/engineering-scenarios.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/engineering-change-management/engineering-scenarios.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @t-benebo
* Microsoft Alias: **benebotg**

**Comment by bishalgoswami** [comment]
Bug 803592 has been logged to address this issue.

**Comment by twheeloc** [comment]
@SajeerAssiz, thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
