### ISSUE TITLE
Doc bug - The pattern NotHandledResponse was deprecated in 10.0.8 and is no longer supported as of 10.0.31 (SDK v9.41)

### ISSUE THREAD

**Issue by RobBertram** [MicrosoftDocs/dynamics-365-unified-operations-public#4504]
[Doc Bug]
The section titled "NotHandledResponse" is outdated.  The pattern described has been outdated for years.  Starting in 10.0.8, the following compiler warning is thrown:  'NotHandledResponse.NotHandledResponse()' is obsolete: 'Use static 'Instance' property instead. Obsolete since version 10.8'    

Starting in 10.0.31, that warning turns into an error. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 70499299-6113-cf26-6f1e-0d8c67e0fcb5
* Version Independent ID: 7401fa31-2c1e-c2bd-8402-078613dc86cc
* Content: [Commerce runtime (CRT) extensibility - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/dev-itpro/commerce-runtime-extensibility)
* Content Source: [articles/commerce/dev-itpro/commerce-runtime-extensibility.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/commerce-runtime-extensibility.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by josaw1** [comment]
@jashanno can you please update this article? Thanks.

**Comment by johnmichalak** [comment]
This issues has been resolved by changes included in https://github.com/MicrosoftDocs/Dynamics-365-Operations/pull/17165 that was merged on 11/08/2023.
