### ISSUE TITLE
Steps to create Commerce build pipeline incorrect

### ISSUE THREAD

**Issue by RobvanB** [MicrosoftDocs/dynamics-365-unified-operations-public#4506]
These steps don't match the current devops process. There is no YAML file to select or even edit if you follow this process.
It's either outdated, or the instructions are not clear enough, i.e. what the exact source directory should be, or where in the repo structure to store the yml file.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d9cf3583-4ed2-d65e-967f-d5a9d6483365
* Version Independent ID: ec10375f-07f9-e027-d4ee-d6832c65d30e
* Content: [Set up a build pipeline for the independent-packaging SDK - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/dev-itpro/build-pipeline)
* Content Source: [articles/commerce/dev-itpro/build-pipeline.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/build-pipeline.md)
* Service: **dynamics-365-commerce**
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by bishalgoswami** [comment]
Bug 804105 has been logged to address this issue.

**Comment by josaw1** [comment]
@lukedgr can you please review, or assign to the correct person? Thanks.

**Comment by RobvanB** [comment]
Please note: it appears that the issue is that the repo is not a GIT 
repo, but a TFVC repo.

So you might just need to add a note to the article that it won't work 
with TFVC, or provide TFVC specific instructions.
