### ISSUE TITLE
Instructions for Instructions on Production Floor Execution Unclear

### ISSUE THREAD

**Issue by rmccarron-napoleon** [MicrosoftDocs/dynamics-365-unified-operations-public#4507]
The following section list an "Example" of a scenario of when instructions appear.  

https://learn.microsoft.com/en-us/dynamics365/supply-chain/production-control/production-floor-execution-use#opening-instructions

"For example, a document that is attached to a product on the Released products page in Supply Chain Management will be available for workers to open in the shop floor execution interface."

Are there other examples?  Is there a configuration needed for this?  Are only specific types of documents applicable?  I am unable to find any specific details on how it should work.

Thanks,

Ryan

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 17fe109b-0191-fae3-c120-608f709208c3
* Version Independent ID: 2ae7d13f-c34e-53de-3265-c1c508c3703e
* Content: [How workers use the production floor execution interface - Supply Chain Management | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/supply-chain/production-control/production-floor-execution-use)
* Content Source: [articles/supply-chain/production-control/production-floor-execution-use.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/production-control/production-floor-execution-use.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @johanhoffmann
* Microsoft Alias: **johanho**

**Comment by bishalgoswami** [comment]
Bug 804149 has been logged to address this issue.

**Comment by twheeloc** [comment]
@rmccarron-napoleon, thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
