### ISSUE TITLE
Can this tutorial be improved to add guidance on running this as a Cloud Hosted Environment?

### ISSUE THREAD

**Issue by JTWWI** [MicrosoftDocs/dynamics-365-unified-operations-public#4509]
Can this tutorial be improved to add guidance on running this as a Cloud Hosted Environment?
Also, what about Source Control? If we're connected to Azure DevOps in VSTS would we need to create a new empty branch?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 26f953f4-532c-4ae7-333d-90d5a901bfb8
* Version Independent ID: a7ee3929-b4cd-bc06-0c06-7f4e73be5789
* Content: [Development tools tutorial - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/introduction-visual-studio)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/introduction-visual-studio.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/dev-tools/introduction-visual-studio.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @gianugo
* Microsoft Alias: **gianura**

**Comment by bishalgoswami** [comment]
Bug 804687 has been logged to address this issue.

**Comment by twheeloc** [comment]
Thanks for your feedback. We have passed this feedback onto the product team for consideration.
