### ISSUE TITLE
Available physical on exact dimensions, not extra

### ISSUE THREAD

**Issue by cavensjan** [MicrosoftDocs/dynamics-365-unified-operations-public#4512]
<html>
<body>

_Available physical on **extra** dimensions_ | The available physical quantity for all the dimensions that are shown in the grid.
-- | --

This should be _Available physical on **exact** dimensions_, not extra

</body>
</html>

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5815c391-19d5-d867-1993-109e8c3f7612
* Version Independent ID: a375dfbc-9f5b-c2ca-0d5f-9521c7fa96ca
* Content: [Inventory on-hand list - Supply Chain Management | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/supply-chain/inventory/inventory-on-hand-list)
* Content Source: [articles/supply-chain/inventory/inventory-on-hand-list.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/inventory/inventory-on-hand-list.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @yufeihuang
* Microsoft Alias: **yufeihuang**

**Comment by bishalgoswami** [comment]
Bug 805365 has been logged to address this issue.

**Comment by kamaybac** [comment]
@cavensjan , thank you for reporting this error. We have now fixed it.
