### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by miursu** [MicrosoftDocs/dynamics-365-unified-operations-public#4513]
The doc mentions A planned maintenance window is typically during the dark hours during Saturday and Sunday of the geographic region that your environment is deployed in. The following table lists the maintenance windows for each geography in Coordinated Universal Time (UTC) and for Europe dark hours are 10:00 PM to 4:00 AM UTC.
For one customer a maintenance occurred on Friday evening between 22:15-22:45UTC, which is why one of a critical process was stopped! Maybe a clarifications regarding specific downtimes should be updated in the doc
Thanks!

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1fcc1802-115b-4ac2-f34f-aa73eac426f4
* Version Independent ID: d758bfc6-245e-43d6-8bde-31282cea0a64
* Content: [Maintenance in self-service environments FAQ - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/plannedmaintenance-selfservice#windows)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/plannedmaintenance-selfservice.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/deployment/plannedmaintenance-selfservice.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @matapg007
* Microsoft Alias: **matgupta**

**Comment by bishalgoswami** [comment]
Bug 805441 has been logged to address this issue.

**Comment by twheeloc** [comment]
Thanks for your feedback. We have passed this feedback onto the product team for consideration.
