### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by jimwillsher** [MicrosoftDocs/dynamics-365-unified-operations-public#4516]
[Enter feedback here]
10.0.33 has been GA for a week now. This page still refers to "preview" and is also missing the crucial section which lists which features have become mandatory (refer to the 10.0.32 page for comparison).

When can we expect the 10.0.34 page?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e1ae3fe5-d77c-0012-fd68-73ca7875b0e3
* Version Independent ID: e1ae3fe5-d77c-0012-fd68-73ca7875b0e3
* Content: [What's new or changed in Dynamics 365 Finance 10.0.33 (April 2023) - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/get-started/whats-new-changed-changed-10-0-33)
* Content Source: [articles/finance/get-started/whats-new-changed-changed-10-0-33.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/get-started/whats-new-changed-changed-10-0-33.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @twheeloc
* Microsoft Alias: **twheeloc**

**Comment by bishalgoswami** [comment]
Bug 805708 has been logged to address this issue.

**Comment by twheeloc** [comment]
@jimwillsher, thank you for the feedback. The What's new for 10.0.34 is available here:  https://learn.microsoft.com/en-us/dynamics365/finance/get-started/whats-new-changed-10-0-34
