### ISSUE TITLE
Feature management and relations between standard tables using custom fields

### ISSUE THREAD

**Issue by cestWP** [MicrosoftDocs/dynamics-365-unified-operations-public#4517]
The feature management allows to enable/disable a feature. But the features work at user interface level and the corresponding data models are not affected by the modification in the feature management.
In particular tables relations added between standard tables using custom fields will be inherited by all those standard queries  that make use of relations, even if the feature linked to those custom fields is not enable.

Let be the following scenario: 
1. Add the new custom field MyCustomField of type InventLocationId in the standard table InventSite.
2. Link this new field to the custom feature MyFeature
3. Add the relation between the tables InventSite and InventLocation using the new field as InventSite.MyCustomField  == InventLocation.InventLocationId

Even if the feature MyFeature is not enabled, all standard queries using the invent site as data source, where the flag 'UseRelations' is YES, will inherit that relation! This means that the standard query could behave differently.

For instance, the query WHSContainerContents used by the standard report WHSContainerContents, will make use of that new relation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 51e63496-19e3-182e-c19d-027a0a5f6acf
* Version Independent ID: c8a51a1e-25e8-fbe3-4580-baca9046b7b0
* Content: [Feature management overview - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/feature-management/feature-management-overview)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/feature-management/feature-management-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/feature-management/feature-management-overview.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Peakerbl
* Microsoft Alias: **peakerbl**

**Comment by bishalgoswami** [comment]
Bug 805858 has been logged to address this issue.

**Comment by twheeloc** [comment]
@cestWP,  Thanks for your feedback. We have passed this feedback onto the product team for consideration.
