### ISSUE TITLE
SPF Information Not Listed

### ISSUE THREAD

**Issue by JohnLBevan** [MicrosoftDocs/dynamics-365-unified-operations-public#4518]
When D365FO is configured to send mails via SMTP (`smtp.office.com`), the originating IP is the IP of the D365FO instance; so this IP needs to be added to the sender's domain's SPF record to avoid being seen as suspect.  If many mails are sent from this account in a  short period, the account may then be automatically disabled as it's seen as compromised/sending spam / so needs to be [removed from the blocked users list](https://learn.microsoft.com/microsoft-365/security/office-365-security/removing-user-from-restricted-users-portal-after-spam).  However, the same issue will recur as the root cause hasn't been resolved.

Please could you update this document to include either a list of IPs that we could add to our SPF record, or better, the address of a TXT/SPF record which to which these IPs are published so we could add an `include` to our SPF which to get the IPs dynamically.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e46e3d2a-37fb-9961-84fe-0be6d9f0235b
* Version Independent ID: c4a46858-a79b-08b4-d81c-941490d42da3
* Content: [Configure and send email - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/organization-administration/configure-email)
* Content Source: [articles/fin-ops-core/fin-ops/organization-administration/configure-email.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/organization-administration/configure-email.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by bishalgoswami** [comment]
Bug 806189 has been logged to address this issue.
