### ISSUE TITLE
Regarding the final blue note starting with "This topic shows how a primary..." - the part "see Cost roll-up policy"

### ISSUE THREAD

**Issue by AXcademy** [MicrosoftDocs/dynamics-365-unified-operations-public#452]
"see Cost roll-up policy. (Note that this topic isn't competed yet but is coming soon.)"

Is this note still valid? When I have a look at the topic mentioned - Cost rollup policy and overhead calculation - it seems OK with me.

https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/cost-accounting/cost-rollup

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9291afb3-bf70-48c0-3a56-10d31580057e
* Version Independent ID: d32a3774-64d8-fdfa-5017-f7d77eb9c3c3
* Content: [Overhead calculation - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/cost-accounting/overhead-calculation)
* Content Source: [articles/financials/cost-accounting/overhead-calculation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/cost-accounting/overhead-calculation.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @AndersGirke
* Microsoft Alias: **shylaw**

**Comment by sericks007** [comment]
@AXcademy, Thanks for letting us know! We'll look into updating this content.

**Comment by sericks007** [comment]
@ShylaThompson  or @AndersGirke could you please update the "Overhead calculation" topic to link to the appropriate cost rollup policy topic?

**Comment by ShylaThompson** [comment]
@AXcademy , thanks for pointing this out. The topic has been updated and will be published later today.
