### ISSUE TITLE
This [service] should be [support].

### ISSUE THREAD

**Issue by yujiim** [MicrosoftDocs/dynamics-365-unified-operations-public#4521]
Please correct this.

This [service] should be [support].
https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/one-version#what-happens-to-an-environment-that-is-running-a-finance-and-operations-app-version-that-is-no-longer-supported:~:text=its%20end%20of-,service,-(N%2D4)%2C%20the

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 23fde63f-0f6f-b1a0-50c8-e1bf5f6a48c4
* Version Independent ID: 59a1f734-87cb-f34c-afd5-9f14de877584
* Content: [One Version service updates FAQ - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/one-version#what-happens-to-an-environment-that-is-running-a-finance-and-operations-app-version-that-is-no-longer-supported)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/one-version.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/one-version.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by bishalgoswami** [comment]
Bug 806416 has been logged to address this issue.

**Comment by twheeloc** [comment]
Thanks for your feedback. We have passed this feedback onto the product team for consideration.
