### ISSUE TITLE
Multi-element revenue allocation is incorrectly titled

### ISSUE THREAD

**Issue by mervynmartin** [MicrosoftDocs/dynamics-365-unified-operations-public#4523]
The following block names the feature incorrectly

`Multi-element revenue allocation – This module helps with revenue compliance by handling pricing and revenue allocation across multiple items.`

The feature in D365 F&O 10.0.33 is named

`Multiple element revenue allocation`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8115fd1e-a90a-6d64-5a52-5ca29303b4f9
* Version Independent ID: 8115fd1e-a90a-6d64-5a52-5ca29303b4f9
* Content: [Subscription billing overview - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/accounts-receivable/subscription-billing-summary)
* Content Source: [articles/finance/accounts-receivable/subscription-billing-summary.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/accounts-receivable/subscription-billing-summary.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @JodiChristiansen
* Microsoft Alias: **jchrist**

**Comment by bishalgoswami** [comment]
Bug 806759 has been logged to address this issue.

**Comment by msftbrking** [comment]
Pull request created.

**Comment by twheeloc** [comment]
@mervynmartin, thank you for the feedback. The topic will be updated.
