### ISSUE TITLE
Wrong connect string example

### ISSUE THREAD

**Issue by d47447** [MicrosoftDocs/dynamics-365-unified-operations-public#4525]
Hello, 

The example of connection string here that says to make it like below

Data Source=<logical server name>,1433; Initial Catalog=<your DB name>; Integrated Security=False; User ID=<SQL user ID>; Password=<password>

While in D365FO when trying with the same example its giving a different format, 

![image](https://user-images.githubusercontent.com/10023144/234651386-4d428212-5547-475c-9268-7fc9a0ce0b12.png)

Can we please make it simple and consistence?  

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 33f75161-0776-a6c1-dc10-dc20ea26973f
* Version Independent ID: 55a81394-4606-745a-9fd2-59fb257d1086
* Content: [Bring your own database (BYOD) - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/export-entities-to-your-own-database)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/export-entities-to-your-own-database.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/analytics/export-entities-to-your-own-database.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Peakerbl
* Microsoft Alias: **peakerbl**

**Comment by bishalgoswami** [comment]
Bug 806878 has been logged to address this issue.

**Comment by johnmichalak** [comment]
@d47447 Thank you for the feedback. The author has reviewed your suggestion and feels the article is accurate. Please make sure you are replacing the sample values with your own values.
