### ISSUE TITLE
Instructions request disablement of GABExtended plug-in steps in CE which is prevented by a SdkMessageProcessingStepService Exception due to Microsoft Registration

### ISSUE THREAD

**Issue by jacobbates** [MicrosoftDocs/dynamics-365-unified-operations-public#4527]
Step 5 is currently not possible in Customer Engagement apps due to a restriction preventing disablement of Microsoft registered SDK message processing steps.

https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/upgrade-party-gab#run-the-templates

`In the customer engagement app, disable the following plug-in steps:

Account Update

Microsoft.Dynamics.GABExtended.Plugins.UpdatePartyAttributesFromAccountEntity: Update of account
Microsoft.Dynamics.FinanceExtended.Plugins.TriggerNotesForCustomerTypeCodes: Update of account
Contact Update

Microsoft.Dynamics.GABExtended.Plugins.UpdatePartyAttributesFromContactEntity: Update of contact
Microsoft.Dynamics.FinanceExtended.Plugins.TriggerNotesForSellableContact: Update of contact

...`

Plugin/Microsoft.Crm.ObjectModel.SdkMessageProcessingStepService:
`Unhandled Exception: System.ServiceModel.FaultException

A Microsoft registered SDK message processing step cannot be modified.`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c9bfd7c9-5974-a0a8-a75f-3d2b5dbfa215
* Version Independent ID: 795c5756-250b-2f31-b635-72e5d889e77e
* Content: [Upgrade to the party and global address book model - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/upgrade-party-gab)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/upgrade-party-gab.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/dual-write/upgrade-party-gab.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @RamaKrishnamoorthy
* Microsoft Alias: **ramasri**

**Comment by bishalgoswami** [comment]
Bug 807119 has been logged to address this issue.

**Comment by jacobbates** [comment]
Some relevant info for my particular use case, MS support was able to request product team to change a flag in environment to allow disablement of plugins. But seems this is by exception and request now and "A Microsoft registered SDK message processing step cannot be modified." response is intended default behaviour for new environments to prevent unwanted OOB plugin step disablement. This may be helpful information when updating this documentation gap. Thanks @RamaKrishnamoorthy
