### ISSUE TITLE
Link Broken

### ISSUE THREAD

**Issue by udaysoni3290** [MicrosoftDocs/dynamics-365-unified-operations-public#4529]
https://hub.bhsolutions.com/creating-a-mock-parcel-engine-in-d365?submissionGuid=46a1fccf-80b0-4b70-a6a0-4bf45a8756b5 
Which is a link on this page is broken. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 02563b14-0ca3-ad00-ef34-d494d4d13d69
* Version Independent ID: 5963986c-1c97-2db6-876c-cccb69ea791e
* Content: [Small parcel shipping - Supply Chain Management | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/supply-chain/warehousing/small-parcel-shipping)
* Content Source: [articles/supply-chain/warehousing/small-parcel-shipping.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/warehousing/small-parcel-shipping.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @Mirzaab
* Microsoft Alias: **mirzaab**

**Comment by bishalgoswami** [comment]
Bug 810270 has been logged to address this issue.
