### ISSUE TITLE
Local components logs location has changed

### ISSUE THREAD

**Issue by ManuLaakkonen** [MicrosoftDocs/dynamics-365-unified-operations-public#4531]
[Enter feedback here]
Local components logs location has changed.

https://community.dynamics.com/365/commerce/f/dynamics-365-commerce-forum/467158/where-are-the-logs-commerce-scale-unit-sealed---self-hosted

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1ea563b0-eb9c-bc38-f17a-f24913eb426f
* Version Independent ID: 1f9c1430-a53c-9a63-77fe-dc4b44b7c3a7
* Content: [Commerce component events for diagnostics and troubleshooting - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/dev-itpro/retail-component-events-diagnostics-troubleshooting)
* Content Source: [articles/commerce/dev-itpro/retail-component-events-diagnostics-troubleshooting.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/retail-component-events-diagnostics-troubleshooting.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @ShalabhjainMSFT
* Microsoft Alias: **shajain**

**Comment by bishalgoswami** [comment]
Bug 810534 has been logged to address this issue.

**Comment by twheeloc** [comment]
Thanks for your feedback. We have passed this feedback onto the product team for consideration.
