### ISSUE TITLE
The product life time of Finance + Operations (on-premises) software ends December 2027!?

### ISSUE THREAD

**Issue by MichaelP-SCALES** [MicrosoftDocs/dynamics-365-unified-operations-public#4532]
Hi,

Product life time
The product life time of Finance + Operations (on-premises) software ends December 2027. Licensed customers who are in compliance with this policy are entitled to product support. Product support is available at a minimum through December 31, 2027.

How should I read this. Does the D365FO LBD version end of life in December 2027? It is a bit unclear for me and one of our prospects.

Appreciate your assistance.

Best regards,
Michael

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 45e09816-9864-f87d-4117-5276a8790a09
* Version Independent ID: 6709e1e7-8130-570d-0f33-64c4bfe604ad
* Content: [Software lifecycle policy and on-premises releases - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/on-prem-version-update-policy?context=%2Fdynamics365%2Fcontext%2Fcommerce)
* Content Source: [articles/fin-ops-core/dev-itpro/migration-upgrade/on-prem-version-update-policy.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/migration-upgrade/on-prem-version-update-policy.md)
* Service: ****
* Product: **dynamics-365**
* Technology: ****
* GitHub Login: @faix
* Microsoft Alias: **osfaixat**

**Comment by bishalgoswami** [comment]
Bug 810559 has been logged to address this issue.

**Comment by faix** [comment]
@johnmichalak this issue can be closed now.
