### ISSUE TITLE
Missing info for one box environments

### ISSUE THREAD

**Issue by ha365** [MicrosoftDocs/dynamics-365-unified-operations-public#4533]
[Enter feedback here]
Got this from Yammer. for onebox environments this additional step needs to be done

The change to web.config involves that you locate the line starting with:
<add key="Infrastructure.TrustedCertificates"
within the value segment add your thumbprint at the end of this followed by a semicolon as delimiter.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e2458b41-99e9-53ff-b898-cdd957c1c924
* Version Independent ID: 9aad0fcb-b367-136a-9fb0-d8d04a2cfc33
* Content: [Regression suite automation tool installation and configuration - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/perf-test/rsat/rsat-install-configure)
* Content Source: [articles/fin-ops-core/dev-itpro/perf-test/rsat/rsat-install-configure.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/perf-test/rsat/rsat-install-configure.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @FrankDahl
* Microsoft Alias: **fdahl**

**Comment by josaw1** [comment]
Won't fix.
