### ISSUE TITLE
Current supported versions

### ISSUE THREAD

**Issue by thedynamicsgirl** [MicrosoftDocs/dynamics-365-unified-operations-public#4534]
[Can the **_Current supported versions_** be updated to reflect what's latest? or can there be a link to re-direct us to any page where it will show what's the least supported version and maybe the respective dates?]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 48746126-f146-6c6d-d8da-307f819896c6
* Version Independent ID: 73cdd013-3569-b678-26f3-75679d84e4f6
* Content: [Dynamics 365 Commerce component versioning requirements - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/arch-component-versioning#current-supported-versions)
* Content Source: [articles/commerce/arch-component-versioning.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/arch-component-versioning.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @Reza-Assadi
* Microsoft Alias: **rassadi**

**Comment by bishalgoswami** [comment]
Bug 810711 has been logged to address this issue.

**Comment by josaw1** [comment]
@Reza-Assadi can you please help with this request? Thanks.
