### ISSUE TITLE
Licensing implications

### ISSUE THREAD

**Issue by Dretah** [MicrosoftDocs/dynamics-365-unified-operations-public#4535]
Hi,

I would really appreciate it if on these setup pages, which are extremely helpful, there would be a section diving deeper into the licensing consequences. Is it included in the standard, are additional licenses required, in this case are PowerPlatform licenses required ?

Thanks for considering,
Regards,
William van de Haterd
Dynamics 365 consultant @ Cegeka Business Solutions

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d57823b0-e4e9-b572-02f6-21a8fde6a5e0
* Version Independent ID: 125e534a-0579-ccb4-b8ff-df1950fcda69
* Content: [Onboard the Asset Management mobile app - Supply Chain Management | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/supply-chain/asset-management/asset-management-mobile-app/onboard-app)
* Content Source: [articles/supply-chain/asset-management/asset-management-mobile-app/onboard-app.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/asset-management/asset-management-mobile-app/onboard-app.md)
* Service: **dynamics-365-supply-chain**
* GitHub Login: @johanhoffmann
* Microsoft Alias: **johanho**

**Comment by josaw1** [comment]
@kamaybac, can you please investigate?

**Comment by twheeloc** [comment]
@Dretah,  thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
