### ISSUE TITLE
Documentation does not show AOS downtime

### ISSUE THREAD

**Issue by v-felipel** [MicrosoftDocs/dynamics-365-unified-operations-public#4536]
[Enter feedback here]

As per feedback from Lane Swenka, when an environment is linked to PP AOS get restarted and there is a downtime of up to 10min per AOS
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ae234693-3a0a-d25c-ecd1-abd01ad7580f
* Version Independent ID: ae234693-3a0a-d25c-ecd1-abd01ad7580f
* Content: [Enable Power Platform Integration - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/power-platform/enable-power-platform-integration)
* Content Source: [articles/fin-ops-core/dev-itpro/power-platform/enable-power-platform-integration.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/power-platform/enable-power-platform-integration.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by bishalgoswami** [comment]
Bug 810997 has been logged to address this issue.
