### ISSUE TITLE
Duplicate Content on Page

### ISSUE THREAD

**Issue by kainar** [MicrosoftDocs/dynamics-365-unified-operations-public#4537]
https://learn.microsoft.com/en-us/dynamics365/finance/accounts-payable/auto-vendr-invc-process#resume-automation-processing-for-multiple-invoices
has the exact same content as
https://learn.microsoft.com/en-us/dynamics365/finance/accounts-payable/auto-vendr-invc-process#vendor-invoice-automation---resume-automation-processing-for-multiple-invoices

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 950c47d9-c9b1-878e-a0cc-7e453554bbc6
* Version Independent ID: 1ec2aaff-8ffb-759a-4337-b6574cf01d55
* Content: [Automated vendor invoicing processes overview - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/accounts-payable/auto-vendr-invc-process)
* Content Source: [articles/finance/accounts-payable/auto-vendr-invc-process.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/accounts-payable/auto-vendr-invc-process.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @abruer
* Microsoft Alias: **shpandey**

**Comment by bishalgoswami** [comment]
Bug 810996 has been logged to address this issue.
