### ISSUE TITLE
Mistitles parameter

### ISSUE THREAD

**Issue by mikecaterino** [MicrosoftDocs/dynamics-365-unified-operations-public#4541]
Hey,
    Super nit-picky, but in the section ExportToPackagePreview there is a "C#" code snippet that states ""count":"<Legal entity Id>"" that should be "count":"<int>" or something similar. Just thought I'd let you know. Cheers!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9d963d4c-de1f-7730-bee2-016dcde40907
* Version Independent ID: 21b95d43-5ad9-0ffc-21b9-6a4ba9086a56
* Content: [Data management package REST API - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/data-management-api)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/data-management-api.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/data-management-api.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Peakerbl
* Microsoft Alias: **peakerbl**

**Comment by bishalgoswami** [comment]
Bug 812393 has been logged to address this issue.

**Comment by josaw1** [comment]
@twheeloc can you please look into fixing this?
