### ISSUE TITLE
Commerce Scale Unit (cloud-hosted) - Earliest supported version

### ISSUE THREAD

**Issue by thedynamicsgirl** [MicrosoftDocs/dynamics-365-unified-operations-public#4542]
[Hey, Why the earliest supported version for Commerce Scale Unit (cloud-hosted) is 10.0.33? I thought 10.0.33 just came in GA]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 48746126-f146-6c6d-d8da-307f819896c6
* Version Independent ID: 73cdd013-3569-b678-26f3-75679d84e4f6
* Content: [Dynamics 365 Commerce component versioning requirements - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/arch-component-versioning#current-supported-versions)
* Content Source: [articles/commerce/arch-component-versioning.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/arch-component-versioning.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @Reza-Assadi
* Microsoft Alias: **rassadi**

**Comment by bishalgoswami** [comment]
Bug 812624 has been logged to address this issue.

**Comment by josaw1** [comment]
@sushma-rao can you please help with this question?

**Comment by josaw1** [comment]
Fixed.
