### ISSUE TITLE
Incorrect column name in create-new-trade-agreement.md

### ISSUE THREAD

**Issue by Weicheng-Gao** [MicrosoftDocs/dynamics-365-unified-operations-public#4543]
![image](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/assets/110089661/49ddc0d6-4da5-4cab-9531-a60449e42b50)
https://learn.microsoft.com/en-us/dynamics365/supply-chain/sales-marketing/tasks/create-new-trade-agreement
In the doc it says "Account code" field.

![image](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/assets/110089661/b1f3ea88-9715-40d0-9b30-915572e5d4ac)
Actually it's "Party code type" field.

![image](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/assets/110089661/332764c8-82f6-4770-b1bc-417e2c4b3c61)
AccountCode is the internal variable name in the code. "Party code type" is the label to display.

Another incorrect label: "Item code" -> "Product code type".

**Comment by Weicheng-Gao** [comment]
@sherry-zheng FYI

**Comment by josaw1** [comment]
@kamaybac can you please review?

**Comment by kamaybac** [comment]
@Weicheng-Gao , thank you for reporting these issues. I have updated the topic and the changes should go live later today.
