### ISSUE TITLE
Connected applications & Link connected applications to environments

### ISSUE THREAD

**Issue by Stuart-Honour-HCL** [MicrosoftDocs/dynamics-365-unified-operations-public#4547]
This page seems to suggest that when creating a connect application there is also a requirements to create an entry in the environment setup for RCS.  although you need a connected application to link it to a service environment for what looks like configuring something to do with electronic invoicing it seem irrelevant on this page when just wanting to use a connected application to reference meta data for an electronic reporting design in RCS.

**Create a connected application**

1. Sign in to your RCS account.
2. In the Globalization feature workspace, in the Related links section, select Environment setup.
3. On the Environment setup page, on the Action Pane, select Connected applications.
4. Select New to create a connected application.
5. In the Name field, enter the name of the application to connect.
6. In the Type field, select Dynamics 365 Finance.
7. In the Application field, enter the URL of the environment to connect.
8. In the Tenant field, enter the tenant of the environment.
9. Select Save.
10. On the Action Pane, select Check connection to test the connection with the environment. Then close the page.

**Link connected applications to environments**

1. On the Environment setup page, select New to assign a connected application to an environment.
2. In the Connected application field, select a connected application.
3. In the Service environment field, select a service environment.
4. Select Save, and then close the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3197c22f-c401-5af8-ef6e-c6fbcdda4084
* Version Independent ID: 3197c22f-c401-5af8-ef6e-c6fbcdda4084
* Content: [Connected applications - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/localizations/e-invoicing-connected-applications)
* Content Source: [articles/finance/localizations/e-invoicing-connected-applications.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/e-invoicing-connected-applications.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @gionoder
* Microsoft Alias: **gionoder**

**Comment by josaw1** [comment]
@kfend, please investigate.

**Comment by twheeloc** [comment]
Thanks for your feedback. We have passed this feedback onto the product team for consideration.
