### ISSUE TITLE
New versions

### ISSUE THREAD

**Issue by HarmD365** [MicrosoftDocs/dynamics-365-unified-operations-public#4548]
Hi,

Could you please update the versions and dates after 10.0.38? We want to schedule the updates with our customers.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e7dcb285-f32c-c92e-fe49-1617f213066b
* Version Independent ID: 8f28c1a0-9da5-f853-90ee-d82a4c32df7e
* Content: [Service update availability - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/public-preview-releases)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/public-preview-releases.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/public-preview-releases.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @hmahl
* Microsoft Alias: **hmahl**

**Comment by bishalgoswami** [comment]
Bug 814837 has been logged to address this issue.

**Comment by twheeloc** [comment]
@HarmD365, thank you for your feedback. This article has been updated.
