### ISSUE TITLE
LogonUser failed for svc-LocalAgent$. ErrorCode=0x80070775

### ISSUE THREAD

**Issue by fordummie** [MicrosoftDocs/dynamics-365-unified-operations-public#456]
On LocalAgent installation. Anyone?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d86d2857-6199-f3cb-208b-db4e1cd9f8e2
* Version Independent ID: d425ad9e-6c01-6145-dad5-2af32ffaaff0
* Content: [Troubleshoot on-premises deployments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/deployment/troubleshoot-on-prem#running-add-certtoserviceprincipal-results-in-no-subscription-found-in-the-context)
* Content Source: [articles/dev-itpro/deployment/troubleshoot-on-prem.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/deployment/troubleshoot-on-prem.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @sarvanisathish
* Microsoft Alias: **sarvanis**

**Comment by sericks007** [comment]
Thanks for contacting us! Unfortunately, we're unable to handle questions for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the Dynamics 365 for Finance and Operations community page to get help with your questions from the Dynamics community.
