### ISSUE TITLE
Picture still contains 'Common Data Service'

### ISSUE THREAD

**Issue by JeroenLeeflang** [MicrosoftDocs/dynamics-365-unified-operations-public#4560]
The picture might need an update. It still contains the Common Data Service iso Dataverse.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 036570ee-85fa-8449-be1c-a5e8755e175c
* Version Independent ID: 2468c8f9-0814-ded0-c6dd-879851a4b9e1
* Content: [Dual-write overview - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/dual-write-overview)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/dual-write-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/dual-write/dual-write-overview.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @RamaKrishnamoorthy
* Microsoft Alias: **ramasri**

**Comment by bishalgoswami** [comment]
Bug 816477 has been logged to address this issue.

**Comment by twheeloc** [comment]
Thanks for your feedback. We have passed this feedback onto the product team for consideration.

**Comment by JeroenLeeflang** [comment]
So after 9 months, this issue still exists. Not really motivating to give feedback this way...
