### ISSUE TITLE
Missing entities on Dual-write mapping documentation

### ISSUE THREAD

**Issue by fgehrke** [MicrosoftDocs/dynamics-365-unified-operations-public#4561]
Some entities are missing on the mapping documentation (https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/mapping-reference), as for example Returned Order Header Entity (https://learn.microsoft.com/en-us/common-data-model/schema/core/operationscommon/entities/supplychain/salesandmarketing/returnorderheaderentity).

I would like to know if this and other missing entities can be added to the documentation. Eventually we need to handle customer cases just to show them that there are other entities that can be used, that if it were in the documentation, they would be able to discover it by themselves - saving a lot of time with that.

**Comment by josaw1** [comment]
@pvillads can you please review?

**Comment by twheeloc** [comment]
Thanks for your feedback. We have passed this feedback onto the product team for consideration.
