### ISSUE TITLE
Related Table, Relationship Type, and Cardinality properties not explained or no links to explanations

### ISSUE THREAD

**Issue by JTWWI** [MicrosoftDocs/dynamics-365-unified-operations-public#4564]
When trying to do this for the first time, the reader may not know what is a Relationship Type, and Cardinality.  Can there be links to what defines Relationship Types and Cardinality?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6ccde6d8-8d53-02fd-8f53-6bf9aeb95ee1
* Version Independent ID: de749aee-cbfc-eae4-3227-1ee2606a2efa
* Content: [Add relations to tables through extension - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/extensibility/add-relation)
* Content Source: [articles/fin-ops-core/dev-itpro/extensibility/add-relation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/extensibility/add-relation.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @ivanv-microsoft
* Microsoft Alias: **ivanv**

**Comment by bishalgoswami** [comment]
Bug 817401 has been logged to address this issue.
