### ISSUE TITLE
Microsoft Dynamic 365 F&O Export to BYOD Failed

### ISSUE THREAD

**Issue by MalshiniNissanka** [MicrosoftDocs/dynamics-365-unified-operations-public#4566]
I am testing the BYOD feature in Dynamics 365. I could do the mapping of a single entity to BYOD successfully. But when trying to export it gets failed and is unable to identify the issue. Gow to resolve this? what can be the issue?

![image](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/assets/34208844/6253e897-2d8c-430f-92fa-3db4fed04126)

**Comment by twheeloc** [comment]
@MalshiniNissanka, thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
