### ISSUE TITLE
Newly added bank account which is in draft review status still can be used on invoice

### ISSUE THREAD

**Issue by cjokanov** [MicrosoftDocs/dynamics-365-unified-operations-public#4567]
Adding new bank account, with workflow setup and Bank account approval (create) parameter to yes produces following behaviour:
Bank account is created, review status is Draft, Status is Active
This bank account can be selected used (i.e. selected on Vendor invoice and posted)

So the statement "The new bank account record won't be available for use until an approver has approved it." is not correct

Furthermore, this whole functionality has very limited use unless it stops ability to add new bank account and use it without approval

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 82d19f25-f8e8-7b5a-ad68-281f49b644a3
* Version Independent ID: 82d19f25-f8e8-7b5a-ad68-281f49b644a3
* Content: [Vendor bank account workflow - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/accounts-payable/vendor-bank-account-workflow)
* Content Source: [articles/finance/accounts-payable/vendor-bank-account-workflow.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/accounts-payable/vendor-bank-account-workflow.md)
* Service: **dynamics-365-finance**
* GitHub Login: @GalynaFedorova
* Microsoft Alias: **gfedorova**

**Comment by bishalgoswami** [comment]
Bug 818704 has been logged to address this issue.

**Comment by twheeloc** [comment]
@cjokanov, thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
