### ISSUE TITLE
What is the pricing for E-Invoicing in Saudi Arabia for Hyper market business?

### ISSUE THREAD

**Issue by liamneesangamer** [MicrosoftDocs/dynamics-365-unified-operations-public#4568]
We are in the implementation stage right now, still we don't have any clarity from either partner side or Microsoft side for pricing of E-Invoicing in Saudia arabia, especially in hyper market business.

we are looking for more than 6 months. still we did not get the clarity so far.

Here is what we noted in "Dynamics 365 Licensing Guide"

"Electronic invoicing is the process of creating, presenting, and exchanging structured,
**transactional invoice documents between businesses and governments for tax
reporting purposes, or trading partners** in an integrated electronic format

Dynamics 365 Commerce, Finance, Project Operations, and Supply Chain Management applications **include 100
electronic invoice transactions/tenant/month**. This included capacity does not rollover and is **100 transactions
per tenant**, regardless of the number of Dynamics 365 licensed applications.

If you need additional transactions, you can buy the Electronic Invoicing additional capacity license for 1K
electronic invoice transactions/tenant/month. The transaction capacity is use-it-or-lose-it on a monthly basis,
and customers will need to purchase for peak capacity."

We are running with 7 stores, each store will have 1500 - 2000 transaction in one day. [7 store * 2000 = 14,000 per day]

Now, How this pricing_(as mentioned in Dynamics 365 Licensing Guide.pdf)_ will be applicable for Hypermarket business?.

 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 84f21366-6fa4-9eb7-3b88-09ae6e9d815d
* Version Independent ID: 84f21366-6fa4-9eb7-3b88-09ae6e9d815d
* Content: [Get started with Electronic invoicing for Saudi Arabia - Phase two - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/localizations/e-invoicing-sa-get-started)
* Content Source: [articles/finance/localizations/e-invoicing-sa-get-started.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/e-invoicing-sa-get-started.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @mrolecki
* Microsoft Alias: **mrolecki**

**Comment by TomasNavarro** [comment]
Hi @liamneesangamer , 
the information you posted from the "Dynamics 365 Licensing Guide" is correct and valid. For details on how this is applied to "hypermarket" business, I suggest you contact with the Microsoft licensing specialist you work with. 
Thanks, 
Tomás Navarro.
