### ISSUE TITLE
Obsolete method call 

### ISSUE THREAD

**Issue by thomasboghaert** [MicrosoftDocs/dynamics-365-unified-operations-public#4569]
[SpecTransManager::construct method is obsolete. Use SpecTransManager::newFromSpec instead]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9e3901cf-4989-fa16-f6d5-ef5e4a9a90dd
* Version Independent ID: b4084a6d-184f-02e8-3a03-88e91d70a533
* Content: [Settle transactions by using CustTrans  settleTransaction - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/financial/settletransact-obsolete)
* Content Source: [articles/fin-ops-core/dev-itpro/financial/settletransact-obsolete.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/financial/settletransact-obsolete.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @josaw1
* Microsoft Alias: **markskun**

**Comment by bishalgoswami** [comment]
Bug 819155 has been logged to address this issue.

**Comment by pvillads** [comment]
Jo,

I see nothing wrong with the web content.

The content clearly states that the SpecTransManager::construct(custTable) is obsolete - It is under a heading "Obsolete code example". To make it super clear, you can put in a comment in the code example:

//Mark for settlement
// Obsolete: Use SpecTransExecutionContext::newFromSource to create a context and
// then construct a SpecTransManager instance from that.
SpecTransManager specTransManager = SpecTransManager::construct(custTable);

I assigned the bug back to you with the text above.

Let me know if I misunderstood anything.


BR PV

**Comment by pvillads** [comment]
Ok, thanks.

From: Peter Villadsen ***@***.***>
Sent: Monday, June 5, 2023 9:29 AM
To: MicrosoftDocs/dynamics-365-unified-operations-public ***@***.***>; MicrosoftDocs/dynamics-365-unified-operations-public ***@***.***>; Jo Sawyer ***@***.***>
Cc: Assign ***@***.***>
Subject: RE: [MicrosoftDocs/dynamics-365-unified-operations-public] Obsolete method call (Issue #4569)

Jo,

I see nothing wrong with the web content.

The content clearly states that the SpecTransManager::construct(custTable) is obsolete - It is under a heading "Obsolete code example". To make it super clear, you can put in a comment in the code example:

//Mark for settlement
// Obsolete: Use SpecTransExecutionContext::newFromSource to create a context and
// then construct a SpecTransManager instance from that.
SpecTransManager specTransManager = SpecTransManager::construct(custTable);

I assigned the bug back to you with the text above.

Let me know if I misunderstood anything.


BR PV
