### ISSUE TITLE
Missing DMT Download Link

### ISSUE THREAD

**Issue by tomhig** [MicrosoftDocs/dynamics-365-unified-operations-public#457]
How is the DMT actually obtained? There is no link in this document nor is there any instruction on how to get it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ca4616b-e29f-a9c3-0d42-fe75c4659d57
* Version Independent ID: 9a438e2c-12e3-bb72-bcb2-1c45b05039e7
* Content: [AX 2009 migration - Install the Data migration tool - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/install-dmt)
* Content Source: [articles/dev-itpro/migration-upgrade/install-dmt.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/migration-upgrade/install-dmt.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @kfend
* Microsoft Alias: **kfend**

**Comment by josaw1** [comment]
Thanks for letting us know! We'll look into adding the information you suggested.

**Comment by ryanwwhittaker** [comment]
Is there any news on where we can get the tool yet please?

**Comment by josaw1** [comment]
Thanks for the comment. We're still working on it.

**Comment by luiscarlosmarin187** [comment]
Hello 

I need download Data migration tool, can I help me?

**Comment by kfend** [comment]
Thanks for the comment. I am working with the engineering team to get the information. We will update the documentation as soon as possible.

**Comment by kfend** [comment]
At this time, the DMT is in private preview. If you are interested you can sign up for the [Preview Program](https://microsoft.qualtrics.com/jfe/form/SV_brOLCioQ7mmeykB). The public release date for the DMT has not been set.

**Comment by jeanflori** [comment]
I signed up for DMT Preview a month ago. However, I have not received any feedback yet. Any forecast of return?

**Comment by kfend** [comment]
@Gokul06  - can you provide any information?

**Comment by vishnu254** [comment]
Could any one help me how to download DMT tool for data migration
