### ISSUE TITLE
Dual display extension upgrade

### ISSUE THREAD

**Issue by Osamaasif9312** [MicrosoftDocs/dynamics-365-unified-operations-public#4570]
Hi,

I was reading this blog to help myself create a dual display for store commerce as this blog was under store commerce section. But after deploying it to a test sandbox environment it was not working. So I have compared the code with Retail-SDK sample, it appears to be the same code as before. Can you guys please update the code as there is no dual display sample for Commerce SDK.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b5a7c0bf-2880-9af7-6227-95bdd0f96a1d
* Version Independent ID: f594e852-0181-9cb5-45b5-b1f0af475569
* Content: [Extend the point of sale (POS) Dual display view - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/dev-itpro/pos-dual-display-extension)
* Content Source: [articles/commerce/dev-itpro/pos-dual-display-extension.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/pos-dual-display-extension.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by josaw1** [comment]
@lukedgr can you please review this?

**Comment by twheeloc** [comment]
Thanks for your feedback. We have passed this feedback onto the product team for consideration.
