### ISSUE TITLE
Good but, how should we use this tutorial and not muck up our code base?

### ISSUE THREAD

**Issue by JTWWI** [MicrosoftDocs/dynamics-365-unified-operations-public#4571]
Hello,

This tutorial looks useful, but what is the best way to use it with an Azure DevOps managed code repository? A link or a paragraph or two on this page should guide people who are not 30 year veterans of coding for D365.

.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f5f9ccf3-650b-c8b0-efb9-b9d8a290db47
* Version Independent ID: 89633a0b-a776-f717-5e46-ffec1b9aa91e
* Content: [Expand Application Suite report data sets - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/expand-app-suite-report-data-sets?context=%2Fdynamics365%2Fcontext%2Fcommerce)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/expand-app-suite-report-data-sets.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/analytics/expand-app-suite-report-data-sets.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @RichdiMSFT
* Microsoft Alias: **richdi**

**Comment by bishalgoswami** [comment]
Bug 819250 has been logged to address this issue.

**Comment by josaw1** [comment]
Thank you for your feedback. As of now we will not be updating this article. Closing as won't fix.
