### ISSUE TITLE
Export grid

### ISSUE THREAD

**Issue by kurthatlevik-inspirit365** [MicrosoftDocs/dynamics-365-unified-operations-public#4572]
In the documentation here, it reference to "Export grid".  Why is this feature removed when applying filtering on fields like "Activity ID etc" ?  Can we only Export grid when we don't have applied filters ?  Why ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e5ff6b0b-7df1-bafd-cbf8-2613a704cd1c
* Version Independent ID: e7445fad-0895-d168-a98a-5b89afa6e7ac
* Content: [Use Azure Data Explorer to query raw information logs - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/azure-data-explorer)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/azure-data-explorer.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/lifecycle-services/azure-data-explorer.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @andreashofmann1
* Microsoft Alias: **andreash**

**Comment by josaw1** [comment]
Thank you for your feedback. As of now we will not be updating this article. Closing as won't fix.
