### ISSUE TITLE
Include information on Product support for a Storage Account behind a Firewall

### ISSUE THREAD

**Issue by msmerimoldi** [MicrosoftDocs/dynamics-365-unified-operations-public#4573]
Please include information on Product support for a Storage Account behind a Firewall. And if so, explain which are the supported configurations for the product, for example, VNET Integration, Resource Instance and/or Private Endpoints

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2f6ba603-2306-85f5-9eae-c71523326291
* Version Independent ID: 2f6ba603-2306-85f5-9eae-c71523326291
* Content: [Export to Azure Data Lake overview - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/azure-data-lake-ga-version-overview)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/Azure-Data-Lake-GA-version-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/Azure-Data-Lake-GA-version-overview.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by josaw1** [comment]
@peter-villadsen can you please review?

**Comment by peter-villadsen** [comment]
I have to decline, I have no idea what this is. If Milinda is fine with this, it is fine.

**Comment by msmerimoldi** [comment]
Feel free to ping me internally for further information, if required (marimo)

**Comment by josaw1** [comment]
@MilindaV2 can you please review?
