### ISSUE TITLE
Support for Always on SQL cluster for high availability in Commerce Scale Unit (Self hosted)

### ISSUE THREAD

**Issue by 5fq** [MicrosoftDocs/dynamics-365-unified-operations-public#4575]
It would be good to have clarification if the Commerce scale unit (self-hosted) supports SQL always on the availability cluster for high availability of the database. Even though there is documentation on how to install it on multiple computers, there is mention if this is supported or not. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 36235fea-cbfc-c300-7da8-9592b0906b57
* Version Independent ID: c27d2974-9c6f-3432-0521-e024b8defa8b
* Content: [Configure and install Commerce Scale Unit (self-hosted) - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/dev-itpro/retail-store-scale-unit-configuration-installation)
* Content Source: [articles/commerce/dev-itpro/retail-store-scale-unit-configuration-installation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/retail-store-scale-unit-configuration-installation.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @jashanno
* Microsoft Alias: **jashanno**

**Comment by bishalgoswami** [comment]
Bug 819621 has been logged to address this issue.

**Comment by Pikhulya** [comment]
@5fq , the links you use correspond to the [retired](https://www.yammer.com/dynamicsaxfeedbackprograms/#/Threads/show?threadId=2502321033625600) Legacy Installers.

As for the new Sealed Installers (such as RSSU and Store Commerce) deploying the Channel DB, the only [parameters ](https://community.dynamics.com/blogs/post/?postid=eeaf1046-8280-433f-af1e-398ce3ed04c6#mcetoc_1fgqloafp0)they provide around database are those allowing you to point to a specific SQL Server, such as:

- TrustSqlServerCertificate
- SqlServerName

If you would like to use any feature available on SQL Server side which doesn't require any new functionality in the installer - you can use it, if any particular feature you are considering on SQL Server is not compatible with the installers - please provide description of the issue including steps to reproduce and we will then be able to comment and or triage it.
