### ISSUE TITLE
URL format mentioned in the document doesn't match with Power Agents portal

### ISSUE THREAD

**Issue by 5fq** [MicrosoftDocs/dynamics-365-unified-operations-public#4576]
In the document, it says the token endpoint URL will look like "https://environment-id.04.environment.api.powerplatform.com/powervirtualagents/bots//directline/token?api-version=2022-03-01-preview". However, on the Power Agents portal, it is "https://defaultfbe1a7xxxxxxxxx.39.environment.api.powerplatform.com/powervirtualagents/botsbyschema/cr790_dynamicsxxxxxxx/directline/token?api-version=2022-03-01-preview". The /bots/ tag is missing and looks like some changes were applied to the power agents portal. Could you please update the document on where to get the bots ID as the said option is not currently available.

![image](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/assets/47292229/02c5a0a7-e2de-4c93-be46-03e51fd85ca6)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9e21e2b5-ffb2-0421-c458-0f3ebe809fc4
* Version Independent ID: 9e21e2b5-ffb2-0421-c458-0f3ebe809fc4
* Content: [Commerce Chat with Power Virtual Agents module - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/chat-module-pva)
* Content Source: [articles/commerce/chat-module-pva.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/chat-module-pva.md)
* Service: **dynamics-365-commerce**
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by bishalgoswami** [comment]
Bug 819620 has been logged to address this issue.
