### ISSUE TITLE
Who writes these examples?

### ISSUE THREAD

**Issue by sbredallMCA** [MicrosoftDocs/dynamics-365-unified-operations-public#4578]
How, exactly, does the documentation on custom D365FO shortcuts clearly explain how to configure/build a custom shortcut?  The examples given provide zero context.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 12ce88fa-eab8-4eaa-7f90-79a6ffbeadea
* Version Independent ID: a4f7a42a-e3df-6b10-ded9-cf5466b5490c
* Content: [Keyboard shortcuts for extensible controls - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/user-interface/keyboard-shortcuts-controls)
* Content Source: [articles/fin-ops-core/dev-itpro/user-interface/keyboard-shortcuts-controls.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/user-interface/keyboard-shortcuts-controls.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by bishalgoswami** [comment]
Bug 819693 has been logged to address this issue.

**Comment by josaw1** [comment]
Thank you for your feedback. As of now, we are not updating this article. Closing as won't fix.
