### ISSUE TITLE
Broken link "Microsoft Dynamics Localization Portal: China report"

### ISSUE THREAD

**Issue by kailu886** [MicrosoftDocs/dynamics-365-unified-operations-public#4579]
Broken link "Microsoft Dynamics Localization Portal: China report". Please help. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3ca19fb9-6d27-91bf-ad07-0ba26dbc66b3
* Version Independent ID: f2ad5c70-9019-f178-1e5d-a9f46851d463
* Content: [China overview - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/localizations/china)
* Content Source: [articles/finance/localizations/china.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/china.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **kfend**

**Comment by bishalgoswami** [comment]
Bug 0 has been logged to address this issue.

**Comment by kfend** [comment]
Removed the broken link.
