### ISSUE TITLE
Is Code upgrade required for existing customers in 8.0, Please specify in the documentation

### ISSUE THREAD

**Issue by manishmoothedath** [MicrosoftDocs/dynamics-365-unified-operations-public#458]
Could you please specify somewhere in the documentation if Code upgrade is required when moving from 8.0 to 8.1.
LCS code upgrade only shows 7.3 to 8.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3c5b4d1-9ab4-ff33-6a3a-14460998fcd1
* Version Independent ID: bfb7d49f-1ab1-542d-62ce-1625a8664bc7
* Content: [What's new or changed in Dynamics 365 for Finance and Operations version 8.1 (October 2018) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/whats-new-changed-8-1-october-2018)
* Content Source: [articles/fin-and-ops/get-started/whats-new-changed-8-1-October-2018.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/whats-new-changed-8-1-October-2018.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @tonyafehr
* Microsoft Alias: **tfehr**

**Comment by sericks007** [comment]
We'll soon be publishing a topic about updating from 8.0 to 8.1.  I'll let you know when it's available.

**Comment by sericks007** [comment]
For information about how to update environments from 8.0 to 8.1 please see [Update environments from version 8.0 to 8.1](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/appupdate-80-81).
