### ISSUE TITLE
Step 8 very difficult to follow

### ISSUE THREAD

**Issue by JTWWI** [MicrosoftDocs/dynamics-365-unified-operations-public#4583]
On this page it guides the reader to :
8. Add a new report handler (X++) class to the project. Give the class a name that appropriately describes that it's a handler for an existing application report. For this example, rename the class FERentalsByCustomerHandler to distinguish it from other report handlers.

How would one do this?  Further more searching the internet for "d365 create a new report handler class" only leads back to this same page that I'm commenting on here.

The closest thing I can find in the AOT is Data Model > Queries > FMRentalsByCustomer. But I don't think that's it.

... upon further reading we see step 9 kind of guides you how to do it, but just reading step 8 leaves you wondering.. am I supposed to already have done step 8 and know how to do so?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f5f9ccf3-650b-c8b0-efb9-b9d8a290db47
* Version Independent ID: 89633a0b-a776-f717-5e46-ffec1b9aa91e
* Content: [Expand Application Suite report data sets - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/expand-app-suite-report-data-sets?context=%2Fdynamics365%2Fcontext%2Fcommerce)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/expand-app-suite-report-data-sets.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/analytics/expand-app-suite-report-data-sets.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @RichdiMSFT
* Microsoft Alias: **richdi**

**Comment by bishalgoswami** [comment]
Bug 820166 has been logged to address this issue.
