### ISSUE TITLE
Link in paragrah 3 is broken

### ISSUE THREAD

**Issue by JTWWI** [MicrosoftDocs/dynamics-365-unified-operations-public#4586]
In this paragrah;
"For some tutorials, you will need to create the FleetManagement solution if it is not on your computer. The steps to create it are listed in [Tutorial: Create a Fleet Management solution file out of the Fleet Management models in the AOT](https://community.dynamics.com/ax/b/newdynamicsax/archive/2016/05/19/tutorial-create-a-fleet-management-solution-file-out-of-the-fleet-management-models-in-the-aot)."

The link does not resolve.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d6a89134-b5ae-dea3-cb41-67ae667cba50
* Version Independent ID: 5777de53-f797-cdd7-f6b3-438eac9c23fb
* Content: [Fleet Management sample application - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/introduction-fleet-management-sample)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/introduction-fleet-management-sample.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/dev-tools/introduction-fleet-management-sample.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @gianugo
* Microsoft Alias: **gianura**

**Comment by bishalgoswami** [comment]
Bug 820264 has been logged to address this issue.

**Comment by josaw1** [comment]
This fix will go live later today.
