### ISSUE TITLE
Definition of Single threaded tables?

### ISSUE THREAD

**Issue by ChaitanyaGolla** [MicrosoftDocs/dynamics-365-unified-operations-public#4588]
Would like to know below details?
Definition of single threaded tables and multi threaded tables in Finance and operation apps.
Factors to categorize the tables as single and multi threaded tables.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: caa6a38c-03b6-7949-e383-aaaa4ca05ff9
* Version Independent ID: 0bf0e3d4-33b7-d54b-e2bc-1531bfbeee6e
* Content: [Considerations for initial synchronization - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/initial-sync-guidance#single-threaded-entities)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/initial-sync-guidance.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/dual-write/initial-sync-guidance.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @RamaKrishnamoorthy
* Microsoft Alias: **ramasri**

**Comment by bishalgoswami** [comment]
Bug 820326 has been logged to address this issue.

**Comment by twheeloc** [comment]
@ChaitanyaGolla, thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
