### ISSUE TITLE
run.py Scrip is not correct

### ISSUE THREAD

**Issue by Jessieliu111** [MicrosoftDocs/dynamics-365-unified-operations-public#4589]
[Enter feedback here]
HI team, 

For the run.py referred by this doc, the source_directory path is not correct. In below link, line 93 should be  source_directory="src/REntryScript", rather than  source_directory="REntryScript". 
Please help adjust this.
Thanks.
https://github.com/microsoft/Templates-For-Dynamics-365-Supply-Chain-Management-Demand-Forecasting-With-Azure-Machine-Learning/blob/main/src/run.py

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a0e5d0e5-6293-10a2-bd86-36815589bab0
* Version Independent ID: ae3a0cdd-93e5-5f26-1b5f-679d90f8d0b4
* Content: [Demand forecasting setup - Supply Chain Management | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/supply-chain/master-planning/demand-forecasting-setup?source=recommendations#demand-forecast-parameters)
* Content Source: [articles/supply-chain/master-planning/demand-forecasting-setup.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/master-planning/demand-forecasting-setup.md)
* Service: **dynamics-365-supply-chain**
* GitHub Login: @t-benebo
* Microsoft Alias: **benebotg**

**Comment by bishalgoswami** [comment]
Bug 820334 has been logged to address this issue.

**Comment by kamaybac** [comment]
@Jessieliu111 , thank you for reporting this issue. We have updated the code sample.

**Comment by andreygarmash** [comment]
Hi @Jessieliu111, the error you're getting might be due to the fact that your REntryScript folder is not on the same level as run.py in the Notebooks as advised in the [public docs](https://learn.microsoft.com/en-us/dynamics365/supply-chain/master-planning/demand-forecasting-setup#ml-workspace-script). Could you please confirm that?

**Comment by Jessieliu111** [comment]
Hi team,

It's below structure when cx gets the error. Please let me know if anything else.
Thanks.

***@***.***

Best regards,
Jessie Liu
Support Engineer | Azure IoT&AI Support Team
Phone: (0510) 6665 8360
Mon-Fri 9:00-17:30/7:00-4:00 (UTC+8)
No.111, Linghu Road, Xin Wu District, Wuxi, Jiangsu, China
***@***.***
Delighting our customers is our #1 priority. We welcome your comments and suggestions about how we can improve the support we provide to you.

**Comment by andreygarmash** [comment]
Hi @Jessieliu111,

Thanks for the quick reply. It seems like you attached an image with the structure but it is not shown here. Could you please repost it?

**Comment by Jessieliu111** [comment]
Hi team,

Please check this one.
[A screenshot of a computer  Description automatically generated]

Best regards,
Jessie Liu
Support Engineer | Azure IoT&AI Support Team
Phone: (0510) 6665 8360
Mon-Fri 9:00-17:30/7:00-4:00 (UTC+8)
No.111, Linghu Road, Xin Wu District, Wuxi, Jiangsu, China
***@***.***
Delighting our customers is our #1 priority. We welcome your comments and suggestions about how we can improve the support we provide to you.
