### ISSUE TITLE
Open Fleet Management Solution section, link to Tutorial: Create a Fleet Management solution.. is broken

### ISSUE THREAD

**Issue by JTWWI** [MicrosoftDocs/dynamics-365-unified-operations-public#4591]
This link is broken: [Tutorial: Create a Fleet Management solution file out of the Fleet Management models in the AOT](https://community.dynamics.com/ax/b/newdynamicsax/archive/2016/05/19/tutorial-create-a-fleet-management-solution-file-out-of-the-fleet-management-models-in-the-aot).

**Comment by josaw1** [comment]
Fixed.
