### ISSUE TITLE
Can't complete any tutorials on this page because link to Tutorial: Create a Fleet Management solution file... is broken

### ISSUE THREAD

**Issue by JTWWI** [MicrosoftDocs/dynamics-365-unified-operations-public#4593]
This page: 
[Tutorial: Create a Fleet Management solution file out of the Fleet Management models in the AOT](https://community.dynamics.com/ax/b/newdynamicsax/archive/2016/05/19/tutorial-create-a-fleet-management-solution-file-out-of-the-fleet-management-models-in-the-aot).
No longer exists, and many MS Learn / MS Documentation pages for 'Development and administration for finance and operations apps' depend on it, including the page I am commenting about here.
Can this please be fixed?

**Comment by josaw1** [comment]
Fixed.
