### ISSUE TITLE
In section "Map your Azure DevOps project to your local model store and projects folder" step 3 to step 4 seems to be missing something

### ISSUE THREAD

**Issue by JTWWI** [MicrosoftDocs/dynamics-365-unified-operations-public#4594]
Step 3 says: "Map the Metadata folder of your team project to the root folder of the model store on your local drive (Typically K:\AOSService\PackagesLocalDirectory), an example is shown in the image below."
Step 3 image shows: https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/media/vsofolders21.png
Then step 4 says: "Click Map, and on the next dialog, click No."

What I think is missing:
No instruction is given on how to start the mapping. What I did was use File > Source Control > Advanced > Map

What is confusing:
The image shows c:\packages\ which makes sense if you're doing a tutorial not on a Cloud Hosted VM.

**Comment by twheeloc** [comment]
@JTWWI, thank you for your feedback. We have passed this feedback onto the product team for consideration.
