### ISSUE TITLE
Update required to reflect no RDP access to sandboxes

### ISSUE THREAD

**Issue by GlenTurnbullD365** [MicrosoftDocs/dynamics-365-unified-operations-public#4596]
[Enter feedback here]
As RDP access to sandbox environments has been removed some time ago, this page should be updated to reflect that - it's still suggesting you must remote desktop in to run Powershell scripts and stop services. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5fd6f761-42ef-48b4-7d33-59d90e6cf053
* Version Independent ID: 0fedd77b-c9dc-6cc8-1366-ccd52678d94c
* Content: [Reset the Financial reporting data mart - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/reset-financial-reporting-datamart-after-restore)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/reset-financial-reporting-datamart-after-restore.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/analytics/reset-financial-reporting-datamart-after-restore.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @aprilolson
* Microsoft Alias: **aolson**

**Comment by bishalgoswami** [comment]
Bug 821505 has been logged to address this issue.

**Comment by twheeloc** [comment]
@GlenTurnbullD365, thank you for your feedback. The article has been updated.
