### ISSUE TITLE
Different labels for same PowerBI file entity store

### ISSUE THREAD

**Issue by d47447** [MicrosoftDocs/dynamics-365-unified-operations-public#4597]
[Enter feedback here]

It regarding entity store for Power BI in D365FO, one of the entity store got a new version (V2) but their labels creating confusion as both are not similar, pl refer below screenshot, pl have a look at system. 

![image](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/assets/10023144/272fcb73-0797-4a82-9968-e84128da1435)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 335abc87-ef2e-9a0c-ce7e-690316800707
* Version Independent ID: b8b113b5-68e8-d8e9-77cf-a755ea826d58
* Content: [Demo data overview - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/demo-data)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/demo-data.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/demo-data.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @sericks007
* Microsoft Alias: **sericks**

**Comment by bishalgoswami** [comment]
Bug 821519 has been logged to address this issue.

**Comment by josaw1** [comment]
@twheeloc can you please look into this?

**Comment by twheeloc** [comment]
@d47447, thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
