### ISSUE TITLE
Upgrade from 8.0 to 8.1

### ISSUE THREAD

**Issue by rat-af** [MicrosoftDocs/dynamics-365-unified-operations-public#460]
With the release of application 8.1 is there anything specific required to move from 8.0 to 8.1?  Also, do I need to perform a code upgrade if my customisations are already on 8.0?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ced3fde-f2c4-5fbe-f543-fac25f846a34
* Version Independent ID: 25e679fc-0ed8-fe8b-bb77-394e7047182c
* Content: [Process for moving to the latest update of Finance and Operations - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/upgrade-latest-update)
* Content Source: [articles/dev-itpro/migration-upgrade/upgrade-latest-update.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/migration-upgrade/upgrade-latest-update.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @robadawy
* Microsoft Alias: **tabell**

**Comment by sericks007** [comment]
We'll soon be publishing a topic about updating from 8.0 to 8.1. I'll let you know when it's available.

**Comment by sericks007** [comment]
For information about how to update environments from 8.0 to 8.1 please see [Update environments from version 8.0 to 8.1](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/appupdate-80-81).
