### ISSUE TITLE
Possible incorrect information in bug link

### ISSUE THREAD

**Issue by mattgo79-MSFT** [MicrosoftDocs/dynamics-365-unified-operations-public#4601]
If you visit this website, https://learn.microsoft.com/en-us/dynamics365/finance/get-started/whats-new-changed-10-0-35 and you navigate to the Bug Fixes section, there is a link to [LCS](https://fix.lcs.dynamics.com/Issue/Details?bugId=817204), that is supposed to show you all fixes for this release.  But it takes you to a fix for AX 2012 that was released in 2013.  Please advise.  Thank you!

Matt

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2e2fee6b-5f09-0c69-54cb-1814f7563e17
* Version Independent ID: 2e2fee6b-5f09-0c69-54cb-1814f7563e17
* Content: [What's new or changed in Dynamics 365 Finance 10.0.35 (July 2023) - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/get-started/whats-new-changed-10-0-35)
* Content Source: [articles/finance/get-started/whats-new-changed-10-0-35.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/get-started/whats-new-changed-10-0-35.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @twheeloc
* Microsoft Alias: **twheeloc**

**Comment by twheeloc** [comment]
@mattgo79-MSFT, thank you for letting us know. The topic will be updated with the correct link later today.
