### ISSUE TITLE
KB List in LCS missing page 2 of 2.

### ISSUE THREAD

**Issue by mattgo79-MSFT** [MicrosoftDocs/dynamics-365-unified-operations-public#4602]
Under the Bug fixes section, there is a link to LCS that is supposed to show you the complete KB list, but only 1 of 2 shows.  Page 2 of 2 is missing.  Here is the link to LCS: https://fix.lcs.dynamics.com/Issue/Details?bugId=787268 . 

Please advise.  
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6f78b2fd-3e6a-0ec6-6b96-f1bdafecf009
* Version Independent ID: 6f78b2fd-3e6a-0ec6-6b96-f1bdafecf009
* Content: [What's new or changed in Dynamics 365 Finance 10.0.32 (March 2023) - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/get-started/whats-new-changed-10-0-32)
* Content Source: [articles/finance/get-started/whats-new-changed-10-0-32.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/get-started/whats-new-changed-10-0-32.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @twheeloc
* Microsoft Alias: **kfend**

**Comment by bishalgoswami** [comment]
Bug 821898 has been logged to address this issue.

**Comment by twheeloc** [comment]
@mattgo79-MSFT, the KB has been updated.
