### ISSUE TITLE
Content now not available Broken links, perhaps due to the new Community Site CMS system?

### ISSUE THREAD

**Issue by JTWWI** [MicrosoftDocs/dynamics-365-unified-operations-public#4603]
Hello,

Note: Please check the links on the pages, not just that the link resolves. At first if you click any links on this page, it will say page not found, then resolve to a page.  **BUT** on the resultant page any linked Presentation Slides in PDF or Presentations in Video fail to work.  Downloads will not work and view in browser do not work.

I think it may be related to this past weekend, June 17th-18th 2023, when it looks like the MS Community Content Management System was upgraded or replaced.

As a result, the Learning Catalog for D365 developers, which I was working my way through, is not usable.

Can this be checked carefully and in full, the learning catalog is a great resource and I'd like to be able to continue to use it.

Best Regards.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 888a4451-c840-625a-d0da-63cc3fe1f55c
* Version Independent ID: f75e81ed-7ba4-123e-5405-99704aaf98d1
* Content: [Learning catalog for Dynamics 365 Finance developers - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/get-started/learning-catalog-developer)
* Content Source: [articles/finance/get-started/learning-catalog-developer.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/get-started/learning-catalog-developer.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @cstorega
* Microsoft Alias: **cstorega**

**Comment by bishalgoswami** [comment]
Bug 821950 has been logged to address this issue.

**Comment by cstorega** [comment]
Fixed in https://github.com/MicrosoftDocs/Dynamics-365-Operations/pull/16319.

**Comment by cstorega** [comment]
@bishalgoswami - please close as fixed - when https://github.com/MicrosoftDocs/Dynamics-365-Operations/pull/16319 is merged, Thanks.
