### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by AartBluestoke** [MicrosoftDocs/dynamics-365-unified-operations-public#4604]
this link text is 404:
[Azure SQL Database Geo-Restore](https://azure.microsoft.com/blog/azure-sql-database-geo-restore/).
if you click the text it goes to
https://azure.microsoft.com/blog/azure-sql-database-geo-restore/
which redirects to 
https://azure.microsoft.com/en-us/blogcategory/databases/
which is 404.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 496ab166-952c-1325-4132-f680af468674
* Version Independent ID: 7ab562ca-bd56-ce01-0df2-d1a6fd244c05
* Content: [Business continuity and disaster recovery - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/business-continuity-disaster-recovery)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/business-continuity-disaster-recovery.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/sysadmin/business-continuity-disaster-recovery.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @MicroSri
* Microsoft Alias: **sriknair**

**Comment by bishalgoswami** [comment]
Bug 821955 has been logged to address this issue.

**Comment by twheeloc** [comment]
@AartBluestoke, thank you for the feedback. The article has been updated.
