### ISSUE TITLE
Latest release is missing

### ISSUE THREAD

**Issue by jimwillsher** [MicrosoftDocs/dynamics-365-unified-operations-public#4606]
[Enter feedback here]

Hi, 10.0.34 is release and 10.0.35 is in preview. Can you add a section for 10.0.34 please? Many thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a81f2d2a-8eac-df73-bf48-2a59ad0ff5ac
* Version Independent ID: 26eb9087-c4d9-85e4-957c-9144269800ee
* Content: [What's new or changed in Dynamics 365 Finance - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/get-started/whats-new-home-page)
* Content Source: [articles/finance/get-started/whats-new-home-page.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/get-started/whats-new-home-page.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @twheeloc
* Microsoft Alias: **twheeloc**

**Comment by twheeloc** [comment]
@jimwillsher, thank you for the feedback. The article has been updated and changes will be reflected later today.
