### ISSUE TITLE
Missing documentation for the MSDyn365Commerce_LOCAL_BASE_URL setting that can be specified in this file

### ISSUE THREAD

**Issue by brettchristiansen** [MicrosoftDocs/dynamics-365-unified-operations-public#4607]
There is no documentation of the MSDyn365Commerce_LOCAL_BASE_URL setting for the .env file.  Without this setup, when users attempt to point at a local retail server many things break and adding this is a much simpler alternative to having to run Fiddler + useing ?debug=true (which also isn't documented)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2e28ccbf-8771-74fe-8bc0-1f6ed4973d53
* Version Independent ID: d17afca6-f765-ea32-12b6-f35720b90c93
* Content: [Configure a development environment (.env) file - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/e-commerce-extensibility/configure-env-file)
* Content Source: [articles/commerce/e-commerce-extensibility/configure-env-file.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/e-commerce-extensibility/configure-env-file.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @samjarawan
* Microsoft Alias: **samjar**

**Comment by bishalgoswami** [comment]
Bug 822668 has been logged to address this issue.

**Comment by samjarawan** [comment]
I no longer work Commerce team…

Sent from my phone...
________________________________

**Comment by twheeloc** [comment]
@brettchristiansen, thank you for your feedback.  We have passed this feedback onto the product team for consideration.
