### ISSUE TITLE
How are the amounts on each posting type calculated

### ISSUE THREAD

**Issue by Ryde65** [MicrosoftDocs/dynamics-365-unified-operations-public#4608]
I need to know how the amounts are calculated, otherwise it is impossible to figure out what accounts they should be posted on.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1b0b775f-5209-f4ce-5721-306541e1fec9
* Version Independent ID: 1b0b775f-5209-f4ce-5721-306541e1fec9
* Content: [Standard cost variance posting - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/general-ledger/standard-cost-variance-posting)
* Content Source: [articles/finance/general-ledger/standard-cost-variance-posting.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/general-ledger/standard-cost-variance-posting.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @RachelProfitt
* Microsoft Alias: **raprofit**

**Comment by bishalgoswami** [comment]
Bug 822751 has been logged to address this issue.

**Comment by sericks007** [comment]
@josaw1, please assign to the appropriate person. Thanks!

**Comment by josaw1** [comment]
@twheeloc, can you please follow up on this?

**Comment by twheeloc** [comment]
@Ryde65, thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
