### ISSUE TITLE
Service update availability update after 10.0.38

### ISSUE THREAD

**Issue by ThoJensen** [MicrosoftDocs/dynamics-365-unified-operations-public#4609]
When is the "Service update availability" page expected to be updated with release schedule after 10.0.38?

**Comment by josaw1** [comment]
@johnmichalak can you please respond?

**Comment by ThoJensen** [comment]
Any update to this one?

**Comment by ThoJensen** [comment]
?

**Comment by twheeloc** [comment]
@ThoJensen, this article has been updated.
