### ISSUE TITLE
LCS environment update deployment status is always downloading

### ISSUE THREAD

**Issue by grubby19870810** [MicrosoftDocs/dynamics-365-unified-operations-public#461]
I tried to promote the code change to sandbox. The code was successfully uploaded. However, the whole package was not able to download to sandbox. The deployment status has been DOWNLOADING for a week now. Not able to kill it.

 Can Microsoft help to kill this process?
![applyissue](https://user-images.githubusercontent.com/38061746/46454657-c0b94c80-c7d9-11e8-9564-903f2a72f006.png)

**Comment by kfend** [comment]
Thanks for contacting us! Unfortunately, we're unable to handle questions for the product here. To contact Support, consider one of the options described here: Support contact options. In particular, you might want to go to the Dynamics 365 for Finance and Operations community page to get help with your questions from the Dynamics community.
