### ISSUE TITLE
Missing the symbol of "bitwise inclusive OR" in the "Order of operator precedence" section

### ISSUE THREAD

**Issue by gbamqzkdyg** [MicrosoftDocs/dynamics-365-unified-operations-public#4611]
[Enter feedback here]

The operator name of the 3rd row of the "Order of operator precedence" is "additive, bitwise inclusive OR". The corresponding syntax should be "+ - |", while currently it is displayed as "+ -". The symbol for the inclusive OR operator (|) is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 17244b39-b36f-56de-6056-19e4753a6692
* Version Independent ID: 71c4df00-c792-74fd-e2b8-bd64bc46ccb6
* Content: [Operator precedence - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-ref/xpp-operator-precedence)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-ref/xpp-operator-precedence.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/dev-ref/xpp-operator-precedence.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @pvillads
* Microsoft Alias: **pvillads**

**Comment by bishalgoswami** [comment]
Bug 822993 has been logged to address this issue.

**Comment by josaw1** [comment]
Fixed. Will be published today.
