### ISSUE TITLE
Missing the symbol of "bitwise inclusive OR" in the "Operator precedence" section

### ISSUE THREAD

**Issue by gbamqzkdyg** [MicrosoftDocs/dynamics-365-unified-operations-public#4612]
[Enter feedback here]

The operator name of the 3rd row of the "Operator precedence" is "additive, bitwise inclusive OR". The corresponding syntax should be "+ - |", while currently it is displayed as "+ -". The symbol for the inclusive OR operator (|) is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dcd01709-02ec-2345-3e11-b404b2c8023f
* Version Independent ID: 04233315-0218-bd79-454d-5e98a75e95a6
* Content: [X++ operators - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-ref/xpp-operators)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-ref/xpp-operators.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/dev-ref/xpp-operators.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by bishalgoswami** [comment]
Bug 822992 has been logged to address this issue.

**Comment by josaw1** [comment]
Fixed. Will be published today.
