### ISSUE TITLE
No documentation and reference available for inventory movement within store in POS

### ISSUE THREAD

**Issue by 5fq** [MicrosoftDocs/dynamics-365-unified-operations-public#4616]
There is no reference or documentation on the support for in-store inventory transfers between locations within the store. The feature was made GE in Aug 2021.

Feature URL: https://learn.microsoft.com/en-us/dynamics365-release-plan/2021wave2/commerce/dynamics365-commerce/support-inventory-movement-between-in-store-locations-pos 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2fafe12b-5dcb-7e32-074d-3776210e9698
* Version Independent ID: f2df7539-d7db-fe8a-9793-e728d715b619
* Content: [Store inventory management - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/work-with-store-inventory)
* Content Source: [articles/commerce/work-with-store-inventory.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/work-with-store-inventory.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @BrianShook
* Microsoft Alias: **hhaines**

**Comment by bishalgoswami** [comment]
Bug 834386 has been logged to address this issue.

**Comment by twheeloc** [comment]
@5fq, thank you for your feedback. We have passed this feedback onto the product team for consideration.
