### ISSUE TITLE
Generate model with source code using Nuget pipeline

### ISSUE THREAD

**Issue by rat-af** [MicrosoftDocs/dynamics-365-unified-operations-public#4618]
This document does not indicate how to generate a model with source and binary only.  The traditional approach that uses a VM has a powershell step that runs a 'GeneratePackages.ps1' script.  If the '-NoSource' option is set to 0, then 2 packages are generated, one binary, and one with source.

Using Nuget, the default examples creates a deployable package with no source.  I can't find any information that shows how you can also generate a package with source with Nuget pipelines.  How can this be done using NuGet?

Regards,
rat-af

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 10459944-bcf8-c5fa-d180-9fb4bb3722da
* Version Independent ID: 29ae9d16-ed7c-92d8-0300-4fc46c777ddf
* Content: [Build automation that uses Microsoft-hosted agents and Azure Pipelines - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-gb/dynamics365/fin-ops-core/dev-itpro/dev-tools/hosted-build-automation)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/hosted-build-automation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/dev-tools/hosted-build-automation.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @gianugo
* Microsoft Alias: **gianura**

**Comment by bishalgoswami** [comment]
Bug 834385 has been logged to address this issue.

**Comment by josaw1** [comment]
@peter-villadsen can you please review?

**Comment by twheeloc** [comment]
@rat-af, thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
