### ISSUE TITLE
'Account reconciliation' as bank account Reconcile command option, not sure if this is visible.

### ISSUE THREAD

**Issue by JTWWI** [MicrosoftDocs/dynamics-365-unified-operations-public#4620]
Instruction text does not match in step 1 for Application Version 10.0.31.
Instrucion reads: 
1. Go to Cash and bank management > Bank Accounts > Bank accounts. Select the bank account to reconcile with the bank statement and select Reconcile > Account reconciliation.
But what I see is this menu of options in the Reconcile ribbon:
Bank statements, Bank transactions, Bank reconciliation, Reconciled transactions, and Unreconciled transactions.

Or maybe I'm looking in the wrong place?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3d3b6674-f4ee-1bf4-2ac3-53aef9f762eb
* Version Independent ID: 3137c70e-92ff-e698-1d58-ecbaa6a72d4c
* Content: [Reconcile a bank account - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/cash-bank-management/reconcile-bank-account)
* Content Source: [articles/finance/cash-bank-management/reconcile-bank-account.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/cash-bank-management/reconcile-bank-account.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @angelad116
* Microsoft Alias: **angelading**

**Comment by josaw1** [comment]
@twheeloc can you please review?

**Comment by twheeloc** [comment]
@JTWWI, thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
