### ISSUE TITLE
Is this product version only for manufacturing?

### ISSUE THREAD

**Issue by fysal-dev** [MicrosoftDocs/dynamics-365-unified-operations-public#4624]
Can we use Product version for retail products?.

For example. lets say, I have a variant (Size 500ml) of product Cooking Oil, But after a few years, supplier released the new version of the same Product Description, cost and price, but reduce the size of the product to 480ml and stop the old version of 500ml,

So, If I create a new variant, then I will lose the previous history,

Suppose, If I create a new version of the same product, It will keep having tracking of old version of Inventory movement and sales of both 500ml and 480 ml.

Is it possible to create a new version of existing product variant(RETAIL PRODUCT, not Manufacturing product or BOM)?

If it can create with version, Is it advisable to create product version for Retail Product?

If not, What is the recommended way to track both old 500ml and 480ml product?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d7b318d2-e930-cf94-e9a8-e5bab7b1408c
* Version Independent ID: 69c78df6-a4ea-33d5-456f-e2a132035bff
* Content: [Product dimensions - Supply Chain Management | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/supply-chain/pim/product-dimensions)
* Content Source: [articles/supply-chain/pim/product-dimensions.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/pim/product-dimensions.md)
* Service: **dynamics-365-supply-chain**
* GitHub Login: @t-benebo
* Microsoft Alias: **benebotg**

**Comment by bishalgoswami** [comment]
Bug 834383 has been logged to address this issue.

**Comment by kamaybac** [comment]
@fysal-dev , thank you for contacting us. It looks like you have a support question. This forum isn't intended for providing support, but for discussing documentation issues. I'm not sure whether the feature will work in the way you are suggesting, so I recommend you contact Microsoft Support for assistance.
