### ISSUE TITLE
Wrong command sample

### ISSUE THREAD

**Issue by d47447** [MicrosoftDocs/dynamics-365-unified-operations-public#4625]
[Enter feedback here]

https://learn.microsoft.com/en-us/sql/tools/sqlpackage-download#get-sqlpackage-net-core-for-windows is showing the wrong command, 

Its syas to use this command 

cd C:\Program Files (x86)\Microsoft SQL Server\140\DAC\bin\
SqlPackage.exe /a:export /ssn:localhost /sdn:AXDB_CopyForExport /tf:D:\Exportedbacpac\AXDB_CopyForExport.bacpac /p:CommandTimeout=1200 /p:VerifyFullTextDocumentTypesSupported=false /SourceTrustServerCertificate:True

Where in DEV box there is folder exist for 'C:\Program Files (x86)\Microsoft SQL Server\140\DAC\bin\'
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8eb7ed3e-f7b9-e384-7308-516deda06bcc
* Version Independent ID: 3cd2e0d0-24fd-c019-eecc-8af6e7e7e66c
* Content: [Golden configuration promotion - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/dbmovement-scenario-goldenconfig)
* Content Source: [articles/fin-ops-core/dev-itpro/database/dbmovement-scenario-goldenconfig.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/database/dbmovement-scenario-goldenconfig.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by d47447** [comment]
The right path for this should be as below

C:\Program Files\Microsoft SQL Server\160\DAC\bin

**Comment by bishalgoswami** [comment]
Bug 834382 has been logged to address this issue.

**Comment by twheeloc** [comment]
Thanks for your feedback. We have passed this feedback onto the product team for consideration.
