### ISSUE TITLE
Purpose of bank file formats AUS

### ISSUE THREAD

**Issue by LUX230701** [MicrosoftDocs/dynamics-365-unified-operations-public#4626]
[Could you please help me understanding what is the purpose of the listed bank file formats for Australia ?  After importing them from ER depository, I am not able to find them in Method of payment, file format setup.  I am currenlty looking for the import customer payment format for AUS, could you please advise?  Thanks]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 111bada3-a333-b517-5907-28f7b9436da4
* Version Independent ID: 0b322b8d-a9bb-98d4-fbc9-e706de3f8a5f
* Content: [Australia overview - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/localizations/australia#bank-file-formats-for-australian-banks)
* Content Source: [articles/finance/localizations/australia.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/australia.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **kfend**

**Comment by twheeloc** [comment]
@LUX230701, thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
