### ISSUE TITLE
Dataverse support for Dynamics 365 F&O On Prem

### ISSUE THREAD

**Issue by 5fq** [MicrosoftDocs/dynamics-365-unified-operations-public#4628]
It is not documented anywhere on the compatibility level/support of Dataverse with Dynamics 365 F&O On-Prem. We can avoid a lot of confusion if it can be called out on any of the Microsoft docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 39b247a8-1e40-07d0-f44b-46f3f362a02d
* Version Independent ID: 09725d7e-90ea-f6a9-3edb-28ff4bcc7510
* Content: [Microsoft Power Platform integration with finance and operations apps - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/power-platform/overview)
* Content Source: [articles/fin-ops-core/dev-itpro/power-platform/overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/power-platform/overview.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by bishalgoswami** [comment]
Bug 834380 has been logged to address this issue.

**Comment by twheeloc** [comment]
Thanks for your feedback. We have passed this feedback onto the product team for consideration.
