### ISSUE TITLE
Missing guidance for the number format

### ISSUE THREAD

**Issue by Gadgetgeek2000** [MicrosoftDocs/dynamics-365-unified-operations-public#4629]
[Enter feedback here]
We attempted to change the format from -#### to .####. This malfunctioned completely. It truncated the project number (-0001 became -1, and the updated project number became PRJ000-01.1  or some other garbage.

We need to know how to force the leading zeroes in the format--there is no guidance on the page. Should I just enter "."? or ".0000" or something else? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 096c3daa-2e95-c034-6c2e-98b85116a987
* Version Independent ID: e019bf0b-60d5-dc0d-5d59-d8d2b5aff937
* Content: [Make the chart of accounts delimiter unique - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/chart-accounts-delimiter-unique)
* Content Source: [articles/fin-ops-core/dev-itpro/migration-upgrade/chart-accounts-delimiter-unique.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/migration-upgrade/chart-accounts-delimiter-unique.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @RyanCCarlson2
* Microsoft Alias: **RCarlson**

**Comment by RyanCCarlson2** [comment]
@Gadgetgeek2000 The #### mask for leading zeros in my sub-project setup works fine in my quick test on the latest builds.  Please contact support with the information if this does not work in a repeated trial for you.

**Comment by twheeloc** [comment]
@Gadgetgeek2000, thanks for contacting us. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
