### ISSUE TITLE
Multiple extensions for the same label file

### ISSUE THREAD

**Issue by OksanaKovaliova** [MicrosoftDocs/dynamics-365-unified-operations-public#463]
Can we have multiple extensions for the same label file? for example AccountsPayable_Extension1 and AccountsPayable_Extension2? (like one is created by Partner, another one - by ISV) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 233d83d4-b489-a31d-40da-35e4e29dc901
* Version Independent ID: ef9ca1d6-0af5-1a8e-31a7-b71bdc8a3dbf
* Content: [Change labels by using label extension files - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/extensibility/change-label)
* Content Source: [articles/dev-itpro/extensibility/change-label.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/extensibility/change-label.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @smithanataraj
* Microsoft Alias: **smnatara**

**Comment by kfend** [comment]
Closing for now. Please reopen if you have tried using multiple extensions for the same label file and it is not working.
