### ISSUE TITLE
Add users permission requirements to BPM public documentation

### ISSUE THREAD

**Issue by v-felipel** [MicrosoftDocs/dynamics-365-unified-operations-public#4631]
Hello Team,

Customers are sharing their concerns regarding the documentation as there is no information provided regarding the permissions necessary to publish the libraries and only the project owner and admin users for the projects can publish the BPM libraries.

Please consider adding this information in the future.

Thank you in advance for your time and support.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ce25d25b-daa2-02f8-89ac-69222074b126
* Version Independent ID: 1b3ab8e7-af9b-cc96-0936-2ce8594af909
* Content: [Complete tasks in Business process modeler (BPM) - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/complete-tasks-bpm#publish-a-bpm-library)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/complete-tasks-bpm.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/lifecycle-services/complete-tasks-bpm.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @AngelMarshall
* Microsoft Alias: **tsmarsha**

**Comment by bishalgoswami** [comment]
Bug 24809341 has been logged to address this issue.

**Comment by twheeloc** [comment]
Thanks for your feedback. We have passed this feedback onto the product team for consideration.
