### ISSUE TITLE
Link to sample app is missing

### ISSUE THREAD

**Issue by MichaelFruergaardPontoppidan** [MicrosoftDocs/dynamics-365-unified-operations-public#4633]
This page should have a direct link to https://aka.ms/scmbetaapp

The page is very detailed, and it gives the impression that this is hard to configure. The sample app makes it very easy, you just install it in your PowerBI Dashboard, and connect it to the ApplicationInsights instance - and voila, you have visualizations of all the 30+ telemetry events.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e0aeed7d-e4a1-94ac-7c30-022bcbd42f70
* Version Independent ID: 7063449a-a43c-9af2-17d1-9189ec00a16f
* Content: [Monitor Warehouse Management usage and performance - Supply Chain Management | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/supply-chain/warehousing/application-insights-monitor-usage-performance#review-sample-code-faqs-and-more-in-the-supply-chain-management-telemetry-github-repository)
* Content Source: [articles/supply-chain/warehousing/application-insights-monitor-usage-performance.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/warehousing/application-insights-monitor-usage-performance.md)
* Service: **dynamics-365-supply-chain**
* GitHub Login: @Mirzaab
* Microsoft Alias: **mirzaab**

**Comment by bishalgoswami** [comment]
Bug 834378 has been logged to address this issue.

**Comment by kamaybac** [comment]
The topic is updated.
