### ISSUE TITLE
Outdated information

### ISSUE THREAD

**Issue by OlgaPetrovaFT** [MicrosoftDocs/dynamics-365-unified-operations-public#4635]
Many questions on this page are extremely outdated, they speak about version 8.1

this link does not lead anywhere - [International availability of Dynamics 365](https://www.microsoft.com/trustcenter/privacy/dynamics365-operations-location)
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 98ef3846-e354-a28e-c904-3ea201f7ad3b
* Version Independent ID: 548d4b90-e614-d0c9-8faa-90df3c80d1c6
* Content: [Self-service deployment FAQ - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/deploymentfaq#what-regions-are-supported-on-self-service-in-north-america)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/deploymentFAQ.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/deployment/deploymentFAQ.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @rashmansur
* Microsoft Alias: **rashmim**

**Comment by bishalgoswami** [comment]
Bug 834376 has been logged to address this issue.

**Comment by twheeloc** [comment]
Thanks for your feedback. We have passed this feedback onto the product team for consideration.
