### ISSUE TITLE
Inaccurate documentation re breaking the chains of available restore points

### ISSUE THREAD

**Issue by agusriy** [MicrosoftDocs/dynamics-365-unified-operations-public#4638]
In the documentation it says that

Several frequently used actions create a new database that won't have the same restore point history as the previously used database. These actions include point-in-time restores, database refreshes, database imports, and point-in-time restores from the production environment to the sandbox environment.

I believe this is inaccurate. It seems only database point-in-time restore against its own database that creates a new database, resulting in breaking the chain of available restore points (as logically because it is new database different to the old one).
The other actions I am not sure but I certainly tested myself that after Import operation from bacpac in LCS, I can restore the database to point-in-time. It seems because the Import action retain the target database thus retain the backup history.

Please correct this documentation. I believe at least you should remove the database refreshes and database imports.
Not sure about point-in-time restore from production. If it is done by creating new database then it will lose backup history.
Thanks,
Agus Riyadi
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 805f3739-0cad-d6ab-7db0-175c972f189f
* Version Independent ID: 68be2d28-d5e9-471d-8648-a8cbae2e1e7d
* Content: [Database point-in-time restore (PITR) - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/database-point-in-time-restore)
* Content Source: [articles/fin-ops-core/dev-itpro/database/database-point-in-time-restore.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/database/database-point-in-time-restore.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by bishalgoswami** [comment]
Bug 834373 has been logged to address this issue.

**Comment by twheeloc** [comment]
@agusriy, thank you for your feedback. We have passed this feedback onto the product team for consideration.
