### ISSUE TITLE
Label file sample

### ISSUE THREAD

**Issue by OksanaKovaliova** [MicrosoftDocs/dynamics-365-unified-operations-public#464]
Hi,
It would be good to see sample of label file - is it the same format as X++ label file and stored in AOT or? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac87ed28-11fd-54d2-e20b-2a46b7bef037
* Version Independent ID: 1eb0d33a-1f03-21ff-d098-4fc4a5824c6a
* Content: [Create localizable labels - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/user-interface/create-localizable-labels-client)
* Content Source: [articles/dev-itpro/user-interface/create-localizable-labels-client.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/user-interface/create-localizable-labels-client.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RobinARH
* Microsoft Alias: **shshabazz**

**Comment by ShylaThompson** [comment]
@OksanaKovaliova The following link might be helpful to you until we can update this topic with more information: https://kaya-consulting.com/how-to-create-a-new-language-or-country-to-dynamics-365-for-operations/ 
The link is not to a Microsoft post, but it shows some screenshots of working with label files. 

We're tracking the work on this topic internally, so I will close this issue for now. If you have further suggestions for improving our help content, please don't hesitate to log more issues.
