### ISSUE TITLE
User Load graphics - what do they tell us?

### ISSUE THREAD

**Issue by JTWWI** [MicrosoftDocs/dynamics-365-unified-operations-public#4641]
The Environment monitoring page, with Overview tab selected, what do the User Load graphics tell us?

What does BATCHAOS1 mean?
What does AOS1 mean?

How do I tell if anyone is actually logged in and making transactions??

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 64b5b03d-9169-f94e-f999-63bc5a8e68ac
* Version Independent ID: 177eb187-6962-ba30-7a63-86b0bf3452d7
* Content: [Monitoring and diagnostics tools in Lifecycle Services (LCS) - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/monitoring-diagnostics)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/monitoring-diagnostics.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/lifecycle-services/monitoring-diagnostics.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @AngelMarshall
* Microsoft Alias: **tsmarsha**

**Comment by bishalgoswami** [comment]
Bug 24809340 has been logged to address this issue.

**Comment by twheeloc** [comment]
@JTWWI, thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
