### ISSUE TITLE
Incomplete documentation for HRMC MTD VZAT web request headers format

### ISSUE THREAD

**Issue by vbrisan** [MicrosoftDocs/dynamics-365-unified-operations-public#4642]
In **Set up application-specific parameters** for MTD VAT web request headers format there is no example/suggestion given to the users as to what URL to set in Gov-Vendor-Public-IP & Gov-Client-Public-IP in order to collect the IP Address.

It should be added an example section similar to the one mentioned in the Business Central documentation page:

https://learn.microsoft.com/en-us/dynamics365/business-central/localfunctionality/unitedkingdom/fraud-prevention-data

E.g.:

IP addresses

Your company can sign up for any of the following endpoints:

https://api.db-ip.com/v2/free/self
https://www.cloudflare.com/cdn-cgi/trace
https://api.ipify.org/
https://jsonip.com/

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 13949dac-f9ce-5110-9f01-129964a5ee41
* Version Independent ID: 52d74b51-fdc8-301c-49c3-cd77a1480c82
* Content: [Prepare your environment to interoperate with HMRC's MTD VAT web service - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/localizations/emea-gbr-mtd-vat-integration-setup#entities)
* Content Source: [articles/finance/localizations/emea-gbr-mtd-vat-integration-setup.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/emea-gbr-mtd-vat-integration-setup.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @AdamTrukawka
* Microsoft Alias: **atrukawk**

**Comment by twheeloc** [comment]
@vbrisan, thank you for your feedback. We have passed this feedback onto the product team for consideration.
