### ISSUE TITLE
what would be the ideal size of a banner for an ultrawide monitor

### ISSUE THREAD

**Issue by Dimitri-Tetsch** [MicrosoftDocs/dynamics-365-unified-operations-public#4644]
A question/remark ... what would be the ideal size of a banner for an ultrawide monitor. Currently it looks a bit clunky on my ultrawide monitor when i use the ideal resolution for a banner image -> 1920 x 281 pixels. Thx in advance for your feedback/advise.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c18ee562-14d3-d68d-1d4c-f09cecff31fa
* Version Independent ID: 249f4593-263d-47d8-e769-6cdf3ac71b03
* Content: [Change the banner or logo - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/tasks/change-banner-or-logo)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/tasks/change-banner-or-logo.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/tasks/change-banner-or-logo.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by bishalgoswami** [comment]
Bug 834372 has been logged to address this issue.

**Comment by jasongre** [comment]
@bishalgoswami I don't have a specific size for an ultra wide monitor. I'd suggest keeping the same aspect ratio for the image size but try a few different resolutions until you find something that works better for your case.

**Comment by Dimitri-Tetsch** [comment]
Imho the uploaded img is resized and is therefore not really responsiveSent from my iPhoneOn 13 Sep 2023, at 19:33, Jason Green ***@***.***> wrote:﻿
@bishalgoswami I don't have a specific size for an ultra wide monitor. I'd suggest keeping the same aspect ratio for the image size but try a few different resolutions until you find something that works better for your case.
