### ISSUE TITLE
10.0.35 with wrong name.

### ISSUE THREAD

**Issue by fsilva-jr** [MicrosoftDocs/dynamics-365-unified-operations-public#4645]
Simple error but appreciate if you fix it!

The [ symbol at the beginning and the 10.0.34 number which should be 10.0.35

[[What's new and changed in Dynamics 365 Finance version 10.0.34](whats-new-changed-10-0-35.md) |

**Comment by twheeloc** [comment]
@fsilva-jr, thank you for the feedback. The article has been updated.
