### ISSUE TITLE
GA Update

### ISSUE THREAD

**Issue by Gopikrish25** [MicrosoftDocs/dynamics-365-unified-operations-public#4646]
[Kindly update the GA features as I can see it is just added as preview.]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 148f4f24-7541-a2ab-5e35-2af0dd44f268
* Version Independent ID: 148f4f24-7541-a2ab-5e35-2af0dd44f268
* Content: [Preview of Dynamics 365 Commerce 10.0.35 (July 2023) - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/get-started/whats-new-commerce-10-0-35)
* Content Source: [articles/commerce/get-started/whats-new-commerce-10-0-35.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/get-started/whats-new-commerce-10-0-35.md)
* Service: **dynamics-365-commerce**
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by bishalgoswami** [comment]
Bug 834371 has been logged to address this issue.
