### ISSUE TITLE
Linked to elearning seems wrong

### ISSUE THREAD

**Issue by DaGovernator** [MicrosoftDocs/dynamics-365-unified-operations-public#4648]
The link in the line "For online courses and training, check out [Dynamics 365 finance and operations](https://learn.microsoft.com/en-us/training/browse/?expanded=dynamics-365&products=dynamics-finance-operations&roles=administrator%2cdeveloper)." yields not results.

However if you change the product from dynamics-finance-operations to dynamics-finance it seems to provide the correct list of training material.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: eccd0dec-f56b-f773-2561-6c2bd9a7dc2d
* Version Independent ID: 1b39f024-aec3-fc02-e1b6-0e66b7e43403
* Content: [Development and administration for finance and operations apps - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/)
* Content Source: [articles/fin-ops-core/dev-itpro/index.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/index.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by twheeloc** [comment]
@DaGovernator, thank you for the feedback. The topic will be updated.
