### ISSUE TITLE
Section 'Production environments'. Can we get details or a link to using LCS to upload and deploy?

### ISSUE THREAD

**Issue by JTWWI** [MicrosoftDocs/dynamics-365-unified-operations-public#4650]
When using this process https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/isv-licensing#production-environments, what do we do with the zip file once created?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 69192df7-736f-1504-e8ab-d1ececb95800
* Version Independent ID: 7707373e-0ef6-ac6b-fcce-efce6a0ade73
* Content: [Independent software vendor (ISV) licensing - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/isv-licensing#production-environments)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/isv-licensing.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/dev-tools/isv-licensing.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @Peakerbl
* Microsoft Alias: **peakerbl**

**Comment by twheeloc** [comment]
@JTWWI, thank you for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
