### ISSUE TITLE
Bank grouping feature for Advanced bank rec

### ISSUE THREAD

**Issue by sbaber82** [MicrosoftDocs/dynamics-365-unified-operations-public#4651]
In which release, the below feature is available:

Advanced bank reconciliation improvement: enable group conditions in reconciliation matching rules

I am on 10.0.34 and can't see this feature and the article is from May 2023

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 24795d36-2430-5d77-9647-c7bcc0d392b2
* Version Independent ID: 07842cfa-7251-af70-2d4e-beadca5dde5a
* Content: [Set up bank reconciliation matching rules - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/cash-bank-management/set-up-bank-reconciliation-matching-rules)
* Content Source: [articles/finance/cash-bank-management/set-up-bank-reconciliation-matching-rules.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/cash-bank-management/set-up-bank-reconciliation-matching-rules.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @angelad116
* Microsoft Alias: **angelading**

**Comment by twheeloc** [comment]
@sbaber82, thank you for your question. This feature was added in November, 2023.
