### ISSUE TITLE
Why is this so long?

### ISSUE THREAD

**Issue by rudiobtain** [MicrosoftDocs/dynamics-365-unified-operations-public#4653]
I was trying to read this article to learn what this was all about, and what I can use it for, but I am kind of lost in the wall of test in the article, and wondering why its so long.

I mean it could be something like this:

The way I understand there are some simple steps you need to do.
Create a class
Publish a package
Run the script from your Environment
And then perhaps some extra info about roles and security.

How can those simple steps be such a long wall of text??

Sorry I am just wondering why?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2f09e8fa-e5dc-2e5d-3613-c6b4f6d7191a
* Version Independent ID: 2f09e8fa-e5dc-2e5d-3613-c6b4f6d7191a
* Content: [Run custom X++ scripts with zero downtime - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/run-custom-scripts)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/run-custom-scripts.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/deployment/run-custom-scripts.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @AndersGirke
* Microsoft Alias: **aevengir**

**Comment by bishalgoswami** [comment]
Bug 834368 has been logged to address this issue.

**Comment by kamaybac** [comment]
@rudiobtain , Thank you for getting in touch. The reason why the text is like this is that the author believed that this amount of information was necessary in order to understand and use the feature.
