### ISSUE TITLE
Issue with the production batch size journal 

### ISSUE THREAD

**Issue by Gsrini1211** [MicrosoftDocs/dynamics-365-unified-operations-public#4656]
Hi Team, 
There is a small calculation problem in Production batch size journal, sometimes it's dividing by 2 and sometimes with some other calculation.
Can any one help on this issue or any one having any document related to Production batch size? Please advise.

Regards,
Vasu G.

**Comment by twheeloc** [comment]
@Gsrini1211,  thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
