### ISSUE TITLE
windows 11 crack

### ISSUE THREAD

**Issue by ShahzadAliideas** [MicrosoftDocs/dynamics-365-unified-operations-public#4659]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fcfc4928-bdf2-e112-bbb7-64605c80ba72
* Version Independent ID: 06fa8533-d429-9c15-b8a5-d7473fd8a292
* Content: [POS extension overview - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/dev-itpro/pos-extension/pos-extension-overview)
* Content Source: [articles/commerce/dev-itpro/pos-extension/pos-extension-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/pos-extension/pos-extension-overview.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by bishalgoswami** [comment]
Bug 834364 has been logged to address this issue.

**Comment by josaw1** [comment]
@ShahzadAliideas do you have a specific question about this article?
