### ISSUE TITLE
Inheritance from Object

### ISSUE THREAD

**Issue by OksanaKovaliova** [MicrosoftDocs/dynamics-365-unified-operations-public#466]
"some classes don't inherit from any class" - is it still valid for D365? Don't all classes inherit from Object class there?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0adabd39-8b76-7d0a-c1c5-b8a1b1798b48
* Version Independent ID: afcd33c6-32ee-1c1a-03fc-ca24c2bc7bcc
* Content: [X++ operators - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-ref/xpp-operators)
* Content Source: [articles/dev-itpro/dev-ref/xpp-operators.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-ref/xpp-operators.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RobinARH
* Microsoft Alias: **robinr**

**Comment by pvillads** [comment]
The concept is the same in D365 as it was in earlier versions. All classes implicitly derive from Object, even if they do not explicitly provide a "class MyClass extends Object" clause.
