### ISSUE TITLE
Typo - Quality instead of Quantity

### ISSUE THREAD

**Issue by gebaluta** [MicrosoftDocs/dynamics-365-unified-operations-public#4660]
There's a typo in the "Print the Sales journal report" section, at step 2.
I believe that instead of "Quality", the author meant "Quantity":
_In the Quality field, enter 1._

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2b14b0dc-1149-4d37-054c-1324f8f5340e
* Version Independent ID: 85841d28-402d-1ece-38f5-cec29c9a2e34
* Content: [Journal reports - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/localizations/emea-bel-journal-reports)
* Content Source: [articles/finance/localizations/emea-bel-journal-reports.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/emea-bel-journal-reports.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @AdamTrukawka
* Microsoft Alias: **atrukawk**

**Comment by gebaluta** [comment]
Same comment for the "Print the Purchase journal report" section:
I think "Quantity" should be written instead of "Quality" at step 2 - _In the Quality field, enter 3._

**Comment by twheeloc** [comment]
@gebaluta, thank you for your feedback. The article has been updated.

**Comment by gebaluta** [comment]
@twheeloc I still see the old(incorrect) statement in the docs:
![image](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/assets/120671509/3c8807a7-db49-418f-a2d1-5763b7a6f868)
![image](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/assets/120671509/9de5d918-45e3-409e-806f-2671d1c4bd18)
