### ISSUE TITLE
DB Sync

### ISSUE THREAD

**Issue by kklyandev** [MicrosoftDocs/dynamics-365-unified-operations-public#4661]
The note about doing database synchronization needs to be moved further down in the text, after the SQL script is executed and the database is renamed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7c5e8701-e1d4-25f8-d76a-ee7870b915e1
* Version Independent ID: 624211c7-2eb4-7154-d38f-236dc6f8f7a9
* Content: [Export a copy of the standard user acceptance testing (UAT) database - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/dbmovement-scenario-exportuat#import-the-database)
* Content Source: [articles/fin-ops-core/dev-itpro/database/dbmovement-scenario-exportuat.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/database/dbmovement-scenario-exportuat.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by bishalgoswami** [comment]
Bug 834819 has been logged to address this issue.

**Comment by twheeloc** [comment]
Thanks for your feedback. We have passed this feedback onto the product team for consideration.
