### ISSUE TITLE
hhedy

### ISSUE THREAD

**Issue by hedystrong** [MicrosoftDocs/dynamics-365-unified-operations-public#4662]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 54af2734-22fa-9124-c30a-8640fb775f95
* Version Independent ID: 4f727208-bc5d-53fb-ecd3-ccb7e551d839
* Content: [Create a new warehouse layout - Supply Chain Management | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/supply-chain/inventory/tasks/create-new-warehouse-layout#define-the-location-name-format)
* Content Source: [articles/supply-chain/inventory/tasks/create-new-warehouse-layout.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/inventory/tasks/create-new-warehouse-layout.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @yufeihuang
* Microsoft Alias: **yufeihuang**

**Comment by bishalgoswami** [comment]
Bug 834929 has been logged to address this issue.

**Comment by kamaybac** [comment]
@hedystrong , you submitted the feedback form for one of our help articles, but didn't include any text. Is there something  you wanted to tell us about this article?
