### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by gebaluta** [MicrosoftDocs/dynamics-365-unified-operations-public#4663]
Section "Set up application-specific parameters for Report field lookup", step 2 should state "_Configurations > Application specific parameters **->** Setup_" instead of "_Configurations > Application specific parameters setup_".
"Setup" is the name of the button to be clicked on the form, not "Application specific parameters setup".

"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f53d91d5-5261-c46d-7943-c6ac147e2c64
* Version Independent ID: f53d91d5-5261-c46d-7943-c6ac147e2c64
* Content: [VAT declaration (Belgium) - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/localizations/emea-bel-vat-declaration-belgium#set-up-application-specific-parameters-for-report-field-lookup)
* Content Source: [articles/finance/localizations/emea-bel-vat-declaration-belgium.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/emea-bel-vat-declaration-belgium.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @AdamTrukawka
* Microsoft Alias: **atrukawk**

**Comment by gebaluta** [comment]
Same observation for "Set up application-specific parameters for Nature" section, step 5.

**Comment by twheeloc** [comment]
@gebaluta, thank you for your feedback. The article has been updated.

**Comment by gebaluta** [comment]
@twheeloc I still see the old(incorrect) version:
![image](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/assets/120671509/58f9d869-4511-4700-8e41-7ba9c7fb1eaa)
![image](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/assets/120671509/a8d3f635-abf8-493b-a096-ff673cff314a)

**Comment by twheeloc** [comment]
@gebaluta, the articles will reflect the update later today.

**Comment by gebaluta** [comment]
[like]  George Baluta reacted to your message:
________________________________
