### ISSUE TITLE
API for getting message Id for request does not explain where to get message id

### ISSUE THREAD

**Issue by AELO23** [MicrosoftDocs/dynamics-365-unified-operations-public#4664]
Documentation does not explain where to get the required messageId for the message status request
![image](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/assets/87655629/52619d8c-7e16-4c2e-87fa-48208c49549c)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 01b2cd6b-f885-7461-fbdf-cf81f9e50d86
* Version Independent ID: 8df7a6ae-67db-5d29-fb6a-0820704ff3ef
* Content: [Recurring integrations - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/recurring-integrations)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/recurring-integrations.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/recurring-integrations.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Peakerbl
* Microsoft Alias: **peakerbl**

**Comment by bishalgoswami** [comment]
Bug 834970 has been logged to address this issue.

**Comment by josaw1** [comment]
@KendalBond007 can you please review this?

**Comment by KendalBond007** [comment]
@josaw1 or @sericks007 - I am unable to access ADO bugs at this time, so I can't track the progress of the item mentioned above (Bug 834970). Could you please add me to be following the item so I can get updates and know when the bug has been resolved?

**Comment by sericks007** [comment]
Hi @KendalBond007, I no longer have access to the F&O ADO, as well.  So @josaw1 will need to help you here.  Thanks!

**Comment by josaw1** [comment]
@KendalBond007, I've engaged with engineering on this. Thanks!

**Comment by KendalBond007** [comment]
I'll keep an eye out for messages from them. :)

**Comment by KendalBond007** [comment]
@josaw1 - I have been able to view an ADO from docs & learn, so I might be able to view the one for this item. Could you (or someone) put a live-link to it here? Thanks!

**Comment by KendalBond007** [comment]
@josaw1 - Just checking in to see about viewing/status of bug 834970.

**Comment by josaw1** [comment]
Hi @KendalBond007, I will sync with you offline, thanks.

**Comment by KendalBond007** [comment]
No problem - thanks!

Regards,

Kendal Bond
Senior Technical Writer
Aquent, LLC

**Comment by KendalBond007** [comment]
The "API for getting message status" section mentions the "enqueue process" which upon completion generates a message containing the status. (Generating this message is described in the section "API for import (enqueue)").
The "...message status" text implies the user should use the message GUID mentioned in the "enqueue" section as the string input in the message status sample code.

**Comment by josaw1** [comment]
Thanks. The article will be updated within the next 24 hours.
