### ISSUE TITLE
What is the schedule for 10.0.1549.125?

### ISSUE THREAD

**Issue by Pawel-Kolosza** [MicrosoftDocs/dynamics-365-unified-operations-public#4665]
Hi,
what is the schedule for 10.0.1549.125, since it's already in PREPROD?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: efdfc5ac-26fd-e9ff-5d10-995275049b70
* Version Independent ID: efdfc5ac-26fd-e9ff-5d10-995275049b70
* Content: [Release schedule for proactive quality updates - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/quality-updates-schedule?context=%2Fdynamics365%2Fcontext%2Fcommerce)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/quality-updates-schedule.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/quality-updates-schedule.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @rashmansur
* Microsoft Alias: **rashmim**

**Comment by bishalgoswami** [comment]
Bug 835115 has been logged to address this issue.

**Comment by twheeloc** [comment]
@Pawel-Kolosza, thank you for your feedback. This article has been updated.
