### ISSUE TITLE
Please add a question related to multi-tenant deployment

### ISSUE THREAD

**Issue by MichaelWeberMSFT** [MicrosoftDocs/dynamics-365-unified-operations-public#4666]
Hi,

it would be a great help if you can also add and document following question on this page:
"Can a customer have multi-tenant deployment? (multiple LCS projects on multiple tenants, within the same contract)?""

Background of this question: Dynamics 365 Sales offers this licensing option and customers ran into the same situation with F&O. Here are the details: "For a multi-tenant deployment, you'll need a Multi-Tenant Amendment" [Considerations for choosing multiple environments or tenants - Power Platform | Microsoft Learn] (https://learn.microsoft.com/en-us/power-platform/admin/multiple-online-environments-tenants#add-a-multi-tenant-deployment-under-volume-licensing)

Thank you

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4119369d-808f-fdce-7887-ac43f2e2ff32
* Version Independent ID: fe631aff-44f4-d6a7-dbff-24f8ab2da9d3
* Content: [Subscriptions, LCS projects, and Azure Active Directory tenants FAQ - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/subscription-overview?context=%2Fdynamics365%2Fcontext%2Fcommerce)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/subscription-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/subscription-overview.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @skaue-ms
* Microsoft Alias: **toskaue**

**Comment by bishalgoswami** [comment]
Bug 835582 has been logged to address this issue.

**Comment by MichaelWeberMSFT** [comment]
[like]  Michael Weber reacted to your message:
________________________________

**Comment by twheeloc** [comment]
@MichaelWeberMSFT, thank you for your feedback. We have passed this feedback onto the product team for consideration.
