### ISSUE TITLE
Seems steps are missing

### ISSUE THREAD

**Issue by d47447** [MicrosoftDocs/dynamics-365-unified-operations-public#4667]
[Enter feedback here]

The details under this heading https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/tasks/security-diagstics-task-recordings#manage-security-for-a-task-recording
is not accurate, after clicking on the close button the next screen doesn't open. I tried this with many different environments including tier 1 and tier 2. Please verify if we are missing adding any step or if something got changed in recent updates. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 91be640e-c5fb-2a2f-a93f-03ccc5329826
* Version Independent ID: 13fb58fc-922c-f251-5213-9c7f630cdd28
* Content: [Security diagnostics for task recordings - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/tasks/security-diagstics-task-recordings)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/tasks/security-diagstics-task-recordings.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/sysadmin/tasks/security-diagstics-task-recordings.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Peakerbl
* Microsoft Alias: **peakerbl**

**Comment by twheeloc** [comment]
@d47447, thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
