### ISSUE TITLE
BOT ID cannot be found anymore by the way it is decribed in this doc

### ISSUE THREAD

**Issue by BasvGMRN** [MicrosoftDocs/dynamics-365-unified-operations-public#4669]
The Bot ID is no longer referenced in the Token Endpoint of the mobile app channel, without the bot ID the PVA on the eCommerce site will not work.

As a workaround we found the bot ID using the PVA demo site and inspected the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9e21e2b5-ffb2-0421-c458-0f3ebe809fc4
* Version Independent ID: 9e21e2b5-ffb2-0421-c458-0f3ebe809fc4
* Content: [Commerce Chat with Power Virtual Agents module - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/chat-module-pva)
* Content Source: [articles/commerce/chat-module-pva.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/chat-module-pva.md)
* Service: **dynamics-365-commerce**
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by bishalgoswami** [comment]
Bug 836124 has been logged to address this issue.

**Comment by josaw1** [comment]
@zhenchaoni can you please review this issue?

**Comment by zhenchaoni** [comment]
I just tried that in my own environment. The Bot ID is still available in multiple places, including the token endpoint.
<img width="971" alt="image" src="https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/assets/10322359/291a8d43-0fad-4376-bee0-dd3edb6d0f66">

**Comment by BasvGMRN** [comment]
Dear Zhenchao,

Thank you for reproducing in your own instance.
Please note the ID shown in your screenshots is not the Bot ID, and thus embedding the PVA in eCommerce site will not work.

|Please see my screenshots below to indicate:
[A screenshot of a computer  Description automatically generated]

eCommerce Sitebuilder (with working PVA):
[A screenshot of a computer  Description automatically generated]
Note: Bot ID is 889d20e4-88e6-449d-92bf-cedef18f7f25, which is not shown in the 3 places n PVA screenshot.

Please reconfirm whether you can render the PVA in eCommerce with your mentioned Bot ID.

Thank you,
Bas

**Comment by zhenchaoni** [comment]
Hello BasvGMRN,

The Bot ID inside the "Token Endpoint" section and the "Embed Code" section doesn't contain hyphens. Therefore, the Bot ID cannot be used.

As a workaround, please find the Bot ID from the browser URL.
<img width="614" alt="image" src="https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/assets/10322359/61ccff77-3fe3-4959-98a3-c7a04cea3faa">

I did a test locally, I am able to retrieve the token by sending a GET request to https://powerva.microsoft.com/api/botmanagement/v1/directline/directlinetoken?botId=eaa57c36-10cc-43f4-898c-23bb1a50cfa4&tenantId={tenant ID}

We will also check with Power Virtual Agent team to see how to properly find the Bot ID from their portal.

**Comment by BasvGMRN** [comment]
Dear Zhenchao,

Thank you for your efforts.

Per my own testing the ID referenced in the URL is not the Bot ID that can be used in the eCommerce Sitebuilder.
Please ensure testing the Bot ID found in conjunction with the eCommerce Msdyn365 pva chat connector – as this is the topic of the document page.

My findings:
ID in browser URL: 273f0092-623b-ee11-bdf4-6045bd0339c8
***@***.***

Is not the Bot ID that works in eCommerce embedded PVA

Bot ID: 889d20e4-88e6-449d-92bf-cedef18f7f25
[A screenshot of a chat  Description automatically generated]

Thanks,
Bas

Bas van Gameren

Technical Specialist
Microsoft Netherlands
Evert van de Beekstraat 354 | 1118 CZ | Schiphol | The Netherlands
( +31 (0) 646381931| • ***@***.******@***.***>

[MSFT_logo_Gray DE sized SIG1.png]

**Comment by zhenchaoni** [comment]
Yes, the Bot ID is used in site builder. The below is some screenshots from our internal testing environment.

1. Get the BOT ID from the URL
<img width="649" alt="image" src="https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/assets/10322359/d600a637-4585-4055-b76f-f93a68f6b028">

2. Use the BOT ID in the site builder
<img width="580" alt="image" src="https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/assets/10322359/bc299237-2de2-4ace-a4f3-86a0c690122e">

3. In the ECommerce site, the direct line token can be retrieved
<img width="668" alt="image" src="https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/assets/10322359/9ddc71e0-25e9-4fe1-a030-54b45632a3e8">

Can you help to paste a few screenshots directly in GitHub? Somehow the screenshots from your email response doesn't populate in the GitHub.

**Comment by BasvGMRN** [comment]
Sorry, don’t know how to work in Github.

Great it works for you at your end, unfortunately this ID does not work for me – the PVA chat pops-up and then closes automatically.

Thanks,
Bas

**Comment by zhenchaoni** [comment]
@BasvGMRN Sorry to hear that it doesn't work for you. For now, you can workaround the problem by inspecting the page. You can also contact support to raise up a ticket if this issue block your business.

**Comment by zhenchaoni** [comment]
@BasvGMRN I am able to repro the problem for **new created** chat bots. For new created chat bots, the GUID shown in the URL is not the correct Bot ID anymore. I think there is a change in Power Virtual Agent. We will continue investigating the problem internally.

For workaround, you can still inspect the source of the demo website. You can find the bot ID in the request payload of `activities` call.
<img width="1506" alt="image" src="https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/assets/10322359/5e5816ed-d016-4668-9f57-db391f3554d0">

Alternatively, you can get the bot ID from the token endpoint.
Copy the Token Endpoint
<img width="727" alt="image" src="https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/assets/10322359/7eef464e-5dec-42ab-9dfc-d20a1c147f2a">

Open the Token Endpoint in a new browser tab, you can get a jwt token
<img width="516" alt="image" src="https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/assets/10322359/6e3e7ac5-d77d-45a2-b7a0-038590a3933e">

Parse the jwt token, you can find a "bot" in the parse result. It is the bot ID.
<img width="710" alt="image" src="https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/assets/10322359/adf5409e-04a0-4ff9-9bb3-76d85e79a706">
