### ISSUE TITLE
Include if Company Specific on the batch jobs

### ISSUE THREAD

**Issue by jake-ms** [MicrosoftDocs/dynamics-365-unified-operations-public#4672]
It would be super helpful if you indicated which batch jobs run for all companies and which ones need to be setup per company.  Ones that I believe are company specific are below. 

Containerization   history cleanup
Warehouse management on-hand entries cleanup
Wave processing history log cleanup
Work creation history cleanup

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 926b5538-8734-b2cf-7d77-21f35dbf0e98
* Version Independent ID: 219ba487-1689-e78c-773e-42d019f779f1
* Content: [Cleanup routines in Dynamics 365 Finance and Dynamics 365 Supply Chain Management - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/cleanuproutines)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/cleanuproutines.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/sysadmin/cleanuproutines.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @dvliegen
* Microsoft Alias: **dvliegen**

**Comment by bishalgoswami** [comment]
Bug 836855 has been logged to address this issue.

**Comment by twheeloc** [comment]
@jake-ms, thank you for your feedback. We have passed this feedback onto the product team for consideration.
