### ISSUE TITLE
Issue with the data in BI report

### ISSUE THREAD

**Issue by Gsrini1211** [MicrosoftDocs/dynamics-365-unified-operations-public#4674]
BI report is not getting the correct data for one of the user.
Sales order count for the user is showing- 809 in the month of June 2022 with BI report. But when we have checked in the Prod and Test environment, there, the sales order count is showing- 627 only. Both are not matching. Kindly advise.

**Comment by twheeloc** [comment]
@Gsrini1211, thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
