### ISSUE TITLE
References to Indonesia

### ISSUE THREAD

**Issue by jbromelow** [MicrosoftDocs/dynamics-365-unified-operations-public#4675]
This is a generic page on how to setup Electronic Invoicing. However it contains references to Indonesia.. (list of virtual entities in Dataverse) What if you are setting this up for another country? Which entities need to be enabled for other countries?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ecf12017-0bdc-5201-3f1a-f7c814f96b03
* Version Independent ID: ecf12017-0bdc-5201-3f1a-f7c814f96b03
* Content: [Microsoft Power Platform plug-in admin reference - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/localizations/e-invoicing-power-platform-plug-in)
* Content Source: [articles/finance/localizations/e-invoicing-power-platform-plug-in.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/e-invoicing-power-platform-plug-in.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @germansh
* Microsoft Alias: **germansh**

**Comment by twheeloc** [comment]
@jbromelow, thank you for your feedback. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
