### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by Pankaj-0723** [MicrosoftDocs/dynamics-365-unified-operations-public#4677]
Getting this "FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory" while I am doing yarn start. As the D365 E-Commerce FAQ, I have also added in the below mentioned tag in package.json

"build": "SET NODE_OPTIONS=--max_old_space_size=4096 && yarn msdyn365b build --use-eslint",

<img width="592" alt="image" src="https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/assets/61287467/21299299-fd65-40c4-ad8e-1f0ffefbe7d1">

@samjarawan Could you please suggest some solution. 

Thanks in Advance.

**Comment by twheeloc** [comment]
@Pankaj-0723, thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
