### ISSUE TITLE
Sample code for the Immediate window

### ISSUE THREAD

**Issue by caroleeschuck** [MicrosoftDocs/dynamics-365-unified-operations-public#4678]
Sample code for the Immediate window would very helpful!  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6fc49240-e646-3ad9-679b-d1e6929d8460
* Version Independent ID: f8e42afe-ad33-dc83-15c7-d93be254c33f
* Content: [Debug X++ code by using the debugger in Visual Studio - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/debug-xpp)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/debug-xpp.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/dev-tools/debug-xpp.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @gianugo
* Microsoft Alias: **gianura**

**Comment by josaw1** [comment]
Closing as won't fix.
