### ISSUE TITLE
Got error when installing the solution

### ISSUE THREAD

**Issue by trucbinh** [MicrosoftDocs/dynamics-365-unified-operations-public#4679]
[Enter feedback here]
Hi,

I followed the steps in this document, but got the error when installing the package "Invoice Capture for Dynamics 365 Finance". The error is:
_"msdyn_FnoInvoiceCaptureAnchor
NotProvided
SDK Message Processing Steps import: FAILURE: Expected to find one SdkMessageFilter for SdkMessageId e8d825f6-7a16-4b45-81f7-d5b601abe190, PrimaryEntity 10478 and SecondaryEntity 0. Found 0 records."_

Please help to check if you are getting this issue.

Thanks,
Binh.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cb7e15d7-810e-01e0-01e4-a96780be9b28
* Version Independent ID: cb7e15d7-810e-01e0-01e4-a96780be9b28
* Content: [Install the Invoice capture solution - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/accounts-payable/install-invoice-capture)
* Content Source: [articles/finance/accounts-payable/Install-invoice-capture.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/accounts-payable/Install-invoice-capture.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @sunfzam
* Microsoft Alias: **zezhangzhao**

**Comment by twheeloc** [comment]
@trucbinh, thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
