### ISSUE TITLE
Samples

### ISSUE THREAD

**Issue by OksanaKovaliova** [MicrosoftDocs/dynamics-365-unified-operations-public#468]
Please, check samples:
1) Example of FOR loop with I = 100 and array of the length = 10 will cause exception, when trying to access array elements with index more then 10
2) Example for Continue statement: i=1; i&lt;100;  - should not it be i &lt;= 100 - because i &lt; 100 will make the last array element excluded from FOR loop
3) server client static Exception error  - in D365 it's client server', not 'server client' 
Thank you 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f325f870-b30d-a45f-4f33-328a823dc460
* Version Independent ID: d57598d2-efc6-b775-81b6-b9669ea72c91
* Content: [X++ statements, loops, and exception handling - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-ref/xpp-statements-loops)
* Content Source: [articles/dev-itpro/dev-ref/xpp-statements-loops.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-ref/xpp-statements-loops.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RobinARH
* Microsoft Alias: **robinr**

**Comment by kfend** [comment]
Thanks for the feedback. We have updated the document.
