### ISSUE TITLE
Allow edits to internal data on general ledger vouchers

### ISSUE THREAD

**Issue by Sreeni9423** [MicrosoftDocs/dynamics-365-unified-operations-public#4680]
[Enter feedback here]
This feature is default in current version 10.0.35 and in document it says that it has to be manually enabled in feature management which needs to be removed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f4ce9426-1560-de5d-deff-1d9b861cc5ba
* Version Independent ID: f4ce9426-1560-de5d-deff-1d9b861cc5ba
* Content: [Financial tags - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/general-ledger/financial-tag)
* Content Source: [articles/finance/general-ledger/financial-tag.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/general-ledger/financial-tag.md)
* Service: **dynamics-365-finance**
* Technology: ****
* GitHub Login: @kweekley
* Microsoft Alias: **kweekley**

**Comment by twheeloc** [comment]
@Sreeni9423, thank you for the feedback. We will look to update the content.
