### ISSUE TITLE
Version attribute has wrong data type assigned

### ISSUE THREAD

**Issue by SysC0mp** [MicrosoftDocs/dynamics-365-unified-operations-public#4683]
The `Version ` attribute of class `SysSetupConfigAttribute ` is of type `integer ` in Dynamics 365, but `real ` is used for the documentation instructions and for the default value. This leads to compiler warnings.
![image](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/assets/8371978/edba6a34-9a15-405b-a655-1ae172bde6cc)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 237c55a3-5541-6133-8cc1-8c24b1356cbe
* Version Independent ID: 237c55a3-5541-6133-8cc1-8c24b1356cbe
* Content: [SysSetup - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/syssetup)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/syssetup.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/dev-tools/syssetup.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @najaidee
* Microsoft Alias: **najaidee**

**Comment by twheeloc** [comment]
@najaidee, thank you for your feedback. We have passed this feedback onto the product team for consideration.
