### ISSUE TITLE
Error: You cannot modify the default active period.

### ISSUE THREAD

**Issue by Pawel-Kolosza** [MicrosoftDocs/dynamics-365-unified-operations-public#4684]
Hi, 

In Installed product version : 10.0.33 (10.0.1549.123)
Installed platform version : Update57 (7.0.6861.100)
I get error: You cannot modify the default active period.
![image](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/assets/141871418/6bbfef6c-1c70-4297-b78c-0d60580967e2)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5ece3a85-8ce7-3474-17be-b477b8475847
* Version Independent ID: 92090706-33bf-0f00-926c-3e1b7bc5314a
* Content: [Active batch periods - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/activeperiod)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/activeperiod.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/sysadmin/activeperiod.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @hasaid
* Microsoft Alias: **hasaid**

**Comment by twheeloc** [comment]
@Pawel-Kolosza, thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
