### ISSUE TITLE
Remove mentioning supported versions

### ISSUE THREAD

**Issue by MichaelFruergaardPontoppidan** [MicrosoftDocs/dynamics-365-unified-operations-public#4685]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cc2ac844-c345-707a-b2e9-5d4edf7c8541
* Version Independent ID: ae6e65c3-c1e1-c4cc-e05c-1c2ebd4bafc6
* Content: [Install and connect the Warehouse Management mobile app - Supply Chain Management | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/supply-chain/warehousing/install-configure-warehouse-management-app)
* Content Source: [articles/supply-chain/warehousing/install-configure-warehouse-management-app.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/warehousing/install-configure-warehouse-management-app.md)
* Service: **dynamics-365-supply-chain**
* GitHub Login: @Mirzaab
* Microsoft Alias: **mirzaab**

**Comment by twheeloc** [comment]
@MichaelFruergaardPontoppidan, thank you for your feedback. The article has been updated.
