### ISSUE TITLE
LinkedIn COnnector

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics-365-unified-operations-public#4687]
I saw a notice about the integrations no long being supported.

What is the alternative path if a customer wants to integration d365 HR to LinkedIn Hub?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5bddd486-4449-8a27-1463-505366eb82a8
* Version Independent ID: 748ac0da-0288-faca-1aa6-00ea3f839a1f
* Content: [Integrate with LinkedIn Talent Hub - Human Resources | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/human-resources/hr-admin-integration-linkedin)
* Content Source: [articles/human-resources/hr-admin-integration-linkedin.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/human-resources/hr-admin-integration-linkedin.md)
* Service: **dynamics-365-human-resources**
* Product: ****
* Technology: ****
* GitHub Login: @jaredha
* Microsoft Alias: **twheeloc**

**Comment by twheeloc** [comment]
@makdaddy8888,  thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

**Comment by benopax8apac** [comment]
This is not a support request! This document talks about an integration which is not supported. Why would I need to speak to support?
