### ISSUE TITLE
How often is the Dynamics Symbol font actually updated

### ISSUE THREAD

**Issue by PalleAgermark** [MicrosoftDocs/dynamics-365-unified-operations-public#4691]
The page you are linking to says "With each release, there are often updates to the symbol font in terms of added or removed symbols", but the latest version shown on the same page is from 10.0.13 October 2020?

Thanks,
Palle

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a5103263-c61e-38db-e6a6-354ed41ee61e
* Version Independent ID: ea0e7fef-f321-5f74-465e-e72accc046ed
* Content: [Dynamics Symbol font - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/user-interface/symbol-font?source=recommendations)
* Content Source: [articles/fin-ops-core/dev-itpro/user-interface/symbol-font.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/user-interface/symbol-font.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by josaw1** [comment]
@jasongre can you please review? Thanks.

**Comment by twheeloc** [comment]
@PalleAgermark, thank you for your feedback.  The content has been updated.
