### ISSUE TITLE
page details for Customer triggers needs updating

### ISSUE THREAD

**Issue by RobBertram** [MicrosoftDocs/dynamics-365-unified-operations-public#4692]
In the section under Customer Triggers, we have incorrect descriptions and are missing at least one trigger on the list:  https://learn.microsoft.com/en-us/dynamics365/commerce/dev-itpro/pos-trigger-printing#customer-triggers

The description for **PostCustomerAddTrigger** reads "Executed after adding a customer to the transaction."  It is not implemented as the description suggests.  This trigger is called when a new customer is created.  It is not called when an existing customer is added.  Similarly, I suspect that the description for **PreCustomerAddTrigger** is incorrect and needs to be adjusted.

The trigger that does fire when a customer is added to the cart is **PostCustomerSetTrigger** which is missing from this document.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f76dd326-7dd2-ba50-5e5d-d670aaf6b717
* Version Independent ID: c25145fd-dca8-c46b-a940-3336dd6f14f3
* Content: [Store Commerce app triggers and printing - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/dev-itpro/pos-trigger-printing#customer-triggers)
* Content Source: [articles/commerce/dev-itpro/pos-trigger-printing.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/pos-trigger-printing.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by twheeloc** [comment]
@RobBertram, thank you for your feedback. We have passed this feedback onto the product team for consideration.
