### ISSUE TITLE
Solution feedback

### ISSUE THREAD

**Issue by DrGee-gethub** [MicrosoftDocs/dynamics-365-unified-operations-public#4693]
[Enter feedback here]
Where can I provide feedback regarding "changes to confirmed purchase orders and their downstream impact"?

I feel this solution in its present form is remarkably un-reliable.  Maybe it is just a Preview behaving poorly?

If I refresh the form I can get it to work.
I again verified the configuration.  There is no real logging that I can find to help troubleshoot.
![image](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/assets/66972079/b0759b13-d70a-4122-8e5d-e5f09a0f5391)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ef63dd20-39df-940a-397d-1a261a50ba1b
* Version Independent ID: 59becf1e-e56a-9466-a9ae-7e3d29bbd750
* Content: [Review and accept changes to confirmed purchase orders - Supply Chain Management | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/supply-chain/procurement/purchase-order-changes-after-confirmation)
* Content Source: [articles/supply-chain/procurement/purchase-order-changes-after-confirmation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/procurement/purchase-order-changes-after-confirmation.md)
* Service: **dynamics-365-supply-chain**
* GitHub Login: @cabeln
* Microsoft Alias: **cabeln**

**Comment by twheeloc** [comment]
@cabeln, thank you for your feedback. You can provide product feedback here: [Dynamics 365 application ideas](//experience.dynamics.com/ideas/).
