### ISSUE TITLE
System administration > Users > Users Microsoft Excel Add-In Open in Excel User Information with enabled column

### ISSUE THREAD

**Issue by Pawel-Kolosza** [MicrosoftDocs/dynamics-365-unified-operations-public#4694]
Hi,
doc. advise "Go to System administration > Users > Users, and enable the users that should have access to the UAT environment. If many users must be enabled, you can complete this task more quickly by using the [Microsoft Excel Add-In](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/office-integration/use-excel-add-in).

However at System administration > Users > Users Microsoft Excel Add-In Open in Excel User Information is without enabled column.
It contains just ID	Provider	UserInfo_language	Helplanguage	Name. 
Column enabled is just in Export to excel User Information: User ID	User name	Email	Company	Person	Telemetry ID	Enabled. 
Could you please provide the same User Information table in Open in Excel User Information?

Thanks,
Pawel.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bf0d39c9-ec24-0664-06a5-53892104f160
* Version Independent ID: 37b5f989-525f-259a-2e4f-34b746d987bd
* Content: [Refresh for training purposes - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/dbmovement-scenario-general-refresh#open-the-environment-to-users)
* Content Source: [articles/fin-ops-core/dev-itpro/database/dbmovement-scenario-general-refresh.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/database/dbmovement-scenario-general-refresh.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by joshdcabrera** [comment]
@Pawel-Kolosza - look up how to update the design of the workbook.

The columns you're seeing are simply the default columns.

You can edit it to add the enabled column so you can update it.

![image](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/assets/34781750/4a7b38ed-6ba0-4201-b6dd-9df5a25eddad)
