### ISSUE TITLE
Grace period 

### ISSUE THREAD

**Issue by jlabustro** [MicrosoftDocs/dynamics-365-unified-operations-public#4695]
if we were doing a license remap, and it states in this article that we need to request a grace period to remain the licenses active on both tenants. how long will this grace period be?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c60834f9-1f56-c5fc-406c-552616feca48
* Version Independent ID: d5fa1d78-e6ee-efe8-88f8-a893069e56ea
* Content: [Move Lifecycle Services implementation projects to different Azure AD tenants - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/move-lcs-implementation-project-tenant)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/move-lcs-implementation-project-tenant.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/move-lcs-implementation-project-tenant.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @RicardoCaeiroPro
* Microsoft Alias: **v-ricaei**

**Comment by twheeloc** [comment]
@RicardoCaeiroPro, thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
