### ISSUE TITLE
Current schedule ends with release 10.0.38, which is 1 month away

### ISSUE THREAD

**Issue by maciunex** [MicrosoftDocs/dynamics-365-unified-operations-public#4696]
Can the schedule be extended to include future dates beyond 10.0.38 version ?
It is crucial for planning environment updates and environment plan for goLives in 2024.
See this Yammer thread for conversation:
https://www.yammer.com/dynamicsaxfeedbackprograms/threads/2270166019022848

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e7dcb285-f32c-c92e-fe49-1617f213066b
* Version Independent ID: 8f28c1a0-9da5-f853-90ee-d82a4c32df7e
* Content: [Service update availability - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/public-preview-releases)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/public-preview-releases.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/public-preview-releases.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @hmahl
* Microsoft Alias: **hmahl**

**Comment by josaw1** [comment]
@kfend can you please address this issue? Thanks.

**Comment by kfend** [comment]
Thanks for letting us know. We are investigating this issue.

**Comment by twheeloc** [comment]
@maciunex, thanks for your question. This article has been updated.
