### ISSUE TITLE
This page seems to not applicable to 10.0.32 version VHD

### ISSUE THREAD

**Issue by madisettyravi** [MicrosoftDocs/dynamics-365-unified-operations-public#4698]
[Enter feedback here]
The instructions mentioned in the page is not applicable for the 10.0.32 VHD as it released with SQL server 2019 and there is no Azure storage emulator 4 versions installed. I would recommend to add a notification banner on the page that steps applicable to version of VHD

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d830cc4d-4375-3d2a-65d2-5427d1e8acdd
* Version Independent ID: cab504a7-d2d4-8722-5dd1-71ff1c39d04e
* Content: [Rename a local development (VHD) environment - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/vso-machine-renaming)
* Content Source: [articles/fin-ops-core/dev-itpro/migration-upgrade/vso-machine-renaming.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/migration-upgrade/vso-machine-renaming.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @josaw1
* Microsoft Alias: **josw**

**Comment by twheeloc** [comment]
@madisettyravi, thank you for your feedback. We have passed this feedback onto the product team for consideration.
