### ISSUE TITLE
Some changes

### ISSUE THREAD

**Issue by OksanaKovaliova** [MicrosoftDocs/dynamics-365-unified-operations-public#470]
Hi,
Some issues notices:
1) All declarations must be at the start of the method, before any X++ statements - it's not valid for D365 anymore.. 
2) X++ and C++ Samples - C++ should be replaced to C#

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d90f60ed-891b-151d-c963-522a1b0b1c17
* Version Independent ID: f9ab9cef-beda-06fb-c5c0-dce07969fbd5
* Content: [X++ and C# comparison - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-ref/xpp-cs-comparison)
* Content Source: [articles/dev-itpro/dev-ref/xpp-cs-comparison.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-ref/xpp-cs-comparison.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RobinARH
* Microsoft Alias: **robinr**

**Comment by kfend** [comment]
Thanks for your comments. We have updated the topic and changes will be reflected later today.
