### ISSUE TITLE
Partially delivered lines statement is incorrect

### ISSUE THREAD

**Issue by MonikaDuplessis** [MicrosoftDocs/dynamics-365-unified-operations-public#4702]
Please can you review the statement where you the article says that partially delivered purchase order line order quantity cant be amended? This only applies when the partial delivery is also invoiced. While only delivered, you can still make changes to the quantity field. Once invoiced, only delivery remainder can be canceled. (tested in contoso USMF 10.0.35)

**Comment by twheeloc** [comment]
Thanks for your feedback. We have passed this feedback onto the product team for consideration.
