### ISSUE TITLE
Hi! I uploaded a PDF photo in item card  of D365, D365 can't insert the PDF Photo in the production order and print it out simultaneously once user posting. Thank you for your help. 

### ISSUE THREAD

**Issue by Anthony9231** [MicrosoftDocs/dynamics-365-unified-operations-public#4703]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a930b313-647b-5f09-a22b-f95c2c4572ad
* Version Independent ID: 25ec2c84-3640-1cf7-89e8-3dd3f0b4237d
* Content: [Release a production order - Supply Chain Management | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/supply-chain/production-control/tasks/release-production-order)
* Content Source: [articles/supply-chain/production-control/tasks/release-production-order.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/production-control/tasks/release-production-order.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @johanhoffmann
* Microsoft Alias: **johanho**

**Comment by twheeloc** [comment]
@Anthony9231, thank you for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
