### ISSUE TITLE
when will edge be live again?

### ISSUE THREAD

**Issue by joro613** [MicrosoftDocs/dynamics-365-unified-operations-public#4705]
when will edge be live again?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d366ee12-06d0-2c97-4314-72434290f060
* Version Independent ID: 8012caf1-ae0c-532d-672a-8df2c3e027ec
* Content: [Scale unit capability for Supply Chain Management is currently paused for new customers - Supply Chain Management | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/supply-chain/cloud-edge/cloud-edge-landing-page)
* Content Source: [articles/supply-chain/cloud-edge/cloud-edge-landing-page.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/cloud-edge/cloud-edge-landing-page.md)
* Service: **dynamics-365-supply-chain**
* GitHub Login: @Mirzaab
* Microsoft Alias: **mirzaab**

**Comment by twheeloc** [comment]
@joro613, thank you for your feedback. You can find plans for future releases here: [Release plans](https://learn.microsoft.com/en-us/dynamics365/release-plans).
