### ISSUE TITLE
Changefeed metadata not changed when tables are paused

### ISSUE THREAD

**Issue by thomas-lange-drc-ngo** [MicrosoftDocs/dynamics-365-unified-operations-public#4709]
In D365FO Export to Data Lake we can add and pause synchronization of individual tables. 

Adding a new table correctly adds the data in the table to the sync and adds the table the metadata for the full tables (Tables.manifest.cdm.json->subfolder.manifest.cdm.json->...) and 
to the metadata for the changefeed tables (ChangeFeed.manifest.cdm.json).

However, pausing the synchronization of a table has only partial effect:
- it correctly stops the data synchronization
- it correctly changes the metadata for the full tables
- **it, *however*, does not change the metadata for changefeed tables (the   
ChangeFeed.manifest.cdm.json)**. In fact no new metadata is delivered, and even if we add a third table (not previously synced) and thus get new metadata, the paused table is still part of the json-file.

This error means, that it is, in effect, not possible to pause any table synchronization when using the changefeeds.

**Comment by twheeloc** [comment]
@thomas-lange-drc-ngo, thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
