### ISSUE TITLE
Validity for D365

### ISSUE THREAD

**Issue by OksanaKovaliova** [MicrosoftDocs/dynamics-365-unified-operations-public#471]
Hi,
Is this article still valid for D365? Looks a bit outdated. For example: "Use this method to avoid a call to the server tier." - does not D365 execute all logic on server and does not execute anything on web client. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ef9d86d-434d-12d8-572d-1736e23a26b1
* Version Independent ID: ff81ecae-8f19-4c18-3649-01af6032a5a5
* Content: [X++ session runtime functions - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-ref/xpp-session-run-time-functions#return-value-1)
* Content Source: [articles/dev-itpro/dev-ref/xpp-session-run-time-functions.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-ref/xpp-session-run-time-functions.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RobinARH
* Microsoft Alias: **robinr**

**Comment by kfend** [comment]
Thanks for the feedback. We have updated the topic.
