### ISSUE TITLE
LastProcessedChange_DateTime get reset

### ISSUE THREAD

**Issue by thomas-lange-drc-ngo** [MicrosoftDocs/dynamics-365-unified-operations-public#4710]
We are using the Export to Data Lake plugin and using both full tables and changefeeds to ingest data into our data warehouse. 

From [documentation](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/azure-data-lake-change-feeds), we read that LastProcessedChange_DateTime is a guaranteed field, that we can use for identifying changes to records in D365FO:

![image](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/assets/118353789/47ba451b-abf7-4cf0-a41a-9eedac536007)

On some tables, some of the LastProcessedChange_DateTime are NULL. So far we have seen this as an acceptable state, as we believed that this could only happen, when a record was last changed before enabling Export to Data Lake. 

However, on one table we are seeing that the LastProcessedChange_DateTime field is being reset to NULL, even when  previously had a non-NULL value. This is, in our view, a bug, as we are loosing the uniqueness of the records given the tuple (table, RECID, LastProcessedChange_DateTime).

The table in question is ProjPostedTransTable, which in our environment is large, highly customized and touched by a number of batchjobs.

**Comment by twheeloc** [comment]
@thomas-lange-drc-ngo, thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
