### ISSUE TITLE
Error when empty field when part of Unique index 

### ISSUE THREAD

**Issue by IllyaR** [MicrosoftDocs/dynamics-365-unified-operations-public#4712]
Hello 
I am currently using D365 FnO and open in Excel functionality. 
I faced a kind of strange issue. 
I have Table1 which has a relation by RecId to Table2 (Table1.Table2RecId = Table2.RecId). 
Table 1 has fields Name and Table2RecId as a unique index. 
Table2 has the field Code as a unique key.
Field Table2RecId could be empty and is part of a unique index.
There is a data entity for Table1. 
So, I also put dataSource Table2 to update it successfully. As Table2RecId is not mandatory, the outer join is used between Table1 and Table2 (Actually, if you create the data entity using the VS vizard, you'll get the same result)
As a result, I have an entity key that includes Name (from Table1) and Code (from Table2). 

Actual issue: when I try to update the record (change any field that is not part of the unique index) and the field Code is empty - I get the following error. When the Code is filled the update is working fine. 
Also, the strange part is that import through the Data management works fine.
On top of that, this error could not be caught by the debugger on AX side. I put a breakpoint to the SysDataEntityPersister.doPersistEntity, but it doesn't go there with such type of error. And this issue is reproducible on a couple of other entities easily.  
![image](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/assets/22895845/c8706b09-8d48-4bad-b5d1-404390212867)

Could you please tell me if you have seen the Silimar issue before? 
I can provide you with an example of an AX project if it is necessary. 

Thank you in advance

**Comment by twheeloc** [comment]
@IllyaR, thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
