### ISSUE TITLE
Integration from sandbox<->sandbox and production<->production

### ISSUE THREAD

**Issue by nandita-gaur** [MicrosoftDocs/dynamics-365-unified-operations-public#4713]
Power Platform integration is supported in the following ways only:
1. Sandbox type Power Platform can be integrated with Sandbox Finance and Operations environment.
2. Production type Power Platform can be integrated with Production instance of Finance and Operations environment. 

It should be good to document this publicly as well. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 52dded93-96f4-502e-66d9-a2cd4beeaaec
* Version Independent ID: 52dded93-96f4-502e-66d9-a2cd4beeaaec
* Content: [Environment lifecycle operations - Core concepts - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/power-platform/environment-lifecycle-core-concepts)
* Content Source: [articles/fin-ops-core/dev-itpro/power-platform/environment-lifecycle-core-concepts.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/power-platform/environment-lifecycle-core-concepts.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by twheeloc** [comment]
@nandita-gaur, thank you for your feedback. We have passed this feedback onto the product team for consideration.
