### ISSUE TITLE
Directions at heading "View and copy a standard business process library" don't match what I'm seeing.

### ISSUE THREAD

**Issue by JTWWI** [MicrosoftDocs/dynamics-365-unified-operations-public#4715]
Hello Microsoft documentation support team,

Could there be something out of date with these instructions:
"View and copy a standard business process library

You can select a standard business process library on the Business process library page. To open this page, sign in to Lifecycle Services, open a project, and then click the Business process modeler tile.
...
To select a standard business process library to start with, follow these steps:

    1 Sign in to Lifecycle Services, open a project, and then click the Business process modeler tile.
    2 In the Global libraries or Corporate libraries section, right-click a library.
    3 On the app bar, click Copy. The library is added to the My libraries section.
    4In the My libraries section, click the library to display the business process library."

In step 1, Business Process Modeller is not a tile once you have selected a project in LCS.
But there is a 'Business Process modeler' entry under the hamburger menu.
![image](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/assets/123598548/6199e9c7-5e49-48fe-8562-1010b2ef7ae3)

In step 2, you can't right click on a Global or Corporate library, it's just dumb HTML text on the page:
![image](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/assets/123598548/6efadac0-7bab-4080-86ea-0b773c3f7a77)

Step 3: There is no app bar:
![image](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/assets/123598548/ff4d92b3-3adb-4dff-857b-a30cd6ae691e)

Given the mis-match in experience to instruction, I can't get to step 4.

Am I missing something or is this instruction out of date or missing some steps?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c7c8e51e-8311-5b2a-2b74-764ee8b43724
* Version Independent ID: 4fd748b7-5e88-eff8-f424-f33d8774bf2c
* Content: [Business process libraries in Business process modeler (BPM) - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/business-process-libraries-business-process-modeler)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/business-process-libraries-business-process-modeler.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/lifecycle-services/business-process-libraries-business-process-modeler.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @gianugo
* Microsoft Alias: **gianura**

**Comment by twheeloc** [comment]
@JTWWI, in LCS, select the ellipsis in the upper right corner of the library to see the copy option.
