### ISSUE TITLE
Instructions at heading: "Configure the ER repository" difficult to follow?

### ISSUE THREAD

**Issue by JTWWI** [MicrosoftDocs/dynamics-365-unified-operations-public#4717]
Hello MS Documenation curation team,

Maybe I'm not reading it right, or didn't do some pre-requisite step, but when I read this section on this page:

Configure the ER repository

1   Close the page.
2  Go to Organization administration > Workspaces > Electronic reporting.
        Open the list of ER repositories for the current ER provider, Litware, Inc.
3  In the list, mark the selected row.
4 Click Repositories.
5 Click Show filters.

But this is what I see at this step: I don't see a 'show filters' button?  

![image](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/assets/123598548/f5e49882-c022-4e47-a2f2-8224bf39125a)

Perhaps this page could be improved with a review of how the UI looks currently, or maybe add a couple images so we know what we should be seeing?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b62064cb-3bc1-942a-7ee4-d6e470ea3ff3
* Version Independent ID: cc5fffe9-fa16-e563-c9b1-8f80105b4162
* Content: [Define the dependency of ER configurations on other components - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/tasks/er-define-dependency-er-configurations-from-other-components-july-2017?context=%2Fdynamics365%2Fcontext%2Ffinance)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/tasks/er-define-dependency-er-configurations-from-other-components-july-2017.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/analytics/tasks/er-define-dependency-er-configurations-from-other-components-july-2017.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **filatovm**

**Comment by JTWWI** [comment]
Follow up on this. Note that LCS has been deprecated in favour of RCS, so when we try to follow the next section to upload.. it says: Repository to share solution into not found for current configuration provider

**Comment by twheeloc** [comment]
@JTWWI, thank you for your feedback.  We have passed this feedback onto the product team for consideration.
