### ISSUE TITLE
Missings steps?

### ISSUE THREAD

**Issue by JTWWI** [MicrosoftDocs/dynamics-365-unified-operations-public#4718]
At this point in the document:

"
63. In the Description field, enter 'The unique identification assigned by the initiating party. This identification is passed on, unchanged, throughout the entire end-to-end chain.'.

64. In the Name field, type 'PaymentModel'.

The PaymentModel name aligns with predefined interfaces of payment forms.

65. Click Save.
"

I think there's a step missing between 63 and 64, I think it should be "Click New to open the drop dialog."

I think there's steps missing between 64 and 65, I think they should be "In the Item type field, select '???'. " and "Click Add."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0cce466c-382a-a37a-cdc1-bca4c73824f4
* Version Independent ID: e5ac5d4e-35a4-552f-50e3-838cea5ced29
* Content: [ER Design domain specific data model - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/tasks/er-design-domain-specific-data-model-2016-11?context=%2Fdynamics365%2Fcontext%2Ffinance)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/tasks/er-design-domain-specific-data-model-2016-11.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/analytics/tasks/er-design-domain-specific-data-model-2016-11.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **filatovm**

**Comment by twheeloc** [comment]
@JTWWI, thank you for your feedback. We have passed this feedback onto the product team for consideration.
