### ISSUE TITLE
Note, then steps.  Not steps in note.

### ISSUE THREAD

**Issue by JTWWI** [MicrosoftDocs/dynamics-365-unified-operations-public#4719]
Hello,

It looks like the note at the bottom of this page contains additional steps. It looks like this:
 Note

We have successfully bound elements of data model with items of data sources that are described by using details of application metadata from the referred ER metadata configuration. 36. Click Save. 37. Close the page. 38. Close the page. 39. When needed, you can extend the existing set of metadata and then export the new completed version of ER metadata configuration. You can then import it to RCS, and update the prerequisites of the configured model mapping configuration referring to a new version of imported metadata configuration.

Perhaps it should look like this instead?
 Note

We have successfully bound elements of data model with items of data sources that are described by using details of application metadata from the referred ER metadata configuration. 

36. Click Save. 
38. Close the page. 
39. 38. Close the page. 
40. 39. When needed, you can extend the existing set of metadata and then export the new completed version of ER metadata configuration. You can then import it to RCS, and update the prerequisites of the configured model mapping configuration referring to a new version of imported metadata configuration.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 55a65078-61cc-62eb-2b50-ff43c22b3912
* Version Independent ID: 9d931a34-440e-c7cc-4386-10cf6bee97b2
* Content: [Access application metadata by using ER configuration - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/tasks/access-application-metadata-er-configuration?context=%2Fdynamics365%2Fcontext%2Ffinance)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/tasks/access-application-metadata-er-configuration.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/analytics/tasks/access-application-metadata-er-configuration.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **filatovm**

**Comment by twheeloc** [comment]
@JTWWI, thank you for the feedback. The article will be updated later today.
