### ISSUE TITLE
Secondary and main instruction

### ISSUE THREAD

**Issue by OksanaKovaliova** [MicrosoftDocs/dynamics-365-unified-operations-public#473]
Could you, please, clarify what instruction drop dialog should have: main or secondary? Frames & Model show secondary instruction, when UX guidelines are about main instruction

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2517cd88-64c7-878d-de3d-04da520a0b6c
* Version Independent ID: f2b14861-c5fb-4cf5-6e18-0a56ad3250b0
* Content: [Drop Dialog form pattern - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/user-interface/drop-dialog-form-pattern)
* Content Source: [articles/dev-itpro/user-interface/drop-dialog-form-pattern.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/user-interface/drop-dialog-form-pattern.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by jasongre** [comment]
Drop dialogs are required to have a main instruction (form caption), as is true with almost all forms in Finance and Operations. The Wireframes do call out the form caption (which is the main instruction); however, the Model section does not explicitly call out the form caption as it only mentions controls (whereas form caption is just a property on Form.Design). Drop dialogs can also have a secondary instruction, but this is optional and should only be included if needed.

**Comment by sericks007** [comment]
Jason made a change to the content based on this issue, so now closing this issue.
