### ISSUE TITLE
The sentence says 'for for' when it should just say 'for'

### ISSUE THREAD

**Issue by blackjoker172** [MicrosoftDocs/dynamics-365-unified-operations-public#4736]
In this sentence: "The timing of the release of packages for for self-update relative to the timing of production auto-updates varies." The word 'for' is written twice.  It should just be there once.
I think this was just at typo.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2ef17be6-d125-5d12-8c25-c047a4c73686
* Version Independent ID: 2ef17be6-d125-5d12-8c25-c047a4c73686
* Content: [Service update availability - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/get-started/public-preview-releases)
* Content Source: [articles/fin-ops-core/dev-itpro/get-started/public-preview-releases.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/get-started/public-preview-releases.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @hmahl
* Microsoft Alias: **hmahl**

**Comment by twheeloc** [comment]
@blackjoker172, thank you for the feedback. The updated article will be published later today.
