### ISSUE TITLE
Please describe which processes are supported by location printer configuraiton

### ISSUE THREAD

**Issue by KarinaNormann** [MicrosoftDocs/dynamics-365-unified-operations-public#4738]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d2fe8bac-ab2f-8975-6d66-ab66fe1f0f7a
* Version Independent ID: 43250af3-9e4d-e0d7-2297-2cc5164116b8
* Content: [Dynamic printer selection - Supply Chain Management | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/supply-chain/warehousing/dynamic-printing-selection)
* Content Source: [articles/supply-chain/warehousing/dynamic-printing-selection.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/warehousing/dynamic-printing-selection.md)
* Service: **dynamics-365-supply-chain**
* GitHub Login: @adesypri
* Microsoft Alias: **adesypri**

**Comment by kamaybac** [comment]
@KarinaNormann . Thank you for reporting this issue. The location is only supported when printing container labels. We have updated the help topic to reflect this.
