### ISSUE TITLE
Retail error events 

### ISSUE THREAD

**Issue by OksanaKovaliova** [MicrosoftDocs/dynamics-365-unified-operations-public#474]
'Retail error events' query does not exist in LCS. We have to use 'All logs' with filters to find error events of Retail components

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2995dab3-754e-79d8-5bb3-857e06a4d9c1
* Version Independent ID: 99a6a217-49d8-67ee-da81-69970750e81a
* Content: [Retail component events for diagnostics and troubleshooting - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/dev-itpro/retail-component-events-diagnostics-troubleshooting)
* Content Source: [articles/retail/dev-itpro/retail-component-events-diagnostics-troubleshooting.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/dev-itpro/retail-component-events-diagnostics-troubleshooting.md)
* Service: **dynamics-365-retail**
* GitHub Login: @aamirallaqaband
* Microsoft Alias: **aamiral**

**Comment by ShylaThompson** [comment]
@aamirallaqaband, please review this issue and update the topic as necessary.

**Comment by sericks007** [comment]
Bug 260005 has been logged to track this issue.
