### ISSUE TITLE
Some wording on Synapse Link for Dataverse with Finance and Operations

### ISSUE THREAD

**Issue by AdamAndersson** [MicrosoftDocs/dynamics-365-unified-operations-public#4740]
Looking at [this post](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/azure-synapse-link-select-fno-data) and the [Finance cross-apps release plan](https://releaseplans.microsoft.com/en-US/?app=Finance+and+Operations+cross-app) then Export to Datalake will be replaced with the Synapse Link for Dataverse. It would be good if the "Export to Data Lake in finance and operations apps" page could have some comments on the Synapse Link for Dataverse and the deprecation of the "Export to Data Lake" feature. Also, some comments/recommendations if you are planning to export the FO data to a Data Lake and what approach to choose.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dc9b3593-eb08-83e6-61f9-392efaae2a30
* Version Independent ID: e70d1b5c-6f55-9834-5b33-abd9ebf1f2be
* Content: [Export to Data Lake in finance and operations apps - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/finance-data-azure-data-lake?source=recommendations)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/finance-data-azure-data-lake.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/finance-data-azure-data-lake.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by twheeloc** [comment]
@AdamAndersson, thank you for your feedback. This feedback has been passed onto the product group for consideration.
