### ISSUE TITLE
Admin consent on PowerBI Integration

### ISSUE THREAD

**Issue by fgehrke** [MicrosoftDocs/dynamics-365-unified-operations-public#4743]
The document https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/analytics/configure-power-bi-integration.md, on topic _Registration process_, contains information on how to create and configure the app in Azure AD. But in addition to this configuration, admin consent must be given for the permissions (after step 9) to allow reports to be published from FnO to PowerBI.

Like the picture below
![image](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/assets/1389743/69913d22-54ab-4205-bf0f-9e64efb09787)

As a support engineer we receive several cases that are resolved configuring the admin consent.

**Comment by twheeloc** [comment]
@fgehrke, thank you for the feedback. The updated article will be published later today.
