### ISSUE TITLE
The AX web application is not loading - giving 500 Error - There is a problem with the server

### ISSUE THREAD

**Issue by tjoshi17** [MicrosoftDocs/dynamics-365-unified-operations-public#4746]
We have created new cloud hosted box on 10.0.36 version and restored DB from UAT environment.
After full build and sync we have build error free but when we are trying to access AX web application it is giving us error as "There is a problem with the server. Sorry, the server has encountered an error. It is either not available or it can't respond at this time. Please contact your system administrator." 
We tried to use Admin Provisioning tool on dev box. will that be the cause for this? 
We tried to set the Admin user back to same which was originally there but still it fails and gives same error.
Is there any way to reset the settings or users to Original mode?
Anyone experienced similar issue on the box?
![Screenshot](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/assets/147721075/053adebd-4654-4946-a4b0-175028a34628)

**Comment by twheeloc** [comment]
@tjoshi17, thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
