### ISSUE TITLE
Incorrect feature mentioned

### ISSUE THREAD

**Issue by bjool** [MicrosoftDocs/dynamics-365-unified-operations-public#4748]
In 10.0.36 there are no feature called "Cancel bank statement reconciliation" in the Feature management workspace. 
Needs to be updated. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3d3b6674-f4ee-1bf4-2ac3-53aef9f762eb
* Version Independent ID: 3137c70e-92ff-e698-1d58-ecbaa6a72d4c
* Content: [Reconcile a bank account - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/cash-bank-management/reconcile-bank-account#cancel-bank-statement-reconciliation)
* Content Source: [articles/finance/cash-bank-management/reconcile-bank-account.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/cash-bank-management/reconcile-bank-account.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @angelad116
* Microsoft Alias: **angelading**

**Comment by twheeloc** [comment]
@bjool, thank you for your feedback. The article has been updated.
