### ISSUE TITLE
Trouble debugging CRT extension

### ISSUE THREAD

**Issue by felipearizaga-aa** [MicrosoftDocs/dynamics-365-unified-operations-public#4750]
Hello. Using the documentation on this page I am now able to debug the POS part of the store commerce, but I am not able to debug the CRT part. I am following the documentation: https://learn.microsoft.com/en-us/dynamics365/commerce/dev-itpro/sc-debug. But when setting a breakpoint I get "No symbols have been loaded for this document". Looking in Debug/Windows/Modules, in the "Symbol Status" column, "Cannot find or open the PDB file" appears. What am I missing?

![Captura de pantalla 2023-10-12 134800](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/assets/131482077/8d3e37b5-daa9-4c79-a1d3-90cd2d402efa)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 516e71f1-be29-9c22-fe2e-60a6eb065365
* Version Independent ID: 516e71f1-be29-9c22-fe2e-60a6eb065365
* Content: [Debug Store Commerce extensions using Visual Studio Code - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/dev-itpro/sc-debug)
* Content Source: [articles/commerce/dev-itpro/sc-debug.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/sc-debug.md)
* Service: **dynamics-365-commerce**
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by twheeloc** [comment]
@felipearizaga-aa, thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
