### ISSUE TITLE
EPSON printer model TM-T88IV is incorrect it should be TM-T88VI

### ISSUE THREAD

**Issue by trafique76** [MicrosoftDocs/dynamics-365-unified-operations-public#4752]
Hi @Microsoft team,

I guess EPSON printer model "TM-T88IV" mentioned under "Microsoft tested peripheral devices section" is incorrect it should be "TM-T88VI". Please check and correct in this page and any other pages applicable.

https://learn.microsoft.com/en-us/dynamics365/commerce/retail-peripherals-overview#microsoft-tested-peripheral-devices

![image](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/assets/147410257/78e3b284-864b-4a13-a090-44cfcd5e71f6)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8b7320ce-06d2-0dea-0077-c87e0c0a5e07
* Version Independent ID: 95ff0b85-b3a2-df8e-a0d2-ed85cc0ad3fe
* Content: [Peripherals - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/retail-peripherals-overview)
* Content Source: [articles/commerce/retail-peripherals-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/retail-peripherals-overview.md)
* Service: **dynamics-365-commerce**
* GitHub Login: @BrianShook
* Microsoft Alias: **brshoo**

**Comment by bishalgoswami** [comment]
Bug 854210 has been logged to address this issue.

**Comment by josaw1** [comment]
Thanks for your comment. @BrianShook can you please review?

**Comment by BrianShook** [comment]
@josaw1 I'll email a PR (sorry, accidentally unassigned myself).

**Comment by josaw1** [comment]
This article will be updated in the next 24 hours. Thanks.
