### ISSUE TITLE
Feature named incorrectly.

### ISSUE THREAD

**Issue by FrostaQRA** [MicrosoftDocs/dynamics-365-unified-operations-public#4753]
In 10.0.34 there are no feature called "Vendor bank account change proposal workflow" in the Feature management workspace.
Needs to be updated to reflect the name "Supplier bank account change proposal workflow"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 82d19f25-f8e8-7b5a-ad68-281f49b644a3
* Version Independent ID: 82d19f25-f8e8-7b5a-ad68-281f49b644a3
* Content: [Vendor bank account workflow - Finance | Dynamics 365](https://learn.microsoft.com/en-gb/dynamics365/finance/accounts-payable/vendor-bank-account-workflow)
* Content Source: [articles/finance/accounts-payable/vendor-bank-account-workflow.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/accounts-payable/vendor-bank-account-workflow.md)
* Service: **dynamics-365-finance**
* GitHub Login: @GalynaFedorova
* Microsoft Alias: **gfedorova**

**Comment by josaw1** [comment]
@twheeloc can you please update this article?

**Comment by joshdcabrera** [comment]
@FrostaQRA are you sure this is an issue? What language are you using in your user options?

I'm using 10.0.35, so it might be different but unlikely. In 10.0.35:

If you have language set to "en-US", it is "Vendor bank account change proposal workflow", and if you have "en-GB", it is "Supplier bank account change proposal workflow".

![image](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/assets/34781750/fd3691b7-ef89-4f6a-b09d-bf99d7721b91)
