### ISSUE TITLE
.pfx is replaced by Hardware or HSM tokens...

### ISSUE THREAD

**Issue by asimevs** [MicrosoftDocs/dynamics-365-unified-operations-public#4757]
Since June 2023, the CA's no more providing .pfx instead we get either hardware or HSM tokens. so please update article how it can be utilized with axutil. also is OV certificate is enough for this purpose?

Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 69192df7-736f-1504-e8ab-d1ececb95800
* Version Independent ID: 7707373e-0ef6-ac6b-fcce-efce6a0ade73
* Content: [Independent software vendor (ISV) licensing - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/isv-licensing)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/isv-licensing.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/dev-tools/isv-licensing.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @pnghub
* Microsoft Alias: **gned**

**Comment by josaw1** [comment]
@pvillads can you please review?

**Comment by johnmichalak** [comment]
Reached out to PM for guidance.

**Comment by johnmichalak** [comment]
This document was recently updated.
