### ISSUE TITLE
New functions not described

### ISSUE THREAD

**Issue by IanPodmore** [MicrosoftDocs/dynamics-365-unified-operations-public#4765]
There appears to be new fields available in CE when adding an F&O virtual table:

  Refresh

  Change Tracking

What do these fields do?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cc844b0c-c603-a69c-9387-1f56ddd875ac
* Version Independent ID: cc844b0c-c603-a69c-9387-1f56ddd875ac
* Content: [Enable Microsoft Dataverse virtual entities - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/power-platform/enable-virtual-entities)
* Content Source: [articles/fin-ops-core/dev-itpro/power-platform/enable-virtual-entities.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/power-platform/enable-virtual-entities.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @jaredha
* Microsoft Alias: **jaredha**

**Comment by twheeloc** [comment]
@IanPodmore, thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
