### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DRG2407** [MicrosoftDocs/dynamics-365-unified-operations-public#4766]
[Enter feedback here]
Article states "Select the Help button (?) in the upper-right corner of the app, and then select Support. "
However, no Support optin is available

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4af9b0a1-58ab-809b-37a6-0c476fe25478
* Version Independent ID: 4af9b0a1-58ab-809b-37a6-0c476fe25478
* Content: [Get support for finance and operations apps or Lifecycle Services (LCS) - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/lcs/lcs-support)
* Content Source: [articles/fin-ops-core/fin-ops/lcs/lcs-support.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/lcs/lcs-support.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @EricMoos
* Microsoft Alias: **emoos**

**Comment by josaw1** [comment]
@EricMoos can you please review this feedback?

**Comment by EricMoos** [comment]
I can see Support option under the '?' selection in FO

[A screenshot of a computer  Description automatically generated]

**Comment by DRG2407** [comment]
***@***.***
