### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by icone99** [MicrosoftDocs/dynamics-365-unified-operations-public#4769]
The link to First Release Program form is broken, leading to a 404 error.

![image](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/assets/68879218/ecf566ba-1033-4a51-bb87-62ab74f7a714)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2ef17be6-d125-5d12-8c25-c047a4c73686
* Version Independent ID: 2ef17be6-d125-5d12-8c25-c047a4c73686
* Content: [Service update availability - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/get-started/public-preview-releases)
* Content Source: [articles/fin-ops-core/dev-itpro/get-started/public-preview-releases.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/get-started/public-preview-releases.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @hmahl
* Microsoft Alias: **hmahl**

**Comment by twheeloc** [comment]
@icone99, thank you for your feedback. This link should be fixed now.
