### ISSUE TITLE
footer

### ISSUE THREAD

**Issue by tomasludi** [MicrosoftDocs/dynamics-365-unified-operations-public#4772]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8cff8489-f3f7-4522-8625-4b86061793fe
* Version Independent ID: 3b2681ce-6290-42d2-a02c-86b32bd6691d
* Content: [Footer module - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/author-footer-module)
* Content Source: [articles/commerce/author-footer-module.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/author-footer-module.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @anupamar-ms
* Microsoft Alias: **anupamar**

**Comment by bishalgoswami** [comment]
Bug 858500 has been logged to address this issue.

**Comment by josaw1** [comment]
@tomasludi, do you have a specific comment on this article? Thanks.
