### ISSUE TITLE
Getting a 404 error when clicking on the graphic

### ISSUE THREAD

**Issue by jkbirchMCAConnect** [MicrosoftDocs/dynamics-365-unified-operations-public#4777]
There is a graphic on the page which has a bad link and returns a 404 error. See the attached screenshots for details.
![MS Docs Issue 2](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/assets/135278058/20613030-d111-4e2c-8297-d3f0f77ae421)
![MS Docs Issue 1](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/assets/135278058/8f135baf-3421-4244-8b86-eb25627447ff)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e8067448-07ee-1508-657e-fa90a11b429c
* Version Independent ID: e8067448-07ee-1508-657e-fa90a11b429c
* Content: [Global address book overview - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/organization-administration/overview-global-address-book)
* Content Source: [articles/fin-ops-core/dev-itpro/organization-administration/overview-global-address-book.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/organization-administration/overview-global-address-book.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @msftbrking
* Microsoft Alias: **brking**

**Comment by kamaybac** [comment]
@jkbirchMCAConnect , thank you for reporting this issue. I am fixing it now.
