### ISSUE TITLE
Manifest is v2

### ISSUE THREAD

**Issue by simon-swtc** [MicrosoftDocs/dynamics-365-unified-operations-public#4784]
Recently installed the TaskRecorderScreenshot browser extension. It works, thank you very much.

Encountered two issues with it. First is the browser (Chrome) displaying an error that the extension uses Manifest V2. Second, over the weekend the extension in both browsers disappeared. Not uninstalled, not disabled, disappeared as if never installed in the first place. I've combined these two issues in case they are related.

Environment: Edge 119.0.2151.44 and Chrome 119.0.6045.106 on Windows 10 on an HP laptop.

**Comment by twheeloc** [comment]
@simon-swtc, thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
