### ISSUE TITLE
Incorrect referance

### ISSUE THREAD

**Issue by MarcRohde** [MicrosoftDocs/dynamics-365-unified-operations-public#4796]
In the last purple box of the page, I think you have the wrong job indicated. I think the proper name for the documentation is "Process automation background process system job"

![image](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/assets/15810225/78c7520b-9087-4354-90e8-aba37bd06e57)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d45d1c62-6273-1eed-432e-0c2db98c4d95
* Version Independent ID: 1c0777b6-6c96-f02f-a2c3-73332ad456bc
* Content: [Configuration for Finance insights - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/finance-insights/configure-for-fin-insites)
* Content Source: [articles/finance/finance-insights/configure-for-fin-insites.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/finance-insights/configure-for-fin-insites.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @ShivamPandey-msft
* Microsoft Alias: **shpandey**

**Comment by twheeloc** [comment]
@MarcRohde, thank you for the feedback. This article has been updated and changes will be reflected later today.
