### ISSUE TITLE
Create company in D365 does not have correct sequence

### ISSUE THREAD

**Issue by IngaJensen** [MicrosoftDocs/dynamics-365-unified-operations-public#4800]
This page is not providing the correct sequence on how to create a legal entity in D365. Please correct. i.e. you need to create number sequences before you can view these for the company.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ba49d180-7539-1759-8038-aa2433390be2
* Version Independent ID: 5398a07f-0645-e78e-d06a-d70c99e7f29c
* Content: [Create a legal entity - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/organization-administration/tasks/create-legal-entity)
* Content Source: [articles/fin-ops-core/fin-ops/organization-administration/tasks/create-legal-entity.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/organization-administration/tasks/create-legal-entity.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @sericks007
* Microsoft Alias: **sericks**

**Comment by twheeloc** [comment]
@IngaJensen, thank you for your feedback. The article has been updated.
