### ISSUE TITLE
filter on "code" doesn't seems to work

### ISSUE THREAD

**Issue by kristofmeesens** [MicrosoftDocs/dynamics-365-unified-operations-public#4801]
When I use on of the filters described on the page, I receive an error message "Invalid filter syntax"

![image](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/assets/82494779/383e2128-d12d-42e7-a912-2a52cd9605d1)

How do I find something in code?

Regards,

Kristof.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 17b1f3ab-dd65-bb8d-6b7d-3a6c1d19c672
* Version Independent ID: 2859401b-a524-18b4-0889-17623906a1fb
* Content: [Metadata search in Visual Studio - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/metadata-search-visual-studio)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/metadata-search-visual-studio.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/dev-tools/metadata-search-visual-studio.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @gianugo
* Microsoft Alias: **gianura**

**Comment by twheeloc** [comment]
@kristofmeesens, thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
