### ISSUE TITLE
Update docs to reflect that Positive days is now supported by Planning Optimization

### ISSUE THREAD

**Issue by texaspete** [MicrosoftDocs/dynamics-365-unified-operations-public#4803]
Hi

Here it is described that _Positive days_ is not used by Planning optimization:

https://learn.microsoft.com/en-us/dynamics365/supply-chain/master-planning/planning-optimization/not-used-parameters#coverage-groups-page

Per this link, _Positive days_ support was added in October 2023:

https://learn.microsoft.com/en-us/dynamics365/supply-chain/master-planning/planning-optimization/release-process

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aad34759-589f-24db-cf35-7664646a7ff3
* Version Independent ID: f2d59d91-7d54-ef2a-65c5-bc5f1541d122
* Content: [Parameters not used by Planning Optimization - Supply Chain Management | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/supply-chain/master-planning/planning-optimization/not-used-parameters?source=docs)
* Content Source: [articles/supply-chain/master-planning/planning-optimization/not-used-parameters.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/master-planning/planning-optimization/not-used-parameters.md)
* Service: **dynamics-365-supply-chain**
* GitHub Login: @t-benebo
* Microsoft Alias: **benebotg**

**Comment by kamaybac** [comment]
@texaspete , Thank you for reporting this issue. I've updated the topic in our system and the change should go live later today.
