### ISSUE TITLE
Synapse link is not compatible with our lake architechture

### ISSUE THREAD

**Issue by cltj** [MicrosoftDocs/dynamics-365-unified-operations-public#4809]
exporting data with your recommended way, through synapse link, is not compatible with your recommendations for designing architecture of the lake.
Through synapse link, we can only define a container in our datalake, but not any blobs (subdirectories)

"a good directory structure has the parent-level directories for things such as region and subject matters (for example, organization, product, or producer)."
[Best practice](https://learn.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-best-practices#batch-jobs-structure)

Considering the source above as well as other documentation and traing microsoft has been responsible for producing we have pieced together this information and came up with the following design. 

datalake -> layer -> product -> source
Example:
(conatiner)-(blob folder)-(blob folder)-(blob folder)
datalake -> bronze -> finance_operations -> dataverse

There are two shortcomming with using synape link. 
1) We can not define the name (it will just create one for us (dataverse-<customer>-org<numbers>)
This is muddying our nameing conventions creating techincal debt as we have to write special code for this particular instance. 
2) We can not decide where in the blob/directory we want to ingest the data.
There is no options for defining this in the synapse link. It will just create a container on its own (and conatiners are not renameable).
 
To keep our architecture clean and usable, as well as not creating any more data silos I do not understand microsoft in this decision. 
Please advice on how to sync data from finance operation into our datalake in a compatible way with its own architectual principals.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2f6ba603-2306-85f5-9eae-c71523326291
* Version Independent ID: 2f6ba603-2306-85f5-9eae-c71523326291
* Content: [Export to Azure Data Lake overview - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/azure-data-lake-ga-version-overview)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/Azure-Data-Lake-GA-version-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/Azure-Data-Lake-GA-version-overview.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by twheeloc** [comment]
@cltj, thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
