### ISSUE TITLE
Minor change needed

### ISSUE THREAD

**Issue by robadawy** [MicrosoftDocs/dynamics-365-unified-operations-public#4810]
[Enter feedback here]
Article mentions "In the One Version model, customer user acceptance testing (UAT) environments and production environments are updated every month". "Every month" should probably be replaced by "several times a year"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2af5d8ed-c2f2-7ec9-6bff-31d8e9506966
* Version Independent ID: 100bc8f6-fb74-4b18-2164-69a088ea8fd0
* Content: [Delivering ISV solutions using One Version - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/oneversion-isv)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/oneversion-isv.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/lifecycle-services/oneversion-isv.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @FrankDahl
* Microsoft Alias: **fdahl**

**Comment by twheeloc** [comment]
@robadawy, thank you for the feedback. The article has been updated and will be published.
