### ISSUE TITLE
Step 1 

### ISSUE THREAD

**Issue by GaryBento** [MicrosoftDocs/dynamics-365-unified-operations-public#4815]
Hi
step 1 should be changed, Legal entity set-up is under Organization Administration.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d5163349-6172-075a-6595-0cb8ff85621a
* Version Independent ID: 8cfe85c6-181f-6996-07b8-26135cdcd083
* Content: [Prepare a legal entity for the consolidation process - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/general-ledger/prepare-company-for-consolidation)
* Content Source: [articles/finance/general-ledger/prepare-company-for-consolidation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/general-ledger/prepare-company-for-consolidation.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @jinniew
* Microsoft Alias: **jiwo**

**Comment by twheeloc** [comment]
@GaryBento, thank you for your feedback. The article has been updated.
