### ISSUE TITLE
This page says you should have already completed the steps in "Create a new data model" but no such page exists I think?

### ISSUE THREAD

**Issue by JTWWI** [MicrosoftDocs/dynamics-365-unified-operations-public#4820]
Look at page: https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/tasks/er-define-model-mapping-select-data-sources-2016-11?context=%2Fdynamics365%2Fcontext%2Ffinance

It reads:
"The following steps explain how a user in the System Administrator or Electronic Reporting Developer role can select data sources for an Electronic reporting (ER) data model. The data sources will be bound to individual components of the selected data model at design time and populate business data to that data model at run-time. In this example, you will select data sources for an existing data model that has been created for sample company, Litware, Inc. To complete these steps, **you must first complete the steps in the "Create a new data model" procedure.**"

There is no nearby branch or page with title: "**Create a new data model**".

Perhaps I'm missing something or maybe the documentation site needs updating?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b90f7813-13eb-ce8b-bec4-f0a35a337805
* Version Independent ID: d8199da7-1e7d-a775-5f5e-7597c7d1192d
* Content: [Define ER model mappings and select data sources for them - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/tasks/er-define-model-mapping-select-data-sources-2016-11?context=%2Fdynamics365%2Fcontext%2Ffinance)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/tasks/er-define-model-mapping-select-data-sources-2016-11.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/analytics/tasks/er-define-model-mapping-select-data-sources-2016-11.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **filatovm**

**Comment by w-azure** [comment]
Thanks @JTWWI,

That link was missing, good eye.

I've added the appropriate link in the article, but here it is for convenience:
[Create a new data model](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/tasks/er-financial-dimensions-data-source-1?context=%2Fdynamics365%2Fcontext%2Ffinance#create-a-new-data-model)

Thanks for reaching out.
Winona
