### ISSUE TITLE
Change tracking can be used on any recurring (export) data job, not only BYODB

### ISSUE THREAD

**Issue by nmaenpaa** [MicrosoftDocs/dynamics-365-unified-operations-public#483]
The change tracking feature can be used on any recurring (export) data job, not just export to BYODB. But this documentation seems to imply that change tracking is something specific to BYODB export.

Actually this text lets room for interpretation that also other than BYODB cases are possible:
"To enable incremental export, you must enable change tracking on entities. If you don't enable change tracking on an entity, you can only enable a full export each time. For bring your own database (BYOD) use cases, change tracking can also track deletes if the entity supports this."

But this sentence implies that it's only available for BYODB: "You can enable change tracking when you publish one or more entities to a data store (BYOD)."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 678ace49-2430-6d7a-b0d9-90388633d31e
* Version Independent ID: 9ba9b3ac-75cf-3bd1-7de0-df20713c85ad
* Content: [Enable change tracking for entities - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/entity-change-track)
* Content Source: [articles/dev-itpro/data-entities/entity-change-track.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/entity-change-track.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by tonyafehr** [comment]
@MilindaV2, please review this issue and update the topic as necessary.

**Comment by Sunil-Garg** [comment]
Thank you for the comment nmaenpaa. The documentation has been updated to address the concern. Thanks.

**Comment by dmitribodiu** [comment]
> Can we use change tracking option on the OData integration while integrating with other application with OData I need to get only those record which is added, modified or deleted? Do we have that kind of option available in change tracking if No kindly mention it, if yes kindly elaborate it.

hello @PashaMohammed ! Did you find the answer to your question? I tried to call Odata with Prefer header, but no luck... No delta is coming back...
