### ISSUE TITLE
Broken link to PBI Install doc

### ISSUE THREAD

**Issue by riblack-microsoft** [MicrosoftDocs/dynamics-365-unified-operations-public#4834]
The [link to PBI Install doc](https://learn.microsoft.com/en-us/dynamics365/finance/business-performance-planning/install-bpp2) is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 614f5dfe-e89b-9ccf-1585-c86a67efa9b3
* Version Independent ID: 614f5dfe-e89b-9ccf-1585-c86a67efa9b3
* Content: [Microsoft Dynamics 365 Finance business performance planning requirements - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/business-performance-planning/install-bpp2)
* Content Source: [articles/finance/business-performance-planning/Install-BPP2.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/business-performance-planning/Install-BPP2.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @ShielaSogge
* Microsoft Alias: **twheeloc**

**Comment by twheeloc** [comment]
@riblack-microsoft, thank you for letting us know. The updated link will be live later today.
