### ISSUE TITLE
 Update current compensation feature

### ISSUE THREAD

**Issue by Sarimawan** [MicrosoftDocs/dynamics-365-unified-operations-public#4835]
[Enter feedback here]
 Update current compensation feature does not allow to update compensation

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0aa8f4cb-bc07-3ed5-045d-10c7c1a41ab3
* Version Independent ID: 45e009c9-208b-13aa-127d-3e8b3b7b699d
* Content: [Compensation plans - Human Resources | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/human-resources/hr-compensation-overview)
* Content Source: [articles/human-resources/hr-compensation-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/human-resources/hr-compensation-overview.md)
* Service: **dynamics-365-human-resources**
* Product: ****
* Technology: ****
* GitHub Login: @twheeloc
* Microsoft Alias: **twheeloc**

**Comment by twheeloc** [comment]
@Sarimawan,  thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
