### ISSUE TITLE
Could/Should this cover updates across Visual Studio versions?

### ISSUE THREAD

**Issue by rrhkpmg** [MicrosoftDocs/dynamics-365-unified-operations-public#4838]
Having discussed the process of updating a dev VM from VS2019 to VS2022, I understand that it's necessary to specify _Visual Studio Extension Development_ workload, with the _Modelling SDK_ option checked, during installation of Visual Studio, in order to use the F&O Development tools. Is that worth capturing here?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f9eb8e0d-73de-5530-5966-67b151ed89f3
* Version Independent ID: 1e98b55e-bced-af14-8a34-373c38af5365
* Content: [Update the Visual Studio development tools - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/update-development-tools)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/update-development-tools.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/dev-tools/update-development-tools.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @gianugo
* Microsoft Alias: **gianura**

**Comment by w-azure** [comment]
Thanks @rrhkpmg for the suggestion.
That's correct and the article has been updated. New changes should publish at some point today.
Many thanks.
