### ISSUE TITLE
[Maximum retries] works only if batch task fails due to batch service restart.

### ISSUE THREAD

**Issue by yujiim** [MicrosoftDocs/dynamics-365-unified-operations-public#4850]
[Maximum retries] works only if batch task fails due to batch service restart.
This sentence should be added to the section below.
https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/retryable-batch#retry-the-batch-job-task-regardless-of-the-error-type

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6a0878ca-257d-9ec4-eab0-8a570635cca2
* Version Independent ID: b5f3068c-b880-b5b9-3f82-ac3326a6dd7b
* Content: [Enable batch retries - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/retryable-batch)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/retryable-batch.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/sysadmin/retryable-batch.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @matapg007
* Microsoft Alias: **matgupta**

**Comment by johnmichalak** [comment]
Reached out to PM for guidance.

**Comment by yujiim** [comment]
We have confirmed that the behavior has changed from some version, and in the latest version, batch task is re-executed even when the batch service is not restarted. Close this request.
