### ISSUE TITLE
Please publish official documents which explain how we can test Dynamics 365 for Financial and operations with JMeter.

### ISSUE THREAD

**Issue by yujiim** [MicrosoftDocs/dynamics-365-unified-operations-public#4858]
[Enter feedback here]
If Performance SDK will be deprecated and Microsoft suggests JMeter, please publish official documents which explain how we can test Dynamics 365 for Financial and operations with JMeter.
https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/perf-test/perfsdk-multi-user-testing#:~:text=Visual%20Studio%202019%20is%20the%20last%20version%20of%20Visual%20Studio%20that%20includes%20web%20performance%20and%20load%20testing%20features%20and%20will%20be%20deprecated%20in%20the%20future.%20We%20suggest%20using%20Apache%20JMeter%20for%20performance%20testing.%20For%20more%20information%2C%20see%20JMeter.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f0b04519-4802-eaaa-c5ed-b13e8979d36d
* Version Independent ID: a4ebe802-e7fd-fd99-00a1-aa0ebf8fcb48
* Content: [Run multi-user testing by using the Performance SDK - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/perf-test/perfsdk-multi-user-testing)
* Content Source: [articles/fin-ops-core/dev-itpro/perf-test/perfsdk-multi-user-testing.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/perf-test/perfsdk-multi-user-testing.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @kennysaelen
* Microsoft Alias: **kesaelen**

**Comment by w-azure** [comment]
Hi @yujiim, apologies for the delay. 
There is currently a good 4-part blog series on Dynamics 365 finance and operations apps performance testing with JMeter. 

You can review the blogs for more information:

[Part 1 - Dynamics 365 finance and operations apps performance testing with JMeter - Introduction](https://community.dynamics.com/blogs/post/?postid=587b9524-30c9-422c-a5f8-4e3726f749b8)
[Part 2 - Dynamics 365 finance and operations apps performance testing with JMeter - Execution](https://community.dynamics.com/blogs/post/?postid=4fc1ab59-1948-ee11-be6d-00224827e8f9)
[Part 3 – Dynamics 365 finance and operations apps performance testing with JMeter - Result Analysis](https://community.dynamics.com/blogs/post/?postid=d1e5e04d-34da-ee11-a73d-6045bdb9f2e1)
[Part 4 – Dynamics 365 finance and operations apps performance testing with JMeter - Tips and Troubleshooting](https://community.dynamics.com/blogs/post/?postid=42ec2e60-59b4-ee11-92bd-002248511ab4)

Within the Dynamics 365 guidance docs, you can find information on [Set up and run load tests for your Dynamics 365 implementation projects](https://learn.microsoft.com/en-us/dynamics365/guidance/resources/test-scale-dynamics-365-solution). A few articles in the testing section require use of JMeter for different scenarios. 

We'll look into adding more links or information to the Dynamics 365 finance and operations documentation to cover JMeter use.
Thanks very much for your suggestion.
