### ISSUE TITLE
A list of available fields and where in D365 the data is pulling from would be really helpful here.

### ISSUE THREAD

**Issue by JuveJay** [MicrosoftDocs/dynamics-365-unified-operations-public#486]
A list of available fields and where in D365 the data is pulling from would be really helpful here.
One of the biggest issues we had was making sure we populated the forms that these fields pulled from.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65bb81dd-0908-099d-c588-e986fa70d912
* Version Independent ID: 1bef717d-99b9-8eae-5bb4-053d90b076fe
* Content: [Set up and design receipt formats - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/receipt-templates-printing)
* Content Source: [articles/retail/receipt-templates-printing.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/receipt-templates-printing.md)
* Service: **dynamics-365-retail**
* GitHub Login: @rubencdelgado
* Microsoft Alias: **rubendel**

**Comment by tonyafehr** [comment]
@rubencdelgado, please review this issue and update the topic as necessary.

**Comment by adrianmizzimlt** [comment]
More than a year passed!   Can this be published please?

**Comment by josaw1** [comment]
BUG 437635 opened for this point.

**Comment by rubencdelgado** [comment]
Apologies for the delay. The request here is very valid, but it is also non-trivial. In the next few monthly updates, we will be adding new options for designing receipts. As part of that work item, we are creating a content deliverable to list all valid receipt designer fields with their definitions.
