### ISSUE TITLE
Setting up the geolocation in  LCS

### ISSUE THREAD

**Issue by jlabustro** [MicrosoftDocs/dynamics-365-unified-operations-public#4862]
Why is APAC not on the list of geographies? Thanks in advance.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2d2fd431-c11f-d562-e81e-c41ee7987720
* Version Independent ID: 2d2fd431-c11f-d562-e81e-c41ee7987720
* Content: [Available geographies for Dynamics 365 finance and operations apps - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/deployment-options-geo)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/deployment-options-geo.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/deployment/deployment-options-geo.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @ShaileshNikam-MSFT
* Microsoft Alias: **shailesn**

**Comment by w-azure** [comment]
Hi @jlabustro,
Thanks for your feedback.
The reason APAC is not in the table is because they're not in a data resident region.
The geographies in the list provide data residency for Dynamics 365 Finance and Operations.
Thanks for the query though.
