### ISSUE TITLE
Error "The token does not contain valid algorithm in header" when setting up a new application

### ISSUE THREAD

**Issue by mihavuk** [MicrosoftDocs/dynamics-365-unified-operations-public#4866]
Following all steps from section "Set up a new application and certificate registration" I still get the error "You are not authorized to connect to 'mydomain.sharepoint.com'" on Document management parameters form and error "The token does not contain valid algorithm in header" in event log. We have customers with the same problem, so it seems the issue is general.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e1024bd5-7dcd-8666-1198-9ab7813bfd66
* Version Independent ID: e1024bd5-7dcd-8666-1198-9ab7813bfd66
* Content: [Secure one-box development environments - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/secure-developer-vm#set-up-a-new-application-and-certificate-registration)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/secure-developer-vm.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/dev-tools/secure-developer-vm.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @mnordick
* Microsoft Alias: **mnordick**

**Comment by twheeloc** [comment]
@mihavuk,  thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

**Comment by mihavuk** [comment]
The instructions on this page are wrong or insufficient. I have talked with different people and no-one managed to establish SharePoint connectivity. If it is out of you scope then just add a note on the page that it does not work.
