### ISSUE TITLE
Wrong path to Microsoft Azure application - should be Entra

### ISSUE THREAD

**Issue by fraga** [MicrosoftDocs/dynamics-365-unified-operations-public#4879]
Path specified here Administration > Setup > Azure Active Directory applications to register Dataverse.

Is actually 

System Administration > Setup > Microsoft Entra ID applications to register Dataverse.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8065cd89-f253-c50b-ed2e-7b84e5b2409c
* Version Independent ID: 8c7e311a-582c-1ac6-328e-be817a62924c
* Content: [Configure Dataverse virtual entities - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/power-platform/admin-reference)
* Content Source: [articles/fin-ops-core/dev-itpro/power-platform/admin-reference.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/power-platform/admin-reference.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by kamaybac** [comment]
@fraga , thank you for reporting this issue. We have now updated terminology throughout the article to use Entra ID.
