### ISSUE TITLE
Is JMeter supported for Dynamics app?

### ISSUE THREAD

**Issue by alneacsu** [MicrosoftDocs/dynamics-365-unified-operations-public#4880]
Hi!

Based on the below doc the JMeter can be used in correlation with Dynamics but talking with Edison Lai from Product Group he mentioned that there is no support for this feature in regards to Dynamics app. I just want to clarify this out.
[Run multi-user testing by using the Performance SDK - Finance & Operations | Dynamics 365 | Microsoft Learn](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/perf-test/perfsdk-multi-user-testing)

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f0b04519-4802-eaaa-c5ed-b13e8979d36d
* Version Independent ID: a4ebe802-e7fd-fd99-00a1-aa0ebf8fcb48
* Content: [Run multi-user testing by using the Performance SDK - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/perf-test/perfsdk-multi-user-testing?source=docs)
* Content Source: [articles/fin-ops-core/dev-itpro/perf-test/perfsdk-multi-user-testing.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/perf-test/perfsdk-multi-user-testing.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @kennysaelen
* Microsoft Alias: **kesaelen**

**Comment by w-azure** [comment]
Hi @alneacsu,
Thanks for your inquiry. That's correct, while JMeter is the recommended app for load testing, it's owned by Apache, therefore not supported by Microsoft.

However, there are several very helpful blogs written on JMeter to assist you in using it with Dynamics 365.

- [Part 1 - Dynamics 365 finance and operations apps performance testing with JMeter - Introduction](https://community.dynamics.com/blogs/post/?postid=587b9524-30c9-422c-a5f8-4e3726f749b8)
- [Part 2 - Dynamics 365 finance and operations apps performance testing with JMeter - Execution](https://community.dynamics.com/blogs/post/?postid=4fc1ab59-1948-ee11-be6d-00224827e8f9)
- [Part 3 – Dynamics 365 finance and operations apps performance testing with JMeter - Result Analysis](https://community.dynamics.com/blogs/post/?postid=d1e5e04d-34da-ee11-a73d-6045bdb9f2e1)
- [Part 4 – Dynamics 365 finance and operations apps performance testing with JMeter - Tips and Troubleshooting](https://community.dynamics.com/blogs/post/?postid=42ec2e60-59b4-ee11-92bd-002248511ab4)

I hope this helps.

**Comment by alneacsu** [comment]
[like]  Alexandru Adrian Neacsu reacted to your message:
________________________________
