### ISSUE TITLE
Wrong limk

### ISSUE THREAD

**Issue by amadse** [MicrosoftDocs/dynamics-365-unified-operations-public#4884]
Start your cloud migration journey with a no-charge, no-obligation migration assessment though the [Dynamics 365 Migration Program](https://dynamics.microsoft.com/migration-program/). The link doesn't lead to a Dynamics 365 Migration Program]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4c106-c0e3-81ba-db99-1fcdaa5158dd
* Version Independent ID: 0f4a76f7-d071-e9ee-4271-866a4ae417f9
* Content: [Upgrade from AX 2012 to finance and operations - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/upgrade-overview-2012?source=docs)
* Content Source: [articles/fin-ops-core/dev-itpro/migration-upgrade/upgrade-overview-2012.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/migration-upgrade/upgrade-overview-2012.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by w-azure** [comment]
Hi @amadse,
Thanks for your feedback. The link is correct, as it helps you understand the benefits of migrating your on-premises business applications to the cloud. You can then select _Get started_ to create your Dynamics 365 account, if needed, or contact Microsoft support to help you. 

However, you might find the documentation versions of this information useful. 
I recommend these articles:
 1. [Overview of the AIM migration program for on-premises solutions](https://learn.microsoft.com/en-us/dynamics365/get-started/aim-migration/migration-overview).
 2. [Move your business from on-premises to the cloud](https://learn.microsoft.com/en-us/dynamics365/guidance/implementation-guide/implementing-cloud-solutions-upgrade-from-onpremises-to-cloud).
 3. [Guidance, tools, and documentation for Dynamics CRM (on-premises) to Dynamics 365 migration](https://learn.microsoft.com/en-us/dynamics365/guidance/fasttrack/migration).
 
I hope this helps.
