### ISSUE TITLE
Notifications for 5 days before are not send now.

### ISSUE THREAD

**Issue by saac-learn** [MicrosoftDocs/dynamics-365-unified-operations-public#4885]
[Enter feedback here]

Notifications for 5 days before are not send now.
You get an emaIl when the update starts for UAT.
Nothing else.....

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 52eae7eb-eea1-e47d-c641-387fe517f990
* Version Independent ID: 6c9b3725-cd73-dbb7-cc4e-28d7c0eec0f4
* Content: [Get notified about service updates through Lifecycle Services (LCS) - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/notifications-service-updates)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/notifications-service-updates.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/lifecycle-services/notifications-service-updates.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @AngelMarshall
* Microsoft Alias: **tsmarsha**

**Comment by w-azure** [comment]
Hi @saac-learn, 

Thanks for reaching out.
The service updates do send out email notifications currently. 
Though if you are updating your environments yourself, you would receive no notification.
If you are not receiving service updates however, you might want to contact [Microsoft Support](https://support.microsoft.com/en-us).

Thanks.
