### ISSUE TITLE
Private keys no longer provided - looking for an alternative approach

### ISSUE THREAD

**Issue by coreyjb** [MicrosoftDocs/dynamics-365-unified-operations-public#4893]
I have a somewhat urgent request for some design support for some of our ISV solutions. As a Microsoft ISV partner, we require the private key certificate to generate our customer licenses. Refer the Microsoft ISV licensing link for further information: https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/isv-licensing 

We recently renewed our Code signing certificate with a Vendor - DigiCert. The last couple of years, we were downloading the private key certificate as .pfx format, and public key as cer format. This year, we were informed we can only receive the public key certificates in .crt, .pem, .cer, .p7b formats  (https://knowledge.digicert.com/general-information/new-private-key-storage-requirement-for-standard-code-signing-certificates-november-2022). However, the Microsoft documentation does not seem to outline how we could use these formats to enable licensing for our ISV solution - this is causing us delays in delivering our solutions to customers.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 69192df7-736f-1504-e8ab-d1ececb95800
* Version Independent ID: 7707373e-0ef6-ac6b-fcce-efce6a0ade73
* Content: [Independent software vendor (ISV) licensing - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/isv-licensing)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/isv-licensing.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/dev-tools/isv-licensing.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @pnghub
* Microsoft Alias: **gned**

**Comment by johnmichalak** [comment]
This document was recently updated.
