### ISSUE TITLE
The Activity monitoring tool retains data for only 16 days.

### ISSUE THREAD

**Issue by damienmaspero** [MicrosoftDocs/dynamics-365-unified-operations-public#4898]
The doc states : 
"The Activity monitoring tool retains data for only 30 days."

Instead : 
"The Activity monitoring tool retains data for only 16 days."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 64b5b03d-9169-f94e-f999-63bc5a8e68ac
* Version Independent ID: 177eb187-6962-ba30-7a63-86b0bf3452d7
* Content: [Monitoring and diagnostics tools in Lifecycle Services (LCS) - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/monitoring-diagnostics)
* Content Source: [articles/fin-ops-core/dev-itpro/lifecycle-services/monitoring-diagnostics.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/lifecycle-services/monitoring-diagnostics.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @AngelMarshall
* Microsoft Alias: **tsmarsha**

**Comment by w-azure** [comment]
Hi @damienmaspero,
Apologies for the delay, but thanks for your inquiry.
Microsoft has data retention policies that adhere to GDPR requirements.
The data retention of 30 days is correct.

You can read more about data retention policies here:
https://learn.microsoft.com/en-us/compliance/assurance/assurance-data-retention-deletion-and-destruction-overview 

Thanks for your feedback just the same.

**Comment by w-azure** [comment]
Thanks @damienmaspero, 
The retention of data policies is 30 days globally (there is no geo-based retention). 
Thank you nonetheless for the feedback.
