### ISSUE TITLE
Mobile emulator installation / configuration

### ISSUE THREAD

**Issue by Frank-Huster** [MicrosoftDocs/dynamics-365-unified-operations-public#490]
Hi, is it possible to emulate the usage of MS Dynamics 365 Unified Operations on the PC? If yes, how can I do this? I can not find an instruction and I'm not mobile developer enough to apply a general guide to this process.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d7b2642-94fe-3875-6edd-5a48a0488483
* Version Independent ID: 41272ea7-2a2d-c358-b013-7ed53056fc8c
* Content: [Publish mobile workspaces - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/mobile-apps/publish-mobile-workspace?toc=/fin-and-ops/toc.json)
* Content Source: [articles/dev-itpro/mobile-apps/publish-mobile-workspace.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/mobile-apps/publish-mobile-workspace.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @sericks007
* Microsoft Alias: **sericks**

**Comment by tonyafehr** [comment]
Thanks for contacting us. We will look into enhancing the documentation to provide the information that you're looking for. In the meantime, to get product help you can contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the Dynamics 365 for Finance and Operations community page to get help with your questions from the Dynamics community.
