### ISSUE TITLE
Signature hash – Enter hpavxC1xAIAr5u39m1waWrUbsO8=.

### ISSUE THREAD

**Issue by V4A001** [MicrosoftDocs/dynamics-365-unified-operations-public#4903]
To avoid setup issues, it is recommended to explicitly explain if the . (dot) must be added yes or no.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 97a79a60-012a-ec20-53cc-1cad1697b1fd
* Version Independent ID: edf1ae75-e8b6-7376-3ce5-74d113b431a0
* Content: [User-based authentication for the Warehouse Management mobile app - Supply Chain Management | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/supply-chain/warehousing/warehouse-app-authenticate-user-based)
* Content Source: [articles/supply-chain/warehousing/warehouse-app-authenticate-user-based.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/warehousing/warehouse-app-authenticate-user-based.md)
* Service: **dynamics-365-supply-chain**
* GitHub Login: @JTOne123
* Microsoft Alias: **pavlodatsiuk**

**Comment by kamaybac** [comment]
@V4A001 , the period is not part of it. I'll edit the topic to make that more clear.
