### ISSUE TITLE
error after submitting E-invoice to ZATCA QR code not attached to sales invoice 

### ISSUE THREAD

**Issue by MrAhmedSayedAli** [MicrosoftDocs/dynamics-365-unified-operations-public#4904]
error after submitting E-invoice to ZATCA QR code not attached to sales invoice also note we follow the attached ref.

https://learn.microsoft.com/en-us/dynamics365/finance/localizations/mea/gs-e-invoicing-sa-get-started#configure-electronic-document-parameters

 
![image](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/assets/7157140/b355b5a0-5c3f-44e3-9fc6-411f2f92dbc0)

![image](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/assets/7157140/8b29a76f-af8b-4f02-9842-f352774da7e7)

**Comment by twheeloc** [comment]
@MrAhmedSayedAli, thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
