### ISSUE TITLE
Microsoft Dynamics 365 - Translation Service - Completed with Error

### ISSUE THREAD

**Issue by BSSI-Vinay** [MicrosoftDocs/dynamics-365-unified-operations-public#4905]
When creating a translation request based on a .xlf file, the translation service reports this as "Completed with errors" and shows no further information. When viewing the output, it shows: File could not be translated. Open a new request. This request completed with the error(s).
The request ids are 85924, 85925, 85926, 85927

Thanks for any advice.

**Comment by twheeloc** [comment]
@BSSI-Vinay, thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
