### ISSUE TITLE
Feature deprecation - manual added users no longer supported without entra account

### ISSUE THREAD

**Issue by SuperVladys** [MicrosoftDocs/dynamics-365-unified-operations-public#4909]
Section about manually adding user "https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/sysadmin/create-new-users#manually-add-a-new-user" is no longer valid. User's without entra id are not allowed since Monday. 

Supporting article about feature depprecation: "https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/removed-deprecated-features-platform-updates#feature-deprecation-effective-march-2024".

Can we please get new guide explaining how to create service accounts? Also please update the current guide, or at least mark it as deprecated. It is causing issues as this is go to article for creating service accounts.

**Comment by johnmichalak** [comment]
Reached out to PM for guidance.

**Comment by johnmichalak** [comment]
@SuperVladys This article was updated last month. Can you take a look to see if the changes that were made address your concerns?
