### ISSUE TITLE
Feature deprecation effective March 2024 - Non-Entra ID external user sign-in - Why in the official document state starting from March but they already have issue since February?

### ISSUE THREAD

**Issue by VeronicaTran** [MicrosoftDocs/dynamics-365-unified-operations-public#4913]
My customer wants to know Why in the official document state starting from March but they already have issue since February?
Ref: https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/removed-deprecated-features-platform-updates#feature-deprecation-effective-march-2024

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 41eb5c0b-0d09-adb4-88ac-81ef04e7c423
* Version Independent ID: 41eb5c0b-0d09-adb4-88ac-81ef04e7c423
* Content: [Personalize the user experience - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/get-started/personalize-user-experience#export-and-import-views-or-personalizations)
* Content Source: [articles/fin-ops-core/dev-itpro/get-started/personalize-user-experience.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/get-started/personalize-user-experience.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by twheeloc** [comment]
@VeronicaTran, thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
