### ISSUE TITLE
the update CY24Q2: 10.0.39 should be available from March 15, 2024

### ISSUE THREAD

**Issue by Pawel-Kolosza** [MicrosoftDocs/dynamics-365-unified-operations-public#4915]
[Hi,

the update CY24Q2: 10.0.39 should be available from March 15, 2024,
But it’s still not visible in LCS On the Environment page, below Available updates.
Could you please explain it ASAP?
 

Thanks in advance.
Best regards,
Pawel Kolosza.
]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2ef17be6-d125-5d12-8c25-c047a4c73686
* Version Independent ID: 2ef17be6-d125-5d12-8c25-c047a4c73686
* Content: [Service update availability - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/get-started/public-preview-releases#targeted-release-schedule-dates-subject-to-change)
* Content Source: [articles/fin-ops-core/dev-itpro/get-started/public-preview-releases.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/get-started/public-preview-releases.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @hmahl
* Microsoft Alias: **hmahl**

**Comment by terry-sys** [comment]
anyupdate?

**Comment by Pawel-Kolosza** [comment]
Hi,

the update CY24Q2: 10.0.39 was available on March 19 instead 15, 2024
in LCS On the Environment page, below Available updates.
