### ISSUE TITLE
Order flow

### ISSUE THREAD

**Issue by weaveriski** [MicrosoftDocs/dynamics-365-unified-operations-public#492]
The diagram indicates a Operations to Sales flow for orders, whilst the video and other pages show the origin of the order in Sales flowing to Operations. The entity exists for both but one message/diagram should be clear. The option changes on the industry and needs of the customer, so perhaps a two way arrow?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 347ab5ee-3ff7-a767-43df-a6c9e04800ca
* Version Independent ID: 97e9ff03-f3be-a454-d067-a619f871f847
* Content: [Synchronize accounts directly from Sales to customers in Finance and Operations - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/sales-marketing/accounts-template-mapping-direct)
* Content Source: [articles/supply-chain/sales-marketing/accounts-template-mapping-direct.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/sales-marketing/accounts-template-mapping-direct.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @ChristianRytt
* Microsoft Alias: **crytt**

**Comment by tonyafehr** [comment]
@weaveriski. Thanks for your feedback. We've made some updates to this topic that will be published later today. Thanks again!
