### ISSUE TITLE
Picture too small

### ISSUE THREAD

**Issue by KittyDreadfull** [MicrosoftDocs/dynamics-365-unified-operations-public#4921]
The architecture picture is too small to read and there's no option to enlarge it.  This is not accessibility-friendly.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 192b1671-b9d3-debd-e7dc-d18f8edf7ba0
* Version Independent ID: 192b1671-b9d3-debd-e7dc-d18f8edf7ba0
* Content: [Dynamics 365 Commerce architecture overview - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/dev-itpro/commerce-architecture)
* Content Source: [articles/commerce/dev-itpro/commerce-architecture.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/commerce-architecture.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @samjarawan
* Microsoft Alias: **samjar**

**Comment by kamaybac** [comment]
@KittyDreadfull , thank you for bringing this issue to our attention. I am adding an enlarge option now. You can also enlarge the image by right-clicking and selecting "Show image in new tab".
