### ISSUE TITLE
Wrong What's new or changed in Microsoft Dynamics 365 Human Resources link is pointing to the old HR CRM release notes

### ISSUE THREAD

**Issue by radu87ro** [MicrosoftDocs/dynamics-365-unified-operations-public#4925]
[Enter feedback here]
The **_What's new or changed in Microsoft Dynamics 365 Human Resources_** link is pointing to the old HR CRM release notes. It should redirect to the HR merged FO infrastructure release notes.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 27899f77-9cc9-1831-fa16-9c0c71f8f1c3
* Version Independent ID: 4bfcb1d6-3e1d-b24b-4429-ab3b8f31eb3e
* Content: [What's new or changed in finance and operations apps home page - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/whats-new-changed?toc=%2Fdynamics365%2Ffinance%2Ftoc.json)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/whats-new-changed.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/whats-new-changed.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @twheeloc
* Microsoft Alias: **twheeloc**

**Comment by twheeloc** [comment]
@radu87ro, thank you for the feedback. The updated article will be live later today.
