### ISSUE TITLE
Appended table of documents to the Collection letter note 

### ISSUE THREAD

**Issue by RuitheCurious** [MicrosoftDocs/dynamics-365-unified-operations-public#4949]
Hi,

The appended table to the Collection letter notes only includes past due open transactions.

Is there a way to change this to include all open transactions (overdue and not overdue)?

Thanks.

Best regards, Rui

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2a4d4d55-5b82-1362-6b5f-70c20ab9b654
* Version Independent ID: 1c51a483-03df-e598-34fb-192b22aadce8
* Content: [Process collection letters - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/accounts-receivable/tasks/process-collection-letters)
* Content Source: [articles/finance/accounts-receivable/tasks/process-collection-letters.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/accounts-receivable/tasks/process-collection-letters.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @ShivamPandey-msft
* Microsoft Alias: **shpandey**

**Comment by twheeloc** [comment]
@RuitheCurious, thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
