### ISSUE TITLE
Memory configuration in SQL Server Sizing section

### ISSUE THREAD

**Issue by TrudAX** [MicrosoftDocs/dynamics-365-unified-operations-public#496]
There is probably a mistake or outdated information for the recommended memory per core in SQL Server Sizing section - it states  "2 GB to 4 GB memory for each core." It is very low for the modern CPUs
If you check Azure VMs that are recommended for SQL Server( E and D series)  they have a larger memory size (for example D8v3 - 4 GB per v-core, E32 16s v3 - 16GB per v-core). 
Can you change this line "2 GB to 4 GB memory for each core"
to  "4 GB - 16GB memory for each v-core"    

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d0233a5-f7d9-5594-594f-faa5e205a513
* Version Independent ID: 80a24631-8773-4158-d745-bd97b8a9c7cd
* Content: [Hardware sizing requirements for on-premises environments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/hardware-sizing-on-premises-environments)
* Content Source: [articles/fin-and-ops/get-started/hardware-sizing-on-premises-environments.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/hardware-sizing-on-premises-environments.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @kfend
* Microsoft Alias: **chwolf**

**Comment by sericks007** [comment]
Thanks for letting us know!  We'll investigate and update the topic if necessary.

**Comment by sericks007** [comment]
This issue is being tracked by bug 261737.
