### ISSUE TITLE
DMFExportToPackageForceSync

### ISSUE THREAD

**Issue by stefanlundquist** [MicrosoftDocs/dynamics-365-unified-operations-public#500]
The add key = is wrong in the text above for DMFExportToPackageForceSync? or should the value be the same for both keys ? 
Sorry, it is the RECID that's wrong. They have the same value for both of them

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c6788e8-dfb0-6108-71ae-e265bad542a2
* Version Independent ID: 68a26703-3d8c-4d46-6f3f-37c30aa79373
* Content: [Data management - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/data-entities-data-packages#features-flighted-in-data-management-and-enabling-flighted-features)
* Content Source: [articles/dev-itpro/data-entities/data-entities-data-packages.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/data-entities-data-packages.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by sericks007** [comment]
This issue is being tracked by bug 261738.

**Comment by tonyafehr** [comment]
This issue has been fixed and updated content will be published today.
