### ISSUE TITLE
Not always...

### ISSUE THREAD

**Issue by BrianHumlicek** [MicrosoftDocs/dynamics-365-unified-operations-public#501]
This document says "Some enums require the elements to have a certain order or value, and cannot be made extensible. This could be status enums, where the values represent a logical progressive sequence...", however, both WHSExpeditionStatus and ProdStatus were made extensible in Dynamics 8.1 release.  The enums represent a clear logical progression and even have 'Status' in their names.

Not only does this go against what is written here, but is a breaking change as discussed here.
https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/extensibility/breaking-changes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc4f7135-87e3-67c0-6bb1-a5ce88a7a909
* Version Independent ID: 473aea55-658c-84a5-2b02-70cc53a6b480
* Content: [Write extensible enums - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/extensibility/extensible-enums)
* Content Source: [articles/dev-itpro/extensibility/extensible-enums.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/extensibility/extensible-enums.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @smithanataraj
* Microsoft Alias: **smithanataraj**

**Comment by ShylaThompson** [comment]
@smithanataraj, can you fix this topic?

**Comment by sericks007** [comment]
This issue is being tracked by bug 261740.

**Comment by smithanataraj** [comment]
Hi Brian,

Enums with progressive sequential values when made extensible, can break consumers using them in comparisons. For 8.1, a recompile was required and hence making such enums like status enums extensible, was a conscious decision that was made, in order to provide extensibility on those. This will not be the case with monthly updates.
