### ISSUE TITLE
Where to see alerts & troubleshooting

### ISSUE THREAD

**Issue by GaborJF** [MicrosoftDocs/dynamics-365-unified-operations-public#502]
Would be great to explain where to see the alerts; is that in the notification icon?  If it isn't working, how to troubleshoot?  Can we also set up to be notified by email?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0a3ca39-86d2-d8e4-6f33-95f1e802b4e7
* Version Independent ID: 3e537bc3-ce30-66bd-9509-d7afd3f71cf4
* Content: [Create alert rules - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/create-alerts)
* Content Source: [articles/fin-and-ops/get-started/create-alerts.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/create-alerts.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by ShylaThompson** [comment]
@TJVass, can you add a screenshot to the topic to show how the user is notified of an alert in the system?

**Comment by sericks007** [comment]
This issue is being tracked by bug 261741.

**Comment by gomezjrs** [comment]
Alerts are shown in the top right corner. Click Show Messages or Ctrl + Shift + F7. You also have run the job from System administration > Periodic tasks > Alert > Change based alerts. What would be nice that I can't seem to find is a history of Alerts, including those which have been cleared. Oh, email too, as previously mentioned.
