### ISSUE TITLE
Register a web application with AAD

### ISSUE THREAD

**Issue by TomekMelissa** [MicrosoftDocs/dynamics-365-unified-operations-public#511]
The header says Register a native application with AAD, but in fact steps are describing web app registration. It creates confusion among users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ba7bfc1-7c23-5662-8f2c-b41b19fb9070
* Version Independent ID: 19eb0a4a-1594-8f8b-054c-2c851df17e8b
* Content: [Service endpoints - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/services-home-page)
* Content Source: [articles/dev-itpro/data-entities/services-home-page.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/services-home-page.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by tonyafehr** [comment]
@Sunil-Garg, can you update this topic to clarify what the user needs to do in the procedure. Thanks!

**Comment by sericks007** [comment]
This issue is being tracked by bug 261742.

**Comment by tonyafehr** [comment]
This issue has been fixed and will be published later today. Thank you!
