### ISSUE TITLE
on-premise environment and Azure

### ISSUE THREAD

**Issue by deeageMu** [MicrosoftDocs/dynamics-365-unified-operations-public#514]
I don't understand why this article mensions Dynamics 365 on-premise installation and Azure in the same article. Is this article really ment for on-premise deployments?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0ec145b-37e3-39d7-f7ef-2ea43a3a9b3a
* Version Independent ID: 30705b5a-301b-63d9-45df-91b1910990cf
* Content: [Configure reverse proxies for on-premises environments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/deployment/onprem-reverseproxy)
* Content Source: [articles/dev-itpro/deployment/onprem-reverseproxy.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/deployment/onprem-reverseproxy.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @sarvanisathish
* Microsoft Alias: **sarvanis**

**Comment by sericks007** [comment]
Thanks for posting this. We'll investigate and look into whether this content needs to be updated.

**Comment by sericks007** [comment]
I reviewed this with a support engineer. Azure is mentioned in this article as Service Fabric is marketed under the Azure product umbrella. For more information about Service Fabric, please see https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/deployment/plan-onprem-deployment#service-fabric.
