### ISSUE TITLE
Apply deployable package on tier 2?

### ISSUE THREAD

**Issue by marihul** [MicrosoftDocs/dynamics-365-unified-operations-public#515]
Is the "Run the data upgrade deployable package" section correct? My experience is, that every time I want to apply the data upgrade deployable package to an Standard Acceptance Test environment I have to open a data upgrade request in the LCS.
Shouldn't that be mentioned in this section?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: babaa821-a53a-020c-4411-d2c39e371d05
* Version Independent ID: afb66707-3384-278c-2827-cff7499c56ea
* Content: [Upgrade from AX 2012 - Data upgrade in sandbox environments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/upgrade-data-sandbox#run-the-data-upgrade-deployable-package)
* Content Source: [articles/dev-itpro/migration-upgrade/upgrade-data-sandbox.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/migration-upgrade/upgrade-data-sandbox.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @tariqbell
* Microsoft Alias: **tabell**

**Comment by sericks007** [comment]
Thanks for posting this.  We'll investigate and look into whether this content needs to be updated.

**Comment by marihul** [comment]
Ah I see I misread the instructions, we need to apply the deployable package manually for tier 2 environments. There is no need to update the documentation :-)

**Comment by sericks007** [comment]
OK, thanks for letting me know!
