### ISSUE TITLE
Link doesn't work

### ISSUE THREAD

**Issue by amadse** [MicrosoftDocs/dynamics-365-unified-operations-public#516]
see Packages, runbooks, and the AXUpdateInstaller in depth at the end of this topic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4008b2e3-4d1a-e146-8bdb-f39280124e9f
* Version Independent ID: 22f8390d-bb4d-1755-515c-7e7ebf1ddaae
* Content: [Apply updates to cloud environments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/deployment/apply-deployable-package-system#packages-runbooks-and-the-AXUpdateInstaller-in-depth)
* Content Source: [articles/dev-itpro/deployment/apply-deployable-package-system.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/deployment/apply-deployable-package-system.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @manalidongre
* Microsoft Alias: **manado**

**Comment by sericks007** [comment]
Thanks for letting us know!  I've fixed the link.  The updated article will be published this week.
