### ISSUE TITLE
Deployment of customized package with metadata hotfix in a new environment

### ISSUE THREAD

**Issue by ripannandy** [MicrosoftDocs/dynamics-365-unified-operations-public#518]
Metadata hotfix(X++ updates) is applied to the development environment. Deployable package is being created from the development environment considering all the models which are modified due to the deployment of X++ updates. If this deployable package is applied to a new environment, is it required to apply the metdata hotfix again that was applied in the earlier development environment? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66b4c899-c7e0-0406-0d39-d32fc41b6104
* Version Independent ID: 5d015069-177d-e33c-094c-257df088a7c0
* Content: [Install metadata hotfixes in development environments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/install-metadata-hotfix-package)
* Content Source: [articles/dev-itpro/migration-upgrade/install-metadata-hotfix-package.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/migration-upgrade/install-metadata-hotfix-package.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RobinARH
* Microsoft Alias: **robadawy**

**Comment by kfend** [comment]
No. If the X++ hotfix is already part of the deployable packages that you created on the development environment, and you apply the deployable package on a destination environment, there is no need to apply the metadata X++ metadata hotfix on the destination environment. Keep in mind that deployable packages are designed to be applied on runtime environment (environments with no source code like Acceptance Test and production environments), so you can’t directly apply X++ hotfixes to these environments anyway, that is why you use deployable packages.
If the destination environment is a development environment, use version control (Azure dev Ops) to move code and not deployable packages.
