### ISSUE TITLE
Production deployment package downtime

### ISSUE THREAD

**Issue by maheshambati410** [MicrosoftDocs/dynamics-365-unified-operations-public#521]
is there any change in downtime for package deployment in production?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50392961-60d5-ee55-613a-1128a25ef11a
* Version Independent ID: c163ee84-669b-137a-a610-9e88c91709ad
* Content: [Prepare for go-live - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/imp-lifecycle/prepare-go-live)
* Content Source: [articles/fin-and-ops/imp-lifecycle/prepare-go-live.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/imp-lifecycle/prepare-go-live.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @ClaudiaBetz-Haubold
* Microsoft Alias: **chaubold**

**Comment by sericks007** [comment]
Bug 263438 has been logged to track this issue.

**Comment by ClaudiaBetz-Haubold** [comment]
Yes, we have made improvements to the time it takes to do package deployments. Generally, 95% of updates are applied in less than an hour. We still recommend to provide a downtime window of 4 hours in case a rollback is required for any reason. If the package deployment succeeds, which it does almost all of the time, the environment will be available as soon as the package deployment has finished, meaning that the longer downtime window does not have any negative effect on the availability of the system.

The Service Description document (https://go.microsoft.com/fwlink/?LinkId=867755&clcid=0x409) specifies the details such as duration and planed maintenance window for all services. It is updated regularly.
