### ISSUE TITLE
How to update tier1 sandboxes

### ISSUE THREAD

**Issue by TirolerDev** [MicrosoftDocs/dynamics-365-unified-operations-public#522]
How would it be possible to update other development tier 1 environments? Is there an ability to deploy directly the 8.1 binary update package?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b3b5ec6-1a21-e71a-df38-ba497f7f1116
* Version Independent ID: d1e49823-7934-6a3a-50e1-547cdd632077
* Content: [Update environments from version 8.0 to 8.1 - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/appupdate-80-81)
* Content Source: [articles/dev-itpro/migration-upgrade/appupdate-80-81.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/migration-upgrade/appupdate-80-81.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by laneswenka** [comment]
Hi Tiroler, right now we are recommending to redeploy the developer environments per the documentation.  We are working on an update experience for the Dev and Build environment topologies.
