### ISSUE TITLE
About LEGACY_CARDINALITY_ESTIMATION

### ISSUE THREAD

**Issue by ZeDocteur** [MicrosoftDocs/dynamics-365-unified-operations-public#523]
I was wondering if LEGACY_CARDINALITY_ESTIMATION set to 1 is still relevant even in D365 FO as it was in Ax 2012 R3. Is there a benchmark available somewhere that compares the two configurations for typical scenarios, with and without Legacy CE, on D365 FO ? Or is it a "rule of thumb" that is applied blindy since SQL Server 2014 and didn't get tested since then?

Edit: Here's the line in the document I'm refering to:
ALTER DATABASE SCOPED CONFIGURATION  SET LEGACY_CARDINALITY_ESTIMATION=ON
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cef28a03-9759-ae74-20ba-2ec089c43d5b
* Version Independent ID: 1b085a75-6c84-c2a8-1ce8-60c272e8bfaf
* Content: [Copy Finance and Operations databases from SQL Server to production Azure SQL Database environments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/copy-database-from-sql-server-to-azure-sql)
* Content Source: [articles/dev-itpro/database/copy-database-from-sql-server-to-azure-sql.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/database/copy-database-from-sql-server-to-azure-sql.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @maertenm
* Microsoft Alias: **maertenm**

**Comment by kfend** [comment]
Thanks for your comment. Here is the information that I received from one of our engineers:
SQL Server uses two methods of cardinality estimation.  One considers the relationship between fields, and the other does not.  In Finance and Operations, with newer versions of SQL Server, we recommend using the cardinality estimation that does consider field relationships.  That is what this ‘database scoped configuration’ does for us.
