### ISSUE TITLE
Text was not updated properly 

### ISSUE THREAD

**Issue by TrudAX** [MicrosoftDocs/dynamics-365-unified-operations-public#524]
1.
"To encapsulate that action, you will create a new method on InventTable and name that method defaultMyInventLocationId."
should be changed to 
"To encapsulate that action, you will create a new method on InventTable and name that method myDefaultInventLocationId."
2.
last code line
"inventTable.defaultMyInventLocationId();"

should be changed to 
"inventTable.myDefaultInventLocationId();"

_Originally posted by @TrudAX in https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/issues/424#issuecomment-431422574_

**Comment by sericks007** [comment]
I re-activated GitHub issue 424.  So closing this one as a duplicate.
