### ISSUE TITLE
Upgrade vanilla 8.0 CU15 test cloud sandbox to 8.1

### ISSUE THREAD

**Issue by DynamicsArvindSingh** [MicrosoftDocs/dynamics-365-unified-operations-public#529]
Hi, 
I have a vanilla 8.0 CU15 test cloud sandbox, what will be the procedure to upgrade it to 8.1 considering the fact that there is no customized code/ Patches involved.

& please can you mention the exact name of the software deployable package to be considered for 8.1 upgrade?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b3b5ec6-1a21-e71a-df38-ba497f7f1116
* Version Independent ID: d1e49823-7934-6a3a-50e1-547cdd632077
* Content: [Update environments from version 8.0 to 8.1 - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/appupdate-80-81)
* Content Source: [articles/dev-itpro/migration-upgrade/appupdate-80-81.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/migration-upgrade/appupdate-80-81.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by ShylaThompson** [comment]
@laneswenka, can you respond?

**Comment by ShylaThompson** [comment]
reopening.

**Comment by laneswenka** [comment]
@DynamicsArvindSingh hello!  when you say 'test cloud sandbox' does that mean a "Sandbox: Standard Acceptance Test" environment from your LCS Project Homepage?  That would be also known as a Microsoft Managed Sandbox environment?

Or is this a cloud-hosted environment?

**Comment by DynamicsArvindSingh** [comment]
Yes it's a Sandbox: Standard Acceptance Test" environment from LCS Project Homepage.

**Comment by laneswenka** [comment]
@DynamicsArvindSingh got it, ok thank you.  Your process will be simpler, you can start at:
https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/appupdate-80-81#deploy-to-target-environments-for-validation

Once the package is available we will announce it on the LCS Blog and on the Docs article as well.

**Comment by DynamicsArvindSingh** [comment]
So what you are saying is software deployable package to be considered for 8.1 upgrade is not available yet?

**Comment by DynamicsArvindSingh** [comment]
Any timelines that we can expect for the availability?

**Comment by laneswenka** [comment]
That's correct, the article was updated to reflect the package hasn't been made available yet and our announcement was also updated.  Keep an eye on the LCS Blog to be notified when it drops:
https://blogs.msdn.microsoft.com/lcs/2018/10/09/dynamics-365-for-finance-and-operations-version-8-1-is-now-available/

**Comment by DynamicsArvindSingh** [comment]
Is there any other way to move to version 8.1 as in my case its vanilla, can i proceed with de-allocating the existing "Sandbox: Standard Acceptance Test" environment from LCS Project & re-configuring the environment? Please help me with the procedure involved along with the expected time lines.

**Comment by laneswenka** [comment]
Yes you can always deallocate, and then delete your sandbox environments and re-deploy on a new version.  This will delete the database entirely so any work you have there will be lost unless you make a backup prior.  Re-deploying the sandbox environment has the following ETA as explained in this article:
https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/submit-request-dynamics-service-engineering-team#service-request-types-and-slas

**Comment by laneswenka** [comment]
I believe your question to be answered, so I'll close #529 .  Let us know if you have any further questions.
