### ISSUE TITLE
Dropping users

### ISSUE THREAD

**Issue by rat-af** [MicrosoftDocs/dynamics-365-unified-operations-public#530]
Dropping user 'axdbadmin' is still an issue in running the 'Prepare the database' script.  I still have to run the following:

ALTER AUTHORIZATION ON schema::shadow TO [dbo]
ALTER AUTHORIZATION ON schema::[BACKUP] TO [dbo]

before all the users can be dropped successfully.  This needs to be done at the start like the full text catalog authorisation changes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3436fbc8-5bdd-dcdc-f5d3-51caf7b6cd76
* Version Independent ID: af78d3ef-b329-11e9-896a-aa3394f6c77c
* Content: [Copy Finance and Operations databases from Azure SQL Database to SQL Server environments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/copy-database-from-azure-sql-to-sql-server)
* Content Source: [articles/dev-itpro/database/copy-database-from-azure-sql-to-sql-server.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/database/copy-database-from-azure-sql-to-sql-server.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by laneswenka** [comment]
@rat-af this doesn't look like a standard requirement.  Are you using 3rd party tools with your Azure SQL database?

**Comment by rat-af** [comment]
No 3rd party tools been used. 
When I run the script in SSMS on the copy of the source database, I always get an error. 
I traced it to the need to perform those alter authorisation commands. The user axdbadmin will not drop from the source database until this happens. 
I should be able to copy the prepare script from the documentation, change the DB name in the script, then run it with no errors. 
That’s not the case in its current format, and it’s because the axdbadmin user can’t be dropped. 
The script needs to be altered in the documentation so no errors occur. New comers to the process could waste lots of time chasing down why the error is there otherwise.

**Comment by laneswenka** [comment]
Hi @rat-af I'm following up with our engineering teams as we have dozens of databases exported daily without this issue.  I'll let you know what I learn here very soon.
