### ISSUE TITLE
On Importing Tax (India GST) Configuration on newly created “SANDBOX: DEVELOP AND TEST” environment getting validation errors

### ISSUE THREAD

**Issue by DynamicsArvindSingh** [MicrosoftDocs/dynamics-365-unified-operations-public#531]
Hi,
I recently created a new “SANDBOX: DEVELOP AND TEST” environment with Application release: Microsoft Dynamics 365 for Finance and Operations (8.1) & Platform release: Update20 (7.0.5030.35333). On this new environment Tried to import the Tax (India GST)version 64.117.221 following above mentioned steps. 

On the Taxable Document (India) node system is throwing 2 Validation warnings:

"Model mapping: GST Registration Number-GST Registration Number/Data source/TaxRegistrationNumberByGST Using 'FILTER' function for the expression is preferable than 'WHERE' from the performance perspective. Click Fix button to replace it automatically."

&

"Model mapping: Party GST Registration Number-Party GST Registration Number/Data source/TaxRegisrationNumbersByPartyGST Using 'FILTER' function for the expression is preferable than 'WHERE' from the performance perspective. Click Fix button to replace it automatically."

The Fix button is disabled for both the Model mapping warnings. Can you please guide me, how to proceed further.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd0a287d-87e0-ad47-31c4-0bf8d485285c
* Version Independent ID: 338a84b7-c041-af9b-0e3f-70689c6157a0
* Content: [Tax engine import configuration - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/general-ledger/tax-engine-import-configuration)
* Content Source: [articles/financials/general-ledger/tax-engine-import-configuration.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/general-ledger/tax-engine-import-configuration.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @yijialuan
* Microsoft Alias: **riluan**

**Comment by ShylaThompson** [comment]
@RichardLuan, can you verify that the steps are correct in this document?

**Comment by yijialuan** [comment]
You can ignore these warnings, and we will release updated configuration to resolve the issue together with 8.1.2.
