### ISSUE TITLE
Extending the printer through Hardware Station 

### ISSUE THREAD

**Issue by neerajc870** [MicrosoftDocs/dynamics-365-unified-operations-public#532]
Can we extend the hardware station for existing hardware like printer to print something on runtime which is not a part of receipt layout designed in HQ ?
Regards,
Neeraj Chawla

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 5d3906b0-4ef0-3ee7-fb68-136442cff5c5
* Version Independent ID: 96819cbc-0e7b-7341-c534-d079387ef5b9
* Content: [Hardware Station extensibility - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/fr-fr/dynamics365/unified-operations/retail/dev-itpro/hardware-station-extensibility)
* Content Source: [articles/retail/dev-itpro/hardware-station-extensibility.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/dev-itpro/hardware-station-extensibility.md)
* Service: **dynamics-365-retail**
* GitHub Login: @RobinARH
* Microsoft Alias: **sijoshi**

**Comment by tonyafehr** [comment]
Thanks for contacting us. We will look into enhancing the documentation to provide the information that you're looking for. In the meantime, to get product help you can contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
