### ISSUE TITLE
How to Upgrade Data from NAV 2018 to Business Central Online

### ISSUE THREAD

**Issue by umang11** [MicrosoftDocs/dynamics-365-unified-operations-public#537]
I had migrated the code to AL extension and now i need to upgrade the data from Nav 2018 to Business Central as i didn't found any fruitfull information about this please help.

**Comment by sericks007** [comment]
Please see the Business Central documentation found here: https://docs.microsoft.com/en-us/dynamics365/business-central/index. Thanks!

**Comment by umang11** [comment]
Thanks for your reply,

But  already gone through the above Link but how i can upgrade my data from NAV 2018 to Business Central Online as my database is in Tera bytes please suggest.

**Comment by umang11** [comment]
> Please see the Business Central documentation found here: https://docs.microsoft.com/en-us/dynamics365/business-central/index. Thanks!

Thanks for your reply,

But already gone through the above Link but how i can upgrade my data from NAV 2018 to Business Central Online as my database is in Tera bytes please suggest.
