### ISSUE TITLE
ClickOnce support in Chrome

### ISSUE THREAD

**Issue by PalleAgermark** [MicrosoftDocs/dynamics-365-unified-operations-public#539]
In the first note, the text about the workflow editor says it will not run in Chrome because Chrome does not support ClickOnce applications. In the same note, on the line below, is says about the Report Designer for Financial reporting that it also wont work with Chrome because it is a ClickOnce application, unless you install an extension to Chrome. So here it is possible to make it work with Chrome. Would that also not be the solution for making the workflow designer work in Chrome? And are there any recommendations for which extension to pick (I can't find a few different, but none seems to be official or from Google or Microsoft)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48a9aeb7-1d83-3ea1-bc82-083c2c15c5eb
* Version Independent ID: 60294de4-5ff9-a757-6ace-63f59a6aab53
* Content: [System requirements for cloud deployments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/system-requirements#supported-web-browsers)
* Content Source: [articles/fin-and-ops/get-started/system-requirements.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/system-requirements.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @sericks007
* Microsoft Alias: **sericks**

**Comment by ChrisGarty** [comment]
I just updated the [System Requirements](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/system-requirements) page to clarify that if you're using Chrome, you must install a ClickOnce extension such as [Meta4](https://chrome.google.com/webstore/detail/meta4-clickonce-launcher/jkncabbipkgbconhaajbapbhokpbgkdc) to use ClickOnce applications.
Hope that helps!
