### ISSUE TITLE
Error on Rate shop

### ISSUE THREAD

**Issue by TabindaNaseem** [MicrosoftDocs/dynamics-365-unified-operations-public#540]
I am getting an error when clicking Rate shop on Rate Rote workbench. The error says "Unexpected error occurred when processing request. Please verify server event log or contact administrator."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de983399-5d89-7c92-3663-91de7b2f5a58
* Version Independent ID: 2b502fb3-764a-eeb0-7375-8a9b01472816
* Content: [Create a new transportation management engine - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/transportation/create-new-transportation-management-engine)
* Content Source: [articles/supply-chain/transportation/create-new-transportation-management-engine.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/transportation/create-new-transportation-management-engine.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @MarkusFogelberg
* Microsoft Alias: **mafoge**

**Comment by sericks007** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support).

**Comment by dferris87** [comment]
I received the same error. The TMSLabelProvider class in the TMSFwkRateEngineFactory::createRateEngine class method was throwing this error on a local Dev VM: "Could not find engine assembly 'ThirdPartyTMSEngines.dll' at 'C:\\AOSService\\PackagesLocalDirectory\\ApplicationSuite\\bin\\ThirdPartyTMSEngines.dll'." I moved the ThirdPartyTMSEngines DLL to the above directory and could see the expected result.
