### ISSUE TITLE
No need for Azure AD Account

### ISSUE THREAD

**Issue by JoPe72** [MicrosoftDocs/dynamics-365-unified-operations-public#548]
Hi...

In Create and configure a user account in Finance and Operations you say that we need to create an Azure AD account... has this changed? We have never had to create this. We have just created a "Dummy account" in Dynamics 365 and mapped to a Azure AD App registration. The WM App only uses the AppRegistration anyway... or am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24ad63f4-807c-fc88-58b6-33514bd034d0
* Version Independent ID: d727eb59-1162-f195-031a-5400301c8e5b
* Content: [Install and configure Microsoft Dynamics 365 for Finance and Operations – Warehousing - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/warehousing/install-configure-warehousing-app)
* Content Source: [articles/supply-chain/warehousing/install-configure-warehousing-app.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/warehousing/install-configure-warehousing-app.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @MarkusFogelberg
* Microsoft Alias: **mafoge**

**Comment by ShylaThompson** [comment]
@MarkusFogelberg Can you review this issue?

**Comment by sericks007** [comment]
Bug 266083 has been logged to track this issue.

**Comment by MarkusFogelberg** [comment]
You are correct that a Azure AD account is not needed for the F&O user in order for the app registration to work. The user associated with the Azure AD application just needs the user role of "Mobile device user". So it can indeed just be created with a "dummy" email if that is enough for you.

**Comment by JoPe72** [comment]
Thanks for the answer... I was just a bit worried that something had changed. The original article did not mention the Azure account :-)

Johan
