### ISSUE TITLE
Is this document really for D365 Finance and Operations?

### ISSUE THREAD

**Issue by pbonny1** [MicrosoftDocs/dynamics-365-unified-operations-public#551]
The options outlined in "Maintain a recording"  are quite different to those of my v8.1.
e.g. 2. Open the Task recorder pane. 3. Click Maintain a recording  - no such option.
Closest is Edit Recording, then options there are again different from this document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43b73341-9131-44c3-274a-457d2f355465
* Version Independent ID: b16bb9a6-01b9-7b5b-4e44-a7c7d2e208d4
* Content: [Task recorder - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/user-interface/task-recorder)
* Content Source: [articles/dev-itpro/user-interface/task-recorder.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/user-interface/task-recorder.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by tomhig** [comment]
This indeed is the Task Recorder for D365 Finance and Operations. However, the section noted, "Maintain a Recording"  is out of date. The screen shots shown in section titled "Screenshot extension setup" are also out of date.

**Comment by sericks007** [comment]
Bug 266084 is tracking this issue.

**Comment by josaw1** [comment]
BUG 437629 created.

**Comment by jasongre** [comment]
Update to bring this article up-to-date as of today have been made and are pending publish.
