### ISSUE TITLE
Error while applying package in business central

### ISSUE THREAD

**Issue by umang11** [MicrosoftDocs/dynamics-365-unified-operations-public#552]
i am getting th below error while applying the package data through configuration package.

![image](https://user-images.githubusercontent.com/12784260/47547427-108bbf00-d913-11e8-8c58-af9408af4db5.png)

**Comment by kfend** [comment]
Thanks for your feedback. This forum is for documentation issues only, please contact [Business Central support](https://community.dynamics.com/business/b/dynamics365financialssupport) for help.
