### ISSUE TITLE
Getting Permission error While uploading data into business central online through configuration package

### ISSUE THREAD

**Issue by umang11** [MicrosoftDocs/dynamics-365-unified-operations-public#553]
Getting Permission error While uploading data into business central online for all ledger and posted tables through configuration package please refer the below screenshot.

Please help!

![image](https://user-images.githubusercontent.com/12784260/47558584-1b554c80-d931-11e8-94a2-5764d4f49171.png)

**Comment by kfend** [comment]
Thanks for your feedback. This forum is for documentation issues only, please contact [Business Central support](https://community.dynamics.com/business/b/dynamics365financialssupport) for help.
