### ISSUE TITLE
Standardize code samples

### ISSUE THREAD

**Issue by SysC0mp** [MicrosoftDocs/dynamics-365-unified-operations-public#554]
The code samples often contain bad formatted or written code which do not take care of the X++ best practices. This is surely not good for new X++ developers.

Examples:
- Method access modifier should always start with lower-case. 
- Method parenthesis should not start with / end with simple blanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2b3708d-a8c1-612b-f4f3-9802ad0c5448
* Version Independent ID: d2f14c0f-b695-a234-53ef-864d8e243d14
* Content: [Class extension - Method wrapping and Chain of Command - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/extensibility/method-wrapping-coc)
* Content Source: [articles/dev-itpro/extensibility/method-wrapping-coc.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/extensibility/method-wrapping-coc.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @robadawy
* Microsoft Alias: **robadawy**

**Comment by tonyafehr** [comment]
@SysC0mp, thank you for making code examples updates. You updates have been approved and will be published later this week.
