### ISSUE TITLE
Table view broken

### ISSUE THREAD

**Issue by wruss** [MicrosoftDocs/dynamics-365-unified-operations-public#555]
Under "Data field ProcurementCategory" the formatting of the table is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 237cbfc2-4d7e-504d-91c5-df9c36c3fb70
* Version Independent ID: 8fc35097-03e4-2277-9be0-bc1ac3b1b75c
* Content: [Migrate default dimensions controls to Dimension Entry controls - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/financial/dimension-entry-control-migration#data-field-procurementcategory)
* Content Source: [articles/dev-itpro/financial/dimension-entry-control-migration.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/financial/dimension-entry-control-migration.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @ShylaThompson
* Microsoft Alias: **ghenriks**

**Comment by ShylaThompson** [comment]
@wruss Thanks for bringing this to our attention. I've fixed the table now.
