### ISSUE TITLE
When clicked 'Implementation process'  image does not auto-expand to full-page view

### ISSUE THREAD

**Issue by NatIFD** [MicrosoftDocs/dynamics-365-unified-operations-public#556]
Implementation process - the image is missing a link. Makes it harder to see the detail. 

    media/mobile-implementation-process-5.png

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0efc0aa-0cb4-1663-a721-4a8e3ed1f5db
* Version Independent ID: b35bd3ce-5dd9-5c5c-0538-5a987462d034
* Content: [Dynamics 365 for Unified Operations mobile app home page - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/mobile-apps/mobile-app-home-page?toc=/fin-and-ops/toc.json#implementation-process)
* Content Source: [articles/dev-itpro/mobile-apps/Mobile-app-home-page.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/mobile-apps/Mobile-app-home-page.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @sericks007
* Microsoft Alias: **sericks**

**Comment by sericks007** [comment]
Thanks for letting us know! I'll look into fixing this.

**Comment by sericks007** [comment]
I believe I have fixed this.  The updated article will be published later today.
