### ISSUE TITLE
Most of the text is in this article is in bold

### ISSUE THREAD

**Issue by PalleAgermark** [MicrosoftDocs/dynamics-365-unified-operations-public#562]
In the top of this article there seems to be some hick-ups with HTML tags, causing most of the document to be shown as if included in a "strong" tag.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f325f870-b30d-a45f-4f33-328a823dc460
* Version Independent ID: d57598d2-efc6-b775-81b6-b9669ea72c91
* Content: [X++ statements, loops, and exception handling - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-ref/xpp-statements-loops)
* Content Source: [articles/dev-itpro/dev-ref/xpp-statements-loops.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-ref/xpp-statements-loops.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RobinARH
* Microsoft Alias: **robinr**

**Comment by tonyafehr** [comment]
Thanks for pointing this out, @PalleAgermark. I'll look at the formatting and make the needed corrections.

**Comment by danimaciasperea** [comment]
Issue is closed but HTML tags are still wrong and text is in bold.

**Comment by tonyafehr** [comment]
We will publish the updates later today.
