### ISSUE TITLE
Accessing developer downloaded VM on local network

### ISSUE THREAD

**Issue by rat-af** [MicrosoftDocs/dynamics-365-unified-operations-public#565]
Hi,
   Up until now, I've only used cloud based VM's.  I've recently downloaded a developer VM and placed in on our network.  I can successfully connect to the VM using my own credentials, and run D365FO on the VM.  However, I want to be able to run that instance of D365FO from a browser on our network (ie: on my PC, not in the VM), that way other users testing any changes can do this without logging onto the VM.  However, this document does not detail this.   I first get an indication that the site is not secure, then I get a page not found error (404) when I choose to proceed.  I suspect that I am missing the certificates for the VM, but the document does not detail what certificates are required to be imported into the local browser. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae28fb1e-25a4-72cd-6694-322bec60769e
* Version Independent ID: 461c7a2b-ce3f-4083-af9d-07093dbed387
* Content: [Deploy and access development environments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-tools/access-instances)
* Content Source: [articles/dev-itpro/dev-tools/access-instances.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-tools/access-instances.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @robadawy
* Microsoft Alias: **robadawy**

**Comment by sericks007** [comment]
Thanks for letting us know! We'll look into adding the information you suggested.

**Comment by sericks007** [comment]
Bug 266089 is tracking this issue.

**Comment by robadawy** [comment]
We do not officially support this scenario. The AOS is a standard web application. If you need to enable access to a local VM via the browser, you are an administrator on the box and have access to configure as you wish, including security.
