### ISSUE TITLE
AxRunner is named DAXRunnerUser@DAXMDSRunner.com on our system

### ISSUE THREAD

**Issue by steevegilbert** [MicrosoftDocs/dynamics-365-unified-operations-public#568]
If you add the real name of the account like "DAXRunnerUser" it will be picked up by the search engine and be easier to find.  I search for "DAXRunnerUser" and never got to this page.  Someone had to point me to it.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8638cab7-c759-2e78-e5bb-ba0228f141df
* Version Independent ID: 58f113b5-493d-2d83-5dac-7c8376296ab6
* Content: [Preconfigured system accounts - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/sysadmin/pre-configured-system-accounts)
* Content Source: [articles/dev-itpro/sysadmin/pre-configured-system-accounts.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/sysadmin/pre-configured-system-accounts.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @manalidongre
* Microsoft Alias: **manado**

**Comment by sericks007** [comment]
@steevegilbert,  Thanks for letting us know!

@manalidongre, Can we change the "Axrunner" reference in this article to "DAXRunnerUser"?

**Comment by sericks007** [comment]
Bug 266093 is logged to track this issue.

**Comment by manalidongre** [comment]
The name of the user is AXRunner in the product and hence will leave it that way.
