### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by MichaelFruergaardPontoppidan** [MicrosoftDocs/dynamics-365-unified-operations-public#573]
Typo here - the last 'd':
Signature must remain compatibled

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e30c0f8e-ffc8-0749-9195-1d16cc365b08
* Version Independent ID: bddc439e-a102-63cd-d695-598f0f9d1c8a
* Content: [Attributes that make methods extensible - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/extensibility/extensibility-attributes)
* Content Source: [articles/dev-itpro/extensibility/extensibility-attributes.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/extensibility/extensibility-attributes.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @MichaelFruergaardPontoppidan
* Microsoft Alias: **mfp**

**Comment by tonyafehr** [comment]
@MichaelFruergaardPontoppidan, thanks for pointing this out. I'll make sure that this gets fixed.
