### ISSUE TITLE
Schema BOYD

### ISSUE THREAD

**Issue by kurthatlevik** [MicrosoftDocs/dynamics-365-unified-operations-public#575]
Our experience in Dynamics 365 V8 shows that the DB schema must be 'dbo', or else the export to BOYD is not working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cd981b1-0ed1-34c8-d22a-e1c6d194ff9c
* Version Independent ID: 1e26cccc-eab2-e170-7004-98585128e3e1
* Content: [Bring your own database (BYOD) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/export-entities-to-your-own-database)
* Content Source: [articles/dev-itpro/analytics/export-entities-to-your-own-database.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/export-entities-to-your-own-database.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by sericks007** [comment]
Bug 270384 has been logged to track this issue.

**Comment by tonyafehr** [comment]
This issue has been resolved and the topic will be updated today to reflect these changes. Thank you!
