### ISSUE TITLE
Windows 10 IoT Enterprise on MPOS

### ISSUE THREAD

**Issue by tomhig** [MicrosoftDocs/dynamics-365-unified-operations-public#579]
Retail MPOS for Windows requirements need to be updated to include Windows 10 IoT Enterprise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48a9aeb7-1d83-3ea1-bc82-083c2c15c5eb
* Version Independent ID: 60294de4-5ff9-a757-6ace-63f59a6aab53
* Content: [System requirements for cloud deployments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/system-requirements#retail-modern-pos-for-windows-requirements)
* Content Source: [articles/fin-and-ops/get-started/system-requirements.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/system-requirements.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @sericks007
* Microsoft Alias: **sericks**

**Comment by tonyafehr** [comment]
@tomhig, thank you for your comment. 
@jashanno, can you review, thanks!

**Comment by sericks007** [comment]
Bug 270382 has been logged to track this issue.

**Comment by jashanno** [comment]
Updates are coming soon to include this in the listings.

**Comment by sericks007** [comment]
The updated topic has been published, so closing this issue.
