### ISSUE TITLE
Triangulation currency parameter

### ISSUE THREAD

**Issue by SabinaFazal** [MicrosoftDocs/dynamics-365-unified-operations-public#580]
Can you let me know if using the triangulation currency feature works with the changes regarding dual currency? Are two sets of exchange rates required to be set up still? I am undergoing some testing at the moment and am finding that the triangulation currency parameter now does not work with this and would like some clarification.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ccd8e83-b132-ac2d-67b0-76f6f96dff05
* Version Independent ID: 399a2cc0-0a02-fdc2-a463-6c19c3897892
* Content: [Dual currency - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/general-ledger/dual-currency#feedback)
* Content Source: [articles/financials/general-ledger/dual-currency.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/general-ledger/dual-currency.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @kweekley
* Microsoft Alias: **kweekley**

**Comment by kweekley** [comment]
@SabinaFazal - There were no intended changes to the triangulation functionality. If you are seeing issues, please contact support with the necessary repro steps.
