### ISSUE TITLE
User account + Which asset library to use

### ISSUE THREAD

**Issue by MZade** [MicrosoftDocs/dynamics-365-unified-operations-public#582]
Hi, Two points I found out today:
- It is important to logon to both d365fo application as well as LCS using the same account;
- It seems also that when you do not define the lcsProjectId in the input XML file, the test framework is going to use the Shared Asset Library and as a matter of fact only the files with "Scope equal to Global" are currently available. To use your own data packages, you should provide the lcsProjectId;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a1cb5a1-742b-580e-0866-8ad52eaec61e
* Version Independent ID: cf55462f-c2d2-81d8-c50d-66490331fb65
* Content: [Data task automation - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/data-task-automation)
* Content Source: [articles/dev-itpro/data-entities/data-task-automation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/data-task-automation.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by tonyafehr** [comment]
@MZade, thanks for the feedback. 
@Sunil-Garg, please review these comments.

**Comment by tonyafehr** [comment]
Bug 268063 has been logged to track this issue.

**Comment by Sunil-Garg** [comment]
Mzade-- the fact about using the same account in both F&O and LCS is already mentioned. Also, the data packages in the shared asset library works with the non-global scope as well. Let's connect offline if you are still seeing this behavior.
