### ISSUE TITLE
Old Screenshot of PowerBI Configuration in this Document

### ISSUE THREAD

**Issue by BernhardRaether** [MicrosoftDocs/dynamics-365-unified-operations-public#584]
Using this document, we tried to get the PowerBI confugiration set up.
Instead of two fields to fill out (ApplicationID and ApplicationKey) we have a different Layout, requiring seven fiels to be filled in
-Azure AD Authority URI
- Azure AD PowerBI resource URI
- AZURE AD Tenant
- ClientID
- Application Key
- Redirect URL
- PowerBI API Address

unknown what to fill in.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 717d397d-4186-c7de-431d-3260d3f0484a
* Version Independent ID: bdd7545b-5970-93e0-5cbb-a59da4ace01b
* Content: [Configure Power BI integration for workspaces - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/configure-power-bi-integration)
* Content Source: [articles/dev-itpro/analytics/configure-power-bi-integration.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/configure-power-bi-integration.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by sericks007** [comment]
@BernhardRaether, thanks for making us aware of this!  We'll investigate.

@TJVass, does this article (and a screen shot) need to be updated?

**Comment by TJVass** [comment]
This customer must be still using a PU15 or earlier build.  This form was significantly simplified in PU18.

-TJ

**Comment by sericks007** [comment]
Bug 268462 is tracking this issue.

**Comment by TJVass** [comment]
YES - for those customers using PU15 or earlier, you'll need to provie a few more settings to connect D365F&O to your PowerBI.com subscription.  Here is a description of the settings used in the PowerBI.com configuration form for customer using **PU15 or before**:

**Authorization URI** -> "​https://login.windows.net"
​AAD authorization address.

​**Resource ID** -> "​https://analysis.windows.net/powerbi/api"
​​The Resource URI for Power BI API.

​**Tenant ID** ->  {Your tenant ID}
​This is the Azure AD tenant for the application. As such, the accounts used for these environments must reside in this tenant. One such account is: administrator@contosoax7.onmicrosoft.com

​**Application ID** -> {Your Application ID}
The unique identifier created in Azure Portal for your application. 

​**Application Key** -> {Your Application Key}
​Secret Key value created in Azure Portal when registering the application.

​**Reply URL** -> "https://{Your D365 Service URL}/oauth"
​Physical address for your app including the "/oauth" postfix to which Windows Azure AD will send SAML authentication tokens for authenticated users.

**​Power BI API Address** -> "​https://api.powerbi.com/beta/myorg/"
​Power BI production API URI

Sorry, about the confusion.  I hope this helps...!

**Comment by BernhardRaether** [comment]
Hello TJ,

Thanks for the explanation, will configure it with these parameters.

Hope it helps making the existing Docs even more useful 😉

Thanks again,
Regards,

Bernhard Räther
Senior Consultant
Inway Systems GmbH
[phone]               +49 -731-880073-12
[mobile]              +49-174-2411625
Inway Systems – BUSINESS. SOFTWARE. EXCELLENCE.

Von: TJ Vassar <notifications@github.com>
Gesendet: Donnerstag, 15. November 2018 22:20
An: MicrosoftDocs/dynamics-365-unified-operations-public <dynamics-365-unified-operations-public@noreply.github.com>
Cc: Bernhard Räther <Bernhard.Raether@inway.de>; Mention <mention@noreply.github.com>
Betreff: Re: [MicrosoftDocs/dynamics-365-unified-operations-public] Old Screenshot of PowerBI Configuration in this Document (#584)


YES - for those customers using PU15 or earlier, you'll need to provie a few more settings to connect D365F&O to your PowerBI.com subscription. Here is a description of the settings used in the PowerBI.com configuration form for customer using PU15 or before:

Authorization URI -> "​https://login.windows.net"
​AAD authorization address.

​Resource ID -> "​https://analysis.windows.net/powerbi/api"
​​The Resource URI for Power BI API.

​Tenant ID -> {Your tenant ID}
​This is the Azure AD tenant for the application. As such, the accounts used for these environments must reside in this tenant. One such account is: administrator@contosoax7.onmicrosoft.com<mailto:administrator@contosoax7.onmicrosoft.com>

​Application ID -> {Your Application ID}
The unique identifier created in Azure Portal for your application.

​Application Key -> {Your Application Key}
​Secret Key value created in Azure Portal when registering the application.

​Reply URL -> "https://{Your D365 Service URL}/oauth"
​Physical address for your app including the "/oauth" postfix to which Windows Azure AD will send SAML authentication tokens for authenticated users.

​Power BI API Address -> "​https://api.powerbi.com/beta/myorg/"
​Power BI production API URI

Sorry, about the confusion. I hope this helps...!

**Comment by taral1311** [comment]
Click Settings > Required permissions > Add > Select an API > Power BI Service (Power BI).

Not able to find the setting in app registration in the azure portal.

**Comment by lachicazul** [comment]
@taral1311 now you have to click on View API Permissions in the Overview area.
