### ISSUE TITLE
Copy database from D365FO 8.0 to 8.1 environment

### ISSUE THREAD

**Issue by ThomasBoehret** [MicrosoftDocs/dynamics-365-unified-operations-public#585]
Hi,
is it possible to copy a database from a source environment with application version 8.0 to a target environment with  application Version 8.1? As there is no data upgrade require according to the upgrade path, we hope so.
 Thanks! 
Thomas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b3b5ec6-1a21-e71a-df38-ba497f7f1116
* Version Independent ID: d1e49823-7934-6a3a-50e1-547cdd632077
* Content: [Update environments from version 8.0 to 8.1 - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/appupdate-80-81)
* Content Source: [articles/dev-itpro/migration-upgrade/appupdate-80-81.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/migration-upgrade/appupdate-80-81.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by sericks007** [comment]
Thanks for contacting us. @laneswenka, can you look into enhancing the documentation to provide the information that @ThomasBoehret  is looking for. 

In the meantime, to get product help you can contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

**Comment by laneswenka** [comment]
Hi all, I will review today

**Comment by sericks007** [comment]
Bug 268464 is tracking this issue.

**Comment by laneswenka** [comment]
Hi @ThomasBoehret you will be able to do this using the Export and Import functionality which is currently in Private Preview.  As soon as this is released I will update the issue with the link to the updated docs.

For now, you can manually import the 8.0 database in to your 8.1 environment and run a dbsync.  That will just work, it is the automated actions we are adding to LCS that won't be there just yet.

**Comment by ThomasBoehret** [comment]
Hi @laneswenka, the question is more, if it is supported to import a database from a source Environment with Version 8.0 to a target Environment with version 8.1 without any data upgrade procedure (as there seem to be no differences in the data model of the database between the two versions). Of Course we are able to Export and Import the database manually.

**Comment by laneswenka** [comment]
@ThomasBoehret this is supported and our tooling for Export and Import via LCS will allow for this.  The Refresh operation between PROD->Sandbox will not work as we have checks in place to ensure the source/target are the same version.  If you are looking to perform data validation as part of the update process then perform the Refresh prior to applying the 8.1 update.
