### ISSUE TITLE
Import or manually create postal codes

### ISSUE THREAD

**Issue by VavaniSarmah** [MicrosoftDocs/dynamics-365-unified-operations-public#586]
This is one of the lowest quality guidance/instructions/help I have ever seen in MS blog is offering regarding Dynamics 365F&O. Contributor is knowingly or unknowingly misleading the community. There is no co-relation between the contents as stated in this blog "Import ZIP/postal codes" with real work to be done if any one wanted to import USA Zip code to Dynamics 365 F&O.  I suggest contributor to put it down or/and try yourself to import USA Zip code/postal codes to Dynamics 365F&O and see if you can follow your blog and import it!!! This blog should/must be modified as soon as possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c87cdf04-f506-4d3b-aefa-0983eb5699cd
* Version Independent ID: 294881af-ec4d-86d3-d233-8be9067b8559
* Content: [Import or manually create postal codes - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/localizations/emea-import-create-postal-codes-manually)
* Content Source: [articles/financials/localizations/emea-import-create-postal-codes-manually.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/localizations/emea-import-create-postal-codes-manually.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @EvgenyPopovMBS
* Microsoft Alias: **epopov**

**Comment by sericks007** [comment]
@VavaniSarmah, thank you for submitting your feedback.

@EvgenyPopovMBS, please look into updating this topic based on the feedback.

**Comment by EvgenyPopovMBS** [comment]
Thanks, we will look at this.
Just one comment for now: the article is located in the Localization and regulatory features folder for Europe, and thus is not supposed to cover the procedure for the USA.

**Comment by VavaniSarmah** [comment]
@EvgenyPopovMBS and @sericks007 - your comments are still not the answer that community is looking for. Let me ask you straight - Can you point me to an article that is explaining how to import USA zipcode into dynamics 365 Finance and Operation or do you know if is there any relevant article on this?

**Comment by VavaniSarmah** [comment]
I found a solution and able to import USA Zipcode into Dynamics 365 F& O
[Steps to import USA Zipcode into D365FO.pdf](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/files/2602847/Steps.to.import.USA.Zipcode.into.D365FO.pdf)
. Explaining the steps below - 

**Pre-requisite**
A.	A.	Make sure that you have the list USA States already created in the system.  (I have another process to import all the states if you don’t want to create manually)
B.	Download the USA ZipCode list from reliable source (I downloaded from here www.pier2pier.com/links/files/Countrystate/USA-Zip.xls) – (Because USA has about 74000 zipcode, I split the downloaded excel file into two smaller files.)
C.	Also I did little modification to the excel file as shown below. Keep only following four columns - ZipCode -City Name - StateCode - CountryName. 

**Now, goto D365F&O Data Management**

Step 1: Create an Import Process (Name like ImportUSAZipCode") under D365F&O "Data Management"
Step 2: Source data format as "Excel"
Step3: Entity name as "Postal codes V3" - which is "LogisticsAddressPostalCodeV3Entity" in D365F&)
Step 4: Keep "Use sample file" option ON
Step 5: Keep "Skip staging" option ON
Step 6: Select "Skip staging = "Full push only"
Step 7:  Keep "Truncate entity data" option as "NO"
Step 8: Select Upload import files - select your ZipCode file that you downloaded as stated in step B above
Step 9: Once uploaded the file Click "View Map" and make sure mapping correct as follows
         9.a.  City -->CityID
         9.b. County -->CountryRegion
         9.c.  State --> StateID
         9.d. ZipCode -->ZipCode
         (At this point if you want you can save the mapping)

         (At this point if you want you can save the mapping)

Step 10: Once mapping is done, click "Import" menu item in the menu bar
Step 11: If successful, you should see Zipcode data in the staging table
Step 12: Click “View Staging Data” 
Step 13: Click “Validate all” to validate the Staging data - Make sure all the rows validated correctly
Step 14: Click "Copy data to Target" menu item in the menu bar. You should see pop-up on your    
              right hand screen.
Step 15: Click "OK"
Step 16: Click "Run" menu item in the menu bar to run the process (ImportUSAZipCode)
 
[Steps to import USA Zipcode.pdf](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/files/2602842/Steps.to.import.USA.Zipcode.pdf)

I did it myself following these steps and is working. If anybody needs any more information, please feel free to contact me at microsoftblue@gmail.com
