### ISSUE TITLE
Extending an existing table Incorrect fields

### ISSUE THREAD

**Issue by ansartroops** [MicrosoftDocs/dynamics-365-unified-operations-public#587]
As provided in the example for RetailTransactionTable fields given as ISB2BSALES and EXTERNALID, where as in enabling Custom CDX  fields given as SeatNumber and ServerStaffId, which is wrong. as in the sample extensions it's given as ContosoRetailSeatNumber and ContosoRetailServerStaffId, Both documents needs to be updated correctly.
https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/dev-itpro/cdx-extensibility

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: caa0202f-ca6c-6d04-fe09-628f828aabd0
* Version Independent ID: 74ef8e7d-32e7-d05f-cfd0-531bc921dc9d
* Content: [Channel database extensions - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/dev-itpro/channel-db-extensions#extending-an-existing-table)
* Content Source: [articles/retail/dev-itpro/channel-db-extensions.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/dev-itpro/channel-db-extensions.md)
* Service: **dynamics-365-retail**
* GitHub Login: @mugunthanm
* Microsoft Alias: **mumani**

**Comment by kfend** [comment]
Thanks for the feedback. We have updated the topics and will publish the changes shortly.
