### ISSUE TITLE
Does these accounts required license?

### ISSUE THREAD

**Issue by maheshambati410** [MicrosoftDocs/dynamics-365-unified-operations-public#588]
Do we need to purchase license for all these accounts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8638cab7-c759-2e78-e5bb-ba0228f141df
* Version Independent ID: 58f113b5-493d-2d83-5dac-7c8376296ab6
* Content: [Preconfigured system accounts - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/sysadmin/pre-configured-system-accounts)
* Content Source: [articles/dev-itpro/sysadmin/pre-configured-system-accounts.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/sysadmin/pre-configured-system-accounts.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @manalidongre
* Microsoft Alias: **manado**

**Comment by kfend** [comment]
@manalidongre - Can you answer this licensing question?

**Comment by sericks007** [comment]
Bug 269635 is tracking this issue.

**Comment by manalidongre** [comment]
No. You do not need licenses for these accounts.
