### ISSUE TITLE
Retail Cloud Scale Unit

### ISSUE THREAD

**Issue by praveenzp** [MicrosoftDocs/dynamics-365-unified-operations-public#589]
There is little to no information available on the docs website on setting up the Retail Cloud Scale Unit. Can this also be covered in the upcoming docs updates?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e22c3ec-f761-f9fe-0dae-2e3f45779301
* Version Independent ID: a2e0f995-5ecf-2544-cf88-f6b441a512bd
* Content: [Retail for IT pros and developers home page - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/dev-itpro/dev-retail-home-page)
* Content Source: [articles/retail/dev-itpro/dev-retail-home-page.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/dev-itpro/dev-retail-home-page.md)
* Service: **dynamics-365-retail**
* GitHub Login: @RobinARH
* Microsoft Alias: **robinr**

**Comment by josaw1** [comment]
Thank you for your comment. We're currently working on the documentation for Retail Cloud Scale Unit and will publish it as soon as we can.

**Comment by sericks007** [comment]
Bug 269637 is tracking this issue.

**Comment by tonyafehr** [comment]
We're closing this issue as resolved, thank you!
