### ISSUE TITLE
Mixing up trade agreements and sales agreements

### ISSUE THREAD

**Issue by vavd** [MicrosoftDocs/dynamics-365-unified-operations-public#594]
Why did you mix up sales and trade agreements by putting trade agreements under sales agreements section? Actually that is very different functionality.
Yes, it's possible to set the price for exact customer by using sales agreements or trade agreements.
But in fact, the purpose of this two options is different. It's very confusing when you mix them the way you did.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 322c2b3a-1716-96a4-de26-7f68b2558035
* Version Independent ID: 2353cddb-c330-bfb7-87fe-00a20780589b
* Content: [Create a new trade agreement - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/sales-marketing/tasks/create-new-trade-agreement)
* Content Source: [articles/supply-chain/sales-marketing/tasks/create-new-trade-agreement.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/sales-marketing/tasks/create-new-trade-agreement.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @omulvad
* Microsoft Alias: **omulvad**

**Comment by ShylaThompson** [comment]
@vavd, Thanks for taking the time to provide feedback! I'll revisit the table of contents organization for this section. Where did you first expect to see the Trade agreements topic in the table of contents?

**Comment by vavd** [comment]
@ShylaThompson, thanks for the quick response.
I think it should be organized the similar way as it is in the D365FO navigation pane.
![image](https://user-images.githubusercontent.com/1788418/48354859-c8ef8c00-e6a3-11e8-9262-31968d8ca55d.png)

It seems this doc lacks information regarding trade agreements except this page. But there is a lot of info in the PDF available in the [link](https://mbs.microsoft.com/files/public/CS/AX2012R3/TradeagreementsinAX.pdf).

**Comment by ShylaThompson** [comment]
@vavd apologies for my delayed response. I've moved the trade agreements topic in the TOC and am reviewing the white paper you linked to. My hope is that we'll have the content in the white paper verified for Finance and Operations and migrated to Docs.microsoft.com in the near future.

**Comment by ShylaThompson** [comment]
The TOC entry has been moved. The white paper is planned for review for migration.
