### ISSUE TITLE
Is there a date for Incremental Refresh?

### ISSUE THREAD

**Issue by RobvanB** [MicrosoftDocs/dynamics-365-unified-operations-public#595]
When will incremental refresh of the entity store be available? (Or even better, direct streaming) ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd3a076-d364-f4e8-fe37-f10c77a75466
* Version Independent ID: 0f767e21-3f33-2139-0931-7cd044c81b9f
* Content: [Power BI integration with Entity store - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/power-bi-integration-entity-store)
* Content Source: [articles/dev-itpro/analytics/power-bi-integration-entity-store.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/power-bi-integration-entity-store.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by ShylaThompson** [comment]
@RobvanB thanks for your comment. We publish planned features in our [Release notes](https://docs.microsoft.com/en-us/business-applications-release-notes/October18/dynamics365-finance-operations/planned-features). If you don't see it as a planned feature, please suggest it on the [Ideas site](https://experience.dynamics.com/ideas/list/?forum=16691718-61e2-e611-8101-5065f38b21f1). If you submit it on the Ideas site, you will receive notifications, you can vote, and you can monitor the progress of your idea more closely.
