### ISSUE TITLE
Import .bacpac file gives error Unable to connect to master or target server 'AXDB_Copy'. You must have a user with the same password in master or target server 'AXDB_Copy'.

### ISSUE THREAD

**Issue by burakuygur** [MicrosoftDocs/dynamics-365-unified-operations-public#603]
Hi
While importing .bacpac file to local VM machine's SQL server. It gives this error message :

Unable to connect to master or target server 'AXDB_Copy'. You must have a user with the same password in master or target server 'AXDB_Copy'. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3436fbc8-5bdd-dcdc-f5d3-51caf7b6cd76
* Version Independent ID: af78d3ef-b329-11e9-896a-aa3394f6c77c
* Content: [Copy Finance and Operations databases from Azure SQL Database to SQL Server environments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/copy-database-from-azure-sql-to-sql-server)
* Content Source: [articles/dev-itpro/database/copy-database-from-azure-sql-to-sql-server.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/database/copy-database-from-azure-sql-to-sql-server.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by tonyafehr** [comment]
Thanks for contacting us. @laneswenka, can you look into enhancing the documentation to provide the information that @burakuygur is looking for. 

In the meantime, to get product help you can contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

**Comment by laneswenka** [comment]
Hi @burakuygur can you provide the import command you used with SQLPackage.exe?  Based on your error message it sounds like you set the /tsn:AXDB_Copy but that should instead be localhost.  Want to confirm the /tdn: is set also to a database name that doesn't exist already on the local VM.

**Comment by sericks007** [comment]
Bug 270369 has been logged to track this issue.

**Comment by laneswenka** [comment]
Not able to reproduce, please provide more details or we will mark this as resolved
