### ISSUE TITLE
Way too basic

### ISSUE THREAD

**Issue by 3DFO** [MicrosoftDocs/dynamics-365-unified-operations-public#606]
Unfortunately this functionality is very limited. There is no link between hubs and customers, warehouses, vendors etc. The system therefore cannot dynamically route loads that contain multiple sales orders and addresses. A route plan and guide must exist. route plans are fine for pre-defined routes where all segments are always used but that's about it. Predefined routes when certain stops are not always used have to be manually edited. Loads that contain multiple orders cannot be dynamically routed into multiple segments. a route must be manually entered.  Also if you use scheduled routes, the system can only assign one load to a scheduled route. If the truck is too small and an additional truck is needed, a new route with multiple segments must be manually created. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acec702b-6e9b-83cc-f3ad-1b1d10d7cc92
* Version Independent ID: 02dd253e-8015-16d4-26ab-46e3ff04a626
* Content: [Plan freight transportation routes with multiple stops - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/transportation/plan-freight-transportation-routes-multiple-stops)
* Content Source: [articles/supply-chain/transportation/plan-freight-transportation-routes-multiple-stops.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/transportation/plan-freight-transportation-routes-multiple-stops.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @MarkusFogelberg
* Microsoft Alias: **mafoge**

**Comment by josaw1** [comment]
Thank you for your comment. We've shared this feedback with the engineering team.

**Comment by MarkusFogelberg** [comment]
Thank you for the feedback. Dynamic routing is not supported by the product today, but it is a great suggestion. I would ask you to also post your feedback on Ideas portal.

**Comment by ShylaThompson** [comment]
@3DFO here is a link to the ideas portal: https://experience.dynamics.com/ideas/
