### ISSUE TITLE
Connection details to Azure SQL

### ISSUE THREAD

**Issue by AndersDahlin** [MicrosoftDocs/dynamics-365-unified-operations-public#607]
A good note that I did not see and for people not used to Azure SQL is that you need to use the syntax &lt;server&gt;.database.windows.net  when connecting to Azure SQL with the SQL manager tool. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3436fbc8-5bdd-dcdc-f5d3-51caf7b6cd76
* Version Independent ID: af78d3ef-b329-11e9-896a-aa3394f6c77c
* Content: [Copy Finance and Operations databases from Azure SQL Database to SQL Server environments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/copy-database-from-azure-sql-to-sql-server)
* Content Source: [articles/dev-itpro/database/copy-database-from-azure-sql-to-sql-server.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/database/copy-database-from-azure-sql-to-sql-server.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by laneswenka** [comment]
I will take a look at this today!

**Comment by sericks007** [comment]
Bug 270379 has been logged to track this issue.

**Comment by laneswenka** [comment]
This was resolved with the release of Self-service Export
