### ISSUE TITLE
Only dbo schema supported in BYOD SQL DB

### ISSUE THREAD

**Issue by sriling** [MicrosoftDocs/dynamics-365-unified-operations-public#609]
Please add under this docs page (https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/export-entities-to-your-own-database ) under known limitation section that on dbo schema usage is supported in the BYOD SQL DB (https://dynamics.wiki/index.php/DMF:_BYOD_could_not_generate_package_file)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cd981b1-0ed1-34c8-d22a-e1c6d194ff9c
* Version Independent ID: 1e26cccc-eab2-e170-7004-98585128e3e1
* Content: [Bring your own database (BYOD) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/export-entities-to-your-own-database)
* Content Source: [articles/dev-itpro/analytics/export-entities-to-your-own-database.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/export-entities-to-your-own-database.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by josaw1** [comment]
Thanks for your comment. I've forwarded this on to the author. Check back for his response.

**Comment by sericks007** [comment]
Bug 270371 has been logged to track this issue.

**Comment by Sunil-Garg** [comment]
Thanks for mentioning this update. We are actually working to bring back the old behavior where non-dbo schemas were working. We will hold off on updating this doc since the work is getting completed as we speak.

**Comment by ShylaThompson** [comment]
@sriling I'm going to close this issue because we won't be making the change to the topic due to current work in progress.

**Comment by steevegilbert** [comment]
For those that need a quick fix : apparently you just need to make sure the table exists in the dbo schema also.  The export will still push the data to you non-dbo table.

**Comment by UmeshPandit** [comment]
How to implement AD authentication on BYOD in Microsoft Dynamic 365
