### ISSUE TITLE
Retail support

### ISSUE THREAD

**Issue by OksanaKovaliova** [MicrosoftDocs/dynamics-365-unified-operations-public#613]
Note: Retail Server is not supported in on-premises deployments at this time - is it still valid? On-premises retail was released some weeks ago

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37b1b122-d4e8-3f49-fdf2-9a830d3ca7c1
* Version Independent ID: 7dcd2c3a-f8de-249d-a84f-329bca14d21f
* Content: [On-premises deployment option - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/deployment/on-premises-overview)
* Content Source: [articles/dev-itpro/deployment/on-premises-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/deployment/on-premises-overview.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @kfend
* Microsoft Alias: **arifk**

**Comment by sericks007** [comment]
@OksanaKovaliova, thanks for making us aware of this!

@AamirAllaq, please review this issue and update the topic appropriately.

**Comment by sericks007** [comment]
This topic has been updated.  The updated topic will be published later today.
