### ISSUE TITLE
8.1 deployable packages

### ISSUE THREAD

**Issue by OksanaKovaliova** [MicrosoftDocs/dynamics-365-unified-operations-public#614]
Hi, in 8.1 environment we do not see any standard packages in 'Create deployable package' form. Is it a design change in 8.1? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 999db527-ff3d-1370-dfc3-7d8a196eaeed
* Version Independent ID: 5b9776d6-3b1d-7b07-6a5e-0153505d31b9
* Content: [Create deployable packages of models - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/deployment/create-apply-deployable-package)
* Content Source: [articles/dev-itpro/deployment/create-apply-deployable-package.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/deployment/create-apply-deployable-package.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @robadawy
* Microsoft Alias: **robadawy**

**Comment by sericks007** [comment]
Bug 270372 has been logged to track this issue.

**Comment by beautifullmind** [comment]
This is by design, In 8.1, regular packages such as application suite will not be available in the Deployment packages form. any individual hotfix will need to be applied in development environment, then use the build environment to create the deployable package that can be applied to other environments such as UAT.

**Comment by robadawy** [comment]
As of 8.1, there is never a need to create a deployable package that includes application suite (whether in development or build environment) as the only customization model that is supported are extensions.
