### ISSUE TITLE
8.1

### ISSUE THREAD

**Issue by OksanaKovaliova** [MicrosoftDocs/dynamics-365-unified-operations-public#615]
Hi, was x++ hotfix installation process changed in 8.1? 
We cannot see standard packages in 'Create deployment package' anymore, so we assume that x++ hotfixes are not merged anymore... New process description will be high appreciated! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66b4c899-c7e0-0406-0d39-d32fc41b6104
* Version Independent ID: 5d015069-177d-e33c-094c-257df088a7c0
* Content: [Install metadata hotfixes in development environments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/install-metadata-hotfix-package)
* Content Source: [articles/dev-itpro/migration-upgrade/install-metadata-hotfix-package.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/migration-upgrade/install-metadata-hotfix-package.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RobinARH
* Microsoft Alias: **robadawy**

**Comment by sericks007** [comment]
Bug 270373 has been logged to track this issue.

**Comment by kfend** [comment]
Hi, 
Version 8.1 does not support X++ hotfixes. Only cumulative binary updates are supported. For more information, please see the topic, [Get updates from Lifecycle Services](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/download-hotfix-lcs).
