### ISSUE TITLE
Loyalty Program in retail

### ISSUE THREAD

**Issue by Ecoent** [MicrosoftDocs/dynamics-365-unified-operations-public#616]
Over-engineered, nothing working module!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9b0202d-3339-d783-9c2a-279d2828675f
* Version Independent ID: 27bf2e48-23bd-c1b2-0826-27aa95e18b1f
* Content: [Define loyalty schemes - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/tasks/define-loyalty-schemes)
* Content Source: [articles/retail/tasks/define-loyalty-schemes.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/tasks/define-loyalty-schemes.md)
* Service: **dynamics-365-retail**
* GitHub Login: @jashanno
* Microsoft Alias: **jashanno**

**Comment by Ecoent** [comment]
can i just re-do everything?
I just want to try a Loyalty program for retail online first! (then offline).
Tried everything as per the documents.
UI is nice, but nothing works and everywhere there is "validation" that goes nowhere!

I just want to add loyalty points, lets say $0.10 per $100 purchase on tier1, then something similar for tier 2 (call it Gold), and tier 3 (Platinum). and see it gets reflected for basic 3 tier members (buyers). 

Whereas this tool talks about a lot of discount codes and I get that its meant for a large retail chain company, but hey, online first!

Can someone pinpoint to a simple one pager document that does only loyalty points and how to see those in demo transactions?

**Comment by sericks007** [comment]
Bug 270374 has been logged to track this issue.
