### ISSUE TITLE
Overlayering and OneBox Issues

### ISSUE THREAD

**Issue by jwilliams-bhsolutions** [MicrosoftDocs/dynamics-365-unified-operations-public#620]
1. The code samples above require overlayering of the Fleet Model.  You can accomplish the code using a form class augmentation, form extension, and event handler in PU20 (required to change form patterns in form extensions), but the sample provided is in violation for 8.0 compilation and best practices in any AU.
2. If you embed a PBIX file from PowerBI Desktop in a one box topology it will not be displayed due to the value of the Microsoft.Dynamics.AX.Framework.Analytics.Deploy.PBIPaaS.PowerBIEmbeddedConfiguration IsEmbedded property being false both in Azure subscription deployed versions and local VHD topologies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc7d8a19-6471-c70f-0452-74df0eded2f7
* Version Independent ID: a357999b-0336-cf39-a6b2-7cce6164be9e
* Content: [Add analytics to workspaces by using Power BI Embedded - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/add-analytics-tab-workspaces?toc=/fin-and-ops/toc.json)
* Content Source: [articles/dev-itpro/analytics/add-analytics-tab-workspaces.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/add-analytics-tab-workspaces.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by sericks007** [comment]
@jwilliams-bhsolutions, thanks for making us aware of this.

@TJVass, please update this article based on the feedback.

**Comment by sericks007** [comment]
Bug 270376 has been logged to track this issue.

**Comment by RobvanB** [comment]
Is there an update on this ? We are having the same problem....

**Comment by jwilliams-bhsolutions** [comment]
@RobvanB what AU/PU are you?  I have some code I'd be happy to share for PU20/8.0 while this is still being worked on if that's helpful.

**Comment by RobvanB** [comment]
@jwilliams-bhsolutions - This is on the latest 8.1 / PU21 version.... Thanks!!

**Comment by jwilliams-bhsolutions** [comment]
@RobvanB here's a Gist with my samples for embedding into the Customer Invoices workspace: https://gist.github.com/jwilliams-bhsolutions/07773630dbbd61e231c597786cfc860b.  

Remember you need an AxResource containing your PBIX file that points (with DQ) to your Entity Store.  

If you haven't seen these links you'll need to dig in to them as well so that you can test your embedding in any Tier 1 or ARM environments (I tested with a local VHD).  @TJVass posted them originally.

1. https://blogs.msdn.microsoft.com/dynamicsaxbi/2017/07/29/deploy-power-bi-embedded-service-for-dynamics-365-for-operations/
2. https://blogs.msdn.microsoft.com/dynamicsaxbi/2017/07/29/deploy-azure-sql-server-for-hosting-entity-store-database/
3. https://blogs.msdn.microsoft.com/dynamicsaxbi/2017/07/29/publish-the-entity-store-database-on-azure-sql-server/
4. https://blogs.msdn.microsoft.com/dynamicsaxbi/2017/07/29/configuring-1box-to-enable-analytical-workspaces-and-reports/

Hope that helps!  Feel free to reach out with questions.

**Comment by jwilliams-bhsolutions** [comment]
@RobvanB that is correct (for the most part), but I haven't tried deploying it in a Tier 2 box - my best guess is that it *will work* since the web.config is filled out for the PowerBIEmbedded.* keys.  If you try it please let me know the results!

**Comment by RobvanB** [comment]
@jwilliams-bhsolutions Josh, I can confirm that it works when you deploy the code to a tier 2 box. The same code that does not work on a 'standard' Tier 1 due to the 'powerbi.enabled' check works fine on tier 2 when deployed. So, build on tier 1, deploy and test on tier 2 works. Not optimal, but might be easier than fiddling with swapping out web.config files and DB backups.

**Comment by jwilliams-bhsolutions** [comment]
Thanks @RobvanB!  That's good news - I agree that this is a much better than the DB backups/configs (cheaper too).  Thanks for checking & sharing!

**Comment by TJVass** [comment]
Although, we do not support directly connecting to the Entity Store from PowerBI.com today, we offer a [preview](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/entity-store-data-lake) of this option using services based on Azure Data Lake.  Available today is the ability to host the data for Power BI on customer managed database.  More information is available [here](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/export-entities-to-your-own-database?toc=/fin-and-ops/toc.json)
