### ISSUE TITLE
Create configuration in design mode

### ISSUE THREAD

**Issue by GitHubSil** [MicrosoftDocs/dynamics-365-unified-operations-public#621]
You can only create a new configuration when Electronic Reporting is in design mode. 

Go to Electronic reporting &gt; Electronic reporting parameters
 
Then set “Enable design mode” to Yes
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f3947cc-f8fb-d3e5-0d16-7f44a537897e
* Version Independent ID: 11d18227-3171-9e5e-b3b9-55eca52c3e31
* Content: [ER Create a format configuration (November 2016) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/tasks/er-format-configuration-2016-11?toc=/fin-and-ops/toc.json)
* Content Source: [articles/dev-itpro/analytics/tasks/er-format-configuration-2016-11.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/tasks/er-format-configuration-2016-11.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @NickSelin
* Microsoft Alias: **nselin**

**Comment by sericks007** [comment]
@GitHubSil, thanks for making us aware of this issue.

@NickSelin, please update this topic based on the feedback.

**Comment by sericks007** [comment]
Bug 271040 has been logged to track this issue.

**Comment by ShylaThompson** [comment]
@GitHubSil , this topic will be updated to reflect this by the end of this week. The change has been made but it won't go live for a day or so. I'm going to close this issue as resolved, but please reopen if you don't see the change you expected within a few days.
