### ISSUE TITLE
8.0

### ISSUE THREAD

**Issue by OksanaKovaliova** [MicrosoftDocs/dynamics-365-unified-operations-public#624]
Is modification of Created/Modified properties still supported in 8.0? Not able to achieve this in 8.0, when in 7.3 I can do this 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a98edcb3-ab65-4e72-c79d-ce2fdd6d7483
* Version Independent ID: 9f39bf65-433b-0e07-f0a2-e2afeca1310b
* Content: [Modify table properties through extension - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/extensibility/modify-properties)
* Content Source: [articles/dev-itpro/extensibility/modify-properties.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/extensibility/modify-properties.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @ivanv-microsoft
* Microsoft Alias: **ivanv**

**Comment by tonyafehr** [comment]
Thanks for the feedback, @OksanaKovaliova! We will look into enhancing the documentation to provide the information that you're looking for. In the meantime, to get product help you can contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

@ivanv-microsoft, please review this topic and make needed updates based on this feedback.

**Comment by ivanv-microsoft** [comment]
@OksanaKovaliova, tagging you to make sure you see the response.

**Comment by ivanv-microsoft** [comment]
Do you create an extension within the same model? Same package? Different package?



Ivan (Vanya) Kashperuk | Senior Engineering Manager | Microsoft Dynamics 365 for Finance and Operations | Microsoft Development Center Copenhagen | http://kashperuk.blogspot.com<http://kashperuk.blogspot.com/>

Our workplace allows for a flexible work schedule. I am sending this email now because it is convenient for me. I do not expect you to read or respond to this email until it is convenient for you.

**Comment by OksanaKovaliova** [comment]
I create an extension in a new model, that references original model. Package is also new.

For example:

  1.  Model for extension = ‘Development Custom Model’ that is packaged separately (not a part of any standard package)
  2.  Original model = ‘Application Suite’
  3.  ‘Development Custom Model’ references original model
  4.  Extension is created inside ‘development Custom Model’
