### ISSUE TITLE
Both step 2 and 4 in "Apply a package to a production environment by using LCS" instructs you to mark the package as a release candidate.

### ISSUE THREAD

**Issue by PalleAgermark** [MicrosoftDocs/dynamics-365-unified-operations-public#625]
I'd assume step 4 would be the right time to do that, and not before applying the package to sandbox.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4008b2e3-4d1a-e146-8bdb-f39280124e9f
* Version Independent ID: 22f8390d-bb4d-1755-515c-7e7ebf1ddaae
* Content: [Apply updates to cloud environments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/deployment/apply-deployable-package-system)
* Content Source: [articles/dev-itpro/deployment/apply-deployable-package-system.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/deployment/apply-deployable-package-system.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @manalidongre
* Microsoft Alias: **manado**

**Comment by tonyafehr** [comment]
Thanks for the feedback, @PalleAgermark.

@manalidongre, please address this question from @PalleAgermark and make needed updates to this topic based on this feedback.

**Comment by tonyafehr** [comment]
Bug 271739 has been logged to track this issue.
