### ISSUE TITLE
Copied inforamtion from Dynamics AX 2012

### ISSUE THREAD

**Issue by amadse** [MicrosoftDocs/dynamics-365-unified-operations-public#632]
the servers in your environment might have different software installed,
All servers has the same software in our cloud deployment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96dc1049-f4c6-b089-f17f-355c29989163
* Version Independent ID: 80372d96-68d2-b931-a164-55f8e82f7e5c
* Content: [Batch processing - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/sysadmin/batch-processing-overview)
* Content Source: [articles/dev-itpro/sysadmin/batch-processing-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/sysadmin/batch-processing-overview.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @hasaid
* Microsoft Alias: **hasaid**

**Comment by sericks007** [comment]
Hi @amadse.  I'm not sure I understand your question.  Could you please provide more information about the scenario? Thanks!

**Comment by amadse** [comment]
Hi Sally

A part of the statement is copied from the Dynamics AX 2012 documentation and is not true for Dynamics 365 Finance & Operations.
I don’t recall the page, If you send I can make it more clear

Anders Madsen

Prin Consultant Erp
Microsoft Global Domain
Denmark


Office: +45 (45) 678213
Mobile: +45 29499831
amadse@microsoft.com<mailto:amadse@microsoft.com>



[Microsoft Logo]
If you have any feedback about my work, please let either me or my manager Christian Appel Christian.Appel@microsoft.com<mailto:Christian.Appel@microsoft.com> know.

**Comment by sericks007** [comment]
Closing, per email with Anders.
