### ISSUE TITLE
Not yet supported in App7.2

### ISSUE THREAD

**Issue by winbrother** [MicrosoftDocs/dynamics-365-unified-operations-public#633]
It's not yet supported in App7.2 for entity method. Only works for table/form/class.
If you want to use it, please upgrade to App8.1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2b3708d-a8c1-612b-f4f3-9802ad0c5448
* Version Independent ID: d2f14c0f-b695-a234-53ef-864d8e243d14
* Content: [Class extension - Method wrapping and Chain of Command - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/extensibility/method-wrapping-coc#extensions-of-form-nested-concepts-such-as-data-sources-data-fields-and-controls)
* Content Source: [articles/dev-itpro/extensibility/method-wrapping-coc.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/extensibility/method-wrapping-coc.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @ChrisGarty
* Microsoft Alias: **cgarty**

**Comment by sericks007** [comment]
@winbrother, thank you for posting this!

@ChrisGarty, is this something that should be added to the topic?

**Comment by tonyafehr** [comment]
Bug 276842 has been logged to track this issue.
