### ISSUE TITLE
SQLite

### ISSUE THREAD

**Issue by OksanaKovaliova** [MicrosoftDocs/dynamics-365-unified-operations-public#637]
Is SQLite still supported in D365 for Retail CRT? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eafa281-1f4f-5a63-d2ce-26fb2c90ba47
* Version Independent ID: 9a222e6a-8bd3-53c3-02ad-d27518632d7e
* Content: [Commerce runtime (CRT) architecture and configuration - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/dev-itpro/commerce-runtime-overview)
* Content Source: [articles/retail/dev-itpro/commerce-runtime-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/dev-itpro/commerce-runtime-overview.md)
* Service: **dynamics-365-retail**
* GitHub Login: @sericks007
* Microsoft Alias: **yabinl**

**Comment by sericks007** [comment]
@OksanaKovaliova, thanks for posting this question.

@mugunthanm, please answer the question and update the topic if necessary.

**Comment by sericks007** [comment]
Bug 276840 has been logged to track this issue.

**Comment by andreesteve** [comment]
@OksanaKovaliova  - SQLite is not currently supported in CRT.
