### ISSUE TITLE
How to handle a new TAG in the ISO20022 bank statements - Dynamics 365 for Finance & Operations

### ISSUE THREAD

**Issue by macchinettid** [MicrosoftDocs/dynamics-365-unified-operations-public#638]
In the blog post below I explain How-to handle a new Tag in the ISO20022 bank statements file.

https://sinedax.blogspot.com/2018/11/how-to-handle-new-tag-in-iso20022-bank.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e05abef3-f815-21a0-eedb-e67901e5bf99
* Version Independent ID: c4556269-06f3-177a-7da7-1de63eea835b
* Content: [Set up the advanced bank reconciliation import process - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/cash-bank-management/set-up-advanced-bank-reconciliation-import-process)
* Content Source: [articles/financials/cash-bank-management/set-up-advanced-bank-reconciliation-import-process.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/cash-bank-management/set-up-advanced-bank-reconciliation-import-process.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @ShylaThompson
* Microsoft Alias: **saraschi**

**Comment by sericks007** [comment]
@macchinettid, thanks for posting this!
