### ISSUE TITLE
Validity

### ISSUE THREAD

**Issue by OksanaKovaliova** [MicrosoftDocs/dynamics-365-unified-operations-public#639]
Hi, for what version of Retail is this article valid? 
Does ExtendedController still exist? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1759797-2d85-a8d2-8183-2d6bb7b48963
* Version Independent ID: 1e3c3757-3191-eecf-76a3-d15cd6bca182
* Content: [Create a Web API controller for Retail Server - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/dev-itpro/odata-controllers-api)
* Content Source: [articles/retail/dev-itpro/odata-controllers-api.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/dev-itpro/odata-controllers-api.md)
* Service: **dynamics-365-retail**
* GitHub Login: @kfend
* Microsoft Alias: **meeram**

**Comment by sericks007** [comment]
@OksanaKovaliova, thanks for posting!

@AamirAllaq or @mugunthanm, could you please answer this question and update the topic, as necessary?

**Comment by sericks007** [comment]
Bug 276843 has been logged to track this issue.

**Comment by mugunthanm** [comment]
We don't support this for now, we have the code for extended controller in the Retail server but don't use it follow the pattern exposed in the Retail server SDK samples, we will retire this doc soon.
