### ISSUE TITLE
Event 5000

### ISSUE THREAD

**Issue by OksanaKovaliova** [MicrosoftDocs/dynamics-365-unified-operations-public#640]
Hi,
Is information about event 5000 & Analytics channel still valid?
Cannot find them in Retail logs.. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2995dab3-754e-79d8-5bb3-857e06a4d9c1
* Version Independent ID: 99a6a217-49d8-67ee-da81-69970750e81a
* Content: [Retail component events for diagnostics and troubleshooting - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/dev-itpro/retail-component-events-diagnostics-troubleshooting)
* Content Source: [articles/retail/dev-itpro/retail-component-events-diagnostics-troubleshooting.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/dev-itpro/retail-component-events-diagnostics-troubleshooting.md)
* Service: **dynamics-365-retail**
* GitHub Login: @aamirallaqaband
* Microsoft Alias: **aamiral**

**Comment by sericks007** [comment]
@OksanaKovaliova, thanks for posting this!

@AamirAllaq, could you please answer this question and update the topic, if necessary?

**Comment by andreesteve** [comment]
@OksanaKovaliova - 5000 events show up in the Analytics node under Commerce-RetailServer. You need to right click on the node and select "Enable log". You need to trigger a Retail Server request to see them, as old events are not persisted when the Analytics node is not enabled. Let me know if they are not there for you environment.

**Comment by tonyafehr** [comment]
Bug 276848 has been logged to track this issue.
