### ISSUE TITLE
List Panel example

### ISSUE THREAD

**Issue by leodas2004** [MicrosoftDocs/dynamics-365-unified-operations-public#642]
Where can I find the CLIPatterns_ListPanel form as mentioned in the article above?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 752fa821-0d42-e5c6-490a-6b263767ce5b
* Version Independent ID: 08c940c6-602c-e6fd-b403-731409b29835
* Content: [List Panel subpattern - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/user-interface/list-panel-subpattern)
* Content Source: [articles/dev-itpro/user-interface/list-panel-subpattern.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/user-interface/list-panel-subpattern.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by tonyafehr** [comment]
@leodas2004, thanks for posting!
@jasongre, please answer this question and update the topic, as necessary.

**Comment by tonyafehr** [comment]
Bug 276851 has been logged to track this issue.

**Comment by jasongre** [comment]
CLIPatterns_ListPanel is an internal test form. It was included to show the visual of what the List Panel looks like with the Move all buttons. I'll remove that reference. The pattern itself should have sufficient details on the controls to add to get that appearance.
