### ISSUE TITLE
XPS is no longer found in D365

### ISSUE THREAD

**Issue by rossdo88** [MicrosoftDocs/dynamics-365-unified-operations-public#644]
Would you please update that whether we can still export using XPS because i cant find it in 7.1 8.0 8.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ae87f0f-08d6-6c4e-3171-4f45ba602220
* Version Independent ID: 2b16c6dc-92bb-a238-7a9d-db6562d568af
* Content: [Financial reporting - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/financial-reporting-intro#features)
* Content Source: [articles/dev-itpro/analytics/financial-reporting-intro.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/financial-reporting-intro.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @aprilolson
* Microsoft Alias: **aolson**

**Comment by tonyafehr** [comment]
@rossdo88, thanks for posting!
@aprilolson, please answer this question and update the topic, as necessary.

**Comment by aprilolson** [comment]
You can export to .pdf, not .xps.
