### ISSUE TITLE
Remove a Party role association - How?

### ISSUE THREAD

**Issue by ggriffith02** [MicrosoftDocs/dynamics-365-unified-operations-public#645]
In D365FO, how can you remove a Party Role Association.  If we have the same Customer in three different legal entities, how can we unlink the party role association?  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c53233ff-e825-c9d6-ddc6-b0e7efc69f0e
* Version Independent ID: 7a3d54c1-df29-9ec2-9d96-7b946d9461b1
* Content: [Global address book - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/organization-administration/overview-global-address-book)
* Content Source: [articles/fin-and-ops/organization-administration/overview-global-address-book.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/organization-administration/overview-global-address-book.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @ShivamPandey-msft
* Microsoft Alias: **shpandey**

**Comment by tonyafehr** [comment]
@ggriffith02, thanks for posting!
@ShivamPandey-msft, please answer this question and update the topic, as necessary.

In the meantime, to get product help you can contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

**Comment by brkingmsft** [comment]
Hi @ggriffith02 -
You can change the party association for a customer by going to Accounts Receivable - Customers - All Customers and clicking on Change party association on the Customer tab in the Accounts section.  You should see a fly-out window where you can see the existing party association and then a drop-down to select a new party.
