### ISSUE TITLE
Could not load file or assembly 'Microsoft.TeamFoundation.Common

### ISSUE THREAD

**Issue by beautifullmind** [MicrosoftDocs/dynamics-365-unified-operations-public#654]
I am running into the following issue when i run the command for source control

Could not load file or assembly 'Microsoft.TeamFoundation.Common, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Microsoft.Dynamics.AX.Servicing.SCDPBundleInstall.PrepareCommand.RunCommand()
   at Microsoft.Dynamics.AX.Servicing.SCDPBundleInstall.Program.Main(String[] args) 

any thoughts what could be the cause?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66b4c899-c7e0-0406-0d39-d32fc41b6104
* Version Independent ID: 5d015069-177d-e33c-094c-257df088a7c0
* Content: [Install metadata hotfixes in development environments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/install-metadata-hotfix-package)
* Content Source: [articles/dev-itpro/migration-upgrade/install-metadata-hotfix-package.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/migration-upgrade/install-metadata-hotfix-package.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RobinARH
* Microsoft Alias: **robadawy**

**Comment by kfend** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: `[Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support)`. In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
