### ISSUE TITLE
Fix for data packages upload sequence

### ISSUE THREAD

**Issue by D365Explorer** [MicrosoftDocs/dynamics-365-unified-operations-public#655]
Please, specify which package should be uploaded first of them?
"300 - Supply chain - PIFB	Load this package after the PICH Supply chain package.
 300 - Supply chain - PICH	Load this package after the PIFB Supply chain package."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fc92d46-8f1c-dc72-82c0-dcbccf014c18
* Version Independent ID: 934a9f55-fd2a-a08c-b8ce-cfd0c1fbb975
* Content: [Generate demo data by using data packages - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/generate-demo-data-packages#demo-data-package-releases)
* Content Source: [articles/dev-itpro/data-entities/generate-demo-data-packages.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/generate-demo-data-packages.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @ryansandness
* Microsoft Alias: **ryansand**

**Comment by ryansandness** [comment]
I have typically done PICH before PIFB, but since they are both labeled as 300, we don't believe there to be any dependency and either could be run first.
