### ISSUE TITLE
"Project management package 250" is depended on Public sector data

### ISSUE THREAD

**Issue by D365Explorer** [MicrosoftDocs/dynamics-365-unified-operations-public#656]
It's written: "there is currently a commercial system and shared package as well as a separate public sector system and shared package that CAN'T be used together". I upload 13 packages of "Commercial data" listed above without Public Sector packages and get more than thousands errors after"250 - Project management - HQUS" is imported, which say that company PSUS doesn't exist. PSUS belongs to Public sector packages. What are the requested packages and the sequence of their upload, if I need Project management data as well? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fc92d46-8f1c-dc72-82c0-dcbccf014c18
* Version Independent ID: 934a9f55-fd2a-a08c-b8ce-cfd0c1fbb975
* Content: [Generate demo data by using data packages - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/generate-demo-data-packages#demo-data-package-releases)
* Content Source: [articles/dev-itpro/data-entities/generate-demo-data-packages.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/generate-demo-data-packages.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @ryansandness
* Microsoft Alias: **ryansand**

**Comment by D365Explorer** [comment]
Hi Ryan,
Data management
![image](https://user-images.githubusercontent.com/45470675/49676525-0d264000-fa48-11e8-95c7-abb5668f379e.png)
Unfortunetly, the logs for Import Sys_And_Shared and Fin_200_HQUS were deleted, but they were uploaded in that sequence.

Project management and accounting
![image](https://user-images.githubusercontent.com/45470675/49676554-25965a80-fa48-11e8-838b-91a7979f7a48.png)

example of error, referencing to PSUS
![image](https://user-images.githubusercontent.com/45470675/49676569-3a72ee00-fa48-11e8-927f-47c8cdde3c5a.png)

**Comment by ryansandness** [comment]
Thank you. Can you re-download the file from LCS (Demo data 8.1. 250 Project management and accounting HQUS) and compare the files within to these last two screenshots?  I downloaded from LCS and clearly see 88 items in the zip file with no reference to employee or fund. 

![image](https://user-images.githubusercontent.com/27744245/49677423-5d9b9e80-fa44-11e8-9020-244617876244.png)
