### ISSUE TITLE
Support Change Tracking for ODATA

### ISSUE THREAD

**Issue by rayzorben** [MicrosoftDocs/dynamics-365-unified-operations-public#658]
Currently there does not seem to be an option for querying only changed records via ODATA.. D365 Customer Engagement supports this capability by adding the HTTP header Prefer: odata.track-changes which will return a URL in the response listing the token and URL to request the next set of changes.

https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/use-change-tracking-synchronize-data-external-systems

I think this capability is necessary in ODATA for integrations that can only be done programatically.

**Comment by ShylaThompson** [comment]
@rayzorben, Thanks for taking the time to provide feedback on Finance and Operations! Can you use the [Ideas site](https://experience.dynamics.com/ideas/list/?forum=16691718-61e2-e611-8101-5065f38b21f1) to submit your feedback directly? The ideas site will enable you to receive notifications, vote, and monitor the progress of your idea more closely. 

As this is product feedback, and not documentation feedback, I'm closing this issue.
