### ISSUE TITLE
Quick Links for Master Planning essentials & Intercompany master planning not working

### ISSUE THREAD

**Issue by Navneetkat** [MicrosoftDocs/dynamics-365-unified-operations-public#661]
Following the above 2 links take us to a screen where it shows the Training material is retired and go back takes us back to this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e78a33e-fc18-ad95-2a98-456dad3ac154
* Version Independent ID: 251b7ff1-df80-3b9e-c8a7-8e7df141eb21
* Content: [Master planning home page - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/master-planning/master-planning-home-page)
* Content Source: [articles/supply-chain/master-planning/master-planning-home-page.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/master-planning/master-planning-home-page.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @ShylaThompson
* Microsoft Alias: **roxanad**

**Comment by ShylaThompson** [comment]
@Navneetkat , Thanks for letting us know about this. I've removed the links.  The training material has expired. 

Over time, we'll be adding new updated training to the new [Microsoft Learn site](https://docs.microsoft.com/en-us/learn/).
