### ISSUE TITLE
    An error occurred getting the Power BI groups. Please contact your system administrator.

### ISSUE THREAD

**Issue by Phineas019** [MicrosoftDocs/dynamics-365-unified-operations-public#662]
We have 4 environments with same link. Configured Only one application to use on them all.
The application works as it meant for in One machine not on other machines. 
Application version is 7.3 PU15 to 8.1 PU20.

Thanks in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 717d397d-4186-c7de-431d-3260d3f0484a
* Version Independent ID: bdd7545b-5970-93e0-5cbb-a59da4ace01b
* Content: [Configure Power BI integration for workspaces - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/configure-power-bi-integration)
* Content Source: [articles/dev-itpro/analytics/configure-power-bi-integration.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/configure-power-bi-integration.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by ShylaThompson** [comment]
@Phineas019 Thanks for contacting us. Unfortunately, we can't handle support requests for the product here. To contact support, consider one of the options described here:  https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support
