### ISSUE TITLE
How to set up exchange

### ISSUE THREAD

**Issue by rossdo88** [MicrosoftDocs/dynamics-365-unified-operations-public#663]
Hello everyone,
Can you please guide me how to set up exchange online if email provider i choose exchange?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3474f86-38f0-8d1c-87fb-ba192e0a8adb
* Version Independent ID: 4c64163d-e9b2-0966-b67e-ae63f4393215
* Content: [Configure and send email - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/organization-administration/configure-email)
* Content Source: [articles/fin-and-ops/organization-administration/configure-email.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/organization-administration/configure-email.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @ChrisGarty
* Microsoft Alias: **cgarty**

**Comment by tonyafehr** [comment]
Bug 276837 has been logged to track this issue.

**Comment by JonathanAnd** [comment]
Can we please have a status on this?  Need to know how to setup Exchange for a current implementation

**Comment by rossdo88** [comment]
>           Can we please have a status on this?  Need to know how to setup Exchange for a current implementation

@JonathanAnd  you need to configure EWS in exchange first then set up in Organisation Administration/Microsoft exchange server synchronization/Microsoft exchange server mapping in AX client

**Comment by ChrisGarty** [comment]
The Email parameters form allows an administrator to select Exchange as an interactive email provider and as the Batch email provider. The Exchange mail provider will use the current user's Exchange Online account to send emails. When used as the Batch email provider, the batch account will be used. No additional configuration is needed. If troubleshooting issues, ensure that the current user's account can be signed into and that emails can be sent from that account to the intended recipients.
