### ISSUE TITLE
Change Position in Group field

### ISSUE THREAD

**Issue by iwiaCorp** [MicrosoftDocs/dynamics-365-unified-operations-public#664]
Hi everyone, it is possible to change position field into field group throughout design? I know how to add dynamic field control into runtime design and set position by code but it need more complex programming.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62c6ef81-7b43-a840-be03-d8d94505348c
* Version Independent ID: 4cfc9e30-79ee-a361-7e87-c36e6d9f7110
* Content: [Add fields to tables through extension - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/extensibility/add-field-extension)
* Content Source: [articles/dev-itpro/extensibility/add-field-extension.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/extensibility/add-field-extension.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @ivanv-microsoft
* Microsoft Alias: **ivanv**

**Comment by tonyafehr** [comment]
@iwiaCorp, thanks for posting!
@ivanv-microsoft, could you answer this question and update this topic based on this feedback.

**Comment by tonyafehr** [comment]
Bug 276836 has been logged to track this issue.

**Comment by iwiaCorp** [comment]
For example, my solution was to add in runtime the following code:

FormGroupControl groupCurrencyControl = formRun.design().controlName("GroupCurrency");
     //get control into runtime  
FormReferenceGroupControl exchangeRateType = formRun.design().controlName("NewControlCustomization");
FormStringControl currencyCodeControl = formRun.design().controlName("GroupCurrency_CurrencyCode");

//Move or Interchange position       
groupCurrencyControl.moveControl(exchangeRateType.id(), currencyCodeControl.id());
groupCurrencyControl.moveControl(currencyCodeControl.id(), exchangeRateType.id())

**Comment by robadawy** [comment]
Standard extension patterns do not support this request via metadata extension.
