### ISSUE TITLE
Maps Extensions

### ISSUE THREAD

**Issue by denizLapantov** [MicrosoftDocs/dynamics-365-unified-operations-public#665]
Hello Everyone,
Will anyone be able to extend maps? 
Or in particular vendDocumentTableMap.
Have a nice day,
Deniz

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a29c2a47-93dc-faaa-7e0b-88edcea63652
* Version Independent ID: 14e1b47b-67e1-accc-c1e0-72b84aab3d55
* Content: [Extensibility changes in Dynamics 365 for Finance and Operations version 8.1.2 - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/extensibility/extensibility-changes-812)
* Content Source: [articles/dev-itpro/extensibility/extensibility-changes-812.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/extensibility/extensibility-changes-812.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @FrankDahl
* Microsoft Alias: **fdahl**

**Comment by FrankDahl** [comment]
Hello Deniz,
Maps are made extensible through that we refactor the structure of these in the application. We are not going to provide general platform support for extending maps. You should familiarize yourself with the documentation resources we have published:
https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/extensibility/map-extensions
https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/extensibility/maps-as-interfaces
https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/extensibility/maps-with-versioning

If you are finding a specific maps does not provide you similar extensibility support for a particular map you need for your customizations, then please log an extensibility request for the map.

Thanks,
Frank
