### ISSUE TITLE
Starting point = Workspace "Electronic reporting"

### ISSUE THREAD

**Issue by SST1982** [MicrosoftDocs/dynamics-365-unified-operations-public#666]
It would be useful to know that when setting things up as instructed, the starting point is the Workspace "Electronic reporting". This hint was missing and I spent an hour searching for "Electronic reporting parameters"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed8868c5-62f4-ecfa-a0d6-39bba9904a01
* Version Independent ID: efbf645f-8f9b-4b7b-9b83-5c26ccaccd8a
* Content: [Configure the Electronic reporting (ER) framework - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/electronic-reporting-er-configure-parameters?toc=/fin-and-ops/toc.json)
* Content Source: [articles/dev-itpro/analytics/electronic-reporting-er-configure-parameters.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/electronic-reporting-er-configure-parameters.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @NickSelin
* Microsoft Alias: **nselin**

**Comment by sericks007** [comment]
@SST1982, thanks for posting this!

@NickSelin, please review this suggestion and update the topic appropriately.

**Comment by sericks007** [comment]
Bug 276847 has been logged to track this issue.

**Comment by sericks007** [comment]
Actually, this issue has already been fixed, so closing this issue and bug 276847.
