### ISSUE TITLE
need some clarification

### ISSUE THREAD

**Issue by prodev42** [MicrosoftDocs/dynamics-365-unified-operations-public#667]
in some of the screenshots what is the difference between left side diagram vs  right side?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b7bb314-de6d-019e-e35e-58d1b0b6050b
* Version Independent ID: 0eaf4a1a-e500-b192-9e7e-42c69e76fa99
* Content: [Validations, default values, and unmapped fields - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/validations-defaults-unmapped-fields?toc=/fin-and-ops/toc.json)
* Content Source: [articles/dev-itpro/data-entities/validations-defaults-unmapped-fields.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/validations-defaults-unmapped-fields.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by sericks007** [comment]
@prodev42, thanks for posting this!

@Sunil-Garg, can you please answer this question, and update the topic, if appropriate.

**Comment by sericks007** [comment]
Bug 276852 has been logged to track this issue.

**Comment by Sunil-Garg** [comment]
prodev42, can you pls clarify as what exactly you are referring to? which diagram? thanks.

**Comment by sericks007** [comment]
@prodev42, can you please respond to Sunil's question above. Thanks!

**Comment by rsteber** [comment]
I cannot find the getDefaultDependencies method mentioned in the document.

**Comment by josaw1** [comment]
@Sunil-Garg reopened bug.

**Comment by Sunil-Garg** [comment]
@prodev42 and @rsteber , -- its getDefaultingDependencies and not getDefaultDependencies. Was it this typo issue?
