### ISSUE TITLE
diagram for outbound flow?

### ISSUE THREAD

**Issue by prodev42** [MicrosoftDocs/dynamics-365-unified-operations-public#668]
Is there diagram for outbound flow?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fefee79b-aac3-6f4d-92bb-ffd7021a85a8
* Version Independent ID: 446e7928-558c-b72d-2b8f-e53f04f2ebd0
* Content: [Data management and integration by using data entities - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/data-management-integration-data-entity?toc=/fin-and-ops/toc.json)
* Content Source: [articles/dev-itpro/data-entities/data-management-integration-data-entity.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/data-management-integration-data-entity.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by sericks007** [comment]
@prodev42, thanks for posting this!

@Sunil-Garg, can you please answer this question, and update the topic, if appropriate.

**Comment by Sunil-Garg** [comment]
prodev42, we currently don't have an outbound diagram. The flow is almost the same as shown for import. One exception I can think of the part where the export file will be uploaded by AOS.
