### ISSUE TITLE
Email Reference Content Update

### ISSUE THREAD

**Issue by tbarron2** [MicrosoftDocs/dynamics-365-unified-operations-public#669]
It's my understanding that email notifications for alerts are not part of the latest release of F&O.  This content implies that the email message functionality is active.  I would suggest removing that reference and clarifying that later releases may have this functionality.   We would love to see the email functionality as soon as possible.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0a3ca39-86d2-d8e4-6f33-95f1e802b4e7
* Version Independent ID: 3e537bc3-ce30-66bd-9509-d7afd3f71cf4
* Content: [Create alert rules - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/create-alerts)
* Content Source: [articles/fin-and-ops/get-started/create-alerts.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/create-alerts.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by sericks007** [comment]
@tbarron2, thanks for posting this!

@TJVass, please update the topic appropriately.

**Comment by sericks007** [comment]
Bug 276857 has been logged to track this issue.
