### ISSUE TITLE
Stock Quote Service Failure

### ISSUE THREAD

**Issue by aaronstackpole** [MicrosoftDocs/dynamics-365-unified-operations-public#670]
The stock quote web service listed in this article is not working for me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3e8a936-3bef-b844-e935-adfadd03516f
* Version Independent ID: 53cc6e3a-a62e-be0f-dba1-38f62394ee0e
* Content: [Consume external web services in Finance and Operations - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/consume-external-web-service)
* Content Source: [articles/dev-itpro/data-entities/consume-external-web-service.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/consume-external-web-service.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by aaronstackpole** [comment]
This article has multiple problems, please update with functional code samples that work with current versions of Dynamics 365 for Finance and Operations.

**Comment by sericks007** [comment]
@aaronstackpole, thanks for making us aware of this issue.

@Sunil-Garg, please update the topic appropriately.

**Comment by sericks007** [comment]
Bug 276858 has been logged to track this issue.

**Comment by DynamicsArvindSingh** [comment]
Hi Guys can you update the documentation with the logic for consuming the .Net based external web APIs with AAD authentication in Microsoft Dynamics 365 Finance & Operation server using X++ code, Can you please provide sample Code examples for the same.

**Comment by DynamicsArvindSingh** [comment]
Getting Error while adding service reference for http://www.webservicex.net/stockquote.asmx

Details are as below :
The HTML document does not contain Web service discovery information.
Metadata contains a reference that cannot be resolved: 'http://www.webservicex.net/stockquote.asmx'.
The content type text/html of the response message does not match the content type of the binding (application/soap+xml; charset=utf-8). If using a custom encoder, be sure that the IsContentTypeSupported method is implemented properly. The first 1024 bytes of the response were: '<!doctype html>
<html lang="en">

<head>

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
  
  <meta charset="utf-8">
  <title>{{title}}</title>
  <base href="/">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
<link rel="stylesheet" href="styles.8dc4251fbfaf022a1baa.css"></head>

<body >


<app-root></app-root>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-1803935-1']);
  _gaq.push(['_trackPageview']);

  (function () {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

<script type="text/javascript" '.
If the service is defined in the current solution, try building the solution and adding the service reference again.
