### ISSUE TITLE
Date Correction - for Inventory Closing

### ISSUE THREAD

**Issue by faheem-usmani** [MicrosoftDocs/dynamics-365-unified-operations-public#673]
In the above content it is mentioned that no transactions can be done for the period closed and further explained that no transaction can be made in the date earlier than Closing date. While you cannot even make an inventory transaction in the closing date. 
So, the word "earlier" is not suitable there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1da3a33-3988-e8de-8a7a-472760c710a9
* Version Independent ID: 4c71af1a-a898-7ee2-27ae-bb083b8a19dd
* Content: [Inventory close - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/cost-management/inventory-close)
* Content Source: [articles/supply-chain/cost-management/inventory-close.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/cost-management/inventory-close.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @AndersGirke
* Microsoft Alias: **shylaw**

**Comment by josaw1** [comment]
Thank you for your feedback. I've sent this to the author for his review.
