### ISSUE TITLE
Code Upgrade tool stops with error at 3%

### ISSUE THREAD

**Issue by mkraus81** [MicrosoftDocs/dynamics-365-unified-operations-public#674]
The code upgrade service stops at 3% with the error message
"We're sorry, the analysis can't be completed. To research this issue, see"

after i removed all packages with binary files from version control
the code-upgrade succeded

i think it would be a great help to add a understandable error message to the code upgrade tool for this case

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54bffa91-2a14-2819-8f74-80fd1f79b9df
* Version Independent ID: f1042837-8207-d07b-3d53-86ead3b6679c
* Content: [Configure the code upgrade service in Lifecycle Services (LCS) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/configure-execute-code-upgrade)
* Content Source: [articles/dev-itpro/lifecycle-services/configure-execute-code-upgrade.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/lifecycle-services/configure-execute-code-upgrade.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @tariqbell
* Microsoft Alias: **tabell**

**Comment by ShylaThompson** [comment]
@mkraus81  Thanks for taking the time to provide feedback on Finance and Operations! Please log your idea on the [Ideas site]( https://experience.dynamics.com/ideas/list/?forum=16691718-61e2-e611-8101-5065f38b21f1) to submit it directly. Logging your idea will enable you to receive notifications, vote, and monitor the progress of your idea more closely. 

As this is not an issue with this help topic on Docs, I'm closing this issue.
