### ISSUE TITLE
Amount of CPU cores used to build X++ Code

### ISSUE THREAD

**Issue by erikpaperik** [MicrosoftDocs/dynamics-365-unified-operations-public#689]
Dear MS Team,

in the article you are writing "However, the compiler will use available resources, so more RAM and more cores may translate into faster compilations ..."

As far as I know the X++ build process will always just utilize one CPU core. Is this still true?
The statement above makes me think that compiler "[...] will use available resources [...]" which includes more CPUs, too?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4edde57d-5529-f34f-e343-b2cff4610d57
* Version Independent ID: 007d952e-9b06-3f87-479d-d1bb6d6234df
* Content: [Development system requirements - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-tools/development-system-requirements)
* Content Source: [articles/dev-itpro/dev-tools/development-system-requirements.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-tools/development-system-requirements.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RobinARH
* Microsoft Alias: **robadawy**

**Comment by tonyafehr** [comment]
@erikpaperik, Thanks for taking the time to provide feedback about our documentation. I've passed your suggestion on to the author of this topic so it's noted for future updates. In the meantime, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

**Comment by tonyafehr** [comment]
Bug 278479 has been logged to track this issue.

**Comment by TrudAX** [comment]
Compiler in D365FO uses all available cores(you can see this by executing Build for the Application source model), so the phrase is correct. I think the issues should be closed

**Comment by erikpaperik** [comment]
@TrudAX 
Thx for clarification.
