### ISSUE TITLE
private static PurchFormLetter constructFromClassNameMethodName

### ISSUE THREAD

**Issue by denizLapantov** [MicrosoftDocs/dynamics-365-unified-operations-public#691]
Hello,

can you for the next upgrading make this method extendable, that is, not private.

Have a nice day,
Deniz

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad71b572-4c50-4ba1-c0f0-cba6402388ce
* Version Independent ID: ee2eb0e4-4a79-962a-4269-39f206a51767
* Content: [Extensibility changes in Dynamics 365 for Finance and Operations version 8.1.3 - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/extensibility/extensibility-changes-813)
* Content Source: [articles/dev-itpro/extensibility/extensibility-changes-813.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/extensibility/extensibility-changes-813.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @FrankDahl
* Microsoft Alias: **fdahl**

**Comment by tonyafehr** [comment]
@denizLapantov, Thanks for taking the time to provide feedback about Finance and Operations. I've passed your suggestion on to the author of this topic so it's noted for future updates. Also, please log your idea on the [Ideas site]( https://experience.dynamics.com/ideas/list/?forum=16691718-61e2-e611-8101-5065f38b21f1) to submit it directly. Logging your idea will enable you to receive notifications, vote, and monitor the progress of your idea more closely. 

As this is not an issue with this help topic on Docs, I am closing this issue.
