### ISSUE TITLE
Change is Web.Config required to enable flighting catalogID

### ISSUE THREAD

**Issue by DutchDynamics** [MicrosoftDocs/dynamics-365-unified-operations-public#692]
After inserting the additional record in the sysflighting for "DMFExportToPackageForceSync", a change to the Web Config is also required to make the functionality work.

Change the web.config for your environment.
add key=”DataAccess.FlightingServiceCatalogID” value=”12719367″

This is not mentioned anywhere in the documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c6788e8-dfb0-6108-71ae-e265bad542a2
* Version Independent ID: 68a26703-3d8c-4d46-6f3f-37c30aa79373
* Content: [Data management - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/data-entities-data-packages#features-flighted-in-data-management-and-enabling-flighted-features)
* Content Source: [articles/dev-itpro/data-entities/data-entities-data-packages.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/data-entities-data-packages.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by tonyafehr** [comment]
@DutchDynamics, Thanks for taking the time to provide feedback on our documentation. I've passed your comment on to the author of this topic so it's noted for future updates. If you need immediate assistance, please contact Support. consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

**Comment by DutchDynamics** [comment]
We noticed that when using the entity trough the recurring integrations, the entity names are still all CAPS.
We added the following lines to the Batch.exe.config

    <add key="DataAccess.FlightingEnvironment" value="" />
    <add key="DataAccess.FlightingCertificateThumbprint" value="" />
    <add key="DataAccess.FlightingServiceCatalogID" value="12719367" />
    <add key="DataAccess.FlightingServiceCacheFolder" value="CarbonRuntimeBackup" />

After this also the batch server are using the PascalCasing

Regatds,
Wouter

**Comment by tonyafehr** [comment]
Bug 278483 has been logged to track this issue.
