### ISSUE TITLE
Supporting Office Software Prerequisites

### ISSUE THREAD

**Issue by tomhig** [MicrosoftDocs/dynamics-365-unified-operations-public#693]
Under Prerequisites, it says you must have Office 2010. Just above the Prerequisites, it notes Word and Visio but it does not note the minimum version. It also needs to mention Excel because BPMs can be exported to Excel or imported from Excel.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50a6fe88-302f-1a22-fdc2-c31b03c6bc7c
* Version Independent ID: 9c2da420-8a13-2c46-78d0-8476d3ce721e
* Content: [Business process modeler (BPM) in Lifecycle Services (LCS) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/bpm-overview)
* Content Source: [articles/dev-itpro/lifecycle-services/bpm-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/lifecycle-services/bpm-overview.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @kfend
* Microsoft Alias: **ntecklu**

**Comment by sericks007** [comment]
@tomhig, thanks for posting this!

@robadawy, please update this topic appropriately.

**Comment by tonyafehr** [comment]
Bug 278484 has been logged to track this issue.
