### ISSUE TITLE
can do Purchase order or Transfer Receive?

### ISSUE THREAD

**Issue by liamneesangamer** [MicrosoftDocs/dynamics-365-unified-operations-public#697]
If we configure RSSU, Can store associative do Purchase order receive and Transfer Receive/send to other stores without HQ back office connection?.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1a9dcb9-1daf-e6ca-48a1-3934727a680c
* Version Independent ID: 5b2d0ae0-62f3-1a89-2fcd-0244b6712bee
* Content: [Retail Store Scale Unit - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/dev-itpro/retail-store-system-begin)
* Content Source: [articles/retail/dev-itpro/retail-store-system-begin.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/dev-itpro/retail-store-system-begin.md)
* Service: **dynamics-365-retail**
* GitHub Login: @athinesh99
* Microsoft Alias: **athinesh**

**Comment by ShylaThompson** [comment]
@EvgenyPopovMBS or @athinesh99 , can you answer the question?

**Comment by liamneesangamer** [comment]
I cannot find a proper guide on anywhere about dynamic 365. These documents are not enough to clear the doubts about the complete function of RSSU

**Comment by josaw1** [comment]
Thanks for your feedback. I've let the author of this topic know of your concerns.

**Comment by jashanno** [comment]
Hi @liamneesangamer
Purchase Orders and Transfer Orders are based in headquarters and are not Point of Sale operations.  The Retail Store Scale Unit (RSSU) is a Retail Server and Channel database for Point of Sale terminals (Modern POS and Cloud POS) only.  You can review the following:
Purchase Order Overview - https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/procurement/purchase-order-overview
Our new feature DOM (Distributed Order Management) - https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/dom
Point of Sale Operations Reference - https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/pos-operations
Hopefully this helps.  I will internalize to see if there is anything we could do in regards to create more documentation that assists in better clarifying any confusion around areas.
