### ISSUE TITLE
Notification on MPOS/CPOS

### ISSUE THREAD

**Issue by meneksesaygili** [MicrosoftDocs/dynamics-365-unified-operations-public#699]
You can only use this operation notification for order fulfillment. The others need to be customized.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3eb22af1-4e63-ed08-7586-341a5593b8fd
* Version Independent ID: b5b82695-ef06-7e5a-37b9-043aef0011e0
* Content: [Show order notifications in the point of sale (POS) - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/notifications-pos)
* Content Source: [articles/retail/Notifications-POS.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/Notifications-POS.md)
* Service: **dynamics-365-retail**
* GitHub Login: @ShalabhjainMSFT
* Microsoft Alias: **ShalabhjainMSFT**

**Comment by ShylaThompson** [comment]
@ShalabhjainMSFT , does this topic need to be updated with the information provided above?

**Comment by ShalabhjainMSFT** [comment]
Yes, the information mentioned in the comment is correct. @ShylaThompson

**Comment by tonyafehr** [comment]
Bug 280751 has been logged to track this issue.

**Comment by vicky-88** [comment]
Is there a way to add notifications in Cloud POS ?
