### ISSUE TITLE
Transfer or Purchase will not receive on store in offline?

### ISSUE THREAD

**Issue by liamneesangamer** [MicrosoftDocs/dynamics-365-unified-operations-public#700]
Is it not possible to receive or make transfer/Purchase order in Store(RSSU), in Offline?.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c1afa28-2fce-5ee9-016c-c6daadf43579
* Version Independent ID: c5cc8f68-2fb4-a9b4-0864-a6f98cecaa0c
* Content: [Commerce Data Exchange and retail channel communications - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/dev-itpro/define-retail-channel-communications-cdx)
* Content Source: [articles/retail/dev-itpro/define-retail-channel-communications-cdx.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/dev-itpro/define-retail-channel-communications-cdx.md)
* Service: **dynamics-365-retail**
* GitHub Login: @athinesh99
* Microsoft Alias: **athinesh**

**Comment by ShylaThompson** [comment]
@EvgenyPopovMBS, do you know the answer?
