### ISSUE TITLE
Conflicting collation requirements in on prem system requirements

### ISSUE THREAD

**Issue by TomVergote** [MicrosoftDocs/dynamics-365-unified-operations-public#701]
In the documentation for [on prem system requirements](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/system-requirements-on-prem.md) there is a conflicting statement about the supported collations : 

The original documentation stated that a Windows collation is recommended over a SQL Server collation.  

> If you’re setting up a new installation, we recommend that you select a Windows collation instead of a SQL Server collation. 

However in commit [5e17380b2026efdf994a40dc7dfb8c19671708bc](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/commit/5e17380b2026efdf994a40dc7dfb8c19671708bc) this line was added:

> Only **SQL_Latin1_General_CP1_CI_AS** is valid for the server and database collation.

This makes the documentation unclear and conflicting since it now states only a SQL collation is supported however a windows collation is recommended.

**Comment by sericks007** [comment]
@TomVergote, thanks for posting this!

@PeterRFriis, can you please update the [System requirements for on-premises deployments](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/system-requirements-on-prem.md) article.

**Comment by tonyafehr** [comment]
Bug 280754 has been logged to track this issue.

**Comment by josaw1** [comment]
BUG 437647 created to replace the item above.

**Comment by PeterRFriis** [comment]
I have removed the conflicting section with the windows server collation.
In practice there is not a conflicting statement, as we only support english windows and there the default collation of that is SQL_Latin1_General_CP1_CI_AS.
But to avoid confusion going the windows part will be removed.
this will be corrected as part of https://review.docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/system-requirements-on-prem?toc=/dynamics365/commerce/toc.json&branch=perahlff%2F2wayTrust#domain-requirements
