### ISSUE TITLE
Configure Maintenance Mode not available anymore in LCS

### ISSUE THREAD

**Issue by pturegano** [MicrosoftDocs/dynamics-365-unified-operations-public#710]
The "Configure Maintenance Mode" is not available in LCS anymore (14th December to 2018).

"Go to the environment details page and on the Maintain menu and click Configure Maintenance Mode. This menu item will display for customers added to the preview."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f2a8d7e-56e8-2ef5-b7a1-4ccf54a6ce1e
* Version Independent ID: 985efdc1-7b47-ad77-4eb9-7bd940547843
* Content: [Maintenance mode - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/sysadmin/maintenance-mode)
* Content Source: [articles/dev-itpro/sysadmin/maintenance-mode.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/sysadmin/maintenance-mode.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @manalidongre
* Microsoft Alias: **manado**

**Comment by tonyafehr** [comment]
@pturegano, thanks for posting this! In the meantime, to get product help you can contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

**Comment by tonyafehr** [comment]
Bug 280762 has been logged to track this issue.

**Comment by manalidongre** [comment]
This feature is generally available and is widely used by everyone. Please log a support ticket if it doesn't show up.
