### ISSUE TITLE
LCS

### ISSUE THREAD

**Issue by Mads-Bech** [MicrosoftDocs/dynamics-365-unified-operations-public#711]
Is it still possible to create an Ax2012 project in LCS?
I only seem to have 365-related project types to choose from?

This is a great tool - if LCS still supports it .. :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b8837ed-94cc-aec1-03db-b0d9f1ac25f6
* Version Independent ID: 6f44df6c-005a-3002-0ed0-fae33da185f7
* Content: [Install and run System diagnostics - AX 2012](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/ax-2012/install-run-system-diagnostics-lcs)
* Content Source: [articles/dev-itpro/lifecycle-services/ax-2012/install-run-system-diagnostics-lcs.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/lifecycle-services/ax-2012/install-run-system-diagnostics-lcs.md)
* Product: **dynamics-ax-2012**
* GitHub Login: @manalidongre
* Microsoft Alias: **manado**

**Comment by tonyafehr** [comment]
Bug 280764 has been logged to track this issue.

**Comment by tonyafehr** [comment]
@Mads-Bech, thanks for making us aware of this.

@manalidongre, please update this topic based on the feedback.

**Comment by hariharasudan-k** [comment]
As per the above step we configured everything perfectly, we get Environment detailed(Job,collectors) in system diagnostics(LCS) working fine, while taking report in Power BI dashboard against the project "https://diag.lcs.dynamics.com/UpgradeAnalysisReport/Report/project Id" we getting blank upgrade analysis power BI dashboard.

**Comment by hariharasudan-k** [comment]
Showing blank data in Upgrade analysis report (Power BI report) for system diagonistics against the project.
"https://diag.lcs.dynamics.com/UpgradeAnalysisReport/Report/projectID"
