### ISSUE TITLE
Task Recordings will not save because I can't select anywhere to save it to

### ISSUE THREAD

**Issue by joecrofts** [MicrosoftDocs/dynamics-365-unified-operations-public#713]

**Comment by joecrofts** [comment]
I am going through the task recording and I will try and edit a step and after I edited a step I could not select ok or cancel to go back to task steps.  Also I tried to save the task recording and all the options to save are grayed out.  I had this happen in Chrome and in Edge.   

![image](https://user-images.githubusercontent.com/45885766/50028761-920fdd00-ffa5-11e8-8c3a-0b65f3cce074.png)
![image](https://user-images.githubusercontent.com/45885766/50028764-94723700-ffa5-11e8-903e-9752154c2a7a.png)

**Comment by ShylaThompson** [comment]
Hi @joecrofts, we can't provide support in this forum. Can you log a support request and share the ticket number with us so we can track the issue?

To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support).

**Comment by joecrofts** [comment]
Thank you Shyla.  I will enter a support request.
