### ISSUE TITLE
Maintenance mod enable

### ISSUE THREAD

**Issue by Daxture** [MicrosoftDocs/dynamics-365-unified-operations-public#714]
With no SQL server access to tier2+ environments, what option is going to be available to enable maintenance mode for tier2+ sandbox environments?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e00de89b-6d2a-b3d2-24d1-e56c5f02d052
* Version Independent ID: 4145fdd6-b293-49b3-94da-dddcfc9fc669
* Content: [Self-service deployment - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/deployment/infrastructure-stack)
* Content Source: [articles/dev-itpro/deployment/infrastructure-stack.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/deployment/infrastructure-stack.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @sarvanisathish
* Microsoft Alias: **sarvanis**

**Comment by sericks007** [comment]
@Daxture, thanks for posting this!

@sarvanisathish, can you please respond to this question and update the topic if necessary.

**Comment by sarvanisathish** [comment]
We are working on self-service feature for maintenance mode. This will become available in January 2019.

**Comment by mrjdomingus** [comment]
Hi, as to "You will continue to have SQL database access using just-in-time access", can you provide a link to a page containing more information about the "just-in-time access" mechanism? Or is this something that is still in development?
