### ISSUE TITLE
External API Consumption with Azure Active Directory authentication

### ISSUE THREAD

**Issue by DynamicsArvindSingh** [MicrosoftDocs/dynamics-365-unified-operations-public#731]
Hi Guys,
Can you update the Microsoft documentation for the logic to consume the .Net based external web APIs with Azure Active Directory authentication in Microsoft Dynamics 365 Finance & Operation using X++ code? Can you please provide sample Code examples for the same?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3e8a936-3bef-b844-e935-adfadd03516f
* Version Independent ID: 53cc6e3a-a62e-be0f-dba1-38f62394ee0e
* Content: [Consume external web services in Finance and Operations - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/consume-external-web-service)
* Content Source: [articles/dev-itpro/data-entities/consume-external-web-service.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/consume-external-web-service.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by tonyafehr** [comment]
@DynamicsArvindSingh, thanks for the feedback. 

@Sunil-Garg, can you review and update the topic if necessary? Bug 280780 has been logged to track this issue.

**Comment by DynamicsArvindSingh** [comment]
Hi Guys,

Recieved no update on this. its been 3 months.

Please update this document.
