### ISSUE TITLE
Intrastat

### ISSUE THREAD

**Issue by leveret64** [MicrosoftDocs/dynamics-365-unified-operations-public#733]
Followed the comments from; https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/localizations/tasks/transfer-transactions-intrastat

using Installed product version : Microsoft Dynamics 365 for Finance and Operations, Enterprise edition (7.3)
Installed platform version : Update12 (7.0.4709.41124)
This product is licensed to:
d365try.onmicrosoft.com
Serial number: eb84c22f-b952-4ca4-9306-54b39cee72db

and there is nothing to select from the lookup against the released product. please feedback. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85a5eb7a-3e08-5770-f406-41e3cf0ed9e5
* Version Independent ID: 70b1259d-7e99-622c-2bd5-7880c1373dd2
* Content: [Transfer transactions to the Intrastat - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/localizations/tasks/transfer-transactions-intrastat)
* Content Source: [articles/financials/localizations/tasks/transfer-transactions-intrastat.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/localizations/tasks/transfer-transactions-intrastat.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @Anasyash
* Microsoft Alias: **anasyash**

**Comment by ShylaThompson** [comment]
@Anasyash please review this documentation issue and update the topic if needed.

**Comment by tonyafehr** [comment]
Bug 280778 has been logged to track this issue.

**Comment by Anasyash** [comment]
Hello. Thanks for your comment. Can you please describe your issue in more details so that we can update the article accordingly.

**Comment by leveret64** [comment]
Sure
Because of the limited setup you are allowing in the version you are showing, there is a parameter setting which is not set, in which case you are not able to investigate the intrastat options of the product.

    On Monday, 7 January 2019, 15:23:06 GMT, Anastasia Yashenina <notifications@github.com> wrote:  
 
 
Hello. Thanks for your comment. Can you please describe your issue in more details so that we can update the article accordingly.

**Comment by Anasyash** [comment]
Unfortunately it's not becoming more clear.
Please describe more precise, what exactly in this help content you suggest to update. Also, please make sure that here you are giving only a feedback for the docs topic, not for the feature itself. If you are looking for technical assistance for system setup, or want to provide feedback about functionality, please log a support ticket.

**Comment by Anasyash** [comment]
Please review these 2 task guides:

https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/localizations/tasks/transfer-transactions-intrastat

https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/localizations/tasks/eur-00002-eu-intrastat-declaration

May be they will help to run the feature end-to-end.

If not, please be more precise in which step \ paragraph of the content topic you observe a different behavior in the system comparing to what is written in the article. Thanks.

**Comment by leveret64** [comment]
Thank you for that, bt from the demo environment provided, I do not have access to certain parameter setting, so do not know whether the documents are incorrect or whether it is the setup of the environment.  I previously supplied you with a link to the trial environment provided.
Thanks

    On Tuesday, 8 January 2019, 14:12:33 GMT, Anastasia Yashenina <notifications@github.com> wrote:  
 
 
Please review these 2 task guides:

https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/localizations/tasks/transfer-transactions-intrastat

https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/localizations/tasks/eur-00002-eu-intrastat-declaration

May be they will help to run the feature end-to-end.

If not, please be more precise in which step \ paragraph of the content topic you observe a different behavior in the system comparing to what is written in the article. Thanks.

**Comment by ShylaThompson** [comment]
The topic is complete. Please log a support request for further assitance.
