### ISSUE TITLE
Discuss different run options

### ISSUE THREAD

**Issue by SST1982** [MicrosoftDocs/dynamics-365-unified-operations-public#734]
It would be helpful to have an official description what the different run options do, what are the differences, pros and cons. In data import projects we have four different menu items for starting the import:
1) Import-Button on the ActionPane
2) Import now
3) Import in batch
4) Re-import

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a195670e-6d06-370a-1776-9be0c30ac8f8
* Version Independent ID: b4072fa9-25c8-8a11-16ec-ffa0ca10f9a5
* Content: [Data import and export jobs - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/data-import-export-job?toc=/fin-and-ops/toc.json)
* Content Source: [articles/dev-itpro/data-entities/data-import-export-job.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/data-import-export-job.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by tonyafehr** [comment]
@SST1982, thanks for the feedback.

@Sunil-Garg, can you review and update the topic if necessary. Bug 280782 has been logged to track this issue.

**Comment by tonyafehr** [comment]
@SST1982, this topic has been updated to reflect your suggested changes. Changes will be published early this week.
