### ISSUE TITLE
Login failed to user ..... 

### ISSUE THREAD

**Issue by eporras23** [MicrosoftDocs/dynamics-365-unified-operations-public#738]
tried to follow the steps creating a devtempuser and a User6bc36843341de1 user. But when try to debug from visual studio we get the error 

"cannot open database "uat_axdb_90ac268941114e1" requested by the login. The login failed. Login failed for user build98155552-1\User6bc36843341de1 when try to connect to business database to provided configuration"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 146fecc8-6786-266e-2a47-d8c96883e837
* Version Independent ID: a7592d6b-7bd8-1d41-95b5-5b4ebae1b59d
* Content: [Debug X++ against copies of production databases - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-tools/debug-x-issue-against-copy-of-production)
* Content Source: [articles/dev-itpro/dev-tools/debug-x-issue-against-copy-of-production.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-tools/debug-x-issue-against-copy-of-production.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @tariqbell
* Microsoft Alias: **tabell**

**Comment by kfend** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
