### ISSUE TITLE
Export: limit for the file size

### ISSUE THREAD

**Issue by Rardd1997** [MicrosoftDocs/dynamics-365-unified-operations-public#740]
In Export process troubleshooting articles, you say, that we have 256 MB limit for the file size that can be handled via export. It is a limit for .zip package or limit for source file which will be packed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c6788e8-dfb0-6108-71ae-e265bad542a2
* Version Independent ID: 68a26703-3d8c-4d46-6f3f-37c30aa79373
* Content: [Data management - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/data-entities-data-packages)
* Content Source: [articles/dev-itpro/data-entities/data-entities-data-packages.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/data-entities-data-packages.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by tonyafehr** [comment]
@Rardd1997, thanks for posting this question. 

@Sunil-Garg, please review and update the topic if needed. Bug 280810 has been logged to track this issue.

**Comment by Sunil-Garg** [comment]
Rardd1997, the limitation is to the total file size (file or package) that is uploaded to the blob storage. This can be a single excel file as an example of a data package zip file. Hope this clarifies.
Thanks.
