### ISSUE TITLE
Relay

### ISSUE THREAD

**Issue by robintheswede** [MicrosoftDocs/dynamics-365-unified-operations-public#741]
Hi, how come you have not mentioned the option to use an SMTP relay? Please provide information about this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3474f86-38f0-8d1c-87fb-ba192e0a8adb
* Version Independent ID: 4c64163d-e9b2-0966-b67e-ae63f4393215
* Content: [Configure and send email - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/organization-administration/configure-email)
* Content Source: [articles/fin-and-ops/organization-administration/configure-email.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/organization-administration/configure-email.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @ChrisGarty
* Microsoft Alias: **cgarty**

**Comment by sericks007** [comment]
Bug 280816 has been logged to track this issue.

**Comment by ChrisGarty** [comment]
SMTP relay is one of many SMTP options. Whether it is an SMTP server assigned to the user or a relay, the settings are not too different, but the configuration of the server is quite different.
