### ISSUE TITLE
Data integration always fail for D365 Ops and Fin with newer platform update 

### ISSUE THREAD

**Issue by winbrother** [MicrosoftDocs/dynamics-365-unified-operations-public#743]
It seems to us that for D365 Ops and Finance, if we have platform update:
- version 15: users will always get either "Bad request error to D365" or "the data value violate integrity constraints"
- version 20 or above: the integration projects (using template) will always complete, but no data will be delivered at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96ad26d7-2a8a-03a5-f742-740f941a5a5b
* Version Independent ID: 0b9c2d3d-a699-71d5-5b03-000e27d0ae28
* Content: [Prospect to cash - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/sales-marketing/prospect-to-cash)
* Content Source: [articles/supply-chain/sales-marketing/prospect-to-cash.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/sales-marketing/prospect-to-cash.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @ChristianRytt
* Microsoft Alias: **crytt**

**Comment by kfend** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
