### ISSUE TITLE
Where to define a number sequence per Customer Group? 

### ISSUE THREAD

**Issue by AXcademy** [MicrosoftDocs/dynamics-365-unified-operations-public#747]
I must have overlooked something.

"You can also set up customer number sequences for each customer group."

How is this possible, please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9c3af4f-aa47-fb1b-4e89-cba689ed93c5
* Version Independent ID: cd2487c5-b203-34be-c5ed-06439b82e0f1
* Content: [Copy customers by using shared number sequences - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/accounts-receivable/copy-customer)
* Content Source: [articles/financials/accounts-receivable/copy-customer.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/accounts-receivable/copy-customer.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @mikefalkner
* Microsoft Alias: **mikefalkner**

**Comment by mikefalkner** [comment]
@axcademy    When you change the customer sequence to a global number sequence,  you will see an additional column on the Customer groups page called Customer accounts number sequence. Add a sequence there. That sequence will be used first. If it is blank, then it will default to the number sequence in the parameters.
