### ISSUE TITLE
Not enough space on DEV VM to restore the database

### ISSUE THREAD

**Issue by sbaber82** [MicrosoftDocs/dynamics-365-unified-operations-public#748]
Hi,

As part of database upgrade, I have uploaded the AX 2012 database backup to Azure storage and then downloaded it to D365 DEV VM. Now when I tried to restore the database to SQL server, I found that there is not enough disk space on DEV VM to restore the database.  The AX 2012 Production database size is around 250 GB. Is there a way to increase the disk space on D365 DEV VM or do I need to raise a support request to get this done.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f408443a-7381-120f-9a42-4a394db4c284
* Version Independent ID: 5ec84f24-c0dd-7ddb-7374-99227632dcb2
* Content: [Upgrade from AX 2012 - Data upgrade in development environments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/data-upgrade-2012)
* Content Source: [articles/dev-itpro/migration-upgrade/data-upgrade-2012.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/migration-upgrade/data-upgrade-2012.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @tariqbell
* Microsoft Alias: **tabell**

**Comment by sericks007** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support).
