### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by TrudAX** [MicrosoftDocs/dynamics-365-unified-operations-public#753]
It seems link is broken in the following sentence "Install your favorite development tools. For information about one automated script, see Auto-Installing most needed dev tools in 5 mins with Chocolatey" 
It displays empty windows
(https://dynamicsnotes.com/auto-installing-most-needed-dev-tools-in-5-mins/)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b9cd3cc-5f85-3f61-4670-83e050cb30e4
* Version Independent ID: 313ff91b-902d-7f27-f9b1-6aa4d2370945
* Content: [Set up new environments, Azure DevOps, and branches for Retail projects - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/dev-itpro/new-environments-visual-studio-teams-branch-retail-projects#prepare-the-development-environment)
* Content Source: [articles/retail/dev-itpro/new-environments-visual-studio-teams-branch-retail-projects.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/dev-itpro/new-environments-visual-studio-teams-branch-retail-projects.md)
* Service: **dynamics-365-retail**
* GitHub Login: @andreash1
* Microsoft Alias: **andreash**

**Comment by tonyafehr** [comment]
@TrudAX, thanks for bringing this to our attention. 
@andreash1, please update the broken link in this topic.

**Comment by tonyafehr** [comment]
This link has been fixed. Thanks!
