### ISSUE TITLE
Firewall rules

### ISSUE THREAD

**Issue by stefanfranken** [MicrosoftDocs/dynamics-365-unified-operations-public#755]
When running DRA on local network server with restricted internet access, we need a list of all Internet-IPs which needs to be opened in firewall for port 443. There is of course the D365FO URL, but what about AAD-authentication infrastructure, akamai-cdn,  etc.? Is it possible to have a documentation about all IP-addresses which are involved in communication?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2128b07d-7349-6642-f05f-c94fe800d104
* Version Independent ID: 0568d0d1-8035-3423-f791-7bd82a5d070f
* Content: [Install the Document Routing Agent to enable network printing - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/install-document-routing-agent)
* Content Source: [articles/dev-itpro/analytics/install-document-routing-agent.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/install-document-routing-agent.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by tonyafehr** [comment]
@stefanfranken, thanks for posting this! 

@TJVass, please review and update the topic as suggested.

**Comment by TJVass** [comment]
Thanks for the question.  Not sure exactly how to accommodate this requirement.  DRA communications to Azure Services and F&O webserver use port 443.  However, the Azure service endpoints don't utilize static IP addresses.  Perhaps, domain name restrictions would work instead.
