### ISSUE TITLE
What about Dynamics 365 for operations on-prem?

### ISSUE THREAD

**Issue by diab-mossa** [MicrosoftDocs/dynamics-365-unified-operations-public#759]
Does this apply on Dynamics 365 for operations on-prem?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66b4c899-c7e0-0406-0d39-d32fc41b6104
* Version Independent ID: 5d015069-177d-e33c-094c-257df088a7c0
* Content: [Install metadata hotfixes in development environments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/install-metadata-hotfix-package)
* Content Source: [articles/dev-itpro/migration-upgrade/install-metadata-hotfix-package.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/migration-upgrade/install-metadata-hotfix-package.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RobinARH
* Microsoft Alias: **robadawy**

**Comment by ShylaThompson** [comment]
@robadawy can you review and comment?

**Comment by sericks007** [comment]
@sarvanisathish, can you please answer this question.

Bug 282874 has been logged to track this issue.

**Comment by PeterRFriis** [comment]
I have just read the documentation.
The process is the same for Onprem/LBD with the regards, that changes needs to be tested on a vm and then a deployable package should be created, which can then be taken to LCS and be deployed to the LBD environment.

The process described does not describe how a package is deployed to the actual LBD environments(sandboxes or prod).
