### ISSUE TITLE
Different Mins per product option?

### ISSUE THREAD

**Issue by DaveC123** [MicrosoftDocs/dynamics-365-unified-operations-public#762]
Very nice but I have a more dynamic warehouse situation out here maybe.  Instead of setting the min for all items to 50 in the example above, "Work Template", how or where do I set the min per item per bin?  depending on forecasts and actual sales, each bin should have a minimum quantity established, which are typically all very different minimums.  If the quantity is less than that "min", I want to get replenishment work.  Also, I would run the query per zone or grouping of pick bins.  Can D365FO do this and if so how?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82ec4b05-8c85-2d44-c716-b93798e460f8
* Version Independent ID: a0e18005-ab75-46ed-feb9-1b38f88f8fd7
* Content: [Set up a min-max replenishment process - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/warehousing/tasks/set-up-min-max-replenishment-process)
* Content Source: [articles/supply-chain/warehousing/tasks/set-up-min-max-replenishment-process.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/warehousing/tasks/set-up-min-max-replenishment-process.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @perlynne
* Microsoft Alias: **perlynne**

**Comment by ShylaThompson** [comment]
@perlynne can you review and comment?

**Comment by perlynne** [comment]
If I understand the business requirements correct this can be achieved by enabling “Replenishment templates details" per product via the ‘Select products’ query and limit the zones to be replenished via the ‘Select locations to replenish’ query.
The "Work templates" is used to define how the replenishment items are going to be picked and put, and the "Location directives" will control from where the items can be picked for the min/max replenishment.
New advanced replenishment processes related to zone threshold replenishment is planned to get released as preview in May.
