### ISSUE TITLE
No updates available

### ISSUE THREAD

**Issue by 6a6kin** [MicrosoftDocs/dynamics-365-unified-operations-public#764]
We've deployed new 8.1.2 PU22 development machine for upgrade needs.
Our current DEV and UAT machines are 8.0 PU20.

Article says that we should apply updates to new 8.1.2 machine and use this package as basement for upgrade old machine:
"we recommend the above approach of taking the latest updates such as 8.1.3 PU23 which will be available from the Update tiles when you deploy your 8.1 PU20 build server."

At this moment we see zero on Updates tile for new 8.1.2 machine.

Does it means that we need to use 8.1.2 package from Shared asset library to merge with our custom package and use it to upgrade our old machines?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b3b5ec6-1a21-e71a-df38-ba497f7f1116
* Version Independent ID: d1e49823-7934-6a3a-50e1-547cdd632077
* Content: [Update environments from version 8.0 to 8.1.X - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/appupdate-80-81)
* Content Source: [articles/dev-itpro/migration-upgrade/appupdate-80-81.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/migration-upgrade/appupdate-80-81.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by tonyafehr** [comment]
@6a6kin, thanks for taking the time to provide feedback on our documentation. I've passed your comment on to the author of this topic. If you need immediate assistance, please contact Support. consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

**Comment by laneswenka** [comment]
@6a6kin yes that is an acceptable secondary approach.  The tiles will only be "0" for a matter of days as we may introduce point hotfixes on PU22 or we may start rolling out 8.1.3 and PU23.  

There is a brief period of time where it can be "0" on your tiles and you'll need to pull the package that matches your Build Server's environment version from the Shared Asset Library.

I'll try to update the docs accordingly as I can see where it is confusing to have 2 possible locations depending on the timing of your environment's creation.  You were, however, thinking about things exactly correct!

**Comment by 6a6kin** [comment]
@tonyafehr @laneswenka Thank you very much for such rapid and very informative answer!
