### ISSUE TITLE
It seems the article is not finished

### ISSUE THREAD

**Issue by vavd** [MicrosoftDocs/dynamics-365-unified-operations-public#766]
The last line of the article looks like a header of a section which doesn't have any content.
Is the article finished? 
I cannot see in the article any explanation how to generate an ISO payment file.
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c086b6d2-2a56-6f80-ea82-31987c0dadb3
* Version Independent ID: e1913e51-e263-cf1a-fa5b-402649ae2611
* Content: [Create and export vendor payments using ISO20022 payment format - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/localizations/tasks/create-export-vendor-payments-iso20022-payment-format#generate-an-iso20022-payment-file)
* Content Source: [articles/financials/localizations/tasks/create-export-vendor-payments-iso20022-payment-format.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/localizations/tasks/create-export-vendor-payments-iso20022-payment-format.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @mrolecki
* Microsoft Alias: **mrolecki**

**Comment by tonyafehr** [comment]
@vavd, thanks for the feedback. @ShylaThompson, can you investigate and re-assign if needed. Thanks!

**Comment by sericks007** [comment]
Bug 283734 has been logged to track this issue.

**Comment by ShylaThompson** [comment]
@vavd The topic has been updated. Thanks again for bringing this to our attention.
