### ISSUE TITLE
PerfSDK\Common\External\Selenium folder

### ISSUE THREAD

**Issue by rpvanmill** [MicrosoftDocs/dynamics-365-unified-operations-public#767]
Hello,

In all my environments there is no PerfSDK\Common\External\Selenium folder. Where should I put the selenium dll files?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71bd6e91-0511-905a-0e70-b0510d961f16
* Version Independent ID: 4942a200-93f3-6f2b-8a59-b88fdf6e825c
* Content: [Performance SDK and multiuser testing via Visual Studio Online - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/perf-test/perfsdk-tutorial)
* Content Source: [articles/dev-itpro/perf-test/perfsdk-tutorial.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/perf-test/perfsdk-tutorial.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @jujoh
* Microsoft Alias: **jujoh**

**Comment by sericks007** [comment]
@rpvanmill, thanks for posting this! We'll look into it. In the meantime, to get product help you can contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community. 

@jujoh, please review and update the topic, if needed.

**Comment by sericks007** [comment]
Bug 283737 has been logged to track this issue.

**Comment by NadigSrinidhi** [comment]
@rpvanmill, The document is not updated. In the latest version of Dynamics365 (8.0 onwards) you can navigate to K:\PerfSDK\PerfSDKLocalDirectory and create the folder structure on your own. 

Finally, your folder structure should look like :
K:\PerfSDK\PerfSDKLocalDirectory\Common\External\Selenium

Inside selenium folder you can place all your dll files. This is working fine for us on Platform release
Update15 and Application release Microsoft Dynamics 365 for Finance and Operations (8.0)

**Comment by RobinARH** [comment]
@kennysaelen - Hi Kenny - Can you take a look at this one? Thanks.
