### ISSUE TITLE
AxTokenIssuer

### ISSUE THREAD

**Issue by rpvanmill** [MicrosoftDocs/dynamics-365-unified-operations-public#768]
Hello,

In my wif.config file there is no authority 'AxTokenIssuer'. Where should I add the tumbprint of the certificate?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71bd6e91-0511-905a-0e70-b0510d961f16
* Version Independent ID: 4942a200-93f3-6f2b-8a59-b88fdf6e825c
* Content: [Performance SDK and multiuser testing via Visual Studio Online - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/perf-test/perfsdk-tutorial)
* Content Source: [articles/dev-itpro/perf-test/perfsdk-tutorial.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/perf-test/perfsdk-tutorial.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @jujoh
* Microsoft Alias: **jujoh**

**Comment by sericks007** [comment]
Bug 283738 has been logged to track this issue.

**Comment by NadigSrinidhi** [comment]
@rpvanmill, You can add the Thumbprint under authority name="https://fakeacs.accesscontrol.windows.net/"> it should work

**Comment by NadigSrinidhi** [comment]
@rpvanmill, You can add the Thumbprint under authority name="https://fakeacs.accesscontrol.windows.net/">
It should work

**Comment by hasaid** [comment]
the correct place in wif.config is under authority https://fakeacs.accesscontrol.windows.net

**Comment by sericks007** [comment]
It looks like @hasaid answered the question, so closing this issue.  Thanks @hasaid!
