### ISSUE TITLE
PBIX File availibility

### ISSUE THREAD

**Issue by kmescha** [MicrosoftDocs/dynamics-365-unified-operations-public#769]
This article mentions the availability of the .pbix file that is used for the Financial Insights dashboards but does not reference where this is available from. Can that be included here or can a subsequent article be linked from this?  Understand that modifications will be overwritten with future releases but we have current needs to modify these dashboards now and can't wait for the roadmap features to become available.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 604a288a-aa59-427e-f872-acfde0c5d5b5
* Version Independent ID: aee7aa7c-0f43-3f46-6fda-b66da38b36f0
* Content: [Financial Insights - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/financial-insights)
* Content Source: [articles/dev-itpro/analytics/financial-insights.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/financial-insights.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @kweekley
* Microsoft Alias: **kweekley**

**Comment by sericks007** [comment]
@kmescha, thanks for posting this!

@kweekley, please review and update the topic as necessary.

**Comment by sericks007** [comment]
Bug 283739 was logged to track this issue.

**Comment by davecope1982** [comment]
is the pbix now available as a resource?

**Comment by sqldaniel** [comment]
Dave, you can find the PBIX file as "FinancialInsights.PBIX" directly in the AOT. Use any Dev/Test or Tier 1 machine in your D365 FO environment.

**Comment by kweekley** [comment]
Daniel is correct that the .pbix is available in the Resources within the AOT.
