### ISSUE TITLE
Common Issues Section

### ISSUE THREAD

**Issue by kmescha** [MicrosoftDocs/dynamics-365-unified-operations-public#770]
In the common issues section the 2nd item around "You can't access the application" the resolution indicates "Step 3 Choose API's to access" is not clear as there are multiple Step 3 sections in this document and note describe Choosing API's. 

Please clarify this more.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 717d397d-4186-c7de-431d-3260d3f0484a
* Version Independent ID: bdd7545b-5970-93e0-5cbb-a59da4ace01b
* Content: [Configure Power BI integration for workspaces - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/configure-power-bi-integration)
* Content Source: [articles/dev-itpro/analytics/configure-power-bi-integration.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/configure-power-bi-integration.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by sericks007** [comment]
Bug 283740 has been logged to track this issue.

**Comment by MilindaV2** [comment]
updated the document
