### ISSUE TITLE
Entity Store Section

### ISSUE THREAD

**Issue by kmescha** [MicrosoftDocs/dynamics-365-unified-operations-public#772]
In the entity store section of this document it references 7 entities to update. However in my system I don't see these 2 available to update. Is this list accurate?

FinancialReportingOtherData
FinancialReportingReferenceData

Here is my version information

VERSION INFORMATION
Installed product version : Microsoft Dynamics 365 for Finance and Operations (8.0)
Installed platform version : Update20 (7.0.5030.41321)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 604a288a-aa59-427e-f872-acfde0c5d5b5
* Version Independent ID: aee7aa7c-0f43-3f46-6fda-b66da38b36f0
* Content: [Financial Insights - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/financial-insights)
* Content Source: [articles/dev-itpro/analytics/financial-insights.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/financial-insights.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @kweekley
* Microsoft Alias: **kweekley**

**Comment by tonyafehr** [comment]
@kmescha, thanks for posting this! We'll look into it. In the meantime, to get product help you can contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community. 

@kweekley, please review and update this topic, if needed.

**Comment by sericks007** [comment]
Bug 283741 has been logged to track this issue.

**Comment by sericks007** [comment]
The topic was recently fixed to resolve this issue.
