### ISSUE TITLE
Data entity selection

### ISSUE THREAD

**Issue by Darijaus** [MicrosoftDocs/dynamics-365-unified-operations-public#775]
quick note - package unfortunately does not pick up entity automatically you need to also pick Data Sharing Policy manually to load package from LCS. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95f6ee35-c974-43c9-b81d-1feecc3a57af
* Version Independent ID: d4318b39-c9cd-6f8f-95bd-19a555c600bd
* Content: [Configure financial cross-company data sharing - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/Dynamics365/unified-operations/dev-itpro/data-entities/tasks/configure-financial-cross-company-data-sharing?toc=/fin-and-ops/toc.json)
* Content Source: [articles/dev-itpro/data-entities/tasks/configure-financial-cross-company-data-sharing.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/tasks/configure-financial-cross-company-data-sharing.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @aprilolson
* Microsoft Alias: **aolson**

**Comment by sericks007** [comment]
@Darijaus, thanks for making us aware of this.

@aprilolson, please update the topic as necessary.

**Comment by tonyafehr** [comment]
Bug 285241 has been logged to track this issue.
