### ISSUE TITLE
Under 365, but is prerelased AX 2012 documentation

### ISSUE THREAD

**Issue by amadse** [MicrosoftDocs/dynamics-365-unified-operations-public#785]
Either this one should be updated to reflect how it works in Dyn365Fo or it should be removed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 247ec037-454d-0371-5b33-35e36d355cb6
* Version Independent ID: 33e0d33f-7293-7a77-51e7-acf2dc3f7e45
* Content: [Define or edit entry point permissions - AX 2012](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/ax-2012/define-edit-entry-point-permissions)
* Content Source: [articles/dev-itpro/lifecycle-services/ax-2012/define-edit-entry-point-permissions.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/lifecycle-services/ax-2012/define-edit-entry-point-permissions.md)
* Product: **dynamics-ax-2012**
* GitHub Login: @kfend
* Microsoft Alias: **kfend**

**Comment by sericks007** [comment]
@amadse, thanks for bring this to our attention.

@manalidongre, should this topic be removed or updated?

**Comment by tonyafehr** [comment]
Bug 285242 has been logged to track this issue.
