### ISSUE TITLE
Dev ALM blog link dead

### ISSUE THREAD

**Issue by marihul** [MicrosoftDocs/dynamics-365-unified-operations-public#793]
The link to the "Dev ALM blog" is dead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18d6a0b7-38dc-ddcd-c495-67e3b7498a7c
* Version Independent ID: 36a6bc94-6939-9daf-ad3d-4e0064258172
* Content: [Create user acceptance test libraries by using task guides and BPM - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/using-task-guides-and-bpm-to-create-user-acceptance-tests)
* Content Source: [articles/dev-itpro/lifecycle-services/using-task-guides-and-bpm-to-create-user-acceptance-tests.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/lifecycle-services/using-task-guides-and-bpm-to-create-user-acceptance-tests.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @kfend
* Microsoft Alias: **ntecklu**

**Comment by kfend** [comment]
I have removed the link. Changes will be published in the next 24 hours.
