### ISSUE TITLE
Corrections required in Run to a Breakpoint section.

### ISSUE THREAD

**Issue by tomhig** [MicrosoftDocs/dynamics-365-unified-operations-public#796]
Step 6. The Startup Project needs to be FleetManagement, not FleetManagementMigrated. In addition, the FMRental_Upcoming Display Menu item needs to be set as the Startup Object. 

Step 7. Needs to refer to the FleetManagement project, not FleetManagementMigrated project.

Step 11. It needs to state "The Current Rentals page will already be open in a new browser window". Sub-steps a, b, c, and d need to be deleted. Step d, which would now be a, should simply say "In the action pane, click Edit". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1906ec8-f80b-4e27-7320-57c68664e482
* Version Independent ID: ab8d0951-67fe-3064-0f29-2524774e5b3c
* Content: [Build and debug projects - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-tools/build-debug-project)
* Content Source: [articles/dev-itpro/dev-tools/build-debug-project.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-tools/build-debug-project.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @pvillads
* Microsoft Alias: **pvillads**

**Comment by tonyafehr** [comment]
Bug 288970 has been logged to track this issue.

**Comment by tonyafehr** [comment]
@tomhig, thanks for making us aware of this! I've fixed the issue, and an updated version of the page will be published soon.
