### ISSUE TITLE
FMLab folder reference in last paragraph

### ISSUE THREAD

**Issue by tomhig** [MicrosoftDocs/dynamics-365-unified-operations-public#797]
The FMLab folder is now found at https://github.com/Microsoft/FMLab. There isn't a Code Best Practice Example folder there. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1906ec8-f80b-4e27-7320-57c68664e482
* Version Independent ID: ab8d0951-67fe-3064-0f29-2524774e5b3c
* Content: [Build and debug projects - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-tools/build-debug-project)
* Content Source: [articles/dev-itpro/dev-tools/build-debug-project.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-tools/build-debug-project.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @pvillads
* Microsoft Alias: **pvillads**

**Comment by sericks007** [comment]
Bug 285577 has been logged to track this issue.
