### ISSUE TITLE
Typo: To remove a node, right-click the new

### ISSUE THREAD

**Issue by Pankaj-Thakur** [MicrosoftDocs/dynamics-365-unified-operations-public#807]
"To remove a node, right-click the new, and then click Delete." should read "To remove a node, right-click the node, and then click Delete."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14e80549-5728-5a8d-960f-05998fa7e20b
* Version Independent ID: 57046b27-2d36-00f4-ee2d-e56c43e29cbf
* Content: [Element designers - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-tools/element-designers)
* Content Source: [articles/dev-itpro/dev-tools/element-designers.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-tools/element-designers.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RobinARH
* Microsoft Alias: **robadawy**

**Comment by tonyafehr** [comment]
@Pankaj-Thakur, thanks for the feedback. I will update this topic.
