### ISSUE TITLE
Developer ALM (blog) Link is broken

### ISSUE THREAD

**Issue by maveloso** [MicrosoftDocs/dynamics-365-unified-operations-public#808]
the developer ALM blog link leads to a page not found

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 201c7886-7fc8-f381-818e-1a611b909c33
* Version Independent ID: 968af3e2-1c8a-3bba-6b52-ca984f5ad515
* Content: [Continuous delivery home page - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-tools/continuous-delivery-home-page)
* Content Source: [articles/dev-itpro/dev-tools/continuous-delivery-home-page.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-tools/continuous-delivery-home-page.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RobinARH
* Microsoft Alias: **robinr**

**Comment by ShylaThompson** [comment]
@maveloso I tested all of the links in the topic and it looks like they all work. I'm going to close this issue.
