### ISSUE TITLE
RunBase vs SysOperation

### ISSUE THREAD

**Issue by jaestevan** [MicrosoftDocs/dynamics-365-unified-operations-public#810]
May the point "Batch processing classes" be obsolete in favor of SysOperation classes? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eaf8b5a7-5678-8263-16af-0bb35fc72f26
* Version Independent ID: a28d68c0-313f-eab6-87c8-ffa3ce7a7125
* Content: [X++ classes and methods - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-ref/xpp-classes-methods#batch-processing-classes)
* Content Source: [articles/dev-itpro/dev-ref/xpp-classes-methods.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-ref/xpp-classes-methods.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RobinARH
* Microsoft Alias: **robinr**

**Comment by tonyafehr** [comment]
@jaestevan, I've assigned your question to @robadawy, who can provide more details about this. Thanks!

**Comment by ChrisGarty** [comment]
I can't see a mention of "Batch processing classes" in https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-ref/xpp-classes-methods#batch-processing-classes
Batch processing classes are still used for batch processing: https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/batch-processing-overview

**Comment by jaestevan** [comment]
Well this bug is almost a year old already :)

The section does not even exists on the current version of the doc (not sure if that's the correct doc page when I found the issue originally), so I guess this can be clossed.

Thanks,
JA.
