### ISSUE TITLE
Its globally available now please review the banner

### ISSUE THREAD

**Issue by fgork** [MicrosoftDocs/dynamics-365-unified-operations-public#813]
The update is available globally but the banner that says as below is still there.
"Functionality noted in this topic is available to targeted users as part of a preview release. "

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28023f28-4aa0-18fd-b5fd-c2cc5f117f0b
* Version Independent ID: fe115611-d105-3b1d-f630-2df5398af447
* Content: [What's new or changed in Dynamics 365 for Finance and Operations platform update 23 (January 2019) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/whats-new-platform-update-23)
* Content Source: [articles/fin-and-ops/get-started/whats-new-platform-update-23.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/whats-new-platform-update-23.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @tonyafehr
* Microsoft Alias: **tfehr**

**Comment by tonyafehr** [comment]
@fgork, you are correct. Thanks for the feedback. We'll remove the banner and republish this topic.

**Comment by cdz1126** [comment]
when is the next update?

**Comment by Junaidahm3d** [comment]
I am having issues deploying Dynamics 365 for Finance and Operations version 8.1.3 on 8.1.2 on prem environment with blank db.

8.1.3 is only for cloud ??

**Comment by tonyafehr** [comment]
We're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
