### ISSUE TITLE
automate the task of filling timesheets

### ISSUE THREAD

**Issue by arehman849** [MicrosoftDocs/dynamics-365-unified-operations-public#817]
above document is complete and awesome for doing this painful task manually every week... is there anyway that we can automate this by integrating it with jira tempo sheets. any api exposed so that we can fill timesheets programmatically. any help is appreciated  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51a8b116-2d42-c829-fd06-04dac7593315
* Version Independent ID: b71ff3c5-a5b5-9d28-993b-e112ab262f26
* Content: [Enter project timesheets - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/hr/tasks/enter-project-timesheets)
* Content Source: [articles/fin-and-ops/hr/tasks/enter-project-timesheets.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/hr/tasks/enter-project-timesheets.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @kherr75
* Microsoft Alias: **kherr**

**Comment by sericks007** [comment]
@KimANelson, can you please answer the above questions, and update the topic, if appropriate.

**Comment by KimANelson** [comment]
@arehman849 - this is a great suggestion. Please log it at https://experience.dynamics.com/ideas/ where other users are able to view and vote for their favorite feature requests. This helps us in our planning process for each release.

**Comment by arehman849** [comment]
hey sally erickson / kim nelson,

thanks for the response... as suggested by Kim i have scribbled a huge
story in your ideas section :-)

link :
https://experience.dynamics.com/ideas/idea/?ideaid=2fefa936-891f-e911-9461-0003ff68953b
