### ISSUE TITLE
SQL Index Defragmentation

### ISSUE THREAD

**Issue by JoelLeichty** [MicrosoftDocs/dynamics-365-unified-operations-public#825]
Where's the documentation for the form under System administration &gt; Setup &gt; System job parameters &gt; SQL index defragmentation?

Apparently this schedules a new batch process called "Database index rebuild system job that needs to regularly run at off hours". This kind of batch could potentially conflict with other batches and is undocumented. It seems to be automatically setup when upgrading Platforms.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 468a9fa8-9f3c-7438-7ee2-321218425585
* Version Independent ID: 88b7da84-d9da-aae8-75b2-5b03f09a5914
* Content: [What's new or changed in Dynamics 365 for Finance and Operations platform update 22 (December 2018) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/whats-new-platform-update-22)
* Content Source: [articles/fin-and-ops/get-started/whats-new-platform-update-22.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/whats-new-platform-update-22.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @tonyafehr
* Microsoft Alias: **tfehr**

**Comment by tonyafehr** [comment]
@JoelLeichty, thanks for the feedback. 

@hasaid, please update this topic based on this feedback.

**Comment by tonyafehr** [comment]
Bug 288971 has been logged to track this issue.
