### ISSUE TITLE
Why Does OneBox Not Support Power BI

### ISSUE THREAD

**Issue by aaronstackpole** [MicrosoftDocs/dynamics-365-unified-operations-public#827]
The text says "Because the service relies on Microsoft Azure services, application analytical workspaces and reports are unavailable in one-box environments. " It's not clear why these two things are mutually exclusive. One would think that anything that relies on an abstract cloud-based service would be accessible regardless of environment. Please clarify, and provide any update on the roadmap to get this service working. Particularly now since Workspaces are gone.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 007a29aa-32bb-bc2e-8c92-aba6cd87aa5d
* Version Independent ID: 8fb71831-2bd7-2d08-9505-0af1e071eb34
* Content: [Power BI Embedded integration - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/power-bi-embedded-integration?toc=/fin-and-ops/toc.json)
* Content Source: [articles/dev-itpro/analytics/power-bi-embedded-integration.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/power-bi-embedded-integration.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by ShylaThompson** [comment]
@TJVass please review and update the topic if necessary.

**Comment by tonyafehr** [comment]
Bug 288972 has been logged to track this issue.

**Comment by dnast01** [comment]
Any update on this? Its now June 2019 and onebox environment is commonly used for Demo environments and Power Bi is a fundamental part of most demos...

**Comment by tomhig** [comment]
The following blog documents how to configure this, which requires you to manually deploy some components to your own Azure Subscription:
https://community.dynamics.com/365/financeandoperations/b/dynamicsaxbi/archive/2019/02/03/how-to-configure-power-bi-embedded-for-dynamics-365-for-finance-and-operations-one-box-environment

**Comment by aaronstackpole** [comment]
This does not work if your Azure subscription is not grandfathered to allow you to deploy power bi workspace collections.

Sent from mobile
________________________________

**Comment by tomhig** [comment]
Does the template deployment script actually fail when you run it? (Step 2 in the aforementioned blog). If the script runs, but you do not see the resource, it is because the resource is Hidden and you need to check show all resources. You also cannot obtain the Keys through the Azure Portal UI. You need to run the following Shell script to obtain them: https://docs.microsoft.com/en-us/powershell/module/azurerm.powerbiembedded/get-azurermpowerbiworkspacecollectionaccesskeys?view=azurermps-6.13.0

If template deployment script indeed fails, you should be able to request your Azure subscription to be whitelisted, via a support request, so that you can you deploy it.

**Comment by aaronstackpole** [comment]
Ok, if you can request this to be enabled then we're good. Thank you!

Sent from mobile
________________________________

**Comment by tomhig** [comment]
You need to request this by creating a new support ticket via the Azure Portal. The specific request you need to make is to whitelist your subscription for the Power BI Workspace Collection so that you can access Analytical Workspaces in a D365F&O 1Box environment.

**Comment by TJVass** [comment]
Great information here.  The process mentioned by @tohmig is still an option.  An alternative worth considering is described [here](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/select-analytical-workspace) which allows partners to takes advantage of assets hosted on PowerBI.com.
