### ISSUE TITLE
Delaying an upgrade

### ISSUE THREAD

**Issue by taylordgordon** [MicrosoftDocs/dynamics-365-unified-operations-public#829]
Can 10.0 update itself be delayed?  Or does the policy for delaying updates only apply once someone is on 10.0?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14372486-6284-da4b-6bbb-30acd36dd7de
* Version Independent ID: f8301c48-61db-e9e5-aba5-413528cd91d2
* Content: [One Version service updates FAQ - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/one-version)
* Content Source: [articles/fin-and-ops/get-started/one-version.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/one-version.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @meeramahabala
* Microsoft Alias: **meeram**

**Comment by ShylaThompson** [comment]
@meeramahabala can you review this and update the topic if necessary?

**Comment by tonyafehr** [comment]
Bug 288973 has been logged to track this issue.

**Comment by meeramahabala** [comment]
The question above answers this question.
