### ISSUE TITLE
Update Database script missing sysglobalconfiguration

### ISSUE THREAD

**Issue by robabb123** [MicrosoftDocs/dynamics-365-unified-operations-public#831]
In the newly updated "Update Database" script on this page, the following is missing:
update sysglobalconfiguration
set value = 'SQLSERVER'
where name = 'BACKENDDB'
This is needed in order to resolve "Object Server Azure: Exception 3762504530 occurred in session 2, process: w3wp.exe, thread: 6396" or similar in Event Viewer & to allow DB sync to run successfully.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3436fbc8-5bdd-dcdc-f5d3-51caf7b6cd76
* Version Independent ID: af78d3ef-b329-11e9-896a-aa3394f6c77c
* Content: [Copy Finance and Operations databases from Azure SQL Database to SQL Server environments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/copy-database-from-azure-sql-to-sql-server)
* Content Source: [articles/dev-itpro/database/copy-database-from-azure-sql-to-sql-server.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/database/copy-database-from-azure-sql-to-sql-server.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by ShylaThompson** [comment]
@robabb123 thanks for raising this issue.  @laneswenka please review and update the topic as necessary.

**Comment by laneswenka** [comment]
@robabb123 this isn't missing as it is performed by the Export Database Self-Service action.

**Comment by sericks007** [comment]
Closing, per Lane's response.
