### ISSUE TITLE
Database Point-in-Time not Available

### ISSUE THREAD

**Issue by aaronstackpole** [MicrosoftDocs/dynamics-365-unified-operations-public#832]
Currently, you can select Production Point-in-Time or Sandbox Point-in-Time, but you cannot select a DEV environment as a target and Database Point-in-Time is no longer available. Also, there is no "Work Items" tab on the service request page. There is a list of Open Work Items, or "Service requests".

Additionally, it would be useful to have instructions on how to import a database to a DEV environment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3faaae0f-df7a-21ef-b570-a4b82bac5db1
* Version Independent ID: a7b21c3d-22fb-c41d-5f30-40d90698caa7
* Content: [Restore databases in non-production environments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/request-point-in-time-restore)
* Content Source: [articles/dev-itpro/database/request-point-in-time-restore.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/database/request-point-in-time-restore.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @MargoC
* Microsoft Alias: **tabell**

**Comment by tonyafehr** [comment]
@aaronstackpole, thank you for noting the differences between the product and the documentation.  

@laneswenka, please review this and provide additional info, if possible.

**Comment by aaronstackpole** [comment]
I did find another location where the import to dev instructions are located, that portion of the request is not needed. Thank you!
