### ISSUE TITLE
Need sample of report

### ISSUE THREAD

**Issue by soniamatos** [MicrosoftDocs/dynamics-365-unified-operations-public#833]
Hello, it would be very helpful to see how the graphs will look on this report. I'm working with an environment that doesn't have much data but I need to show the users how the report will look. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 867e9d23-090a-106a-4bf8-35a0d37cfd83
* Version Independent ID: d826e1c7-7e02-918f-7a04-ee47028c40ed
* Content: [Purchase spend analysis Power BI content - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/purchase-content-pack-for-power-bi?toc=/fin-and-ops/toc.json)
* Content Source: [articles/dev-itpro/analytics/purchase-content-pack-for-power-bi.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/purchase-content-pack-for-power-bi.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @FrankDahl
* Microsoft Alias: **fdahl**

**Comment by tonyafehr** [comment]
Bug #291721 has been logged to track this issue.

**Comment by tonyafehr** [comment]
Samples have been added to this topic and will be published later today.
