### ISSUE TITLE
Bank format MT940 File format multiple pages issue

### ISSUE THREAD

**Issue by d47447** [MicrosoftDocs/dynamics-365-unified-operations-public#834]
There is an known issue with MT940 bank statement. MS raised LCS ticket, lets hope there will be a solution soon. 
LCS Issue Id: 286776

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 700b2381-9dac-3f94-4cf0-77bffe5fe13c
* Version Independent ID: 4fa5d8a1-ae96-0e70-b1b5-6c97fdac9df9
* Content: [Bank statement file import troubleshooting - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/cash-bank-management/import-bank-statement-file-failed-incorrect-results)
* Content Source: [articles/financials/cash-bank-management/import-bank-statement-file-failed-incorrect-results.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/cash-bank-management/import-bank-statement-file-failed-incorrect-results.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @ShylaThompson
* Microsoft Alias: **saraschi**

**Comment by tonyafehr** [comment]
@d47447, thanks for noting this issue.  

@saraschi2, I've assigned this to you in case there is anything to note, if not, we can close this comment.

**Comment by saraschi2** [comment]
I'm no longer on the Dynamics team, you'll have to find the new PM.




-------- Original message --------

**Comment by ShylaThompson** [comment]
@ShivamPandey-msft can you review this issue and update the topic if necessary?
