### ISSUE TITLE
Self-service export dontime

### ISSUE THREAD

**Issue by emstn** [MicrosoftDocs/dynamics-365-unified-operations-public#835]
When I use the self service export there is a checkbox that says: "By clicking Submit, I agree Export Database will make this environment temporarily unavailable"
But in the documentation it says "The environment will be unavailable for other servicing operations such as Sandbox Refresh or Package Deployment during this time. The source environment will be usable from a Dynamics user perspective." These seem contradicting to me. Is LCS just displaying a generic message?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3436fbc8-5bdd-dcdc-f5d3-51caf7b6cd76
* Version Independent ID: af78d3ef-b329-11e9-896a-aa3394f6c77c
* Content: [Copy Finance and Operations databases from Azure SQL Database to SQL Server environments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/copy-database-from-azure-sql-to-sql-server)
* Content Source: [articles/dev-itpro/database/copy-database-from-azure-sql-to-sql-server.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/database/copy-database-from-azure-sql-to-sql-server.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by emstn** [comment]
Title should say downtime

**Comment by tonyafehr** [comment]
@emstn. thanks for pointing this out. 

@laneswenka, consider updating this topic based on this feedback.

**Comment by sericks007** [comment]
Closing, based on Lane's response.
