### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by mihavuk** [MicrosoftDocs/dynamics-365-unified-operations-public#836]
Fix "how how" in the first chapter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ba89df6-0742-de49-e122-4af40e1480a4
* Version Independent ID: 7d4bdd46-b807-3bb3-f39e-785b80311de7
* Content: [SysTest filtering using class and method attributes - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/perf-test/systest-filtering)
* Content Source: [articles/dev-itpro/perf-test/systest-filtering.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/perf-test/systest-filtering.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @jorisdg
* Microsoft Alias: **jorisde**

**Comment by tonyafehr** [comment]
@mihavuk, thanks for the feedback. This will be fixed.
