### ISSUE TITLE
Generate URL from D365 Sales

### ISSUE THREAD

**Issue by lukaskujawa** [MicrosoftDocs/dynamics-365-unified-operations-public#837]
I am going to create web service in the D365FO, which will be generated URL to drop into D365Fo forms from D365 Sales. D365 Sales will be called this web service, D365FO return URL. Will be it work?

**Comment by tonyafehr** [comment]
Thanks for posting this! In the meantime, to get product help you can contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
