### ISSUE TITLE
Update24 hyperlink redirects to Update23

### ISSUE THREAD

**Issue by fgork** [MicrosoftDocs/dynamics-365-unified-operations-public#843]
When users click  the hyperlink for Platform Update 24 under Platform releases, the page for Platform Update 23 opens instead. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 891d6997-ca3b-bde4-4ede-07ea577e6f9d
* Version Independent ID: f6afa30b-fb54-39a7-bd85-7ec8c081ac6e
* Content: [What's new or changed - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/whats-new-changed)
* Content Source: [articles/fin-and-ops/get-started/whats-new-changed.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/whats-new-changed.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by sericks007** [comment]
@fgork, thanks for making us aware of this!  I've fixed the issue, and an updated version of the page will be published soon.
