### ISSUE TITLE
Global class method numeralsToTxt 

### ISSUE THREAD

**Issue by d47447** [MicrosoftDocs/dynamics-365-unified-operations-public#844]
Label used in this method '@SYS26645' having value 'Forty' while it should be 'Fourty'. I agree the modern form is Forty but in that case a new label may require with old value. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0ff3167-4d2a-cd81-d37c-503ffca5cb3d
* Version Independent ID: 180d680f-01a4-8bc2-a0db-a265c20e190d
* Content: [G classes - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-ref/g-classes)
* Content Source: [articles/dev-itpro/dev-ref/g-classes.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-ref/g-classes.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RobinARH
* Microsoft Alias: **robinr**

**Comment by ShylaThompson** [comment]
@d47447 thanks for commenting. Are you suggesting a change to this topic?

**Comment by d47447** [comment]
@ShylaThompson Well, i think yes. as still most of the banks use 'Fourty' on cheque prints than 'Forty'. Either give another label with 'Fourty' or just add a few lines in the document about the same.

**Comment by d47447** [comment]
Hey, 
Well, its more like generic feedback for labels. This particular label donest exist in this document.
