### ISSUE TITLE
Option to switch to automatic updates missing

### ISSUE THREAD

**Issue by dwijc** [MicrosoftDocs/dynamics-365-unified-operations-public#845]
I'm on PU23, but it doesnt give any option to switch to automatic updates.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e110aad1-fa4e-5fa0-ab1f-daae28097266
* Version Independent ID: c7aecc90-8e7c-ab0d-2cfe-94e9d09da1b0
* Content: [Automated Entity store refresh - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/automated-entity-store-refresh)
* Content Source: [articles/dev-itpro/analytics/automated-entity-store-refresh.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/automated-entity-store-refresh.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by MilindaV2** [comment]
Hi - you should see a message in asking you to switch. This should happen after you have visited the Entity store form. Can you provide the steps you followed?

**Comment by dwijc** [comment]
**Environment version information**
_Application release
Microsoft Dynamics 365 for Finance and Operations (8.1)
Platform release
Update23 (7.0.5126.35371)_

Its a one box demo environment. 

System Administration > Setup > Entity Store.

**Comment by renaudpaquaynsi** [comment]
I also have the same issue on an acceptance environment. I can't find any issue on LCS

**Comment by mhammons** [comment]
Hello, ditto, I was not prompted and the option is not available.

Installed product version : Microsoft Dynamics 365 for Finance and Operations (10)
Installed platform version : Update24 (7.0.5179.35390)

**Comment by stefanfranken** [comment]
Hi, same experience also with  Version 10 Update25 (7.0.5222.35401)

**Comment by sericks007** [comment]
Closing this issue, as it was logged over a year ago.  If this issue still persists, please log a new issue, or re-activate this one. Thank you!
