### ISSUE TITLE
Add some Links

### ISSUE THREAD

**Issue by cmw2** [MicrosoftDocs/dynamics-365-unified-operations-public#846]
This article could be improved by adding relevant links to other areas of documentation where details about the mentioned components could be found.  For example, the Publishing section makes mention of a publishing API.  A link to reference material for that API would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ef35f74-ef0d-6651-0def-14a92a23155b
* Version Independent ID: 05d40149-38e2-b7d7-6726-977e59914a03
* Content: [e-Commerce platform - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/dev-itpro/ecommerce-platform)
* Content Source: [articles/retail/dev-itpro/ecommerce-platform.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/dev-itpro/ecommerce-platform.md)
* Service: **dynamics-365-retail**
* GitHub Login: @kfend
* Microsoft Alias: **meeram**

**Comment by sericks007** [comment]
@mugunthanm, could you please update this article as suggested.

**Comment by sericks007** [comment]
Bug 289988 has been logged to track this issue.

**Comment by mugunthanm** [comment]
Updated the article with relevant links to the sub topics.
