### ISSUE TITLE
How To Links Needed

### ISSUE THREAD

**Issue by cmw2** [MicrosoftDocs/dynamics-365-unified-operations-public#847]
This page would benefit from linking from this bulleted high level list of "what" needs to be done, to a set of lower level instructions to explain "how" to do these things.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9afcb5f6-8b55-f088-5cf6-c2b8e2365701
* Version Independent ID: 7936e07d-fdb9-a548-04b1-d0e18272882a
* Content: [Set up online stores - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/online-stores)
* Content Source: [articles/retail/online-stores.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/online-stores.md)
* Service: **dynamics-365-retail**
* GitHub Login: @kfend
* Microsoft Alias: **meeram**

**Comment by sericks007** [comment]
@jblucher, could you please update this article as suggested.

**Comment by sericks007** [comment]
Bug 289989 has been logged to track this issue.
