### ISSUE TITLE
"Retail channel components" Binary update from LCS ?

### ISSUE THREAD

**Issue by Junaidahm3d** [MicrosoftDocs/dynamics-365-unified-operations-public#849]
Microsoft team,

I have configured & deployed D365FO onprem, now I need to download "Retail channel components" from binary updates but unable to find the "Binary updates" tile in environment page. showing only one tile "Updates".

Application release is 8.1 (8.1.195.20006)
Platform release is Update 22 (7.0.5095.41329)

please update document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecc51933-08be-36c7-8f82-d9df6f220bfa
* Version Independent ID: 29846b09-d0e5-9076-d451-0f86429a778a
* Content: [Installation steps for Retail channel components in an on-premises environment - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/deployment/deploy-retail-onprem)
* Content Source: [articles/dev-itpro/deployment/deploy-retail-onprem.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/deployment/deploy-retail-onprem.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @jashanno
* Microsoft Alias: **jashanno**

**Comment by jashanno** [comment]
Hello,

An update will be made.  LCS has just recently updated their site to make all updates located in the "Updates" tile instead of the previous flow where Application (X++) and Binary were separated.  Apologies for the confusion.

**Comment by Junaidahm3d** [comment]
Thanks for the update jashanno, I have downloaded the self service packages from **LCS shared Asset Library**  ,  **software deployable package**, latest Generally Available Update , extracted the package inside and found retailselfservice folder , it contains all the setups. :)
