### ISSUE TITLE
5 hour lead time gone?

### ISSUE THREAD

**Issue by ThomasZak** [MicrosoftDocs/dynamics-365-unified-operations-public#850]
Am I correct in understanding that the new Move Databases -&gt; Refresh Database feature has eliminated the 5 hour lead time that was required in the previous Service Request process? Does it still have the requirement that the source environment cannot be doing any LCS operations, and that all previous operations must be signed off? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4ec2cf9-20fb-cf47-eb1e-a1f987e6ba44
* Version Independent ID: bd7c5fc6-39d2-857e-b8b1-1ee634bd63ec
* Content: [Database Movement operations - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/dbmovement-operations)
* Content Source: [articles/dev-itpro/database/dbmovement-operations.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/database/dbmovement-operations.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by sericks007** [comment]
Closing, per Lane's response.
