### ISSUE TITLE
Country/Region Localization

### ISSUE THREAD

**Issue by AdminLekong** [MicrosoftDocs/dynamics-365-unified-operations-public#854]
Why Indonesia is not on the list of Localization Features?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05359761-bd4b-2841-db9a-5bcc11359430
* Version Independent ID: 86a4d7d2-9ce9-b0dc-0300-67c3e1e5b74a
* Content: [Localization and regulatory features - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lcs-solutions/country-region)
* Content Source: [articles/dev-itpro/lcs-solutions/country-region.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/lcs-solutions/country-region.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @ShylaThompson
* Microsoft Alias: **shylaw**

**Comment by ShylaThompson** [comment]
@AdminLekong thanks for your question. Are there specific Indonesian localization features that you were expecting to see documented here? Please provide as much information as possible so I can follow up with the product team.

**Comment by ShylaThompson** [comment]
Closing due to lack of information from original poster.
