### ISSUE TITLE
Exchanges throwing an error "you cant include a return in a customer order or quotation. remote the return and try again"

### ISSUE THREAD

**Issue by ankurmota** [MicrosoftDocs/dynamics-365-unified-operations-public#855]
The Retail parameters have been configured as per the content above and job 1110 is complete. Now new items can be added in the return order cart but while applying delivery type, it throws the error "you cant include a return in a customer order or quotation. remote the return and try again"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10ad1bd7-be06-8fb4-2345-5c2ad3343a18
* Version Independent ID: f962877f-dbba-ab99-e378-c44c4cd39931
* Content: [Configure and process an exchange on a return order - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/orderexchanges)
* Content Source: [articles/retail/orderexchanges.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/orderexchanges.md)
* Service: **dynamics-365-retail**
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by ShylaThompson** [comment]
@ankurmota Thanks for contacting us. Unfortunately, we can't handle support requests for the product here. To contact support, consider one of the options described here:  [Support](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support).
