### ISSUE TITLE
The way described here to reply to RFQ does not work. 

### ISSUE THREAD

**Issue by Izmiyash** [MicrosoftDocs/dynamics-365-unified-operations-public#862]
you need to update this page according to the change made '18 Spring update. 
see the link below.
https://community.dynamics.com/365/financeandoperations/f/765/t/279503

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: def35637-917e-1640-7a1f-53173d1d172e
* Version Independent ID: 43bad46b-5f82-aca9-96ee-2b373e9c4285
* Content: [Enter and compare RFQ bids, and award contracts - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/procurement/tasks/enter-compare-rfq-bids-award-contracts#enter-a-reply-for-another-vendor)
* Content Source: [articles/supply-chain/procurement/tasks/enter-compare-rfq-bids-award-contracts.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/procurement/tasks/enter-compare-rfq-bids-award-contracts.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @mkirknel
* Microsoft Alias: **mkirknel**

**Comment by tonyafehr** [comment]
@Izmiyash, thanks for bring this to our attention.

@mkirknel, can you update this topic as noted. Thank you!

**Comment by ShylaThompson** [comment]
@mkirknel I logged bug # 291442 to track this issue.

**Comment by ShylaThompson** [comment]
@Izmiyash thanks again for logging this issue. We should have the topic updated within the next week.
