### ISSUE TITLE
Copy paste error. Version "8.1.1" mentioned 3 times, should be 8.1.2 and 8.1.3.

### ISSUE THREAD

**Issue by MichaelFruergaardPontoppidan** [MicrosoftDocs/dynamics-365-unified-operations-public#863]
Copy paste error

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcdefbcf-c3ad-9b1f-0988-452cea3e2108
* Version Independent ID: 7e002437-1ad9-ca29-7844-87e6709fe0fe
* Content: [Software lifecycle policy and cloud releases - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/versions-update-policy#dates-and-versions-for-finance-and-operations-application-and-platform-releases)
* Content Source: [articles/dev-itpro/migration-upgrade/versions-update-policy.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/migration-upgrade/versions-update-policy.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RyanCCarlson2
* Microsoft Alias: **rcarlson**

**Comment by tonyafehr** [comment]
@MichaelFruergaardPontoppidan, can you provide more information as to what needs to be corrected. Perhaps you would like to make update in the public repo to fix this issue.

**Comment by emstn** [comment]
I think the comment is referring to "Table 4: Application Updates". KB number might be incorrect too.

**Comment by tonyafehr** [comment]
The topic is being updated with correct information. It will be published later this week.
