### ISSUE TITLE
Code is wrong

### ISSUE THREAD

**Issue by TrudAX** [MicrosoftDocs/dynamics-365-unified-operations-public#864]
The code is wrong in the second example for the 8.1 version(and it is a current release). If you just copy and paste it into a new job and run it you will get "Unable to cast object..." exception.
So the code needs to be modified to reflect the actual 8.1 version 
Full example: 
class RunnableClass1
{        
    public static void main(Args _args)
    {        
        Dialog dialog = new Dialog("");
        DialogField dimensionEntryField;
        DimensionEntryControl dimensionEntryValues;
        dimensionEntryField = DimensionEntryControlBuild::addToDialog(dialog, classstr(LedgerDimensionEntryController));
        //next line generates an exception
        //Unable to cast object of type 'Dynamics.AX.Application.DimensionEntryControlBuild' to type 'Dynamics.AX.Application.DimensionEntryControl'.
        dimensionEntryValues = dimensionEntryField.control();
        dimensionEntryValues.parmNonActiveValueErrorTolerance(ErrorTolerance::Error);
        dimensionEntryValues.parmDisplayValues(true);
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14dccd26-8d37-9226-b21f-b77ff40bcce4
* Version Independent ID: 3b3dc395-e3ad-67f2-d5bc-2d4de4edcc4b
* Content: [Support for Dimension Entry controls on dialogs - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/financial/dimension-entry-control-dialog-support)
* Content Source: [articles/dev-itpro/financial/dimension-entry-control-dialog-support.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/financial/dimension-entry-control-dialog-support.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @ShylaThompson
* Microsoft Alias: **ghenriks**

**Comment by tonyafehr** [comment]
@TrudAX, We’ll work on updating the simplified example to be more complete and compatible with the current version.

To work correctly, a modeled dialog class deriving from RunBase or SysOperationAutomaticUIBuilder is needed. Add the code in the appropriate locations based on the methods typically overridden by those classes.  Specifically, place the final 3 lines of code in the post-super() of the “dialogPostRun()” or “postRun()”.

Examples can be found in “AssetTransferMassUIBuilder” and “JmgComposeScheduleLoan” core product classes, as well as “DimensionEntryControlUIDialogTest” in the test models.

**Comment by TrudAX** [comment]
Thanks, @tonyafehr. I have created a pull request #873  to correct the document based on your answer(the code should be separated into 2 blocks)

**Comment by tonyafehr** [comment]
@TrudAX, I'll get your updates published later today.
