### ISSUE TITLE
Old way to deploy BIMeasure must be keep running after enabling the pushing of Entity store data in Azure to have fresh data in embedded Pbix report 

### ISSUE THREAD

**Issue by franzbusatto** [MicrosoftDocs/dynamics-365-unified-operations-public#865]
After switching to Automated Entity store refresh and enabling the pushing of Entity store data in Azure Data Lake, data are refreshed correctly in Azure data blob by the new 2 batch jobs (BIMeasurementProcessorFull, BIMeasurementProcessorIncremental).
However embedded PBI reports (i.e. Sales and Profitability Analysis) still point to AxDW data (the relational Entity store database) and this is evident holding execution of old batch job for BI updates (BIMeasurementDeployManagementEntityBatchJob). 
So please make clear the point in documentation that when enabling the pushing of Entity store data in Azure, to allow users to continue use embedded Pbix report without rework, the “old way” to deploy BIMeasure must be keep running.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48cf34e5-5de2-319c-c709-f06ea8fe4164
* Version Independent ID: 1b04f148-d442-f72b-a3b9-3eb4ede9f719
* Content: [Make Entity store available as a Data Lake - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/entity-store-data-lake)
* Content Source: [articles/dev-itpro/data-entities/entity-store-data-lake.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/entity-store-data-lake.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by tonyafehr** [comment]
Bug #291718 has been logged to track this issue.
