### ISSUE TITLE
Step 1 in the instructions is not Step 1

### ISSUE THREAD

**Issue by ijensen808** [MicrosoftDocs/dynamics-365-unified-operations-public#868]
Step 1 of the instructions in this article has an attribute dependency on a contract class that is not yet created at that point in the instructions.  I believe a reordering of the steps makes sense here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be8eb23c-c09a-00c0-1dae-dc7e57484339
* Version Independent ID: 55b1e31c-b00b-c1f0-51b6-6528cc9ff602
* Content: [Business events developer documentation - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/business-events/business-events-dev-doc)
* Content Source: [articles/dev-itpro/business-events/business-events-dev-doc.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/business-events/business-events-dev-doc.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by tonyafehr** [comment]
@ijensen808, thanks for the feedback.

@Sunil-Garg, can you look into this and determine if the documentation needs to be updated.

**Comment by tonyafehr** [comment]
Bug #291719 has been logged to track this issue.

**Comment by Sunil-Garg** [comment]
Thanks Ian. Update has been submitted.
