### ISSUE TITLE
Yonatan

### ISSUE THREAD

**Issue by yonatan1987** [MicrosoftDocs/dynamics-365-unified-operations-public#870]
אין תרגום לעברית וזה חיסרון גדולה לא מאפשר לי להתשמש בתוכנה שלכם

---
#### פרטי מסמך

⚠ *אין לערוך מקטע זה. פעולה זו נדרשת עבור קישור לנושאים ב- docs.microsoft.com ← GitHub.*

* ID: eebb7e31-ba41-656b-7dc1-aa5c65ea3f40
* Version Independent ID: 104841d9-485c-3ef8-bd97-8a60d2ff4d22
* Content: [Microsoft FastTrack for Finance and Operations - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/he-il/dynamics365/unified-operations/fin-and-ops/get-started/fasttrack-dynamics-365-overview)
* Content Source: [articles/fin-and-ops/get-started/fasttrack-dynamics-365-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/fasttrack-dynamics-365-overview.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @MargoC
* Microsoft Alias: **margoc**

**Comment by sericks007** [comment]
@yonatan1987, thanks for posting this.  I've forwarded your comments to our Localization team. Please log your suggestion on our [Ideas site](https://experience.dynamics.com/ideas/), as well.

**Comment by sericks007** [comment]
@yonatan1987, I sent your comments for our Localization team, and they said that Prodware has published the Israeli localization for Dynamics 365 Finance and Operations in AppSource. Here is the [link](https://appsource.microsoft.com/en-us/product/dynamics-365-for-finance-and-operations/prodware-israel.pwilloc?tab=Overview).
