### ISSUE TITLE
Financial dimension lookup issue in data connector 

### ISSUE THREAD

**Issue by Tjsonata054** [MicrosoftDocs/dynamics-365-unified-operations-public#874]
We have added financial dimensions lookup in the data connector but the lookup does not show more than 999 records . Does any one have any idea of how to over come that ?

**Comment by sericks007** [comment]
@Tjsonata054, thanks for posting this.  Please see GitHub issue [#604](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/issues/604#), as I believe it will answer your question.

To get product help, you can contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
