### ISSUE TITLE
users other than sysadmin with organizational hierarchy cannot see the data in settle transactions form 

### ISSUE THREAD

**Issue by Tjsonata054** [MicrosoftDocs/dynamics-365-unified-operations-public#875]
We have users with certain roles cannot see the data in settle transactions form when a organization hierarchy is attached to role.

**Comment by sericks007** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support).
