### ISSUE TITLE
Unable to create "ADFSServerApplicationForRetail" CommandNotFoundException.

### ISSUE THREAD

**Issue by Junaidahm3d** [MicrosoftDocs/dynamics-365-unified-operations-public#878]
Need Help..!

I am stuck at point 6, where I need to create **"ADFSServerApplicationForRetail"**.

6) On the ADFS machine currently viewing, run this script in a new PowerShell window using the command **.\Create-ADFSServerApplicationForRetail -HostUrl 'ax.d365ffo.onprem.contoso.com',** where the HostUrl value can be found in Service Fabric. To find the HostUrl value, navigate to Service Fabric > Application fabric:/AXSF > Details > Aad_AADValidAudience.

--x--

PS C:\scripts> .\Create-ADFSServerApplicationForRetail -HostUrl 'https://ax.dynamics.dax365.com'
New-D365FOAdfsServerApplicationForRetail-HostUrl:$HostUrl : The term
'New-D365FOAdfsServerApplicationForRetail-HostUrl:$HostUrl' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.
At C:\scripts\Create-ADFSServerApplicationForRetail.ps1:51 char:30
+ ... plication = New-D365FOAdfsServerApplicationForRetail-HostUrl:$HostUrl ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : ObjectNotFound: (New-D365FOAdfsS...ostUrl:$HostUrl:String) [], ParentContainsErrorRecord
Exception
+ FullyQualifiedErrorId : CommandNotFoundException

-- x --

Environment Details:
Environment version information
Application release 8.1 (8.1.195.20006)
Platform release Update22 (7.0.5095.41329)
 
I have also tried to run the command on another environment and other than ADFS machine but face the same issue. 
Regards,

Junaid Ahmed

**Comment by ahmerkhalid636** [comment]
Hi,

I am having the same issue on same version, where "New-D365FOAdfsServerApplicationForRetail" is not recognized as the name of a cmdlet, function, script file, or operable program.

**Comment by OsamaOmer1990** [comment]
Hello Experts,

I am struggling with the same issue, does anyone has any idea about this error?

**Comment by ahmerkhalid636** [comment]
The issue is in "Create-ADFSServerApplicationForRetail.ps1" line 51 where 'New-D365FOAdfsServerApplicationForRetail-HostUrl:$HostUrl' is incorrect.  ApplicationForRetail(just 1 space)-HostUrl. 

Now the issue resolve

Thanks 
Ahmer Khalid

**Comment by sericks007** [comment]
Can you please let me know which article you are viewing?

**Comment by Junaidahm3d** [comment]
https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/deployment/deploy-retail-onprem
