### ISSUE TITLE
Azure timeout while refreshing entity store

### ISSUE THREAD

**Issue by ha365** [MicrosoftDocs/dynamics-365-unified-operations-public#884]
When we refresh the entity store in d365 f&o the batch job ends after 10 minutes due to timeout error on azure sql. How can we increase the timeout?

**Comment by ShylaThompson** [comment]
@ha365  Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support).
