### ISSUE TITLE
Azure timeout while refreshing entity store 

### ISSUE THREAD

**Issue by ha365** [MicrosoftDocs/dynamics-365-unified-operations-public#885]
When we refresh the entity store in d365 f&o the batch job ends after 10 minutes due to timeout error on azure sql. How can we increase the timeout?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd3a076-d364-f4e8-fe37-f10c77a75466
* Version Independent ID: 0f767e21-3f33-2139-0931-7cd044c81b9f
* Content: [Power BI integration with Entity store - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/power-bi-integration-entity-store)
* Content Source: [articles/dev-itpro/analytics/power-bi-integration-entity-store.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/power-bi-integration-entity-store.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by ShylaThompson** [comment]
@ha365  Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support).
