### ISSUE TITLE
Enabling change tracking in FO database

### ISSUE THREAD

**Issue by Asgardi** [MicrosoftDocs/dynamics-365-unified-operations-public#886]
"For the change tracking functionality to work, you must enable the Change tracking option in the Finance and Operations database."

- How?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cd981b1-0ed1-34c8-d22a-e1c6d194ff9c
* Version Independent ID: 1e26cccc-eab2-e170-7004-98585128e3e1
* Content: [Bring your own database (BYOD) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/export-entities-to-your-own-database?toc=/fin-and-ops/toc.json)
* Content Source: [articles/dev-itpro/analytics/export-entities-to-your-own-database.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/export-entities-to-your-own-database.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by tonyafehr** [comment]
@Asgardi, thanks for the feedback. 

@Sunil-Garg, bug 292643 has been logged to track this issue.

**Comment by tonyafehr** [comment]
@Asgardi, updates have made to this topic based on your feedback. These changes should be live tomorrow.
