### ISSUE TITLE
Client-bank inerface

### ISSUE THREAD

**Issue by vavd** [MicrosoftDocs/dynamics-365-unified-operations-public#892]
The topic in the link below provides information that the client-bank interface must be available in 8.1.3 release:
https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/whats-new-changed-8-1-3#client-bank-interface-and-reconciliation-procedure

Where can I find documentation how to set it up?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 679412ac-7258-2a30-df2c-8b27be9bd834
* Version Independent ID: c6bb3d79-f14f-0bed-9c0b-03a4433aee44
* Content: [Set up and process payment orders for Russia - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/localizations/rus-payment-order-settings-processing)
* Content Source: [articles/financials/localizations/rus-payment-order-settings-processing.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/localizations/rus-payment-order-settings-processing.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @ShylaThompson
* Microsoft Alias: **shylaw**

**Comment by ShylaThompson** [comment]
@vavd We're in the process of publishing Cash flow management documentation for Russia. I'll update this issue when the content is available.

**Comment by ShylaThompson** [comment]
@vavd please see [Cash flow management](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/localizations/rus-cash-flow).
