### ISSUE TITLE
The page is doubled in the left navigation pane 

### ISSUE THREAD

**Issue by vavd** [MicrosoftDocs/dynamics-365-unified-operations-public#893]
I can see this page under:
Sales books, purchase books, and invoice-factures journals
Create a purchase book

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bf139dc-e7cd-c025-6217-944a87ee3dfc
* Version Independent ID: 61f1f251-8be8-d4a6-9326-08fa56434898
* Content: [Sales books, purchase books, and invoice-factures journals for Russia - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/localizations/rus-sales-books-purchase-books)
* Content Source: [articles/financials/localizations/rus-sales-books-purchase-books.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/localizations/rus-sales-books-purchase-books.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @ShylaThompson
* Microsoft Alias: **shylaw**

**Comment by ShylaThompson** [comment]
@vavd Thanks for letting us know. This should be fixed by the end of the day.
