### ISSUE TITLE
Report template

### ISSUE THREAD

**Issue by vavd** [MicrosoftDocs/dynamics-365-unified-operations-public#894]
We have an option in AX 2012 Financial reports generator to specify a report template for printable version of the report.

Regarding D365FO, do we have to use Electronic reporting to prepare printable layout?

If so, do you have any default config files for RUS balance sheet, P&L, and other statutory RUS reports, which can be uploaded in the system? Or we have to set up RUS external financial reporting from the scratch?

In case of any configuration files are available, could you please provide a links where can be found a guide how to deploy them.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 017826e1-601b-1a04-2b4b-68ea29b73fb4
* Version Independent ID: e53c5899-2801-9028-233b-f58435f92fd7
* Content: [Financial reporting (Russia) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/localizations/rus-financial-reports)
* Content Source: [articles/financials/localizations/rus-financial-reports.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/localizations/rus-financial-reports.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @Anasyash
* Microsoft Alias: **anasyash**

**Comment by ShylaThompson** [comment]
@Anasyash Can you review this question and update the topic if necessary?

**Comment by Anasyash** [comment]
Hello.

Accounting reporting in Electronic format (xml) is planned for delivery as ER configuration, plan is published here: https://docs.microsoft.com/en-us/business-applications-release-notes/April19/dynamics365-finance-operations/russian-localization

Please create a support ticket for getting more details on examples of creating ER formats based on Excel templates for RU accounting reporting.

Best regards, Anastasia

**Comment by vavd** [comment]
Hello @Anasyash,

Thank you for your reply.

Regarding XML, it's clear, thanks. Looking forward to having this functionality in April 2019.

About Excel templates - don't you plan to publish a detailed guide in this documentation? I believe it would be beneficial for the community and the Dynamics ecosystem.

Thanks

**Comment by Anasyash** [comment]
Thank you. We'll consider your request for updating this documentation in regards to exporting to Excel template.

Best regards, Anastasia
