### ISSUE TITLE
axruntimeuser missing in LCS

### ISSUE THREAD

**Issue by 5fq** [MicrosoftDocs/dynamics-365-unified-operations-public#901]
LCS is not showing the axruntimeuser and its credentials any more. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4020aba-daa3-d086-ceff-a1af3cd008aa
* Version Independent ID: 28e93b50-84c8-d36a-85d4-95e0273ccb14
* Content: [Export copies of Finance and Operations databases to restore later - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/copy-operations-database)
* Content Source: [articles/dev-itpro/database/copy-operations-database.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/database/copy-operations-database.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @laneswenka
* Microsoft Alias: **LaneSwenka**

**Comment by ShylaThompson** [comment]
@5fq  Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support).

**Comment by ornjohan** [comment]
@ShylaThompson Im having same issue as above.
So we get provided a guide by Microsoft, which is now out of date, and its still not fixed after 2 months.
Where if not here should we say that the article is out of date?
axruntimeuser doesnt exist in LCS anymore, so the above SQL script needs to be updated to work, or this article is just unnecessary.

**Comment by kurthatlevik** [comment]
@shylaThompson and @laneswenka.  

In the script, the following lines are spesified:

CREATE USER axruntimeuser WITH PASSWORD = '<password from LCS>'
EXEC sp_addrolemember 'db_datareader', 'axruntimeuser'
EXEC sp_addrolemember 'db_datawriter', 'axruntimeuser'

The user axruntimeuser is no longer spesified in the LCS user list on environment, and therefore we cannot spesify any password for it as instructed.  Please validate and check the script in the docs, and update the article.
