### ISSUE TITLE
Changes made to Custom reports are not updated

### ISSUE THREAD

**Issue by manishmoothedath** [MicrosoftDocs/dynamics-365-unified-operations-public#904]
Changes made to Custom reports are not updated unless Reporting service is restarted in the sandboxes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4008b2e3-4d1a-e146-8bdb-f39280124e9f
* Version Independent ID: 22f8390d-bb4d-1755-515c-7e7ebf1ddaae
* Content: [Apply updates to cloud environments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/deployment/apply-deployable-package-system)
* Content Source: [articles/dev-itpro/deployment/apply-deployable-package-system.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/deployment/apply-deployable-package-system.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @manalidongre
* Microsoft Alias: **manado**

**Comment by tonyafehr** [comment]
@manishmoothedath, thanks for the feedback. 

@manalidongre, could you update this topic as suggested.

**Comment by tonyafehr** [comment]
Bug 293276 has been logged to track this issue.
