### ISSUE TITLE
This is great but....

### ISSUE THREAD

**Issue by joengelhart** [MicrosoftDocs/dynamics-365-unified-operations-public#910]
This is great but those of us who don't have this feature yet....How do we get back to the old instructions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4ec2cf9-20fb-cf47-eb1e-a1f987e6ba44
* Version Independent ID: bd7c5fc6-39d2-857e-b8b1-1ee634bd63ec
* Content: [Database movement operations home page - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/dbmovement-operations)
* Content Source: [articles/dev-itpro/database/dbmovement-operations.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/database/dbmovement-operations.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by sericks007** [comment]
@joengelhart, thanks for bringing this to our attention.

@laneswenka, can you please update the documentation to accommodate this request?

**Comment by laneswenka** [comment]
@joengelhart these features are all generally available.  They only work on your Standard Acceptance Test or Performance Acceptance Test environments.  There are still manual instructions available in the Tutorials for your DevTest / OneBox environments.  If you are missing Refresh, Import, Export, or Point-in-time Restore on your UAT environment please file a Support Ticket and cc lane.swenka@microsoft.com

@sericks007 FYI these features are all GA.
