### ISSUE TITLE
Missing information on Import DB on Build

### ISSUE THREAD

**Issue by DutchDynamics** [MicrosoftDocs/dynamics-365-unified-operations-public#912]
Hi,

Please add back the documentation about how to import an exported DB into a Build/Dev environment.
On these type of environments, the move database/import is not available and resorting the backpac is the only option.

Now the instructions are gone

Wouter

 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4ec2cf9-20fb-cf47-eb1e-a1f987e6ba44
* Version Independent ID: bd7c5fc6-39d2-857e-b8b1-1ee634bd63ec
* Content: [Database movement operations home page - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/dbmovement-operations)
* Content Source: [articles/dev-itpro/database/dbmovement-operations.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/database/dbmovement-operations.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by sericks007** [comment]
@DutchDynamics, thanks for bringing this to our attention!

@laneswenka, can you please update the documentation to accommodate this request?

**Comment by laneswenka** [comment]
@DutchDynamics this sounds exactly like the Debugging & Diagnostics scenario, did you see this Tutorial?
https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/dbmovement-scenario-debugdiag

@sericks007 FYI this information is still available, just in a new format.

**Comment by DutchDynamics** [comment]
Hi, sorry I missed that part ;-) Thanks
