### ISSUE TITLE
Manual import steps missing

### ISSUE THREAD

**Issue by JoPe72** [MicrosoftDocs/dynamics-365-unified-operations-public#919]
Previously there was instructions on how to manually import the bacpac file to a Tier-1 DEV machine. Since you re not able to use LCS to import to Cloud Hosted environments I think these instructions should still be there in its own section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 142d4b7f-e485-b424-39a0-c059b81481a8
* Version Independent ID: 5a4c7cd0-f446-0c79-cc1a-2b69ba46b579
* Content: [Import a database - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/import-database)
* Content Source: [articles/dev-itpro/database/import-database.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/database/import-database.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @laneswenka
* Microsoft Alias: **laneswenka**

**Comment by marihul** [comment]
Hi, 

you can find the instructions under Tutorials --> Debugging an diagnostics:
https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/dbmovement-scenario-debugdiag

**Comment by JoPe72** [comment]
Ahh... Thanks
