### ISSUE TITLE
Ambiguous Application References

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics-365-unified-operations-public#922]
It is not clear whether tokens like "Depreciation conventions" or "fixed asset group book" have any analog in the actual UI. In other words, is "Depreciation convention" a drop-down selection in the application? If so, where? It would be very helpful if tokens which were references to actual UI fields or tables or pages were clearly identified as such by some typographical convention or even an image reference. Otherwise the user is left to wander all around the application looking for concrete artifacts that may or may not exist. This would not require a lot of overhead and would save a considerable amount of user/developer time in tracking down ambiguous references.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ba8763c-e5fc-440f-b5bb-5f71ecb69902
* Version Independent ID: d2ad87a3-ba47-8ff6-1c19-ea4371c4543c
* Content: [Fixed asset depreciation conventions - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/fixed-assets/fixed-asset-depreciation-conventions)
* Content Source: [articles/financials/fixed-assets/Fixed-asset-depreciation-conventions.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/fixed-assets/Fixed-asset-depreciation-conventions.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @saraschi2
* Microsoft Alias: **saraschi**

**Comment by tonyafehr** [comment]
@buzzwick, thanks for the feedback. 

@ShivamPandey-msft, please review this feedback and consider making updates to this topic to help provide further clarity.

**Comment by buzzwick** [comment]
Hi,
Just putting in my two cents:  the feedback suggests conventions that ought to be considered for the documentation _generally_. It would be a shame if any remedy were limited to this topic only.
Thanks for listening.

**Comment by sericks007** [comment]
Bug 293922 has been logged to track this issue.

**Comment by ShivamPandey-msft** [comment]
@Annette Bruer<mailto:Annette.Bruer@microsoft.com>
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sericks007** [comment]
This topic was updated and published.
