### ISSUE TITLE
Correction

### ISSUE THREAD

**Issue by mannesneuer** [MicrosoftDocs/dynamics-365-unified-operations-public#923]
Topic: Reprint a check for a worker before the payment journal is posted
3. Follow one of these steps:
If you can change the parameter to reuse checks, click Payment status, and then select Reuse to remove the check number from the bank journal.
If you can't change the parameter to reuse checks, click Payment status, and then select Reuse to remove the check number from the bank journal.

The last instruction is incorrect and needs to be corrected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c7dd397-2b16-282b-94ac-6c814ae62fee
* Version Independent ID: 4e115ec5-9dff-6e7a-50a2-55252c339249
* Content: [Process existing payroll payments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/hr/localizations/noam-usa-existing-payroll-payments)
* Content Source: [articles/fin-and-ops/hr/localizations/noam-usa-existing-payroll-payments.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/hr/localizations/noam-usa-existing-payroll-payments.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @rschloma
* Microsoft Alias: **brpotter**

**Comment by sericks007** [comment]
@mannesneuer, thanks for making us aware of this issue.

@brpotter, please update update the topic accordingly.
