### ISSUE TITLE
919	Extended log on info incorrect

### ISSUE THREAD

**Issue by mueckeflo** [MicrosoftDocs/dynamics-365-unified-operations-public#925]
Operation 919	"Extended log on" is also available in offline mode after the 1040 job has run.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd017c26-1971-fadf-9aa1-d9001e600ce9
* Version Independent ID: 0f0dd3b3-7bcb-306c-a66a-a96b614f21ae
* Content: [Online and offline point of sale (POS) operations - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/pos-operations)
* Content Source: [articles/retail/pos-operations.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/pos-operations.md)
* Service: **dynamics-365-retail**
* GitHub Login: @jblucher
* Microsoft Alias: **jeffbl**

**Comment by sericks007** [comment]
@mueckeflo, thanks for posting this info!

@jblucher, please update the topic, as appropriate.

**Comment by sericks007** [comment]
Bug 294405 has been logged to track this issue.

**Comment by sericks007** [comment]
This topic has been updated and will be published later today.
