### ISSUE TITLE
How is Entity Store Accessed in Production

### ISSUE THREAD

**Issue by mhammons** [MicrosoftDocs/dynamics-365-unified-operations-public#927]
"For troubleshooting and diagnostics, you can connect to the Entity store database directly from a related sandbox environment" - how does one connect to Entity Store when in a Production environment? Is it possible to do an import with Power BI instead of DirectQuery?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd3a076-d364-f4e8-fe37-f10c77a75466
* Version Independent ID: 0f767e21-3f33-2139-0931-7cd044c81b9f
* Content: [Power BI integration with Entity store - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/power-bi-integration-entity-store)
* Content Source: [articles/dev-itpro/analytics/power-bi-integration-entity-store.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/power-bi-integration-entity-store.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by tonyafehr** [comment]
@mhammons, Thanks for posting this! In the meantime, to get product help you can contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

@MilindaV2, please review this feedback and consider enhancing this topic.

**Comment by sericks007** [comment]
Bug 294407 has been logged to track this issue.

**Comment by sericks007** [comment]
According to @MilindaV2 the entity store can't be accessed directly in production. For more information, please see [Embedded Power BI in workspaces](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/embed-power-bi-workspaces)
