### ISSUE TITLE
This "set up" document doesn't actually instruct you how to set up

### ISSUE THREAD

**Issue by howalker3514** [MicrosoftDocs/dynamics-365-unified-operations-public#928]
This document should not be called "set up" because it does not provide instruction on how to actually set up anything.  It points you in the direction of where you need to go.  For example, it points you to the page on which customer pools are set up, but it does not tell you how to assign customers to a pool.  So this page isn't not nearly as helpful as it could be.  It's like the Cliff Notes of set up documentation.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5eea1eb7-385c-71e3-6257-4481e10f9d61
* Version Independent ID: 44be0618-36c2-f1d8-17be-d71d3944858d
* Content: [Set up Credit and collections - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/accounts-receivable/set-up-collections)
* Content Source: [articles/financials/accounts-receivable/set-up-collections.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/accounts-receivable/set-up-collections.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @ShivamPandey-msft
* Microsoft Alias: **shpandey**

**Comment by tonyafehr** [comment]
@howalker3514, Thanks for posting this! In the meantime, to get product help you can contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

@ShivamPandey-msft, please review this feedback and consider enhancing this topic.

**Comment by howalker3514** [comment]
I'm not going to contact Microsoft support about this.  That's not necessary.  This is just an example of Microsoft documentation "referring" to set up but ti doesn't actually tell you navigation steps to set up.  As a consultant who doesn't use this functionality often, we rely on through documentation to help the client.  This documentation is not adequate in that regard. 
Howard   
 
    On Friday, February 15, 2019, 3:19:44 PM MST, Tonya Fehr <notifications@github.com> wrote:  
 
 
@howalker3514, Thanks for posting this! In the meantime, to get product help you can contact Support using one of the options described here: Support contact options. In particular, you might want to go to the Dynamics 365 for Finance and Operations community page to get help with your questions from the Dynamics community.

@ShivamPandey-msft, please review this feedback and consider enhancing this topic.

**Comment by sericks007** [comment]
Bug 294408 has been logged to track this issue.

**Comment by johnnystruck** [comment]
@howalker3514 Hello Howard,

This may be useful to you: https://community.dynamics.com/cfs-file/__key/communityserver-discussions-components-files/765/CollectionPools.gif (Collection Pools)

Not exhaustive but I will agree that many official Microsoft D365 docs are lacking but likely due to the broad scope of each use case among different businesses and industries.

**Comment by josaw1** [comment]
BUG 437643 created.
