### ISSUE TITLE
Update financial reporting - do not run from PowerShell ISE

### ISSUE THREAD

**Issue by batetech** [MicrosoftDocs/dynamics-365-unified-operations-public#933]
The "Update financial reporting" step script will fail if run from PowerShell ISE because the ConfigureMRDatabase.ps1 script uses $Host.UI.RawUI.ReadKey which isn't supported in ISE.  When this happens, the script attempts to continue on and tries to treat it as an Azure SQL Database during the upgrade instead of local SQL Server by appending .database.windows.net to the server name, which causes upgrade errrors.

If using ISE, then you can use the "-NoPause" option to get around this, or run in the command window without ISE.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4de6e5a-2e8f-72a8-69b3-feb8f0de79ae
* Version Independent ID: c546c52e-cc11-bfdd-b27d-a2b4a0e31564
* Content: [Rename a local development (VHD) environment - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/vso-machine-renaming#update-the-azure-storage-emulator)
* Content Source: [articles/dev-itpro/migration-upgrade/vso-machine-renaming.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/migration-upgrade/vso-machine-renaming.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @MargoC
* Microsoft Alias: **tabell**

**Comment by tonyafehr** [comment]
@batetech, thanks for posting this! In the meantime, to get product help you can contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

**Comment by tonyafehr** [comment]
Bug 296517 has been logged to track this issue.

**Comment by RobinARH** [comment]
Thanks for the tip!
