### ISSUE TITLE
Update the Azure Storage Emulator clarification

### ISSUE THREAD

**Issue by batetech** [MicrosoftDocs/dynamics-365-unified-operations-public#934]
The "Update the Azure Storage Emulator" step should be updated to clarify that if the commands listed should not all be run in the order listed, and that the example commands are for troubleshooting only if the emulator will not start.  For example, if the "AzureStorageEmulator.exe status" command shows that it is running, or the "AzureStorageEmulator.exe start" command starts successfully, then you do not have to run the rest of the commands (including init).  

Also if you get an error "Port conflict with existing application" when trying to start the Azure Storage Emulator, then you might have to update the Azure Storage Emulator config file (AzureStorageEmulator.exe.config) to use ports 10010, 10011, 10012 instead, and then try to start the emulator again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4de6e5a-2e8f-72a8-69b3-feb8f0de79ae
* Version Independent ID: c546c52e-cc11-bfdd-b27d-a2b4a0e31564
* Content: [Rename a local development (VHD) environment - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/vso-machine-renaming#update-the-azure-storage-emulator)
* Content Source: [articles/dev-itpro/migration-upgrade/vso-machine-renaming.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/migration-upgrade/vso-machine-renaming.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @MargoC
* Microsoft Alias: **tabell**

**Comment by tonyafehr** [comment]
@batetech, thanks for posting this! In the meantime, to get product help you can contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

**Comment by tonyafehr** [comment]
Bug 296523 has been logged to track this issue.

**Comment by RobvanB** [comment]
I had to specifically give SQL permissions to the builtin\administrators group to Connect to SQL for some reason. There are 2 entries (SSMS -> Security -> Logins -> Builtin\administrators -> properties -> Securables -> Connect SQL) - I checked the one that wasn't checked, and that allowed the connector to connect to the DB
