### ISSUE TITLE
Loss of Documentation

### ISSUE THREAD

**Issue by ThomasZak** [MicrosoftDocs/dynamics-365-unified-operations-public#936]
As part of rollout of this feature, Microsoft has just erased the documentation on importing databases into Tier1 and Development environments. There were multiple steps to that process, including .bacpac imports and post-import SQL scripts for adjusting user accounts. Does MS no longer support copying databases to non-Tier2 servers?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 142d4b7f-e485-b424-39a0-c059b81481a8
* Version Independent ID: 5a4c7cd0-f446-0c79-cc1a-2b69ba46b579
* Content: [Import a database - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/import-database)
* Content Source: [articles/dev-itpro/database/import-database.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/database/import-database.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @laneswenka
* Microsoft Alias: **laneswenka**

**Comment by tonyafehr** [comment]
@ThomasZak, thanks for the feedback. 

@laneswenka, can you address this. Thank you!

**Comment by laneswenka** [comment]
Please see the Debugging and Diagnostics tutorial.

Lane

**Comment by laneswenka** [comment]
Pardon tried to reply via email.  Specifically I mean can you review this part of the new documentation?  It should have everything you need...
https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/dbmovement-scenario-debugdiag
