### ISSUE TITLE
Not applicable for D365FO

### ISSUE THREAD

**Issue by depakgupta** [MicrosoftDocs/dynamics-365-unified-operations-public#940]
Items like WMDP, web-pages etc. are not valid for D365FO but AX 2012. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c09b52d-b0f9-c026-2002-a2d1405fdde8
* Version Independent ID: d772efac-6970-4b62-3911-d5cd3f199f6d
* Content: [Warehouse mobile device display settings - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/warehousing/change-warehouse-mobile-device-displays)
* Content Source: [articles/supply-chain/warehousing/change-warehouse-mobile-device-displays.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/warehousing/change-warehouse-mobile-device-displays.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @perlynne
* Microsoft Alias: **perlynne**

**Comment by ShylaThompson** [comment]
@perlynne please review and update the topic if necessary.

**Comment by sericks007** [comment]
Bug 296961 has been logged to track this issue.

**Comment by ShylaThompson** [comment]
@depakgupta thanks for bringing this to our attention. We've added a note to the top of relevant topics to let users know that the feature has been deprecated.  Please note that it may take a few days before the changes to the topics go live.
