### ISSUE TITLE
Can we take backup of trial environment and restore to other trial/production environment? 

### ISSUE THREAD

**Issue by maheshambati410** [MicrosoftDocs/dynamics-365-unified-operations-public#944]
Can we take backup of trial environment after expires can it restore to new trial/production environment?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fff33773-d8bc-b57c-8bf2-a5f6dd2b1a80
* Version Independent ID: 454118d1-cd83-5707-0b3c-a7cecdb1e562
* Content: [Provision Talent - Talent | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/talent/provisioning-talent)
* Content Source: [articles/talent/provisioning-talent.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/talent/provisioning-talent.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @rschloma
* Microsoft Alias: **rschloma**

**Comment by sericks007** [comment]
@maheshambati410, thanks for posting this. In the meantime, to get product help you can contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community. 

@josaw1, please review and assign to the appropriate author.

**Comment by josaw1** [comment]
I've forwarded this to Par. Thanks.

**Comment by andreabichsel** [comment]
Hi @maheshambati410, I hope you got help with this question earlier through one of the above channels, but I'm adding the answer in case others want to know. At this time, it's not possible to back up and restore a trial environment. Thank you!
