### ISSUE TITLE
XDS not mentioned

### ISSUE THREAD

**Issue by AtisDimants** [MicrosoftDocs/dynamics-365-unified-operations-public#947]
I wonder where XDS comes in picture? Reading whitepapers about XDS (Extensible Data Security) one gets impression, that XDS is applied overall, but don't see it works for data entities. 

It isn't supposed to work, or am I doing something wrong? 

Please extend this chapter by adding info about XDS. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e4d5c85-124d-4001-9dc5-0837179c107e
* Version Independent ID: 5bebdc99-b637-75f1-4536-04c9f1fd55f7
* Content: [Security and data entities - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/security-data-entities?toc=/fin-and-ops/toc.json)
* Content Source: [articles/dev-itpro/data-entities/security-data-entities.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/security-data-entities.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by sericks007** [comment]
@AtisDimants, thank you for this feedback!

@Sunil-Garg, please review this feedback and update the topic, as appropriate.

**Comment by sericks007** [comment]
Bug 297033 has been logged to track this issue.

**Comment by tonyafehr** [comment]
@AtisDimants, we will be updating this topic to denote that "Data entities do not support the Extensible Data Security (XDS) concepts." I am closing this comment.
