### ISSUE TITLE
8.1.3 Platform Update 23 Installation Issue - Dynamics 365 for Finance & Operations On-Prem

### ISSUE THREAD

**Issue by Ruveles** [MicrosoftDocs/dynamics-365-unified-operations-public#948]
Hello, I just want to write here about the error during the installation of 8.1.3 Platform Update 23.

The Troubleshooting section says:  (https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/deployment/troubleshoot-on-prem#error-there-was-an-error-during-codepackage-activation-service-host-failed-to-activate-error0x8007052e) :
To resolve this issue, follow these steps:
1. Download the nuget package: https://www.nuget.org/api/v2/package/NETStandard.Library/2.0.0
2. Rename the file extension from .nupkg to .zip and extract.
3. Locate the "netstandard.dll" file that you extracted. This should be in the following location: \netstandard.library.2.0.0\build\netstandard2.0\ref\netstandard.dll
4. Create a folder called "Files" on the C: drive on all the AOS servers. Copy the "netstandard.dll" file to this folder on all the AOS servers.
5. On each AOS server, open an Admin Command Prompt, and run the following command.

"C:\Program Files (x86)\Microsoft SDKs\Windows\v8.1A\bin\NETFX 4.5.1 Tools\gacutil.exe" -i C:\Files\netstandard.dll /f

But, if you do as it is written here, then you will have an error with the registration DLL:
C:\Windows\system32>"C:\Program Files (x86)\Microsoft SDKs\Windows\v8.1A\bin\NETFX 4.5.1 Tools\gacutil.exe" -i C:\Files\netstandard.dll /f
Microsoft (R) .NET Global Assembly Cache Utility.  Version 4.0.30319.33440
Copyright (c) Microsoft Corporation.  All rights reserved.

Failure adding assembly to the cache:   An attempt was made to load a program with an incorrect format.

Denis's post in his blog helped me:
http://sinedax.blogspot.com/2019/02/813-platform-update-23-installation.html

To resolve this, you can find the properly DLL to the Agent path \\....WP\EnvName\StandaloneSetup-xxxxxxx\Apps\AOS\AXServiceApp\AXSF\Code\bin\

**Comment by sericks007** [comment]
@Ruveles, thank you for posting this!

@PeterRFriis or @EricMoos, please review this feedback and update the topic as appropriate.

**Comment by PeterRFriis** [comment]
@EricMoos have this been fixed, or is this still todo?

**Comment by tonyafehr** [comment]
Bug 298440 has been logged to track this issue.

**Comment by sericks007** [comment]
This topic has been updated and will be published later today.
