### ISSUE TITLE
Clarify Async vs. Batch

### ISSUE THREAD

**Issue by SST1982** [MicrosoftDocs/dynamics-365-unified-operations-public#950]
Thanks for adding some information on the run options. Yet, I think it would be helpful to have some comparison of the options "ansyncronous" and batch. In which scenario should I use async instead of batch?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a195670e-6d06-370a-1776-9be0c30ac8f8
* Version Independent ID: b4072fa9-25c8-8a11-16ec-ffa0ca10f9a5
* Content: [Data import and export jobs - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/data-import-export-job?toc=/fin-and-ops/toc.json)
* Content Source: [articles/dev-itpro/data-entities/data-import-export-job.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/data-import-export-job.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by sericks007** [comment]
@SST1982, thank you for the feedback!

@Sunil-Garg, please review and update the topic as appropriate.

**Comment by tonyafehr** [comment]
Bug 298441 has been logged to track this issue.

**Comment by tonyafehr** [comment]
@SST1982, we have updated this topic to clarify the differences between async and batch. These updates will be published tomorrow. I am closing this comment. Thanks!
