### ISSUE TITLE
Unknown datasource BillingAddress

### ISSUE THREAD

**Issue by artemt1** [MicrosoftDocs/dynamics-365-unified-operations-public#951]
Where could I find "BillingAddress" datasource on FMCustomerEntity data entity? Seems like this data source was removed, checked on 8.1 Update 20

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 897be989-9546-94dd-a260-6dcfcef08c53
* Version Independent ID: b4b73984-d8a8-edb4-2333-2ccde9b48488
* Content: [Computed columns and virtual fields in data entities - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/data-entity-computed-columns-virtual-fields)
* Content Source: [articles/dev-itpro/data-entities/data-entity-computed-columns-virtual-fields.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/data-entity-computed-columns-virtual-fields.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by sericks007** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

**Comment by artemt1** [comment]
That was not a Support request. The code example in this article seems outdated, it will not be compiled in the latest version of D365FO, because there is no "BillingAddress" datasource on FMCustomerEntity data entity.

**Comment by sericks007** [comment]
@artemt1, thank you for clarifying. I've reopened this issue.

@Sunil-Garg, please review and update the topic accordingly.

**Comment by ShylaThompson** [comment]
@Sunil-Garg I logged bug # 298201 for investigating this issue.

**Comment by sericks007** [comment]
This topic was updated.
