### ISSUE TITLE
Entity store data in Azure Data Lake flighting

### ISSUE THREAD

**Issue by valerymoskalenko** [MicrosoftDocs/dynamics-365-unified-operations-public#956]
What is the secret flight key to enable entity data store in Azure Data Lake?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48cf34e5-5de2-319c-c709-f06ea8fe4164
* Version Independent ID: 1b04f148-d442-f72b-a3b9-3eb4ede9f719
* Content: [Make Entity store available as a Data Lake - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/entity-store-data-lake)
* Content Source: [articles/dev-itpro/data-entities/entity-store-data-lake.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/entity-store-data-lake.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by tonyafehr** [comment]
@valerymoskalenko, thanks for posting this! In the meantime, to get product help you can contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

**Comment by tonyafehr** [comment]
Bug 298442 has been logged to track this issue.

**Comment by franzbusatto** [comment]
Enable flight for system parameters Data Connection with
INSERT INTO SYSFLIGHTING ( [FLIGHTNAME], [ENABLED], [FLIGHTSERVICEID] ) VALUES ('CDSAMaster', 1, 12719367) . For PROD environment need to open support issue not a service request.
