### ISSUE TITLE
Contradicting information

### ISSUE THREAD

**Issue by amadse** [MicrosoftDocs/dynamics-365-unified-operations-public#957]
With the new self service it states:
The refresh operation will begin immediately.
But it is still the old conditions for a database refresh  that is lists:
This is wrong:
Requests must be submitted 5 hours before the desired downtime window, to help ensure that resources will be available to complete the request.
There might be other lines that is wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15a09763-c088-80d0-b7c4-3eb7ff337017
* Version Independent ID: 42d1dcda-ca5d-3bb2-7e56-b080ee4a2dd4
* Content: [Refresh database - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/database-refresh)
* Content Source: [articles/dev-itpro/database/database-refresh.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/database/database-refresh.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @laneswenka
* Microsoft Alias: **laneswenka**

**Comment by tonyafehr** [comment]
@amadse, thanks for posting this! In the meantime, to get product help you can contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community. 

@laneswenka, please review this feedback and update this topic if needed.

**Comment by tonyafehr** [comment]
Bug 298444 has been logged to track this issue.

**Comment by laneswenka** [comment]
This has been resolved in the latest documentation updates.
