### ISSUE TITLE
Has this logic been added?

### ISSUE THREAD

**Issue by ConradVAva** [MicrosoftDocs/dynamics-365-unified-operations-public#958]
Above you write: "During the delay calculation, new logic will be added" - has this happend to date? From what version on is that available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08f6ecb2-3b60-ec64-f1ae-66fe973dfb14
* Version Independent ID: bf15ecc2-7f3c-eaff-f872-77c19d83130d
* Content: [Safety stock fulfillment for items - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/supply-chain/master-planning/safety-stock-replenishment)
* Content Source: [articles/supply-chain/master-planning/safety-stock-replenishment.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/master-planning/safety-stock-replenishment.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @roxanadiaconu
* Microsoft Alias: **roxanad**

**Comment by tonyafehr** [comment]
@ConradVAva, thanks for posting this! In the meantime, to get product help you can contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

@FrankDahl, please review this feedback and provide updates, if needed.

**Comment by sericks007** [comment]
Bug 298713 has been logged to track this issue.

**Comment by ChristianRytt** [comment]
Yes, this functionality is in the current version of F&O. The functionality was added with 8.0 for sure, might also be available with 7.3 - would require some investigation to find the exact version number.
