### ISSUE TITLE
pre-go-live Checklist link gives error

### ISSUE THREAD

**Issue by AvaSueGould** [MicrosoftDocs/dynamics-365-unified-operations-public#963]
Could someone let me know what the customer needs to do to access this link successfully?  I am the delivery manager from the Partner and I get the same error message.
https://mbs.microsoft.com/customersource/Global/365Enterprise/learning/documentation/installation-setup-guides/fasttrack-checklist-fin-and-ops

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50392961-60d5-ee55-613a-1128a25ef11a
* Version Independent ID: c163ee84-669b-137a-a610-9e88c91709ad
* Content: [Prepare for go-live - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/imp-lifecycle/prepare-go-live)
* Content Source: [articles/fin-and-ops/imp-lifecycle/prepare-go-live.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/imp-lifecycle/prepare-go-live.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @ClaudiaBetz-Haubold
* Microsoft Alias: **chaubold**

**Comment by AvaSueGould** [comment]
I forgot to paste in the actual text of the error message...
Sorry, something went wrong
An unexpected error has occurred.

Web Parts Maintenance Page: If you have permission, you can use this page to temporarily close Web Parts or remove personal settings. For more information, contact your site administrator.
TECHNICAL DETAILS



Troubleshoot issues with Microsoft SharePoint Foundation.
Correlation ID: d1ffc39e-b3ca-e028-d4eb-66b4506e65b0

Date and Time: 2/27/2019 7:16:58 AM

**Comment by sericks007** [comment]
@ClaudiaBetz-Haubold, is there something customers/partners need to do to access the link?

@AvaSueGould, the link opens a CustomerSource page that says this:

Microsoft Dynamics 365 for Finance and Operations customers should complete a Pre-Go-live review with the Microsoft FastTrack team before requesting their production environment. 

If you are not familiar with Microsoft FastTrack, see the [Microsoft FastTrack for Dynamics 365 overview](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/fasttrack-dynamics-365-overview) for more information. 

This checklist lists the tasks that the project team must complete before requesting a production environment.

The project manager or a key project member must complete this checklist during the Pre-Go-live phase of the project, generally 4–6 weeks before the proposed Go-live date, when user acceptance testing (UAT) is completed or almost completed. 

When you have completed this checklist:

If you have over 150 seats and are working with a Microsoft solutions architect assigned to your project, send it to them.

If you have 20-149 seats, send it to go-live@microsoft.com.

**Comment by ClaudiaBetz-Haubold** [comment]
Yes, there was an issue within Customer Source that prevented users from accessing it. This was resolved within the same day. Please try again.

Sorry for the inconvenience!

Kind regards,  Claudia

Outlook für Android<https://aka.ms/ghei36> herunterladen

________________________________
