### ISSUE TITLE
Prerequisite for purchase order year-end process

### ISSUE THREAD

**Issue by ravimeda** [MicrosoftDocs/dynamics-365-unified-operations-public#966]
There is no article for purchase order year-end process in ( https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/ ). Hence, customers refer to the document available at ( https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/process-purchase-orders-at-year-end ). However, this document does not describe a prerequisite. The missing prerequisite is the invoices for the purchase orders should be posted before the end of the fiscal year. If there is a invoice that is not in posted state, then the corresponding purchase order will not be accepted for the year-end process. The following error message will be thrown -

> The accounting date for the invoice must be in the same fiscal year as the related purchased order. Run the purchase order year-end process or change the date to the current fiscal year.

Hence, this issue has the following two tasks
- [ ] Provide a document for purchase order year-end process at ( https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/ )
- [ ] Ensure the prerequisite that invoices should be posted before the start of the new fiscal, is stated

**Comment by sericks007** [comment]
Bug 298720 has been logged to track this issue.
