### ISSUE TITLE
Service endpoint authentication on behalf of a user

### ISSUE THREAD

**Issue by bojanmisic** [MicrosoftDocs/dynamics-365-unified-operations-public#968]
How should we approach a scenario where we have a middleware (a web service) accessing D365 F&O sitting between a client (mobile) app and D365 F&O back-end? The mobile app on the client side needs to authenticate (and authorize) the user to D365, but talk only to the middleware layer (web service), and then the web service should invoke the call to D365 F&O on behalf of the user. As far as I see in the documentation - D365 F&O AAD authentication does not support "[On Behalf of](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-on-behalf-of-flow)" grant flow? Is there a way to impersonate a user in the middleware layer talking to D365 F&O backend which is authenticated to D365 via service-to-service authentication (client-credentials)? [Here](https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/webapi/impersonate-another-user-web-api) is how it can be handled for D365 Customer Engagement, is there something similar for Finance and Ops?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ba7bfc1-7c23-5662-8f2c-b41b19fb9070
* Version Independent ID: 19eb0a4a-1594-8f8b-054c-2c851df17e8b
* Content: [Service endpoints - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/services-home-page)
* Content Source: [articles/dev-itpro/data-entities/services-home-page.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/services-home-page.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by sericks007** [comment]
@bojanmisic, thanks for posting this! In the meantime, to get product help you can contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community. 

@Sunil-Garg, please review and update the documentation, as appropriate.

**Comment by jbpoulsen** [comment]
@bojanmisic Did you figure out a solution for this case? I'm currently exhausting the options for this to work, but since D365FO does not support OBO Grant flow, the possibilities are limited.
