### ISSUE TITLE
Process Data Packages - Step 12 - Incorrect Screenshot

### ISSUE THREAD

**Issue by JohnLBevan** [MicrosoftDocs/dynamics-365-unified-operations-public#972]
The screenshot associated with step 12 is incorrect:

Step 12: "To create a better sequence, select the Customers entity, and then update the value of the Execution unit field from 1 to 2. This change helps guarantee that customer groups are imported before the Customers entity is run."

... Yet the screenshot shows Customers with EU1, and Customer Groups with EU2; also Customer Groups has changed Sequence to 0.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8efea16-9cb3-e281-e8bd-373f0cf37735
* Version Independent ID: 9772f535-3b25-5818-733d-c094b79e3372
* Content: [Process and consume data packages in Finance and Operations solutions - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations//dev-itpro/lcs-solutions/process-data-packages-lcs-solutions#process-data-packages)
* Content Source: [articles/dev-itpro/lcs-solutions/process-data-packages-lcs-solutions.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/lcs-solutions/process-data-packages-lcs-solutions.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @kfend
* Microsoft Alias: **omarc**

**Comment by ShylaThompson** [comment]
Bug # 299938 assigned for investigation
