### ISSUE TITLE
user role and contact microsoft

### ISSUE THREAD

**Issue by renaudpaquaynsi** [MicrosoftDocs/dynamics-365-unified-operations-public#975]
You should explain (appeared with the febreary release of LCS) the user roles we can set on each users and the use of the toggle button to be contacted by Microsoft

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea6cec1a-8a9f-89e9-2ea0-c3016579a93c
* Version Independent ID: 063cd7e1-fb86-3fe6-6c59-74cdf69f7682
* Content: [Configure Lifecycle Services (LCS) security - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/configure-lcs-security)
* Content Source: [articles/dev-itpro/lifecycle-services/configure-lcs-security.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/lifecycle-services/configure-lcs-security.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RobinARH
* Microsoft Alias: **robadawy**

**Comment by ShylaThompson** [comment]
@robadawy I've logged bug #299937 for investigation.
