### ISSUE TITLE
Alert Notification Email Templates

### ISSUE THREAD

**Issue by tomhig** [MicrosoftDocs/dynamics-365-unified-operations-public#978]
There needs to be clarification that the Alert Email Templates that are illustrated at the end of the article cannot fully be created due to an impending Platform Update. Specifically, the "Deep Links" at the end of each template, where you can drill to the specific record that generated the alert, is not supported yet. Also, there is no Doc article that provides step-by-step instruction/guidance on how to actually create these templates, as you must use the proper HTML syntax.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b9b2766-4ec8-bc37-67a6-624308c4cacb
* Version Independent ID: b0f59676-4dc7-afc5-0b82-75f6614e1402
* Content: [Client alert notifications by email - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/alert-email-notifications)
* Content Source: [articles/fin-and-ops/get-started/alert-email-notifications.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/alert-email-notifications.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by ShylaThompson** [comment]
@tomhig this topic has a preview banner on it that identifies it as applying to a preview release. 

Functionality noted in this topic is available to targeted users as part of a preview release. The content and the functionality are subject to change. For more information about preview releases, see Standard and First release service updates.
