### ISSUE TITLE
Is Windows server 2019 supported OS for document routing agent?

### ISSUE THREAD

**Issue by maheshrajput2907** [MicrosoftDocs/dynamics-365-unified-operations-public#982]
Is Windows server 2019 supported OS for document routing agent?

**Comment by tonyafehr** [comment]
@maheshrajput2907, thank you for the feedback. It does not appear that you have a question about a help specific topic. I suggest that contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
