### ISSUE TITLE
Dyn365Fo inforamtion is missing

### ISSUE THREAD

**Issue by amadse** [MicrosoftDocs/dynamics-365-unified-operations-public#983]
Hi Dyn365 FO documentation links to the article that only contains AX 2012 in the information. The links on this page also only tells how to work with the is in AX 2012 and nothing about Dyn365FO. Beside that there is nothing about what it can be used for and how that related to the Asset library in LCS, where is still is shown in Dyn365FO projects and not as previews

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67056234-28d5-f6c2-6c40-9bd300021d35
* Version Independent ID: 378867ee-3d11-ad05-6739-c2d8d9462d77
* Content: [Configuration manager in Lifecycle Services (LCS) - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/configuration-manager-lcs)
* Content Source: [articles/dev-itpro/lifecycle-services/configuration-manager-lcs.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/lifecycle-services/configuration-manager-lcs.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RobinARH
* Microsoft Alias: **robadawy**

**Comment by tonyafehr** [comment]
@amadse, thank you for the feedback. In the meantime, to get product help you can contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

@robadawy , please review this feedback and provide updates, if needed.

**Comment by tonyafehr** [comment]
Bug 296523 has been logged to track this issue.

**Comment by maveloso** [comment]
Any update on this issue? its been 3 months and we still cant tell from the documentation if this LCS feature is usable in D365FO projects.
