### ISSUE TITLE
What is AOS?

### ISSUE THREAD

**Issue by gvrmohanreddy** [MicrosoftDocs/dynamics-365-unified-operations-public#985]
Diagram has AOS multiple places, and the document doesn't include what AOS acronym stands for. It would be great to have AOS explained in the document. 

Thanks,
Mohan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f426bc8-8659-3e4a-ce23-5d8356a97543
* Version Independent ID: 1d4e57b9-4975-01c8-4617-d518348180aa
* Content: [Retail components - Retail | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/retail-components#feedback)
* Content Source: [articles/retail/retail-components.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/retail-components.md)
* Service: **dynamics-365-retail**
* GitHub Login: @sericks007
* Microsoft Alias: **yabinl**

**Comment by tonyafehr** [comment]
Application Object Server (AOS) is a core component of your Dynamics 365 for Finance and Operations installation. An AOS instance enforces security, manages connections between clients and the database, and provides the foundation where the business logic runs. Here’s a topic that explains the [AOS architecture](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/aos-architecture).
