### ISSUE TITLE
Issue copy of the source database multiple times

### ISSUE THREAD

**Issue by antongeenens** [MicrosoftDocs/dynamics-365-unified-operations-public#990]
For the "create a copy of the source database" section, there is a script to automatically backup and restore the db. There is an issue with this. The backup script uses NOINIT which will append a backup if the file already exists. The restore script will restore the first backup in the file with the FILE = 1 parameter. So if you run this script for the second time and you didn't deleted the axdb_golden.bak file, you will restore an old backup.
It should be documented that you need to remove the file before starting the script or the script needs to be changed that the backup uses INIT instead of NOINIT so it is an overwrite instead of an append.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 277452eb-70c4-3d29-5219-1355a40bb714
* Version Independent ID: a9d425c4-c627-d20f-4098-307eceb2dd07
* Content: [Golden configuration promotion - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/dbmovement-scenario-goldenconfig#feedback)
* Content Source: [articles/dev-itpro/database/dbmovement-scenario-goldenconfig.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/database/dbmovement-scenario-goldenconfig.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @laneswenka
* Microsoft Alias: **laneswenka**

**Comment by sericks007** [comment]
@antongeenens, thanks for posting this feedback.

@laneswenka, please review and update the topic, as appropriate.

**Comment by laneswenka** [comment]
Thanks @antongeenens I will review and get this corrected

**Comment by sericks007** [comment]
Bug 300445 has been logged to track this issue.

**Comment by laneswenka** [comment]
@antongeenens this fix is in the next wave of commits
