### ISSUE TITLE
Free text invoice correction configuration key

### ISSUE THREAD

**Issue by johnnystruck** [MicrosoftDocs/dynamics-365-unified-operations-public#998]
It may be useful to include information regarding how to turn on this configuration key or provide some specificity. Had to find the correct information using AX2012 official documentation from 2014

At least link to the License Codes Configuration Keys Report -  https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/sysadmin/license-codes-configuration-keys-report

Or a direct path to turn on: System Administration &gt; Setup &gt; License configuration - Configuration keys &gt; General Ledger &gt; Free text invoice correction select check box.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 463f56a8-323e-18c1-f1d0-fe641b920a5e
* Version Independent ID: 11c68e7e-d46e-45b7-3d92-9cc86e688044
* Content: [Correct a free text invoice - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations//financials/accounts-receivable/correct-free-text-invoice#feedback)
* Content Source: [articles/financials/accounts-receivable/correct-free-text-invoice.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/accounts-receivable/correct-free-text-invoice.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @ShivamPandey-msft
* Microsoft Alias: **shpandey**

**Comment by sericks007** [comment]
Bug 300446 has been logged to track this issue.
